Add keyboard ajisai74
qmk/qmk_firmware pull request #10021
Opened 2020-08-12 17:38 UTC by Salicylic-acid3

Add ajisai74 keyboard.

A 74 keys ANSI/JIS Layout keyboard.
Salicylic-acid3

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-17 11:12 UTC, Salicylic-acid3 commented
Is there anything wrong with this pull request?

2020-08-18 23:57 UTC, zvecr requested changes

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/keymaps/salicylic/keymap.c
> +
```suggestion

```

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/keymaps/via/keymap.c
> +
```suggestion

```

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/keymaps/via/keymap.c
> +}
```suggestion
```

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/rules.mk
> +SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/keymaps/default/keymap.c
> +extern uint8_t is_master;
```suggestion
```

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/keymaps/default/keymap.c
> +}
```suggestion
``

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/keymaps/jis/keymap.c
> +
```suggestion

```

2020-08-18 23:57 UTC, zvecr commented on keyboards/ajisai74/rev1/rev1.h
> +#include "ajisai74.h"
```suggestion
```

2020-08-19 02:52 UTC, noroadsleft commented on keyboards/ajisai74/rules.mk
> +DEFAULT_FOLDER = ajisai74
```suggestion
```

2020-08-19 19:06 UTC, Salicylic-acid3 commented
The reason I need tap-dancing in jis and salicylic keymaps is that we want to prevent KC_ENT from being sent twice when the adjacent enter key is pressed at the same time.

2020-08-20 01:07 UTC, noroadsleft commented on keyboards/ajisai74/ajisai74.h
> + * |  L40  |  L41  |  L42  |  L43  |  L44  |   |  R40 | R41 |  R42 | R43 | R44 | R45 | R46 | R47 | R48 |
`R45` doesn't exist.

```suggestion
 * |  L40  |  L41  |  L42  |  L43  |  L44  |   |  R40 | R41 |  R42 | R43 | R44 |     | R46 | R47 | R48 |
```

2020-08-20 01:42 UTC, fauxpark approved these changes

2020-08-20 01:50 UTC, merged

2020-08-20 01:50 UTC, noroadsleft commented
Thanks!