[kbdfans] Added dbroqua layout for kbd6x
qmk/qmk_firmware pull request #10072
Opened 2020-08-17 18:02 UTC by Dbroqua

## Description
Add dbroqua layout for kbd6x with HHKB style and RGB.

## Types of Changes

   * [ ]  Core
   * [ ]  Bugfix
   * [ ]  New feature
   * [ ]  Enhancement/optimization
   * [ ]  Keyboard (addition or update)
   * [x]  Keymap/layout/userspace (addition or update)
   * [ ]  Documentation

## Issues Fixed or Closed by This PR

## Checklist

   * [x]  My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
   * [x]  I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
   * [ ]  My change requires a change to the documentation.
   * [ ]  I have updated the documentation accordingly.
   * [x]  I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
   * [ ]  I have added tests to cover my changes.

2020-08-18 23:39 UTC, zvecr requested changes

2020-08-18 23:39 UTC, zvecr commented on keyboards/kbdfans/kbd6x/keymaps/dbroqua/keymap.c
> +};
Deprecated per <https://docs.qmk.fm/#/feature_macros?id=deprecated-the-old-way-macro-amp-action_get_macro>, and also unused?
```suggestion
```

2020-08-18 23:39 UTC, zvecr commented on keyboards/kbdfans/kbd6x/keymaps/dbroqua/keymap.c
> +enum planck_layers {
```suggestion
enum layer_names {
```

2020-08-19 09:47 UTC, fauxpark approved these changes

2020-08-19 18:21 UTC, merged

2020-08-19 18:21 UTC, noroadsleft commented
Thanks!