Add Support for "45-ATS" Keyboard + VIA Keymap
qmk/qmk_firmware pull request #10104
Opened 2020-08-20 01:51 UTC by The-Royal

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-20 02:22 UTC, The-Royal commented
There we go. Somehow I really confused myself.

2020-08-28 19:34 UTC, drashna commented on keyboards/45_ats/45_ats.c
> +#include "45_ats.h"
I'd say your name, since you're the one writing the firmware for it.  

Though both would be fine, too.

2020-08-28 19:34 UTC, drashna commented on keyboards/45_ats/keymaps/default/config.h
> +#define TAPPING_TERM 175
```suggestion
#pragma once

#define TAPPING_TERM 175
```

2020-08-28 19:40 UTC, drashna commented on keyboards/45_ats/keymaps/default/keymap.c
> +}
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
    writePin(D0, (get_highest_layer(state) == 0));
    writePin(D1, (get_highest_layer(state) == 1));
    writePin(D2, (get_highest_layer(state) == 2));
    return state;
}
```

Or, if you want them to light up regardless of the rest of the layers (eg each acts independant:

```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
    writePin(D0, layer_state_cmp(state, 0));
    writePin(D1, layer_state_cmp(state, 1));
    writePin(D2, layer_state_cmp(state, 2));
    return state;
}
```

2020-08-28 19:41 UTC, drashna commented on keyboards/45_ats/keymaps/via/keymap.c
> +}
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
    writePin(D0, (get_highest_layer(state) == 0));
    writePin(D1, (get_highest_layer(state) == 1));
    writePin(D2, (get_highest_layer(state) == 2));
    return state;
}
```

Or, if you want them to light up regardless of the rest of the layers (eg each acts independant:

```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
    writePin(D0, layer_state_cmp(state, 0));
    writePin(D1, layer_state_cmp(state, 1));
    writePin(D2, layer_state_cmp(state, 2));
    return state;
}
```

2020-10-14 02:46 UTC, fauxpark requested changes

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/info.json
> +        "key_count": 50,
```suggestion
```

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/info.json
> +        "key_count": 49,
```suggestion
```

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/info.json
> +        "key_count": 49,
```suggestion
```

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/readme.md
> +![45ats](https://i.imgur.com/Paqx5zG.png)
```suggestion
![45ats](https://i.imgur.com/Paqx5zGl.png)
```

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/rules.mk
> +BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = full     # Virtual DIP switch configuration
```

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
```

2020-10-14 02:46 UTC, fauxpark commented on keyboards/45_ats/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
```

2020-10-14 04:44 UTC, fauxpark approved these changes

2020-10-15 20:50 UTC, noroadsleft requested changes

2020-10-15 20:50 UTC, noroadsleft commented on keyboards/45_ats/config.h
> +#define VENDOR_ID       0xFEED
You have a `via` keymap present, but VIA actively discourages use of `0xFEED` as a Vendor ID.

Simple suggestion:

```suggestion
#define VENDOR_ID       0xAB13
```

2020-10-17 05:15 UTC, noroadsleft approved these changes

2020-10-17 05:19 UTC, merged

2020-10-17 05:20 UTC, noroadsleft commented
Thanks!