update info.json file for keyboard
qmk/qmk_firmware pull request #10117
Opened 2020-08-21 08:24 UTC by greenjack-z

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-24 06:32 UTC, greenjack-z commented
this layout is in line with a physical rows at PCB, it was got from keyboard firmware builder generated files. That firmware works well, but after compiling under QMK Configurator - there are displacements/ You are right.
So which way is right?

2020-08-24 19:06 UTC, noroadsleft commented
> this layout is in line with a physical rows at PCB, it was got from keyboard firmware builder generated files. That firmware works well, but after compiling under QMK Configurator - there are displacements/ You are right.
> So which way is right?

The idea of the layout macro ([this block of code](https://github.com/qmk/qmk_firmware/blob/ff91b86bcb16240b062bef6145f23519dde00d15/keyboards/handwired/zergo/zergo.h#L21-L35)) is that the bottom section represents how your switches are connected, and the top represents where they are geographically. If the 5 key is between 4 and 6 on the assembled keyboard, its switch identifier should be between those for 4 and 6 in the top section, regardless of what's going on electrically.

The [Clueboard 66 rev4](https://github.com/qmk/qmk_firmware/blob/5772ac8bf68f5e8e003b4a047494ac3fa2065524/keyboards/clueboard/66/rev4/rev4.h#L53-L70) has a good example of this. The 8, I, K and M keys are actually electrically in the same column of the switch matrix as the Esc, Tab, Caps Lock, Left Shift, and Left Ctrl keys.

2020-08-25 05:50 UTC, greenjack-z commented
great example! thanks. I will fix it now.

2020-08-25 09:23 UTC, noroadsleft commented
@greenjack-z You should flash your board from this branch and make sure the keys are assigned correctly.

If I'm right, your key assignments will be out of place, similarly to how the assignments looked in QMK Configurator.

2020-08-25 09:24 UTC, greenjack-z commented
> You should flash your board from this branch
what is the best way to do that?

2020-08-25 09:46 UTC, noroadsleft commented
I just realized you're probably using GitHub's web interface to make these changes. You would actually need a development environment set up to do it properly. You should look into [setting up a development environment](https://docs.qmk.fm/#/newbs_getting_started), but for now, don't worry about it. I checked and the keymap does need to be updated.

2020-08-25 10:23 UTC, greenjack-z commented
> I just realized you're probably using GitHub's web interface to make these changes.
Sorry, but yes. It's not easy to set up environment and I do that in parallel, however the main issue is to be able to use the QMK Configurator without mistakes.

2020-08-26 02:55 UTC, fauxpark requested changes

2020-08-26 02:55 UTC, fauxpark commented on keyboards/handwired/zergo/info.json
> +            "key_count": 80,
```suggestion
```

2020-08-26 06:04 UTC, greenjack-z commented
looks like not all the docs are up to date? cause some requirements are deprecated

2020-08-26 06:47 UTC, fauxpark approved these changes

2020-08-26 10:03 UTC, noroadsleft commented on keyboards/handwired/zergo/keymaps/default/keymap.c
> +		MT(MOD_LCTL, KC_END), KC_DOWN, KC_RGHT, KC_LALT, KC_SPC, KC_ENT, KC_SPC, KC_RALT, KC_LGUI, KC_MENU, MT(MOD_RCTL, KC_PGDN),
Missing an end parenthesis here.

```suggestion
		MT(MOD_LCTL, KC_END), KC_DOWN, KC_RGHT, KC_LALT, KC_SPC, KC_ENT, KC_SPC, KC_RALT, KC_LGUI, KC_MENU, MT(MOD_RCTL, KC_PGDN)),
```

2020-08-26 19:36 UTC, merged

2020-08-26 19:36 UTC, noroadsleft commented
Thanks!