Maja soldered
qmk/qmk_firmware pull request #10152
Opened 2020-08-24 07:07 UTC by moyi4681

add maja_soldered keyboard

2020-08-29 01:02 UTC, drashna commented on keyboards/kbdfans/maja_soldered/config.h
> +#define DESCRIPTION     MAJA SOLDERED keyboard
```suggestion
```

2020-08-29 01:03 UTC, drashna commented on keyboards/kbdfans/maja_soldered/keymaps/via/keymap.c
> +const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
All 4 layers need to be populated for the via keymap, unless the number of layers has been decreased.

2020-08-29 12:19 UTC, fauxpark requested changes

2020-08-29 12:19 UTC, fauxpark commented on keyboards/kbdfans/maja_soldered/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-08-29 12:19 UTC, fauxpark commented on keyboards/kbdfans/maja_soldered/rules.mk
> +NO_USB_STARTUP_CHECK = no   # Disable initialization only when usb is plugged in
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
NO_USB_STARTUP_CHECK = no   # Disable initialization only when usb is plugged in
```

2020-09-05 21:53 UTC, drashna approved these changes

2020-09-05 22:58 UTC, fauxpark approved these changes

2020-09-07 00:54 UTC, drashna commented
Thanks!

2020-09-07 00:55 UTC, merged