Drakon updates 2
qmk/qmk_firmware pull request #10155
Opened 2020-08-24 13:37 UTC by JagdPietr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-24 13:39 UTC, JagdPietr commented
Updates in this PR:
1. Transfer of drakon to jagdpietr dir
2. Fix of encoder switch placement and orientation
3. Transfer of OLED stuff from keymap(s).c to keyboard.c for OLED functionality

2020-08-29 01:09 UTC, drashna commented on keyboards/jagdpietr/drakon/drakon.c
> +__attribute__ ((weak))
```suggestion
```

2020-08-29 01:10 UTC, drashna commented on keyboards/jagdpietr/drakon/drakon.c
> +oled_rotation_t oled_init_user(oled_rotation_t rotation) {
```suggestion
__attribute__((weak))
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
```

2020-08-29 01:10 UTC, drashna commented on keyboards/jagdpietr/drakon/drakon.c
> +void render_status(void) {
```suggestion
static void render_status(void) {
```

2020-08-29 01:10 UTC, drashna commented on keyboards/jagdpietr/drakon/drakon.c
> +void oled_task_user(void) {
```suggestion
__attribute__((weak))
void oled_task_user(void) {
```

2020-09-01 12:06 UTC, JagdPietr commented
> This branch needs to be rebased upon QMK's current `master` branch. As you've already added this board in #10071, what this PR would do when merged is add a duplicate under a new folder, instead of moving the existing files (modified or not) to the new folder.
> 
> To sort this properly, you should [resynchronize your master branch](https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch), then run the following commands:
> 
> ```shell
> # check out this branch:
> git checkout drakon-updates-2
> 
> # rewrite this branch to match the now-synchronized master:
> git reset --hard master
> 
> # create the jagdpietr directory, which won't exist at this point:
> mkdir -p keyboards/jagdpietr/
> 
> # move the keyboard source files:
> git mv -- keyboards/drakon/ keyboards/jagdpietr/drakon/
> 
> # remove the logo keymap, which I notice isn't present here:
> git rm -rf -- keyboards/jagdpietr/drakon/keymaps/logo/
> 
> # commit the changes:
> git commit -m "move Drakon to jagdpietr directory"
> 
> # update this pull request:
> git push --force-with-lease
> ```

noted and finished the instructions
thank you very much!

2020-09-02 18:15 UTC, noroadsleft commented
@JagdPietr Your resynchronization wasn't done properly; there should only be one commit on this PR.

2020-09-03 00:39 UTC, JagdPietr commented
I apologize for that; will redo this action

2020-09-07 03:27 UTC, JagdPietr commented
Finished with the instructions already, and I hope this is correct this time.
However, I'm quite worried because the changes on keyboard.c and keymap/s.c were not reflected on this latest commit when I viewed them.

2020-09-07 04:19 UTC, drashna commented
Yeah, the changes don't seem to be reflected, unfortunately. :(

2020-09-09 22:52 UTC, noroadsleft requested changes
Also, the changes to `lib/vusb/` need to be reverted:

From your `qmk_firmware` directory, run:

```shell
cd lib/vusb/
git checkout bdb53e4c043d089279d9891b68bea77614cb97ee
cd ../../
git add -- lib/vusb/
git commit -m "fix vusb submodule"
git push
```

2020-09-10 02:31 UTC, JagdPietr commented
Changes and recommendations finished - I just hope I got them all correct :)

2020-09-21 17:49 UTC, noroadsleft approved these changes

2020-10-15 00:37 UTC, JagdPietr commented
Hi! May I ask what should I do to finish this PR? It has taken a bit while now, and maybe I missed something to do to finish this PR.

2020-10-15 00:44 UTC, fauxpark approved these changes

2020-10-16 07:49 UTC, noroadsleft commented
I don't recall if it was asked, but are there any of these in the wild?

2020-10-16 21:50 UTC, JagdPietr commented
I have twp working prototypes in my care, and another in the proxy. The GB is still on production phase.

2020-10-17 09:08 UTC, noroadsleft commented
Ah, wanted to make sure we're not messing things up for end users if we move this now.

2020-10-17 09:11 UTC, merged

2020-10-17 09:11 UTC, noroadsleft commented
Thanks!

2020-10-17 10:44 UTC, JagdPietr commented
Thank you very much for all of you! Such a great team :)