Add Plume65
qmk/qmk_firmware pull request #10176
Opened 2020-08-26 16:12 UTC by Maartenwut

## Description

Adds the Plume65 keyboard by Plume Keyboards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-29 11:42 UTC, fauxpark requested changes

2020-08-29 11:42 UTC, fauxpark commented on keyboards/plume/plume65/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
```

2020-09-01 19:17 UTC, noroadsleft commented on keyboards/plume/plume65/readme.md
> +* Keyboard Maintainer: maartenwut
```suggestion
* Keyboard Maintainer: [maartenwut](https://github.com/maartenwut)
```

2020-09-01 19:18 UTC, noroadsleft commented on keyboards/plume/plume65/plume65.h
> +/* Copyright 2020 Dekkers
The Split Backspace layouts also need their layout data added to `info.json`.

2020-09-01 19:22 UTC, noroadsleft commented on keyboards/plume/plume65/config.h
> +
```suggestion
```

2020-09-05 22:52 UTC, fauxpark approved these changes

2020-09-06 07:32 UTC, noroadsleft approved these changes

2020-09-06 07:33 UTC, merged

2020-09-06 07:33 UTC, noroadsleft commented
Thanks!