Added the NoStab63 keymap to the keyboard folder
qmk/qmk_firmware pull request #10180
Opened 2020-08-27 09:46 UTC by santy81855

## Added a keyboard called NoStab63 to the handwired folder in the keyboard folder. It is fully functional and uses the proton c controller. I have already flashed the bin file to the microcontroller

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-29 02:07 UTC, drashna commented on keyboards/handwired/NoStab63/NoStab63.c
> +}
This isn't needed.

```suggestion
```

2020-08-29 02:08 UTC, drashna commented on keyboards/handwired/NoStab63/config.h
> +#define PRODUCT_ID      0x0000
```suggestion
#define PRODUCT_ID      0x1707
```

2020-08-29 02:08 UTC, drashna commented on keyboards/handwired/NoStab63/config.h
> +#define DESCRIPTION     An Ergonomic Stabless Keyboard
```suggestion
```

2020-08-29 02:09 UTC, drashna commented on keyboards/handwired/NoStab63/keymaps/default/keymap.c
> +};
```suggestion
enum layers {
    _DVORAK,
    _CAMILA,
    _NUMBER,
    _FN1,
    _ARROW,
    _LSHIFT,
    _RSHIFT,
    _GAMING,
};
```

2020-08-29 02:09 UTC, drashna commented on keyboards/handwired/NoStab63/keymaps/default/keymap.c
> +  SE_OE_LOW,
```suggestion
    SE_AA_HIGH,
    SE_AE_HIGH,
    SE_OE_HIGH,
    SE_AA_LOW,
    SE_AE_LOW,
    SE_OE_LOW,
```

2020-08-29 02:10 UTC, drashna commented on keyboards/handwired/NoStab63/rules.mk
> +NO_SUSPEND_POWER_DOWN = yes
```suggestion
```

2020-08-29 11:56 UTC, fauxpark requested changes

2020-08-29 11:56 UTC, fauxpark commented on keyboards/handwired/NoStab63/config.h
> +>>>>>>> 4291fa68390067549e51bb52195ec9cabf6153cb
```suggestion
#define VENDOR_ID       0xFEED
```

2020-08-29 11:56 UTC, fauxpark commented on keyboards/handwired/NoStab63/info.json
> +            "key_count": 63,
```suggestion
```

2020-08-29 11:56 UTC, fauxpark commented on keyboards/handwired/NoStab63/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2020-08-29 11:56 UTC, fauxpark commented on keyboards/handwired/NoStab63/rules.mk
> +#   comment out to disable the options.
```suggestion
#   change yes to no to disable
```

2020-09-01 23:32 UTC, noroadsleft commented on keyboards/handwired/NoStab63/nostab.h
> +	                                   K40, K41, K42										  \
Which matrix position is the encoder click? Seems like it should be `K1F` or `K1G`.

2020-11-07 00:54 UTC, noroadsleft commented
This can't be merged with all the other keyboards removed, but since you've deleted the source repository, this PR can't be updated. Closing.

2020-11-07 00:54 UTC, closed without merging