Update DZ60 Information
qmk/qmk_firmware pull request #10186
Opened 2020-08-27 20:23 UTC by mrsendyyk

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-28 19:21 UTC, mrsendyyk commented
Cc: @fauxpark @drashna @tzarc @noroadsleft :)

2020-08-29 02:30 UTC, drashna commented
@mrsendyyk just a heads up, you don't need to tag us in each of the PRs.  We will get to them sooner or later, as time and life permits. 

That said, I do like your enthusiasm. :)

2020-08-29 11:37 UTC, fauxpark requested changes
Looks good other than the changes to `keyboards/readme.md`, which I think we are probably going to remove altogether; it's way out of date and just too much of a hassle to maintain.

2020-08-29 11:37 UTC, fauxpark commented on keyboards/readme.md
> +* [DZ60 60% Mechanical Keyboard PCB](/keyboards/dz60) &mdash; A Customizable 60% Mechanical Keyboard PCB.
```suggestion
```

2020-08-29 11:37 UTC, fauxpark commented on keyboards/readme.md
> +* [KBD75](/keyboards/kbdfans/kbd75) &mdash; A 75% keyboard made by made by KBDFans.
```suggestion
* [KBD75](/keyboards/kbd75) &mdash; A 75% keyboard made by made by KBDFans.
```

2020-08-29 18:33 UTC, mrsendyyk commented on keyboards/readme.md
> +* [DZ60 60% Mechanical Keyboard PCB](/keyboards/dz60) &mdash; A Customizable 60% Mechanical Keyboard PCB.
Ok, done.

2020-08-29 18:34 UTC, mrsendyyk commented on keyboards/readme.md
> +* [KBD75](/keyboards/kbdfans/kbd75) &mdash; A 75% keyboard made by made by KBDFans.
Ok, done.

2020-08-29 19:22 UTC, mrsendyyk commented
Sorry @drashna, i accidentally dismissed your stale review.

2020-09-02 03:54 UTC, fauxpark approved these changes

2020-09-03 08:36 UTC, merged

2020-09-03 08:36 UTC, noroadsleft commented
Thanks!