Add Bakeneko 65
qmk/qmk_firmware pull request #10234
Opened 2020-09-04 14:59 UTC by kkatano

## Description

Add Bakeneko 65 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-06 22:12 UTC, drashna approved these changes

2020-09-06 22:29 UTC, fauxpark requested changes

2020-09-06 22:29 UTC, fauxpark commented on keyboards/bakeneko65/rules.mk
> +LAYOUTS = 65_ansi_split_bs 65_ansi 65_ansi_split_bs_2_right_mods 65_ansi_2_right_mods
```suggestion
LAYOUTS = 65_ansi
```

2020-09-07 01:04 UTC, fauxpark approved these changes

2020-09-07 04:03 UTC, merged