4pplet keyboards
qmk/qmk_firmware pull request #10251
Opened 2020-09-06 07:12 UTC by 4pplet

## Description

Adding masterwork classy_tkl keyboard. Information about group buy: https://geekhack.org/index.php?topic=108263.0

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-07 03:06 UTC, drashna requested changes

2020-09-07 03:06 UTC, drashna commented on keyboards/masterwork/classy_tkl/rev_a/rules.mk
> +HD44780_ENABLE = no         # Enable support for HD44780 based LCDs
```suggestion
```

2020-09-07 03:06 UTC, drashna commented on keyboards/masterwork/classy_tkl/rev_a/rules.mk
> +# OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
BOOTLOADER = atmel-dfu

```

2020-09-07 06:21 UTC, 4pplet commented
Thanks @drashna ! :)

2020-09-08 08:24 UTC, 4pplet commented
Fixed spelling error for masterwork to masterworks, sorry about that!

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/info.json
> +            "key_count": 89,
```suggestion
```

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/info.json
> +            "key_count": 84,
```suggestion
```

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/info.json
> +            "key_count": 85,
```suggestion
```

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a license header, here as well?

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/keymaps/default_tkl_ansi_wkl/keymap.c
> +#include QMK_KEYBOARD_H
And here?

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/keymaps/default_tkl_iso_wkl/keymap.c
> +#include QMK_KEYBOARD_H
And here?

2020-09-09 04:27 UTC, drashna commented on keyboards/masterworks/classy_tkl/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Also, here?

2020-09-11 09:23 UTC, noroadsleft requested changes

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/info.json
> +                },
QMK Configurator's UI code actually doesn't support `ks`, so we do this:

```suggestion
                { "label": "Enter", "x": 13.75, "y": 2.5, "w": 1.25, "h": 2 },
```

... and it renders like an ISO Enter.

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/readme.md
> +![Classy TKL](https://i.imgur.com/p1dxfYK.jpg)
Swaps this image for a smaller version.

```suggestion
![Classy TKL](https://i.imgur.com/p1dxfYKl.jpg)
```

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/readme.md
> +Hardware Availability: https://geekhack.org/index.php?topic=105933
```suggestion
* Keyboard Maintainer: [Mathias Andersson](https://github.com/wraul)
* Hardware Supported: [Classy TKL PCB](https://github.com/4pplet/classyTKL)
* Hardware Availability: https://geekhack.org/index.php?topic=105933
```

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/rev_a/config.h
> +#define DESCRIPTION A classy keyboard
`DESCRIPTION` isn't used anywhere in QMK anymore.

```suggestion
```

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/rev_a/rev_a.c
> +
```suggestion
```

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/rev_a/rev_a.h
> +    k30,      k31, k32, k33, k34, k35, k36, k37, k38, k39, k3A, k3B, k3C,                               \
Based on the ISO keymap you've provided, I think this needs to be:

```suggestion
    k20,      k21, k22, k23, k24, k25, k26, k27, k28, k29, k2A, k2B, k2C,                k2E, k2F, k2G, \
    k30,      k31, k32, k33, k34, k35, k36, k37, k38, k39, k3A, k3B, k3C,      k2D,                     \
```

QMK custom is that ISO Enter is to the end of the home row.

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/rev_a/rules.mk
> +MIDI_ENABLE = no            # MIDI support
```suggestion
```

2020-09-11 09:23 UTC, noroadsleft commented on keyboards/masterworks/classy_tkl/rev_a/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-12 01:23 UTC, noroadsleft commented
Still two comments unaddressed on my previous review.

2020-09-12 12:45 UTC, 4pplet commented
Thanks for the suggestions, good catch on the ISO-enter!

2020-09-13 09:10 UTC, noroadsleft approved these changes

2020-09-18 09:57 UTC, 4pplet commented
Any update on this? All seems done? @drashna :)

2020-09-19 02:31 UTC, drashna approved these changes
Thanks!

2020-09-19 02:31 UTC, merged