Add Phoenix Keyboard
qmk/qmk_firmware pull request #10256
Opened 2020-09-06 12:10 UTC by LSChyi

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-07 03:40 UTC, drashna requested changes

2020-09-07 03:40 UTC, drashna commented on keyboards/phoenix/phoenix.h
> +#define LAYOUT_ergodox(                    \
Could you add the `ergodox_pretty` layout too?

2020-09-07 03:40 UTC, drashna commented on keyboards/phoenix/rules.mk
> +LINK_TIME_OPTIMIZATION_ENABLE=yes
This line should be removed, as it tends to cause issues with ARM/ChibiOS. 

```suggestion
```

Also ... as is, this doesn't actually do anything, anymore.

2020-09-09 04:49 UTC, drashna requested changes

2020-09-09 04:49 UTC, drashna commented on keyboards/phoenix/phoenix.c
> +}
```suggestion
    keyboard_pre_init_user();
}
```

2020-09-09 04:49 UTC, drashna commented on keyboards/phoenix/phoenix.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2020-09-09 04:49 UTC, drashna commented on keyboards/phoenix/phoenix.c
> +}
```suggestion
layer_state_t layer_state_set_kb(layer_state_t state) {
    state = layer_state_set_user(state);
    uint8_t layer = get_highest_layer(state);
    manipulate_led(1, layer  & 1);
    manipulate_led(2, layer >> 1 & 1);
    manipulate_led(3, layer >> 2 & 1);
    return state;
}
```

2020-09-09 04:49 UTC, drashna commented on keyboards/phoenix/info.json
> +    "layouts": {
Would like to have `ergodox pretty` added here too.

2020-09-09 05:37 UTC, drashna approved these changes

2020-09-11 09:00 UTC, noroadsleft requested changes

2020-09-11 09:00 UTC, noroadsleft commented on keyboards/phoenix/rules.mk
> +BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality on B7 by default
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
```

2020-09-11 09:00 UTC, noroadsleft commented on keyboards/phoenix/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-14 10:32 UTC, noroadsleft approved these changes

2020-09-14 10:33 UTC, merged

2020-09-14 10:33 UTC, noroadsleft commented
Thanks!