[Keyboard] Add maJIStic keyboard
qmk/qmk_firmware pull request #10258
Opened 2020-09-06 21:55 UTC by yossiyossy

## Description

Added support for the maJIStic, a split JIS keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-07 03:57 UTC, drashna approved these changes

2020-09-07 05:13 UTC, fauxpark requested changes
Please rename the keyboard folder to lowercase.

2020-09-07 05:13 UTC, fauxpark commented on keyboards/maJIStic/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu
```

2020-09-07 05:13 UTC, fauxpark commented on keyboards/maJIStic/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
AUDIO_ENABLE = no           # Audio output
```

2020-09-07 05:13 UTC, fauxpark commented on keyboards/maJIStic/readme.md
> +A short description of the keyboard/project
Please fill this out.

2020-09-07 05:13 UTC, fauxpark commented on keyboards/maJIStic/keymaps/default/keymap.c
> +}
```suggestion
    [_BASE] = LAYOUT(
                     JP_1,    JP_2,    JP_3,    JP_4,     JP_5,               JP_6,     JP_7,               JP_8,    JP_9,     JP_0,    JP_MINS, JP_CIRC, JP_YEN,  KC_BSPC,
                     KC_TAB,  KC_Q,    KC_W,    KC_E,     KC_R,               KC_T,     KC_Y,               KC_U,    KC_I,     KC_O,    KC_P,    JP_AT,   JP_LBRC, KC_ENT ,
                     KC_CAPS, KC_A,    KC_S,    KC_D,     KC_F,               KC_G,     KC_H,               KC_J,    KC_K,     KC_L,    JP_SCLN, JP_COLN, JP_RBRC,
                     KC_LSFT, KC_Z,    KC_X,    KC_C,     KC_V,               KC_B,     KC_N,               KC_M,    JP_COMM,  JP_DOT,  JP_SLSH, KC_UP,   KC_RSFT,
                     KC_LCTL, KC_LALT, KC_LGUI, KC_LANG2, LT(_LOWER, KC_SPC),           LT(_LOWER, KC_SPC), KC_LANG1, KC_RGUI, KC_LEFT, KC_DOWN, KC_RIGHT
    ),
    [_LOWER] = LAYOUT(
                     KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______, _______,
                     KC_ESC,  _______, _______, _______, _______, _______,              _______, _______, _______, _______, _______, _______, _______, _______,
                     _______, _______, _______, _______, _______, _______,              _______, _______, _______, _______, _______, JP_UNDS, _______,
                     _______, _______, _______, _______, _______, _______,              _______, _______, _______, _______, KC_BRMU, KC_VOLU, _______,
                     _______, _______, _______, _______, _______,                       _______,          _______, _______, KC_BRMD, KC_VOLD, _______
    )
};
```

2020-09-07 05:13 UTC, fauxpark commented on keyboards/maJIStic/config.h
> +    { B6, B2, B3, B1, F7, F6, F5, F4 }
```suggestion
#define MATRIX_ROW_PINS { F6, F7, B1, B3, B2 }
#define MATRIX_COL_PINS { D4, C6, D7, E6, B4, B5, F4, F5 }  // F4, F5 is dummy
#define MATRIX_ROW_PINS_RIGHT { D4, C6, D7, E6, B4 }
#define MATRIX_COL_PINS_RIGHT { B6, B2, B3, B1, F7, F6, F5, F4 }
```

2020-09-07 05:13 UTC, fauxpark commented on keyboards/maJIStic/config.h
> +#define PRODUCT_ID 0x0000
```suggestion
#define PRODUCT_ID 0x6E55
```
```
echo -n "maJIStic" | sha1sum | cut -c1-4
```

2020-09-17 20:18 UTC, noroadsleft requested changes

2020-09-17 20:18 UTC, noroadsleft commented on keyboards/majistic/majistic.h
> +               l20, l21, l22, l23, l24, l25,     r20, r21, r22, r23, r24, r25, r26,      \
QMK custom is that ISO/JIS Enter keys should be on the home row.

```suggestion
               l10, l11, l12, l13, l14, l15,     r10, r11, r12, r13, r14, r15, r16,      \
               l20, l21, l22, l23, l24, l25,     r20, r21, r22, r23, r24, r25, r26, r17, \
```

2020-09-17 20:18 UTC, noroadsleft commented on keyboards/majistic/keymaps/default/keymap.c
> +                     KC_CAPS, KC_A,    KC_S,    KC_D,     KC_F,               KC_G,     KC_H,               KC_J,    KC_K,     KC_L,    JP_SCLN, JP_COLN, JP_RBRC, \
```suggestion
                     KC_TAB,  KC_Q,    KC_W,    KC_E,     KC_R,               KC_T,     KC_Y,               KC_U,    KC_I,     KC_O,    KC_P,    JP_AT,   JP_LBRC,          \
                     KC_CAPS, KC_A,    KC_S,    KC_D,     KC_F,               KC_G,     KC_H,               KC_J,    KC_K,     KC_L,    JP_SCLN, JP_COLN, JP_RBRC, KC_ENT , \
```

2020-09-17 20:18 UTC, noroadsleft commented on keyboards/majistic/keymaps/default/keymap.c
> +                     _______, _______, _______, _______, _______, _______,              _______, _______, _______, _______, _______, JP_UNDS, _______, \
```suggestion
                     KC_ESC,  _______, _______, _______, _______, _______,              _______, _______, _______, _______, _______, _______, _______,          \
                     _______, _______, _______, _______, _______, _______,              _______, _______, _______, _______, _______, JP_UNDS, _______, _______, \
```

2020-09-17 20:18 UTC, noroadsleft commented on keyboards/majistic/info.json
> +								{"label":"Enter", "x":14.25, "y":1, "w":1.25, "h":2},
```suggestion
```

2020-09-17 20:18 UTC, noroadsleft commented on keyboards/majistic/info.json
> +								{"label":"Shift", "x":0, "y":3, "w":1.75},
```suggestion
								{"label":"Enter", "x":14.25, "y":1, "w":1.25, "h":2},
								{"label":"Shift", "x":0, "y":3, "w":1.75},
```

2020-09-18 06:21 UTC, yossiyossy commented
@fauxpark @noroadsleft 
Thank you for comments! I fixed all my mistakes, I think.
Could you review again? And if there are any other mistakes, I'm very sorry but, please tell me again!

2020-09-18 19:00 UTC, noroadsleft approved these changes

2020-09-18 19:01 UTC, merged

2020-09-18 19:01 UTC, noroadsleft commented
Thanks!