Compile commands
qmk/qmk_firmware pull request #10264
Opened 2020-09-07 22:58 UTC by xton

## Description

(I'm not able to re-open https://github.com/qmk/qmk_firmware/pull/8916, so I'm filing a new PR)

I use clangd as a languageserver along with coc.vim[0]. It requires a compilation database[1] to help it figure out how to find all the required files for a given compilation pass. This PR adds a flag (`-c`) to `qmk compile` which creates that for you. Now your dev environment can figure out what `#include QMK_KEYBOARD_H` means.

[0] https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c
[1] https://clang.llvm.org/docs/JSONCompilationDatabase.html

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/issues/4855

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-07 23:00 UTC, xton commented
(See https://github.com/qmk/qmk_firmware/pull/8916 for prior discussion, feedback, and fixes)

2020-09-09 03:20 UTC, drashna commented
two questions. I think I've asked this before, actually ...

1. This requires version 12 of clang, correct?  If so, that may be a problem. I know that MacOS is limited to 11.0.3 on catalina. 
2. This applies to only one keyboard, at a time, correct? I'm pretty sure it's "yes", based on code and comments, but want to be 100% sure.

2020-09-09 03:26 UTC, xton commented
1. No, I'm using this with version 10 on mojave and it works just fine.
2. Yes. Just one at a time. It's quite quick to rebuild though.

2020-09-09 03:46 UTC, xton commented
(also to be clear, I'm not using clang to build qmk. this is strictly used by my dev environment to help intellisense)

2020-09-09 03:52 UTC, drashna commented
Okay, sounds good then.  I just wanted to make sure.

2020-09-09 03:52 UTC, drashna approved these changes

2020-09-23 09:19 UTC, MForster commented
Just some quick feedback: This seems to work well for me, and I'd like to see this merged into master.

2020-09-23 09:48 UTC, MForster commented on .gitignore
> +.clangd/
Newer versions of clangd store the index in `.clangd/`:

```suggestion
# clangd
compile_commands.json
.clangd/
.cache/
```

2020-09-27 05:50 UTC, xton commented
committed suggestion.
ptal @MForster

2020-09-27 05:57 UTC, MForster commented
> committed suggestion.
> ptal @MForster

lgtm

2020-10-04 18:51 UTC, skullydazed commented on docs/cli_commands.md
> +
```suggestion

**Usage**:
```
qmk compiledb [-kb KEYBOARD] [-km KEYMAP]
```

2020-10-11 18:01 UTC, xton commented
Usage line added. Anything else?

ptal @skullydazed

2020-11-10 05:13 UTC, tzarc requested changes
Just a minor docs change, otherwise LGTM.

2020-11-10 05:13 UTC, tzarc commented on lib/python/qmk/cli/compiledb.py
> +    Only tested on OSX+homebrew so far.
```suggestion
```
Seems to be working fine on Linux:
```
% uname -a
Linux hailstorm 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
% qmk compiledb -kb massdrop/ctrl -km default
Ψ Making clean with make clean
Ψ Gathering build instructions from make -n massdrop/ctrl:default
Ψ Found 54 compile commands
Ψ Writing build database to /home/nickb/qmk_build/qmk_firmware/compile_commands.json
```

2020-12-12 18:27 UTC, skullydazed commented
Apologies for not getting back to this sooner. Overall this looks good but I wasn't able to come up with a name that worked better. Normally I'd have merged it anyway but 2020 has changed a lot of routines, and I hadn't cycled around to reviews again in a while.

In the meantime a lot of our current and future work has coalesced around a naming pattern for this sort of this. Could you make one last change to fit this scheme? Calling it `qmk generate-compile-commands` fits our existing scheme, and isn't too bad to tab complete.

2021-03-05 15:40 UTC, closed without merging

2021-07-27 14:13 UTC, j-hui commented
Was there anything else blocking this PR, aside from deciding on the name of the target? I'd also love to see this feature merged in!