Fujitsu T111 keyboard
qmk/qmk_firmware pull request #10262
Opened 2020-09-07 09:14 UTC by DmNosachev

New keyboard: Fujitsu N860-2500-T111
QMK-conversion by directly connecting to the existing matrix 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-09 03:04 UTC, drashna requested changes

2020-09-09 03:04 UTC, drashna commented on keyboards/handwired/t111/keymaps/oleg/keymap.c
> +  VRSN,
You need/want to set this to `SAFE_RANGE`, or you'll run into weird issues, later on. 

```suggestion
  VRSN = SAFE_RANGE,
```

2020-09-09 03:04 UTC, drashna commented on keyboards/handwired/t111/keymaps/oleg/keymap.c
> +	  case VRSN:
```suggestion
      case VRSN:
```

2020-09-09 03:04 UTC, drashna commented on keyboards/handwired/t111/keymaps/oleg/keymap.c
> +	  case MC1:
```suggestion
   case MC1:
```

2020-09-09 03:04 UTC, drashna commented on keyboards/handwired/t111/keymaps/oleg/keymap.c
> +        send_unicode_string("[]");
Why not just? 
```suggestion
        SEND_STRING("[]");
```

2020-09-09 19:04 UTC, DmNosachev commented on keyboards/handwired/t111/keymaps/oleg/keymap.c
> +        send_unicode_string("[]");
I've made 'oleg' keymap by request of the keyboards owner. His idea was to have an ability to input certain characters (e.g. this pair of square brackets) independently of current language layout in OS. Russian layout has х and ъ on [ and ].

2020-09-11 17:53 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/10262/files).

2020-09-11 17:53 UTC, noroadsleft commented on keyboards/handwired/t111/t111.h
> +  K0A,   K19, K29, K39, K49, K59, K69, K79, K09, K1A, K2A, K3A, K4A,           K6A, K7A,   K2B, K3B, K4B, K5B, \
QMK custom is that ISO Enter's location is toward the end of the home row.

```suggestion
  K10,  K17, K27, K37, K47, K57, K67, K77, K07, K18, K28, K38, K48,            K68, K78,   K1B, K00, K70, K60, \
  K0A,   K19, K29, K39, K49, K59, K69, K79, K09, K1A, K2A, K3A, K4A,    K5A,   K6A, K7A,   K2B, K3B, K4B, K5B, \
```

2020-09-11 17:53 UTC, noroadsleft commented on keyboards/handwired/t111/keymaps/default/keymap.c
> +    KC_LCTRL, KC_A,   KC_S,   KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS,                   KC_HOME, KC_END,   KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
```suggestion
    KC_TAB,  KC_Q,    KC_W,   KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,                   KC_PGUP, KC_PGDN,  KC_P7,   KC_P8,   KC_P9,   KC_EQL,
    KC_LCTRL, KC_A,   KC_S,   KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS,        KC_ENT,    KC_HOME, KC_END,   KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
```

2020-09-11 17:53 UTC, noroadsleft commented on keyboards/handwired/t111/info.json
> +            "layout": [{"label":"Break", "x":0, "y":0}, {"label":"PF1", "x":2, "y":0}, {"label":"PF2", "x":3, "y":0}, {"label":"PF3", "x":4, "y":0}, {"label":"PF4", "x":5, "y":0}, {"label":"PF5", "x"
Moving the ISO Enter key's object.

```suggestion
            "layout": [{"label":"Break", "x":0, "y":0}, {"label":"PF1", "x":2, "y":0}, {"label":"PF2", "x":3, "y":0}, {"label":"PF3", "x":4, "y":0}, {"label":"PF4", "x":5, "y":0}, {"label":"PF5", "x":6, "y":0}, {"label":"PF6", "x":7, "y":0}, {"label":"PF7", "x":8, "y":0}, {"label":"PF8", "x":9, "y":0}, {"label":"PF9", "x":10, "y":0}, {"label":"PF10", "x":11, "y":0}, {"label":"PF11", "x":12, "y":0}, {"label":"PF12", "x":13, "y":0}, {"label":"PF13", "x":14, "y":0}, {"label":"PF14", "x":15, "y":0}, {"label":"PF15", "x":16, "y":0}, {"label":"PF16", "x":17, "y":0}, {"label":"Esc", "x":0, "y":1.5}, {"label":"!", "x":1, "y":1.5}, {"label":"@", "x":2, "y":1.5}, {"label":"#", "x":3, "y":1.5}, {"label":"$", "x":4, "y":1.5}, {"label":"%", "x":5, "y":1.5}, {"label":"^", "x":6, "y":1.5}, {"label":"&", "x":7, "y":1.5}, {"label":"*", "x":8, "y":1.5}, {"label":"(", "x":9, "y":1.5}, {"label":")", "x":10, "y":1.5}, {"label":"_", "x":11, "y":1.5}, {"label":"+", "x":12, "y":1.5}, {"label":"~", "x":13, "y":1.5}, {"label":"bkspc", "x":14, "y":1.5, "w":1.25}, {"label":"Ins", "x":15.5, "y":1.5}, {"label":"Cls", "x":16.5, "y":1.5}, {"label":"*", "x":17.75, "y":1.5}, {"label":"/", "x":18.75, "y":1.5}, {"label":"+", "x":19.75, "y":1.5}, {"label":"-", "x":20.75, "y":1.5}, {"label":"Tab", "x":0, "y":2.5, "w":1.5}, {"label":"Q", "x":1.5, "y":2.5}, {"label":"W", "x":2.5, "y":2.5}, {"label":"E", "x":3.5, "y":2.5}, {"label":"R", "x":4.5, "y":2.5}, {"label":"T", "x":5.5, "y":2.5}, {"label":"Y", "x":6.5, "y":2.5}, {"label":"U", "x":7.5, "y":2.5}, {"label":"I", "x":8.5, "y":2.5}, {"label":"O", "x":9.5, "y":2.5}, {"label":"P", "x":10.5, "y":2.5}, {"label":"{", "x":11.5, "y":2.5}, {"label":"}", "x":12.5, "y":2.5}, {"label":"El", "x":15.5, "y":2.5}, {"label":"Dup", "x":16.5, "y":2.5}, {"label":"7", "x":17.75, "y":2.5}, {"label":"8", "x":18.75, "y":2.5}, {"label":"9", "x":19.75, "y":2.5}, {"label":"=", "x":20.75, "y":2.5}, {"label":"Caps Lock", "x":0, "y":3.5, "w":1.75}, {"label":"A", "x":1.75, "y":3.5}, {"label":"S", "x":2.75, "y":3.5}, {"label":"D", "x":3.75, "y":3.5}, {"label":"F", "x":4.75, "y":3.5}, {"label":"G", "x":5.75, "y":3.5}, {"label":"H", "x":6.75, "y":3.5}, {"label":"J", "x":7.75, "y":3.5}, {"label":"K", "x":8.75, "y":3.5}, {"label":"L", "x":9.75, "y":3.5}, {"label":":", "x":10.75, "y":3.5}, {"label":"\"", "x":11.75, "y":3.5}, {"label":"|", "x":12.75, "y":3.5}, {"label":"Enter", "x":13.75, "y":2.5, "w":1.5, "h":2}, {"label":"Del", "x":15.5, "y":3.5}, {"label":"Home", "x":16.5, "y":3.5}, {"label":"4", "x":17.75, "y":3.5}, {"label":"5", "x":18.75, "y":3.5}, {"label":"6", "x":19.75, "y":3.5}, {"label":",", "x":20.75, "y":3.5}, {"label":"Shift", "x":0, "y":4.5, "w":2.25}, {"label":"Z", "x":2.25, "y":4.5}, {"label":"X", "x":3.25, "y":4.5}, {"label":"C", "x":4.25, "y":4.5}, {"label":"V", "x":5.25, "y":4.5}, {"label":"B", "x":6.25, "y":4.5}, {"label":"N", "x":7.25, "y":4.5}, {"label":"M", "x":8.25, "y":4.5}, {"label":"<", "x":9.25, "y":4.5}, {"label":">", "x":10.25, "y":4.5}, {"label":"?", "x":11.25, "y":4.5}, {"x":12.25, "y":4.5}, {"label":"Shift", "x":13.25, "y":4.5, "w":2}, {"label":"\u0432\u2020\u2018", "x":15.5, "y":4.5}, {"label":"\u0432\u2020\u201c", "x":16.5, "y":4.5}, {"label":"1", "x":17.75, "y":4.5}, {"label":"2", "x":18.75, "y":4.5}, {"label":"3", "x":19.75, "y":4.5}, {"label":"Enter", "x":20.75, "y":4.5, "h":2}, {"label":"Caps", "x":1.75, "y":5.5}, {"label":"Graph", "x":2.75, "y":5.5, "w":1.5}, {"x":4.25, "y":5.5, "w":8}, {"label":"Alt", "x":12.25, "y":5.5, "w":1.5}, {"label":"\u0432\u2020\u0452", "x":15.5, "y":5.5}, {"label":"\u0432\u2020\u2019", "x":16.5, "y":5.5}, {"label":"0", "x":17.75, "y":5.5, "w":2}, {"label":".", "x":19.75, "y":5.5}]
```

2020-09-11 17:53 UTC, noroadsleft commented on keyboards/handwired/t111/rules.mk
> +CONSOLE_ENABLE = yes         # Console for debug
```suggestion
CONSOLE_ENABLE = yes        # Console for debug
```

2020-09-11 17:53 UTC, noroadsleft commented on keyboards/handwired/t111/rules.mk
> +DFU_SUFFIX_ARGS = -v 1eaf -p 0003
```suggestion
DFU_ARGS = -d 1EAF:0003 -a2 -R
DFU_SUFFIX_ARGS = -v 1EAF -p 0003
```

2020-09-17 23:21 UTC, noroadsleft commented
It seems the re-request for reviews may have marked my review comments as resolved, but the issues I flagged are still outstanding. Was that deliberate?

2020-09-18 07:25 UTC, DmNosachev commented
> It seems the re-request for reviews may have marked my review comments as resolved, but the issues I flagged are still outstanding. Was that deliberate?

Sorry, that's because I don't know much about how GitHub's UI handles pull requests. I have marked all your suggested changes as _Resolved_ and thought that it makes them to be applied automatically. But I still can see _noroadsleft requested changes_ on the bottom of the page and can't find any other buttons and/or links to agree with proposed changes.

2020-09-19 03:42 UTC, noroadsleft commented
> Sorry, that's because I don't know much about how GitHub's UI handles pull requests. I have marked all your suggested changes as _Resolved_ and thought that it makes them to be applied automatically. But I still can see _noroadsleft requested changes_ on the bottom of the page and can't find any other buttons and/or links to agree with proposed changes.

Okay, there's a couple different systems at play here:

- **Marking a conversation as resolved**:
  "I have completed the requested action."
- **[user] requested changes**:
  You see this when a reviewer requests changes, up until the point that user changes the status of their request. They may request more changes, or approve the changes you've made.

When you have changes requested, you'll see something like this:

![image](https://user-images.githubusercontent.com/18669334/93658139-c1127880-f9ed-11ea-8a7b-0d98425c9036.png)

You can commit that suggestion by clicking the button, but if you go to the Files Changed tab, you gain access to the **Add suggestion to batch** feature:

![image](https://user-images.githubusercontent.com/18669334/93658250-d4721380-f9ee-11ea-8d36-77257cff91e2.png)

Instead of committing that change directly, it adds that suggestion to a queue, where all the suggestions you add to the queue can be committed at once. (I sort of selfishly prefer this because it saves CPU cycles on our CI infrastructure.)

I've unresolved my previous review comments. I don't recall if committing the suggestions (individually or in a batch) marks the conversations as resolved automatically or not, but I'll review them anyway when the PR updates.

Hope this helps.

2020-09-22 06:41 UTC, noroadsleft commented
[Missed one](https://github.com/qmk/qmk_firmware/pull/10262#discussion_r486988268), but you found the right buttons. :slightly_smiling_face:

2020-09-22 07:54 UTC, noroadsleft approved these changes

2020-09-22 08:27 UTC, fauxpark approved these changes

2020-09-22 19:26 UTC, merged

2020-09-22 19:26 UTC, noroadsleft commented
Thanks!