Add hannah65 PCB
qmk/qmk_firmware pull request #10284
Opened 2020-09-10 12:50 UTC by mechlovin

## Description
Add hannah65 PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-20 22:49 UTC, drashna commented on keyboards/mechlovin/hannah65/hannah65.h
> +#endif
```suggestion
#if defined(KEYBOARD_mechlovin_hannah65_rev1)
#    include "rev1.h"
#elif defined(KEYBOARD_mechlovin_hannah65_mechlovin9)
#    include "mechlovin9.h"
#endif
```

2020-09-20 22:51 UTC, drashna commented on keyboards/mechlovin/hannah65/rev1/info.json
> +    }
I think this line might be extra (PR Lint has a fit on/near this line

2020-09-21 06:37 UTC, fauxpark requested changes

2020-09-21 06:37 UTC, fauxpark commented on keyboards/mechlovin/hannah65/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-22 08:17 UTC, fauxpark requested changes

2020-09-22 08:17 UTC, fauxpark commented on keyboards/mechlovin/hannah65/mechlovin9/readme.md
> +
```suggestion
```

2020-09-22 08:17 UTC, fauxpark commented on keyboards/mechlovin/hannah65/readme.md
> +
```suggestion
```

2020-09-22 08:17 UTC, fauxpark commented on keyboards/mechlovin/hannah65/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-22 08:17 UTC, fauxpark commented on keyboards/mechlovin/hannah65/rev1/keymaps/via/keymap.c
> +
You need to add three blank layers here.

2020-09-23 21:30 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/10284/files).

2020-09-23 21:30 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/rev1/rev1.h
> +#define LAYOUT_ansi( \
```suggestion
#define LAYOUT_65_ansi_blocker( \
```

2020-09-23 21:30 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/rev1/rev1.h
> +#define LAYOUT_iso( \
```suggestion
#define LAYOUT_65_iso_blocker( \
```

2020-09-23 21:30 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/rev1/info.json
> +        "LAYOUT_ansi": {
```suggestion
        "LAYOUT_65_ansi_blocker": {
```

2020-09-23 21:30 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/rev1/info.json
> +        "LAYOUT_iso": {
```suggestion
        "LAYOUT_65_iso_blocker": {
```

2020-09-23 21:30 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/rev1/info.json
> +    }
```suggestion
        }
    }
}
```

2020-09-24 07:10 UTC, noroadsleft commented
[One review comment outstanding.](https://github.com/qmk/qmk_firmware/pull/10284#discussion_r493902167)

2020-09-24 08:05 UTC, noroadsleft requested changes

2020-09-24 08:05 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/mechlovin9/info.json
> +            "layout_all": [
```suggestion
        "LAYOUT_all": {
            "layout": [
```

2020-09-24 11:02 UTC, mechlovin commented
> GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/10284/files).

Its new for me. Thank you

2020-09-26 01:41 UTC, noroadsleft requested changes

2020-09-26 01:41 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/mechlovin9/info.json
> +                {"label":"K30 (B3,B5)", "x":0, "y":3, "w":1.25},
Fixing a couple errors with the key sizing/positioning.

![image](https://user-images.githubusercontent.com/18669334/94327277-b1031780-ff5e-11ea-8f3f-c2ae8cb2fdc5.png)

```suggestion
                {"label":"K30 (B3,B5)", "x":0, "y":3, "w":2.25},
```

2020-09-26 01:41 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/mechlovin9/info.json
> +                {"label":"K4B (B4,D0)", "x":11.25, "y":4, "w":1.25},
```suggestion
                {"label":"K40 (B4,B5)", "x":0, "y":4, "w":1.5},
                {"label":"K41 (B4,B6)", "x":1.5, "y":4},
                {"label":"K42 (B4,B7)", "x":2.5, "y":4, "w":1.5},
                {"label":"K46 (B4,C3)", "x":4, "y":4, "w":7},
                {"label":"K4B (B4,D0)", "x":11, "y":4, "w":1.5},
```

2020-09-26 05:09 UTC, fauxpark approved these changes

2020-09-26 05:32 UTC, noroadsleft approved these changes

2020-09-26 05:33 UTC, merged

2020-09-26 05:33 UTC, noroadsleft commented
Thanks!