[Core] DYNAMIC_KEYMAP_EEPROM_MAX_ADDR check
qmk/qmk_firmware pull request #10315
Opened 2020-09-14 15:22 UTC by Xelus22

## Description

Due to the return type of `uint16_t` it would be a temporary control to add in a check for the size

Previously it would compile with a number greater than 65535, e.g.  65536. 

However as shown in the issue below, the compiler only tells us when the #define is much larger than the `uint16_t` max size.

https://github.com/qmk/qmk_firmware/issues/8742 - see  more here

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Max EEPROM size check for dynamic keymaps

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-14 16:03 UTC, nooges approved these changes

2020-09-14 16:12 UTC, fauxpark requested changes

2020-09-14 16:12 UTC, fauxpark commented on quantum/dynamic_keymap.c
> +    #error DYNAMIC_KEYMAP_EEPROM_MAX_ADDR is greater than 65535
```suggestion
#    error DYNAMIC_KEYMAP_EEPROM_MAX_ADDR must be less than 65536
```

2020-09-15 00:52 UTC, fauxpark approved these changes

2020-09-15 06:02 UTC, drashna approved these changes

2020-09-16 06:15 UTC, tzarc approved these changes

2020-09-16 06:16 UTC, merged