moved encoder code to timberwolf.c
qmk/qmk_firmware pull request #10317
Opened 2020-09-15 04:24 UTC by Croktopus

## Description

Found that having encoder code in keymap files made it so that when you flashed firmware from qmk configurator, the encoder stopped working. moved the code to keyboard.c in order to fix that issue

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-21 00:16 UTC, drashna requested changes

2020-09-21 00:16 UTC, drashna commented on keyboards/metamechs/timberwolf/timberwolf.c
> +void encoder_update_kb(uint8_t index, bool clockwise) {
```suggestion
__attribute__((weak))
void encoder_update_user(uint8_t index, bool clockwise) {
```

2020-09-21 20:37 UTC, noroadsleft approved these changes

2020-09-22 05:54 UTC, drashna approved these changes

2020-09-22 05:54 UTC, merged