adding V2 compatibility
qmk/qmk_firmware pull request #10310
Opened 2020-09-13 23:07 UTC by worldspawn00

adding support for new layout options

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-13 23:25 UTC, worldspawn00 commented
checks will fail till all 3 modified files are approved

2020-09-13 23:26 UTC, worldspawn00 commented
Pull 10312, 10311, 10310

2020-09-14 19:04 UTC, ridingqwerty approved these changes

2020-09-21 00:28 UTC, drashna requested changes

2020-09-21 00:28 UTC, drashna commented on keyboards/wsk/sl40/sl40.h
> +	K300, K301, K302,       K304,       K306,       K308, K309, K310, K311, K312, K313  \
```suggestion
    K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011, K012, K013, \
    K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111,       K113, \
    K200,       K202, K203, K204, K205, K206, K207, K208, K209, K210, K211, K212, K213, \
    K300, K301, K302,       K304,       K306,       K308, K309, K310, K311, K312, K313  \
```

2020-09-21 00:28 UTC, drashna commented on keyboards/wsk/sl40/sl40.h
> +	{ K300,  K301,  K302,  KC_NO, K304,  KC_NO, K306,  KC_NO, K308,  K309,  K310,  K311,  K312,  K313 }  \
```suggestion
    { K000,  K001,  K002,  K003,  K004,  K005,  K006,  K007,  K008,  K009,  K010,  K011,  K012,  K013 }, \
    { K100,  K101,  K102,  K103,  K104,  K105,  K106,  K107,  K108,  K109,  K110,  K111,  KC_NO, K113 }, \
    { K200,  KC_NO, K202,  K203,  K204,  K205,  K206,  K207,  K208,  K209,  K210,  K211,  K212,  K213 }, \
    { K300,  K301,  K302,  KC_NO, K304,  KC_NO, K306,  KC_NO, K308,  K309,  K310,  K311,  K312,  K313 }  \
```

2020-09-22 04:40 UTC, noroadsleft commented
Closing per https://github.com/qmk/qmk_firmware/pull/10311#issuecomment-696504518.

2020-09-22 04:40 UTC, closed without merging