add handwired/swiftrax/retropad
qmk/qmk_firmware pull request #10331
Opened 2020-09-17 02:10 UTC by swiftrax

## Description
Add keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-17 02:10 UTC, swiftrax commented
![image](https://user-images.githubusercontent.com/48102030/93411585-52e47f00-f850-11ea-80d1-3872b2b98b3a.png)

2020-09-20 23:55 UTC, drashna requested changes

2020-09-20 23:55 UTC, drashna commented on keyboards/handwired/swiftrax/retropad/config.h
> +#define DESCRIPTION     2x2 macro pad with a rotary encoder
```suggestion
```

2020-09-20 23:55 UTC, drashna commented on keyboards/handwired/swiftrax/retropad/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 3
Since the matrix is super small, you can up this, if you wanted.

2020-09-20 23:55 UTC, drashna commented on keyboards/handwired/swiftrax/retropad/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
```

2020-09-21 07:29 UTC, fauxpark requested changes

2020-09-21 07:29 UTC, fauxpark commented on keyboards/handwired/swiftrax/retropad/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-09-21 07:29 UTC, fauxpark commented on keyboards/handwired/swiftrax/retropad/rules.mk
> +MIDI_ENABLE = no            # MIDI support
```suggestion
```

2020-09-22 05:38 UTC, drashna approved these changes

2020-09-22 08:19 UTC, fauxpark approved these changes

2020-09-22 22:39 UTC, merged

2020-09-22 22:39 UTC, zvecr commented
Thanks!

2020-09-23 03:27 UTC, swiftrax commented
Thanks