Add ai03/soyuz VIA Support
qmk/qmk_firmware pull request #10336
Opened 2020-09-17 07:27 UTC by mrsendyyk

## Description

Add `ai03/soyuz` VIA Support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-19 02:58 UTC, drashna commented on keyboards/ai03/soyuz/config.h
> +#define PRODUCT_ID      0x0004 // ai03
Ummmm ... vender ID?

2020-09-20 06:30 UTC, noroadsleft requested changes
This actually won't work because `0xA103:0x0004` is the same Vendor ID/Product ID pair that the Equinox has, and the Equinox is already supported by VIA.

@ai03-2725, what would you like done here? Soyuz was added to QMK first, but Equinox already has VIA support, so Soyuz would be easier to change.

2020-09-20 21:41 UTC, mrsendyyk commented on keyboards/ai03/soyuz/config.h
> +#define PRODUCT_ID      0x0004 // ai03
@ai03-2725

2020-09-22 17:16 UTC, ai03-2725 commented
> This actually won't work because `0xA103:0x0004` is the same Vendor ID/Product ID pair that the Equinox has, and the Equinox is already supported by VIA.
> 
> @ai03-2725, what would you like done here? Soyuz was added to QMK first, but Equinox already has VIA support, so Soyuz would be easier to change.

If it is fine, would it be possible to change the product ID of Soyuz from 0004 to 0018?
Honestly no clue how the conflicting ID happened since I usually refer to a running list of PIDs, adding new boards with incremented ID as necessary. Perhaps this board was from before I started keeping track.

2020-09-22 20:29 UTC, noroadsleft commented
> If it is fine, would it be possible to change the product ID of Soyuz from 0004 to 0018?
> Honestly no clue how the conflicting ID happened since I usually refer to a running list of PIDs, adding new boards with incremented ID as necessary. Perhaps this board was from before I started keeping track.

Sounds good, thanks.

2020-09-22 20:30 UTC, noroadsleft requested changes

2020-09-22 20:30 UTC, noroadsleft commented on keyboards/ai03/soyuz/config.h
> +#define PRODUCT_ID      0x0004 // ai03
```suggestion
#define PRODUCT_ID      0x0018
```

2020-09-24 02:26 UTC, noroadsleft approved these changes

2020-09-24 02:29 UTC, fauxpark approved these changes

2020-09-24 02:34 UTC, merged

2020-09-24 02:34 UTC, noroadsleft commented
Thanks!