Add Canoe Gen2
qmk/qmk_firmware pull request #10344
Opened 2020-09-17 14:57 UTC by evyd13

## Description

Adds the Canoe Gen2. It has per key RGB using the ws2812 protocol.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-20 23:15 UTC, drashna approved these changes
I'm not really a fan of the folder name.  `/percent/canoe/gen2` or rev2 would be better, I think.

2020-09-21 07:24 UTC, fauxpark requested changes

2020-09-21 07:24 UTC, fauxpark commented on keyboards/percent/canoegen2/keymaps/via/rules.mk
> +#
```suggestion
```

2020-09-21 07:24 UTC, fauxpark commented on keyboards/percent/canoegen2/canoegen2.h
> +void matrix_scan_user(void);
```suggestion
```

2020-09-21 07:24 UTC, fauxpark commented on keyboards/percent/canoegen2/canoegen2.c
> +void suspend_power_down_kb(void) {
```suggestion
#ifdef RGB_MATRIX_ENABLE
void suspend_power_down_kb(void) {
```

2020-09-21 07:24 UTC, fauxpark commented on keyboards/percent/canoegen2/canoegen2.c
> +} };
```suggestion
} };
#endif
```

2020-09-23 09:56 UTC, noroadsleft requested changes
> I'm not really a fan of the folder name. `/percent/canoe/gen2` or rev2 would be better, I think.

I agree with @drashna about this. The folder name should definitely be `percent/canoe/gen2` or `percent/canoe/rev2`.

----

## Summary of Requested Changes

- rename `LAYOUT_65_ansi` to `LAYOUT_65_ansi_blocker_split_bs`
- rename `LAYOUT_65_iso` to `LAYOUT_65_iso_blocker_split_bs`
- update Community Layout support per the above (though based on keyboard renders `65_(ansi|iso)` layouts are almost undoubtedly supported)

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/canoegen2.h
> +#define LAYOUT_all LAYOUT_65_iso
```suggestion
#define LAYOUT_all LAYOUT_65_iso_blocker_split_bs
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/canoegen2.h
> +#define LAYOUT_65_ansi( \
```suggestion
#define LAYOUT_65_ansi_blocker_split_bs( \
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/canoegen2.h
> +#define LAYOUT_65_iso( \
```suggestion
#define LAYOUT_65_iso_blocker_split_bs( \
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/info.json
> +        "LAYOUT_65_ansi": {
```suggestion
        "LAYOUT_65_ansi_blocker_split_bs": {
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/info.json
> +        "LAYOUT_65_iso": {
```suggestion
        "LAYOUT_65_iso_blocker_split_bs": {
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/keymaps/default/keymap.c
> +[0] = LAYOUT_65_ansi(
```suggestion
[0] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/keymaps/default/keymap.c
> +[1] = LAYOUT_65_ansi(
```suggestion
[1] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-23 09:56 UTC, noroadsleft commented on keyboards/percent/canoegen2/rules.mk
> +LAYOUTS = 65_ansi 65_iso
```suggestion
LAYOUTS = 65_ansi_blocker_split_bs 65_iso_blocker_split_bs
```

2020-09-25 13:22 UTC, kb-elmo commented
> 
> 
> > I'm not really a fan of the folder name. `/percent/canoe/gen2` or rev2 would be better, I think.
> 
> I agree with @drashna about this. The folder name should definitely be `percent/canoe/gen2` or `percent/canoe/rev2`.

Imho no because that would give the impression that the boards are in some way related to each other design or pcb wise which is entirely not the case.
The Gen 2 is a complete redesign with an entirely different PCB (the gen 1 used a ps2avr PCB).
The only similarity between these boards is that they are called Canoe.

2020-09-25 13:25 UTC, fauxpark commented
The same is technically true of the Planck and Preonic...

2020-09-25 13:30 UTC, kb-elmo commented
Putting the boards in one folder would be like putting Keycult boards in one folder named TKL with subfolders named No1 and No2 because "technically" they are just another version of the Keycult TKL.

It doesn't make sense because it's not just some revision of the board.
The first board was called Canoe. The second Canoe Gen2. 
So it makes sense to put it in a folder called canoegen2.

2020-09-25 19:13 UTC, drashna commented
> The first board was called Canoe. The second Canoe Gen2.

Both boards use the same layout, correct?  If so, then revision works fine here.  
That's fauxparks point with the planck and preonic.  Specifically, there are 4 different planck boards, the Rev1-5, the Rev6, the EZ, and the Light.  They're all "planck" but the matrix and features and controller are all different. Rev1-5 uses atmega32u4, the rev6 and EZ use stm32f303, and the light uses at90usb1286. The EZ and Light use per key RGB, using different ISSI controllers), etc.

So having a different controller, a different matrix and different features really isn't a good reason to have a completely different name and folder.  

And there are plenty of other boards that follow this pattern too (for instance, the helix).  



> So it makes sense to put it in a folder called canoegen2.

IMO, no it doesn't, given the precedent already in the repo. 

However `canoe/gen2` would also be fine.  and looks better than `canoegen2`.

2020-09-25 19:19 UTC, Erovia commented
>  So it makes sense to put it in a folder called canoegen2.

Not just looks better, but is what the user's familiar with QMK are expecting.

2020-09-25 19:21 UTC, jackhumbert commented
> It doesn't make sense because it's not just some revision of the board.

I think "gen" is functionally the same as "rev" here, so should get the same treatment. 

Usually when introducing another revision, what code was previously just `keyboard/` gets moved to `keyboard/rev1/`, and any shared code can be moved to back to `keyboard/`. This allows folks to easily use the same keymap between both revisions without having to copy it into the new keyboard's folder.

2020-09-25 19:44 UTC, kb-elmo commented
> 
> 
> > It doesn't make sense because it's not just some revision of the board.
> 
> I think "gen" is functionally the same as "rev" here, so should get the same treatment.
> 

No it is not. You apparently didn't read what I said.
This is not a "revision" of the board.
It's an entirely new design and should be treated as such.

And like I said the boards do not share anything but a part of the name.

2020-09-25 20:01 UTC, kb-elmo commented
> 
> > The first board was called Canoe. The second Canoe Gen2.
> 
> Both boards use the same layout, correct? If so, then revision works fine here.
> 

This doesn't make any sense at all.
Just because a board has the same layout doesn't mean that it's in any way a similar keyboard.
By that logic we could just place all boards by the same designer in folders named after the layouts.

>
> However `canoe/gen2` would also be fine. and looks better than `canoegen2`.
>

The planck is still the same board and all the PCBs are compatible with the Planck case.
This is simply not the case with the Canoe Gen2.

Again: This is an entirely new design and the boards are in no way compatible with each other.
The Gen2 PCB does **not** fit the original Canoe case and vice versa.
Placing the two boards in the same folder would imply that the boards are compatible with each other.

2020-09-25 20:06 UTC, fauxpark commented
> it would give the impression that the boards are in some way compatible with each other which is not the case.

The only compatibility that really matters here is the layout support, as we aim to abstract away the hardware-specific stuff for exactly this reason.

> The planck example does not apply here because the planck with all it's PCB revisions is still the same board

As Drashna mentioned above, the different revisions of the Planck use different MCUs (and I believe the rev6 was designed by someone else whereas most/all of the earlier revs were designed by Wilba). So I think it very much applies here.

The very fact that this board is named "Gen2" kind of *implies* that a gen1 also exists. I'd argue that is more confusing to users.

2020-09-25 20:10 UTC, kb-elmo commented
> 
> 
> > it would give the impression that the boards are in some way compatible with each other which is not the case.
> 
> The only compatibility that really matters here is the layout support, as we aim to abstract away the hardware-specific stuff for exactly this reason.
> 
> > The planck example does not apply here because the planck with all it's PCB revisions is still the same board
> 
> As Drashna mentioned above, the different revisions of the Planck use different MCUs (and I believe the rev6 was designed by someone else whereas most/all of the earlier revs were designed by Wilba). So I think it very much applies here.
> 
> The very fact that this board is named "Gen2" kind of _implies_ that a gen1 also exists. I'd argue that is more confusing to users.

"Canoe Gen2" is the name of the board. It's not "Canoe" generation 2 or something. Yes technically this could be seen like this but it is meant as the name of the board here.

And again it is not just the MCU or matrix that is different on the new PCB. It does not fit the original Canoe case.

2020-09-25 20:18 UTC, fauxpark commented
So why does the website say "revision"?

As for it not fitting the case - AFAICT it doesn't seem like you can buy the PCB on its own, so that doesn't matter anyway.

2020-09-25 20:19 UTC, kb-elmo commented
> 
> 
> So why does the website say "revision"?
> 
> As for it not fitting the case - AFAICT it doesn't seem like you can buy the PCB on its own, so that doesn't matter anyway.

You can't right now but there are more PCBs planned. A hotswap PCB should become available later this year for the board as well as a separately available soldered PCB.

2020-09-25 20:23 UTC, jackhumbert commented
After talking to kingnestea on the Percent Studio discord, they're ok with `/percent/canoe_gen2` - if you update the keyboard name to that, that'd be great!

2020-09-26 02:01 UTC, noroadsleft requested changes
https://github.com/qmk/qmk_firmware/pull/10344#discussion_r493387459 still needs changing; the `via` keymap won't compile without this change (`LAYOUT_65_iso` doesn't exist).

2020-09-26 05:10 UTC, fauxpark approved these changes

2020-09-26 05:38 UTC, noroadsleft approved these changes
Looks good to me.

2020-09-26 05:39 UTC, merged

2020-09-26 05:39 UTC, noroadsleft commented
Thanks!

2020-09-26 05:44 UTC, evyd13 commented
Thank you!