Add keyboard and keymap for The Nines macropad
qmk/qmk_firmware pull request #10356
Opened 2020-09-18 18:23 UTC by luis-godinez

Ungodly Design | The Nines Macropad.

## Description

Add keyboard and mapping.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-19 02:53 UTC, drashna reviewed
Could you add a license header to all of the `c` and `h` files (including the keymaps? 

Aside from that, it looks good to me.

2020-09-19 02:55 UTC, fauxpark requested changes

2020-09-19 02:55 UTC, fauxpark commented on keyboards/ungodly/nines/config.h
> +#define DESCRIPTION     A 9 key (3x3) macropad with rotary encoder support.
```suggestion
```

2020-09-19 02:55 UTC, fauxpark commented on keyboards/ungodly/nines/config.h
> +#define PRODUCT         The Nines by Ungodly Design
```suggestion
#define PRODUCT         The Nines
```

2020-09-19 02:55 UTC, fauxpark commented on keyboards/ungodly/nines/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-09-19 02:55 UTC, fauxpark commented on keyboards/ungodly/nines/rules.mk
> +ENCODER_ENABLE = yes        # Rotary encoder support
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes        # Rotary encoder support
```

2020-09-19 04:58 UTC, luis-godinez reviewed
thanks. done.

2020-09-19 06:08 UTC, fauxpark requested changes

2020-09-19 06:08 UTC, fauxpark commented on keyboards/ungodly/nines/readme.md
> +![Nines](http://i.imgur.com/q2M3uEU.jpg)
```suggestion
![Nines](https://i.imgur.com/q2M3uEUl.jpg)
```

2020-09-19 23:51 UTC, luis-godinez commented on keyboards/ungodly/nines/readme.md
> +![Nines](http://i.imgur.com/q2M3uEU.jpg)
Updated url with correct link.

2020-09-20 01:04 UTC, drashna approved these changes

2020-09-20 02:49 UTC, fauxpark requested changes

2020-09-20 02:49 UTC, fauxpark commented on keyboards/ungodly/nines/readme.md
> +![Nines](https://www.instagram.com/p/CFFPIJBHDSp)
This doesn't render anymore. An imgur link is preferred.

2020-09-20 02:49 UTC, fauxpark commented on keyboards/ungodly/nines/config.h
> +
```suggestion
```

2020-09-26 01:35 UTC, noroadsleft requested changes

2020-09-26 01:35 UTC, noroadsleft commented on keyboards/ungodly/nines/readme.md
> +![Nines](https://imgur.com/a/EcypUBG)
This needs to be a direct image link.

```suggestion
![Nines](https://i.imgur.com/zNnmPV9l.jpg)
```

2020-09-26 17:56 UTC, closed without merging

2020-09-26 18:31 UTC, noroadsleft commented
@luis-godinez What was the reason for closing this pull request?

2020-09-26 21:50 UTC, luis-godinez commented
I'll clean up the CL and request a pull in the future.

2020-09-26 22:56 UTC, noroadsleft commented
You don't actually have to open a whole new pull request. When you open a pull request, GitHub tracks which branch contains your changes. All you have to do is make any requested changes and commit them to the same branch from which you opened the PR, then push the branch to GitHub.