Adding preonic layout
qmk/qmk_firmware pull request #10364
Opened 2020-09-19 06:55 UTC by xplusplus

## Description

Added Keymaps:
preonic/rev3

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-19 11:19 UTC, zvecr approved these changes

2020-09-19 11:27 UTC, fauxpark requested changes

2020-09-19 11:27 UTC, fauxpark commented on keyboards/preonic/keymaps/codecoffeecode/keymap.c
> +  KC_LCTL, KC_LCTL, KC_LALT, KC_LGUI, MO(1),       KC_SPC,       MO(2),   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT  \
```suggestion
[0] = LAYOUT_preonic_1x2uC(
  KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC,
  KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_DEL,
  KC_ESC,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
  KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
  KC_LCTL, KC_LCTL, KC_LALT, KC_LGUI, MO(1),       KC_SPC,       MO(2),   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT
```

2020-09-19 11:27 UTC, fauxpark commented on keyboards/preonic/keymaps/codecoffeecode/keymap.c
> +  _______, _______, _______, _______, _______,      _______,     _______, KC_MNXT, KC_VOLD, KC_VOLU, KC_MPLY  \
```suggestion
[1] = LAYOUT_preonic_1x2uC(
  KC_GRV,  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______,      _______,     _______, KC_MNXT, KC_VOLD, KC_VOLU, KC_MPLY
```

2020-09-19 11:27 UTC, fauxpark commented on keyboards/preonic/keymaps/codecoffeecode/keymap.c
> +)};
```suggestion
[2] = LAYOUT_preonic_1x2uC(
  _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,
  _______, RESET,   DEBUG,   _______, _______, _______, _______, _______, _______, _______, KC_F12,  _______,
  _______, _______, _______, _______, _______, _______, _______, KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______,     _______,      _______, _______, _______, _______, _______
)};
```

2020-09-19 19:37 UTC, noroadsleft requested changes

2020-09-19 19:37 UTC, noroadsleft commented on keyboards/preonic/keymaps/codecoffeecode/keymap.c
> +#include QMK_KEYBOARD_H
Could we get a license header here, please?

2020-09-21 04:50 UTC, drashna approved these changes

2020-09-21 07:04 UTC, fauxpark approved these changes

2020-09-22 01:40 UTC, noroadsleft approved these changes

2020-09-22 01:41 UTC, merged

2020-09-22 01:41 UTC, noroadsleft commented
Thanks!