Add Handwired/Curiosity [Keyboard Addition]
qmk/qmk_firmware pull request #10369
Opened 2020-09-20 00:32 UTC by Spaceman

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-20 00:57 UTC, drashna requested changes

2020-09-20 00:57 UTC, drashna commented on keyboards/handwired/curiosity/curiosity.h
> +#define SMALL_MODS( \
```suggestion
#define LAYOUT_small_mods( \
```

2020-09-20 00:57 UTC, drashna commented on keyboards/handwired/curiosity/curiosity.h
> +#define LARGE_MODS( \
```suggestion
#define LAYOUT_large_mods( \
```

2020-09-20 00:57 UTC, drashna commented on keyboards/handwired/curiosity/info.json
> +    "SMALL_MODS": {
```suggestion
    "LAYOUT_small_mods": {
```

2020-09-20 00:57 UTC, drashna commented on keyboards/handwired/curiosity/info.json
> +    "LARGE_MODS": {
```suggestion
    "LAYOUT_large_mods": {
```

2020-09-20 00:57 UTC, drashna commented on keyboards/handwired/curiosity/keymaps/default/keymap.c
> +	[0] = SMALL_MODS(
```suggestion
    [0] = LAYOUT_small_mods(
```

2020-09-20 00:57 UTC, drashna commented on keyboards/handwired/curiosity/keymaps/default/keymap.c
> +	[1] = SMALL_MODS(
```suggestion
    [1] = LAYOUT_small_mods(
```

2020-09-20 01:48 UTC, drashna approved these changes

2020-09-20 02:58 UTC, fauxpark requested changes

2020-09-20 02:58 UTC, fauxpark commented on keyboards/handwired/curiosity/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-09-20 02:58 UTC, fauxpark commented on keyboards/handwired/curiosity/rules.mk
> +RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = no             # Use link time optimization
```

2020-09-20 02:58 UTC, fauxpark commented on keyboards/handwired/curiosity/rules.mk
> +BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality on B7 by default
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```

2020-09-21 18:01 UTC, noroadsleft requested changes

2020-09-21 18:01 UTC, noroadsleft commented on keyboards/handwired/curiosity/keymaps/default/keymap.c
> +/* Copyright 2019 marhalloweenvt
marhalloweenvt?

2020-09-21 18:21 UTC, Spaceman commented on keyboards/handwired/curiosity/keymaps/default/keymap.c
> +/* Copyright 2019 marhalloweenvt
Whoops my bad just copied from another keyboard

2020-09-22 07:32 UTC, noroadsleft approved these changes

2020-09-22 07:33 UTC, merged

2020-09-22 07:33 UTC, noroadsleft commented
Thanks!