Bella
qmk/qmk_firmware pull request #10381
Opened 2020-09-20 23:52 UTC by moyi4681

add bella soldered keyboard

2020-09-21 04:36 UTC, drashna requested changes

2020-09-21 04:36 UTC, drashna commented on keyboards/kbdfans/bella/soldered/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=4096
This isn't needed. But bootloader type is. 

```suggestion
# Bootloader  type
BOOTLOADER = atmel-dfu
```

2020-09-21 04:36 UTC, drashna commented on keyboards/kbdfans/bella/soldered/rules.mk
> +RGBLIGHT_ENABLE ?= no
```suggestion
BOOTMAGIC_ENABLE = lite # Virtual DIP switch configuration
MOUSEKEY_ENABLE  = yes  # Mouse keys
EXTRAKEY_ENABLE  = yes  # Audio control and System control
CONSOLE_ENABLE   = no   # Console for debug
COMMAND_ENABLE   = no   # Commands for debug and configuration
SLEEP_LED_ENABLE = no   # Breathing sleep LED during USB suspend
NKRO_ENABLE      = yes  # USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = yes  # Enable keyboard backlight functionality
AUDIO_ENABLE     = no
RGBLIGHT_ENABLE  = no
```

2020-09-21 07:00 UTC, fauxpark requested changes

2020-09-21 07:00 UTC, fauxpark commented on keyboards/kbdfans/bella/soldered/rules.mk
> +RGBLIGHT_ENABLE  = no
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-22 01:51 UTC, noroadsleft requested changes

2020-09-22 01:51 UTC, noroadsleft commented on keyboards/kbdfans/bella/soldered/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2020-09-22 05:22 UTC, drashna approved these changes

2020-09-22 07:48 UTC, noroadsleft approved these changes

2020-09-22 07:48 UTC, merged

2020-09-22 07:49 UTC, noroadsleft commented
Thanks!