add swap hands config
qmk/qmk_firmware pull request #10397
Opened 2020-09-22 06:36 UTC by winterNebs

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_firmware/pull/10328#discussion_r492484999

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-22 22:20 UTC, zvecr requested changes
As the root level config.h doesnt have matrix info, the swap hands config should be moved to `keyboards/kyria/rev1/rev1.c` so that if a ver2 is introduced with a different matrix size it doesnt cause any issues.

2020-09-22 23:13 UTC, zvecr approved these changes

2020-09-23 00:08 UTC, fauxpark approved these changes

2020-09-23 00:35 UTC, merged

2020-09-23 00:35 UTC, zvecr commented
Thanks!