Terrazzo Keyboard
qmk/qmk_firmware pull request #10408
Opened 2020-09-23 15:47 UTC by ademey

## Description

Hi, this PR is for Terrazzo, a pro-micro 40% keyboard that integrates a IS31FL3731 single color LED module. There are staggered and ortho versions of the keyboard. 

For images and a video, please see this [Imgur page](https://imgur.com/a/L8YjlqU).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-25 15:18 UTC, ridingqwerty requested changes
Just some outmoded conventions for which I made some suggestions.  The terrazzo effects bit seems sound although I have no way to test that.  Everything looks good otherwise.

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/config.h
> +#define CONFIG_H
```suggestion
#pragma once
```

Prefer `#pragma once` here over the old-style include guards.

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/config.h
> +#define DESCRIPTION     40% Keyboard with LED Matrix
```suggestion
```

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/config.h
> +#endif
```suggestion
```

See above re: `#pragma once`, which obviates the need for a closing `#endif`.

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/keymaps/default/keymap.c
> +#include "terrazzo.h"
```suggestion
```

This is redundant as `#include QMK_KEYBOARD_H` will include `"terrazzo.h"`.

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/keymaps/ortho/keymap.c
> +#include "terrazzo.h"
```suggestion
```

This is redundant as `#include QMK_KEYBOARD_H` will include `"terrazzo.h"`.

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/keymaps/ortho_all/keymap.c
> +#include "terrazzo.h"
```suggestion
```

This is redundant as `#include QMK_KEYBOARD_H` will include `"terrazzo.h"`.

2020-09-25 15:18 UTC, ridingqwerty commented on keyboards/terrazzo/keymaps/ortho_mit/keymap.c
> +#include "terrazzo.h"
```suggestion
```

This is redundant as `#include QMK_KEYBOARD_H` will include `"terrazzo.h"`.

2020-10-02 01:57 UTC, ademey commented on keyboards/terrazzo/rules.mk
> +
I was not able to get my keymaps to build with this change. The one thing it was missing was:
```
# MCU name
MCU = atmega32u4
```
All keymaps build fine now.

2020-10-04 20:17 UTC, drashna requested changes
Very cool! 

However, for all of the `c` and `h` files, could you add a GPL2+ compatible license header?

2020-10-04 20:17 UTC, drashna commented on keyboards/terrazzo/keymaps/default/keymap.c
> +    switch(biton32(layer_state)) {
```suggestion
    switch(get_highest_layer(layer_state)) {
```

2020-10-04 20:17 UTC, drashna commented on keyboards/terrazzo/keymaps/ortho/keymap.c
> +    switch(biton32(layer_state)) {
```suggestion
    switch(get_highest_layer(layer_state)) {
```

2020-10-04 20:17 UTC, drashna commented on keyboards/terrazzo/keymaps/ortho_all/keymap.c
> +    switch(biton32(layer_state)) {
```suggestion
    switch(get_highest_layer(layer_state)) {
```

2020-10-04 20:17 UTC, drashna commented on keyboards/terrazzo/keymaps/ortho_mit/keymap.c
> +    switch(biton32(layer_state)) {
```suggestion
    switch(get_highest_layer(layer_state)) {
```

2020-10-13 11:28 UTC, drashna approved these changes

2020-10-21 16:03 UTC, ridingqwerty approved these changes

2020-10-23 22:14 UTC, merged