Add userspace and personal keymaps for brandonschlack
qmk/qmk_firmware pull request #10411
Opened 2020-09-23 16:46 UTC by brandonschlack

## Description

Add my personal keymaps and userspace to QMK Core. I have benefited greatly from seeing all the user functions and maps, that I would like to contribute my own that I've been working on throughout the last year.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-23 17:03 UTC, Spaceman requested changes

2020-09-23 17:03 UTC, Spaceman commented on keyboards/kbdfans/kbd67/rev2/keymaps/brandonschlack/keymap.c
> +/* Copyright 2019 MechMerlin
```suggestion
/* Copyright 2019 Brandon Schlack
```

2020-09-23 17:03 UTC, Spaceman commented on keyboards/kingly_keys/romac/keymaps/brandonschlack/keymap.c
> +/* Copyright 2018 Jack Humbert
```suggestion
/* Copyright 2019 Brandon Schlack
```

2020-09-23 17:03 UTC, Spaceman commented on keyboards/nightmare/keymaps/brandonschlack/keymap.c
> +/* Copyright 2019 cfbender
```suggestion
/* Copyright 2019 Brandon Schlack
```

2020-09-23 17:03 UTC, Spaceman commented on layouts/community/60_ansi_split_bs_rshift/brandonschlack-split/keymap.c
> +/* Copyright 2018 Yiancar
```suggestion
/* Copyright 2019 Brandon Schlack
```

2020-09-23 17:05 UTC, Spaceman requested changes

2020-09-23 17:05 UTC, Spaceman commented on keyboards/mechlovin/adelais/keymaps/brandonschlack/keymap.c
> +/* Copyright 2020 Team Mechlovin
```suggestion
/* Copyright 2019 Brandon Schlack
```

2020-09-23 17:07 UTC, Spaceman requested changes

2020-09-23 17:07 UTC, Spaceman commented on keyboards/gray_studio/think65/solder/keymaps/brandonschlack/config.h
> +/* Copyright 2019 MechMerlin
```suggestion
/* Copyright 2019 Brandon Schlack
```

2020-10-04 21:02 UTC, drashna requested changes
Could you make sure that all of the `c` and `h` files have a GPL2+ compatible license header?

2020-10-04 21:02 UTC, drashna commented on layouts/community/65_ansi_blocker_split_bs/brandonschlack-split/keymap.c
> +};
```suggetion
```

2020-10-07 02:04 UTC, fauxpark requested changes

2020-10-07 02:04 UTC, fauxpark commented on keyboards/coseyfannitutti/discipline/keymaps/brandonschlack/keymap.c
> +    KC_LCTL, KC_LOPT, KC_LCMD,                            KC_SPC,                    KC_RCMD, PLY_FN1,          KC_LEFT, KC_DOWN, KC_RGHT  \
```suggestion
[_BASE] = LAYOUT_65_ansi_2_right_mods(
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_HOME,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_PGUP,
    HY_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGDN,
    KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_END,
    KC_LCTL, KC_LOPT, KC_LCMD,                            KC_SPC,                    KC_RCMD, PLY_FN1,          KC_LEFT, KC_DOWN, KC_RGHT
```

etc.

2020-10-07 21:57 UTC, drashna approved these changes

2020-11-05 05:22 UTC, noroadsleft approved these changes
Looks good to me.

Be advised that Maartenwut is rebranding as @evyd13, and the Wonderland (along with all other released Maartenwut boards) will be moving to a `keyboards/evyd13/` directory at the end of this month.

2020-11-05 05:55 UTC, merged

2020-11-05 05:58 UTC, noroadsleft commented
Thanks!