New keyboard: wsk/g4m3ralpha
qmk/qmk_firmware pull request #10431
Opened 2020-09-24 18:09 UTC by ridingqwerty

## Description

This keyboard is a variant of Alpha28 by PyroL with a partial numrow.
Submitted on behalf of Worldspawn00.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-26 23:39 UTC, zvecr requested changes

2020-09-26 23:39 UTC, zvecr commented on keyboards/wsk/g4m3ralpha/config.h
> +
```suggestion
```

2020-09-26 23:39 UTC, zvecr commented on keyboards/wsk/g4m3ralpha/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-09-26 23:39 UTC, zvecr commented on keyboards/wsk/g4m3ralpha/g4m3ralpha.c
> +#include "g4m3ralpha.h"
```suggestion
#include "g4m3ralpha.h"


void matrix_init_kb(void) {
    setPinOutput(D3);
    writePinLow(D3);
    setPinOutput(D2);
    writePinLow(D2);
    setPinOutput(D0);
    writePinLow(D0);

    matrix_init_user();
};

bool led_update_kb(led_t led_state) {
    bool res = led_update_user(led_state);
    if(res) {
        writePin(D3, led_state.num_lock);
        writePin(D0, led_state.caps_lock);
        writePin(D2, led_state.scroll_lock);
    }
    return res;
}
```

2020-09-26 23:39 UTC, zvecr commented on keyboards/wsk/g4m3ralpha/keymaps/default/keymap.c
> +}
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
    case _FN:
        writePinHigh(D3);
        writePinLow(D2);
        break;
    case _FNCHAR:
        writePinLow(D3);
        writePinHigh(D2);
        break;
    case _FKEYS:
        writePinHigh(D3);
        writePinHigh(D2);
        break;
    default: //  for any other layers, or the default layer
        writePinLow(D3);
        writePinLow(D2);
        break;
    }
  return state;
}

bool led_update_user(led_t led_state) {
    writePin(D0, led_state.caps_lock);
    return false;
}
```

2020-09-28 17:40 UTC, noroadsleft requested changes

2020-09-28 17:40 UTC, noroadsleft commented on keyboards/wsk/g4m3ralpha/config.h
> +#define PRODUCT_ID      0x6060
```suggestion
#define VENDOR_ID       0x5753  // "WS" - Worldspawn00
#define PRODUCT_ID      0x56D9
```

2020-09-28 17:40 UTC, noroadsleft commented on keyboards/wsk/g4m3ralpha/info.json
> +  "bootloader": "Catarina",
```suggestion
```

2020-09-29 01:43 UTC, fauxpark requested changes

2020-09-29 01:43 UTC, fauxpark commented on keyboards/wsk/g4m3ralpha/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = full     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-29 05:03 UTC, noroadsleft approved these changes

2020-10-01 22:57 UTC, zvecr approved these changes

2020-10-01 22:58 UTC, merged

2020-10-01 22:58 UTC, zvecr commented
Thanks!