Add smk65/revf support
qmk/qmk_firmware pull request #10434
Opened 2020-09-24 23:29 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-05 01:05 UTC, tzarc approved these changes

2020-10-07 01:50 UTC, fauxpark requested changes

2020-10-07 01:50 UTC, fauxpark commented on keyboards/lfkeyboards/smk65/keymaps/default/rules.mk
> +AUDIO_ENABLE = no              # Audio output on port C6
```suggestion
AUDIO_ENABLE = no              # Audio output
```

2020-10-07 01:50 UTC, fauxpark commented on keyboards/lfkeyboards/smk65/keymaps/default/rules.mk
> +RGBLIGHT_ENABLE = no           # Disable RGB underlight
```suggestion
RGBLIGHT_ENABLE = no           # Enable keyboard RGB underglow
```

2020-10-07 01:50 UTC, fauxpark commented on keyboards/lfkeyboards/smk65/keymaps/iso/rules.mk
> +RGBLIGHT_ENABLE = no           # Disable RGB underlight
```suggestion
AUDIO_ENABLE = no              # Audio output
RGBLIGHT_ENABLE = no           # Enable keyboard RGB underglow
```

2020-10-07 01:50 UTC, fauxpark commented on keyboards/lfkeyboards/smk65/revb/rules.mk
> +SRC = TWIlib.c issi.c lighting.c
```suggestion
SRC += TWIlib.c issi.c lighting.c
```

2020-10-08 20:28 UTC, fauxpark approved these changes
Can get rid of the kb.h stuff and `cbi`/`sbi`, otherwise LGTM

2020-10-08 20:37 UTC, drashna approved these changes

2020-10-08 20:58 UTC, merged