Add astro65
qmk/qmk_firmware pull request #10449
Opened 2020-09-26 04:42 UTC by swiftrax

## Description
Add handwired/swiftrax/astro65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-26 05:33 UTC, swiftrax commented
![image](https://user-images.githubusercontent.com/48102030/94331182-30084800-ff7f-11ea-81f1-3595da788075.png)

2020-09-26 19:24 UTC, zvecr requested changes

2020-09-26 19:24 UTC, zvecr commented on keyboards/handwired/swiftrax/astro65/config.h
> +
```suggestion

```

2020-09-26 19:24 UTC, zvecr commented on keyboards/handwired/swiftrax/astro65/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
This is the default right now so having the define doesnt add much value
```suggestion
```

2020-09-26 19:24 UTC, zvecr commented on keyboards/handwired/swiftrax/astro65/keymaps/via/keymap.c
> +  _______,   _______,_______,                _______,                       _______, _______,                           _______,_______,_______),
Should add 2 more blank layers here

2020-09-26 19:24 UTC, zvecr commented on keyboards/handwired/swiftrax/astro65/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-09-26 19:24 UTC, zvecr commented on keyboards/handwired/swiftrax/astro65/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-27 04:27 UTC, fauxpark approved these changes

2020-09-28 08:03 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/10449/files).

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/astro65.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_65_ansi_blocker_split_bs( \
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_65_ansi_blocker_split_bs": {
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/keymaps/default/keymap.c
> +[0] = LAYOUT(
```suggestion
[0] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/keymaps/default/keymap.c
> +[1] = LAYOUT(
```suggestion
[1] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/keymaps/via/keymap.c
> +[0] = LAYOUT(
```suggestion
[0] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/keymaps/via/keymap.c
> +[1] = LAYOUT(
```suggestion
[1] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/keymaps/via/keymap.c
> +[2] = LAYOUT(
```suggestion
[2] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/keymaps/via/keymap.c
> +[3] = LAYOUT(
```suggestion
[3] = LAYOUT_65_ansi_blocker_split_bs(
```

2020-09-28 08:03 UTC, noroadsleft commented on keyboards/handwired/swiftrax/astro65/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output

LAYOUTS = 65_ansi_blocker_split_bs
```

2020-09-29 01:44 UTC, fauxpark approved these changes

2020-09-29 05:07 UTC, noroadsleft commented
https://github.com/qmk/qmk_firmware/pull/10449#discussion_r495756252 still needs updating.

2020-09-29 10:02 UTC, noroadsleft approved these changes

2020-09-29 11:30 UTC, merged

2020-09-29 11:30 UTC, noroadsleft commented
Thanks!

2020-09-29 18:23 UTC, swiftrax commented
Thanks!