Add Unicode modes for `handwired/riblee_f401:riblee`
qmk/qmk_firmware pull request #10461
Opened 2020-09-27 14:33 UTC by riblee

## Description

This PR adds the ability to change Unicode input mode for `handwired/riblee_f401:riblee` so it works under Linux as well

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-27 22:02 UTC, zvecr requested changes

2020-09-27 22:02 UTC, zvecr commented on keyboards/handwired/riblee_f401/keymaps/riblee/config.h
> +
```suggestion

```

2020-09-28 09:17 UTC, fauxpark approved these changes

2020-09-29 04:48 UTC, noroadsleft approved these changes

2020-09-29 04:48 UTC, merged

2020-09-29 04:48 UTC, noroadsleft commented
Thanks!