Fix SPLIT_KEYBOARD compilation for ATMega*U2, which doesn't have VBUS/OTG control
qmk/qmk_firmware pull request #10460
Opened 2020-09-27 08:42 UTC by s-ol

in split_util.c a code block `#ifdef`'d for AVR deals with specific USB features that only ATMega*U4 support, compilation on U2 fails like this:

```
quantum/split_common/split_util.c:77:5: error: implicit declaration of function 'USB_OTGPAD_On'; did you mean 'USB_REG_On'? [-Werror=implicit-function-declaration]
   77 |     USB_OTGPAD_On();  // enables VBUS pad
      |     ^~~~~~~~~~~~~
      |     USB_REG_On
quantum/split_common/split_util.c:80:12: error: implicit declaration of function 'USB_VBUS_GetStatus' [-Werror=implicit-function-declaration]
   80 |     return USB_VBUS_GetStatus();  // checks state of VBUS
      |            ^~~~~~~~~~~~~~~~~~
```

## Description

This PR adjusts the ifdef to not attempt to use these facilities on ATmega16U2 and ATMega32U2 targets.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-27 09:02 UTC, fauxpark requested changes

2020-09-27 09:02 UTC, fauxpark commented on quantum/split_common/split_util.c
> +#elif defined(PROTOCOL_LUFA) && !(defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega32U2__))
```suggestion
#elif defined(PROTOCOL_LUFA) && defined(OTGPADE)
```

2020-09-27 09:03 UTC, fauxpark commented
Since this is a bug, it can probably go into master.

2020-09-27 19:17 UTC, s-ol commented on quantum/split_common/split_util.c
> +#elif defined(PROTOCOL_LUFA) && !(defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega32U2__))
Ok, adjusted :slightly_smiling_face:

2020-09-28 01:40 UTC, fauxpark approved these changes

2020-09-28 09:21 UTC, mtei approved these changes

2020-10-01 18:16 UTC, fauxpark commented
Thanks!

2020-10-01 18:17 UTC, merged