Rename commit
qmk/qmk_firmware pull request #10490
Opened 2020-09-30 10:32 UTC by yiancar

Last minute rename please 

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-30 22:19 UTC, tzarc approved these changes

2020-10-01 03:46 UTC, fauxpark requested changes

2020-10-01 03:46 UTC, fauxpark commented on keyboards/nebula68/config.h
> +#define DESCRIPTION     "A 68-percent, tool-free RGB keyboard"
```suggestion
```
Don't even need this, in fact.

2020-10-01 03:46 UTC, fauxpark commented on keyboards/nebula68/readme.md
>  # Nebula65
```suggestion
# Nebula68
```

2020-10-01 07:22 UTC, yiancar commented
Cheers!

2020-10-01 07:27 UTC, fauxpark approved these changes

2020-10-01 07:27 UTC, merged