[Keyboard] Add handwired F411
qmk/qmk_firmware pull request #10504
Opened 2020-10-01 22:20 UTC by riblee

## Description

Added a new Blackpill F411 based handwired keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-04 23:01 UTC, drashna approved these changes

2020-10-07 01:40 UTC, fauxpark requested changes

2020-10-07 01:40 UTC, fauxpark commented on keyboards/handwired/riblee_f411/keymaps/default/readme.md
> +# The default Preonic layout - largely based on the Planck's
This file can be deleted.

2020-10-07 01:40 UTC, fauxpark commented on keyboards/handwired/riblee_f411/README.md
> +# Handwired Preonic
Please rename this file to lowercase.

2020-10-07 08:57 UTC, riblee commented on keyboards/handwired/riblee_f411/keymaps/default/readme.md
> +# The default Preonic layout - largely based on the Planck's
Done

2020-10-07 08:57 UTC, riblee commented on keyboards/handwired/riblee_f411/README.md
> +# Handwired Preonic
Done

2020-10-27 13:02 UTC, riblee commented
Could somebody merge this PR please? I have some work going on which is depends on this.

2020-10-27 13:37 UTC, fauxpark requested changes
Just these two minor things, LGTM otherwise.

2020-10-27 13:37 UTC, fauxpark commented on keyboards/handwired/riblee_f411/keymaps/default/keymap.c
> +enum preonic_keycodes {
```suggestion
enum custom_keycodes {
```

2020-10-27 13:37 UTC, fauxpark commented on keyboards/handwired/riblee_f411/keymaps/default/keymap.c
> +enum preonic_layers {
```suggestion
enum layer_names {
```

2020-10-27 13:53 UTC, riblee commented on keyboards/handwired/riblee_f411/keymaps/default/keymap.c
> +enum preonic_keycodes {
I've changed them

2020-10-27 13:54 UTC, fauxpark approved these changes

2020-10-27 14:05 UTC, fauxpark commented
Thanks!
(Just waiting on Travis now)

2020-10-27 14:39 UTC, merged

2020-10-27 14:43 UTC, riblee commented
Thank you!