Clean LeftyNumpad code
qmk/qmk_firmware pull request #10500
Opened 2020-10-01 16:49 UTC by tomswartz07

## Description
Add new handwired keypad

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-01 17:33 UTC, tomswartz07 commented
Apologies for the noise on the PR, seems there was a minor conflict between how the tests ran and how the make process worked.

`make` worked fine, no issues, but the discrepancy between the layout was caught by the PR tests (yay PR tests!)

2020-10-01 22:31 UTC, zvecr requested changes

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/lefty-numpad.json
> +[
This file should be removed.

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/leftynumpad.c
> +*/
```suggestion
```

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/readme.md
> +A short description of the keyboard/project
This needs to be filled in, or removed

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/rules.mk
> +HD44780_ENABLE = no         # Enable support for HD44780 based LCDs
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/readme.md
> +* Hardware Availability: Links to where you can find this hardware
This should also be changed from the template defaults

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/config.h
> +
```suggestion

```

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/config.h
> +
```suggestion

```

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/config.h
> +// #define BOOTMAGIC_LITE_COLUMN 0
```suggestion
/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */

/* disable debug print */
//#define NO_DEBUG

/* disable print */
//#define NO_PRINT

/* disable action features */
//#define NO_ACTION_LAYER
//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT

/* disable these deprecated features by default */
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

/* Bootmagic Lite key configuration */
//#define BOOTMAGIC_LITE_ROW 0
//#define BOOTMAGIC_LITE_COLUMN 0
```

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/keymaps/default/config.h
> +/* Copyright 2020 Tom Swartz
This file should be removed

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/keymaps/default/keymap.c
> +                // when keycode QMKURL is released
```suggestion
```

2020-10-01 22:31 UTC, zvecr commented on keyboards/handwired/leftynumpad/keymaps/default/keymap.c
> +*/
```suggestion
```

2020-10-03 02:55 UTC, fauxpark requested changes

2020-10-03 02:55 UTC, fauxpark commented on keyboards/handwired/leftynumpad/readme.md
> +    make handwired/leftynumpad:default:flash
```suggestion
    make handwired/leftynumpad:default
```

2020-10-03 09:04 UTC, Erovia commented on keyboards/handwired/leftynumpad/readme.md
> +
If you have a picture/render of the board, this would be a fine place to showcase it.
See other keyboards.

2020-10-03 09:35 UTC, noroadsleft requested changes

2020-10-03 09:35 UTC, noroadsleft commented on keyboards/handwired/leftynumpad/info.json
> +                    {"label":"3,2", "x":3, "y":2},
These objects need to be in the same order that `keymap.c` uses.

```suggestion
                    {"label":"0,2", "x":0, "y":2},
                    {"label":"1,2", "x":1, "y":2},
                    {"label":"2,2", "x":2, "y":2},
                    {"label":"3,2", "x":3, "y":2},
                    {"label":"5,1", "x":4, "y":1, "h":2},
```

2020-10-03 09:35 UTC, noroadsleft commented on keyboards/handwired/leftynumpad/info.json
> +                    {"label":"3,4", "x":3, "y":4}
```suggestion
                    {"label":"0,4", "x":0, "y":4},
                    {"label":"1,4", "x":1, "y":4},
                    {"label":"2,4", "x":2, "y":4},
                    {"label":"3,4", "x":3, "y":4},
                    {"label":"4,3", "x":4, "y":3, "h":2}
```

2020-10-04 18:48 UTC, tomswartz07 commented
Thanks all for the feedback. There were a lot of items here which I didn't consider and seemed to be glossed over in the PR guide.


If you feel it's appropriate, I would be more than happy to make a PR to those docs as well to fill out the documentation there.

2020-10-04 22:30 UTC, drashna approved these changes

2020-10-07 01:42 UTC, fauxpark requested changes

2020-10-07 01:42 UTC, fauxpark commented on keyboards/handwired/leftynumpad/readme.md
> +![Image of LeftyNumpad](https://i.imgur.com/kkSPIxp.png)
```suggestion
![Image of LeftyNumpad](https://i.imgur.com/kkSPIxpl.png)
```

2020-10-07 02:16 UTC, fauxpark approved these changes

2020-10-07 22:35 UTC, merged