1 Oct 20
qmk/qmk_firmware pull request #10507
Opened 2020-10-01 23:43 UTC by AlisGraveNil

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-01 23:57 UTC, zvecr requested changes

2020-10-01 23:57 UTC, zvecr commented on keyboards/clawsome/fightpad/config.h
> +
```suggestion

```

2020-10-01 23:57 UTC, zvecr commented on keyboards/clawsome/fightpad/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-10-02 01:52 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/10507/files).

2020-10-02 01:52 UTC, noroadsleft commented on keyboards/clawsome/fightpad/config.h
> +#define PRODUCT_ID      0x0000
```suggestion
#define PRODUCT_ID      0x481C
```

2020-10-02 01:52 UTC, noroadsleft commented on keyboards/clawsome/fightpad/info.json
> +            "key_count": 12,
```suggestion
```

2020-10-02 01:52 UTC, noroadsleft commented on keyboards/clawsome/fightpad/info.json
> +    ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/"
```suggestion
```

2020-10-02 01:52 UTC, noroadsleft commented on keyboards/clawsome/fightpad/readme.md
> +* Hardware Supported: Los Numeros, Pro Micro, Elite-C
```suggestion
* Hardware Supported: FightPad; Pro Micro or Elite-C
```

2020-10-02 01:52 UTC, noroadsleft commented on keyboards/clawsome/fightpad/readme.md
> +* Hardware Availability: www.clawboards.xyz
```suggestion
* Hardware Availability: [Clawsome Boards](https://www.clawboards.xyz/)
```

2020-10-02 02:41 UTC, noroadsleft approved these changes

2020-10-02 03:37 UTC, fauxpark approved these changes

2020-10-02 05:53 UTC, merged

2020-10-02 05:53 UTC, noroadsleft commented
Thanks!