Add joestrong keymap for quefrency rev 2
qmk/qmk_firmware pull request #10503
Opened 2020-10-01 20:41 UTC by joestrong

## Description

Adds a UK ISO keymap for the 60% version of quefrency rev 2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-01 22:39 UTC, zvecr requested changes

2020-10-01 22:39 UTC, zvecr commented on keyboards/keebio/quefrency/keymaps/joestrong/keymap.c
> +#define _FN1 1
```suggestion
// Defines names for use in layer keycodes and the keymap
enum layer_names {
    _BASE,
    _FN1
};
```

2020-10-01 22:39 UTC, zvecr commented on keyboards/keebio/quefrency/keymaps/joestrong/keymap.c
> +
```suggestion
```

2020-10-02 01:26 UTC, noroadsleft requested changes

2020-10-02 01:26 UTC, noroadsleft commented on keyboards/keebio/quefrency/keymaps/joestrong/README.md
> +Function layer provides vim-like arrows and various function keys
Reads a bit easier.

```suggestion
* Standard UK ISO qwerty layout
* Function key in place of Caps Lock
* Function layer provides vim-like arrows and various function keys
```

2020-10-02 01:26 UTC, noroadsleft commented on keyboards/keebio/quefrency/keymaps/joestrong/keymap.c
> +#include QMK_KEYBOARD_H
This file should have a license header.

Here's a sample:

https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-02 07:10 UTC, joestrong commented
Requested changes resolved, plus indenting changed from 2 to 4 characters

2020-10-02 07:29 UTC, fauxpark approved these changes

2020-10-02 16:23 UTC, Erovia approved these changes

2020-10-02 16:26 UTC, merged

2020-10-02 16:26 UTC, Erovia commented
Thank you for your contribution!