Add Voyager60-Alps keyboard
qmk/qmk_firmware pull request #10516
Opened 2020-10-03 00:32 UTC by twalla

## Description

Add support for Voyager60-Alps

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-04 23:23 UTC, drashna requested changes

2020-10-04 23:23 UTC, drashna commented on keyboards/ai03/voyager60_alps/keymaps/default/keymap.c
> +}
```suggestion
```

2020-10-04 23:23 UTC, drashna commented on keyboards/ai03/voyager60_alps/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
AUDIO_ENABLE = no           # Audio output
```

2020-10-04 23:23 UTC, drashna commented on keyboards/ai03/voyager60_alps/voyager60_alps.c
> +}
```suggestion
```

2020-10-07 01:45 UTC, fauxpark requested changes

2020-10-07 01:45 UTC, fauxpark commented on keyboards/ai03/voyager60_alps/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
```

2020-10-07 01:45 UTC, fauxpark commented on keyboards/ai03/voyager60_alps/readme.md
> +Hardware Availability: [Gerbers](https://github.com/ai03-2725/Voyager60/tree/alps)
```suggestion
* Keyboard Maintainer: [ai03](https://github.com/ai03-2725)
* Hardware Supported: Voyager60-Alps PCB
* Hardware Availability: [Gerbers](https://github.com/ai03-2725/Voyager60/tree/alps)
```

2020-10-10 04:25 UTC, fauxpark approved these changes

2020-10-13 11:42 UTC, drashna approved these changes

2020-10-13 11:46 UTC, merged