Bm60rgb iso nordic keymap with sleepmode functional
qmk/qmk_firmware pull request #10510
Opened 2020-10-02 11:46 UTC by JakobST1n

## Description
This is an additional keymap for the bm60rgb_iso board.

- Better suited for nordic layouts
  - `KC_GRAVE` on second layer instead of having `KC_GESC` as that is problematic with nordic layout and macos. (grave giving `'`)
  - Button  right of `LSHIFT` is `KC_NUBS` as that follows the "norm".
- Some general modifications to layout
  - Right-shift has mod-tap with `KC_SLSH` as that button has a bit weird location on this board.
  - On the second layer the arrow cluster is media keys.
  - HJKL is home/end pg up/down on second layer (Nice for anyone used to vim).
  - Backspace is delete on second
  - numbers are function row.
- Also added a sleepmode function. This, separately from usb suspend and such, sets the rgb_matrix effects to a "sleep mode" when no keypresses have been detected for 10 minutes (default sleep effect is "off").

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-04 23:19 UTC, drashna requested changes

2020-10-04 23:19 UTC, drashna commented on keyboards/bm60rgb_iso/keymaps/iso_nordic_sleepmode/config.h
> +/*****************************
```suggestion
#pragma once

/*****************************
```

2020-10-07 23:33 UTC, drashna reviewed
the sleepmode appears to be the same or similar to `RGB_DISABLE_TIMEOUT` in the core feature.

https://docs.qmk.fm/#/feature_rgb_matrix?id=additional-configh-options

2020-10-07 23:33 UTC, drashna commented on keyboards/bm60rgb_iso/keymaps/iso_nordic_sleepmode/keymap.c
> +    #ifdef SLEEPMODE_ENABLE
This is a bit less verbose, easier to read, and formatted correctly. 
```suggestion
#if defined(RGB_MATRIX_ENABLE) && defined(SLEEPMODE_ENABLE)
```

2020-10-07 23:33 UTC, drashna commented on keyboards/bm60rgb_iso/keymaps/iso_nordic_sleepmode/keymap.c
> +    #endif
```suggestion
#endif
```

2020-10-07 23:33 UTC, drashna commented on keyboards/bm60rgb_iso/keymaps/iso_nordic_sleepmode/keymap.c
> +     #ifdef SLEEPMODE_ENABLE
```suggestion
#if defined(RGB_MATRIX_ENABLE) && defined(SLEEPMODE_ENABLE)
```

2020-10-07 23:33 UTC, drashna commented on keyboards/bm60rgb_iso/keymaps/iso_nordic_sleepmode/keymap.c
> +    #endif
```suggestion
#endif
```

2020-10-08 05:37 UTC, JakobST1n commented
> the sleepmode appears to be the same or similar to `RGB_DISABLE_TIMEOUT` in the core feature.
> 
> https://docs.qmk.fm/#/feature_rgb_matrix?id=additional-configh-options

It is kind of similar, but the added functionality of setting any animation mode on timeout. Rather that just off.
Might be better to add this functionality to core?
Although then I would have to read up on timers, as at least on my board I believe most of them are already in in use...

2020-10-13 11:59 UTC, drashna commented
Ah, okay.  

And no, there isn't.  But... maybe there should be, because I have something similar implemented in my userspace. :D

2020-10-13 12:01 UTC, drashna approved these changes
It looks like this needs a formatting pass, but otherwise, looks good.

2020-10-16 07:32 UTC, noroadsleft requested changes

2020-10-16 07:32 UTC, noroadsleft commented on keyboards/bm60rgb_iso/keymaps/iso_nordic_sleepmode/keymap.c
> +         _______, _______, _______,                      _______,                         _______, _______, KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK
No logic change; just makes this more readable.

```suggestion
         KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_DEL,
         _______, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, _______, _______, _______, _______,
         _______, _______, _______, _______, _______, _______, KC_HOME, KC_PGDN, KC_PGUP, KC_END,  _______, _______, _______, _______,
         _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_VOLD, KC_VOLU,
         _______, _______, _______,                      _______,                         _______, _______, KC_MPRV, KC_MPLY, KC_MNXT
```

2020-10-17 04:09 UTC, noroadsleft approved these changes

2020-10-17 04:29 UTC, merged

2020-10-17 04:29 UTC, noroadsleft commented
Thanks!