Moved s7_elephant and bear65 into 1 folder
qmk/qmk_firmware pull request #10528
Opened 2020-10-03 23:03 UTC by MudkipMao

Jacky, the designer of S7 Elephant and Bear 65 will have his own folder now, in the event that he runs more products in the future (which is likely).

## Description

The 2 boards are now moved into the folder jacky_studio/
I have checked with Jacky, and he is ok with this naming convention

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-04 00:11 UTC, zvecr requested changes
Keyboard moves are currently considered a "breaking change" and will need to target develop. Also build commands within readmes should be updated.

2020-10-06 03:07 UTC, MudkipMao commented
Holy moly, I did it right this time!

2020-10-07 23:58 UTC, drashna commented
> Holy moly, I did it right this time! I rebased my branch against develop

Glad to hear it!  And yeah, the first few times can be .... "fun".  After a while, you really git it down. :)

2020-10-08 00:00 UTC, drashna reviewed
Could you add a GPL2+ compatible license header to all of the `c` and `h` files? Including the keymap.c files? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-08 05:50 UTC, fauxpark requested changes

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/config.h
> +#define DESCRIPTION     A high-end 70% custom keyboard
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/keymaps/default/config.h
> +#define RGBLIGHT_LIMIT_VAL 80
```suggestion
#pragma once

#define RGBLIGHT_LIMIT_VAL 80
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/keymaps/default/keymap.c
> +}
```suggestion
bool led_update_user(led_t led_state) {
    // Turn LEDs On/Off for Caps Lock
    if (led_state.caps_lock) {
        rgblight_enable_noeeprom();
        rgblight_sethsv_noeeprom(0, 0, 80);
    } else {
        rgblight_sethsv_noeeprom(0, 0, 80);
        rgblight_disable_noeeprom();
    }
    return false;
}
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 75,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 71,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 71,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 75,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 74,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 72,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev1/rules.mk
> +#   comment out to disable the options.
```suggestion
#   change yes to no to disable
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev2/config.h
> +#define DESCRIPTION     A high-end 70% custom keyboard
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev2/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev2/rules.mk
> +FAUXCLICKY_ENABLE = no       # Use buzzer to emulate clicky switches
```suggestion
BLUETOOTH_ENABLE = no        # Enable Bluetooth
AUDIO_ENABLE = no            # Audio output
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev2/info.json
> +            "key_count": 73,
```suggestion
```

2020-10-08 05:50 UTC, fauxpark commented on keyboards/jacky_studio/s7_elephant/rev2/info.json
> +            "key_count": 75,
```suggestion
```

2020-10-14 02:50 UTC, fauxpark approved these changes

2020-10-15 11:35 UTC, drashna approved these changes

2020-11-28 21:11 UTC, MudkipMao commented
What's the current status of this? I had it ready to merge before, but now it's been closed and reopened. If I fix the conflicts, would this be ready to merge again?

2020-11-28 21:16 UTC, tzarc commented
We were in the process of merging the `develop` beach, which was accidentally deleted. We're in the process of reopening all closed PRs -- yours was one of about 80 accidentally closed.

2020-11-29 14:14 UTC, fauxpark commented
@MudkipMao yes, please rebase this PR, then it should be ready to merge next cycle.

2020-12-13 04:31 UTC, MudkipMao commented
I had to do a --force-with-lease to rebase into develop, but it should be ready to go now

2020-12-13 15:07 UTC, fauxpark approved these changes

2020-12-24 22:53 UTC, merged