own KBD67 MKII keymap
qmk/qmk_firmware pull request #10532
Opened 2020-10-04 09:37 UTC by cykedev

added own keymap

2020-10-04 23:45 UTC, drashna requested changes
could you add a GPL2+ license header to the config.h and keymap.c files?

2020-10-04 23:45 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/cykedev/config.h
> +#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
```suggestion
#pragma once

#undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
```

2020-10-05 08:11 UTC, cykedev commented
> could you add a GPL2+ license header to the config.h and keymap.c files?

done

2020-10-07 01:59 UTC, fauxpark approved these changes

2020-10-08 00:07 UTC, drashna commented
> done

I don't see any changes for it?  by chance, forgot to push the changes?

2020-10-08 05:09 UTC, cykedev commented
> > done
> 
> I don't see any changes for it? by chance, forgot to push the changes?

Ah I see I messed it up. Should be done now

2020-10-08 06:13 UTC, mrsendyyk approved these changes

2020-10-13 11:40 UTC, drashna approved these changes
LGTM, thanks!

2020-10-13 11:40 UTC, merged