Add infinity88 PCB
qmk/qmk_firmware pull request #10531
Opened 2020-10-04 05:53 UTC by mechlovin

## Description

Add Infinity88 Tenkeyless PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-04 23:44 UTC, drashna approved these changes

2020-10-20 15:52 UTC, mechlovin commented
bump

2020-10-20 16:18 UTC, fauxpark requested changes
Just a tiny typo here, otherwise LGTM

2020-10-20 16:18 UTC, fauxpark commented on keyboards/mechlovin/infinity88/rules.mk
> +RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow=
```suggestion
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
```

2020-10-21 04:20 UTC, fauxpark approved these changes

2020-10-23 02:55 UTC, merged