add support for sand ortholinear keyboard
qmk/qmk_firmware pull request #10543
Opened 2020-10-05 02:05 UTC by Sandpiper131

Add support for a 47 key ortholinear keyboard I designed

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-08 00:17 UTC, drashna commented on keyboards/sandortho/sandortho.c
> +*/
These aren't used, and can be removed.
```suggestion
```

2020-10-08 00:17 UTC, drashna commented on keyboards/sandortho/keymaps/default/keymap.c
> +   	KC_NO,     EXCL,     AT,      POUND,   DOLLAR,     PERCENT,   CARAT,        AND,        STAR,     LPAR,      RPAR,        KC_DELETE,
```suggestion
   	KC_NO,     KC_EXCL,     KC_AT,      KC_HASH,   KC_DLR,     KC_PERCENT,   KC_CIRC,        KC_AMP,        KC_ASTR,     KC_LPRN,      KC_RPRN,        KC_DELETE,               
```

2020-10-08 00:17 UTC, drashna commented on keyboards/sandortho/keymaps/default/keymap.c
> +	    break;
Just a heads up, most of these actually have dedicated keycodes. 

https://docs.qmk.fm/#/keycodes?id=us-ansi-shifted-symbols

And for the most part, they're just `LSFT(kc)`, actually.

```suggestion
```

2020-10-25 19:25 UTC, zvecr requested changes

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/keymaps/default/config.h
> +/* Copyright 2020 Luke LaCasse
This file should be deleted

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/keymaps/default/keymap.c
> +*/
```suggestion
```

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/readme.md
> +![sandortho](imgur.com image replace me!)
This should be filled in, or removed

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/sandortho.h
> +}
This abstract physical layout, and not require the end user to add a bunch of KC_NO in dead spots
```suggestion
#define LAYOUT( \
    k00, k01, k02, k03, k04, k05, k06, k07, k08, k09, k010, k011, \
      k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k110, k111, \
        k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k210, k211, \
	  k30, k31, k32, k33, k34,   k36,   k37, k38, k39, k310, k311 \
) \
{ \
    { k00, k01, k02, k03, k04, k05, k06, k07, k08, k09, k010, k011}, \
    { k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k110, k111},  \
    { k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k210, k211}, \
    { k30, k31, k32, k33, k34, KC_NO, k36, k37, k38, k39, k310, k311} \
}
```

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/sandortho.c
> +*/
```suggestion
```

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/rules.mk
> +
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/keymaps/default/keymap.c
> +    KC_NO,     KC_LCTRL, KC_LALT, KC_LGUI, MO(_LOWER), KC_NO,     KC_SPACE,     MO(_RAISE), KC_LEFT,  KC_DOWN,  KC_UP,       KC_RIGHT  //HC_NO before space is not a key in hardware
Same for the rest of the layers, these should be updated to the layout macro
```suggestion
    KC_NO,     KC_LCTRL, KC_LALT, KC_LGUI, MO(_LOWER), KC_SPACE,     MO(_RAISE), KC_LEFT,  KC_DOWN,  KC_UP,       KC_RIGHT
```

2020-10-25 19:25 UTC, zvecr commented on keyboards/sandortho/config.h
> +// #define BOOTMAGIC_LITE_COLUMN 0
```suggestion
/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */

/* disable debug print */
//#define NO_DEBUG

/* disable print */
//#define NO_PRINT

/* disable action features */
//#define NO_ACTION_LAYER
//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT

/* disable these deprecated features by default */
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

/* Bootmagic Lite key configuration */
//#define BOOTMAGIC_LITE_ROW 0
//#define BOOTMAGIC_LITE_COLUMN 0
```

2020-12-05 07:21 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/10543/files).

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/keymaps/default/keymap.c
> +}
Unused.

```suggestion
```

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/keymaps/default/keymap.c
> +    )/*,
- use short-form keycodes to make this easier to read
- remove an extra keycode from the `_RAISE` and `_LOWER` layers that prevented the keymap from being compiled

```suggestion
    [_BASE] = LAYOUT(
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,       KC_T,    KC_Y,    KC_U,       KC_I,    KC_O,    KC_P,    KC_BSPC,
        KC_ESC,  KC_A,    KC_S,    KC_D,    KC_F,       KC_G,    KC_H,    KC_J,       KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,       KC_B,    KC_N,    KC_M,       KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
        KC_NO,   KC_LCTL, KC_LALT, KC_LGUI, MO(_LOWER),     KC_SPC,       MO(_RAISE), KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT
    ),
    [_RAISE] = LAYOUT(
        KC_NO,   KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        KC_NO,   KC_4,    KC_5,    KC_6,    KC_0,    KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_MINS, KC_EQL,  KC_NO,
        KC_LSFT, KC_7,    KC_8,    KC_9,    KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        RESET,   KC_LCTL, KC_LALT, KC_LGUI, KC_NO,       KC_SPC,       KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO
    ),
    [_LOWER] = LAYOUT(
        KC_NO,   KC_EXCL, KC_AT,   KC_HASH, KC_DLR,  KC_PERC, KC_CIRC, KC_AMP,  KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL,
        KC_NO,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_BSLS, KC_LBRC, KC_RBRC,
        KC_LSFT, KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_LCTL, KC_LALT, KC_LGUI, KC_NO,       KC_SPC,       KC_NO,   KC_HOME, KC_PGDN, KC_PGUP, KC_END
    )/*,
```

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/readme.md
> +The sand ortholinear keyboard was inpired by silicon, the element used to make semiconductor materials. The keyboard has 47 keys laid out in an ortholinear grid with a 2U spacebar. The board can be a
Typo fixes.

```suggestion
The sand ortholinear keyboard was inspired by silicon, the element used to make semiconductor materials. The keyboard has 47 keys laid out in an ortholinear grid with a 2U spacebar. The board can be assembled with standoffs in between the backplate, the keyboard can be as short as 7.2mm tall (excluding switches and keycaps) or as tall as ~9.5mm with a 1/4" piece of acrylic sandwiched in between. I worked on this project from the end of July 2020 to September 2020.
```

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/readme.md
> +* Hardware Supported: ATMEGA32-U4
```suggestion
* Hardware Supported: ATmega32U4
```

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/sandortho.h
> +	  k30, k31, k32, k33, k34,   k36,   k37, k38, k39, k310, k311 \
Cleans up the spacing/indentation.

```suggestion
    k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k110, k111, \
    k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k210, k211, \
    k30, k31, k32, k33, k34,   k36,    k37, k38, k39, k310, k311 \
```

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/info.json
> +                {"label":"k36", "x":6, "y":3},{"label":"k37", "x":7, "y":3},{"label":"k38", "x":8, "y":3},{"label":"k39", "x":9, "y":3},{"label":"k310", "x":10, "y":3},{"label":"k311", "x":11, "y":3}
Bugfix for an extra object.

```suggestion
                {"label":"k30", "x":0, "y":3},{"label":"k31", "x":1, "y":3},{"label":"k32", "x":2, "y":3},{"label":"k33", "x":3, "y":3},{"label":"k34", "x":4, "y":3},
                {"label":"k36", "x":5, "y":3, "w":2},{"label":"k37", "x":7, "y":3},{"label":"k38", "x":8, "y":3},{"label":"k39", "x":9, "y":3},{"label":"k310", "x":10, "y":3},{"label":"k311", "x":11, "y":3}
```

2020-12-05 07:21 UTC, noroadsleft commented on keyboards/sandortho/config.h
> +
None of this is needed.

```suggestion
```

2021-02-21 22:23 UTC, closed without merging