Add nfriend's ErgoDox EZ keymap
qmk/qmk_firmware pull request #10545
Opened 2020-10-05 03:37 UTC by nfriend

## Description

Adds [nfriend](https://gitlab.com/nfriend)'s ErgoDox EZ keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-05 08:07 UTC, drashna requested changes

2020-10-05 08:07 UTC, drashna commented on keyboards/ergodox_ez/keymaps/nfriend/keymap.c
> +#define MISC 13
We generally recommend using enums for layer names. As well as prepending them with underscores. 

```suggestion
enum layer_names {
    COLEMAK,
    QWERTY,
    DVORAK,
    COMMON,
    MAC,
    WINDOWS,
    NUMPAD,
    SYMBOLS,
    WM_MAC,
    WM_WINDOWS,
    ARROWS_MAC,
    ARROWS_WINDOWS,
    MISC,
};
```

2020-10-05 08:07 UTC, drashna commented on keyboards/ergodox_ez/keymaps/nfriend/keymap.c
> +    EPRM,
This isn't needed, as you can use `EEP_RST` for this, as it's a core code.
```suggestion
```

2020-10-05 08:07 UTC, drashna commented on keyboards/ergodox_ez/keymaps/nfriend/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2020-10-05 08:07 UTC, drashna commented on keyboards/ergodox_ez/keymaps/nfriend/rules.mk
> +UNICODEMAP_ENABLE = false
```suggestion
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
```

2020-10-05 13:34 UTC, nfriend commented
@drashna Thanks for all the suggestions, they are much appreciated! 😄 

I applied all of your suggestions; please let me know if there are any other changes I need to make.

Back to you 🏓

2020-10-08 00:50 UTC, drashna reviewed
Just a heads, if you only need to switch the alt/gui/control mods, bootmagic may be a better way to do that. 

https://docs.qmk.fm/#/feature_bootmagic?id=keycodes

And even if bootmagic isn't enabled, these keycodes still work.

2020-11-05 02:20 UTC, noroadsleft approved these changes

2020-11-15 18:57 UTC, drashna approved these changes

2020-11-15 18:57 UTC, merged