adds eosti/planck keymaps
qmk/qmk_firmware pull request #10565
Opened 2020-10-06 18:59 UTC by eosti

## Description

Adds the eosti/planck keymap. This keymap has a number of features, such as HJKL navigation, MacOS navigation shortcuts, and tmux navigation macros. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-08 02:55 UTC, drashna requested changes

2020-10-08 02:55 UTC, drashna commented on keyboards/planck/keymaps/eosti/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-08 02:55 UTC, drashna commented on keyboards/planck/keymaps/eosti/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-08 05:56 UTC, fauxpark approved these changes

2020-10-11 21:01 UTC, eosti commented
Ah, nuts, I now see why keeping my PR on a different branch is a good idea.

2020-10-11 21:01 UTC, closed without merging