Make via config for redox_w
qmk/qmk_firmware pull request #10578
Opened 2020-10-08 15:25 UTC by harshitgoel96

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-09 19:16 UTC, zvecr requested changes
I might be missing something, but the keymap doesnt seem to provide a way to access layers 1-3

2020-10-09 19:16 UTC, zvecr commented on keyboards/redox_w/keymaps/via/keymap.c
> +  * With permission form jpconstantineau, the original maintainer of the Ergo Travel hardware.
```suggestion
  * With permission from jpconstantineau, the original maintainer of the Ergo Travel hardware.
```

2020-10-16 05:12 UTC, drashna approved these changes

2020-10-16 05:37 UTC, fauxpark approved these changes

2020-10-16 22:59 UTC, noroadsleft approved these changes

2020-10-16 23:01 UTC, merged

2020-10-16 23:01 UTC, noroadsleft commented
Thanks!