Add support for ikki68
qmk/qmk_firmware pull request #10576
Opened 2020-10-08 07:45 UTC by spbgzh

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Keyboard firmware after change again

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-08 12:50 UTC, zvecr commented
<https://github.com/qmk/qmk_firmware/pull/10569#pullrequestreview-504298308>

Again, please stop making new PRs, and just accept the changes to the same branch. Tracking these changes is becoming a real pain.

2020-10-08 14:32 UTC, spbgzh commented
> [#10569 (review)](https://github.com/qmk/qmk_firmware/pull/10569#pullrequestreview-504298308)
> 
> Again, please stop making new PRs, and just accept the changes to the same branch. 
> Sorry i didn't see the message, I will not do it again.

2020-10-08 14:34 UTC, spbgzh commented
Sorry, this is my first firmware submission.😂

2020-10-13 04:16 UTC, ridingqwerty requested changes
Whitespace touchup in the readme

2020-10-13 04:16 UTC, ridingqwerty commented on keyboards/wuque/ikki68/readme.md
> +More Info at[wuquestudio](https://shop.wuquestudio.com/).
```suggestion
More Info at [wuquestudio](https://shop.wuquestudio.com/).
```

2020-10-16 04:54 UTC, drashna approved these changes

2020-10-16 15:11 UTC, ridingqwerty approved these changes

2020-10-18 20:51 UTC, drashna approved these changes

2020-10-18 20:52 UTC, merged