Add IDOBAO ID87.
qmk/qmk_firmware pull request #10577
Opened 2020-10-08 11:33 UTC by mehoron

## Description

Adding the ID87 board support to QMK repository as well as adding VIA support. This is a keyboard sold through IDOBAO and utilizes a YMDK PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-10 13:15 UTC, sigprof requested changes

2020-10-10 13:15 UTC, sigprof commented on keyboards/id87/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
Please update this to match [`quantum/template/avr/readme.md`](https://github.com/qmk/qmk_firmware/blob/master/quantum/template/avr/readme.md) (maybe you used an older version of template).

You could probably drop the `?variant=33990062604419` part from the URL.

2020-10-10 16:29 UTC, mehoron commented on keyboards/id87/id87.h
> +	      K101, K102,       K104, K105, K106, K107, K108  \
I don't have the json file for it yet, I'll try to get a hold of it. I just received a base firmware. I'll do what I can to fix it up. Thanks for taking a look.

2020-10-10 17:00 UTC, sigprof commented
I found the ID87 definition at http://mtkeyboard.vip/: open that page (be patient, the site loads really slow), select the “id87” button, then click “SETTINGS” below the keyboard area, scroll down and click the yellow button with Chinese text below the “Save your layout” label — you will get `id87.json`. Upload that JSON to https://noroadsleft.github.io/kbf_qmk_converter/, and you will get usable id87.h and keymap.c from there (just adjust the macro name to `LAYOUT_tkl_ansi`).

2020-10-10 21:08 UTC, mehoron commented on keyboards/id87/config.h
> +#define RGBLED_NUM 30
The number of LEDs is 22 16 on the bottom and 6 on the top.

2020-10-10 21:09 UTC, mehoron commented
Thanks for the help @sigprof I redid the layouts. Let me know if there is anything else I need to update.

2020-10-11 01:48 UTC, mehoron commented on keyboards/id87/keymaps/default/keymap.c
> +		KC_RGHT, KC_DOWN, KC_RSFT, KC_SLSH, KC_LEFT, KC_DOT, KC_COMM
Updated to use LT(1, KC_APP) instead. Verified it worked correctly with a few online key-testers.  (Still doesn't work in VIA).

2020-10-11 01:49 UTC, mehoron commented on keyboards/id87/keymaps/default/keymap.c
> +                ),
Removed the empty layers from the default keymap.

2020-10-11 01:54 UTC, mehoron commented on keyboards/id87/keymaps/default/keymap.c
> +                _______, BL_DEC, _______, _______, _______, _______, _______
Added default RGB commands back. Added additional commands and moved around the default

2020-10-16 05:08 UTC, drashna approved these changes

2020-10-16 05:36 UTC, fauxpark requested changes

2020-10-16 05:36 UTC, fauxpark commented on keyboards/id87/info.json
> +            "key_count": 87,
```suggestion
```

2020-10-16 05:36 UTC, fauxpark commented on keyboards/id87/readme.md
> +*A TKL hotswap board from IDOBAO*
```suggestion
A TKL hotswap board from IDOBAO.
```

2020-10-16 05:36 UTC, fauxpark commented on keyboards/id87/readme.md
> +:
```suggestion
Flashing example for this keyboard:

```

2020-10-16 05:36 UTC, fauxpark commented on keyboards/id87/rules.mk
> +LAYOUTS = tkl_ansi
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output

LAYOUTS = tkl_ansi
```

2020-10-17 08:58 UTC, noroadsleft requested changes

2020-10-17 08:58 UTC, noroadsleft commented on keyboards/id87/info.json
> +    ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/"
I don't need you to shill for me. :)

```suggestion
```

2020-10-17 09:58 UTC, fauxpark approved these changes

2020-10-18 23:16 UTC, merged