Addpersonal userspace and maps
qmk/qmk_firmware pull request #10581
Opened 2020-10-08 23:42 UTC by draevin

## Description

Includes:
- Add `draevin` userspace (Hey, that's me!)
- Add keymaps for my current boards:
  - Keeb.io Sinc (80)
  - Keeb.io Quefrency (65 w/ macro)
  - DZ60

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-09 19:10 UTC, zvecr commented
You will want to add copyright headers to all the `*.c` and `*.h` file you have added.

2020-10-09 21:10 UTC, draevin commented
So, I was curious about that, specifically in regards to the files in the `users/draevin` directory. The [Userspace](https://beta.docs.qmk.fm/using-qmk/software-features/feature_userspace#readme-readme-md) portion of the docs specifically calls out for the license to be included in the readme but does not explicitly call for it in the other files. I did see some examples of that pattern without blocks in the associated `*.c` and `*.h` files, as well as at least one example of a separate `LICENSE` file which is a pattern I know is sometimes followed for repos. I did, however, include copyright blocks for all source files outside of `users/draevin` where they are not accompanied by the license. 

Ultimately I'm asking: is the `LICENSE` file in `users/draevin` not sufficient for the other files therein? On the other side of that, if I were to add the blocks in the associated `*.c` and `*.h` files, would that `LICENSE` or (or in line with the docs, a license in the readme) then become superfluous? I'm willing to follow whatever the established pattern is, but docs and existing examples seemed inconsistent so I was unsure. Thanks for any clarification you can provide.

2020-10-10 02:43 UTC, fauxpark requested changes

2020-10-10 02:43 UTC, fauxpark commented on users/draevin/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2020-10-10 02:43 UTC, fauxpark commented on users/draevin/draevin.c
> +                tap_code(KC_ENT);
```suggestion
                SEND_STRING("make " QMK_KEYBOARD ":" QMK_KEYMAP ":flash\n");
```

2020-10-10 05:04 UTC, fauxpark approved these changes

2020-10-16 05:15 UTC, drashna approved these changes
LGTM

2020-10-16 22:04 UTC, noroadsleft commented
> Ultimately I'm asking: is the `LICENSE` file in `users/draevin` not sufficient for the other files therein? On the other side of that, if I were to add the blocks in the associated `*.c` and `*.h` files, would that `LICENSE` or (or in line with the docs, a license in the readme) then become superfluous? I'm willing to follow whatever the established pattern is, but docs and existing examples seemed inconsistent so I was unsure. Thanks for any clarification you can provide.

I actually raised this question internally a week or two ago, and the feedback I got was that including a `LICENSE` file isn't sufficient because it's possible for the source code to become separated from the corresponding license file. Having the header in the file prevents this separation.

2020-10-16 23:06 UTC, draevin commented
I figured that was the intent with having the header localized to the file; thanks for the clarification @noroadsleft 

I'll go ahead and add them, and assume it's fine to remove the separate `LICENSE` as it would seem redundant at that point.

2020-10-16 23:10 UTC, skullydazed commented
For some more background GNU covers this issue in their FAQ- [Is it enough just to put a copy of the GNU GPL in my repository?](https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly) The next question is relevant as well- [Why should I put a license notice in each source file?](https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile)

2020-10-18 23:20 UTC, drashna requested changes

2020-10-18 23:20 UTC, drashna commented on users/draevin/rules.mk
> +MOUSEKEY_WHEEL_TIME_TO_MAX = 64
This doesn't do anything.  These need to be set in the `config.h`

```suggestion
```

2020-10-18 23:20 UTC, drashna commented on users/draevin/draevin.h
> +#define TAPPING_TERM 150
These must be in the `config.h`
```suggestion
```

2020-10-23 02:44 UTC, drashna approved these changes

2020-10-23 02:44 UTC, drashna commented
Thanks!

2020-10-23 02:46 UTC, merged