Add miniMACRO5 User Keymaps
qmk/qmk_firmware pull request #10595
Opened 2020-10-10 10:45 UTC by dezlidezlidezli

## Description

Add user keymaps for the miniMACRO5. These were programmed by me, but are designed by and requested by people who joined my recent group-buy for this macropad. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2020-10-16 05:27 UTC, drashna requested changes

2020-10-16 05:27 UTC, drashna commented on keyboards/minimacro5/keymaps/kabraxcis/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-16 05:27 UTC, drashna commented on keyboards/minimacro5/keymaps/voaraq/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-17 16:28 UTC, fauxpark approved these changes

2020-10-17 19:15 UTC, noroadsleft approved these changes

2020-10-17 19:16 UTC, merged

2020-10-17 19:16 UTC, noroadsleft commented
Thanks!