50-qmk.rules: Move udev rules from documentation into a file
qmk/qmk_firmware pull request #10664
Opened 2020-10-16 18:47 UTC by Foxboron

This makes it overall easier to package for downstream distributions
instead of keeping tabs with inline documentation.

Signed-off-by: Morten Linderud <morten@linderud.pw>

2020-10-16 19:22 UTC, Erovia approved these changes

2020-10-17 01:02 UTC, fauxpark requested changes

2020-10-17 01:02 UTC, fauxpark commented on docs/faq_build.md
> +On Linux, you'll need proper privileges to communicate with the bootloader device. You can either use `sudo` when flashing firmware, or place a udev rules file in [`/etc/udev/rules.d/50-qmk.rules`](h
```suggestion
On Linux, you'll need proper privileges to communicate with the bootloader device. You can either use `sudo` when flashing firmware (not recommended), or place [this file](https://github.com/qmk/qmk_firmware/tree/master/util/udev/50-qmk.rules) into `/etc/udev/rules.d/`.
```

2020-10-17 09:56 UTC, fauxpark approved these changes

2020-10-17 17:55 UTC, zvecr approved these changes

2020-10-17 17:55 UTC, zvecr commented
Thanks!

2020-10-17 19:30 UTC, merged