adds eosti/maypad keymap
qmk/qmk_firmware pull request #10663
Opened 2020-10-16 18:43 UTC by eosti

## Description
Adds eosti/maypad layout. Pretty standard layout, only with a tap-danced mod layer that has a few commonly used mathematical special functions. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-16 20:04 UTC, zvecr requested changes

2020-10-16 20:04 UTC, zvecr commented on keyboards/keyhive/maypad/keymaps/eosti/readme.md
> +#EosTi's Maypad Layout
```suggestion
# EosTi's Maypad Layout
```

2020-10-16 20:04 UTC, zvecr commented on keyboards/keyhive/maypad/keymaps/eosti/keymap.c
> +}
```suggestion
```

2020-10-17 01:03 UTC, fauxpark approved these changes

2020-10-17 09:30 UTC, noroadsleft approved these changes

2020-10-17 09:31 UTC, merged

2020-10-17 09:31 UTC, noroadsleft commented
Thanks!