Enabled the use of VIA for KPRepublic BM40
qmk/qmk_firmware pull request #10677
Opened 2020-10-17 12:34 UTC by strawy

## Description
Enabled the use of VIA for KPRepublic BM40

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

Enabled the use of VIA for KPRepublic BM40

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-17 16:13 UTC, fauxpark requested changes

2020-10-17 16:13 UTC, fauxpark commented on keyboards/bm40hsrgb/config.h
> +#define PRODUCT         KPRepublic BM40 Hotswap RGB
```suggestion
#define PRODUCT         BM40 Hotswap RGB
```

2020-10-18 02:11 UTC, noroadsleft approved these changes

2020-10-18 04:06 UTC, fauxpark requested changes

2020-10-18 04:06 UTC, fauxpark commented on keyboards/bm40hsrgb/config.h
> +#define PRODUCT_ID      0x3430
```suggestion
#define PRODUCT_ID      0x3430 // "40"
```
Just for clarity.

2020-10-18 07:36 UTC, fauxpark approved these changes

2020-10-18 07:36 UTC, fauxpark commented
Thanks!

2020-10-18 07:36 UTC, merged