Roadster
qmk/qmk_firmware pull request #10698
Opened 2020-10-20 03:03 UTC by AlisGraveNil

This is a 40% style keyboard with 44 keys

All new keyboard

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-23 03:48 UTC, drashna approved these changes

2020-10-23 03:59 UTC, fauxpark requested changes

2020-10-23 03:59 UTC, fauxpark commented on keyboards/clawsome/roadster/config.h
> +#define DESCRIPTION     QMK Firmware: Roadster1.0
```suggestion
```

2020-10-23 03:59 UTC, fauxpark commented on keyboards/clawsome/roadster/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth with the Adafruit EZ-Key HID
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
```

2020-10-24 16:44 UTC, fauxpark approved these changes

2020-10-24 18:16 UTC, zvecr approved these changes

2020-10-24 18:17 UTC, merged

2020-10-24 18:17 UTC, zvecr commented
Thanks!