[Keyboard] Added Crazy Keyboard 68
qmk/qmk_firmware pull request #10693
Opened 2020-10-19 15:05 UTC by chent7

## Description

Added files for Crazy Keyboard 68 from taobao. Everything tested working except for caps lock led (see keyboard.c).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-23 03:41 UTC, drashna approved these changes

2020-10-25 00:11 UTC, zvecr requested changes

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/crazy_keyboard_68.c
> +	led_init_ports();
```suggestion
	led_init_ports();
	
	matrix_init_user();
```

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/keymaps/default/keymap.c
> +    [_FN] = LAYOUT(
```suggestion
    [_FN] = LAYOUT_65_ansi(
```

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_65_ansi(
```

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/info.json
> +            "key_count": 68,
```suggestion
        "LAYOUT_65_ansi": {
```

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/crazy_keyboard_68.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_65_ansi( \
```

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output

LAYOUTS = 65_ansi
```

2020-10-25 00:11 UTC, zvecr commented on keyboards/crazy_keyboard_68/rules.mk
> +RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow
```suggestion
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
```

2020-10-29 08:25 UTC, fauxpark approved these changes

2020-11-08 04:27 UTC, noroadsleft requested changes
Just this, please.

2020-11-08 04:27 UTC, noroadsleft commented on keyboards/crazy_keyboard_68/config.h
> +#define PRODUCT_ID   0x6060
```suggestion
#define PRODUCT_ID   0x13DE
```

2020-11-08 16:45 UTC, chent7 commented on keyboards/crazy_keyboard_68/config.h
> +#define PRODUCT_ID   0x6060
done :+1:

2020-11-10 05:06 UTC, noroadsleft approved these changes

2020-11-10 05:06 UTC, merged

2020-11-10 05:07 UTC, noroadsleft commented
Thanks!