Add definition based on currently-selected serial driver.
qmk/qmk_firmware pull request #10716
Opened 2020-10-21 22:56 UTC by tzarc

## Description

Adds a `#define` based on the currently selected serial driver, so that preprocessor can be used to modify functionality in code.
Djinn has a serial driver based off the normal `serial_usart.c`, but adds arbitrary data transfer from master to slave and back.
Would be useful if I could determine which serial driver was in use from `users/` and modify my user area's functionality accordingly.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-21 23:14 UTC, zvecr requested changes
We can make it work per ws2812 here

2020-10-21 23:14 UTC, zvecr commented on common_features.mk
>          SERIAL_DRIVER ?= bitbang
```suggestion
        SERIAL_DRIVER ?= bitbang
        OPT_DEFS += -DSERIAL_DRIVER_$(strip $(shell echo $(SERIAL_DRIVER) | tr '[:lower:]' '[:upper:]'))
```

2020-10-21 23:14 UTC, zvecr commented on common_features.mk
> +            OPT_DEFS += -DSERIAL_DRIVER_bitbang
```suggestion
```

2020-10-21 23:14 UTC, zvecr commented on common_features.mk
> +            OPT_DEFS += -DSERIAL_DRIVER_$(strip $(SERIAL_DRIVER))
```suggestion
```

2020-10-21 23:59 UTC, tzarc commented
> 
> 
> We can make it work per ws2812 here

Perfect.

2020-10-22 17:37 UTC, zvecr approved these changes

2020-10-22 17:37 UTC, zvecr commented
:tada:

2020-10-22 17:37 UTC, merged