Minor typo in comments Colemak DM-MK -> DH-MK
qmk/qmk_firmware pull request #10721
Opened 2020-10-22 07:49 UTC by AvdN

## Description

The Colemak base mod is named after swapping D and H from next to the base row.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

N/A

2020-10-22 17:47 UTC, zvecr requested changes
Needs sign off from keyboard author @finex before we can merge

2020-12-10 10:54 UTC, finex commented
Hi, the keymap is quite outdated. I've to push a new release of my keymap. Thanks for the fix, I've already fixed on my branch! :-)

2020-12-23 07:43 UTC, drashna approved these changes

2021-02-07 16:37 UTC, drashna approved these changes

2021-03-26 12:37 UTC, fauxpark approved these changes

2021-03-26 12:37 UTC, merged