Add Hannah65-RGB PCB Rev.1
qmk/qmk_firmware pull request #10748
Opened 2020-10-24 16:28 UTC by mechlovin

## Description

Add Hannah65-RGB PCB rev.1
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-29 06:12 UTC, drashna approved these changes

2020-10-29 06:18 UTC, drashna commented
Because this moves around different keyboard folders and their locations, please target develop.  You may need to rebase this after you've done so.

2020-11-10 05:30 UTC, tzarc requested changes
Just some minor stuff to do with the PR checklist.

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/rgb_led/config.h
> +#pragma once
Please add a copyright header here.

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/rgb_led/rev1/config.h
> +#pragma once
Please add a copyright header here.

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/standard_led/config.h
> +#pragma once
Please add a copyright header here.

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/standard_led/mechlovin9/config.h
> +#pragma once
Please add a copyright header here.

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/rgb_led/rules.mk
> +
```suggestion
```

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/standard_led/rev1/keymaps/default/keymap.c
> +
```suggestion
```

2020-11-10 05:30 UTC, tzarc commented on keyboards/mechlovin/hannah65/standard_led/rev1/keymaps/via/keymap.c
> +
```suggestion
```

2020-11-12 22:02 UTC, fauxpark approved these changes

2020-12-04 01:34 UTC, drashna commented
Looks like you have a merge conflict here.

2020-12-10 06:22 UTC, mechlovin commented
I don't see conflict here, can you tell me?
I will correct it. Thank you

2020-12-10 07:33 UTC, fauxpark commented
![image](https://user-images.githubusercontent.com/4781841/101735538-29b55100-3b16-11eb-86ff-10c7344f6f74.png)

2020-12-11 03:23 UTC, mechlovin commented
@fauxpark @drashna hi guy, is it ok?
I don't have much experience using github. Thanks for your help

2020-12-23 07:30 UTC, drashna commented
This should cover how to update stuff: https://docs.qmk.fm/#/newbs_git_resolving_merge_conflicts

2020-12-24 23:12 UTC, drashna commented
If possible, any folder that requires the `DEFAULT_FOLDER` to compile should have the `.noci` file in it, to prevent the CI from trying to compile the same keyboard revision multiple times.

2020-12-25 02:50 UTC, mechlovin commented
> If possible, any folder that requires the `DEFAULT_FOLDER` to compile should have the `.noci` file in it, to prevent the CI from trying to compile the same keyboard revision multiple times.


Thank you, this is new to me.
I thought my computer had a problem when I first saw the .noci file :D

2020-12-30 02:44 UTC, drashna commented
The `.noci` is ***very*** new.  It was added a week or so ago, actually, and it is to prevent duplicate folders from being compiled.  This way, we can drastically speed up the Travis CI runs, so they stop timing out due to running too long.  And it has definitely helped!

2020-12-30 02:47 UTC, drashna commented
Lint isn't happy, not sure if that's critical, @yanfali @Erovia ?

2021-01-17 00:23 UTC, noroadsleft commented
@drashna That lint check fails because not all of the revision folders have readme files. I believe the lint check expects a `readme.md` file in every keyboard folder that has a `rules.mk`. Not a deal-breaker IMO; the link check should probably be updated, rather than the codebase.

2021-01-17 04:01 UTC, noroadsleft requested changes

2021-01-17 04:01 UTC, noroadsleft commented on keyboards/mechlovin/hannah65/rgb_led/rev1/rules.mk
> +DEFAULT_FOLDER = mechlovin/hannah65/rgb_led/rev1
This line isn't needed.

```suggestion
```

2021-02-20 06:36 UTC, mechlovin commented
PCB has faulty part in hardware design, RGB matrix is ​​faulty due to not complying with datasheet, some red LEDs blink when using RGB_MATRIX_KEYPRESSES and RGB_MATRIX_KEYRELEASES.
Q9, page 6. 
https://github.com/UltimateHackingKeyboard/datasheets/blob/master/leds/IS31FL3731%20Application%20Note%20Rev.C.pdf

2021-02-20 06:37 UTC, mechlovin commented
I will close this PR and open another PR, use another LED driver.
Thank you for support!

2021-02-20 06:37 UTC, closed without merging