Beegboy
qmk/qmk_firmware pull request #10762
Opened 2020-10-25 19:34 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-25 20:33 UTC, swiftrax commented
![image](https://user-images.githubusercontent.com/48102030/97118331-b753f300-16c6-11eb-80dd-b438bb3dd8f8.png)

2020-10-29 05:56 UTC, drashna approved these changes

2020-10-29 05:58 UTC, fauxpark requested changes

2020-10-29 05:58 UTC, fauxpark commented on keyboards/handwired/swiftrax/beegboy/config.h
> +//#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```suggestion
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2020-10-29 18:22 UTC, fauxpark approved these changes

2020-11-01 00:12 UTC, zvecr approved these changes

2020-11-01 00:13 UTC, merged

2020-11-01 00:13 UTC, zvecr commented
Thanks!