olligranlund keymap updates for DZ60 and Keebio/Iris
qmk/qmk_firmware pull request #10760
Opened 2020-10-25 15:48 UTC by OlliGranlund

I've reworked my keymaps for both Iris and DZ60. 

### DZ60
I created a new keymap for my second DZ60 board which has a different layout than my first one. Added VIA support.

### Keebio/Iris
I created a new keymap for the rebuild of my Iris board. This layout differs to some extent from the original and tries to be more inline with any normal 60% ISO keyboard. Added VIA support.

## Description

The changes done are only keymap changes to keymaps which I've uploaded earlier.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-25 16:24 UTC, zvecr commented
In its current form, this PR cannot be accepted due to the submodule changes in `lib/vusb`.

2020-10-25 17:19 UTC, OlliGranlund commented
I guess I had an too old version of qmk fork, merged now from upstream latest master

2020-10-25 17:50 UTC, zvecr commented
![image](https://user-images.githubusercontent.com/16520359/97114780-78d02f80-16ea-11eb-9add-c13d48af8226.png)

Still no good.

2020-10-25 18:16 UTC, OlliGranlund commented
Updated all the submodules with this command:

`git submodule foreach git pull origin master`

2020-10-25 18:34 UTC, zvecr commented
Now you have `lib/googletest` and `lib/lufa` changes

2020-10-26 07:26 UTC, OlliGranlund commented
Apparently updating the submodules turned out to be trickier than I expected... Where do we have stated which versions of the submodules should be used? I redownloaded QMK and replaced the lib-folder with the latest generated by qmk, but still running into the same issue...

Any hints on how I should proceed?

2020-10-26 21:06 UTC, OlliGranlund commented
Got some help from QMK discord to cleanup the repo, no changes to git submodules anymore :)

2020-10-29 05:48 UTC, drashna requested changes

2020-10-29 05:48 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-10-29 05:48 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +extern keymap_config_t keymap_config;
This is not needed.
```suggestion
```

2020-10-29 05:48 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +#define _ADJUST 16
Should use an enum for this:
```suggestion
enum layers (
    _QWERTY,
    _LOWER,
    _RAISE
    _ADJUST,
};
```

2020-10-29 05:48 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +}
```suggestion
```

2020-11-15 19:32 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic/config.h
> +#define MASTER_LEFT
Technically, this isn't required, as it's the default behavior.

2020-11-15 19:32 UTC, drashna approved these changes

2020-12-05 17:23 UTC, noroadsleft approved these changes

2020-12-05 17:31 UTC, noroadsleft requested changes
Actually, you need this:

2020-12-05 17:31 UTC, noroadsleft commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +    _RAISE
Fixing two typos; this keymap doesn't compile without these fixes.

```suggestion
enum layers {
    _QWERTY,
    _LOWER,
    _RAISE,
```

2020-12-06 17:57 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +#define KC_ KC_TRNS
This should be removed, as it doesn't appear to be used. 
```suggestion
```

2020-12-24 23:29 UTC, drashna requested changes

2020-12-24 23:29 UTC, drashna commented on keyboards/handwired/neito/config.h
> +#define VENDOR_ID       0x2602
This vendor ID is already in use. 
https://www.the-sz.com/products/usbid/index.php?v=0x2602&p=&n=

```
❯ echo -n "Oliver Granlund" | shasum | cut -c1-4 | tr '[:lower:]' '[:upper:]'   
B9F7
```

```suggestion
#define VENDOR_ID       0xB9F7
```
Or if you want to use ascii
```suggestion
#define VENDOR_ID       0x4F47 // "OG"
```

2020-12-24 23:29 UTC, drashna commented on keyboards/keebio/iris/keymaps/olligranlund_nordic_v2/keymap.c
> +			break;
This isn't needed, since you only have the one default layer. 
```suggetion
```

2020-12-25 10:03 UTC, closed without merging