Add via keymap to E6.5
qmk/qmk_firmware pull request #10771
Opened 2020-10-26 09:32 UTC by bintobean

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-26 09:39 UTC, fauxpark requested changes

2020-10-26 09:39 UTC, fauxpark commented on keyboards/exclusive/e65/keymaps/via/keymap.c
> +    [0] = LAYOUT_65_ansi_noblocker(
These should be `LAYOUT_all`.

2020-10-26 09:39 UTC, fauxpark commented on keyboards/exclusive/e65/keymaps/via/keymap.c
> +}
```suggestion
```

2020-10-26 09:39 UTC, fauxpark commented on keyboards/exclusive/e65/config.h
> +#define PRODUCT_ID   0xE605 // E6.5
```suggestion
#define VENDOR_ID    0x4558 // "EX"
#define PRODUCT_ID   0xE605 // E6.5
```

2020-10-27 05:40 UTC, fauxpark approved these changes

2020-10-29 06:55 UTC, drashna approved these changes

2020-10-29 07:00 UTC, merged