Hnah108 refactor
qmk/qmk_firmware pull request #10787
Opened 2020-10-28 19:33 UTC by fauxpark

## Description

```
☒ keyboards/handwired/hnah108/hnah108.h: LAYOUT_fullsize_iso: Nested layout macro detected. Matrix data not available!
```

@vuhopkep

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-29 08:02 UTC, drashna requested changes

2020-10-29 08:02 UTC, drashna commented on keyboards/handwired/hnah108/hnah108.c
> +led_config_t g_led_config = {
```suggestion
#ifdef RGB_MATRIX_ENABLE
led_config_t g_led_config = {
```

2020-10-29 08:02 UTC, drashna commented on keyboards/handwired/hnah108/hnah108.c
> +};
```suggestion
};
#endif
```

2020-10-29 08:02 UTC, drashna commented on keyboards/handwired/hnah108/readme.md
> +![hnah108](https://i.imgur.com/rV0lM8M.jpg)
```suggestion
![hnah108](https://i.imgur.com/rV0lM8Ml.jpg)
```

2020-10-29 08:07 UTC, fauxpark commented on keyboards/handwired/hnah108/hnah108.c
> +led_config_t g_led_config = {
Whoops

2020-10-29 08:31 UTC, drashna approved these changes

2020-10-30 01:02 UTC, zvecr approved these changes

2020-10-30 11:06 UTC, merged