added to handwired pill60
qmk/qmk_firmware pull request #10798
Opened 2020-10-30 03:56 UTC by IktaS

I added Pill60 firmware to handwired folder.

## Description

I added Pill60 firmware to handwired folder.

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-01 20:02 UTC, drashna requested changes
Looks good, minus a couple of things

2020-11-01 20:02 UTC, drashna commented on keyboards/handwired/pill60/config.h
> +#define DESCRIPTION "QMK keyboard firmware for Pill60"
This isn't used, and should be removed
```suggestion
```

2020-11-01 20:02 UTC, drashna commented on keyboards/handwired/pill60/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-11-01 20:02 UTC, drashna commented on keyboards/handwired/pill60/pill60.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-11-01 20:02 UTC, drashna commented on keyboards/handwired/pill60/readme.md
> +![Pill60](https://i.imgur.com/7WmHa6m.png)
```suggestion
![Pill60](https://i.imgur.com/7WmHa6ml.png)
```

2020-11-01 20:36 UTC, fauxpark requested changes

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/info.json
> +            "key_count": 63,
```suggestion
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/keymaps/default/keymap.c
> +        KC_TRNS,  KC_TRNS,  KC_TRNS,                     KC_TRNS,                                KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS \
```suggestion
    [_BL] = LAYOUT(
        KC_F1,
        KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSLS, KC_DEL,
        KC_TAB,  KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC,   KC_BSPC,
        KC_LCTL,  KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,    KC_ENT,
        KC_RSFT,   KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,    KC_LSFT, MO(_FL),
        MO(_FL),  KC_LGUI,  KC_LALT,               KC_SPC,                KC_RALT, KC_RGUI, MO(_FL), KC_RCTL
    ),
    [_FL] = LAYOUT(
        KC_TRNS,
        KC_GRV,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11, KC_F12, KC_PSCR, KC_INS,
        KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS,   KC_TRNS,
        KC_CAPS,  KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT,    KC_TRNS,
        KC_TRNS,  KC_HOME, XXXXXXX, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, XXXXXXX, KC_END,    KC_TRNS, KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS,                     KC_TRNS,                                KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/pill60.h
> +#include "led.h"
```suggestion
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/blackpill_f401/rules.mk
> +DFU_SUFFIX_ARGS = -v 0483 -p df11
```suggestion
# MCU name
MCU = STM32F401

# Options to pass to dfu-util when flashing
DFU_ARGS = -d 0483:DF11 -a 0 -s 0x08000000:leave
DFU_SUFFIX_ARGS = -v 0483 -p DF11
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/blackpill_f411/rules.mk
> +DFU_SUFFIX_ARGS = -v 0483 -p df11
```suggestion
# MCU name
MCU = STM32F411

# Options to pass to dfu-util when flashing
DFU_ARGS = -d 0483:DF11 -a 0 -s 0x08000000:leave
DFU_SUFFIX_ARGS = -v 0483 -p DF11
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/blackpill_f411/rules.mk
> +KEYBOARD_SHARED_EP       = yes
```suggestion
KEYBOARD_SHARED_EP = yes
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/bluepill/bootloader_defs.h
> +#define STM32_BOOTLOADER_ADDRESS 0x80000000
This file should be deleted.

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/bluepill/rules.mk
> +
```suggestion
# Bootloader selection
BOOTLOADER = stm32duino
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/blackpill_f401/config.h
> +
```suggestion
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/config.h
> +#define VENDOR_ID 0x4454
```suggestion

#include "config_common.h"

#define VENDOR_ID 0x4454
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/bluepill/config.h
> +
```suggestion
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/blackpill_f411/config.h
> +
```suggestion
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = yes      # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
BACKLIGHT_DRIVER = software
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
OLED_DRIVER_ENABLE = yes
ENCODER_ENABLE = yes
```

2020-11-01 20:36 UTC, fauxpark commented on keyboards/handwired/pill60/keymaps/default/readme.md
> +
```suggestion
![Pill60 Layout Image](https://i.imgur.com/86mrAwZ.png)

```

2020-11-02 08:15 UTC, fauxpark approved these changes

2020-11-09 17:56 UTC, drashna requested changes

2020-11-09 17:56 UTC, drashna commented on keyboards/handwired/pill60/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-11-15 19:40 UTC, drashna approved these changes

2020-11-15 19:40 UTC, merged