Update massdrop/alt and arm_atsam/led_matrix to fix #10813
qmk/qmk_firmware pull request #10818
Opened 2020-10-31 23:34 UTC by cmerrill

## Description

This PR makes the following three changes:
- Updates the custom LED matrix handling code in `tmk_core/protocol/arm_atsam/led_matrix.c` to only change the appearance of the CapsLock key if the LED_FLAG_INDICATOR flag is set.
- Updates the `keyboard/massdrop/alt/config_led.c` file to correctly call out all of the modifier keys on the keyboard (in the same style as on massdrop/ctrl) and to add the additional "INDICATOR" flag to the CapsLock key for use as an indicator. I am not entirely sure if this is the *right* way to deal with using a key LED as an indicator, but it was the closest to the current implementation.
- Updates the `keyboard/massdrop/alt/keymaps/default/keymap.c` file to correctly set the "MODIFIER" and "INDICATOR" flags as enabled when cycling between RGB lighting for All/Keys Only/Underglow Only/None. 

In general, I tried to make minimal changes while still implementing the fix. 

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #10813 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-01 06:53 UTC, fauxpark reviewed
Does this also need to be done for the CTRL?

2020-11-01 18:19 UTC, cmerrill commented
This should likely also be done for the CTRL, but I don't have a keyboard to verify the changes.

I've pushed the equivalent CTRL changes to my branch (it is implemented for both the Caps Lock and Scroll Lock options on the CTRL). The CTRL seemed to have this already partially, but not entirely, implemented.

2020-11-01 20:22 UTC, fauxpark requested changes
@ash0x0 @MatthewRobo @XScorpion2 if one of you could test out the CTRL side of things here?

2020-11-01 20:22 UTC, fauxpark commented on keyboards/massdrop/ctrl/keymaps/default/keymap.c
> +                case LED_FLAG_KEYLIGHT | LED_FLAG_MODIFIER | LED_FLAG_INDICATOR: {
```suggestion
                case (LED_FLAG_KEYLIGHT | LED_FLAG_MODIFIER | LED_FLAG_INDICATOR): {
```

2020-11-02 00:35 UTC, drashna approved these changes

2020-11-02 00:40 UTC, XScorpion2 approved these changes

2020-11-02 00:42 UTC, ash0x0 approved these changes
LGTM. No visible changes for CTRL as this wasn't an issue at least for me.

2020-11-02 16:33 UTC, fauxpark approved these changes

2020-11-09 21:30 UTC, noroadsleft approved these changes

2020-11-09 21:33 UTC, merged

2020-11-09 21:33 UTC, noroadsleft commented
Thanks!