Add support for Noxary Vulcan
qmk/qmk_firmware pull request #10822
Opened 2020-11-01 05:13 UTC by ai03-2725

## Description

Adds support for the Vulcan by Noxary Keyboards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for Noxary Vulcan

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-01 06:51 UTC, fauxpark requested changes

2020-11-01 06:51 UTC, fauxpark commented on keyboards/noxary/vulcan/readme.md
> +![Vulcan](https://i.imgur.com/ZwlJ0sx.png)
```suggestion
![Vulcan](https://i.imgur.com/ZwlJ0sxl.png)
```

2020-11-01 06:51 UTC, fauxpark commented on keyboards/noxary/vulcan/readme.md
> +Hardware Availability: [Noxary Webstore](https://noxary.co/)
```suggestion
* Keyboard Maintainer: [ai03](https://github.com/ai03-2725)/Noxary Keyboards
* Hardware Supported: The Vulcan PCB
* Hardware Availability: [Noxary Webstore](https://noxary.co/)
```

2020-11-01 06:51 UTC, fauxpark commented on keyboards/noxary/vulcan/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
AUDIO_ENABLE = no           # Audio output
```

2020-11-01 14:49 UTC, fauxpark approved these changes

2020-11-02 00:46 UTC, drashna approved these changes

2020-11-02 13:44 UTC, fauxpark commented
Thanks!

2020-11-02 13:45 UTC, merged