XD68: add 65_ansi_split_bs layuout
qmk/qmk_firmware pull request #10835
Opened 2020-11-02 11:31 UTC by owestend

XD68 support also a split backspace.

## Description

What I did:
- add macro ```LAYOUT_65_ansi_split_bs``` to ```xd68.h```
- add this layout also to ```info.json```
- add this layout also to ``LAYOUTS``` in ```rules.mk```

What I **not** did:
- I did **not** add the additional key to ```LAYOUT_all```
- I did **not** change any other layout

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-02 13:28 UTC, fauxpark requested changes

2020-11-02 13:28 UTC, fauxpark commented on keyboards/xd68/info.json
> +            "key_count": 68,
```suggestion
```

2020-11-02 15:47 UTC, fauxpark requested changes

2020-11-02 15:47 UTC, fauxpark commented on keyboards/xd68/info.json
> +            "key_count": 69,
```suggestion
```

2020-11-03 00:58 UTC, fauxpark approved these changes

2020-11-09 07:53 UTC, owestend commented
What else can I do to get these changes accepted?

2020-11-10 05:22 UTC, noroadsleft approved these changes

2020-11-10 05:24 UTC, noroadsleft commented
> What else can I do to get these changes accepted?

In my case, I was busy with non-QMK stuff and I fell behind on my PR reviews. Sorry for that.

But looks good, thanks!

2020-11-10 05:26 UTC, merged

2020-11-10 07:54 UTC, owestend commented
Thanks!