[Docs] Japanese translation of feature_rawhid.md
qmk/qmk_firmware pull request #10858
Opened 2020-11-04 19:57 UTC by umi-umi

## Description

Add Japanese translation of docs/feature_rawhid.md.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-05 08:00 UTC, mtei commented
@shelaf @s-show @hsgw @satt99 @takashiski @yoshihara よかったらレビューお願いします。

2020-11-06 05:01 UTC, hsgw requested changes

2020-11-06 05:01 UTC, hsgw commented on docs/ja/feature_rawhid.md
> +言うまでもなく、使っているライブラリに関係なく、終了したらインタフェースを必ずインタフェースを閉じる必要があります。オペレーティングシステムと特定の環境によっては、明示的に接続が閉じられていない場合、後で他のクライアントまたは同じクライアントの他のインスタンスに再接続する時に問題が発生する可能性があります。
```suggestion
言うまでもなく、使っているライブラリに関係なく、終了したらインタフェースを必ず閉じる必要があります。オペレーティングシステムと特定の環境によっては、明示的に接続が閉じられていない場合、後で他のクライアントまたは同じクライアントの他のインスタンスに接続しなおした時に問題が発生する可能性があります。
```

2020-11-08 04:17 UTC, shelaf commented on docs/ja/feature_rawhid.md
> +Vendor ID と Product ID はデバイスを開くために実際には必要ないことに注意してください。それらは接続した多くの HID デバイスから特定のデバイスをフィルターするためだけに使われます。多くのライブラリでは、代わりに製品名と製造元名を使ってデバイスを開くオプションがあります。`node-hid` が代表的な例です。これは USB ハブが組み込まれているデバイスや、同じ製品名また
designationはdestinationと間違えて翻訳されている？
```suggestion
Vendor ID と Product ID はデバイスを開くために実際には必要ないことに注意してください。それらは接続した多くの HID デバイスから特定のデバイスをフィルターするためだけに使われます。多くのライブラリでは、代わりに製品名と製造元名を使ってデバイスを開くオプションがあります。`node-hid` が代表的な例です。これは USB ハブが組み込まれているデバイスや、同じ製品名または同じ製造元の複数のインタフェースがある特別な HID インタフェースで問題になります。Product ID と Vendor ID を合わせると単一のインタフェースの固有名を作成できるため、この問題を防げます。したがって、ライブラリで必要が無い場合でも、この問題を防ぐためにそれらを使うことをお勧めします。
```

2020-11-08 13:07 UTC, umi-umi commented on docs/ja/feature_rawhid.md
> +Vendor ID と Product ID はデバイスを開くために実際には必要ないことに注意してください。それらは接続した多くの HID デバイスから特定のデバイスをフィルターするためだけに使われます。多くのライブラリでは、代わりに製品名と製造元名を使ってデバイスを開くオプションがあります。`node-hid` が代表的な例です。これは USB ハブが組み込まれているデバイスや、同じ製品名また
ご指摘ありがとうございます。
まさに、その読み間違いをしていました。

2020-11-08 13:12 UTC, shelaf approved these changes

2020-11-09 14:52 UTC, s-show commented on docs/ja/feature_rawhid.md
> +`"raw_hid.h"` ヘッダは、キーボードからホストにパケットを送信できる `void raw_hid_send(uint8_t *data, uint8_t length);` も宣言します。例として、全てのデータをホストに返すことでホストアプリケーションを構築する時にデバッグをするために使うこともできます。
2番目の文の長さを考えると、句読点がもう1つ必要かなと思いますので、次の訳はどうでしょうか？
```suggestion
`"raw_hid.h"` ヘッダは、キーボードからホストにパケットを送信できる `void raw_hid_send(uint8_t *data, uint8_t length);` も宣言します。例として、全てのデータをホストに返すことで、ホストアプリケーションを構築する時のデバッグに使うこともできます。
```

2020-11-09 22:53 UTC, s-show approved these changes

2020-11-16 13:39 UTC, hsgw approved these changes

2021-01-01 18:08 UTC, mtei approved these changes

2021-01-01 18:12 UTC, mtei commented
I think this is ready to merge.

umi\-umi さん、その他のレビュアーの皆さん、大変お待たししました。_o_

2021-01-06 05:08 UTC, merged

2021-01-06 05:08 UTC, mtei commented
Thanks!