Added wilba.tech WT65-H1
qmk/qmk_firmware pull request #10880
Opened 2020-11-07 13:57 UTC by Wilba6582

## Description

Added wilba.tech WT65-H1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-16 01:07 UTC, drashna approved these changes

2020-11-18 20:11 UTC, noroadsleft requested changes

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/info.json
> +        "LAYOUT_all": {
This is one of our Community Layouts.

```suggestion
        "LAYOUT_65_ansi_blocker_tsangan": {
```

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/keymaps/default/keymap.c
> +	[0] = LAYOUT_all(
```suggestion
	[0] = LAYOUT_65_ansi_blocker_tsangan(
```

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/keymaps/default/keymap.c
> +	[1] = LAYOUT_all(
```suggestion
	[1] = LAYOUT_65_ansi_blocker_tsangan(
```

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/keymaps/default/keymap.c
> +	[2] = LAYOUT_all(
```suggestion
	[2] = LAYOUT_65_ansi_blocker_tsangan(
```

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/keymaps/default/keymap.c
> +	[3] = LAYOUT_all(
```suggestion
	[3] = LAYOUT_65_ansi_blocker_tsangan(
```

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output

LAYOUTS = 65_ansi_blocker_tsangan
```

2020-11-18 20:11 UTC, noroadsleft commented on keyboards/wilba_tech/wt65_h1/wt65_h1.h
> +#define LAYOUT_all( \
```suggestion
// This is equivalent to LAYOUT_all
#define LAYOUT_65_ansi_blocker_tsangan( \
```

2020-11-25 21:26 UTC, noroadsleft approved these changes

2020-11-25 21:26 UTC, merged

2020-11-25 21:27 UTC, noroadsleft commented
Thanks!