add unsplit
qmk/qmk_firmware pull request #10892
Opened 2020-11-08 19:20 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-08 19:24 UTC, swiftrax commented
![image](https://user-images.githubusercontent.com/48102030/98482238-e6815e80-21b4-11eb-8a1c-f78f3230e49e.png)

2020-11-16 01:27 UTC, drashna requested changes

2020-11-16 01:27 UTC, drashna commented on keyboards/handwired/swiftrax/unsplit/config.h
> +#define DESCRIPTION     A 44 key fixed split keyboard
```suggestion
```

2020-11-17 05:10 UTC, drashna approved these changes

2020-11-18 09:52 UTC, fauxpark approved these changes

2020-11-18 18:19 UTC, Erovia requested changes

2020-11-19 19:29 UTC, Erovia approved these changes

2020-11-19 19:29 UTC, merged