Allow APM32 MCUs on certain CannonKeys PCBs
qmk/qmk_firmware pull request #10899
Opened 2020-11-09 05:30 UTC by awkannan

## Description

Allow APM32 MCUs on certain CannonKeys PCBs
We'll do this by removing the DFU suffix which locks in the firmware to just STM32 device ids.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-16 21:12 UTC, drashna commented
Didn't we want `FFFF` for the VID/PID combo, as this seems to work with dfu-util?

2020-11-19 19:32 UTC, awkannan commented
Yup, I haven't had a chance to update my PRs since that convo - I will make the changes

2020-12-02 19:18 UTC, zvecr requested changes

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/an_c/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/db60/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/devastatingtkl/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/instant60/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/instant65/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/obliterated75/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/rekt1800/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/satisfaction75/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/savage65/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 19:18 UTC, zvecr commented on keyboards/cannonkeys/tmov2/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```

2020-12-02 22:06 UTC, zvecr approved these changes

2020-12-04 02:20 UTC, drashna approved these changes

2020-12-04 02:22 UTC, merged