Add M4cs Keymap for dekunukem/duckyPad
qmk/qmk_firmware pull request #10900
Opened 2020-11-09 06:06 UTC by M4cs

This is a pull request containing my keymap for the duckyPad by @dekunukem. Includes 3 layers w/ RGB settings as well.

## Description

- Adds keymap for duckypad
- Adds dekunukem/duckypad folder

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-16 21:19 UTC, drashna requested changes

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/config.h
> +#define DESCRIPTION Open Source Keypad
```suggestion
```

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/duckypad.c
> +#include "duckypad.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/duckypad.c
> +#include "rgb_matrix.h"
This shouldn't be needed, if quantum.h is included in the keyboard's header file, properly. 
```suggestion
```

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/duckypad.c
> +#include "stdio.h"
Not sure that this is needed. 

```suggestion
```

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/duckypad.c
> +    rgb_matrix_toggle_noeeprom();
```suggestion
#ifdef RGB_MATRIX_ENABLE
    rgb_matrix_toggle_noeeprom();
#endif
```

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/duckypad.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/keymaps/m4cs/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
#pragma once
```

The rest shouldn't be needed if console isn't enabled. 
And needs a license header.

2020-11-16 21:19 UTC, drashna commented on keyboards/dekunukem/duckypad/keymaps/m4cs/rules.mk
> +EXTRAFLAGS += -flto
The above LTO_ENABLE adds this. Not needed here.
```suggestion
```

2020-11-17 03:23 UTC, M4cs commented
Made changes based on your comments. All have been resolved.

2020-11-17 05:04 UTC, drashna approved these changes

2020-11-18 09:24 UTC, fauxpark requested changes
This board is missing a default keymap.

2020-11-18 09:24 UTC, fauxpark commented on keyboards/dekunukem/duckypad/info.json
> +            "key_count": 17,
```suggestion
```

2020-11-18 09:24 UTC, fauxpark commented on keyboards/dekunukem/duckypad/keymaps/m4cs/rules.mk
> +
```suggestion
```

2020-11-18 09:24 UTC, fauxpark commented on keyboards/dekunukem/duckypad/rules.mk
> +OLED_DRIVER_ENABLE = yes
```suggestion
# MCU name
MCU = STM32F072

BOARD = ST_STM32F072B_DISCOVERY

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output

# TODO: Can we get this working with SPI?
RGB_MATRIX_ENABLE = WS2812
WS2812_DRIVER = bitbang

OLED_DRIVER_ENABLE = yes
```

2020-11-18 09:24 UTC, fauxpark commented on keyboards/dekunukem/duckypad/readme.md
> +* Hardware Supported: All duckyPad Revisions
```suggestion
* Hardware Supported: All duckyPad Revisions

Make example for this keyboard (after setting up your build environment):

    make dekunukem/duckypad:default

Flashing example for this keyboard:

    make dekunukem/duckypad:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

```

2020-11-18 16:43 UTC, M4cs commented
@fauxpark I've made changes to resolve your comments. Thank you :)

2020-11-18 21:39 UTC, zvecr requested changes

2020-11-18 21:39 UTC, zvecr commented on keyboards/dekunukem/duckypad/config.h
> +#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2
These values are not valid for I2Cv2, if needing to reconfigure you will require <https://docs.qmk.fm/#/i2c_driver?id=i2cv2>
```suggestion
```

2020-11-18 21:42 UTC, zvecr requested changes

2020-11-18 21:42 UTC, zvecr commented on keyboards/dekunukem/duckypad/bootloader_defs.h
> +/*
This file should be removed

2020-11-18 21:42 UTC, zvecr commented on keyboards/dekunukem/duckypad/rules.mk
> +BOARD = ST_STM32F072B_DISCOVERY
```suggestion
```

2020-11-19 11:00 UTC, fauxpark requested changes

2020-11-19 11:00 UTC, fauxpark commented on keyboards/dekunukem/duckypad/keymaps/default/keymap.c
> +    Z9, Z10, Z11, \
```suggestion
    Z0 = SAFE_RANGE, Z1, Z2,
    Z3, Z4, Z5,
    Z6, Z7, Z8,
    Z9, Z10, Z11,
```

2020-11-19 11:00 UTC, fauxpark commented on keyboards/dekunukem/duckypad/keymaps/m4cs/keymap.c
> +    Z9, Z10, Z11, \
```suggestion
    Z0 = SAFE_RANGE, Z1, Z2,
    Z3, Z4, Z5,
    Z6, Z7, Z8,
    Z9, Z10, Z11,
```

2020-11-19 11:00 UTC, fauxpark commented on keyboards/dekunukem/duckypad/readme.md
> +```
```suggestion
    make dekunukem/duckypad:default
```

2020-11-19 11:00 UTC, fauxpark commented on keyboards/dekunukem/duckypad/readme.md
> +```
```suggestion
    make dekunukem/duckypad:default:flash
```

2020-11-19 11:00 UTC, fauxpark commented on keyboards/dekunukem/duckypad/rules.mk
> +#	change no to yes to enable
```suggestion
```

2020-11-19 11:00 UTC, fauxpark commented on keyboards/dekunukem/duckypad/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-19 16:45 UTC, M4cs commented
@fauxpark Thanks for the suggested changes. I've gone ahead and fixed up my files.

2020-11-19 16:49 UTC, fauxpark requested changes

2020-11-19 16:49 UTC, fauxpark commented on keyboards/dekunukem/duckypad/readme.md
> +
```suggestion
    make dekunukem/duckypad:default

Flashing example for this keyboard:

    make dekunukem/duckypad:default:flash
```

2020-11-19 16:49 UTC, fauxpark commented on keyboards/dekunukem/duckypad/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-19 16:49 UTC, fauxpark commented on keyboards/dekunukem/duckypad/readme.md
> +
```suggestion
```

2020-11-19 16:54 UTC, fauxpark requested changes

2020-11-19 16:54 UTC, fauxpark commented on keyboards/dekunukem/duckypad/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-20 17:16 UTC, M4cs commented
Is my build failing due to other keyboards or is it mine?

2020-11-21 03:48 UTC, fauxpark commented
The former, but you can rebase this branch onto current master to make Travis build only this board.

2020-11-21 03:49 UTC, fauxpark approved these changes

2020-11-21 19:37 UTC, M4cs commented
> The former, but you can rebase this branch onto current master to make Travis build only this board.

Thanks! Merged qmk upstream master into my branch, should fix the issue :)

2020-11-23 19:32 UTC, zvecr requested changes

2020-11-23 19:32 UTC, zvecr commented on keyboards/dekunukem/duckypad/duckypad.c
> +    writePinHigh(A0);
```suggestion
    writePinHigh(A0);
    
    keyboard_pre_init_user();
```

2020-11-23 19:32 UTC, zvecr commented on keyboards/dekunukem/duckypad/keymaps/default/config.h
> +
```suggestion
#pragma once

```

2020-11-23 19:32 UTC, zvecr commented on keyboards/dekunukem/duckypad/keymaps/m4cs/config.h
> +
```suggestion
#pragma once

```

2020-11-23 20:59 UTC, M4cs commented
Fixed thanks @zvecr +1

2020-11-24 13:46 UTC, zvecr approved these changes

2020-11-24 13:46 UTC, merged

2020-11-24 13:46 UTC, zvecr commented
Thanks!