Add domnantas lily58 keymap
qmk/qmk_firmware pull request #10910
Opened 2020-11-10 18:37 UTC by domnantas

## Description
Add my keymap for lily58

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-16 23:00 UTC, drashna requested changes

2020-12-13 17:18 UTC, domnantas commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +#include QMK_KEYBOARD_H
Thanks for review! Added

2020-12-13 19:16 UTC, domnantas commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +#include <stdio.h>
On [Line 250](https://github.com/qmk/qmk_firmware/pull/10910/files#diff-e82b5668f3ef95f8d1fdbb28e76f516e5203eed4e9ddabff1ffe3c6db2a863d7R250) `sprintf` is used. `oled_write_ln(get_current_wpm(), false);` didn't compile. Error thrown:

```
Compiling: keyboards/lily58/keymaps/domnantas/keymap.c                                             keyboards/lily58/keymaps/domnantas/keymap.c: In function ‘render_status’:
keyboards/lily58/keymaps/domnantas/keymap.c:251:19: error: passing argument 1 of ‘oled_write_ln’ makes pointer from integer without a cast [-Werror=int-conversion]
     oled_write_ln(get_current_wpm(), false);
                   ^
In file included from quantum/quantum.h:166:0,
                 from keyboards/lily58/rev1/rev1.h:5,
                 from keyboards/lily58/lily58.h:4,
                 from keyboards/lily58/keymaps/domnantas/keymap.c:17:
drivers/oled/oled_driver.h:214:6: note: expected ‘const char *’ but argument is of type ‘uint8_t {aka unsigned char}’
 void oled_write_ln(const char *data, bool invert);
      ^
cc1: all warnings being treated as errors
```

I tried typecasting like this:
```c
oled_write_ln((char) get_current_wpm(), false)
```
but that didn't work either. I'm not familiar with C enough to figure out what's wrong.

2020-12-14 02:07 UTC, fauxpark commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +#include <stdio.h>
You'll need to print `get_current_wpm()` into a string first, then pass that to `oled_write_ln()`.

2020-12-14 02:11 UTC, fauxpark requested changes

2020-12-14 02:11 UTC, fauxpark commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +                                KC_LGUI, KC_LALT, MO(_LOWER), KC_SPC,  KC_ENT,  KC_BSPC, MO(_RAISE), KC_DEL \
```suggestion
    [_QWERTY] = LAYOUT(
        KC_ESC,   LT_A_OG, LT_C_CA, LT_E_OG, LT_E_DO, LT_I_OG,                  LT_S_CA, LT_U_OG, LT_U_MA, KC_9,    KC_0,    LT_Z_CA,
        KC_TAB,   KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_MINS,
        KC_LSFT,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                     KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LCTRL, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,   KC_LBRC, KC_RBRC, KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RALT,
                                KC_LGUI, KC_LALT, MO(_LOWER), KC_SPC,  KC_ENT,  KC_BSPC, MO(_RAISE), KC_DEL
```

2020-12-14 02:11 UTC, fauxpark commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +                                   _______, _______, _______, _______, _______, _______, _______, _______\
```suggestion
    [_LOWER] = LAYOUT(
        _______, LT_1,    LT_2,    LT_3,    LT_4,    LT_5,                      LT_6,    LT_7,    LT_8,    LT_9,    LT_0,    KC_GRV,
        _______, LT_4,    LT_5,    LT_6,    _______, _______,                   _______, _______, _______, _______, _______, _______,
        _______, LT_7,    LT_8,    LT_9,    LT_0,    _______,                   _______, _______, _______, _______, _______, _______,
        _______, LT_EQL, KC_PPLS, KC_PMNS, KC_PIPE, _______, _______, _______, _______, _______, _______, _______, _______, _______,
                                   _______, _______, _______, _______, _______, _______, _______, _______
```

2020-12-14 02:11 UTC, fauxpark commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +                                   _______, _______, _______, _______, _______, _______, _______, _______ \
```suggestion
    [_RAISE] = LAYOUT(
        _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                     KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_PSCR,
        _______, KC_F11,  KC_F12,  _______, _______, _______,                   _______, KC_PGUP, KC_HOME, KC_UP,   KC_END,  KC_VOLU,
        _______, _______, _______, _______, _______, _______,                   _______, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_VOLD,
        _______, C(KC_Z), C(KC_X), C(KC_C), C(KC_V), _______, _______, _______, _______, _______, KC_MPRV, KC_MNXT, KC_MPLY, _______,
                                   _______, _______, _______, _______, _______, _______, _______, _______
```

2020-12-14 02:11 UTC, fauxpark commented on keyboards/lily58/keymaps/domnantas/keymap.c
> +                                   _______, _______, _______, _______, _______,  _______, _______, _______ \
```suggestion
    [_ADJUST] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        KC_CAPS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                   _______, _______, _______, _______, _______,  _______, _______, _______
```

2020-12-14 02:11 UTC, fauxpark commented on keyboards/lily58/keymaps/domnantas/rules.mk
> +SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
```suggestion
```

2021-01-13 01:37 UTC, drashna approved these changes

2021-01-13 09:42 UTC, domnantas commented
@fauxpark Thanks for the review!

2021-01-14 00:06 UTC, fauxpark approved these changes

2021-01-14 19:04 UTC, merged

2021-01-14 19:04 UTC, drashna commented
Thank you for the contribution!!