Railroad fix
qmk/qmk_firmware pull request #10935
Opened 2020-11-13 05:38 UTC by nopunin10did

## Description

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Noticed that I'd forgotten to rename a couple files after moving them to a rev0 folder.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-13 05:42 UTC, fauxpark requested changes

2020-11-13 05:42 UTC, fauxpark commented on keyboards/nopunin10did/railroad/rev0/rules.mk
> +LAYOUTS = prototype
```suggestion
```

2020-11-13 05:42 UTC, fauxpark commented on keyboards/nopunin10did/railroad/rev0/rev0.h
> +#define LAYOUT_prototype LAYOUT
```suggestion
```

2020-11-19 11:22 UTC, fauxpark approved these changes

2020-11-23 09:45 UTC, noroadsleft requested changes

2020-11-23 09:45 UTC, noroadsleft commented on keyboards/nopunin10did/railroad/rev0/readme.md
> +* Keyboard Maintainer: [Alex Ronke](diplomacyvariants.wordpress.com), also known as NoPunIn10Did.
Fixes the first link, and also links to your GitHub account.

```suggestion
* Keyboard Maintainer: [Alex Ronke](https://diplomacyvariants.wordpress.com/), also known as [NoPunIn10Did](https://github.com/nopunin10did). 
```

2020-11-23 14:38 UTC, nopunin10did commented
@noroadsleft Change committed.

2020-11-24 09:58 UTC, noroadsleft approved these changes

2020-11-24 09:59 UTC, merged

2020-11-24 09:59 UTC, noroadsleft commented
Thanks!