Add 3x3 macropad keyboard and layout.
qmk/qmk_firmware pull request #10931
Opened 2020-11-12 23:05 UTC by luis-godinez

## Description

Add qmk support for 3x3 macropad with dual rotary encoders.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-17 04:00 UTC, drashna approved these changes

2020-11-18 10:02 UTC, fauxpark requested changes

2020-11-18 10:02 UTC, fauxpark commented on keyboards/ungodly/nines/rules.mk
> +ENCODER_ENABLE = yes        # Rotary encoder support
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes        # Rotary encoder support
```

2020-11-18 19:28 UTC, Erovia requested changes

2020-11-18 19:28 UTC, Erovia commented on keyboards/ungodly/nines/keymaps/default/keymap.c
> +    _______, _______, _______
```suggestion
```

2020-11-18 19:28 UTC, Erovia commented on keyboards/ungodly/nines/readme.md
> +
Can you add "clear instructions on how to reset the board into bootloader mode" as per the [PR Checklist](https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs)?

2020-11-18 21:29 UTC, zvecr requested changes

2020-11-18 21:29 UTC, zvecr commented on keyboards/ungodly/nines/nines.c
> +void encoder_update_kb(uint8_t index, bool clockwise) {
```suggestion
__attribute__((weak)) void encoder_update_user(uint8_t index, bool clockwise) {
```

2020-11-19 11:03 UTC, fauxpark approved these changes

2020-11-19 19:30 UTC, Erovia approved these changes

2020-11-19 19:30 UTC, merged