add matrix abelx keyboard
qmk/qmk_firmware pull request #10968
Opened 2020-11-18 07:36 UTC by yulei

Add abelx keyboard from the Matrix Lab

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-19 17:29 UTC, drashna approved these changes

2020-11-19 17:29 UTC, drashna commented on keyboards/matrix/abelx/abelx.c
> +extern rgblight_config_t rgblight_config;
```suggestion
```

2021-01-24 16:15 UTC, noroadsleft requested changes

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/keymaps/default/keymap.c
> + * This program is free software: you can redistribute it and/or modify
```suggestion
 * Copyright 2020 astro <yuleiz@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
```

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/keymaps/iso/keymap.c
> + * This program is free software: you can redistribute it and/or modify
```suggestion
 * Copyright 2020 astro <yuleiz@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
```

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/matrix.c
> + * This program is free software: you can redistribute it and/or modify
```suggestion
 * Copyright 2020 astro <yuleiz@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
```

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/readme.md
> +Hardware Availability:
```suggestion
* Keyboard Maintainer: [astro](https://github.com/yulei)
* Hardware Supported: Matrix ABELX keyboard
* Hardware Availability: 
```

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
NO_USB_STARTUP_CHECK = yes  # Disable initialization only when usb is plugged in
```

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/tca6424.c
> + * This program is free software: you can redistribute it and/or modify
```suggestion
 * Copyright 2020 astro <yuleiz@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
```

2021-01-24 16:15 UTC, noroadsleft commented on keyboards/matrix/abelx/tca6424.h
> + * This program is free software: you can redistribute it and/or modify
```suggestion
 * Copyright 2020 astro <yuleiz@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
```

2021-02-02 21:09 UTC, tzarc requested changes
A few changes required.

One note though, once the new `develop` branch lands, it will be very unlikely that modified ChibiOS board files will be accepted due to ongoing maintenance costs whenever we attempt to upgrade.

You can see for [matrix/noah](https://github.com/qmk/qmk_firmware/tree/develop/keyboards/matrix/noah) I've already removed the `board.c`/`board.mk` and moved your `board.h` to the keyboard directory temporarily, to ensure it still builds. ChibiOS configs have been migrated also. After the modificationss, binaries were identical, with sha1sum's verified to be the same before and after the migration. You'll note that the board is now set to `ST_NUCLEO64_F411RE` in `rules.mk`, and future boards will be expected to leverage the definitions present in ChibiOS itself in much the same way.

For now, I'll let this slide through -- I'll perform the modifications much like the noah -- however you should expect to review a few PRs for the existing matrix boards once `develop` is merged to eliminate the last remnants of the custom board files.

2021-02-03 01:43 UTC, yulei commented on keyboards/matrix/abelx/abelx.c
> +
yes, it can be removed now, the```initialized``` was added recently.

2021-02-03 05:55 UTC, yulei commented on keyboards/matrix/abelx/abelx.c
> +#endif
I have moved it to housekeeping_kb(). And for other stm32f4 based keyboards, after the merging of the ```develop``` branch, I'll update them asap.

2021-11-05 02:54 UTC, tzarc approved these changes

2021-11-05 02:54 UTC, merged