Add keyboard PistachioMacroPad
qmk/qmk_firmware pull request #10980
Opened 2020-11-19 13:22 UTC by 7-rate

Add keyboard "PistachioMacroPad"

This is a numeric keypad with a rotary encoder that uses a stainless steel plate.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-21 19:10 UTC, zvecr requested changes
Project name cannot be camel case per <https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=naming-your-keyboardproject>. There will be more suggestions, but it might be worth a rename beforehand so they do not get lost.

2020-11-22 01:53 UTC, 7-rate commented
Thanks, for the review.
I have already modified the Project name.

I also modified some parts of the keymap.

2020-11-22 21:18 UTC, zvecr requested changes

2020-11-22 21:18 UTC, zvecr commented on keyboards/pistachio_mp/config.h
> +#define TAPPING_TERM 170
```suggestion
```

2020-11-22 21:18 UTC, zvecr commented on keyboards/pistachio_mp/config.h
> +#define RGBLIGHT_LAYERS
```suggestion
```

2020-11-22 21:18 UTC, zvecr commented on keyboards/pistachio_mp/keymaps/default/keymap.c
> +
```suggestion
```

2020-11-22 21:18 UTC, zvecr commented on keyboards/pistachio_mp/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-25 18:49 UTC, Erovia approved these changes

2020-11-25 21:22 UTC, drashna approved these changes

2020-11-26 12:16 UTC, fauxpark approved these changes

2020-11-26 12:16 UTC, fauxpark commented
Thanks!

2020-11-26 12:16 UTC, merged