[Keyboard] Add Viktus Styrka
qmk/qmk_firmware pull request #10982
Opened 2020-11-19 16:12 UTC by jrfhoutx

Initial commit to add support for the Viktus Styrka

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-19 16:20 UTC, fauxpark requested changes

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/styrka.c
> +*/
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/keymaps/split_bs/keymap.c
> +  ),
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/keymaps/all/keymap.c
> +  ),
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/info.json
> +        "key_count": 80,
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/info.json
> +        "key_count": 78,
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/info.json
> +      "key_count": 77,
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/config.h
> +
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/config.h
> +#define DESCRIPTION     65% with left-hand dual macro columns
```suggestion
```

2020-11-19 16:20 UTC, fauxpark commented on keyboards/viktus/styrka/config.h
> +
```suggestion
```

2020-11-19 17:00 UTC, jrfhoutx commented
made requested changes

2020-11-19 17:04 UTC, fauxpark requested changes

2020-11-19 17:04 UTC, fauxpark commented on keyboards/viktus/styrka/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-22 11:20 UTC, fauxpark approved these changes

2020-11-25 18:47 UTC, drashna approved these changes

2020-11-25 18:48 UTC, merged