Add initial VIA support for gherkin and pockettype
qmk/qmk_firmware pull request #11040
Opened 2020-11-26 22:14 UTC by sirdicholas15

40percentclub gherkin and maartenwut pockettype

Added the requred files needed for initial VIA support for the Gherkin and PocketType

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-29 17:57 UTC, zvecr requested changes
pockettype has been moved to <https://github.com/qmk/qmk_firmware/tree/master/keyboards/evyd13/pockettype>

Also licence headers need to be added to the keymap.c files

2020-11-30 09:39 UTC, Suschman commented
Can the USB ids for gherkin be aligned with the other enabled 40percentclub boards before it goes into VIA?

#define VENDOR_ID       0x3430 // "40"
#define PRODUCT_ID       0x4748 // "GH"

> It is recommended to choose a value of VENDOR_ID that unique to the keyboard PCB’s designer/vendor, i.e. it will be the same for all keyboards with a common parent directory.

2020-12-17 05:47 UTC, drashna requested changes

2020-12-17 05:47 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-17 05:47 UTC, drashna commented on keyboards/evyd13/pockettype/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-03-05 15:40 UTC, closed without merging