Added taleguers75 rev1 keyboard
qmk/qmk_firmware pull request #11052
Opened 2020-11-28 13:55 UTC by borlopjim

## Description

Initial PR for adding Taleguers75 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-29 20:22 UTC, zvecr requested changes

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/keymaps/default/keymap.c
> +	[0] = KEYMAP(
```suggestion
	[0] = LAYOUT(
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/keymaps/default/keymap.c
> +#include "rgblight.h"
```suggestion
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/keymaps/default/keymap.c
> +	[1] = KEYMAP(
```suggestion
	[1] = LAYOUT(
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/keymaps/default/keymap.c
> +
```suggestion
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/keymaps/via/keymap.c
> +#include "rgblight.h"
```suggestion
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/keymaps/via/keymap.c
> +	[3] =KEYMAP(
```suggestion
	[0] = LAYOUT(
		KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_DEL, 
		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, 
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, 
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_PGUP, 
		KC_LSFT, KC_PSCR, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_PGDN, 
		KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_RALT, MO(1), KC_RCTL, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT),

	[1] = LAYOUT(
		KC_TRNS, RGB_MODE_FORWARD, RGB_MODE_REVERSE, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[2] = KEYMAP(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[3] =LAYOUT(
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/info.json
> +        "LAYOUT": {
Order here does not match layout macro, most obvious at the up arrow location

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/config.h
> +#define PREVENT_STUCK_MODIFIERS
```suggestion
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/config.h
> +#define DESCRIPTION     Taleguers75 Keyboard
```suggestion
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/rules.mk
> +RGBLIGHT_ENABLE ?= yes
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/taleguers75.c
> +void encoder_update_kb(uint8_t index, bool clockwise) {
```suggestion
__attribute__ ((weak)) void encoder_update_user(uint8_t index, bool clockwise) {
```

2020-11-29 20:22 UTC, zvecr commented on keyboards/taleguers/taleguers75/taleguers75.h
> +#define KEYMAP( \
```suggestion
#define LAYOUT( \
```

2020-12-01 11:12 UTC, fauxpark approved these changes

2020-12-04 04:59 UTC, drashna approved these changes

2020-12-04 04:59 UTC, merged