Add customMK Genesis Macro Pad
qmk/qmk_firmware pull request #11080
Opened 2020-11-30 10:34 UTC by infinityis

Adding keyboard and keymap files for customMK Genesis, a 5x4 macro pad.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-30 21:42 UTC, zvecr requested changes

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/keymaps/via/keymap.c
> +	[3] = LAYOUT_ORTHO(
```suggestion
	[3] = LAYOUT_ortho_5x4(
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/keymaps/via/keymap.c
> +	[2] = LAYOUT_ORTHO(
```suggestion
	[2] = LAYOUT_ortho_5x4(
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/keymaps/via/keymap.c
> +	[1] = LAYOUT_ORTHO(
```suggestion
	[1] = LAYOUT_ortho_5x4(
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/keymaps/via/keymap.c
> +	[0] = LAYOUT_ORTHO(
```suggestion
	[0] = LAYOUT_ortho_5x4(
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/keymaps/default/keymap.c
> +	[0] = LAYOUT_ORTHO(
```suggestion
	[0] = LAYOUT_ortho_5x4(
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/keymaps/default/keymap.c
> +	[1] = LAYOUT_ORTHO(
```suggestion
	[1] = LAYOUT_ortho_5x4(
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/info.json
> +        "LAYOUT": {
This doesnt cover the 2 layouts that are defined for the keyboard

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/genesis.h
> +#define LAYOUT_ORTHO( \
```suggestion
#define LAYOUT_ortho_5x4( \
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/genesis.c
> +void encoder_update_user(uint8_t index, bool clockwise) {
```suggestion
__attribute__((weak)) void encoder_update_user(uint8_t index, bool clockwise) {
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/config.h
> +
```suggestion

```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/genesis.h
> +}
```suggestion
#define LAYOUT_numpad_5x4( \
	K00, K01, K02, K03, \
	K10, K11, K12,      \
	K20, K21, K22, K23, \
	K30, K31, K32,      \
	  K40,    K42, K43  \
) { \
	{ K00,   K01,   K02,   K03 }, \
	{ K10,   K11,   K12,   KC_NO }, \
	{ K20,   K21,   K22,   K23 }, \
	{ K30,   K31,   K32,   KC_NO }, \
	{ K40,   KC_NO, K42,   K43 }  \
}
```

2020-11-30 21:42 UTC, zvecr commented on keyboards/custommk/genesis/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion

# Bootloader selection
BOOTLOADER = qmk-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2020-12-01 05:33 UTC, infinityis commented
Thank you! All suggested changes have been incorporated.

2020-12-01 11:54 UTC, fauxpark requested changes

2020-12-01 11:54 UTC, fauxpark commented on keyboards/custommk/genesis/config.h
> +#define DEVICE_VER      0x0001
```suggestion
#define DEVICE_VER      0x0001
#define MANUFACTURER    customMK
```

2020-12-01 11:54 UTC, fauxpark commented on keyboards/custommk/genesis/readme.md
> +    make custommk/genesis:default:dfu
```suggestion
    make custommk/genesis:default:flash
```

2020-12-01 19:59 UTC, infinityis reviewed
Recommended suggestions have been incorporated

2020-12-04 05:16 UTC, drashna approved these changes

2020-12-05 05:43 UTC, fauxpark approved these changes

2020-12-08 02:10 UTC, merged