New keyboard SLZ40
qmk/qmk_firmware pull request #11088
Opened 2020-11-30 19:36 UTC by sithlord121

## Description

New keyboard, 40% style keyboard with 11 num row keys on top row for Zhuyin input.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-30 20:17 UTC, sithlord121 commented
updated info.json file

2020-11-30 21:16 UTC, zvecr requested changes

2020-11-30 21:16 UTC, zvecr commented on keyboards/slz40/keymaps/default/keymap.c
> +
```suggestion
```

2020-11-30 21:16 UTC, zvecr commented on keyboards/slz40/keymaps/default/keymap.c
> +}
```suggestion
```

2020-12-01 11:50 UTC, fauxpark requested changes

2020-12-01 11:50 UTC, fauxpark commented on keyboards/slz40/readme.md
> +![slz40](imgur.com image replace me!)
Please fill this out.

2020-12-01 15:59 UTC, sithlord121 commented on keyboards/slz40/readme.md
> +![slz40](imgur.com image replace me!)
updated

2020-12-04 00:52 UTC, zvecr approved these changes

2020-12-04 05:22 UTC, drashna approved these changes

2020-12-05 05:44 UTC, fauxpark approved these changes

2020-12-08 02:18 UTC, merged