add nt750
qmk/qmk_firmware pull request #11091
Opened 2020-12-01 07:34 UTC by evyd13

## Description

Adds the nt750 PCB, a replacement PCB for the Leopold FC750R (PD).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-01 20:45 UTC, zvecr requested changes

2020-12-01 20:45 UTC, zvecr commented on keyboards/evyd13/nt750/nt750.c
> +}
```suggestion
```

2020-12-01 20:45 UTC, zvecr commented on keyboards/evyd13/nt750/config.h
> +
```suggestion

#define LED_CAPS_LOCK_PIN D5
#define LED_PIN_ON_STATE 0

```

2020-12-04 00:53 UTC, zvecr approved these changes

2020-12-04 05:25 UTC, drashna approved these changes

2020-12-05 05:45 UTC, fauxpark approved these changes

2020-12-05 05:45 UTC, fauxpark commented
Thanks!

2020-12-05 05:45 UTC, merged