ISO layout for KBD67 rev 2.0
qmk/qmk_firmware pull request #11136
Opened 2020-12-06 19:50 UTC by hekekee

## Description

KBD67 rev 2.0 was missing a ISO layout keymap, made with `LAYOUT_65_iso`.
This provides easier starting point for future keymap customization for ISO layout users.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-09 01:17 UTC, drashna requested changes

2020-12-09 01:17 UTC, drashna commented on keyboards/kbdfans/kbd67/rev2/keymaps/iso/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-09 01:17 UTC, drashna commented on keyboards/kbdfans/kbd67/rev2/keymaps/iso/config.h
> +/* Copyright 2018 MechMerlin
Can be removed. Is no override to be placed.

2020-12-09 01:17 UTC, drashna commented on keyboards/kbdfans/kbd67/rev2/keymaps/iso/keymap.c
> +}
```suggestion
```

2020-12-09 08:32 UTC, hekekee commented
Made the changes according to @drashna's comments. This is my first ever pull request on Github, thanks for being gentle ♥

2020-12-09 08:34 UTC, fauxpark approved these changes

2020-12-17 06:46 UTC, drashna approved these changes

2020-12-17 06:47 UTC, merged