Helen 80 addition
qmk/qmk_firmware pull request #11133
Opened 2020-12-06 06:27 UTC by yj7272098

## Description

Add Helen 80 keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-08 16:55 UTC, yj7272098 commented
I will go back to this PR when previous PR is done.

2020-12-17 06:42 UTC, drashna approved these changes

2020-12-20 02:12 UTC, fauxpark requested changes

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/readme.md
> +
```suggestion

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/rules.mk
> +LAYOUTS = ansi_87
```suggestion
LAYOUTS = tkl_ansi
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/info.json
> +        "LAYOUT_ansi_87": {
```suggestion
        "LAYOUT_tkl_ansi": {
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/helen80.h
> +#define LAYOUT_ansi_87( \
```suggestion
#define LAYOUT_tkl_ansi( \
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/keymaps/default/keymap.c
> +  [0] = LAYOUT_ansi_87(
```suggestion
  [0] = LAYOUT_tkl_ansi(
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/keymaps/default/keymap.c
> +  [1] = LAYOUT_ansi_87(
```suggestion
  [1] = LAYOUT_tkl_ansi(
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/keymaps/via/keymap.c
> +  [0] = LAYOUT_ansi_87(
```suggestion
  [0] = LAYOUT_tkl_ansi(
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/keymaps/via/keymap.c
> +  [1] = LAYOUT_ansi_87(
```suggestion
  [1] = LAYOUT_tkl_ansi(
```

2020-12-20 02:12 UTC, fauxpark commented on keyboards/playkbtw/helen80/keymaps/via/keymap.c
> +    ),
You need two more empty layers here.

2020-12-20 02:23 UTC, yj7272098 commented
@fauxpark Done. Thanks for checking!

2020-12-22 05:58 UTC, fauxpark approved these changes

2020-12-22 18:55 UTC, Erovia requested changes

2020-12-22 18:55 UTC, Erovia commented on keyboards/playkbtw/helen80/readme.md
> +
Can you add "clear instructions on how to reset the board into bootloader mode" as per [PR Checklist](https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs)?

2020-12-22 18:55 UTC, Erovia commented on keyboards/playkbtw/helen80/keymaps/via/keymap.c
> +    BASE,
```suggestion
    _BASE,
```

2020-12-22 18:55 UTC, Erovia commented on keyboards/playkbtw/helen80/keymaps/via/keymap.c
> +  [BASE] = LAYOUT_tkl_ansi(
```suggestion
  [_BASE] = LAYOUT_tkl_ansi(
```

2020-12-22 18:55 UTC, Erovia commented on keyboards/playkbtw/helen80/keymaps/default/keymap.c
> +    BASE,
```suggestion
    _BASE,
```
I recommend sticking to one format when naming layers.

2020-12-22 18:55 UTC, Erovia commented on keyboards/playkbtw/helen80/keymaps/default/keymap.c
> +  [BASE] = LAYOUT_tkl_ansi(
```suggestion
  [_BASE] = LAYOUT_tkl_ansi(
```

2020-12-22 18:55 UTC, Erovia commented on keyboards/playkbtw/helen80/keymaps/default/readme.md
> +This is the default layout that comes flashed on every Helen 80. All key pins are shown in the file.
> All key pins are shown in the file.

Not sure I know what you mean.

2020-12-23 05:10 UTC, yj7272098 commented
@Erovia Thanks for checking!

2020-12-23 09:22 UTC, Erovia approved these changes

2020-12-23 09:22 UTC, merged