[Keymap] Added initial lily58 mysticmechs keymap
qmk/qmk_firmware pull request #11155
Opened 2020-12-08 10:46 UTC by christiangda

Add keymap 'lily58:mysticmechs'

This allows users of the [Keyboard MysticMech Lily58 PRO with Rotary Encoder](https://mysticmechs.com/) flash it using the command

```
make lily58:mysticmechs:avrdude
```
without any modifications of `qmk_firmware` repository files.

This PR apply necessary changes over the `qmk_firmware` sourced code following the instructions of the `keyboard manufacturer` described here [https://mysticmechs.com/pages/lily58-pro-documentation](https://mysticmechs.com/pages/lily58-pro-documentation) to enable the `Rotary Encoder`

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-09 02:18 UTC, drashna requested changes

2020-12-09 02:18 UTC, drashna commented on keyboards/lily58/keymaps/christiangda/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-09 02:18 UTC, drashna commented on keyboards/lily58/keymaps/christiangda/keymap.c
> +#endif
These shouldn't be needed.
```suggestion
```

2020-12-09 02:18 UTC, drashna commented on keyboards/lily58/keymaps/mysticmechs/README.md
> +    make lily58:mysticmechs:avrdude
```suggestion
    make lily58:mysticmechs:flash
```

2020-12-09 02:18 UTC, drashna commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-09 02:18 UTC, drashna commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +#endif
```suggestion
```

2020-12-13 11:16 UTC, christiangda reviewed
removed unnecessary files

2020-12-13 12:05 UTC, christiangda reviewed
add a GPL2+ compatible license header and removed unnecessary headers

2020-12-22 19:20 UTC, drashna approved these changes

2020-12-22 19:29 UTC, fauxpark requested changes

2020-12-22 19:29 UTC, fauxpark commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> + * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  | F10  | F11  | F12  |
```suggestion
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  | F10  | F11  | F12  |
```

2020-12-22 19:29 UTC, fauxpark commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> + * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |-------.    ,-------|      | Left | Down |  Up  |Right |      |
```suggestion
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |-------.    ,-------|      | Left | Down |  Up  |Right |      |
```

2021-02-14 22:22 UTC, fauxpark requested changes

2021-02-14 22:22 UTC, fauxpark commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +                        KC_LALT, KC_LGUI, MO(_LOWER), KC_SPC, KC_ENT, MO(_RAISE), KC_BSPC, KC_RGUI \
```suggestion
 [_QWERTY] = LAYOUT(
  KC_ESC,   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                     KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_GRV,
  KC_TAB,   KC_Q,   KC_W,    KC_E,    KC_R,    KC_T,                     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_MINS,
  KC_LCTRL, KC_A,   KC_S,    KC_D,    KC_F,    KC_G,                     KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
  KC_LSFT,  KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, KC_LBRC,  KC_RBRC,  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,  KC_RSFT,
                        KC_LALT, KC_LGUI, MO(_LOWER), KC_SPC, KC_ENT, MO(_RAISE), KC_BSPC, KC_RGUI
```

2021-02-14 22:22 UTC, fauxpark commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +                             _______, _______, _______, _______, _______,  _______, _______, _______\
```suggestion
[_LOWER] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                   _______, _______, _______,_______, _______, _______,
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                     KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,
  KC_GRV, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,                   KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TILD,
  _______, _______, _______, _______, _______, _______, _______, _______, XXXXXXX, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
                             _______, _______, _______, _______, _______,  _______, _______, _______
```

2021-02-14 22:22 UTC, fauxpark commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +                             _______, _______, _______,  _______, _______,  _______, _______, _______ \
```suggestion
[_RAISE] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                     _______, _______, _______, _______, _______, _______,
  KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    _______,
  KC_F1,  KC_F2,    KC_F3,   KC_F4,   KC_F5,   KC_F6,                       XXXXXXX, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX,
  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,   _______, _______,  KC_PLUS, KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS,
                             _______, _______, _______,  _______, _______,  _______, _______, _______
```

2021-02-14 22:22 UTC, fauxpark commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +                             _______, _______, _______, _______, _______,  _______, _______, _______ \
```suggestion
  [_ADJUST] = LAYOUT(
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                             _______, _______, _______, _______, _______,  _______, _______, _______
```

2021-02-21 04:09 UTC, drashna commented on keyboards/lily58/keymaps/mysticmechs/keymap.c
> +extern uint8_t is_master;
```suggestion
```

2021-07-08 00:47 UTC, closed without merging