spidey3 keymap for DMQDesign Spin
qmk/qmk_firmware pull request #11194
Opened 2020-12-12 15:59 UTC by spidey3

## Description

My first cut at firmware for the DMQDesign Spin

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-22 19:34 UTC, drashna requested changes

2020-12-22 19:34 UTC, drashna commented on keyboards/dmqdesign/spin/keymaps/spidey3_pad/keymap.c
> +            rgb_layer_ack_yn(rgblight_config.enable);
```suggestion
            rgb_layer_ack_yn(rgblight_is_enabled());
```

2020-12-22 19:34 UTC, drashna commented on keyboards/dmqdesign/spin/keymaps/spidey3_pad/keymap.c
> +extern rgblight_config_t rgblight_config;
```suggestion
```

2020-12-23 06:20 UTC, drashna approved these changes

2020-12-23 09:17 UTC, fauxpark requested changes

2020-12-23 09:17 UTC, fauxpark commented on keyboards/dmqdesign/spin/keymaps/spidey3_pad/keymap.c
> +#include <version.h>
```suggestion
#include "version.h"
```

2020-12-23 15:53 UTC, fauxpark approved these changes

2020-12-30 03:21 UTC, merged