corrected the pid and added a new layout.
qmk/qmk_firmware pull request #11198
Opened 2020-12-13 03:36 UTC by ibnuda

1. pid and vid changes.
2. keymap layout addition.

## Description
1. based on [pidcodes#585](https://github.com/pidcodes/pidcodes.github.com/pull/585), i corrected the vendor id and product id of squiggle keyboard.
2. i added a new keymap layout for the previously mentioned keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-22 19:52 UTC, drashna requested changes

2020-12-22 19:52 UTC, drashna commented on keyboards/squiggle/keymaps/default38/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-22 20:02 UTC, fauxpark approved these changes

2020-12-23 05:52 UTC, drashna approved these changes

2020-12-23 05:53 UTC, merged