Rebound, adding files for VIA compat
qmk/qmk_firmware pull request #11193
Opened 2020-12-12 15:34 UTC by Rossman360

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-22 19:42 UTC, drashna requested changes

2020-12-22 19:42 UTC, drashna commented on keyboards/montsinger/rebound/rev4/config.h
> +#define PRODUCT Montsinger Rebound
```suggestion
#define PRODUCT Rebound
```

2020-12-22 19:48 UTC, fauxpark requested changes

2020-12-22 19:48 UTC, fauxpark commented on keyboards/montsinger/rebound/rev4/config.h
>  #define DESCRIPTION "A conjoined Let's Split"
```suggestion
```

2020-12-25 14:46 UTC, fauxpark approved these changes

2020-12-30 03:21 UTC, drashna requested changes

2020-12-30 03:21 UTC, drashna commented on keyboards/montsinger/rebound/rev4/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-31 02:22 UTC, fauxpark approved these changes

2021-01-01 22:57 UTC, drashna approved these changes
Thanks!

2021-01-01 23:04 UTC, drashna commented
Also, it looks like the `ortho_4x12` layout is erroring out on the rev4 stuff.  That's outside the scope of this PR, but is something that should be fixed, eventually.

2021-01-01 23:05 UTC, merged