Adding new keyboard: Tenkey++ (tenkey_plusplus)
qmk/qmk_firmware pull request #11197
Opened 2020-12-12 22:47 UTC by jonbobcar

## Description

Adding a new keyboard: Tenkey++ (tenkey_plusplus)

I will be merging in another keyboard soon, so I nested this one inside the /lizard_trick directory to keep my keyboards in the same place in the future.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-22 19:50 UTC, drashna approved these changes

2020-12-22 19:56 UTC, fauxpark requested changes

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/config.h
> +
```suggestion
```

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/info.json
> +            "layout": [
```suggestion
            "LAYOUT": [
```

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/readme.md
> +    Press the button on the back of the PCB labeled "RESET"
```suggestion
```

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/readme.md
> +![TK++](https://i.imgur.com/DOJUglt.jpg)
```suggestion
![TK++](https://i.imgur.com/DOJUgltl.jpg)
```

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/readme.md
> +![PCB](https://i.imgur.com/aMii80b.jpg)
```suggestion
![PCB](https://i.imgur.com/aMii80bl.jpg)
```

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/rules.mk
> +ENCODER_ENABLE = yes		# Adds support for rotary encoders
```suggestion
```

2020-12-22 19:56 UTC, fauxpark commented on keyboards/lizard_trick/tenkey_plusplus/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2020-12-25 14:41 UTC, fauxpark approved these changes

2020-12-25 14:42 UTC, fauxpark commented
Thanks!

2020-12-25 14:42 UTC, merged