Quark PCB for Planck/Preonic
qmk/qmk_firmware pull request #11206
Opened 2020-12-13 22:08 UTC by npspears

Quark provides alternate bottom row layouts for both the OLKB Planck and Preonic

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-13 22:10 UTC, npspears commented
Thanks for looking this over!

2020-12-16 17:32 UTC, ridingqwerty requested changes
The via `rules.mk` file needs the `.txt` suffix removed.
You could also consider moving `#define TAPPING_TOGGLE 2` into the keyboard-level `config.h` to cut down on the number of files.

2020-12-16 17:32 UTC, ridingqwerty commented on keyboards/quark/rules.mk
> +UNICODE_ENABLE = yes 	    # Unicode
```suggestion
  UNICODE_ENABLE = yes 	    # Unicode
```

2020-12-16 17:32 UTC, ridingqwerty commented on keyboards/quark/keymaps/via/rules.mk.txt
> +VIA_ENABLE = yes
This file has to have the `.txt` suffix removed.

2020-12-16 19:23 UTC, npspears reviewed
.txt ending remove
place #define TAPPING_TOGGLE 2 into the keyboard-level config.h

2020-12-16 19:31 UTC, npspears reviewed
tapping toggle relocated, and removed txt at end of file done

2020-12-22 20:17 UTC, drashna requested changes

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/config.h
> +#define DESCRIPTION     ortholinear PCB with alternate bottom rows
This value is no longer used.

```suggestion
```

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/keymaps/default_4x12_grid/keymap.c
> +  [0] = LAYOUT_4x12_Grid( \
```suggestion
  [0] = LAYOUT_ortho_4x12( \
```

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/keymaps/default_4x12_grid/keymap.c
> +  [1] = LAYOUT_4x12_Grid( \
```suggestion
  [1] = LAYOUT_ortho_4x12( \
```

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/keymaps/default_4x12_grid/keymap.c
> +  [2] = LAYOUT_4x12_Grid( \
```suggestion
  [2] = LAYOUT_ortho_4x12( \
```

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/keymaps/default_4x12_mit/config.h
> +
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

As well as:
```c
#pragma once
```

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/keymaps/default_5x12_2x3/config.h
> +
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/quark.h
> +#define LAYOUT_4x12_Grid( \
```suggestion
#define LAYOUT_ortho_4x12( \
```

2020-12-22 20:17 UTC, drashna commented on keyboards/quark/rules.mk
> +UNICODE_ENABLE = yes 	    # Unicode
```suggestion
UNICODE_ENABLE = yes        # Unicode
```

2020-12-22 20:19 UTC, drashna commented on keyboards/quark/rules.mk
> +
```suggestion

LAYOUTS = ortho_4x12
```

2020-12-23 14:24 UTC, npspears reviewed
all review comments (so far) have been added

2020-12-23 14:32 UTC, npspears reviewed
fixed the broken info.json - sorry about that

2020-12-30 09:05 UTC, drashna approved these changes

2020-12-31 14:59 UTC, ridingqwerty approved these changes

2020-12-31 15:00 UTC, merged

2020-12-31 15:00 UTC, ridingqwerty commented
Thanks!