Update Choco60 firmware to support new PCB
qmk/qmk_firmware pull request #11218
Opened 2020-12-15 13:42 UTC by takai

## Description

Update Choco60 firmware to support new PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-23 00:39 UTC, drashna approved these changes

2020-12-23 05:04 UTC, fauxpark requested changes

2020-12-23 05:04 UTC, fauxpark commented on keyboards/choco60/config.h
> +#define DESCRIPTION     recompile keys Choco60
```suggestion
```

2020-12-23 05:04 UTC, fauxpark commented on keyboards/choco60/rev1/readme.md
> +    make choco60:default
```suggestion
    make choco60/rev1:default
```

2020-12-23 05:04 UTC, fauxpark commented on keyboards/choco60/rev1/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-12-23 05:04 UTC, fauxpark commented on keyboards/choco60/rev1/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-12-23 09:16 UTC, fauxpark approved these changes

2020-12-30 00:05 UTC, zvecr approved these changes

2020-12-30 00:05 UTC, merged

2020-12-30 00:05 UTC, zvecr commented
Thanks!