Fix Issue #9533 - Delayed shift state handling
qmk/qmk_firmware pull request #11220
Opened 2020-12-15 21:53 UTC by spidey3

## Description

As @sigprof mentions in #9533, this was broken in #8770. Now that `unicodemap_index()` is called before the unicode input functions, it must use the current modifier state, not the saved state.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Issue #9533 
* Issue #9405 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-16 00:17 UTC, zvecr commented
Duplicate (be it maybe more complete?) of #10627.

2020-12-16 00:42 UTC, spidey3 commented
> Duplicate (be it maybe more complete?) of #10627.
Yes, I realized that #10627 tried to address this too, but as you said that PR is less complete, and it seems to be stale.

2020-12-21 16:05 UTC, fauxpark requested changes

2020-12-21 16:05 UTC, fauxpark commented on quantum/process_keycode/process_unicodemap.c
>          bool caps  = IS_HOST_LED_ON(USB_LED_CAPS_LOCK);
```suggestion
        bool caps  = host_keyboard_led_state().caps_lock;
```
While we're here...

2020-12-21 19:46 UTC, fauxpark approved these changes

2020-12-22 16:17 UTC, bit-shifter commented
Really happy to see a fix being raised for this.
qmk has been patched locally and the fix appears to work for my use case (greek lower/upper case) without issue.

Tested on arch linux against a `UNICODEMAP_ENABLE`d keymap for the hyper7 (PR incoming).

2020-12-22 17:04 UTC, Erovia approved these changes

2020-12-22 17:23 UTC, merged