Add support for idobao id80 iso layout
qmk/qmk_firmware pull request #11246
Opened 2020-12-20 07:12 UTC by cwr10010

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-23 01:37 UTC, drashna reviewed
The only change here is adding an ISO layout, and nothing else?  

If so, I'm not really a fan of splitting this up into two different revisions.  Rather `LAYOUT_ansi` and `LAYOUT_iso` in the keyboard will work.  Additionally, VIA is capable of layout grouping, so you can toggle between the two, without problem.

2020-12-23 06:36 UTC, cwr10010 commented
> The only change here is adding an ISO layout, and nothing else?
> 
> If so, I'm not really a fan of splitting this up into two different revisions. Rather `LAYOUT_ansi` and `LAYOUT_iso` in the keyboard will work. Additionally, VIA is capable of layout grouping, so you can toggle between the two, without problem.

Yes that is the only change. In fact the board is a hot swap board with two revisions that are wired differently. You may want to have  look at the Enter key that is on the A-row for ansi and on the Q row for ISO. If your suggestion is that the board would support ISO just in VIA this would not follow my intention of this PR.

2020-12-23 07:00 UTC, drashna commented
In that case, a `LAYOUT_all` for via/etc and a layout for ansi and iso would take care the issue, as the layout allows you to remap the positions.

2020-12-23 07:33 UTC, cwr10010 commented
This would (imho) break the ability to flash the VIA variant to the board and have it working with ISO out of the box without remapping anything.

2020-12-23 07:42 UTC, fauxpark commented
That's exactly what `LAYOUT_all` is for and why we recommend VIA keymaps use it, as it contains all possible matrix positions that can be mapped to the correct keycodes. This way, it doesn't matter whether you have an ANSI or ISO layout, the VIA keymap will work as you expect.

2020-12-23 08:01 UTC, cwr10010 commented
Then you will have to help me on this one. On the ANSI variant Enter is on Pin 83 and Backslash on Pin 96. With ISO it is the other way around. As what I have understood of VIA it is a layout editor that displays the layout and makes you reassign keys. How can VIA detect if it is ANSI or ISO when it is the same layout mapping, the same firmware, with the same vendor and product id? If I have flashed the via variant my enter key on the ISO board would be on Backslash and I would require to go to via and change that there, right?

2020-12-23 08:05 UTC, fauxpark commented
Oh, I did not see your comment above:

> In fact the board is a hot swap board with two revisions that are wired differently.

If the ANSI and ISO layouts are two different boards, then that is fine.

2020-12-23 11:50 UTC, cwr10010 commented
Just to clarify my understanding on how all works together:

### id80.h
Maps the wiring of the PCB to the physical location on the board. ANSI and ISO have just one main difference here. ISO is having the split left shift in adding pin 11 in the key layout (being KC_NO on ANSI)

### keyboard.c
Maps the physical layout of the board to the keymaps. Here ANSI and ISO are not compatible. ANSI is having KC_ENT on pin 83 and KC_BSPC on pin 96. ISO is the other way around as the routing of the wires is different Physically the Enter key belongs to the A-row on ANSi and to the Q-row on ISO. 

If I understand this right, it is not possible to have VIA on this board and have it working out of the box for both variants. You would need to go to VIA first and reassign the key mapping for the enter key. Based on this I don't know if this is a good idea that one of the variants will not work correctly directly after flashing.

By the way I have a JSON file her ready for a PR for VIA that adds the left split shift key and the different mapping for Enter. via two switches.

2021-01-04 18:39 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/11246/files).

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/id80.h
> +    K20,    K21, K22, K23, K24, K25, K26, K27, K28, K78, K77, K75, K74,               \
QMK custom is that Enter key keycodes should be toward the end of the home row.

(1/9)

```suggestion
    K30,   K31, K32, K33, K34, K35, K36, K37, K38, K88, K87, K85, K84,          K82,  \
    K20,    K21, K22, K23, K24, K25, K26, K27, K28, K78, K77, K75, K74, K83,          \
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/info.json
> +                {"label":"Enter", "x":13.5, "y":2.25, "w":1.5, "h":2},
(2/9)

```suggestion
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/info.json
> +
Move the Enter key's object to match the updated `id80.h`.

(3/9)

```suggestion
                {"label":"Enter", "x":13.5, "y":2.25, "w":1.5, "h":2},

```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/iso/keymaps/default/keymap.c
> +        KC_CAPS,       KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN,  KC_QUOT,  KC_BSLS,
(4/9)

```suggestion
        KC_TAB,      KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,                 KC_DEL,
        KC_CAPS,       KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN,  KC_QUOT,  KC_BSLS, KC_ENT,
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/iso/keymaps/default/keymap.c
> +        _______,       _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
(5/9)

```suggestion
        _______,     RGB_TOG, _______, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, _______, _______, _______,                 _______,
        _______,       _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/iso/keymaps/via/keymap.c
> +        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS,
(6/9)

```suggestion
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,          KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/iso/keymaps/via/keymap.c
> +        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
(7/9)

```suggestion
        _______, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, _______, _______, _______, _______,          KC_DEL,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/iso/keymaps/via/keymap.c
> +        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
(8/9)

```suggestion
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2021-01-04 18:39 UTC, noroadsleft commented on keyboards/id80/iso/keymaps/via/keymap.c
> +        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
(9/9)

```suggestion
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2021-01-04 18:47 UTC, noroadsleft commented
> ### id80.h
> 
> Maps the wiring of the PCB to the physical location on the board. ANSI and ISO have just one main difference here. ISO is having the split left shift in adding pin 11 in the key layout (being KC_NO on ANSI)

Correct.

> ### keyboard.c
> 
> Maps the physical layout of the board to the keymaps. Here ANSI and ISO are not compatible. ANSI is having KC_ENT on pin 83 and KC_BSLS on pin 96. ISO is the other way around as the routing of the wires is different Physically the Enter key belongs to the A-row on ANSi and to the Q-row on ISO.

I think you meant `keymap.c` here, but that's pretty much it.

> If I understand this right, it is not possible to have VIA on this board and have it working out of the box for both variants. You would need to go to VIA first and reassign the key mapping for the enter key. Based on this I don't know if this is a good idea that one of the variants will not work correctly directly after flashing.
> 
> By the way I have a JSON file her ready for a PR for VIA that adds the left split shift key and the different mapping for Enter via two switches.

Actually, come to think of it, I think this will need more changes to properly support VIA. VIA uses the Vendor and Product ID pairings in `config.h` to identify the connected board. As it stands right now, both the ANSI and ISO variants will use the same pairing, but as you've said, the ANSI and ISO keymaps aren't compatible because the PCBs wire the Enter key differently.

The `PRODUCT_ID` and `PRODUCT` strings from `keyboards/id80/config.h` should be moved to `keyboards/id80/ansi/config.h`, and then a `keyboards/id80/iso/config.h` should be created that has a different `PRODUCT_ID` (I'd suggest `0x0081`) and specifies `PRODUCT` as `ID80 ISO`.

2021-01-07 14:25 UTC, cwr10010 commented
Wait a second.. the changed mapping does not work

2021-01-07 17:10 UTC, cwr10010 commented
@noroadsleft  As written in my last commit I have a problem now with positioning ENT to the home row. When I compile this with VIA support, the ENT shifts all keys on the Q-row one pin to the right with the supposed ENT key. When I deactivate VIA but have the same keymap definition, the keyboard behaves perfectly. Any idea?

2021-01-09 03:36 UTC, noroadsleft commented
@cwr10010 Can you post your VIA JSON file? I'll take a look.

2021-01-09 06:47 UTC, cwr10010 commented
[id80iso.json.zip](https://github.com/qmk/qmk_firmware/files/5790254/id80iso.json.zip)

Hi James, here is the VIA JSON file. I also have a Gist for the layout editor: http://www.keyboard-layout-editor.com/#/gists/f43b8162d839ceb856d2f8093818d561

Thanks!

2021-01-09 10:54 UTC, noroadsleft commented
Hm, the VIA JSON file looks okay. The only things I can think are:

* make sure it's the ISO version's VIA keymap that is flashed to the PCB
  * `make id80/iso:via`, then flash the board – `make id80:via` will compile the ANSI version's VIA keymap instead.
* reset the EEPROM
  1. unplug the board
  2. press and hold the Left Ctrl key
  3. replug the board
  4. release the Left Ctrl key
  5. unplug and replug the board again
* change `KC_BSLS` to `KC_NUHS` in the ISO version's keymaps and reflash the PCB.

Any chance you could post a screenshot of what happens in VIA when you load it on this PCB and keymap? Hard for me to visually/experience as I don't have the board.

2021-01-09 11:28 UTC, cwr10010 commented
I have reset the EEPROM and this did the trick. Mapping works perfectly now also with the VIA keymap. Thank you!

Is there anything left I should do here now?

2021-01-10 22:34 UTC, noroadsleft approved these changes
Looks good to me.

2021-01-11 06:22 UTC, drashna approved these changes

2021-01-11 06:22 UTC, merged

2021-01-11 14:43 UTC, cwr10010 commented
Thanks!