Dbroqua alps64 poker
qmk/qmk_firmware pull request #11254
Opened 2020-12-20 16:45 UTC by Dbroqua

## Description

Added keymap for ALPS64 PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-23 01:39 UTC, drashna requested changes

2020-12-23 01:39 UTC, drashna commented on keyboards/alps64/keymaps/dbroqua/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2020-12-30 03:48 UTC, drashna approved these changes

2020-12-30 04:08 UTC, fauxpark requested changes

2020-12-30 04:08 UTC, fauxpark commented on keyboards/alps64/keymaps/dbroqua/keymap.c
> +    KC_LSFT, _______, KC_Z,    KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,   KC_COMM, KC_DOT,   KC_SLSH,  KC_RSFT,  _______,  \
```suggestion
  [0] = LAYOUT_all(
    KC_GRV,  KC_1,    KC_2,    KC_3,   KC_4,   KC_5,   KC_6,   KC_7,   KC_8,   KC_9,    KC_0,     KC_MINS,  KC_EQL,   _______, KC_BSPC,
    KC_TAB,  KC_Q,    KC_W,    KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,   KC_O,    KC_P,     KC_LBRC,  KC_RBRC,  KC_BSLS,
    KC_CAPS, KC_A,    KC_S,    KC_D,   KC_F,   KC_G,   KC_H,   KC_J,   KC_K,   KC_L,    KC_SCLN,  KC_QUOT,  KC_ENT,
    KC_LSFT, _______, KC_Z,    KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,   KC_COMM, KC_DOT,   KC_SLSH,  KC_RSFT,  _______,
```

2020-12-30 04:08 UTC, fauxpark commented on keyboards/alps64/keymaps/dbroqua/keymap.c
> +    _______,  _______,  KC_APP,   _______,  _______,  _______,  _______,  KC_END,   _______,  _______,  _______,  _______,  _______,  _______, \
```suggestion
  [1] = LAYOUT_all(
    KC_ESC,   KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,   KC_F12,   _______, KC_DEL,
    _______,  _______,  _______,  _______,  _______,  _______,  KC_CALC,  KC_PGUP,  KC_UP,    KC_PGDN,  KC_PSCR,  KC_SLCK,  KC_PAUS,  _______,
    _______,  KC_VOLD,  KC_VOLU,  KC_MUTE,  _______,  _______,  KC_HOME,  KC_LEFT,  KC_DOWN,  KC_RIGHT, KC_INS,   KC_DEL,   _______,
    _______,  _______,  KC_APP,   _______,  _______,  _______,  _______,  KC_END,   _______,  _______,  _______,  _______,  _______,  _______,
```

2021-01-02 14:39 UTC, fauxpark approved these changes

2021-01-06 17:50 UTC, merged