Add GKB-M16 Macro Pad
qmk/qmk_firmware pull request #11262
Opened 2020-12-21 02:11 UTC by gkeyboard

Add GKB-M16 (gkb_m16) Macro Pad under gkeyboard

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-23 01:53 UTC, drashna approved these changes

2020-12-29 23:23 UTC, zvecr requested changes

2020-12-29 23:23 UTC, zvecr commented on keyboards/gkeyboard/gkb_m16/config.h
> +
```suggestion

```

2020-12-29 23:23 UTC, zvecr commented on keyboards/gkeyboard/gkb_m16/keymaps/via/keymap.c
> +
```suggestion

```

2020-12-30 02:46 UTC, fauxpark requested changes

2020-12-30 02:46 UTC, fauxpark commented on keyboards/gkeyboard/gkb_m16/info.json
> +            "key_count": 16,
```suggestion
```

2020-12-30 02:46 UTC, fauxpark commented on keyboards/gkeyboard/gkb_m16/keymaps/default/keymap.c
> +    RGB_TOG,  _______,  QMKBEST,  QMKURL   \
```suggestion
    KC_PGUP,  KC_HOME,  KC_UP,    KC_END ,
    KC_PGDN,  KC_LEFT,  KC_DOWN,  KC_RGHT,
    MO(_FN2), KC_VOLU,  KC_MPLY,  KC_MPRV,
    MO(_FN1), KC_VOLD,  KC_MUTE,  KC_MNXT
  ),
  [_FN1] = LAYOUT_ortho_4x4(
    KC_ESC,   KC_P7,    KC_P8,    KC_P9,
    KC_TAB,   KC_P4,    KC_P5,    KC_P6,
    KC_ENT,   KC_P1,    KC_P2,    KC_P3,
    _______,  KC_P0,    KC_P0,    KC_DOT
  ),
  [_FN2] = LAYOUT_ortho_4x4(
    RGB_MOD,  RGB_HUI,  RGB_SAI,  RGB_VAI,
    RGB_RMOD, RGB_HUD,  RGB_SAD,  RGB_VAD,
    _______,  _______,  _______,  RESET,
    RGB_TOG,  _______,  QMKBEST,  QMKURL
```

2020-12-30 03:39 UTC, drashna approved these changes

2020-12-30 04:09 UTC, fauxpark approved these changes

2021-01-01 23:26 UTC, merged