Added a new keyboard, the [n]40-o
qmk/qmk_firmware pull request #11286
Opened 2020-12-23 09:46 UTC by NightlyBoards

Added [n]40-o. A 40% ortholinear layout pcb with rotary encoder and piezo buzzer support

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-02 00:51 UTC, drashna approved these changes

2021-01-02 14:49 UTC, fauxpark requested changes

2021-01-02 14:49 UTC, fauxpark commented on keyboards/nightly_boards/n40_o/readme.md
> +	make nightly_boards/n40_o:default
```suggestion
    make nightly_boards/n40_o:default
```

2021-01-02 14:49 UTC, fauxpark commented on keyboards/nightly_boards/n40_o/readme.md
> +	make nightly_boards/n40_o:default:flash
```suggestion
    make nightly_boards/n40_o:default:flash
```

2021-01-08 03:26 UTC, fauxpark approved these changes

2021-01-11 06:18 UTC, merged