Added Phantom Solder PCB and KBD8X HS PCB Variants
qmk/qmk_firmware pull request #11282
Opened 2020-12-23 02:57 UTC by mrnoisytiger

Added Phantom Solder PCB variant and upcoming KBD8X HS PCB variants. 

For Phantom Solder, did not include multiple layout options as VIA is the expected use case.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-23 04:45 UTC, drashna reviewed
Could you switch the `LAYOUT_ALL` to `LAYOUT_all`.  Anything after the `LAYOUT` part should be lower case.

2020-12-23 04:45 UTC, drashna commented on keyboards/lucid/phantom_solder/rules.mk
> +LAYOUTS = 65_all
This doesn't appear to be used. 
```suggestion
```

2020-12-23 05:00 UTC, mrnoisytiger commented
@drashna Changes made! Did not realize that convention, thanks for clarifying.

2020-12-29 23:00 UTC, zvecr requested changes

2020-12-29 23:00 UTC, zvecr commented on keyboards/lucid/phantom_solder/readme.md
> +
```suggestion

```

2020-12-29 23:00 UTC, zvecr commented on keyboards/lucid/phantom_solder/rules.mk
> +LAYOUTS = all
```suggestion
```

2020-12-29 23:05 UTC, mrnoisytiger commented on keyboards/lucid/kbd8x_hs/rules.mk
> +LAYOUTS = tkl_ansi tkl_ansi_7u tkl_all
Just for my understanding, what is the purpose of this section? I do see this listing pretty frequently and have not found any documentation regarding it. Would love to be pointed in the right direction here.

2020-12-29 23:05 UTC, mrnoisytiger commented on keyboards/lucid/phantom_solder/rules.mk
> +LAYOUTS = all
Same question as above here.

2020-12-29 23:09 UTC, mrnoisytiger commented
@zvecr I was taking a look at the broken PR Lint and it appears that removing the 
```
LAYOUTS = [...]
```
section is causing the issue. It appears that the `info.json` file is required to match the layouts defined in the `rules.mk`. Can you please clarify why the `LAYOUTS =` in `rules.mk` needed to be removed?

2020-12-30 02:22 UTC, fauxpark commented on keyboards/lucid/kbd8x_hs/rules.mk
> +LAYOUTS = tkl_ansi tkl_ansi_7u tkl_all
https://docs.qmk.fm/#/feature_layouts

2020-12-30 02:24 UTC, fauxpark commented
@mrnoisytiger no, the thing that caused the lint to fail is the renaming of the `LAYOUT_all` macro in info.json to match the definition in <keyboard>.h. This allowed the lint check to match the two up and see that one has more elements than the other:
```
☒ lucid/phantom_solder: LAYOUT_all: Number of elements in info.json does not match! info.json:72 != LAYOUT_all:71
```

2020-12-30 03:24 UTC, mrnoisytiger commented
Thanks @fauxpark. It appears I misread the linting result. I believe I have fixed the issue, as I had an errant key in Row 3. Apologies for the confusion there and thank you for clarifying the usage of the `LAYOUT = ` section.

2020-12-30 04:07 UTC, fauxpark commented
Travis got rate limited, let me just poke it again.

2020-12-30 04:24 UTC, mrnoisytiger commented
Thanks! Looks like checks passed. 😊

2020-12-30 04:30 UTC, fauxpark approved these changes

2021-01-02 00:43 UTC, drashna approved these changes

2021-01-02 00:44 UTC, merged