Add keyboard GRS-70EC
qmk/qmk_firmware pull request #11296
Opened 2020-12-24 13:41 UTC by sekigon-gonnoc

## Description

Add a new keyboard: GRS-70EC

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-29 22:24 UTC, zvecr requested changes

2020-12-29 22:24 UTC, zvecr commented on keyboards/sekigon/grs_70ec/keymaps/default/keymap.c
> +}
```suggestion
```

2020-12-29 22:24 UTC, zvecr commented on keyboards/sekigon/grs_70ec/keymaps/default/keymap.c
> +
```suggestion

```

2020-12-29 22:24 UTC, zvecr commented on keyboards/sekigon/grs_70ec/grs_70ec.c
> +    led_on();
```suggestion
    led_on();
    
    keyboard_post_init_user();
```

2020-12-29 22:24 UTC, zvecr commented on keyboards/sekigon/grs_70ec/grs_70ec.c
> +    writePinHigh(F7);
```suggestion
    writePinHigh(F7);
    
    keyboard_pre_init_user();
```

2020-12-30 02:09 UTC, fauxpark requested changes

2020-12-30 02:09 UTC, fauxpark commented on keyboards/sekigon/grs_70ec/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
CUSTOM_MATRIX = lite
SPLIT_KEYBOARD = yes

SRC += analog.c ec_switch_matrix.c matrix.c
```

2020-12-30 02:09 UTC, fauxpark commented on keyboards/sekigon/grs_70ec/readme.md
> +* A split keyboard using electrostatic capacitive switch
```suggestion
A split keyboard using electrostatic capacitive switch
```

2021-01-02 01:13 UTC, drashna approved these changes

2021-07-15 14:50 UTC, mtei approved these changes
Looks good to me.

2021-07-20 17:23 UTC, drashna commented
Thanks!

2021-07-20 17:24 UTC, merged

2021-07-21 12:07 UTC, fauxpark commented on keyboards/sekigon/grs_70ec/config.h
> +#define MATRIX_COL_PINS { S2, S1, S0, S3, S5, S7, S6, S4 }
The API really does not seem to like this.
https://github.com/qmk/qmk_firmware/runs/3120879453