New keyboard: 0-Sixty
qmk/qmk_firmware pull request #11303
Opened 2020-12-25 20:03 UTC by vinamarora8

## Description

Adds support for a new keyboard: 0-Sixty, a 60 key ortholinear keyboard based on the ProMicro.
A new directory called `0_sixty` is created inside `keyboards/`. To this, all necessary files are added, along with 3 keymaps: default, via, and a personal one.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-02 04:11 UTC, drashna approved these changes

2021-01-02 14:56 UTC, fauxpark requested changes

2021-01-02 14:56 UTC, fauxpark commented on keyboards/0_sixty/0_sixty.h
> +#define LAYOUT_1x2uL(						\
```suggestion
#define LAYOUT_1x2uL( \
```

2021-01-02 14:56 UTC, fauxpark commented on keyboards/0_sixty/readme.md
> +![0-Sixty](https://imgur.com/azmMb6R.jpg)
```suggestion
![0-Sixty](https://imgur.com/azmMb6Rl.jpg)
```

2021-01-02 14:56 UTC, fauxpark commented on keyboards/0_sixty/readme.md
> +![0-Sixty PCB](https://i.imgur.com/I0TkQ0R.jpg)
```suggestion
![0-Sixty PCB](https://i.imgur.com/I0TkQ0Rl.jpg)
```

2021-01-02 14:56 UTC, fauxpark commented on keyboards/0_sixty/readme.md
> +controller.
```suggestion
0-Sixty (pronounced "zero to sixty") is a 60 key ortholinear keyboard inspired by the [Discipline](https://github.com/coseyfannitutti/discipline) and the [Preonic](https://drop.com/buy/preonic-mechanical-keyboard). It is designed as a DIY through-hole kit and uses the ProMicro as its controller.
```

2021-01-02 14:56 UTC, fauxpark commented on keyboards/0_sixty/readme.md
> +twice. The button is placed to the right of the ProMicro.
```suggestion
To be able to flash firmware onto this board, you'll need to bring the ProMicro into bootloader mode. Simply tap the small reset button twice. The button is placed to the right of the ProMicro.
```

2021-01-02 14:56 UTC, fauxpark commented on keyboards/0_sixty/rules.mk
> +NKRO_ENABLE = yes           # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-01-11 06:35 UTC, drashna approved these changes

2021-01-11 09:12 UTC, fauxpark approved these changes

2021-01-11 09:21 UTC, merged

2021-01-11 09:23 UTC, vinamarora8 commented
Thanks a lot! :)