Adding my Planck Keymap
qmk/qmk_firmware pull request #11315
Opened 2020-12-26 20:29 UTC by eshesh2

## Description

Adding my Planck keymap to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-02 06:24 UTC, drashna requested changes

2021-01-02 06:24 UTC, drashna commented on keyboards/planck/keymaps/eshesh2/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-02 15:03 UTC, fauxpark requested changes

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> +# eshesh2's Planck layout with a rotary encoder on the top left of the Planck. It is designed for everyday use along with a numpad layer for quickly typing in Excel and other workbook programs.
```suggestion
![eshesh2's Planck Layout](https://i.imgur.com/eVgHH6k.png)

eshesh2's Planck layout with a rotary encoder on the top left of the Planck. It is designed for everyday use along with a numpad layer for quickly typing in Excel and other workbook programs.
```

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> + * `-----------------------------------------------------------------------------------'
```suggestion

    ,-----------------------------------------------------------------------------------.
    | Mute |   Q  |   W  |   E  |   R  |   T  |   Y  |   U  |   I  |   O  |   P  | Bksp |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    | Tab  |   A  |   S  |   D  |   F  |   G  |   H  |   J  |   K  |   L  |   ;  |  "   |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    | Shift|   Z  |   X  |   C  |   V  |   B  |   N  |   M  |   ,  |   .  |   /  |Enter |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    | Esc  | Ctrl | GUI  | Alt  |Lower |    Space    |Raise | Left | Down |  Up  |Right |
    `-----------------------------------------------------------------------------------'
```

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> +# Qwerty
```suggestion
## Qwerty
```

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> + * `-----------------------------------------------------------------------------------'
```suggestion
## Lower

    ,-----------------------------------------------------------------------------------.
    | Play |   !  |   @  |   #  |   $  |   %  |   ^  |   &  |   *  |   (  |   )  | Bksp |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    | Del  |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |   _  |   +  |   {  |   }  |  |   |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |  F7  |  F8  |  F9  |  F10 |  F11 |  F12 |ISO ~ |ISO | | Home | End  |      |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |      |      |      |      |             |      | Next | Vol- | Vol+ | Play |
    `-----------------------------------------------------------------------------------'
```

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> + * `-----------------------------------------------------------------------------------'
```suggestion
## Raise

    ,-----------------------------------------------------------------------------------.
    |   `  |   1  |   2  |   3  |   4  |   5  |   6  |   7  |   8  |   9  |   0  | Bksp |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    | Del  |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |   -  |   =  |   [  |   ]  |  \   |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |  F7  |  F8  |  F9  |  F10 |  F11 |  F12 |ISO # |ISO / |Pg Up |Pg Dn |      |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |      |      |      |      |             |      | Next | Vol- | Vol+ | Play |
    `-----------------------------------------------------------------------------------'
```

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> + * `-----------------------------------------------------------------------------------'
```suggestion
# Numpad layer

    ,-----------------------------------------------------------------------------------.
    |      |      |  Up  |      |      |      |      |      |NumLck|   7  |  8   |  9   |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      | Left | Down | Right|      |      |      |      |      |   4  |  5   |   6  |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |Enter |  Tab |      |      |      |      |      |      |   1  |  2   |   3  |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    | Exit |      |      |      |      |             |      |      |   .  |  0   |Bksp |
    `-----------------------------------------------------------------------------------'
```

2021-01-02 15:03 UTC, fauxpark commented on keyboards/planck/keymaps/eshesh2/readme.md
> + */
```suggestion
# Adjust (Lower + Raise)

                         v------------------------RGB CONTROL--------------------v
    ,-----------------------------------------------------------------------------------.
    |      | Reset|Debug | RGB  |RGBMOD| HUE+ | HUE- | SAT+ | SAT- |BRGTH+|BRGTH-|  Del |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |      |MUSmod|Aud on|Audoff|AGnorm|AGswap|Qwerty|      |      |Numpad|      |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |Voice-|Voice+|Mus on|Musoff|MIDIon|MIDIof|TermOn|TermOf|      |      |      |
    |------+------+------+------+------+------+------+------+------+------+------+------|
    |      |      |      |      |      |             |      |      |      |      |      |
    `-----------------------------------------------------------------------------------'
```

2021-01-06 18:06 UTC, drashna approved these changes

2021-01-08 03:34 UTC, fauxpark approved these changes

2021-01-11 06:38 UTC, merged