[Keymap] Add peej userspace and keymaps
qmk/qmk_firmware pull request #11332
Opened 2020-12-28 22:02 UTC by peej

Add personal userspace functions and keymaps for boardwalk, lets split, plaid, and planck keyboards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-02 08:41 UTC, drashna commented on users/peej/peej.c
> +    bool is_shifted = keyboard_report->mods & MOD_LSFT;
This may be better: 
```suggestion
    bool is_shifted = get_mods() & MOD_LSFT;
```

2021-01-06 18:24 UTC, drashna requested changes

2021-01-06 18:24 UTC, drashna commented on users/peej/peej.h
> +#endif
This shouldn't be needed, actually.

2021-01-06 18:24 UTC, drashna commented on users/peej/peej.h
> +#define TAPPING_TERM 100
These should be in the config.h file if you want them to be picked up.

2021-01-06 18:24 UTC, drashna commented on users/peej/peej.h
> +#define _ADJUST 16
These should be contiguous, not spread out like this. This generates a larger firmware size, as the empty layers inbetween get populated automagically. 

```suggestion
enum custom_layers {
    _BASE,
    _SYMBOL,
    _FUNCTION,
    _ADJUST,
};
```

2021-01-06 18:24 UTC, drashna commented on users/peej/peej.h
> +#define XXXXXXX KC_NO
These defines aren't necessary, as these are actually defined in the core.  You can safely remove them. 

https://github.com/qmk/qmk_firmware/blob/a0309db983150fd0197eb620a6ba552d90d29f93/quantum/quantum_keycodes.h#L30-L31


```suggestion
```

2021-01-11 06:54 UTC, drashna approved these changes

2021-01-19 02:10 UTC, tzarc approved these changes

2021-01-19 02:10 UTC, merged