Fixed typo in readme.md
qmk/qmk_firmware pull request #11333
Opened 2020-12-28 22:33 UTC by cleichner

censor -> sensor

## Description

Fixing a typo

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-29 02:30 UTC, fauxpark approved these changes

2020-12-29 21:34 UTC, zvecr requested changes
Same spelling mistake is in `keyboards/ploopyco/trackball/readme.md`, can this be updated too.

2020-12-31 14:52 UTC, zvecr approved these changes

2020-12-31 14:53 UTC, merged

2020-12-31 14:53 UTC, zvecr commented
Thanks!