urbanvanilla keymap for drop/alt
qmk/qmk_firmware pull request #11365
Opened 2020-12-30 22:43 UTC by urbanvanilla

## Description

Keymap with simple changes all in userspace for the drop/alt.
Modified matrix.c in the wait_us function to get rid of annoying key chatter that plays this keyboard.
Implemented a really simple RGB timer that turns off RGB Matrix lighting after a set time.
Changed escape key to grave escape.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-07 07:00 UTC, drashna requested changes

2021-01-07 07:00 UTC, drashna commented on keyboards/massdrop/alt/keymaps/urbanvanilla/rules.mk
> +VELOCIKEY_ENABLE = yes # doesn't work with RGB MATRIX only RGB LIGHT :(
Everything but these two lines should be removed.

2021-01-07 22:28 UTC, urbanvanilla commented on keyboards/massdrop/alt/keymaps/urbanvanilla/matrix.c
> +/*
this file has the wait_us() function modification in the uint8_t matrix_scan() function that actually makes the change for key chatter with this keyboard. I've increased it in my latest update. But would it be customary to just put the single function and remove all other code?

2021-01-07 22:36 UTC, urbanvanilla reviewed
made the changes as reviewed, except for the matrix.c not sure if I should clear it all and just have the one function or keep it all with that minor change.

2021-01-08 01:30 UTC, drashna commented on keyboards/massdrop/alt/keymaps/urbanvanilla/matrix.c
> +/*
You mean this delay? 
https://github.com/qmk/qmk_firmware/blob/985b8cab7ca7103aee2b83696824683bd5159888/quantum/matrix.c#L152

If so, that can be set by defining `MATRIX_IO_DELAY`, or replacing the function outright:
https://github.com/qmk/qmk_firmware/blob/985b8cab7ca7103aee2b83696824683bd5159888/quantum/matrix_common.c#L86

2021-01-08 02:19 UTC, zvecr requested changes
With #11472, matrix,.c can be removed and the suggestion applied to get the same behaviour.

2021-01-08 02:19 UTC, zvecr commented on keyboards/massdrop/alt/keymaps/urbanvanilla/config.h
> +
```suggestion

#define MATRIX_IO_DELAY 40

```

2021-01-08 02:45 UTC, urbanvanilla commented on keyboards/massdrop/alt/keymaps/urbanvanilla/matrix.c
> +/*
sorted it out with the later review  by @zvecr, thanks!

2021-01-11 07:06 UTC, drashna commented
This has a bunch of existing commits, that is messing up the diff and such.  
It looks like this may need a rebase to clean stuff up.

2021-01-12 09:26 UTC, fauxpark requested changes

2021-01-12 09:26 UTC, fauxpark commented on keyboards/massdrop/alt/keymaps/urbanvanilla/keymap.c
> +        _______, _______, _______,                            _______,                            _______, _______, _______, _______, _______  \
```suggestion
        KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_HOME,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGUP,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,          KC_UP,   KC_PGDN,
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT, MO(1),   KC_LEFT, KC_DOWN, KC_RGHT
    ),
    [1] = LAYOUT_65_ansi_blocker(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  VLK_TOG, KC_MUTE,
        _______, RGB_SPD, RGB_VAI, RGB_SPI, RGB_HUI, RGB_SAI, _______, U_T_AUTO,U_T_AGCR,_______, KC_PSCR, KC_SLCK, KC_PAUS, _______, KC_END,
        _______, RGB_RMOD,RGB_VAD, RGB_MOD, RGB_HUD, RGB_SAD, _______, _______, _______, _______, _______, _______,          _______, KC_VOLU,
        _______, _______, RGB_TOG, _______, _______, MD_BOOT, NK_TOGG, DBG_TOG, _______, _______, _______, _______,          KC_PGUP, KC_VOLD,
        _______, _______, _______,                            _______,                            _______, _______, KC_HOME, KC_PGDN, KC_END
    ),
    /*
    [X] = LAYOUT(
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______,
        _______, _______, _______,                            _______,                            _______, _______, _______, _______, _______
```

2021-01-13 01:52 UTC, drashna approved these changes

2021-01-13 12:13 UTC, fauxpark approved these changes

2021-01-14 05:52 UTC, merged

2021-01-14 05:52 UTC, drashna commented
Thanks!

2021-01-14 05:56 UTC, urbanvanilla commented
Thanks!