[keyboard] Adding new keyboard UD_40 ortho version
qmk/qmk_firmware pull request #11401
Opened 2021-01-02 01:44 UTC by dejaeghered

## Description

Added PCB for the Ortho version for keyboard UD_40 (directory: mechstudio/ud_40_ortho)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-07 08:31 UTC, drashna requested changes

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/info.json
> +    "LAYOUT": {
```suggestion
    "LAYOUT_ortho_4x12": {
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/default/keymap.c
> +[_MA] = LAYOUT(
```suggestion
[_MA] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/default/keymap.c
> +[_LO] = LAYOUT(
```suggestion
[_LO] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/default/keymap.c
> +[_HI] = LAYOUT(
```suggestion
[_HI] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/via/keymap.c
> +[0] = LAYOUT(
```suggestion
[0] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/via/keymap.c
> +[1] = LAYOUT(
```suggestion
[1] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/via/keymap.c
> +  _______,  KC_LCTRL,    KC_LALT,     KC_LGUI,     MO(1),       KC_SPC,   KC_SPC,   MO(2),    KC_LEFT,  KC_DOWN,  KC_UP,    KC_RGHT),
Via supports tri layer with specific keycodes. 
```suggestion
  _______,  KC_LCTRL,    KC_LALT,     KC_LGUI,     KC_FN13,     KC_SPC,   KC_SPC,   KC_FN23,  KC_LEFT,  KC_DOWN,  KC_UP,    KC_RGHT),
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/via/keymap.c
> +[2] = LAYOUT(
```suggestion
[2] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/keymaps/via/keymap.c
> +[3] = LAYOUT(
```suggestion
[3] = LAYOUT_ortho_4x12(
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/ud_40_ortho.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_ortho_4x12( \
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/ud_40_ortho.h
> +void matrix_scan_user(void);
These shouldn't be needed. 
```suggestion
```

2021-01-07 08:31 UTC, drashna commented on keyboards/mechstudio/ud_40_ortho/rules.mk
> +ENCODER_ENABLE = no
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow
UNICODE_ENABLE = no         # Unicode
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output 
ENCODER_ENABLE = no

LAYOUTS = ortho_4x12
```

2021-01-07 23:44 UTC, dejaeghered commented
@drashna thank you for reviewing.  I merged the suggestions and resolved some syntax issues.

2021-01-08 21:44 UTC, zvecr requested changes

2021-01-08 21:44 UTC, zvecr commented on keyboards/mechstudio/ud_40_ortho/config.h
> +#define DESCRIPTION     "A 40% keyboard by Goldworms"
```suggestion
```

2021-01-08 21:44 UTC, zvecr commented on keyboards/mechstudio/ud_40_ortho/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-01-08 21:44 UTC, zvecr commented on keyboards/mechstudio/ud_40_ortho/ud_40_ortho.h
> +#define XXX KC_NO
Unused
```suggestion
```

2021-01-08 21:44 UTC, zvecr commented on keyboards/mechstudio/ud_40_ortho/rules.mk
> +ENCODER_ENABLE = no
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-01-08 21:44 UTC, zvecr commented on keyboards/mechstudio/ud_40_ortho/keymaps/default/keymap.c
> +#define _HI 2 //High
```suggestion
// Defines names for use in layer keycodes and the keymap
enum layer_names {
    _MA,
    _LO,
    _HI
};
```

2021-01-09 01:15 UTC, fauxpark requested changes

2021-01-09 01:15 UTC, fauxpark commented on keyboards/mechstudio/ud_40_ortho/config.h
> +#define PRODUCT         "UD_40 Ortholinear"
```suggestion
#define MANUFACTURER    Mech Studio
#define PRODUCT         UD_40 Ortholinear
```

2021-01-11 07:26 UTC, drashna approved these changes

2021-01-13 11:41 UTC, fauxpark approved these changes

2021-01-14 05:58 UTC, merged

2021-01-14 05:58 UTC, drashna commented
Thanks!