Add new atreus keymap to planck keyboard
qmk/qmk_firmware pull request #11420
Opened 2021-01-03 13:41 UTC by matthyx

Add new atreus keymap to planck keyboard

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-03 13:45 UTC, matthyx commented
Do I really need to delete this PR and create a new one from a branch?

2021-01-07 08:53 UTC, drashna commented
> Do I really need to delete this PR and create a new one from a branch?

No.  However, the warning/message about it is to help you out, longer term, as working from master can cause issue, over time. 

For now, this is just fine.

2021-01-07 08:55 UTC, drashna requested changes

2021-01-07 08:55 UTC, drashna commented on keyboards/planck/keymaps/atreus/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-07 08:55 UTC, drashna commented on keyboards/planck/keymaps/atreus/keymap.c
> +[0] = KEYMAP(
```suggestion
[0] = LAYOUT_ortho_4x12(
```

2021-01-07 08:55 UTC, drashna commented on keyboards/planck/keymaps/atreus/keymap.c
> +[1] = KEYMAP(
```suggestion
[1] = LAYOUT_ortho_4x12(
```

2021-01-07 08:55 UTC, drashna commented on keyboards/planck/keymaps/atreus/keymap.c
> +[2] = KEYMAP(
```suggestion
[2] = LAYOUT_ortho_4x12(
```

2021-01-07 10:30 UTC, matthyx commented
@drashna thanks, updated

2021-01-07 19:44 UTC, drashna approved these changes

2021-01-08 03:53 UTC, fauxpark approved these changes

2021-01-10 04:01 UTC, merged