add bella rgb keyboards
qmk/qmk_firmware pull request #11438
Opened 2021-01-05 03:20 UTC by moyi4681

add bella rgb keyboards

2021-01-07 09:16 UTC, drashna requested changes

2021-01-07 09:16 UTC, drashna commented on keyboards/kbdfans/bella/rgb/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
# Bootloader
BOOTLOADER = atmel-dfu
```

2021-01-07 09:16 UTC, drashna commented on keyboards/kbdfans/bella/rgb_iso/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
# Bootloader
BOOTLOADER = atmel-dfu
```

2021-01-08 02:27 UTC, drashna approved these changes

2021-01-08 22:01 UTC, zvecr requested changes

2021-01-08 22:01 UTC, zvecr commented on keyboards/kbdfans/bella/rgb/info.json
> +        "LAYOUT": {
May need further changes, but at a minimum
```suggestion
        "LAYOUT_all": {
```

2021-01-08 22:01 UTC, zvecr commented on keyboards/kbdfans/bella/rgb_iso/info.json
> +        "LAYOUT": {
May need further changes, but at a minimum
```suggestion
        "LAYOUT_all": {
```

2021-01-08 22:02 UTC, zvecr requested changes

2021-01-08 22:02 UTC, zvecr commented on keyboards/kbdfans/bella/rgb/config.h
> +#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2
```suggestion
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
```

2021-01-08 22:02 UTC, zvecr commented on keyboards/kbdfans/bella/rgb_iso/config.h
> +#endif
```suggestion
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
```

2021-01-09 01:01 UTC, fauxpark requested changes

2021-01-09 01:01 UTC, fauxpark commented on keyboards/kbdfans/bella/rgb_iso/rules.mk
> +RGB_MATRIX_ENABLE = IS31FL3741 # Use RGB matrix
```suggestion
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3741
```

2021-01-09 01:01 UTC, fauxpark commented on keyboards/kbdfans/bella/rgb/rules.mk
> +# Bootloader
```suggestion
# Bootloader selection
```

2021-01-09 01:01 UTC, fauxpark commented on keyboards/kbdfans/bella/rgb/rules.mk
> +RGB_MATRIX_ENABLE = IS31FL3741 # Use RGB matrix
```suggestion
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3741
```

2021-01-09 01:03 UTC, fauxpark requested changes

2021-01-09 01:03 UTC, fauxpark commented on keyboards/kbdfans/bella/rgb/rules.mk
> +BOOTMAGIC_ENABLE = lite        # Virtual DIP switch configuration
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite        # Virtual DIP switch configuration
```

2021-01-30 05:12 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/11438/files).

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
Flashing example for this keyboard:

    make kbdfans/bella/rgb:default:flash

## Accessing Bootloader Mode

To reset the board into bootloader mode, hold the key at the top left of the keyboard while connecting the USB cable (also erases persistent settings).

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/config.h
> +#define PRODUCT         BELLA_RGB_ISO
```suggestion
#define PRODUCT         BELLA RGB ISO
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/rgb_iso.h
> +#define LAYOUT_all( \
```suggestion
#define LAYOUT( \
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/rgb_iso.h
> +	K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311,       K213,       K315, \
Moves the ISO Enter key to the home row in the keymaps.

```suggestion
	K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211, K212,             K215, \
	K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311, K213, K313,       K315, \
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/info.json
> +    "keyboard_name": "bella_rgb_iso",
```suggestion
    "keyboard_name": "BELLA RGB ISO", 
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/info.json
> +        "LAYOUT_all": {
```suggestion
        "LAYOUT": {
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/info.json
> +            "layout": [{"label":"Esc", "x":0, "y":0}, {"label":"F1", "x":2, "y":0}, {"label":"F2", "x":3, "y":0}, {"label":"F3", "x":4, "y":0}, {"label":"F4", "x":5, "y":0}, {"label":"F5", "x":6.5, "
```suggestion
            "layout": [{"label":"Esc", "x":0, "y":0}, {"label":"F1", "x":2, "y":0}, {"label":"F2", "x":3, "y":0}, {"label":"F3", "x":4, "y":0}, {"label":"F4", "x":5, "y":0}, {"label":"F5", "x":6.5, "y":0}, {"label":"F6", "x":7.5, "y":0}, {"label":"F7", "x":8.5, "y":0}, {"label":"F8", "x":9.5, "y":0}, {"label":"F9", "x":11, "y":0}, {"label":"F10", "x":12, "y":0}, {"label":"F11", "x":13, "y":0}, {"label":"F12", "x":14, "y":0}, {"label":"Page Up", "x":15.25, "y":0}, {"label":"~", "x":0, "y":1}, {"label":"!", "x":1, "y":1}, {"label":"@", "x":2, "y":1}, {"label":"#", "x":3, "y":1}, {"label":"$", "x":4, "y":1}, {"label":"%", "x":5, "y":1}, {"label":"^", "x":6, "y":1}, {"label":"&", "x":7, "y":1}, {"label":"*", "x":8, "y":1}, {"label":"(", "x":9, "y":1}, {"label":")", "x":10, "y":1}, {"label":"_", "x":11, "y":1}, {"label":"+", "x":12, "y":1}, {"label":"Backspace", "x":13, "y":1, "w":2}, {"label":"Insert", "x":15.25, "y":1}, {"label":"Tab", "x":0, "y":2, "w":1.5}, {"label":"Q", "x":1.5, "y":2}, {"label":"W", "x":2.5, "y":2}, {"label":"E", "x":3.5, "y":2}, {"label":"R", "x":4.5, "y":2}, {"label":"T", "x":5.5, "y":2}, {"label":"Y", "x":6.5, "y":2}, {"label":"U", "x":7.5, "y":2}, {"label":"I", "x":8.5, "y":2}, {"label":"O", "x":9.5, "y":2}, {"label":"P", "x":10.5, "y":2}, {"label":"{", "x":11.5, "y":2}, {"label":"}", "x":12.5, "y":2}, {"label":"Delete", "x":15.25, "y":2}, {"label":"Caps Lock", "x":0, "y":3, "w":1.75}, {"label":"A", "x":1.75, "y":3}, {"label":"S", "x":2.75, "y":3}, {"label":"D", "x":3.75, "y":3}, {"label":"F", "x":4.75, "y":3}, {"label":"G", "x":5.75, "y":3}, {"label":"H", "x":6.75, "y":3}, {"label":"J", "x":7.75, "y":3}, {"label":"K", "x":8.75, "y":3}, {"label":"L", "x":9.75, "y":3}, {"label":":", "x":10.75, "y":3}, {"label":"\"", "x":11.75, "y":3}, {"label":"~", "x":12.75, "y":3}, {"label":"Enter", "x":13.75, "y":2, "w":1.25, "h":2}, {"label":"Page Down", "x":15.25, "y":3}, {"label":"Shift", "x":0, "y":4, "w":1.25}, {"label":"|", "x":1.25, "y":4}, {"label":"Z", "x":2.25, "y":4}, {"label":"X", "x":3.25, "y":4}, {"label":"C", "x":4.25, "y":4}, {"label":"V", "x":5.25, "y":4}, {"label":"B", "x":6.25, "y":4}, {"label":"N", "x":7.25, "y":4}, {"label":"M", "x":8.25, "y":4}, {"label":"<", "x":9.25, "y":4}, {"label":">", "x":10.25, "y":4}, {"label":"?", "x":11.25, "y":4}, {"label":"Shift", "x":12.25, "y":4, "w":1.75}, {"label":"\u2191", "x":14.25, "y":4.25}, {"label":"Ctrl", "x":0, "y":5, "w":1.25}, {"label":"Win", "x":1.25, "y":5, "w":1.25}, {"label":"Alt", "x":2.5, "y":5, "w":1.25}, {"x":3.75, "y":5, "w":6.25}, {"label":"Alt", "x":10, "y":5, "w":1.5}, {"label":"Fn", "x":11.5, "y":5, "w":1.5}, {"label":"\u2190", "x":13.25, "y":5.25}, {"label":"\u2193", "x":14.25, "y":5.25}, {"label":"\u2192", "x":15.25, "y":5.25}]
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/default/keymap.c
> +	LAYOUT_all(
```suggestion
	LAYOUT(
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/default/keymap.c
> +		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_PGDN,
```suggestion
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC,         KC_DEL, 
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT, KC_PGDN, 
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/default/keymap.c
> +	LAYOUT_all(
```suggestion
	LAYOUT(
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/default/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET, KC_TRNS,
```suggestion
		KC_TRNS, RGB_MOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET, EEP_RST, KC_TRNS, 
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/via/keymap.c
> +	LAYOUT_all(
```suggestion
	LAYOUT(
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/via/keymap.c
> +		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_PGDN,
```suggestion
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC,        KC_DEL, 
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT, KC_PGDN, 
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/via/keymap.c
> +	LAYOUT_all(
```suggestion
	LAYOUT(
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/keymaps/via/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET,   KC_TRNS,
```suggestion
		KC_TRNS, RGB_MOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET,   EEP_RST, KC_TRNS, 
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/readme.md
> +# BELLA_RGB_ISO (Hotswap)
```suggestion
# BELLA RGB ISO (Hotswap)
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/readme.md
> +* Hardware Supported: BELLA_RGB_ISO
```suggestion
* Hardware Supported: BELLA RGB ISO (ATmega32U4)
```

2021-01-30 05:12 UTC, noroadsleft commented on keyboards/kbdfans/bella/rgb_iso/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
Flashing example for this keyboard:

    make kbdfans/bella/rgb_iso:default:flash

## Accessing Bootloader Mode

To reset the board into bootloader mode, hold the key at the top left of the keyboard while connecting the USB cable (also erases persistent settings).

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2021-02-04 21:56 UTC, noroadsleft commented
@moyi4681 I took the liberty of applying the remaining suggestions I had left that you missed to your pull request, because they were the only things remaining to make it merge-ready, and the compilation wouldn't have worked without them.

Thanks!

2021-02-04 21:58 UTC, merged