Leafcutterlabs
qmk/qmk_firmware pull request #11464
Opened 2021-01-07 15:12 UTC by LeafCutterLabs

## Description

Correcting/removing the tap dance error from configurator

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Configurator was giving an error due to the use of Tap Dance, the tap dance button was removed

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-07 19:07 UTC, drashna approved these changes

2021-01-08 03:57 UTC, fauxpark approved these changes

2021-01-08 21:19 UTC, zvecr requested changes
This doesnt actually have any changes in comparison to master. I would recommend you do not reuse the same branch as before, as that is part of the issue here.

2021-01-09 13:34 UTC, LeafCutterLabs reviewed
remove tap dance

2021-01-09 13:34 UTC, fauxpark requested changes

2021-01-09 13:34 UTC, fauxpark commented on keyboards/leafcutterlabs/bigknob/rules.mk
> +TAP_DANCE_ENABLE = no
```suggestion
```

2021-01-09 13:44 UTC, LeafCutterLabs reviewed
removed tap dance

2021-01-09 22:20 UTC, drashna approved these changes

2021-01-09 22:21 UTC, drashna commented
Looks like you have some merge conflicts here.

2021-01-16 14:36 UTC, LeafCutterLabs reviewed
removing/resolving conflicts

2021-01-16 14:44 UTC, LeafCutterLabs reviewed
trying tp pass test

2021-01-16 14:57 UTC, LeafCutterLabs reviewed
local compiles fine but fails travis?

2021-01-16 15:24 UTC, fauxpark commented
Tap Dance should not be enabled at the keyboard level, since it expects custom code to be present in the keymap, but the Configurator does not use the default keymap, where it would be defined.

2021-01-16 15:24 UTC, fauxpark approved these changes

2021-01-20 02:51 UTC, merged