Add CherryB Studio Keyboards
qmk/qmk_firmware pull request #11475
Opened 2021-01-08 18:23 UTC by duongaanh

## Description

This PR add new keyboards from CherryB Studio for community access and development. 
First we added the CB87 and many newer projects coming later.
For more info, please visis our Discord: [https://discord.gg/qVwv3gcq83](url)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-08 20:40 UTC, duongaanh commented
Need help about lint check. I thought there was some conflict with layout name define but not, seem lack of something, can anyone help me ?
` cherrybstudio/CB87: Missing LAYOUT() macro for tkl_ansi`

2021-01-08 21:12 UTC, zvecr requested changes
Also, all filenames should be lowercase per PR checklist and <https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=naming-your-keyboardproject>

2021-01-08 21:12 UTC, zvecr commented on keyboards/cherrybstudio/CB87/CB87.c
> +}
```suggestion
#include "cb87.h"
```

2021-01-08 21:12 UTC, zvecr commented on keyboards/cherrybstudio/CB87/config.h
> +#define DESCRIPTION     CB87 TKL Rev1
```suggestion
```

2021-01-08 21:12 UTC, zvecr commented on keyboards/cherrybstudio/CB87/config.h
> +#define CAPS_LOCK_LED_PIN F0
```suggestion
#define LED_CAPS_LOCK_PIN F0
```

2021-01-08 21:12 UTC, zvecr commented on keyboards/cherrybstudio/CB87/readme.md
> +    make cherrybstudio/CB87:default:flash
```suggestion
    make cherrybstudio/cb87:default

Flashing example for this keyboard:

    make cherrybstudio/cb87:default:flash
```

2021-01-08 21:22 UTC, zvecr requested changes

2021-01-08 21:22 UTC, zvecr commented on keyboards/cherrybstudio/CB87/cb87.c
> +}
This should not be added back
```suggestion
```

2021-01-08 22:31 UTC, zvecr requested changes
Still have uppercase folders.

2021-01-08 22:31 UTC, zvecr commented on keyboards/cherrybstudio/CB87/config.h
> +#define LED_CAPS_LOCK_PIN F0
```suggestion
#define LED_CAPS_LOCK_PIN F0
#define LED_SCROLL_LOCK_PIN F4
```

2021-01-08 22:31 UTC, zvecr commented on keyboards/cherrybstudio/CB87/cb87.c
> +}
Please... stop
```suggestion
```

2021-01-09 00:33 UTC, fauxpark requested changes

2021-01-09 00:33 UTC, fauxpark commented on keyboards/cherrybstudio/CB87/readme.md
> +![CB87](https://i.imgur.com/balJ20X.png)
```suggestion
![CB87](https://i.imgur.com/balJ20Xl.png)
```

2021-01-09 09:38 UTC, duongaanh commented on keyboards/cherrybstudio/CB87/cb87.c
> +}
aight thanks I will edit it

2021-01-09 12:49 UTC, fauxpark requested changes

2021-01-09 12:49 UTC, fauxpark commented on keyboards/cherrybstudio/cb87/readme.md
> +![CB87](https://i.imgur.com/balJ20X.png)
```suggestion
![CB87](https://i.imgur.com/balJ20Xl.png)
```

2021-01-09 12:49 UTC, fauxpark commented on keyboards/cherrybstudio/cb87/keymaps/default/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
This layer should be a default TKL layout.

2021-01-24 21:46 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/11475/files).

2021-01-24 21:46 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +		KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
Converting tabs to spaces...

```suggestion
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
```

2021-01-24 21:46 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2021-01-24 21:46 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
    [3] = LAYOUT_tkl_ansi(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2021-01-24 21:46 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
    [3] = LAYOUT_tkl_ansi(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2021-01-24 21:46 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/default/keymap.c
> +    ),
```suggestion
    [0] = LAYOUT_tkl_ansi(
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,             KC_PSCR, KC_SLCK, KC_PAUS,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,   KC_INS,  KC_HOME, KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,   KC_DEL,  KC_END,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
        KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,     KC_RSFT,                 KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                                      KC_RALT, KC_RGUI, KC_APP,  KC_RCTL,   KC_LEFT, KC_DOWN, KC_RGHT
    ),
      [2] = LAYOUT_tkl_ansi(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS,                 KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS,                                     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS
    ),
```

2021-01-24 21:46 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
## Accessing Bootloader Mode

To access Bootloader Mode, do one of the following:

* Tap the Reset switch mounted on the top side of the PCB to the left of the spacebar
* Hold the top left key of the keyboard while connecting the USB cable

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2021-02-04 22:58 UTC, noroadsleft requested changes
I just realized that this keyboard isn't `LAYOUT_tkl_ansi`, though that layout is supported.

I'll post a second review after this changeset is applied that will add `tkl_ansi` and `tkl_iso` support.

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/cb87.h
> +#define LAYOUT_tkl_ansi( \
This should actually be:

```suggestion
#define LAYOUT_all( \
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/info.json
> +        "LAYOUT_tkl_ansi": {
```suggestion
        "LAYOUT_all": {
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/default/keymap.c
> +    [0] = LAYOUT_tkl_ansi(
```suggestion
    [0] = LAYOUT_all(
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/default/keymap.c
> +      [2] = LAYOUT_tkl_ansi(
```suggestion
    [2] = LAYOUT_all(
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +    [0] = LAYOUT_tkl_ansi(
```suggestion
    [0] = LAYOUT_all(
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +      [2] = LAYOUT_tkl_ansi(
The layers are misnumbered from here down.

```suggestion
    [1] = LAYOUT_all(
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +    [3] = LAYOUT_tkl_ansi(
```suggestion
    [2] = LAYOUT_all(
```

2021-02-04 22:58 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +    [3] = LAYOUT_tkl_ansi(
```suggestion
    [3] = LAYOUT_tkl_ansi(
```

2021-02-07 16:55 UTC, drashna approved these changes

2021-02-07 18:49 UTC, fauxpark requested changes
This board is missing a layout macro for `tkl_ansi`, which you have specified in the rules.mk.

2021-03-06 00:35 UTC, noroadsleft requested changes
Adding layout macros for Community Layout support, and fixing a couple minor issues.

2021-03-06 00:35 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/cb87.h
> +
```suggestion

#define LAYOUT_tkl_ansi( \
    K000,      K001, K002, K003, K004,   K005, K006, K007, K008,    K009, K100, K101, K102,    K103, K104, K105, \
    K106, K107, K108, K109, K200, K201, K202, K203, K204, K205, K206, K207, K208,     K209,    K300, K301, K302, \
    K303,   K304, K305, K306, K307, K308, K309, K400, K401, K402, K403, K404, K405,   K406,    K407, K408, K409, \
    K500,    K501, K502, K503, K504, K505, K506, K507, K508, K509, K600, K601,        K603,                      \
    K604,       K606, K607, K608, K609, K700, K701, K702, K703, K704, K705,           K706,          K707,       \
    K708,  K709,  K800,              K801,                K802,  K803,  K804,    K805,         K806, K807, K808  \
) { \
    { K000,  K001,  K002,  K003,  K004,  K005,  K006,  K007,  K008,  K009 }, \
    { K100,  K101,  K102,  K103,  K104,  K105,  K106,  K107,  K108,  K109 }, \
    { K200,  K201,  K202,  K203,  K204,  K205,  K206,  K207,  K208,  K209 }, \
    { K300,  K301,  K302,  K303,  K304,  K305,  K306,  K307,  K308,  K309 }, \
    { K400,  K401,  K402,  K403,  K404,  K405,  K406,  K407,  K408,  K409 }, \
    { K500,  K501,  K502,  K503,  K504,  K505,  K506,  K507,  K508,  K509 }, \
    { K600,  K601,  KC_NO, K603,  K604,  KC_NO, K606,  K607,  K608,  K609 }, \
    { K700,  K701,  K702,  K703,  K704,  K705,  K706,  K707,  K708,  K709 }, \
    { K800,  K801,  K802,  K803,  K804,  K805,  K806,  K807,  K808,  KC_NO }  \
}

#define LAYOUT_tkl_iso( \
    K000,      K001, K002, K003, K004,   K005, K006, K007, K008,    K009, K100, K101, K102,    K103, K104, K105, \
    K106, K107, K108, K109, K200, K201, K202, K203, K204, K205, K206, K207, K208,     K209,    K300, K301, K302, \
    K303,   K304, K305, K306, K307, K308, K309, K400, K401, K402, K403, K404, K405,            K407, K408, K409, \
    K500,    K501, K502, K503, K504, K505, K506, K507, K508, K509, K600, K601, K602,  K603,                      \
    K604, K605, K606, K607, K608, K609, K700, K701, K702, K703, K704, K705,           K706,          K707,       \
    K708,  K709,  K800,              K801,                K802,  K803,  K804,    K805,         K806, K807, K808  \
) { \
    { K000,  K001,  K002,  K003,  K004,  K005,  K006,  K007,  K008,  K009 }, \
    { K100,  K101,  K102,  K103,  K104,  K105,  K106,  K107,  K108,  K109 }, \
    { K200,  K201,  K202,  K203,  K204,  K205,  K206,  K207,  K208,  K209 }, \
    { K300,  K301,  K302,  K303,  K304,  K305,  K306,  K307,  K308,  K309 }, \
    { K400,  K401,  K402,  K403,  K404,  K405,  KC_NO, K407,  K408,  K409 }, \
    { K500,  K501,  K502,  K503,  K504,  K505,  K506,  K507,  K508,  K509 }, \
    { K600,  K601,  K602,  K603,  K604,  K605,  K606,  K607,  K608,  K609 }, \
    { K700,  K701,  K702,  K703,  K704,  K705,  K706,  K707,  K708,  K709 }, \
    { K800,  K801,  K802,  K803,  K804,  K805,  K806,  K807,  K808,  KC_NO }  \
}
```

2021-03-06 00:35 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/info.json
> +        }
```suggestion
        },
        "LAYOUT_tkl_ansi": {
            "layout": [
                {"x":0, "y":0},
                {"x":2, "y":0},
                {"x":3, "y":0},
                {"x":4, "y":0},
                {"x":5, "y":0},
                {"x":6.5, "y":0},
                {"x":7.5, "y":0},
                {"x":8.5, "y":0},
                {"x":9.5, "y":0},
                {"x":11, "y":0},
                {"x":12, "y":0},
                {"x":13, "y":0},
                {"x":14, "y":0},
                {"x":15.25, "y":0},
                {"x":16.25, "y":0},
                {"x":17.25, "y":0},

                {"x":0, "y":1.5},
                {"x":1, "y":1.5},
                {"x":2, "y":1.5},
                {"x":3, "y":1.5},
                {"x":4, "y":1.5},
                {"x":5, "y":1.5},
                {"x":6, "y":1.5},
                {"x":7, "y":1.5},
                {"x":8, "y":1.5},
                {"x":9, "y":1.5},
                {"x":10, "y":1.5},
                {"x":11, "y":1.5},
                {"x":12, "y":1.5},
                {"x":13, "y":1.5, "w":2},
                {"x":15.25, "y":1.5},
                {"x":16.25, "y":1.5},
                {"x":17.25, "y":1.5},

                {"x":0, "y":2.5, "w":1.5},
                {"x":1.5, "y":2.5},
                {"x":2.5, "y":2.5},
                {"x":3.5, "y":2.5},
                {"x":4.5, "y":2.5},
                {"x":5.5, "y":2.5},
                {"x":6.5, "y":2.5},
                {"x":7.5, "y":2.5},
                {"x":8.5, "y":2.5},
                {"x":9.5, "y":2.5},
                {"x":10.5, "y":2.5},
                {"x":11.5, "y":2.5},
                {"x":12.5, "y":2.5},
                {"x":13.5, "y":2.5, "w":1.5},
                {"x":15.25, "y":2.5},
                {"x":16.25, "y":2.5},
                {"x":17.25, "y":2.5},

                {"x":0, "y":3.5, "w":1.75},
                {"x":1.75, "y":3.5},
                {"x":2.75, "y":3.5},
                {"x":3.75, "y":3.5},
                {"x":4.75, "y":3.5},
                {"x":5.75, "y":3.5},
                {"x":6.75, "y":3.5},
                {"x":7.75, "y":3.5},
                {"x":8.75, "y":3.5},
                {"x":9.75, "y":3.5},
                {"x":10.75, "y":3.5},
                {"x":11.75, "y":3.5},
                {"x":12.75, "y":3.5, "w":2.25},

                {"x":0, "y":4.5, "w":2.25},
                {"x":2.25, "y":4.5},
                {"x":3.25, "y":4.5},
                {"x":4.25, "y":4.5},
                {"x":5.25, "y":4.5},
                {"x":6.25, "y":4.5},
                {"x":7.25, "y":4.5},
                {"x":8.25, "y":4.5},
                {"x":9.25, "y":4.5},
                {"x":10.25, "y":4.5},
                {"x":11.25, "y":4.5},
                {"x":12.25, "y":4.5, "w":2.75},
                {"x":16.25, "y":4.5},

                {"x":0, "y":5.5, "w":1.25},
                {"x":1.25, "y":5.5, "w":1.25},
                {"x":2.5, "y":5.5, "w":1.25},
                {"x":3.75, "y":5.5, "w":6.25},
                {"x":10, "y":5.5, "w":1.25},
                {"x":11.25, "y":5.5, "w":1.25},
                {"x":12.5, "y":5.5, "w":1.25},
                {"x":13.75, "y":5.5, "w":1.25},
                {"x":15.25, "y":5.5},
                {"x":16.25, "y":5.5},
                {"x":17.25, "y":5.5}
            ]
        },
        "LAYOUT_tkl_iso": {
            "layout": [
                {"x":0, "y":0},
                {"x":2, "y":0},
                {"x":3, "y":0},
                {"x":4, "y":0},
                {"x":5, "y":0},
                {"x":6.5, "y":0},
                {"x":7.5, "y":0},
                {"x":8.5, "y":0},
                {"x":9.5, "y":0},
                {"x":11, "y":0},
                {"x":12, "y":0},
                {"x":13, "y":0},
                {"x":14, "y":0},
                {"x":15.25, "y":0},
                {"x":16.25, "y":0},
                {"x":17.25, "y":0},

                {"x":0, "y":1.5},
                {"x":1, "y":1.5},
                {"x":2, "y":1.5},
                {"x":3, "y":1.5},
                {"x":4, "y":1.5},
                {"x":5, "y":1.5},
                {"x":6, "y":1.5},
                {"x":7, "y":1.5},
                {"x":8, "y":1.5},
                {"x":9, "y":1.5},
                {"x":10, "y":1.5},
                {"x":11, "y":1.5},
                {"x":12, "y":1.5},
                {"x":13, "y":1.5, "w":2},
                {"x":15.25, "y":1.5},
                {"x":16.25, "y":1.5},
                {"x":17.25, "y":1.5},

                {"x":0, "y":2.5, "w":1.5},
                {"x":1.5, "y":2.5},
                {"x":2.5, "y":2.5},
                {"x":3.5, "y":2.5},
                {"x":4.5, "y":2.5},
                {"x":5.5, "y":2.5},
                {"x":6.5, "y":2.5},
                {"x":7.5, "y":2.5},
                {"x":8.5, "y":2.5},
                {"x":9.5, "y":2.5},
                {"x":10.5, "y":2.5},
                {"x":11.5, "y":2.5},
                {"x":12.5, "y":2.5},
                {"x":15.25, "y":2.5},
                {"x":16.25, "y":2.5},
                {"x":17.25, "y":2.5},

                {"x":0, "y":3.5, "w":1.75},
                {"x":1.75, "y":3.5},
                {"x":2.75, "y":3.5},
                {"x":3.75, "y":3.5},
                {"x":4.75, "y":3.5},
                {"x":5.75, "y":3.5},
                {"x":6.75, "y":3.5},
                {"x":7.75, "y":3.5},
                {"x":8.75, "y":3.5},
                {"x":9.75, "y":3.5},
                {"x":10.75, "y":3.5},
                {"x":11.75, "y":3.5},
                {"x":12.75, "y":3.5},
                {"x":13.75, "y":2.5, "w":1.25, "h":2},

                {"x":0, "y":4.5, "w":1.25},
                {"x":1.25, "y":4.5},
                {"x":2.25, "y":4.5},
                {"x":3.25, "y":4.5},
                {"x":4.25, "y":4.5},
                {"x":5.25, "y":4.5},
                {"x":6.25, "y":4.5},
                {"x":7.25, "y":4.5},
                {"x":8.25, "y":4.5},
                {"x":9.25, "y":4.5},
                {"x":10.25, "y":4.5},
                {"x":11.25, "y":4.5},
                {"x":12.25, "y":4.5, "w":2.75},
                {"x":16.25, "y":4.5},

                {"x":0, "y":5.5, "w":1.25},
                {"x":1.25, "y":5.5, "w":1.25},
                {"x":2.5, "y":5.5, "w":1.25},
                {"x":3.75, "y":5.5, "w":6.25},
                {"x":10, "y":5.5, "w":1.25},
                {"x":11.25, "y":5.5, "w":1.25},
                {"x":12.5, "y":5.5, "w":1.25},
                {"x":13.75, "y":5.5, "w":1.25},
                {"x":15.25, "y":5.5},
                {"x":16.25, "y":5.5},
                {"x":17.25, "y":5.5}
            ]
        }
```

2021-03-06 00:35 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/default/keymap.c
> +    [2] = LAYOUT_all(
Should be Layers 0 and 1, not 0 and 2.

```suggestion
    [1] = LAYOUT_all(
```

2021-03-06 00:35 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/keymaps/via/keymap.c
> +    [3] = LAYOUT_tkl_ansi(
This was my mistake on a previous review.

```suggestion
    [3] = LAYOUT_all(
```

2021-03-06 00:35 UTC, noroadsleft commented on keyboards/cherrybstudio/cb87/rules.mk
> +LAYOUTS = tkl_ansi
```suggestion
LAYOUTS = tkl_ansi tkl_iso
```

2021-03-23 21:25 UTC, duongaanh reviewed
fixed code issues. Big thanks to QMK Community ;)

2021-03-24 02:02 UTC, fauxpark approved these changes

2021-04-02 21:25 UTC, drashna commented
Thanks!

2021-04-02 21:25 UTC, merged