Whale 75
qmk/qmk_firmware pull request #11486
Opened 2021-01-09 14:09 UTC by ebastler

## Description

Adds support for the Linworks Whale75 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for Linworks Whale75 keyboard

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-09 20:21 UTC, zvecr requested changes

2021-01-09 20:21 UTC, zvecr commented on keyboards/linworks/whale75/whale75.c
> +}
```suggestion

```

2021-01-09 20:21 UTC, zvecr commented on keyboards/linworks/whale75/config.h
> +
```suggestion

#define LED_NUM_LOCK_PIN A8
#define LED_CAPS_LOCK_PIN A9
#define LED_SCROLL_LOCK_PIN A13
#define LED_PIN_ON_STATE 0

```

2021-01-10 03:19 UTC, drashna requested changes

2021-01-10 03:19 UTC, drashna commented on keyboards/linworks/whale75/config.h
> +#define RGB_DI_PIN B9
You have this defined twice
```suggestion
```

2021-01-10 13:05 UTC, ebastler commented on keyboards/linworks/whale75/config.h
> +#define RGB_DI_PIN B9
ooops. thanks!

2021-01-11 02:38 UTC, fauxpark requested changes

2021-01-11 02:38 UTC, fauxpark commented on keyboards/linworks/whale75/info.json
> +      "key_count": 80,
```suggestion
```

2021-01-11 02:38 UTC, fauxpark commented on keyboards/linworks/whale75/info.json
> +        "key_count": 79,
```suggestion
```

2021-01-11 02:38 UTC, fauxpark commented on keyboards/linworks/whale75/info.json
> +        "key_count": 81,
```suggestion
```

2021-01-11 02:38 UTC, fauxpark commented on keyboards/linworks/whale75/info.json
> +        "key_count": 80,
```suggestion
```

2021-01-23 17:27 UTC, Erovia requested changes

2021-01-23 17:27 UTC, Erovia commented on keyboards/linworks/whale75/readme.md
> +# Lx3 Whale 75
Can you make this to be more in line with our [current template](https://github.com/qmk/qmk_firmware/blob/master/quantum/template/avr/readme.md)?

2021-01-23 18:34 UTC, ebastler commented
Thanks @Erovia - I modified the readme.md to fit the template. I am still waiting for a picture from the keyboard designer, which he will send me on monday, I think. I pushed the file the way it is (without a link) for now.

2021-01-23 21:27 UTC, drashna approved these changes

2021-01-24 00:07 UTC, drashna approved these changes

2021-01-31 22:21 UTC, ebastler commented
Readme fixed - it follows the example now.

2021-02-04 20:56 UTC, fauxpark approved these changes

2021-02-07 16:54 UTC, merged