Add Rect44 keyboard
qmk/qmk_firmware pull request #11484
Opened 2021-01-09 09:40 UTC by koshinoya

## Description
A 44-48 keys ANSI/ISO layout keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-09 21:11 UTC, zvecr requested changes

2021-01-09 21:11 UTC, zvecr commented on keyboards/rect44/keymaps/ansi_44key/config.h
> +/* Copyright 2020-2021 koshinoya
This file should be removed

2021-01-09 21:11 UTC, zvecr commented on keyboards/rect44/keymaps/ansi_47key/config.h
> +/* Copyright 2020-2021 koshinoya
This file should be removed

2021-01-09 21:11 UTC, zvecr commented on keyboards/rect44/keymaps/default/config.h
> +/* Copyright 2020-2021 koshinoya
This file should be removed

2021-01-09 21:11 UTC, zvecr commented on keyboards/rect44/keymaps/iso_48key/config.h
> +/* Copyright 2020-2021 koshinoya
This file should be removed

2021-01-09 21:11 UTC, zvecr commented on keyboards/rect44/readme.md
> +    make rect44:ansi_44key
```suggestion
    make rect44:default

Flashing example for this keyboard:

    make rect44:default:flash
```

2021-01-11 02:37 UTC, fauxpark requested changes

2021-01-11 02:37 UTC, fauxpark commented on keyboards/rect44/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-01-11 02:37 UTC, fauxpark commented on keyboards/rect44/readme.md
> +![Rect44](https://i.imgur.com/TWXGnfm.jpg)
```suggestion
![Rect44](https://i.imgur.com/TWXGnfml.jpg)
```

2021-01-11 08:21 UTC, drashna commented on keyboards/rect44/config.h
> +#define PRODUCT_ID      0x4dd7
```suggestion
#define PRODUCT_ID      0x4DD7
```

2021-01-11 09:07 UTC, drashna approved these changes

2021-01-13 11:39 UTC, fauxpark approved these changes

2021-01-14 06:40 UTC, merged

2021-01-14 06:40 UTC, drashna commented
Thanks!

2021-01-14 09:18 UTC, koshinoya commented
Thanks everyone for review!