Add KL-90
qmk/qmk_firmware pull request #11494
Opened 2021-01-09 23:54 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-10 03:46 UTC, drashna approved these changes

2021-01-27 00:55 UTC, zvecr requested changes

2021-01-27 00:55 UTC, zvecr commented on keyboards/kikoslab/kl90/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2021-01-27 00:55 UTC, zvecr commented on keyboards/kikoslab/kl90/rules.mk
> +WPM_ENABLE = yes
Shouldnt be enabled at the keyboard level, if required move to keymap
```suggestion
```

2021-01-27 06:21 UTC, fauxpark approved these changes

2021-01-30 03:28 UTC, drashna commented
Looks like the info.json doesn't match the number of keys in the layout_all macro.

2021-01-30 18:27 UTC, swiftrax commented
> Looks like the info.json doesn't match the number of keys in the layout_all macro.

I believe I fixed it now

2021-02-04 17:45 UTC, drashna approved these changes

2021-02-04 17:45 UTC, merged