A new symmetric stagger keyboard: Angel.
qmk/qmk_firmware pull request #11501
Opened 2021-01-10 15:55 UTC by jamessa

## Description

A new symmetric staggered keyboard: Angel. >

## Types of Changes

- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-11 00:22 UTC, jamessa commented
I think Travis build status is wrong. In fact it failed on docker image download. 

docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

2021-01-11 08:48 UTC, drashna approved these changes

2021-01-13 02:07 UTC, drashna approved these changes

2021-01-13 02:34 UTC, jamessa commented
It looks like force push will affect review status. I will freeze current layout for review. Thank you all for making such great QMK that I can design the keyboard interaction instantaneously. Amazing.

2021-01-14 10:05 UTC, fauxpark requested changes

2021-01-14 10:05 UTC, fauxpark commented on keyboards/angel/config.h
> +// #define BOOTMAGIC_LITE_COLUMN 0
```suggestion
```

2021-01-14 10:05 UTC, fauxpark commented on keyboards/angel/info.json
> +            "key_count": 47,
```suggestion
```

2021-01-14 10:05 UTC, fauxpark commented on keyboards/angel/keymaps/default/keymap.c
> +}
```suggestion
```

2021-01-14 10:05 UTC, fauxpark commented on keyboards/angel/readme.md
> +     avrdude -p atmega32u4 -c avr109 -U flash:w:angel_default.hex:i -P /dev/tty.usbmodem14201
```suggestion
Make example for this keyboard (after setting up your build environment):

    make angel:default

Flashing example for this keyboard:

    make angel:default:flash
```

2021-01-14 10:05 UTC, fauxpark commented on keyboards/angel/rules.mk
> +COMMAND_ENABLE = yes        # Commands for debug and configuration
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = full     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-01-14 16:41 UTC, fauxpark approved these changes

2021-01-20 02:54 UTC, drashna commented
This should probably go in the `handwired` folder.

2021-01-26 02:04 UTC, jamessa commented
Definitely. Let me fix it.

2021-01-30 03:24 UTC, merged