Add new afternoonlabs/breeze/rev0 split keyboard
qmk/qmk_firmware pull request #11510
Opened 2021-01-11 03:02 UTC by eithanshavit

Adding a new keyboard named Breeze under the AfternoonLabs brand.

## Description

Breeze Rev0 is a split keyboard with 6×4 keys, 4 key thumb cluster, arrow keys, and a 6 key macro cluster, with ortholinear column-staggered.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-11 09:03 UTC, drashna requested changes

2021-01-11 09:03 UTC, drashna commented on keyboards/afternoonlabs/breeze/rev0/config.h
> +#define DESCRIPTION Breeze Rev0 is a split keyboard with 6×4 keys, 4 key thumb cluster, arrow keys, and a 6 key macro cluster, with ortholinear column - staggered.
This setting is not used anymore and should be removed.
```suggestion
```

2021-01-11 09:03 UTC, drashna commented on keyboards/afternoonlabs/breeze/rev0/rules.mk
> +SLEEP_LED_ENABLE = no      # Breathing sleep LED during USB suspend
```suggestion
AUDIO_ENABLE = no          # Audio output
UNICODE_ENABLE = no        # Unicode
BLUETOOTH_ENABLE = no      # Enable Bluetooth
RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
SLEEP_LED_ENABLE = no      # Breathing sleep LED during USB suspend
```

2021-01-11 16:58 UTC, eithanshavit commented on keyboards/afternoonlabs/breeze/rev0/rules.mk
> +SLEEP_LED_ENABLE = no      # Breathing sleep LED during USB suspend
Thanks @drashna!

2021-01-11 19:06 UTC, drashna requested changes
The empty rules.mk file should be removed from the default keymap folder.

2021-01-11 19:06 UTC, drashna commented on keyboards/afternoonlabs/breeze/config.h
> +#endif
```suggestion
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
```

2021-01-11 19:59 UTC, eithanshavit commented on keyboards/afternoonlabs/breeze/config.h
> +#endif
Thanks again @drashna, I've resolved your comments.

2021-01-12 22:37 UTC, eithanshavit commented
Thanks for the feedback, all recent change request addressed. @drashna, anything else I should consider?

2021-01-13 02:11 UTC, drashna approved these changes

2021-01-14 00:05 UTC, fauxpark requested changes

2021-01-14 00:05 UTC, fauxpark commented on keyboards/afternoonlabs/breeze/keymaps/default/readme.md
> +# Default Breeze Layout
```suggestion
# Default Breeze Layout

![Breeze Layout Image](https://i.imgur.com/O8FJWD6.jpeg)
```

2021-01-14 00:05 UTC, fauxpark commented on keyboards/afternoonlabs/breeze/rev0/readme.md
> +![Breeze](https://imgur.com/a/1BKNmyR)
```suggestion
# Breeze

![Breeze](https://i.imgur.com/O8FJWD6.jpeg)
```

2021-01-14 00:05 UTC, fauxpark commented on keyboards/afternoonlabs/breeze/rev0/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-01-14 00:05 UTC, fauxpark commented on keyboards/afternoonlabs/breeze/rev0/rules.mk
> +SPLIT_KEYBOARD = yes
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
```

2021-01-14 00:17 UTC, eithanshavit commented
Thanks for the suggestions @fauxpark, I've updated the PR with the changes.

2021-01-14 00:17 UTC, fauxpark approved these changes

2021-01-14 06:51 UTC, merged

2021-01-14 06:51 UTC, drashna commented
Thanks!