[Keymap] Adding Fancy keymap and Bongocat Keymap to Mercutio Keyboard
qmk/qmk_firmware pull request #11520
Opened 2021-01-11 23:47 UTC by kylemccreery

## Description

Added 2 different more complex keymaps to make use of the encoder and OLED on the board.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-13 02:31 UTC, drashna approved these changes
The years don't need to be updated, IIRC.

But otherwise, LGTM

2021-01-14 10:15 UTC, fauxpark requested changes

2021-01-14 10:15 UTC, fauxpark commented on keyboards/mechwild/mercutio/keymaps/fancy/keymap.c
> +            oled_write_P(IS_LED_ON(led_usb_state, USB_LED_CAPS_LOCK) ? PSTR("CAPS ") : PSTR("     "), false);
```suggestion
            led_t led_state = host_keyboard_led_state();
            oled_set_cursor(8,0);
            oled_write_P(led_state.scroll_lock ? PSTR("SCRLK") : PSTR("     "), false);
            oled_set_cursor(8,1);
            oled_write_P(led_state.num_lock ? PSTR("NLCK ") : PSTR("     "), false);
            oled_write_P(led_state.caps_lock ? PSTR("CAPS ") : PSTR("     "), false);
```

2021-01-21 03:26 UTC, fauxpark approved these changes

2021-01-23 17:32 UTC, merged