Add indicator LED support
qmk/qmk_firmware pull request #11560
Opened 2021-01-15 05:32 UTC by LSChyi

Add indicator LED support.

## Description

Add indicator LED for capslock and scroll lock.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-15 12:29 UTC, zvecr requested changes

2021-01-15 12:29 UTC, zvecr commented on keyboards/playkbtw/helen80/helen80.c
> +}
Instead this should use <https://docs.qmk.fm/#/feature_led_indicators?id=configuration-options>
```suggestion
```

And within `config.h`

```c
#define LED_CAPS_LOCK_PIN B3
#define LED_SCROLL_LOCK_PIN B2
#define LED_PIN_ON_STATE 0
```

2021-01-15 13:37 UTC, zvecr approved these changes

2021-01-15 17:14 UTC, fauxpark approved these changes

2021-01-20 05:05 UTC, drashna approved these changes

2021-01-20 05:06 UTC, merged