Clean up KBD8X keyboard
qmk/qmk_firmware pull request #11565
Opened 2021-01-15 16:47 UTC by drashna

## Description

Turned off console, since it's a memory hog, and compiling over sized. 
Also, cleaned up default keymaps.

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Issues Fixed or Closed by This PR

* Travis CI

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-15 17:05 UTC, fauxpark approved these changes

2021-01-26 04:39 UTC, noroadsleft requested changes
Looks good to me besides this:

2021-01-26 04:39 UTC, noroadsleft commented on keyboards/kbdfans/kbd8x/rules.mk
>  UNICODE_ENABLE = no         # Unicode
```suggestion
```

2021-02-02 20:48 UTC, noroadsleft approved these changes

2021-02-02 20:49 UTC, merged

2021-02-02 20:49 UTC, noroadsleft commented
Thanks!