Add DSP40
qmk/qmk_firmware pull request #11579
Opened 2021-01-16 22:28 UTC by nooges

## Description

Adds DSP40 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-20 05:39 UTC, drashna requested changes

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/dsp40.c
> +#include "dsp40.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/dsp40.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/bakingpy/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/bakingpy/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/bakingpy/keymap.c
> +extern keymap_config_t keymap_config;
Already included.
```suggestion
```

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/default/keymap.c
> +#define _ADJUST 3
```suggestion
enum custom_layer {
    _QWERTY,
    _LOWER,
    _RAISE,
    _ADJUST,
};
```

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/via/keymap.c
> +#define _FN3 3
```suggestion
enum via_layers {
    _MAIN,
    _FN1,
    _FN2,
    _FN3,
};
```

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/rev1/rev1.c
> +#include "rev1.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:39 UTC, drashna commented on keyboards/keebio/dsp40/rev1/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2021-01-24 00:17 UTC, drashna commented on keyboards/keebio/dsp40/keymaps/bakingpy/keymap.c
> +#define LAYOUT_kc_ortho_4x12( \
/cries

2021-01-24 00:18 UTC, drashna approved these changes

2021-01-24 00:19 UTC, drashna commented
Lint is mad.

2021-01-24 23:02 UTC, nooges commented on keyboards/keebio/dsp40/keymaps/bakingpy/keymap.c
> +#define LAYOUT_kc_ortho_4x12( \
Yeah, one day I'll kill this all off

2021-02-04 20:55 UTC, fauxpark requested changes

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/keymaps/bakingpy/keymap.c
> +    _______, _______, _______, _______, _______, _______,          _______, _______, _______, _______, _______, _______ \
```suggestion
  [_ADJUST] = LAYOUT_ortho_4x12(
    _______, RESET  , RGB_TOG, RGB_MOD, RGB_HUD, RGB_HUI,          RGB_SAD, RGB_SAI, RGB_VAD, RGB_VAI, _______, _______,
    _______, _______, _______, AU_ON,   AU_OFF,  AG_NORM,          AG_SWAP, MAC,     WINDOWS, TESTMODE,_______, _______,
    _______, _______, _______, _______, _______, _______,          _______, _______, _______, _______, _______, _______,
    _______, _______, _______, _______, _______, _______,          _______, _______, _______, _______, _______, _______
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/keymaps/default/keymap.c
> +    [_QWERTY] = LAYOUT( \
```suggestion
    [_QWERTY] = LAYOUT(
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/keymaps/default/keymap.c
> +    [_LOWER] = LAYOUT( \
```suggestion
    [_LOWER] = LAYOUT(
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/keymaps/default/keymap.c
> +    [_RAISE] = LAYOUT( \
```suggestion
    [_RAISE] = LAYOUT(
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/keymaps/default/keymap.c
> +    [_ADJUST] = LAYOUT( \
```suggestion
    [_ADJUST] = LAYOUT(
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/readme.md
> +Hardware Availability: [Keebio](https://keeb.io/)
```suggestion
* Keyboard Maintainer: [Bakingpy/nooges](https://github.com/nooges)
* Hardware Supported: STM32F072CBT6
* Hardware Availability: [Keebio](https://keeb.io/)
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/rev1/config.h
> +#define DESCRIPTION     40% Keyboard with identity crisis
```suggestion
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/rev1/readme.md
> +Hardware Availability: [Keebio](https://keeb.io/)
```suggestion
* Keyboard Maintainer: [Bakingpy/nooges](https://github.com/nooges)
* Hardware Supported: STM32F072CBT6
* Hardware Availability: [Keebio](https://keeb.io/)
```

2021-02-04 20:55 UTC, fauxpark commented on keyboards/keebio/dsp40/rev1/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-02-07 18:39 UTC, fauxpark approved these changes

2021-02-07 20:49 UTC, merged