Add Quefrency Rev. 3
qmk/qmk_firmware pull request #11578
Opened 2021-01-16 21:57 UTC by nooges

## Description

Add Quefrency Rev. 3

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-20 05:27 UTC, drashna requested changes

2021-01-20 05:27 UTC, drashna commented on keyboards/keebio/quefrency/rev3/rev3.c
> +#include "quefrency.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-20 05:27 UTC, drashna commented on keyboards/keebio/quefrency/rev3/rev3.h
> +#endif
Pretty sure this block isn't needed.
```suggestion
```

2021-01-20 05:27 UTC, drashna commented on keyboards/keebio/quefrency/rev3/rev3.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-01-24 00:29 UTC, drashna approved these changes

2021-01-24 04:29 UTC, fauxpark requested changes

2021-01-24 04:29 UTC, fauxpark commented on keyboards/keebio/quefrency/rev3/config.h
> +#define DESCRIPTION     Split 60/65 percent staggered keyboard
```suggestion
```

2021-01-25 05:28 UTC, fauxpark approved these changes

2021-01-25 06:39 UTC, merged