Adds AT90USB162 support
qmk/qmk_firmware pull request #11570
Opened 2021-01-15 23:05 UTC by daskygit

## Description

Adds support for the AT90USB162.

After my previous PR failure I hope this one is smoother. I've ran `make all:default` and there are failures with some boards but they appear to happen on develop as well. I've compiled and flashed AT90USB162, ATmega32u4 and STM32F401 boards using this branch.

I've added preliminary support into spi_master, uart and serial but I've not tested these features but the registers, bits and pins line up with the datasheet. I've been able to test the changes to backlight_avr on a couple of accessible pins with hardware pwm. I'm a little unsure about the edit I've made to the max eeprom address in dynamic_keymap.c as it doesn't make an exception for the 16u2?

The MCU has no ADCs or support for I2C. I found a [datasheet](http://ww1.microchip.com/downloads/en/AppNotes/doc8224.pdf) while creating a the first pull request stating the ATmega16u2 is functional equivalent to the AT90USB162 which lines up with the edits I've made.

I'm expecting to have missed something but hopefully not too much. 

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-16 15:47 UTC, daskygit commented
Also I forgot to ask, in common_features there's a comment saying ATmegaxxU2 doesn't have a hardware MUL instruction. 

When checking the avr instruction set they're listed as AVRe+ cores that should have the instruction with the only missing instructions being "ELPM, EIJMP, EICALL". It wouldn't be the first time the datasheets were wrong about something. 

I've added the AT90USB162 as a precaution considering the ATmega16u2 should be a replacement and I guess the only downside being performance.

2021-01-16 16:02 UTC, fauxpark requested changes

2021-01-16 16:02 UTC, fauxpark commented on quantum/backlight/backlight_avr.c
> +#elif (defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega32U2__) || defined(__AVR_AT90USB162__)) && (BACKLIGHT_PIN == B7 || BACKLIGHT_PIN == C5 || BACKLIGHT_PIN == C6)
```suggestion
#elif (defined(__AVR_AT90USB162__) || defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega32U2__)) && (BACKLIGHT_PIN == B7 || BACKLIGHT_PIN == C5 || BACKLIGHT_PIN == C6)
```

2021-01-16 16:02 UTC, fauxpark commented on quantum/config_common.h
> +#    elif defined(__AVR_ATmega32U2__) || defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega328P__) || defined(__AVR_ATmega328__) || defined(__AVR_AT90USB162__)
```suggestion
#    elif defined(__AVR_AT90USB162__) || defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega32U2__) || defined(__AVR_ATmega328P__) || defined(__AVR_ATmega328__)
```

2021-01-16 16:02 UTC, fauxpark commented on quantum/mcu_selection.mk
> +ifneq (,$(filter $(MCU),atmega16u2 atmega32u2 atmega16u4 atmega32u4 at90usb646 at90usb647 at90usb1286 at90usb1287 at90usb162))
```suggestion
ifneq (,$(filter $(MCU),at90usb162 atmega16u2 atmega32u2 atmega16u4 atmega32u4 at90usb646 at90usb647 at90usb1286 at90usb1287))
```

2021-01-16 16:02 UTC, fauxpark commented on quantum/mcu_selection.mk
> +  ifneq (,$(filter $(MCU),atmega16u2 atmega32u2 at90usb162))
```suggestion
  ifneq (,$(filter $(MCU),at90usb162 atmega16u2 atmega32u2))
```

2021-01-16 16:02 UTC, fauxpark commented on tmk_core/common/uart.c
> +#elif defined(__AVR_ATmega32U4__) || defined(__AVR_ATmega32U2__) || defined(__AVR_AT90USB646__) || defined(__AVR_AT90USB647__) || defined(__AVR_AT90USB1286__) || defined(__AVR_AT90USB1287__) || defin
```suggestion
#elif defined(__AVR_AT90USB162__) || defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega32U2__) || defined(__AVR_ATmega16U4__) || defined(__AVR_ATmega32U4__) || defined(__AVR_AT90USB646__) || defined(__AVR_AT90USB647__) || defined(__AVR_AT90USB1286__) || defined(__AVR_AT90USB1287__)
```

2021-01-16 17:34 UTC, daskygit commented on docs/feature_backlight.md
> +|Backlight Pin|AT90USB64/128|AT90USB162|ATmega16/32U4|ATmega16/32U2|ATmega32A|ATmega328/P|
I couldn't decide on how to format it when adding to the existing column. Is there a preference for the field header?

So we have something like this below that looks good using `qmk docs` but a little harder to understand just as text.
```suggestion
|Backlight Pin|AT90USB64/128|ATmega16/32U4|AT90USB162<br>ATmega16/32U2|ATmega32A|ATmega328/P|
|-------------|-------------|-------------|-------------|---------|-----------|
|`B1`         |             |             |             |         |Timer 1    |
|`B2`         |             |             |             |         |Timer 1    |
|`B5`         |Timer 1      |Timer 1      |             |         |           |
|`B6`         |Timer 1      |Timer 1      |             |         |           |
|`B7`         |Timer 1      |Timer 1      |Timer 1      |         |           |
|`C4`         |Timer 3      |             |             |         |           |
|`C5`         |Timer 3      |             |Timer 1      |         |           |
|`C6`         |Timer 3      |Timer 3      |Timer 1      |         |           |
|`D4`         |             |             |             |Timer 1  |           |
|`D5`         |             |             |             |Timer 1  |           |
```


Or something like below but I think shortening it to 162 probably isn't clear enough and adding the full name makes the column extra wide.
```suggestion
|Backlight Pin|AT90USB64/128|ATmega16/32U4|ATmega16/32U2/162|ATmega32A|ATmega328/P|
|-------------|-------------|-------------|-----------------|---------|-----------|
|`B1`         |             |             |                 |         |Timer 1    |
|`B2`         |             |             |                 |         |Timer 1    |
|`B5`         |Timer 1      |Timer 1      |                 |         |           |
|`B6`         |Timer 1      |Timer 1      |                 |         |           |
|`B7`         |Timer 1      |Timer 1      |Timer 1          |         |           |
|`C4`         |Timer 3      |             |                 |         |           |
|`C5`         |Timer 3      |             |Timer 1          |         |           |
|`C6`         |Timer 3      |Timer 3      |Timer 1          |         |           |
|`D4`         |             |             |                 |Timer 1  |           |
|`D5`         |             |             |                 |Timer 1  |           |
```

There's probably another option but my markdown knowledge is non-existent.

2021-01-16 18:09 UTC, daskygit commented on docs/feature_backlight.md
> +|`D5`         |             |          |             |             |Timer 1  |           |
So we have something like this below that looks good using `qmk docs` but a little harder to understand just as text.
```suggestion
|Backlight Pin|AT90USB64/128|ATmega16/32U4|AT90USB162<br>ATmega16/32U2|ATmega32A|ATmega328/P|
|-------------|-------------|-------------|-------------|---------|-----------|
|`B1`         |             |             |             |         |Timer 1    |
|`B2`         |             |             |             |         |Timer 1    |
|`B5`         |Timer 1      |Timer 1      |             |         |           |
|`B6`         |Timer 1      |Timer 1      |             |         |           |
|`B7`         |Timer 1      |Timer 1      |Timer 1      |         |           |
|`C4`         |Timer 3      |             |             |         |           |
|`C5`         |Timer 3      |             |Timer 1      |         |           |
|`C6`         |Timer 3      |Timer 3      |Timer 1      |         |           |
|`D4`         |             |             |             |Timer 1  |           |
|`D5`         |             |             |             |Timer 1  |           |
```


Or something like below but I think shortening it to 162 probably isn't clear enough and adding the full name makes the column extra wide.
```suggestion
|Backlight Pin|AT90USB64/128|ATmega16/32U4|ATmega16/32U2/162|ATmega32A|ATmega328/P|
|-------------|-------------|-------------|-----------------|---------|-----------|
|`B1`         |             |             |                 |         |Timer 1    |
|`B2`         |             |             |                 |         |Timer 1    |
|`B5`         |Timer 1      |Timer 1      |                 |         |           |
|`B6`         |Timer 1      |Timer 1      |                 |         |           |
|`B7`         |Timer 1      |Timer 1      |Timer 1          |         |           |
|`C4`         |Timer 3      |             |                 |         |           |
|`C5`         |Timer 3      |             |Timer 1          |         |           |
|`C6`         |Timer 3      |Timer 3      |Timer 1          |         |           |
|`D4`         |             |             |                 |Timer 1  |           |
|`D5`         |             |             |                 |Timer 1  |           |
```

There's probably another option but my markdown knowledge is non-existent.

2021-01-17 03:36 UTC, fauxpark commented on docs/feature_backlight.md
> +|Backlight Pin|AT90USB64/128|AT90USB162|ATmega16/32U4|ATmega16/32U2|ATmega32A|ATmega328/P|
Yeah, that's fair. Might as well just leave it then :)

2021-01-17 03:37 UTC, fauxpark approved these changes

2021-01-20 05:22 UTC, drashna approved these changes

2021-01-29 11:44 UTC, daskygit commented
Resolved merge conflicts with uart.c and keyboard.jsonschema.

2021-01-30 03:53 UTC, merged