Add sowbug/68keys and sowbug/ansi_tkl
qmk/qmk_firmware pull request #11589
Opened 2021-01-17 07:11 UTC by sowbug

## Description

Adds two new Blue Pill-based keyboards using reasonably common layouts (Magicforce 68 and ANSI tenkeyless), with
USB-C, optional Kailh hotswap sockets, per-key RGB lighting. Both keyboards have been built as prototypes.

These keyboards were generated with the help of https://github.com/sowbug/keycad.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

I read https://beta.docs.qmk.fm/developing-qmk/c-development/hardware_keyboard_guidelines and believe this PR complies.

2021-01-20 06:00 UTC, drashna requested changes

2021-01-20 16:36 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.c
> +// 68keys.c
done

2021-01-20 16:37 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.c
> +#include "quantum/rgb_matrix.h"
done

2021-01-20 16:37 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.c
> +led_config_t g_led_config = { {
done

2021-01-20 16:38 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.c
> +};
done

2021-01-20 16:38 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.c
> +}
done

2021-01-20 16:39 UTC, sowbug commented on keyboards/sowbug/68keys/config.h
> +#define DESCRIPTION     Keyboard
done

2021-01-20 16:40 UTC, sowbug commented on keyboards/sowbug/68keys/config.h
> +#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 128
done

2021-01-20 17:13 UTC, sowbug commented on keyboards/sowbug/68keys/info.json
> +    "maintainer": "sowbug"
Oh, that's cool. My keyboard is based on Blue Pill, so not all the generated files applied, but the current info.json is now complete AFAICT.

2021-01-20 17:14 UTC, sowbug commented on keyboards/sowbug/68keys/keymaps/default/keymap.c
> +// keymaps/default/keymap.c
done

2021-01-20 17:16 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.h
> +// 68keys.h
done

2021-01-20 17:18 UTC, sowbug commented on keyboards/sowbug/68keys/config.h
> +#define DESCRIPTION     Keyboard
done (did all the corresponding changes to the new ansi_tkl keyboard as well)

2021-01-20 17:19 UTC, sowbug commented on keyboards/sowbug/68keys/readme.md
> +* `qmk compile -kb sowbug/68keys -km default`
done

2021-01-20 17:21 UTC, sowbug commented on keyboards/sowbug/68keys/68keys.c
> +#ifdef BACKLIGHT_DRIVER
done

2021-01-20 17:22 UTC, sowbug commented on keyboards/sowbug/68keys/config.h
> +// config.h
done

2021-01-20 17:47 UTC, sowbug commented on keyboards/sowbug/68keys/info.json
> +    "maintainer": "sowbug"
done for both

2021-01-20 17:51 UTC, sowbug commented
All comments address. Please re-review. Thanks!

2021-01-22 17:41 UTC, drashna approved these changes

2021-01-25 15:47 UTC, sowbug commented
Thank you for the approval, @drashna. How do I get the upstream merge to happen? Is there anything else I need to do on my end?

2021-02-09 23:27 UTC, spidey3 approved these changes

2021-02-10 04:45 UTC, drashna commented
Thanks

2021-02-10 04:45 UTC, merged