Added My First Keymap
qmk/qmk_firmware pull request #11599
Opened 2021-01-17 23:29 UTC by Magascorada

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-20 00:35 UTC, Spaceman requested changes

2021-01-20 00:35 UTC, Spaceman commented on keyboards/kyria/keymaps/MagasCorada
> +
This file should be deleted

2021-01-20 00:35 UTC, Spaceman commented on keyboards/kyria/keymaps/MagasCorada
> +
Other than that this PR looks good to me

2021-01-20 01:30 UTC, Magascorada commented
I don't know how to delete the file. I'm sorry.

On Tue, Jan 19, 2021, 18:35 Spaceman <notifications@github.com> wrote:

> *@Spaceman* requested changes on this pull request.
> ------------------------------
>
> In keyboards/kyria/keymaps/MagasCorada
> <https://github.com/qmk/qmk_firmware/pull/11599#discussion_r560593396>:
>
> > @@ -0,0 +1 @@
> +
>
> This file should be deleted
> ------------------------------
>
> In keyboards/kyria/keymaps/MagasCorada
> <https://github.com/qmk/qmk_firmware/pull/11599#discussion_r560593666>:
>
> > @@ -0,0 +1 @@
> +
>
> Other than that this PR looks good to me
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qmk/qmk_firmware/pull/11599#pullrequestreview-571778293>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOHNJ6KPRKVOQFVFXV6ECPTS2YQM3ANCNFSM4WGPWMPA>
> .
>

2021-02-01 06:46 UTC, JunoNgx commented
You created an empty file named `MagasCorada` (without an extension) in the `kyria` folder. This is a file, not a folder and it doesn't do anything. The quickest way is to delete it with the github web GUI.

Else you can just delete it locally from your repository clone and push to the change to remote.

2021-02-05 02:28 UTC, drashna requested changes
Also, if you could rename all of the files so that they're all lower case? 

You should be able to do that in the webUI for github, if needed.

2021-02-05 02:28 UTC, drashna commented on keyboards/kyria/keymaps/Magascorada/keymap.c
> +    _QWERTY = 0,
The zero isn't needed here, as enums start at 0, and increment up from there.
```suggestion
    _QWERTY,
```

2021-04-02 21:32 UTC, drashna commented
If you're still having issues with removing the file, you can do this through github's UI.

Via command line, it would be:
```
git rm keyboards/kyria/keymaps/MagasCorada
```

And then `git commit`.

2021-06-02 17:30 UTC, closed without merging