Add nknl7en keyboard
qmk/qmk_firmware pull request #11590
Opened 2021-01-17 15:53 UTC by Salicylic-acid3

A 70 keys ANSI Layout split keyboard.
Salicylic-acid3

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-20 06:03 UTC, drashna requested changes

2021-01-20 06:03 UTC, drashna commented on keyboards/nknl7en/keymaps/salicylic/keymap.c
> +#endif
Isn't needed.
```suggestion
```

2021-01-20 06:03 UTC, drashna commented on keyboards/nknl7en/keymaps/salicylic/keymap.c
> +int RGB_current_mode;
```suggestion
uint8_t RGB_current_mode;
```

2021-01-20 06:03 UTC, drashna commented on keyboards/nknl7en/keymaps/salicylic/keymap.c
> +            RGB_current_mode = rgblight_config.mode;
```suggestion
            RGB_current_mode = rgblight_get_mode();
```

2021-01-20 06:03 UTC, drashna commented on keyboards/nknl7en/keymaps/salicylic/keymap.c
> +            RGB_current_mode = rgblight_config.mode;
```suggestion
            RGB_current_mode = rgblight_get_mode();
```

2021-01-21 17:45 UTC, Salicylic-acid3 commented
In the local environment, the build succeeds, but Travis fails.
What could be the cause?

2021-01-22 17:40 UTC, drashna approved these changes

2021-01-30 07:14 UTC, Salicylic-acid3 commented
Is there anything else I can do?

2021-02-05 22:03 UTC, fauxpark approved these changes

2021-02-07 17:05 UTC, drashna approved these changes

2021-02-07 17:06 UTC, drashna commented
Thanks!

2021-02-07 17:07 UTC, merged