[Keyboard] Add Lumberjack keyboard
qmk/qmk_firmware pull request #11626
Opened 2021-01-19 19:51 UTC by peej

## Description

Add the firmware details for the Lumberjack PCB.
The Lumberjack is a through-hole ortholinear 60% keyboard PCB that fits in a tray mount case but is inspired by the Plaid.

![Lumberjack](https://i.imgur.com/mHluuOA.jpg)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-20 07:28 UTC, drashna requested changes

2021-01-20 07:28 UTC, drashna commented on keyboards/peej/lumberjack/config.h
> +#define VENDOR_ID 0x706a
```suggestion
#define VENDOR_ID 0x706A
```

2021-01-20 07:28 UTC, drashna commented on keyboards/peej/lumberjack/config.h
> +#define DESCRIPTION 12x5 ortholinear keyboard with through hole components
```suggestion
```

2021-03-05 21:28 UTC, closed without merging

2021-04-12 05:22 UTC, Soundtoxin commented
Any chance this could be made to appear split in the qmk configurator?