UART driver refactor
qmk/qmk_firmware pull request #11637
Opened 2021-01-20 09:55 UTC by fauxpark

## Description

Moves the existing `uart.[ch]` driver to `drivers/`, and adds a ChibiOS counterpart (which may need some QA from someone more versed in the ARM side of things).

It would also be good to get some `puts()` and `gets()` implementations added, if possible. And I'm not really sure what to do with `uart_available()` on ARM.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-20 10:02 UTC, fauxpark commented
Working on AVR (tested Pro Micro), Bluepill F103, and Proton-C, though for the latter, USART2 is actually enabled by default, despite the fact that A9 and A10 (labelled TX and RX on the pinout) are AFs of USART1. Should I change this?

2021-01-21 06:10 UTC, tzarc commented on drivers/chibios/uart.c
> +    return 0;
How about:
```suggestion
    return sdGetWouldBlock(&SERIAL_DRIVER);
```

2021-01-21 06:27 UTC, tzarc approved these changes

2021-01-21 09:22 UTC, tzarc requested changes

2021-01-21 09:22 UTC, tzarc commented on docs/uart_driver.md
> +Currently, this driver does not support enabling hardware flow control (the `RTS` and `CTS` pins) if available, but will do so in future.
```suggestion
Currently, this driver does not support enabling hardware flow control (the `RTS` and `CTS` pins) if available, but may do so in future.
```

2021-01-21 09:22 UTC, tzarc commented on docs/uart_driver.md
> +To enable UART, modify your board's `mcuconf.h` to enable the peripheral you've chosen -- in the case of using USART2, modify `STM32_SERIAL_USE_USART2` to be `TRUE`.
```suggestion
To enable UART, modify your board's `mcuconf.h` to enable the peripheral you've chosen -- in the case of using USART2, modify `STM32_SERIAL_USE_USART2` to be `TRUE`. If not using a Proton-C, you will also need to supply a `halconf.h`, which includes the definition `#define HAL_USE_SERIAL TRUE`.
```

2021-01-21 09:49 UTC, tzarc approved these changes

2021-01-22 16:30 UTC, drashna approved these changes

2021-01-27 06:42 UTC, merged