Adding my Kyria/rev1 keymap
qmk/qmk_firmware pull request #11663
Opened 2021-01-22 15:40 UTC by ghidalgo93

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-22 17:20 UTC, drashna approved these changes

2021-01-22 17:55 UTC, fauxpark requested changes

2021-01-22 17:55 UTC, fauxpark commented on keyboards/kyria/keymaps/ghidalgo93/keymap.c
> +    oled_write_P(IS_LED_ON(led_usb_state, USB_LED_SCROLL_LOCK) ? PSTR("SCRLCK ") : PSTR("       "), false);
```suggestion
    led_t led_state = host_keyboard_led_state();
    oled_write_P(led_state.num_lock ? PSTR("NUMLCK ") : PSTR("       "), false);
    oled_write_P(led_state.caps_lock ? PSTR("CAPLCK ") : PSTR("       "), false);
    oled_write_P(led_state.scroll_lock ? PSTR("SCRLCK ") : PSTR("       "), false);
```

2021-01-24 15:42 UTC, precondition commented on keyboards/kyria/keymaps/ghidalgo93/keymap.c
> + *                        `----------------------------------'  `----------------------------------'
```suggestion
 *                        |      |  GUI |      | Tab  | Enter|  | Bksp   | Space| Alt  | Home | End  |
 *                        |      |      | LCTL | Lower|      |  | 	   | Raise|      |      |      |
 *                        `----------------------------------'  `----------------------------------'
```

2021-01-27 19:18 UTC, ghidalgo93 reviewed
adding suggested changes

2021-02-03 02:00 UTC, noroadsleft requested changes

2021-02-03 02:00 UTC, noroadsleft commented on keyboards/kyria/keymaps/ghidalgo93/keymap.c
> + *                        |      |      | LCTL | Lower|      |  | 	   | Raise|      |      |      |
Alignment fix

```suggestion
 *                        |      |  GUI |      | Tab  | Enter|  | Bksp | Space| Alt  | Home | End  |
 *                        |      |      | LCTL | Lower|      |  |      | Raise|      |      |      |
```

2021-02-04 00:26 UTC, fauxpark approved these changes

2021-02-05 00:12 UTC, noroadsleft approved these changes

2021-02-05 00:14 UTC, merged

2021-02-05 00:14 UTC, noroadsleft commented
For future reference, we recommend against committing to your `master` branch as you've done here, because pull requests from modified `master` branches can make it more difficult to keep your QMK fork updated. It is highly recommended for QMK development – regardless of what is being done or where – to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your fork updated here:

[**Best Practices: Your Fork's Master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_git_using_your_master_branch)

[Fixing Your Branch](https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch) will walk you through fixing up your `master` branch moving forward. If you need any help with this just ask.

Thanks for contributing!