Xyverz bastyl
qmk/qmk_firmware pull request #11662
Opened 2021-01-22 15:14 UTC by Xyverz

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-22 17:16 UTC, drashna commented on keyboards/crkbd/keymaps/xyverz/config.h
> +<<<<<<< HEAD
Whoops

2021-01-22 17:16 UTC, drashna commented on keyboards/crkbd/keymaps/xyverz/rules.mk
> +<<<<<<< HEAD
Whoops

2021-01-24 19:37 UTC, Xyverz commented on keyboards/crkbd/keymaps/xyverz/config.h
> +<<<<<<< HEAD
LOL, thanks! Fixed. =D

2021-01-24 19:38 UTC, Xyverz commented on keyboards/crkbd/keymaps/xyverz/rules.mk
> +<<<<<<< HEAD
LOL, thanks! Fixed. =D

2021-01-25 06:30 UTC, drashna approved these changes

2021-01-30 10:48 UTC, fauxpark requested changes

2021-01-30 10:48 UTC, fauxpark commented on keyboards/hidtech/bastyl/keymaps/xyverz/keymap.c
> +                             _______, _______, _______,     _______, _______, _______, \
```suggestion
  KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSLS,
  KC_TAB,  KC_QUOT, KC_COMM, KC_DOT,  KC_P,    KC_Y,        KC_F,    KC_G,    KC_C,    KC_R,    KC_L,    KC_SLSH,
  KC_GRV,  KC_A,    KC_O,    KC_E,    KC_U,    KC_I,        KC_D,    KC_H,    KC_T,    KC_N,    KC_S,    KC_MINS,
  KC_LSFT, KC_SCLN, KC_Q,    KC_J,    KC_K,    KC_X,        KC_B,    KC_M,    KC_W,    KC_V,    KC_Z,    KC_RSFT,
                             LOWER,   KC_BSPC, KC_DEL,      KC_ENT,  KC_SPC,  RAISE,
                                      KC_LCTL, KC_LALT,     KC_RGUI, KC_RCTL
  ),

[_MAC] = LAYOUT(
  KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSLS,
  KC_TAB,  KC_QUOT, KC_COMM, KC_DOT,  KC_P,    KC_Y,        KC_F,    KC_G,    KC_C,    KC_R,    KC_L,    KC_SLSH,
  KC_GRV,  KC_A,    KC_O,    KC_E,    KC_U,    KC_I,        KC_D,    KC_H,    KC_T,    KC_N,    KC_S,    KC_MINS,
  KC_LSFT, KC_SCLN, KC_Q,    KC_J,    KC_K,    KC_X,        KC_B,    KC_M,    KC_W,    KC_V,    KC_Z,    KC_RSFT,
                             LOWER,   KC_BSPC, DELGUI,      KC_ENT,  KC_SPC,  RAISE,
                                      KC_LCTL, KC_LALT,     KC_RGUI, KC_RCTL
  ),

[_LOWER] = LAYOUT(
  KC_F11,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,       KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F12,
  RESET,   _______, _______, KC_UP,   _______, _______,     _______, KC_PSCR, KC_SLCK, KC_PAUS, _______, _______,
  KC_CAPS, _______, KC_LEFT, KC_DOWN, KC_RGHT, KC_HOME,     KC_PGUP, _______, KC_PLUS, KC_LCBR, KC_RCBR, _______,
  _______, _______, KC_MPRV, KC_MPLY, KC_MNXT, KC_END,      KC_PGDN, KC_MUTE, KC_VOLD, KC_VOLU, _______, _______,
                             _______, KC_DEL,  _______,     _______, _______, _______,
                                      MACLOCK, _______,     _______, WINLOCK
  ),

[_RAISE] = LAYOUT(
  KC_F11,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,       KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F12,
  _______, _______, _______, KC_UP,   _______, _______,     _______, KC_PSCR, KC_SLCK, KC_PAUS, _______, RESET,
  KC_CAPS, _______, KC_LEFT, KC_DOWN, KC_RGHT, KC_HOME,     KC_PGUP, _______, KC_EQL,  KC_LBRC, KC_RBRC, _______,
  _______, _______, KC_MPRV, KC_MPLY, KC_MNXT, KC_END,      KC_PGDN, KC_MUTE, KC_VOLD, KC_VOLU, _______, _______,
                             _______, KC_DEL,  _______,     _______, _______, _______,
                                      MACLOCK, _______,     _______, WINLOCK
  ),

[_ADJUST] = LAYOUT(
  _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______, _______,
  _______, RESET,   _______, _______, _______, _______,     _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______,     _______, WINDOWS, MAC,     _______, _______, _______,
  _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______, _______,
                             _______, _______, _______,     _______, _______, _______,
```

2021-02-04 05:39 UTC, Xyverz commented on keyboards/hidtech/bastyl/keymaps/xyverz/keymap.c
> +                             _______, _______, _______,     _______, _______, _______, \
Fixed.

2021-02-04 08:36 UTC, fauxpark approved these changes

2021-02-04 08:36 UTC, fauxpark commented
Thanks!

2021-02-04 08:36 UTC, merged