Knobgoblin keyboard initial commit
qmk/qmk_firmware pull request #11664
Opened 2021-01-22 18:09 UTC by mrT1ddl3s

New macropad initial commit. Keyboard and keymap

## Description
This is a keyboard and keymap addition for a new board.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-24 00:53 UTC, drashna approved these changes

2021-01-24 04:28 UTC, fauxpark requested changes

2021-01-24 04:28 UTC, fauxpark commented on keyboards/knobgoblin/config.h
> +#define DESCRIPTION     numpad macropad 2x encoders and oled support
```suggestion
```

2021-01-24 04:28 UTC, fauxpark commented on keyboards/knobgoblin/readme.md
> +![Knob Goblin](https://i.imgur.com/oYnzqqN.jpg)
```suggestion
![Knob Goblin](https://i.imgur.com/oYnzqqNl.jpg)
```

2021-01-24 04:28 UTC, fauxpark commented on keyboards/knobgoblin/readme.md
> +	make knobgoblin:default
```suggestion
    make knobgoblin:default
```

2021-01-24 19:00 UTC, mrT1ddl3s commented
Thank you Drashna and Fauxpark. I've commited your suggested changes. Please let me know if there are any other changes to be made before merge.

2021-01-24 19:22 UTC, fauxpark approved these changes

2021-01-25 06:25 UTC, merged

2021-01-25 06:25 UTC, drashna commented
Thanks!