[Keymap] add noroadsleft userspace; add and update keymaps
qmk/qmk_firmware pull request #11686
Opened 2021-01-24 23:50 UTC by noroadsleft

## Description

[title]

## Types of Changes

- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-25 02:03 UTC, drashna commented on users/noroadsleft/noroadsleft.c
> +    return process_record_keymap(keycode, record);
Personally, I like having this checked at top, before the switch.  Eg:

```c 
if (!process_record_keymap(keycode, record)) return false;
```
It's a bit more inline with the core.

2021-01-25 02:03 UTC, drashna approved these changes

2021-01-25 05:31 UTC, fauxpark requested changes

2021-01-25 05:31 UTC, fauxpark commented on keyboards/kbdfans/kbd75/keymaps/noroadsleft/config.h
> +#undef DESCRIPTION
```suggestion
```

2021-01-25 05:31 UTC, fauxpark commented on keyboards/kbdfans/kbd75/keymaps/noroadsleft/keymap.c
> +#include <sendstring_dvorak.h>
```suggestion
#include "sendstring_dvorak.h"
```

2021-01-25 05:31 UTC, fauxpark commented on keyboards/kc60/keymaps/noroadsleft/keymap.c
>  #include <print.h>
```suggestion
#include "sendstring_dvorak.h"
//#include "sendstring_colemak.h"
#include "print.h"
```

2021-02-10 19:15 UTC, Erovia approved these changes

2021-02-10 19:17 UTC, merged