Adding YMDK Wings Keyboard
qmk/qmk_firmware pull request #11693
Opened 2021-01-26 09:43 UTC by alittlepeace

## Description

YMDK Wings is an Arisu/Alice-style keyboard with a nav cluster that started being sold at the end of 2020. Their website instructs people to use their own tool off their own fork of QMK, so I decided to create the files for use with the configurator. I've also created a VIA .json. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-26 09:59 UTC, fauxpark requested changes
Also missing a readme.md.

2021-01-26 09:59 UTC, fauxpark commented on keyboards/ymdk/wings/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth with the Adafruit EZ-Key HID
```suggestion
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
```

2021-01-26 16:35 UTC, alittlepeace commented on keyboards/ymdk/wings/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth with the Adafruit EZ-Key HID
Fixed rules.mk and added readme

2021-01-28 00:38 UTC, zvecr requested changes

2021-01-28 00:38 UTC, zvecr commented on keyboards/ymdk/wings/info.json
> +        "LAYOUT_default": {
```suggestion
        "LAYOUT": {
```

2021-01-28 01:32 UTC, alittlepeace commented on keyboards/ymdk/wings/info.json
> +        "LAYOUT_default": {
changed

2021-01-30 04:40 UTC, drashna requested changes

2021-01-30 04:40 UTC, drashna commented on keyboards/ymdk/wings/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
```

2021-01-30 07:53 UTC, alittlepeace commented on keyboards/ymdk/wings/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
fixed

2021-01-30 11:00 UTC, fauxpark approved these changes

2021-02-03 21:35 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/11693/files).

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/info.json
> +    "width": 20,
```suggestion
    "width": 20.25,
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/readme.md
> +* Keyboard Maintainer: alittlepeace
```suggestion
* Keyboard Maintainer: [alittlepeace](https://github.com/alittlepeace)
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
Flashing example for this keyboard:

    make ymdk/wings:default:flash

To reset the board into bootloader mode, hold the key at the top left of the keyboard while connecting the USB cable (also erases persistent settings).

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/wings.h
> +#define LAYOUT( \
The PCB, according to the YMDK site, supports a 2u Backspace, even if the case doesn't.

```suggestion
#define LAYOUT_all( \
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/keymaps/default/keymap.c
> +  [0] = LAYOUT(
```suggestion
  [0] = LAYOUT_all(
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/keymaps/default/keymap.c
> +  [1] = LAYOUT(
```suggestion
  [1] = LAYOUT_all(
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/keymaps/via/keymap.c
> +  [0] = LAYOUT(
```suggestion
  [0] = LAYOUT_all(
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/keymaps/via/keymap.c
> +  [1] = LAYOUT(
```suggestion
  [1] = LAYOUT_all(
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/keymaps/via/keymap.c
> +  [2] = LAYOUT(
```suggestion
  [2] = LAYOUT_all(
```

2021-02-03 21:35 UTC, noroadsleft commented on keyboards/ymdk/wings/keymaps/via/keymap.c
> +  [3] = LAYOUT(
```suggestion
  [3] = LAYOUT_all(
```

2021-02-05 03:01 UTC, drashna approved these changes

2021-02-05 03:02 UTC, merged