Adding support for a keyboard called ortho4exent
qmk/qmk_firmware pull request #11699
Opened 2021-01-26 20:14 UTC by tszaboo

## Description

Adding support for a keyboard called ortho4exent 
QMK MSYS compiled the hex, and I was able to upload it to the board.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-24 23:02 UTC, zvecr requested changes

2021-02-24 23:02 UTC, zvecr commented on keyboards/tszaboo/ortho4exent/readme.md
> +Hardware Availability: [Geekhack Group Buy](https://geekhack.org/index.php?topic=110120.0)
```suggestion
* Keyboard Maintainer: [tszaboo](https://github.com/tszaboo/)
* Keyboard Product owner: [Riba]
* Hardware Supported: Ortho4exent
* Hardware Availability: [Geekhack Group Buy](https://geekhack.org/index.php?topic=110120.0)
```

2021-02-24 23:02 UTC, zvecr commented on keyboards/tszaboo/ortho4exent/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-02-24 23:02 UTC, zvecr commented on keyboards/tszaboo/ortho4exent/rules.mk
> +VIA_ENABLE = yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-02-24 23:02 UTC, zvecr commented on keyboards/tszaboo/ortho4exent/info.json
> +        "key_count": 71,
```suggestion
```

2021-02-24 23:16 UTC, drashna requested changes

2021-02-25 10:20 UTC, tszaboo commented on keyboards/tszaboo/ortho4exent/config.h
> +Copyright 2019 mechmerlin
Ok ,changed

2021-02-25 10:46 UTC, tszaboo commented
After merging your changes, I was able to build the firmware with QMK MSYS

2021-03-15 17:33 UTC, zvecr requested changes

2021-03-15 17:33 UTC, zvecr commented on keyboards/tszaboo/ortho4exent/config.h
> +Copyright 2019 mechmerlin
```suggestion
Copyright 2021 tszaboo
```

2021-03-15 17:33 UTC, zvecr commented on keyboards/handwired/onekey/blackpill_f411/config.h
> +/* Copyright 2021 tszaboo
```suggestion
/* Copyright 2019
```

2021-03-15 17:33 UTC, zvecr commented on keyboards/tszaboo/ortho4exent/rules.mk
> +
```suggestion
# Bootloader selection
BOOTLOADER = caterina
```

2021-03-15 17:38 UTC, tszaboo commented on keyboards/tszaboo/ortho4exent/config.h
> +Copyright 2019 mechmerlin
resolved

2021-03-15 20:48 UTC, fauxpark commented on keyboards/tszaboo/ortho4exent/rules.mk
> +# Bootloader selection
```suggestion

# Bootloader selection
```

2021-03-15 20:49 UTC, fauxpark commented on keyboards/tszaboo/ortho4exent/rules.mk
> +LTO_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
```

2021-03-15 21:01 UTC, fauxpark approved these changes

2021-03-17 06:49 UTC, drashna approved these changes

2021-03-17 06:50 UTC, merged

2021-03-17 06:50 UTC, drashna commented
Thanks!

2021-03-17 13:42 UTC, tszaboo commented
Thank you guys, I appreciate the help!