Add my keymap for Mark65
qmk/qmk_firmware pull request #11717
Opened 2021-01-28 01:12 UTC by stanrc85

Add my keymap and enable VIA for Mark65 keyboard

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-30 05:48 UTC, drashna approved these changes

2021-02-05 03:34 UTC, drashna approved these changes

2021-02-05 21:59 UTC, fauxpark requested changes

2021-02-05 21:59 UTC, fauxpark commented on keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c
> +  uint8_t layer = biton32(layer_state);
```suggestion
  uint8_t layer = get_highest_layer(layer_state);
```

2021-02-05 21:59 UTC, fauxpark commented on keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c
> +  if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK)) {
```suggestion
  if (host_keyboard_led_state().caps_lock) {
```

2021-02-06 00:57 UTC, stanrc85 commented on keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c
> +  if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK)) {
Fixed

2021-02-06 00:57 UTC, stanrc85 commented on keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c
> +  uint8_t layer = biton32(layer_state);
Fixed

2021-02-06 02:16 UTC, fauxpark approved these changes

2021-02-07 17:25 UTC, drashna commented
Thanks!

2021-02-07 17:26 UTC, merged