Added Function96v2 Keyboard
qmk/qmk_firmware pull request #11718
Opened 2021-01-28 04:13 UTC by MatthieuLu

## Description

Added the firmware files for the function96v2 board, and all files compile properly.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-30 05:50 UTC, drashna approved these changes

2021-02-05 21:58 UTC, fauxpark requested changes

2021-02-05 21:58 UTC, fauxpark commented on keyboards/function96v2/keymaps/ansi_splitspace/keymap.c
> +      )
```suggestion
```

2021-02-05 21:58 UTC, fauxpark commented on keyboards/function96v2/keymaps/ansi_splitspace/keymap.c
> +// Hello World
```suggestion
```

2021-02-05 21:58 UTC, fauxpark commented on keyboards/function96v2/keymaps/default/keymap.c
> +// Hello World
```suggestion
};
```

2021-02-05 21:58 UTC, fauxpark commented on keyboards/function96v2/keymaps/iso/keymap.c
> +// Hello World
```suggestion
};
```

2021-02-05 21:58 UTC, fauxpark commented on keyboards/function96v2/keymaps/iso_splitspace/keymap.c
> +// Hello World
```suggestion
};
```

2021-02-05 21:58 UTC, fauxpark commented on keyboards/function96v2/readme.md
> +* Keyboard Maintainer: The QMK Community
```suggestion
* Keyboard Maintainer: The QMK Community
```

2021-02-06 11:01 UTC, fauxpark approved these changes

2021-02-06 11:06 UTC, fauxpark requested changes
Whoops, actually the lint is complaining about these:

```
 ☒ function96v2: LAYOUT_default: Number of elements in info.json does not match! info.json:100 != LAYOUT_default:98
☒ function96v2: LAYOUT_ansi_splitspace: Number of elements in info.json does not match! info.json:102 != LAYOUT_ansi_splitspace:100
```

2021-02-07 17:24 UTC, drashna commented on keyboards/function96v2/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
Could you add instructions on how to enter the bootloader?

2021-02-08 22:30 UTC, noroadsleft commented
As this is a new revision of an existing keyboard design, you can and should set this up to share code across both v1 and v2 boards.

https://github.com/MatthieuLu/qmk_firmware/compare/d3845f15d899e4670ac245b5b3ba788ca6ee8cde...noroadsleft:c31136602bca520d7728a69d497e03e41c8b5377

2021-02-10 04:24 UTC, closed without merging