Add Alicia Cook keyboard
qmk/qmk_firmware pull request #11722
Opened 2021-01-29 14:08 UTC by ibnuda

add support for a split alice that will be given away soon in r/emk.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-01-30 06:10 UTC, drashna approved these changes

2021-02-07 22:43 UTC, zvecr requested changes

2021-02-07 22:43 UTC, zvecr commented on keyboards/alicia_cook/readme.md
> +*A short description of the keyboard/project*
```suggestion
```

2021-04-03 09:27 UTC, fauxpark requested changes

2021-04-03 09:27 UTC, fauxpark commented on keyboards/alicia_cook/info.json
> +            {"x":0,"y":0,"w":1,"h":1},
Width and height for 1u keys can be omitted.

2021-04-03 09:27 UTC, fauxpark commented on keyboards/alicia_cook/keymaps/default/keymap.c
> +        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL \
```suggestion
        KC_ESC, KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,            KC_Y,   KC_U,   KC_I,   KC_O,   KC_P,   KC_DEL, KC_BSPC,
        KC_LCTL,SH_A,   CT_S,   AL_D,   KC_F,   KC_G,            KC_H,   KC_J,   KC_K,   KC_L,   KC_QUOT,     KC_SCLN,
        KC_LSFT,KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,            KC_N,   KC_M,   KC_COMM,KC_DOT, KC_SLSH,KC_RSFT,MO(1),
        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL
    ),
    [1] = LAYOUT(
        KC_ESC, KC_1,   KC_2,   KC_3,   KC_4,   KC_5,            KC_6,   KC_7,   KC_8,   KC_9,   KC_0,   KC_DEL, KC_BSPC,
        KC_LCTL,KC_EXLM,KC_AT,  KC_HASH,KC_DLR, KC_PERC,         KC_CIRC,KC_AMPR,KC_ASTR,KC_LPRN,KC_RPRN,   KC_SCLN,
        KC_LSFT,KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,            KC_N,   KC_M,   KC_COMM,KC_DOT, KC_SLSH,KC_RSFT,MO(2),
        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL
    ),
    [2] = LAYOUT(
        KC_F1,  KC_F2,  KC_F3,  KC_F4,  KC_F5,  KC_F6,           KC_F7,  KC_F8,  KC_F9,  KC_F10, KC_F11, KC_F12, KC_F13,
        KC_LCTL,KC_EXLM,KC_AT,  KC_HASH,KC_DLR, KC_PERC,         KC_CIRC,KC_AMPR,KC_ASTR,KC_LPRN,KC_RPRN,   KC_SCLN,
        KC_LSFT,KC_Z,   KC_X,   KC_C,   KC_V,   RESET,           KC_N,   KC_M,   KC_COMM,KC_DOT, KC_SLSH,KC_RSFT,MO(1),
        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL
```

2021-04-03 09:27 UTC, fauxpark commented on keyboards/alicia_cook/keymaps/rick/keymap.c
> +        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL \
```suggestion
        KC_ESC, KC_SCLN,KC_COMM,KC_DOT, KC_P,   KC_Y,            KC_F,   KC_G,   KC_C,   KC_R,   KC_L,   KC_BSPC, KC_BSPC,
        KC_LCTL,SH_A,   CT_O,   AL_T,   KC_U,   GU_I,            GU_D,   KC_H,   AL_T,   CT_N,   SH_S,   KC_ENT,
        KC_LSFT,KC_QUOT,KC_Q,   KC_J,   KC_K,   KC_X,            KC_B,   KC_M,   KC_W,   KC_V,   KC_Z,   KC_RSFT,MO(1),
        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL
    ),
    [1] = LAYOUT(
        KC_ESC, KC_1,   KC_2,   KC_3,   KC_4,   KC_5,            KC_6,   KC_7,   KC_8,   KC_9,   KC_0,   KC_DEL, KC_BSPC,
        KC_LCTL,KC_EXLM,KC_AT,  KC_HASH,KC_DLR, KC_PERC,         KC_CIRC,KC_AMPR,KC_ASTR,KC_LPRN,KC_RPRN,   KC_SCLN,
        KC_LSFT,KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,            KC_N,   KC_M,   KC_COMM,KC_DOT, KC_SLSH,KC_RSFT,MO(2),
        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL
    ),
    [2] = LAYOUT(
        KC_F1,  KC_F2,  KC_F3,  KC_F4,  KC_F5,  KC_F6,           KC_F7,  KC_F8,  KC_F9,  KC_F10, KC_F11, KC_F12, KC_F13,
        KC_LCTL,KC_EXLM,KC_AT,  KC_HASH,KC_DLR, KC_PERC,         KC_CIRC,KC_AMPR,KC_ASTR,KC_LPRN,KC_RPRN,   KC_SCLN,
        KC_LSFT,KC_Z,   KC_X,   KC_C,   KC_V,   RESET,           KC_N,   KC_M,   KC_COMM,KC_DOT, KC_SLSH,KC_RSFT,MO(1),
        KC_LGUI,KC_LALT,        KC_LGUI,LW_BSPC,SFT_ESC,         ALT_ENT,RS_SPC, KC_LALT,                KC_RGUI,KC_RCTL
```

2021-05-11 22:17 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/11722/files).

2021-05-11 22:17 UTC, noroadsleft commented on keyboards/alicia_cook/config.h
> +
All of this can go.

```suggestion
```

2021-05-11 22:17 UTC, noroadsleft commented on keyboards/alicia_cook/keymaps/default/keymap.c
> +    [0] = LAYOUT(
```suggestion
    [0] = LAYOUT_all(
```

2021-11-05 03:01 UTC, tzarc commented
Removed tags preventing stalebot from auto-closing this PR.
I'd recommend working through the suggestions if you are keen on getting this PR merged.

2021-12-20 10:12 UTC, ibnuda commented
chief. any update?

2021-12-21 00:29 UTC, fauxpark requested changes

2021-12-21 00:29 UTC, fauxpark commented on keyboards/alicia_cook/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-21 00:29 UTC, fauxpark commented on keyboards/alicia_cook/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-12-21 00:29 UTC, fauxpark commented on keyboards/alicia_cook/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-12-21 00:29 UTC, fauxpark commented on keyboards/alicia_cook/info.json
> +  "height": 4,
```suggestion
```

2021-12-21 16:09 UTC, fauxpark requested changes

2021-12-21 16:09 UTC, fauxpark commented on keyboards/alicia_cook/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```

2021-12-21 16:09 UTC, fauxpark commented on keyboards/alicia_cook/rules.mk
> +NKRO_ENABLE = no            # Enable N-Key Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-21 17:32 UTC, drashna requested changes

2021-12-21 17:32 UTC, drashna commented on keyboards/alicia_cook/keymaps/rick/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-21 17:32 UTC, drashna commented on keyboards/alicia_cook/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-09 02:34 UTC, noroadsleft requested changes

2022-01-09 02:34 UTC, noroadsleft commented on keyboards/alicia_cook/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```

2022-01-09 02:34 UTC, noroadsleft commented on keyboards/alicia_cook/rules.mk
>  # if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-10 20:16 UTC, noroadsleft approved these changes

2022-01-10 22:47 UTC, fauxpark approved these changes

2022-01-11 03:20 UTC, merged

2022-01-11 03:20 UTC, drashna commented
Thanks!