Fix noxary i ds
qmk/qmk_firmware pull request #11771
Opened 2021-02-02 15:56 UTC by Rozakiin

## Description

Changed the product ID of noxary boards so that different revisions can have different IDs, previously used Device_Ver. This was changed so VIA can differenciate the boards correctly.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-05 06:53 UTC, drashna requested changes

2021-02-05 06:53 UTC, drashna commented on keyboards/noxary/220/config.h
> +#define DESCRIPTION     A fully customizable numpad keyboard.
This is no longer used, and should be removed.
```suggestion
```

2021-02-05 06:53 UTC, drashna commented on keyboards/noxary/260/config.h
> +#define DESCRIPTION     A fully customizable 60% keyboard.
This is no longer used, and should be removed.
```suggestion
```

2021-02-05 06:53 UTC, drashna commented on keyboards/noxary/280/config.h
> +#define DESCRIPTION     A fully customizable TKL keyboard.
This is no longer used, and should be removed.
```suggestion
```

2021-02-07 18:12 UTC, drashna approved these changes

2021-02-09 22:07 UTC, spidey3 approved these changes

2021-02-12 01:02 UTC, merged