[Keyboard] Support MJ64 REV3 which is a 60% RGB Hotswap keyboard with arrow
qmk/qmk_firmware pull request #11785
Opened 2021-02-04 06:48 UTC by melgeek001365

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-05 07:12 UTC, drashna requested changes

2021-02-05 07:12 UTC, drashna commented on keyboards/melgeek/mj64/rev3/rev3.c
> +#endif
```suggestion
#endif

void keyboard_pre_init_kb(void) {
    setPinOutput(A2);
    writePinHigh(A2);
    keyboard_pre_init_user();
}
```

2021-02-12 02:45 UTC, drashna approved these changes

2021-02-19 01:06 UTC, melgeek001365 commented
@fauxpark  hey, pleae help review this PR, :)

2021-02-20 04:07 UTC, fauxpark approved these changes

2021-02-21 05:05 UTC, drashna commented
Thanks!

2021-02-21 05:05 UTC, merged