Add UTD80 PCB
qmk/qmk_firmware pull request #11799
Opened 2021-02-05 04:08 UTC by dominicgan

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Continuing #7701 (abandoned by owner)

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-05 07:39 UTC, drashna requested changes

2021-02-05 07:39 UTC, drashna commented on keyboards/utd80/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-05 07:39 UTC, drashna commented on keyboards/utd80/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-05 07:39 UTC, drashna commented on keyboards/utd80/utd80.c
> +}
All of this can be replaced with a define. or two. 
```suggestion
```

2021-02-05 07:39 UTC, drashna commented on keyboards/utd80/config.h
> +/* define if matrix has ghost */
```suggestion
#define LED_CAPS_LOCK_PIN B6
#define LED_SCROLL_LOCK_PIN B5

/* define if matrix has ghost */
```

2021-02-05 07:39 UTC, drashna commented on keyboards/utd80/utd80.c
> +#include "utd80.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-05 07:39 UTC, drashna commented on keyboards/utd80/utd80.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-05 08:20 UTC, drashna approved these changes

2021-02-16 01:25 UTC, spidey3 reviewed
Just to be clear - I see from your description that you have picked this up when the original maintainer (UTDKeyboard) didn't finish getting their PR approved and merged. But I note that you've added their company name to the copyright notice, and not your own name. Is that what you intend? Are you associated with UTDKeyboard, or have you spoken with them about this?

2021-02-16 01:56 UTC, dominicgan commented
@spidey3 Hello, no I'm not affiliated with the company, I was just picking up on the changes requested where the previous PR #7701 was left off. I used their company name since I didn't contribute much aside from cleaning it up and adding a via keymap. 

I have tried to contact them to no avail so I'm working on this independently. If it helps I could change the attribution?

2021-02-16 02:07 UTC, spidey3 commented
> @spidey3 Hello, no I'm not affiliated with the company, I was just picking up on the changes requested where the previous PR #7701 was left off. I used their company name since I didn't contribute much aside from cleaning it up and adding a via keymap.

I think I would change the attribution to "UTDKeyboard & Dominic Gan", just to be accurate.

2021-02-16 02:47 UTC, dominicgan commented
> I think I would change the attribution to "UTDKeyboard & Dominic Gan", just to be accurate.

will do, thanks!

2021-02-18 20:30 UTC, spidey3 approved these changes

2021-02-18 20:30 UTC, merged