Simplify NIBBLE encoder code and clean up keymaps
qmk/qmk_firmware pull request #11808
Opened 2021-02-06 07:56 UTC by jaygreco

## Description

-Removed overly complex VIA encoder code. It wasn't adding any value and was confusing users who were trying to customize encoder functionality on VIA keymaps.
-Replaced KC_TILDE with KC_HOME in all keymaps, as KC_TILDE sends a left shift, which was confusing some folks as they tested their build.
-Move layer names to enum

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-06 12:54 UTC, zvecr requested changes

2021-02-06 12:54 UTC, zvecr commented on keyboards/nullbitsco/nibble/keymaps/via/keymap.c
> +void encoder_update_kb(uint8_t index, bool clockwise) {
Looks like the other keymaps also suffer from this issue

```suggestion
void encoder_update_user(uint8_t index, bool clockwise) {
```

2021-02-09 12:16 UTC, fauxpark approved these changes

2021-02-09 14:50 UTC, zvecr approved these changes

2021-02-09 14:50 UTC, merged