Add DimplePlus 7u Layout
qmk/qmk_firmware pull request #11816
Opened 2021-02-07 17:32 UTC by jbaskeen

## Description

This change introduces the 7u layout option with 2.25 enter key and 2.0 BS key to qmk for the DimplePlus keyboard. Since this layout was being added, I also updated the existing layout's layout spacing in an attempt to improve readability.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

No/A

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-07 18:26 UTC, drashna approved these changes

2021-02-07 19:10 UTC, jbaskeen commented
@jackytrabbit FYI in case I did anything inappropriate here. This is my first qmk contribution so I'm not confident I put it together correctly for D+.

2021-02-07 20:37 UTC, zvecr requested changes

2021-02-07 20:37 UTC, zvecr commented on keyboards/lazydesigners/dimpleplus/info.json
> +                {"label":"K404 (F5,C7)", "x":3.75, "y":4.25, "w":7.00},
```suggestion
                {"label":"K404 (F5,C7)", "x":2.75, "y":4.25, "w":7.00},
```

2021-02-07 22:00 UTC, jbaskeen commented on keyboards/lazydesigners/dimpleplus/info.json
> +                {"label":"K404 (F5,C7)", "x":3.75, "y":4.25, "w":7.00},
@zvecr good catch, thanks. Fix pushed

2021-02-17 02:26 UTC, jbaskeen commented
@zvecr any other feedback to get this wrapped up?

2021-02-20 05:23 UTC, fauxpark approved these changes

2021-02-21 04:49 UTC, drashna commented
Thanks!

2021-02-21 04:49 UTC, merged