Latin6rgb use IS31FL3731 IC
qmk/qmk_firmware pull request #11819
Opened 2021-02-07 21:27 UTC by 18438880

## Description

Latin6rgb use IS31FL3731 IC

## Types of Changes

- [x] Core
- [x] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-12 03:06 UTC, drashna commented on keyboards/latin6rgb/rules.mk
> +RGB_MATRIX_DRIVER = IS31FL3731
```suggestion
RGB_MATRIX_DRIVER = IS31FL3731

RGB_MATRIX_SUPPORTED = yes
```

2021-02-12 23:23 UTC, drashna requested changes

2021-02-12 23:23 UTC, drashna commented on keyboards/latin6rgb/keymaps/default/keymap.c
> +const uint8_t music_map[MATRIX_ROWS][MATRIX_COLS] = LAYOUT_numpad_2x3(
This should probably go into the keyboard's c file rather than in the keymap.

2021-02-12 23:23 UTC, drashna commented on keyboards/latin6rgb/rules.mk
> +HD44780_ENABLE = no            # Enable support for HD44780 based LCDs
```suggestion
BLUETOOTH_ENABLE = no          # Enable Bluetooth
AUDIO_ENABLE = no              # Audio output
```

2021-03-03 21:12 UTC, drashna approved these changes

2021-05-14 02:02 UTC, drashna approved these changes

2021-06-24 02:45 UTC, tzarc approved these changes

2021-06-24 02:46 UTC, merged