[Keyboard] keyboards/anavi: Add ANAVI Macro Pad 2
qmk/qmk_firmware pull request #11821
Opened 2021-02-07 23:39 UTC by leon-anavi

ANAVI Macro Pad 2 is an open source mini mechanical keyboard with
2 keys and backlit. Powered by ATtiny 85 microcontroller and with
microUSB connector. Designed with KiCad.

Provides the following keymaps for ANAVI Macro Pad 2:

- Default (with a, b and combo to control the LEDs)
- Copy & paste
- Tap dance example with a, b and c
- Mute
- Volume
- Zoom
- Jitsi Meet

Signed-off-by: Leon Anavi <leon@anavi.org>

## Description

Add new keyboard ANAVI Macro Pad 2 and several keymaps for it.

ANAVI Macro Pad 2 is an open source mini mechanical keyboard with 2 keys and 2 LEDs for backlit. Powered by ATtiny 85 microcontroller and with microUSB connector. The PCB has been designed with the free and open source software KiCad.

This patch provides the following keymaps for ANAVI Macro Pad 2:

- Default (with a, b and combo to control the LEDs)
- Copy & paste
- Tap dance example with a, b and c
- Mute
- Volume
- Zoom
- Jitsi Meet

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-12 03:14 UTC, drashna requested changes

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/copypaste/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/jitsi/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/mute/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/tap_dance/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/tap_dance/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 03:14 UTC, drashna commented on keyboards/anavi/macropad2/keymaps/zoom/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-12 23:13 UTC, leon-anavi commented
Hi @drashna,

Thank you for the feedback. Following your recommendations I have added GPL2+ compatible license header to all .c files for the keymaps.
 
 Best regards, Leon

2021-02-12 23:28 UTC, drashna commented on keyboards/anavi/macropad2/rules.mk
> +HD44780_ENABLE = no         # Enable support for HD44780 based LCDs
```suggestion
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
MIDI_ENABLE = no            # MIDI support
UNICODE_ENABLE = no         # Unicode
BLUETOOTH_ENABLE = no       # Enable Bluetooth 
AUDIO_ENABLE = no           # Audio output
```

2021-02-12 23:56 UTC, leon-anavi commented
@drashna thank you. I've fix it, added your credentials as `Co-authored-by` git trailer and forced push the new version of the patch.

Thanks, Leon

2021-02-14 21:12 UTC, drashna approved these changes

2021-02-20 19:46 UTC, spidey3 approved these changes

2021-02-20 19:47 UTC, merged