Add Conone 65
qmk/qmk_firmware pull request #11827
Opened 2021-02-08 10:49 UTC by evyd13

## Description

Adds the Conone 65 keyboard to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-12 23:53 UTC, drashna requested changes

2021-02-12 23:53 UTC, drashna commented on keyboards/kindakeyboards/conone65/config.h
> +#define VENDOR_ID    0x1776
This vendor ID is already in use.  Please change.

https://www.the-sz.com/products/usbid/index.php?v=0x1776&p=&n=

2021-02-12 23:53 UTC, drashna commented on keyboards/kindakeyboards/conone65/config.h
> +#define PRODUCT_ID   0x6aab
```suggestion
#define PRODUCT_ID   0x6AAB
```

2021-02-19 03:34 UTC, drashna approved these changes

2021-02-20 05:23 UTC, fauxpark requested changes

2021-02-20 05:23 UTC, fauxpark commented on keyboards/kindakeyboards/conone65/readme.md
> +*The Conone 65 is a custom keyboard designed and machined in Belgium.*
```suggestion
The Conone 65 is a custom keyboard designed and machined in Belgium.
```

2021-03-02 13:44 UTC, fauxpark approved these changes

2021-03-03 21:14 UTC, drashna commented
Thanks for your contribution!

2021-03-03 21:14 UTC, merged