[Keymap] Add MOC keymap for meishi2
qmk/qmk_firmware pull request #11833
Opened 2021-02-09 00:15 UTC by ngs

## Description

Keymap to control [MOC] music player with Meishi2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

[MOC]: http://moc.daper.net/

2021-02-13 01:43 UTC, spidey3 requested changes

2021-02-13 01:43 UTC, spidey3 commented on keyboards/meishi2/keymaps/moc/config.h
> +/* Copyright 2019 Biacco42
This should refer to your actual name, not just to a user id.  Also, you might want to update the year.

2021-02-13 01:43 UTC, spidey3 commented on keyboards/meishi2/keymaps/moc/keymap.c
> +/* Copyright 2019 Biacco42
Same here; it needs a full name, and the correct year.

2021-02-13 01:43 UTC, spidey3 commented on keyboards/meishi2/keymaps/moc/keymap.c
> +    RAISE, KC_B, KC_N, KC_SPC \
No backslash needed at the end of this line.
```suggestion
    RAISE, KC_B, KC_N, KC_SPC
```

2021-02-13 01:43 UTC, spidey3 commented on keyboards/meishi2/keymaps/moc/keymap.c
> +    _______, KC_LEFT, KC_RGHT, LSFT(KC_S) \
```suggestion
    _______, KC_LEFT, KC_RGHT, LSFT(KC_S)
```

2021-02-14 16:43 UTC, spidey3 approved these changes

2021-02-14 21:19 UTC, drashna approved these changes

2021-02-14 21:19 UTC, drashna commented
Thanks!

2021-02-14 21:19 UTC, merged