Add Manibus keyboard and layout from Blank Tehnologii
qmk/qmk_firmware pull request #11832
Opened 2021-02-08 23:06 UTC by SamuraiKek

## Description
Initial PR adding Manibus keyboard. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-13 00:21 UTC, drashna requested changes

2021-02-13 00:21 UTC, drashna commented on keyboards/blank_tehnologii/manibus/keymaps/default/keymap.c
> +};
```suggestion
enum custom_keycodes {
  _QWERTY,
  _LOWER
};

#define LOWER MO(_LOWER)
```

2021-02-13 00:21 UTC, drashna commented on keyboards/blank_tehnologii/manibus/keymaps/default/keymap.c
> +}
```suggestion
```

2021-02-13 00:21 UTC, drashna commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +#define _MEDIA 4
We highly recommend using enums for the layer naming, as it is easier to maintain long term. 

```suggestion
enum custom_layers {
    _QWERTY,
    _LOWER,
    _UPPER,
    _MOUSE,
    _MEDIA,  
);
```

2021-02-13 00:21 UTC, drashna commented on keyboards/blank_tehnologii/manibus/rules.mk
> +# OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu
```

2021-02-13 00:21 UTC, drashna commented on keyboards/blank_tehnologii/manibus/rules.mk
> +HD44780_ENABLE = no 		# Enable support for HD44780 based LCDs (+400)
```suggestion
# Build Options
#   change yes to no to disable
BOOTMAGIC_ENABLE = no      # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
UNICODE_ENABLE = no         # Unicode
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-02-14 22:09 UTC, fauxpark requested changes

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/readme.md
> +```make blank_tehnologii/manibus:default```
```suggestion
    make blank_tehnologii/manibus:default
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/readme.md
> +```make blank_tehnologii/manibus:default:dfu-split-right```
```suggestion
    make blank_tehnologii/manibus:default:dfu-split-left # Left half
    make blank_tehnologii/manibus:default:dfu-split-right # Right half
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/readme.md
> +
```suggestion
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/readme.md
> +Hardware Availability: [Blank Tehnologii](https://blank.computer/)
```suggestion
* Keyboard Maintainer: [Alex Paulescu/SamuraiKek](https://github.com/SamuraiKek)
* Hardware Supported: [ATmega32u4](https://www.digikey.com/en/products/detail/microchip-technology/ATMEGA32U4-AU/1914602)
*  Hardware Availability: [Blank Tehnologii](https://blank.computer/)
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/readme.md
> +![Imgur](https://i.imgur.com/0l17Xyy.jpg)
```suggestion
![Imgur](https://i.imgur.com/0l17Xyyl.jpg)
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +    unregister_code(KC_NUMLOCK);
```suggestion
    tap_code(KC_NLCK);
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +            SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSHIFT)SS_TAP(X_T)SS_UP(X_LCTL)SS_UP(X_LSHIFT));
```suggestion
            tap_code16(C(S(KC_T)));
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +            SEND_STRING(SS_DOWN(X_LCTL)SS_TAP(X_T)SS_UP(X_LCTL));
```suggestion
            tap_code16(C(KC_T));
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +            SEND_STRING(SS_DOWN(X_LCTL)SS_TAP(X_W)SS_UP(X_LCTL));
```suggestion
            tap_code16(C(KC_W));
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +        SEND_STRING(SS_DOWN(X_LALT)SS_TAP(X_F4)SS_UP(X_LALT));
```suggestion
        tap_code16(A(KC_F4));
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +        SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LSHIFT)SS_TAP(X_TAB)SS_UP(X_LCTL)SS_UP(X_LSHIFT));
```suggestion
        tap_code16(C(S(KC_TAB)));
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +        SEND_STRING(SS_DOWN(X_LCTL)SS_TAP(X_TAB)SS_UP(X_LCTL));
```suggestion
        tap_code16(C(KC_TAB));
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +            SEND_STRING(SS_TAP(X_SPC));
```suggestion
            tap_code(KC_SPC);
```

2021-02-14 22:09 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
> +             SEND_STRING(SS_TAP(X_ENT));
```suggestion
             tap_code(KC_ENT);
```

2021-02-18 19:40 UTC, SamuraiKek commented
Thanks for the changes folks. Some nice improvements to the code that I didn't know about :D

2021-02-19 03:37 UTC, drashna approved these changes

2021-02-20 05:29 UTC, fauxpark requested changes

2021-02-20 05:29 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/rules.mk
> +
```suggestion
```

2021-02-20 05:29 UTC, fauxpark commented on keyboards/blank_tehnologii/manibus/readme.md
> +*  Hardware Availability: [Blank Tehnologii](https://blank.computer/)
```suggestion
* Hardware Availability: [Blank Tehnologii](https://blank.computer/)
```

2021-02-22 00:21 UTC, fauxpark approved these changes

2021-02-22 04:44 UTC, drashna approved these changes

2021-02-22 04:45 UTC, merged