Adding Zodiark Split keyboard
qmk/qmk_firmware pull request #11837
Opened 2021-02-09 04:16 UTC by Aleblazer

## Description

Adding Aleblazer/Zodiark split keyboard and keymaps

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-09 14:29 UTC, zvecr requested changes

2021-02-09 14:29 UTC, zvecr commented on keyboards/aleblazer/zodiark/zodiark.h
> + L00, L01, L02, L03, L04, L05, L06, R00, R01, R02, R03, R04, R05, R06, \
Top part of layout macro should represent physical layout, currently it does not match the image provided in the readme

2021-02-09 14:29 UTC, zvecr commented on keyboards/aleblazer/zodiark/rules.mk
> +RGB_MATRIX_DRIVER = WS2812
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
OLED_DRIVER_ENABLE = yes    # Enable Support for SSD1306 or SH1106 OLED Displays; Communicating over I2C
ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
```

2021-02-09 14:29 UTC, zvecr commented on keyboards/aleblazer/zodiark/config.h
> +#define CONFIG_H
```suggestion
#pragma once
```

2021-02-09 14:29 UTC, zvecr commented on keyboards/aleblazer/zodiark/config.h
> +
```suggestion

```

2021-02-09 14:29 UTC, zvecr commented on keyboards/aleblazer/zodiark/config.h
> +#endif
```suggestion
```

2021-02-10 03:48 UTC, Aleblazer commented
Applied all change requests, and thanks to ridingqwerty in the QMK Discord, fixed the zodiark.h layout and all the keymaps to reflect the shift in key locations.

2021-02-10 04:02 UTC, fauxpark requested changes

2021-02-10 04:02 UTC, fauxpark commented on keyboards/aleblazer/zodiark/readme.md
> +```
```suggestion
* Keyboard Maintainer: [Aleblazer](https://github.com/Aleblazer/), [Discord Link](https://discord.gg/BCSbXwskVt)
* Hardware Supported: Pro Micro and derivatives
* Hardware Availability: Pending Group Buy - [Discord Link](https://discord.gg/BCSbXwskVt)

Make example for this keyboard (after setting up your build environment):

    make zodiark:default

Flashing example for this keyboard:

    make zodiark:default:flash

2021-02-10 04:02 UTC, fauxpark commented on keyboards/aleblazer/zodiark/zodiark.h
> +#include "split_util.h"
```suggestion
```

2021-02-10 04:02 UTC, fauxpark commented on keyboards/aleblazer/zodiark/rules.mk
> +RGB_MATRIX_ENABLE = no
```suggestion
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
OLED_DRIVER_ENABLE = yes    # Enable Support for SSD1306 or SH1106 OLED Displays; Communicating over I2C
ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
LTO_ENABLE = yes
```

2021-02-10 04:14 UTC, Aleblazer commented
Applied all suggestions from fauxpark, and added RGB_MATRIX_DRIVER = WS2812 to my rgbmatrixwip keymap rules.mk.

2021-02-13 00:44 UTC, drashna requested changes

2021-02-13 00:44 UTC, drashna commented on keyboards/aleblazer/zodiark/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-13 00:44 UTC, drashna commented on keyboards/aleblazer/zodiark/config.h
> +#endif
Is this is defined at the keyboard level, it probably doesn't need to be fined here.
```suggestion
```

2021-02-13 00:44 UTC, drashna commented on keyboards/aleblazer/zodiark/keymaps/rgbmatrixwip/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-13 00:44 UTC, drashna commented on keyboards/aleblazer/zodiark/keymaps/rgbmatrixwip/rules.mk
> +RGB_MATRIX_DRIVER = WS2812
This should be moved to the keyboard's config.

2021-02-13 00:44 UTC, drashna commented on keyboards/aleblazer/zodiark/keymaps/slimoled/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-13 01:11 UTC, Aleblazer commented
Cleaned up the OLED code from the keyboard level config.h, added the GPL2+ license header to all keymaps, and removed the rgbmatrixwip keymap (Matrix split effects didn't work without a custom solution at this time).

2021-02-14 21:38 UTC, drashna approved these changes

2021-02-14 21:38 UTC, drashna commented on keyboards/aleblazer/zodiark/config.h
> +#define MASTER_LEFT
This isn't actually needed, as this is the default behavior. 
```suggestion
```

2021-02-14 21:38 UTC, drashna commented on keyboards/aleblazer/zodiark/config.h
> +#define USE_SERIAL
This is the default behavior, so this isn't needed.
```suggestion
```

2021-02-14 22:29 UTC, fauxpark requested changes

2021-02-14 22:29 UTC, fauxpark commented on keyboards/aleblazer/zodiark/readme.md
> +![Zodiark Split](https://i.imgur.com/49O8aow.jpg)
```suggestion
![Zodiark Split](https://i.imgur.com/49O8aowl.jpg)
```

2021-03-04 02:32 UTC, Aleblazer commented
All requested changes have been made, and added a VIA keymap.

2021-03-04 04:40 UTC, fauxpark approved these changes

2021-03-06 18:56 UTC, zvecr approved these changes

2021-03-06 18:56 UTC, merged

2021-03-06 18:56 UTC, zvecr commented
Thanks"