Adding phrygiandesign ph100 attempt 2
qmk/qmk_firmware pull request #11860
Opened 2021-02-11 11:51 UTC by phrygiandesign

Second attempt for pulling ph100 config and code into mainline qmk. Previous attempt here: https://github.com/qmk/qmk_firmware/pull/11514

Re, the removal of the "boards" folder, the ph100 firmware does not compile without it, throwing the following error:

```
Compiling keymap with make phrygian/ph100:default

QMK Firmware 0.9.32
Making phrygian/ph100 with keymap default

tmk_core/chibios.mk:111: lib/chibios-contrib/os/hal/boards/GENERIC_STM32_F042X6/board.mk: No such file or directory
make[1]: *** No rule to make target 'lib/chibios-contrib/os/hal/boards/GENERIC_STM32_F042X6/board.mk'.  Stop.
Make finished with errors
make: *** [Makefile:584: phrygian/ph100:default] Error 1
```

## Description

Addition of files and configuration for the [Phrygian Design ph100](https://phrygiandesign.com/products/ph100-mechanical-keyboard)

The ph100 board uses a STM32F042 microcontroller and provides 100 modular keyswitch positions.

I'm available to be contacted via github: @phrygiandesign or email: contact@phrygiandesign.com

2021-02-13 01:11 UTC, drashna requested changes

2021-02-13 01:11 UTC, drashna commented on keyboards/phrygian/ph100/boards/GENERIC_STM32_F042X6/board.c
> +/*
All of these chibiOS files may not be needed, since they also reside in `/platform/chibios/GENERIC_STM32_F04X6`

2021-02-27 20:32 UTC, tzarc commented
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

2021-05-04 15:57 UTC, noroadsleft commented
I am able to get a successful compile for this board by following these steps:

1. Rebase your source branch `phrygiandesign:develop` upon `qmk:master`.
2. `cd` to the root `qmk_firmware` directory.
3. Run the following commands, one at a time:
   ```shell
   qmk chibios-confmigrate -r platforms/chibios/common/configs/chconf.h -i keyboards/phrygian/ph100/chconf.h -o
   qmk chibios-confmigrate -r platforms/chibios/common/configs/halconf.h -i keyboards/phrygian/ph100/halconf.h -o
   qmk chibios-confmigrate -r platforms/chibios/GENERIC_STM32_F042X6/configs/mcuconf.h -i keyboards/phrygian/ph100/mcuconf.h -o -d
   rm -r keyboards/phrygian/ph100/boards/
   ```
   - The third command above will give a notice, but still delete your `mcuconf.h`

Your ChibiOS files are based on an older version of ChibiOS, so your board doesn't compile on current QMK as-is. QMK periodically updates the ChibiOS version, and uses an "import" system of sorts such that the keyboards are not tied to a specific ChibiOS version. Without this system, those boards could break every time QMK updates ChibiOS.

You'll want to test the firmware on a board after making these changes but **BEFORE** committing them to your source branch.

2021-05-24 08:50 UTC, phrygiandesign commented
Hey again, apologies for the long time between commits.
phrygiandesign/qmk_firmware has been brought up to date with the mainline repo, I've also made the requisite changes to get this thing over the line.
Let me know if you need anything else or if there are any more issues pulling my code in.

2021-06-16 05:22 UTC, drashna commented
it looks like you need a rebase, as it's touching a BUNCH of files that it shouldn't (eg, that are older commits)

2021-07-27 09:45 UTC, phrygiandesign commented
Closing for the time being, will create a new pull request with a cleaner branch.

2021-07-27 09:45 UTC, closed without merging