Refactor platform logic within print.h
qmk/qmk_firmware pull request #11863
Opened 2021-02-11 23:54 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-13 01:28 UTC, drashna approved these changes

2021-02-13 01:37 UTC, fauxpark requested changes
Would prefer not to use CamelCase for the function pointer type, but otherwise looks nice.

2021-02-13 01:37 UTC, fauxpark commented on tmk_core/protocol/vusb/main.c
>      // for Console_Task
```suggestion
```

2021-02-14 00:44 UTC, tzarc approved these changes

2021-02-14 00:44 UTC, tzarc commented on tmk_core/common/printf.c
> +}
```suggestion
static int8_t null_sendchar_func(uint8_t c) { return 0; }
static sendchar_func_t func = null_sendchar_func;

void print_set_sendchar(sendchar_func_t send) { func = send; }

void _putchar(char character) {
    func(character);
}
```

Maybe we do this so we're not checking a conditional each character?

2021-02-14 00:58 UTC, fauxpark approved these changes

2021-02-14 01:44 UTC, merged