Update rules.mk
qmk/qmk_firmware pull request #11906
Opened 2021-02-14 19:55 UTC by chilok29

changes enabling mouse keys and media keys on Octagon V2

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-14 19:57 UTC, chilok29 commented
I'm trying to find a way to enable media key and mouse key on Octagon V2 layers. First time messing with github apology if not done correctly

2021-02-16 11:11 UTC, filterpaper requested changes

2021-02-16 11:11 UTC, filterpaper commented on keyboards/duck/octagon/v2/rules.mk
> +EXTRAKEY_ENABLE = yes        # Audio control and System control
```suggestion
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = no       # Audio control and System control
```
You should leave these as default, and add both changes to the `rules.mk` in your own keymap folder: `keyboards/duck/octagon/keymaps/chilok29/rules.mk`. See [this page](https://docs.qmk.fm/#/newbs_building_firmware) for more details.

2021-02-20 19:08 UTC, spidey3 requested changes
I agree with @filterpaper's suggestion. Please address that, and we will be able to complete the review.

2021-06-02 17:30 UTC, closed without merging