[Keyboard] Pill60: fix default keymap shift key, fix info.json to default keymap
qmk/qmk_firmware pull request #11919
Opened 2021-02-15 16:51 UTC by IktaS

Default keymap left and right shift key is fixed. Also fixed info.json to represent default keymap.

## Description

Swapped keymap left and right shift key is to fix it, removed "Ikta's" to make it more general. Also fixed info.json to represent how default keymap is.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-18 23:45 UTC, zvecr requested changes

2021-02-18 23:45 UTC, zvecr commented on keyboards/handwired/pill60/info.json
>                  {"label": "0","x": 10, "y": 1},
This file still renders incorrectly, as shown in the lint jobs output
```
Layout:
┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐
│e0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k0││k1││k1││k1││k1││k1││k1││k1││k1││k1││k1││k1││k1││k1││k1││k2││k2││k2││k2││k2││k2││k2││k2││k2││k2││k2││k2││k2││k3││k3││k3││k3││k3││k3││k3││k3││k3││k3││k3││k3││k3││k4││k4││k4││k4││k4││k4││k4││k4│
└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘
```

2021-02-20 05:36 UTC, fauxpark approved these changes

2021-02-21 06:16 UTC, drashna approved these changes

2021-02-21 06:19 UTC, merged