Add missing RGB_MODE_TWINKLE / RGB_M_TW keycodes
qmk/qmk_firmware pull request #11935
Opened 2021-02-16 18:51 UTC by spidey3

## Description

When the Twinkle effect was implemented, keycodes were not created to select it.
This adds them.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-16 20:40 UTC, fauxpark commented
Just a note, this will break VIA. At least the Space Cadet keycodes, and maybe EEPROM reset, though I can't find it in the list.

2021-02-16 20:46 UTC, spidey3 commented
> Just a note, this will break VIA. At least the Space Cadet keycodes, and maybe EEPROM reset, though I can't find it in the list.

Ooh, ouch.
Should I re-point it at develop?

2021-02-19 06:31 UTC, drashna approved these changes

2021-02-27 20:32 UTC, tzarc commented
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

2021-04-05 19:02 UTC, spidey3 commented
Rebased, taken off hold.

2021-04-05 19:25 UTC, drashna approved these changes

2021-04-06 04:13 UTC, fauxpark requested changes

2021-04-06 04:13 UTC, fauxpark commented on quantum/quantum_keycodes.h
> +    // Miscellaneous recent additions
```suggestion
    // RGB underglow/matrix (continued)
```

2021-04-08 02:15 UTC, fauxpark approved these changes

2021-04-15 23:32 UTC, merged