Matrix fix for KBD75 round 1&2
qmk/qmk_firmware pull request #11941
Opened 2021-02-17 18:57 UTC by gazer000

## Description

- KBD75 round 1&2, even though using ps2avrGB (same as B.mini), appears to have a different key matrix, upon flashing B.mini hex onto these boards, some keys are incorrectly mapped while 1-2 keys may not work

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-17 23:52 UTC, mechmerlin commented
I would prefer that the directory naming would be

kbdfans/kbd75/bmc or kbdfans/kbd75/ps2avrGB

also, don't forget to update the readme located in the kbdfans/kbd75 directory to point to these new ones.

2021-02-18 00:59 UTC, spidey3 requested changes
Please update LAYOUT_splitbs too.

2021-02-18 00:59 UTC, spidey3 commented on keyboards/kbdfans/kbd75round1/kbd75round1.h
> +
Can you apply your fix to the LAYOUT_splitbs too?  The only difference should be split backspace support.

2021-02-18 00:59 UTC, spidey3 commented on keyboards/kbdfans/kbd75round1/readme.md
> +
Please add a link to a pcb image, and some text describing how to discern this vs. other "kbd75" variants.

2021-02-18 14:53 UTC, gazer000 commented
> I would prefer that the directory naming would be
> 
> kbdfans/kbd75/bmc or kbdfans/kbd75/ps2avrGB
> 
> also, don't forget to update the readme located in the kbdfans/kbd75 directory to point to these new ones.
> 
> Also, there is a chance that there are other discrepencies here, as I've build a few BMC KBD75s, and the b mini hex file worked just fine.

My PCB is a white v1 PCB (probably round 2) that looks exactly like any other v1 PCB but without the reset button and uses atmega32a instead of 32u4. I'll rename the folder to my exact PCB (which is a round 2 PCB) instead of generalizing this for both round 1 and 2 PCBs.

2021-02-18 16:48 UTC, spidey3 requested changes
Sorry - one more small change requested.

2021-02-18 16:48 UTC, spidey3 commented on keyboards/kbdfans/kbd75_round2/rules.mk
> +BOOTMAGIC_ENABLE = full
We prefer [Bootmagic Lite](https://docs.qmk.fm/#/feature_bootmagic?id=bootmagic-lite) for any new keyboards, as it eliminates a major source of confusion around key swaps, disabled keys, eeprom reset, etc.
```suggestion
BOOTMAGIC_ENABLE = lite
```

2021-02-18 20:17 UTC, spidey3 approved these changes

2021-02-18 23:16 UTC, zvecr requested changes
> I would prefer that the directory naming would be
> 
> kbdfans/kbd75/bmc or kbdfans/kbd75/ps2avrGB

I 2nd this, and would rather see it under the existing kbd75 folder as a sub revision. As for revision name, `round2` would be fine with me. (if going with "ps2avrGB", it would have to be lower case)

2021-02-19 01:59 UTC, spidey3 commented
@gazer000 can you please check whether `ymd75/rev1` firmware works on your keyboard as you would expect, with the correct key mappings? We have some evidence that this might be the case.

Also, please verify the mappings of the Del vs. Backspace for the splitbs LAYOUT.  I suspect they might be reversed.

2021-02-19 02:46 UTC, gazer000 commented
> @gazer000 can you please check whether `ymd75/rev1` firmware works on your keyboard as you would expect, with the correct key mappings? We have some evidence that this might be the case.
> 
> Also, please verify the mappings of the Del vs. Backspace for the splitbs LAYOUT. I suspect they might be reversed.

It seems that what you're suspecting is true, the ymd75/rev1 firmware does work on my board with the correct key mappings

2021-02-19 03:13 UTC, spidey3 commented
> It seems that what you're suspecting is true, the ymd75/rev1 firmware does work on my board with the correct key mappings - the header files look identical

If that firmware works on your keyboard, I think I would like to close this PR, and file a new one to update `kbd75/readme.md` to indicate that round2 == ymd75/rev1.

2021-02-21 07:31 UTC, closed without merging