Add Daji Seis Cinco
qmk/qmk_firmware pull request #11955
Opened 2021-02-19 16:46 UTC by toraifu

## Description

Adding support for the Daji Seis Cinco, a minimalist 65% layout keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-20 07:05 UTC, drashna requested changes

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/config.h
> +#define DESCRIPTION     65 layout keyboard
```suggestion
```

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/keymaps/split_backspace/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/seis_cinco.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-20 07:05 UTC, drashna commented on keyboards/daji/seis_cinco/seis_cinco.c
> +#include "seis_cinco.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-21 06:20 UTC, drashna approved these changes

2021-02-21 07:07 UTC, fauxpark requested changes

2021-02-21 07:07 UTC, fauxpark commented on keyboards/daji/seis_cinco/keymaps/default/keymap.c
> +    KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                            KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS)
```suggestion
```

2021-02-21 07:07 UTC, fauxpark commented on keyboards/daji/seis_cinco/keymaps/split_backspace/keymap.c
> +    KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                            KC_TRNS,          KC_TRNS, KC_TRNS,          KC_TRNS)
```suggestion
```

2021-02-21 07:07 UTC, fauxpark commented on keyboards/daji/seis_cinco/rules.mk
> +RGBLIGHT_ENABLE = no
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = yes      # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-02-22 00:18 UTC, fauxpark approved these changes

2021-02-22 03:42 UTC, merged