NK65 Pinout change for rev 1.4
qmk/qmk_firmware pull request #11991
Opened 2021-02-23 15:57 UTC by yiancar

## Description
New revision of NK65 has a pin change for 3 columns.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-04 21:05 UTC, zvecr requested changes

2021-03-04 21:05 UTC, zvecr commented on keyboards/nk65/v1_4/rules.mk
> +		drivers/chibios/i2c_master.c
Empty file should be enough to make it a board revision
```suggestion
```

2021-03-04 21:10 UTC, zvecr approved these changes

2021-03-05 02:38 UTC, fauxpark approved these changes

2021-03-05 05:15 UTC, noroadsleft approved these changes

2021-03-05 05:15 UTC, merged

2021-03-05 05:15 UTC, noroadsleft commented
Thanks!