Keymaps and Readme
qmk/qmk_firmware pull request #12004
Opened 2021-02-25 02:40 UTC by nautxx

## Description
New keymaps added for Hasu USB to USB, Ramaworks U80 and HHKB. Revised old keymaps for Ramaworks M65-A and M6-A. Readme's updated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [x ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-27 05:21 UTC, drashna requested changes

2021-02-27 05:21 UTC, drashna commented on keyboards/converter/usb_usb/keymaps/naut/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/converter/usb_usb/keymaps/naut/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/hhkb/ansi/keymaps/naut/keymap.c
> +/*  -*-  eval: (turn-on-orgtbl); -*-
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/jc65/v32a/keymaps/gbarnz/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/jc65/v32a/keymaps/naut/keymap.c
>  #include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/jc65/v32u4/keymaps/naut/keymap.c
>  #include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/wilba_tech/rama_works_m60_a/keymaps/naut/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/wilba_tech/rama_works_m6_a/keymaps/naut/keymap.c
>  #include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-27 05:21 UTC, drashna commented on keyboards/wilba_tech/rama_works_u80_a/keymaps/naut/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-03-20 15:12 UTC, nautxx reviewed
Requested changes made.

2021-04-03 00:09 UTC, drashna approved these changes

2021-04-03 09:33 UTC, fauxpark requested changes

2021-04-03 09:33 UTC, fauxpark commented on keyboards/converter/usb_usb/keymaps/naut/config.h
> +/* Copyright 2021 Jason Barnachea
This file can be deleted.

2021-04-03 09:33 UTC, fauxpark commented on keyboards/jc65/v32a/keymaps/gbarnz/rules.mk
> +
```suggestion
```

2021-04-19 04:56 UTC, drashna requested changes

2021-04-19 04:56 UTC, drashna commented on keyboards/hhkb/ansi/keymaps/naut/keymap.c
> +#define HHKB 1
```suggestion
enum custom_layers {
    _BASE,
    _HHKB,
};
```

2021-04-19 04:56 UTC, drashna commented on keyboards/hhkb/ansi/keymaps/naut/keymap.c
> +    [BASE] = LAYOUT( //  default layer
```suggestion
    [_BASE] = LAYOUT( //  default layer
```

2021-04-19 04:56 UTC, drashna commented on keyboards/hhkb/ansi/keymaps/naut/keymap.c
> +        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(HHKB),
```suggestion
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(_HHKB),
```

2021-04-19 04:56 UTC, drashna commented on keyboards/hhkb/ansi/keymaps/naut/keymap.c
> +    [HHKB] = LAYOUT(
```suggestion
    [_HHKB] = LAYOUT(
```

2021-07-27 22:56 UTC, closed without merging