Add new Keyboard: SENDYYeah Bevi
qmk/qmk_firmware pull request #12011
Opened 2021-02-25 15:54 UTC by sendz

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-28 03:00 UTC, drashna requested changes

2021-03-01 07:31 UTC, sendz commented on keyboards/sendyyeah/bevi/bevi.h
> +          K80 , K90 , K81 ,  K91  ,  K82  ,  K92  ,             K83                ,  K95  ,  K86  ,  K96  ,  K87   \
@drashna may I know what the issue is?

2021-03-02 05:49 UTC, drashna approved these changes

2021-03-25 12:39 UTC, tzarc approved these changes

2021-03-25 12:39 UTC, merged