adding Montsinger Trio
qmk/qmk_firmware pull request #12029
Opened 2021-02-26 18:51 UTC by Rossman360

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-28 03:28 UTC, drashna requested changes

2021-02-28 03:28 UTC, drashna commented on keyboards/montsinger/trio/rev1.c
> +#include "rev1.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-28 03:28 UTC, drashna commented on keyboards/montsinger/trio/trio.c
> +#include "trio.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-02-28 03:28 UTC, drashna commented on keyboards/montsinger/trio/trio.h
> +#include "trio.h"
```suggestion
```

2021-02-28 03:28 UTC, drashna commented on keyboards/montsinger/trio/config.h
> +#define DESCRIPTION     Trio of keys and/or encoders
```suggestion
```

2021-03-01 20:08 UTC, zvecr requested changes

2021-03-01 20:08 UTC, zvecr commented on keyboards/montsinger/trio/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2021-03-01 20:08 UTC, zvecr commented on keyboards/montsinger/trio/rev1.c
> +}
```suggestion
```

2021-03-02 05:19 UTC, drashna approved these changes

2021-03-17 14:17 UTC, closed without merging

2021-03-17 14:56 UTC, Rossman360 commented
what the hellll

2021-03-17 15:15 UTC, Rossman360 commented
well, that was silly. Hopefully it's okay that all the changes so far from this PR are now under https://github.com/qmk/qmk_firmware/pull/12268 instead