Add CLI command to import info.json files
qmk/qmk_firmware pull request #12031
Opened 2021-02-26 23:11 UTC by zvecr

## Description

As a side project, i've been working on a replacement of kbfirmware that exports `info.json` files.

Looking at what the user does next, this cli command stubs out the `qmk new-keyboard` side of things while allowing import of `info.json` files.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-27 20:31 UTC, tzarc commented
Sorry about that, GitHub decided to delete the `develop` branch from upstream when we merged it, despite being told otherwise. Reopened.

2021-05-09 10:35 UTC, Erovia requested changes

2021-05-09 10:35 UTC, Erovia commented on docs/cli_commands.md
> +qmk new-keyboard [-kb KEYBOARD] [filename]
```suggestion
qmk new-keyboard [filename]
```

2021-05-09 10:35 UTC, Erovia commented on lib/python/qmk/cli/new/keyboard.py
> +def import_info_json(name, info):
```suggestion
def import_info_json(info):
```

2021-05-09 10:35 UTC, Erovia commented on lib/python/qmk/cli/new/keyboard.py
> +
```suggestion

   try:
       name = info_data["keyboard_name"]
   except KeyError:
       cli.log.error("%s does not contain 'keyboard_name' field.", info.name)
       exit(1)
```

2021-05-09 10:35 UTC, Erovia commented on lib/python/qmk/cli/new/keyboard.py
> +@cli.argument('-kb', '--keyboard', arg_only=True, help='Specify keyboard name. Example: 1upkeyboards/1up60hse')
```suggestion
```

2021-05-09 10:35 UTC, Erovia commented on lib/python/qmk/cli/new/keyboard.py
> +        import_info_json(cli.args.keyboard, cli.args.filename)
```suggestion
        import_info_json(cli.args.filename)
```

2021-07-27 22:56 UTC, closed without merging