New Keyboard: TGR Jane V2 CE
qmk/qmk_firmware pull request #12114
Opened 2021-03-04 20:05 UTC by mechmerlin

## Description

New Keyboard, the TGR Jane V2 CE which is essentially the same as the original TGR Jane V2

I moved around directories and put the original v2 in its own. 

Special thanks to frostfiree for letting me poke at his busted PCB. Special thanks to Xerpocalypse for testing the firmware. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-04 22:54 UTC, zvecr commented
Moving and existing keyboard is still considered a "breaking change", so i have re-targeted the PR to develop.

2021-03-07 23:06 UTC, drashna requested changes

2021-03-07 23:06 UTC, drashna commented on keyboards/tgr/jane/v2ce/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```suggestion
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2021-03-07 23:06 UTC, drashna commented on keyboards/tgr/jane/v2ce/v2ce.c
> +}
```suggestion
```

2021-03-07 23:06 UTC, drashna commented on keyboards/tgr/jane/v2ce/config.h
> +#define BACKLIGHT_LEVELS 3
```suggestion
#define BACKLIGHT_LEVELS 3

#define LED_CAPS_LOCK_PIN D1
#define LED_NUM_LOCK_PIN D6
```

2021-03-17 01:07 UTC, drashna commented
Has some merge conflicts

2021-04-19 05:32 UTC, drashna approved these changes

2021-04-19 05:41 UTC, fauxpark requested changes

2021-04-19 05:41 UTC, fauxpark commented on keyboards/tgr/jane/v2ce/keymaps/default/config.h
> +/* Copyright 2018 amnesia0287
This file can be deleted.

2021-04-19 05:41 UTC, fauxpark commented on keyboards/tgr/jane/v2ce/keymaps/default/keymap.c
> +  KC_LCTL,KC_LGUI,KC_LALT,                 KC_SPC,                                KC_RALT,KC_RGUI, KC_APP,KC_RCTL,  KC_LEFT,KC_DOWN,KC_RGHT) \
```suggestion
[0] = LAYOUT_tkl_ansi_f13(
  KC_ESC,  KC_F1,  KC_F2,  KC_F3,  KC_F4,  KC_F5,  KC_F6,  KC_F7,  KC_F8,  KC_F9, KC_F10, KC_F11, KC_F12,   KC_F13, KC_PSCR,KC_SLCK,KC_PAUS,
  KC_GRV,   KC_1,   KC_2,   KC_3,   KC_4,   KC_5,   KC_6,   KC_7,   KC_8,   KC_9,   KC_0,KC_MINS, KC_EQL,KC_BSPC,   KC_INS ,KC_HOME,KC_PGUP,
  KC_TAB,   KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,   KC_O,   KC_P,KC_LBRC,KC_RBRC,KC_BSLS,   KC_DEL ,KC_END ,KC_PGDN,
  KC_CAPS,   KC_A,   KC_S,   KC_D,   KC_F,   KC_G,   KC_H,   KC_J,   KC_K,   KC_L,KC_SCLN,KC_QUOT,         KC_ENT,
  KC_LSFT,    KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,KC_COMM, KC_DOT,KC_SLSH,        KC_RSFT,            KC_UP,
  KC_LCTL,KC_LGUI,KC_LALT,                 KC_SPC,                                KC_RALT,KC_RGUI, KC_APP,KC_RCTL,  KC_LEFT,KC_DOWN,KC_RGHT)
```

2021-04-19 05:41 UTC, fauxpark commented on keyboards/tgr/jane/v2ce/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-04-19 05:41 UTC, fauxpark commented on keyboards/tgr/jane/v2ce/rules.mk
> +WS2812_DRIVER = i2c
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
WS2812_DRIVER = i2c
```

2021-07-08 00:47 UTC, closed without merging