[Keymap] My ErgoDash Keymap
qmk/qmk_firmware pull request #12152
Opened 2021-03-08 00:05 UTC by totuus1157

## Description

My personal layout for ErgoDash

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the ### ### documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-08 01:14 UTC, drashna requested changes

2021-03-08 01:14 UTC, drashna commented on keyboards/ergodash/rev1/keymaps/totuus1157/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-03-08 01:14 UTC, drashna commented on keyboards/ergodash/rev1/keymaps/totuus1157/keymap.c
> +#define _ADJUST 16
We recommend using an enum for layer names, as they auto increment.  Especially in this case, as you're adding 13 unused layers, by setting adjust to layer 16.
```suggestion
enum custom_layers {
    _QWERTY,
    _LOWER,
    _RAISE,
    _ADJUST,
};
```

2021-03-08 01:14 UTC, drashna commented on keyboards/ergodash/rev1/keymaps/totuus1157/keymap.c
> +}
Could you remove this function?  

It's been deprecated in favor of the `set_single_persistent_default_layer` function (which is a core function).

https://docs.qmk.fm/#/ref_functions?id=setting-the-persistent-default-layer
```suggestion
```

2021-03-08 01:14 UTC, drashna commented on keyboards/ergodash/rev1/keymaps/totuus1157/keymap.c
> +        set_single_persistent_default_layer(_QWERTY);
If this is the only default layer, then you can remove this macro completely.

2021-03-09 00:50 UTC, closed without merging

2021-03-09 00:58 UTC, totuus1157 commented
Since we don't want to make it far from the default settings, we decided to drop this pull request.