[Keyboard] Added Roses Lite Support
qmk/qmk_firmware pull request #12173
Opened 2021-03-09 00:28 UTC by vk2fgav

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Added Roses Lite Compatability

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-09 22:38 UTC, fauxpark requested changes

2021-03-09 22:38 UTC, fauxpark commented on keyboards/roseslite/config.h
> +
```suggestion
```

2021-03-09 22:38 UTC, fauxpark commented on keyboards/roseslite/config.h
> +//#define MIDI_TONE_KEYCODE_OCTAVES 1
```suggestion
```

2021-03-09 22:38 UTC, fauxpark commented on keyboards/roseslite/readme.md
> +    make roses_lite:default:flash
```suggestion
Flashing example for this keyboard:

    make roseslite:default:flash
```

2021-03-09 22:38 UTC, fauxpark commented on keyboards/roseslite/readme.md
> +    make roses_lite:default
```suggestion
    make roseslite:default
```

2021-03-09 22:38 UTC, fauxpark commented on keyboards/roseslite/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-03-09 23:05 UTC, fauxpark requested changes

2021-03-09 23:05 UTC, fauxpark commented on keyboards/roseslite/info.json
> +}
```suggestion
{
    "keyboard_name": "roses lite",
    "url": "delta-design.xyz",
    "maintainer": "Reason6/Vk2fgav",
    "width": 18,
    "height": 5,
    "layouts": {
        "LAYOUT": {
            "layout": [
                {"x": 0, "y": 0},

                {"x": 1.5, "y": 0},
                {"x": 2.5, "y": 0},
                {"x": 3.5, "y": 0},
                {"x": 4.5, "y": 0},
                {"x": 5.5, "y": 0},
                {"x": 6.5, "y": 0},
                {"x": 7.5, "y": 0},

                {"x": 10, "y": 0},
                {"x": 11, "y": 0},
                {"x": 12, "y": 0},
                {"x": 13, "y": 0},
                {"x": 14, "y": 0},
                {"x": 15, "y": 0},
                {"x": 16, "y": 0},
                {"x": 17, "y": 0},

                {"x": 18.5, "y": 0},

                {"x": 0, "y": 1},

                {"x": 1.5, "y": 1, "w": 1.5},
                {"x": 3, "y": 1},
                {"x": 4, "y": 1},
                {"x": 5, "y": 1},
                {"x": 6, "y": 1},
                {"x": 7, "y": 1},

                {"x": 9.5, "y": 1},
                {"x": 10.5, "y": 1},
                {"x": 11.5, "y": 1},
                {"x": 12.5, "y": 1},
                {"x": 13.5, "y": 1},
                {"x": 14.5, "y": 1},
                {"x": 15.5, "y": 1},
                {"x": 16.5, "y": 1, "w": 1.5},

                {"x": 18.5, "y": 1},

                {"x": 0, "y": 2},

                {"x": 1.5, "y": 2, "w": 1.75},
                {"x": 3.25, "y": 2},
                {"x": 4.25, "y": 2},
                {"x": 5.25, "y": 2},
                {"x": 6.25, "y": 2},
                {"x": 7.25, "y": 2},

                {"x": 9.75, "y": 2},
                {"x": 10.75, "y": 2},
                {"x": 11.75, "y": 2},
                {"x": 12.75, "y": 2},
                {"x": 13.75, "y": 2},
                {"x": 14.75, "y": 2},
                {"x": 15.75, "y": 2, "w": 2.25},

                {"x": 18.5, "y": 2},

                {"x": 1.5, "y": 3, "w": 2},
                {"x": 3.5, "y": 3},
                {"x": 4.5, "y": 3},
                {"x": 5.5, "y": 3},
                {"x": 6.5, "y": 3},
                {"x": 7.5, "y": 3},

                {"x": 10.25, "y": 3},
                {"x": 11.25, "y": 3},
                {"x": 12.25, "y": 3},
                {"x": 13.25, "y": 3},
                {"x": 14.25, "y": 3},
                {"x": 15.25, "y": 3, "w": 1.75},

                {"x": 17.5, "y": 3},

                {"x": 1.5, "y": 4, "w": 1.25},
                {"x": 3.75, "y": 4, "w": 1.25},
                {"x": 5, "y": 4, "w": 2.75},
                {"x": 7.75, "y": 4},

                {"x": 10.25, "y": 4, "w": 2.75},
                {"x": 13, "y": 4, "w": 1.25},

                {"x": 16.5, "y": 4},
                {"x": 17.5, "y": 4},
                {"x": 18.5, "y": 4}
            ]
        }
    }
}
```

2021-03-09 23:10 UTC, vk2fgav commented
And again XD

2021-03-15 06:55 UTC, fauxpark approved these changes

2021-03-16 04:30 UTC, vk2fgav commented
Honestly I love how a miss click doesnt have an undo button for something like reviews #thanksgit @fauxpark sorry to bother you again :/

2021-03-16 04:34 UTC, vk2fgav reviewed
@Gucci

2021-03-16 05:03 UTC, fauxpark approved these changes

2021-03-17 02:23 UTC, drashna approved these changes

2021-03-17 02:23 UTC, merged