Mojito - removed layer macros
qmk/qmk_firmware pull request #12201
Opened 2021-03-12 09:14 UTC by Mojitas

## Description

The layer macros was removed and some minor changes to the layout was made. Workman layout was removed.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-12 21:36 UTC, fauxpark requested changes

2021-03-12 21:36 UTC, fauxpark commented on keyboards/keebio/iris/keymaps/mojitas/keymap.c
> +#include "eeconfig.h"
```suggestion
```

2021-03-12 23:40 UTC, fauxpark approved these changes

2021-03-17 03:09 UTC, drashna approved these changes

2021-03-17 03:09 UTC, merged

2021-03-17 03:09 UTC, drashna commented
Thank you for your contribution!