03/14
qmk/qmk_firmware pull request #12243
Opened 2021-03-14 22:42 UTC by AlisGraveNil

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-17 04:00 UTC, drashna approved these changes

2021-03-17 04:24 UTC, fauxpark requested changes

2021-03-17 04:24 UTC, fauxpark commented on keyboards/clawsome/doodle/keymaps/default/keymap.c
> +    [0] = LAYOUT( \
```suggestion
    [0] = LAYOUT(
```

2021-03-17 04:31 UTC, fauxpark approved these changes

2021-03-17 04:31 UTC, fauxpark commented
Thanks!

2021-03-17 04:32 UTC, fauxpark requested changes
Oops, one last thing.

2021-03-17 04:32 UTC, fauxpark commented on keyboards/clawsome/doodle/doodle.h
> +}
```suggestion
}
```

2021-03-17 06:18 UTC, drashna approved these changes

2021-04-11 23:08 UTC, AlisGraveNil commented
@fauxpark - anything else I need to change to get final approval for this?

2021-04-12 04:32 UTC, fauxpark approved these changes

2021-04-19 05:37 UTC, drashna approved these changes

2021-04-19 05:37 UTC, drashna commented
Thanks!

2021-04-19 05:38 UTC, drashna commented on keyboards/clawsome/doodle/doodle.h
> +    { K10,   K11,   K12   }, \
```suggestion
    { K10,   K11,   K12   } \
```

2021-04-20 16:59 UTC, merged