Add FoldKB
qmk/qmk_firmware pull request #12255
Opened 2021-03-16 02:21 UTC by nooges

## Description

Add FoldKB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-17 04:56 UTC, drashna requested changes

2021-03-17 04:56 UTC, drashna commented on keyboards/keebio/foldkb/rev1/rev1.c
> +#include "foldkb.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-03-17 04:56 UTC, drashna commented on keyboards/keebio/foldkb/rev1/rev1.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-03-17 04:56 UTC, drashna commented on keyboards/keebio/foldkb/rev1/rev1.h
> +#endif
```suggestion

2021-03-25 07:21 UTC, fauxpark requested changes

2021-03-25 07:21 UTC, fauxpark commented on keyboards/keebio/foldkb/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-03-25 07:21 UTC, fauxpark commented on keyboards/keebio/foldkb/rules.mk
> +SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
```suggestion
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-03-25 07:21 UTC, fauxpark commented on keyboards/keebio/foldkb/keymaps/default/keymap.c
> +  )
```suggestion
```

2021-03-26 04:03 UTC, fauxpark approved these changes

2021-04-03 00:50 UTC, drashna approved these changes

2021-04-03 00:51 UTC, drashna commented
Thanks!

2021-04-03 00:51 UTC, merged