Update readme.md on quefrency
qmk/qmk_firmware pull request #12276
Opened 2021-03-17 23:51 UTC by cyanpencil

Fix incorrect flashing instructions

2021-03-18 03:11 UTC, fauxpark requested changes

2021-03-18 03:11 UTC, fauxpark commented on keyboards/keebio/quefrency/readme.md
> +    bin/qmk flash -kb keebio/quefrency/rev3 -km default
```suggestion
```

2021-03-18 13:06 UTC, fauxpark approved these changes

2021-03-23 07:00 UTC, noroadsleft approved these changes

2021-03-23 07:00 UTC, merged

2021-03-23 07:00 UTC, noroadsleft commented
Thanks!