Adding afternoonlabs/oceanbreeze
qmk/qmk_firmware pull request #12299
Opened 2021-03-19 21:59 UTC by eithanshavit

## Description
Adding the new Ocean Breeze keyboard to Afternoon Labs

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-24 04:59 UTC, eithanshavit commented
@fauxpark and @drashna, you both helped me review stuff before. Looking for some feedback. Thx!

2021-03-24 05:01 UTC, fauxpark requested changes
Looks good, except the info.json needs to be redone without the rotation:
![image](https://user-images.githubusercontent.com/4781841/112258229-3a9b6400-8cba-11eb-97df-de138f301a7e.png)

2021-03-24 05:15 UTC, eithanshavit commented
@fauxpark, I should probably know this by now, but how are you testing these info.json files? Where's the render you're showing from?

2021-03-24 05:16 UTC, fauxpark commented
You can preview info.json files by pressing Ctrl+Shift+I in the Configurator.

2021-03-25 00:08 UTC, eithanshavit commented
Thanks so much @fauxpark, I fixed the layout!

2021-03-25 07:02 UTC, fauxpark commented on keyboards/afternoonlabs/oceanbreeze/rev1/info.json
> +{
Sorry, the thumb keys still seem to be slightly out of order:
![image](https://user-images.githubusercontent.com/4781841/112431889-32aff280-8d94-11eb-9806-69488849b7ec.png)

2021-04-04 05:19 UTC, eithanshavit commented
@fauxpark, I think I finally got it :) Sorry for the delay.

<img width="820" alt="Screen Shot 2021-04-03 at 10 17 36 PM" src="https://user-images.githubusercontent.com/946224/113499406-a35cba80-94ca-11eb-97b2-ea68b4be437c.png">

2021-04-04 05:29 UTC, fauxpark commented
Per the layout macro:
![image](https://user-images.githubusercontent.com/4781841/113499573-6fc97100-955a-11eb-9d9b-a6a5e9ede21f.png)

I think it should be more like this:
![image](https://user-images.githubusercontent.com/4781841/113499564-5de7ce00-955a-11eb-8a23-6d6732d62e48.png)

2021-04-04 05:40 UTC, eithanshavit commented
Thanks @fauxpark, is there a requirement that the macro and the info.json will follow the same order? I think that my proposal right now makes sense from the eyes of a user of this keyboard. For the macro, it makes sense for someone configuring this layout visually per the macro layout. For the info.json layout and configurator, the current proposal makes sense because configuring the thumb clusters is a different process than the alphas. And so I don't necessarily agree with your latest screenshot of having the upper thumb keys be in order of the lower alpha row.

2021-04-04 05:48 UTC, fauxpark commented
The info.json determines what order the keys will be placed into the top half of the layout macro, and so they must exactly match. You've placed LT4 and RT1 in the lower alpha row of the layout macro, which is about where they are physically, thus they have to be placed there in the info.json. If you want your ordering, you'll need to shift those four thumb keys down a line in the layout macro.

2021-04-04 05:57 UTC, eithanshavit commented
I see, ok I've updated it to behave like this.
<img width="818" alt="Screen Shot 2021-04-03 at 10 55 57 PM" src="https://user-images.githubusercontent.com/946224/113500067-eec59780-94cf-11eb-96c8-f5fff57e4482.png">

2021-04-05 01:31 UTC, eithanshavit commented
How's this looking now @fauxpark? Thanks for all the guidance

2021-04-05 03:33 UTC, fauxpark requested changes
Looks pretty good, just a couple of minor cosmetic things.

2021-04-05 03:33 UTC, fauxpark commented on keyboards/afternoonlabs/oceanbreeze/rev1/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
```

2021-04-05 03:33 UTC, fauxpark commented on keyboards/afternoonlabs/oceanbreeze/rev1/rev1.h
> +  }
```suggestion
#define XXX KC_NO

#define LAYOUT( \
    L00, L01, L02, L03, L04, L05,             R00, R01, R02, R03, R04, R05,   MC0, MC1, MC2, \
    L10, L11, L12, L13, L14, L15,             R10, R11, R12, R13, R14, R15,   MC3, MC4, MC5, \
    L20, L21, L22, L23, L24, L25,             R20, R21, R22, R23, R24, R25,        AUP, \
    L30, L31, L32, L33, L34, L35, LT4,   RT1, R30, R31, R32, R33, R34, R35,   ALT, ADN, ART, \
                   LT0, LT1, LT2, LT3,   RT2, RT3, RT4, RT5 \
) { \
    { L05, L04, L03, L02, L01, L00, XXX, XXX, XXX }, \
    { L15, L14, L13, L12, L11, L10, XXX, XXX, XXX }, \
    { L25, L24, L23, L22, L21, L20, XXX, XXX, XXX }, \
    { L35, L34, L33, L32, L31, L30, XXX, XXX, XXX }, \
    { LT3, LT2, LT1, LT0, XXX, XXX, XXX, XXX, XXX }, \
    { LT4, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX }, \
    { R00, R01, R02, R03, R04, R05, MC0, MC1, MC2 }, \
    { R10, R11, R12, R13, R14, R15, MC3, MC4, MC5 }, \
    { R20, R21, R22, R23, R24, R25, XXX, AUP, XXX }, \
    { R30, R31, R32, R33, R34, R35, ALT, ADN, ART }, \
    { RT2, RT3, RT4, RT5, XXX, XXX, XXX, XXX, XXX }, \
    { RT1, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX } \
}
```

2021-04-06 04:23 UTC, fauxpark approved these changes

2021-04-09 21:37 UTC, eithanshavit commented
Looking for more reviews please 🙏

2021-04-10 05:56 UTC, drashna approved these changes

2021-04-10 05:57 UTC, drashna commented
Thanks!

2021-04-10 05:57 UTC, merged