Add new keyboard column13 series
qmk/qmk_firmware pull request #12313
Opened 2021-03-21 06:02 UTC by abplus-lab

## Description

Add the following 3 types of keyboards

* Column13 ansi
* Column13 iso
* Column13 ortho

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 02:26 UTC, drashna reviewed
Please revert the changes to the submodules. 

You may need to run `make git-submodule`

2021-04-03 09:36 UTC, kazhida commented
Than you for advice.
I corrected sub-modules problem .

2021-04-10 06:02 UTC, drashna approved these changes

2021-04-25 02:08 UTC, tzarc requested changes
Please remove any changes not related to `keyboards/column13` -- there are a couple of modified files in other keyboards that should not be present.

As there is no difference between implementations of `matrix.c`, please move all of the files in `ansi` and `iso` up one directory into `column13`, and provide `LAYOUT_ansi` and `LAYOUT_iso` macros, with corresponding keymaps. As far as I can see, there's no reason to define these as two different keyboards.

2021-07-03 05:26 UTC, drashna requested changes

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/ansi/config.h
> +#define USE_I2C 1
```suggestion
```

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/ansi/matrix.c
> +            xprintf("row[%d]: %04X -> %04X\n", i, last_row, current_row);
```suggestion
            dprintf("row[%d]: %04X -> %04X\n", i, last_row, current_row);
```

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/iso/config.h
> +#define USE_I2C 1
```suggestion
```

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/iso/matrix.c
> +            xprintf("row[%d]: %04X -> %04X\n", i, last_row, current_row);
```suggestion
            dprintf("row[%d]: %04X -> %04X\n", i, last_row, current_row);
```

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/modulo/expander.c
> +//
This appears to be a re-implementation of https://github.com/qmk/qmk_firmware/blob/master/drivers/gpio/pca9555.c

If so, please use that instead.

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/ortho/config.h
> +#define USE_I2C 1
```suggestion
```

2021-07-03 05:26 UTC, drashna commented on keyboards/pkb65/info.json
> +{
This change should be reverted.

2021-07-03 05:26 UTC, drashna commented on keyboards/column13/ortho/matrix.c
> +            xprintf("row[%d]: %04X -> %04X\n", i, last_row, current_row);
```suggestion
            dprintf("row[%d]: %04X -> %04X\n", i, last_row, current_row);
```

2021-09-21 22:04 UTC, closed without merging