Added upcoming FJLabs Polaris PCB's
qmk/qmk_firmware pull request #12325
Opened 2021-03-21 22:35 UTC by mrnoisytiger

## Description

Added upcoming FJLabs Polaris PCB's. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 02:58 UTC, drashna requested changes
Please revert the changes to the submodules. 

You may need to run `make git-submodule` and then commit, to do so

2021-04-05 21:51 UTC, mrnoisytiger commented
@drashna Submodules reverted.

Steps:

1. Checkout branch
2. `cd <qmk base dir>`
3. `make git-submodule`

```
QMK Firmware 0.12.15
Synchronizing submodule url for 'lib/chibios'
Synchronizing submodule url for 'lib/chibios-contrib'
Synchronizing submodule url for 'lib/googletest'
Synchronizing submodule url for 'lib/lufa'
Synchronizing submodule url for 'lib/printf'
Synchronizing submodule url for 'lib/ugfx'
Synchronizing submodule url for 'lib/vusb'
Submodule path 'lib/chibios': checked out '313416b8fda90d9973a749a0a35970956852c286'
Submodule path 'lib/chibios-contrib': checked out 'e3a3a24047717af33b098266e11c2e4e5102206a'
```

4. `cd <keyboard dir>`
5. Make random small change
6. `git add .`
7. `git commit -m"___"`
8. `git push`

2021-04-05 21:54 UTC, drashna commented
Awesome! Though there is a flag to allow empty commits, too.

2021-04-05 21:55 UTC, mrnoisytiger commented
> Awesome! Though there is a flag to allow empty commits, too.

This is news to me. 😂  Thanks for the info!

2021-04-13 02:27 UTC, mrnoisytiger commented
Any chance I could get review on this? Submodules should be fixed.

2021-04-17 23:35 UTC, mrnoisytiger commented
@drashna  Could I get the dependency tag removed on this guy? Thanks!

2021-04-19 05:54 UTC, drashna approved these changes

2021-04-19 06:05 UTC, fauxpark requested changes

2021-04-19 06:05 UTC, fauxpark commented on keyboards/fjlabs/polaris/readme.md
> +
```suggestion
```

2021-04-19 06:05 UTC, fauxpark requested changes
Submodule changes still need to be undone.

2021-04-20 03:41 UTC, mrnoisytiger commented
This should do it...... 
```
make git-submodule
git commit --allow-empty -m "Fix submodules"
git push
```

2021-04-20 07:31 UTC, fauxpark commented
Nope. You may need to rebase instead.

2021-04-29 21:39 UTC, mrnoisytiger commented
Closing to recreate new branch and destroy current.

2021-04-29 21:39 UTC, closed without merging