Add support for alfredslab 65
qmk/qmk_firmware pull request #12334
Opened 2021-03-22 19:26 UTC by spooknik

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-25 07:17 UTC, fauxpark commented
Looks like this is generated from kbfirmware - we recommend using https://noroadsleft.github.io/kbf_qmk_converter to generate more up to date code from the JSON file instead. Please also look at the PR checklist; there are a number of things that need fixing here.

2021-03-25 07:50 UTC, spooknik commented
Thanks for the comments, will work on it.

2021-03-27 10:09 UTC, spooknik commented
Hello again, I have updated everything again. Used the site you suggested to re-do the files. Also went through the PR check list best I could.

2021-03-27 10:42 UTC, fauxpark requested changes

2021-03-27 10:42 UTC, fauxpark commented on keyboards/alfredslab/swift65/solder/config.h
> +#define DESCRIPTION     Swift65
```suggestion
```

2021-03-27 10:42 UTC, fauxpark commented on keyboards/alfredslab/swift65/solder/keymaps/default/readme.md
> +
```suggestion
# Default Swift65 Solder Layout

![](https://i.imgur.com/7Capi8W.png)
```

2021-03-27 10:42 UTC, fauxpark commented on keyboards/alfredslab/swift65/solder/keymaps/via/keymap.c
> +    ),
Need two more empty layers here.

2021-03-27 10:42 UTC, fauxpark commented on keyboards/alfredslab/swift65/solder/keymaps/via/readme.md
> +
```suggestion
# Default Swift65 Solder Layout

![](https://i.imgur.com/7Capi8W.png)
```

2021-03-27 10:42 UTC, fauxpark commented on keyboards/alfredslab/swift65/solder/readme.md
> +# Swift65
Please use Unix line endings for all files.

2021-03-27 11:11 UTC, fauxpark approved these changes

2021-04-03 03:15 UTC, drashna approved these changes

2021-04-16 10:31 UTC, spooknik commented
Hello again, just wondering when this will be pushed to master?

2021-04-16 11:37 UTC, fauxpark requested changes
Sorry, just one more thing.

2021-04-16 11:37 UTC, fauxpark commented on keyboards/alfredslab/swift65/solder/info.json
> +        "LAYOUT_all": {
```suggestion
        "LAYOUT": {
```

2021-04-16 12:32 UTC, spooknik commented
> 
> 
> Sorry, just one more thing.

Thanks for the quick reply. I approved the change.  Should it always be `LAYOUT_all` in into.json then? (Just for my own purposes, so I know next time)

2021-04-16 14:13 UTC, fauxpark commented
The layouts in info.json must match what you place into `<keyboard>.h` - in this case you've only provided a single one named `LAYOUT`, so that's what should be in there.

2021-05-03 12:45 UTC, spooknik commented
Thanks for detailed reply 👍

2021-05-16 00:34 UTC, drashna requested changes

2021-05-16 00:34 UTC, drashna commented on keyboards/alfredslab/swift65/solder/readme.md
> +# Swift65
Could you add instructions on how to jump to bootloader, to flash the keyboard?

2021-05-16 00:34 UTC, drashna commented on keyboards/ggkeyboards/genesis/hotswap/readme.md
> +# GG Keyboards Hotswap PCB
Could you ad instructions on how to jump to bootloader?

2021-05-17 23:33 UTC, fauxpark requested changes

2021-05-17 23:33 UTC, fauxpark commented on keyboards/ggkeyboards/genesis/hotswap/readme.md
> +    make ggkeyboards/genesis/solder:default
```suggestion
    make ggkeyboards/genesis/hotswap:default
```

2021-05-17 23:33 UTC, fauxpark commented on keyboards/ggkeyboards/genesis/hotswap/keymaps/via/readme.md
> +# GG Keyboards Hotswap PCB
This file should be deleted.

2021-05-17 23:33 UTC, fauxpark commented on keyboards/ggkeyboards/genesis/hotswap/keymaps/default/readme.md
> +# GG Keyboards Hotswap PCB
This file should be deleted.

2021-05-17 23:33 UTC, fauxpark commented on keyboards/ggkeyboards/genesis/solder/keymaps/via/readme.md
> +# GG Keyboards Solder PCB
This file should be deleted.

2021-05-17 23:33 UTC, fauxpark commented on keyboards/ggkeyboards/genesis/solder/keymaps/default/readme.md
> +# GG Keyboards Solder PCB
This file should be deleted.

2021-05-18 06:07 UTC, spooknik commented
Thanks once again @fauxpark . Have made those changes you suggested.

2021-05-18 07:07 UTC, fauxpark approved these changes

2021-05-22 04:43 UTC, drashna approved these changes

2021-05-22 04:44 UTC, drashna commented
Thanks!

2021-05-22 04:44 UTC, merged