Added RAMA WORKS KARA
qmk/qmk_firmware pull request #12346
Opened 2021-03-23 10:25 UTC by Wilba6582

Added RAMA WORKS KARA

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-25 06:53 UTC, fauxpark requested changes

2021-03-25 06:53 UTC, fauxpark commented on keyboards/wilba_tech/rama_works_kara/config.h
> +#define DESCRIPTION     RAMA WORKS KARA
```suggestion
```

2021-03-25 06:53 UTC, fauxpark commented on keyboards/wilba_tech/rama_works_kara/readme.md
> +Hardware Availability: [RAMA WORKS Store](https://ramaworks.store/)
```suggestion
* Keyboard Maintainer: [Wilba6582](https://github.com/Wilba6582)
* Hardware Supported: RAMA WORKS KARA PCB
* Hardware Availability: [RAMA WORKS Store](https://ramaworks.store/)
```

2021-03-25 06:53 UTC, fauxpark commented on keyboards/wilba_tech/rama_works_kara/rules.mk
> +SLEEP_LED_ENABLE = no      # Breathing sleep LED during USB suspend
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no      # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-03-26 00:46 UTC, fauxpark approved these changes

2021-04-03 03:47 UTC, drashna approved these changes

2021-04-03 03:48 UTC, drashna commented
Thanks!

2021-04-03 03:48 UTC, merged