Added the GK64 layout to DZ60
qmk/qmk_firmware pull request #12378
Opened 2021-03-25 08:23 UTC by kb-elmo

## Description

The DZ60 PCB was missing the GK64 layout. Since it's one of the most used layouts for the board I thought it would make sense to add it.  
I used LAYOUT_gk64 as a preset name but I'm open for other suggestions there.

It has the 2u left shift and all 1u keys on the right side.
![image](https://i.imgur.com/9zQ9Sb5l.jpg)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-25 11:32 UTC, tzarc approved these changes

2021-03-27 02:43 UTC, noroadsleft requested changes

2021-03-27 02:43 UTC, noroadsleft commented on keyboards/dz60/dz60.h
> +/* LAYOUT_gk64
This is actually [one of QMK's Community Layouts](https://github.com/qmk/qmk_firmware/tree/8af72000851dbe2c50a66bf2b9452011cbfe835a/layouts/default/64_ansi).

```suggestion
/* LAYOUT_64_ansi
```

Reference: https://docs.qmk.fm/#/feature_layouts

2021-03-27 02:43 UTC, noroadsleft commented on keyboards/dz60/dz60.h
> +#define LAYOUT_gk64( \
```suggestion
#define LAYOUT_64_ansi( \
```

2021-03-27 02:43 UTC, noroadsleft commented on keyboards/dz60/info.json
> +        "LAYOUT_gk64": {
```suggestion
        "LAYOUT_64_ansi": {
```

2021-03-27 02:43 UTC, noroadsleft commented on keyboards/dz60/keymaps/gk64/keymap.c
> +	LAYOUT_gk64(
```suggestion
	LAYOUT_64_ansi(
```

2021-03-27 02:43 UTC, noroadsleft commented on keyboards/dz60/keymaps/gk64/keymap.c
> +	LAYOUT_gk64(
```suggestion
	LAYOUT_64_ansi(
```

2021-03-27 10:35 UTC, fauxpark approved these changes

2021-03-29 03:45 UTC, noroadsleft approved these changes

2021-03-29 03:46 UTC, merged

2021-03-29 03:46 UTC, noroadsleft commented
Thanks!