Added Leave Meeting Button to Handwired folder
qmk/qmk_firmware pull request #12385
Opened 2021-03-25 20:20 UTC by aerialviews007

I 3D printed and assembled the Leave Meeting button created by 9gel.  https://github.com/9gel/leave_meeting_button

Rather than use his software, I installed QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 02:50 UTC, drashna approved these changes

2021-04-25 00:59 UTC, tzarc requested changes
Could this not be handled by a keymap under `handwired/onekey` instead?
Seems like it's just a `DIRECT_PINS` definition with `Alt+F4` binding?

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/config.h
> +Copyright 2019 Keebio
Wrong author.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/keymaps/default/config.h
> +/* Copyright 2019 Keebio
Wrong author.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/config.h
> +#define MANUFACTURER    You
Wrong manufacturer.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/keymaps/default/keymap.c
> +/* Copyright 2019 Keebio
Wrong author.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/keymaps/default/config.h
> +/* Copyright 2019 Keebio
Actually, just delete this file -- it serves no purpose.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/keymaps/default/readme.md
> +# The default keymap for tukey
Wrong name. Probably best to just remove the file.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/leave_meeting.c
> +/* Copyright 2019 Keebio
Wrong author.

2021-04-25 00:59 UTC, tzarc commented on keyboards/handwired/leave_meeting/leave_meeting.h
> +/* Copyright 2019 Keebio
Wrong author.

2021-05-16 00:29 UTC, drashna requested changes

2021-05-16 00:29 UTC, drashna commented on keyboards/handwired/leave_meeting/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-05-16 00:29 UTC, drashna commented on keyboards/handwired/leave_meeting/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output 
```

2021-07-30 10:23 UTC, closed without merging