Move the module checking and updating to lib/python
qmk/qmk_firmware pull request #12416
Opened 2021-03-29 02:16 UTC by skullydazed

## Description

## Types of Changes

- [x] Core
- [x] Enhancement/optimization

## Issues Fixed or Closed by This PR

* fixes #12413 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-29 20:10 UTC, tzarc approved these changes
Weak approval.

2021-04-14 19:01 UTC, Erovia approved these changes

2021-04-14 19:01 UTC, Erovia commented on lib/python/qmk/cli/__init__.py
> +        exit(1)
```suggestion
    if len(sys.argv) == 1 or (len(sys.argv) > 1 and 'config' != sys.argv[1]):
        if yesno('Would you like to install the required developer Python modules?'):
            _run_cmd(sys.executable, '-m', 'pip', 'install', '-r', 'requirements-dev.txt')
        else:
            print()
            print(msg_install % (str(Path('requirements-dev.txt').resolve()),))
            print('You can also turn off developer mode: qmk config user.developer=None')
            print()
            exit(1)
```
We want to allow the user to run `qmk config` so they can turn off dev mode.

2021-04-14 19:02 UTC, Erovia requested changes
Misclicked... -.-

2021-04-16 18:30 UTC, Erovia commented on lib/python/qmk/cli/__init__.py
> +        exit(1)
```suggestion
if cli.config.user.developer:
    args = sys.argv[1:]
    while args and args[0][0] == '-':
        del args[0]
    if not args or args[0] != 'config':
        if _broken_module_imports('requirements-dev.txt'):
            if yesno('Would you like to install the required developer Python modules?'):
                _run_cmd(sys.executable, '-m', 'pip', 'install', '-r', 'requirements-dev.txt')
            else:
                print()
                print(msg_install % (str(Path('requirements-dev.txt').resolve()),))
                print('You can also turn off developer mode: qmk config user.developer=None')
                print()
                exit(1)
```
We want to allow the user to run `qmk config` so they can turn off dev mode.

2021-05-10 18:59 UTC, Erovia approved these changes

2021-05-10 19:00 UTC, merged