add feels/feels65
qmk/qmk_firmware pull request #12426
Opened 2021-03-30 04:59 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 05:08 UTC, drashna commented on keyboards/feels/feels65/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader for this board, too?  Eg, hardware reset button, bootmagic, etc.

2021-04-19 06:33 UTC, drashna approved these changes

2021-04-19 06:35 UTC, drashna requested changes

2021-04-19 06:35 UTC, drashna commented on keyboards/feels/feels65/feels65.h
> +#define XXX K_NO
```suggestion
#define XXX KC_NO
```

2021-04-21 02:22 UTC, drashna approved these changes

2021-04-21 06:45 UTC, fauxpark requested changes

2021-04-21 06:45 UTC, fauxpark commented on keyboards/feels/feels65/rules.mk
> +RGBLIGHT_ENABLE  = no   # This can be enabled if a ws2812 strip is connected to the expansion port.
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-04-21 06:45 UTC, fauxpark commented on keyboards/feels/feels65/config.h
> +#include "config_common.h"
```suggestion

#include "config_common.h"
```

2021-04-21 08:47 UTC, fauxpark approved these changes

2021-05-14 02:39 UTC, drashna commented
Thanks!

2021-05-14 02:39 UTC, merged