Patch 1
qmk/qmk_firmware pull request #12448
Opened 2021-03-31 17:56 UTC by u17194907425

## Description

Hi. Adding a support for a handwired keyboard that I've designed.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 06:02 UTC, drashna approved these changes

2021-04-19 08:50 UTC, fauxpark requested changes

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/rules.mk
> +# https://noroadsleft.github.io/kbf_qmk_converter/
```suggestion
```

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/info.json
> +    ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/"
```suggestion
```

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/info.json
> +    "height": 6.362672937370583,
```suggestion
    "height": 6,
```

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/g_split_board.h
> +// https://noroadsleft.github.io/kbf_qmk_converter/
```suggestion
```

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/g_split_board.c
> +// https://noroadsleft.github.io/kbf_qmk_converter/
```suggestion
```

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/config.h
> +// https://noroadsleft.github.io/kbf_qmk_converter/
```suggestion
```

2021-04-19 08:50 UTC, fauxpark commented on keyboards/handwired/g_split_board/readme.md
> +A split ergonomic keyboard with enough key's for national layout
This file should follow the [template](https://github.com/qmk/qmk_firmware/blob/master/quantum/template/avr/readme.md).

2021-07-08 00:47 UTC, closed without merging