Added BKS65 Solder PCB
qmk/qmk_firmware pull request #12451
Opened 2021-04-01 00:36 UTC by mrnoisytiger

## Description
Added BKS65 Solder PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 06:09 UTC, drashna approved these changes

2021-04-13 02:27 UTC, mrnoisytiger commented
Any chance I could get review on this?

2021-04-19 08:51 UTC, fauxpark requested changes

2021-04-19 08:51 UTC, fauxpark commented on keyboards/fjlabs/bks65solder/readme.md
> +    make fjlabs/bks65-solder:default
```suggestion
    make fjlabs/bks65solder:default
```

2021-04-20 07:34 UTC, fauxpark approved these changes

2021-04-20 17:47 UTC, drashna commented
Thanks!

2021-04-20 17:47 UTC, merged