Keymap: Orthocarpus keymap for idobo
qmk/qmk_firmware pull request #12462
Opened 2021-04-02 06:57 UTC by gkbd

## Description

Ortholinear carpalx optimized layout with home row Shift modifier

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-03 06:24 UTC, drashna requested changes

2021-04-03 06:24 UTC, drashna commented on keyboards/idobo/keymaps/gkbd_75/config.h
> +
```suggestion

#pragma once

```

2021-04-03 06:27 UTC, drashna approved these changes

2021-04-03 06:29 UTC, gkbd commented
Thank you @drashna

2021-04-18 22:22 UTC, spidey3 approved these changes

2021-04-18 22:22 UTC, merged

2021-04-18 22:27 UTC, gkbd commented
Thank you @spidey3