[Config] Add VSCode workspace files to .gitignore
qmk/qmk_firmware pull request #12469
Opened 2021-04-03 09:43 UTC by LuisMorenoSerrano

When using **VSCode with QMK** as IDE, if you create a **.code-workspace** file in root folder **qmk_firmware** (i.e. **qmk_firmware.code-workspace** or any other file name), this user specific file shows as modified.

## Description

Add **.code-workspace** extension files to **.gitignore**.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-19 08:08 UTC, drashna approved these changes

2021-04-25 03:57 UTC, tzarc requested changes
Please remove unrelated changes.

2021-04-25 11:50 UTC, LuisMorenoSerrano commented
Sorry, this is my first pull request. I didn't know that subsequent local commits were added to pull request. I think I have fixed the situation, please tell me if you need some more changes of my own.

Thanks in advance,
Luis

2021-04-25 20:46 UTC, tzarc approved these changes

2021-04-25 20:46 UTC, tzarc commented
All good, cheers!

2021-04-25 20:46 UTC, merged