snowe keymap/userspace and Ocean Dream animation
qmk/qmk_firmware pull request #12477
Opened 2021-04-04 06:52 UTC by snowe2010

## Description

Add my keymap and userspace. Also add a neat animation that I think others will like, along with detailed documentation.

I was unable to reset --soft and squash all my changes due to this being an extremely long running fork that I've been working on for years, and I was working off master (I know, shouldn't have done that). I am fine with a squash and merge to squash the commits. If needed I can try to rebase squash locally, but it's quite a number of commits. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-19 07:42 UTC, drashna requested changes

2021-04-19 07:42 UTC, drashna commented on keyboards/crkbd/keymaps/snowe/keycode_aliases.h
> +#define GUI_ESC GUI_T(KC_ESC)
```suggestion
#pragma once

#define GUI_ESC GUI_T(KC_ESC)
```

2021-04-20 04:09 UTC, drashna approved these changes

2021-06-24 02:21 UTC, tzarc approved these changes

2021-06-24 02:21 UTC, merged

2021-11-04 12:29 UTC, keyboard-magpie commented
@snowe2010 this could do with some updates to the readme to fall in line with the last round of OLED code updates.

2022-03-15 19:04 UTC, snowe2010 commented
@keyboard-magpie just now got the notification for your comment for some reason. What were the updates?