Baseline pull
qmk/qmk_firmware pull request #12494
Opened 2021-04-06 03:55 UTC by peott-fr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-18 22:35 UTC, spidey3 requested changes
You have unexpected changes to `lib/chibios` and ` lib/chibios-contrib`. 
Please do `make git-submodule` to synchronize them with master, then push again to update this PR.

2021-04-19 08:30 UTC, drashna requested changes

2021-04-19 08:30 UTC, drashna commented on keyboards/lily58/keymaps/peott-fr/keymap.c
> +#endif
```suggestion
```

2021-04-19 08:30 UTC, drashna commented on keyboards/lily58/keymaps/peott-fr/keymap.c
> +extern uint8_t is_master;
```suggestion
```

2021-07-08 00:47 UTC, closed without merging