Add qmk support for Mechanical Gamepad/Macro Pad
qmk/qmk_firmware pull request #12525
Opened 2021-04-08 21:29 UTC by Taktloss

## Description
Added qmk support for a custom keypad from maker-tutorials. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-19 17:18 UTC, drashna requested changes

2021-04-19 17:18 UTC, drashna commented on keyboards/handwired/macropad21/config.h
> +#define PREVENT_STUCK_MODIFIERS
```suggestion
```

2021-04-19 17:18 UTC, drashna commented on keyboards/handwired/macropad21/keymaps/default/keymap.c
> +#include <quantum/keymap_extras/keymap_german.h>
```suggestion
#include "keymap_german.h"
```

2021-04-19 17:18 UTC, drashna commented on keyboards/handwired/macropad21/keymaps/via/keymap.c
> +#include <quantum/keymap_extras/keymap_german.h>
```suggestion
#include "keymap_german.h"
```

2021-04-19 17:18 UTC, drashna commented on keyboards/handwired/macropad21/rules.mk
> +RGBLIGHT_ENABLE ?= no
```suggestion
BOOTMAGIC_ENABLE = yes	# Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes	# Mouse keys
EXTRAKEY_ENABLE = yes	# Audio control and System control
CONSOLE_ENABLE = no	# Console for debug
COMMAND_ENABLE = yes    # Commands for debug and configuration
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
NKRO_ENABLE = yes		# USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = no  # Enable keyboard backlight functionality
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
```

2021-04-20 04:08 UTC, drashna requested changes

2021-04-20 04:08 UTC, drashna commented on keyboards/handwired/macropad21/keymaps/via/rules.mk
> +RGBLIGHT_ENABLE ?= no
Most of this isn't needed. In fact, only what has been changed from the default is needed. 

```suggestion
VIA_ENABLE = yes
```

2021-04-20 20:01 UTC, drashna approved these changes

2021-06-07 10:58 UTC, fauxpark requested changes

2021-06-07 10:58 UTC, fauxpark commented on keyboards/handwired/macropad21/rules.mk
> +RGBLIGHT_ENABLE = no
```suggestion
# Bootloader selection
BOOTLOADER = caterina

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = full     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-08-22 17:05 UTC, closed without merging