Add UM-70
qmk/qmk_firmware pull request #12556
Opened 2021-04-11 19:55 UTC by duoshock

## Description
Please add UM-70 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-20 01:28 UTC, drashna requested changes

2021-04-20 01:28 UTC, drashna commented on keyboards/merge/um70/um70.h
> +#define LAYOUT_RSpace_SplitBksp( \
```suggestion
#define LAYOUT_rspace_split_bksp( \
```

2021-04-20 01:28 UTC, drashna commented on keyboards/merge/um70/um70.h
> +#define LAYOUT_RSpace_2UBksp( \
```suggestion
#define LAYOUT_rspace_2ubksp( \
```

2021-04-20 01:28 UTC, drashna commented on keyboards/merge/um70/um70.h
> +#define LAYOUT_LSpace_2UBksp( \
```suggestion
#define LAYOUT_lspace_2ubksp( \
```

2021-04-20 01:28 UTC, drashna commented on keyboards/merge/um70/um70.h
> +#define LAYOUT_LSpace_SplitBksp( \
```suggestion
#define LAYOUT_lspace_splitbksp( \
```

2021-04-20 01:28 UTC, drashna commented on keyboards/merge/um70/keymaps/via/keymap.c
> +[_BASE] = LAYOUT_RSpace_SplitBksp(
```suggestion
[_BASE] = LAYOUT_rspace_splitbksp(
```

2021-04-20 01:28 UTC, drashna commented on keyboards/merge/um70/keymaps/via/keymap.c
> +[_TWO] = LAYOUT_RSpace_SplitBksp(
```suggestion
[_TWO] = LAYOUT_rspace_splitbksp(
```

2021-04-21 13:44 UTC, duoshock commented on keyboards/merge/um70/um70.c
> +    2, 2, 2, 2, 2, 2,
Thanks. It's updated.

2021-04-21 13:49 UTC, duoshock commented
Thanks for reviewing. I've updated layout names and RGB matrix flag.

2021-05-14 03:03 UTC, drashna commented on keyboards/merge/um70/config.h
> +#    define RGB_MATRIX_SPLIT RGBLED_SPLIT
This may not work.

2021-05-14 03:06 UTC, drashna approved these changes

2021-05-14 08:43 UTC, fauxpark requested changes

2021-05-14 08:43 UTC, fauxpark commented on keyboards/merge/um70/rules.mk
> +BOOTMAGIC_ENABLE = lite
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
OLED_DRIVER_ENABLE = yes
```

2021-05-14 11:53 UTC, fauxpark approved these changes

2021-05-14 15:36 UTC, drashna commented
Thanks!

2021-05-14 15:36 UTC, merged