Terrazzo: Fix wrong LED Matrix function names
qmk/qmk_firmware pull request #12561
Opened 2021-04-12 10:06 UTC by fauxpark

## Description

Didn't realise these were referenced elsewhere...

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-12 11:24 UTC, tzarc approved these changes

2021-04-12 18:48 UTC, Erovia approved these changes

2021-04-12 19:12 UTC, Erovia requested changes
I guess https://github.com/qmk/qmk_firmware/blob/develop/quantum/led_matrix.c#L177 needs an update as well.

2021-04-13 03:28 UTC, fauxpark commented
Yeah, I already noticed that in https://github.com/qmk/qmk_firmware/pull/12509

2021-04-13 09:19 UTC, Erovia approved these changes

2021-04-13 09:51 UTC, merged