The Uni keyboard. Add keyboard
qmk/qmk_firmware pull request #12566
Opened 2021-04-13 01:08 UTC by petercpark

Addition of the Uni and its keymaps to the qmk directory.

## Description
The Uni is an unibody split ortholinear keyboard made specifically for stenography to be used in conjunction with Plover.

Add ./keyboards/the_uni and files within the folder.
## Types of Changes
Add keyboard and keymap.

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-20 01:37 UTC, drashna requested changes

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/config.h
> +#define VENDOR_ID       0x2353
This Vender ID is already in use.  Please change it. Above 0x4000 is pretty safe

https://www.the-sz.com/products/usbid/index.php?v=0x2353&p=&n=

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/config.h
> +#define DESCRIPTION     Used in conjunction with plover stenography
```suggestion
```

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/config.h
> +#define PREVENT_STUCK_MODIFIERS
```suggestion
```

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/keymaps/qwerty/keymap.c
> +#include "the_uni.h"
```suggestion
#include QMK_KEYBOARD_H
```

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/readme.md
> +    Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootlaoder for the board?

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
# Bootloader
BOOTLOADER = atmel-dfu
```

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/rules.mk
> +STENO_ENABLE = yes          # Additional protocols for Stenography(+1700), requires VIRTSER
```suggestion
BOOTMAGIC_ENABLE = lite	# Virtual DIP switch configuration
CONSOLE_ENABLE = no	# Console for debug
COMMAND_ENABLE = no    # Commands for debug and configuration
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
NKRO_ENABLE = yes		# USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = no  # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no
FORCE_NKRO = yes
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = no        # Mouse keys
STENO_ENABLE = yes      
```

2021-04-20 01:37 UTC, drashna commented on keyboards/the_uni/the_uni.h
> +#define THE_UNI_H
```suggestion
```

2021-04-21 16:15 UTC, petercpark commented on keyboards/the_uni/config.h
> +#define VENDOR_ID       0x2353
```suggestion
#define VENDOR_ID       0x9000
```

2021-04-21 16:18 UTC, petercpark commented on keyboards/the_uni/readme.md
> +    ​
```suggestion
    ​To enter the bootloader, short the rst and gnd pins with a conductive material such as a tweezer or a wire. Uni v2 will have reset pads next to the pro micro so you can short these pads to reset the pro micro.
```

2021-05-03 21:39 UTC, ridingqwerty requested changes

2021-05-03 21:39 UTC, ridingqwerty commented on keyboards/the_uni/keymaps/default/keymap.c
> +	[_PLOVER] = KEYMAP(
```suggestion
	 [_QWERTY] = LAYOUT(
	 	KC_Q, KC_W, KC_E, KC_R, LT(_CHOOSE, KC_T), KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, 
	 	KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, 
	 	            KC_1, KC_C, KC_V, KC_N, KC_M, KC_2),

	 [_CHOOSE] = LAYOUT(
	 	_______, _______, _______, _______, _______, PLOVER, _______, _______, _______, _______, _______, 
	 	_______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, 
	 	            _______, _______, _______, _______, _______, _______),
*/
	[_PLOVER] = LAYOUT(
```

Prefer `LAYOUT` over `KEYMAP`.  The json already references `LAYOUT` in this PR so the configurator would likely not work as-is.

2021-05-03 21:39 UTC, ridingqwerty commented on keyboards/the_uni/keymaps/qwerty/keymap.c
> +	[_PLOVER] = KEYMAP(
```suggestion
	 [_QWERTY] = LAYOUT(
	 	KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, 
	 	KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, 
	 	            KC_1, KC_C, KC_V, KC_N, KC_M, KC_2),
/*

	 [_CHOOSE] = LAYOUT(
	 	_______, _______, _______, _______, _______, PLOVER, _______, _______, _______, _______, _______, 
	 	_______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, 
	 	            _______, _______, _______, _______, _______, _______),
	[_PLOVER] = LAYOUT(
```

Prefer `LAYOUT` over `KEYMAP`.

2021-05-03 21:39 UTC, ridingqwerty commented on keyboards/the_uni/the_uni.h
> +#define KEYMAP( \
```suggestion
#define LAYOUT( \
```

Prefer `LAYOUT` over `KEYMAP`.

2021-05-14 03:01 UTC, drashna commented on keyboards/the_uni/config.h
> +#define FORCE_NKRO
In general, I recommend against this, as it can cause the keyboard to become unusable before the OS has booted up.

2021-05-14 03:01 UTC, drashna approved these changes

2021-05-18 17:51 UTC, ridingqwerty approved these changes
Looks good, thanks.

2021-05-18 17:52 UTC, merged