Added basic QMK support and keymap for Lotus58 Glow
qmk/qmk_firmware pull request #12594
Opened 2021-04-16 08:04 UTC by TweetyDaBird

## Lotus58 Split keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-20 02:45 UTC, drashna requested changes

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/keymaps/default/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +enum sofle_layers {
Sofie?

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/lotus58.c
> +#include "lotus58.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/lotus58.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/rev1/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/rev1/rev1.c
> +#include "lotus58.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/rev1/rev1.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-04-20 02:45 UTC, drashna commented on keyboards/tweetydabird/lotus58/rules.mk
> +DEFAULT_FOLDER = lotus58/rev1
```suggestion
```

2021-04-20 07:20 UTC, fauxpark requested changes

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/README.md
> +Default keymap
This file can be deleted.

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/config.h
> +#pragma once
This file can be deleted.

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/readme.md
> +    make lotus58:default:avrdude
```suggestion
    make tweetydabird/lotus58:default:flash
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/readme.md
> +Flash the default keymap:
```suggestion
Flashing example for this keyboard:
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/readme.md
> +    make lotus58:default
```suggestion
    make tweetydabird/lotus58:default
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/rev1/info.json
> +            "key_count": 60,
```suggestion
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/rev1/rev1.h
> +    }
```suggestion
    L00, L01, L02, L03, L04, L05,           R00, R01, R02, R03, R04, R05,  \
    L10, L11, L12, L13, L14, L15,           R10, R11, R12, R13, R14, R15,  \
    L20, L21, L22, L23, L24, L25,           R20, R21, R22, R23, R24, R25,  \
    L30, L31, L32, L33, L34, L35, L45, R40, R30, R31, R32, R33, R34, R35, \
              L40, L41, L42, L43, L44, R41, R42, R43, R44, R45  \
) { \
    { L00, L01, L02, L03, L04, L05 }, \
    { L10, L11, L12, L13, L14, L15 }, \
    { L20, L21, L22, L23, L24, L25 }, \
    { L30, L31, L32, L33, L34, L35 }, \
    { L40, L41, L42, L43, L44, L45 }, \
    { R05, R04, R03, R02, R01, R00 }, \
    { R15, R14, R13, R12, R11, R10 }, \
    { R25, R24, R23, R22, R21, R20 }, \
    { R35, R34, R33, R32, R31, R30 }, \
    { R45, R44, R43, R42, R41, R40 } \
}
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/rules.mk
> +BOOTLOADER = caterina
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                 KC_LGUI,TD(DEL_INS), TT(_LOWER), MT(MOD_LALT, KC_APP), MT(MOD_LSFT, KC_SPC),      MT(MOD_RSFT,KC_ENT), MT(MOD_RALT, KC_RGUI), TT(_RAISE), KC_BSPC, TD(MEDIA_SCROLL) \
```suggestion
[_QWERTY] = LAYOUT(
  TD(ESC_PIPE),   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                     KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_MINS,
  KC_TAB,   KC_Q,   KC_W,    KC_E,    KC_R,    KC_T,                     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,  KC_LBRC,
  KC_NUHS,   KC_A,   KC_S,    KC_D,    KC_F,    KC_G,                     KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN,  KC_QUOT,
  MT(MOD_LCTL, KC_LEFT),  KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, TD(PG_DN),     TD(PG_UP),KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH,  MT(MOD_RCTL, KC_RIGHT),
                 KC_LGUI,TD(DEL_INS), TT(_LOWER), MT(MOD_LALT, KC_APP), MT(MOD_LSFT, KC_SPC),      MT(MOD_RSFT,KC_ENT), MT(MOD_RALT, KC_RGUI), TT(_RAISE), KC_BSPC, TD(MEDIA_SCROLL)
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                 KC_LGUI,KC_LALT,KC_LCTRL,KC_LOWER, KC_ENT,      KC_SPC,  KC_RAISE, KC_RCTRL, KC_RALT, KC_RGUI \
```suggestion
[_COLEMAK] = LAYOUT(
  KC_GRV,   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_GRV,
  KC_ESC,   KC_Q,   KC_W,    KC_F,    KC_P,    KC_G,                      KC_J,    KC_L,    KC_U,    KC_Y, KC_SCLN,  KC_BSPC,
  KC_TAB,   KC_A,   KC_R,    KC_S,    KC_T,    KC_D,                      KC_H,    KC_N,    KC_E,    KC_I,    KC_O,  KC_QUOT,
  KC_LSFT,  KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, KC_MUTE,      XXXXXXX,KC_K,    KC_M, KC_COMM,  KC_DOT, KC_SLSH,  KC_RSFT,
                 KC_LGUI,KC_LALT,KC_LCTRL,KC_LOWER, KC_ENT,      KC_SPC,  KC_RAISE, KC_RCTRL, KC_RALT, KC_RGUI
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                       _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______\
```suggestion
[_LOWER] = LAYOUT(
  _______,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                       KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,
  KC_GRV,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                       KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_F12,
  _______, KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, KC_PERC,                       KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE,
  _______,  KC_EQL, KC_MINS, KC_PLUS, KC_LCBR, KC_RCBR, _______,       _______, KC_LBRC, KC_RBRC, KC_SCLN, KC_COLN, KC_BSLS, _______,
                       _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______ \
```suggestion
[_RAISE] = LAYOUT(
  _______,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                       KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,
  _______,  KC_INS,  KC_PSCR,   KC_APP,  XXXXXXX, XXXXXXX,                        KC_PGUP, KC_PRVWD,   KC_UP, KC_NXTWD,KC_DLINE, KC_BSPC,
  _______, KC_LALT,  KC_LCTL,  KC_LSFT,  XXXXXXX, KC_CAPS,                       KC_PGDN,  KC_LEFT, KC_DOWN, KC_RGHT,  KC_DEL, KC_BSPC,
  _______,KC_UNDO, KC_CUT, KC_COPY, KC_PASTE, XXXXXXX,  _______,       _______,  XXXXXXX, KC_LSTRT, XXXXXXX, KC_LEND,   XXXXXXX, _______,
                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______
```

2021-04-20 07:20 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                   _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______ \
```suggestion
  [_ADJUST] = LAYOUT(
  XXXXXXX , XXXXXXX,  XXXXXXX ,  XXXXXXX , XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  RESET  , XXXXXXX,KC_QWERTY,KC_COLEMAK,CG_TOGG,XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX , XXXXXXX,CG_TOGG, XXXXXXX,    XXXXXXX,  XXXXXXX,                     XXXXXXX, KC_VOLD, KC_MUTE, KC_VOLU, XXXXXXX, XXXXXXX,
  XXXXXXX , XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX,  XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT, XXXXXXX, XXXXXXX,
                   _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______
```

2021-07-10 05:54 UTC, fauxpark requested changes

2021-07-10 05:54 UTC, fauxpark commented on keyboards/sofle/keymaps/default/keymap.c
> -#include QMK_KEYBOARD_H
Please restore this file.

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/info.json
> +{
This file is incomplete.

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +	KC_LGUI, TD(DEL_INS),	TT(_NUM),	MT(MOD_LALT, KC_RGUI), MT(MOD_LSFT, KC_SPC),			MT(MOD_RSFT,KC_ENT), MT(MOD_RALT, KC_APP), TT(_FUNC), 	KC_BSPC, 			TD(MEDIA_SCROLL) \
```suggestion
[_QWERTY] = LAYOUT(
/* ,-----------------------------------------------------------------`                              ,-----------------------------------------------------------------.
 * |   ESC    |     1    |     2    |     3    |     4    |     5    |                              |     6    |     7    |     8    |     9    |     0    |     +    |
 * |----------+----------+----------+----------+----------+----------|                              |----------+----------+----------+----------+----------+----------|*/
	TD(ESC_PIPE),	KC_1, 	  KC_2,   	KC_3, 	  KC_4,    	KC_5,										KC_6,		KC_7,		KC_8,	  KC_9,		KC_0,		KC_MINS,
/* |-----------------------------------------------------------------|                              |-----------------------------------------------------------------|
 * |   TAB    |     Q    |     W    |     E    |     R    |     T    |                              |     Y    |     U    |     I    |     O    |     P    |     Å    |
 * |----------+----------+----------+----------+----------+----------|                              |----------+----------+----------+----------+----------+----------|*/ 
    KC_TAB,   		KC_Q,	  KC_W,   	KC_E,     KC_R,		KC_T,                      					KC_Y,    	KC_U,		KC_I,     KC_O,		KC_P,		KC_LBRC,
/* |-----------------------------------------------------------------|                              |-----------------------------------------------------------------|
 * |     '    |     A    |     S    |     D    |     F    |     G    |                              |     H    |     J    |     K    |     L    |     Ö    |     Ä    |
 * |----------+----------+----------+----------+----------+----------|                              |----------+----------+----------+----------+----------+----------|*/ 	 
	KC_NUHS,   	KC_A,  		KC_S,    	KC_D,    	KC_F,    KC_G,                     					KC_H,    	KC_J,		KC_K,	  KC_L, 	KC_SCLN,	KC_QUOT,
/* |-----------------------------------------------------------------+------------`    ,------------+---------------------------------------------------------------------|
 * |LEFT(CTRL)|     Z    |     X    |     C    |     V    |     B    | DOWN(PG_DN)|    |  UP(PG_UP) |     N    |     M    |     ,    |     .    |     -    |RIGHT(CTRL)|
 * `----------+----------+----------+----------+----------+----------+------------|    |------------+----------+----------+----------+----------+----------|----------´*/
 MT(MOD_LCTL, KC_LEFT), KC_Z, KC_X,   	KC_C,    	KC_V,		KC_B,	TD(PG_DN),		TD(PG_UP),	KC_N,    	KC_M, 	  KC_COMM,   KC_DOT, 	KC_SLSH,  MT(MOD_RCTL, KC_RIGHT),
/*         |--------------------------------------------------------------------´        `----------------------------------------------------------------------|
 *         |    DEL*INS*   |   LOWER      |   ALT(WIN)       |  SPACE(SHIFT)  |           |  ENTER(SHIFT)     |    ALT(MENU)         |   RAISE    |  BACKSPACE  |  
 *         `-------------------------------------------------------------------´           `--------------------------------------------------------------------´*/ 	 
	KC_LGUI, TD(DEL_INS),	TT(_NUM),	MT(MOD_LALT, KC_RGUI), MT(MOD_LSFT, KC_SPC),			MT(MOD_RSFT,KC_ENT), MT(MOD_RALT, KC_APP), TT(_FUNC), 	KC_BSPC, 			TD(MEDIA_SCROLL)
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                       _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______\
```suggestion
[_NUM] = LAYOUT(
  _______,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                       KC_CIRC,   KC_7,   KC_8,   KC_9,  XXXXXXX,  XXXXXXX,
  _______,    XXXXXXX,    KC_UP,    XXXXXXX,    XXXXXXX,    XXXXXXX,        KC_HASH,    KC_4,    KC_5,    KC_6,	XXXXXXX, XXXXXXX,
  XXXXXXX, KC_LEFT,   KC_DOWN, KC_RIGHT,  KC_LBRC, KC_RBRC,                 KC_AMPR, 	KC_1, 	KC_2, 	KC_3, 	XXXXXXX, XXXXXXX,
  _______,  XXXXXXX, KC_PAST, KC_PPLS, KC_PSLS, KC_EQL, _______,       _______, KC_DLR, KC_0, KC_SCLN, KC_COLN, KC_PMNS, _______,
                       _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______ \
```suggestion
[_FUNC] = LAYOUT(
  _______,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                       KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  _______,
  _______,  _______,  _______,   _______,  _______, _______,                        _______, _______,   _______, _______,_______, _______,
  _______, _______,  _______,  _______,  _______, _______,                       _______,  _______, _______, _______,  _______, _______,
  _______,_______, _______, _______, _______, _______,  _______,       _______,  _______, _______, _______, _______,   _______, _______,
                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +                   _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______ \
```suggestion
  [_SYSTEM] = LAYOUT(
  XXXXXXX , XXXXXXX,  XXXXXXX ,  XXXXXXX , XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  RESET  , XXXXXXX,KC_QWERTY,KC_COLEMAK,XXXXXXX,KC_ASTG,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX , XXXXXXX,XXXXXXX, XXXXXXX,    XXXXXXX,  XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX , XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX,  XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                   _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +    //led_t led_usb_state = host_keyboard_led_state();
```suggestion
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +*/
```suggestion
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
These need to be filled out.

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/readme.md
> +    make lotus58:default:flash
```suggestion
    make tweetydabird/lotus58:default:flash
```

2021-07-10 05:54 UTC, fauxpark commented on keyboards/tweetydabird/lotus58/rules.mk
> +SPLIT_KEYBOARD = yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
AUTO_SHIFT_ENABLE = yes
ENCODER_ENABLE = yes
OLED_DRIVER_ENABLE = yes
```

Tap Dance cannot be enabled at keyboard level. Add a rules.mk with `TAP_DANCE_ENABLE = yes` under the default keymap instead.

2021-09-15 02:22 UTC, drashna requested changes
you have changes to the submodules, which need to be reverted. 

Most likely, the PR needs a rebase to fix the issue.  If you need help with this, let us know.

2021-09-15 02:22 UTC, drashna commented on keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
> +#ifdef OLED_ENABLE
If you could, please move the oled code and the encoder code to the keyboard's c file.  Make sure that the oled code is set weak (eg `__attribute__((weak)) void oled_task_user(void) {`),

2021-09-15 02:22 UTC, drashna commented on keyboards/tweetydabird/lotus58/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
This information needs to be filled out

2021-09-15 02:22 UTC, drashna commented on keyboards/tweetydabird/lotus58/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-11-05 15:04 UTC, keyboard-magpie commented
@TweetyDaBird we have continuing requests for firmware for this keyboard in the QMK discord- if you can address the changes or need help making them please reach out https://discord.gg/3QUsJqvwbm

2022-01-09 01:14 UTC, closed without merging