[Keyboard] Add SiddersKB Majbritt Rev2
qmk/qmk_firmware pull request #12598
Opened 2021-04-16 18:37 UTC by Sleepdealr

Added support for the Majbritt Rev2 by SiddersKB

## Description

Added the Majbritt Rev2 keyboard and keymap

Moved the old Rev1 to a new folder under sidderskb/majbritt

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-20 03:06 UTC, drashna requested changes

2021-04-20 03:06 UTC, drashna commented on keyboards/sidderskb/majbritt/rev2/keymaps/default/keymap.c
> +[0] = KEYMAP( //Default layout (currently ISO)
```suggestion
[0] = LAYOUT( //Default layout (currently ISO)
```

2021-04-20 03:06 UTC, drashna commented on keyboards/sidderskb/majbritt/rev2/keymaps/default/keymap.c
> +[1] = KEYMAP(
```suggestion
[1] = LAYOUT(
```

2021-04-20 03:06 UTC, drashna commented on keyboards/sidderskb/majbritt/rev2/keymaps/default/keymap.c
> +[2] = KEYMAP(
```suggestion
[2] = LAYOUT(
```

2021-04-20 03:06 UTC, drashna commented on keyboards/sidderskb/majbritt/rev2/keymaps/default/keymap.c
> +[3] = KEYMAP(
```suggestion
[3] = LAYOUT(
```

2021-04-20 03:06 UTC, drashna commented on keyboards/sidderskb/majbritt/rev2/rev2.h
> +#define KEYMAP( \
```suggestion
#define LAYOUT( \
```

2021-05-14 03:35 UTC, drashna approved these changes

2021-05-14 08:48 UTC, fauxpark approved these changes

2021-05-16 00:18 UTC, drashna commented
Thanks!

2021-05-16 00:18 UTC, merged