Added Delilah keyboard
qmk/qmk_firmware pull request #12636
Opened 2021-04-20 22:28 UTC by rainkeebs

## Description
Added support for Delilah keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-20 23:11 UTC, ridingqwerty requested changes
Some minor suggestions.  Definitely remove the chibios files from this PR.

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/config.h
> +
```suggestion
```

This is in core now, no need to put in your `config.h`

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = lite # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes   # Mouse keys
EXTRAKEY_ENABLE = yes   # Audio control and System control
CONSOLE_ENABLE = no     # Console for debug
COMMAND_ENABLE = no     # Commands for debug and configuration
SLEEP_LED_ENABLE = no   # Breathing sleep LED during USB suspend
NKRO_ENABLE = yes       # USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = no   # Enable keyboard backlight functionality
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = yes

```

Aligned comments, converted tabs to spaces, removed firmware size diffs as they are variable & inaccurate

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion

#  Bootloader selection
BOOTLOADER = atmel-dfu
```

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/keymaps/via/keymap.c
> +#include "delilah.h"
```suggestion
#include QMK_KEYBOARD_H
```

Prefer the generic `QMK_KEYBOARD_H` here over the explicit header name.

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/keymaps/via/keymap.c
> +}
```suggestion
```

Remove unused functions.

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/keymaps/default/keymap.c
> +}
```suggestion
```

Remove unused functions.

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/keymaps/default/keymap.c
> +#include "delilah.h"
```suggestion
#include QMK_KEYBOARD_H
```

Prefer the generic `QMK_KEYBOARD_H` over the explicit header name here.

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/delilah.h
> +}
```suggestion
}

```

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/readme.md
> +    make delilah:default
```suggestion
    qmk compile -kb delilah -kb default
```

Prefer `qmk` CLI syntax in favor of `make` syntax here.

2021-04-20 23:11 UTC, ridingqwerty commented on keyboards/delilah/readme.md
> +    make delilah:default:flash
```suggestion
    qmk flash -kb delilah -km default
```

Prefer `qmk` CLI over `make` syntax here.

2021-04-20 23:56 UTC, rainkeebs commented
> Some minor suggestions. Definitely remove the chibios files from this PR.

I'm not sure how to get the chibios files out of the PR... didn't even notice they were part of it

2021-04-21 00:56 UTC, closed without merging

2021-04-21 00:57 UTC, rainkeebs commented
opening a new PR without the changed chibios files