Add personal keymaps
qmk/qmk_firmware pull request #12644
Opened 2021-04-21 16:28 UTC by ALysaght

Add primarily 36/46 key keymaps

## Description

Preonic, Atreus62, dz65, nyquist, user files

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-12 17:08 UTC, ridingqwerty requested changes
We usually don't recommend new keyboard submission with large userspace updates, but since it's a handwired board it isn't a big deal.  I left a few suggestions regarding convention used on the ortho36.

2021-05-12 17:08 UTC, ridingqwerty commented on keyboards/handwired/ortho36/config.h
> +#endif
```suggestion
```

Use of `#pragma once` above obviates need for this `#endif`

2021-05-12 17:08 UTC, ridingqwerty commented on keyboards/handwired/ortho36/config.h
> +#define DESCRIPTION     handwired mini-planck
```suggestion
```

Omit description field.

2021-05-13 17:54 UTC, drashna requested changes

2021-05-13 17:54 UTC, drashna commented on keyboards/handwired/ortho36/rules.mk
> +# OPT_DEFS += -DBOOTLOADER_SIZE=512
```suggestion
```

Though, you will want to define the `BOOTLOADER`

2021-05-13 17:54 UTC, drashna commented on keyboards/preonic/keymaps/alysaght/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-13 17:54 UTC, drashna commented on users/alysaght/alysaght.c
> +#include "alysaght.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-13 17:54 UTC, drashna commented on users/alysaght/alysaght.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-13 17:54 UTC, drashna commented on users/alysaght/config.h
> +#define TAPPING_TERM 215
```suggestion
#pragma once

#define TAPPING_TERM 215
```

Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-15 14:08 UTC, ALysaght commented
@ridingqwerty and @drashna thank you both for the feedback, apologies for my complete lack of understanding of C++. I believe each of your requests have been addressed, let me know if additional changes are needed.

2021-05-15 18:40 UTC, drashna requested changes

2021-05-15 18:40 UTC, drashna commented on keyboards/dztech/dz65rgb/keymaps/alysaght/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-15 18:40 UTC, drashna commented on keyboards/handwired/ortho36/ortho36.c
> +#include "ortho36.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-15 18:40 UTC, drashna commented on keyboards/handwired/ortho36/ortho36.c
> +};
```suggestion
```

2021-05-15 18:40 UTC, drashna commented on keyboards/handwired/ortho36/ortho36.h
> +#define PLANCK_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

```suggestion
#pragma once
```

2021-05-15 18:40 UTC, drashna commented on keyboards/handwired/ortho36/ortho36.h
> +#endif
```suggestion
```

2021-05-15 18:40 UTC, drashna commented on keyboards/keebio/nyquist/keymaps/alysaght/keymap.c
> +}
```suggestion
```

2021-05-15 18:40 UTC, drashna commented on users/alysaght/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-30 10:23 UTC, closed without merging