Add program yoink via keymap
qmk/qmk_firmware pull request #12645
Opened 2021-04-21 17:35 UTC by matthewdias

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2021-05-12 17:10 UTC, ridingqwerty approved these changes

2021-05-12 23:48 UTC, fauxpark requested changes

2021-05-12 23:48 UTC, fauxpark commented on keyboards/program_yoink/staggered/keymaps/via/config.h
> +#endif
```suggestion
#define RGBLIGHT_ANIMATIONS
```

2021-06-06 18:33 UTC, fauxpark approved these changes

2021-06-07 05:10 UTC, drashna approved these changes

2021-06-07 05:10 UTC, merged