Updated keyboard & keymaps
qmk/qmk_firmware pull request #12667
Opened 2021-04-23 18:29 UTC by farfalleflickan

## Description

I've updated my username to my new one & fixed related URLs. I've also made small changes to the keyboard's default configuration & keymap. The audio functionality is now correctly configured for the board.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-19 23:40 UTC, farfalleflickan commented
Bump! :)

2021-07-20 16:57 UTC, drashna approved these changes

2021-07-20 17:03 UTC, fauxpark requested changes

2021-07-20 17:03 UTC, fauxpark commented on keyboards/nack/keymaps/farfalleflickan/keymap.c
> +    | \            \            \            \            \            \            \            \            \            \            \            \            \            \        */
```suggestion
    | \            \            \            \            \            \            \            \            \            \            \            \            \            \        */
```
Please remove all trailing whitespace.

2021-07-21 05:30 UTC, fauxpark approved these changes

2021-07-22 06:56 UTC, drashna commented
Thanks!

2021-07-22 06:57 UTC, merged