Change RGB/LED Matrix to use a simple define for USB suspend
qmk/qmk_firmware pull request #12697
Opened 2021-04-25 23:23 UTC by drashna

## Description

Like the title says. 
But more specifically, instead of using a bool for the define, it changes it to be a simple define. If present, then enables the functionality, if not defined, then it stays running when USB suspends. 
Also makes the g_suspend_state variable static to not conflict between rgb matrix and led matrix.

And adds a check to make sure it's properly handled. 

Does not touch existing keyboards, just changes how the define works. 

## Types of Changes

- [x] Core
- [x] Enhancement/optimization
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-04-26 06:29 UTC, fauxpark requested changes

2021-04-26 06:29 UTC, fauxpark commented on tmk_core/common/chibios/suspend.c
> +    rgb_matrix_set_suspend_state(true);
```suggestion
    rgb_matrix_set_suspend_state(false);
```

2021-04-26 06:29 UTC, fauxpark commented on quantum/rgb_matrix.c
> +static bool            g_suspend_state   = false;
Should not be prefixed with `g_` if it is not global anymore.

2021-04-28 18:59 UTC, XScorpion2 approved these changes

2021-04-28 19:14 UTC, Erovia approved these changes
`__attribute__ ((weak))`

2021-04-29 02:39 UTC, fauxpark approved these changes

2021-04-29 02:39 UTC, merged