Think6.5v2 keymap with working caps-lock indicator
qmk/qmk_firmware pull request #12709
Opened 2021-04-27 00:23 UTC by dangjoeltang

## Description

Custom keymap with working caps-lock indicator light, when using static RGB mode. The firmware that ships with the Think6.5v2 has a working Caps-lock indicator that lights up the top part of the badge. However, the version in `gray_studio/think65/solder` does not. 

This is a stopgap for those who re-flashed their board's and would like to have the indicator light functionality back. 

I will continue working to make a better default keymap and submit a keyboard update in a later PR.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-04 15:57 UTC, dangjoeltang commented
@mechmerlin, can you take a look at my keymap? I saw that you were the maintainer for the Think6.5v1 firmware

2021-05-13 17:28 UTC, drashna requested changes

2021-05-13 17:28 UTC, drashna commented on keyboards/gray_studio/think65/solder/keymaps/dangjoeltang/config.h
> +/* Copyright 2021 Qiaowei Tang
This file should be removed.

2021-05-13 17:28 UTC, drashna commented on keyboards/gray_studio/think65/solder/keymaps/dangjoeltang/keymap.c
> +#define XXXXXXX KC_NO
These defines aren't necessary, as these are actually defined in the core.  You can safely remove them. 

https://github.com/qmk/qmk_firmware/blob/a0309db983150fd0197eb620a6ba552d90d29f93/quantum/quantum_keycodes.h#L30-L31


```suggestion
```

2021-05-14 04:10 UTC, drashna approved these changes

2021-05-14 08:50 UTC, fauxpark requested changes

2021-05-14 08:50 UTC, fauxpark commented on keyboards/gray_studio/think65/solder/keymaps/dangjoeltang/rules.mk
> +# Build Options
This file can be deleted.

2021-06-29 00:05 UTC, fauxpark approved these changes

2021-07-03 06:31 UTC, drashna commented
Thanks!

2021-07-03 06:31 UTC, merged