Add np12
qmk/qmk_firmware pull request #12703
Opened 2021-04-26 12:20 UTC by nut1414

## Description

Adding np12 keypad

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-12 17:17 UTC, ridingqwerty approved these changes

2021-05-12 23:47 UTC, fauxpark requested changes

2021-05-12 23:47 UTC, fauxpark commented on keyboards/np12/readme.md
> +![np12 pcb](https://i.imgur.com/DIIvW95.jpg)
```suggestion
![np12](https://i.imgur.com/gci7qqZh.jpg)

![np12 pcb](https://i.imgur.com/DIIvW95h.jpg)
```

2021-05-12 23:47 UTC, fauxpark commented on keyboards/np12/readme.md
> +
```suggestion
```

2021-05-12 23:47 UTC, fauxpark commented on keyboards/np12/rules.mk
> +RGBLIGHT_ENABLE = no	# Enable keyboard RGB underglow
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-05-13 00:42 UTC, fauxpark approved these changes

2021-05-13 00:43 UTC, nut1414 commented
Thanks for reviewing this.

2021-05-13 01:27 UTC, drashna approved these changes

2021-05-13 01:27 UTC, merged