Add RGB matrix support for Kyria
qmk/qmk_firmware pull request #12789
Opened 2021-05-03 07:51 UTC by filterpaper

## Description

This change adds `g_led_config` struct to Kyria, allowing LEDs to be addressed by `RGB_MATRIX_ENABLE` features if users enable support in their own configuration.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-03 11:00 UTC, filterpaper commented
RGB matrix transport is still in the develop tree, this will not work properly until that is merged into master.

2021-06-20 01:59 UTC, drashna approved these changes

2021-07-27 01:26 UTC, filterpaper commented
Rebased changes to `develop` to reflect new path.

2021-07-27 01:27 UTC, drashna requested changes

2021-07-27 01:27 UTC, drashna commented on keyboards/splitkb/kyria/rev1/config.h
> +#    endif
```suggestion
#    define RGB_DISABLE_WHEN_USB_SUSPENDED
```

2021-07-27 01:27 UTC, drashna commented on keyboards/splitkb/kyria/rev1/rules.mk
> +RGB_MATRIX_DRIVER = WS2812 # RGB matrix driver support
```suggestion
RGB_MATRIX_DRIVER = WS2812 # RGB matrix driver support

RGB_MATRIX_SUPPORTED = yes
```

2021-07-27 02:07 UTC, fauxpark approved these changes

2021-07-27 02:42 UTC, drashna approved these changes

2021-07-27 02:42 UTC, merged