JETVAN: Add initial support
qmk/qmk_firmware pull request #12790
Opened 2021-05-03 17:27 UTC by TerryMathews

## Description

Initial support for JetVan keyboard including VIA.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-11 21:48 UTC, fauxpark requested changes

2021-05-11 21:48 UTC, fauxpark commented on keyboards/thevankeyboards/jetvan/readme.md
> +Hardware Availability: TBA
```suggestion
* Keyboard Maintainer: QMK Community
* Hardware Supported: JetVan PCB
* Hardware Availability: TBA
```

2021-05-11 21:48 UTC, fauxpark commented on keyboards/thevankeyboards/jetvan/rules.mk
> +
```suggestion
```

2021-05-12 01:27 UTC, drashna approved these changes

2021-06-05 22:25 UTC, TerryMathews commented
@drashna Can this get merged please?

2021-06-05 22:26 UTC, merged