Convert Encoder callbacks to be boolean functions
qmk/qmk_firmware pull request #12805
Opened 2021-05-05 01:51 UTC by drashna

## Description

This converts the callback functions for encoders to be boolean, so that you can easily have code at the keyboard level that can overridden, or even that cannot (useful for oled/haptic/clicky behavior). 

## Types of Changes

- [x} Core
- [x] Bugfix
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-06 18:27 UTC, noroadsleft requested changes
Everything else in here is slight `__attribute__ ((weak))` :heavy_check_mark: for me.

2021-05-06 18:27 UTC, noroadsleft commented on keyboards/cannonkeys/ortho75/ortho75.c
> +    unregistenr_code(mapped_code);
```suggestion
    unregister_code(mapped_code);
```

2021-05-06 20:18 UTC, noroadsleft approved these changes
`__attribute__ ((weak))` :heavy_check_mark:

2021-05-19 17:41 UTC, ridingqwerty approved these changes
Everything here looks good to me.

2021-05-19 18:38 UTC, drashna commented
(don't merge yet, rebasing and updating)

2021-05-22 06:17 UTC, merged