VIA support with top facing LEDs and underglow
qmk/qmk_firmware pull request #12814
Opened 2021-05-05 20:24 UTC by killmaster

## Description

Added VIA support for the top facing RGB LEDs on top of the existing underglow.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-03 06:58 UTC, drashna approved these changes

2021-07-03 07:04 UTC, fauxpark requested changes

2021-07-03 07:04 UTC, fauxpark commented on keyboards/sofle/keymaps/via/config.h
> +//Add RGB underglow and top facil lighting
```suggestion
//Add RGB underglow and top facing lighting
```

2021-09-11 02:48 UTC, fauxpark approved these changes

2021-09-15 03:38 UTC, merged