[keymap] Added new `oled_status` keymap to `nullbitsco/nibble` keyboard
qmk/qmk_firmware pull request #12824
Opened 2021-05-07 07:12 UTC by joadtor

## Description

Added new `oled_status` keymap to `nullbitsco/nibble` keyboard, providing features not present in other keymaps from that keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-13 02:27 UTC, drashna requested changes

2021-05-13 02:27 UTC, drashna commented on keyboards/nullbitsco/nibble/keymaps/oled_status/rules.mk
> +	       glcdfont.c
```suggestion
	SRC += oled_display.c
```

2021-05-13 16:36 UTC, drashna approved these changes

2021-06-24 02:24 UTC, tzarc approved these changes

2021-06-24 02:24 UTC, merged