adding my keymap
qmk/qmk_firmware pull request #12834
Opened 2021-05-08 21:20 UTC by MVi06

## Description

It’s the keymap I use. Based on the bépo french layout.

2021-05-13 02:23 UTC, drashna requested changes

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/config.h
> +    #define RGBLIGHT_VAL_STEP 17
Nit pick:
```suggestion
#    undef RGBLED_NUM
#    define RGBLED_NUM 27
#    define RGBLIGHT_ANIMATIONS
#    define RGBLIGHT_SLEEP
#    define RGBLIGHT_SPLIT
#    define RGBLIGHT_LIMIT_VAL 120
#    define RGBLIGHT_HUE_STEP 10
#    define RGBLIGHT_SAT_STEP 17
#    define RGBLIGHT_VAL_STEP 17
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/config.h
> +#define OLED_FONT_H "keyboards/crkbd/keymaps/soundmonster/glcdfont.c"
```suggestion
#define OLED_FONT_H "keyboards/crkbd/keymaps/mvi/glcdfont.c"
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +#include "action_layer.h"
```suggestion
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +#endif
Is this needed?

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +#endif
```suggestion
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +int current_base_layer = _BEPO;
```suggestion
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +int RGB_current_mode;
```suggestion
uint8_t RGB_current_mode;
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +
Could you remove this function?  

It's been deprecated in favor of the `set_single_persistent_default_layer` function (which is a core function).

https://docs.qmk.fm/#/ref_functions?id=setting-the-persistent-default-layer

Same with the tri layer function 
```suggestion
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +      RGB_current_mode = rgblight_config.mode;
```suggestion
      RGB_current_mode = rgblight_get_mode();
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +    switch(current_base_layer) {
```suggestion
    switch(get_highest_layer(default_layer_state)) {
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +	current_base_layer = _BEPO;
```suggestion
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +      current_base_layer = _NUMPAD;
```suggestion
```

2021-05-13 02:23 UTC, drashna commented on keyboards/crkbd/keymaps/mvi/keymap.c
> +        persistent_default_layer_set(1UL<<_BEPO);
```suggestion
        set_single_persistent_default_layer(_BEPO);
```

2021-05-13 02:23 UTC, drashna commented on keyboards/planck/keymaps/a2b/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2021-05-13 02:23 UTC, drashna commented on keyboards/planck/keymaps/mvi/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-13 02:23 UTC, drashna commented on keyboards/planck/keymaps/mvi/keymap.c
> +#endif
Is this needed?

2021-05-13 02:23 UTC, drashna commented on keyboards/planck/keymaps/mvi/keymap.c
> +extern keymap_config_t keymap_config;
```suggestion
```

2021-05-13 16:51 UTC, drashna approved these changes

2021-05-14 01:20 UTC, drashna commented
It looks like you need to rebase your branch here.

2021-06-24 02:52 UTC, tzarc requested changes

2021-06-24 02:52 UTC, tzarc commented on keyboards/crkbd/keymaps/mvi/config.h
> +<<<<<<< HEAD
I think you might've had a problematic merge. Might want to go through your entire PR again.

2021-06-28 12:00 UTC, MVi06 commented
I will try to do a cleaner pull request. Thanks for the advices.

2021-06-28 12:00 UTC, closed without merging