Adding bm60ec rgb
qmk/qmk_firmware pull request #12852
Opened 2021-05-09 21:35 UTC by umbacos

Hi, I wrote the keyboard "bm60ec rgb" which is the bm60 with rotary encoder that was missing in the QMK master branch.

## Description

created a new directory under keyboard called bm60ec_rgb, and added all the required files, including via support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-10 06:23 UTC, drashna commented
Please revert all changes outside of the keyboard addition, itself.

2021-06-16 04:17 UTC, drashna requested changes
You have a lot of additions changes outside of the bm60ec rgb keyboard.  

Please revert these changes. If you need help with this, don't hesitate to ask.

2021-06-16 04:17 UTC, drashna commented on .gitignore
> +lib/ugfx
Please revert this change.
```suggestion
```

2021-08-13 19:41 UTC, drashna requested changes

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos/keymap.c
> +#endif
```suggestion
```

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos/keymap.c
> +extern keymap_config_t keymap_config;
```suggestion
```

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos_light/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos_light/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos_light/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-13 19:41 UTC, drashna commented on keyboards/40percentclub/gherkin/keymaps/umbacos_midi/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-15 12:03 UTC, filterpaper commented
KPrepublic PCBs are now located within `keyboards/kprepublic`. `bm60ec_rgb` should reside in there as well.

2021-11-06 12:34 UTC, peepeetee commented
Also, I standardized the naming format for KPrepublic PCBs. (see #15047) See if you can rename the board to bm60ec

2022-06-12 15:55 UTC, closed without merging