Update oled_bongocat to match VIA keymap
qmk/qmk_firmware pull request #12875
Opened 2021-05-12 06:15 UTC by jaygreco

## Description

The original version of this keymap was missing layers 3 and 4, which messed with VIA support.
The "extra" macros from the default keymap were also added (Discord mute, super alt-tab, etc).

Tested locally on a NIBBLE keyboard with OLED display.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-13 01:48 UTC, drashna requested changes

2021-05-13 01:48 UTC, drashna commented on keyboards/nullbitsco/nibble/keymaps/oled_bongocat/keymap.c
>  };
This is way over complicated, IMO. 

If you use USER00-USER15, this is a lot simpler. Eg

```suggestion
enum custom_keycodes {
  PROG = USER00,
  DISC_MUTE,
  DISC_DEAF,
  SUPER_ALT_TAB,
  _NUM_CUST_KCS,
};
```

2021-05-13 01:48 UTC, drashna commented on keyboards/nullbitsco/nibble/keymaps/oled_bongocat/keymap.c
> +
The above change would remove the need for this. 
```suggestion
```

2021-05-13 01:48 UTC, drashna commented on keyboards/nullbitsco/nibble/keymaps/oled_bongocat/keymap.c
> +    map_via_keycode(&keycode);
And this. 
```suggestion
```

2021-05-13 02:24 UTC, jaygreco commented
@drashna Thanks for the feedback. Updated to use the USER00 offset instead of the remapping. That was some older code I copied from the other VIA keymap; I must have written it before the USER00 offset was added (or I just missed it).

When this PR is okay'ed I'll make the same change in the VIA keymap as well, I like the simplicity.

2021-05-13 02:59 UTC, drashna commented
Sounds good.  And yeah, I like simplicity too!

2021-05-13 03:00 UTC, drashna approved these changes

2021-06-24 02:22 UTC, tzarc approved these changes

2021-06-24 02:22 UTC, merged