Add WTF60
qmk/qmk_firmware pull request #12883
Opened 2021-05-12 21:10 UTC by nooges

## Description

Add WTF60 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-12 23:41 UTC, fauxpark requested changes

2021-05-12 23:41 UTC, fauxpark commented on keyboards/keebio/wtf60/config.h
> +#define DESCRIPTION     Mirrored 60% keyboard
```suggestion
```

2021-05-12 23:41 UTC, fauxpark commented on keyboards/keebio/wtf60/readme.md
> +Hardware Availability: [Keebio](https://keeb.io)
```suggestion
* Keyboard Maintainer: [nooges/bakingpy](https://github.com/nooges)
* Hardware Supported: WTF60 PCB w/ATmega32u4
* Hardware Availability: [Keebio](https://keeb.io)
```

2021-05-12 23:41 UTC, fauxpark commented on keyboards/keebio/wtf60/readme.md
> +    make keebio/wtf60:default:dfu
```suggestion
    make keebio/wtf60:default

Flashing example for this keyboard:

    make keebio/wtf60:default:flash
```

2021-05-12 23:41 UTC, fauxpark commented on keyboards/keebio/wtf60/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-05-12 23:41 UTC, fauxpark commented on keyboards/keebio/wtf60/rules.mk
> +SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-05-13 01:40 UTC, drashna requested changes

2021-05-13 01:40 UTC, drashna commented on keyboards/keebio/wtf60/config.h
> +  #define RGBLIGHT_ANIMATIONS
nit pick: 
```suggestion
#    define RGBLED_NUM 16
#    define RGBLIGHT_HUE_STEP 8
#    define RGBLIGHT_SAT_STEP 8
#    define RGBLIGHT_VAL_STEP 8
#    define RGBLIGHT_LIMIT_VAL 255 /* The maximum brightness level */
#    define RGBLIGHT_SLEEP  /* If defined, the RGB lighting will be switched off when the host goes to sleep */
/*== all animations enable ==*/
#    define RGBLIGHT_ANIMATIONS
```

2021-05-13 01:40 UTC, drashna commented on keyboards/keebio/wtf60/wtf60.h
> +LAYOUT_full_wtf( \
Please no recursive layouts.

2021-05-17 17:20 UTC, nooges commented on keyboards/keebio/wtf60/wtf60.h
> +LAYOUT_full_wtf( \
Done, killed it. 🔪

2021-05-17 23:27 UTC, fauxpark approved these changes

2021-05-22 05:29 UTC, drashna approved these changes

2021-05-22 05:29 UTC, merged