[Keyboard] New Keyboard - Murphpad
qmk/qmk_firmware pull request #12885
Opened 2021-05-13 02:04 UTC by kylemccreery

## Description

Initial PR for adding the MurphPad numpad by MechWild. This is the default and VIA keymaps. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-13 17:15 UTC, drashna approved these changes

2021-05-13 17:23 UTC, fauxpark requested changes

2021-05-13 17:23 UTC, fauxpark commented on keyboards/mechwild/murphpad/keymaps/via/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2021-05-13 17:23 UTC, fauxpark commented on keyboards/mechwild/murphpad/readme.md
> +![murphpad](https://i.imgur.com/UmlpQ9p.jpg)
```suggestion

![murphpad](https://i.imgur.com/UmlpQ9ph.jpg)
```

2021-05-13 17:23 UTC, fauxpark commented on keyboards/mechwild/murphpad/rules.mk
> +OLED_DRIVER_ENABLE = yes	# Enable OLED Screen
```suggestion
ENCODER_ENABLE = yes        # Enable encoder
OLED_DRIVER_ENABLE = yes    # Enable OLED Screen
```

2021-05-13 17:27 UTC, fauxpark approved these changes

2021-05-18 07:06 UTC, fauxpark requested changes
Submodule changes need to be reverted before this can be merged.

2021-05-18 10:34 UTC, kylemccreery commented
> Submodule changes need to be reverted before this can be merged.

Yep. This wasn't supposed to push. Not sure why it did.

2021-05-18 11:07 UTC, kylemccreery commented
@fauxpark Sorry about that. Git still confuses me sometimes. I believe it is fixed now.

2021-05-19 00:00 UTC, fauxpark requested changes

2021-05-19 00:23 UTC, fauxpark requested changes
And some other stuff above.

2021-05-19 00:23 UTC, fauxpark commented on keyboards/mechwild/murphpad/rules.mk
> +OLED_DRIVER_ENABLE = yes	# Enable OLED Screen
```suggestion
OLED_DRIVER_ENABLE = yes    # Enable OLED Screen
```

2021-05-19 00:50 UTC, kylemccreery commented
I think those changes were undone when I reverted to try and fix the submodule. My bad. Thanks for catching it @fauxpark

2021-05-19 01:02 UTC, fauxpark approved these changes

2021-05-22 05:28 UTC, drashna commented
Thanks!

2021-05-22 05:28 UTC, merged