[Keyboard] SKErgo
qmk/qmk_firmware pull request #12923
Opened 2021-05-16 23:23 UTC by C1intMason

## Description

Add SKErgo support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add SKErgo support

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-22 05:52 UTC, drashna requested changes

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/keymaps/default/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
```suggestion
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)

```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/keymaps/default/keymap.c
> +#include "skergo.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

```suggestion
#include QMK_KEYBOARD_H
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/keymaps/via/keymap.c
> +#include "skergo.h"
```suggestion
#include QMK_KEYBOARD_H
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/keymaps/via/rules.mk
> +MOUSEKEY_ENABLE = no
You probably want these enabled.

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=2048
```suggestion
# Processor frequency.
F_CPU = 16000000

# Bootloader
BOOTLOADER = USBasp
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/rules.mk
> +RGBLIGHT_ENABLE ?= no
```suggestion
BOOTMAGIC_ENABLE = lite	# Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes	# Mouse keys
EXTRAKEY_ENABLE = yes	# Audio control and System control
CONSOLE_ENABLE = no	# Console for debug
COMMAND_ENABLE = no    # Commands for debug and configuration
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
NKRO_ENABLE = no		# USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = no  # Enable keyboard backlight functionality
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/skergo.h
> +#define KB_H
```suggestion
#pragma once
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/skergo.h
> +#endif
```suggestion
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/config.h
> +#define CONFIG_H
```suggestion
#pragma once
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/config.h
> +#define DESCRIPTION     Through-hole Ergonomic Keyboard
```suggestion
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2021-05-22 05:52 UTC, drashna commented on keyboards/skergo/config.h
> +#endif
```suggestion
```

2021-05-22 06:38 UTC, C1intMason reviewed
Suggestions lgtm, implemented everything.

2021-05-22 06:57 UTC, drashna approved these changes

2021-05-22 07:42 UTC, fauxpark requested changes

2021-05-22 07:42 UTC, fauxpark commented on keyboards/skergo/rules.mk
> +RGBLIGHT_ENABLE = no
```suggestion
# Processor frequency
F_CPU = 16000000

# Bootloader selection
BOOTLOADER = USBasp

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-05-22 08:41 UTC, fauxpark requested changes

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/info.json
> +    "key_count": 67,
```suggestion
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/skergo.h
> +#define LAYOUT_default( \
```suggestion
#define LAYOUT( \
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/readme.md
> +![skergo](https://cdn.shopify.com/s/files/1/0396/3001/2582/products/Keyzio-5_1024x1024@2x.jpg?v=1612909648)
```suggestion
![skergo](https://i.imgur.com/WIqxiMfh.png)
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/info.json
> +      "LAYOUT_default": {
```suggestion
      "LAYOUT": {
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/keymaps/default/keymap.c
> +	[0] = LAYOUT_default(
```suggestion
	[0] = LAYOUT(
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/keymaps/default/keymap.c
> +	[1] = LAYOUT_default(
```suggestion
	[1] = LAYOUT(
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/keymaps/via/keymap.c
> +	[0] =	LAYOUT_default(
```suggestion
	[0] =	LAYOUT(
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/keymaps/via/keymap.c
> +		[1] =	LAYOUT_default(
```suggestion
		[1] =	LAYOUT(
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/keymaps/via/keymap.c
> +		[2] =	LAYOUT_default(
```suggestion
		[2] =	LAYOUT(
```

2021-05-22 08:41 UTC, fauxpark commented on keyboards/skergo/keymaps/via/keymap.c
> +		[3] =	LAYOUT_default(
```suggestion
		[3] =	LAYOUT(
```

2021-05-22 20:32 UTC, C1intMason reviewed
Commited changes

2021-05-22 23:46 UTC, fauxpark approved these changes

2021-05-27 04:00 UTC, merged

2021-05-27 04:00 UTC, drashna commented
Thanks!

2021-05-27 04:02 UTC, C1intMason commented
Thanks for the help!