[Keymap] update gunp layout for Planck
qmk/qmk_firmware pull request #12926
Opened 2021-05-17 11:54 UTC by gunpinyo

Major update on gunp layout for Planck

## Description

This PR contains many updates to my keymap but the main mechanism of binary switching is the same. I also clean up my `readme.md`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-18 01:37 UTC, gunpinyo commented
Hi @yanfali, could you merge my PR?
It has been almost 3 years since our last conversation.
I have fixed all of the problems (I believe).

2021-05-22 05:43 UTC, drashna approved these changes

2021-05-22 05:58 UTC, fauxpark requested changes
Please also undo the permissions changes.

2021-05-22 05:58 UTC, fauxpark commented on keyboards/planck/keymaps/gunp/rules.mk
> +# https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = yes          # Audio output
```

2021-05-22 05:58 UTC, fauxpark commented on keyboards/planck/keymaps/gunp/rules.mk
> +DEBOUNCE_TYPE        = sym_defer_pk
```suggestion
KEY_LOCK_ENABLE = yes
DEBOUNCE_TYPE = sym_defer_pk
```

2021-05-22 05:58 UTC, fauxpark commented on keyboards/planck/keymaps/gunp/rules.mk
>  #
```suggestion
```

2021-05-26 11:06 UTC, gunpinyo commented
@fauxpark, all fixed.

2021-05-26 12:03 UTC, fauxpark approved these changes

2021-05-27 03:48 UTC, merged