Hatchback
qmk/qmk_firmware pull request #12958
Opened 2021-05-20 03:41 UTC by AlisGraveNil

## Description

This is a TKL DIY solder kit that can be converted into a 75% keyboard + a 13-key macropad.
This firmware is only for the TKL/75% and only one .hex needs to be created to control both; the firmware for the macropad will be in a different PR.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-22 06:33 UTC, drashna requested changes
Could you rename the folder to only be lower case? 

Also, you may need to rebase to fix the git submodules (the `lib` folder) changes.

2021-05-22 15:54 UTC, AlisGraveNil commented
@drashna - I think I got the rebase right; I can't tell if trying to lower-case it took

2021-05-22 17:10 UTC, drashna commented
submodules fixed, but folder name needs the temp name treatment, it looks like.

2021-05-22 17:47 UTC, AlisGraveNil commented
well... I corrected the name, but for some reason it wants to rewrite a bunch of other files too...

2021-05-22 17:50 UTC, AlisGraveNil commented
or maybe now it's fixed?

2021-05-27 04:02 UTC, drashna reviewed
Just missing a readme

2021-05-30 21:04 UTC, drashna commented on keyboards/clawsome/hatchback/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader to flash new firmware?

2021-06-07 05:38 UTC, drashna approved these changes

2021-06-07 11:06 UTC, fauxpark approved these changes

2021-06-13 20:58 UTC, AlisGraveNil commented
@drashna - can you push this to merge to the Master, since it's gotten two approval checks?

2021-06-16 04:19 UTC, drashna commented
Thanks!

2021-06-16 04:20 UTC, merged