add anomalykb a65i
qmk/qmk_firmware pull request #12967
Opened 2021-05-20 18:55 UTC by lfgberg

## Description

Added support for the anomalykb a65i pcb

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-22 06:48 UTC, drashna requested changes

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/a65i.c
> +#include "a65i.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/config.h
> +#define PREVENT_STUCK_MODIFIERS
```suggestion
```

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/keymaps/ansi_splitbs/config.h
> +/* Copyright 2021 Lfgberg
This file should be removed, since it doesn't contain any settings.

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/keymaps/default/config.h
> +/* Copyright 2021 Lfgberg
This file should be removed.

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/keymaps/iso/config.h
> +/* Copyright 2021 Lfgberg
Should be removed.

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/keymaps/iso_splitbs/config.h
> +/* Copyright 2021 Lfgberg
Should be removed.

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 2
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

```suggestion
#pragma once 

#define DYNAMIC_KEYMAP_LAYER_COUNT 2
```

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-05-22 06:48 UTC, drashna commented on keyboards/anomalykb/a65i/rules.mk
> +HD44780_ENABLE = no 		# Enable support for HD44780 based LCDs
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
UNICODE_ENABLE = no         # Unicode
BLUETOOTH_ENABLE = no       # Enable Bluetooth 
AUDIO_ENABLE = no           # Audio output
```

2021-05-27 04:05 UTC, drashna commented on keyboards/anomalykb/a65i/config.h
> +#define PREVENT_STUCK_MODIFIERS
Please remove this.  This is deprecated, and no longer does anything.

Specifically, it's now the default functionality, and has to be explicitly turned off.

2021-05-30 21:01 UTC, drashna commented on keyboards/anomalykb/a65i/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to jump to the bootloader to flash new firmware?

2021-06-11 05:30 UTC, drashna approved these changes

2021-07-16 03:01 UTC, fauxpark requested changes

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/keymaps/iso/keymap.c
> +    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS, \
```suggestion
    RESET,    KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,  KC_F12,  KC_TRNS,           KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,                    KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS,
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/keymaps/iso_splitbs/keymap.c
> +  KC_LSFT, KC_BSLS,  KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,          KC_UP,   KC_DEL,  \
```suggestion
  KC_ESC,  KC_1,     KC_2,   KC_3,   KC_4,   KC_5,   KC_6,   KC_7,   KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_GRV,  KC_BSPC, KC_PSCR,
  KC_TAB,  KC_Q,     KC_W,   KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,                   KC_PGUP,
  KC_CAPS, KC_A,     KC_S,   KC_D,   KC_F,   KC_G,   KC_H,   KC_J,   KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS,          KC_ENT,  KC_PGDN,
  KC_LSFT, KC_BSLS,  KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,          KC_UP,   KC_DEL,
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/keymaps/iso_splitbs/keymap.c
> +    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS, \
```suggestion
    RESET,    KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,  KC_F12,  KC_TRNS, KC_TRNS,  KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,                    KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS,
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/keymaps/via/keymap.c
> +  KC_LSFT,           KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,          KC_UP,   KC_DEL,  \
```suggestion
  KC_ESC,  KC_1,     KC_2,   KC_3,   KC_4,   KC_5,   KC_6,   KC_7,   KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,          KC_PSCR,
  KC_TAB,  KC_Q,     KC_W,   KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,          KC_BSLS, KC_PGUP,
  KC_CAPS, KC_A,     KC_S,   KC_D,   KC_F,   KC_G,   KC_H,   KC_J,   KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,           KC_PGDN,
  KC_LSFT,           KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,          KC_UP,   KC_DEL,
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/readme.md
> +![a65i](https://i.imgur.com/J4fzVVt.jpg)
```suggestion
![a65i](https://i.imgur.com/J4fzVVth.jpg)
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/readme.md
> +    make a65i:default
```suggestion
    make anomalykb/a65i:default
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion
# Bootloader selection
BOOTLOADER = atmel-dfu
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
```

2021-07-16 03:01 UTC, fauxpark commented on keyboards/anomalykb/a65i/keymaps/via/keymap.c
> +    KC_TRNS,            KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS, \
```suggestion
    RESET,    KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,  KC_F12,  KC_TRNS,           KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,          KC_TRNS,           KC_TRNS,
    KC_TRNS,            KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS,
```

2021-07-17 02:55 UTC, fauxpark requested changes
Still some outstanding suggestions.

2021-07-18 13:37 UTC, lfgberg commented
> Still some outstanding suggestions.

My bad, thought I'd gotten them all, thanks!

2021-07-18 13:55 UTC, fauxpark approved these changes

2021-07-20 16:34 UTC, drashna commented
Thanks!

2021-07-20 16:34 UTC, merged