Added Gentleman65
qmk/qmk_firmware pull request #12971
Opened 2021-05-21 07:49 UTC by ramyac6

## Description

Added Gentleman65 PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-22 06:50 UTC, drashna approved these changes

2021-05-30 21:00 UTC, drashna commented
It looks like you need to rebase this PR.

2021-07-20 16:20 UTC, drashna commented on keyboards/gentleman65/config.h
> +#define VENDOR_ID       0x00FA
While this vender ID doesn't appear to be in use, the low number bothers me. 

(doesn't need to be changed)

2021-07-20 16:24 UTC, drashna requested changes

2021-07-20 16:24 UTC, drashna commented on keyboards/gentleman65/keymaps/default/keymap.c
> +}
```suggestion
```

2021-07-20 16:24 UTC, drashna commented on keyboards/gentleman65/keymaps/via/keymap.c
> +}
```suggestion
```

2021-07-20 16:24 UTC, drashna commented on keyboards/gentleman65/gentleman65.c
> +#include "gentleman65.h"
This sets the behavior by default, and allows for user keymaps to over-ride the behavior. 

Also, this allows the encoders to work for the QMK Configurator. 
As well is updated to use the proper callbacks for the encoder functions (they changed to booleans recently)

```suggestion
#include "gentleman65.h"

bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) { /* First encoder */
        if (clockwise) {
            tap_code_delay(KC_AUDIO_VOL_UP, 10);
        } else {
            tap_code_delay(KC_AUDIO_VOL_DOWN, 10);
        }
    }
    return true;
}
```

2021-08-12 15:46 UTC, drashna requested changes

2021-08-12 15:46 UTC, drashna commented on keyboards/gentleman65/config.h
> +#define RGBLIGHT_ANIMATIONS
could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-08-12 15:46 UTC, drashna commented on keyboards/gentleman65/rules.mk
> +#   Atmel DFU    atmel-dfu
```suggestion
```

2021-09-11 03:07 UTC, drashna requested changes

2021-09-11 03:07 UTC, drashna commented on keyboards/gentleman65/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality on B7 by default
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
MIDI_ENABLE = no            # MIDI support
UNICODE_ENABLE = no         # Unicode
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
ENCODER_ENABLE = yes
```

2021-09-11 03:57 UTC, fauxpark requested changes

2021-09-11 03:57 UTC, fauxpark commented on keyboards/gentleman65/info.json
> +    "lighting": "qmk_backlight",
```suggestion
```

2021-09-11 03:57 UTC, fauxpark commented on keyboards/gentleman65/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
ENCODER_ENABLE = yes
```

2021-09-11 04:32 UTC, fauxpark requested changes

2021-09-11 04:32 UTC, fauxpark commented on keyboards/gentleman65/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-11 05:27 UTC, fauxpark approved these changes

2021-09-15 03:13 UTC, drashna approved these changes

2021-09-15 03:14 UTC, drashna commented
Thanks!

2021-09-15 03:20 UTC, drashna commented
Oh,: 

> ☒ gentleman65: gentleman65: LAYOUT_all: Number of elements in info.json does not match! info.json:69 != LAYOUT_all:68

This needs to be resolved.

2021-09-15 05:23 UTC, ramyac6 commented
I believe it's fixed now

2021-09-15 06:27 UTC, fauxpark approved these changes

2021-09-18 19:47 UTC, drashna approved these changes

2021-09-18 19:47 UTC, drashna commented
Thanks!

2021-09-18 19:47 UTC, merged