Jonavin merc
qmk/qmk_firmware pull request #12973
Opened 2021-05-21 17:40 UTC by Jonavin

## Description

- Add new mechwild/mercutio custom keymap with layered numpad and nav cluster
- keebio/quefency jonavin keymap layout changes  
- add README.md for joanvin keymaps
- numpad layers - left spacebar as Backspace

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-22 06:54 UTC, drashna requested changes

2021-05-22 06:54 UTC, drashna commented on keyboards/keebio/quefrency/keymaps/jonavin/README.md
> +# Jonathan's Quefrency layout - No Macros 65%
please rename this to be all lower case

2021-05-22 06:54 UTC, drashna commented on keyboards/mechwild/mercutio/keymaps/jonavin/config.h
> +#define OLED_FONT_H "keyboards/mechwild/mercutio/lib/mercutiofont.c"
Should only need 
```suggestion
#define OLED_FONT_H "lib/mercutiofont.c"
```

2021-05-22 14:36 UTC, Jonavin reviewed
Suggested changes applied

2021-05-22 14:36 UTC, Jonavin commented on keyboards/keebio/quefrency/keymaps/jonavin/README.md
> +# Jonathan's Quefrency layout - No Macros 65%
Done

2021-05-22 17:28 UTC, drashna approved these changes

2021-05-22 23:49 UTC, fauxpark approved these changes

2021-05-27 04:06 UTC, drashna commented
Thanks!

2021-05-27 04:06 UTC, merged