Add Vicious40 to QMK
qmk/qmk_firmware pull request #12981
Opened 2021-05-22 17:49 UTC by awkannan

## Description

Adding the Vicious40 PCB to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-27 04:19 UTC, drashna approved these changes

2021-05-27 04:23 UTC, fauxpark requested changes

2021-05-27 04:23 UTC, fauxpark commented on keyboards/cannonkeys/vicious40/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
```suggestion
# Wildcard to allow APM32 MCU
DFU_SUFFIX_ARGS = -p FFFF -v FFFF

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = yes      # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output

# Enter lower-power sleep mode when on the ChibiOS idle thread
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```

2021-05-27 04:23 UTC, fauxpark commented on keyboards/cannonkeys/vicious40/readme.md
> +Hardware Supported: STM32F072CBT6 or APM32F072CBT6
```suggestion
* Keyboard Maintainer: [Andrew Kannan](https://github.com/awkannan)
* Hardware Supported: STM32F072CBT6 or APM32F072CBT6
```

2021-06-02 04:56 UTC, fauxpark requested changes

2021-06-02 04:56 UTC, fauxpark commented on keyboards/cannonkeys/vicious40/keymaps/via/rules.mk
> +
```suggestion
VIA_ENABLE = yes
```

2021-06-29 01:13 UTC, awkannan commented
Should be all set for another look!

2021-06-29 01:21 UTC, fauxpark requested changes

2021-06-29 01:21 UTC, fauxpark commented on keyboards/cannonkeys/vicious40/rules.mk
> +# Wildcard to allow APM32 MCU
```suggestion
# Bootloader selection
BOOTLOADER = stm32-dfu

# Wildcard to allow APM32 MCU
```

2021-07-08 03:01 UTC, fauxpark requested changes
Whoops, one more thing then looks good to go.

2021-07-08 03:01 UTC, fauxpark commented on keyboards/cannonkeys/vicious40/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_default": {
```

2021-07-14 03:17 UTC, fauxpark approved these changes

2021-07-20 16:19 UTC, drashna commented
Thanks!

2021-07-20 16:19 UTC, merged