adding keymap for pistachio
qmk/qmk_firmware pull request #12996
Opened 2021-05-25 01:12 UTC by 7-rate

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-27 04:43 UTC, drashna requested changes

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/rate/keymap.c
> +extern rgblight_config_t rgblight_config;
```suggestion
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/rate/keymap.c
> +int RGB_current_mode;
```suggestion
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/rate/keymap.c
> +            RGB_current_mode = rgblight_config.mode;
```suggestion
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/rate/keymap.c
> +  bool result = false;
```suggestion
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/rate/keymap.c
> +      break;
```suggestion
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/rate/keymap.c
> +  return result;
```suggestion
  return true;
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/via/keymap.c
> +extern rgblight_config_t rgblight_config;
```suggestion
```

2021-05-27 04:43 UTC, drashna commented on keyboards/pistachio/keymaps/via/keymap.c
> +}
```suggestion
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case RGB_RST:
            if (record->event.pressed) {
                eeconfig_update_rgblight_default();
                rgblight_enable();
            }
            break;
    }

    return true;
}
```

2021-05-27 06:09 UTC, 7-rate commented
Thanks for the review.
I have responded to your suggestion.

2021-05-27 17:33 UTC, drashna approved these changes

2021-06-09 12:52 UTC, 7-rate commented
What else can I do to merge?

2021-06-16 04:31 UTC, drashna approved these changes

2021-06-16 04:32 UTC, drashna commented
> What else can I do to merge?

It can take a while for us to get to PRs, as we do this in our free time.  

And generally, we want two approved reviews before a PR gets merged.

2021-06-16 04:35 UTC, fauxpark approved these changes

2021-06-19 00:54 UTC, merged