WIP: Support for the IS31FL3236 LED Driver as an RGB Matrix Driver
qmk/qmk_firmware pull request #12998
Opened 2021-05-25 02:12 UTC by Electro707

## Description

Adding support for the IS31FL3236 LED driver as an RGB matrix driver.

Tested with a prototype keyboard if mine with the IS31FL3236A IC (backwards compatible with the IS31FL3236 IC with the exception of a selectable PWM frequency which isn't used in this driver yet (See TODO)).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [?] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [See TODO] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

## TODO:
- [] The IC supports adjustable current (from IMAX to IMAX/4). As of right now the driver drives the LEDs at IMAX. 
  -  Should we have a callable function to allow that to be changed, or is unnecessary at the moment (would be trivial to add)
- [] As IS31FL3236 and the IS31FL3236A are similar, should I add another define for the A version but have it use the same driver (and perhaps add the adjustable PWM for the A version as a callable function only when the A version is used)
- [] __BUG__: On my device, after 10-20 minutes the LED driver shuts down (so all LEDs turns off) and no LED binded key-press awakes it (but the keyboard still works). Unsure if that's a QMK shutdown feature or a bug in the driver. Need to investigate further.

2021-06-18 02:03 UTC, drashna approved these changes

2021-06-18 03:09 UTC, fauxpark requested changes

2021-06-18 03:09 UTC, fauxpark commented on common_features.mk
> +
Move this before the 3731 stanza.

2021-06-18 03:09 UTC, fauxpark commented on docs/feature_rgb_matrix.md
> +# IS31FL3236 :id=is31fl3236
As above.

2021-06-18 03:09 UTC, fauxpark commented on quantum/rgb_matrix.h
> +#elif defined(IS31FL3236)
etc.

2021-06-21 00:28 UTC, Electro707 commented on common_features.mk
> +
Should be moved by recent commit

2021-06-21 00:28 UTC, Electro707 commented on docs/feature_rgb_matrix.md
> +# IS31FL3236 :id=is31fl3236
Same as above

2021-06-21 00:28 UTC, Electro707 commented on quantum/rgb_matrix.h
> +#elif defined(IS31FL3236)
Same as above^2

2022-05-28 05:13 UTC, Electro707 commented
This PR should be ready to merge, all of the review's comments have been addressed last time I checked.

2022-06-18 23:14 UTC, Electro707 commented
@drashna @fauxpark Do you want to re-open this PR? I know it's been a while, but I do eventually want to merge this.
I will look into re-basing master on this branch to see if there are any new changes to the LED drive that this PR conflicts with since this PR was created.

2022-06-18 23:38 UTC, tzarc commented
> I will look into re-basing master on this branch 
Just an FYI, core changes need to go to `develop`, not `master`.

2022-06-19 04:11 UTC, Electro707 commented
Thanks for also changing this PR's merging branch. I think the develop branch is something relatively new, at least since I originally created this PR.

2022-06-19 05:43 UTC, Electro707 commented
Fixed some issues that occurred when re-basing. Tested with my keypad.
Fixed docs and added the `g_is31_leds` LED definition instead of amusing a sequential connection.
This PR should be all set, at least from my end

2022-06-19 18:21 UTC, drashna requested changes
Lint no happy.

2022-06-19 18:21 UTC, drashna commented on drivers/led/issi/is31fl3236.c
> +    g_pwm_buffer_update_required = true;
```suggestion
    g_pwm_buffer[led.r]          = red;
    g_pwm_buffer[led.g]          = green;
    g_pwm_buffer[led.b]          = blue;
    g_pwm_buffer_update_required = true;
```

2022-06-19 18:21 UTC, drashna commented on drivers/led/issi/is31fl3236.c
> +    g_led_control_update_required = true;
```suggestion
    g_led_control_update_required  = true;
```

2022-06-19 18:29 UTC, Electro707 commented on drivers/led/issi/is31fl3236.c
> +    g_pwm_buffer_update_required = true;
Should be fixed in 133d473

2022-06-19 18:29 UTC, Electro707 commented on drivers/led/issi/is31fl3236.c
> +    g_led_control_update_required = true;
Should be fixed in 133d473

2022-06-19 21:31 UTC, drashna approved these changes

2022-09-03 02:17 UTC, closed without merging

2022-10-17 02:02 UTC, Electro707 commented
@drashna @fauxpark Another request to re-open this PR to merge it, as the review request didn't happen last time