Murphpad Changes and Updates
qmk/qmk_firmware pull request #12995
Opened 2021-05-24 07:57 UTC by kylemccreery

## Description

Adding in second encoder, updating readme device versioning, and changing default and via keymaps to support other layout options more readily by default.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-27 04:41 UTC, drashna requested changes

2021-05-27 04:41 UTC, drashna commented on keyboards/mechwild/murphpad/keymaps/default/keymap.c
> +		static const char PROGMEM logo_2[] = {0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0x00};
```suggestion
```

2021-06-07 05:43 UTC, drashna commented
You have some merge conflicts that need to be resolved here.

2021-06-07 20:39 UTC, kylemccreery commented
> You have some merge conflicts that need to be resolved here.

Should be good now @drashna

2021-06-16 04:32 UTC, drashna approved these changes

2021-06-16 04:36 UTC, fauxpark approved these changes

2021-06-19 00:48 UTC, merged