World domination
qmk/qmk_firmware pull request #13021
Opened 2021-05-27 21:04 UTC by Erovia

## Description

Title :point_up_2: 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-27 22:57 UTC, tzarc requested changes

2021-05-27 22:57 UTC, tzarc commented on lib/python/qmk/cli/bux.py
> +    print(f"{buck}\nYou've been blessed with by the QMK gods!\nYou {cli.config.user.bux} QMK bux.")
```suggestion
    print(f"{buck}\nYou've been blessed with by the QMK gods!\nYou have {cli.config.user.bux} QMK bux.")
```

2021-05-28 16:12 UTC, fauxpark requested changes

2021-05-28 16:12 UTC, fauxpark commented on lib/python/qmk/cli/bux.py
> +@cli.subcommand('QMK Hello World.', hidden=True)
```suggestion
@cli.subcommand('QMK Bux miner.', hidden=True)
```

2021-05-28 22:26 UTC, tzarc approved these changes

2021-05-29 01:13 UTC, fauxpark approved these changes

2021-05-29 19:05 UTC, merged

2021-05-30 22:10 UTC, controlxcv commented
I did not expect this.  When moon?