Iris Rev 4 - modifier thumb cluster and dual encoder support
qmk/qmk_firmware pull request #13033
Opened 2021-05-29 17:51 UTC by compilation-error

## Description
Keebio Iris rev4 layout. The modifiers are set up in the thumb clusters. Supports dual encoders - one for volume and one for scrolling. Mouse support is enabled on layer 1 along with keypad. Layer 2 is mostly default with reset and EEPROM reset moved to thumb cluster.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-30 21:41 UTC, drashna requested changes

2021-05-30 21:41 UTC, drashna commented on keyboards/keebio/iris/keymaps/compilation-error/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-30 21:41 UTC, drashna commented on keyboards/keebio/iris/keymaps/compilation-error/keymap.c
> +#define _ADJUST 3
```suggestion
enum custom_layers {
    _QWERTY,
    _LOWER,
    _RAISE,
    _ADJUST,
};
```

2021-05-30 21:41 UTC, drashna commented on keyboards/keebio/iris/keymaps/compilation-error/keymap.c
> +}
```suggestion
bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) {
        if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
    }
    else if (index == 1) {
        if (clockwise) {
            tap_code(KC_WH_D);
        } else {
            tap_code(KC_WH_U);
        }
    }
    return true;
}
```

2021-05-30 21:41 UTC, drashna commented on keyboards/keebio/iris/keymaps/compilation-error/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-06-01 04:17 UTC, compilation-error commented
thank you for your review and suggested updates. I will incorporate them and create a new PR - this layout has some deficiencies.

2021-06-01 04:17 UTC, closed without merging