Implement OpenRGB protctol for RGB Matrix keyboards #10961
qmk/qmk_firmware pull request #13036
Opened 2021-05-29 23:16 UTC by Kasper24

This is a major improvement over #10961 - the matrix in OpenRGB is now using the points array to build the matrix, which makes adding more keyboard as easy as OPENRGB_ENABLE = YES in the rules file.

2021-05-30 21:34 UTC, drashna requested changes

2021-05-30 21:34 UTC, drashna commented on common_features.mk
> +endif
```suggestion
ifeq ($(strip $(OPENRGB_ENABLE)), yes)
     ifeq ($(strip $(VIA_ENABLE)), yes)
        $(error OPENRGB_ENABLE and VIA_ENABLE cannot currently be enabled simultaneously)
    endif
    RAW_ENABLE := yes
    SRC += $(QUANTUM_DIR)/openrgb.c
    OPT_DEFS += -DOPENRGB_ENABLE
endif
```

2021-05-30 21:34 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/openrgb/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-30 21:34 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/openrgb/keymap.c
> +#define _LAYER1 1
```suggestion
enum custom_layer {
    _LAYER0,
    _LAYER1,
};
```

2021-05-30 21:34 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/openrgb/keymap.c
> +}
```suggestion
```

2021-05-30 21:34 UTC, drashna commented on keyboards/massdrop/alt/keymaps/openrgb/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-30 21:34 UTC, drashna commented on keyboards/massdrop/ctrl/keymaps/openrgb/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-05-30 21:34 UTC, drashna commented on keyboards/massdrop/ctrl/keymaps/openrgb/keymap.c
> +};
```suggestion
```

2021-05-30 21:34 UTC, drashna commented on quantum/rgb_matrix_animations/rgb_matrix_effects.inc
> +#include "rgb_matrix_animations/openrgb_direct_anim.h"
Would prefer that this was at the end of the list, so it doesn't screw up the mode eeprom setting. 

Instead, could set the default mode to the openRGB mode, if the feature is enabled.

2021-05-30 21:34 UTC, drashna commented on tmk_core/protocol/usb_descriptor.h
> +#define RAW_EPSIZE 64
IIRC, this may cause issues.

2021-06-12 15:36 UTC, Kasper24 commented on tmk_core/protocol/usb_descriptor.h
> +#define RAW_EPSIZE 64
Issues with VIA?

2021-06-12 15:37 UTC, Kasper24 commented
@drashna Updated the PR with the changes you asked for. Is this something you guys will be more willing to merge?

2021-07-12 19:11 UTC, tzarc commented
At this stage I think I'm okay with the changes as they stand, apart from the question about `RAW_EPSIZE`. I'm inclined to leave it at 32, mainly because going forward I'd expect that XAP (#11567) would end up being used instead of raw hid.

@Kasper24 -- coming from the perspective of using this PR as heavy inspiration for the lighting side of things with XAP, was the implementaton of "zones" something that was inherently useful for UI-side configurability? Wondering if we need to extend the rgb_matrix definitions "properly" beforehand, allowing for zone naming and assignment of LEDs to specific zones. Thoughts?

2021-07-12 21:29 UTC, CalcProgrammer1 commented
32 bytes per packet would be rather limiting.  The frame rate of effects run from the host is dependent on how many color values we can pack into one USB message.  Right now we can pack 20 colors into one 64-byte packet which allows for smooth animations at 60fps as long as the RGB Matrix layer can keep up.  I would expect 32 bytes (10 colors, and that's if we only use 2 bytes of overhead) would be significantly slower.

2021-07-13 00:06 UTC, tzarc commented
Then in this case you're going to have to only bump it to 64 when OpenRGB is enabled. Not using OpenRGB shouldn't inadvertently break other people using raw hid, on the off chance that they're reliant on it being 32 bytes long.

2021-07-22 01:45 UTC, Kasper24 commented
@tzarc > coming from the perspective of using this PR as heavy inspiration for the lighting side of things with XAP, was the implementaton of "zones" something that was inherently useful for UI-side configurability? Wondering if we need to extend the rgb_matrix definitions "properly" beforehand, allowing for zone naming and assignment of LEDs to specific zones. Thoughts?

1. In the updated version, we tried to use the already available info as much as possible. We used the led_flags array to determine how many zones the keyboard has. If we found 1 or more LEDs flagged as underglow, it means (or should) that keyboard has 2 zones - 1 for key LEDs, 1 for underglow LEDs. We then automitcally name it "Keyboard" and "Underglow" respectively. The issue is maybe some keyboards should have more than 2 zones? since the options with QMK are endless, this method might not always be correct for less tradiontal keyboards. The reason we changed it to work this way compared to #10961 is that we couldn't manually configure every QMK keyboard, so it was a trade-off of sorts. 

2. OpenRGB and QMK are using 2 different grid systems. That's why in #10961 I had to add the OPENRGB_MATRIX_MAP macro. If you look here, @jath03 added all the functioniallity needed to convert the grid QMK uses to something OpenRGB can use, again to reduce manual configuration. While the QMK method is superiror, other apps might still be doing something closer to what OpenRGB is doing to layout a matrix. 

3. Another issue we had was getting the names from QMK, since the keymap array also contains the "empty' cellls it wasn't as staright-forward. Maybe implenent a method to easily retrive those?

4. Limiting the endpoint size to 32 will be very limiting for RGB animations controllred from the host. If the goal is to eventually replace VIA, why not bump it to highest value possible?

2021-07-31 01:25 UTC, tzarc commented
@Kasper24

1. Understood, I was asking whether or not you believe it's useful if the RGB matrix definitions were amended for XAP-enabled firmwares, to allow for explicit assignment of things like zones if it helps host applications with UX in general. This obviously would also need the ability to define zone names, as well as being able to query them from the XAP endpoint. It sounds like it would be useful from the perspective of removing ambiguity?
2. Assuming a "clean slate" -- what would your recommendation be in this area? We're currently moving towards a data-driven approach for keyboard definitions, so build-time codegen for things like mappings is absolutely achievable, so long as enough information is present in the `info.json` file. Alternatively, the next point.....
3. Yes, that would be the intent. At this stage we're looking at embedding a compressed copy of a cut-down version of the `info.json`. I'm pushing for "layout configurations" where you can swap sections based on user selection -- (ansi or iso enter) for example, with the embedded json containing both physical positions as well as equivalent matrix positions. I'm uncertain if we'd be best suited to use a different mechanism, but it's early stages at this point.

Also, XAP has its own endpoint, and is 64 bytes in length. There is some preamble required to correlate messages with their responses, and at this point the maximum data size is 60 bytes.

2022-02-04 21:29 UTC, lbibass commented
Any updates on getting this pulled in? Seems it’s just waiting on a review?

2022-02-04 22:31 UTC, CorePoint commented
@lbibass 
I'm pretty sure this will never get merged in favor of XAP.
The protocol could then be used by OpenRGB to communicate with your device.
But there is [this fork](https://github.com/Kasper24/QMK-OpenRGB) you could play around with until then.

2025-10-31 17:58 UTC, cybik commented
Is this PR dead?

2026-07-06 20:16 UTC, drashna commented
Closing this, as this is now available as a community module.
https://gitlab.com/OpenRGBDevelopers/QMK-OpenRGB

2026-07-06 20:16 UTC, closed without merging