Adding VIA
qmk/qmk_firmware pull request #13031
Opened 2021-05-29 11:28 UTC by alittlepeace

Adding VIA

## Description
Adding via in keymap, and enabling mouse keys for scrolling with encoder

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-30 21:42 UTC, drashna requested changes

2021-05-30 21:42 UTC, drashna commented on keyboards/absinthe/keymaps/via/keymap.c
> +}
```suggestion
bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) { /* First encoder */
          switch(get_highest_layer(layer_state)){
            case 1:
                if (clockwise){
                    tap_code(KC_VOLU);
                } else{
                    tap_code(KC_VOLD);
                }
                break;
            default:
                if (clockwise) {
                    tap_code(KC_WH_D);
                } else {
                    tap_code(KC_WH_U);
                }
                break;
        }
    }
    return true;
}

```

2021-05-30 21:59 UTC, drashna approved these changes

2021-08-12 18:39 UTC, fauxpark approved these changes

2021-08-13 19:35 UTC, drashna commented
Thanks!

2021-08-13 19:35 UTC, merged