adding my keymap "vayashiko"
qmk/qmk_firmware pull request #13049
Opened 2021-05-30 19:57 UTC by kryuki

## Description

Add new keymap named "vayashiko."
This keymap is made for those who type Japanese.
This keymap contains KC_MHEN and KC_HENK to switch between Japanese and English, which makes typing very fast for you.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-30 21:17 UTC, drashna requested changes

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/config.h
> +#define SSD1306OLED
```suggestion
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/config.h
> +#define USE_SERIAL_PD2
```suggestion
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/config.h
> +#define RGBLED_NUM 27
only 27?

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +extern uint8_t is_master;
```suggestion
#include "keymap_jp.h"
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +#define _ADJUST 3
```suggestion
enum custom_layers {
    _QWERTY,
    _LOWER,
    _RAISE,
    _ADJUST,
};
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +enum macro_keycodes {
```suggestion
  RGBRST,
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +#define KC_ALTKN ALT_T(KC_LANG1)
```suggestion
#define KC_CTLTB CTL_T(KC_TAB)
#define KC_GUIEI GUI_T(KC_LANG2)
#define KC_ALTKN ALT_T(KC_LANG1)
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +}
```suggestion
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +}
```suggestion
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +#ifdef SSD1306OLED
the `SSD1306OLED` code has been deprecated, and the "OLED Driver" feature should be used instead. 

You can take a look at the default keymap for updates, or use the conversion guide:
https://docs.qmk.fm/#/feature_oled_driver?id=ssd1306h-driver-conversion-guide

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +        persistent_default_layer_set(1UL<<_QWERTY);
```suggestion
        set_single_persistent_default_layer(_QWERTY);
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +        persistent_default_layer_set(1UL<<_QWERTY);
Also, this can be removed since you only have the qwerty layer.

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +          RGB_current_mode = rgblight_config.mode;
```suggestion
```

2021-05-30 21:17 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +      break;
```suggestion
```

2021-05-30 23:01 UTC, kryuki commented on keyboards/crkbd/keymaps/vayashiko/config.h
> +#define RGBLED_NUM 27
Changed to 42. Thank you.

2021-05-30 23:01 UTC, kryuki commented on keyboards/crkbd/keymaps/vayashiko/config.h
> +#define USE_SERIAL_PD2
Changed. Thank you.

2021-05-30 23:01 UTC, kryuki commented on keyboards/crkbd/keymaps/vayashiko/config.h
> +#define SSD1306OLED
Changed. Thank you.

2021-05-31 03:47 UTC, drashna commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +#include "keymap.h"
This shouldn't be needed. 
```suggestion
```

2021-05-31 03:53 UTC, kryuki commented on keyboards/crkbd/keymaps/vayashiko/keymap.c
> +#include "keymap.h"
removed this. Thank you.

2021-06-01 03:41 UTC, drashna approved these changes

2021-08-10 04:06 UTC, noroadsleft approved these changes

2021-08-10 04:07 UTC, merged

2021-08-10 04:07 UTC, noroadsleft commented
Thanks!