added 0xCB Static
qmk/qmk_firmware pull request #13047
Opened 2021-05-30 13:25 UTC by Conor-Burns

## Description

Added the TH board 0xCB static with a default keymap and a keymap with via support enabled

The is a 40% with an OLED and an encoder -> [hardware](https://github.com/0xCB-dev/0xcb-static)
Also thank you @drashna for all the help with the OLED code!

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Issues Fixed or Closed by This PR

*  No Issues

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-30 21:19 UTC, drashna approved these changes

2021-05-31 03:11 UTC, fauxpark requested changes

2021-05-31 03:11 UTC, fauxpark commented on keyboards/0xcb/static/rules.mk
> +MOUSEKEY_ENABLE = yes 	    # Mouse keys
```suggestion
MOUSEKEY_ENABLE = yes       # Mouse keys
```

2021-05-31 03:11 UTC, fauxpark commented on keyboards/0xcb/static/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```

2021-05-31 21:10 UTC, Conor-Burns commented
Yeah, Travis keeps failing but I don't think thats my fault :D

2021-06-05 04:24 UTC, fauxpark approved these changes

2021-06-14 09:03 UTC, fauxpark requested changes
.

2021-06-16 04:58 UTC, drashna requested changes

2021-06-16 04:58 UTC, drashna commented on keyboards/0xcb/1337/1337.c
> +    #ifdef RGBLIGHT_ANIMATIONS
```suggestion
#    ifdef RGBLIGHT_ANIMATIONS
```

2021-06-16 04:58 UTC, drashna commented on keyboards/0xcb/1337/1337.c
> +// clang-format on
```suggestion
#    endif
```

2021-06-16 04:58 UTC, drashna commented on keyboards/0xcb/1337/config.h
> +// clang-format off
```suggestion
```

2021-06-16 04:58 UTC, drashna commented on keyboards/0xcb/1337/config.h
> +// clang-format on
```suggestion

```

2021-06-16 04:58 UTC, drashna commented on keyboards/0xcb/static/keymaps/via/keymap.c
> +uint32_t layer_state_set_user(uint32_t state) {
Also, via has keycodes to handles this, actually. 
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
```

Specifically `FN_MO13` and `FN_MO23`

2021-06-16 04:58 UTC, drashna commented on keyboards/0xcb/static/keymaps/default/keymap.c
> +uint32_t layer_state_set_user(uint32_t state) {
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
```

2021-06-19 01:10 UTC, drashna approved these changes

2021-06-28 17:18 UTC, fauxpark requested changes

2021-06-28 17:18 UTC, fauxpark commented on keyboards/0xcb/static/readme.md
> +    make 0xcb/1337:static:flash
```suggestion
    make 0xcb/static:flash
```

2021-06-28 17:19 UTC, fauxpark approved these changes

2021-07-02 18:38 UTC, Erovia approved these changes

2021-07-02 18:38 UTC, merged

2021-07-02 18:39 UTC, Conor-Burns commented
@Erovia thanks, mate!