Add Alico48
qmk/qmk_firmware pull request #13051
Opened 2021-05-31 05:02 UTC by marby3

I'll add the keyboard I made.
I made a keyboard that uses three TRRS cables.
It uses only one ProMicro.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-11 03:16 UTC, drashna requested changes

2021-09-11 03:16 UTC, drashna commented on keyboards/alico48/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-09-11 03:16 UTC, drashna commented on keyboards/alico48/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-11 03:16 UTC, drashna commented on keyboards/alico48/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
# Bootloader selection
BOOTLOADER = caterina

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = yes      # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-09-11 03:30 UTC, fauxpark requested changes

2021-09-11 03:30 UTC, fauxpark commented on keyboards/alico48/readme.md
> +    make alico48:default:avrdude
```suggestion
    make alico48:default:flash
```

2021-09-11 03:30 UTC, fauxpark commented on keyboards/alico48/info.json
> +{
This file is incorrect:
![image](https://user-images.githubusercontent.com/4781841/132934832-6fbdae68-306f-47ff-8e98-457067362e4a.png)

2021-09-14 08:04 UTC, marby3 commented
I'm not very good with Github, were the changes appropriate?

2021-09-14 08:44 UTC, fauxpark requested changes

2021-09-14 08:44 UTC, fauxpark commented on keyboards/alico48/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-14 08:44 UTC, fauxpark commented on keyboards/alico48/info.json
> +    "height": 11,
```suggestion
```

2021-09-14 08:44 UTC, fauxpark commented on keyboards/alico48/readme.md
> +![alico48](imgur.com image replace me!)
Please fill this out.

2021-09-14 08:44 UTC, fauxpark commented on keyboards/alico48/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*l
As above.

2021-09-14 08:44 UTC, fauxpark commented on keyboards/alico48/info.json
> +{
Still not correct. Please use the Configurator to check the positioning and ordering of the info.json layout matches the LAYOUT macro, by pressing Ctrl+Shift+I and turning on Fast Input. When you generate the info.json, don't use rotation either.

2022-01-09 02:13 UTC, closed without merging