core: allow setting USB version in descriptor to 2.00 from config.h
qmk/qmk_firmware pull request #13078
Opened 2021-06-02 07:31 UTC by stapelberg

## Description

The Teensy 4.x comes with USB 2.0 support. This change is required to make the device advertise itself as USB 2.0 in the USB device descriptor.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-03 14:15 UTC, drashna reviewed
n

2021-06-03 14:18 UTC, drashna commented on tmk_core/protocol/usb_descriptor.c
> +    .USBSpecification           = USB_VERSION,
I'd almost prefer:
```suggestion
#if defined(USB_VERSION_2)
    .USBSpecification           = VERSION_BCD(2, 1, 0),
```

2021-06-05 08:01 UTC, stapelberg commented on tmk_core/protocol/usb_descriptor.c
> +    .USBSpecification           = USB_VERSION,
Done

2021-06-05 14:44 UTC, drashna approved these changes

2021-06-05 14:55 UTC, drashna commented
Honestly, I'm not exactly happy with the name for the define, but ... I suck at naming. 

Also, could this be documented in: https://github.com/qmk/qmk_firmware/blob/master/docs/config_options.md

2021-06-05 15:12 UTC, stapelberg commented
Sure. Updated the docs.

2021-06-05 16:54 UTC, fauxpark reviewed
I'm kinda wondering if this even needs a define - all of the MCUs these descriptors currently cover seem to comply with USB 2.0 FS. My previous assumption was this value had to be 1.1 because a USB 2.0 device must also provide a device qualifier descriptor, but I'm now thinking that's only if it is capable of running at high speed *and* full speed:

https://www.keil.com/pack/doc/mw/USB/html/_u_s_b__device__qualifier__descriptor.html
> A high-speed capable device that has different device information for full-speed and high-speed must have a Device Qualifier Descriptor (USB_DEVICE_QUALIFIER_DESCRIPTOR). For example, if the device is currently operating at full-speed, the Device Qualifier returns information about how it would operate at high-speed and vice-versa.

What happens if you define this for, say, an ATmega32U4? If the Windows, macOS and Linux don't complain, I'd say just change it...

2021-06-05 16:58 UTC, stapelberg commented
> What happens if you define this for, say, an ATmega32U4

Unfortunately, I don’t have an ATmega32U4 handy. Could you test it, or should we file an issue and address that separately from this change at a later point?

2021-06-05 17:35 UTC, fauxpark commented
Just tried on my Satan, it (and/or Windows) didn't like `2, 1, 0` but `2, 0, 0` seems to work fine.
![image](https://user-images.githubusercontent.com/4781841/120900454-373c3580-c678-11eb-93e7-103d0a1959e5.png)

2021-06-05 17:59 UTC, stapelberg commented
> Some Googling around suggests that 2.10 is not a "real" value, and is what is reported when a USB 3 device is plugged into a USB 2 port. So, that may explain why Windows was confused.

Ah, yeah, https://community.osr.com/discussion/249588/where-is-the-usb-2-1-specification seems to confirm.

Changed it to `2, 0, 0`.

2021-06-05 18:07 UTC, fauxpark requested changes

2021-06-05 18:07 UTC, fauxpark commented on tmk_core/protocol/usb_descriptor.c
> +#endif
```suggestion
    .USBSpecification           = VERSION_BCD(2, 0, 0),
```

2021-06-05 18:07 UTC, fauxpark commented on docs/config_options.md
> +  * set the USB device descriptor to USB version 2.
```suggestion
```

2021-06-05 18:34 UTC, stapelberg commented
Done

2021-06-05 18:37 UTC, fauxpark approved these changes

2021-06-06 22:48 UTC, merged