Add Gvalchca GA15.0
qmk/qmk_firmware pull request #13114
Opened 2021-06-05 13:20 UTC by Gvalch-ca

## Description

Add Gvalch'ca GA15.0 PCB to QMK. This PCB is an Alps standard 60% with flex cutouts and some weird layout support. I have ran 2 groupbuys of GA15.0 on keebmeup.com discord server, and now running the 3rd, preparing of open GB. 
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Added new keyboard - GA15.0 by Gvalch'ca

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-07 06:54 UTC, drashna requested changes

2021-06-07 06:54 UTC, drashna commented on keyboards/gvalchca/ga150/rules.mk
> +LAYOUTS = all
There is no "all" layout.

```suggestion
```

2021-06-07 17:38 UTC, Gvalch-ca commented on keyboards/gvalchca/ga150/rules.mk
> +LAYOUTS = all
Deleted that.

2021-06-12 11:31 UTC, Gvalch-ca commented on keyboards/gvalchca/ga150/readme.md
> +Make example for this keyboard (after setting up your build environment):
Line 3 says 'press Reset button'. Hardware reset button.

2021-06-16 05:13 UTC, drashna approved these changes

2021-06-20 01:23 UTC, fauxpark requested changes

2021-06-20 01:23 UTC, fauxpark commented on keyboards/gvalchca/ga150/keymaps/default/keymap.c
> +  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          \
```suggestion
  KC_ESC,  KC_1,    KC_2,   KC_3,   KC_4,   KC_5,   KC_6,   KC_7,   KC_8,   KC_9,    KC_0,    KC_MINS, KC_EQL,   KC_BSLS, KC_BSPC,
  KC_TAB,  KC_Q,    KC_W,   KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,   KC_O,    KC_P,    KC_LBRC, KC_RBRC,  KC_BSLS,
  KC_CAPS, KC_A,    KC_S,   KC_D,   KC_F,   KC_G,   KC_H,   KC_J,   KC_K,   KC_L,    KC_SCLN, KC_QUOT, KC_BSLS,  KC_ENT,
  KC_LSFT, KC_NUBS, KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,   KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,  KC_RSFT,
  KC_LCTL, KC_LGUI, KC_LALT,                        KC_SPC,                          KC_RALT, KC_RGUI, KC_RCTRL, KC_RCTRL),

[_FUNC] = LAYOUT(
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2021-06-20 01:23 UTC, fauxpark commented on keyboards/gvalchca/ga150/readme.md
> +![GA15.0 image](https://i.imgur.com/Z7tNlGD.jpeg)
```suggestion

![GA15.0 image](https://i.imgur.com/Z7tNlGDh.jpeg)
```

2021-06-20 01:23 UTC, fauxpark commented on keyboards/gvalchca/ga150/readme.md
> +* Keyboard Maintainer: [Gvalchca](https://github.com/Gvalch-ca)
```suggestion
* Keyboard Maintainer: [Gvalchca](https://github.com/Gvalch-ca)
```

2021-06-20 11:24 UTC, fauxpark approved these changes

2021-06-26 04:12 UTC, drashna commented
Thanks!

2021-06-26 04:12 UTC, merged

2021-07-16 15:53 UTC, mfkiiyd commented
sorry, copy err