Bop added via & unicode support
qmk/qmk_firmware pull request #13122
Opened 2021-06-06 20:46 UTC by NathanBlais

## Description

For the BOP board I added a VIA layout and added support for basic Unicode to that layout

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-07 07:35 UTC, drashna requested changes

2021-06-07 07:35 UTC, drashna commented on keyboards/bop/keymaps/via/rules.mk
> +  */
```suggestion
```

2021-06-07 07:35 UTC, drashna commented on keyboards/bop/keymaps/via/rules.mk
> +UNICODE_ENABLE = yes
VIA doesn't support unicode, as far as I'm aware.  So no real point of having it enabled here. 

```suggestion
```

2021-06-07 20:22 UTC, NathanBlais commented
Thanks for the feedback, changes made

2021-06-07 21:00 UTC, drashna approved these changes

2021-06-16 01:39 UTC, blewis308 commented
Bumping for one more approval

2021-06-16 04:48 UTC, fauxpark requested changes

2021-06-16 04:48 UTC, fauxpark commented on keyboards/bop/keymaps/via/keymap.c
> +        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
```suggestion
		KC_F1, 	 KC_F5,   KC_F9,   KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_UNDS, KC_PLUS, KC_DEL,  KC_LCBR, KC_RCBR, KC_PIPE,
		KC_F2, 	 KC_F6,   KC_F10,  KC_ESC,  KC_1, 	 KC_2,    KC_3,    KC_4,   KC_5, 	KC_6, 	 KC_7,    KC_8,    KC_9, 	KC_0, 	 KC_PMNS, KC_PEQL, KC_BSPC, KC_HOME, KC_END,  KC_PGUP,
		KC_F3,   KC_F7,   KC_F11,  KC_TAB,  KC_Q, 	 KC_W,    KC_E,    KC_R,   KC_T, 	KC_Y, 	 KC_U,    KC_I,    KC_O, 	KC_P, 	 KC_LBRC, KC_RBRC, KC_BSLS, KC_COLN, KC_DQUO, KC_PGDN,
		KC_F4,   KC_F8,   KC_F12,  KC_CAPS, KC_A, 	 KC_S,    KC_D,    KC_F,   KC_G, 	KC_H, 	 KC_J,    KC_K,    KC_L, 	KC_SCLN, KC_QUOT, KC_ENT,  KC_KP_0, KC_KP_7, KC_KP_8, KC_KP_9,
		KC_PSCR, KC_SLCK, KC_PAUS, KC_LSFT, KC_Z, 	 KC_X,    KC_C,    KC_V,   KC_B, 	KC_N, 	 KC_M,    KC_LABK, KC_RABK, KC_QUES, KC_RSFT, KC_UP,   KC_KP_0, KC_KP_4, KC_KP_5, KC_KP_6,
        KC_CUT,  KC_COPY, KC_PSTE, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,  KC_SPC, MO(1) ,  KC_SPC,  KC_SPC,  KC_PCMM, KC_PDOT, KC_SLSH, KC_LEFT, KC_DOWN, KC_RGHT, KC_KP_1, KC_KP_2, KC_KP_3),
    
    [1] = LAYOUT(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    
    [2] = LAYOUT(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    
    [3] = LAYOUT(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
```

2021-06-17 14:32 UTC, NathanBlais commented
@fauxpark changes have been made

2021-06-24 03:57 UTC, blewis308 commented
@fauxpark any approval?

2021-06-24 04:18 UTC, fauxpark approved these changes

2021-06-24 15:29 UTC, NathanBlais commented
What do I need to do to get this merged?

2021-06-24 15:46 UTC, blewis308 commented
> What do I need to do to get this merged?

Click the Merge pull request below changes approved at the bottom

2021-06-24 15:53 UTC, NathanBlais commented
> > What do I need to do to get this merged?
> 
> Click the Merge pull request below changes approved at the bottom

I'm not authorized

2021-06-24 23:15 UTC, merged

2021-06-24 23:15 UTC, fauxpark commented
Thanks!