Top level heading for common config
qmk/qmk_firmware pull request #13120
Opened 2021-06-06 19:57 UTC by brianlow

Prior to this, the some of the common config looks like a detail of the APA102 driver

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-06 20:12 UTC, fauxpark requested changes

2021-06-06 20:12 UTC, fauxpark commented on docs/feature_rgb_matrix.md
> +## LED Matrix :id=matrix
```suggestion
## Common Configuration :id=common-configuration
```
And should be done for the LED Matrix docs as well.

2021-06-09 15:58 UTC, brianlow commented
@fauxpark updated, thanks! Updated LED Matrix in #13153 (I am using the github web editor so couldn't add to existing PR)

2021-06-16 05:06 UTC, drashna approved these changes

2021-06-16 05:07 UTC, merged