Fixes for Ploopy devices
qmk/qmk_firmware pull request #13144
Opened 2021-06-09 01:02 UTC by ploopyco

## Description

The DPI code for the Ploopy Nano and Mini was not functioning due to a bug with the ADNS serial write function, as well as with the ADNS initialization routine. This PR fixes both issues.

The backwards and forwards button on the Mini were reversed; this is fixed in this PR.

This PR also addresses the fact that some of the PCB revisions for the Mini and Classic are updated, so READMEs and directories have been changed to make this a bit more obvious.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-09 01:18 UTC, drashna commented
Could you separate out the adns fix from the folder moves? 

In general, folder moves require that he PR target the `develop` branch and go through the breaking changes process.  which means it wouldn't hit master for a few months. 

Alternative, I can see about pulling out the bug fixes and add them to #13043

2021-06-09 03:11 UTC, ploopyco commented
I'll pull the folder moves out.

2021-06-09 18:06 UTC, ploopyco commented
Fixed; no breaking changes are included anymore.

2021-06-15 03:03 UTC, drashna approved these changes

2021-06-18 04:19 UTC, fauxpark requested changes

2021-06-18 04:19 UTC, fauxpark commented on keyboards/ploopyco/trackball_mini/trackball_mini.c
>  void keyboard_post_init_kb(void) {
```suggestion
```

2021-06-18 04:19 UTC, fauxpark commented on keyboards/ploopyco/trackball_mini/trackball_mini.c
>  }
```suggestion
```

2021-06-18 04:19 UTC, fauxpark commented on keyboards/ploopyco/trackball_mini/trackball_mini.c
> +#include "print.h"
```suggestion
#include "debug.h"
```

2021-06-21 17:05 UTC, nooges approved these changes

2021-06-21 19:59 UTC, merged