Add my planck layout
qmk/qmk_firmware pull request #13143
Opened 2021-06-08 23:52 UTC by abhixec

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-17 03:08 UTC, drashna requested changes

2021-06-17 03:08 UTC, drashna commented on keyboards/planck/keymaps/abhixec/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-01 06:50 UTC, drashna commented on keyboards/planck/keymaps/abhixec/readme.md
> +# The Default Planck Layout
Probably should remove or update this

2021-07-01 06:50 UTC, drashna approved these changes

2021-08-22 03:33 UTC, fauxpark requested changes

2021-08-22 03:33 UTC, fauxpark commented on keyboards/planck/keymaps/abhixec/config.h
> +
```suggestion
```

2021-08-24 08:12 UTC, fauxpark approved these changes

2021-09-11 03:34 UTC, drashna requested changes

2021-09-11 03:34 UTC, drashna commented on keyboards/planck/keymaps/abhixec/keymap.c
> +void dip_switch_update_user(uint8_t index, bool active) {
```suggestion
bool dip_switch_update_user(uint8_t index, bool active) {
```

2021-09-11 03:34 UTC, drashna commented on keyboards/planck/keymaps/abhixec/keymap.c
> +}
```suggestion
    return true;
}
```

2022-03-08 04:01 UTC, drashna approved these changes

2022-04-19 10:32 UTC, tzarc approved these changes

2022-04-19 10:33 UTC, merged