added list of MIDI keycodes
qmk/qmk_firmware pull request #13159
Opened 2021-06-10 02:11 UTC by wxyangf

## Description

Added the list of MIDI keycodes already present in` feature_midi.md` to the full list of keycodes in` keycodes.md`

see issue: https://github.com/qmk/qmk_firmware/issues/9868

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-10 02:12 UTC, fauxpark requested changes
~~Again, should be in alphabetical order (between Leader and Mouse Keys).~~ Too late 😄

2021-06-10 02:14 UTC, wxyangf commented
Literally thought I pushed an alphabetized version as you wrote that, seems like github hasn't quite updated.

2021-06-10 02:14 UTC, fauxpark requested changes

2021-06-10 02:14 UTC, fauxpark commented on docs/keycodes.md
>  ## Mouse Keys :id=mouse-keys
```suggestion

## Mouse Keys :id=mouse-keys
```

2021-06-10 02:19 UTC, fauxpark approved these changes

2021-07-05 00:34 UTC, drashna approved these changes

2021-07-05 00:34 UTC, merged