Add Ready100 Keyboard
qmk/qmk_firmware pull request #13158
Opened 2021-06-10 02:02 UTC by mrnoisytiger

## Description

Add Ready100 Keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-17 03:24 UTC, drashna commented on keyboards/fjlabs/ready100/rules.mk
> +LAYOUTS = 64key
```suggestion
```

2021-06-17 04:34 UTC, drashna approved these changes

2021-06-22 15:16 UTC, mrnoisytiger commented
Bump. 😅

2021-06-26 04:32 UTC, drashna requested changes

2021-06-26 04:32 UTC, drashna commented on keyboards/fjlabs/ready100/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader?

2021-08-03 02:51 UTC, mrnoisytiger commented
Can I get review on this? Thanks!

2021-08-12 15:27 UTC, drashna approved these changes

2021-08-12 18:28 UTC, fauxpark approved these changes

2021-08-19 16:31 UTC, drashna commented
Thanks!

2021-08-19 16:31 UTC, merged