Added the Naja75 keyboard
qmk/qmk_firmware pull request #13167
Opened 2021-06-10 14:45 UTC by NightlyBoards

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-17 03:30 UTC, drashna requested changes

2021-06-17 03:30 UTC, drashna commented on keyboards/nightly_boards/naja75/keymaps/via/keymap.c
> +char wpm_str[8];
```suggestion
```

2021-06-26 04:27 UTC, drashna approved these changes

2021-08-12 18:27 UTC, fauxpark requested changes

2021-08-12 18:27 UTC, fauxpark commented on keyboards/nightly_boards/naja75/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-08-12 18:27 UTC, fauxpark commented on keyboards/nightly_boards/naja75/readme.md
> +![Naja](https://i.imgur.com/uM0hQ92.jpg)
```suggestion
![Naja](https://i.imgur.com/uM0hQ92h.jpg)
```

2022-01-09 02:13 UTC, closed without merging