[Keyboard] Updates ScrabblePad, try 2
qmk/qmk_firmware pull request #13177
Opened 2021-06-11 04:26 UTC by DonutCables

Basically a copy of #12894 , but I ruined that one when I did a reset yesterday without realizing that one from a month ago wasn't actually pushed.

Updates to ScrabblePad files to facilitate VIA compatibility including:    

- Cleanup of core files

- Addition of VIA keymap folder and files    

- Update to vendor and board info to align with VIA requirements

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-17 03:45 UTC, drashna approved these changes

2021-08-12 15:17 UTC, drashna approved these changes

2021-08-12 18:22 UTC, fauxpark requested changes

2021-08-12 18:22 UTC, fauxpark commented on keyboards/donutcables/scrabblepad/rules.mk
> +BACKLIGHT_ENABLE = no
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-08-12 18:22 UTC, fauxpark commented on keyboards/donutcables/scrabblepad/rules.mk
>  BOOTLOADER = halfkay
Remove the list above this line (I can't reach it).

2021-08-12 18:22 UTC, fauxpark commented on keyboards/donutcables/scrabblepad/keymaps/via/rules.mk
> +TERMINAL_ENABLE = no
```suggestion
```

2021-08-12 18:22 UTC, fauxpark commented on keyboards/donutcables/scrabblepad/keymaps/via/config.h
> +/*
This file can be deleted.

2021-08-12 18:22 UTC, fauxpark commented on keyboards/donutcables/scrabblepad/config.h
> +#define VENDOR_ID       0x4443
Please keep the comments in this file as per the template.

2021-08-13 03:25 UTC, fauxpark approved these changes

2021-08-13 19:30 UTC, drashna commented
Thanks!

2021-08-13 19:30 UTC, merged