add keyball directory
qmk/qmk_firmware pull request #13185
Opened 2021-06-11 20:59 UTC by Yowkees

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-11 21:01 UTC, Yowkees commented
I want to add my new keyborad with trackball "keyball". Thank you.

2021-06-17 04:43 UTC, drashna requested changes
If you haven't already, you may want to check out my dactyl manuform code, as it includes a split transport and additional code that supports using the pointing device no matter which side is plugged in. 

https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/dactyl_manuform/5x6_right_trackball

2021-06-17 04:43 UTC, drashna commented on keyboards/keyball/keyball.c
> +#include "keyball.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:43 UTC, drashna commented on keyboards/keyball/keyball.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:43 UTC, drashna commented on keyboards/keyball/keymaps/default/keymap.c
> +  }
```suggestion
#ifndef MOUSEKEY_ENABLE
    if (IS_MOUSEKEY_BUTTON(keycode)) {
        report_mouse_t currentReport = pointing_device_get_report();
        if (record->event.pressed) {
            currentReport.buttons |= 1 << (keycode - KC_MS_BTN1);
        } else {
            currentReport.buttons &= ~(1 << (keycode - KC_MS_BTN1));
        }
        pointing_device_set_report(currentReport);
        pointing_device_send();
    }
#endif
```

2021-06-17 04:43 UTC, drashna commented on keyboards/keyball/keymaps/default/keymap.c
> +/*#ifndef MOUSEKEY_ENABLE
Ah, I see you had it.  This is probably easier, though.

2021-06-17 04:43 UTC, drashna commented on keyboards/keyball/rev1/rev1.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:43 UTC, drashna commented on keyboards/keyball/rev1/rev1.c
> +#include "rev1.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-03 02:28 UTC, closed without merging