Add q4z keyboard
qmk/qmk_firmware pull request #13198
Opened 2021-06-12 23:22 UTC by rjboone

## Description

This pull request contains the necessary files to add Q4Z to QMK main. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Initial addition of keyboard

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-17 04:53 UTC, drashna requested changes

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/info.json
> +{
This file should be filled out or removed. 

Ideally, filled out.  If you have the kbfirmware json, you can use this: https://noroadsleft.github.io/kbf_qmk_converter/

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/keymaps/default/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/keymaps/rjboone/keymap.c
> +    switch(get_highest_layer(state|default_layer_state)) {
```suggestion
    switch(get_highest_layer(state)) {
```

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/q4z.c
> +#include "q4z.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-17 04:53 UTC, drashna commented on keyboards/q4z/q4z.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 01:19 UTC, drashna approved these changes

2021-07-08 16:05 UTC, fauxpark requested changes

2021-07-08 16:05 UTC, fauxpark commented on keyboards/q4z/q4z.h
> +{ K05, K10, K15, K20, K25, K29, K33, K37 } \
```suggestion
    K01, K06, K11, K16, K21, \
    K02, K07, K12, K17, K22, K26, K30, K34, K38,  K41, \
    K03,  K08, K13, K18, K23, K27, K31, K35, K39, K42, \
    K04,    K09, K14, K19, K24, K28, K32, K36,    K40, \
    K05, K10, K15,     K20,    K25,    K29, K33, K37 \
) { \
    { K01, K06, K11, K16, K21, XXX, XXX, XXX, XXX, XXX }, \
    { K02, K07, K12, K17, K22, K26, K30, K34, K38, K41 }, \
    { K03, K08, K13, K18, K23, K27, K31, K35, K39, K42 }, \
    { K04, K09, K14, K19, K24, K28, K32, K36, K40, XXX }, \
    { K05, K10, K15, K20, K25, K29, K33, K37, XXX, XXX } \
```

2021-07-08 16:05 UTC, fauxpark commented on keyboards/q4z/readme.md
> +# Q4Z
This file should follow the [template](https://github.com/qmk/qmk_firmware/blob/master/quantum/template/avr/readme.md).

2021-07-13 22:49 UTC, fauxpark requested changes

2021-07-13 22:49 UTC, fauxpark commented on keyboards/q4z/readme.md
> +`make q4z:default:flash`
```suggestion
    make q4z:default

Flashing example for this keyboard:

    make q4z:default:flash
```

2021-07-20 04:08 UTC, fauxpark approved these changes

2021-07-20 05:27 UTC, drashna commented
Thanks!

2021-07-20 05:27 UTC, merged