Refactor atom47 and add rev4 and rev5
qmk/qmk_firmware pull request #13201
Opened 2021-06-13 13:57 UTC by evyd13

## Description
Refactors the atom47, adds rev4 and rev5. Rev4 is a very [minimalistic version](https://cdn.discordapp.com/attachments/535222217974480896/707904153577324594/57fj3TV.png) and [rev5 is the opposite](https://cdn.discordapp.com/attachments/535222217974480896/853599021155614770/PXL_20210613_113710540.jpg).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [z] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [z] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-14 06:31 UTC, evyd13 commented
This is a breaking change, by the way.

2021-06-17 05:02 UTC, drashna requested changes

2021-06-17 05:02 UTC, drashna commented on keyboards/evyd13/atom47/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-12 15:10 UTC, drashna commented
There are merge conflicts here.

2021-08-12 15:25 UTC, evyd13 commented
Should be solved now!

2021-08-12 15:49 UTC, drashna approved these changes

2021-08-12 18:36 UTC, fauxpark requested changes

2021-08-12 18:36 UTC, fauxpark commented on keyboards/evyd13/atom47/readme.md
> +Hardware Availability: [Open source on GitHub](https://github.com/evyd13/atom47)
```suggestion
* Keyboard Maintainer: [Evelien Dekkers](https://github.com/evyd13)
* Hardware Supported: Atom47 rev2/rev3/rev4/rev5
* Hardware Availability: [Open source on GitHub](https://github.com/evyd13/atom47)
```

2021-08-12 18:36 UTC, fauxpark commented on keyboards/evyd13/atom47/rev2/rules.mk
>  RGBLIGHT_ENABLE = no   # Enable keyboard underlight functionality
```suggestion
RGBLIGHT_ENABLE = no
```

2021-08-12 18:36 UTC, fauxpark commented on keyboards/evyd13/atom47/rev4/rev4.c
> +}
Shouldn't be needed if you have the define in config.h.

2021-08-12 18:36 UTC, fauxpark commented on keyboards/evyd13/atom47/rev4/rules.mk
> +RGBLIGHT_ENABLE = no   # Enable keyboard underlight functionality
```suggestion
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
```

2021-08-12 18:36 UTC, fauxpark commented on keyboards/evyd13/atom47/rev5/rev5.c
> +}
```suggestion
void rgb_matrix_indicators_kb(void) {
    if (host_keyboard_led_state().caps_lock) {
        rgb_matrix_set_color(26, 255, 255, 255);
    } else {
        rgb_matrix_set_color(26, 0, 0, 0);
    }
}
```

2021-08-13 09:43 UTC, fauxpark approved these changes

2021-08-17 21:21 UTC, tzarc commented
@evyd13 I've pushed some changes that should fix things once merged, can you pull your branch and give them a quick try-out?

2021-08-17 21:21 UTC, tzarc approved these changes

2021-08-18 06:36 UTC, evyd13 commented
@tzarc I'm getting the following error on building the rev5 with any keymap: https://pastebin.com/gRFDT2eN

2021-08-18 08:07 UTC, fauxpark commented
You need to be on the `develop` branch.

2021-08-18 08:32 UTC, evyd13 commented
> You need to be on the `develop` branch.

Ah, works perfectly now :)

2021-08-19 16:40 UTC, merged