[Keyboard] Fix revision issues with Kyria
qmk/qmk_firmware pull request #13208
Opened 2021-06-14 04:57 UTC by drashna

## Description

This is a hidden bug, as it doesn't show up, because somebody got clever. 

However, the keyboard header files will cause issues if the `LAYOUT` macro is changed, and the rev3.h file is not properly included, either. 

This fixes the issues and moves the layout macros into the rev1.h file. 

There is NO functional change here, and this should be invisible to users. 

## Types of Changes

- [x] Bugfix
- [x] Keyboard (addition or update)

## Issues Fixed or Closed by This PR

*  Compiler issue 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-14 12:45 UTC, Duckle29 approved these changes

2021-06-17 23:07 UTC, fauxpark requested changes

2021-06-17 23:07 UTC, fauxpark commented on keyboards/kyria/rules.mk
> +
```suggestion
```

2021-06-18 03:09 UTC, fauxpark approved these changes

2021-06-18 04:11 UTC, merged