Keyboards/mun
qmk/qmk_firmware pull request #13239
Opened 2021-06-18 17:07 UTC by XScorpion2

## Description

RGBKB's Mun keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-19 02:03 UTC, drashna requested changes

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/mcuconf.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/mun.c
> +#include "mun.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/mun.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/rev1/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/mun.h
> +#include "rev1.h"
```suggestion
#if defined(KEYBOARD_rgbkb_mun_rev1)
#    include "rev1.h"
#endif
```

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/rev1/rev1.c
> +#include "rev1.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/rev1/rev1.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-06-19 02:03 UTC, drashna commented on keyboards/rgbkb/mun/rev1/rgbkb_mun.json
> +{
Is a via json, please remove.

2021-06-19 03:03 UTC, XScorpion2 commented on keyboards/rgbkb/common/touch_encoder.c
> +    touch_handness = is_keyboard_left() ? 0 : 1;
Believe it or not, that is actually bad practice when you need to consume the int value itself. Boolean is defined as 0 = false, any other value is true. So if you get in the habit of doing that, you could end up in a situation where your expected result is wrong. And yes, this has happened to me.

2021-06-19 04:04 UTC, drashna approved these changes

2021-06-22 00:38 UTC, Legonut commented
Approved by RGBKB

2021-06-23 15:19 UTC, kageurufu approved these changes

2021-06-26 04:59 UTC, drashna commented
Thanks!

2021-06-26 05:00 UTC, merged

2021-06-26 05:36 UTC, fauxpark reviewed
This PR has a few checklist problems and should not have been merged in its current state.

2021-06-27 14:54 UTC, XScorpion2 commented
> 
> 
> This PR has a few checklist problems and should not have been merged in its current state.

I'll reread the checklist and go fix them...been a while since I read that and it's probably changed.