Added pistachio rev2
qmk/qmk_firmware pull request #13248
Opened 2021-06-19 13:40 UTC by 7-rate

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-26 05:20 UTC, drashna requested changes

2021-06-26 05:20 UTC, drashna commented on keyboards/pistachio/pistachio.h
> +#endif
```suggestion
#if defined(KEYBOARD_pistachio_rev1)
#    include "rev1.h"
#elif defined(KEYBOARD_pistachio_rev2)
#    include "rev2.h"
#endif
```

2021-07-01 07:14 UTC, drashna approved these changes

2021-07-01 10:52 UTC, fauxpark approved these changes

2021-07-03 07:59 UTC, drashna commented
Thanks!

2021-07-03 07:59 UTC, merged