Nostromo maintenance
qmk/qmk_firmware pull request #13254
Opened 2021-06-20 01:29 UTC by su8044

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-20 01:30 UTC, su8044 commented
Adding Nostromo to QMK

2021-08-05 02:52 UTC, tzarc commented
Please remove the design files and place them in a separate repository.

2021-08-09 01:06 UTC, su8044 commented
Will do.

2021-08-11 23:04 UTC, su8044 commented
Alright, i left my master branch without the design files and the nostromo_mainteinance branch with them. is this correct? if not, could you please point me to the correct way? i searched the docs on the contributions but that was one of those things that i didn't quite get. thanks!

2021-08-11 23:07 UTC, su8044 commented
if it is the other way around (I'm starting to think it is), how do i do that on git? I'm quite noob on the subject

2021-10-30 07:34 UTC, fauxpark requested changes
Design files still need to be removed.

2021-10-30 07:34 UTC, fauxpark commented on keyboards/nostromo/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite
```

2021-10-30 07:34 UTC, fauxpark commented on keyboards/nostromo/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-10-30 07:34 UTC, fauxpark commented on keyboards/nostromo/info.json
> +    "height": 5,
```suggestion
```

2021-11-30 16:54 UTC, su8044 commented
Guys i'm having trouble isntalling MSYS and even if i isntall it i have no idea how to easily swap the location of the files. could you please give me a hand?

2021-12-06 02:17 UTC, drashna commented
> Guys i'm having trouble isntalling MSYS and even if i isntall it i have no idea how to easily swap the location of the files. could you please give me a hand?

Are you using QMK MSYS? 
https://msys.qmk.fm/

Also, you can do a lot of stuff from the browser.

2021-12-06 22:29 UTC, su8044 commented
yep, tried qmk msys too but for some reason i get an error compiling. either it compiles with an older version of qmk, or it doesn't at all. 

how can i make the changes to the file structure from the browser? never tried that

2021-12-06 22:36 UTC, drashna commented
if you head to the discord, can probably sort the msys issues for you.  But QMK WSL may work better. 

as for using the web: https://github.com/su8044/qmk_firmware/tree/nostromo_maintenance/keyboards/nostromo/PCB_5x12

There is an ellipse button in the top right corner that can delete files.

2021-12-06 22:43 UTC, su8044 commented
I'll connect to the qmk discord tonight and try again with MSYS. if I'm not successful ill delete that folder. thanks

2021-12-15 19:00 UTC, su8044 commented
Alright, i finally managed to delete Gerber and dwg folders :)

2021-12-16 05:55 UTC, fauxpark requested changes

2021-12-16 05:55 UTC, fauxpark commented on keyboards/nostromo/keymaps/default/readme.md
> +**Email:** su8044@gmail.com
```suggestion
```

2021-12-16 05:55 UTC, fauxpark commented on keyboards/preonic/keymaps/default/readme.md
> +# Nostromo
Please revert this file.

2021-12-16 05:55 UTC, fauxpark commented on keyboards/nostromo/rules.mk
> +
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
WS2812_DRIVER = pwm
BACKLIGHT_DRIVER = pwm

LAYOUTS = ortho_5x12
```

2021-12-16 05:55 UTC, fauxpark commented on keyboards/nostromo/readme.md
> +**Email:** su8044@gmail.com
```suggestion
```

2022-01-09 00:53 UTC, noroadsleft requested changes

2022-01-09 00:53 UTC, noroadsleft commented on keyboards/nostromo/keymaps/default/readme.md
> +# Nostromo
This file can actually be removed.

```
git rm keyboards/nostromo/keymaps/default/readme.md
git commit -m "Remove keyboards/nostromo/keymaps/default/readme.md"
```

2022-01-09 00:53 UTC, noroadsleft commented on keyboards/preonic/keymaps/default/readme.md
> +# Nostromo
```
git checkout 3fa592a4024a24a636fa0c562e6761667a94f565 -- 3fa592a4024a24a636fa0c562e6761667a94f565
git commit -m "Revert keyboards/preonic/keymaps/default/readme.md"
```

2022-06-12 15:56 UTC, closed without merging