Add Serratus PCB
qmk/qmk_firmware pull request #13281
Opened 2021-06-21 08:02 UTC by mechlovin

## Description

Add Serratus TKL PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-21 16:06 UTC, drashna requested changes

2021-06-21 16:06 UTC, drashna commented on keyboards/mechlovin/hannah910/rev3/config.h
> +#define USB_POLLING_INTERVAL_MS 1
Could this change be reverted?

2021-06-21 16:06 UTC, drashna commented on keyboards/mechlovin/infinity87/rgb_rev1/config.h
> +#define USB_POLLING_INTERVAL_MS 1
Could this change be reverted?

2021-06-21 16:06 UTC, drashna commented on keyboards/mechlovin/th1800/config.h
> +#define USB_POLLING_INTERVAL_MS 1
Could this change be reverted.

2021-06-21 16:10 UTC, mechlovin commented
Thank you. I have tested polling rate on my board and forgot to delete them.

2021-06-26 05:58 UTC, drashna approved these changes

2021-06-26 06:03 UTC, fauxpark requested changes

2021-06-26 06:03 UTC, fauxpark commented on keyboards/mechlovin/serratus/matrix.c
> +#ifdef DIRECT_PINS
All the direct pins stuff can be removed from here.

2021-07-14 15:45 UTC, mechlovin commented
Hi. @fauxpark.
Anything else I can do?

2021-07-14 15:57 UTC, fauxpark requested changes

2021-07-14 15:57 UTC, fauxpark commented on keyboards/mechlovin/serratus/readme.md
> +![serratus](https://i.imgur.com/VN38ogY.jpeg)
```suggestion
![serratus](https://i.imgur.com/VN38ogYh.jpeg)
```

2021-07-14 16:12 UTC, fauxpark approved these changes

2021-07-14 20:55 UTC, drashna commented
Thanks!

2021-07-14 20:55 UTC, merged