haervig_dev-branch
qmk/qmk_firmware pull request #13362
Opened 2021-06-27 09:23 UTC by jakobhaervig

## Description

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-06-27 10:32 UTC, jakobhaervig commented
Minor update to fix macOS keys (alt and ui switched)

2021-06-29 17:20 UTC, zvecr requested changes
From the PR checklist,

> valid license headers on all *.c and *.h source files
>   * GPL2/GPL3 recommended for consistency

2021-06-29 22:50 UTC, fauxpark requested changes

2021-06-29 22:50 UTC, fauxpark commented on users/haervig/haervig.h
> +    register_code(kc2); \
Pairs like this can be written as:
```suggestion
tap_code(kc2);
```
If you're expecting modified keycodes here as well, use `tap_code16()`.

2021-06-30 10:49 UTC, fauxpark commented on users/haervig/haervig.h
> +    register_code(kc2); \
Looks like I misread, actually, this won't work since the unregister is coming before the register.

2021-06-30 10:50 UTC, fauxpark commented on users/haervig/LICENSE
> +Copyright 2021 Jakob Hærvig <jakob.haervig@gmail.com>
No need for this file.

2021-07-01 08:18 UTC, drashna requested changes

2021-07-01 08:18 UTC, drashna commented on keyboards/dztech/dz65rgb/keymaps/haervig/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-01 10:54 UTC, fauxpark approved these changes

2021-07-01 17:10 UTC, drashna approved these changes

2021-07-01 17:12 UTC, merged