added the ortho boards from the technik gb
qmk/qmk_firmware pull request #13382
Opened 2021-06-29 17:43 UTC by daysgobye

## Description

Added ortho version of technik keyboard the technik-o and the macro pad to go with it the beiwagon to the Boardsource folder.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-01 18:05 UTC, drashna commented on keyboards/boardsource/beiwagon/readme.md
> +*A short description of the keyboard/project*
description here?

2021-07-01 18:07 UTC, drashna requested changes
You have changes to chibios libraries. 

You may need to rebase to fix these.

2021-07-01 18:07 UTC, drashna commented on keyboards/boardsource/beiwagon/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2021-07-01 18:07 UTC, drashna commented on keyboards/boardsource/technik_o/readme.md
> +*A short description of the keyboard/project*
here too

2021-07-01 18:07 UTC, drashna commented on keyboards/boardsource/technik_o/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2021-07-03 08:18 UTC, drashna approved these changes

2021-07-03 08:29 UTC, fauxpark requested changes

2021-07-03 08:29 UTC, fauxpark commented on keyboards/boardsource/beiwagon/readme.md
> +![Beiwagon](https://imgur.com/eQi2Laq)
```suggestion
![Beiwagon](https://i.imgur.com/eQi2Laqh.jpeg)
```

2021-07-03 08:29 UTC, fauxpark commented on keyboards/boardsource/beiwagon/readme.md
> +    make boardsource/beiwagon:default:flash
```suggestion
    make boardsource/beiwagon:default:flash

Reset keyboard by pushing reset button on back of pcb through access hole. Or hold down top left key while you plug in the usb cable.
```

2021-07-03 08:29 UTC, fauxpark commented on keyboards/boardsource/technik_o/readme.md
> +![Technik-O](https://imgur.com/F2VTqAs)
```suggestion
![Technik-O](https://i.imgur.com/F2VTqAs.jpeg)
```

2021-07-03 08:29 UTC, fauxpark commented on keyboards/boardsource/technik_o/readme.md
> +    make boardsource/technik_o:default:flash
```suggestion
    make boardsource/technik_o:default:flash

Reset keyboard by pushing reset button on back of pcb through access hole. Or hold down top left key while you plug in the usb cable.
```

2021-07-04 00:44 UTC, fauxpark approved these changes

2021-07-04 01:05 UTC, drashna commented
Thanks!

2021-07-04 01:06 UTC, merged