[Keyboard] Add TypeTheory Keyboard
qmk/qmk_firmware pull request #13408
Opened 2021-07-01 21:01 UTC by mgvx

## Description

Add support for the [TypeTheory Keyboard](https://typetheory.co.uk).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-03 09:06 UTC, drashna requested changes

2021-07-03 09:06 UTC, drashna commented on keyboards/typetheory/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-03 09:06 UTC, drashna commented on keyboards/typetheory/typetheory.c
> +#include "typetheory.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-03 14:50 UTC, drashna approved these changes

2021-08-22 04:06 UTC, fauxpark requested changes

2021-08-22 04:06 UTC, fauxpark commented on keyboards/typetheory/rules.mk
> +BLUETOOTH_ENABLE = no
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
LTO_ENABLE = yes
```

2021-08-22 04:06 UTC, fauxpark commented on keyboards/typetheory/readme.md
> +Tip: if desired, you can flash different layouts to the left/right side. Then, the entire keyboard will use the 'left' layout when the left side is plugged into the computer, and vice-versa for the r
```suggestion
# TypeTheory Keyboard

![Picture of TypeTheory Keyboard](https://typetheory.co.uk/thumb/front.jpg)

The [TypeTheory Keyboard](https://typetheory.co.uk/) is a split ergonomic keyboard inspired by the [Dactyl-Manuform](https://github.com/tshort/dactyl-keyboard) and the Kinesis Advantage2. It uses two Puchi-C microcontrollers, with physical reset buttons.

* Keyboard Maintainer: Marius Gavrilescu
* Hardware Supported: TypeTheory Keyboard
* Hardware Availability: https://typetheory.co.uk

Make example for this keyboard (after setting up your build environment):

    make typetheory:default

Flashing example for this keyboard:

    make typetheory:default:dfu-split-left
    make typetheory:default:dfu-split-right

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the Puchi-C
* **Keycode in layout**: Press the key mapped to `RESET` (`RAISE`+Right Shift on the default keymap)
```

2021-09-11 04:16 UTC, fauxpark requested changes

2021-09-11 04:16 UTC, fauxpark commented on keyboards/typetheory/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-11 04:16 UTC, fauxpark commented on keyboards/typetheory/info.json
> +    "height": 8,
```suggestion
```

2022-01-09 02:13 UTC, closed without merging