Add Hex4B PCB
qmk/qmk_firmware pull request #13435
Opened 2021-07-03 18:18 UTC by mechlovin

## Description

Add Hex4B PCB, Atmega32a.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-04 00:26 UTC, drashna reviewed
Looks like you need to rebase to fix the lib/chibios changes

2021-07-23 14:56 UTC, drashna approved these changes

2021-07-23 16:57 UTC, fauxpark requested changes

2021-07-23 16:57 UTC, fauxpark commented on keyboards/mechlovin/hex4b/rules.mk
> +F_CPU ?= 16000000
```suggestion
# Processor frequency
F_CPU = 16000000
```

2021-07-23 16:57 UTC, fauxpark commented on keyboards/mechlovin/hex4b/rules.mk
> +BACKLIGHT_ENABLE = yes       # Enable keyboard backlight functionality
```suggestion
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
```

2021-07-23 16:57 UTC, fauxpark commented on keyboards/mechlovin/hex4b/readme.md
> +![hex4b](https://i.imgur.com/lArfGgH.jpeg)
```suggestion
![hex4b](https://i.imgur.com/lArfGgHh.jpeg)
```

2021-07-23 16:57 UTC, fauxpark commented on keyboards/mechlovin/hex4b/readme.md
> +    make mechlovin/hex_kb/hex4b:default:flash
```suggestion
    make mechlovin/hex4b:default

Flashing example for this keyboard:

    make mechlovin/hex4b:default:flash
```

2021-07-31 07:02 UTC, fauxpark approved these changes

2021-08-07 00:02 UTC, merged