fixes and additions to the Marauder hand wired keyboard
qmk/qmk_firmware pull request #13462
Opened 2021-07-06 08:02 UTC by BB-66

## Description

    1000Hz polling rate;
    added OLED and bongo cat as well as WPM feedback;
    refined caps/num/sclk OLED indicators;
    added NKRO indicator on OLED;
    added RGB support;
    added VIA support (JSON to be added to the VIA keyboards repo);
    changed the controller pins used due to additions of OLED and RGB support;
    optimizing overall firmware size (console and command disabled, most RGB animatinos disabled);
    fixed readme.md;
    further size optimizations on-going, as well as bongo cat size in the firmware to be addressed at a later date;
    full documentation of the process is in the works.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-06 23:32 UTC, drashna requested changes

2021-07-06 23:32 UTC, drashna commented on keyboards/handwired/marauder/keymaps/orvia/keymap.c
> +char wpm_str[10];
```suggestion
char wpm_str[4];
```

2021-07-11 14:44 UTC, drashna approved these changes

2021-07-11 15:20 UTC, fauxpark approved these changes

2021-07-13 15:58 UTC, merged