Add CannonKeys Balance PCB to QMK
qmk/qmk_firmware pull request #13489
Opened 2021-07-08 01:47 UTC by awkannan

## Description

Adding Balance keyboard to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-11 06:22 UTC, drashna requested changes
n

2021-07-11 06:22 UTC, drashna commented on keyboards/cannonkeys/balance/balance.c
> +    if (clockwise) {
```suggestion
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (clockwise) {
```

2021-07-11 06:22 UTC, drashna commented on keyboards/cannonkeys/balance/config.h
> +#define DESCRIPTION Balance Keyboard
```suggestion
```

2021-07-14 04:03 UTC, drashna approved these changes

2021-07-14 04:12 UTC, fauxpark requested changes

2021-07-14 04:12 UTC, fauxpark commented on keyboards/cannonkeys/balance/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2021-07-15 15:03 UTC, fauxpark approved these changes

2021-07-20 01:49 UTC, drashna commented
Thanks

2021-07-20 01:49 UTC, merged