add support for alternate ortho UD40 PCB
qmk/qmk_firmware pull request #13491
Opened 2021-07-08 04:22 UTC by npspears

alternate ortho PCB for UD40 sold on Checkerboards.xyz

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-11 06:27 UTC, drashna approved these changes

2021-08-13 13:51 UTC, fauxpark requested changes

2021-08-13 13:51 UTC, fauxpark commented on keyboards/checkerboards/ud40_ortho_alt/readme.md
> +![UD40_Ortho_Alt](https://i.imgur.com/a/bHvpzUX.jpg)
```suggestion
![UD40_Ortho_Alt](https://i.imgur.com/NnGIo0O.png)
```

2021-08-13 13:51 UTC, fauxpark commented on keyboards/checkerboards/ud40_ortho_alt/readme.md
> +    make ud40_ortho_alt:default
```suggestion
    make checkerboards/ud40_ortho_alt:default
```

2021-08-13 13:54 UTC, npspears reviewed
suggestions committed

2021-08-13 14:15 UTC, fauxpark approved these changes

2021-08-13 19:26 UTC, drashna commented
Thanks!

2021-08-13 19:26 UTC, merged