[Keyboard] Add MelGeek MJ6xy which is a 60% keyboard that support mul…
qmk/qmk_firmware pull request #13494
Opened 2021-07-08 14:58 UTC by mj-bomb

…ti-layous

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-11 06:30 UTC, drashna approved these changes

2021-07-12 01:45 UTC, mj-bomb commented
@fauxpark @labria   hello, please kindly review this PR, Thank you very much

2021-07-12 02:48 UTC, fauxpark requested changes

2021-07-12 02:48 UTC, fauxpark commented on keyboards/melgeek/mj6xy/rev3/config.h
> +#	define BACKLIGHT_LEVELS    10
```suggestion
#	define BACKLIGHT_LEVELS    10
```

2021-07-12 02:48 UTC, fauxpark commented on keyboards/melgeek/mj6xy/rev3/rules.mk
> +
```suggestion

# Bootloader selection
BOOTLOADER = atmel-dfu
```

2021-07-13 17:08 UTC, drashna approved these changes

2021-07-13 22:47 UTC, fauxpark approved these changes

2021-07-14 06:24 UTC, mj-bomb commented
@tzarc @zvecr  hello, please kindly review this PR, Thank you very much

2021-07-14 15:39 UTC, drashna commented
Thanks

2021-07-14 15:39 UTC, merged