add simple gmmk pro macos keymap with rgb
qmk/qmk_firmware pull request #13504
Opened 2021-07-10 00:36 UTC by alexmarmon

## Description

![Layout Image](https://i.imgur.com/MizMvsI.jpg)

* Working basic RGB thanks to https://github.com/qmk/qmk_firmware/pull/13430
* Restore working rotary knob volume control
* Add media_previous and media_next to FN+left and FN+right

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-10 01:35 UTC, zvecr requested changes

2021-07-10 01:35 UTC, zvecr commented on keyboards/gmmk/pro/keymaps/alexmarmon/rules.mk
> +RGB_MATRIX_DRIVER = AW20216
https://github.com/qmk/qmk_firmware/blob/40d13e1210afc65f01f9afc4fa68086892862210/keyboards/gmmk/pro/rules.mk#L24-L25

Already specified at the parent level so not required. As there are no other overrides, this file should be removed/

2021-07-11 23:26 UTC, fauxpark approved these changes

2021-07-12 15:54 UTC, drashna approved these changes

2021-07-12 16:36 UTC, merged