Dumbpad VIA support added
qmk/qmk_firmware pull request #13512
Opened 2021-07-11 02:35 UTC by jfescobar18

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-11 02:36 UTC, jfescobar18 commented
This keymap adds VIA support for this keyboard

2021-07-11 06:48 UTC, drashna approved these changes

2021-07-31 07:34 UTC, fauxpark requested changes

2021-07-31 07:34 UTC, fauxpark commented on keyboards/dumbpad/keymaps/via/keymap.c
> +
```suggestion
```

2021-07-31 07:34 UTC, fauxpark commented on keyboards/dumbpad/keymaps/default/keymap.c
> +
```suggestion
```

2021-08-13 18:57 UTC, drashna commented
This needs to be rebased to fix a bunch of the unintentional commits added to the PR.

2021-08-15 23:20 UTC, fauxpark approved these changes

2021-08-19 17:37 UTC, drashna approved these changes

2021-08-19 17:38 UTC, drashna commented
Thanks!

2021-08-19 17:39 UTC, merged