Add ianklug grooveboard
qmk/qmk_firmware pull request #13536
Opened 2021-07-13 15:45 UTC by ianklug

## Description

Add files for ianklug grooveboard, a four-key keyboard for rhythm games.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-13 16:17 UTC, drashna approved these changes

2021-07-13 16:20 UTC, fauxpark requested changes

2021-07-13 16:20 UTC, fauxpark commented on keyboards/ianklug/grooveboard/readme.md
> +* Hardware Availability: *https://github.com/ianklug/grooveboard*
```suggestion
A four-key mechanical keyboard for rhythm games.

![Grooveboard Choc PCB](https://i.imgur.com/wbMkbHX.jpg)

* Keyboard Maintainer: [ianklug](https://github.com/ianklug)
* Hardware Supported: grooveboard, grooveboard mx, grooveboard choc
* Hardware Availability: https://github.com/ianklug/grooveboard
```

2021-07-13 16:21 UTC, fauxpark commented
```
⚠ ianklug/grooveboard: DEVICE_VER in config.h is overwriting usb.device_ver in info.json
⚠ ianklug/grooveboard: PRODUCT_ID in config.h is overwriting usb.pid in info.json
⚠ ianklug/grooveboard: VENDOR_ID in config.h is overwriting usb.vid in info.json
⚠ ianklug/grooveboard: Direct pins are specified in both info.json and config.h, the config.h values win.
```

2021-07-13 16:27 UTC, fauxpark approved these changes

2021-07-14 04:04 UTC, drashna commented
Thanks!

2021-07-14 04:04 UTC, merged