Fix clang unit tests
qmk/qmk_firmware pull request #13546
Opened 2021-07-15 00:56 UTC by dkjer

On Mac, clang errors out on some flags when attempting to run tests.

## Description

On Mac, clang errors out on some flags when attempting to run tests:
`clang: error: the clang compiler does not support '-funsigned-bitfields' [-Werror]`
`clang: error: optimization flag '-fno-inline-small-functions' is not supported [-Werror,-Wignored-optimization-argument]`
`clang: error: unsupported argument '-adhlns=.build/test_obj/eeprom_stm32/tmk_core/common/test/flash_stm32_mock.lst' to option 'Wa,'`

Steps to reproduce:
* On a system using clang, run `make test:debounce_sym_defer_g`

This change skips including a few non-compatible compiler flags when using clang.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-15 02:32 UTC, drashna approved these changes

2021-07-15 19:02 UTC, zvecr requested changes
Continuing from <https://github.com/qmk/qmk_firmware/pull/12567#issuecomment-880279414>.

The main issue this is trying to solve is clangs limited gcc compatibility. clang can be run on more than systems that report as apple, likewise gcc can work fine on x86 darwin systems. There seems to still be little movement in providing a gcc for apple Arm64.

So would still be keen to pivot the issue from "is apple" to "is clang".

2021-07-18 01:54 UTC, dkjer commented
@zvecr Ok, updated to check for clang

2021-08-17 21:12 UTC, tzarc approved these changes

2021-08-17 21:12 UTC, merged