Update the XBows/Knight keyboard
qmk/qmk_firmware pull request #13541
Opened 2021-07-14 02:04 UTC by XBowsTech

## Description

Update the XBows/Knight keyboard and fixed some other bugs.
Updated files include: all files for knight.
                                    knight_plus: info.json and rules.mk
                                    numpad: info,json

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-14 15:57 UTC, fauxpark requested changes

2021-07-14 15:57 UTC, fauxpark commented on keyboards/xbows/knight_plus/rules.mk
> +NO_USB_STARTUP_CHECK = no  # Disables usb supend check after keyboard startup
```suggestion
```

2021-07-14 15:57 UTC, fauxpark commented on keyboards/xbows/knight/rules.mk
> +#NO_USB_STARTUP_CHECK = yes  # Disables usb supend check after keyboard startup
```suggestion
```

2021-07-15 02:57 UTC, fauxpark approved these changes

2021-07-20 01:28 UTC, drashna approved these changes

2021-07-20 01:28 UTC, drashna commented
Thanks!

2021-07-20 01:28 UTC, merged