[Keyboard] Valor Rev 2
qmk/qmk_firmware pull request #13551
Opened 2021-07-15 08:59 UTC by Xelus22

## Description

Add Valor Rev 2
This targets develop as it uses STM32L422

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add Valor Rev 2

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-20 01:09 UTC, drashna requested changes

2021-07-20 01:09 UTC, drashna commented on keyboards/xelus/valor/rev2/rev2.c
> +}
Not needed. 
```suggestion
```

2021-07-20 05:04 UTC, drashna approved these changes

2021-07-25 07:59 UTC, fauxpark requested changes

2021-07-25 07:59 UTC, fauxpark commented on keyboards/xelus/valor/rev2/rules.mk
> +MCU = STM32L422
```suggestion
MCU = STM32L422

# Bootloader selection
BOOTLOADER = stm32-dfu
```

2021-07-25 07:59 UTC, fauxpark commented on keyboards/xelus/valor/rev2/rules.mk
> +WS2812_DRIVER = pwm
```suggestion
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_CUSTOM_KB = yes
WS2812_DRIVER = pwm
EEPROM_DRIVER = i2c

OPT = 2
LTO_ENABLE = yes

LAYOUTS = alice_split_bs
```

2021-07-25 11:39 UTC, fauxpark approved these changes

2021-07-26 05:33 UTC, drashna commented
Thanks!

2021-07-26 05:34 UTC, merged