Update LUFA to newest (18-07-2021) and add QMK-HID Bootloader support
qmk/qmk_firmware pull request #13588
Opened 2021-07-18 17:20 UTC by drashna

## Description

Like the title says. 
Updates LUFA to the latest version, as well as adds support for generating the lufa HID bootloader, as well as flashing it.

## Types of Changes

- [x] Core
- [x] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-18 18:11 UTC, fauxpark commented on bootloader.mk
> +ifeq ($(strip $(BOOTLOADER)), qmk-hid)
Also add to list at the top.

2021-07-18 21:42 UTC, drashna commented on bootloader.mk
> +ifeq ($(strip $(BOOTLOADER)), qmk-hid)
Added

2021-07-18 21:43 UTC, drashna commented
Added additional documentation. 

Also want to add a split left/right target, but doesn't support that natively.  Would have to be a hack like dfu-util.  teensy/halfkay could use that too.

2021-07-19 17:17 UTC, fauxpark requested changes

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +  * Currently, you need to either use the [python script](https://github.com/qmk/lufa/tree/master/Bootloaders/HID/HostLoaderApp_python) in the lufa repo, or compile the [`hid_bootloader_cli`](https:/
```suggestion
  * Currently, you need to either use the [Python script](https://github.com/qmk/lufa/tree/master/Bootloaders/HID/HostLoaderApp_python), or compile [`hid_bootloader_cli`](https://github.com/qmk/lufa/tree/master/Bootloaders/HID/HostLoaderApp), from the LUFA repo. Homebrew may (will) have support for this directly (via `brew install qmk/qmk/hid_bootloader_cli`).
```

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +
```suggestion
```

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +
```suggestion
```

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +
```suggestion
```

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +QMK maintains [a fork of the LUFA HID bootloader](https://github.com/qmk/lufa/tree/master/Bootloaders/HID), which uses a USB HID Endpoint for flashing in the way that the PJRC's Teensy Loader flasher
```suggestion
QMK maintains [a fork of the LUFA HID bootloader](https://github.com/qmk/lufa/tree/master/Bootloaders/HID), which uses a USB HID Endpoint for flashing in the way that the PJRC's Teensy Loader flasher and HalfKay bootloader work. Additionally, it performs a simple matrix scan for exiting the bootloader and returning to the application, as well as flashing an LED/making a ticking noise with a speaker when things are happening.
```

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +1. Enter the bootloader using any of the following methods (you only have 7 seconds to flash once it enters):
```suggestion
1. Enter the bootloader using any of the following methods:
```
I guess this is copied from the HalfKay section - only Caterina has this 7-second timeout, so it should be removed from there too.

2021-07-19 17:17 UTC, fauxpark commented on docs/flashing.md
> +    * Press the `RESET` button on the Teensy or PCB if available
```suggestion
    * Press the `RESET` button on the PCB if available
```

2021-07-19 17:17 UTC, fauxpark commented on tmk_core/avr.mk
> +
```suggestion
```

2021-07-19 17:17 UTC, fauxpark commented on tmk_core/avr.mk
> +
```suggestion
```

2021-07-19 17:23 UTC, fauxpark requested changes
Should also add the following to the table at the end of `driver_installation_zadig.md`:

```
|`qmk-hid`    |(keyboard name) Bootloader    |`03EB:2067`   |HidUsb |
```

2021-07-19 17:38 UTC, fauxpark approved these changes

2021-07-25 05:59 UTC, tzarc approved these changes

2021-07-25 06:00 UTC, merged