DZ60 and GMMK keymaps
qmk/qmk_firmware pull request #13594
Opened 2021-07-19 08:56 UTC by dnedbaylo

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-19 20:48 UTC, Madnace commented
Hi ! Sorry i'm really new and nut at programing... I'm owning rn the GMMk full size and i wandted to know if it would be possible to add the complete firmware to qmk because i'm playing rythmic game and saw that the polling rate is 62.5hz wich means every keys  entries are sent to the pc every 16 milliseconds that is clearly impossible to play with this one...

Do you have some tips ? Can i still make my own firmware ?

2021-07-20 00:21 UTC, drashna requested changes

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/config.h
> +#define CONFIG_KEYMAP_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

Also
```suggestion
#pragma once
```

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/config.h
> +#include "../../config.h"
This line is not actually needed, and should be removed. 

```suggestion
```

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/config.h
> +#endif
```suggestion
```

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/keymap.c
> +    switch (biton32(state)) {
```suggestion
    switch (get_highest_layer(state)) {
```

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/keymap.c
> +            rgblight_setrgb (0x00,  0x00, 0xFF);
```suggestion
            default_layer_state_set_user(default_layer_state);
```

2021-07-20 00:21 UTC, drashna commented on keyboards/dz60/keymaps/dmitrynedbaylo/keymap.c
> +    switch (biton32(state)) {
```suggestion
    switch (get_highest_layer(state)) {
```

2021-07-20 00:21 UTC, drashna commented on keyboards/gmmk/pro/keymaps/dmitrynedbaylo/config.h
> +#include "../../config.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

```suggestion
#pragma once
```

2021-07-20 00:21 UTC, drashna commented on keyboards/gmmk/pro/keymaps/dmitrynedbaylo/config.h
> +#endif
```suggestion
```

2021-07-20 00:24 UTC, drashna commented
> Hi ! Sorry i'm really new and nut at programing... I'm owning rn the GMMk full size and i wandted to know if it would be possible to add the complete firmware to qmk because i'm playing rythmic game and saw that the polling rate is 62.5hz wich means every keys entries are sent to the pc every 16 milliseconds that is clearly impossible to play with this one...
> 
> Do you have some tips ? Can i still make my own firmware ?

This isn't exactly the correct place to ask this.  As a separate issue, or on the QMK Discord would be a better place for this. 

unfortunately, the full sized GMMK probably won't support QMK, period.

2021-07-20 13:15 UTC, dnedbaylo commented
@drashna Sorry, I just realized I created a PR in qmk repo, not in my fork :facepalm: . Closing the PR.

2021-07-20 13:15 UTC, closed without merging