keymaps: add kinesis/keymaps/jwon
qmk/qmk_firmware pull request #13618
Opened 2021-07-20 17:24 UTC by jwon

## Description

Created my own personal keymap for the Kinesis Advantage 2 using the Stapelberg mod.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-21 05:08 UTC, drashna requested changes

2021-07-21 05:08 UTC, drashna commented on keyboards/kinesis/keymaps/jwon/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-21 05:08 UTC, drashna commented on keyboards/kinesis/keymaps/jwon/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-21 05:08 UTC, drashna commented on keyboards/kinesis/keymaps/jwon/keymap.c
> +}
You could do this, too:
```suggestion
void matrix_scan_user(void) {
    writePin(LED_CAPS_LOCK_PIN, !(get_mods() & MOD_MASK_SHIFT));
}
```

2021-07-22 16:53 UTC, jwon commented
Thank you for the feedback @drashna !

I made the changes you suggested. Can you please take another look?

2021-07-22 17:42 UTC, drashna approved these changes

2021-07-22 17:48 UTC, fauxpark requested changes

2021-07-22 17:48 UTC, fauxpark commented on keyboards/kinesis/keymaps/jwon/config.h
> +/* Copyright 2021 James Won <me@jwon.me>
This file can actually be removed entirely.

2021-07-22 17:48 UTC, fauxpark commented on keyboards/kinesis/keymaps/jwon/rules.mk
> +
Most of this can be removed, you only need the differences from the keymap/revision level rules.mk.

2021-07-22 22:18 UTC, jwon commented
@fauxpark I made the changes you requested. Can you please take another look? Thank you very much!

2021-07-23 04:30 UTC, fauxpark requested changes

2021-07-23 04:30 UTC, fauxpark commented on keyboards/kinesis/keymaps/jwon/rules.mk
> +NKRO_ENABLE = yes           # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
```

2021-07-23 15:59 UTC, fauxpark approved these changes

2021-07-24 15:39 UTC, drashna commented
Thanks!

2021-07-24 15:40 UTC, merged