Create keymap.c
qmk/qmk_firmware pull request #13612
Opened 2021-07-20 06:39 UTC by MauliQT

Edited the OG version with multiple layers and a few macros for Photoshop and "non Working existing Keys" like copy, paste, cut and undo.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
Fixes #
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-20 06:39 UTC, MauliQT commented
Just a layout and macro addition

2021-07-21 05:18 UTC, drashna requested changes

2021-07-21 05:18 UTC, drashna commented on keyboards/pabile/p18/keymaps/macro_layer/keymap.c
> + -0,0 +1,77 @@
```suggestion
```

And could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-21 05:18 UTC, drashna commented on keyboards/pabile/p18/keymaps/macro_layer/keymap.c
> +        break;
These can be replaced with `C(KC_C)`, `C(KC_V)`, and `C(KC_X)` respectively, in your keymap.

2021-07-21 05:18 UTC, drashna commented on keyboards/pabile/p18/keymaps/macro_layer/keymap.c
> +    }
Same with these, `C(KC_Z)` amd `C(KC_Y)`.

2021-07-21 05:18 UTC, drashna commented on keyboards/pabile/p18/keymaps/macro_layer/keymap.c
> +  if (index == 0) { / First encoder below the controller /
```suggestion
  if (index == 0) { /* First encoder below the controller */
```

2021-07-21 05:18 UTC, drashna commented on keyboards/pabile/p18/keymaps/macro_layer/keymap.c
> +      tap_code16(C(KC_PPLS); /ZOOM OUT*/
```suggestion
      tap_code(KC_VOLD); /* volume down */
    } else {
      tap_code(KC_VOLU); /* volume up */
                 //Just plain audio controlle
    }
  } else if (index == 1) { /* Second encoder */
    if (clockwise) {
      tap_code16(C(KC_PMNS); /* ZOOM IN */               
    } else {
      tap_code16(C(KC_PPLS); /* ZOOM OUT */
```

2021-07-23 14:37 UTC, closed without merging