Created "paddlegame" keymap
qmk/qmk_firmware pull request #13629
Opened 2021-07-21 17:40 UTC by tguinan

## Description

Added a paddle game to layer 2 using the rotary encoder, accessible by pressing Fn+P.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-21 20:54 UTC, drashna requested changes

2021-07-21 20:54 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/paddlegame/keymap.c
> +bool _isWinKeyDisabled = false;
```suggestion
```

2021-07-21 20:54 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/paddlegame/keymap.c
> +            if(_isWinKeyDisabled) {
```suggestion
            if(!keymap_config.no_gui) {
```

2021-07-22 05:49 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/paddlegame/keymap.c
> +    }
This isn't needed. 
```suggestion
```

2021-07-22 07:36 UTC, drashna approved these changes

2021-08-17 22:43 UTC, tzarc approved these changes

2021-08-17 22:43 UTC, merged