Add personal planck keymap
qmk/qmk_firmware pull request #13635
Opened 2021-07-21 19:40 UTC by adamtabrams

## Description

This adds my personal keymap for the planck keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-21 21:03 UTC, drashna requested changes

2021-07-21 21:03 UTC, drashna commented on keyboards/planck/keymaps/adamtabrams/keymap.c
> +            layer_off(_SYSTEM);
```suggestion
            layer_clear();
```

2021-07-21 21:03 UTC, drashna commented on keyboards/planck/keymaps/adamtabrams/keymap.c
> +            return true;
```suggestion
        case SHFTESC:
        case NUMSPAC:
        case SFTENTR:
        case ALT__A:
        case ALTSCLN:
        case ALT__O:
        case GUI__S:
        case GUI__L:
        case GUI__R:
        case GUI__I:
        case SFT__D:
        case SFT__K:
        case SFT__S:
        case SFT__E:
        case CTL__F:
        case CTL__J:
        case CTL__T:
        case CTL__N:
            return true;
```

2021-07-21 21:03 UTC, drashna commented on keyboards/planck/keymaps/adamtabrams/keymap.c
> +            return true;
```suggestion
        case ALT__A:
        case ALTSCLN:
        case ALT__O:
        case GUI__S:
        case GUI__L:
        case GUI__R:
        case GUI__I:
        case SFT__D:
        case SFT__K:
        case SFT__S:
        case SFT__E:
        case CTL__F:
        case CTL__J:
        case CTL__T:
        case CTL__N:
            return true;
```

2021-07-22 03:12 UTC, fauxpark approved these changes

2021-07-22 05:55 UTC, drashna approved these changes

2021-07-22 05:56 UTC, drashna commented
Thanks!

2021-07-22 05:56 UTC, merged