Change the default RGB light effects.
qmk/qmk_firmware pull request #13657
Opened 2021-07-23 08:55 UTC by mj-bomb

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-23 15:10 UTC, drashna commented on keyboards/melgeek/mj6xy/rev3/config.h
> +#	 define RGBLIGHT_EFFECT_RAINBOW_MOOD
if `RGBLIGHT_ANIMATIONS` is defined, you don't need this defined, as well,
```suggestion
```

2021-07-26 01:33 UTC, mj-bomb commented
@tzarc @fauxpark   Hello, my friend. Can you vet it for me

2021-07-26 01:39 UTC, mj-bomb commented
@tzarc @fauxpark   Hello, my friend. Could you mind review for my PR?

2021-07-26 01:53 UTC, fauxpark requested changes

2021-07-26 01:53 UTC, fauxpark commented on keyboards/melgeek/mj6xy/rev3/config.h
> +#	 define RGBLIGHT_DEFAULT_MODE (RGBLIGHT_EFFECT_RAINBOW_MOOD + 6)
```suggestion
#    define RGBLIGHT_ANIMATIONS
#    define RGBLIGHT_DEFAULT_MODE (RGBLIGHT_EFFECT_RAINBOW_MOOD + 6) 
```

2021-07-26 02:21 UTC, fauxpark approved these changes

2021-07-26 04:19 UTC, drashna approved these changes

2021-07-26 04:21 UTC, drashna commented
Thanks!

2021-07-26 04:22 UTC, merged