[Keyboard] Dharma
qmk/qmk_firmware pull request #13663
Opened 2021-07-23 14:30 UTC by Xelus22

## Description

Add Dharma Keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add Dharma Keyboard

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-23 15:33 UTC, drashna approved these changes

2021-07-23 15:58 UTC, fauxpark requested changes

2021-07-23 15:58 UTC, fauxpark commented on keyboards/xelus/dharma/readme.md
> +Hardware Availability: Custom keyboard group buys
```suggestion
* Keyboard Maintainer: [Xelus22](https://github.com/Xelus22)
* Hardware Supported: Dharma
* Hardware Availability: Custom keyboard group buys
```

2021-07-24 07:31 UTC, fauxpark approved these changes

2021-07-24 15:39 UTC, drashna commented
Thanks!

2021-07-24 15:39 UTC, merged