Add kbdfans kbd67 mkii rgb v3
qmk/qmk_firmware pull request #13714
Opened 2021-07-26 02:30 UTC by datafx

KBDFans released a new version of their kbd67 mkii rgb pcb.  The new board uses a different rgbmatrix driver so the entire setup for v1 and v2 need to be changed to allow this since all the versions could no longer share code.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-26 02:37 UTC, datafx commented
This board was designed by @moyi4681 so I don't know if he has a better implementation or suggestions for this PR.  I'm not sure if I should change the product id back to the default 0x0100 since that is what is in kbdfans VIA json they have on their website.  The rest of the boards were just incremented by one so that's what I did here.

2021-07-26 04:26 UTC, drashna requested changes

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v1/v1.c
> +#include "v1.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v1/v1.c
> +}
This is no longer needed, at all. 
```suggestion
```

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v1/v1.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v2/v2.c
> +#include "v2.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v2/v2.c
> +}
```suggestion
```

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v2/v2.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-07-26 04:26 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v3/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
```

2021-07-27 03:09 UTC, drashna requested changes

2021-07-27 03:09 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/mkiirgb.h
> +#endif
```suggestion
#if defined(KEYBOARD_kbdfans_kbd67_mkiirgb_v1)
    #include "v1.h"
#elif defined(KEYBOARD_kbdfans_kbd67_mkiirgb_v2
    #include "v2.h"
#elif defined(KEYBOARD_kbdfans_kbd67_mkiirgb_v3)
    #include "v3.h"
#endif
```

2021-07-27 03:09 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v2/rules.mk
> +FAUXCLICKY_ENABLE = no      # Use buzzer to emulate clicky switches
Please remove this.
```suggestion
```

2021-07-31 07:33 UTC, fauxpark requested changes

2021-07-31 07:33 UTC, fauxpark commented on keyboards/kbdfans/kbd67/mkiirgb/mkiirgb.h
> +#elif defined(KEYBOARD_kbdfans_kbd67_mkiirgb_v2
```suggestion
#elif defined(KEYBOARD_kbdfans_kbd67_mkiirgb_v2)
```

2021-07-31 07:33 UTC, fauxpark commented on keyboards/kbdfans/kbd67/mkiirgb/v1/rules.mk
> +LAYOUTS = 65_ansi_blocker
```suggestion
LAYOUTS = 65_ansi_blocker

```

2021-07-31 07:33 UTC, fauxpark commented on keyboards/kbdfans/kbd67/mkiirgb/v1/v1.c
> +    if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK))
```suggestion
    if (host_keyboard_led_state().caps_lock)
```

2021-07-31 07:33 UTC, fauxpark commented on keyboards/kbdfans/kbd67/mkiirgb/v2/v2.c
> +    if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK))
```suggestion
    if (host_keyboard_led_state().caps_lock)
```

2021-08-07 03:59 UTC, drashna approved these changes

2021-08-07 06:02 UTC, fauxpark approved these changes

2021-08-08 04:45 UTC, drashna commented
Thanks!

2021-08-08 04:45 UTC, merged