Hard Light Mark 2 and keymaps
qmk/qmk_firmware pull request #13719
Opened 2021-07-26 12:22 UTC by FateEverywhere

This time with minor competence!

## Description

I have learned what was causing a bunch of weird conflicting changes with prior PRs, and will adjust for this in future. Thanks in advance for your patience.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-27 01:05 UTC, drashna approved these changes

2021-07-31 07:30 UTC, fauxpark requested changes

2021-07-31 07:30 UTC, fauxpark commented on keyboards/edi/hardlight/mk2/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```suggestion
# MCU name
MCU = STM32F072

# Bootloader selection
Bootloader = stm32-dfu

# Wildcard to allow APM32 MCU 
DFU_SUFFIX_ARGS = -v FFFF -p FFFF

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
VELOCIKEY_ENABLE = yes
KEY_LOCK_ENABLE = yes
WS2812_DRIVER = pwm

# Layout definitions
LAYOUTS = ortho_4x16

# Enter lower-power sleep mode when on the ChibiOS idle thread
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```

2021-07-31 07:30 UTC, fauxpark commented on keyboards/edi/hardlight/mk2/keymaps/kate/config.h
> +/*
This file can be deleted.

2021-07-31 07:44 UTC, FateEverywhere commented on keyboards/edi/hardlight/mk2/keymaps/kate/config.h
> +/*
Done!

2021-09-19 19:29 UTC, fauxpark requested changes

2021-09-19 19:29 UTC, fauxpark commented on keyboards/edi/hardlight/mk2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-19 19:29 UTC, fauxpark commented on keyboards/edi/hardlight/mk2/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-19 19:29 UTC, fauxpark commented on keyboards/edi/hardlight/mk2/rules.mk
> +# Wildcard to allow APM32 MCU
```suggestion
# Wildcard to allow APM32 MCU
```

2022-01-07 20:14 UTC, noroadsleft approved these changes

2022-01-07 20:20 UTC, noroadsleft commented on keyboards/edi/hardlight/mk2/rules.mk
> +LAYOUTS = ortho_4x16
We don't actually have this but I think I'll add one.

2022-01-07 20:21 UTC, merged

2022-01-07 20:21 UTC, noroadsleft commented
Thanks!