Adding phrygian design ph100
qmk/qmk_firmware pull request #13738
Opened 2021-07-27 10:07 UTC by phrygiandesign

Adding the phrygian design ph100 into the mainline QMK repo

## Description

Addition of files and configuration for the [Phrygian Design ph100](https://phrygiandesign.com/products/ph100-mechanical-keyboard)

The ph100 board uses a STM32F042 microcontroller and provides 100 modular keyswitch positions.

I'm available to be contacted via github: @phrygiandesign or email: contact@phrygiandesign.com

2021-07-29 17:05 UTC, drashna requested changes

2021-07-29 17:05 UTC, drashna commented on keyboards/phrygian/ph100/readme.md
> +Keyboard support: contact@phrygiandesign.com
```suggestion
* Keyboard support: contact@phrygiandesign.com
```

2021-07-29 17:05 UTC, drashna commented on keyboards/phrygian/ph100/rules.mk
> +BOOTMAGIC_ENABLE = full     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```

2021-07-30 10:49 UTC, phrygiandesign commented
Commit your suggested changes, thanks for getting back quick btw.

2021-07-30 16:56 UTC, drashna commented on keyboards/phrygian/ph100/rules.mk
> +# Build Options
```suggestion
# Bootloader selection
BOOTLOADER = stm32-dfu

# Build Options
```

2021-08-07 04:41 UTC, drashna approved these changes

2021-09-21 23:47 UTC, drashna requested changes

2021-09-21 23:47 UTC, drashna commented on keyboards/phrygian/ph100/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-21 23:47 UTC, drashna commented on keyboards/phrygian/ph100/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-22 03:38 UTC, fauxpark requested changes

2021-09-22 03:38 UTC, fauxpark commented on keyboards/phrygian/ph100/bootloader_defs.h
> +/* Address for jumping to bootloader on STM32 chips. */
This file can be deleted.

2021-09-22 03:38 UTC, fauxpark commented on keyboards/phrygian/ph100/info.json
> +    "height": 6,
```suggestion
```

2021-09-23 07:30 UTC, phrygiandesign commented on keyboards/phrygian/ph100/bootloader_defs.h
> +/* Address for jumping to bootloader on STM32 chips. */
Deleted and committed to master

2021-09-23 07:31 UTC, phrygiandesign commented
Committed all suggestions, let me know if you need anything else. Keen to get this pulled finally

2021-09-23 07:35 UTC, fauxpark approved these changes

2021-09-24 07:24 UTC, drashna approved these changes

2021-09-24 07:25 UTC, merged