Ares refactor
qmk/qmk_firmware pull request #13730
Opened 2021-07-26 21:36 UTC by noroadsleft

## Description

- renames `LAYOUT` to `LAYOUT_all`
- adds `LAYOUT_60_ansi_split_bs_rshift` and `LAYOUT_60_hhkb` layouts, enables Community Layout support
- change Bootmagic Lite trigger key
- `default` keymap refactor
- readme touch-up

cc @evyd13 (original keyboard submitter)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-26 22:42 UTC, fauxpark requested changes

2021-07-26 22:42 UTC, fauxpark commented on keyboards/ares/rules.mk
> +
```
# MCU name
MCU = atmega32a

# Bootloader selection
BOOTLOADER = bootloadHID

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
WS2812_DRIVER = i2c
```

2021-07-27 00:57 UTC, noroadsleft commented on keyboards/ares/rules.mk
> +
[`983ea6a`](https://github.com/qmk/qmk_firmware/pull/13730/commits/983ea6a15e6d7d16c61ba6125166c663010b2f2b)

2021-07-27 00:58 UTC, fauxpark approved these changes

2021-07-27 02:43 UTC, drashna approved these changes

2021-07-27 02:43 UTC, merged