added n6 keyboard
qmk/qmk_firmware pull request #13768
Opened 2021-07-29 04:32 UTC by yulei

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-29 17:44 UTC, drashna commented
is there a reason this uses rgblight instead of rgb matrix?

2021-07-30 13:51 UTC, yulei commented
> is there a reason this uses rgblight instead of rgb matrix?

It's a seperate rgb bar, not the per key rgb led.

2021-07-30 16:12 UTC, drashna approved these changes

2021-07-30 16:12 UTC, drashna approved these changes

2021-07-30 16:17 UTC, fauxpark requested changes

2021-07-30 16:17 UTC, fauxpark commented on keyboards/neson_design/n6/rules.mk
> +SRC += i2c_master.c issi/is31fl3731.c
```suggestion
QUANTUM_LIB_SRC += i2c_master.c issi/is31fl3731.c
```

2021-07-30 16:17 UTC, fauxpark commented on keyboards/neson_design/n6/readme.md
> +    make inett_studio/n6:default
```suggestion
    make neson_design/n6:default
```

2021-08-15 04:25 UTC, fauxpark approved these changes

2021-08-17 16:06 UTC, drashna commented
Thanks!

2021-08-17 16:06 UTC, merged