Add bootloader section to keyboard template
qmk/qmk_firmware pull request #13774
Opened 2021-07-29 16:01 UTC by drashna

## Types of Changes

- [x] Core
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-07-31 07:19 UTC, fauxpark requested changes

2021-07-31 07:19 UTC, fauxpark commented on quantum/template/avr/readme.md
> +* Keycode in layout: Specifically, if there is a `RESET` keycode, and it's location.
```suggestion

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-07-31 07:19 UTC, fauxpark commented on quantum/template/ps2avrgb/readme.md
> +* Keycode in layout: Specifically, if there is a `RESET` keycode, and it's location.
```suggestion

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **BootloadHID reset**: Hold down the key connected to the `A0` and `B0` pins on the MCU if it is known (often top left or bottom left) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-07-31 16:10 UTC, fauxpark approved these changes

2021-08-04 00:23 UTC, zvecr approved these changes

2021-08-04 00:23 UTC, merged