Add superuser keyboard definitions.
qmk/qmk_firmware pull request #13840
Opened 2021-08-01 18:54 UTC by kaylanm

## Description

Add superuser tkl, ftl, ext keyboard definitions & default + via keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-07 05:04 UTC, drashna requested changes

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/config.h
> +#include "config_common.h"
```suggestion
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/config.h
> +/* USB Device descriptor parameter */
```suggestion
#pragma once

#include "config_common.h"

/* USB Device descriptor parameter */
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/ext.c
> +#include QMK_KEYBOARD_H
```suggestion
#include "ext.h"
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/readme.md
> +=============
```suggestion
# superuser ext
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/readme.md
> +Hardware Availability: Group buy
```suggestion
* Keyboard Maintainer: superuser
* Hardware Supported: superuser ext
* Hardware Availability: Group buy
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/ext/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/frl/config.h
> +#include "config_common.h"
```suggestion
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/frl/config.h
> +/* USB Device descriptor parameter */
```suggestion
#pragma once

#include "config_common.h"

/* USB Device descriptor parameter */
```

2021-08-07 05:04 UTC, drashna commented on keyboards/superuser/frl/frl.c
> +#include QMK_KEYBOARD_H
```suggestion
#include "fri.h"
```

2021-08-07 14:25 UTC, kaylanm commented
Thank you for reviewing @drashna! I've made your updates across the board.

2021-08-08 04:25 UTC, drashna approved these changes

2021-09-14 00:52 UTC, kaylanm commented
@drashna do I need to do anything else on this PR?

2021-09-14 01:31 UTC, fauxpark requested changes

2021-09-14 01:31 UTC, fauxpark commented on keyboards/superuser/tkl/info.json
> +    "height": 6.25,
```suggestion
```

2021-09-14 01:31 UTC, fauxpark commented on keyboards/superuser/frl/info.json
> +    "height": 5,
```suggestion
```

2021-09-14 01:31 UTC, fauxpark commented on keyboards/superuser/ext/info.json
> +    "height": 5,
```suggestion
```

2021-09-14 01:31 UTC, fauxpark commented on keyboards/superuser/tkl/rules.mk
> +LTO_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
```

2021-09-14 01:31 UTC, fauxpark commented on keyboards/superuser/frl/rules.mk
> +LTO_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
```

2021-09-14 01:31 UTC, fauxpark commented on keyboards/superuser/ext/rules.mk
> +LTO_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
```

2021-09-18 06:08 UTC, fauxpark approved these changes

2021-09-18 19:27 UTC, drashna commented
Thanks!

2021-09-18 19:27 UTC, merged