Ava initial commit
qmk/qmk_firmware pull request #13845
Opened 2021-08-02 00:45 UTC by SneakboxKB

Initial AVA firmware commit

First firmware submission for AVA keyboard

- [X] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-07 05:17 UTC, drashna requested changes

2021-08-07 05:17 UTC, drashna commented on keyboards/sneakbox/ava/ava.c
> +}
```suggestion
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index,clockwise)) { return false; }
    if (index == 0) { /* First encoder */
        if (clockwise) {
            tap_code(KC_DOWN);
        } else {
            tap_code(KC_UP);
        }
    } else if (index == 1) { /* Second encoder */
        if (clockwise) {
            tap_code(KC_DOWN);
        } else {
            tap_code(KC_UP);
        }
    }
    return true;
}

2021-08-07 05:17 UTC, drashna commented on keyboards/sneakbox/ava/config.h
> +#define RGB_DI_PIN F7
```suggestion
#define LED_NUM_LOCK_PIN  D4
#define LED_CAPS_LOCK_PIN D6

#define RGB_DI_PIN F7
```

2021-08-07 05:17 UTC, drashna commented on keyboards/sneakbox/ava/config.h
> +#define LOCKING_RESYNC_ENABLE
```suggestion
```

2021-08-07 05:17 UTC, drashna commented on keyboards/sneakbox/ava/config.h
> +#define RGBLIGHT_ANIMATIONS
could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-08-07 05:17 UTC, drashna commented on keyboards/sneakbox/ava/keymaps/default/keymap.c
> +}
```suggestion
```

2021-08-07 05:17 UTC, drashna commented on keyboards/sneakbox/ava/keymaps/via/keymap.c
> +}
```suggestion
```

2021-08-13 17:16 UTC, SneakboxKB reviewed
Reviewed and agree. Thanks!

2021-08-13 17:29 UTC, fauxpark requested changes

2021-08-13 17:29 UTC, fauxpark commented on keyboards/sneakbox/ava/readme.md
> +![Sneakbox AVA](https://i.imgur.com/lVaAmfS.jpg)
```suggestion
![Sneakbox AVA](https://i.imgur.com/lVaAmfSh.jpg)
```

2021-08-14 01:09 UTC, drashna approved these changes

2021-08-14 04:17 UTC, fauxpark requested changes

2021-08-14 04:17 UTC, fauxpark commented on keyboards/sneakbox/ava/info.json
> +      "LAYOUT_ava_split_bs": {
```suggestion
      "LAYOUT_alice_split_bs": {
```

2021-08-14 04:17 UTC, fauxpark commented on keyboards/sneakbox/ava/info.json
> +      "LAYOUT_ava": {
```suggestion
      "LAYOUT_alice": {
```

2021-08-14 07:05 UTC, fauxpark approved these changes

2021-08-19 18:58 UTC, drashna commented
Thanks!

2021-08-19 18:58 UTC, merged