Fave87
qmk/qmk_firmware pull request #13873
Opened 2021-08-03 21:27 UTC by ebastler

## Description

Adds support for the Linworks FAVE 87 PCB (used in multiple keyboards by Linworks)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for the Linworks FAVE 87 PCB 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-04 00:19 UTC, zvecr requested changes

2021-08-04 00:19 UTC, zvecr commented on keyboards/linworks/fave87/rules.mk
> +ENCODER_ENABLE = no         # Rotary encoder
```suggestion
```

2021-08-04 00:19 UTC, zvecr commented on keyboards/linworks/fave87/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion

# Bootloader selection
BOOTLOADER = atmel-dfu
```

2021-08-04 12:39 UTC, fauxpark approved these changes

2021-08-04 12:46 UTC, ebastler commented
The new commit was to address zvecr's second requested changes, after I accidentally commited only half of his changes.

2021-08-07 05:47 UTC, drashna approved these changes

2021-08-07 05:48 UTC, merged