Add kbd67 mkiirgb keymap
qmk/qmk_firmware pull request #13884
Opened 2021-08-04 14:08 UTC by pascalpfeil

## Description

Add kbd67 mkiirgb keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-07 14:55 UTC, Spaceman requested changes

2021-08-07 14:55 UTC, Spaceman commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/pascalpfeil/config.h
> +#endif
```suggestion
#endif

```

2021-08-07 14:55 UTC, Spaceman commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/pascalpfeil/rules.mk
> +LTO_ENABLE = yes
```suggestion
LTO_ENABLE = yes

```

2021-08-08 04:12 UTC, drashna requested changes

2021-08-08 04:12 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/keymaps/pascalpfeil/config.h
> +/* 1000Hz USB polling */
```suggestion
#pragma once

/* 1000Hz USB polling */
```

2021-08-09 06:10 UTC, drashna approved these changes

2021-08-09 06:12 UTC, fauxpark approved these changes

2021-08-09 17:04 UTC, drashna commented
Thanks!

2021-08-09 17:04 UTC, merged