Clean up lfkpad and add keymap
qmk/qmk_firmware pull request #13881
Opened 2021-08-04 13:47 UTC by pascalpfeil

## Description

Clean up lfkpad code and add my own keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-07 06:05 UTC, drashna requested changes

2021-08-07 06:05 UTC, drashna commented on keyboards/lfkeyboards/lfkpad/keymaps/pascalpfeil/config.h
> +/* 1000Hz USB polling */
```suggestion
#pragma once

/* 1000Hz USB polling */
```

2021-08-07 06:53 UTC, drashna approved these changes

2021-08-07 06:58 UTC, fauxpark approved these changes

2021-08-08 03:37 UTC, drashna commented
Thanks!

2021-08-08 03:37 UTC, merged