Add new keyboard - TouhouPad
qmk/qmk_firmware pull request #13915
Opened 2021-08-07 15:45 UTC by Pimentoso

## Description

Add support for the TouhouPad mechanical keypad.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-07 15:48 UTC, fauxpark requested changes

2021-08-07 15:48 UTC, fauxpark commented on keyboards/pimentoso/touhoupad/readme.md
> +![TouhouPad](https://imgur.com/a/jcuEr8q)
```suggestion
![TouhouPad](https://i.imgur.com/JeEqeEs.png)
```

2021-08-07 15:48 UTC, fauxpark commented on keyboards/pimentoso/touhoupad/readme.md
> +`make pimentoso/paddino02/rev2/right:default:flash`
```suggestion

Make example for this keyboard (after setting up your build environment):

    make pimentoso/touhoupad:default
```

2021-08-07 15:48 UTC, fauxpark commented on keyboards/pimentoso/touhoupad/keymaps/default/config.h
> +/* Copyright 2021 Michele Ferri <zomgsako@gmail.com>
This file can be deleted.

2021-08-07 15:48 UTC, fauxpark commented on keyboards/pimentoso/touhoupad/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-08-07 15:48 UTC, fauxpark commented on keyboards/pimentoso/touhoupad/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-08-08 04:11 UTC, drashna requested changes

2021-08-08 04:11 UTC, drashna commented on keyboards/pimentoso/touhoupad/config.h
> +  #define RGBLIGHT_ANIMATIONS
```suggestion
```

2021-08-09 06:08 UTC, drashna approved these changes

2021-08-09 06:13 UTC, fauxpark approved these changes

2021-08-09 17:03 UTC, drashna commented
Thanks!

2021-08-09 17:04 UTC, merged