add Wang V2 keyboard
qmk/qmk_firmware pull request #13948
Opened 2021-08-10 12:04 UTC by oceeean

## Description

add Wang V2, 40% ortholinear keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-11 02:23 UTC, drashna approved these changes

2021-08-11 05:44 UTC, fauxpark requested changes

2021-08-11 05:44 UTC, fauxpark commented on keyboards/ocean/wang_v2/wang_v2.h
> +  { K30, K31, K32, K33, KC_NO, K35,   K36, KC_NO, K38, K39, K3A, K3B }, \
```suggestion
  { K10, K11, K12, K13, K14,   K15,   K16, K17,   K18, K19, K1A, K1B, KC_NO }, \
  { K20, K21, K22, K23, K24,   K25,   K26, K27,   K28, K29, K2A, K2B, KC_NO }, \
  { K30, K31, K32, K33, KC_NO, K35,   K36, KC_NO, K38, K39, K3A, K3B, KC_NO }, \
```

2021-08-11 06:56 UTC, fauxpark requested changes

2021-08-11 07:39 UTC, fauxpark requested changes

2021-08-11 07:39 UTC, fauxpark commented on keyboards/ocean/wang_v2/readme.md
> +![Wang V2](https://media.discordapp.net/attachments/406032987243806721/859276477354868736/20210629_112245.jpg?width=1166&height=657)
Please rehost this on imgur.

2021-08-11 07:58 UTC, oceeean commented on keyboards/ocean/wang_v2/readme.md
> +![Wang V2](https://media.discordapp.net/attachments/406032987243806721/859276477354868736/20210629_112245.jpg?width=1166&height=657)
changed to imgur

2021-08-11 08:24 UTC, fauxpark approved these changes

2021-08-12 02:42 UTC, drashna approved these changes

2021-08-12 02:44 UTC, drashna commented
Thanks!

2021-08-12 02:44 UTC, merged

2021-08-12 03:16 UTC, oceeean commented
thank you ❤️