adding new keymap for the idobo keyboard with backlight
qmk/qmk_firmware pull request #13969
Opened 2021-08-11 16:14 UTC by pathnirvana

## Description

adding a new keymap for the idobo keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-12 02:19 UTC, drashna requested changes

2021-08-12 02:19 UTC, drashna commented on keyboards/idobo/keymaps/pathnirvana/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-12 14:19 UTC, drashna approved these changes

2021-08-12 18:04 UTC, fauxpark requested changes

2021-08-12 18:04 UTC, fauxpark commented on keyboards/idobo/keymaps/pathnirvana/rules.mk
> +MOUSEKEY_ENABLE = yes # enable mouse keys
```suggestion
BACKLIGHT_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
MOUSEKEY_ENABLE = yes
```

2021-08-12 18:18 UTC, fauxpark approved these changes

2021-08-13 18:30 UTC, drashna commented
Thanks!

2021-08-13 18:31 UTC, merged