[Keyboard] Add Frooastboard
qmk/qmk_firmware pull request #13970
Opened 2021-08-11 16:55 UTC by Frooastside

## Description

I added my own Keyboard to QMK.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Added Frooastboard

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-12 02:18 UTC, drashna requested changes

2021-08-12 02:18 UTC, drashna commented on keyboards/frooastboard/keymaps/via/config.h
> +#define RGBLIGHT_ANIMATIONS
could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

Also, in the via json you can specify which modes are enabled or not.

2021-08-12 02:18 UTC, drashna commented on keyboards/frooastboard/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
```

2021-08-12 02:18 UTC, drashna commented on keyboards/frooastboard/rules.mk
> +RGBLIGHT_ENABLE ?= yes     # Enable keyboard RGB underglow
```suggestion
BOOTMAGIC_ENABLE = lite   # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no      # Mouse keys
EXTRAKEY_ENABLE = no      # Audio control and System control
CONSOLE_ENABLE = no       # Console for debug
COMMAND_ENABLE = no       # Commands for debug and configuration
SLEEP_LED_ENABLE = no     # Breathing sleep LED during USB suspend
NKRO_ENABLE = yes         # USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = no     # Enable keyboard backlight functionality
AUDIO_ENABLE = no         # Audio output
BLUETOOTH_ENABLE = no     # Enable Bluetooth
RGBLIGHT_ENABLE = yes     # Enable keyboard RGB underglow
```

2021-08-12 14:24 UTC, drashna commented on keyboards/frooastboard/rules.mk
> +
```suggestion
# Bootloader selection
BOOTLOADER = atmel-dfu

```

2021-08-12 14:38 UTC, drashna approved these changes

2021-08-12 18:23 UTC, fauxpark approved these changes

2021-08-13 18:18 UTC, drashna approved these changes

2021-08-13 18:19 UTC, drashna commented
Thanks!

2021-08-13 18:21 UTC, merged