[Keymap]: Added Basketweave VIA keymap
qmk/qmk_firmware pull request #13972
Opened 2021-08-12 07:05 UTC by Vinna152

## Description

Added a basic keymap for via support on the Basketweave

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-12 14:25 UTC, drashna commented on keyboards/basketweave/keymaps/via/keymap.c
> +#include "basketweave.h"
```suggestion
#include QMK_KEYBOARD_H
```

2021-08-12 18:49 UTC, fauxpark requested changes

2021-08-12 18:49 UTC, fauxpark commented on keyboards/basketweave/keymaps/via/rules.mk
> +LTO_ENABLE          = yes
```suggestion
VIA_ENABLE = yes
LTO_ENABLE = yes
```

2021-08-13 03:25 UTC, fauxpark approved these changes

2021-08-13 18:21 UTC, merged