add rart75m keyboard and support via
qmk/qmk_firmware pull request #13975
Opened 2021-08-12 13:27 UTC by alabahuy

## Description

add new keyboard, rart75m. and support via

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-12 14:36 UTC, drashna approved these changes

2021-08-12 18:06 UTC, fauxpark requested changes

2021-08-12 18:06 UTC, fauxpark commented on keyboards/rart/rart75m/info.json
> +                {"x":16.75, "y":5.5 }
```suggestion
                {"x":16.75, "y":5.5 }
```

2021-08-12 18:06 UTC, fauxpark commented on keyboards/rart/rart75m/info.json
> +                {"x":14.5, "y":0},
```suggestion
                {"x":14.5, "y":0},
```

2021-08-12 18:06 UTC, fauxpark commented on keyboards/rart/rart75m/info.json
> +                {"x":0, "y":3.25},
```suggestion
                {"x":0, "y":3.25},
```

2021-08-12 23:04 UTC, alabahuy commented on keyboards/rart/rart75m/info.json
> +                {"x":0, "y":3.25},
done @fauxpark :)

2021-08-13 03:21 UTC, fauxpark approved these changes

2021-08-13 18:17 UTC, drashna approved these changes

2021-08-13 18:17 UTC, drashna commented
Thanks!

2021-08-13 18:18 UTC, merged