Add 3keyecosystem and 2key2 keyboard
qmk/qmk_firmware pull request #14023
Opened 2021-08-15 22:20 UTC by softplus

Added a new group ("3keyecosystem") and a 2x1 macro-keyboard there ("2key2").

## Description

I made a modular keyboard base-board and built a 2x1 macro-keyboard for it.
This includes a default and a "via" keymap for it.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-18 00:15 UTC, drashna requested changes

2021-08-18 00:15 UTC, drashna commented on keyboards/3keyecosystem/2key2/2key2.c
> +#include "quantum/rgb_matrix.h"
```suggestion
```

2021-08-18 00:15 UTC, drashna commented on keyboards/3keyecosystem/2key2/keymaps/default/keymap.c
> +#include "quantum.h"
```suggestion
```

2021-08-18 00:15 UTC, drashna commented on keyboards/3keyecosystem/2key2/keymaps/via/keymap.c
> +#include "quantum.h"
```suggestion
```

2021-08-18 00:15 UTC, drashna commented on keyboards/3keyecosystem/2key2/rules.mk
> +DEFAULT_FOLDER = 3keyecosystem/2key2
Move this entire file to the 2key2 folder, and you don't need this. 
```suggestion
```

2021-08-18 14:05 UTC, softplus commented
Thanks! Fixed.

2021-08-19 18:19 UTC, drashna requested changes

2021-08-19 18:19 UTC, drashna commented on keyboards/3keyecosystem/2key2/2key2.c
> +} };
```suggestion
#ifdef RGB_MATRIX_ENABLE
led_config_t g_led_config = { {
  // Key Matrix to LED Index
  {   0, 1 }
}, {
  // LED Index to Physical Position
  // Using range { 0..224, 0..64 }
  { 0,  32 }, { 224,  32 }
}, {
  // LED Index to Flag
  // https://docs.qmk.fm/#/feature_rgb_matrix?id=flags
  LED_FLAG_ALL, LED_FLAG_ALL
} };
#endif
```

2021-08-21 21:45 UTC, drashna approved these changes

2021-09-01 19:17 UTC, softplus commented
Just checking in here to see if I need to do something, or just be more patient :-). Thanks!

2021-09-11 05:23 UTC, fauxpark requested changes

2021-09-11 05:23 UTC, fauxpark commented on keyboards/3keyecosystem/2key2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-11 05:23 UTC, fauxpark commented on keyboards/3keyecosystem/2key2/rules.mk
> +
```suggestion
```

2021-09-11 05:23 UTC, fauxpark commented on keyboards/3keyecosystem/2key2/readme.md
> +    `make 3keyecosystem/2key2:default:flash`
```suggestion
    make 3keyecosystem/2key2:default

Flashing example for this keyboard:

    make 3keyecosystem/2key2:default:flash
```

2021-09-11 05:23 UTC, fauxpark commented on keyboards/3keyecosystem/2key2/info.json
> +    "height": 1,
```suggestion
```

2021-09-11 08:48 UTC, softplus commented
Thanks, updated!

2021-09-11 08:53 UTC, fauxpark approved these changes

2021-09-11 14:33 UTC, drashna commented
Thanks!n

2021-09-11 14:33 UTC, merged

2021-09-11 20:17 UTC, softplus commented
Thanks for the reviews, folks!