[Keyboard] adds new keyboard version: dztech/dz60rgb_wkl/v2_1
qmk/qmk_firmware pull request #14021
Opened 2021-08-15 14:49 UTC by trankimtung

New keyboard version: DZ60RGB-WKL v2_1

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-18 00:16 UTC, drashna approved these changes

2021-08-18 00:37 UTC, fauxpark requested changes

2021-08-18 00:37 UTC, fauxpark commented on keyboards/dztech/dz60rgb_wkl/readme.md
> +* V2.1: ATmega32U4 (AVR), takes .bin files [Flash Manual](https://docs.google.com/document/d/111qx6Qec4JqtIhWaZlMND-VuRnFtn9a-gJaHN8fsL7M/edit?usp=sharing)
```suggestion
* V2.1: ATmega32U4 (AVR), takes .bin files
```

2021-08-18 00:37 UTC, fauxpark commented on keyboards/dztech/dz60rgb_wkl/v2_1/rules.mk
> +NO_USB_STARTUP_CHECK = no      # Disable initialization only when usb is plugged in
```suggestion
```

2021-08-19 02:42 UTC, fauxpark approved these changes

2021-08-19 15:51 UTC, merged

2021-08-19 15:51 UTC, zvecr commented
Thanks!