Add MNK50
qmk/qmk_firmware pull request #14031
Opened 2021-08-16 13:09 UTC by yiancar

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-17 23:53 UTC, drashna requested changes

2021-08-17 23:53 UTC, drashna commented on keyboards/mnk50/rules.mk
> +# Do not put the microcontroller into power saving mode
```suggestion
# Bootloader selection
BOOTLOADER = stm32-dfu

# Do not put the microcontroller into power saving mode
```

2021-08-18 00:36 UTC, drashna approved these changes

2021-08-18 00:41 UTC, fauxpark requested changes

2021-08-18 00:41 UTC, fauxpark commented on keyboards/mnk50/rules.mk
> +NO_USB_STARTUP_CHECK = no   # Disable initialization only when usb is plugged in
```suggestion
```

2021-08-18 00:41 UTC, fauxpark commented on keyboards/mnk50/readme.md
> +    make mnK50:default
```suggestion
    make mnk50:default
```

2021-08-18 00:41 UTC, fauxpark commented on keyboards/mnk50/keymaps/default/readme.md
> +# The default keymap for MNK50. VIA support disabled.
```suggestion
# The default keymap for MNK50
```

2021-08-18 22:28 UTC, yiancar commented
I think we good now?:)

2021-08-19 02:42 UTC, fauxpark approved these changes

2021-08-19 15:53 UTC, zvecr approved these changes

2021-08-19 15:53 UTC, merged