Add h08_ocelot PCB
qmk/qmk_firmware pull request #14054
Opened 2021-08-18 03:13 UTC by hineybush

## Description

Firmware for the h08, currently only used on the upcoming version of the Singa Ocelot.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-18 17:24 UTC, drashna requested changes

2021-08-18 17:24 UTC, drashna commented on keyboards/hineybush/h65/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-08-18 17:24 UTC, drashna commented on keyboards/hineybush/h08_ocelot/readme.md
> +![h08](imgur.com image replace me!)
Image?

2021-08-18 17:24 UTC, drashna commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
You need to have 4 layers, or to have the define to limit it to 3 layers.

2021-09-01 08:50 UTC, hineybush commented on keyboards/hineybush/h08_ocelot/readme.md
> +Make example for this keyboard (after setting up your build environment):
do you mean something like "press the reset button"?

2021-09-01 08:54 UTC, hineybush commented
oh no i just realized i was on the wrong branch for the h08 stuff and it pushed all of my other in-development h65 stuff, help

2021-09-11 05:07 UTC, drashna commented on keyboards/hineybush/h08_ocelot/readme.md
> +Make example for this keyboard (after setting up your build environment):
Yup.

Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-11 05:08 UTC, drashna requested changes

2021-09-11 05:08 UTC, drashna commented on keyboards/hineybush/h65/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-11 05:08 UTC, drashna commented on keyboards/hineybush/h65_hotswap/readme.md
> +*A short description of the keyboard/project*
info for?

2021-09-11 05:08 UTC, drashna commented on keyboards/hineybush/h65_hotswap/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-11 05:08 UTC, drashna commented on keyboards/hineybush/h65_hotswap/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-11 05:08 UTC, drashna commented on keyboards/hineybush/h65/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-11 05:37 UTC, hineybush commented
@drashna finally made updates to this, lol

2021-11-15 02:30 UTC, drashna requested changes

2021-11-15 02:30 UTC, drashna commented on keyboards/hineybush/h65_hotswap/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-15 04:40 UTC, drashna approved these changes

2021-11-15 05:10 UTC, fauxpark requested changes

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/readme.md
> +![h65 hotswap](https://i.imgur.com/QKeHtDr.png)
```suggestion
![h65 hotswap](https://i.imgur.com/QKeHtDrh.png)
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/info.json
> +    "height": 2,
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/info.json
> +        }
This file needs to match the layout macros specified in the .h file.

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/readme.md
> +![h65](https://i.imgur.com/Q1m98Hn.png)
```suggestion
![h65](https://i.imgur.com/Q1m98Hnh.png)
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/info.json
> +    "height": 2,
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/info.json
> +        }
As above.

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/readme.md
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/info.json
> +    "height": 2,
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/info.json
> +        }
As above.

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/h08_ocelot.h
> +#define LAYOUT_ALL( \
```suggestion
#define LAYOUT( \
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/keymaps/default/keymap.c
> +    [_FN] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
        KC_1, KC_2, KC_3, KC_4,
        KC_5, KC_6, KC_7, MO(_FN)
    ),
    [_FN] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/keymaps/via/keymap.c
> +    [_FN3] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
        KC_1, KC_2, KC_3, KC_4,
        KC_5, KC_6, KC_7, MO(_FN)
    ),
    [_FN1] = LAYOUT(
        RGB_TOG, RGB_MOD, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )
    [_FN2] = LAYOUT(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )
    [_FN3] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/default/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/default/keymap.c
> +    [_FN] = LAYOUT_ALL(
```suggestion
    [_FN] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/default/keymap.c
> +}
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +    [_BASE] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +    [_FN1] = LAYOUT_ALL(
```suggestion
    [_FN1] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +    [_FN2] = LAYOUT_ALL(
```suggestion
    [_FN2] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +    [_BASE] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +    [_FN1] = LAYOUT_ALL(
```suggestion
    [_FN1] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +    [_FN2] = LAYOUT_ALL(
```suggestion
    [_FN2] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65/h65.h
> +#define LAYOUT_ALL( \
```suggestion
#define LAYOUT( \
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/keymaps/via/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h08_ocelot/keymaps/default/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +    [_BASE] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +    [_FN1] = LAYOUT_ALL(
```suggestion
    [_FN1] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +    [_FN2] = LAYOUT_ALL(
```suggestion
    [_FN2] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/default/keymap.c
> +}
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT_ALL(
```suggestion
    [_BASE] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/default/keymap.c
> +    [_FN] = LAYOUT_ALL(
```suggestion
    [_FN] = LAYOUT(
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/keymaps/default/keymap.c
> +
```suggestion
```

2021-11-15 05:10 UTC, fauxpark commented on keyboards/hineybush/h65_hotswap/h65_hotswap.h
> +#define LAYOUT_ALL( \
```suggestion
 * layout of the board and position of the keys.
 *
 * The second converts the arguments into a two-dimensional array which
 * represents the switch matrix.
 */
#define LAYOUT( \
```

2022-01-08 00:44 UTC, noroadsleft requested changes
All the suggestions here are basically:

* `rules.mk` clean-up to match QMK's template
* `#define DYNAMIC_KEYMAP_LAYER_COUNT 3` for VIA support
* rename the layout macros to `LAYOUT_all` because the boards support multiple layouts

GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/14054/files).

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/config.h
> +//#define BOOTMAGIC_LITE_COLUMN 0
```suggestion
//#define BOOTMAGIC_LITE_COLUMN 0

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/default/keymap.c
> +    [_FN] = LAYOUT(
```suggestion
    [_FN] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +    [_FN1] = LAYOUT(
```suggestion
    [_FN1] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/mc65/keymap.c
> +    [_FN2] = LAYOUT(
```suggestion
    [_FN2] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +    [_FN1] = LAYOUT(
```suggestion
    [_FN1] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/keymaps/via/keymap.c
> +    [_FN2] = LAYOUT(
```suggestion
    [_FN2] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/config.h
> +//#define BOOTMAGIC_LITE_COLUMN 0
```suggestion
//#define BOOTMAGIC_LITE_COLUMN 0

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/h65_hotswap.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_all( \
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/keymaps/default/keymap.c
> +    [_FN] = LAYOUT(
```suggestion
    [_FN] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +    [_FN1] = LAYOUT(
```suggestion
    [_FN1] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/keymaps/via/keymap.c
> +    [_FN2] = LAYOUT(
```suggestion
    [_FN2] = LAYOUT_all(
```

2022-01-08 00:44 UTC, noroadsleft commented on keyboards/hineybush/h65_hotswap/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-24 06:25 UTC, hineybush commented
Forgot I could push multiple suggestions on the files changed tab. oops lol

2022-02-20 08:13 UTC, noroadsleft approved these changes

2022-02-20 08:21 UTC, merged

2022-02-20 08:21 UTC, noroadsleft commented
Thanks!