[Keyboard] Add "Uno" rev2
qmk/qmk_firmware pull request #14071
Opened 2021-08-19 05:07 UTC by spencer-p

## Description

Adds support for the second revision of Uno, courtesy of @Snipeye.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- N/A I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-19 05:18 UTC, Snipeye commented
I was going to say something about modifying the default keymap, but then I saw that you put it as a "demo" keymap - really appreciate the work you put in, thank you.

2021-08-19 18:36 UTC, drashna approved these changes

2021-09-06 00:50 UTC, fauxpark requested changes

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/info.json
>      "height": 1,
```suggestion
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/info.json
> +        "key_count": 1,
```suggestion
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/readme.md
> +	make uno/rev2:default:flash
```suggestion
    make uno/rev2:default:flash
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/readme.md
> +Guide](https://docs.qmk.fm/#/newbs).
```suggestion
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/readme.md
> +	qmk new-keymap -kb uno/rev2
```suggestion
    qmk compile -kb uno/rev2 -km default

Create your own keymap with:

    qmk new-keymap -kb uno/rev2
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/rev1/config.h
> +#define DESCRIPTION     A one-key board for the lulz
```suggestion
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/rev1/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/rev1/rules.mk
> +HD44780_ENABLE = no         # Enable support for HD44780 based LCDs
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/rev2/config.h
> +#define DESCRIPTION     A one-key board for the lulz
```suggestion
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/rev2/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-09-06 00:50 UTC, fauxpark commented on keyboards/uno/rev2/rules.mk
> +ENCODER_ENABLE = yes        # Enable rotary encoder support for rev2.
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2021-09-06 03:44 UTC, spencer-p commented
@fauxpark Merged your changes and fixup'd into the original commit.

2021-09-11 05:22 UTC, fauxpark requested changes

2021-09-11 05:22 UTC, fauxpark commented on keyboards/uno/rev2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-11 05:22 UTC, fauxpark commented on keyboards/uno/rev1/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-15 05:09 UTC, drashna commented on keyboards/uno/uno.h
> +#endif
```suggestion
#if defined(KEYBOARD_uno_rev1)
#    include "rev1.h"
#elif defined(KEYBOARD_uno_rev2)
#    include "rev2.h"
#endif
```

2021-09-16 23:31 UTC, spencer-p commented
Committed all requested changes; Github still thinks @fauxpark changes are outstanding (??)

2021-11-06 04:16 UTC, spencer-p commented
@fauxpark Can you verify your requested changes have been accepted?

2021-11-06 04:41 UTC, fauxpark requested changes

2021-11-06 04:41 UTC, fauxpark commented on keyboards/uno/rev2/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
```

2021-11-06 04:41 UTC, fauxpark commented on keyboards/uno/rev1/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
```

2021-11-06 04:41 UTC, fauxpark commented on keyboards/uno/keymaps/demo/keymap.c
> +                        SEND_STRING(SS_TAP(X_ENTER)SS_TAP(X_ENTER)"I am uno!");
```suggestion
                        SEND_STRING("\n\nI am uno!");
```

2021-11-06 04:41 UTC, fauxpark commented on keyboards/uno/keymaps/demo/keymap.c
> +                        SEND_STRING(SS_TAP(X_ENTER)SS_TAP(X_ENTER)"I can do all sorts of useless things!");
```suggestion
                        SEND_STRING("\n\nI can do all sorts of useless things!");
```

2021-11-06 04:41 UTC, fauxpark commented on keyboards/uno/keymaps/demo/keymap.c
> +                        SEND_STRING(SS_TAP(X_ENTER)SS_TAP(X_ENTER)"And I have a built-in RGB LED!"SS_TAP(X_ENTER)SS_TAP(X_ENTER)SS_TAP(X_ENTER));
```suggestion
                        SEND_STRING("\n\nAnd I have a built-in RGB LED!\n\n\n");
```

2021-12-14 06:17 UTC, spencer-p commented
@fauxpark Can you confirm there are no outstanding changes required?

2021-12-14 07:19 UTC, fauxpark requested changes

2021-12-14 07:19 UTC, fauxpark commented on keyboards/uno/rev2/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-14 07:19 UTC, fauxpark commented on keyboards/uno/rev1/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-14 17:10 UTC, spencer-p commented
@fauxpark Done

2022-03-09 21:44 UTC, noroadsleft requested changes

2022-03-09 21:44 UTC, noroadsleft commented on keyboards/uno/info.json
> +    "keyboard_folder": "uno",
Use of `keyboard_folder` breaks the API that supports QMK Configurator.

```suggestion
```

2022-03-09 21:44 UTC, noroadsleft commented on keyboards/uno/rev1/config.h
> +#define PRODUCT         Uno
I prefer if the revisions are designated more specifically.

```suggestion
#define PRODUCT         Uno rev1
```

2022-03-09 21:44 UTC, noroadsleft commented on keyboards/uno/rev2/config.h
> +#define DEVICE_VER      0x0001
Changes the `DEVICE_VER` so it's different between rev1 and rev2.

```suggestion
#define DEVICE_VER      0x0002
```

2022-03-10 01:11 UTC, fauxpark requested changes

2022-03-10 01:11 UTC, fauxpark commented on keyboards/uno/rev2/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-03-10 01:11 UTC, fauxpark commented on keyboards/uno/rev1/config.h
> +
```suggestion
```

2022-03-11 18:14 UTC, spencer-p commented
@fauxpark @noroadsleft All suggested changes committed.

2022-03-13 21:30 UTC, noroadsleft approved these changes

2022-03-13 21:49 UTC, merged

2022-03-13 21:49 UTC, noroadsleft commented
Thanks!