added bongocat keymap to 0xCB Static
qmk/qmk_firmware pull request #14093
Opened 2021-08-20 20:12 UTC by Conor-Burns

## Description
Added bongocat animation with WPM counter.
Enabled by pressing ESC on layer 4 (toggles)

## Types of Changes

- [x] Keymap/layout/userspace (addition or update)

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.

- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).

- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-21 04:39 UTC, drashna requested changes

2021-08-21 04:39 UTC, drashna commented on keyboards/0xcb/static/keymaps/bongocat/keymap.c
> +  WPM
```suggestion
    WPM = SAFE_RANGE,
```

2021-08-21 04:39 UTC, drashna commented on keyboards/0xcb/static/keymaps/bongocat/keymap.c
> +return state;
```suggestion
    state = update_tri_layer_state(state, _FN2, _FN3, _FN4);
    return state;
```

2021-08-21 16:08 UTC, drashna commented
Also, it may be a good idea to run a format pass on these files. 
```sh
qmk cformat keyboards/0xcb/static/keymaps/bongocat/*
```

You may want to wrap the keymap itself and the animation chars with  `// clang-format off` and `// clang-format on` so it doesn't reformat those.

2021-08-21 16:08 UTC, drashna approved these changes

2021-08-21 23:37 UTC, Conor-Burns commented
> Also, it may be a good idea to run a format pass on these files.
> 
> ```shell
> qmk cformat keyboards/0xcb/static/keymaps/bongocat/*
> ```
> 
> You may want to wrap the keymap itself and the animation chars with `// clang-format off` and `// clang-format on` so it doesn't reformat those.

Ok thank you!

2021-08-22 04:08 UTC, fauxpark approved these changes

2021-08-22 05:11 UTC, merged