Fixed GMMK Pro -> stickandgum keymap readme.md
qmk/qmk_firmware pull request #14123
Opened 2021-08-23 03:21 UTC by stickandgum

Very minor edits to readme.md mostly to reflect NKRO no longer default.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-23 03:23 UTC, fauxpark requested changes

2021-08-23 03:23 UTC, fauxpark commented on keyboards/gmmk/pro/ansi/keymaps/stickandgum/config.h
> +/* Copyright 2021 stickandgum
Needs to use Unix line endings.

2021-08-23 03:23 UTC, fauxpark commented on keyboards/gmmk/pro/ansi/keymaps/stickandgum/readme.md
> +# Glorious GMMK Pro / ANSI - Enhanced Keyboard
Needs to use Unix line endings.

2021-08-23 03:23 UTC, fauxpark commented on keyboards/gmmk/pro/ansi/keymaps/stickandgum/rules.mk
> +CONSOLE_ENABLE = no
Needs to use Unix line endings.

2021-08-23 16:23 UTC, noroadsleft approved these changes

2021-08-24 08:12 UTC, fauxpark approved these changes

2021-08-24 08:48 UTC, drashna commented
Thanks!

2021-08-24 08:48 UTC, merged