Update info.json for ocean/gin_v2
qmk/qmk_firmware pull request #14121
Opened 2021-08-22 23:48 UTC by oceeean

## Description

Update info.json for ocean/gin_v2
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-23 01:39 UTC, drashna approved these changes

2021-08-23 03:27 UTC, fauxpark requested changes

2021-08-23 03:27 UTC, fauxpark commented on keyboards/ocean/gin_v2/info.json
>  }
```suggestion
    "keyboard_name": "Gin V2",
    "url": "",
    "maintainer": "Ocean",
    "width": 16.25,
    "height": 4,
    "layouts": {
        "LAYOUT": {
            "layout": [
                {"x": 0, "y": 0},
                {"x": 1, "y": 0},
                {"x": 2, "y": 0},
                {"x": 3.25, "y": 0},
                {"x": 4.25, "y": 0},
                {"x": 5.25, "y": 0},
                {"x": 6.25, "y": 0},
                {"x": 7.25, "y": 0},
                {"x": 8.25, "y": 0},
                {"x": 9.25, "y": 0},
                {"x": 10.25, "y": 0},
                {"x": 11.25, "y": 0},
                {"x": 12.25, "y": 0},
                {"x": 13.25, "y": 0},
                {"x": 14.25, "y": 0},
                {"x": 15.25, "y": 0},

                {"x": 0, "y": 1},
                {"x": 1, "y": 1},
                {"x": 2, "y": 1},
                {"x": 3.25, "y": 1, "w": 1.25},
                {"x": 4.5, "y": 1},
                {"x": 5.5, "y": 1},
                {"x": 6.5, "y": 1},
                {"x": 7.5, "y": 1},
                {"x": 8.5, "y": 1},
                {"x": 9.5, "y": 1},
                {"x": 10.5, "y": 1},
                {"x": 11.5, "y": 1},
                {"x": 12.5, "y": 1},
                {"x": 13.5, "y": 1},
                {"x": 14.5, "y": 1, "w": 1.75},

                {"x": 0, "y": 2},
                {"x": 1, "y": 2},
                {"x": 2, "y": 2},
                {"x": 3.25, "y": 2, "w": 1.75},
                {"x": 5, "y": 2},
                {"x": 6, "y": 2},
                {"x": 7, "y": 2},
                {"x": 8, "y": 2},
                {"x": 9, "y": 2},
                {"x": 10, "y": 2},
                {"x": 11, "y": 2},
                {"x": 12, "y": 2},
                {"x": 13, "y": 2},
                {"x": 14, "y": 2},
                {"x": 15, "y": 2, "w": 1.25},

                {"x": 0, "y": 3},
                {"x": 1, "y": 3},
                {"x": 2, "y": 3},
                {"x": 3.25, "y": 3, "w": 1.25},
                {"x": 4.5, "y": 3, "w": 1.25},
                {"x": 5.75, "y": 3, "w": 1.25},
                {"x": 7, "y": 3, "w": 2.25},
                {"x": 9.25, "y": 3, "w": 2.75},
                {"x": 12, "y": 3, "w": 1.25},
                {"x": 13.25, "y": 3},
                {"x": 14.25, "y": 3},
                {"x": 15.25, "y": 3}
            ]
        }
    }
}
```

2021-08-24 08:24 UTC, fauxpark approved these changes

2021-08-24 08:42 UTC, drashna commented
Thanks!

2021-08-24 08:42 UTC, merged