Add kelownaRGB64
qmk/qmk_firmware pull request #14141
Opened 2021-08-24 08:23 UTC by Weirdo-F

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-24 08:53 UTC, drashna requested changes

2021-08-24 08:53 UTC, drashna commented on keyboards/kelowna/rgb64/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, so that new firmware can be flashed.

2021-08-24 09:05 UTC, Weirdo-F commented on keyboards/kelowna/rgb64/readme.md
> +Make example for this keyboard (after setting up your build environment):
好的，已经做出修改。

2021-08-24 22:19 UTC, drashna commented on keyboards/kelowna/rgb64/rules.mk
> +LAYOUTS = 64_ansi
```suggestion
LAYOUTS = 64_ansi

```

2021-08-24 23:51 UTC, Weirdo-F commented on keyboards/kelowna/rgb64/rules.mk
> +LAYOUTS = 64_ansi
ok thanks！

2021-08-28 11:38 UTC, Weirdo-F commented
@drashna

2021-08-29 06:46 UTC, drashna approved these changes

2021-08-29 11:07 UTC, merged