New Keyboard - bstk100
qmk/qmk_firmware pull request #14158
Opened 2021-08-25 16:43 UTC by FREEWING-JP

## Description
Adding a new keyboard (bstk100) BUFFALO USB 10-Key keyboard BSTK100 and Pro Micro .

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 1st release of bstk100

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-07 08:59 UTC, noroadsleft requested changes
Just this; everything else looks good to me.

2022-01-07 08:59 UTC, noroadsleft commented on keyboards/handwired/bstk100/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-08 21:09 UTC, noroadsleft approved these changes

2022-01-08 21:13 UTC, merged

2022-01-08 21:13 UTC, noroadsleft commented
Thanks!

2022-01-09 02:57 UTC, FREEWING-JP commented
Thank You !