Adding a C64 Mini Keyboard product to Keyboards
qmk/qmk_firmware pull request #14159
Opened 2021-08-25 18:12 UTC by bleughb

Submitting a new c64 Mini keyboard matrix. This is for a Keyboard kit sold by Myself to upgrade the Small Commodore 64 Mini device to have a fully working keyboard.

## Description

No Changes to main code, just the addition of an extra keyboard product firmware / map

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 11:06 UTC, drashna requested changes

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/C64.h
> +) { \
This should be reformatted to match the layout of the keyboard, not the matrix. 

You can look at boards like the planck ez, gmmk pro and the like to see what I mean.

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/config.h
> +#define DESCRIPTION     USB Keyboard for the C64 Mini by Retrogames
```suggestion
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/config.h
> +#define CONFIG_H
```suggestion
#pragma once
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/config.h
> +
```suggestion
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/keymaps/default/keymap.c
> +#include "C64.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

```suggestion
#include QMK_KEYBOARD_H
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/keymaps/default/keymap.c
> +#define XXXXXXX KC_NO
These defines aren't necessary, as these are actually defined in the core.  You can safely remove them. 

https://github.com/qmk/qmk_firmware/blob/a0309db983150fd0197eb620a6ba552d90d29f93/quantum/quantum_keycodes.h#L30-L31


```suggestion
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/keymaps/default/keymap.c
> +#define _SHFT 	2
```suggestion
enum custom_layers {
    _QW,
    _ALT,
    _SHFT,
};
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/keymaps/default/keymap.c
> +};
```suggestion
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-08-29 11:06 UTC, drashna commented on keyboards/c64/rules.mk
> +LTO_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
EXTRAKEY_ENABLE = yes        # Audio control and System control
CONSOLE_ENABLE = yes         # Console for debug
COMMAND_ENABLE = yes         # Commands for debug and configuration
NKRO_ENABLE = no             # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
BACKLIGHT_ENABLE = no        # Enable keyboard backlight functionality
AUDIO_ENABLE = no            # Audio output
UNICODE_ENABLE = no          # Unicode
BLUETOOTH_ENABLE = no        # Enable Bluetooth
RGBLIGHT_ENABLE = no         # Enable WS2812 RGB underlight.

# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend

LTO_ENABLE = yes
```

2021-09-03 20:59 UTC, bleughb commented
HI, I deleted the old request fully, and have submitted a new one with i hope all the correct changes,
thankyou for your patience, i'm new at this :-)

2021-09-03 20:59 UTC, closed without merging