Add a mini keyboard: Dosa40RGB
qmk/qmk_firmware pull request #14175
Opened 2021-08-26 16:49 UTC by daotakisaac

## Description

Add a 40 percent keyboard: Dosa40RGB BLE

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 10:04 UTC, drashna requested changes

2021-08-29 10:04 UTC, drashna commented on keyboards/dtisaac/dosa40rgb/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED false // turn off effects when suspended
```suggestion
// #define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
```

2021-08-29 11:14 UTC, drashna approved these changes

2021-08-30 00:16 UTC, fauxpark requested changes

2021-08-30 00:16 UTC, fauxpark commented on keyboards/dtisaac/dosa40rgb/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
BLUETOOTH = AdafruitBLE     # Enable Bluetooth
```

2021-08-30 00:16 UTC, fauxpark commented on keyboards/dtisaac/dosa40rgb/readme.md
> +    make dosa40rgb:default:flash
```suggestion
    make dtisaac/dosa40rgb:default

Flashing example for this keyboard:

    make dtisaac/dosa40rgb:default:flash
```

2021-08-30 00:16 UTC, fauxpark commented on keyboards/dtisaac/dosa40rgb/keymaps/default/keymap.c
> + 	if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK))
```suggestion
 	if (host_keyboard_led_state().caps_lock)
```

2021-09-01 14:11 UTC, daotakisaac commented
Please help me check it again!!

2021-09-02 02:15 UTC, fauxpark requested changes

2021-09-02 02:15 UTC, fauxpark commented on keyboards/dtisaac/dosa40rgb/info.json
> +    "height": 4,
```suggestion
```

2021-09-03 14:03 UTC, daotakisaac commented
Please help me!!!

2021-09-05 08:46 UTC, daotakisaac commented
Bump again for review, thanks!

2021-09-09 14:27 UTC, daotakisaac commented
Does the file have any errors?
Please help me check it, thanks!

2021-09-16 09:53 UTC, daotakisaac commented
**### Hello, please help me!!!  I waited so long.......**

2021-09-17 04:29 UTC, drashna commented
This has a number of merge conflicts that need to be resolved.

2021-09-17 08:06 UTC, daotakisaac commented
Do not need to merge anymore

2021-09-17 08:06 UTC, closed without merging