[keyboard] Add hotswap YMDK Wings
qmk/qmk_firmware pull request #14176
Opened 2021-08-26 16:56 UTC by alittlepeace

Adding the YMDK Hotswap Wings

## Description

Adding a keyboard
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 09:50 UTC, drashna commented on keyboards/ymdk/wingshs/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-08-30 18:19 UTC, drashna approved these changes

2021-09-03 04:34 UTC, itsff commented
Hi @zvecr, how are we doing on this merge?

2021-09-11 06:02 UTC, fauxpark requested changes

2021-09-11 06:02 UTC, fauxpark commented on keyboards/ymdk/wingshs/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-11 06:02 UTC, fauxpark commented on keyboards/ymdk/wingshs/info.json
> +    "height": 5.25,
```suggestion
```

2021-09-11 08:50 UTC, fauxpark approved these changes

2021-09-11 14:33 UTC, drashna commented
Thanks!

2021-09-11 14:33 UTC, merged