Adalyn keyboard initial
qmk/qmk_firmware pull request #14184
Opened 2021-08-27 03:03 UTC by tominabox1

## Description

Initial support for Adalyn, an Alice-Like QAZ keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 11:51 UTC, drashna requested changes

2021-08-29 11:51 UTC, drashna commented on keyboards/adalyn/adalyn.c
> +#include "adalyn.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-29 11:51 UTC, drashna commented on keyboards/adalyn/adalyn.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-29 11:51 UTC, drashna commented on keyboards/adalyn/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-29 11:51 UTC, drashna commented on keyboards/adalyn/keymaps/default/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-29 11:51 UTC, drashna commented on keyboards/adalyn/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-08-29 11:51 UTC, drashna commented on keyboards/adalyn/rules.mk
> +COMBO_ENABLE = yes
```suggestion
```

2021-09-15 05:28 UTC, drashna requested changes

2021-09-15 05:28 UTC, drashna commented on keyboards/adalyn/keymaps/vial/config.h
> + /* Copyright TJ Campie
VIAL is not supported in the main repo, and the vial config and keymap should be removed.

2021-09-15 05:28 UTC, drashna commented on keyboards/adalyn/keymaps/vial/keymap.c
> + /* Copyright TJ Campie
VIAL is not supported in the main repo, and the vial config and keymap should be removed.

2021-09-15 05:28 UTC, drashna commented on keyboards/adalyn/keymaps/vial/rules.mk
> +VIA_ENABLE = yes
VIAL is not supported in the main repo, and the vial config and keymap should be removed.

2021-09-15 05:28 UTC, drashna commented on keyboards/adalyn/keymaps/vial/vial.json
> +
VIAL is not supported in the main repo, and the vial config and keymap should be removed.

2021-09-15 05:28 UTC, drashna commented on keyboards/adalyn/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-15 05:28 UTC, drashna commented on keyboards/adalyn/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-25 16:44 UTC, drashna approved these changes

2021-09-26 04:21 UTC, fauxpark requested changes

2021-09-26 04:21 UTC, fauxpark commented on keyboards/adalyn/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```

2021-09-26 04:21 UTC, fauxpark commented on keyboards/adalyn/info.json
> +  "height": 4,
```suggestion
```

2021-09-26 04:21 UTC, fauxpark commented on keyboards/adalyn/readme.md
> +Todo
```suggestion
![%KEYBOARD%](imgur.com image replace me!)

*A short description of the keyboard/project*

* Keyboard Maintainer: [%YOUR_NAME%](https://github.com/yourusername)
* Hardware Supported: *The PCBs, controllers supported*
* Hardware Availability: *Links to where you can find this hardware*

Make example for this keyboard (after setting up your build environment):

    make %KEYBOARD%:default

Flashing example for this keyboard:

    make %KEYBOARD%:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-07 03:05 UTC, noroadsleft approved these changes

2022-01-07 03:07 UTC, merged

2022-01-07 03:07 UTC, noroadsleft commented
Thanks!