add slamz keyboard
qmk/qmk_firmware pull request #14188
Opened 2021-08-27 15:19 UTC by oceeean

## Description

add slamz keyboard to qmk and via support
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 12:00 UTC, drashna approved these changes

2021-08-30 00:17 UTC, fauxpark requested changes

2021-08-30 00:17 UTC, fauxpark commented on keyboards/ocean/slamz/readme.md
> +
```suggestion
![Slamz](https://i.imgur.com/rWtHIfYh.jpeg)
```

2021-08-30 00:17 UTC, fauxpark commented on keyboards/ocean/slamz/keymaps/default/keymap.c
> +  ),
```suggestion
```

2021-08-30 01:03 UTC, fauxpark approved these changes

2021-08-30 18:28 UTC, drashna approved these changes

2021-08-30 18:28 UTC, drashna commented
Thanks!

2021-08-30 18:28 UTC, merged