Add OwLab Jelly Epoch
qmk/qmk_firmware pull request #14190
Opened 2021-08-27 16:27 UTC by kb-elmo

## Description

Added support for the two PCBs (hotswap and soldered) of the OwLab Jelly Epoch.
The original PR https://github.com/qmk/qmk_firmware/pull/13756 created for this board did not properly follow QMK standards and had quite a few errors in the code. It can be closed now.

(Also changed the manufacturer name for the Voice65 to match with this board)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 12:02 UTC, drashna approved these changes

2021-08-30 00:22 UTC, fauxpark requested changes

2021-08-30 00:22 UTC, fauxpark commented on keyboards/owlab/jelly_epoch/soldered/rules.mk
> +#   comment out to disable the options.
```suggestion
#   change yes to no to disable
```

2021-08-30 00:22 UTC, fauxpark commented on keyboards/owlab/jelly_epoch/hotswap/rules.mk
> +#   comment out to disable the options.
```suggestion
#   change yes to no to disable
```

2021-08-30 16:40 UTC, fauxpark approved these changes

2021-08-30 18:29 UTC, drashna commented
Thanks!

2021-08-30 18:29 UTC, merged