updates to own dactyl keymap
qmk/qmk_firmware pull request #14223
Opened 2021-08-29 16:55 UTC by cykedev

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 19:15 UTC, drashna approved these changes

2021-09-08 07:32 UTC, drashna approved these changes

2021-11-27 11:53 UTC, fauxpark requested changes

2021-11-27 11:53 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6_5/keymaps/cykedev/rules.mk
> +LTO_ENABLE          = no
```suggestion
MOUSEKEY_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
```

2021-11-28 06:58 UTC, drashna approved these changes

2021-11-28 06:59 UTC, drashna commented
This has some merge conflicts that need resolution.

2021-11-30 05:52 UTC, fauxpark approved these changes

2021-12-06 02:16 UTC, drashna commented
This has a merge conflict that needs to be fixed before we can merge it.

2021-12-06 07:24 UTC, cykedev commented
conflict has been resolved

2021-12-06 17:12 UTC, merged