[Keymap]Addition of VIA keymap and a few fixes for naked48
qmk/qmk_firmware pull request #14225
Opened 2021-08-29 17:46 UTC by Salicylic-acid3

1.Addition of VIA keymap
2.Addition of rules.mk options
3.Change VID/PID
4.Update copywrite

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 21:36 UTC, zvecr requested changes

2021-08-29 21:36 UTC, zvecr commented on keyboards/naked60/rev1/rev1.h
> +#endif
```suggestion
```

2021-08-29 21:36 UTC, zvecr commented on keyboards/naked60/keymaps/via/rules.mk
> +SPLIT_KEYBOARD = no
Not sure why you would want to disable this
```suggestion
```

2021-08-30 19:06 UTC, zvecr approved these changes

2021-08-30 23:15 UTC, fauxpark approved these changes

2021-08-31 05:18 UTC, drashna approved these changes

2021-08-31 05:19 UTC, merged