Documentation: Fix links in key overrides
qmk/qmk_firmware pull request #14228
Opened 2021-08-29 21:50 UTC by coliss86

## Description

This is a fix for the links in the documentation of the feature key overrides.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 22:19 UTC, zvecr requested changes

2021-08-29 22:19 UTC, zvecr commented on docs/feature_key_overrides.md
> +The [Grave Escape feature](https://docs.qmk.fm/#/feature_grave_esc) is limited in its configurability and has [bugs when used on macOS](https://docs.qmk.fm/#/feature_grave_esc?id=caveats). Key overri
```suggestion
The [Grave Escape feature](feature_grave_esc.md) is limited in its configurability and has [bugs when used on macOS](feature_grave_esc.md#caveats). Key overrides can be used to achieve a similar functionality as Grave Escape, but with more customization and without bugs on macOS.
```

2021-08-30 09:39 UTC, coliss86 commented on docs/feature_key_overrides.md
> +The [Grave Escape feature](https://docs.qmk.fm/#/feature_grave_esc) is limited in its configurability and has [bugs when used on macOS](https://docs.qmk.fm/#/feature_grave_esc?id=caveats). Key overri
Thanks

2021-08-30 19:01 UTC, zvecr approved these changes

2021-08-30 23:13 UTC, fauxpark approved these changes

2021-08-30 23:13 UTC, merged