own scylla keymap
qmk/qmk_firmware pull request #14224
Opened 2021-08-29 16:55 UTC by cykedev

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-29 19:14 UTC, drashna requested changes

2021-08-29 19:14 UTC, drashna commented on keyboards/bastardkb/scylla/keymaps/cykedev/rules.mk
> +SPLIT_KEYBOARD      = yes     # Split Keyboard
You only need to include what the keyboard doesn't have set the same. 

```suggestion
MOUSEKEY_ENABLE     = no      # Mouse keys
NKRO_ENABLE         = yes     # USB Nkey Rollover
RGB_MATRIX_ENABLE   = no      # Enable keyboard RGB matrix
KEY_OVERRIDE_ENABLE = yes     # Enable Key Overrides, see https://docs.qmk.fm/#/feature_key_overrides
```

2021-08-31 18:59 UTC, drashna approved these changes

2021-08-31 22:48 UTC, fauxpark approved these changes

2021-09-02 03:40 UTC, drashna commented
Thanks!

2021-09-02 03:41 UTC, merged