Keyboard/miniashen40
qmk/qmk_firmware pull request #14238
Opened 2021-08-30 07:39 UTC by jfescobar18

## Description

New keyboard added, already tested and working with physical device, and functional prototype

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-30 18:56 UTC, zvecr requested changes

2021-08-30 18:56 UTC, zvecr commented on keyboards/mechanickeys/miniashen40/README.md
> +    make miniashen40/:default
```suggestion
    make mechanickeys/miniashen40:default
```

2021-08-30 18:56 UTC, zvecr commented on keyboards/mechanickeys/miniashen40/README.md
> +    make miniashen40:default:flash
```suggestion
    make mechanickeys/miniashen40:default:flash
```

2021-08-30 18:56 UTC, zvecr commented on keyboards/mechanickeys/miniashen40/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
# MCU name
MCU = atmega328p

# Bootloader selection
BOOTLOADER = USBasp

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-08-31 22:10 UTC, drashna requested changes

2021-08-31 22:10 UTC, drashna commented on keyboards/mechanickeys/miniashen40/README.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-02 04:05 UTC, drashna approved these changes

2021-09-02 04:08 UTC, fauxpark requested changes

2021-09-02 04:08 UTC, fauxpark commented on keyboards/mechanickeys/miniashen40/info.json
> +  "height": 4.25,
```suggestion
```

2021-11-02 15:52 UTC, jfescobar18 commented
Any updated on this?

2021-11-17 09:27 UTC, jfescobar18 commented
@drashna  @fauxpark @zvecr 

Any update??

2021-11-19 05:03 UTC, drashna commented
Sorry about that.

And thanks!

2021-11-19 05:03 UTC, merged