add wang ergo to qmk
qmk/qmk_firmware pull request #14245
Opened 2021-08-30 23:40 UTC by oceeean

## Description

add wang ergo keyboard to qmk
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-31 22:32 UTC, drashna approved these changes

2021-09-02 04:07 UTC, drashna approved these changes

2021-09-02 04:09 UTC, fauxpark requested changes

2021-09-02 04:09 UTC, fauxpark commented on keyboards/ocean/wang_ergo/readme.md
> +![Wang Ergo](https://i.imgur.com/vsYWYfx.jpeg)
```suggestion
![Wang Ergo](https://i.imgur.com/vsYWYfxh.jpeg)
```

2021-09-04 12:44 UTC, oceeean commented
could you check the changes you requested? @fauxpark

2021-09-04 13:56 UTC, fauxpark approved these changes

2021-09-05 21:59 UTC, oceeean commented
thank you 😁

2021-09-06 21:48 UTC, oceeean commented
i misclicked :(

2021-09-08 04:06 UTC, drashna approved these changes

2021-09-08 04:06 UTC, drashna commented
Thanks!

2021-09-08 04:07 UTC, merged