Change keyboard level include guards to `pragma once`
qmk/qmk_firmware pull request #14248
Opened 2021-08-31 05:07 UTC by fauxpark

## Description

And clean up a lot of layout macros.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-31 05:32 UTC, drashna approved these changes

2021-08-31 05:59 UTC, fauxpark commented
Lint errors are all non-assignment stuff from rules.mk.

2021-08-31 20:17 UTC, noroadsleft requested changes
* `keyboards/bigseries/3key/config.h`: Lines 58-59 should be deleted.

2021-09-01 05:37 UTC, noroadsleft approved these changes

2021-09-01 09:03 UTC, tzarc approved these changes

2021-09-01 09:03 UTC, merged