Version 2 of Draytronics Elise Keyboard + ISO Keymap Change
qmk/qmk_firmware pull request #14253
Opened 2021-08-31 15:52 UTC by ghostseven

Add v2 of the Draytronics Elise PCB and tweak ISO keyboard layout. 

## Description

Adding version 2 of the Draytronics Elise keyboard, this version has 16 underglow LEDs that are more evenly distributed than the original.  There is also a tweak to the original Draytronics ELISE Blake IOS keycap. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-31 22:56 UTC, drashna requested changes

2021-08-31 22:56 UTC, drashna commented on keyboards/draytronics/elise_v2/config.h
> +  #define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-09-08 04:04 UTC, drashna approved these changes

2021-09-08 04:04 UTC, drashna commented on keyboards/draytronics/elise_v2/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-19 20:08 UTC, ghostseven commented
Anything else required to get this over the line? Thanks

2021-09-21 21:47 UTC, drashna commented
Yup, usually, we want 2 reviews before the PR is merged

2021-09-21 21:48 UTC, drashna requested changes

2021-09-21 21:48 UTC, drashna commented on keyboards/draytronics/elise_v2/info.json
> +    "height": 5,
```suggestion
```

2021-09-21 23:42 UTC, drashna approved these changes

2021-09-22 03:40 UTC, fauxpark requested changes

2021-09-22 03:40 UTC, fauxpark commented on keyboards/draytronics/elise_v2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-22 06:21 UTC, fauxpark approved these changes

2021-09-22 06:49 UTC, drashna commented
Thanks!

2021-09-22 06:49 UTC, merged