owl8: add info.json file
qmk/qmk_firmware pull request #14256
Opened 2021-08-31 18:47 UTC by noroadsleft

## Description

[title]

cc @yfuku (keyboard maintainer)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-08-31 22:45 UTC, fauxpark requested changes

2021-08-31 22:45 UTC, fauxpark commented on keyboards/owl8/info.json
> +    "height": 4,
```suggestion
```

2021-09-01 00:01 UTC, fauxpark approved these changes

2021-09-01 12:20 UTC, zvecr approved these changes

2021-09-01 12:20 UTC, merged