Matrix Falcon info.json fixes
qmk/qmk_firmware pull request #14273
Opened 2021-09-02 09:15 UTC by noroadsleft

## Description

* add data for `LAYOUT_all` macro
* update labels for `LAYOUT_60_hhkb` macro
* update maintainer field to use GitHub username
* trim trailing whitespace

cc @yulei (keyboard maintainer)

## Issues Fixed or Closed by This PR

* Fixes improper display of `LAYOUT_all` in QMK Configurator:
  ![image](https://user-images.githubusercontent.com/18669334/131817375-3479b180-ac3a-4f41-aed6-662ef6db7c14.png)

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-02 09:16 UTC, fauxpark requested changes

2021-09-02 09:16 UTC, fauxpark commented on keyboards/matrix/falcon/info.json
> +    "height": 5,
```suggestion
```

2021-09-02 17:01 UTC, fauxpark approved these changes

2021-09-02 17:09 UTC, merged

2021-09-15 23:40 UTC, yulei commented
> ## Description
> * add data for `LAYOUT_all` macro
> * update labels for `LAYOUT_60_hhkb` macro
> * update maintainer field to use GitHub username
> * trim trailing whitespace
> 
> cc @yulei (keyboard maintainer)
> 
> ## Issues Fixed or Closed by This PR
> * Fixes improper display of `LAYOUT_all` in QMK Configurator:
>   ![image](https://user-images.githubusercontent.com/18669334/131817375-3479b180-ac3a-4f41-aed6-662ef6db7c14.png)
> 
> ## Types of Changes
> * [x]  Enhancement/optimization
> * [x]  Keyboard (addition or update)
> 
> ## Checklist
> * [x]  My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
> * [x]  I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
> * [x]  I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
> * [x]  I have tested the changes and verified that they work and don't break anything (as well as I can manage).



> ## Description
> * add data for `LAYOUT_all` macro
> * update labels for `LAYOUT_60_hhkb` macro
> * update maintainer field to use GitHub username
> * trim trailing whitespace
> 
> cc @yulei (keyboard maintainer)
> 
> ## Issues Fixed or Closed by This PR
> * Fixes improper display of `LAYOUT_all` in QMK Configurator:
>   ![image](https://user-images.githubusercontent.com/18669334/131817375-3479b180-ac3a-4f41-aed6-662ef6db7c14.png)
> 
> ## Types of Changes
> * [x]  Enhancement/optimization
> * [x]  Keyboard (addition or update)
> 
> ## Checklist
> * [x]  My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
> * [x]  I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
> * [x]  I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
> * [x]  I have tested the changes and verified that they work and don't break anything (as well as I can manage).

Seems the same issue occurs after merged the Matrix/Me, but I don't know the root cause.