Add RGBW support to PWM and SPI drivers for ChibiOS
qmk/qmk_firmware pull request #14327
Opened 2021-09-06 06:04 UTC by drashna

## Description

Adds support for RGBW LEDs to the PWM and SPI Drivers for ChibiOS. 

PWM driver has support added upstream, so mirrors that. 
SPI driver doesn't, but appears to be able to support it, with minimal modification. 

Todo: Test changes.

## Types of Changes

- [x] Core
- [x] Enhancement/optimization

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-06 06:48 UTC, fauxpark requested changes

2021-09-06 06:48 UTC, fauxpark commented on platforms/chibios/drivers/ws2812_pwm.c
> +#    define WS2812_COLOR_N 3
```suggestion
#    define WS2812_CHANNELS 4
#else
#    define WS2812_CHANNELS 3
```

2021-09-06 06:48 UTC, fauxpark commented on platforms/chibios/drivers/ws2812_pwm.c
> +#define WS2812_COLOR_BITS (WS2812_COLOR_N * 8)
```suggestion
#define WS2812_COLOR_BITS (WS2812_CHANNELS * 8)
```

2021-09-06 06:48 UTC, fauxpark commented on platforms/chibios/drivers/ws2812_spi.c
>  #define BYTES_FOR_LED (BYTES_FOR_LED_BYTE * NB_COLORS)
```suggestion
#    define WS2812_CHANNELS 4
#else
#    define WS2812_CHANNELS 3
#endif
#define BYTES_FOR_LED (BYTES_FOR_LED_BYTE * WS2812_CHANNELS)
```

2021-09-08 02:43 UTC, fauxpark approved these changes

2021-09-18 07:28 UTC, tzarc approved these changes

2021-09-18 07:28 UTC, merged