3w6/rev1 - Refactor use of AVR only I2C functions
qmk/qmk_firmware pull request #14339
Opened 2021-09-06 22:37 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-06 23:15 UTC, fauxpark approved these changes

2021-09-07 06:15 UTC, sigprof requested changes

2021-09-07 06:15 UTC, sigprof commented on keyboards/3w6/rev1/matrix.c
> +    tca9555_status = i2c_writeReg(IODIRA, IODIRA, conf, 2, I2C_TIMEOUT);
```suggestion
    tca9555_status = i2c_writeReg(I2C_ADDR, IODIRA, conf, 2, I2C_TIMEOUT);
```

2021-09-07 13:49 UTC, zvecr commented on keyboards/3w6/rev1/matrix.c
> +    tca9555_status = i2c_writeReg(IODIRA, IODIRA, conf, 2, I2C_TIMEOUT);
Good catch!

2021-09-07 15:35 UTC, merged