[Keyboard] Add custom pcb for Polaris
qmk/qmk_firmware pull request #14347
Opened 2021-09-08 02:14 UTC by uybv

## Description

Custom PCB for Polaris

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-08 03:01 UTC, drashna commented on keyboards/wekey/polaris/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-09 01:22 UTC, drashna approved these changes

2021-09-09 01:29 UTC, fauxpark requested changes

2021-09-09 01:29 UTC, fauxpark commented on keyboards/wekey/polaris/info.json
> +    "height": 5,
```suggestion
```

2021-09-09 13:11 UTC, fauxpark approved these changes

2021-09-09 17:02 UTC, merged