Add mokey63
qmk/qmk_firmware pull request #14357
Opened 2021-09-09 03:25 UTC by rhmokey

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-09 03:53 UTC, drashna requested changes

2021-09-09 03:53 UTC, drashna commented on keyboards/mokey/mokey63/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2021-09-09 04:32 UTC, rhmokey commented
mokey63 also needs to be merged, thank you

2021-09-09 05:08 UTC, drashna approved these changes

2021-09-09 05:34 UTC, rhmokey commented
Need to merge, thank you

2021-09-09 16:45 UTC, drashna approved these changes

2021-09-10 03:05 UTC, fauxpark approved these changes

2021-09-10 21:29 UTC, rhmokey commented
Need to merge, thank you

2021-09-11 06:24 UTC, merged

2021-09-13 02:43 UTC, Xelus22 commented
Mokey63 is broken with both the default and VIA keymaps.