Initial keymap creation
qmk/qmk_firmware pull request #14353
Opened 2021-09-09 01:44 UTC by masoncowen

## Description
Initial keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-11 06:08 UTC, drashna requested changes

2021-09-11 06:08 UTC, drashna commented on keyboards/planck/keymaps/masoncowen/readme.md
> +# The Default Planck Layout
This file can/should be removed

2021-09-11 06:08 UTC, drashna commented on keyboards/planck/keymaps/masoncowen/rules.mk
> +SRC += muse.c
This file can/should be removed

2021-09-11 06:08 UTC, drashna commented on keyboards/planck/keymaps/masoncowen/keymap.c
> +[_ZWFP] = LAYOUT_planck_grid(
```suggestion
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  LAYOUT_planck_grid(
```

2021-09-17 04:38 UTC, drashna approved these changes

2021-09-18 06:13 UTC, fauxpark requested changes

2021-09-18 06:13 UTC, fauxpark commented on keyboards/planck/keymaps/masoncowen/config.h
> +/* Copyright %YEAR% %YOUR_NAME%
Please fill this out.

2021-09-18 06:13 UTC, fauxpark commented on keyboards/planck/keymaps/masoncowen/config.h
> +
```suggestion
```

2021-09-18 06:13 UTC, fauxpark commented on keyboards/planck/keymaps/masoncowen/keymap.c
> +/* Copyright 2015-2017 Jack Humbert
Should update this as well.

2021-09-19 18:24 UTC, masoncowen commented
Did a git rebase trying to get rid of the merge commits, should I copy my changes to a fresh branch of master and make a new pull request?

2021-09-21 21:23 UTC, drashna commented
> Did a git rebase trying to get rid of the merge commits, should I copy my changes to a fresh branch of master and make a new pull request?

Looks like the rebase messed up?  Not sure why.   I've rebased the PR for you, and that has corrected the issue.

2021-09-22 03:41 UTC, fauxpark requested changes

2021-09-22 03:41 UTC, fauxpark commented on keyboards/planck/keymaps/masoncowen/config.h
> +/* Copyright 2021 masoncowen
This file can be deleted.

2021-09-23 15:08 UTC, masoncowen commented
Sorry it happened again.
I had to pull from my own repo, I assume for the rebase drashna did.
I entered git rebase (no repo after rebase) to try get rid of the merge commit.
Not sure what I'm meant to do there, I'll just leave the merge commits from now on.

2021-09-24 07:31 UTC, drashna commented
> Sorry it happened again.
> I had to pull from my own repo, I assume for the rebase drashna did.
> I entered git rebase (no repo after rebase) to try get rid of the merge commit.
> Not sure what I'm meant to do there, I'll just leave the merge commits from now on.

Are you using an app (such as github desktop) to help manage the repo?  if so, it can cause issues with syncing.

2021-09-24 12:33 UTC, masoncowen commented
> > Sorry it happened again.
> > I had to pull from my own repo, I assume for the rebase drashna did.
> > I entered git rebase (no repo after rebase) to try get rid of the merge commit.
> > Not sure what I'm meant to do there, I'll just leave the merge commits from now on.
> 
> Are you using an app (such as github desktop) to help manage the repo? if so, it can cause issues with syncing.

No, purely using git on the command line.

2022-01-06 05:11 UTC, fauxpark approved these changes

2022-01-07 05:25 UTC, merged