Multiple personal layout keyboards and support for ZlantXL keyboard and dz60rgb_ansi new bootloader
qmk/qmk_firmware pull request #14376
Opened 2021-09-10 15:16 UTC by ChrisGVE

The pull request includes layouts (chrisgve) for several keyboards
- cannonkeys/savage65
- dz60
- dz60rgb_ansi
- dz60rgb
- dz65rgb
- preonic
- zlant XL

Additionally it includes support for the ZlantXL keyboard and for the new version of the bootloader used with dz60rgb_ansi keyboard (now requires .bin files instead of the .hex)

## Description

All the layouts include a vim-like navigation: hold D to get HJKL navigation, hold D and F to get HJKL as Home/PgDn/PgUp/End. This is included for layout that have navigation keys to bring the flexibility of quick navigation while typing.

The Ortho layouts are designed to remain very close to traditional keyboards (e.g. 2 shift keys) to facilitate the transition from traditional to ortho. The layout flavor is rather for coders since the backslash key is accessible without mod for vim users.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-11 06:57 UTC, drashna requested changes

2021-09-11 06:57 UTC, drashna commented on keyboards/dz60/keymaps/chrisgve_split_spacebar/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-11 06:57 UTC, drashna commented on keyboards/dztech/dz60rgb/keymaps/chrisgve/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-11 06:57 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/keymaps/chrisgve/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-11 06:57 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-11 06:57 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/rules.mk
> +#BOOTLOADER = atmel-dfu
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes         # Enable Bootmagic Lite
```

2021-09-11 06:57 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/rules.mk
> +AUDIO_ENABLE = no              # Audio output on port C6
```suggestion
AUDIO_ENABLE = no              # Audio output
```

2021-09-11 06:57 UTC, drashna commented on keyboards/preonic/keymaps/chrisgve/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-11 06:57 UTC, drashna commented on keyboards/preonic/keymaps/chrisgve/keymap.c
> +      unregister_code(KC_PGUP);
```suggestion
      tap_code(KC_PGDN);
    } else {
      tap_code(KC_PGUP);
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/config.h
> +#define DESCRIPTION     A custom keyboard
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/config.h
> +//#define MAGIC_KEY_SLEEP_LED      Z
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/config.h
> +*/
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/keymaps/default/keymap.c
> +}
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/rules.mk
> +TAP_DANCE_ENABLE=yes
```suggestion
# MCU name
#MCU = atmega32u2

# Bootloader selection
BOOTLOADER = halfkay

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes

SRC = vimmode.c
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/vimmode.h
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/vimmode.h
> +#define VIMMOD_H
```suggestion
#pragma once
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/vimmode.h
> +#endif
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/zindar12x5.c
> +}
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5_chris/config.h
> +#define DESCRIPTION     A custom keyboard
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5/zindar12x5.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_ortho_5x12( \
```
This would require changes to the keymaps too

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5_chris/config.h
> +//#define MAGIC_KEY_SLEEP_LED      Z
```suggestion
```

2021-09-11 06:57 UTC, drashna commented on keyboards/zindar12x5_chris/config.h
> +*/
```suggestion
```

2021-09-12 04:02 UTC, ChrisGVE commented on keyboards/zindar12x5_chris/config.h
> +*/
Requested changes made, an obsolete keyboard was also removed.

2021-09-18 19:12 UTC, drashna requested changes

2021-09-18 19:12 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2021-09-18 19:12 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/config.h
> +#    define DRIVER_LED_TOTAL DRIVER_1_LED_TOTAL
```suggestion
```

2021-09-18 19:12 UTC, drashna commented on keyboards/dztech/dz60rgb_ansi/v2_1_chrisgve/rules.mk
> +# MCU name
You only need what is changed, not the entire contents

2021-09-18 19:12 UTC, drashna commented on keyboards/preonic/keymaps/chrisgve/rules.mk
> +//TAP_DANCE_ENABLE = yes      # Enable tap dance
```suggestion
#TAP_DANCE_ENABLE = yes      # Enable tap dance
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/keymaps/default/keymap.c
> +/*}*/
```suggestion
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/config.h
> +/*== or choose animations ==*/
```suggestion
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/keymaps/default/keymap.c
> +#include "kb.h"
```suggestion
#include QMK_KEYBOARD_H
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/rules.mk
> +src = zlant_xl.c
```suggestion
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-18 19:12 UTC, drashna commented on keyboards/zlant_xl/keymaps/default/keymap.c
> +	[BASE] = LAYOUT(KC_ESC, KC_2, KC_4, KC_6, KC_8, KC_0,
This needs to be reformatted

2021-11-28 06:58 UTC, drashna commented
Could you pull out the core code change into its own PR?
https://docs.qmk.fm/#/contributing?id=general-guidelines

> Separate PRs into logical units. For example, do not submit one PR covering two separate features, instead submit a separate PR for each feature.

To clarify, we absolutely appreciate both contributions, but we try to keep core changes separate from keyboard changes/additions, and keyboard code separate from keymap/layout additions.  The reason for this, is that if we need to revert code, it doesn't create a mess for us.  And it makes it easier to track changes, long term, and to review.

And once you've separated these out, we will be more than happen to review and merge them, as appropriate.

2021-12-08 19:54 UTC, tzarc commented
This PR should really be split up, with each area having its own PR in isolation:

* Core changes (though the Apple FN key stuff will likely be closed as `wontfix`)
* Keyboard additions should be done by themselves, one keyboard per PR unless they're revisions of the same keyboard
* Personal keymap additions going into a separate PR -- if you split these up too they'll be much easier for us to review

2022-10-06 10:10 UTC, keyboard-magpie commented
Closing this now, as stale, and with regards to Tzarc's previous comment:

This PR should really be split up, with each area having its own PR in isolation:

    Core changes (though the Apple FN key stuff will likely be closed as wontfix)
    Keyboard additions should be done by themselves, one keyboard per PR unless they're revisions of the same keyboard
    Personal keymap additions going into a separate PR -- if you split these up too they'll be much easier for us to review

2022-10-06 10:10 UTC, closed without merging