Add Anne Pro 2 keyboard
qmk/qmk_firmware pull request #14385
Opened 2021-09-11 15:31 UTC by bwisn

## Description

Introduces support for Anne Pro 2

## Types of Changes

- [ x ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-11 15:59 UTC, fauxpark requested changes
Please submit the core changes as a separate PR.

2021-09-11 16:35 UTC, bwisn commented
> Please submit the core changes as a separate PR.
 Removed core and submitted it in another PR:
#14388

2021-09-12 00:37 UTC, zvecr requested changes
I would also recommend removing all non-default keymaps from the PR. Theres quite a lot that needs to change (a lot of which is on the PR checklist), which bloats this PR and would be better for them to resubmit after this has merged.

2021-09-12 06:14 UTC, tzarc commented
Retargeted to `develop` due to dependent PR requiring core changes.

2021-09-15 07:08 UTC, drashna commented on keyboards/annepro2/annepro2.c
> +#include "ch.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-15 07:15 UTC, drashna requested changes

2021-09-15 07:15 UTC, drashna commented on keyboards/annepro2/c15/config.h
> +}
This should go in the keyboard's header file, not here. 
```suggestion
```

2021-09-15 07:15 UTC, drashna commented on keyboards/annepro2/c15/config.h
> +//#define MAGIC_KEY_SLEEP_LED      Z
```suggestion
```

2021-09-15 07:15 UTC, drashna commented on keyboards/annepro2/c15/rules.mk
> +LAYOUTS +=
```suggestion
```

2021-09-15 07:15 UTC, drashna commented on keyboards/annepro2/c15/rules.mk
> +CUSTOM_MATRIX = yes
This should be converted to matrix lite, if/when possible. 

https://docs.qmk.fm/#/custom_matrix?id=lite

2021-09-15 07:15 UTC, drashna commented on keyboards/annepro2/c18/config.h
> +//#define MAGIC_KEY_SLEEP_LED      Z
```suggestion
```

2021-09-15 07:15 UTC, drashna commented on keyboards/annepro2/c18/rules.mk
> +CUSTOM_MATRIX = yes
Same as above (matrix lite)

2021-09-15 07:41 UTC, bwisn commented
@drashna fixed!

2021-09-16 03:36 UTC, drashna requested changes

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/info.json
> +    "height": 5,
```suggestion
```

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default-full-caps/keymap.c
> +#include "config.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

And:
```suggestion
#include QMK_KEYBOARD_H
```

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default-full-caps/config.h
> +// Obins stock firmware has something similar to this already enabled, but disabled by default in QMK
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

```suggestion
#pragma once
// Obins stock firmware has something similar to this already enabled, but disabled by default in QMK
```

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default-full-caps/keymap.c
> +layer_state_t layer_state_set_user(layer_state_t layer) { return layer; }
```suggestion

// Code to run after initializing the keyboard
void keyboard_post_init_user(void) {
    // Here are two common functions that you can use. For more LED functions, refer to the file "qmk_ap2_led.h"

    // annepro2-shine disables LEDs by default. Uncomment this function to enable them at startup.
    // annepro2LedEnable();

    // Additionally, it also chooses the first LED profile by default. Refer to the "profiles" array in main.c in
    // annepro2-shine to see the order. Replace "i" with the index of your preferred profile. (i.e the RED profile is index 0)
    // annepro2LedSetProfile(i);
}
```

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default-layer-indicators/config.h
> +#define PERMISSIVE_HOLD
Same as previous

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default-layer-indicators/keymap.c
> +#include <stdint.h>
Same as previous

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default-layer-indicators/keymap.c
> +    switch (get_highest_layer(layer)) {
While the name doesn't technically matter to the compiler, this is a bitmask of the layer state, so `state` is a bit more accurate and clear. 
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
```

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default/config.h
> +// Obins stock firmware has something similar to this already enabled, but disabled by default in QMK
Same as previous

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/keymaps/default/keymap.c
> +#include <stdint.h>
same as previous

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/qmk_ap2_led.c
> +#include <string.h>
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-16 03:36 UTC, drashna commented on keyboards/annepro2/qmk_ap2_led.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-17 04:48 UTC, drashna requested changes

2021-09-17 04:48 UTC, drashna commented on keyboards/annepro2/annepro2.h
> +#include "config.h"
This line is not needed, at all. 
```suggestion
```

2021-09-18 06:31 UTC, fauxpark commented on keyboards/annepro2/keymaps/default-full-caps/keymap.c
> + [_BASE_LAYER] = KEYMAP( /* Base */
These need to be updated.

2021-10-18 19:20 UTC, rpeshkov commented
I have the same problem as for @tzarc. Keyboard gets flashed, but it's not functional. Previously I had success with repo https://github.com/OpenAnnePro/qmk_firmware.

Played around with the code in this PR. For me reverting back `CUSTOM_MATRIX = yes` and restoring matrix methods did the trick and my Anne Pro started to work. I have C18 version.

2021-10-31 20:10 UTC, tzarc commented
For reference, I've left this PR alone as you've resolved comments on the GitHub UI, but not fixed them in the code.
We spoke on Discord about this, you apologised, and they're still unaddressed.

I'd suggest going through each and every comment made by myself, @drashna and @zvecr, ensuring every item has been addressed.

Feel free to ping here when done -- I'll go through every request to ensure it's been handled.

2021-11-01 10:18 UTC, tzarc requested changes
Round 2.

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/annepro2_ble.c
> +    sdWrite(&SD1, 0x0, 3);
```suggestion
    static const uint8_t dummy[3] = {0};
    sdWrite(&SD1, dummy, sizeof(dummy));
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/boards/ANNEPRO2_C15/board.c
> +#include "annepro2.h"
ChibiOS board definitions should not include keyboard files.
```suggestion
#include "hal.h"
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/boards/ANNEPRO2_C15/board.c
> +void boardInit(void) {}
These are QMK-specific constructs and do not belong in the `board.c`.
You've misinterpreted the intent here -- `ht32_clock_init();` does indeed go into `__early_init()`, as per normal board files for stm32, which place `stm32_clock_init()` in the same location.

As I pointed out on specific lines highlighted in the previous comment, the issue was the `gpt_init()` and the `spi_init()`, not the placement of the clock init.

Refer to an existing ChibiOS board file for example structure.

```suggestion
void __early_init(void) { ht32_clock_init(); }

void boardInit(void) {}
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/boards/ANNEPRO2_C15/board.h
> +#define LINE_COL14 PAL_LINE(IOPORTB, 3)
These are keyboard-specific, and should be swapped out for normal GPIO definitions as per the MCU's datasheet.

The config.h file for each board can then be keyboard-specific and map the rows/cols to the MCU pin definitions.

```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/boards/ANNEPRO2_C15/board.h
> +#define ANNEPRO2
```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/boards/ANNEPRO2_C18/board.h
> +#define ANNEPRO2
```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/boards/ANNEPRO2_C18/board.h
> +
As per C15.
```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/c15/rules.mk
> +	hardfault_handler.c \
```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/c18/rules.mk
> +	hardfault_handler.c \
```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/chconf.h
> +#define CH_DBG_ENABLE_ASSERTS FALSE  // adds about 3K code
Remove as much of these as is possible.
This looks like copypaste without understanding the implications.

```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/mcuconf.h
> +
```suggestion
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/protocol.h
> +#include <inttypes.h>
```suggestion
#include <stdint.h>
```

2021-11-01 10:18 UTC, tzarc commented on keyboards/annepro2/readme.md
> +See the [installing instructions](https://openannepro.github.io/install/)
This document needs flashing instructions embedded here, rather than linked to.

```suggestion
```

2021-12-10 15:22 UTC, bwisn commented
@tzarc friendly ping :) IMO everything is fixed, waiting for review

2022-01-21 16:43 UTC, blaa commented
We can wait, but maybe there's something more we can do. We've got a recent branch with a better RGB integration with the QMK (letting QMK control LEDs via commands to Shine/LED CPU), it still needs tests on C15 variant (less RAM) though. Our original idea was to leave it as it is, well-tested and work on bells and whistles later.

2022-02-11 23:13 UTC, drashna approved these changes

2022-03-06 10:32 UTC, bwisn commented
Please change target from master to develop. It needs #16548 to be merged first.

2022-03-08 01:12 UTC, tzarc approved these changes
Close enough.

2022-03-08 01:12 UTC, merged