Added FJLabs TF60 Variants and TF65 Variant
qmk/qmk_firmware pull request #14392
Opened 2021-09-11 18:34 UTC by mrnoisytiger

## Description

Added FJLabs DZ60 Variants and DZ65RGBv2 variant.

New Pull Request for https://github.com/qmk/qmk_firmware/pull/14126. Fixed changes described in latest comments.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-15 07:20 UTC, drashna approved these changes

2021-09-15 07:26 UTC, fauxpark requested changes

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf65rgbv2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf65rgbv2/info.json
> +    "height": 5,
```suggestion
```

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf60v2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf60v2/info.json
> +    "height": 5,
```suggestion
```

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf60ansi/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf60ansi/info.json
> +                {"x": 13.75, "y": 4, "w": 1.25}
```suggestion
                {"x": 13.75, "y": 4, "w": 1.25}
```

2021-09-15 07:26 UTC, fauxpark commented on keyboards/fjlabs/tf60ansi/info.json
> +    "height": 5,
```suggestion
```

2021-09-15 17:23 UTC, fauxpark approved these changes

2021-09-16 02:25 UTC, drashna commented
Thanks!

2021-09-16 02:25 UTC, merged