Added Absolute Designs AD65 Keyboard
qmk/qmk_firmware pull request #14391
Opened 2021-09-11 18:29 UTC by mrnoisytiger

## Description

Added Absolute Designs AD65 Keyboard.

New pull request for https://github.com/qmk/qmk_firmware/pull/14279

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-15 07:18 UTC, drashna approved these changes

2021-09-15 07:20 UTC, fauxpark requested changes

2021-09-15 07:20 UTC, fauxpark commented on keyboards/fjlabs/ad65/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-15 07:20 UTC, fauxpark commented on keyboards/fjlabs/ad65/info.json
> +                {"x": 0, "y": 4, "w": 1.25},
```suggestion
                {"x": 0, "y": 4, "w": 1.25},
```

2021-09-15 07:20 UTC, fauxpark commented on keyboards/fjlabs/ad65/info.json
> +    "height": 5,
```suggestion
```

2021-09-15 17:24 UTC, fauxpark approved these changes

2021-09-16 02:24 UTC, drashna commented
Thanks!

2021-09-16 02:25 UTC, merged