add ein_60
qmk/qmk_firmware pull request #14398
Opened 2021-09-12 02:20 UTC by Klackygears

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-12 02:56 UTC, Klackygears commented
oops. I need to change the "layout_4x6_2"

2021-09-12 03:48 UTC, Klackygears commented
Should be good to go?

2021-09-15 07:41 UTC, drashna requested changes
You have changes to the git submodules that need to be fixed.  This should be fixed by rebasing the branch that was used to open the PR.

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/config.h
> +//   #define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/glcdfont.c
> +#endif
```suggestion
#pragma once

#include "progmem.h"
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/keymaps/default/keymap.c
> +#include "stdio.h"
```suggestion
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/keymaps/default/keymap.c
> +    sprintf(wpm_str, "WPM: %03d", get_current_wpm());
This uses up ~1.5kb of firmware space.  So, bad. 

```suggestion
    uint8_t n = get_current_wpm();
    char    wpm_counter[4];
    wpm_counter[3] = '\0';
    wpm_counter[2] = '0' + n % 10;
    wpm_counter[1] = (n /= 10) % 10 ? '0' + (n) % 10 : (n / 10) % 10 ? '0' : ' ';
    wpm_counter[0] = n / 10 ? '0' + n / 10 : ' ';
    oled_write_P(PSTR("WPM: "), false);
    oled_write(wpm_counter, false);
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/keymaps/default/keymap.c
> +void encoder_update_user(uint8_t index, bool clockwise) {
```suggestion
bool encoder_update_user(uint8_t index, bool clockwise) {
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/keymaps/default/keymap.c
> +#ifdef OLED_DRIVER_ENABLE
```suggestion
#ifdef OLED_ENABLE
```

Also, ideally, all of the oled and encoder code should be moved to the keyboard's C file.  Eg: 
https://github.com/qmk/qmk_firmware/blob/a2d43ca024d8e840c882cc72e80e9eb6b70384f1/keyboards/splitkb/kyria/rev1/rev1.c#L58-L148

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/keymaps/default/rules.mk
> +RGB_MATRIX_DRIVER = WS2812  # Define RGB Matrix
This should go in the keyboard's rules.mk, instead.
```suggestion
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/rules.mk
> +#RGB_MATRIX_DRIVER = WS2812  # Define RGB Matrix
```suggestion
RGB_MATRIX_DRIVER = WS2812  # Define RGB Matrix
```

2021-09-15 07:41 UTC, drashna commented on keyboards/ein_60/rules.mk
> +OLED_DRIVER_ENABLE = yes    # Enables the use of OLED displays
```suggestion
OLED_ENABLE = yes    # Enables the use of OLED displays
```

2021-09-15 11:46 UTC, Klackygears commented
> You have changes to the git submodules that need to be fixed. This should be fixed by rebasing the branch that was used to open the PR.

Shoot! I thought I did that! I’ll work on it!

2021-09-15 17:13 UTC, Klackygears commented
> You have changes to the git submodules that need to be fixed. This should be fixed by rebasing the branch that was used to open the PR.

Regarding this, does using the below command not work? git is sometimes really confusing for me.
```
git submodule update --init
```

2021-09-16 18:00 UTC, Klackygears commented
Hey @drashna I removed the WPM thing but, I'm wondering if it's a problem? I think there's a lot of space on the AT90USB1286 if that's the concern. However, as always, I may not know anything about what I'm saying lol.

2021-09-16 18:35 UTC, Klackygears commented
I added in my keymap with the with the wpm on the oled so that it's available that way. Do you think that's better?

2021-09-17 04:57 UTC, drashna requested changes

2021-09-17 04:57 UTC, drashna commented on keyboards/ein_60/keymaps/klackygears/config.h
> +#define PREVENT_STUCK_MODIFIERS
This is no longer used.
```suggestion
```

2021-09-17 04:58 UTC, drashna commented
> Hey @drashna I removed the WPM thing but, I'm wondering if it's a problem? I think there's a lot of space on the AT90USB1286 if that's the concern. However, as always, I may not know anything about what I'm saying lol.

Fair point.  But it's probably best to just not use the snprintf stuff anyways.

2021-09-17 05:06 UTC, Klackygears commented
> > Hey @drashna I removed the WPM thing but, I'm wondering if it's a problem? I think there's a lot of space on the AT90USB1286 if that's the concern. However, as always, I may not know anything about what I'm saying lol.
> 
> Fair point. But it's probably best to just not use the snprintf stuff anyways.

Cool! I'll have to learn more about that :-)

2021-09-17 05:10 UTC, drashna approved these changes

2021-09-18 06:25 UTC, fauxpark requested changes

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/default/readme.md
> +# The default keymap for EIN_60. It utilizes a nearly identical layout as the Plank. The OLED is enabled, rotary encoders are enabled, and the LEDs are enabled with RGB Matrix. You'll need to alter t
```suggestion
# The default keymap for EIN_60.

It utilizes a nearly identical layout as the Plank. The OLED is enabled, rotary encoders are enabled, and the LEDs are enabled with RGB Matrix. You'll need to alter the rules.mk file in your own keymap to change this or simply cut the jumper pad with a hobby knife to disconnect them completely. There is an option to install a KELIKING KLJ-1102 speaker and enable with "AUDIO_ENABLE = yes" in your rules.mk file.
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/klackygears/readme.md
> +# This is the klackygears userspace keymap for EIN_60. My userspace is heavily based on Drashna's userspace and draws a lot of features from him.
```suggestion
This is the klackygears userspace keymap for EIN_60. My userspace is heavily based on Drashna's userspace and draws a lot of features from him.
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/default/keymap.c
> +    [_FUNCTION] = LAYOUT( \
```suggestion
    [_FUNCTION] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/default/keymap.c
> +    [_ADJUST] = LAYOUT( \
```suggestion
    [_ADJUST] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/default/keymap.c
> +    [_RAISE] = LAYOUT( \
```suggestion
    [_RAISE] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/default/keymap.c
> +    [_LOWER] = LAYOUT( \
```suggestion
    [_LOWER] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/default/keymap.c
> +    [_QWERTY] = LAYOUT( \
```suggestion
    [_QWERTY] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/ledtest/keymap.c
> +    [_QWERTY] = LAYOUT( \
```suggestion
    [_QWERTY] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/ledtest/keymap.c
> +    [_LOWER] = LAYOUT( \
```suggestion
    [_LOWER] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/ledtest/keymap.c
> +    [_RAISE] = LAYOUT( \
```suggestion
    [_RAISE] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/ledtest/keymap.c
> +    [_ADJUST] = LAYOUT( \
```suggestion
    [_ADJUST] = LAYOUT(
```

2021-09-18 06:25 UTC, fauxpark commented on keyboards/ein_60/keymaps/ledtest/keymap.c
> +    [_FUNCTION] = LAYOUT( \
```suggestion
    [_FUNCTION] = LAYOUT(
```

2021-09-18 19:01 UTC, drashna requested changes

2021-09-18 19:01 UTC, drashna commented on keyboards/ein_60/keymaps/ledtest/keymap.c
> +}
```suggestion
```

2021-09-18 22:05 UTC, Klackygears commented
Hey @drashna , regarding moving the oled stuff, I like that! Would it be easier to modify if its in a seperate file?

2021-09-18 22:16 UTC, drashna commented
> Hey @drashna , regarding moving the oled stuff, I like that! Would it be easier to modify if its in a seperate file?

Nope.  I forgot to add a "weak" to it, though (fixed).  But the point for it being there is that it's included automatically with the keyboard, but can be replaced by specifying it in the keymap (or elsewhere).  This allows it to work if a user doesn't specify it, such as when compiling from the configurator.

2021-09-18 22:34 UTC, Klackygears commented
> > Hey @drashna , regarding moving the oled stuff, I like that! Would it be easier to modify if its in a seperate file?
> 
> Nope. I forgot to add a "weak" to it, though (fixed). But the point for it being there is that it's included automatically with the keyboard, but can be replaced by specifying it in the keymap (or elsewhere). This allows it to work if a user doesn't specify it, such as when compiling from the configurator.

Oh! That makes sense! That's smart!

2021-09-19 05:23 UTC, Klackygears commented
Hey @drashna I have a question. After making the changes to the oled, it's not playing nice with the layer indicators

```Compiling: keyboards/ein_60/ein_60.c                                                               keyboards/ein_60/ein_60.c: In function 'oled_task_user':
keyboards/ein_60/ein_60.c:64:14: error: '_QWERTY' undeclared (first use in this function)
         case _QWERTY:
              ^~~~~~~
keyboards/ein_60/ein_60.c:64:14: note: each undeclared identifier is reported only once for each function it appears in
keyboards/ein_60/ein_60.c:67:14: error: '_LOWER' undeclared (first use in this function); did you mean 'X_POWER'?
         case _LOWER:
              ^~~~~~
              X_POWER
keyboards/ein_60/ein_60.c:70:14: error: '_RAISE' undeclared (first use in this function); did you mean 'X_PAUSE'?
         case _RAISE:
              ^~~~~~
              X_PAUSE
keyboards/ein_60/ein_60.c:73:14: error: '_ADJUST' undeclared (first use in this function)
         case _ADJUST:
              ^~~~~~~
keyboards/ein_60/ein_60.c:76:14: error: '_FUNCTION' undeclared (first use in this function); did you mean 'QK_FUNCTION'?
         case _FUNCTION:
              ^~~~~~~~~
              QK_FUNCTION
 [ERRORS]
 |```
 
 I'm not sure how to correct this. What would be the best way?

2021-09-20 07:01 UTC, Klackygears commented
I reverted the changes to the OLED because any time a layer was called, it caused errors especially in the circumstance that the layers were named differently that the default.

2021-09-21 22:08 UTC, drashna commented
> Hey @drashna I have a question. After making the changes to the oled, it's not playing nice with the layer indicators
> 
>  
>  I'm not sure how to correct this. What would be the best way?

Basically just don't use the names.  Use numbers.  It's not as elegant, but ....  I would prefer it be there.

Probably can keep the code that is in the default keymap too.  That way, at least, it will work on the configurator.

2021-09-22 02:07 UTC, Klackygears commented
> > Hey @drashna I have a question. After making the changes to the oled, it's not playing nice with the layer indicators
> > I'm not sure how to correct this. What would be the best way?
> 
> Basically just don't use the names. Use numbers. It's not as elegant, but .... I would prefer it be there.
> 
> Probably can keep the code that is in the default keymap too. That way, at least, it will work on the configurator.

So, something like what is in there now?

2021-09-22 03:04 UTC, drashna approved these changes
Yup!

2021-09-22 03:04 UTC, drashna commented on keyboards/ein_60/config.h
> +#ifdef OLED_DRIVER_ENABLE
```suggestion
#ifdef OLED_ENABLE
```

2021-09-22 03:04 UTC, drashna commented on keyboards/ein_60/keymaps/klackygears/keymap.c
> +#ifdef OLED_DRIVER_ENABLE
```suggestion
#ifdef OLED_ENABLE
```

2021-09-22 03:28 UTC, Klackygears commented
> Yup!

Awesome! Thanks!

2021-09-22 03:34 UTC, fauxpark approved these changes

2021-09-22 04:18 UTC, drashna commented
Thanks!

2021-09-22 04:18 UTC, merged

2021-09-22 04:20 UTC, Klackygears commented
Thanks @drashna and @fauxpark !!!