Add support for Coarse60
qmk/qmk_firmware pull request #14416
Opened 2021-09-12 22:06 UTC by e11i0t23

## Description
Add support for Coarse60 in collaberation with keebs for all and seh0nky

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-12 22:34 UTC, zvecr requested changes

2021-09-12 22:34 UTC, zvecr commented on keyboards/keebsforall/coarse60/coarse60.c
> +}
```suggestion
```

2021-09-12 22:34 UTC, zvecr commented on keyboards/keebsforall/coarse60/config.h
> +#define INDICATOR_PIN_2 B11
```suggestion

#define LED_NUM_LOCK_PIN B2
#define LED_CAPS_LOCK_PIN B10
#define LED_SCROLL_LOCK_PIN B11
#define LED_PIN_ON_STATE 0
```

2021-09-12 22:34 UTC, zvecr commented on keyboards/keebsforall/coarse60/readme.md
> +Keyboard Availabilty: [keebsforall](https://keebsforall.com)
```suggestion
* Hardware Supported: seh0nky x KeebsForAll Coarse60
* Keyboard Maintainer: [e11i0t23](https://github.com/e11i0t23)
* Keyboard Availabilty: [keebsforall](https://keebsforall.com) 
```

2021-09-13 22:33 UTC, e11i0t23 commented
Thanks for review, requested changes have been commited

2021-09-15 08:05 UTC, drashna requested changes

2021-09-15 08:05 UTC, drashna commented on keyboards/keebsforall/coarse60/config.h
> +#define PRODUCT_ID      0x5341
```suggestion
#define VENDOR_ID       0x6B66
#define PRODUCT_ID      0x5341
```

2021-09-15 08:05 UTC, drashna commented on keyboards/keebsforall/coarse60/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-09-15 08:05 UTC, drashna commented on keyboards/keebsforall/coarse60/keymaps/default/keymap.c
> +}
This should be moved to the keyboard's c file.

2021-09-15 08:05 UTC, drashna commented on keyboards/keebsforall/coarse60/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-15 08:05 UTC, drashna commented on keyboards/keebsforall/coarse60/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-15 08:05 UTC, drashna commented on keyboards/keebsforall/coarse60/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
AUDIO_ENABLE = no           # Audio output
```

2021-09-16 00:15 UTC, e11i0t23 commented
Thank you, updated as requested

2021-09-16 03:14 UTC, drashna requested changes

2021-09-16 03:14 UTC, drashna commented on keyboards/keebsforall/coarse60/coarse60.c
> +    if (index == 0) {
```suggestion
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
```

2021-09-16 03:14 UTC, drashna commented on keyboards/keebsforall/coarse60/coarse60.c
> +    return encoder_update_user(index, clockwise);
```suggestion
    return true;
```

2021-09-17 05:34 UTC, drashna approved these changes

2021-09-18 06:11 UTC, fauxpark requested changes

2021-09-18 06:11 UTC, fauxpark commented on keyboards/keebsforall/coarse60/info.json
> +    "height": 5.25,
```suggestion
```

2021-09-18 08:29 UTC, fauxpark approved these changes

2021-09-18 18:39 UTC, drashna commented
Thanks!

2021-09-18 18:39 UTC, merged