Add Dango40
qmk/qmk_firmware pull request #14437
Opened 2021-09-14 21:19 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-15 08:27 UTC, drashna requested changes

2021-09-15 08:27 UTC, drashna commented on keyboards/onekeyco/dango40/readme.md
> +Make example for flashing this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-09-15 08:27 UTC, drashna commented on keyboards/onekeyco/dango40/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-15 08:27 UTC, drashna commented on keyboards/onekeyco/dango40/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-09-17 05:56 UTC, drashna requested changes

2021-09-17 05:56 UTC, drashna commented on keyboards/onekeyco/dango40/info.json
> +   "height":4,
```suggestion
```

2021-09-17 05:56 UTC, drashna commented on keyboards/onekeyco/dango40/keymaps/default/keymap.c
> +}
```suggestion
```

2021-09-17 05:56 UTC, drashna commented on keyboards/onekeyco/dango40/keymaps/via/keymap.c
> +}
```suggestion
```

2021-09-17 05:56 UTC, drashna commented on keyboards/onekeyco/dango40/dango40.c
> +#include "dango40.h"
```suggestion
#include "dango40.h"

bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (clockwise) {
        tap_code_delay(KC_VOLU, 10);
    } else {
        tap_code_delay(KC_VOLD, 10);
    }
    return true;
} 
```

2021-09-18 15:34 UTC, drashna approved these changes

2021-09-19 05:21 UTC, fauxpark approved these changes

2021-09-21 23:49 UTC, drashna approved these changes

2021-09-22 03:39 UTC, fauxpark approved these changes

2021-09-22 04:25 UTC, drashna commented
Thanks!

2021-09-22 04:25 UTC, merged