Add custom keymap 'j4ckofalltrades' for sofle/rev1
qmk/qmk_firmware pull request #14446
Opened 2021-09-15 14:11 UTC by j4ckofalltrades

## Description
    
Modified version of default Via-compatible keymap with focus on adding a standard navigation cluster layer
plus some Vim-inspired features e.g. soft escape (Esc when held, Ctrl when tapped), using 'h', 'j', 'k', 'l' as arrow keys.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-16 03:21 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/config.h
> +/* Copyright 2021 Jordan Duabe
This file can be removed.

2021-09-16 03:24 UTC, drashna requested changes

2021-09-16 03:24 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/encoder.c
> +            tap_code(KC_VOLD);
```suggestion
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
```

2021-09-16 03:24 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/keymap.c
> +#include "encoder.c"
You should not include C files like this.  Only header files should be included. 
```suggestion
```

2021-09-16 03:24 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/encoder.c
> +#ifdef ENCODER_ENABLE
```suggestion
#ifdef ENCODER_ENABLE
#    include QMK_KEYBOARD_H
```

2021-09-16 03:24 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/oled.c
> +#ifdef OLED_ENABLE
```suggestion
#ifdef OLED_ENABLE
#    include QMK_KEYBOARD_H
```

2021-09-16 03:24 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/rules.mk
> +LTO_ENABLE = yes
```suggestion
LTO_ENABLE = yes

SRC += oled.c encoder.c
```

2021-09-16 03:24 UTC, drashna commented on keyboards/sofle/keymaps/j4ckofalltrades/rules.mk
> +ENCODER_ENABLE = yes
These are defined at the keyboard level, so aren't technically needed. 
```suggestion
```

2021-09-16 12:13 UTC, j4ckofalltrades commented
Suggestions applied, ready for next round of review.

2021-09-17 06:05 UTC, drashna approved these changes

2021-09-18 06:31 UTC, fauxpark approved these changes

2021-09-18 06:52 UTC, drashna commented
Thanks!

2021-09-18 06:52 UTC, merged