Adding personal keymap
qmk/qmk_firmware pull request #14475
Opened 2021-09-17 08:19 UTC by cankoklu

## Description
Personal keymap with specific shortcuts etc.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-17 14:33 UTC, drashna requested changes

2021-09-17 14:33 UTC, drashna commented on keyboards/splitkb/kyria/keymaps/cankoklu/config.h
> +#    define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
// #define RGBLIGHT_EFFECT_RGB_TEST
// #define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-09-17 14:33 UTC, drashna commented on keyboards/splitkb/kyria/keymaps/cankoklu/keymap.c
> +  LINKIFY,
```suggestion
  LINKIFY = SAFE_RANGE,
```

2021-10-04 22:01 UTC, daskygit reviewed
You don't need to `break;` as you're already using `return false;` above them, they're never reached.

2021-10-04 22:04 UTC, daskygit commented on keyboards/splitkb/kyria/keymaps/cankoklu/keymap.c
> +      break;
```suggestion
```

2021-10-04 22:04 UTC, daskygit commented on keyboards/splitkb/kyria/keymaps/cankoklu/keymap.c
> +      break;
```suggestion
```

2021-10-04 22:04 UTC, daskygit commented on keyboards/splitkb/kyria/keymaps/cankoklu/keymap.c
> +      break;
```suggestion
```

2021-10-04 22:04 UTC, daskygit commented on keyboards/splitkb/kyria/keymaps/cankoklu/keymap.c
> +      break;
```suggestion
```

2021-10-04 22:04 UTC, daskygit commented on keyboards/splitkb/kyria/keymaps/cankoklu/keymap.c
> +      break;
```suggestion
```

2022-01-09 02:59 UTC, drashna approved these changes

2022-01-12 21:46 UTC, EricGebhart reviewed
Looks good except for the changes that Dasky requested are still pending.

2022-06-12 18:57 UTC, closed without merging