Keyboard/kyria ctpc
qmk/qmk_firmware pull request #14490
Opened 2021-09-18 07:28 UTC by drashna

## Description

Adds default configurations for using the `Convert to Proton C` configuration so that all features work. 

Includes documentation on how to mod the board to wire everything up. 

Targeting develop since it needs the post_rules.mk to properly handle everything.

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-18 07:31 UTC, fauxpark requested changes

2021-09-18 07:31 UTC, fauxpark commented on keyboards/splitkb/kyria/readme.md
> +## Proton C Convertion Guide
```suggestion
## Proton C Conversion Guide
```

2021-09-18 07:33 UTC, drashna commented on keyboards/splitkb/kyria/readme.md
> +## Proton C Convertion Guide
I know how to speel.

2021-09-18 07:50 UTC, fauxpark approved these changes

2021-10-02 02:05 UTC, splitkb commented
Very nice addition, thank you very much for the contribution @drashna!

2021-10-02 02:07 UTC, splitkb approved these changes

2021-10-02 02:11 UTC, merged