refactor signum30
qmk/qmk_firmware pull request #14527
Opened 2021-09-19 22:27 UTC by sgurenkov

## Description

Refactor `signum` keyboard to allow different microcontrollers (teensy)
Add one more keymap for signum/3_0

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

cc: @jceb

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-21 22:00 UTC, drashna commented on keyboards/signum/3_0/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:00 UTC, drashna commented on keyboards/signum/3_0/config.h
> +#define MANUFACTURER    "Troy Fletcher"
```suggestion
#define MANUFACTURER    Troy Fletcher
```

2021-09-21 22:01 UTC, drashna commented on keyboards/signum/3_0/keymaps/sgurenkov/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:01 UTC, drashna commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +#include "signum.h"
```suggestion
#include QMK_KEYBOARD_H
```

Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:01 UTC, drashna commented on keyboards/signum/3_0/signum.c
> +#include "signum.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:01 UTC, drashna commented on keyboards/signum/3_0/signum.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:01 UTC, drashna commented on keyboards/signum/3_0/teensy/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:02 UTC, drashna commented on keyboards/signum/3_0/teensy/teensy.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-21 22:02 UTC, drashna commented on keyboards/signum/3_0/teensy/teensy.c
> +#include "teensy.h"
Could you add a GPL2+ compatible license header here? 

For instance: 
https://github.com/qmk/qmk_firmware/blob/28ff51175b6d45ce5a8dbfe7ed6e7a12df3bc8a8/quantum/template/base/keyboard.c#L1-L15

2021-09-22 03:49 UTC, fauxpark requested changes

2021-09-22 03:49 UTC, fauxpark commented on keyboards/signum/3_0/rules.mk
> +UNICODEMAP_ENABLE = no
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-09-22 16:08 UTC, fauxpark requested changes

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      SEND_STRING(SS_LCTL("c"));
These can be simplified:
```suggestion
      tap_code16(C(KC_C));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      unregister_code(KC_LCMD);
```suggestion
      tap_code16(G(KC_LEFT));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      unregister_code(KC_LCMD);
```suggestion
      tap_code16(G(KC_RIGHT));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      unregister_code(KC_BSPACE);
```suggestion
      tap_code(KC_RIGHT);

      tap_code(KC_BSPACE);
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      SEND_STRING(SS_LCMD("c"));
```suggestion
      tap_code16(G(KC_C));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      SEND_STRING(SS_LCMD("x"));
```suggestion
      tap_code16(G(KC_X));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      SEND_STRING(SS_LCMD("v"));
```suggestion
      tap_code16(G(KC_V));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      SEND_STRING(SS_LCMD("z"));
```suggestion
      tap_code16(G(KC_Z));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +      SEND_STRING(SS_LCMD(SS_LSFT("z")));
```suggestion
      tap_code16(S(G(KC_Z)));
```

2021-09-22 16:08 UTC, fauxpark commented on keyboards/signum/3_0/keymaps/sgurenkov/keymap.c
> +            unregister_code(KC_TAB);
```suggestion
            tap_code(KC_TAB);
```

2021-09-22 16:59 UTC, sgurenkov commented
@drashna @fauxpark Thank you for the review and suggestions!
I've updated the PR, please give it another look

Thank you

2021-09-24 02:45 UTC, fauxpark requested changes
One last thing.

2021-09-24 02:45 UTC, fauxpark commented on keyboards/signum/3_0/readme.md
> +   make signum/3_0/teensy:default
```suggestion
    make signum/3_0/elitec:default
    make signum/3_0/teensy:default
```

2021-09-24 15:26 UTC, drashna approved these changes

2021-09-24 15:42 UTC, fauxpark approved these changes

2021-09-24 17:05 UTC, drashna commented
Thanks!

2021-09-24 17:05 UTC, merged