PLX info.json update
qmk/qmk_firmware pull request #14536
Opened 2021-09-21 02:33 UTC by 2Moons-JP

info.json  update

## Description

Fix for QMK configurator by addiing a default layout. 
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
QMK configurator fix.
* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-21 04:08 UTC, fauxpark requested changes

2021-09-21 04:08 UTC, fauxpark commented on keyboards/plx/info.json
> +    "height": 5,
```suggestion
```

2021-09-24 06:40 UTC, drashna approved these changes

2021-09-24 06:44 UTC, fauxpark approved these changes

2021-09-24 15:56 UTC, drashna commented
Thanks!

2021-09-24 15:57 UTC, merged