Added Krush65 Solder ver
qmk/qmk_firmware pull request #14581
Opened 2021-09-24 14:19 UTC by MaiTheSan

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-28 18:52 UTC, drashna requested changes

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/info.json
> +    "height": 5,
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/ansi_blocker/keymap.c
> +}
Please remove these, as these would be best in the keyboard's c file. 
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/ansi_blocker_split_all/keymap.c
> +}
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/ansi_blocker_split_bs/keymap.c
> +}
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/default/keymap.c
> +}
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/via/keymap.c
> +}
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/solder.c
> +}
```suggestion
    /*  Custom encoder control - handles CW/CCW turning of encoder
     *  Default behavior:
     *    main layer:
     *       CW: move mouse right
     *      CCW: move mouse left
     *    other layers:
     *       CW: = (equals/plus - increase slider in Adobe products)
     *      CCW: - (minus/underscore - decrease slider in adobe products)
     */
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        switch (get_highest_layer(layer_state)) {

#ifdef MOUSEKEY_ENABLE
            case 0:
                // main layer - move mouse right (CW) and left (CCW)
                if (clockwise) {
                    tap_code(KC_MS_R);
                } else {
                    tap_code(KC_MS_L);
                }
                break;
#endif
            default:
                // other layers - =/+ (quals/plus) (CW) and -/_ (minus/underscore) (CCW)
                if (clockwise) {
                    tap_code(KC_EQL);
                } else {
                    tap_code(KC_MINS);
                }
                break;
        }
    }
    return true;
}
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/config.h
> +/* rotary */
```suggestion
#define LED_CAPS_LOCK_PIN F0

/* rotary */
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/ansi_blocker/keymap.c
> +}
```suggestion
```

2021-09-28 18:52 UTC, drashna commented on keyboards/sawnsprojects/krush65/solder/keymaps/sawns/keymap.c
> +}
```suggestion
bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) {
        switch (get_highest_layer(layer_state)) {
            case 0:
                // main layer - move mouse right (CW) and left (CCW)
                if (clockwise) {
                    tap_code_delay(KC_VOLU, 10);
                } else {
                    tap_code_delay(KC_VOLD, 10);
                }
                break;

            default:
                // other layers - =/+ (quals/plus) (CW) and -/_ (minus/underscore) (CCW)
                if (clockwise) {
                    tap_code16(C(KC_EQL));
                } else {
                    tap_code(C(KC_MINS));
                }
                break;
        }
    }
    return false;
}
```

2021-11-05 10:39 UTC, closed without merging

2021-11-05 10:52 UTC, MaiTheSan commented
repull in https://github.com/qmk/qmk_firmware/pull/15063