[Keyboard] Add Runner3680 with 5x6+5x8 layout
qmk/qmk_firmware pull request #14617
Opened 2021-09-27 03:46 UTC by Hybrid-Force

## Description

Adds Runner3680 with 5x6+5x8 layout variant which is a very practical layout. It includes config for RGB matrix feature, basic keymaps which are duplicated and modified from original 5x8 layout, my custom keymap, and via support.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-28 18:54 UTC, drashna commented
Please review the [PR Checklist document](https://docs.qmk.fm/#/pr_checklist), and apply the changes outlined in it.

2021-10-05 00:20 UTC, drashna requested changes
The `JIS` files need to be renamed so that they're all lower cased.

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/info.json
> +    "height": 5,
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/JIS/keymap.c
> +#endif
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/JIS/keymap.c
> +            RGB_current_config = rgblight_config;
This isn't actually be used and should be removed. 
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/default/keymap.c
> +#endif
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/default/keymap.c
> +            RGB_current_config = rgblight_config;
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/via/keymap.c
> +#endif
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/via/keymap.c
> +            RGB_current_config = rgblight_config;
```suggestion
```

2021-10-05 00:20 UTC, drashna commented on keyboards/runner3680/5x6_5x8/keymaps/derekhsu/rules.mk
> +RGB_MATRIX_DRIVER = WS2812
```suggestion
```

This should be moved to the keyboard's rules.mk file.

2021-12-27 02:39 UTC, tzarc approved these changes

2021-12-27 02:39 UTC, merged