Update Grandiceps to Rev2
qmk/qmk_firmware pull request #14618
Opened 2021-09-27 10:50 UTC by vattern

## Description

Changes to use the rev2 boards. Split hand detect using pin and allows for trackball
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-28 19:11 UTC, drashna approved these changes

2021-09-28 19:22 UTC, fauxpark requested changes

2021-09-28 19:22 UTC, fauxpark commented on keyboards/tkw/grandiceps/info.json
> +    "height": 5.25,
```suggestion
```

2021-09-28 19:22 UTC, fauxpark commented on keyboards/tkw/grandiceps/readme.md
> +
```suggestion
```

2021-09-29 03:49 UTC, daskygit commented on keyboards/tkw/grandiceps/readme.md
> +* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
```suggestion
* **Physical reset buttons**: Hold down the BOOT0 button and then briefly press the NRST button on the BlackPill PCB.
```

2021-09-29 07:48 UTC, fauxpark approved these changes

2021-09-29 16:55 UTC, drashna commented
Thanks!

2021-09-29 16:55 UTC, merged