arkag userspace/keymap -- new macro and minor preonic keymap change
qmk/qmk_firmware pull request #14623
Opened 2021-09-27 23:05 UTC by arkag

## Description

Added a new leader sequence and modified my keymap slightly.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-09-27 23:06 UTC, fauxpark requested changes

2021-09-27 23:06 UTC, fauxpark commented on users/arkag/arkag.c
> +      tap_code(KC_I);
```suggestion
      SEND_STRING("ggvG}x:set paste\ni");
```

2021-09-27 23:08 UTC, arkag commented on users/arkag/arkag.c
> +      tap_code(KC_I);
Oh, does SEND_STRING interpret `\n` as an enter? Wild.

2021-09-27 23:10 UTC, fauxpark approved these changes

2021-09-28 19:20 UTC, drashna approved these changes

2021-09-28 19:21 UTC, drashna commented
Thanks!

2021-09-28 19:21 UTC, merged