add duo_s keyboard
qmk/qmk_firmware pull request #14625
Opened 2021-09-28 02:02 UTC by moyi4681

add duo_s keyboard

2021-09-28 19:20 UTC, drashna requested changes

2021-09-28 19:20 UTC, drashna commented on keyboards/dztech/duo_s/rules.mk
> +BOOTMAGIC_ENABLE = lite      # Enable Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-09-28 19:20 UTC, drashna commented on keyboards/dztech/duo_s/rules.mk
> +# Build Options
```suggestion
# Bootloader selection
BOOTLOADER = stm32-dfu

# Build Options
```

2021-09-29 02:46 UTC, drashna requested changes

2021-09-29 02:46 UTC, drashna commented on keyboards/dztech/duo_s/config.h
> +#define DESCRIPTION     65% Keyboard
```suggestion
```

2021-10-05 00:08 UTC, drashna approved these changes

2021-10-05 01:05 UTC, fauxpark approved these changes

2021-10-05 01:16 UTC, drashna commented
Thanks!

2021-10-05 01:16 UTC, merged