Add support for Mode SixtyFive M65HA and M65HI
qmk/qmk_firmware pull request #14685
Opened 2021-10-03 23:36 UTC by Gondolindrim

This PR adds initial compatibility for Mode SixtyFive's M65HA and M65HI PCBs, respectively the ANSI and the ISO versions of its hotswap PCBs.

Both PCBs had two versions, a prototype (pre-Alpha) and a final run (Alpha); while the mass-production will ship with version Alpha, pre-Alpha had a significant number of units made sent to reviewers, streamers and early adoptersd. Also release Alpha had matrix changes, hence why there are firmwares for both. Hence this PR adds four PCBs: M65HA pA and A, and M65HI pA and A.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-05 03:16 UTC, drashna requested changes

2021-10-05 03:16 UTC, drashna commented on keyboards/mode/m65ha_alpha/README.md
> +# Mode M65HA (pre-release Alpha version)
Please rename the file to be lower case.

2021-10-05 03:16 UTC, drashna commented on keyboards/mode/m65ha_alpha/rules.mk
> +BOOTMAGIC_ENABLE = full     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-10-05 03:16 UTC, drashna commented on keyboards/mode/m65ha_alpha/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-10-30 22:34 UTC, Gondolindrim commented on keyboards/xbows/knight/keymaps/via/config.h
> +/* Copyright 2021 Shulin Huang <mumu@x-bows.com>
Why do you guys assume there's a reason for everything? Maybe I'm just stupid.

2021-11-12 20:59 UTC, Jaicob commented
@fauxpark can you please give this PR another review or reassign someone who is available to?

2021-11-16 00:06 UTC, fauxpark commented on keyboards/xbows/knight/keymaps/via/config.h
> +/* Copyright 2021 Shulin Huang <mumu@x-bows.com>
This is still outstanding.

2021-11-16 03:06 UTC, Gondolindrim commented
@fauxpark thanks for your patience -- I force-pushed the past commits to only include the M65H files.

2021-11-16 07:30 UTC, fauxpark requested changes

2021-11-16 07:30 UTC, fauxpark commented on keyboards/mode/m65hi_pre-alpha/m65hi_preAlpha.c
> +/*
All file and folder names should be lowercase and not contain `-`s.

2021-11-23 18:53 UTC, Gondolindrim commented
In talks with Mode we decided to keep the pre-alpha firmwares in our forks and just submit the alpha final production files, because the configurator files were not checking out.

2021-11-27 17:38 UTC, fauxpark commented on keyboards/mode/m65ha_alpha/m65ha_alpha.c
> +}
What is this for?

2021-11-30 05:52 UTC, fauxpark approved these changes

2021-12-01 08:58 UTC, merged