Add Iris Rev. 6
qmk/qmk_firmware pull request #14683
Opened 2021-10-03 22:39 UTC by nooges

## Description

Add Iris Rev. 6

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-03 22:58 UTC, fauxpark requested changes

2021-10-03 22:58 UTC, fauxpark commented on keyboards/keebio/iris/rev6/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
```

2021-10-03 23:25 UTC, fauxpark approved these changes

2021-10-04 05:34 UTC, drashna approved these changes

2021-10-04 05:35 UTC, merged