Ellora65
qmk/qmk_firmware pull request #14754
Opened 2021-10-08 17:38 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-31 08:56 UTC, sigprof commented on keyboards/kikoslab/ellora65/readme.md
> +* **Keycode in layout**: Press the key mapped to `RESET` if it is available
Could this generic text be replaced with something more specific? In particular, the key at (0,0) is mapped to `KC_MUTE` in the default keymap — it it actually the encoder? And does the PCB have an actual reset button on the back, or just pads?

2022-01-07 05:15 UTC, drashna requested changes

2022-01-07 05:15 UTC, drashna commented on keyboards/kikoslab/ellora65/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-09 03:17 UTC, drashna approved these changes

2022-01-10 22:29 UTC, fauxpark requested changes

2022-01-10 22:29 UTC, fauxpark commented on keyboards/kikoslab/ellora65/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-02-12 06:47 UTC, fauxpark approved these changes

2022-02-21 08:55 UTC, merged

2022-02-21 08:55 UTC, drashna commented
Thanks!