Glacier
qmk/qmk_firmware pull request #14758
Opened 2021-10-09 01:06 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-09 13:31 UTC, zvecr commented
> ☒ handwired/swiftrax/glacier: handwired/swiftrax/glacier: LAYOUT_all: Number of elements in info.json does not match! info.json:103 != LAYOUT_all:102
☒ Errors found when generating info.json.

2022-01-07 03:41 UTC, noroadsleft requested changes

2022-01-07 03:41 UTC, noroadsleft commented on keyboards/handwired/swiftrax/glacier/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-08 21:18 UTC, noroadsleft approved these changes

2022-01-08 21:19 UTC, merged

2022-01-08 21:19 UTC, noroadsleft commented
Thanks!