Added support for keyboard Pila87 / XM87 Pro
qmk/qmk_firmware pull request #14764
Opened 2021-10-09 13:34 UTC by HorrorTroll

## Description

Added support for keyboard Pila87 / XM87 Pro. It's using CKS32F103RBT6 (a clone STM32F103RBT6), more info is on readme files

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-07 03:50 UTC, noroadsleft requested changes
Additionally, any .c, .h, or .inc files you authored need to have GPL v2-compatible license headers.

* [Example GPLv2 Header - QMK Firmware Documentation](https://docs.qmk.fm/#/pr_checklist?id=example-gplv2-header)

2022-01-07 03:50 UTC, noroadsleft commented on keyboards/phage_studio/pila87_mod/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-09 03:20 UTC, drashna requested changes

2022-01-09 03:20 UTC, drashna commented on keyboards/phage_studio/pila87_mod/config.h
> +#define DISABLE_RGB_MATRIX_SOLID_SPLASH
rgb matrix modes are explicitly enabled now.

2022-01-09 03:20 UTC, drashna commented on keyboards/phage_studio/pila87_mod/keymaps/horrortroll/keymap_stuff.h
> +    switch (biton32(layer_state)) {
```suggestion
    switch (get_highest_layer(layer_state)) {
```

2022-06-12 15:56 UTC, closed without merging