Update the support for lazydesigners/dimple
qmk/qmk_firmware pull request #14797
Opened 2021-10-12 04:03 UTC by jackytrabbit

Update the support for lazydesigners/dimple

## Description

Added more layout support.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-12 04:18 UTC, jackytrabbit commented
@fauxpark I am sorry that I messed up the previous PR. I tried to resolve the conflicts with Github Desktop and command line but the branch became more complex with new commits. At last I couldn't resolve the conflicts and get more issues. So I opened a new branch  and use the files that are updated in the last PR. Thanks for your help.

And thanks for helping me with this @drashna @tominabox1 @Erovia

2021-10-12 04:19 UTC, jackytrabbit commented
And here is the previous PR which is closed
https://github.com/qmk/qmk_firmware/pull/14168

2021-11-17 00:37 UTC, jackytrabbit commented
Hi, is there anyone could help me on this? It seems everything is ready.

2021-12-10 14:56 UTC, jackytrabbit commented
@fauxpark Don't mean to rush you but do you think this PR is ready for merge? I really appreciate all your works. Let me know if anything is needed. Thank you so much!

2021-12-11 04:59 UTC, fauxpark requested changes

2021-12-11 04:59 UTC, fauxpark commented on keyboards/lazydesigners/dimple/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2021-12-11 04:59 UTC, fauxpark commented on keyboards/lazydesigners/dimple/rules.mk
> +
```suggestion
```

2022-01-04 02:56 UTC, jackytrabbit commented
@fauxpark Happy New Year! I wonder that is there anything I can do to make this PR ready for merge? Thank you so much for the rewiew.

2022-01-06 05:23 UTC, fauxpark requested changes
There is a merge conflict that needs to be resolved, otherwise looks OK.

2022-01-06 14:47 UTC, jackytrabbit commented
> There is a merge conflict that needs to be resolved, otherwise looks OK.
 
Oh, I see. The conflict has been resolved. Thank you for your help!

2022-01-16 02:12 UTC, jackytrabbit commented
> There is a merge conflict that needs to be resolved, otherwise looks OK.

@fauxpark Thank you so much! Is it OK to merge by now? I know you are busy. Thanks again for your service!

2022-02-12 14:15 UTC, jackytrabbit commented
@fauxpark Sorry for boring you again. Just wondering if this PR is OK to be merged. Thanks for what you are doing for community.

2022-02-21 09:03 UTC, Erovia approved these changes

2022-02-21 09:03 UTC, merged