[Keyboard] Add Nozbe Macropad
qmk/qmk_firmware pull request #14803
Opened 2021-10-12 17:19 UTC by rozPierog

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-04 05:16 UTC, drashna commented
Please review the PR Checklist docs, and make the changes outlined there:
https://docs.qmk.fm/#/pr_checklist

Eg, you haven't followed it: 
* You're missing copyright headers for your c and h files
* You're using old style include guards (ifndef/define, instead of `#pragma once`)
* including default IS_COMMAND
* prevent stuck modifiers has not been a setting for 3+ years, now
* question marks in rules.mk file

These need to be resolved before the PR can be considered for merging

2021-11-09 16:18 UTC, rozPierog commented
Thanks for the reply @drashna I've updated the files to be compliant with PR_checklist. I hope that I didn't miss anything

2021-11-10 15:44 UTC, drashna requested changes

2021-11-10 15:44 UTC, drashna commented on keyboards/handwired/nozbe_macro/config.h
> +#    define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-10 15:44 UTC, drashna commented on keyboards/handwired/nozbe_macro/info.json
> +    "height": 1,
```suggestion
```

2021-11-10 15:44 UTC, drashna commented on keyboards/handwired/nozbe_macro/rules.mk
> +OPT_DEFS += -DBOOTLOADER_SIZE=4096
```suggestion
# Bootloader Section
BOOTLOADER = atmel-dfu
```

2021-11-10 15:44 UTC, drashna commented on keyboards/handwired/nozbe_macro/rules.mk
> +BOOTMAGIC_ENABLE = yes	# Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-10 15:44 UTC, drashna commented on keyboards/handwired/nozbe_macro/rules.mk
> +NKRO_ENABLE = yes		# USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
NKRO_ENABLE = yes       # USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```

2021-11-10 15:44 UTC, drashna commented on keyboards/handwired/nozbe_macro/rules.mk
> +ENCODER_ENABLE = no
```suggestion
```

2021-11-10 16:43 UTC, rozPierog commented
Thanks for the review @drashna I've fixed the issues. Sorry about having so much old stuff in the code, I must have based my keyboard of some very old template. Let me know if there is anything else that I need to look at

2021-11-10 16:58 UTC, drashna commented on keyboards/handwired/nozbe_macro/keymaps/default/keymap.c
> +    [_FN]   = LAYOUT(KC_TRNS, KC_1, KC_2, BL_STEP),
This is more of a nitpick for readability, but: 
```suggestion
enum layer_names { 
    _BASE, 
    _FN,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        LT(_FN, KC_N), LALT(KC_UP), LALT(KC_DOWN), LALT(KC_D)
    ),
    [_FN]   = LAYOUT(
        KC_TRNS, KC_1, KC_2, BL_STEP
    ),
```

2021-11-10 16:58 UTC, drashna approved these changes

2021-11-10 17:44 UTC, fauxpark requested changes

2021-11-10 17:44 UTC, fauxpark commented on keyboards/handwired/nozbe_macro/readme.md
> +* Hardware Supported: *Custom handwired 4 key (or 3 key + rotary encoder) pad*
```suggestion
![Nozbe Macropad](https://i.imgur.com/fUMtWmah.png)

4 key macropad with optional rotary encoder.

* Keyboard Maintainer: [rozPierog](https://github.com/rozPierog)
* Hardware Supported: Custom handwired 4 key (or 3 key + rotary encoder) pad
```

2021-11-10 17:44 UTC, fauxpark commented on keyboards/handwired/nozbe_macro/rules.mk
> +# Bootloader Section
```suggestion
# Bootloader selection
```

2021-11-10 17:44 UTC, fauxpark commented on keyboards/handwired/nozbe_macro/rules.mk
> +
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-11-10 17:44 UTC, fauxpark commented on keyboards/handwired/nozbe_macro/nozbe_macro.h
> +#endif
```suggestion
#define LAYOUT( \
    k00, k01, k02, k03 \
) { \
    { k00, k01, k02, k03 } \
}
```

2021-11-11 13:18 UTC, rozPierog commented
Thanks @fauxpark for the review. I've committed changes you've suggested

2021-11-26 20:46 UTC, rozPierog commented
Hey @fauxpark could you look at this again? I've fixed the issues you've reported in Code Review

2021-11-27 11:56 UTC, fauxpark approved these changes

2021-11-28 06:43 UTC, drashna approved these changes

2021-11-28 06:43 UTC, drashna commented
Thanks!

2021-11-28 06:44 UTC, merged