Add rotated numpad variant of Keeb.io Viterbi
qmk/qmk_firmware pull request #14823
Opened 2021-10-14 23:04 UTC by joshchngs

## Description

This is just the right-hand side of a Viterbi rev2 used as a numpad with
a few media & special keys.

You could apply the same concept to the left-hand side, but you would have
to use a 1U enter, since the 2U space would be on the wrong side.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-05 02:54 UTC, drashna commented
Honestly, I'm not sure that this is needed. 

You can add a custom layout, and redefine the matrix values.  I've done exactly that, in fact:
https://github.com/qmk/qmk_firmware/tree/master/keyboards/keebio/viterbi/keymaps/drashna

2022-01-07 05:08 UTC, drashna requested changes

2022-01-07 05:08 UTC, drashna commented on keyboards/keebio/viterbi_numpad/keymaps/default/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-01-07 05:08 UTC, drashna commented on keyboards/keebio/viterbi_numpad/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-07 05:08 UTC, drashna commented on keyboards/keebio/viterbi_numpad/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-07 05:08 UTC, drashna commented on keyboards/keebio/viterbi_numpad/readme.md
> +========================
```suggestion
# Viterbi (numpad variant)
```

2022-01-07 05:08 UTC, drashna commented on keyboards/keebio/viterbi_numpad/readme.md
> +Hardware Availability: [Keebio](https://keeb.io)
it it really available at keebio?
```suggestion
* Keyboard Maintainer: [Josh Channings](https://github.com/joshch)
* Hardware Supported: Elite C
* Hardware Availability: [Keebio](https://keeb.io)
```

2022-01-07 05:08 UTC, drashna commented on keyboards/keebio/viterbi_numpad/rev2/rev2.c
> +#include "viterbi.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-09 11:49 UTC, joshchngs commented
Sory @drashna, I thoughty I closed this.

Your first suggestion of using a custom layout is probably what I needed. I'll close this and resubmit with the correct version next time I make a change to it.

For the rest of your comments - I just duplicated the standard keyboard definition. I haven't tested animations or anything like that. Again, probably another sign that this is just a custom layout.

Thanks for your time.

2022-01-09 11:49 UTC, closed without merging