Add Wete R2
qmk/qmk_firmware pull request #14873
Opened 2021-10-18 13:19 UTC by ramonimbao

## Description

Move `ramonimbao/wete` files to `ramonimbao/wete/rev1`.
Add `ramonimbao/wete/rev2` (default).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-19 08:42 UTC, fauxpark requested changes

2021-11-19 08:42 UTC, fauxpark commented on keyboards/ramonimbao/wete/v1/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = yes      # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-11-28 06:21 UTC, drashna commented
This has some merge conflicts that need resolution.

2021-11-28 06:50 UTC, ramonimbao commented
Not sure how to resolve the conflict - there shouldn't even be a `keyboards/ramonimbao/wete/keymaps/via/rules.mk` file anymore since I moved that to the `v1` folder.

2021-11-28 18:15 UTC, ramonimbao commented
Huh, guess all I needed to do was pull the latest master into the branch. Hopefully that's it.

2021-11-29 08:23 UTC, fauxpark approved these changes

2021-11-29 08:29 UTC, merged