Teleport numpad
qmk/qmk_firmware pull request #14905
Opened 2021-10-21 20:04 UTC by ebastler

Adds support for The Teleport  Macropad PCB

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for The Teleport  Macropad PCB

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-04 05:27 UTC, drashna approved these changes

2021-11-04 07:01 UTC, fauxpark requested changes

2021-11-04 07:01 UTC, fauxpark commented on keyboards/teleport/numpad/rules.mk
> +# BOOTLOADER = bootloadHID
```suggestion
```

2021-11-04 07:01 UTC, fauxpark commented on keyboards/teleport/numpad/readme.md
> +Hardware Availability: [TheTeleport.de](https://www.theteleport.de/)
```suggestion
* Keyboard Maintainer: [ebastler](https://github.com/ebastler)
* Hardware Supported: Teleport NumPad
* Hardware Availability: [TheTeleport.de](https://www.theteleport.de/)
```

2021-11-06 23:54 UTC, fauxpark approved these changes

2021-11-10 14:22 UTC, drashna commented
Thanks!

2021-11-10 14:22 UTC, merged