Adding the keymap of the wpm responsive bongocat
qmk/qmk_firmware pull request #14922
Opened 2021-10-23 07:51 UTC by dbrglc

## Description

I added a keymap for the Lily58 keyboard.
Here there is a WPM responsive animation of the bongo cat in the right Oled, and in the left one some stats like WMP and Layer.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-06 04:39 UTC, fauxpark requested changes

2021-11-06 04:39 UTC, fauxpark commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/keymap.c
> +                             KC_LCTRL, KC_LALT, KC_LGUI, KC_SPC,   KC_ENT,  KC_BSPC, RAISE, LOWER \
```suggestion
 [_QWERTY] = LAYOUT(
  KC_ESC,   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                     KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_EQL,
  KC_TAB,   KC_Q,   KC_W,    KC_E,    KC_R,    KC_T,                     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_MINS,
  KC_DEL,   KC_A,   KC_S,    KC_D,    KC_F,    KC_G,                     KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
  KC_LSFT,  KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, KC_LBRC,  KC_RBRC,  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,  KC_RSFT,
                             KC_LCTRL, KC_LALT, KC_LGUI, KC_SPC,   KC_ENT,  KC_BSPC, RAISE, LOWER
```

2021-11-06 04:39 UTC, fauxpark commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/keymap.c
> +                             _______, _______, _______, _______, _______,  _______, _______, _______\
```suggestion
[_LOWER] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                   _______, _______, _______,_______, _______, _______,
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                     KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,
  KC_GRV,  KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,                   KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TILD,
  _______, _______, _______, _______, _______, _______, _______, _______, XXXXXXX, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
                             _______, _______, _______, _______, _______,  _______, _______, _______
```

2021-11-06 04:39 UTC, fauxpark commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/keymap.c
> +                             _______, _______, _______,  _______, _______,  _______, _______, _______ \
```suggestion
[_RAISE] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                     _______, _______, _______, _______, _______, _______,
  KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    _______,
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                       XXXXXXX, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX,
  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,   _______, _______,  KC_PLUS, KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS,
                             _______, _______, _______,  _______, _______,  _______, _______, _______
```

2021-11-06 04:39 UTC, fauxpark commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/keymap.c
> +                             _______, _______, _______, _______, _______,  _______, _______, _______ \
```suggestion
  [_ADJUST] = LAYOUT(
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD,
                             _______, _______, _______, _______, _______,  _______, _______, _______
```

2021-11-06 04:39 UTC, fauxpark commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/rules.mk
> + SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
```suggestion
WPM_ENABLE = yes
LTO_ENABLE = yes
```

2021-11-08 00:33 UTC, drashna requested changes

2021-11-08 00:33 UTC, drashna commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/keymap.c
> +#ifdef OLED_DRIVER_ENABLE
```suggestion
#ifdef OLED_ENABLE
```

2021-11-10 15:06 UTC, drashna commented on keyboards/lily58/keymaps/bongocat_wpm_responsive/keymap.c
> +//SSD1306 OLED update loop, make sure to enable OLED_DRIVER_ENABLE=yes in rules.mk
```suggestion
//SSD1306 OLED update loop, make sure to enable OLED_ENABLE=yes in rules.mk
```

2021-11-16 00:22 UTC, drashna approved these changes

2022-01-10 09:12 UTC, noroadsleft approved these changes
Slight `__attribute__ ((weak))` :heavy_check_mark: as I don't use OLED, but I don't see anything concerning here.

2022-01-10 09:13 UTC, merged

2022-01-10 09:13 UTC, noroadsleft commented
Thanks!