Add new keyboard "Radialex"
qmk/qmk_firmware pull request #14949
Opened 2021-10-25 16:44 UTC by takashicompany

## Description
Radialex is 40% larger keyboard.  
The radial key layout allows you to place your hand in a natural position and move your fingers the shortest distance to type.  
Your iconic keys and keycaps can be placed in the center of the keyboard.  
It is possible to make it shine with LED backlighting.  
The keyswitches can also be replaced with MX sockets.  

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-14 14:45 UTC, takashicompany commented
@drashna  
What is the status of this Pull Request?

2021-11-15 04:39 UTC, drashna commented
> What is the status of this Pull Request?

Mostly, it's waiting on a second review.

2021-12-07 19:21 UTC, fauxpark requested changes

2021-12-07 19:21 UTC, fauxpark commented on keyboards/takashicompany/radialex/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-07 19:21 UTC, fauxpark commented on keyboards/takashicompany/radialex/keymaps/via/keymap.c
> +            break;
```suggestion
            return false;
```

2021-12-07 19:21 UTC, fauxpark commented on keyboards/takashicompany/radialex/keymaps/default/keymap.c
> +                tap_code16(RGB_TOG);
```suggestion
                rgblight_toggle();
```

2021-12-07 19:21 UTC, fauxpark commented on keyboards/takashicompany/radialex/keymaps/default/keymap.c
> +            break;
```suggestion
            return false;
```

2021-12-08 04:32 UTC, takashicompany commented on keyboards/takashicompany/radialex/keymaps/default/keymap.c
> +                tap_code16(RGB_TOG);
Fixed! https://github.com/qmk/qmk_firmware/pull/14949/commits/cbf3710a0e1b180dfd12c588a7b376c7c1d612c7

2021-12-10 04:29 UTC, fauxpark approved these changes

2021-12-11 06:46 UTC, merged

2021-12-11 06:47 UTC, drashna commented
Thanks!