Add MW65_r2 Series PCB
qmk/qmk_firmware pull request #14940
Opened 2021-10-24 11:44 UTC by TW59420

## Description
MWStudio is a custom keyboard enthusiast
Upload qmk firmware of mw65_r2 series PCB

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-29 20:18 UTC, drashna commented on keyboards/mwstudio/mw65_r2/readme.md
> +![MW65_R2](https://i.imgur.com/QzECiuJ.jpg?2)
```suggestion
![MW65_R2](https://i.imgur.com/QzECiuJh.jpg)
```

2021-10-29 20:19 UTC, drashna requested changes
You also have a merge conflict that needs resolution.

2021-11-03 15:55 UTC, TW59420 commented
Please grant my request for merger, Thanks! @drashna

2021-11-03 17:26 UTC, drashna commented
> Please grant my request for merger, Thanks! @drashna

You have merge conflicts that must be resolved still.  Until that's done, I can't actually merge it.  Also, we generally want 2 approvals before we merge.

2021-11-04 02:35 UTC, TW59420 commented
> > 请批准我的合并请求，谢谢！@德拉什纳
> 
> 您有必须仍然解决的合并冲突。在完成之前，我实际上无法合并它。此外，我们通常在合并之前需要 2 个批准。

I see,Sorry! is my problem

2021-11-30 14:16 UTC, TW59420 commented
@fauxpark  @drashna  Can you help me agree to my pull request?

2021-12-06 02:21 UTC, drashna requested changes

2021-12-06 02:21 UTC, drashna commented on keyboards/mwstudio/mw65_r2/config.h
> +
These aren't really needed, if they're the default. 
```suggestion
```

2021-12-06 02:21 UTC, drashna commented on keyboards/mwstudio/mw65_r2/config.h
> +#ifdef RGB_DI_PIN
No animation modes?

2021-12-06 02:21 UTC, drashna commented on keyboards/mwstudio/mw65_r2/keymaps/via/keymap.c
> +    return true;
```suggestion
    return false;
```

2021-12-06 02:21 UTC, drashna commented on keyboards/mwstudio/mw65_r2/mw65_r2.c
> +#include "mw65_r2.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "mw65_r2.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2021-12-06 04:39 UTC, fauxpark requested changes

2021-12-06 04:39 UTC, fauxpark commented on keyboards/mwstudio/mw65_r2/rules.mk
> +SLEEP_LED_ENABLE = no      # Breathing sleep LED during USB suspend
```suggestion
```

2021-12-06 14:08 UTC, TW59420 commented on keyboards/mwstudio/mw65_r2/config.h
> +#ifdef RGB_DI_PIN
Just need a light band

2021-12-06 17:13 UTC, drashna approved these changes

2021-12-22 08:07 UTC, TW59420 commented
@fauxpark  Can you agree to my request? plase，because it's been a long time

2021-12-22 09:40 UTC, fauxpark requested changes

2021-12-22 09:40 UTC, fauxpark commented on keyboards/mwstudio/mw65_r2/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2021-12-23 10:15 UTC, TW59420 commented
@fauxpark i fix it

2022-01-03 07:58 UTC, closed without merging

2022-01-03 08:08 UTC, peepeetee commented
Why the PR closure? Do you need language help? I can offer to add you on QICQ

您怎么把PR关了？您需要语言帮助吗？我可以加您QQ