Add new keyboard "QooLee"
qmk/qmk_firmware pull request #14977
Opened 2021-10-29 06:19 UTC by takashicompany

## Description

QooLee is a keyboard with a 30% layout with ISO Enter.
It can also be equipped with a rotary encoder.
It supports hot-swapping of keyswitches with MX sockets and mounting of LEDs.
VIA (Remap) firmware is also available.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-29 21:42 UTC, drashna approved these changes

2021-10-30 02:44 UTC, fauxpark requested changes

2021-10-30 02:44 UTC, fauxpark commented on keyboards/takashicompany/qoolee/info.json
> +    "height": 3,
```suggestion
```

2021-10-31 03:08 UTC, fauxpark approved these changes

2021-10-31 08:17 UTC, merged

2021-10-31 08:17 UTC, drashna commented
Thanks!