Move Blackplum and Tenki Directory
qmk/qmk_firmware pull request #14987
Opened 2021-10-30 09:16 UTC by eriqadams

Move blackplum and tenki Directory into pixlupkeyboards directory.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-04 05:56 UTC, drashna requested changes

2021-11-04 05:56 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-04 05:56 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-04 05:56 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-04 05:56 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-04 05:56 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/tenki.c
> +#include "tenki.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-04 05:56 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/tenki.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-10 16:06 UTC, drashna commented on keyboards/pixlupkeyboards/tenki/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-16 00:19 UTC, drashna approved these changes

2021-11-16 01:58 UTC, fauxpark requested changes

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/readme.md
> +Hardware Availability: [If you're in Indonesia you can purchase here](https://tokopedia.com/pixlup)
```suggestion
* Keyboard Maintainer: [eriqadams](https://github.com/eriqadams)
* Hardware Supported: TENKI PCB, Pro Micro
* Hardware Availability: [If you're in Indonesia you can purchase here](https://tokopedia.com/pixlup)
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/keymaps/default/keymap.c
> +    KC_P1,  	KC_P2,    	KC_P3,    		KC_PEQL,\
```suggestion
    KC_NLCK, 	KC_PSLS,    KC_PAST,    	KC_PMNS,
    KC_P7,  	KC_P8,    	KC_P9,    		KC_PPLS,
    KC_P4,  	KC_P5,    	KC_P6,    		KC_BSPC,
    KC_P1,  	KC_P2,    	KC_P3,    		KC_PEQL,
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/keymaps/default/keymap.c
> +    KC_TRNS,  KC_VOLD,    KC_TRNS,    	KC_TRNS,\
```suggestion
    KC_TRNS, 	RGB_HUI,    RGB_HUD,    	RGB_VAD,
    KC_TRNS, 	KC_VOLU,    RGB_TOG,    	RGB_VAI,
    KC_MPRV, 	KC_MUTE,    KC_MNXT,    	KC_TRNS,
    KC_TRNS,  KC_VOLD,    KC_TRNS,    	KC_TRNS,
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/blackplum/rules.mk
>  #   comment out to disable the options.
```suggestion
#   change yes to no to disable
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/keymaps/via/keymap.c
> +    KC_P1,  	KC_P2,    	KC_P3,    		KC_PEQL,\
```suggestion
    KC_NLCK, 	KC_PSLS,    KC_PAST,    	KC_PMNS,
    KC_P7,  	KC_P8,    	KC_P9,    		KC_PPLS,
    KC_P4,  	KC_P5,    	KC_P6,    		KC_BSPC,
    KC_P1,  	KC_P2,    	KC_P3,    		KC_PEQL,
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/keymaps/via/keymap.c
> +    KC_TRNS,  KC_VOLD,    KC_TRNS,    	KC_TRNS,\
```suggestion
    KC_TRNS, 	RGB_HUI,    RGB_HUD,    	RGB_VAD,
    KC_TRNS, 	KC_VOLU,    RGB_TOG,    	RGB_VAI,
    KC_MPRV, 	KC_MUTE,    KC_MNXT,    	KC_TRNS,
    KC_TRNS,  KC_VOLD,    KC_TRNS,    	KC_TRNS,
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/keymaps/via/keymap.c
> +    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,\
```suggestion
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/keymaps/via/keymap.c
> +    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,\
```suggestion
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
    KC_TRNS, 	KC_TRNS,    KC_TRNS,    	KC_TRNS,
```

2021-11-16 01:58 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-11-19 05:50 UTC, drashna approved these changes

2021-11-19 08:30 UTC, fauxpark requested changes

2021-11-19 08:30 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-11-28 06:15 UTC, drashna commented
This has merge conflicts.

2021-11-29 04:22 UTC, eriqadams commented
> This has merge conflicts.

Ok

2021-11-29 06:12 UTC, tzarc commented
Moves need to go through the `develop` branch to minimise disruption to users.

2021-12-12 16:39 UTC, fauxpark requested changes

2021-12-12 16:39 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2021-12-12 16:39 UTC, fauxpark commented on keyboards/pixlupkeyboards/tenki/rules.mk
> +
```suggestion
```

2022-08-13 02:15 UTC, closed without merging