K.O.Y and German layout for several boards
qmk/qmk_firmware pull request #14991
Opened 2021-10-30 21:19 UTC by ScheiklP

## Description

Added K.O,Y layout for several boards, as well as a German keyboard layout for xd75re.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-04 05:49 UTC, drashna requested changes

2021-11-04 05:49 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x6/keymaps/scheiklp/rules.mk
> +RGBLIGHT_DRIVER = WS2812
```suggestion
```

2021-11-04 05:49 UTC, drashna commented on keyboards/naked48/keymaps/scheiklp/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-04 05:49 UTC, drashna commented on keyboards/naked48/keymaps/scheiklp/keymap.c
> +extern uint8_t is_master;
```suggestion
```

2021-11-04 05:49 UTC, drashna commented on keyboards/naked48/keymaps/scheiklp/keymap.c
> +            RGB_current_mode = rgblight_config.mode;
```suggestion
            RGB_current_mode = rgblight_get_mode();
```

2021-11-04 05:49 UTC, drashna commented on keyboards/naked48/keymaps/scheiklp/keymap.c
> +            RGB_current_mode = rgblight_config.mode;
```suggestion
            RGB_current_mode = rgblight_get_mode();
```

2021-11-04 05:49 UTC, drashna commented on keyboards/splitreus62/keymaps/scheiklp/config.h
> +#include "config_common.h"
You do not need all of this.  Only the settings that are not set at the keyboard level.

2021-11-04 05:49 UTC, drashna commented on keyboards/splitreus62/keymaps/scheiklp/rules.mk
> +MCU = atmega32u4
You only need the values tha are changed from the keyboard level

2021-11-10 14:59 UTC, drashna requested changes

2021-11-10 14:59 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x6/keymaps/scheiklp/keymap.c
> +/* A K.O,Y layout for the Dactyl Manuform 4x6 Keyboard */
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-10 14:59 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x6/keymaps/scheiklp/keymap.c
> +#define _7 3
We highly recommend using an enum here, as it auto increments, and makes things easier to manage, long term. 
```suggestion
enum custom_layers {
    _1,
    _3,
    _4,
    _7,
};
```

2021-11-10 14:59 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/scheiklp/keymap.c
> +/* A K.O,Y layout for the Dactyl Manuform 5x6 Keyboard */
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-10 14:59 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/scheiklp/keymap.c
> +#define _7 3
```suggestion
enum custom_layers {
    _1,
    _3,
    _4,
    _7,
};
```

2021-11-10 14:59 UTC, drashna commented on keyboards/naked48/keymaps/scheiklp/keymap.c
> +}
```suggestion
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
#ifdef RGBLIGHT_ENABLE
        case RGB_RST:
            if (record->event.pressed) {
                eeconfig_update_rgblight_default();
                rgblight_enable();
            }
            break;
#endif
    }

    return true;
}
```

2021-11-10 14:59 UTC, drashna commented on keyboards/splitreus62/keymaps/scheiklp/config.h
> +/* USB Device descriptor parameter */
This should all be removed, and only changes from the keyboard level should be kept.

2021-11-10 14:59 UTC, drashna commented on keyboards/splitreus62/keymaps/scheiklp/rules.mk
> +SPLIT_KEYBOARD = yes
```suggestion
BOOTLOADER = atmel-dfu

# Build Options
AUTO_SHIFT_ENABLE = yes
BOOTMAGIC_ENABLE = no     # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = no       # Audio control and System control
NKRO_ENABLE = yes           # USB Nkey Rollover

SPLIT_KEYBOARD = yes
```

2021-11-16 00:18 UTC, drashna requested changes

2021-11-16 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x6/keymaps/scheiklpLED/config.h
> +// Copyright 2021 Paul Maria Scheikl (@ScheiklP)
Please rename the folder so that it's not using upper case.

2021-11-16 00:18 UTC, drashna commented on keyboards/xd75/config.h
> +#define DESCRIPTION     XD75Re 15x5 ortholinear keyboard
```suggestion
```

2021-11-16 00:18 UTC, drashna commented on keyboards/xd75/config.h
> +//#define MAGIC_KEY_SLEEP_LED      Z
```suggestion
```

2021-11-16 00:18 UTC, drashna commented on keyboards/xd75/config.h
> +#define RGBLIGHT_ANIMATIONS // run RGB animations
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-16 00:18 UTC, drashna commented on keyboards/xd75/keymaps/default/keymap.c
> +}
```suggestion
```

2021-11-16 00:18 UTC, drashna commented on keyboards/xd75/keymaps/scheiklb/config.h
> +// normal characters
These should not be needed. 

instead you should use `#include "keymap_german.h'`, instead.  That file contains all of these defines already: 
https://github.com/qmk/qmk_firmware/blob/master/quantum/keymap_extras/keymap_german.h

2021-11-16 00:18 UTC, drashna commented on keyboards/xd75/keymaps/scheiklb/keymap.c
> +#endif
```suggestion
#include "keymap_german.h"
```

2021-11-19 04:12 UTC, drashna commented on keyboards/xd75/config.h
> +/*
this file should be removed.

Specifically, it resides in `keyboards/xiud/xd75` already.

2021-11-28 06:13 UTC, drashna commented
This has some merge conflicts that needs to be resolved.

2021-11-28 17:56 UTC, drashna approved these changes

2021-12-27 03:40 UTC, tzarc approved these changes

2021-12-27 03:40 UTC, merged