add bm60v2_poker
qmk/qmk_firmware pull request #15001
Opened 2021-11-01 13:21 UTC by bdtc123

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-01 15:00 UTC, sigprof requested changes

2021-11-05 02:37 UTC, drashna requested changes

2021-11-05 02:37 UTC, drashna commented on keyboards/bm60v2_poker/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-05 02:37 UTC, drashna commented on keyboards/bm60v2_poker/config.h
> +    #define RGB_MATRIX_DISABLE_KEYCODES
```suggestion
#    define RGB_MATRIX_DISABLE_KEYCODES
```

2021-11-05 02:37 UTC, drashna commented on keyboards/bm60v2_poker/rules.mk
> +BOOTMAGIC_ENABLE = lite        # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-06 12:25 UTC, peepeetee commented
Take a look at my #15040, which concerns bm60poker
see if you can target develop and move this to bm60poker/rev2, or wait until next breaking change

2021-11-07 15:55 UTC, bdtc123 commented
> 我的#15040，它与 bm60poker 相关， 您是否可以将开发目标移至 bm60poker/rev2，或者下次看看重大变化



> 看看我的#15040，它与 bm60poker 相关， 看看您是否可以将开发目标移至 bm60poker/rev2，或者等到下一次重大更改



> Take a look at my #15040, which concerns bm60poker see if you can target develop and move this to bm60poker/rev2, or wait until next breaking change

Ok，may i have your email address?

2021-11-07 19:36 UTC, peepeetee commented
> 
> 
> > 我的#15040，它与 bm60poker 相关， 您是否可以将开发目标移至 bm60poker/rev2，或者下次看看重大变化
> 
> > 看看我的#15040，它与 bm60poker 相关， 看看您是否可以将开发目标移至 bm60poker/rev2，或者等到下一次重大更改
> 
> > Take a look at my #15040, which concerns bm60poker see if you can target develop and move this to bm60poker/rev2, or wait until next breaking change
> 
> Ok，may i have your email address?

8行(
看我profile啊

2022-01-05 05:37 UTC, peepeetee commented
As I've mentioned in the description of #15103, after a discussion with @bdtc123, we decided to have me take over this PR and reincarnate it as #15103, which is already merged. This PR should be able to be safely closed now.

2022-01-05 05:38 UTC, closed without merging