Add Ziggurat keyboard
qmk/qmk_firmware pull request #15008
Opened 2021-11-01 23:10 UTC by kb-elmo

## Description

Adds support for the Ziggurat keyboard (future groupbuy).

The readme currently doesn't have an image or a link to the project because it's not public yet. They will be added later.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-04 06:15 UTC, drashna approved these changes

2021-11-04 07:14 UTC, fauxpark requested changes
Looks good, pending readme image.

2021-11-04 07:14 UTC, fauxpark commented on keyboards/ziggurat/keymaps/iso/keymap.c
> +        KC_F7,   KC_F8,     KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN,
```suggestion
        KC_F7,   KC_F8,     KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN,
```

2021-11-04 07:14 UTC, fauxpark commented on keyboards/ziggurat/keymaps/default/keymap.c
> +        KC_F7,   KC_F8,     KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN,
```suggestion
        KC_F7,   KC_F8,     KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN,
```

2021-11-04 07:14 UTC, fauxpark commented on keyboards/ziggurat/keymaps/via/keymap.c
> +        KC_F7,   KC_F8,     KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN,
```suggestion
        KC_F7,   KC_F8,     KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_PGDN,
```

2021-11-05 18:23 UTC, fauxpark approved these changes

2021-11-05 18:48 UTC, merged