add kbd67mkiirgb v4 support
qmk/qmk_firmware pull request #15024
Opened 2021-11-02 07:11 UTC by moyi4681

add kbd67mkiirgb v4 support

2021-11-04 06:17 UTC, drashna requested changes

2021-11-04 06:17 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v4/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
```

2021-11-04 06:17 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v4/rules.mk
> +RGB_MATRIX_DRIVER = WS2812
```suggestion
RGB_MATRIX_DRIVER = WS2812

```

2021-11-04 06:17 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v4/v4.c
> +#endif
```suggestion
#endif

```

2021-11-28 06:11 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v4/config.h
> +#ifdef RGB_MATRIX_ENABLE
Just a heads up, RGB Matrix animation modes are now explicitly enabled, and are not enabled by default. 

```c
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_PIXEL_RAIN

#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
```

2022-01-07 22:47 UTC, noroadsleft requested changes

2022-01-07 22:47 UTC, noroadsleft commented on keyboards/kbdfans/kbd67/mkiirgb/v4/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-09 03:30 UTC, drashna requested changes

2022-01-09 03:30 UTC, drashna commented on keyboards/kbdfans/kbd67/mkiirgb/v4/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-01-10 10:25 UTC, noroadsleft requested changes

2022-01-10 10:25 UTC, noroadsleft commented on keyboards/kbdfans/kbd67/mkiirgb/v4/config.h
> +#define PRODUCT         KBD67MKIIRGB_V4
```suggestion
#define PRODUCT         KBD67 MKII RGB V4
```

2022-01-11 02:56 UTC, noroadsleft approved these changes
Looks good to me.

2022-01-11 03:11 UTC, drashna approved these changes

2022-01-11 03:12 UTC, merged