Add new keyboard "Heavy Left"
qmk/qmk_firmware pull request #15052
Opened 2021-11-04 12:30 UTC by takashicompany

## Description

This is a 95-key split type Japanese keyboard.  
It has a numeric keypad on the left hand side, which can be used not only for entering numbers but also as a dedicated macro pad.  
It also supports key switch replacement with MX sockets and LED underglow.  

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-04 22:43 UTC, drashna requested changes

2021-11-04 22:43 UTC, drashna commented on keyboards/takashicompany/heavy_left/config.h
> +#    define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-04 22:43 UTC, drashna commented on keyboards/takashicompany/heavy_left/keymaps/default/keymap.c
> +    KC_00
```suggestion
    KC_00 = SAFE_RANGE`
```

2021-11-04 22:43 UTC, drashna commented on keyboards/takashicompany/heavy_left/keymaps/via/keymap.c
> +    KC_00
```suggestion
    KC_00 = USER00,
```

2021-11-05 15:30 UTC, drashna approved these changes

2021-11-05 16:44 UTC, mtei commented on keyboards/takashicompany/heavy_left/keymaps/default/keymap.c
> +    KC_00 = SAFE_RANGE`
```suggestion
    KC_00 = SAFE_RANGE
```

2021-11-05 18:24 UTC, fauxpark commented on keyboards/takashicompany/heavy_left/keymaps/via/keymap.c
> +                // when keycode QMKBEST is pressed
```suggestion
```

2021-11-05 18:24 UTC, fauxpark commented on keyboards/takashicompany/heavy_left/keymaps/via/keymap.c
> +            break;
```suggestion
            return false;
```

2021-11-05 18:25 UTC, fauxpark commented on keyboards/takashicompany/heavy_left/keymaps/default/keymap.c
> +            break;
```suggestion
            return false;
```

2021-11-05 18:25 UTC, fauxpark commented on keyboards/takashicompany/heavy_left/keymaps/default/keymap.c
> +
```suggestion
```

2021-11-06 14:23 UTC, mtei approved these changes

2021-11-06 15:41 UTC, drashna approved these changes

2021-11-06 15:41 UTC, merged