Add BM65RGB/rev2
qmk/qmk_firmware pull request #15060
Opened 2021-11-05 07:57 UTC by peepeetee

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-10 16:13 UTC, drashna requested changes

2021-11-10 16:13 UTC, drashna commented on keyboards/kprepublic/bm65rgb/rev2/rev2.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-13 03:10 UTC, rotaryking commented
After flashing on my BM65V2, it works successfully

2021-11-15 17:16 UTC, drashna approved these changes

2021-12-02 11:32 UTC, fauxpark requested changes

2021-12-02 11:32 UTC, fauxpark commented on keyboards/kprepublic/bm65hsrgb/rev2/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
```suggestion
```

2021-12-10 04:33 UTC, fauxpark requested changes

2021-12-10 04:33 UTC, fauxpark commented on keyboards/kprepublic/bm65hsrgb/rev2/rules.mk
> +
```suggestion
```

2021-12-10 04:35 UTC, peepeetee commented on keyboards/kprepublic/bm65hsrgb/rev2/rules.mk
> +
Why?

2021-12-24 00:27 UTC, rotaryking commented
![image](https://user-images.githubusercontent.com/66388490/147301735-a2d9fdea-7bf8-430a-80b4-a20547e7d726.png)
error within rev2.c

2021-12-24 03:20 UTC, peepeetee commented
@rotaryking compiles fine after my latest commit, 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/43021794/147311964-9c974551-4d20-4cb1-92be-c01f693e4424.png">
<img width="141" alt="image" src="https://user-images.githubusercontent.com/43021794/147311995-f868d47b-da69-420d-ab70-fb6a15fe5f7f.png">

2021-12-24 20:31 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/keymaps/peepeetee/config.h
> +#define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN              // Static gradient top to bottom, speed controls how much gradient changes
These need to be updated.

2022-02-07 07:47 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/keymaps/peepeetee/config.h
> +#define USB_POLLING_INTERVAL_MS 1
May not be worth having, as this is the default on develop, and due to be merged soon

2022-02-07 07:47 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/keymaps/peepeetee/config.h
> +#define USB_POLLING_INTERVAL_MS 1
May not be worth having, as this is the default on develop, and due to be merged soon

2022-02-07 07:49 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/rules.mk
> +RGB_MATRIX_ENABLE = yes
Would probably be a good idea to add: 
```suggestion
RGB_MATRIX_ENABLE = yes
RGBLIGHT_SUPPORTED = no
```

2022-02-07 07:49 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/rules.mk
> +RGB_MATRIX_ENABLE = yes
Would probably be a good idea to add: 
```suggestion
RGB_MATRIX_ENABLE = yes
RGBLIGHT_SUPPORTED = no
```

2022-02-08 01:42 UTC, fauxpark requested changes

2022-02-08 01:42 UTC, fauxpark commented on keyboards/kprepublic/bm65hsrgb/rev2/rules.mk
> +
```suggestion
```

2022-03-01 19:53 UTC, 4itor commented
Sorry about the noob question, is it possible to compile QMK for the board (rev2) before this pull-request gets finished?

Thanks in advance.

PD: Wanting to play with tap-dance and combos so bad :)

2022-04-24 19:24 UTC, 4itor commented
Please, what is missing for the pull request to succeed?
Can we help?

2022-06-26 16:37 UTC, peepeetee commented
Rebased just now, should have resolved the conflicts

2022-07-02 18:03 UTC, drashna commented
> ☒ kprepublic/bm65hsrgb/rev2: NO_ACTION_MACRO in config.h is no longer a valid option
> ☒ kprepublic/bm65hsrgb/rev2: NO_ACTION_FUNCTION in config.h is no longer a valid option

2022-12-26 19:35 UTC, CerebroJD commented
Is there an opportunity to get these changes merged into qmk so these v2 boards are supported?

2023-03-14 22:46 UTC, chigzy commented
What’s remaining for this?
Anywhere to help?

2023-03-15 05:31 UTC, peepeetee commented
> What’s remaining for this? Anywhere to help?

just had to poke me, and you did

2023-04-19 19:37 UTC, noroadsleft commented
This PR needs to be rebased upon a current `qmk:master` – there are a lot of merge conflicts, which makes this unable to be merged.

2023-04-19 20:20 UTC, peepeetee commented
> This PR needs to be rebased upon a current `qmk:master` – there are a lot of merge conflicts, which makes this unable to be merged.

I need to undo [b67c072](https://github.com/qmk/qmk_firmware/pull/15060/commits/b67c072682f9b6bb1a61492f71e91169d72460a8) and rebase on master instead. how would I do that?

2023-05-03 01:14 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/config.h
> +//#define DIODE_DIRECTION COL2ROW
This should be removed, not just commented out.

2023-05-03 01:14 UTC, drashna commented on keyboards/kprepublic/bm65hsrgb/rev2/config.h
> +    #define RGBLED_NUM 6
These may need to be updated.

2023-07-17 02:13 UTC, closed without merging

2023-11-03 19:49 UTC, AstralCookie commented
Any updates on this? Just got myself a BM65V2 and I want to change the backlight's LED's color