Added b87 keyboard
qmk/qmk_firmware pull request #15091
Opened 2021-11-08 15:15 UTC by Jels-kb

## Description

Added QMK support for the B87, a board produced by winkeyless.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-10 15:34 UTC, drashna requested changes

2021-11-10 15:34 UTC, drashna commented on keyboards/winkeyless/b87/info.json
> +    "height": 6.25,
```suggestion
```

2021-11-10 15:34 UTC, drashna commented on keyboards/winkeyless/b87/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```suggestion
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2021-11-10 15:34 UTC, drashna commented on keyboards/winkeyless/b87/rules.mk
> +WS2812_DRIVER = i2c
```suggestion
# Bootloader selection
BOOTLOADER = bootloadHID

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = yes 	    # Enable keyboard backlight functionality
AUDIO_ENABLE = no           # Audio output
RGBLIGHT_ENABLE = yes       # Enable WS2812 RGB underlight.
WS2812_DRIVER = i2c
```

2021-11-15 23:30 UTC, drashna requested changes

2021-11-15 23:30 UTC, drashna commented on keyboards/winkeyless/b87/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-15 23:30 UTC, drashna commented on keyboards/winkeyless/b87/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-11-15 23:30 UTC, drashna commented on keyboards/winkeyless/b87/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
```

2021-11-19 04:05 UTC, drashna approved these changes

2021-11-19 06:32 UTC, fauxpark requested changes

2021-11-19 06:32 UTC, fauxpark commented on keyboards/winkeyless/b87/rules.mk
> +WS2812_DRIVER = i2c
```suggestion

# Bootloader selection
BOOTLOADER = bootloadhid

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
WS2812_DRIVER = i2c
```

2021-11-19 08:40 UTC, fauxpark approved these changes

2021-11-19 17:51 UTC, merged

2021-11-19 17:51 UTC, drashna commented
Thanks!