Add Yunomi Support
qmk/qmk_firmware pull request #15119
Opened 2021-11-11 06:10 UTC by Dafondo

## Description

Adds support for [mozc-yunomi](https://github.com/google/mozc-devices/tree/master/mozc-yunomi)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-11 17:27 UTC, zvecr requested changes

2021-11-11 17:27 UTC, zvecr commented on keyboards/yunomi/keymaps/default/config.h
> +/* Unicode input modes
```suggestion
// Copyright 2021 Austin Wang (@Dafondo)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once 

/* Unicode input modes 
```

2021-11-11 17:27 UTC, zvecr commented on keyboards/yunomi/rules.mk
> +UNICODEMAP_ENABLE = yes
Should not be enabled at the keyboard level
```suggestion
```

2022-01-07 03:26 UTC, drashna requested changes

2022-01-07 03:26 UTC, drashna commented on keyboards/yunomi/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-06-12 15:56 UTC, closed without merging