Add macro3 PCB support
qmk/qmk_firmware pull request #15131
Opened 2021-11-12 06:56 UTC by filterpaper

## Description

Add support for macro3 PCB

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-12 14:45 UTC, zvecr requested changes

2021-11-12 14:45 UTC, zvecr commented on keyboards/macro3/config.h
> +#define PREVENT_STUCK_MODIFIERS
```suggestion
```

2021-11-12 22:28 UTC, drashna requested changes

2021-11-12 22:28 UTC, drashna commented on keyboards/macro3/keymaps/default/keymap.c
> +#endif
```suggestion
```

2021-11-12 22:28 UTC, drashna commented on keyboards/macro3/macro3.c
> +
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 1) {
        if (clockwise) {
            tap_code(KC_VOLD);
        } else {
            tap_code(KC_VOLU);
        }
    } else if (index == 0) {
        if (clockwise) {
            tap_code(KC_PGDN);
        } else {
            tap_code(KC_PGUP);
        }
    }
    return true;
}
#endif
```

2021-11-15 23:23 UTC, drashna requested changes

2021-11-15 23:23 UTC, drashna commented on keyboards/macro3/rules.mk
> +SPLIT_KEYBOARD = no         # Use shared split_common code
```suggestion

```

2021-11-15 23:23 UTC, drashna commented on keyboards/macro3/rules.mk
> +UNICODE_ENABLE = yes        # Unicode
```suggestion
```

2021-11-15 23:42 UTC, drashna approved these changes

2021-11-15 23:52 UTC, fauxpark approved these changes

2021-11-15 23:52 UTC, fauxpark commented on keyboards/macro3/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
```

2021-11-15 23:52 UTC, fauxpark commented on keyboards/macro3/rules.mk
> +
```suggestion
ENCODER_ENABLE = yes
```

2021-11-16 01:05 UTC, merged

2021-11-16 01:05 UTC, drashna commented
Thanks!