Add Keebcats Denis PCB
qmk/qmk_firmware pull request #15154
Opened 2021-11-14 21:25 UTC by mini-ninja-64

This PR adds the Denis 60% PCB

## Description

Currently the picture in the readme is not of a production unit, I will update this as soon as production units arrive :)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-15 22:55 UTC, drashna requested changes

2021-11-15 22:55 UTC, drashna commented on keyboards/cutie_club/keebcats/denis/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion

# Bootloader selection
BOOTLOADER = atmel-dfu
```

2021-11-15 22:55 UTC, drashna commented on keyboards/cutie_club/keebcats/denis/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-11-15 22:55 UTC, drashna commented on keyboards/cutie_club/keebcats/denis/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-15 22:55 UTC, drashna commented on keyboards/cutie_club/keebcats/denis/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-15 22:55 UTC, drashna commented on keyboards/cutie_club/keebcats/denis/rules.mk
> +LAYOUTS = 60_iso_tsangan 60_iso_split_bs_rshift 60_iso 60_tsangan_hhkb 60_hhkb 60_ansi_tsangan 60_ansi_split_bs_rshift 60_ansi
```suggestion

LAYOUTS = 60_iso_tsangan 60_iso_split_bs_rshift 60_iso 60_tsangan_hhkb 60_hhkb 60_ansi_tsangan 60_ansi_split_bs_rshift 60_ansi
```

2021-11-16 13:16 UTC, mini-ninja-64 commented
@drashna thank you so much for the changes, I have made them now :)

2021-11-19 05:55 UTC, drashna approved these changes

2021-11-19 08:33 UTC, fauxpark approved these changes

2021-11-19 17:51 UTC, merged

2021-11-19 17:51 UTC, drashna commented
Thanks!