Add KBIC65 keyboard
qmk/qmk_firmware pull request #15151
Opened 2021-11-14 12:41 UTC by b-karl

## Description

After receiving requests to add QMK and VIA support for the [KBIC65 keyboard](https://github.com/b-karl/KBIC65) I would like to officially merge my keyboard definition with the QMK master branch. It is an open-source 65% FR4-stack keyboard with through-hole diodes and a ProMicro footprint, for all features please see [the GitHub repo for the board](https://github.com/b-karl/KBIC65) itself.
 
## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-14 12:45 UTC, b-karl commented
Items I believe are left:
- [ ] Harmonize keymaps between default and VIA
- [ ] Create default ANSI and ISO layouts
- [ ] Create an alternative full-key layout
- [ ] Test firmware again on real board

2021-11-15 22:58 UTC, drashna requested changes

2021-11-15 22:58 UTC, drashna commented on keyboards/karlb/kbic65/info.json
> +    "height": 5.25,
```suggestion
```

2021-11-15 22:58 UTC, drashna commented on keyboards/karlb/kbic65/info.json
> +        "vid": "0xFEED",
```suggestion
        "vid": "0x424B",
```

2021-11-15 22:58 UTC, drashna commented on keyboards/karlb/kbic65/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
We do recommend enabling bootmagic lite by default.  Especially, as it's enabled as part of VIA.
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-15 22:58 UTC, drashna commented on keyboards/karlb/kbic65/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-16 08:19 UTC, b-karl commented
@drashna Thanks for the comments/changes, have accepted all of them. Looked around and compared to other merged keyboard PRs, but just to double check, is there any other documentation then the readme.md for the keyboard itself that I should update? And are there any tests I should implement or run, except for testing the final firmware on an actual keyboard?

2021-11-19 04:08 UTC, drashna requested changes

2021-11-19 04:08 UTC, drashna commented on keyboards/karlb/kbic65/config.h
> +#define DIODE_DIRECTION ROW2COL
This is redundant. 
```suggestion
```

2022-01-03 20:51 UTC, b-karl commented
Sorry for keeping this sitting, busy life. Will try to work on it soon to finish the last points that I commented on previously.

2022-01-07 03:19 UTC, drashna approved these changes

2022-01-10 21:57 UTC, fauxpark requested changes

2022-01-10 21:57 UTC, fauxpark commented on keyboards/karlb/kbic65/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-10 21:57 UTC, fauxpark commented on keyboards/karlb/kbic65/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
```suggestion
```

2022-01-11 09:58 UTC, fauxpark approved these changes

2022-01-12 23:05 UTC, drashna commented
Thanks

2022-01-12 23:05 UTC, merged