add 5-row support for an existing board, Quark^2
qmk/qmk_firmware pull request #15188
Opened 2021-11-17 12:14 UTC by npspears

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-17 12:16 UTC, npspears commented
thanks for looking this over...again. Hopefully everything is correct this time

2021-11-19 05:05 UTC, drashna requested changes

2021-11-19 05:05 UTC, drashna commented on keyboards/checkerboards/quark_squared/info.json
> +    "url": "https://www.github.com/qmk/qmk_firmware/tree/master/keyboards/checkerboards/quark_squared",
This should be a URL to the store or repo for the pcb files, or the like.

2021-11-19 05:05 UTC, drashna commented on keyboards/checkerboards/quark_squared/info.json
> +        "LAYOUT_4_2x225u": {
Something like this would be better: 
```suggestion
        "LAYOUT_ortho_4x12_2x225u": {
```

2021-11-28 05:30 UTC, drashna approved these changes

2021-12-27 03:32 UTC, tzarc approved these changes

2021-12-27 03:32 UTC, merged