Adding Charon keyboard to Charue family
qmk/qmk_firmware pull request #15190
Opened 2021-11-17 16:12 UTC by PiKeeb

## Description

Added Charon keyboard to the Charue family

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (**addition** or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-19 05:14 UTC, drashna requested changes

2021-11-19 05:14 UTC, drashna commented on keyboards/charue/charon/info.json
> +    "height": 2,
```suggestion
```

2021-11-19 05:14 UTC, drashna commented on keyboards/charue/charon/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-26 11:42 UTC, PiKeeb commented
@drashna done. All requested changes are in!

2021-11-28 05:30 UTC, drashna approved these changes

2021-12-27 03:28 UTC, tzarc commented
Please refer to the QMK [PR Checklist](https://docs.qmk.fm/#/pr_checklist) and work through all the required changes.
There are a few obvious things in the PR (most obvious being `QMKBEST`) that show that the PR checklist hasn't been consulted; this document helps us keep things standard as much as possible and makes it easier for reviews to occur.

2021-12-27 05:28 UTC, fauxpark requested changes

2021-12-27 05:28 UTC, fauxpark commented on keyboards/charue/charon/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-27 05:28 UTC, fauxpark commented on keyboards/charue/charon/readme.md
> +![Charon](https://i.imgur.com/fnQLZ2T.jpg)
```suggestion
![Charon](https://i.imgur.com/fnQLZ2Th.jpg)
```

2021-12-27 05:28 UTC, fauxpark commented on keyboards/charue/charon/readme.md
> +    make charon:default:flash
```suggestion
    make charue/charon:default

Flashing example for this keyboard:

    make charue/charon:default:flash
```

2021-12-27 12:18 UTC, PiKeeb commented
@tzarc

> Please refer to the QMK [PR Checklist](https://docs.qmk.fm/#/pr_checklist) and work through all the required changes.
> There are a few obvious things in the PR (most obvious being `QMKBEST`) that show that the PR checklist hasn't been consulted; this document helps us keep things standard as much as possible and makes it easier for reviews to occur.

Thanks for your comments. The `default` or `via` keymaps does not contain `QMKURL`/`QMKBEST`. It's in the `debug` keymap and is there for debug purposes (to check how it handles these `SEND_STRING` commands). I can change these to something different, if needed.

Before doing the PR, I've tried to follow the PR Checklist to the T, but I think I might have slipped on a few points. I'll check and adjust, but can you look at my PR as well? That would be very helpful.

2021-12-27 17:58 UTC, drashna approved these changes

2021-12-28 04:13 UTC, fauxpark approved these changes

2021-12-29 10:57 UTC, merged