Add firmware for the RooPad
qmk/qmk_firmware pull request #15215
Opened 2021-11-19 10:32 UTC by ToastyStoemp

## Description

Firmware for small little numpad with macro keys.
Per key RGB 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-20 03:52 UTC, drashna requested changes

2021-11-20 03:52 UTC, drashna commented on keyboards/wolf/roopad/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-11-28 05:17 UTC, drashna approved these changes

2021-11-29 07:38 UTC, fauxpark requested changes

2021-11-29 07:38 UTC, fauxpark commented on keyboards/skippys_custom_pcs/roopad/keymaps/via/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
```suggestion
                 KC_NLCK, KC_PSLS, KC_PAST, RGB_VAD,
        KC_TRNS, KC_F7,   KC_F8,   KC_F9,   RGB_VAI,
        KC_TRNS, KC_F4,   KC_F5,   KC_F6,
        KC_TRNS, KC_F1,   KC_F2,   KC_F3,   RGB_MOD,
        KC_TRNS, KC_TRNS,          RGB_TOG     
    ),

    [_LAYER2] = LAYOUT(
                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS,          KC_TRNS     
    ),

    [_LAYER3] = LAYOUT(
                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2021-11-29 07:38 UTC, fauxpark commented on keyboards/skippys_custom_pcs/roopad/keymaps/via/keymap.c
> +        KC_MAIL, KC_P1,   KC_P2,   KC_P3,   KC_PENT, \
```suggestion
                 KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
        KC_CALC, KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_WSCH, KC_P4,   KC_P5,   KC_P6,
        KC_MAIL, KC_P1,   KC_P2,   KC_P3,   KC_PENT,
```

2021-11-29 07:38 UTC, fauxpark commented on keyboards/skippys_custom_pcs/roopad/keymaps/default/keymap.c
> +        KC_TRNS, KC_F1,   KC_F2,   KC_F3,   RGB_MOD, \
```suggestion
                 KC_NLCK, KC_PSLS, KC_PAST, RGB_VAD,
        KC_TRNS, KC_F7,   KC_F8,   KC_F9,   RGB_VAI,
        KC_TRNS, KC_F4,   KC_F5,   KC_F6,
        KC_TRNS, KC_F1,   KC_F2,   KC_F3,   RGB_MOD,
```

2021-11-29 07:38 UTC, fauxpark commented on keyboards/skippys_custom_pcs/roopad/keymaps/default/keymap.c
> +        KC_MAIL, KC_P1,   KC_P2,   KC_P3,   KC_PENT, \
```suggestion
                 KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
        KC_CALC, KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_WSCH, KC_P4,   KC_P5,   KC_P6,
        KC_MAIL, KC_P1,   KC_P2,   KC_P3,   KC_PENT,
```

2021-11-29 12:52 UTC, fauxpark approved these changes

2021-11-29 16:27 UTC, merged