Add new keyboard "DogTag"
qmk/qmk_firmware pull request #15259
Opened 2021-11-22 04:30 UTC by takashicompany

DogTag is a compact macro pad with 9 keys.  
It is assembled from a PCB no larger than 100mm x 100mm.  
It is reversible and can be used as a split macro pad by connecting two units with a TRRS cable.  
Other features include a rotary encoder and MX sockets for hot-swapping of keyswitches.  
LED underglow is also available.  

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-22 04:33 UTC, takashicompany commented
Thank you for all your help.
I know you are busy, but please don't forget to review these Pull Requests🙏

https://github.com/qmk/qmk_firmware/pull/14949
https://github.com/qmk/qmk_firmware/pull/15077

2021-11-28 04:47 UTC, drashna requested changes

2021-11-28 04:47 UTC, drashna commented on keyboards/takashicompany/dogtag/keymaps/default/keymap.c
> +}
```suggestion
```

2021-11-28 04:47 UTC, drashna commented on keyboards/takashicompany/dogtag/keymaps/via/keymap.c
> +}
```suggestion
```

2021-11-28 04:47 UTC, drashna commented on keyboards/takashicompany/dogtag/dogtag.c
> +#include "dogtag.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "dogtag.h"

bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (clockwise) {
        tap_code(KC_MS_WH_DOWN);
    } else {
        tap_code(KC_MS_WH_UP);
    }

    return true;
}
```

2021-11-28 17:35 UTC, drashna approved these changes

2021-11-29 08:01 UTC, fauxpark approved these changes

2021-11-29 08:20 UTC, merged