adding carlosala keymap to kprepublic/bm60poker
qmk/qmk_firmware pull request #15281
Opened 2021-11-23 13:38 UTC by carlosala

I added my own keymap to kprepublic/bm60poker keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-28 04:27 UTC, drashna requested changes

2021-11-28 04:27 UTC, drashna commented on keyboards/kprepublic/bm60poker/keymaps/carlosala/config.h
> +#define UNICODE_SELECTED_MODES UC_LNX
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

Also, this needs `#pragma once` before the define.

2021-11-28 04:27 UTC, drashna commented on keyboards/kprepublic/bm60poker/keymaps/carlosala/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-28 11:23 UTC, carlosala commented
Thanks for the comments @drashna, now it's done!

2021-11-28 17:17 UTC, drashna approved these changes

2021-11-29 07:33 UTC, fauxpark approved these changes

2021-11-29 08:18 UTC, merged