Make default layer size 8-bit
qmk/qmk_firmware pull request #15286
Opened 2021-11-23 20:36 UTC by drashna

## Description

Set the layer state to be 8 bit by default.  As most keyboards don't use more than 8 (or even 8) layers, and maxing out at 8 allows for smaller compile size (and in theory, faster scans), it makes sense to reduce the size. 

## Types of Changes

- [x] Core
- [ ] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-24 13:32 UTC, KarlK90 approved these changes
LGTM and is a sane default.

2021-11-27 18:01 UTC, precondition commented
I can already hear the unrest that would come from the havoc caused by all the `biton32` in the wild no longer working. Other than that, I'm in favor of this.

2021-11-27 18:03 UTC, fauxpark commented
That's why you're supposed to use `get_highest_layer()` instead ;)

2021-11-27 18:04 UTC, precondition commented
Yes, indeed but I still see too many people on the QMK discord server posting code bits using `biton32` instead of `get_highest_layer` :(

2021-11-27 18:11 UTC, precondition approved these changes

2021-11-27 18:19 UTC, precondition commented
Speaking of `biton32`, shouldn't the ~265 user files calling the `biton32` function in place of `get_highest_layer` get changed in this PR too? For example:
```
keyboards/bpiphany/kitten_paw/keymaps/ickerwx/keymap.c:135:    layer = biton32(layer_state);
```

2021-11-27 18:19 UTC, fauxpark commented
We try to avoid changing user code en masse like that...

2021-11-27 18:23 UTC, drashna commented
> Yes, indeed but I still see too many people on the QMK discord server posting code bits using `biton32` instead of `get_highest_layer` :(

That's because it in a lot of the default keymaps.  And people copy and paste code. 

But I've been flagging that in any new PRs, so more copy-paste code hasn't been incorrectly added.

2021-11-28 02:52 UTC, drashna commented
> Speaking of `biton32`, shouldn't the ~265 user files calling the `biton32` function in place of `get_highest_layer` get changed in this PR too? For example:
> 
> ```
> keyboards/bpiphany/kitten_paw/keymaps/ickerwx/keymap.c:135:    layer = biton32(layer_state);
> ```

Also, some of the rational behind not changing all of the user files doing this (besides, "that's a lot of work"), is that using biton32 will work and "fail gracefully". So there is no harm in leaving it. But future examples and the default keymps *should* use the correct function.

2021-12-02 22:55 UTC, zvecr commented
Also worth noting that the configurator currently supports more than 8 layers.

2021-12-04 06:21 UTC, drashna commented
> Also worth noting that the configurator currently supports more than 8 layers. And some keyboards also set `DYNAMIC_KEYMAP_LAYER_COUNT` greater than 8.

The dynamic keymap layer count is already taken into account, but github doesn't show a lot of context.  Literally, right above: 

https://github.com/qmk/qmk_firmware/blob/c76cfc2d36ead86a5ec9e4d5061a28987b0bca18/quantum/action_layer.h#L24-L41

However, the configurator is a good point, and this PR should wait to be merged until there is something in place to handle that.

2022-01-13 04:05 UTC, noroadsleft commented
Merge conflicts.

2022-01-22 18:10 UTC, fauxpark requested changes

2022-01-22 18:10 UTC, fauxpark commented on keyboards/helix/rev3_5rows/keymaps/five_rows/keymap.c
>      current_default_layer = biton32(state);
```suggestion
    current_default_layer = get_highest_layer(state);
```
?

2022-01-22 18:10 UTC, fauxpark commented on keyboards/helix/rev2/keymaps/five_rows/keymap.c
>      current_default_layer = biton32(state);
```suggestion
    current_default_layer = get_highest_layer(state);
```

2022-01-22 18:10 UTC, fauxpark commented on keyboards/helix/rev2/keymaps/edvorakjp/keymap.c
>      switch (biton32(state)) {
```suggestion
    switch (get_highest_layer(state)) {
```

2022-02-06 03:00 UTC, drashna commented
> Also worth noting that the configurator currently supports more than 8 layers. And some keyboards also set `DYNAMIC_KEYMAP_LAYER_COUNT` greater than 8.

Default set to 16, which matches the max of what the configurator supports.  So, between that, and the "autodetection" based on the dynamic layers define, it should cover all the bases, for now.

2022-02-08 01:53 UTC, noroadsleft commented on quantum/action_layer.h
> +#    define get_highest_layer(state) get_highest_layer(state)
:thinking:

2022-02-08 02:41 UTC, drashna commented on quantum/action_layer.h
> +#    define get_highest_layer(state) get_highest_layer(state)
blind find replace strikes again. 😅 
```suggestion
#    define get_highest_layer(state) biton32(state)
```

2022-02-12 01:16 UTC, fauxpark commented
Merge conflicts :(

2022-03-04 05:18 UTC, noroadsleft approved these changes

2022-04-05 22:07 UTC, tzarc approved these changes

2022-05-15 11:15 UTC, tzarc commented
Seems to break the helix boards.

2022-05-15 11:16 UTC, tzarc commented
Deferred to Q3 so helix can be fixed and verified.

2022-06-18 03:38 UTC, drashna commented
> Deferred to Q3 so helix can be fixed and verified.

How was this breaking the helix boards?  

I do see one keymap that won't compile, but that's because it's doing some really weird stuff.  All the rest compile.  However, I don't have a board to test on.

2022-06-18 06:53 UTC, tzarc commented
I don't remember, and at this stage I'm inclined to say "develop can break, we can fix over time if issues occur".

2022-06-18 21:37 UTC, merged