Add kikkou keyboard
qmk/qmk_firmware pull request #15291
Opened 2021-11-24 17:26 UTC by matthewdias

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2021-11-28 04:21 UTC, drashna requested changes

2021-11-28 04:21 UTC, drashna commented on keyboards/kikkou/rules.mk
> +BOOTMAGIC_ENABLE = lite	    # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-11-28 04:21 UTC, drashna commented on keyboards/kikkou/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-12-04 06:10 UTC, drashna approved these changes

2021-12-04 10:04 UTC, fauxpark requested changes

2021-12-04 10:04 UTC, fauxpark commented on keyboards/kikkou/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-01-08 03:28 UTC, noroadsleft requested changes
* renames `LAYOUT_all` to `LAYOUT_65_ansi_blocker`
* renames `LAYOUT_tsangan` to `LAYOUT_65_ansi_blocker_tsangan`

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/kikkou.h
> +#define LAYOUT_all( \
```suggestion
#define LAYOUT_65_ansi_blocker( \
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/info.json
> +        "LAYOUT_all": {
```suggestion
        "LAYOUT_65_ansi_blocker": {
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/default/keymap.c
> +	[0] = LAYOUT_all(
```suggestion
	[0] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/default/keymap.c
> +	[1] = LAYOUT_all(
```suggestion
	[1] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/default/keymap.c
> +	[2] = LAYOUT_all(
```suggestion
	[2] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/default/keymap.c
> +	[3] = LAYOUT_all(
```suggestion
	[3] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/via/keymap.c
> +	[0] = LAYOUT_all(
```suggestion
	[0] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/via/keymap.c
> +	[1] = LAYOUT_all(
```suggestion
	[1] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/via/keymap.c
> +	[2] = LAYOUT_all(
```suggestion
	[2] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/keymaps/via/keymap.c
> +	[3] = LAYOUT_all(
```suggestion
	[3] = LAYOUT_65_ansi_blocker(
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/kikkou.h
> +#define LAYOUT_tsangan( \
```suggestion
#define LAYOUT_65_ansi_blocker_tsangan( \
```

2022-01-08 03:28 UTC, noroadsleft commented on keyboards/kikkou/info.json
> +        "LAYOUT_tsangan": {
```suggestion
        "LAYOUT_65_ansi_blocker_tsangan": {
```

2022-02-20 05:50 UTC, noroadsleft approved these changes

2022-02-20 05:52 UTC, merged

2022-02-20 05:52 UTC, noroadsleft commented
Thanks!