handwired/sono1: Teensy2.0++ revision, VIA keymap, documentation
qmk/qmk_firmware pull request #15296
Opened 2021-11-25 10:34 UTC by DmNosachev

Another ASkeyboard Sono1 + Sono 2 numpad controller replacement project. I've used Teensy2.0++ this time as it almost perfectly fits to the footprint and pinout of original MCU.

## Description
1. Separated the revisions: `t2pp` (default) and `stm32f103`.
2. Made corresponding changes to `readme.md`.
3. Added `via` keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-28 03:46 UTC, drashna approved these changes

2021-11-29 07:30 UTC, fauxpark requested changes

2021-11-29 07:30 UTC, fauxpark commented on keyboards/handwired/sono1/t2pp/rules.mk
> +BOOTLOADER = halfkay
```suggestion
# MCU name
MCU = at90usb1286

# Bootloader selection
BOOTLOADER = halfkay
```

2021-11-29 07:30 UTC, fauxpark commented on keyboards/handwired/sono1/stm32f103/mcuconf.h
>  /*
These comments can probably go.

2022-01-10 09:26 UTC, merged

2022-01-10 09:26 UTC, noroadsleft commented
Thanks!

2022-01-15 07:16 UTC, drashna commented
Just a heads up, the stm32f103 version doesn't compile correctly for the via keymap, due to eeprom size.