Han60 QMK Support
qmk/qmk_firmware pull request #15332
Opened 2021-11-28 06:48 UTC by farhandsome

## Description

Adding QMK support for the upcoming keyboard Han60.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-28 07:31 UTC, drashna requested changes

2021-11-28 07:31 UTC, drashna commented on keyboards/han60/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2021-11-28 08:25 UTC, drashna approved these changes

2021-11-28 20:10 UTC, zvecr requested changes

2021-11-28 20:10 UTC, zvecr commented on keyboards/han60/han60.h
> +#define LAYOUT_tsangan_ISO( \
```suggestion
#define LAYOUT_tsangan_iso( \
```

2021-11-28 20:10 UTC, zvecr commented on keyboards/han60/han60.h
> +#define LAYOUT_tsangan_ISO_arrowkeys( \
```suggestion
#define LAYOUT_tsangan_iso_arrowkeys( \
```

2021-11-28 20:10 UTC, zvecr commented on keyboards/han60/info.json
> +        "LAYOUT_tsangan_ISO": {
```suggestion
        "LAYOUT_tsangan_iso": {
```

2021-11-28 20:10 UTC, zvecr commented on keyboards/han60/info.json
> +        "LAYOUT_tsangan_ISO_arrowkeys": {
```suggestion
        "LAYOUT_tsangan_iso_arrowkeys": {
```

2021-11-28 20:10 UTC, zvecr commented on keyboards/han60/readme.md
> +*A short description of the keyboard/project*
Image and description needs updating

2021-11-29 08:25 UTC, fauxpark requested changes

2021-11-30 05:50 UTC, fauxpark approved these changes

2021-12-01 17:30 UTC, drashna commented on keyboards/han60/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2021-12-01 17:38 UTC, merged