Fix bit loss in cie_lightness() when doing division to resolve #15331
qmk/qmk_firmware pull request #15344
Opened 2021-11-28 21:03 UTC by karlshea

## Description

Bit loss during division breaks static backlight levels.

@Duckle29 since you authored the PR that made these changes can you confirm this doesn't break what you were trying to accomplish?

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #15331

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-28 21:07 UTC, tzarc requested changes

2021-11-28 21:07 UTC, tzarc commented on quantum/backlight/backlight_avr.c
> +        uint32_t y   = (((uint32_t)v + (unsigned long)ICRx / 6) << 5) / ((unsigned long)ICRx / 6 + ICRx);  // If above 8%, add ~16% of max, and normalize with (max + ~16% max)
```suggestion
        uint32_t y   = (((uint32_t)v + (uint32_t)ICRx / 6) << 5) / ((uint32_t)ICRx / 6 + ICRx);  // If above 8%, add ~16% of max, and normalize with (max + ~16% max)
```

2021-11-28 21:07 UTC, tzarc commented on quantum/backlight/backlight_avr.c
> +    if (v <= (unsigned long)ICRx / 12)  // If the value is less than or equal to ~8% of max
```suggestion
    if (v <= (uint32_t)ICRx / 12)  // If the value is less than or equal to ~8% of max
```

2021-11-28 21:09 UTC, zvecr reviewed
Should probably  `uint32_t` like the rest of the function.

2021-11-28 21:09 UTC, zvecr commented on quantum/backlight/backlight_avr.c
> +    if (v <= (unsigned long)ICRx / 12)  // If the value is less than or equal to ~8% of max
```suggestion
    if (v <= (uint32_t)ICRx / 12)  // If the value is less than or equal to ~8% of max
```

2021-11-28 21:09 UTC, zvecr commented on quantum/backlight/backlight_avr.c
> +        uint32_t y   = (((uint32_t)v + (unsigned long)ICRx / 6) << 5) / ((unsigned long)ICRx / 6 + ICRx);  // If above 8%, add ~16% of max, and normalize with (max + ~16% max)
```suggestion
        uint32_t y   = (((uint32_t)v + (uint32_t)ICRx / 6) << 5) / ((uint32_t)ICRx / 6 + ICRx);  // If above 8%, add ~16% of max, and normalize with (max + ~16% max)
```

2021-11-28 21:16 UTC, zvecr approved these changes

2021-11-28 21:18 UTC, karlshea commented on quantum/backlight/backlight_avr.c
> +        uint32_t y   = (((uint32_t)v + (unsigned long)ICRx / 6) << 5) / ((unsigned long)ICRx / 6 + ICRx);  // If above 8%, add ~16% of max, and normalize with (max + ~16% max)
Already on it :-)

2021-11-28 21:22 UTC, drashna approved these changes

2021-11-29 10:42 UTC, tzarc commented
CI says the file needs formatting.

2021-11-29 15:07 UTC, merged