Add mini winni
qmk/qmk_firmware pull request #15341
Opened 2021-11-28 20:42 UTC by matthewdias

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2021-11-28 20:56 UTC, zvecr requested changes

2021-11-28 20:56 UTC, zvecr commented on keyboards/mini_winni/mini_winni.h
> +
```suggestion

```

2021-11-28 20:56 UTC, zvecr commented on keyboards/mini_winni/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2021-11-28 21:29 UTC, drashna requested changes

2021-11-28 21:29 UTC, drashna commented on keyboards/mini_winni/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-12-09 06:34 UTC, drashna commented on keyboards/mini_winni/rules.mk
> +BOOTMAGIC_ENABLE = yes	    # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-12-09 06:34 UTC, drashna requested changes

2021-12-09 06:34 UTC, drashna commented on keyboards/mini_winni/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-07 03:00 UTC, drashna requested changes
This needs a readme

2022-02-24 18:40 UTC, fauxpark requested changes

2022-02-24 18:40 UTC, fauxpark commented on keyboards/winkeys/mini_winni/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no	        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-02-28 12:30 UTC, fauxpark approved these changes

2022-03-08 04:22 UTC, drashna approved these changes

2022-03-08 04:23 UTC, merged