added info.json
qmk/qmk_firmware pull request #15355
Opened 2021-11-30 01:45 UTC by ll3macorn

added info.json

2021-11-30 16:48 UTC, zvecr requested changes

2021-11-30 16:48 UTC, zvecr commented on keyboards/ll3macorn/bongopad/info.json
> +	    "LAYOUT": {
```suggestion
	    "LAYOUT_default": {
```

2021-11-30 18:12 UTC, ll3macorn commented on keyboards/ll3macorn/bongopad/info.json
> +	    "LAYOUT": {
done

2021-12-30 00:34 UTC, ll3macorn commented
hello?

2022-01-07 02:58 UTC, drashna approved these changes

2022-01-10 21:55 UTC, fauxpark approved these changes

2022-01-11 01:32 UTC, merged