Add personal keymaps
qmk/qmk_firmware pull request #15351
Opened 2021-11-29 16:35 UTC by thattolleyguy

## Description
Adding personal keymaps for redox, iris and dactyl manuform

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-29 16:52 UTC, drashna requested changes

2021-11-29 16:52 UTC, drashna commented on keyboards/redox/keymaps/thattolleyguy/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-04-05 15:51 UTC, thattolleyguy commented
@drashna Is there anything else I need to do to merge this in?

2022-04-13 05:34 UTC, drashna approved these changes

2022-04-13 10:14 UTC, fauxpark approved these changes

2022-04-13 14:27 UTC, merged

2022-04-13 14:27 UTC, drashna commented
Thanks!

2022-04-13 14:35 UTC, thattolleyguy commented
Thanks everyone! Excited to be part of the community!