[Keyboard] Add pluto12
qmk/qmk_firmware pull request #15369
Opened 2021-12-01 05:26 UTC by wymcg

## Description

Adds support for the pluto12 macropad

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-01 17:15 UTC, drashna requested changes

2021-12-01 17:15 UTC, drashna commented on keyboards/psuieee/pluto12/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2021-12-01 17:15 UTC, drashna commented on keyboards/psuieee/pluto12/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2021-12-04 06:07 UTC, drashna approved these changes

2021-12-11 06:39 UTC, fauxpark requested changes

2021-12-11 06:39 UTC, fauxpark commented on keyboards/psuieee/pluto12/readme.md
> +![pluto12](https://i.imgur.com/XYtwexo.jpg)
```suggestion
![pluto12](https://i.imgur.com/XYtwexoh.jpg)
```

2021-12-11 06:39 UTC, fauxpark commented on keyboards/psuieee/pluto12/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-11 23:38 UTC, fauxpark approved these changes

2021-12-14 22:56 UTC, wymcg commented
@drashna @fauxpark is there anything else you all need from me? Thanks!

2021-12-15 02:52 UTC, merged

2021-12-15 02:52 UTC, drashna commented
Thanks!