Updated pins configuration and keymaps for Vaengr
qmk/qmk_firmware pull request #15379
Opened 2021-12-02 01:43 UTC by vicktorhu

Changed the PCB design and updated the pins configuration. Also changed the default keymap.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-02 14:34 UTC, zvecr requested changes

2021-12-02 14:34 UTC, zvecr commented on keyboards/runes/vaengr/config.h
> +// #define MATRIX_COL_PINS { D4, D6, D7, B4, B5, B6, F7, F6, F5, F4, F1, F0 }
```suggestion
```

2021-12-03 08:37 UTC, vicktorhu commented
Thank you!

2021-12-04 06:02 UTC, drashna approved these changes

2021-12-04 10:00 UTC, fauxpark approved these changes

2021-12-06 00:31 UTC, merged