Update K type
qmk/qmk_firmware pull request #15405
Opened 2021-12-05 19:35 UTC by Andrew-Fahmy

This is a small update to the K-type to get it working again. There were some small changes to fix compile errors and the addition of the macros to enable all the lighting modes. I also updated the default keymap to have RGB lighting.

One issue that came up while I was trying to get the lighting working was that it would only work right after flashing. Unplugging or turning off the lighting would causes it to not turn on again. I opened an issue about it [here](https://github.com/qmk/qmk_firmware/issues/15273). I'm still not sure if this only effects this keyboard but I would like to help to fix it and was hoping someone could give me some direction on it.

Lastly, I have also updated my own keymap but haven't included those changes here yet. Would it be okay if I added them here or should I open another pr?

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-05 20:11 UTC, drashna requested changes

2021-12-05 20:11 UTC, drashna commented on keyboards/k_type/keymaps/default/config.h
> +#pragma once
This config should probably go into the keyboard's config.h file, rather than here.

Otherwise, this file requires a license header.

2021-12-05 20:11 UTC, drashna commented on keyboards/k_type/keymaps/default/config.h
> +#    define I2C1_SDA 1 // A2 on pinout = B1
```suggestion
#    define I2C1_SCL_PIN B0 // A2 on pinout = B0
#    define I2C1_SDA_PIN B1 // A2 on pinout = B1
```

2021-12-05 20:11 UTC, drashna commented on keyboards/k_type/keymaps/default/config.h
> +#    define I2C2_SDA 11 // A2 on pinout = C11
```suggestion
#    define I2C2_SCL_PIN C10 // A2 on pinout = C10
#    define I2C2_SDA_PIN C11 // A2 on pinout = C11
```

2021-12-05 20:11 UTC, drashna commented on keyboards/k_type/keymaps/default/keymap.c
> +    palSetPad(GPIOB, 16);
Per https://docs.qmk.fm/#/internals_gpio_control

```suggestion
    setPinOutput(B16);
    writePinHigh(B16);
```

2021-12-05 21:58 UTC, Andrew-Fahmy commented
I moved the default config to the keyboards config. When I tried to implement your other suggestions about the gpio pins I ran into some trouble. If I `#include "gpio.h"` there are conflicts with the macros that it defines and the `hal_lld.c` file:
```c
Compiling: lib/chibios-contrib/os/hal/ports/KINETIS/K20x/hal_lld.c                                 In file included from ./lib/chibios/os/hal/include/hal_pal.h:174,
                 from ./lib/chibios/os/hal/include/hal.h:139,
                 from platforms/chibios/gpio.h:18,
                 from platforms/gpio.h:21,
                 from ./keyboards/k_type/config.h:111,
                 from <command-line>:
lib/chibios-contrib/os/hal/ports/KINETIS/K20x/hal_lld.c: In function 'k20x_clock_init':
./lib/chibios-contrib/os/hal/ports/KINETIS/LLD/GPIOv1/hal_pal_lld.h:194:3: error: expected identifier before '(' token
  194 |   ((ioline_t)((uint32_t)(port) | ((uint32_t)(pad)<<20)))
      |   ^
platforms/chibios/pin_defs.h:125:16: note: in expansion of macro 'PAL_LINE'
  125 | #    define C2 PAL_LINE(GPIOC, 2)
      |                ^~~~~~~~
lib/chibios-contrib/os/hal/ports/KINETIS/K20x/hal_lld.c:152:10: note: in expansion of macro 'C2'
  152 |     MCG->C2 = MCG_C2_LOCRE0 | MCG_C2_EREFS0 | MCG_C2_RANGE0(2);
      |          ^~
```

It looks like there is a struct or something that has a variable named `C2`  and the gpio macro has a conflicting name. Is there a way to avoid this?

2021-12-05 22:14 UTC, drashna commented
If that is the case, then don't worry about it

2021-12-06 21:41 UTC, Andrew-Fahmy commented
I took a second stab at it and was able to make the changes you recommended. I had to update some other files which may have been the reason I was getting those error. I also moved some things around to more proper places, as well as some fixes for the issues with the lighting I mentioned in the original post. 

If anyone else has anyone else has recommendations let me know but for now I think it is good to go :)

2021-12-06 23:41 UTC, drashna approved these changes

2021-12-07 01:39 UTC, fauxpark requested changes

2021-12-07 01:39 UTC, fauxpark commented on keyboards/k_type/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
```suggestion
```

2021-12-07 01:39 UTC, fauxpark commented on keyboards/k_type/rules.mk
>  RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-12-07 01:39 UTC, fauxpark commented on keyboards/k_type/rules.mk
```suggestion

LAYOUTS = tkl_ansi

```

2021-12-07 01:39 UTC, fauxpark commented on keyboards/k_type/rules.mk
```suggestion
```

2021-12-07 01:51 UTC, fauxpark approved these changes

2021-12-07 04:58 UTC, merged