New PCB MB-65S from MechBrewery
qmk/qmk_firmware pull request #15422
Opened 2021-12-07 07:20 UTC by AnthonyNguyen168

## Description

New PCB MB-65S from MechBrewery. It is a layout 65 soldered PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-07 14:46 UTC, zvecr requested changes
Please ensure that submissions actually compile

2021-12-07 14:46 UTC, zvecr commented on keyboards/mechbrewery/mb_65s/keymaps/default/keymap.c
> +}
```suggestion
```

2021-12-07 14:46 UTC, zvecr commented on keyboards/mechbrewery/mb_65s/keymaps/default/keymap.c
> +};
```suggestion
```

2021-12-07 14:46 UTC, zvecr commented on keyboards/mechbrewery/mb_65s/info.json
> +        "LAYOUT_65_iso": { ///////
```suggestion
        "LAYOUT_65_iso": {
```

2021-12-08 04:52 UTC, drashna requested changes

2021-12-08 04:52 UTC, drashna commented on keyboards/mechbrewery/mb_65s/mb65s.c
> +#include "mb65s.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-08 04:52 UTC, drashna commented on keyboards/mechbrewery/mb_65s/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-12-10 13:04 UTC, AnthonyNguyen168 commented
Hi all,
I fixed all your recommendation.
Please merge.
Thank you.

2021-12-11 06:17 UTC, drashna requested changes

2021-12-11 06:17 UTC, drashna commented on keyboards/mechbrewery/mb65s/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-12-11 06:17 UTC, drashna commented on keyboards/mechbrewery/mb65s/keymaps/default/config.h
> +/* Copyright 2021 MechBrewery
This file should be removed.

2021-12-11 06:17 UTC, drashna commented on keyboards/mechbrewery/mb65s/keymaps/split_bs/config.h
> +/* Copyright 2021 MechBrewery
This file should be removed.

2021-12-11 06:17 UTC, drashna commented on keyboards/mechbrewery/mb65s/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2021-12-11 18:40 UTC, drashna approved these changes

2021-12-13 08:12 UTC, AnthonyNguyen168 commented
Hi all,
Please consider to merge this pull request.
Thank you.

2021-12-14 07:29 UTC, fauxpark approved these changes

2021-12-15 02:25 UTC, drashna commented
Thanks!

2021-12-15 02:26 UTC, merged