Initial commit for Nebula65B
qmk/qmk_firmware pull request #15433
Opened 2021-12-08 14:57 UTC by yiancar

## Description
Add Nebula 65B

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-08 16:57 UTC, drashna approved these changes

2021-12-09 00:36 UTC, fauxpark requested changes

2021-12-09 00:36 UTC, fauxpark commented on keyboards/nebula68b/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2021-12-09 00:36 UTC, fauxpark commented on keyboards/nebula68b/rules.mk
> +#   comment out to disable the options.
```suggestion
#   change yes to no to disable
```

2022-01-09 00:21 UTC, noroadsleft reviewed
Your reference images show a 68-key layout with a 2u Backspace, but your `info.json` and layout macro have 69 keys and are set up for a split Backspace. Which is it?

2022-01-09 01:14 UTC, yiancar commented
it can do both, split backspace is the most complete.

2022-01-10 10:09 UTC, noroadsleft requested changes
* renames `LAYOUT_68_ansi` to `LAYOUT_68_ansi_split_bs`

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/info.json
> +        "LAYOUT_68_ansi": {
```suggestion
        "LAYOUT_68_ansi_split_bs": {
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/info.json
> +                {"x":13, "y":0},
Your keys are overlapping here.

```suggestion
                {"x":13, "y":0},
                {"x":14, "y":0},
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/keymaps/default/keymap.c
> +[0] = LAYOUT_68_ansi( /* Base */
```suggestion
[0] = LAYOUT_68_ansi_split_bs( /* Base */
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/keymaps/default/keymap.c
> +[1] = LAYOUT_68_ansi( /* FN */
```suggestion
[1] = LAYOUT_68_ansi_split_bs( /* FN */
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/keymaps/via/keymap.c
> +[0] = LAYOUT_68_ansi( /* Base */
```suggestion
[0] = LAYOUT_68_ansi_split_bs( /* Base */
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/keymaps/via/keymap.c
> +[1] = LAYOUT_68_ansi( /* FN */
```suggestion
[1] = LAYOUT_68_ansi_split_bs( /* FN */
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/keymaps/via/keymap.c
> +[2] = LAYOUT_68_ansi( /* Empty for dynamic keymaps */
```suggestion
[2] = LAYOUT_68_ansi_split_bs( /* Empty for dynamic keymaps */
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/keymaps/via/keymap.c
> +[3] = LAYOUT_68_ansi( /* Empty for dynamic keymaps */
```suggestion
[3] = LAYOUT_68_ansi_split_bs( /* Empty for dynamic keymaps */
```

2022-01-10 10:09 UTC, noroadsleft commented on keyboards/nebula68b/nebula68b.h
> +#define LAYOUT_68_ansi( \
```suggestion
#define LAYOUT_68_ansi_split_bs( \
```

2022-01-10 13:21 UTC, yiancar commented
Cheers thank you,
Sorry I didnt realize 68% split bc was in the standard layouts:D

2022-01-10 22:44 UTC, fauxpark approved these changes

2022-01-11 01:36 UTC, merged

2022-01-11 01:37 UTC, drashna commented
Thanks!