[Keyboard] Add LZ erGhost
qmk/qmk_firmware pull request #15451
Opened 2021-12-10 07:08 UTC by mechlovin

## Description
Add LZ erGhost PCB rev. a.
Thank you.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-10 13:43 UTC, zvecr requested changes

2021-12-10 13:43 UTC, zvecr commented on keyboards/lz/erghost/matrix.c
> +/*
This needs stripping of all unused code. Keeping the COL2ROW and DIRECT_PINS logic just causes maintenance issues.

2021-12-11 06:28 UTC, drashna requested changes

2021-12-11 06:28 UTC, drashna commented on keyboards/lz/erghost/info.json
> +    "height": 6.25,
```suggestion
```

2021-12-11 06:28 UTC, drashna commented on keyboards/lz/erghost/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-12-11 06:28 UTC, drashna commented on keyboards/lz/erghost/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
NKRO_ENABLE = yes           # USB Nkey Rollover
BACKLIGHT_ENABLE = yes      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2021-12-23 06:42 UTC, drashna approved these changes

2021-12-23 07:50 UTC, fauxpark requested changes

2021-12-23 07:50 UTC, fauxpark commented on keyboards/lz/erghost/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2021-12-23 07:50 UTC, fauxpark commented on keyboards/lz/erghost/readme.md
> +![erGhost](https://geekhack.org/index.php?topic=115100.0)
This needs to be a direct image link.

2021-12-25 00:19 UTC, fauxpark approved these changes

2021-12-25 01:47 UTC, merged