Add Dactyl Manuform 6x6_4 and Kinesis keyboards
qmk/qmk_firmware pull request #15475
Opened 2021-12-14 21:34 UTC by dmik

## Description

This pull request adds two new keyboards to `handwired/dactyl_manuform`: `6x6_4` and `6x6_kinesis`.  The first one is based on `6x6` but it adds 4 new keys to the bottom alpha-numeric row increasing the total number of keys from 76 to 80. The second one is based on `6x6_4` but it assumes the physical key layout like on the Kinesis Advantage keyboard (and it is the primary reason `6x6_4` was hacked out — Kinesis Advantage needs a bit more keys).

It's worth to mention that the functional row of the original Kinesis Advantage keyboard is very specific and it is not fully implemented by this keyboard. The function keys occupy the top row but there is room only for 10 F-keys (because of ESC living to the left of F1) — F11 and F12 go to the second layer. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2021-12-15 00:18 UTC, drashna requested changes

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_4/keymaps/default/config.h
> +/*
This entire file can be removed, as the defines are ... the default behavior.

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_4/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_4/6x6_4.c
> +#include "6x6_4.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_4/6x6_4.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_4/keymaps/default/keymap.c
> +#define _RAISE 2
```suggestion
enum custom_layers {
    _QWERTY,
    _LOWER,
    _RAISE,
);
```

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/6x6_kinesis.c
> +#include "6x6_kinesis.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/6x6_kinesis.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/keymaps/default/config.h
> +/*
File should be removed.

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-12-15 00:18 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/keymaps/default/keymap.c
> +#define _RAISE 2
```suggestion
enum custom_layers {
    _QWERTY,
    _LOWER,
    _RAISE,
);
```

2021-12-15 12:06 UTC, dmik commented
Thanks for the feedback, I guess I fixed it all.

BTW is there a way to test info.json other than publish it at https://config.qmk.fm? I'm worried if I guessed it all right.

2021-12-15 17:43 UTC, drashna commented
If you hit Ctrl + Shft + I on the Configurator, it will let you load an info.json.

2021-12-15 20:16 UTC, dmik commented
This doesn't appear to work in Safari under macOS. Is there any other way?

2021-12-15 20:30 UTC, drashna commented
It should, but you have to hit control, then shift, then I, in that order, and one at a time.  It's ... very picky.  And I can confirm that it works in Safari under MacOS>  Though, safari isn't officially supported, from what I recall.

2021-12-15 20:43 UTC, dmik commented
Great, it worked, thanks. Fixed one minor glitch.

Okay, do I also need to provide `keymap.json` to show the default layout in the UI or it is somehow generated from a respective `keymap.c` automatically?

Re compatibility, yeah there is a banner about using an unsupported browser when under Safari but everything appears to work very well (Safari 15.1 at least).

2021-12-15 21:37 UTC, drashna commented
Default layout for QMK Configurator is added to that repo, and is done afterwards

https://docs.qmk.fm/#/configurator_default_keymaps

2021-12-15 22:37 UTC, dmik commented
Okay, I see. So do I need to do anything else within this pull request?

2022-01-08 18:19 UTC, dmik commented
Could anyone please tell me what else needs to be done for this pull request to be merged in and appear on the configurator page? @drashna?

2022-01-09 03:50 UTC, drashna requested changes

2022-01-09 03:50 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_4/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-09 03:50 UTC, drashna commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-09 03:51 UTC, drashna commented
Also, would prefer to see bootmagic enabled, as it can be a pita to get to the bootloader  boards like these.

2022-01-11 16:31 UTC, dmik commented
@drashna Committed your suggestions.

> Also, would prefer to see bootmagic enabled, as it can be a pita to get to the bootloader boards like these.

Well, I don't have such an experience as all boards I've dealt with have physical reset pins. So unless you insist, I would leave it as is (those who need it will enable it on their own). Also considering that bootmgic is disabled for all other Dactyl Manuform variants out there.

2022-01-11 18:35 UTC, drashna approved these changes

2022-01-12 00:10 UTC, fauxpark requested changes

2022-01-12 00:10 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/6x6_kinesis/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-12 00:10 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/6x6_4/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-13 06:32 UTC, fauxpark approved these changes

2022-01-13 17:18 UTC, merged

2022-01-13 17:18 UTC, drashna commented
Thanks!

2022-01-13 21:42 UTC, DuMaM commented
@dmik  Why don't you just added new keymap and new layer to 6x6?

2022-01-13 22:44 UTC, DuMaM commented
That's not problem. My also is different one, take a look on 6x6.h and keymaps
There is a 5thumb one where there are missing 2 keys from thumb cluster and it works flawlessly.

2022-01-15 17:12 UTC, DuMaM commented
@dmik If I make PR which adds your keyboard to Dactyl Manuform 6x6 folder, would you test it for me?

2022-01-15 17:38 UTC, dmik commented
@DuMaM Ok now I see what you mean. But this example was not there when I did mine so I had no idea it would be picked up by the UI this way (I modelled mine after the 5x6 series). My 6x6_4 would definitely fit as a separate layout into 6x6 series now but I'm not sure about 6x6_kinesis because it also has a different geometry (physical key layout). What happens if `info.json` will contain both `LAYOUT_6x6` and, say, `LAYOUT_6x6_kinesis`? Will the UI select the correct one when selecting `LAYOUT_6x6_kinesis` merged into 6x6 according to your scheme?

If the answer is yes — then sure, go on with your PR, I will review and test it

P.S. I wonder why keymaps are completely ignored by the UI. How to have it recognise, say, `keymaps/default/keymap.c`? Is it possible to do automatically or one needs to create `keymap.json` with a copy of `keymap.c` data as done for e.g. `5x6_2_5/keymaps/default`? From that file it looks like it can be generated from `keymap.c` in an unattended way...

2022-01-15 18:04 UTC, DuMaM commented
> I'm not sure about 6x6_kinesis because it also has a different geometry (physical key layout). What happens if info.json will contain both LAYOUT_6x6 and, say, LAYOUT_6x6_kinesis? Will the UI select the correct one when selecting LAYOUT_6x6_kinesis merged into 6x6 according to your scheme?
I guess by UI you mean QMK Configurator. It will be loaded without issues. The only problem is qmk configurator will load default keymap instead of yours. :disappointed:. 
If you referring to [toolbox](https://github.com/qmk/qmk_toolbox/releases) the answer is yes. 

> P.S. I wonder why keymaps are completely ignored by the UI (I see N/A for all keys when I select one of my layouts). How to make it recognise, say, keymaps/default/keymap.c? Is it possible to do automatically or one needs to create keymap.json with a copy of keymap.c data as done for e.g. 5x6_2_5/keymaps/default? From that file it looks like it can be generated from keymap.c in an unattended way...
https://github.com/qmk/qmk_firmware/pull/15891 Here is fix for this N/A problems. I recently added blackpill support and it was broken by this change.

2022-01-15 18:21 UTC, DuMaM commented
@dmik It looks it could be looked up in ui. So when somebody will pick your layout, your keymap will be loaded :)

2022-01-15 18:56 UTC, dmik commented
@DuMaM it doesn't seem to work this way. When I select my layout, the default keymap is not loaded... May be I didn't do something which is necessary for that, I don't know what.

2022-01-15 19:00 UTC, DuMaM commented
https://github.com/qmk/qmk_firmware/pull/15891#pullrequestreview-853580647 
Take a look on this comment.

2022-01-15 19:02 UTC, dmik commented
@DuMaM ok I see. And btw selecting the default keymap is more than fine. By `mine` I meant my keyboards (6x6_4 and 6x6_kinesis). If `keymaps/default` will be loaded for them - it will be exactly what I'd expect to.

2022-01-15 19:09 UTC, DuMaM commented
@dmik yep, I will now try to fix this, please give me some time to do this and then we try to merge it into 6x6 :wink:

2022-01-16 10:42 UTC, dmik commented
@DuMaM sure take your time! :) I'm ready to test.