Add Mode Eighty M80v2 PCB support
qmk/qmk_firmware pull request #15486
Opened 2021-12-15 21:48 UTC by Gondolindrim

## Description

Adds support for Mode Design's Mode Eight M80v2 PCBs.

The PR also moves the v1 PCBs firmware files to a  `v1` folder, whereas the v2 firmware is in a `v2` folder. The readme's were updated with compiling and flashing instructions.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-18 02:41 UTC, drashna approved these changes

2021-12-18 04:14 UTC, fauxpark requested changes

2021-12-18 04:14 UTC, fauxpark commented on keyboards/mode/m80v2/m80v2s/rules.mk
> +MCU = STM32F072
```suggestion
MCU = STM32F072

# Bootloader selection
BOOTLOADER = stm32-dfu
```

2021-12-18 04:14 UTC, fauxpark commented on keyboards/mode/m80v2/m80v2s/rules.mk
> +# Enter lower-power sleep mode when on the ChibiOS idle thread
```suggestion

# Enter lower-power sleep mode when on the ChibiOS idle thread
```

2021-12-18 04:14 UTC, fauxpark commented on keyboards/mode/m80v2/m80v2h/rules.mk
> +MCU = STM32F072
```suggestion
MCU = STM32F072

# Bootloader selection
BOOTLOADER = stm32-dfu
```

2021-12-18 04:14 UTC, fauxpark commented on keyboards/mode/m80v2/m80v2h/rules.mk
> +# Enter lower-power sleep mode when on the ChibiOS idle thread
```suggestion

# Enter lower-power sleep mode when on the ChibiOS idle thread
```

2021-12-27 20:30 UTC, BradMello commented
@fauxpark Please review when you get a chance. Thanks

2021-12-28 04:15 UTC, fauxpark approved these changes

2021-12-29 10:57 UTC, merged