[Keyboard] Add Buzzard support
qmk/qmk_firmware pull request #15493
Opened 2021-12-16 20:02 UTC by crehmann

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-17 07:32 UTC, drashna requested changes

2021-12-17 07:32 UTC, drashna commented on keyboards/buzzard/keymaps/crehmann/features/haptic_utils.c
> +    switch (biton32(state)) {
```suggestion
    switch (get_highest_layer(state)) {
```

2021-12-17 07:32 UTC, drashna commented on keyboards/buzzard/rev1/rev1.c
> +    switch (biton32(state)) {
```suggestion
    switch (get_highest_layer(state)) {
```

2021-12-17 16:10 UTC, drashna approved these changes

2021-12-17 21:24 UTC, fauxpark requested changes

2021-12-17 21:24 UTC, fauxpark commented on keyboards/buzzard/rules.mk
> +LTO_ENABLE = yes
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
LTO_ENABLE = yes
```

2021-12-18 02:39 UTC, drashna commented on keyboards/buzzard/buzzard.h
> +#include "rev1.h"
Nitpick: 
```suggestion
#    include "rev1.h"
```

2022-01-09 01:20 UTC, noroadsleft requested changes

2022-01-09 01:20 UTC, noroadsleft commented on keyboards/buzzard/rev1/rev1.h
> +#define LAYOUT_split_3x6_3 LAYOUT
This isn't needed.

```suggestion
```

2022-01-09 19:14 UTC, crehmann commented on keyboards/buzzard/rev1/rev1.h
> +#define LAYOUT_split_3x6_3 LAYOUT
Thanks good catch! I removed it

2022-01-10 10:33 UTC, noroadsleft approved these changes

2022-01-10 10:33 UTC, merged

2022-01-10 10:33 UTC, noroadsleft commented
Thanks!