[Keyboard] Add Borderland
qmk/qmk_firmware pull request #15501
Opened 2021-12-17 06:09 UTC by kiwikey

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-17 07:24 UTC, drashna requested changes

2021-12-17 07:24 UTC, drashna commented on keyboards/kiwikey/borderland/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-12-17 07:24 UTC, drashna commented on keyboards/kiwikey/borderland/keymaps/default/keymap.c
> +#include "encoder.c"
C files shouldn't be included this way. 
```suggestion
```

2021-12-17 07:24 UTC, drashna commented on keyboards/kiwikey/borderland/keymaps/default/encoder.c
> +// Copyright 2021 KiwiKey (@KiwiKey)
This file should be removed.

2021-12-17 07:24 UTC, drashna commented on keyboards/kiwikey/borderland/keymaps/via/encoder.c
> +// Copyright 2021 KiwiKey (@KiwiKey)
This file should be removed.

2021-12-17 07:24 UTC, drashna commented on keyboards/kiwikey/borderland/keymaps/via/keymap.c
> +#include "encoder.c"
```suggestion
```

2021-12-17 07:24 UTC, drashna commented on keyboards/kiwikey/borderland/borderland.c
> +#include "borderland.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "borderland.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2021-12-17 08:04 UTC, kiwikey commented
Hi @drashna, thank you for reviewing the codes. I have updated and commited changes as your suggestion.
I also re-built firmwares in my local PC, and tested with PCB, they all works.

Please help to re-check again and merge my PR if there is no issues left.

P.s: I am not so familiar with Git, hope all gonna be fine. Please let me know if there is need of any correction.

2021-12-17 16:03 UTC, drashna approved these changes

2021-12-17 21:25 UTC, fauxpark approved these changes

2021-12-18 02:29 UTC, merged

2021-12-18 02:29 UTC, drashna commented
Thanks!

2021-12-18 02:59 UTC, kiwikey commented
Thank you guys!!! Happy weekend.