Addd victorsavu3's Keychron Q1 keymap (ISO)
qmk/qmk_firmware pull request #15517
Opened 2021-12-19 15:50 UTC by victorsavu3

## Description

Adding a new keymap for Keychron Q1 (ISO).

Very similar to the default layout. Enables reactive and framebuffer RGB, but disables most effects enabled by keychron.
Uses Caps Lock as a leader key for emojis and to enable a random mouse wiggler to prevent the system from going to sleep.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-19 20:08 UTC, drashna requested changes

2021-12-19 20:08 UTC, drashna commented on keyboards/keychron/q1/rev_0102/keymaps/victorsavu3/keymap.c
> +            unregister_code(KC_CAPS);
```suggestion
            tap_code(KC_CAPS);
```

2021-12-20 07:27 UTC, fauxpark requested changes

2021-12-20 07:27 UTC, fauxpark commented on keyboards/keychron/q1/rev_0102/keymaps/victorsavu3/rules.mk
> +VIA_ENABLE = no
```suggestion
```

2021-12-20 07:27 UTC, fauxpark commented on keyboards/keychron/q1/rev_0102/keymaps/victorsavu3/keymap.c
> +            send_unicode_string(R"(¯\_(ツ)_/¯)");
```suggestion
            send_unicode_string(R"(¯\\_(ツ)_/¯)");
```
Backslash needs to be escaped.

2021-12-27 05:23 UTC, fauxpark approved these changes

2021-12-27 10:22 UTC, tzarc approved these changes

2021-12-27 10:22 UTC, merged