doc/faq_debug: qmk cli can also be used to print debug messages
qmk/qmk_firmware pull request #15528
Opened 2021-12-21 08:16 UTC by Zlika

Add to the documentation that "qmk console" can also be used to print debug messages from the keyboard.

2021-12-21 16:30 UTC, zvecr requested changes

2021-12-21 16:30 UTC, zvecr commented on docs/faq_debug.md
> +There are different tools you can use to debug your keyboard.
```suggestion
Various tools are available to debug your keyboard.
```

2021-12-21 16:30 UTC, zvecr commented on docs/faq_debug.md
> +The [QMK CLI console command](https://beta.docs.qmk.fm/cli/cli_commands#qmk-console) can be used to display debug messages from your keyboard.
```suggestion
Prefer a terminal based solution? The [QMK CLI console command](https://beta.docs.qmk.fm/cli/cli_commands#qmk-console) can be used to display debug messages from your keyboard.
```

2021-12-21 16:30 UTC, zvecr commented on docs/faq_debug.md
>  Prefer a terminal based solution? [hid_listen](https://www.pjrc.com/teensy/hid_listen.html), provided by PJRC, can also be used to display debug messages. Prebuilt binaries for Windows,Linux,and MacO
```suggestion
Something stand-alone? [hid_listen](https://www.pjrc.com/teensy/hid_listen.html), provided by PJRC, can also be used to display debug messages. Prebuilt binaries for Windows,Linux,and MacOS are available.
```

2021-12-21 16:39 UTC, Zlika commented
Hi @zvecr , thanks for your review. I pushed a new commit to take your remarks into account.

2021-12-21 17:27 UTC, drashna approved these changes

2021-12-21 17:28 UTC, drashna requested changes

2021-12-21 17:28 UTC, drashna commented on docs/faq_debug.md
> +Prefer a terminal based solution? The [QMK CLI console command](https://beta.docs.qmk.fm/cli/cli_commands#qmk-console) can be used to display debug messages from your keyboard.
```suggestion
Prefer a terminal based solution? The [QMK CLI console command](cli_commands.md#qmk-console) can be used to display debug messages from your keyboard.
```

2021-12-22 09:47 UTC, Zlika commented
Thanks @zvecr and @drashna. I've taken into account all your remarks, squashed all the commits and rebased on origin/master.

2021-12-22 13:17 UTC, zvecr approved these changes

2021-12-22 14:26 UTC, drashna approved these changes

2021-12-22 14:27 UTC, merged