M60 simple 5x12 in lego keyboard
qmk/qmk_firmware pull request #15534
Opened 2021-12-21 17:33 UTC by alinelena

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-21 17:50 UTC, drashna commented on keyboards/mlego/m60/keymaps/default/keymap.c
> +            unregister_code(KC_VOLD);
This entire block can be replaced with simply: 
```suggestion
            tap_code(KC_VOLD, MEDIA_KEY_DELAY);
```

2021-12-23 07:45 UTC, fauxpark requested changes

2021-12-23 07:45 UTC, fauxpark commented on keyboards/mlego/m60/readme.md
> +![M60](https://i.imgur.com/Zm7LaHi.jpg)
```suggestion
![M60](https://i.imgur.com/Zm7LaHih.jpg)

```

2021-12-23 21:29 UTC, drashna requested changes

2021-12-24 22:30 UTC, drashna approved these changes

2022-01-09 17:56 UTC, noroadsleft requested changes

2022-01-09 17:56 UTC, noroadsleft commented on keyboards/mlego/m60/m60.h
> +    }
This is just a white space change, but not having the layout macro formatted somewhat defeats its purpose.

```suggestion
#define LAYOUT_ortho_5x12( \
    K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011, \
    K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111, \
    K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211, \
    K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311, \
    K400, K401, K402, K403, K404, K405, K406, K407, K408, K409, K410, K411  \
) { \
    {K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011}, \
    {K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111}, \
    {K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211}, \
    {K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311}, \
    {K400, K401, K402, K403, K404, K405, K406, K407, K408, K409, K410, K411}  \
}
```

2022-01-10 20:52 UTC, noroadsleft requested changes

2022-01-10 20:52 UTC, noroadsleft commented on keyboards/mlego/m60/m60.h
> +    }
```suggestion
#define LAYOUT_ortho_5x12( \
    K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011, \
    K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111, \
    K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211, \
    K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311, \
    K400, K401, K402, K403, K404, K405, K406, K407, K408, K409, K410, K411  \
) { \
    {K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011}, \
    {K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111}, \
    {K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211}, \
    {K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311}, \
    {K400, K401, K402, K403, K404, K405, K406, K407, K408, K409, K410, K411}  \
}
```

2022-01-10 20:52 UTC, noroadsleft commented on keyboards/mlego/m60/keymaps/default/keymap.c
> +
```suggestion

enum layer_names {
    _QW = 0,
    _LWR,
    _RSE,
    _ADJ
};

```

2022-01-10 20:52 UTC, noroadsleft commented on keyboards/mlego/m60/keymaps/via/keymap.c
> +
```suggestion

enum layer_names {
    _QW = 0,
    _LWR,
    _RSE,
    _ADJ
};

```

2022-01-10 20:52 UTC, noroadsleft commented on keyboards/mlego/m60/m60.h
> +
```suggestion
```

2022-01-11 01:47 UTC, noroadsleft approved these changes
Looks good to me.

2022-01-11 01:47 UTC, merged

2022-01-11 01:47 UTC, noroadsleft commented
Thanks!