M48 12x4 lego ortholinear keyboard
qmk/qmk_firmware pull request #15536
Opened 2021-12-21 18:27 UTC by alinelena

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-22 17:41 UTC, drashna requested changes

2021-12-22 17:41 UTC, drashna commented on keyboards/mlego/m48/info.json
> +    "height": 4,
```suggestion
```

2021-12-22 17:41 UTC, drashna commented on keyboards/mlego/m48/keymaps/via/rules.mk
> +BOOTMAGIC_ENABLE = yes
This isn't needed, as via automatically enables it. 
```suggestion
```

2021-12-23 01:04 UTC, drashna approved these changes

2021-12-25 00:33 UTC, fauxpark requested changes

2021-12-25 00:33 UTC, fauxpark commented on keyboards/mlego/m48/readme.md
> +![M48](https://i.imgur.com/QLuCAlW.jpg)
```suggestion
![M48](https://i.imgur.com/QLuCAlWh.jpg)
```

2022-01-09 17:59 UTC, noroadsleft requested changes

2022-01-09 17:59 UTC, noroadsleft commented on keyboards/mlego/m48/m48.h
> +    }
```suggestion
#define LAYOUT_ortho_4x12( \
    K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011, \
    K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111, \
    K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211, \
    K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311  \
) { \
    { K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011 }, \
    { K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111 }, \
    { K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211 }, \
    { K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311 }  \
}
```

2022-01-10 18:54 UTC, noroadsleft reviewed
I just realized your PR targets the `develop` branch, and I don't see any reason that it needs to do so. Was that a deliberate decision?

2022-01-10 20:15 UTC, noroadsleft approved these changes

2022-01-10 20:15 UTC, merged

2022-01-10 20:15 UTC, noroadsleft commented
Thanks!