Add MMKZOO65 PCB
qmk/qmk_firmware pull request #15546
Opened 2021-12-22 08:37 UTC by TW59420

## Description
MWStudio is a custom keyboard enthusiast
Upload qmk firmware of MMKZOO65 PCB

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-22 17:09 UTC, drashna requested changes

2021-12-22 17:09 UTC, drashna commented on keyboards/mmkzoo65/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2021-12-23 21:28 UTC, drashna approved these changes

2021-12-24 00:15 UTC, fauxpark requested changes

2021-12-24 00:15 UTC, fauxpark commented on keyboards/mmkzoo65/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2021-12-24 20:39 UTC, drashna approved these changes

2022-01-09 03:57 UTC, noroadsleft approved these changes

2022-01-09 03:57 UTC, merged

2022-01-09 03:57 UTC, noroadsleft commented
Thanks!

2022-01-29 06:12 UTC, peepeetee commented
在？
我想把这个键盘挪到 /mwstudio 里去，您怎么看？