Add Kay60 PCB
qmk/qmk_firmware pull request #15566
Opened 2021-12-24 08:05 UTC by mechlovin

## Description

Add Kay60 PCB, Atmega32u4, RGB underglow.
Thank you.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-24 19:20 UTC, drashna commented
This has changes to the submodules which need to be reverted, first. 

```sh
git checkout master
git submodule foreach 'git log -n1 --oneline'
# remember the first abcdef1234 on the submodules that have an issue
git checkout @@your-branch@@
# for each of the problematic repo's:
cd lib/@@name@@
git checkout abcdef1234
```

2021-12-25 00:18 UTC, fauxpark requested changes

2021-12-25 00:18 UTC, fauxpark commented on keyboards/mechlovin/kay60/rules.mk
> +NKRO_ENABLE = yes            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes            # Enable N-Key Rollover
```

2021-12-27 09:36 UTC, mechlovin commented
> This has changes to the submodules which need to be reverted, first.
> 
> ```shell
> git checkout master
> git submodule foreach 'git log -n1 --oneline'
> # remember the first abcdef1234 on the submodules that have an issue
> git checkout @@your-branch@@
> # for each of the problematic repo's:
> cd lib/@@name@@
> git checkout abcdef1234
> ```

I followed your instruction and there seem to be no changes recorded in the current repo. Please take a look at the attached screenshot and let me know if I need to do anything else. Thank you!

2021-12-27 09:37 UTC, mechlovin commented
> > This has changes to the submodules which need to be reverted, first.
> > ```shell
> > git checkout master
> > git submodule foreach 'git log -n1 --oneline'
> > # remember the first abcdef1234 on the submodules that have an issue
> > git checkout @@your-branch@@
> > # for each of the problematic repo's:
> > cd lib/@@name@@
> > git checkout abcdef1234
> > ```
> 
> I followed your instruction and there seem to be no changes recorded in the current repo. Please take a look at the attached screenshot and let me know if I need to do anything else. Thank you!

Sorry I forgot to attach the screenshot. 
![Kay60](https://user-images.githubusercontent.com/57231893/147458230-9522d739-7270-43b0-95ff-dfd7c2715b1d.png)

2021-12-27 17:55 UTC, drashna commented
If you want, I can see about fixing the branch.  Though, you'd need to use `git reset` locally, to pull the changes afterwards.

2022-01-10 06:32 UTC, noroadsleft commented
If you have QMK's `qmk_firmware` repository configured as `upstream` in Git:

```
git checkout kay60
git fetch upstream master
git rebase upstream/master
git push --force-with-lease origin HEAD:kay60
```

2022-01-10 22:43 UTC, fauxpark approved these changes

2022-01-11 01:07 UTC, drashna approved these changes

2022-01-11 01:08 UTC, merged

2022-01-11 01:08 UTC, drashna commented
Thanks!