Add Kay65 PCB
qmk/qmk_firmware pull request #15565
Opened 2021-12-24 07:06 UTC by mechlovin

## Description

Add Kay65 PCB. Top right RGB LED, Atmega32u4
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-24 19:32 UTC, drashna requested changes

2021-12-24 19:32 UTC, drashna commented on keyboards/mechlovin/kay65/rev1/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2021-12-25 00:17 UTC, fauxpark requested changes

2021-12-25 00:17 UTC, fauxpark commented on keyboards/mechlovin/olly/jf/rules.mk
> +BOOTMAGIC_ENABLE = lite      # Enable Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-12-25 00:17 UTC, fauxpark commented on keyboards/mechlovin/kay65/rev1/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2021-12-25 00:17 UTC, fauxpark commented on keyboards/mechlovin/kay65/rev1/info.json
> +    "height": 5,
```suggestion
```

2022-01-06 05:27 UTC, fauxpark requested changes

2022-01-06 05:27 UTC, fauxpark commented on keyboards/mechlovin/kay65/rev1/rev1.c
> +// Copyright %(YEAR)s %(YOUR_NAME)s (@%(USER_NAME)s)
These should be filled out.

2022-01-09 18:29 UTC, noroadsleft requested changes
Are the changes to the Olly JF intended to be in this PR?

2022-01-09 18:29 UTC, noroadsleft commented on keyboards/mechlovin/kay65/rev1/rev1.h
> +    K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A, K2B, K2C,      K2E,   \
```suggestion
    K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, K1B, K1C,      K1E,   \
    K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A, K2B, K2C, K2D, K2E,   \
```

2022-01-09 18:29 UTC, noroadsleft commented on keyboards/mechlovin/kay65/rev1/info.json
> +                {"label":"K2D (B2,D2)", "x":13.75, "y":1, "w":1.25, "h":2},
```suggestion
```

2022-01-09 18:29 UTC, noroadsleft commented on keyboards/mechlovin/kay65/rev1/info.json
> +                {"label":"K2E (B2,D3)", "x":15, "y":2},
```suggestion
                {"label":"K2D (B2,D2)", "x":13.75, "y":1, "w":1.25, "h":2},
                {"label":"K2E (B2,D3)", "x":15, "y":2},
```

2022-01-09 18:29 UTC, noroadsleft commented on keyboards/mechlovin/kay65/rev1/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output

LAYOUTS = 65_ansi_blocker 65_iso_blocker
```

2022-01-10 19:27 UTC, noroadsleft requested changes

2022-01-10 19:27 UTC, noroadsleft commented on keyboards/mechlovin/olly/jf/config.h
> +#define BOOTMAGIC_LITE_COLUMN 14
Based on this, [keyboards/mechlovin/olly/jf/readme.md#L23](https://github.com/qmk/qmk_firmware/blame/2b4eee4bf75f828360c4d874b3b6e0b4afa10101/keyboards/mechlovin/olly/jf/readme.md#L23) should read:

```
By bootloader: hold Backspace key while plugging in
```

2022-01-10 19:27 UTC, noroadsleft commented on keyboards/mechlovin/olly/jf/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 2
[keyboards/mechlovin/olly/jf/keymaps/via/keymap.c](https://github.com/qmk/qmk_firmware/blob/2b4eee4bf75f828360c4d874b3b6e0b4afa10101/keyboards/mechlovin/olly/jf/keymaps/via/keymap.c) still has six layers.

2022-01-11 03:14 UTC, drashna approved these changes

2022-03-04 06:58 UTC, noroadsleft requested changes
I maintain that due to the Bootmagic settings, [Line 23 of `keyboards/mechlovin/olly/jf/readme.md`](https://github.com/qmk/qmk_firmware/blame/fbec68f89898c264d995209bae068129517ab6df/keyboards/mechlovin/olly/jf/readme.md#L23) should read:

```
By bootloader: hold Insert key while plugging in
```

Everything else looks good though.

2022-03-07 08:00 UTC, mechlovin commented
> I maintain that due to the Bootmagic settings, [Line 23 of `keyboards/mechlovin/olly/jf/readme.md`](https://github.com/qmk/qmk_firmware/blame/fbec68f89898c264d995209bae068129517ab6df/keyboards/mechlovin/olly/jf/readme.md#L23) should read:
> 
> ```
> By bootloader: hold Insert key while plugging in
> ```
> 
> Everything else looks good though.

Our apologies for not noticing your question regarding the Olly JF from 10 Jan. The changes to the Olly JF are isolated to that PCB only. Rationale for the changes is as follows:

- Currently, holding ESC + Plug cable enters Bootloader. We understand that you'd like to change it to Insert + Plug cable, however that cannot be changed without the use of a hardware programmer, which is not ideal as the Olly JF PCBs are already being used by many users. 

- We made a mistake by having both Bootloader and Bootmagic on ESC, and while Bootloader cannot be changed easily, changing the way to enter Bootmagic can be done in QMK. So that's why we're suggesting keeping ESC + Cable = Bootloader (as current setting); and making a change in QMK so that Insert + Cable = Bootmagic. 

We hope the explanation is clear enough and that the change we proposed is ok. 

With regards to the Kay65, everything is standard so if everything looks good, please go ahead with approval without worries. Thank you very much!

2022-03-09 20:41 UTC, noroadsleft commented
@mechlovin Do I understand this correctly, then?

- `Esc` + plug in USB = jump to bootloader (cannot be changed without flashing a new bootloader using a hardware programmer)
- `Insert` + plug in USB = jump to bootloader *and* reset EEPROM via QMK's Bootmagic

2022-03-10 07:42 UTC, mechlovin commented
>

2022-03-10 07:43 UTC, mechlovin commented
> @mechlovin Do I understand this correctly, then?
> 
> * `Esc` + plug in USB = jump to bootloader (cannot be changed without flashing a new bootloader using a hardware programmer)
> * `Insert` + plug in USB = jump to bootloader _and_ reset EEPROM via QMK's Bootmagic

Yes that's correct! We hope that doesn't cause you any trouble.

2022-03-11 05:00 UTC, noroadsleft commented
> Yes that's correct! We hope that doesn't cause you any trouble.

Ah, okay. Then an additional line in the readme to specify Bootloader Reset vs. Bootmagic Reset would be good to have.

2022-03-13 21:28 UTC, noroadsleft requested changes

2022-03-13 21:28 UTC, noroadsleft commented on keyboards/mechlovin/olly/jf/readme.md
> +By Bootmagic: hold Insert key while pluging in (jump to bootloader and resset EEPROM)
Tiny typo here. :)

```suggestion
By Bootmagic: hold Insert key while pluging in (jump to bootloader and reset EEPROM)
```

2022-03-14 07:22 UTC, fauxpark requested changes

2022-03-14 07:22 UTC, fauxpark commented on keyboards/mechlovin/kay65/rev1/config.h
> +
```suggestion
```

2022-03-15 00:17 UTC, noroadsleft approved these changes

2022-03-15 00:23 UTC, fauxpark approved these changes

2022-03-15 00:23 UTC, merged

2022-03-15 00:24 UTC, noroadsleft commented
Thanks!