Clarify placement and usage of RGB matrix effect inc files
qmk/qmk_firmware pull request #15572
Opened 2021-12-25 05:42 UTC by filterpaper

## Description

Clarify the location and intended usage of `rgb_matrix_user.inc` and `rgb_matrix_kb.inc` files.

## Types of Changes

- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-27 05:22 UTC, fauxpark requested changes

2021-12-27 05:22 UTC, fauxpark commented on docs/feature_rgb_matrix.md
> +By setting `RGB_MATRIX_CUSTOM_USER = yes` in `rules.mk`, new effects can be defined directly from userspace, without having to edit any QMK core files.
```suggestion
By setting `RGB_MATRIX_CUSTOM_USER = yes` in `rules.mk`, new effects can be defined directly from your keymap or userspace, without having to edit any QMK core files.
```

2021-12-27 06:39 UTC, fauxpark requested changes

2021-12-27 06:39 UTC, fauxpark commented on docs/feature_rgb_matrix.md
> +?> Hardware maintainer who wants to limit custom effects to a specific keyboard can create a `rgb_matrix_kb.inc` file in the root of the keyboard directory, and add `RGB_MATRIX_CUSTOM_KB = yes` to th
```suggestion
?> Hardware maintainers who want to limit custom effects to a specific keyboard can create a `rgb_matrix_kb.inc` file in the root of the keyboard directory, and add `RGB_MATRIX_CUSTOM_KB = yes` to the keyboard level `rules.mk`.
```

2021-12-28 04:13 UTC, fauxpark approved these changes

2021-12-28 21:00 UTC, drashna approved these changes

2021-12-28 21:00 UTC, merged