zh-cn document translate
qmk/qmk_firmware pull request #15575
Opened 2021-12-25 14:45 UTC by epiciskandar

IDE configuration parts: Eclipse and VSCode

## Description

following after PR #14924

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* tracking issue: #15443

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-25 14:51 UTC, peepeetee requested changes

2021-12-25 14:51 UTC, peepeetee commented on docs/zh-cn/other_eclipse.md
> +*译注：由于译者没有Eclipse环境，部分菜单项可能与真实描述不同，请酌情甄别，并欢迎提cr进行修改完善*
```suggestion
*译注：由于译者没有Eclipse环境，部分菜单项可能与真实描述不同，请酌情甄别，并欢迎提pr进行修改完善*
```

2021-12-25 14:51 UTC, peepeetee commented on docs/zh-cn/other_eclipse.md
> +Eclipse为Java程序，因此需要安装Java 8或更高版本才能允许。你可以选择JRE或JDK，后者在进行Java开发时需要用到。
```suggestion
Eclipse为Java程序，因此需要安装Java 8或更高版本才能运行。你可以选择JRE或JDK，后者在进行Java开发时需要用到。
```

2021-12-25 14:51 UTC, peepeetee commented on docs/zh-cn/other_eclipse.md
> +安装很简单：遵循[Eclipse安装5布走](https://eclipse.org/downloads/eclipse-packages/?show_instructions=TRUE)，并在第三步选择 **用于C/C++开发者的Eclipse IDE（Eclipse IDE for C/C++ Developers）**。
```suggestion
安装很简单：遵循[Eclipse安装5步走](https://eclipse.org/downloads/eclipse-packages/?show_instructions=TRUE)，并在第三步选择 **用于C/C++开发者的Eclipse IDE（Eclipse IDE for C/C++ Developers）**。
```

2022-01-05 03:31 UTC, peepeetee requested changes

2022-01-05 03:31 UTC, peepeetee commented on docs/zh-cn/other_eclipse.md
> +*译注：由于译者没有Eclipse环境，部分菜单项可能与真实描述不同，请酌情甄别，并欢迎提pr进行修改完善*
```suggestion

<!---
  original document: 0.15.12:docs/other_eclipse.md 
  git diff 0.15.12 HEAD -- docs/other_eclipse.md  | cat
-->

*译注：由于译者没有Eclipse环境，部分菜单项可能与真实描述不同，请酌情甄别，并欢迎提pr进行修改完善*
```

2022-01-05 03:31 UTC, peepeetee commented on docs/zh-cn/other_vscode.md
> +
```suggestion

<!---
  original document: 0.15.12:docs/other_vscode.md 
  git diff 0.15.12 HEAD -- docs/other_vscode.md  | cat
-->

```

2022-01-26 22:15 UTC, daskygit requested changes

2022-01-26 22:15 UTC, daskygit commented on docs/zh-cn/other_eclipse.md
> +*译注：由于译者没有Eclipse环境，部分菜单项可能与真实描述不同，请酌情甄别，并欢迎提pr进行修改完善*
```suggestion

```
I wouldn't worry about including this line.

2022-01-27 20:13 UTC, daskygit approved these changes

2022-01-29 12:01 UTC, peepeetee approved these changes

2022-01-29 14:27 UTC, merged

2022-01-29 16:16 UTC, daskygit commented
Thanks.