[Keyboard] Add Rosaline
qmk/qmk_firmware pull request #15595
Opened 2021-12-27 15:29 UTC by peej

## Description

Add keyboard configuration for Rosaline PCB https://github.com/peej/rosaline-keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-28 20:59 UTC, drashna requested changes

2021-12-28 20:59 UTC, drashna commented on keyboards/peej/rosaline/info.json
> +  "height": 4,
```suggestion
```

2021-12-28 20:59 UTC, drashna commented on keyboards/peej/rosaline/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2021-12-28 20:59 UTC, drashna commented on keyboards/peej/rosaline/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2021-12-28 20:59 UTC, drashna commented on keyboards/peej/rosaline/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-01-07 00:01 UTC, drashna approved these changes

2022-01-10 21:52 UTC, fauxpark requested changes

2022-01-10 21:52 UTC, fauxpark commented on keyboards/peej/rosaline/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-15 00:54 UTC, fauxpark approved these changes

2022-01-15 07:28 UTC, merged