[Keyboard] Add xox70hot
qmk/qmk_firmware pull request #15632
Opened 2021-12-29 04:28 UTC by rhmokey

## Description
Add xox70hot

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-12-29 05:19 UTC, drashna requested changes

2021-12-29 05:19 UTC, drashna commented on keyboards/mokey/xox70hot/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2021-12-29 05:19 UTC, drashna commented on keyboards/mokey/xox70hot/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
All of this information needs to be filled out.

2022-01-06 23:53 UTC, drashna approved these changes

2022-01-10 21:51 UTC, fauxpark approved these changes

2022-01-11 01:07 UTC, merged

2022-01-11 01:07 UTC, drashna commented
Thanks!