add support for Plexus75_HE
qmk/qmk_firmware pull request #15634
Opened 2021-12-29 05:28 UTC by npspears

Hotswap edition for the Plexus75

## Description

add Plexus75_HE PCB to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-06 23:52 UTC, drashna requested changes

2022-01-06 23:52 UTC, drashna commented on keyboards/checkerboards/plexus75_he/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-07 00:01 UTC, npspears commented
Thanks Drashna. Resolved rules.mk file

2022-01-09 01:50 UTC, drashna approved these changes

2022-01-10 22:24 UTC, fauxpark requested changes

2022-01-10 22:24 UTC, fauxpark commented on keyboards/checkerboards/plexus75_he/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-01-10 23:11 UTC, npspears commented
Thanks Fauxpark. Issue resolved

2022-01-19 06:21 UTC, fauxpark approved these changes

2022-01-20 17:24 UTC, merged

2022-01-20 17:24 UTC, drashna commented
Thanks!