Add Milk Truck keyboard
qmk/qmk_firmware pull request #15651
Opened 2021-12-29 16:07 UTC by rjboone

## Description

This pull request contains the necessary files to add Q4Z to QMK main.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Initial addition of keyboard

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-06 20:32 UTC, drashna commented on keyboards/milk_truck/config.h
> +#define DEVICE_VER 0x0001
Please chaleg

2022-01-06 20:36 UTC, drashna requested changes

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/keymaps/default/keymap.c
> +#ifdef OLED_DRIVER_ENABLE  //Special thanks to Sickbabies for this great OLED widget!
```suggestion
#ifdef OLED_ENABLE  //Special thanks to Sickbabies for this great OLED widget!
```

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/keymaps/default/keymap.c
> +void oled_task_user(void) {
```suggestion
bool oled_task_user(void) {
```

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/keymaps/default/keymap.c
> +}
```suggestion

    return false;
}
```

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/keymaps/rjboone/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-06 20:36 UTC, drashna commented on keyboards/milk_truck/rules.mk
> +OLED_DRIVER_ENABLE = yes
```suggestion
OLED_ENABLE = yes
```

2022-02-24 18:58 UTC, fauxpark requested changes

2022-02-24 18:58 UTC, fauxpark commented on keyboards/milk_truck/readme.md
> +![Milk Truck](https://imgur.com/NUmiTDS.jpg)
```suggestion
![Milk Truck](https://imgur.com/NUmiTDSh.jpg)
```

2022-02-24 18:58 UTC, fauxpark commented on keyboards/milk_truck/keymaps/rjboone/readme.md
> +# rjboone's Milk Truck Layout
`rules.mk` here can be deleted.

2022-02-24 18:58 UTC, fauxpark commented on keyboards/milk_truck/keymaps/default/readme.md
> +# Default Milk Truck Layout
`rules.mk` here can be deleted.

2022-02-24 18:58 UTC, fauxpark commented on keyboards/milk_truck/info.json
> +}
```suggestion
{
    "keyboard_name": "milk_truck",
    "url": "",
    "maintainer": "rjboone",
    "layouts": {
        "LAYOUT": {
            "layout": [
                {"x": 0, "y": 0},
                {"x": 1, "y": 0},
                {"x": 2, "y": 0},

                {"x": 4, "y": 0},
                {"x": 5, "y": 0},
                {"x": 6, "y": 0},
                {"x": 7, "y": 0},
                {"x": 8, "y": 0},
                {"x": 9, "y": 0},
                {"x": 10, "y": 0},
                {"x": 11, "y": 0},
                {"x": 12, "y": 0},
                {"x": 13, "y": 0},
                {"x": 14, "y": 0},
                {"x": 15, "y": 0, "w": 1.75},

                {"x": 0, "y": 1},
                {"x": 1, "y": 1},
                {"x": 2, "y": 1},

                {"x": 4, "y": 1, "w": 1.25},
                {"x": 5.25, "y": 1},
                {"x": 6.25, "y": 1},
                {"x": 7.25, "y": 1},
                {"x": 8.25, "y": 1},
                {"x": 9.25, "y": 1},
                {"x": 10.25, "y": 1},
                {"x": 11.25, "y": 1},
                {"x": 12.25, "y": 1},
                {"x": 13.25, "y": 1},
                {"x": 14.25, "y": 1},
                {"x": 15.25, "y": 1, "w": 1.5},

                {"x": 0, "y": 2},
                {"x": 1, "y": 2},
                {"x": 2, "y": 2},
                {"x": 3, "y": 2},

                {"x": 4, "y": 2, "w": 1.75},
                {"x": 5.75, "y": 2},
                {"x": 6.75, "y": 2},
                {"x": 7.75, "y": 2},
                {"x": 8.75, "y": 2},
                {"x": 9.75, "y": 2},
                {"x": 10.75, "y": 2},
                {"x": 11.75, "y": 2},
                {"x": 12.75, "y": 2},
                {"x": 13.75, "y": 2},
                {"x": 14.75, "y": 2},
                {"x": 15.75, "y": 2},

                {"x": 0, "y": 3},
                {"x": 1, "y": 3},
                {"x": 2, "y": 3},
                {"x": 3, "y": 3},

                {"x": 4, "y": 3},
                {"x": 5.5, "y": 3, "w": 1.5},
                {"x": 7, "y": 3},
                {"x": 8, "y": 3, "w": 2.25},
                {"x": 10.25, "y": 3, "w": 2},
                {"x": 12.25, "y": 3},
                {"x": 13.25, "y": 3, "w": 1.25},
                {"x": 14.5, "y": 3},
                {"x": 15.5, "y": 3, "w": 1.25}
            ]
        }
    }
}
```

2022-02-26 20:37 UTC, drashna approved these changes

2022-07-15 19:25 UTC, noroadsleft requested changes
GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/15651/files).

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/readme.md
> +* **Keycode in layout**: Press the key mapped to `RESET`
```suggestion
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (the top left key) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB
* **Keycode in layout**: Press the key mapped to `RESET`

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/milk_truck.h
> +#define LAYOUT( \
As the PCB supports multiple layouts, this should be named:

```suggestion
#define LAYOUT_all( \
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/rjboone/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/rjboone/keymap.c
> +    [_NUM_SYM] = LAYOUT(
```suggestion
    [_NUM_SYM] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/rjboone/keymap.c
> +    [_NAV] = LAYOUT(
```suggestion
    [_NAV] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/rjboone/keymap.c
> +    [_FKEY_RGB] = LAYOUT(
```suggestion
    [_FKEY_RGB] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/default/keymap.c
> +    [_NUM_SYM] = LAYOUT(
```suggestion
    [_NUM_SYM] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/default/keymap.c
> +    [_NAV] = LAYOUT(
```suggestion
    [_NAV] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/default/keymap.c
> +    [_FKEY_RGB] = LAYOUT(
```suggestion
    [_FKEY_RGB] = LAYOUT_all(
```

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/keymaps/default/config.h
> +/* Copyright 2022 rjboone
This file can be deleted.

2022-07-15 19:25 UTC, noroadsleft commented on keyboards/milk_truck/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2022-09-30 02:18 UTC, closed without merging