[Docs] zh-cn documentation translate
qmk/qmk_firmware pull request #15666
Opened 2021-12-30 12:18 UTC by epiciskandar

* hand wire

## Description

following after PR #14924

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* tracking issue: #15443 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-05 03:27 UTC, peepeetee requested changes

2022-01-05 03:27 UTC, peepeetee commented on docs/zh-cn/hand_wire.md
> +
```suggestion

<!---
  original document: 0.15.12:docs/isp_flashing_guide.md 
  git diff 0.15.12 HEAD -- docs/isp_flashing_guide.md  | cat
-->

```

2022-01-26 22:42 UTC, daskygit requested changes

2022-01-26 22:42 UTC, daskygit commented on docs/zh-cn/hand_wire.md
> +  git diff 0.15.12 HEAD -- docs/hand_wire.md  | cat
```suggestion
  original document: 0.15.17:docs/hand_wire.md 
  git diff 0.15.17 HEAD -- docs/hand_wire.md  | cat
```

2022-01-27 20:12 UTC, daskygit approved these changes

2022-01-29 11:56 UTC, peepeetee approved these changes

2022-01-29 16:06 UTC, merged

2022-01-29 16:16 UTC, daskygit commented
Thanks.