Add new The GMMK PRO keymap
qmk/qmk_firmware pull request #15664
Opened 2021-12-30 09:43 UTC by batin

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-06 20:20 UTC, drashna requested changes

2022-01-06 20:20 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/batin/keymap.c
> +    return true;
```suggestion
    return false;
```

2022-01-06 20:20 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/batin/rules.mk
> +RGB_MATRIX_DRIVER = AW20216
This file an be deleted.  Specifically, you only need what is changed from the keyboard's rules.mk. 
```suggestion
```

2022-01-09 01:40 UTC, drashna approved these changes

2022-01-10 22:22 UTC, fauxpark approved these changes

2022-01-11 00:50 UTC, merged