Do not enable PERMISSIVE_HOLD when TAPPING_TERM exceeds 500ms
qmk/qmk_firmware pull request #15674
Opened 2021-12-30 22:58 UTC by precondition

## Description
Do not enable PERMISSIVE_HOLD-like behaviour when TAPPING_TERM ≥ 500ms. 

This is a poorly documented obscure "feature" that's entirely unnecessary and does more harm than good. When people are testing dual-role keys like `MT()`, they need to play around with the different tap-hold option and tweak their tapping term in order to limit misfires. A lot of times, people enable `IGNORE_MOD_TAP_INTERRUPT` because this is the option that is the most restrictive when it comes to selecting the hold action (desirable for a person using home row mods for example) but because they're not used to it, they get a lot of misfires. In which case, they're advised to cramp up the tapping term. 

However, some users crank it way above 500ms "just to be safe" and make it very hard to accidentally trigger a hold. That's when QMK "helpfully" enables permissive hold (despite the user not having enabled the setting in `config.h`) under their nose. Now, when testing, the user encounters *even more* misfires than before because permissive hold activates an additional way to trigger holds. This only servers to frustrate the users and push them away from exploiting the full capacities of the advanced tap-hold mechanics that QMK offers.

Finally, this PR is not a loss of functionality because one only needs to add `#define PERMISSIVE_HOLD` to their `config.h` to get the behaviour if they so desire. Furthermore, you can expect this PR to free up about 55 bytes in keymaps that don't enable `PERMISSIVE_HOLD`. (Everything counts on AVR)

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-08 04:22 UTC, drashna approved these changes
code change looks good.  But I'm not sure that this is for the best.

2022-06-24 09:35 UTC, KarlK90 commented on quantum/action_tapping.c
> -                            GET_TAPPING_TERM(tapping_keycode, &tapping_key) >= 500
Same here.

2022-06-24 09:37 UTC, KarlK90 commented
> Can I also remove these (would-be-)outdated comments?

Yes, please remove them.

2022-06-24 09:42 UTC, KarlK90 commented
One more request:

```
❯ rg "TAPPING_TERM [5-9]\d\d"
users/wanleg/config.h
14:#define TAPPING_TERM 700

keyboards/1k/keymaps/tap_dance/config.h
6:#define TAPPING_TERM 500

keyboards/idobao/id67/keymaps/thewerther/config.h
20:#define TAPPING_TERM 500

keyboards/handwired/onekey/config.h
44:#define TAPPING_TERM 500

keyboards/handwired/ergocheap/config.h
49:#define TAPPING_TERM 500

keyboards/handwired/uthol/rev3/config.h
59:#define TAPPING_TERM 500

keyboards/xiudi/xd002/keymaps/tap_dance/config.h
3:#define TAPPING_TERM 500

keyboards/1upkeyboards/sweet16/keymaps/ridingintraffic/config.h
5:#define TAPPING_TERM 500

keyboards/keebio/quefrency/keymaps/bjohnson/config.h
29:#define TAPPING_TERM 500

keyboards/thevankeyboards/minivan/keymaps/halvves/config.h
3:#define TAPPING_TERM 505

keyboards/thevankeyboards/minivan/keymaps/belak/config.h
6:#define TAPPING_TERM 500

keyboards/flehrad/bigswitch/keymaps/333fred/config.h
26:#define TAPPING_TERM 500

keyboards/zfrontier/big_switch/config.h
53:#define TAPPING_TERM 500

layouts/community/66_ansi/xyverz/config.h
3:#define TAPPING_TERM 600 // ms
```

These configs should get `#define PERMISSIVE_HOLD` as they expected (?) or at least use this behavior.

2022-06-24 09:46 UTC, filterpaper commented
Do we typically have to manage user config/keymaps for breaking changes?

2022-06-24 10:01 UTC, KarlK90 commented
> Do we typically have to manage user config/keymaps for breaking changes?

I would say that QMK should not break user space if it is possible. So if there is a trivial backwards compatible conversion it should be done in the PR.

2022-06-24 10:11 UTC, precondition commented
> Yes, please remove them. This doesn't need confirmation from the owners as it just rectifies the situation.
Solved in https://github.com/qmk/qmk_firmware/pull/15674/commits/9167f41ca340a33edf2c13d694893dcb9810dd52

> These configs should get #define PERMISSIVE_HOLD as they expected (?) or at least use this behavior.

Solved in https://github.com/qmk/qmk_firmware/pull/15674/commits/f3e9fa777bee464f725904cb71b9c2b8aeac9174

2022-06-24 10:17 UTC, KarlK90 commented on quantum/action_tapping.c
> -#    if defined(TAPPING_TERM_PER_KEY) || (TAPPING_TERM >= 500) || defined(PERMISSIVE_HOLD) || defined(PERMISSIVE_HOLD_PER_KEY) || (defined(AUTO_SHIFT_ENABLE) && defined(RETRO_SHIFT))
Ah yes, you are totally right.

2022-06-24 10:18 UTC, KarlK90 approved these changes
Thanks for quickly implementing the changes.

2022-06-24 10:33 UTC, KarlK90 requested changes

2022-06-24 10:33 UTC, KarlK90 commented on quantum/action_tapping.c
>  #        endif
That was a bit rushed, the unit-tests are failing now with:

```
Making test caps_word_autoshift                                                                                [ERRORS]
quantum/action_tapping.c: In function ‘process_tapping’:
quantum/action_tapping.c:176:25: error: expected expression before ‘)’ token
  176 |                         ) && IS_RELEASED(event) && waiting_buffer_typed(event)
      |                         ^
 | 
 | 
 | 
```

I guess we need a false at this position for all other cases?

```suggestion
                            true
#        else
                            false                     
#        endif
```

2022-06-24 10:36 UTC, KarlK90 commented on quantum/action_tapping.c
>  #        endif
Thanks!

2022-06-24 10:39 UTC, KarlK90 approved these changes
All test are green now. This is good to go.

2022-06-24 10:40 UTC, merged

2022-06-24 10:46 UTC, precondition commented
It also passes all the new tap hold configuration unit tests I had added in https://github.com/qmk/qmk_firmware/pull/15741 so that's extra re-insurance