Sol 3 Keyboard from RGBKB
qmk/qmk_firmware pull request #15687
Opened 2021-12-31 14:49 UTC by XScorpion2

Sol 3 Keyboard from RGBKB

## Description
This adds QMK Keyboard support for the RGBKB Sol 3. 
The VIA keymap version is coming factory flashed on the Sol 3.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-02 08:02 UTC, drashna requested changes

2022-01-02 08:02 UTC, drashna commented on keyboards/rgbkb/sol3/keymaps/kageurufu/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED
```

2022-01-02 08:02 UTC, drashna commented on keyboards/rgbkb/sol3/keymaps/kageurufu/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-02 08:02 UTC, drashna commented on keyboards/rgbkb/sol3/rules.mk
> +AUDIO_DRIVER = dac_basic
I'd recommend dac_additive instead.  dac basic seems to have some issues, especially for stuff like music mode and audio clicky. 
```suggestion
AUDIO_DRIVER = dac_additive
```

2022-01-02 08:02 UTC, drashna commented on keyboards/rgbkb/sol3/keymaps/default/keymap.c
> +bool oled_task_user(void) {
Please move/add default oled behavior using `oled_render_kb` to the keyboard code.

2022-01-03 15:56 UTC, Legonut commented
Tested and working on my Sol 3, approved by RGBKB (me)

2022-01-03 17:18 UTC, drashna approved these changes

2022-01-06 05:08 UTC, fauxpark requested changes

2022-01-06 05:08 UTC, fauxpark commented on keyboards/rgbkb/sol3/rules.mk
> +RGBLIGHT_ENABLE = no        # Enable WS2812 RGB underlight.
```suggestion
RGBLIGHT_ENABLE = no
```

2022-01-06 05:08 UTC, fauxpark commented on keyboards/rgbkb/sol3/keymaps/kageurufu/keymap.c
> +      _________________ADJUST_L5_________________, _______, _______, _______, _______, _________________ADJUST_R5_________________  \
```suggestion
  [_QWERTY] = EXPAND_LAYOUT(
      KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    RGB_MOD,                   KC_EQL,  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC,
      KC_TAB,  _________________QWERTY_L1_________________, KC_LBRC,                   KC_RBRC, _________________QWERTY_R1_________________, KC_BSLS,
      FN_ESC,  _________________QWERTY_L2_________________, RGB_SAI,                   RGB_VAI, _________________QWERTY_R2_________________, KC_QUOT,
      KC_LSPO, _________________QWERTY_L3_________________, RGB_SAD,                   RGB_VAD, _________________QWERTY_R3_________________, KC_RSPC,
      KC_LCTL, KC_LGUI, KC_LGUI, KC_LALT, FN,      KC_SPC,  KC_MUTE, KC_BSPC, KC_ENT,  FN,      KC_SPC,  KC_MINS, KC_EQL,  KC_DOWN, KC_PGUP, KC_PGDN
  ),

  [_FN] = EXPAND_LAYOUT(
      ________________FUNCTION_L1________________, _______,                   KC_PSCR, ________________FUNCTION_R1________________,
      ________________FUNCTION_L2________________, _______,                   _______, ________________FUNCTION_R2________________,
      ________________FUNCTION_L3________________, _______,                   _______, ________________FUNCTION_R3________________,
      ________________FUNCTION_L4________________, _______,                   _______, ________________FUNCTION_R4________________,
      ________________FUNCTION_L5________________, ADJ,     KC_DEL,  _______, ADJ,     ________________FUNCTION_R5________________
      ),

  [_ADJ] = EXPAND_LAYOUT(
      _________________ADJUST_L1_________________, _______,                   _______, _________________ADJUST_R1_________________,
      _________________ADJUST_L2_________________, _______,                   _______, _________________ADJUST_R2_________________,
      _________________ADJUST_L3_________________, _______,                   _______, _________________ADJUST_R3_________________,
      _________________ADJUST_L4_________________, _______,                   _______, _________________ADJUST_R4_________________,
      _________________ADJUST_L5_________________, _______, _______, _______, _______, _________________ADJUST_R5_________________
```

2022-01-06 14:30 UTC, XScorpion2 commented
Code review changes applied @fauxpark

2022-01-16 16:51 UTC, fauxpark requested changes

2022-01-16 16:51 UTC, fauxpark commented on keyboards/rgbkb/sol3/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-01-21 17:11 UTC, XScorpion2 commented
Bump, can this land before the breaking change merge?

2022-01-22 03:30 UTC, fauxpark approved these changes
`.noci` file can be deleted since Travis is no longer running.

2022-01-22 03:51 UTC, merged

2022-01-22 03:51 UTC, drashna commented
Thanks!

2022-01-22 15:12 UTC, XScorpion2 commented
no thank you @drashna and @fauxpark!