[Docs]zh-cn document translate: ISP flashing
qmk/qmk_firmware pull request #15716
Opened 2022-01-03 03:56 UTC by epiciskandar

* isp flashing

## Description

following after PR #14924

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* tracking issue: #15443

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-03 08:22 UTC, peepeetee requested changes

2022-01-03 08:22 UTC, peepeetee commented on docs/zh-cn/isp_flashing_guide.md
> +接线比较简单，大部分情况下接到相似的上面就行。可以查阅MCU的数据手册以确定准确的 `RESET`、`SCLK`、`MOSI` 以及 `MISO` 引脚。
```suggestion
接线比较简单，大部分情况下接到对应的上面就行。可以查阅MCU的数据手册以确定准确的 `RESET`、`SCLK`、`MOSI` 以及 `MISO` 引脚。
```

2022-01-03 08:22 UTC, peepeetee commented on docs/zh-cn/isp_flashing_guide.md
> +?> 标 * 的文件同时附带了 Arduin sketch，默认启动且也会呈现出一个串口，但那个*可不是* bootloader 设备。
```suggestion
?> 标 * 的文件同时附带了 Arduino sketch，默认启动且也会呈现出一个串口，但那个*可不是* bootloader 设备。
```

2022-01-05 03:26 UTC, peepeetee requested changes

2022-01-05 03:26 UTC, peepeetee commented on docs/zh-cn/isp_flashing_guide.md
> +
```suggestion

<!---
  original document: 0.15.12:docs/isp_flashing_guide.md 
  git diff 0.15.12 HEAD -- docs/isp_flashing_guide.md  | cat
-->

```

2022-01-29 15:06 UTC, daskygit commented
Could you include this change please? https://github.com/qmk/qmk_firmware/pull/15898 it'd likely be merged before this anyway.

2022-02-05 07:16 UTC, epiciskandar commented
> Could you include this change please? #15898
It has been includede now.

2022-05-20 11:07 UTC, epiciskandar commented
keep this

2022-08-04 02:17 UTC, closed without merging