[Docs] Recommend the use of RGB light functions for code
qmk/qmk_firmware pull request #15745
Opened 2022-01-05 06:09 UTC by filterpaper

## Description

Questions on using RGB_* keycodes with code comes up often on Discord. This change adds a note to recommend using direct RGB light functions if users need to control RGB feature with code. 

## Types of Changes

- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-06 18:40 UTC, drashna approved these changes

2022-01-06 20:44 UTC, EricGebhart approved these changes

2022-01-06 21:04 UTC, tzarc requested changes

2022-01-06 21:04 UTC, tzarc commented on docs/feature_rgblight.md
> +?> `RGB_*` keycodes cannot be used with functions like `tap_code16(RGB_HUI)` inside `encoder_update_user()` or `process_record_user()`. RGB [functions](#functions) should be implemented in their plac
```suggestion
?> `RGB_*` keycodes cannot be used with functions like `tap_code16(RGB_HUI)` as they're not USB HID keycodes. If you wish to replicate similar behaviour in custom code within your firmware (e.g. inside `encoder_update_user()` or `process_record_user()`), the equivalent [RGB functions](#functions-idfunctions) should be used instead.
```

2022-01-10 16:22 UTC, tzarc approved these changes

2022-01-10 16:23 UTC, merged