HHKB YDKB Yang BT Controller
qmk/qmk_firmware pull request #15759
Opened 2022-01-06 13:59 UTC by kanru

## Description

Adds support for the Yang controller for HHKB Pro 2.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* The previous PR #11011 was closed and I can't reopen it so I'm opening a new one.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-09 20:07 UTC, drashna requested changes

2022-01-09 20:07 UTC, drashna commented on keyboards/hhkb/yang/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-04-19 01:34 UTC, drashna requested changes

2022-04-19 01:34 UTC, drashna commented on keyboards/hhkb/yang/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-19 01:34 UTC, drashna commented on keyboards/hhkb/yang/keymaps/kanru/keymap.c
> +#define MOUSE 2
```suggestion
enum custom_layers {
    BASE,
    HHKB,
    MOUSE,
};
```

2022-04-19 01:34 UTC, drashna commented on keyboards/hhkb/yang/keymaps/default/keymap.c
> +#define HHKB 1
```suggestion
enum custom_layers {
    BASE,
    HHKB,
};
```

2022-04-19 01:34 UTC, drashna commented on keyboards/hhkb/yang/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-04-19 01:34 UTC, drashna commented on keyboards/hhkb/yang/rules.mk
> +# BLUETOOTH = AdafruitBLE_UART
This is no longer the syntax used.  You need to set the driver, *and* enable it. 
For here, just setting the driver is fine: 
```suggestion
BLUETOOTH_DRIVER = BluefruitLE
```

2022-04-23 21:01 UTC, drashna requested changes

2022-05-11 09:24 UTC, drashna approved these changes

2022-07-02 11:00 UTC, tzarc approved these changes

2022-07-02 11:01 UTC, merged