Add Aves60
qmk/qmk_firmware pull request #15770
Opened 2022-01-07 09:18 UTC by evyd13

## Description

Adds the Aves 60 keyboard to QMK.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-08 05:22 UTC, drashna requested changes

2022-01-08 05:22 UTC, drashna commented on keyboards/aves60/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-01-08 05:22 UTC, drashna commented on keyboards/aves60/keymaps/default/keymap.c
> +  _______, _______, _______,          _______,          _______,          _______,          _______, _______, _______, _______)
```suggestion
```

2022-01-08 05:22 UTC, drashna commented on keyboards/aves60/keymaps/default/keymap.c
> +    _FN3,
```suggestion
```

2022-01-08 05:22 UTC, drashna commented on keyboards/aves60/readme.md
> +![Aves60](https://i.imgur.com/U5UpFAV.jpg)
```suggestion
![Aves60](https://i.imgur.com/U5UpFAVl.jpg)
```

2022-01-09 01:11 UTC, drashna approved these changes

2022-01-10 22:21 UTC, fauxpark approved these changes

2022-01-10 23:06 UTC, merged