Add mikeneko65 keyboard
qmk/qmk_firmware pull request #15792
Opened 2022-01-08 15:15 UTC by takishim

## Description

Add mikeneko65 keyboard to qmk.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-09 00:57 UTC, drashna requested changes

2022-01-09 00:57 UTC, drashna commented on keyboards/mikeneko65/rev3/config.h
> +#define VENDOR_ID    0x1028
This Vendor ID is in use, and needs to be changed. 

https://www.the-sz.com/products/usbid/index.php?v=0x1028&p=&n=

Anything above 0x4000 should be okay.

2022-01-09 00:57 UTC, drashna commented on keyboards/mikeneko65/rev3/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-09 00:57 UTC, drashna commented on keyboards/mikeneko65/rev4/config.h
> +#define VENDOR_ID    0x1028
As above.

2022-01-09 00:57 UTC, drashna commented on keyboards/mikeneko65/rev4/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-09 06:19 UTC, kinmojr commented
Thank you for reviewing.
I fixed Vendor ID and added an explanation of how to enter the bootloader.
Could you please check it ?

2022-01-09 07:09 UTC, drashna approved these changes

2022-01-10 22:36 UTC, fauxpark approved these changes

2022-01-10 23:02 UTC, merged