Add Hex4B rev.2 PCB
qmk/qmk_firmware pull request #15811
Opened 2022-01-10 08:08 UTC by mechlovin

## Description

Add Hex 4B rev.2 PCB, APM32F103.
Thank you.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-11 02:19 UTC, drashna requested changes

2022-01-11 02:19 UTC, drashna commented on keyboards/mechlovin/hex4b/rev1/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-11 03:08 UTC, drashna requested changes

2022-01-11 03:08 UTC, drashna commented on keyboards/mechlovin/hex4b/rev1/readme.md
> +*/
whoops, sorry, my fault. 
```suggestion
```

2022-01-11 03:08 UTC, drashna commented on keyboards/mechlovin/hex4b/rev1/readme.md
> +Reset Key: To put the Hex4B into bootloader, hold esc key while plugging in (bootloader), hold backspace while plugging in (bootmagic) and plug cable.
This should be easier to see, ideally.

2022-01-11 03:08 UTC, drashna commented on keyboards/mechlovin/hex4b/rev2/readme.md
> +*/
```suggestion
```

2022-01-11 10:02 UTC, fauxpark requested changes

2022-01-11 10:02 UTC, fauxpark commented on keyboards/mechlovin/hex4b/rev2/rules.mk
> +
```suggestion
```

2022-01-11 10:02 UTC, fauxpark commented on keyboards/mechlovin/hex4b/readme.md
> +
```suggestion
```

2022-01-11 10:02 UTC, fauxpark commented on keyboards/mechlovin/hex4b/rev1/readme.md
> +
```suggestion
```

2022-01-11 10:02 UTC, fauxpark commented on keyboards/mechlovin/hex4b/rev2/readme.md
> +
```suggestion
```

2022-01-12 00:07 UTC, fauxpark approved these changes

2022-01-12 22:09 UTC, drashna approved these changes

2022-01-12 22:09 UTC, merged

2022-01-12 22:09 UTC, drashna commented
Thanks!