Added support for Devil68 Pro keyboard
qmk/qmk_firmware pull request #15820
Opened 2022-01-10 14:25 UTC by HorrorTroll

## Description

Added support for Devil68 Pro keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-11 02:37 UTC, drashna requested changes
Should remove any includes in the keymap that are not explicitly required.

2022-01-11 02:37 UTC, drashna commented on keyboards/devil68_pro/keymaps/default/keymap.c
> +#include "eeprom.h"
```suggestion
```

2022-01-12 05:55 UTC, HorrorTroll commented on keyboards/devil68_pro/keymaps/default/keymap.c
> +#include "eeprom.h"
Done, thanks

2022-01-12 12:12 UTC, HorrorTroll commented
I'm just update a bit of folder structure, so it should better than before

2022-01-12 22:47 UTC, drashna approved these changes

2022-01-15 07:26 UTC, merged