[keyboard] Adding Atlas_65
qmk/qmk_firmware pull request #15839
Opened 2022-01-11 13:26 UTC by ryanstevensmith

## Description

Creation of the Atlas-65 board designed by Joshua Nguyen, with the help of Ryan Smith. It is based off the Alice design, and similar to the Arisutea board. It has an extra B Key on the fourth row, and a full sized backspace.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-11 18:46 UTC, drashna commented on keyboards/Atlas_65/rules.mk
> +
These are not needed. 
```suggestion
```

These are set by default in `builddefs/mcu_seleection.mk`

2022-01-12 22:07 UTC, drashna approved these changes

2022-01-13 06:35 UTC, fauxpark requested changes
Keyboard folder name needs to be lowercase.

2022-01-13 23:53 UTC, fauxpark approved these changes

2022-01-14 04:42 UTC, merged

2022-01-14 04:42 UTC, drashna commented
Thanks!