add AddOn macropad
qmk/qmk_firmware pull request #15841
Opened 2022-01-11 16:24 UTC by oceeean

## Description

add AddOn macropad to QMK and VIA support
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-11 18:37 UTC, drashna commented on keyboards/ocean/addon/readme.md
> +![AddOn](https://i.imgur.com/hd2ETLP.jpeg)
```suggestion
![AddOn](https://i.imgur.com/hd2ETLPl.jpeg)
```

2022-01-11 18:37 UTC, drashna approved these changes

2022-01-12 00:11 UTC, fauxpark requested changes

2022-01-12 00:11 UTC, fauxpark commented on keyboards/ocean/addon/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-12 00:11 UTC, fauxpark commented on keyboards/ocean/addon/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-01-12 00:11 UTC, fauxpark commented on keyboards/ocean/addon/rules.mk
> +BOOTMAGIC_ENABLE = yes       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes       # Enable Bootmagic Lite
```

2022-01-12 00:11 UTC, fauxpark commented on keyboards/ocean/addon/info.json
> +    "height": 5,
```suggestion
```

2022-01-12 04:31 UTC, fauxpark approved these changes

2022-01-12 22:15 UTC, drashna approved these changes
Thanks!

2022-01-12 22:15 UTC, merged