Keyboard rura66
qmk/qmk_firmware pull request #15853
Opened 2022-01-12 08:39 UTC by ShinoharaTa

Please open this pull request again as # 12345 has not been fixed.
The fix for # 12345 has been merged into this pull request for me.
Please do a code review again.

2022-01-12 22:29 UTC, drashna requested changes

2022-01-12 22:29 UTC, drashna commented on keyboards/rura66/readme.md
> +Make for this keyboard default keymap (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-01-12 22:29 UTC, drashna commented on keyboards/rura66/rev1/config.h
> +  #define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended
```suggestion
  #define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
```

2022-01-12 22:29 UTC, drashna commented on keyboards/rura66/rev1/config.h
> +#endif
No animation modes are enabled here, so no modes except solid color, unless they are explicitly enabled. 

```c
// RGB Matrix Animation modes. Explicitly enabled
// For full list of effects, see:
// https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
#    define ENABLE_RGB_MATRIX_ALPHAS_MODS
#    define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#    define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#    define ENABLE_RGB_MATRIX_BREATHING
#    define ENABLE_RGB_MATRIX_BAND_SAT
#    define ENABLE_RGB_MATRIX_BAND_VAL
#    define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#    define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#    define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#    define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#    define ENABLE_RGB_MATRIX_CYCLE_ALL
#    define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#    define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#    define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#    define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#    define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#    define ENABLE_RGB_MATRIX_DUAL_BEACON
#    define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#    define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#    define ENABLE_RGB_MATRIX_RAINDROPS
#    define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#    define ENABLE_RGB_MATRIX_HUE_BREATHING
#    define ENABLE_RGB_MATRIX_HUE_PENDULUM
#    define ENABLE_RGB_MATRIX_HUE_WAVE
#    define ENABLE_RGB_MATRIX_PIXEL_RAIN
#    define ENABLE_RGB_MATRIX_PIXEL_FLOW
#    define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
// enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
#    define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#    define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#    define ENABLE_RGB_MATRIX_SPLASH
#    define ENABLE_RGB_MATRIX_MULTISPLASH
#    define ENABLE_RGB_MATRIX_SOLID_SPLASH
#    define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
```

2022-01-12 22:29 UTC, drashna commented on keyboards/rura66/rev1/oled_display.c
> +          snprintf(buf, sizeof(buf), " LED %2d: %d,%d,%d ",
Just a heads up, snprintf can use ~1.5k of firmware space.  

https://docs.qmk.fm/#/squeezing_avr?id=oled-tweaks

2022-01-12 22:29 UTC, drashna commented on keyboards/rura66/rules.mk
> +DIP_SWITCH_ENABLE = no
```suggestion
NKRO_ENABLE = no            # USB Nkey Rollover
BACKLIGHT_ENABLE = yes       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
```

2022-01-12 22:29 UTC, drashna commented on keyboards/rura66/rura66.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-16 19:42 UTC, tzarc commented
Please fix your merge such that it's only your changes.

2022-01-17 01:25 UTC, ShinoharaTa commented
I'm sorry.
There are many changes.
Delete this branch once, create a new branch from develop, and submit your pull request.
Please close this pull request.

2022-01-17 19:00 UTC, drashna commented
rebasing it will most likely fix most of these issues.

2022-03-10 05:03 UTC, noroadsleft commented
If rebasing is too intimidating or confusing, you can use `git checkout` to grab the files from another branch/commit, at the cost of losing the original Git history.

```
# Change to your local `Keyboard_RURA66` branch
git checkout Keyboard_RURA66

# Updates your local repo's `master` branch to be identical to that of QMK's `master` branch
git fetch upstream master:master

# Rewrites your local repo's `Keyboard_RURA66` branch to be identical to that of your local `master` branch
git reset --hard master                                                   

# Retrieves the contents of the `keyboards/rura66/` directory as of commit `0cf502fa96d30a643f0607650c628287a39b30ea`
git checkout 0cf502fa96d30a643f0607650c628287a39b30ea -- keyboards/rura66/

# Commit to branch as usual
git commit -m "Add RURA66 new keyboard"

# Push your local `Keyboard_RURA66` branch to GitHub, overwriting the changes to the `Keyboard_RURA66` branch that are on your GitHub fork
git push --force-with-lease origin
```

2022-07-15 03:07 UTC, noroadsleft commented
There's a lot of unrelated files in this pull request. With your permission, I can re-implement this PR from a clean state so it's only the files necessary to support this board.

2022-08-31 16:36 UTC, ShinoharaTa commented
Thank you for your comments.
I am hoping to be able to resume this pull request from a clean environment.
Please let me know the steps to allow it. I want to complete this keyboard myself.

2022-10-03 08:13 UTC, noroadsleft commented
@ShinoharaTa,

The following commands will clean the branch you used for this PR:

```sh
# Untrack the additional files
#         -r = allow recursive removal
#   --cached = removes the files from Git's tracking, but leaves them present on your filesystem
git rm -r --cached keyboards/_mayshino30/ keyboards/blackmask60/ keyboards/mayshi_no30/

# Commit the changes
git commit -m "remove additional files"

# Update your GitHub fork and this PR:
git push
```

You'll be able to re-add the files to Git by creating a new branch or branches, and adding the files to those branches using your normal methods.

2022-12-01 07:51 UTC, ShinoharaTa commented
@noroadsleft 

Sorry for the delay in responding.
I ran the command as you pointed out and pushed it to my repository.
I would appreciate you reopening this PR if possible.

2022-12-01 08:19 UTC, fauxpark requested changes

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/keymaps/default/keymap.c
> +      XXXXXXX, RESET,   RGBRST,  EEP_RST, XXXXXXX, XXXXXXX,                                     RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, XXXXXXX, XXXXXXX,
```suggestion
      XXXXXXX, QK_BOOT, RGBRST,  EE_CLR,  XXXXXXX, XXXXXXX,                                     RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, XXXXXXX, XXXXXXX,
```

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/info.json
> +  "height": 5,
```suggestion
```

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/config.h
> +
```suggestion
```

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/info.json
> +  "keyboard_name": "RURA66",
```suggestion
  "keyboard_name": "RURA66",
  "manufacturer": "ShinoharaTa",
```

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/info.json
> +  "maintainer": "ShinoharaTa",
```suggestion
  "maintainer": "ShinoharaTa",
  "usb": {
    "vid": "0xFEED",
    "pid": "0x3060",
    "device_version": "0.0.1"
  },
```

2022-12-01 08:19 UTC, fauxpark commented on keyboards/rura66/rev1/config.h
> +  #define DRIVER_LED_TOTAL RGBLED_NUM
```suggestion
  #define RGB_MATRIX_LED_COUNT 66
```

2022-12-02 18:53 UTC, noroadsleft reviewed
Your list of included files is now correct. :+1: 

No issues other than the ones already flagged by drashna (https://github.com/qmk/qmk_firmware/pull/15853#pullrequestreview-851067481) and fauxpark (https://github.com/qmk/qmk_firmware/pull/15853#pullrequestreview-1200536269).

2022-12-04 14:34 UTC, ShinoharaTa commented
Thanks to all the maintainers for the code check.

I would like to confirm one thing.
Should I write in Data-Driven? Or old style?

I couldn't decide on my own and would like to get your opinion.

2022-12-10 22:21 UTC, yswallow commented
I did many changes:

* add instructions to how to enter bootloader on README
* remove `snprintf()` on `oled_display.c`
* disable RGB Matrix and backlight
* disable `SPLIT_HAND_MATRIX_GRID`
* change VID/PID
* add VIA keymap

We're sorry that we enabled unnecessary features and that we make changes after your reviews.

2022-12-11 02:43 UTC, drashna approved these changes

2022-12-11 04:04 UTC, fauxpark requested changes

2022-12-11 04:04 UTC, fauxpark commented on keyboards/rura66/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-12-11 04:04 UTC, fauxpark commented on keyboards/rura66/rules.mk
> +#   change yes to no to disable
```suggestion
#   change yes to no to disable
#
```

2022-12-11 04:04 UTC, fauxpark commented on keyboards/rura66/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
```

2022-12-12 07:28 UTC, noroadsleft requested changes
One small thing from me:

2022-12-12 23:23 UTC, noroadsleft approved these changes

2022-12-12 23:23 UTC, merged

2022-12-12 23:24 UTC, noroadsleft commented
Thanks!

2022-12-13 01:02 UTC, ShinoharaTa commented
Thanks for the merge.
I appreciate all of you.