[Keymap] Planck Keymap: tomkonidas
qmk/qmk_firmware pull request #15869
Opened 2022-01-14 02:37 UTC by tomkonidas

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-14 04:34 UTC, drashna approved these changes

2022-01-14 07:21 UTC, fauxpark requested changes

2022-01-14 07:21 UTC, fauxpark commented on keyboards/planck/keymaps/tomkonidas/config.h
> +
```suggestion
```

2022-01-29 06:49 UTC, drashna commented on keyboards/planck/keymaps/tomkonidas/readme.md
> +</p>
Please remove all html tags.

2022-02-01 03:44 UTC, tomkonidas commented on keyboards/planck/keymaps/tomkonidas/readme.md
> +</p>
Removed them 👉 8919627

2022-02-01 03:50 UTC, drashna approved these changes

2022-03-15 22:47 UTC, noroadsleft approved these changes

2022-03-15 22:48 UTC, merged

2022-03-15 22:48 UTC, noroadsleft commented
Thanks!