Fix encoder bug zoom65 and zoom65_litte
qmk/qmk_firmware pull request #15876
Opened 2022-01-14 13:04 UTC by spbgzh

## Description
Fix encoder bug zoom65 and zoom65_litte

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
https://github.com/qmk/qmk_firmware/pull/15218
https://github.com/qmk/qmk_firmware/pull/14926

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-14 14:49 UTC, zvecr requested changes

2022-01-14 14:49 UTC, zvecr commented on keyboards/meletrix/zoom65/config.h
> +#endif
```suggestion
```

2022-01-14 14:49 UTC, zvecr commented on keyboards/meletrix/zoom65_lite/config.h
> +#endif
```suggestion
```

2022-01-14 15:31 UTC, spbgzh commented on keyboards/meletrix/zoom65/config.h
> +#endif
Deleted

2022-01-14 17:36 UTC, zvecr approved these changes

2022-01-15 00:54 UTC, fauxpark approved these changes

2022-01-15 05:49 UTC, merged

2023-04-11 23:35 UTC, ibrokemypie commented
Which product is the zoom65_lite? Can't find any mention of it online

Do either of these cover the zoom65 essential edition (wireless version)?

2023-06-22 16:45 UTC, BigBoiMan123 commented
Will the zoom65 v2 be added?