add Yuri to QMK
qmk/qmk_firmware pull request #15874
Opened 2022-01-14 11:30 UTC by oceeean

## Description

add Yuri to QMK and VIA support
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-14 14:48 UTC, zvecr requested changes

2022-01-14 14:48 UTC, zvecr commented on keyboards/ocean/yuri/config.h
> +#define DESCRIPTION     40 percent alice
```suggestion
```

2022-01-17 12:34 UTC, oceeean commented
could you help me review this PR, please? @drashna @fauxpark

2022-01-19 06:16 UTC, fauxpark approved these changes

2022-01-22 06:08 UTC, drashna approved these changes

2022-01-22 06:09 UTC, merged

2022-01-22 06:09 UTC, drashna commented
Thanks!