Add LAYOUTS entry to rules.mk
qmk/qmk_firmware pull request #15900
Opened 2022-01-16 11:39 UTC by filterpaper

## Description

Add LAYOUTS entry to `rules.mk` that was missed out in #15850

## Types of Changes

- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-16 16:59 UTC, zvecr requested changes

2022-01-16 16:59 UTC, zvecr commented on keyboards/a_dux/rules.mk
> +SPLIT_KEYBOARD = yes        # Use shared split_common code
```suggestion
```

2022-01-17 01:31 UTC, zvecr approved these changes

2022-01-17 09:50 UTC, fauxpark approved these changes

2022-01-17 14:11 UTC, merged