Digicarp65
qmk/qmk_firmware pull request #15926
Opened 2022-01-18 06:03 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-29 03:38 UTC, drashna requested changes

2022-01-29 03:38 UTC, drashna commented on keyboards/handwired/swiftrax/digicarp65/keymaps/via/keymap.c
> +}
```suggestion
```

2022-01-29 03:38 UTC, drashna commented on keyboards/handwired/swiftrax/digicarp65/digicarp65.c
> +#include "digicarp65.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "digicarp65.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2022-01-30 19:01 UTC, drashna requested changes

2022-01-30 19:01 UTC, drashna commented on keyboards/handwired/swiftrax/digicarp65/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-02-05 03:09 UTC, drashna approved these changes

2022-02-05 04:23 UTC, fauxpark requested changes

2022-02-05 04:23 UTC, fauxpark commented on keyboards/handwired/swiftrax/digicarp65/rules.mk
> +ENCODER_ENABLE = yes        # Rotary Encder
```suggestion
ENCODER_ENABLE = yes        # Rotary Encoder

LAYOUTS = 65_ansi 65_ansi_split_bs 65_iso 65_iso_split_bs
```

?

2022-02-05 04:23 UTC, fauxpark commented on keyboards/handwired/swiftrax/digicarp65/digicarp65.h
> + #define LAYOUT_65_ansi_splitbs( \
```suggestion
 #define LAYOUT_65_ansi_split_bs( \
```

2022-02-05 04:23 UTC, fauxpark commented on keyboards/handwired/swiftrax/digicarp65/digicarp65.h
> +#define LAYOUT_65_iso_splitbs( \
```suggestion
#define LAYOUT_65_iso_split_bs( \
```

2022-02-05 04:23 UTC, fauxpark commented on keyboards/handwired/swiftrax/digicarp65/info.json
> +        "LAYOUT_65_ansi_splitbs": {
```suggestion
        "LAYOUT_65_ansi_split_bs": {
```

2022-02-05 04:23 UTC, fauxpark commented on keyboards/handwired/swiftrax/digicarp65/info.json
> +        "LAYOUT_65_iso_splitbs": {
```suggestion
        "LAYOUT_65_iso_split_bs": {
```

2022-02-07 18:41 UTC, swiftrax commented on keyboards/handwired/swiftrax/digicarp65/rules.mk
> +ENCODER_ENABLE = yes        # Rotary Encder
probably accidentally deleted

2022-02-08 01:44 UTC, fauxpark approved these changes

2022-02-09 05:41 UTC, drashna commented
> ☒ handwired/swiftrax/digicarp65: Claims to support a community layout that does not exist: 65_iso_split_bs

2022-02-09 05:47 UTC, fauxpark commented
I can whip up a default layout for `65_iso_split_bs` in a bit.

2022-02-09 05:51 UTC, merged

2022-02-12 05:26 UTC, fauxpark commented
@swiftrax it seems like the LAYOUT macros and info.json don't match up here. Does this board support the normal `65_ansi` layout *and* `65_ansi_blocker`, or just one of them?

2022-02-12 19:36 UTC, swiftrax commented
> @swiftrax it seems like the LAYOUT macros and info.json don't match up here. Does this board support the normal `65_ansi` layout _and_ `65_ansi_blocker`, or just one of them?

It only supports `65_ansi` not blocker