BDN9 keymap
qmk/qmk_firmware pull request #15924
Opened 2022-01-18 03:58 UTC by lickel

## Description

This is a BDN9 keymap that toggles between two core layers. It has VIA enabled by default.
It uses the RGB matrix to signify which layer is currently active.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-18 14:42 UTC, zvecr commented
Core changes need to be submitted as its own PR.

2022-01-18 14:46 UTC, lickel commented
Yup. This is a draft, waiting for the core PR to merge

2022-02-05 03:15 UTC, lickel commented
@zvecr the "awaiting_pr" tag is no longer accurate. I am not able to remove it myself.

2022-02-06 15:58 UTC, drashna commented on keyboards/keebio/bdn9/keymaps/lickel/keymap.c
> +#ifdef RGBLIGHT_ANIMATIONS
Not a fan of using this, as been working to deprecate it, in general.

2022-02-06 16:03 UTC, drashna requested changes

2022-02-06 16:03 UTC, drashna commented on keyboards/keebio/bdn9/keymaps/lickel/keymap.c
> +#ifdef RGBLIGHT_ANIMATIONS
```suggestion
#if defined(RGBLIGHT_ENABLE) || defined(RGB_MATRIX_ENABLE)
```

2022-02-12 04:21 UTC, drashna approved these changes

2022-02-12 05:03 UTC, fauxpark approved these changes

2022-02-21 17:05 UTC, lickel commented
@drashna or @fauxpark anything else needed to merge this?

2022-02-21 17:35 UTC, merged

2022-02-21 17:35 UTC, drashna commented
Thanks!

2022-02-21 17:36 UTC, lickel commented
Thanks!