RGB matrix effects definiton fix
qmk/qmk_firmware pull request #15930
Opened 2022-01-18 20:31 UTC by fOmey

RGB matrix effects were incorrectly defined in the first pull request and made it through.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-19 02:48 UTC, drashna approved these changes

2022-01-19 21:12 UTC, fOmey commented
Mistakenly deleted branch thinking changes were merged.

2022-01-19 22:59 UTC, daskygit requested changes
The default keymap now compiles oversize, you can either use `LTO_ENABLE = yes` or remove some of the enabled RGB effects.

2022-01-20 10:24 UTC, daskygit requested changes
Just some small white space corrections and edits to keep comments consistent with template. https://github.com/qmk/qmk_firmware/blob/master/data/templates/avr/rules.mk

2022-01-20 10:24 UTC, daskygit commented on keyboards/atlantis/ak81_ve/rules.mk
> +BOOTMAGIC_ENABLE = yes      # Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-01-20 10:24 UTC, daskygit commented on keyboards/atlantis/ak81_ve/rules.mk
> +NKRO_ENABLE = yes           # N-Key Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-20 10:24 UTC, daskygit commented on keyboards/atlantis/ak81_ve/rules.mk
> +LTO_ENABLE = yes			# Link time optimization
```suggestion
RGB_MATRIX_ENABLE = yes     # Enable RGB matrix
RGB_MATRIX_DRIVER = WS2812  # RGB matrix driver
LTO_ENABLE = yes            # Link time optimization
```

2022-01-20 10:24 UTC, daskygit commented on keyboards/atlantis/ak81_ve/rules.mk
> +ENCODER_ENABLE = yes		# Encoder
```suggestion
DYNAMIC_MACRO_ENABLE = yes  # Macro recording in realtime
ENCODER_ENABLE = yes        # Encoder
```

2022-01-20 22:45 UTC, fauxpark requested changes

2022-01-20 22:45 UTC, fauxpark commented on keyboards/atlantis/ak81_ve/rules.mk
> +ENCODER_ENABLE = yes		# Encoder
```suggestion
BOOTMAGIC_ENABLE = yes      # Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Keyboard RGB underglow
AUDIO_ENABLE = no			# Audio output
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
ENCODER_ENABLE = yes
```

2022-01-20 22:58 UTC, fauxpark requested changes

2022-01-20 22:58 UTC, fauxpark commented on keyboards/atlantis/ak81_ve/rules.mk
> +AUDIO_ENABLE = no			# Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output
```

2022-01-23 23:40 UTC, fauxpark approved these changes

2022-01-24 01:36 UTC, zvecr approved these changes

2022-01-24 01:37 UTC, merged