Add Axolstudio Foundation
qmk/qmk_firmware pull request #15948
Opened 2022-01-20 09:17 UTC by kb-elmo

## Description

Added support for the Axolstudio Foundation TKL PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-22 05:28 UTC, drashna requested changes

2022-01-22 05:28 UTC, drashna commented on keyboards/axolstudio/foundation_gamma/info.json
> +    "height": 6.5,
```suggestion
```

2022-01-22 05:28 UTC, drashna commented on keyboards/axolstudio/foundation_gamma/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-01-22 05:28 UTC, drashna commented on keyboards/axolstudio/foundation_gamma/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
NKRO_ENABLE = no            # Enable N-key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```

2022-02-20 21:41 UTC, kb-elmo commented
must have missed the change requests.
updated the pr now :)

2022-03-14 10:47 UTC, kb-elmo commented
bump :)

2022-03-15 10:03 UTC, drashna approved these changes

2022-03-16 03:05 UTC, fauxpark requested changes

2022-03-16 03:05 UTC, fauxpark commented on keyboards/axolstudio/foundation_gamma/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-03-18 05:15 UTC, fauxpark approved these changes

2022-03-23 05:06 UTC, merged