Small fixes to the Keybee65
qmk/qmk_firmware pull request #15966
Opened 2022-01-21 00:54 UTC by ToastyStoemp

## Description

Fix issues with brightness on the Keybee 65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-22 04:24 UTC, drashna requested changes

2022-01-22 04:24 UTC, drashna commented on keyboards/keybee/keybee65/rules.mk
> +KEYBOARD_LOCK_ENABLE = yes
Please revert
```suggestion
NKRO_ENABLE = yes           # Enable N-key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-01-28 23:38 UTC, drashna approved these changes

2022-01-29 00:56 UTC, fauxpark requested changes

2022-01-29 00:56 UTC, fauxpark commented on keyboards/keybee/keybee65/rules.mk
> +NKRO_ENABLE = yes           # Enable N-key Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-29 00:56 UTC, fauxpark commented on keyboards/keybee/keybee65/rules.mk
> +BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-01-29 14:13 UTC, fauxpark approved these changes

2022-01-30 18:59 UTC, drashna commented
Thanks!

2022-01-30 18:59 UTC, merged