Add base FAve 84H firmware
qmk/qmk_firmware pull request #15967
Opened 2022-01-21 00:56 UTC by ToastyStoemp

## Description

Add base firmware for the Linworks  FAve 84H

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-21 01:08 UTC, zvecr requested changes

2022-01-21 01:08 UTC, zvecr commented on keyboards/linworks/fave84h/readme.md
> +    make wolf/fave84h:default
```suggestion
    make linworks/fave84h:default
```

2022-01-21 01:08 UTC, zvecr commented on keyboards/linworks/fave84h/keymaps/via/keymap.c
> +void rgb_matrix_indicators_kb(void) {
```suggestion
void rgb_matrix_indicators_user(void) {
```

2022-01-21 01:08 UTC, zvecr commented on keyboards/linworks/fave84h/keymaps/default/keymap.c
> +void rgb_matrix_indicators_kb(void) {
```suggestion
void rgb_matrix_indicators_user(void) {
```

2022-01-28 23:37 UTC, drashna approved these changes

2022-01-29 00:57 UTC, fauxpark requested changes

2022-01-29 00:57 UTC, fauxpark commented on keyboards/linworks/fave84h/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-01-29 14:14 UTC, fauxpark approved these changes

2022-01-30 18:58 UTC, merged

2022-01-30 18:59 UTC, drashna commented
Thanks!