Add support for Mode SeventyFive
qmk/qmk_firmware pull request #16030
Opened 2022-01-24 23:32 UTC by Gondolindrim

Adds support for Mode SeventyFive's solderable and hotswap variants.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-24 23:41 UTC, fauxpark requested changes

2022-01-24 23:41 UTC, fauxpark commented on keyboards/mode/m75h/rules.mk
> +MCU = STM32F401
```suggestion
MCU = STM32F401

# Bootloader selection
BOOTLOADER = stm32-dfu
```

2022-01-24 23:41 UTC, fauxpark commented on keyboards/mode/m75h/rules.mk
> +STM32_BOOTLOADER_ADDRESS = 0x1FFF0000
```suggestion

# Enter lower-power sleep mode when on the ChibiOS idle thread
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE -DDEBUG_EEPROM_OUTPUT=TRUE
```

2022-01-24 23:41 UTC, fauxpark commented on keyboards/mode/m75s/rules.mk
> +MCU = STM32F401
```suggestion
MCU = STM32F401

# Bootloader selection
BOOTLOADER = stm32-dfu
```

2022-01-24 23:41 UTC, fauxpark commented on keyboards/mode/m75s/rules.mk
> +STM32_BOOTLOADER_ADDRESS = 0x1FFF0000
```suggestion

# Enter lower-power sleep mode when on the ChibiOS idle thread
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE -DDEBUG_EEPROM_OUTPUT=TRUE
```

2022-01-26 20:27 UTC, fauxpark approved these changes

2022-01-27 15:50 UTC, zvecr approved these changes

2022-01-27 15:50 UTC, merged