Add glacier in creatkeebs folder
qmk/qmk_firmware pull request #16079
Opened 2022-01-27 12:59 UTC by Timliuzhaolu

## Description
Add glacier in creatkeebs folder

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-27 15:04 UTC, zvecr requested changes

2022-01-27 15:04 UTC, zvecr commented on keyboards/creatkeebs/glacier/config.h
> +
```suggestion
```

2022-01-27 15:04 UTC, zvecr commented on keyboards/creatkeebs/glacier/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2022-01-27 23:40 UTC, drashna requested changes

2022-01-27 23:40 UTC, drashna commented on keyboards/creatkeebs/glacier/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-01-28 20:22 UTC, drashna approved these changes

2022-02-13 02:58 UTC, Timliuzhaolu commented
Hi @drashna am I missing any requested changes? It has been half a month since the last time I committed...

2022-02-13 03:12 UTC, fauxpark requested changes

2022-02-13 03:12 UTC, fauxpark commented on keyboards/creatkeebs/glacier/readme.md
> +![glacier](https://cdn.shopify.com/s/files/1/0481/5840/8853/products/4b8d52820aab652152cd749123d3f8b_6a073c5e-336d-47b4-90fc-8b0fe5a790fe_720x.png?v=1641814324)
Could you please reupload this to imgur?

2022-02-13 03:12 UTC, fauxpark commented on keyboards/creatkeebs/glacier/info.json
> +		{"x":17.25, "y":0},
```suggestion
                {"x":16.25, "y":0},
                {"x":17.25, "y":0},
```

2022-02-13 03:12 UTC, fauxpark commented on keyboards/creatkeebs/glacier/info.json
> +		{"x":17.25, "y":1.25},
```suggestion
                {"x":16.25, "y":1.25},
                {"x":17.25, "y":1.25},
```

2022-02-13 03:12 UTC, fauxpark commented on keyboards/creatkeebs/glacier/info.json
> +		{"x":17.25, "y":2.25},
```suggestion
                {"x":16.25, "y":2.25},
                {"x":17.25, "y":2.25},
```

2022-02-13 03:12 UTC, fauxpark commented on keyboards/creatkeebs/glacier/info.json
> +		{"x":17.25, "y":5.25}
```suggestion
                {"x":13.5, "y":5.25, "w":1.5},
                {"x":15.25, "y":5.25},
                {"x":16.25, "y":5.25},
                {"x":17.25, "y":5.25}
```

2022-02-13 08:37 UTC, fauxpark approved these changes

2022-02-13 08:59 UTC, Timliuzhaolu commented
Thanks again guys! Shall we wait for the other reviewer who requested changes a while ago to approve or is it good to go

2022-02-16 14:17 UTC, Timliuzhaolu commented
> Thanks again guys! Shall we wait for the other reviewer who requested changes a while ago to approve or is it good to go

Sorry for the pinning but not sure about whether you guys saw the previous message... @fauxpark @drashna

2022-02-21 07:52 UTC, merged

2022-02-21 07:52 UTC, drashna commented
Thanks!