Fixed issue flash size on Handwired K552 keyboard
qmk/qmk_firmware pull request #16092
Opened 2022-01-28 06:33 UTC by HorrorTroll

## Description

It was mistake to use ldscript from STM32F103x8, instead using STM32F103xC. So the flash size was limited at 64kb, while it should be 256kb

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-28 19:49 UTC, drashna approved these changes

2022-03-05 05:25 UTC, tzarc commented
As far as I can tell, you can do all of this in a much simpler way.

* Remove the custom board files (i.e. `boards/STM32_F103XC_STM32DUINO` in its entirety)
* Swap board to the normal STM32duino: `BOARD = STM32_F103_STM32DUINO`
* Remove the other customisations in the `rules.mk` apart from the `MCU_LDSCRIPT`
* Add a keyboard-level `board.h` file with the content:
```c
#pragma once
#include_next <board.h>
#undef STM32F103xB
#define STM32F103xE
```
* Add a validation inside `handwired_k552.c`:
```c
#ifndef STM32F103xE
#error "Should be building for F103xE but wasn't!"
#endif
```

2022-03-05 10:46 UTC, tzarc commented
Ignore the change to target develop; I saw board files and automatically assumed it was a core modification.

2022-04-18 08:55 UTC, fauxpark requested changes

2022-04-18 08:55 UTC, fauxpark commented on keyboards/horrortroll/handwired_k552/rules.mk
> +DFU_SUFFIX_ARGS = -v 1EAF -p 0003
```suggestion
# Custom loader configuration
BOOTLOADER_TYPE = stm32duino
OPT_DEFS += -DBOOTLOADER_STM32DUINO
MCU_LDSCRIPT = STM32F103xC_stm32duino_bootloader
BOARD = STM32_F103XC_STM32DUINO
DFU_ARGS = -d 1EAF:0003 -a 2 -R
DFU_SUFFIX_ARGS = -v 1EAF -p 0003
```

2022-04-18 13:43 UTC, HorrorTroll commented on keyboards/horrortroll/handwired_k552/rules.mk
> +DFU_SUFFIX_ARGS = -v 1EAF -p 0003
fixed now, thanks

2022-06-13 06:36 UTC, HorrorTroll commented
Just pushed an updated code, testing and working normally

2022-08-14 03:28 UTC, HorrorTroll commented
Closed

2022-08-14 03:28 UTC, closed without merging