Add rgb-light and encoder for lily58 mod
qmk/qmk_firmware pull request #16101
Opened 2022-01-28 16:24 UTC by LVladymyr

Add rgb-light and encoders for [lily58-glow-enc mod](https://github.com/orvisevans/Lily58-Glow-Enc)

## Description

Set custom pins and settings for enabling rgb-light and encoders (one per controller).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-28 20:10 UTC, drashna requested changes
please rename the folder and files to be all lower case.

2022-01-28 20:10 UTC, drashna commented on keyboards/lily58/glowEnc/glowEnc.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-01-28 20:10 UTC, drashna commented on keyboards/lily58/glowEnc/config.h
> +#define DESCRIPTION     Lily58 is 6×4+5keys column-staggered split keyboard with glowing keys and encoders.
```suggestion
```

2022-01-28 21:13 UTC, drashna approved these changes

2022-03-10 20:20 UTC, noroadsleft approved these changes
Looks good to me.

2022-03-10 20:21 UTC, merged

2022-03-10 20:21 UTC, noroadsleft commented
Thanks!