Io mini1800 - New Keyboard
qmk/qmk_firmware pull request #16115
Opened 2022-01-29 15:39 UTC by jpuerto96

## Description

This PR adds a new keyboard to QMK - IO-Mini 1800

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-29 15:41 UTC, fauxpark requested changes

2022-01-29 15:41 UTC, fauxpark commented on keyboards/io_mini1800/rules.mk
> +# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
```suggestion
```

2022-01-30 18:45 UTC, drashna requested changes

2022-01-30 18:45 UTC, drashna commented on keyboards/io_mini1800/keymaps/default/keymap.c
> +}
```suggestion
```

2022-01-30 18:45 UTC, drashna commented on keyboards/io_mini1800/keymaps/2x3u/keymap.c
> +
```suggestion
```

2022-01-30 18:45 UTC, drashna commented on keyboards/io_mini1800/io_mini1800.c
> +#include "io_mini1800.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "io_mini1800.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2022-01-30 18:49 UTC, fauxpark approved these changes

2022-02-07 04:16 UTC, jpuerto96 commented
@drashna ping for re-review.

2022-02-21 20:58 UTC, jpuerto96 commented
@drashna - re-pinging for re-review.

2022-03-15 02:46 UTC, noroadsleft requested changes

2022-03-15 02:46 UTC, noroadsleft commented on keyboards/io_mini1800/readme.md
> +To reset the board, you will want to short the pad labeled RESET on the back (near the MCU).
```suggestion
## Bootloader

To reset the board into bootloader, do one of the following:

* **Hardware reset**: short the pad labeled RESET on the back, near the microcontroller
* **Bootmagic reset**: hold down the top left key (usually programmed as Escape) while plugging in the keyboard (also resets persistent storage)
```

2022-03-15 02:46 UTC, noroadsleft commented on keyboards/io_mini1800/keymaps/2x3u/readme.md
> +# The default keymap for io_mini1800
```suggestion
# The default Split Spacebar keymap for io_mini1800
```

2022-03-15 08:32 UTC, noroadsleft approved these changes

2022-03-15 08:35 UTC, merged

2022-03-15 08:35 UTC, noroadsleft commented
Thanks!