R2 version of jadookb/jkb65
qmk/qmk_firmware pull request #16129
Opened 2022-01-30 05:51 UTC by wizard-gg

## Description
 new R2 version added

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-01-30 18:38 UTC, drashna approved these changes

2022-01-30 18:46 UTC, fauxpark requested changes

2022-01-30 18:46 UTC, fauxpark commented on keyboards/jadookb/jkb65/r2/readme.md
> +    make jadookb/jkb65/R2:default:flash
```suggestion
    make jadookb/jkb65/r2:default

Flashing example for this keyboard:

    make jadookb/jkb65/r2:default:flash
```

2022-01-31 06:35 UTC, wizard-gg reviewed
updated

2022-01-31 19:21 UTC, drashna approved these changes

2022-01-31 20:33 UTC, fauxpark approved these changes

2022-02-01 02:11 UTC, merged