Add splitkb Kyria rev. 2
qmk/qmk_firmware pull request #16178
Opened 2022-02-03 01:15 UTC by Crote

This commit adds the code to support the newest revision of splitkb's Kyria.

## Description

Compared to the Kyria 1.x, the 2.x series features the following significant changes:
- Handedness by matrix pin
- Reworked matrix wiring
- Reworked WS2812B ordering

This means a new software revision is required as those make it backwards incompatible.
The code is pretty much a copy/paste from rev1, with minor changes where neccesary.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
_**Note:** `make keyboard:all` returned firmware size errors, but those were already present before this commit._
_**Note:** Proton-C support has not been tested as we do not have a pair of controllers at hand._

2022-02-03 01:18 UTC, splitkb approved these changes

2022-02-03 16:09 UTC, drashna requested changes

2022-02-07 13:38 UTC, Crote commented on keyboards/splitkb/kyria/rev2/config.h
> +#define SPLIT_HAND_MATRIX_GRID E6, B3 // row first because the board is col2row
Good catch, added it!

2022-02-07 18:23 UTC, drashna requested changes

2022-02-07 18:23 UTC, drashna commented on keyboards/splitkb/kyria/rev2/rev2.c
> +        oled_write_P(PSTR("Kyria rev2\n\n"), false);
And if we're moving stuff:
```suggestion
        oled_write_P(PSTR("Kyria ", false);
#if defined(KEYBOARD_splitkb_kyria_rev1)
        oled_write_P(PSTR("rev1"), false);
#elif defined(KEYBOARD_splitkb_kyria_rev2)
        oled_write_P(PSTR("rev2"), false);
#endif
        oled_advance_page(true);
        oled_advance_page(true);
```

2022-02-11 15:23 UTC, drashna approved these changes

2022-02-12 01:23 UTC, splitkb commented on keyboards/splitkb/kyria/rev2/proton_c/rules.mk
> +CONVERT_TO_PROTON_C = yes
That seems agreeable to me - the Proton C seems to not enjoy wider availability at the moment, and compiling firmware from source is an option.

Is there a way to make it play nice with both AVR-based controllers and the Proton C? If there's no better alternative, I suggest we leave it this way.

2022-02-12 01:27 UTC, fauxpark commented on keyboards/splitkb/kyria/rev2/proton_c/rules.mk
> +CONVERT_TO_PROTON_C = yes
You can implement the `proton_c` revision without using CTPC - ie. setting `MCU` to `STM32F303`, adding `BOARD = QMK_PROTON_C`, `BOOTLOADER = stm32-dfu`, redefining the pins, etc.

2022-02-12 02:44 UTC, fauxpark commented on keyboards/splitkb/kyria/rev2/proton_c/rules.mk
> +CONVERT_TO_PROTON_C = yes
It's not a blocker, I've been cleaning up some of the Configurator build failures recently anyway and noticed rev1 and another unrelated board were on that list already. So I can fix them all up later if need be.

2022-02-12 02:59 UTC, drashna commented on keyboards/splitkb/kyria/rev2/proton_c/rules.mk
> +CONVERT_TO_PROTON_C = yes
> You can implement the `proton_c` revision without using CTPC - ie. setting `MCU` to `STM32F303`, adding `BOARD = QMK_PROTON_C`, `BOOTLOADER = stm32-dfu`, redefining the pins, etc.

Keeping the convert to proton c rule should prevent needing pin redefinitions.  So adding the others should be good (though, that's what happens eventually. 

Eg, this should work:

```make
# MCU name
MCU = STM32F303

BOARD = QMK_PROTON_C

# Bootloader selection
BOOTLOADER = stm32-dfu

CONVERT_TO_PROTON_C = yes
```

2022-02-15 13:43 UTC, splitkb commented
Is there anything we can do to get this pull request merged into the main branch?

2022-02-17 03:00 UTC, fauxpark commented
Let's wait for #16377 to be merged, and if it works, the same change can be applied here.

2022-02-19 13:03 UTC, fauxpark requested changes

2022-02-19 13:03 UTC, fauxpark commented on keyboards/splitkb/kyria/rev2/proton_c/rules.mk
> +WS2812_DRIVER = pwm
```suggestion
# MCU name
MCU = STM32F303
BOARD = QMK_PROTON_C

# Bootloader selection
BOOTLOADER = stm32-dfu

WS2812_DRIVER = pwm
```

2022-02-20 05:16 UTC, splitkb commented
Requested changes have been applied, please let us know if there's anything else that should be patched up :)

2022-02-20 05:24 UTC, fauxpark approved these changes

2022-02-21 06:33 UTC, merged