New Keyboard: 1upkeyboards super16v2
qmk/qmk_firmware pull request #16198
Opened 2022-02-04 05:13 UTC by mechmerlin

## Description

Add a new 1upkeyboards keyboard the super16v2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-04 05:13 UTC, tzarc commented
Denied.

2022-02-04 05:35 UTC, drashna requested changes

2022-02-04 05:35 UTC, drashna commented on keyboards/1upkeyboards/super16v2/config.h
> +/*== or choose animations ==*/
```suggestion
```

2022-02-06 05:13 UTC, drashna commented on keyboards/1upkeyboards/super16v2/readme.md
> +*A short description of the keyboard/project*
something something

2022-02-09 05:22 UTC, drashna approved these changes

2022-02-09 05:46 UTC, fauxpark approved these changes

2022-02-09 05:51 UTC, merged