New custom keymap for Glorious GMMK Pro ANSI layout
qmk/qmk_firmware pull request #16199
Opened 2022-02-04 05:44 UTC by gourdo1

## Description

This Windows-centric layout is based on Jonavin's GMMK Pro ANSI layout (https://github.com/qmk/qmk_firmware/tree/master/keyboards/gmmk/pro/ansi/keymaps/jonavin) with modifications to keymap, functionality and RGB.

Details in the readme.md:
https://github.com/gourdo1/qmk_firmware/tree/PR-branch/keyboards/gmmk/pro/ansi/keymaps/gourdo1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

none

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-04 17:45 UTC, drashna requested changes
please remove the PDF file. 

Also, please run a formatting pass of the files in questin.

2022-02-04 17:45 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/gourdo1/keymap.c
> +    }
```suggestion
```

2022-02-04 17:45 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/gourdo1/keymap.c
> +        rgb_matrix_mode(RGB_MATRIX_SOLID_COLOR);
```suggestion
        rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
```

2022-02-04 17:45 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/gourdo1/keymap.c
> +        rgb_matrix_set_color_all(RGB_NAUTILUS); // Default startup colour
```suggestion
        rgb_matrix_sethsv_noeeprom(129, 255, 170); // Default startup colour
```

2022-02-05 01:43 UTC, gourdo1 commented
PDF file removed, all requested code changes made. All .c and .h files formatted.

2022-02-05 02:00 UTC, drashna approved these changes

2022-02-06 05:02 UTC, drashna approved these changes

2022-03-26 00:44 UTC, drashna approved these changes

2022-04-19 11:05 UTC, tzarc approved these changes

2022-04-19 11:05 UTC, merged