Added support for Paws 60 keyboard
qmk/qmk_firmware pull request #16204
Opened 2022-02-04 13:09 UTC by HorrorTroll

## Description

Added support for Paws 60 keyboard. A keyboard that inspired Bakeneko60, more details is in readme

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-04 17:39 UTC, drashna requested changes

2022-02-04 17:39 UTC, drashna commented on keyboards/horrortroll/paws60/config.h
> +#define USB_POLLING_INTERVAL_MS 1
Won't be needed for long. 
```suggestion
```

2022-02-04 17:39 UTC, drashna commented on keyboards/horrortroll/paws60/keymaps/default/keymap.c
> +    _FN = 1
No need to explicitly set a number here.  It starts at 0 and increments up by one, automatically. 
```suggestion
    _BASE,
    _FN,
```

2022-02-04 17:39 UTC, drashna commented on keyboards/horrortroll/paws60/keymaps/via/keymap.c
> +    _FN = 1
```suggestion
    _BASE,
    _FN,
```

2022-02-05 03:10 UTC, HorrorTroll commented on keyboards/horrortroll/paws60/keymaps/via/keymap.c
> +    _FN = 1
Done, thanks

2022-02-05 03:15 UTC, drashna approved these changes

2022-02-05 04:24 UTC, fauxpark requested changes

2022-02-05 04:24 UTC, fauxpark commented on keyboards/horrortroll/paws60/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
AUDIO_ENABLE = no           # Audio output

LAYOUTS = 60_ansi
```

?

2022-02-05 06:00 UTC, HorrorTroll commented on keyboards/horrortroll/paws60/rules.mk
> +AUDIO_ENABLE = no           # Audio output
Oops, just added them now

2022-02-05 06:44 UTC, fauxpark approved these changes

2022-02-05 17:01 UTC, merged