Add Dactyl_Manuform/3x5_3
qmk/qmk_firmware pull request #16238
Opened 2022-02-05 21:18 UTC by dlford

## Description

Added Dactyl_Manuform/3x5_3 configuration and `dlford` keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-06 04:52 UTC, drashna requested changes

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/3x5_3.c
> +}
This is deprecated, and should be removed (eg, the handling is done in the core, now)
```suggestion
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/3x5_3.h
> +#endif
```suggestion
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/3x5_3.h
> +#include "quantum.h"
In theory, isn't needed. 

```suggestion
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/config.h
> +#define USE_I2C
I would highly recommend defaulting to serial, instead of i2c.

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/config.h
> +#endif
This shouldn't be needed:
```suggestion
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/keymaps/dlford/config.h
> +#endif // !NO_PRINT
This isn't the way to disable NKRO.

```suggestion
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/keymaps/dlford/rules.mk
> +EXTRAFLAGS += -flto
`LTO_ENABLE` handles all of this automatically. 
```suggestion
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/keymaps/dlford/rules.mk
> +LAYOUTS = split_3x5_3
Only what is different from the keyboard level should be set here.  LAYOUTS shouldnt be defined here, either. Neither should the MCU

```suggestion
DYNAMIC_MACRO_ENABLE = yes  # Create macros on the fly
RGB_MATRIX_ENABLE = yes
LTO_ENABLE = yes
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/rules.mk
> +# Build Options
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

# Build Options
```

2022-02-06 04:52 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/rules.mk
> +SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = yes          # Audio output

RGB_MATRIX_ENABLE = yes     # Enable WS2812 RGB matrix
RGB_MATRIX_DRIVER = WS2812
SPLIT_KEYBOARD = yes

RGBLIGHT_SUPPORTED = yes
RGB_MATRIX_SUPPORTED = yes

LAYOUTS = split_3x5_3
```

2022-02-08 14:28 UTC, dlford commented
Thank you for the tips drashna! These should all be addressed now.

2022-02-08 16:32 UTC, drashna commented on keyboards/handwired/dactyl_manuform/3x5_3/keymaps/dlford/config.h
> +#endif
You don't really need the ifdefs.
```suggestion
#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_DELAY
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_DELAY
```

2022-02-08 16:33 UTC, drashna approved these changes

2022-02-11 19:13 UTC, dlford commented on keyboards/handwired/dactyl_manuform/3x5_3/keymaps/dlford/config.h
> +#endif
Fixed, thank you!

2022-04-22 08:16 UTC, tzarc approved these changes

2022-04-22 08:16 UTC, merged