[Keyboard] Add Kapl
qmk/qmk_firmware pull request #16255
Opened 2022-02-07 00:51 UTC by keyzog

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-07 19:26 UTC, drashna requested changes

2022-02-07 19:26 UTC, drashna commented on keyboards/kapl/rev1/rules.mk
> +RGB_MATRIX_FRAMEBUFFER_EFFECTS = no		# Enable framebuffer effects
These are defines, not makefile rules.  They need to be defined there. 
```suggestion
```

2022-02-08 01:50 UTC, fauxpark requested changes

2022-02-08 01:50 UTC, fauxpark commented on keyboards/kapl/rules.mk
> +BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality
```suggestion
BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
```

2022-02-08 01:50 UTC, fauxpark commented on keyboards/kapl/rev1/rules.mk
> +
```suggestion
```

2022-02-08 22:09 UTC, fauxpark approved these changes

2022-02-09 05:19 UTC, drashna approved these changes

2022-02-09 05:19 UTC, merged