Adding the custom handwired 5x5 macropad.
qmk/qmk_firmware pull request #16288
Opened 2022-02-09 18:31 UTC by m40-dev

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-10 01:19 UTC, drashna requested changes

2022-02-10 01:19 UTC, drashna commented on keyboards/handwired/m40/5x5_macropad/readme.md
> +![m40](https://imgur.com/bWXH3FV)
```suggestion
![m40](https://i.imgur.com/bWXH3FVl.jpeg)
```

2022-02-12 04:14 UTC, drashna approved these changes

2022-02-12 05:01 UTC, fauxpark requested changes

2022-02-12 05:01 UTC, fauxpark commented on keyboards/handwired/m40/5x5_macropad/rules.mk
> +RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-02-12 05:01 UTC, fauxpark commented on keyboards/handwired/m40/5x5_macropad/readme.md
> +* Hardware Availability: *https://www.thingiverse.com/thing:5239739*
```suggestion
This is very simple 5x5 macropad for general use. It does not come with any particular layout, it is assumed that layouts will be built on the qmk configurator site. Row and column pins start on the edge of Arduino, if smaller board is required, you can simply connect only first x row/column pairs to the board and get the size of the board you need.

* Keyboard Maintainer: [Tomek](https://github.com/m40)
* Hardware Supported: 3D Printed, handwired, using Arduino Pro-Micro (Atmega32U4) for controller
* Hardware Availability: https://www.thingiverse.com/thing:5239739
```

2022-03-15 01:30 UTC, noroadsleft reviewed
Is @m40 an alternate account of yours?

2022-03-15 19:41 UTC, m40-dev commented
> Is @M40 an alternate account of yours?

@noroadsleft - no, m40 is my typical username (also on discord) but on github it was already taken.

2022-03-16 02:44 UTC, noroadsleft requested changes
* changes the username references that are intended to reference the GitHub username to `m40-dev`
* renames `LAYOUT` to `LAYOUT_ortho_5x5`

GitHub tip: You can apply multiple suggestions to a single commit by using the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/16288/files).

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/5x5_macropad.c
> +// Copyright 2022 Tomek (@m40)
```suggestion
// Copyright 2022 Tomek (@m40-dev)
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/5x5_macropad.h
> +// Copyright 2022 Tomek (@m40)
```suggestion
// Copyright 2022 Tomek (@m40-dev)
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/5x5_macropad.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_ortho_5x5( \
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/config.h
> +// Copyright 2022 Tomek (@m40)
```suggestion
// Copyright 2022 Tomek (@m40-dev)
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/config.h
> +//#define BOOTMAGIC_LITE_COLUMN 0
`NO_ACTION_MACRO` and `NO_ACTION_FUNCTION` no longer do anything.

`BOOTMAGIC_LITE_ROW` and `BOOTMAGIC_LITE_COLUMN` only need to be defined if you're using something other than Row 0, Column 0 - this is the default setting in QMK Firmware.

```suggestion
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/info.json
> +    "maintainer": "m40",
```suggestion
    "maintainer": "m40-dev", 
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_ortho_5x5": {
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/keymaps/default/keymap.c
> +// Copyright 2022 Tomek (@m40)
```suggestion
// Copyright 2022 Tomek (@m40-dev)
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/keymaps/default/keymap.c
> +    [_BASE] = LAYOUT(
```suggestion
    [_BASE] = LAYOUT_ortho_5x5(
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/keymaps/default/readme.md
> +# The default keymap for m40
```suggestion
# The default keymap for 5x5_macropad
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/readme.md
> +# m40
```suggestion
# 5x5_macropad
```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/readme.md
> +* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
You have Bootmagic Lite disabled, so the first method won't work.

```suggestion
Enter the bootloader in 2 ways:

```

2022-03-16 02:44 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/readme.md
> +* Keyboard Maintainer: [Tomek](https://github.com/m40-dev)
If you wanted to put your Discord username here, that would be okay.

2022-03-19 00:47 UTC, noroadsleft requested changes
Also one change request from the last review is still pending:

* https://github.com/qmk/qmk_firmware/pull/16288/files/878a27a2522e7dd664a14700a480c553849d9aaa..9895c8d90fc9eadc4be0e5307e2c6e74b21d8079#r827571793

2022-03-19 00:47 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/readme.md
> +* Keyboard Maintainer: [Tomek](https://github.com/m40-dev, discord: m40#4792)
```suggestion
* Keyboard Maintainer: [Tomek](https://github.com/m40-dev) (discord: m40#4792)
```

2022-03-24 21:02 UTC, m40-dev reviewed
All files up-to-date

2022-03-27 16:38 UTC, noroadsleft requested changes

2022-03-27 16:38 UTC, noroadsleft commented on keyboards/handwired/m40/5x5_macropad/info.json
> +        "LAYOUT": {
QMK Configurator won't render the board layout properly unless this is changed.

```suggestion
        "LAYOUT_ortho_5x5": {
```

2022-03-29 19:16 UTC, noroadsleft approved these changes

2022-03-29 19:18 UTC, fauxpark approved these changes

2022-03-29 19:18 UTC, merged

2022-03-29 19:18 UTC, noroadsleft commented
Thanks!