add support for Quark_Plus
qmk/qmk_firmware pull request #16324
Opened 2022-02-12 06:08 UTC by npspears

## Description

Add new keyboard, Quark_Plus

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-12 06:17 UTC, fauxpark requested changes

2022-02-12 06:17 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/readme.md
> +    make quark_plus:default
```suggestion
    make checkerboards/quark_plus:default
```

2022-02-12 06:17 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2u/keymap.c
> +  [0] = LAYOUT_2u( \
```suggestion
  [0] = LAYOUT_2u(
```
etc.

2022-02-12 06:21 UTC, npspears commented
thanks for the quick review, fauxpark

2022-02-23 17:40 UTC, ridingqwerty approved these changes

2022-02-23 18:43 UTC, fauxpark requested changes

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/readme.md
> +![Quark_Plus](https://i.imgur.com/4TI6BA0.png)
```suggestion
![Quark_Plus](https://i.imgur.com/4TI6BA0h.png)
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/via/keymap.c
> +  [2] = LAYOUT_grid( \
```suggestion
  [2] = LAYOUT_grid(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/via/keymap.c
> +  [1] = LAYOUT_grid( \
```suggestion
  [1] = LAYOUT_grid(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/via/keymap.c
> +  [0] = LAYOUT_grid( \
```suggestion
  [0] = LAYOUT_grid(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/default/keymap.c
> +  [2] = LAYOUT_grid( \
```suggestion
  [2] = LAYOUT_grid(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/default/keymap.c
> +  [1] = LAYOUT_grid( \
```suggestion
  [1] = LAYOUT_grid(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/default/keymap.c
> +  [0] = LAYOUT_grid( \
```suggestion
  [0] = LAYOUT_grid(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2x3u/keymap.c
> +[2] = LAYOUT_2x3u( \
```suggestion
[2] = LAYOUT_2x3u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2x3u/keymap.c
> +[1] = LAYOUT_2x3u( \
```suggestion
[1] = LAYOUT_2x3u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2x3u/keymap.c
> +[0] = LAYOUT_2x3u( \
```suggestion
[0] = LAYOUT_2x3u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2x225u/keymap.c
> +  [2] = LAYOUT_2x225u( \
```suggestion
  [2] = LAYOUT_2x225u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2x225u/keymap.c
> +  [1] = LAYOUT_2x225u( \
```suggestion
  [1] = LAYOUT_2x225u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2x225u/keymap.c
> +  [0] = LAYOUT_2x225u( \
```suggestion
  [0] = LAYOUT_2x225u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2u/keymap.c
> +  [2] = LAYOUT_2u( \
```suggestion
  [2] = LAYOUT_2u(
```

2022-02-23 18:43 UTC, fauxpark commented on keyboards/checkerboards/quark_plus/keymaps/2u/keymap.c
> +  [1] = LAYOUT_2u( \
```suggestion
  [1] = LAYOUT_2u(
```

2022-02-27 00:48 UTC, drashna approved these changes

2022-02-27 08:46 UTC, fauxpark approved these changes

2022-03-07 03:26 UTC, merged