[Keyboard] infinity81
qmk/qmk_firmware pull request #16387
Opened 2022-02-17 06:04 UTC by peepeetee

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-17 09:13 UTC, peepeetee commented on keyboards/ada/infinity81/rules.mk
> +RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```suggestion
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
```

2022-02-17 16:20 UTC, drashna requested changes

2022-02-17 16:20 UTC, drashna commented on keyboards/ada/infinity81/config.h
> +#define VENDOR_ID    0xada0
```suggestion
#define VENDOR_ID    0xADA0
```

2022-02-17 16:20 UTC, drashna commented on keyboards/ada/infinity81/config.h
> +#ifdef RGB_DI_PIN
No animations enabled?

2022-02-21 07:18 UTC, drashna approved these changes

2022-02-21 10:43 UTC, fauxpark approved these changes

2022-02-21 17:12 UTC, merged

2022-02-21 17:12 UTC, drashna commented
Thanks!