[Handwired] Support for Adafruit lemon keypad
qmk/qmk_firmware pull request #16395
Opened 2022-02-18 21:40 UTC by dari-studios

## Description

QMK + Via support for a handwired Lemon-themed keypad, designed by Adafruit. Modified for a pro micro.
https://learn.adafruit.com/qtpy-lemon-mechanical-keypad-macropad

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-21 07:10 UTC, drashna commented
This contains changes from other PRs, which need to be reverted.

2022-02-21 07:11 UTC, drashna requested changes

2022-02-21 07:11 UTC, drashna commented on keyboards/handwired/lemonpad/keymaps/default/keymap.c
> +    	)
```suggestion
```

2022-02-21 07:11 UTC, drashna commented on keyboards/handwired/lemonpad/keymaps/default/keymap.c
> +    	_EMPTY8
```suggestion
```

2022-02-21 10:41 UTC, fauxpark requested changes

2022-02-21 10:41 UTC, fauxpark commented on keyboards/handwired/lemonpad/readme.md
> +![lemonpad](https://i.imgur.com/hAp2Nic.jpeg)
```suggestion
![lemonpad](https://i.imgur.com/hAp2Nich.jpeg)
```

2022-02-21 10:41 UTC, fauxpark commented on keyboards/handwired/lemonpad/readme.md
> +* VIA JSON: https://pastebin.com/WXR3jy52
```suggestion
```

2022-02-21 10:41 UTC, fauxpark commented on keyboards/handwired/lemonpad/config.h
> +#define PRODUCT      dari-studios lemonpad
```suggestion
#define PRODUCT      lemonpad
```

2022-02-22 17:44 UTC, dari-studios commented
Reverted changes from other PRs and added suggested changes. Thank you all for your time.

2022-02-22 18:51 UTC, drashna commented
Other changes are still there, it looks like.  Rebasing may work better to fix the issues.

2022-02-22 21:34 UTC, fauxpark requested changes

2022-02-22 21:34 UTC, fauxpark commented on keyboards/handwired/lemonpad/rules.mk
> +VIA_ENABLE = yes
```suggestion
```

2022-02-22 21:34 UTC, zvecr approved these changes

2022-02-27 01:18 UTC, drashna approved these changes

2022-02-27 01:18 UTC, merged