Add support for Typ65+
qmk/qmk_firmware pull request #16399
Opened 2022-02-19 14:10 UTC by kopibeng

## Description
Adds support for Axiom Studios Typ65+

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for Axiom Studios Typ65+

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-19 15:16 UTC, zvecr requested changes

2022-02-19 15:16 UTC, zvecr commented on keyboards/kopibeng/typ65/typ65.c
> +}
```suggestion
```

2022-02-19 15:16 UTC, zvecr commented on keyboards/kopibeng/typ65/typ65.c
> +  setPinOutput(LED_CAPS_LOCK_PIN);
```suggestion

  keyboard_pre_init_user();
```

2022-02-21 06:53 UTC, drashna requested changes

2022-02-21 06:53 UTC, drashna commented on keyboards/kopibeng/typ65/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-02-27 01:19 UTC, drashna approved these changes

2022-02-27 08:47 UTC, fauxpark approved these changes

2022-03-07 03:36 UTC, merged