Add support for MNK65
qmk/qmk_firmware pull request #16400
Opened 2022-02-19 14:35 UTC by kopibeng

## Description
Adds support for MONOKEI MNK65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for MONOKEI MNK65

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-19 15:15 UTC, zvecr requested changes

2022-02-19 15:15 UTC, zvecr commented on keyboards/kopibeng/mnk65/mnk65.c
> +}
```suggestion
```

2022-02-21 06:54 UTC, drashna requested changes

2022-02-21 06:54 UTC, drashna commented on keyboards/kopibeng/mnk65/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-02-27 01:20 UTC, drashna commented on keyboards/kopibeng/mnk65/readme.md
> +![MNK65](https://i.imgur.com/5BzAgPg.png)
```suggestion
![MNK65](https://i.imgur.com/5BzAgPgl.png)
```

2022-03-07 03:38 UTC, drashna approved these changes

2022-03-07 04:24 UTC, fauxpark requested changes

2022-03-07 04:24 UTC, fauxpark commented on keyboards/kopibeng/mnk65/keymaps/default/keymap.c
> +	),
```suggestion
```

2022-03-09 10:39 UTC, fauxpark requested changes

2022-03-09 10:39 UTC, fauxpark commented on keyboards/kopibeng/mnk65/rules.mk
> +ENCODER_ENABLE = no			# Enable Encoder
```suggestion
```

2022-03-10 01:06 UTC, fauxpark approved these changes

2022-03-10 19:10 UTC, drashna commented
Thanks!

2022-03-10 19:10 UTC, merged