[Keyboard] Add labbeminiv1
qmk/qmk_firmware pull request #16401
Opened 2022-02-19 21:33 UTC by alabbe9545

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2022-02-21 06:43 UTC, drashna requested changes

2022-02-21 06:43 UTC, drashna commented on keyboards/labbe/labbeminiv1/config.h
> +#define VENDOR_ID       0x1BBE
This vendor ID is in use already.  Please change it. 

https://www.the-sz.com/products/usbid/index.php?v=0x1BBE&p=&n=

tHe further past 0x4000, the better, actually.

2022-02-21 06:43 UTC, drashna commented on keyboards/labbe/labbeminiv1/keymaps/rgb/keymap.c
> +}*/
```suggestion
```

2022-02-21 17:23 UTC, alabbe9545 commented
Fixed both issues

2022-02-26 13:04 UTC, alabbe9545 commented
Is there an ETA for this?

2022-02-27 01:21 UTC, drashna approved these changes

2022-02-27 08:53 UTC, fauxpark requested changes

2022-02-27 08:53 UTC, fauxpark commented on keyboards/labbe/labbeminiv1/rules.mk
> +RGBLIGHT_ENABLE = no  	    # Enable keyboard RGB underglow
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-02-27 13:07 UTC, alabbe9545 commented
the change was applied

2022-04-12 17:52 UTC, alabbe9545 commented
Is there any ETA for this?

2022-04-13 05:58 UTC, drashna approved these changes

2022-06-14 16:42 UTC, alabbe9545 commented
Hello im waiting for a review,
Please add label "awaiting review"
Thanks.

2022-06-16 09:51 UTC, fauxpark commented on keyboards/labbe/labbeminiv1/keymaps/rgb-matrix/config.h
> +/*
Keymap folders should not contain `-`.

2022-06-20 18:19 UTC, alabbe9545 commented
Hello @fauxpark, '-' removed from keymap folder

2022-06-21 02:51 UTC, fauxpark approved these changes

2022-06-21 03:33 UTC, merged

2022-06-21 03:33 UTC, drashna commented
Thanks!