Rename the parameter name to avoid mistaking it for the new operator, resolve #16416
qmk/qmk_firmware pull request #16417
Opened 2022-02-21 11:19 UTC by ziteh

## Description

The original parameter name `new` could be mistaken for new operator and cause a compilation error.

I changed this parameter name from `new` to `newMouseReport`,  I think changing the parameter name to newMouseReport can also make it consistent with the other functions (`pointing_device_set_report(report_mouse_t newMouseReport)`).

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fiexs #16416 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-21 11:36 UTC, fauxpark commented
There is no `new` operator in C.

2022-02-21 13:22 UTC, ziteh commented
I'm also a little confused and unsure.

But "the compiler mistook it for a new operator" is the only reason I can think of that would cause an ` error: expected ',' or '...' before 'new'` in the compilation.

In addition, I renamed the parameters to `new_report` and `old_report`.

2022-02-21 13:37 UTC, fauxpark commented
Sorry, I didn't see the linked issue.

It looks like `pointing_device.h` is being included in `adafruit_ble.cpp` (which, yes, is one of the few things written in C++ in QMK) through `analog.h` -> `quantum.h`. I doubt `analog.h` really needs most of the stuff in `quantum.h` - could you try changing it to `gpio.h` instead?

2022-02-21 13:39 UTC, fauxpark commented on quantum/pointing_device.c
>   * @param[in] old report_mouse_t
Doc comments should be changed to match.

2022-02-21 13:40 UTC, fauxpark requested changes

2022-02-21 13:40 UTC, fauxpark commented on quantum/pointing_device.h
>  void           pointing_device_set_report(report_mouse_t newMouseReport);
```suggestion
void           pointing_device_set_report(report_mouse_t report);
```
\+ on line 42 of the .c file.

2022-02-22 03:05 UTC, ziteh commented
I tried to replace `quantum.h` in `analog.h` to `gpio.h`, but when using joystick as a pointer device (`POINTING_DEVICE_DRIVER = analog_joystick` in `rules.mk`), it causes a compilation error: 

```
Compiling: drivers/sensors/analog_joystick.c                                                       drivers/sensors/analog_joystick.c: In function 'axisToMouseComponent':
drivers/sensors/analog_joystick.c:67:44: error: implicit declaration of function 'abs' [-Werror=implicit-function-declaration]
         return percent * maxCursorSpeed * (abs(coordinate) / speedRegulator);
                                            ^~~
drivers/sensors/analog_joystick.c: In function 'analog_joystick_read':
drivers/sensors/analog_joystick.c:76:9: error: implicit declaration of function 'timer_elapsed' [-Werror=implicit-function-declaration]
     if (timer_elapsed(lastCursor) > ANALOG_JOYSTICK_READ_INTERVAL) {
         ^~~~~~~~~~~~~
drivers/sensors/analog_joystick.c:77:22: error: implicit declaration of function 'timer_read'; did you mean 'adc_read'? [-Werror=implicit-function-declaration]
         lastCursor = timer_read();
                      ^~~~~~~~~~
                      adc_read
cc1.exe: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:457: .build/obj_kb_default/drivers/sensors/analog_joystick.o] Error 1
```

Although including `stdlib.h` and `timer.h` can solve the above problem, I'm not sure if this is a reasonable architecture.

And I found a lot of files that include `analog.h`. I'm not sure if there are other problems in other cases.

2022-02-22 06:34 UTC, fauxpark commented on quantum/pointing_device.h
> +void           pointing_device_set_report(report_mouse_t report);
Needs to be changed in the .c file too.

2022-02-27 01:38 UTC, drashna commented
Could the docs be updated? 

Also, linter wants changes.

2022-02-28 13:33 UTC, ziteh commented
Sorry, I'm not sure what "Docs" actually means

And lint, which seems to be something related to CI ?

2022-02-28 13:36 UTC, fauxpark commented
The lint error can be ignored. And docs refers to...the docs.

2022-03-01 03:18 UTC, ziteh commented
Oh, I forgot that there is also a function list in the docs,
I think this is what you are talking about

2022-03-07 06:52 UTC, drashna commented on docs/feature_pointing_device.md
> +* `pointing_device_set_report(report_mouse_t mous_report)` - Overrides and saves the report_mouse_t to be sent to the host computer
```suggestion
* `pointing_device_set_report(report_mouse_t mouse_report)` - Overrides and saves the report_mouse_t to be sent to the host computer
```

2022-03-08 03:01 UTC, drashna approved these changes

2022-03-08 03:02 UTC, fauxpark approved these changes

2022-03-08 04:16 UTC, merged