add baguette66 keyboard
qmk/qmk_firmware pull request #16429
Opened 2022-02-22 03:33 UTC by moyi4681

reopen https://github.com/qmk/qmk_firmware/pull/15933

[[[

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
](https://github.com/qmk/qmk_firmware/pull/15933)](https://github.com/qmk/qmk_firmware/pull/15933)](https://github.com/qmk/qmk_firmware/pull/15933)

2022-02-27 01:41 UTC, drashna approved these changes

2022-04-14 02:39 UTC, moyi4681 commented
can you guys check and approve this pull request again,  thanks @drashna

2022-04-14 03:28 UTC, fauxpark requested changes

2022-04-14 03:28 UTC, fauxpark commented on keyboards/kbdfans/baguette66/soldered/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-14 03:28 UTC, fauxpark commented on keyboards/kbdfans/baguette66/soldered/config.h
> +#define USB_SUSPEND_WAKEUP_DELAY 5000
Is this needed?

2022-04-14 03:28 UTC, fauxpark commented on keyboards/kbdfans/baguette66/rgb/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-14 03:28 UTC, fauxpark commented on keyboards/kbdfans/baguette66/rgb/config.h
> +#define USB_SUSPEND_WAKEUP_DELAY 5000
As above.

2022-07-02 10:53 UTC, tzarc approved these changes

2022-07-02 10:54 UTC, merged