add phase one keyboard
qmk/qmk_firmware pull request #16430
Opened 2022-02-22 03:34 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-27 01:42 UTC, drashna approved these changes

2022-02-27 09:13 UTC, fauxpark requested changes

2022-02-27 18:41 UTC, fauxpark requested changes

2022-02-27 18:41 UTC, fauxpark commented on keyboards/kbdfans/phaseone/rules.mk
> +RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```suggestion
```

2022-02-27 18:41 UTC, fauxpark commented on keyboards/kbdfans/phaseone/phaseone.c
> +    setPinOutput(D4);
What is this for?

2022-02-28 07:45 UTC, moyi4681 commented on keyboards/kbdfans/phaseone/phaseone.c
> +    setPinOutput(D4);
D4 connect to one LED that always on

2022-04-14 02:40 UTC, moyi4681 commented
can you guys check and approve this pull request again, thanks @fauxpark @drashna

2022-04-15 15:06 UTC, fauxpark approved these changes

2022-04-16 18:28 UTC, merged

2022-04-16 18:28 UTC, drashna commented
Thanks!