Add toinux's crkbd keymap and userspace
qmk/qmk_firmware pull request #16437
Opened 2022-02-23 00:15 UTC by toinux

## Description

* OLED : 
  * Custom font with graphics already 90° oriented (don't need OLED_ROTATION_90 or OLED_ROTATION_270)
  * Graphic modifier indicator ⌘ ⇧ ⌥ ⌃ (inspired by [soundmonster](https://github.com/qmk/qmk_firmware/tree/master/keyboards/crkbd/keymaps/soundmonster))
  * Graphic layers as small icon on top
  * Led indicators on bottom
  * No keylogger, but display position of last pressed key to test switches.
* Keymap :
  * Optimized for [qwerty-fr](http://marin.jb.free.fr/qwerty-fr) with a layer dedicated to accents. This layer uses specific keymap in userspace.
  * Keypad layer with auto-enable numlock
  * Mouse layer
  * 2 gaming layers
* RGB : 
  * Lights specific to layers and CAPSLOCK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-27 02:01 UTC, drashna requested changes

2022-02-28 17:28 UTC, toinux commented on keyboards/crkbd/keymaps/toinux/oled.c
> +  snprintf(keylog_str, sizeof(keylog_str), "%dx%d", record->event.key.row, record->event.key.col);
Good point, thank you !

2022-02-28 17:39 UTC, drashna approved these changes

2022-04-16 18:26 UTC, drashna commented
Go away stale bot. for now.

2022-04-22 07:41 UTC, tzarc approved these changes

2022-04-22 07:41 UTC, merged