Update DogTag Macro Pad
qmk/qmk_firmware pull request #16446
Opened 2022-02-25 11:19 UTC by takashicompany

## Description

Update matrix, and keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-25 11:20 UTC, takashicompany commented
1st PR : https://github.com/qmk/qmk_firmware/pull/15259

2022-02-27 02:29 UTC, drashna requested changes

2022-02-27 02:29 UTC, drashna commented on keyboards/takashicompany/dogtag/config.h
> +#define MATRIX_ROWS 3 * 2
```suggestion
#define MATRIX_ROWS 6
```

2022-03-07 03:43 UTC, drashna approved these changes

2022-03-07 04:25 UTC, fauxpark approved these changes

2022-03-07 07:02 UTC, merged

2022-03-07 07:02 UTC, drashna commented
thanks!