[Keyboard] BM68HSRGB/rev2
qmk/qmk_firmware pull request #16454
Opened 2022-02-26 14:35 UTC by peepeetee

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-27 02:34 UTC, drashna requested changes

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/config.h
> +
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/config.h
> +#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
Deprecated. 

Please use the enable defines.

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/rev2.c
> +
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/rev2.h
> +
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/rules.mk
> +BOOTMAGIC_ENABLE = lite        # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-02-27 02:34 UTC, drashna commented on keyboards/kprepublic/bm68hsrgb/rev2/rules.mk
> +BLUETOOTH_ENABLE = no          # Enable Bluetooth
```suggestion
NKRO_ENABLE = yes              # Enable N-Key Rollover
BACKLIGHT_ENABLE = no          # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes          # Enable keyboard RGB underglow
```

2022-03-07 03:52 UTC, drashna approved these changes

2022-03-07 04:42 UTC, fauxpark requested changes

2022-03-07 04:42 UTC, fauxpark commented on keyboards/kprepublic/bm68hsrgb/rev2/rules.mk
> +RGB_MATRIX_ENABLE = yes        # Use RGB matrix
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
RGB_MATRIX_ENABLE = yes
```

2022-03-07 04:42 UTC, fauxpark commented on keyboards/kprepublic/bm68hsrgb/rev2/keymaps/via/keymap.c
> +    RMDV
```suggestion
    RM_TOGG = SAFE_RANGE,
    RM_MOD,
    RM_HUI,
    RM_HUD,
    RM_SAI,
    RM_SAD,
    RM_VAI,
    RM_VAD
```

2022-03-07 04:42 UTC, fauxpark commented on keyboards/kprepublic/bm68hsrgb/rev2/keymaps/via/keymap.c
> +      case RMDV:
```suggestion
    case RM_TOGG:
      if (record->event.pressed)
      {rgb_matrix_toggle();
      }
      return false;
    case RM_MOD:
      if (record->event.pressed)
      {rgb_matrix_step();
      }
      return false;
      case RM_HUI:
      if (record->event.pressed)
      {rgb_matrix_increase_hue();
      }
      return false;
      case RM_HUD:
      if (record->event.pressed)
      {rgb_matrix_decrease_hue();
      }
      return false;
      case RM_SAI:
      if (record->event.pressed)
      {rgb_matrix_increase_sat();
      }
      return false;
      case RM_SAD:
      if (record->event.pressed)
      {rgb_matrix_decrease_sat();
      }
      return false;
      case RM_VAI:
      if (record->event.pressed)
      {rgb_matrix_increase_val();
      }
      return false;
      case RM_VAD:
```

2022-03-07 04:42 UTC, fauxpark commented on keyboards/kprepublic/bm68hsrgb/rev2/keymaps/via/keymap.c
> +        KC_CAPS,        RMT,     RMS,     RMIH,    RMDH,    RMIS,    RMDS,    RMIV,    RMDV,    _______, _______,  _______,         _______, _______,
```suggestion
        KC_CAPS,        RM_TOGG, RM_MOD,  RM_HUI,  RM_HUD,  RM_SAI,  RM_SAD,  RM_VAI,  RM_VAD,  _______, _______,  _______,         _______, _______,
```

2022-03-07 05:45 UTC, fauxpark approved these changes

2022-03-07 07:02 UTC, merged