add custom keymap
qmk/qmk_firmware pull request #16453
Opened 2022-02-26 14:15 UTC by mly32

## Description

Added a custom layout for GMMK Pro with a custom RGB matrix effect. Details in `readme.md`.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-27 02:31 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/mly32/keymap.c
> +    return true;
```suggestion
    return false;
```

2022-02-27 03:32 UTC, mly32 commented
Nice catch. Thank you.

2022-02-27 04:06 UTC, drashna approved these changes

2022-04-16 02:19 UTC, mly32 commented
^ bump.

2022-04-17 12:45 UTC, fauxpark requested changes

2022-04-17 12:45 UTC, fauxpark commented on keyboards/gmmk/pro/ansi/keymaps/mly32/keymap.c
> +#include "binds.c"
Don't include .c files in other .c files. Put the keymap array in this file.

2022-08-28 02:18 UTC, closed without merging