Add nt210 config to QMK
qmk/qmk_firmware pull request #16461
Opened 2022-02-27 06:06 UTC by evyd13

## Description

Adds the nt210, a custom PCB for the Leopold FC210TP, to QMK.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-02-27 10:59 UTC, zvecr requested changes

2022-02-27 10:59 UTC, zvecr commented on keyboards/evyd13/nt210/readme.md
> +*A short description of the keyboard/project*
```suggestion
A custom PCB for the Leopold FC210TP.
```

Or something.

2022-02-27 10:59 UTC, zvecr commented on keyboards/evyd13/nt210/readme.md
> +    make nt210:default:flash
```suggestion
    make evyd13/nt210:default

Flashing example for this keyboard:

    make evyd13/nt210:default:flash
```

2022-03-05 20:40 UTC, ikbenkous commented
When using the `default` keymap, `BOOTMAGIC_ENABLE` is not `yes` and thus 'bootmagic lite' is not compiled in. This seems to effectively disable the "press ESC for bootloader during power up" functionality.

Putting `BOOTMAGIC_ENABLE = yes` in the global rules.mk seems to fix it.

2022-03-05 20:56 UTC, zvecr requested changes

2022-03-05 20:56 UTC, zvecr commented on keyboards/evyd13/nt210/info.json
> +        "bootmagic_lite": true,
```suggestion
        "bootmagic": true,
```

2022-03-07 04:03 UTC, drashna approved these changes

2022-03-23 18:24 UTC, evyd13 commented
🥺🙏

2022-03-23 19:30 UTC, fauxpark requested changes

2022-03-24 03:52 UTC, fauxpark approved these changes

2022-03-26 01:06 UTC, merged

2022-03-26 01:06 UTC, drashna commented
Thanks!