Fix yandrstudio/zhou65
qmk/qmk_firmware pull request #16589
Opened 2022-03-08 22:29 UTC by waffle87

## Description

`RGBLED_NUM` is never defined, causing compilation errors when `RGBLIGHT` is enabled. I've disabled it for the time being until @[jiaxin96](https://github.com/jiaxin96) can provide the correct number of LEDs to be defined.
Also some misc cleanup. 

## Types of Changes

- [x] Bugfix
- [x] Keyboard (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-08 22:32 UTC, zvecr requested changes
`keyboards/yandrstudio/zhou65/rules.mk` needs `DEFAULT_FOLDER = yandrstudio/zhou65/f401` (or that folder squashed down so it doesnt exist).

2022-03-08 22:49 UTC, zvecr approved these changes

2022-03-09 00:04 UTC, fauxpark approved these changes

2022-03-09 00:37 UTC, zvecr approved these changes

2022-03-09 00:37 UTC, merged