Support for Jels60
qmk/qmk_firmware pull request #16605
Opened 2022-03-10 06:57 UTC by Jels02

Add Jels60

## Description

Add support for Jels60 PCB

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-10 07:10 UTC, fauxpark requested changes

2022-03-10 07:10 UTC, fauxpark commented on keyboards/jels/jels60/rules.mk
> +# Bootloader
```suggestion

# Bootloader selection
```

2022-03-10 07:10 UTC, fauxpark commented on keyboards/jels/jels60/rules.mk
> +BOOTMAGIC_ENABLE = yes      # Enable Bootmagic
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-03-10 07:10 UTC, fauxpark commented on keyboards/jels/jels60/keymaps/via/keymap.c
> +
```suggestion
```

2022-03-10 07:10 UTC, fauxpark commented on keyboards/jels/jels60/keymaps/default/keymap.c
> +
```suggestion
```

2022-03-10 07:10 UTC, fauxpark commented on keyboards/jels/jels60/jels60.c
> +
```suggestion
#include "jels60.h"
```

2022-03-10 07:10 UTC, fauxpark commented on keyboards/jels/jels60/config.h
> +#define VENDOR_ID       0x006a    //Jels (J)
```suggestion
#define VENDOR_ID       0x006A    //Jels (J)
```

2022-03-10 07:56 UTC, fauxpark approved these changes

2022-03-10 18:19 UTC, drashna requested changes

2022-03-10 18:19 UTC, drashna commented on keyboards/jels/jels60/jels60.c
> +#include "jels60.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-03-10 18:19 UTC, drashna commented on keyboards/jels/jels60/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-03-10 18:19 UTC, drashna commented on keyboards/jels/jels60/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-03-13 07:15 UTC, drashna commented on keyboards/jels/jels60/config.h
> +
These are the defaults, so don't really need to be defined
```suggestion
```

2022-03-13 07:15 UTC, drashna commented on keyboards/jels/jels60/readme.md
> +![jels60](https://i.imgur.com/3Ec4YZN.png)
```suggestion
![jels60](https://i.imgur.com/3Ec4YZNh.png)
```

2022-03-13 17:30 UTC, drashna approved these changes

2022-03-13 17:30 UTC, merged