Add frameworking for development board presets
qmk/qmk_firmware pull request #16637
Opened 2022-03-13 20:05 UTC by zvecr

## Description

Cherry picked whats ready to go from https://github.com/qmk/qmk_firmware/pull/16598.

This PR aims to...
* Provide context for later conversion logic to key against

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-18 22:09 UTC, KarlK90 commented
Development board is ubiquitous but I would prefer `controller` in QMK, `preset` is to generic in my opinion.

2022-03-18 22:10 UTC, KarlK90 approved these changes

2022-03-25 19:44 UTC, Erovia commented on lib/python/qmk/info.py
> +                info_data[key] = value
```suggestion
                if key not in info_data:
                    info_data[key] = value
```

We probably don't want to overwrite the data from the `info.json` with the defaults.

2022-03-25 19:50 UTC, Erovia commented
> Development board is ubiquitous but I would prefer `controller` in QMK, `preset` is to generic in my opinion.

I'm torn between `controller` and `development_board`. For some reason I prefer the latter, but wouldn't mind either, tbh.

2022-04-03 17:30 UTC, tzarc requested changes

2022-04-03 17:30 UTC, tzarc commented on lib/python/qmk/info.py
> +    """Proccess any additional defaults based on currently discovered infomation
```suggestion
    """Process any additional defaults based on currently discovered information
```

2022-04-03 17:31 UTC, tzarc approved these changes

2022-04-03 17:45 UTC, merged