Add initial support for the Makey Makey Classic
qmk/qmk_firmware pull request #16658
Opened 2022-03-15 05:47 UTC by Jpe230

## Description

This PR aims to add support for the Makey Makey Classic (atmega32u4).  The "object" sensing still works, so banana-macropad powered by QMK can be achieved. I have tested QMK on the Makey Makey with several fruits with great success. 

Debounce can be fine-tuned but at least with bananas and apples it appears that the debounce is in a sweet spot.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-15 09:41 UTC, drashna approved these changes

2022-03-15 10:36 UTC, dexter93 requested changes
I am pretty sure potato support is required for QMK Configurator support. Please verify potato compatibility and provide the appropriate keymap for it.

2022-03-15 18:08 UTC, Jpe230 commented
> I am pretty sure potato support is required for QMK Configurator functionality. Please verify potato compatibility and provide the appropriate keymap for it.

@dexter93 Thanks for the suggestion, I had to go to the supermarket to buy a potato to ensure compatibility, luckily they have stock so no need to enter a group buy! 

I attached some evidence: ![image](https://user-images.githubusercontent.com/6202305/158443431-6030b78b-f8b7-4d44-8f4f-1995b6b06ab5.jpeg)

2022-03-15 22:52 UTC, dexter93 approved these changes

2022-04-19 10:51 UTC, tzarc approved these changes

2022-04-19 10:53 UTC, merged