Added Mino Hotswap PCB
qmk/qmk_firmware pull request #16664
Opened 2022-03-16 01:00 UTC by CheeseL0ver

## Description
Add QMK support for Mino Hotswap PCB with default and VIA keymaps. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-18 00:18 UTC, drashna requested changes

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/hotswap/config.h
> +#define NO_ACTION_FUNCTION
deprecated 
```suggestion
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/hotswap/info.json
> +    "height": 4,
```suggestion
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/hotswap/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/hotswap/rules.mk
> +BOOTMAGIC_ENABLE = no     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/keymaps/default/keymap.c
> +#include <stdio.h>
```suggestion
#include QMK_KEYBOARD_H
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/keymaps/via/keymap.c
> +#include <stdio.h>
```suggestion
#include QMK_KEYBOARD_H
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/readme.md
> +![Mino](https://i.imgur.com/f5kHu8Q.jpg)
```suggestion
![Mino](https://i.imgur.com/f5kHu8Qh.jpg)
```

2022-03-18 00:18 UTC, drashna commented on keyboards/mino/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-03-18 17:26 UTC, drashna requested changes

2022-03-18 17:26 UTC, drashna commented on keyboards/mino/keymaps/default/keymap.c
> +// #include <stdio.h>
```suggestion
```

2022-03-18 17:26 UTC, drashna commented on keyboards/mino/keymaps/default/keymap.c
> +char wpm_str[10];
```suggestion
```

2022-03-18 17:26 UTC, drashna commented on keyboards/mino/keymaps/via/keymap.c
> +char wpm_str[10];
```suggestion
```

2022-03-18 17:26 UTC, drashna commented on keyboards/mino/mino.h
> +#include "hotswap.h"
```suggestion
#ifdef KEYBOARD_mino_hotswap
#    include "hotswap.h"
#endif
```

2022-03-20 19:21 UTC, drashna approved these changes

2022-03-21 09:35 UTC, fauxpark requested changes

2022-03-21 09:35 UTC, fauxpark commented on keyboards/mino/hotswap/rules.mk
> +BOOTLOADER = caterina #Make sure you change this if you are not using the kit Pro Micro
```suggestion
BOOTLOADER = caterina
```

2022-03-21 09:35 UTC, fauxpark commented on keyboards/mino/hotswap/rules.mk
> +WPM_ENABLE = yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
OLED_ENABLE = yes
WPM_ENABLE = yes
```

2022-03-26 00:53 UTC, drashna approved these changes

2022-03-26 07:13 UTC, fauxpark approved these changes

2022-03-27 02:02 UTC, merged

2022-03-27 02:03 UTC, drashna commented
Thanks!