Add Krush65 Hotswap
qmk/qmk_firmware pull request #16692
Opened 2022-03-19 16:54 UTC by MaiTheSan

Add support for Krush65 Hotswap PCB

## Description

Add sawnsprojects/krush/krush65/hotswap keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-20 19:08 UTC, drashna commented
Could you move the encoder action stuff to the via keymap, only?

2022-03-29 02:30 UTC, MaiTheSan commented
> Could you move the encoder action stuff to the via keymap, only?

ofc :>

2022-04-13 06:32 UTC, drashna requested changes

2022-04-13 06:32 UTC, drashna commented on keyboards/sawnsprojects/krush/krush65/hotswap/rules.mk
> +SRC +=  encoder_actions.c
```suggestion
```

2022-04-13 06:32 UTC, drashna commented on keyboards/sawnsprojects/krush/krush65/hotswap/keymaps/via/rules.mk
> +LTO_ENABLE = yes
```suggestion
LTO_ENABLE = yes

```suggestion
# Added encoder Action
SRC +=  encoder_actions.c
```
```

2022-04-13 06:32 UTC, drashna commented on keyboards/sawnsprojects/krush/krush65/hotswap/hotswap.c
> +};
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2022-04-13 06:32 UTC, drashna commented on keyboards/sawnsprojects/krush/krush65/hotswap/keymaps/via/keymap.c
> +};
```suggestion
};

void matrix_scan_user(void) {
    encoder_action_unregister();
}

bool encoder_update_user(uint8_t index, bool clockwise) {
    encoder_action_register(index, clockwise);
    return false; // override kb default behavior
};
```

2022-04-15 15:12 UTC, fauxpark requested changes

2022-04-15 15:12 UTC, fauxpark commented on keyboards/sawnsprojects/krush/krush65/hotswap/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
```suggestion
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-04-15 15:12 UTC, fauxpark commented on keyboards/sawnsprojects/krush/krush65/hotswap/readme.md
> +![Krush65](https://imgur.com/56ZvWUm.jpg)
```suggestion
![Krush65](https://imgur.com/56ZvWUmh.jpg)
```

2022-04-24 00:53 UTC, drashna requested changes

2022-04-24 00:53 UTC, drashna commented on keyboards/sawnsprojects/krush/krush65/hotswap/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-04-28 18:19 UTC, drashna approved these changes

2022-04-28 23:25 UTC, fauxpark requested changes

2022-04-28 23:25 UTC, fauxpark commented on keyboards/sawnsprojects/krush/krush65/hotswap/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
```

2022-04-28 23:25 UTC, fauxpark commented on keyboards/sawnsprojects/krush/krush65/hotswap/readme.md
> +    make sawnsprojects/krush65/Hotswap:default
```suggestion
    make sawnsprojects/krush65/hotswap:default
```

2022-07-13 22:18 UTC, noroadsleft requested changes

2022-07-13 22:18 UTC, noroadsleft commented on keyboards/sawnsprojects/krush/krush65/hotswap/info.json
> +                { "label": "", "x": 15, "y": 0.75 },
```suggestion
                { "label": "", "x": 0, "y": 0.75 },
                { "label": "", "x": 1, "y": 0.75 },
                { "label": "", "x": 2, "y": 0.75 },
                { "label": "", "x": 3, "y": 0.75 },
                { "label": "", "x": 4, "y": 0.75 },
                { "label": "", "x": 5, "y": 0.75 },
                { "label": "", "x": 6, "y": 0.75 },
                { "label": "", "x": 7, "y": 0.75 },
                { "label": "", "x": 8, "y": 0.75 },
                { "label": "", "x": 9, "y": 0.75 },
                { "label": "", "x": 10, "y": 0.75 },
                { "label": "", "x": 11, "y": 0.75 },
                { "label": "", "x": 12, "y": 0.75 },
                { "label": "", "x": 13, "y": 0.75 },
                { "label": "", "x": 14, "y": 0.75 },
                { "label": "", "x": 15, "y": 0.75 },
                { "label": "", "x": 14.75, "y": 0, "w": 0.75, "h": 0.75 },
                { "label": "", "x": 15.5, "y": 0, "w": 0.75, "h": 0.75 },
```

2022-07-13 22:18 UTC, noroadsleft commented on keyboards/sawnsprojects/krush/krush65/hotswap/info.json
> +    "maintainer": "Mai The San",
This field is meant to reference your GitHub username.

```suggestion
    "maintainer": "MaiTheSan",
```

2022-07-13 22:18 UTC, noroadsleft commented on keyboards/sawnsprojects/krush/krush65/hotswap/readme.md
> +* Hardware Availability: [Facebook](https://mechkey.store/products/krush-65-hotswap-pcb)
```suggestion
* Hardware Availability: [mechkey.store](https://mechkey.store/products/krush-65-hotswap-pcb)
```

2022-07-13 22:18 UTC, noroadsleft commented on keyboards/sawnsprojects/krush/krush65/hotswap/readme.md
> +    make sawnsprojects/krush65/hotswap:default
```suggestion
    make sawnsprojects/krush/krush65/hotswap:default
```

2022-07-22 03:41 UTC, noroadsleft approved these changes

2022-07-22 03:42 UTC, merged

2022-07-22 03:42 UTC, noroadsleft commented
Thanks!