add via support for creatkeebs/thera
qmk/qmk_firmware pull request #16719
Opened 2022-03-23 21:50 UTC by jdenyc

Thera missing VIA support

## Description

Added creatkeebs/thera/keymaps/via and friends
fix keyboard_name in info.json

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-12 15:24 UTC, take commented
@jdenyc this PR didn't work for my envrionemnt somehow 🤔 are there any tips?

2022-06-12 18:44 UTC, drashna requested changes

2022-06-12 18:44 UTC, drashna commented on keyboards/creatkeebs/thera/keymaps/via/keymap.c
> +#include "../default/keymap.c"
Do not do this. 

Please include a full keymap.

2022-06-13 01:08 UTC, take commented
> @jdenyc this PR didn't work(via couldn't recognize the keyboard) for my envrionemnt somehow 🤔 are there any tips?

Got it working after reading the following keymap file in VIA

```
{
	"name": "thera-via",
	"vendorId": "0xFEED",
	"productId": "0x6060",
	"lighting": "none",
	"matrix": {
		"rows": 6,
		"cols": 15
	},
	"layouts": {
		"labels": [
			"Split Backspace",
      		"ISO Enter",
      		"Split Left Shift",
			["Bottom Row", "6.25U-1", "6.25U-2","7U"]
		],
		"keymap": [
			[
				"0,0",{"x": 0.25},"0,1","0,2","0,3","0,4",{"x": 0.25},"0,5","0,6","0,7","0,8",
                    {"x": 0.25},"0,9","0,10","0,11","0,12",{"x": 0.25},"0,13"
			],
            [
				{"y": 0.5},"1,0","1,1","1,2","1,3","1,4","1,5","1,6","1,7","1,8","1,9","1,10","1,11","1,12",
                    {"w": 2},"1,13\n\n\n0,0","0,14\n\n\n0,1","1,13\n\n\n0,1",{"x": -1.5},"1,14"
			],
			[
				{"w":1.5},"2,0","2,1","2,2","2,3","2,4","2,5","2,6","2,7","2,8","2,9","2,10","2,11","2,12",
				{"w": 1.5},"2,13\n\n\n1,0",{"x":0.25,"w":1.25,"h":2,"w2":1.5,"h2":1,"x2":-0.25},"3,13\n\n\n1,1",
                {"x": -1},"2,14"
			],
			[
				{"w": 1.75},"3,0","3,1","3,2","3,3","3,4","3,5","3,6","3,7","3,8","3,9","3,10","3,11",
                {"w": 2.25},"3,13\n\n\n1,0",{"x": -0.75},"2,13\n\n\n1,1",{"x": 0.25},"3,14"
			],
			[
				{"w": 2.25},"4,0\n\n\n2,0",{"w": 1.25},"4,0\n\n\n2,1","4,1\n\n\n2,1",
                {"x": -2.25},"4,2","4,3","4,4","4,5","4,6","4,7","4,8","4,9","4,10","4,11",
                {"w": 1.75},"4,12", {"x": 0.25,"y":0.25},"4,13"
			],
			[
				{"w": 1.25,"y":-0.25},"5,0\n\n\n3,0",{"w": 1.25},"5,1\n\n\n3,0",{"w": 1.25},"5,2\n\n\n3,0",
                {"w": 6.25},"5,6\n\n\n3,0","5,9\n\n\n3,0","5,10\n\n\n3,0","5,11\n\n\n3,0",
                    {"w": 1.25},"5,0\n\n\n3,1",{"w": 1.25},"5,1\n\n\n3,1",{"w": 1.25},"5,2\n\n\n3,1",
                    {"w": 6.25},"5,6\n\n\n3,1",{"w": 1.5},"5,9\n\n\n3,1",{"w": 1.5},"5,11\n\n\n3,1",
                        {"w": 1.25},"5,0\n\n\n3,2","5,1\n\n\n3,2",{"w": 1.25},"5,2\n\n\n3,2",
                        {"w": 7},"5,6\n\n\n3,2",{"w": 1.25},"5,9\n\n\n3,2",{"w": 1.25},"5,11\n\n\n3,2",
            {"x": -25.75,"y":0.25},"5,12","5,13","5,14"
			]
		]

	}
}
```

2022-09-13 02:19 UTC, closed without merging