add tiger80 keyboard
qmk/qmk_firmware pull request #16742
Opened 2022-03-28 01:20 UTC by moyi4681

add tiger80 keyboard

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-29 05:26 UTC, drashna requested changes

2022-03-29 05:26 UTC, drashna commented on keyboards/kbdfans/tiger80/config.h
> +
Deprecated features, no longer needed. 
```suggestion
```

2022-03-29 05:26 UTC, drashna commented on keyboards/kbdfans/tiger80/keymaps/default/keymap.c
> +    )
```suggestion
```

2022-04-13 06:41 UTC, drashna approved these changes

2022-04-13 10:26 UTC, fauxpark approved these changes

2022-04-13 14:24 UTC, merged

2022-04-13 14:25 UTC, drashna commented
Thanks!