Add scrolling and caps lock bootloader mode to Ploopy nano
qmk/qmk_firmware pull request #16746
Opened 2022-03-28 19:45 UTC by squk

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-29 02:35 UTC, drashna commented
You have some merge conflicts that need to be addressed here.

2022-03-29 23:06 UTC, squk commented
> You have some merge conflicts that need to be addressed here.

Resolved.

2022-07-12 22:50 UTC, squk commented
Bump :)

2022-07-13 04:53 UTC, drashna requested changes

2022-07-15 14:55 UTC, squk commented on keyboards/ploopyco/trackball_nano/trackball_nano.c
> +__attribute__((weak)) void process_mouse(report_mouse_t* mouse_report) {
GitHub is only showing 4 lines selected. Could you give me the line numbers :)

2022-09-30 02:18 UTC, closed without merging