Added via keymap
qmk/qmk_firmware pull request #16747
Opened 2022-03-29 12:26 UTC by Timliuzhaolu

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-29 14:21 UTC, zvecr requested changes

2022-03-29 14:21 UTC, zvecr commented on keyboards/creatkeebs/glacier/keymaps/via/rules.mk
> +LAYOUTS = tkl_f13_ansi_tsangan
```suggestion
VIA_ENABLE = yes
```

2022-04-13 06:47 UTC, drashna approved these changes

2022-04-13 10:24 UTC, fauxpark approved these changes

2022-04-14 17:01 UTC, merged

2022-04-14 17:01 UTC, drashna commented
Thanks!