Stm32f4 uF2 prompt the problem of insufficient EEPROM
qmk/qmk_firmware pull request #16750
Opened 2022-03-30 03:31 UTC by swkidden

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-30 18:58 UTC, zvecr requested changes
Also <https://github.com/qmk/qmk_firmware/pull/16287#discussion_r822234320> and #16586 for why this change isnt enough on its own.

2022-03-30 18:58 UTC, zvecr commented on platforms/chibios/eeprom_stm32_defs.h
> +#            define FEE_PAGE_SIZE 0x4000// Page size = 16KByte
```suggestion
#            define FEE_PAGE_SIZE 0x4000 // Page size = 16KByte
```

2022-03-30 18:58 UTC, zvecr commented on builddefs/common_features.mk
> +      ifneq ($(filter STM32F3xx_% STM32F1xx_% %_STM32F401xC%_STM32F401xC_tinyuf2 % %_STM32F401xE %_STM32F405xG %_STM32F411xE %_STM32F411xE_tinyuf2 %_STM32F072xB %_STM32F042x6 %_GD32VF103xB %_GD32VF10
```suggestion
      ifneq ($(filter STM32F3xx_% STM32F1xx_% %_STM32F401xC %_STM32F401xC_tinyuf2 %_STM32F401xE %_STM32F405xG %_STM32F411xE %_STM32F411xE_tinyuf2 %_STM32F072xB %_STM32F042x6 %_GD32VF103xB %_GD32VF103x8, $(MCU_SERIES)_$(MCU_LDSCRIPT)),)
```

2022-03-31 10:58 UTC, sigprof requested changes
The changes that are done here are incomplete — you also need to change `FEE_PAGE_BASE_ADDRESS` (the default value used on F4x1 would leave only  16 KiB for the bootloader, which is apparently not enough). From https://github.com/qmk/qmk_firmware/pull/16287#discussion_r822234320 it seems that the flash portion reserved for the bootloader code is 32 KiB, and sectors 2 and 3 can be used for EEPROM.

2022-08-14 17:56 UTC, zvecr commented
Superseded by #18042

2022-08-14 17:56 UTC, closed without merging