kin80
qmk/qmk_firmware pull request #16754
Opened 2022-03-30 11:48 UTC by DmNosachev

Kin80 — controller for modded Kinesis Contoured keyboards ([PCB](https://github.com/DmNosachev/kin80))

This is a duplicate of pull request [16678](https://github.com/qmk/qmk_firmware/pull/16678), which I closed because I couldn't fix problems with submodules.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-13 07:01 UTC, drashna approved these changes

2022-04-19 11:24 UTC, tzarc requested changes

2022-04-19 11:24 UTC, tzarc commented on keyboards/kin80/rules.mk
> +DEFAULT_FOLDER = kinesis80/blackpill401
```suggestion
DEFAULT_FOLDER = kin80/blackpill401
```

2022-04-19 11:30 UTC, tzarc approved these changes

2022-04-19 11:30 UTC, merged