PJB Eros PCB firmware
qmk/qmk_firmware pull request #16756
Opened 2022-03-31 04:15 UTC by 602studios

## Description

Added the base files for the Eros keyboard PCB.

These include:
config.h
eros.c
eros.h
info.json
rules.mk
readme.md
keymaps/default/keymap.c
keymaps/via/config.h
keymaps/via/keymap.c
keymaps/via/rules.mk

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-31 15:01 UTC, fauxpark commented on keyboards/pjb/eros/rules.mk
> +BOOTLOADER = bootloadHID
Is this correct?

2022-03-31 15:01 UTC, fauxpark commented on keyboards/pjb/eros/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
```suggestion
```

2022-03-31 15:01 UTC, fauxpark commented on keyboards/pjb/eros/rules.mk
> +RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```suggestion
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Enable audio output
```

2022-03-31 15:02 UTC, fauxpark commented on keyboards/pjb/eros/rules.mk
> +VIA_ENABLE = yes
```suggestion
```
VIA must not be enabled at keyboard level.

2022-03-31 15:02 UTC, fauxpark commented on keyboards/pjb/eros/info.json
> +	  "LAYOUT_tkl_ansi_f13_Split_Shift": {
Layout macros must be all lowercase after the `LAYOUT_`.

2022-03-31 22:44 UTC, zvecr requested changes

2022-03-31 22:44 UTC, zvecr commented on keyboards/pjb/eros/rules.mk
> +WS2812_DRIVER = i2c
```suggestion
```

2022-04-04 06:34 UTC, 602studios commented
Uploads from 4/3/22 did not change any of the files! They should all be the same version as reviewed.

2022-04-05 00:51 UTC, fauxpark requested changes

2022-04-05 00:51 UTC, fauxpark commented on keyboards/pjb/eros/readme.md
> +Flashing example for this keyboard ([after setting up the bootloadHID flashing environment](https://docs.qmk.fm/#/flashing_bootloadhid))
```suggestion
Flashing example for this keyboard:
```

2022-04-07 05:54 UTC, fauxpark approved these changes

2022-04-07 05:54 UTC, fauxpark commented on keyboards/pjb/eros/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
This is the default, this file can be removed.

2022-04-13 07:04 UTC, merged

2022-04-13 07:04 UTC, drashna commented
Thanks!