Add Vertex user space and AngleR2 keyboard
qmk/qmk_firmware pull request #16764
Opened 2022-04-01 07:47 UTC by Vertex-kb

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-02 09:38 UTC, Vertex-kb commented
The modification has been completed. Please approve.

2022-04-13 07:19 UTC, drashna approved these changes

2022-04-13 10:27 UTC, fauxpark approved these changes

2022-05-15 12:36 UTC, Vertex-kb commented
@fauxpark Hi,bro!Excuse me, maybe it can be merged? Maybe there is something wrong? Thank you very much for taking your precious time

2022-07-14 00:34 UTC, noroadsleft requested changes

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/keymaps/default/keymap.c
> +  [0] = LAYOUT(
```suggestion
  [0] = LAYOUT_all(
```

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/keymaps/default/keymap.c
> +  [1] = LAYOUT(
```suggestion
  [1] = LAYOUT_all(
```

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/keymaps/via/keymap.c
> +  [0] = LAYOUT(
```suggestion
  [0] = LAYOUT_all(
```

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/keymaps/via/keymap.c
> +  [1] = LAYOUT(
```suggestion
  [1] = LAYOUT_all(
```

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/keymaps/via/keymap.c
> +  [2] = LAYOUT(
```suggestion
  [2] = LAYOUT_all(
```

2022-07-14 00:34 UTC, noroadsleft commented on keyboards/vertex/angler2/keymaps/via/keymap.c
> +  [3] = LAYOUT(
```suggestion
  [3] = LAYOUT_all(
```

2022-08-08 09:42 UTC, noroadsleft approved these changes

2022-08-08 09:45 UTC, merged

2022-08-08 09:45 UTC, noroadsleft commented
Thanks!