Update X-Bows Keyboard
qmk/qmk_firmware pull request #16765
Opened 2022-04-01 08:15 UTC by XBowsTech

## Description

Update LTO_ENABLE and VENDOR_ID.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-13 07:20 UTC, drashna requested changes

2022-04-13 07:20 UTC, drashna commented on keyboards/xbows/nature/rules.mk
> +SLEEP_LED_ENABLE = no
```suggestion
```

2022-04-13 07:20 UTC, drashna commented on keyboards/xbows/knight/config.h
> +#define PRODUCT_ID   0x4b6e
```suggestion
#define PRODUCT_ID   0x4B6E
```

2022-04-13 07:20 UTC, drashna commented on keyboards/xbows/knight_plus/config.h
> +#define PRODUCT_ID   0x4b50
```suggestion
#define PRODUCT_ID   0x4B50
```

2022-04-13 07:20 UTC, drashna commented on keyboards/xbows/nature/config.h
> +#define PRODUCT_ID   0x4e61
```suggestion
#define PRODUCT_ID   0x4E61
```

2022-04-13 07:20 UTC, drashna commented on keyboards/xbows/numpad/config.h
> +#define PRODUCT_ID   0x4e75
```suggestion
#define PRODUCT_ID   0x4E75
```

2022-04-14 17:04 UTC, drashna approved these changes

2022-04-15 15:11 UTC, fauxpark approved these changes

2022-04-16 18:19 UTC, merged

2022-04-16 18:19 UTC, drashna commented
Thanks!