Add digicarpice
qmk/qmk_firmware pull request #16791
Opened 2022-04-04 18:12 UTC by swiftrax

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-14 16:29 UTC, drashna commented on keyboards/handwired/swiftrax/digicarpice/keymaps/via/keymap.c
> +    ),
4 is the default, unless specified by a define
```suggestion
```

2022-04-14 16:29 UTC, drashna requested changes

2022-04-14 16:29 UTC, drashna commented on keyboards/handwired/swiftrax/digicarpice/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-04-16 18:15 UTC, drashna approved these changes

2022-04-17 12:27 UTC, fauxpark approved these changes

2022-04-18 09:11 UTC, merged

2022-04-18 09:11 UTC, drashna commented
Thanks!