Added Wait time to sending each Keys for Dynamic Macros function
qmk/qmk_firmware pull request #16800
Opened 2022-04-05 13:56 UTC by FREEWING-JP

## Description

When recording and playing back UI operations in the Dynamic Macros function, the UI may miss keystrokes because the keys are sent too fast. 
This problem can be solved by adding a wait time for each key transmission.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-05 23:10 UTC, zvecr requested changes
Most items in this area are `_DELAY` and not "wait".

2022-04-05 23:10 UTC, zvecr commented on docs/feature_dynamic_macros.md
> +|`DYNAMIC_MACRO_WAIT`        |*Not Defined*   |Sets the waiting time (ms unit) when sending each key.                                                           |
```suggestion
|`DYNAMIC_MACRO_DELAY`        |*Not Defined*   |Sets the waiting time (ms unit) when sending each key.                                                           |
```

2022-04-05 23:10 UTC, zvecr commented on quantum/process_keycode/process_dynamic_macro.c
> +        wait_ms(DYNAMIC_MACRO_WAIT);
```suggestion
#ifdef DYNAMIC_MACRO_DELAY
        wait_ms(DYNAMIC_MACRO_DELAY);
```

2022-04-05 23:10 UTC, zvecr commented on docs/ja/feature_dynamic_macros.md
> +| `DYNAMIC_MACRO_WAIT` | *定義なし* | 各キーを送信する時の待ち時間（ms単位）を設定します。 |
```suggestion
| `DYNAMIC_MACRO_DELAY` | *定義なし* | 各キーを送信する時の待ち時間（ms単位）を設定します。 |
```

2022-04-06 20:47 UTC, zvecr approved these changes

2022-04-06 21:02 UTC, drashna commented
It may be worth having this set to use `TAP_CODE_DELAY` by default, or just use it altogether, rather than a separate define.

2022-04-12 12:29 UTC, FREEWING-JP commented
I traced program .
dynamic_macro_play() -> process_record() -> process_record_handler() -> process_action() .
In process_action() function using TAP_CODE_DELAY .

Looks like It is not appropriate to put delay logic inside the dynamic_macro_play() function .
However, defining TAP_CODE_DELAY affects all process_record()/ process_actions() .

Hmm...

2022-07-02 11:48 UTC, tzarc approved these changes

2022-07-02 11:48 UTC, merged

2022-07-04 15:13 UTC, FREEWING-JP commented
Thank you .