move/rename obro to Meridian RGB
qmk/qmk_firmware pull request #16828
Opened 2022-04-09 20:26 UTC by holtenc

## Description

What used to be a personal project has been produced in mass and made available to the community for the next batch of Meridian keyboard kits. This change moves the firmware from handwired/obro to primekb/meridian_rgb

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-11 15:36 UTC, zvecr requested changes

2022-04-12 12:55 UTC, zvecr requested changes

2022-04-12 12:55 UTC, zvecr commented on .gitignore
> +keyboards/primekb/meridian_rgb/.vscode/c_cpp_properties.json
```suggestion
```

2022-04-13 08:12 UTC, drashna approved these changes

2022-04-13 10:42 UTC, fauxpark approved these changes

2022-04-14 16:26 UTC, merged