Add Axostudio Yeti hotswap version
qmk/qmk_firmware pull request #16820
Opened 2022-04-08 08:20 UTC by kb-elmo

## Description

Adds support for the Yeti hotswap RGB PCB.
The PCB was commission designed by DZtech hence the differenct manufacturer in the config.h.
However it should ideally stay in the Axolstudio directory so that users can find it more easily (both the soldered and hotswap PCB are sold in the same groupbuy under the Axolstudio name).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-08 12:23 UTC, zvecr requested changes

2022-04-08 12:23 UTC, zvecr commented on keyboards/axolstudio/yeti/hotswap/hotswap.c
> +
```suggestion
```

2022-04-08 12:23 UTC, zvecr commented on keyboards/axolstudio/yeti/hotswap/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-08 12:23 UTC, zvecr commented on keyboards/axolstudio/yeti/soldered/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-13 08:10 UTC, drashna approved these changes

2022-04-13 10:39 UTC, fauxpark requested changes

2022-04-13 10:39 UTC, fauxpark commented on keyboards/axolstudio/yeti/hotswap/rules.mk
> +FORCE_NKRO = yes
```suggestion
```

2022-05-04 19:39 UTC, kb-elmo commented
Bump :)

2022-05-05 00:21 UTC, fauxpark approved these changes

2022-05-11 10:13 UTC, merged