Add kprepublic/bm980v2
qmk/qmk_firmware pull request #16837
Opened 2022-04-11 16:02 UTC by bdtc123

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-18 14:30 UTC, bdtc123 commented
@drashna@zvecr@fauxpark excuse me,what should i do?

2022-06-13 06:20 UTC, drashna requested changes

2022-06-13 06:20 UTC, drashna commented on keyboards/kprepublic/bm980v2/config.h
> +#define NO_ACTION_FUNCTION
These features are removed, so they don't need to be disabled.
```suggestion
```

2022-06-13 06:20 UTC, drashna commented on keyboards/kprepublic/bm980v2/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
```

2022-09-14 02:18 UTC, closed without merging