Added the Resume1800 from CrimsonKeyboards
qmk/qmk_firmware pull request #16842
Opened 2022-04-12 14:53 UTC by DeeDesired

Added my custom keyboard, the Resume1800, to the firmware.

## Description
Added my keyboard to the firmware list, with an ISO and ANSI layout.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation
## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x]  I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-13 08:26 UTC, drashna requested changes
The readme file needs to be filled out

2022-04-14 16:00 UTC, drashna requested changes

2022-04-14 16:00 UTC, drashna commented on keyboards/crimsonkeyboards/resume1800/resume1800.h
> +#define LED_CAPS_LOCK	B6
```suggestion
```

2022-04-14 16:00 UTC, drashna commented on keyboards/crimsonkeyboards/resume1800/config.h
> +/* define if matrix has ghost (lacks anti-ghosting diodes) */
```suggestion
#define LED_NUM_LOCK_PIN B5
#define LED_CAPS_LOCK_PIN B6

/* define if matrix has ghost (lacks anti-ghosting diodes) */
```

2022-04-16 17:50 UTC, drashna approved these changes

2022-04-17 12:31 UTC, fauxpark requested changes

2022-04-17 12:31 UTC, fauxpark commented on keyboards/crimsonkeyboards/resume1800/config.h
> +//#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-18 05:52 UTC, fauxpark approved these changes

2022-04-18 09:29 UTC, merged

2022-04-18 09:29 UTC, drashna commented
Thanks!