RM_Numpad: Fix layout bug
qmk/qmk_firmware pull request #16857
Opened 2022-04-16 00:36 UTC by RuckerMachine

## Description

The layout submitted in the original PR included a suggested change by a reviewer that slipped past me, and resulted in an incorrect layout in rm_numpad.h

## Types of Changes

- [X ] Bugfix

## Issues Fixed or Closed by This PR

* rm_numpad layout fixed

## Checklist

- [ X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-16 01:41 UTC, zvecr requested changes
Per `layouts/default/numpad_6x4/default_numpad_6x4/keymap.c`, this fix is incorrect as the community layout expects the 2u keys to be bottom aligned. Keymaps and info.json order should be changed instead.

For example:
```diff
diff --git a/keyboards/rmkeebs/rm_numpad/info.json b/keyboards/rmkeebs/rm_numpad/info.json
index 0f60a8ec06..026eb7ddd2 100644
--- a/keyboards/rmkeebs/rm_numpad/info.json
+++ b/keyboards/rmkeebs/rm_numpad/info.json
@@ -9,28 +9,28 @@
                 {"label": "Prev", "x": 1, "y": 0.25},
                 {"label": "Next", "x": 2, "y": 0.25},
                 {"label": "Mute", "x": 3.5, "y": 0},
-               
+
                 {"label": "Num_Lock", "x": 0, "y": 1.25},
                 {"label": "/", "x": 1, "y": 1.25},
                 {"label": "*", "x": 2, "y": 1.25},
                 {"label": "-", "x": 3, "y": 1.25},
-               
+
                 {"label": "7", "x": 0, "y": 2.25},
                 {"label": "8", "x": 1, "y": 2.25},
                 {"label": "9", "x": 2, "y": 2.25},
-                {"label": "+", "x": 3, "y": 2.25, "h": 2},
-               
+
                 {"label": "4", "x": 0, "y": 3.25},
                 {"label": "5", "x": 1, "y": 3.25},
                 {"label": "6", "x": 2, "y": 3.25},
-               
+                {"label": "+", "x": 3, "y": 2.25, "h": 2},
+
                 {"label": "1", "x": 0, "y": 4.25},
                 {"label": "2", "x": 1, "y": 4.25},
                 {"label": "3", "x": 2, "y": 4.25},
-                {"label": "Enter", "x": 3, "y": 4.25, "h": 2},
-               
+
                 {"label": "0", "x": 0, "y": 5.25, "w": 2},
-                {"label": ".", "x": 2, "y": 5.25}
+                {"label": ".", "x": 2, "y": 5.25},
+                {"label": "Enter", "x": 3, "y": 4.25, "h": 2}
             ]
         },
         "LAYOUT_split_plus_6x4": {
diff --git a/keyboards/rmkeebs/rm_numpad/keymaps/default/keymap.c b/keyboards/rmkeebs/rm_numpad/keymaps/default/keymap.c
index 240442558c..0aa3dd28db 100644
--- a/keyboards/rmkeebs/rm_numpad/keymaps/default/keymap.c
+++ b/keyboards/rmkeebs/rm_numpad/keymaps/default/keymap.c
@@ -22,10 +22,10 @@ const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
     LAYOUT_numpad_6x4(
         KC_MPLY, KC_MPRV, KC_MNXT, KC_MUTE,
         KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, 
-        KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
-        KC_P4,   KC_P5,   KC_P6,    
-        KC_P1,   KC_P2,   KC_P3,   KC_PENT,
-           KC_P0,      KC_PDOT
+        KC_P7,   KC_P8,   KC_P9,
+        KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
+        KC_P1,   KC_P2,   KC_P3,
+        KC_P0,            KC_PDOT, KC_PENT
     )
 
 };
```

2022-04-24 21:10 UTC, jrucker2004 commented
> Per `layouts/default/numpad_6x4/default_numpad_6x4/keymap.c`, this fix is incorrect as the community layout expects the 2u keys to be bottom aligned. Keymaps and info.json order should be changed instead.

Thank you for the explanation and example, the requested changes from the previous PR make more sense now.
I've pushed the changes needed.

2022-04-28 18:10 UTC, drashna approved these changes

2022-04-28 18:40 UTC, zvecr requested changes

2022-04-28 18:40 UTC, zvecr commented on keyboards/rmkeebs/rm_numpad/rm_numpad.h
> +    k51,      k53, k44 \
Not k44 is moved, `LAYOUT_split_plus` in `info.json` will also need updates.

2022-04-28 22:58 UTC, zvecr approved these changes

2022-04-28 23:17 UTC, fauxpark approved these changes

2022-04-29 08:13 UTC, merged