Added new layout for keebio/iris
qmk/qmk_firmware pull request #16858
Opened 2022-04-16 01:37 UTC by elliotpatros

## Description

My personal layout for the keebio/iris. Really simple, only two layers, have been using it for work for several years.

Added keymap.c and config.h to keyboards/keebio/iris/keymaps/emp

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [nearly] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-16 01:49 UTC, zvecr requested changes

2022-04-16 01:49 UTC, zvecr commented on keyboards/keebio/iris/keymaps/emp/config.h
> +
```suggestion
```

2022-04-16 18:01 UTC, drashna requested changes
Also, the formatting bothers me

2022-04-16 18:01 UTC, drashna commented on keyboards/keebio/iris/keymaps/emp/keymap.c
> +{
```suggestion
enum custom_layers {
    _COLEMAK,
    _FUNCTION,
};

// Custom keycodes, implemented later, in function: process_record_user()
enum custom_keycodes {
```

2022-04-18 09:26 UTC, drashna approved these changes

2022-07-15 06:10 UTC, noroadsleft approved these changes

2022-07-15 06:11 UTC, merged

2022-07-15 06:11 UTC, noroadsleft commented
Thanks!