Adding new keyboard: Trkeyboards trk1
qmk/qmk_firmware pull request #16850
Opened 2022-04-13 16:59 UTC by TvrdRadKeyboards

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-14 16:14 UTC, drashna requested changes

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/config.h
> +#define LOCKING_RESYNC_ENABLE
```suggestion
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/default/keymap.c
> +#endif
```suggestion
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/via/keymap.c
> +#include "../default/keymap.c"
Please include the full keymap.

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/readme.md
> +![TRK1](https://i.imgur.com/nTHrBMr.jpg)
```suggestion
![TRK1](https://i.imgur.com/nTHrBMrh.jpg)
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/readme.md
> +*A short description of the keyboard/project*
???

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/rules.mk
> +# OLED - #OLED_DRIVER_ENABLE = yes
```suggestion
```

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/rules.mk
> +endif
This should be moved to `post_rules.mk`

2022-04-14 16:14 UTC, drashna commented on keyboards/trkeyboards/trk1/trk1.c
> +#include "trk1.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "trk1.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2022-04-20 12:34 UTC, vomindoraan commented on keyboards/trkeyboards/trk1/config.h
> +#undef  LOCKING_SUPPORT_ENABLE
Why the removal?

2022-09-14 02:18 UTC, closed without merging