reuploading ano
qmk/qmk_firmware pull request #16885
Opened 2022-04-19 03:58 UTC by sauvehoo

putting ano files to dev_branch

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-20 06:39 UTC, drashna approved these changes

2022-04-20 06:49 UTC, fauxpark requested changes

2022-04-20 06:49 UTC, fauxpark commented on keyboards/ano/config.h
> +//#define NO_ACTION_FUNCTION
```suggestion
```

2022-05-07 04:56 UTC, sauvehoo commented on keyboards/ano/config.h
> +//#define NO_ACTION_FUNCTION
changed to be what was requested.

2022-05-07 05:00 UTC, sauvehoo commented
Is there anyway I can re request a review?

2022-05-11 10:55 UTC, drashna approved these changes

2022-05-11 11:14 UTC, fauxpark approved these changes

2022-05-11 23:39 UTC, merged

2022-05-11 23:40 UTC, drashna commented
Thanks!