gameroyadvance
qmk/qmk_firmware pull request #16882
Opened 2022-04-19 00:58 UTC by ROYMEETSWORLD

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-19 02:45 UTC, drashna requested changes

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/README.md
> +![GRALAYOUTS](https://user-images.githubusercontent.com/63612683/162095125-48746ddd-9b80-4f82-aea0-9a0d02c0e62e.JPG)
Please rehost these images on Imgur, or simular image hosting sit.

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/config.h
> +)
```suggestion
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/config.h
> +#define DEBOUNCING_DELAY 5
```suggestion
#define DEBOUNCE 5
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/config.h
> +#define USB_POLLING_INTERVAL_MS 1
Is the default. 
```suggestion
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/config.h
> +#define PREVENT_STUCK_MODIFIERS
Deprecated a LONG time ago.
```suggestion
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/keymaps/default/keymap.c
> +}
```suggestion
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/gameroyadvance.c
> +#include "gameroyadvance.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "gameroyadvance.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/keymaps/default_all/keymap.c
> +}
```suggestion
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/rules.mk
> +SPLIT_KEYBOARD = yes
```suggestion
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output

ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
```

2022-04-19 02:45 UTC, drashna commented on keyboards/keystonecaps/gameroyadvance/README.md
> +# Game Roy ADVANCE
Pleaes rename this file to be lower case.

2022-04-19 20:43 UTC, ROYMEETSWORLD commented
I believe I made all the changes that you suggested. Thank you again for your time.

2022-04-20 06:38 UTC, drashna approved these changes

2022-04-20 06:48 UTC, fauxpark requested changes

2022-04-20 06:48 UTC, fauxpark commented on keyboards/keystonecaps/gameroyadvance/readme.md
> +![Game Roy ADVANCE](https://i.imgur.com/N6RI4fU.jpg)
```suggestion
![Game Roy ADVANCE](https://i.imgur.com/N6RI4fUh.jpg)
```

2022-04-20 06:48 UTC, fauxpark commented on keyboards/keystonecaps/gameroyadvance/readme.md
> +```
```suggestion
    make keystonecaps/gameroyadvance:default

Flashing example for this keyboard:

    make keystonecaps/gameroyadvance:default:flash
```

2022-04-24 01:13 UTC, drashna approved these changes

2022-05-01 17:41 UTC, ROYMEETSWORLD commented
@fauxpark is there something else you would like me to change?

2022-05-01 17:47 UTC, fauxpark approved these changes

2022-05-01 17:59 UTC, merged

2022-10-11 09:26 UTC, ROYMEETSWORLD commented
Thank you for your time. I'll make those changes as soon as I can.

On Mon, Apr 18, 2022, 10:45 PM Drashna Jaelre ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/README.md
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852546846>:
>
> > +![Game Roy ADVANCE](https://user-images.githubusercontent.com/63612683/162093240-656e8740-f73c-454d-8b30-d60db9da212f.jpg)
>
> +![GRALAYOUTS](https://user-images.githubusercontent.com/63612683/162095125-48746ddd-9b80-4f82-aea0-9a0d02c0e62e.JPG)
>
>
> Please rehost these images on Imgur, or simular image hosting sit.
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/config.h
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852546941>:
>
> > +/* key combination for command */
>
> +#define IS_COMMAND() ( \
>
> +    keyboard_report->mods == (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_RSHIFT)) \
>
> +)
>
>
> ⬇️ Suggested change
>
> -/* key combination for command */
>
> -#define IS_COMMAND() ( \
>
> -    keyboard_report->mods == (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_RSHIFT)) \
>
> -)
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/config.h
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547020>:
>
> > +#define ENCODERS_PAD_B_RIGHT { B2 }
>
> +#define SOFT_SERIAL_PIN D2
>
> +
>
> +#define UNUSED_PINS
>
> +
>
> +/* COL2ROW or ROW2COL */
>
> +#define DIODE_DIRECTION COL2ROW
>
> +
>
> +/* number of backlight levels */
>
> +
>
> +#ifdef BACKLIGHT_PIN
>
> +#define BACKLIGHT_LEVELS 3
>
> +#endif
>
> +
>
> +/* Set 0 if debouncing isn't needed */
>
> +#define DEBOUNCING_DELAY 5
>
>
> ⬇️ Suggested change
>
> -#define DEBOUNCING_DELAY 5
>
> +#define DEBOUNCE 5
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/config.h
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547181>:
>
> > +/* Mechanical locking support. Use KC_LCAP, KC_LNUM or KC_LSCR instead in keymap */
>
> +#define LOCKING_SUPPORT_ENABLE
>
> +
>
> +/* Locking resynchronize hack */
>
> +#define LOCKING_RESYNC_ENABLE
>
> +
>
> +/* key combination for command */
>
> +#define IS_COMMAND() ( \
>
> +    keyboard_report->mods == (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_RSHIFT)) \
>
> +)
>
> +
>
> +/* prevent stuck modifiers */
>
> +#define PREVENT_STUCK_MODIFIERS
>
> +
>
> +/* Change USB Polling Rate to 1000hz and a larger keys per scan for elite gaming*/
>
> +#define USB_POLLING_INTERVAL_MS 1
>
>
> Is the default.
> ⬇️ Suggested change
>
> -#define USB_POLLING_INTERVAL_MS 1
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/config.h
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547242>:
>
> > +/* prevent stuck modifiers */
>
> +#define PREVENT_STUCK_MODIFIERS
>
>
> Deprecated a LONG time ago.
> ⬇️ Suggested change
>
> -/* prevent stuck modifiers */
>
> -#define PREVENT_STUCK_MODIFIERS
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/config.h
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547382>:
>
> > +
>
> +/* key combination for command */
>
> +#define IS_COMMAND() ( \
>
> +    keyboard_report->mods == (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_RSHIFT)) \
>
> +)
>
> +
>
> +/* prevent stuck modifiers */
>
> +#define PREVENT_STUCK_MODIFIERS
>
> +
>
> +/* Change USB Polling Rate to 1000hz and a larger keys per scan for elite gaming*/
>
> +#define USB_POLLING_INTERVAL_MS 1
>
> +#define QMK_KEYS_PER_SCAN 12
>
> +
>
> +#define RGB_DI_PIN C7
>
> +#ifdef RGB_DI_PIN
>
> +#define RGBLIGHT_ANIMATIONS
>
>
> Could you explicitly define which animations are enabled?
> ⬇️ Suggested change
>
> -#define RGBLIGHT_ANIMATIONS
>
> +#define RGBLIGHT_EFFECT_BREATHING
>
> +#define RGBLIGHT_EFFECT_RAINBOW_MOOD
>
> +#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
>
> +#define RGBLIGHT_EFFECT_SNAKE
>
> +#define RGBLIGHT_EFFECT_KNIGHT
>
> +#define RGBLIGHT_EFFECT_CHRISTMAS
>
> +#define RGBLIGHT_EFFECT_STATIC_GRADIENT
>
> +#define RGBLIGHT_EFFECT_RGB_TEST
>
> +#define RGBLIGHT_EFFECT_ALTERNATING
>
> +#define RGBLIGHT_EFFECT_TWINKLE
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/keymaps/default/keymap.c
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547554>:
>
> > +bool encoder_update_user(uint8_t index, bool clockwise) {
>
> +    if (index == 0) { /* First encoder */
>
> +        if (clockwise) {
>
> +            tap_code(KC_VOLD);
>
> +        } else {
>
> +            tap_code(KC_VOLU);
>
> +        }
>
> +    }
>
> +    return false;
>
> +}
>
>
> ⬇️ Suggested change
>
> -bool encoder_update_user(uint8_t index, bool clockwise) {
>
> -    if (index == 0) { /* First encoder */
>
> -        if (clockwise) {
>
> -            tap_code(KC_VOLD);
>
> -        } else {
>
> -            tap_code(KC_VOLU);
>
> -        }
>
> -    }
>
> -    return false;
>
> -}
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/gameroyadvance.c
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547694>:
>
> > +
>
> +This program is free software: you can redistribute it and/or modify
>
> +it under the terms of the GNU General Public License as published by
>
> +the Free Software Foundation, either version 2 of the License, or
>
> +(at your option) any later version.
>
> +
>
> +This program is distributed in the hope that it will be useful,
>
> +but WITHOUT ANY WARRANTY; without even the implied warranty of
>
> +MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>
> +GNU General Public License for more details.
>
> +
>
> +You should have received a copy of the GNU General Public License
>
> +along with this program.  If not, see <http://www.gnu.org/licenses/>.
>
> +*/
>
> +
>
> +#include "gameroyadvance.h"
>
>
> This allows for a default behavior to be defined, without the need for the
> user to specify the behavior. This is very useful for the configurator
> which doesn't have a way to configure this behavior, currently.
> ⬇️ Suggested change
>
> -#include "gameroyadvance.h"
>
> +#include "gameroyadvance.h"
>
> +
>
> +#ifdef ENCODER_ENABLE
>
> +bool encoder_update_kb(uint8_t index, bool clockwise) {
>
> +    if (!encoder_update_user(index, clockwise)) { return false; }
>
> +    if (index == 0) {
>
> +        if (clockwise) {
>
> +            tap_code_delay(KC_VOLU, 10);
>
> +        } else {
>
> +            tap_code_delay(KC_VOLD, 10);
>
> +        }
>
> +    }
>
> +    return true;
>
> +}
>
> +#endif
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/keymaps/default_all/keymap.c
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852547802>:
>
> > +bool encoder_update_user(uint8_t index, bool clockwise) {
>
> +    if (index == 0) { /* First encoder */
>
> +        if (clockwise) {
>
> +            tap_code(KC_VOLD);
>
> +        } else {
>
> +            tap_code(KC_VOLU);
>
> +        }
>
> +    }
>
> +    return false;
>
> +}
>
>
> ⬇️ Suggested change
>
> -bool encoder_update_user(uint8_t index, bool clockwise) {
>
> -    if (index == 0) { /* First encoder */
>
> -        if (clockwise) {
>
> -            tap_code(KC_VOLD);
>
> -        } else {
>
> -            tap_code(KC_VOLU);
>
> -        }
>
> -    }
>
> -    return false;
>
> -}
>
>
> ------------------------------
>
> In keyboards/keystonecaps/gameroyadvance/rules.mk
> <https://github.com/qmk/qmk_firmware/pull/16882#discussion_r852548313>:
>
> > +#   comment out to disable the options.
>
> +#
>
> +BOOTMAGIC_ENABLE ?= yes	# Virtual DIP switch configuration(+1000)
>
> +MOUSEKEY_ENABLE ?= yes	# Mouse keys(+4700)
>
> +EXTRAKEY_ENABLE ?= yes	# Audio control and System control(+450)
>
> +CONSOLE_ENABLE ?= no	# Console for debug(+400)
>
> +COMMAND_ENABLE ?= no    # Commands for debug and configuration
>
> +SLEEP_LED_ENABLE ?= no  # Breathing sleep LED during USB suspend
>
> +NKRO_ENABLE ?= yes		# USB Nkey Rollo [...]