Add Idobao Montex RGB (V2)
qmk/qmk_firmware pull request #16897
Opened 2022-04-20 13:56 UTC by IBNobody

## Description

Add IdoBao Montex RGB (V2), an upgraded PCB from the original V1 from @NachoxMacho . 

The V2 added per-key RGB LEDs using RGBLIGHT in addition to the original underbody LED lighting. Other than extending the LED lighting, I also added the RGBLIGHT_SLEEP option to turn off the LEDs when the host PC is asleep. No changes to the keymaps were made at this time.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-22 02:14 UTC, drashna requested changes

2022-04-22 02:14 UTC, drashna commented on keyboards/idobao/montex/v2/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-04-22 04:31 UTC, IBNobody commented
Thanks, fixed.

2022-04-22 06:27 UTC, fauxpark approved these changes

2022-04-22 07:54 UTC, drashna commented on keyboards/idobao/montex/v2/rules.mk
> +AUDIO_ENABLE = no           # Audio output
Oh, and: 
```suggestion
AUDIO_ENABLE = no           # Audio output

LAYOUTS = numpad_6x5
```

2022-04-22 13:00 UTC, vinorodrigues commented
Is this not a duplicate of #15865 that was PR'ed back in Jan 13th by @peepeetee, who was on contract by IDOBAO to do so?

2022-04-22 13:26 UTC, IBNobody commented
> Is this not a duplicate of #15865 ?

Yes and no. It's the same kb, but instead of using RGB_MATRIX which was the hold-up on that PR, it uses the original RGBLIGHT which V1 used. This avoids the VIA conflict.

2022-04-29 15:26 UTC, IBNobody commented
Worked with @vinorodrigues to update the code to support RGB_MATRIX rather than RGBLIGHT.

2022-04-29 15:36 UTC, vinorodrigues commented
I can confirm that this code is functional and tested with the V2 PCB sold both separately and with current "Montex RGB" kits.  PR #15865 is also *(probably)* correct, albeit for the older "Montex RGB" variants that pre-date the V2 PCB's *(thus that folder should be named `v1rgb`)*.

This code also honours existing VIA users by using a different PID so that it does not conflict with Montex (V1) boards.

2022-04-29 15:40 UTC, vinorodrigues approved these changes

2022-04-29 17:18 UTC, fauxpark requested changes

2022-04-29 17:18 UTC, fauxpark commented on keyboards/idobao/montex/v2/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-04-29 17:18 UTC, fauxpark commented on keyboards/idobao/montex/v2/v2.h
> +---------------------------------------- */
```suggestion
```

2022-04-29 17:18 UTC, fauxpark commented on keyboards/idobao/montex/v2/config.h
> +
```suggestion
```

2022-05-01 10:46 UTC, vinorodrigues commented
VIA PR is draft/ready for review once this is PR merged. [#1251](https://github.com/the-via/keyboards/pull/1251)

2022-05-01 10:52 UTC, fauxpark approved these changes

2022-05-07 21:21 UTC, IBNobody commented
@drashna Is there anything else I need to do for this?

2022-05-11 11:11 UTC, drashna commented
Would prefer that the layouts used the `numpad_6x5` community layout.  Eg: 
https://github.com/drashna/qmk_firmware/blob/78fbc54d83d57b830a51bb52cb86daa394d46baf/layouts/default/numpad_6x5/default_numpad_6x5/keymap.c

2022-05-11 11:18 UTC, vinorodrigues commented
ok - changing ... gimme a mo

2022-05-11 12:15 UTC, vinorodrigues commented
@IBNobody - you can also delete the `default_nug` keymap entirely.  This is redundant / duplicated code and can be done via other means. *(my bad for suggesting it in the first place)*

2022-05-11 12:58 UTC, IBNobody commented
> Would prefer that the layouts used the `numpad_6x5` community layout. Eg: https://github.com/drashna/qmk_firmware/blob/78fbc54d83d57b830a51bb52cb86daa394d46baf/layouts/default/numpad_6x5/default_numpad_6x5/keymap.c

Are you requesting that I use that identical keymap, or is it acceptable to use that keymap and then add the needed RGB controls to my keymap?

After looking at the `numpad_6x5` community layout, am I able to propose changes to it? 

The `numpad_6x5` layout was added with the original Montex V1. The only other keyboard using that layout is the [WE27](https://github.com/qmk/qmk_firmware/tree/a8d440e4e043dc8427f17c07631556d0ff3efc20/keyboards/wekey/we27) added 1 month later, and it follows the Montex V2 layout closer than it does the Montex V1 layout. (Function key is in the lower left.) I would like to propose a change to the `numpad_6x5` community layout to follow suit, especially since the Montex V1 is no longer obtainable for new users.

2022-05-11 14:49 UTC, IBNobody commented
> @IBNobody - you can also delete the `default_nug` keymap entirely. This is redundant / duplicated code and can be done via other means. _(my bad for suggesting it in the first place)_

I just had the via_nug there. I am removing it.

2022-05-20 14:37 UTC, IBNobody commented
> > Would prefer that the layouts used the `numpad_6x5` community layout. Eg: https://github.com/drashna/qmk_firmware/blob/78fbc54d83d57b830a51bb52cb86daa394d46baf/layouts/default/numpad_6x5/default_numpad_6x5/keymap.c
> 
> Are you requesting that I use that identical keymap, or is it acceptable to use that keymap and then add the needed RGB controls to my keymap?
> 
> After looking at the `numpad_6x5` community layout, am I able to propose changes to it?
> 
> The `numpad_6x5` layout was added with the original Montex V1. The only other keyboard using that layout is the [WE27](https://github.com/qmk/qmk_firmware/tree/a8d440e4e043dc8427f17c07631556d0ff3efc20/keyboards/wekey/we27) added 1 month later, and it follows the Montex V2 layout closer than it does the Montex V1 layout. (Function key is in the lower left.) I would like to propose a change to the `numpad_6x5` community layout to follow suit, especially since the Montex V1 is no longer obtainable for new users.

I'm still not 100% sure how to proceed.

2022-05-20 16:05 UTC, drashna approved these changes

2022-05-20 16:05 UTC, drashna commented on keyboards/idobao/montex/v2/keymaps/via/config.h
> +#endif
This won't be needed anymore, as of the end of the month (or if you compile from the develop branch).
```suggestion
```

2022-06-16 02:04 UTC, merged