Revert "Fix id67 RGB Matrix (#16916)" - on IDOBAO ID67 kb
qmk/qmk_firmware pull request #16917
Opened 2022-04-22 12:53 UTC by vinorodrigues

#15558 introduced a non-compile condition with the addition of a Caps-Lock LED lighting code in the root `id67.c` file.  This code leveraged a define `ID67_CAPS_LOCK_KEY_INDEX` that was only ever used in the `vinorodrigues` keymap, but wasn't declared anywhere.

Furthermore, the code for the Caps-Lock LED turned that LED to #FFFFFF - that is really bright (!) and does not account for the current user selected brightness values.  Also, using a fixed key for Caps-Lock LED leveraging a non-dedicated RGB matrix LED may not function as desired especially if that key is mapped to a non-Caps-Lock function.

#16916 attempted to resolve the compile error by removing the define and replacing it with the value `23`.  This is also problematic as it's the wrong LED index for the desired key. *(As idx-2-phys & led-idx are reversed, but not the kmtrx-2-led-idx in `g_led_config`.)*  It also tampers with the user keymap `vinorodrigues` that was not needed for a successful compile of the `default` *(used by config.qmk.fm)* and `via` *(used by the-via firmware automation)* keymaps.  However, the fix in that keymap merely needs a declaration of `#define CAPS_LOCK_KEY_INDEX 36` to correct.

## Description

- `keyboards/idobao/id67/config.h` - minor typo fixes
- `keyboards/idobao/id67/id67.c` - removal of the offending `rgb_matrix_indicators_user()` function
- `keyboards/idobao/id67/keymaps/vinorodrigues/*` - reversion to working code
- `keyboards/idobao/id67/config.h`
- `keyboards/idobao/id67/readme.md` - leverage correct branding on kb image, and simplification of product url's

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard *(addition or update)*
- [x] Keymap/layout/userspace *(addition or update)*
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #15558
* #16916

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything *(as well as I can manage)*.

2022-04-24 04:24 UTC, vinorodrigues commented
Confirming that `ID67_CAPS_LOCK_KEY_INDEX` should be `36` - as was before #16916

https://user-images.githubusercontent.com/366673/164956515-9b075342-c586-48f5-a640-37996e41ccfa.mp4

Added comment to code to ensure the reversal nature of the indices are made clearer (?).

2022-04-25 05:21 UTC, tzarc approved these changes

2022-04-25 05:21 UTC, tzarc commented
Cheers for addressing this!

2022-04-28 17:40 UTC, drashna approved these changes

2022-04-28 17:42 UTC, drashna requested changes

2022-04-28 17:42 UTC, drashna commented on keyboards/idobao/id67/config.h
> +    #define RGB_DISABLE_WHEN_USB_SUSPENDED true  // turn off effects when suspended
```suggestion
    #define RGB_DISABLE_WHEN_USB_SUSPENDED  // turn off effects when suspended
```

2022-04-29 07:16 UTC, drashna approved these changes

2022-05-12 00:09 UTC, merged