Update FAve 84H RGB firmware
qmk/qmk_firmware pull request #16919
Opened 2022-04-22 22:19 UTC by ToastyStoemp

## Description

Added VIA compatible RGB Matrix options

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-22 22:28 UTC, zvecr requested changes
Doesnt exist any more.

2022-04-22 22:28 UTC, zvecr commented on keyboards/linworks/fave84h/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-04-24 01:35 UTC, drashna commented
Mostly, this is adding support for via, for rgb light, correct?   

That's what it looks like.   But develop includes these changes already.  Compiling from develop will handle this already. !

2022-04-29 01:19 UTC, ToastyStoemp commented
> Mostly, this is adding support for via, for rgb matrix, correct?
> 
> That's what it looks like. But develop includes these changes already. Compiling from develop will handle this already. !

Sorry for the late reply, yes (did reduce the max brightness a little also) but this is pretty much just the VIA hack implementation

2022-05-20 05:01 UTC, drashna approved these changes

2022-05-20 13:30 UTC, fauxpark requested changes

2022-05-20 13:30 UTC, fauxpark commented on keyboards/linworks/fave84h/rules.mk
> +RGB_MATRIX_DRIVER = WS2812
```suggestion
RGB_MATRIX_DRIVER = WS2812
```
All lines should end in a newline character.

2022-05-20 13:30 UTC, fauxpark commented on keyboards/linworks/fave84h/keymaps/via/rules.mk
> +LTO_ENABLE = yes
```suggestion
LTO_ENABLE = yes
```

2022-05-23 03:58 UTC, fauxpark approved these changes

2022-06-20 11:40 UTC, ToastyStoemp commented
bump

2022-06-21 02:22 UTC, merged

2022-06-21 02:22 UTC, drashna commented
Thanks!