Introduced New layer & Imprvoments
qmk/qmk_firmware pull request #16921
Opened 2022-04-23 09:58 UTC by ioef

Introduced a New layer for the keymap & Improvements

This commit introduces a new layer in the existing vs code keymap. It also includes improvements
for presenting in the OLED screen the last key pressed.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-24 01:11 UTC, drashna approved these changes

2022-04-30 12:50 UTC, fauxpark requested changes

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 283:
```suggestion
            case LCTL(KC_X):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 265:
```suggestion
            case LCTL(KC_F):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 285:
```suggestion
            case LCTL(KC_Z):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 262:
```suggestion
            case LCTL(KC_C):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 281:
```suggestion
            case LCTL(KC_V):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 4868:
```suggestion
            case RCS(KC_A):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 312:
```suggestion
            case LCTL(KC_SLASH):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 550:
```suggestion
            case LSFT(KC_9):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 47:
```suggestion
            case KC_LEFT_BRACKET:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 559:
```suggestion
            case LSFT(KC_LEFT_BRACKET):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 42:
```suggestion
            case KC_BACKSPACE:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 76:
```suggestion
            case KC_DELETE:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 260:
```suggestion
            case LCTL(KC_A):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 278:
```suggestion
            case LCTL(KC_S):
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23747:
```suggestion
            case RGB_TOG:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23748:
```suggestion
            case RGB_MODE_FORWARD:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23760:
```suggestion
            case RGB_MODE_RAINBOW:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23762:
```suggestion
            case RGB_MODE_SNAKE:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23744:
```suggestion
            case BL_TOGG:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23745:
```suggestion
            case BL_STEP:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 23746:
```suggestion
            case BL_BRTG:
```

2022-04-30 12:50 UTC, fauxpark commented on keyboards/anavi/macropad8/keymaps/vscode/keymap.c
> +            case 20499:
```suggestion
            case TO(_BASIC) ... TO(_FN):
```

2022-05-03 22:45 UTC, drashna approved these changes

2022-05-04 00:01 UTC, fauxpark approved these changes

2022-05-04 15:08 UTC, merged