Solanis H87C/H88C Compatible Replacement PCBs
qmk/qmk_firmware pull request #16942
Opened 2022-04-26 04:55 UTC by mrnoisytiger

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-27 18:21 UTC, drashna approved these changes

2022-04-27 18:41 UTC, fauxpark requested changes

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/solanis.h
> +#define LAYOUT_tkl_all( \
```suggestion
#define LAYOUT_all( \
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/keymaps/via/keymap.c
> +    [_LAYER3] = LAYOUT_tkl_all(
```suggestion
    [_LAYER3] = LAYOUT_all(
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/keymaps/via/keymap.c
> +    [_LAYER2] = LAYOUT_tkl_all(
```suggestion
    [_LAYER2] = LAYOUT_all(
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/keymaps/via/keymap.c
> +    [_LAYER1] = LAYOUT_tkl_all(
```suggestion
    [_LAYER1] = LAYOUT_all(
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/keymaps/via/keymap.c
> +    [_LAYER0] = LAYOUT_tkl_all(
```suggestion
    [_LAYER0] = LAYOUT_all(
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/keymaps/default/keymap.c
> +    [_LAYER1] = LAYOUT_tkl_all(
```suggestion
    [_LAYER1] = LAYOUT_all(
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/keymaps/default/keymap.c
> +    [_LAYER0] = LAYOUT_tkl_all(
```suggestion
    [_LAYER0] = LAYOUT_all(
```

2022-04-27 18:41 UTC, fauxpark commented on keyboards/fjlabs/solanis/info.json
> +        "LAYOUT_tkl_all": {
```suggestion
        "LAYOUT_all": {
```

2022-04-28 23:19 UTC, fauxpark approved these changes

2022-04-29 07:06 UTC, merged

2022-04-29 07:15 UTC, mrnoisytiger commented
Thanks!