Fix Keychron Q2 rotary encoder detection issue
qmk/qmk_firmware pull request #16954
Opened 2022-04-28 09:31 UTC by lalalademaxiya1

Fixed encoder and update q2

## Description

- Update keyboard rev_0111 of keychron q2.
- Improve the encoder and make it perform better, specifcally add a function which called "encoder_inset_state", and will be called in pal set line event callback function.
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-28 15:21 UTC, zvecr commented
Core changes should be separate to keyboard changes.

2022-04-29 01:06 UTC, lokher commented
> Core changes should be separate to keyboard changes.

We added a new function to encoder.h and encoder.c, which is only invoked by Q2, and it won't break anything, why do we need to separate it? It's kinda wierd if we just add a single function, maybe someone would ask how to use it to fix this issue.

2022-04-29 01:19 UTC, zvecr commented
Because that is the process we ask people to follow, as it allows us manage the project easier.

By default core changes also have to go via develop, so i have updated the merge target (this is within the PR checklist).

2022-06-05 23:19 UTC, FWest98 commented
This change no longer works properly - it causes the rotary encoder to stop functioning altogether. This is due to the new if-condition at https://github.com/qmk/qmk_firmware/blob/master/quantum/encoder.c#L197, introduced in #16812. It prevents the encoder from triggering an action when this code path does not detect a state change - this will almost always be the case since `encoder_insert_state` already updates this state. The best solution I found to this issue is to introduce an additional condition that will trigger the update function to be called after the external update. See: https://github.com/FWest98/OS-QMK_Firmware/commit/95fbce9628191522bf9acb07808812b5c5463152#diff-c8e0671af976b0c896b651211e9605562985027873e5ef0d8a51a74c17aa8a6e

2022-11-16 10:58 UTC, spacecakes commented
Any updates on this? Is it still relevant? @lokher

2022-11-20 05:35 UTC, drashna requested changes

2022-11-20 05:35 UTC, drashna commented on quantum/encoder.c
> +
This would need to be pulled out and handled as a separate PR.

2022-11-20 05:35 UTC, drashna commented on keyboards/keychron/q2/rev_0111/rules.mk
> +# EEPROM_DRIVER = i2c
Why this change?  

This would remove any eeprom support from the board and make via support useless.

2023-02-21 02:42 UTC, tzarc commented
We'll be moving towards a decoupled model with `ENCODER_DRIVER = xxxx` instead of continuing here.

2023-02-21 02:42 UTC, closed without merging