Add base firmware for the Frog Numpad
qmk/qmk_firmware pull request #16963
Opened 2022-04-29 01:32 UTC by ToastyStoemp

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-29 08:09 UTC, drashna requested changes

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/frog_np.h
> +#include "encoder_action.h"
```suggestion
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/frog_np.c
> +};
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    } else if (index == 1) {
        if (clockwise) {
            tap_code_delay(KC_WH_U, 10);
        } else {
            tap_code_delay(KC_WH_D, 10);
        }
    }

    }
    return true;
}
#endif
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/frog_np.h
> +    E00A, E00B, E01A, E01B, \
```suggestion
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/frog_np.h
> +    { E00A, E00B, E01A, E01B }, \
```suggestion
    { KC_NO, KC_NO, KC_NO, KC_NO }, \
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/info.json
> +            "layout": [{"label":"0,0", "x":2.25, "y":0}, {"label":"0,1", "x":3.25, "y":0}, {"label":"1,0", "x":4.5, "y":0}, {"label":"1,1", "x":5.5, "y":0}, {"label":"1,2", "x":6.5, "y":0}, {"label":
```suggestion
            "layout": [{{"label":"1,1", "x":5.5, "y":0}, {"label":"1,2", "x":6.5, "y":0}, {"label":"1,3", "x":7.5, "y":0}, {"label":"0,2", "x":8.75, "y":0}, {"label":"0,3", "x":9.75, "y":0}, {"label":"2,0", "x":4.5, "y":1.25}, {"label":"2,1", "x":5.5, "y":1.25}, {"label":"2,2", "x":6.5, "y":1.25}, {"label":"2,3", "x":7.5, "y":1.25}, {"label":"3,0", "x":4.5, "y":2.25}, {"label":"3,1", "x":5.5, "y":2.25}, {"label":"3,2", "x":6.5, "y":2.25}, {"label":"3,3", "x":7.5, "y":2.25}, {"label":"4,0", "x":4.5, "y":3.25}, {"label":"4,1", "x":5.5, "y":3.25}, {"label":"4,2", "x":6.5, "y":3.25}, {"label":"4,3", "x":7.5, "y":3.25}, {"label":"5,0", "x":4.5, "y":4.25}, {"label":"5,1", "x":5.5, "y":4.25}, {"label":"5,2", "x":6.5, "y":4.25}, {"label":"5,3", "x":7.5, "y":4.25}, {"label":"6,0", "x":4.5, "y":5.25}, {"label":"6,1", "x":5.5, "y":5.25}, {"label":"6,2", "x":6.5, "y":5.25}, {"label":"6,3", "x":7.5, "y":5.25}]
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/default/keymap.c
> +        KC_VOLD, KC_VOLU, KC_WH_D, KC_WH_U,
```suggestion
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/default/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-04-29 08:09 UTC, drashna commented on keyboards/wolf/frog_np/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-07-23 16:16 UTC, ToastyStoemp commented
Closing until I tested the changes

2022-09-20 08:18 UTC, ToastyStoemp commented
Reopened the Pull Request with a rework using the QMK encoder mappings

2022-09-24 14:02 UTC, drashna requested changes

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/frog_np.h
> +#define LAYOUT( \
```suggestion
#define LAYOUT_orhto_6x4( \
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_orhto_6x4": {
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/default/keymap.c
> +    [_LAYER0] = LAYOUT(
```suggestion
    [_LAYER0] = LAYOUT_orhto_6x4(
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/default/keymap.c
> +    [_LAYER1] = LAYOUT(
```suggestion
    [_LAYER1] = LAYOUT_orhto_6x4(
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/via/keymap.c
> +    [_LAYER0] = LAYOUT(
```suggestion
    [_LAYER0] = LAYOUT_orhto_6x4(
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/via/keymap.c
> +    [_LAYER1] = LAYOUT(
```suggestion
    [_LAYER1] = LAYOUT_orhto_6x4(
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/via/keymap.c
> +    [_LAYER2] = LAYOUT(
```suggestion
    [_LAYER2] = LAYOUT_orhto_6x4(
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/keymaps/via/keymap.c
> +    [_LAYER3] = LAYOUT(
```suggestion
    [_LAYER3] = LAYOUT_orhto_6x4(
```

2022-09-24 14:02 UTC, drashna commented on keyboards/wolf/frog_np/rules.mk
> +ENCODER_MAP_ENABLE = yes
Encoder map should only be enabled as the keymap level.
```suggestion
```

2022-12-09 02:35 UTC, closed without merging