Add BigBoy macro pad
qmk/qmk_firmware pull request #16962
Opened 2022-04-29 00:46 UTC by tominabox1

## Description

add big boy macro pad

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-29 01:14 UTC, zvecr commented on keyboards/tominabox1/bigboy/config.h
> +    { D0, B1, B0, C7 }, \
2x4, but layout macro is 2x3?

2022-04-29 01:31 UTC, tominabox1 commented on keyboards/tominabox1/bigboy/config.h
> +    { D0, B1, B0, C7 }, \
oops thanks, forgot to fix that

2022-04-29 07:57 UTC, drashna requested changes

2022-04-29 07:57 UTC, drashna commented on keyboards/tominabox1/bigboy/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-04-29 07:57 UTC, drashna commented on keyboards/tominabox1/bigboy/keymaps/default/keymap.c
> +}
```suggestion
```

2022-04-29 07:57 UTC, drashna commented on keyboards/tominabox1/bigboy/bigboy.c
> +#include "bigboy.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#include "bigboy.h"

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    }
    return true;
}
#endif
```

2022-05-03 20:43 UTC, drashna commented on keyboards/tominabox1/bigboy/readme.md
> +![bigboy](update .jpg)
image?

2022-05-11 10:15 UTC, drashna approved these changes

2022-06-26 13:44 UTC, tominabox1 commented
any update on this

2022-07-02 14:05 UTC, tzarc approved these changes

2022-07-02 14:05 UTC, merged