change ANC rev3 to F103 MCU
qmk/qmk_firmware pull request #16964
Opened 2022-04-29 03:11 UTC by mechlovin

## Description

Change ANC Rev3 (adelais/rgb_led/rev3) from STM32F303 to APM32F103.
Thanks. 
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-04-29 08:10 UTC, drashna requested changes

2022-04-29 08:10 UTC, drashna commented on keyboards/mechlovin/adelais/rgb_led/rev3/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
```

2022-04-29 14:16 UTC, fauxpark requested changes

2022-04-29 14:16 UTC, fauxpark commented on keyboards/mechlovin/adelais/rgb_led/rev3/boards/adelais_f103/board.mk
> +# List of all the board related files.
This file can be deleted.

2022-05-20 09:32 UTC, mechlovin commented on keyboards/mechlovin/adelais/rgb_led/rev3/boards/adelais_f103/board.h
> +/*
This file was deleted as instructed.

2022-05-20 13:42 UTC, fauxpark requested changes
Still some outstanding reviews here.

2022-05-21 17:18 UTC, drashna approved these changes

2022-05-21 17:20 UTC, fauxpark requested changes

2022-05-21 17:20 UTC, fauxpark commented on keyboards/mechlovin/adelais/rgb_led/rev3/mcuconf.h
> +
```suggestion
```

2022-08-07 15:32 UTC, mechlovin commented
@fauxpark would really appreciate your final review. Thanks a ton!

2022-08-08 08:03 UTC, fauxpark approved these changes

2022-08-09 18:20 UTC, merged