Crkbd/thunderbird2086
qmk/qmk_firmware pull request #16973
Opened 2022-04-30 13:19 UTC by Thunderbird2086

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-03 20:26 UTC, drashna commented on keyboards/crkbd/keymaps/thunderbird2086/config.h
> +#    define RGBBLIGHT_ANIMATIONS
```suggestion
```

2022-05-03 20:27 UTC, drashna commented on keyboards/crkbd/keymaps/thunderbird2086/keycodes.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-03 20:28 UTC, drashna commented on keyboards/crkbd/keymaps/thunderbird2086/keymap.c
> +
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-03 20:28 UTC, drashna commented on keyboards/crkbd/keymaps/thunderbird2086/layers_block.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-11 10:33 UTC, drashna commented on keyboards/crkbd/keymaps/thunderbird2086/oled.c
> +#endif
There are functions for getting the values for these, and these shouldn't be used directly. 

https://docs.qmk.fm/#/feature_rgblight?id=query
https://docs.qmk.fm/#/feature_rgb_matrix?id=query-current-status

2022-05-12 00:09 UTC, drashna approved these changes

2022-05-12 04:44 UTC, fauxpark requested changes

2022-05-12 04:44 UTC, fauxpark commented on keyboards/crkbd/keymaps/thunderbird2086/rules.mk
> +MOUSEKEY_ENABLE = no        # Mouse keys(+4700)
```suggestion
MOUSEKEY_ENABLE = no
```

2022-06-04 14:13 UTC, Thunderbird2086 commented
@fauxpark could you review again?

2022-07-16 07:24 UTC, noroadsleft approved these changes

2022-07-16 07:29 UTC, merged

2022-07-16 07:29 UTC, noroadsleft commented
Thanks!