Add personal YMDK Split64 keymap
qmk/qmk_firmware pull request #16980
Opened 2022-05-01 08:26 UTC by minkezhang

## Description

Add personal YMDK Split64 keymap for [minkezhang](https://github.com/minkezhang)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-03 06:44 UTC, drashna commented
Please review the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and verify that you have followed the checklist for the type of PR this is.


Namely, c and h files need licensing headers, and files should be all lower case.

2022-05-03 07:23 UTC, minkezhang commented
Done. PR Checklist mentions "GPL-compatible" licenses, but is not explicit on the version. I assume since this implies there is GPLv2 code in the repo, we cannot use Apache2?

2022-05-18 06:26 UTC, minkezhang commented
@drashna Gentle ping, anything else here that I should be on the lookout for?

2022-05-20 05:15 UTC, drashna requested changes

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +#ifdef RGBLIGHT_LAYERS
```suggestion
#if defined(RGBLIGHT_ENABLE) && defined(RGBLIGHT_LAYERS)
```

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +#ifdef RGBLIGHT_LAYERS
```suggestion
layer_state_t default_layer_state_set_user(layer_state_t state) {
```

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +#endif  // RGBLIGHT_ENABLE
```suggestion
```

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +uint32_t layer_state_set_user(uint32_t state) {
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
```

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +#ifdef RGBLIGHT_LAYERS
```suggestion
```

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +#endif  // RGBLIGHT_ENABLE
```suggestion
```

2022-05-20 05:15 UTC, drashna commented on keyboards/ymdk/sp64/keymaps/minkezhang/keymap.c
> +}
```suggestion
}
#endif
```

2022-06-10 03:50 UTC, drashna approved these changes

2022-07-02 12:39 UTC, tzarc approved these changes

2022-07-02 12:39 UTC, merged