H60 updates
qmk/qmk_firmware pull request #16999
Opened 2022-05-04 17:39 UTC by hineybush

## Description

Slight update to the backlight config, wrapped in changes from #16811 as well, closed that PR.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-11 10:39 UTC, drashna approved these changes

2022-05-11 11:04 UTC, fauxpark requested changes

2022-05-11 11:04 UTC, fauxpark commented on keyboards/hineybush/h60/config.h
> +#define BACKLIGHT_ON_STATE 1
```suggestion
```

2022-05-11 11:04 UTC, fauxpark commented on keyboards/hineybush/h60/keymaps/via/keymap.c
> +    [0] = LAYOUT_all(
Technically, you can do this too:
```suggestion
    LAYOUT_all(
```

2022-05-12 04:41 UTC, fauxpark requested changes

2022-05-12 04:41 UTC, fauxpark commented on keyboards/hineybush/h60/keymaps/via/keymap.c
> +    [1] = LAYOUT_all(
```suggestion
    LAYOUT_all(
```

2022-05-12 04:41 UTC, fauxpark commented on keyboards/hineybush/h60/keymaps/via/keymap.c
> +    [2] = LAYOUT_all(
```suggestion
    LAYOUT_all(
```

2022-05-12 04:41 UTC, fauxpark commented on keyboards/hineybush/h60/keymaps/via/keymap.c
> +    [3] = LAYOUT_all(
```suggestion
    LAYOUT_all(
```

2022-05-13 05:21 UTC, fauxpark approved these changes

2022-05-13 06:33 UTC, drashna approved these changes

2022-05-13 06:33 UTC, merged