[Keyboard] Fix compilation issues for Quark LP
qmk/qmk_firmware pull request #17009
Opened 2022-05-05 04:51 UTC by drashna

## Description

As title. 

@npspears, would prefer that you checked off on this. 

## Types of Changes

- [x] Bugfix
- [x] Keyboard (addition or update)

## Issues Fixed or Closed by This PR

* Tzarc CI: 
  >  * RGB_MATRIX_DRIVER= is not a valid matrix type                                                          [ERRORS]
  > 
  > builddefs/common_features.mk:341: *** Invalid RGB_MATRIX_DRIVER.  Stop.

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-05 05:04 UTC, npspears commented
https://github.com/qmk/qmk_firmware/pull/17008#issuecomment-1118148305

I think I know what's going on, but I want to check in with Jack tomorrow so I better know the error and how to correct it.

2022-05-05 06:39 UTC, drashna commented
Well, to clarify, the first block (the "key matrix to led index" one), the LEDs are mapped to the matrix.  Eg, if the first leds are on the bottom row, thenyou have it upside down.  Eg: 

```c
  { 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47 }
  { 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24 },
  { 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 },
  { 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0 },
```

And if you have LEDs at all the possible key positions ... eg, in between, then that gets more complicated.

2022-05-05 07:00 UTC, drashna commented
In fact, I'm just going to assume this is the case

2022-05-06 02:43 UTC, npspears commented
The LEDs start at the top right corner and continue to the left, then down one row and continue to the right, and so forth. I suppose you could think of it like a snake

2022-05-16 21:56 UTC, npspears commented
what else do you need from me to in order to see this pushed?

2022-05-17 01:53 UTC, fauxpark requested changes

2022-05-17 01:53 UTC, fauxpark commented on keyboards/checkerboards/quark_lp/quark_lp.c
> + * the Free Software Foundation, either version 2 of the License, orj
```suggestion
 * the Free Software Foundation, either version 2 of the License, or
```

2022-05-17 02:22 UTC, fauxpark approved these changes

2022-05-17 03:27 UTC, merged