Timeout lights
qmk/qmk_firmware pull request #17021
Opened 2022-05-06 18:32 UTC by jmaguire

As implemented the RGB lights stay on forever especially since computers keep their USB ports on even when the computer sleeps. This ensures lights shut off after 5m. 

## Description

Adds 5 minute RGB light time out. Also turns off lights when USB enters a suspended mode or if the main device sleeps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-06 18:37 UTC, jmaguire commented
@drashna FYI I'm not sure why these settings are defaulted to an unused state. They leave result in keyboard lights on 24/7 on most new computers that keep their usb ports on all the time...

2022-09-14 18:17 UTC, drashna requested changes

2022-09-14 18:17 UTC, drashna commented on keyboards/gmmk/pro/ansi/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED
```

2022-09-14 18:17 UTC, drashna commented
This also has merge conflicts

2022-10-06 16:13 UTC, closed without merging