RESET -> QK_BOOT default-ish keymaps
qmk/qmk_firmware pull request #17037
Opened 2022-05-09 00:15 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-09 03:42 UTC, fauxpark requested changes

2022-05-09 03:42 UTC, fauxpark commented on keyboards/unicomp/spacesaver_m_post_2013/keymaps/default/keymap.c
> +        KC_TAB,    KC_Q,  KC_W,EEPROM_QK_BOOT,QK_BOOT,KC_T,KC_Y, KC_U,  KC_I,  KC_O,  KC_P,  KC_LBRC, KC_RBRC,    KC_BSLS,  KC_DEL,  KC_END,  KC_PGDN,  KC_P7,   KC_P8,   KC_P9,   KC_PMNS,
```suggestion
        KC_TAB,    KC_Q,  KC_W,EEP_RST,QK_BOOT,KC_T,KC_Y, KC_U,  KC_I,  KC_O,  KC_P,  KC_LBRC, KC_RBRC,    KC_BSLS,  KC_DEL,  KC_END,  KC_PGDN,  KC_P7,   KC_P8,   KC_P9,   KC_PMNS,
```

2022-05-09 03:42 UTC, fauxpark commented on keyboards/unicomp/spacesaver_m_pre_2013/keymaps/default/keymap.c
> +        KC_TAB,    KC_Q,  KC_W,EEPROM_QK_BOOT,QK_BOOT,KC_T,KC_Y, KC_U,  KC_I,  KC_O,  KC_P,  KC_LBRC, KC_RBRC,    KC_BSLS,  KC_DEL,  KC_END,  KC_PGDN,  KC_P7,   KC_P8,   KC_P9,   KC_PMNS,
```suggestion
        KC_TAB,    KC_Q,  KC_W,EEP_RST,QK_BOOT,KC_T,KC_Y, KC_U,  KC_I,  KC_O,  KC_P,  KC_LBRC, KC_RBRC,    KC_BSLS,  KC_DEL,  KC_END,  KC_PGDN,  KC_P7,   KC_P8,   KC_P9,   KC_PMNS,
```

2022-05-09 13:49 UTC, zvecr commented
Updated `sed`s to be less stupid, should address the above issue with changes being too aggressive.

2022-05-15 15:47 UTC, fauxpark approved these changes

2022-05-15 18:50 UTC, KarlK90 approved these changes

2022-05-15 19:26 UTC, merged