Added MS Sculpt ISO-layout conversion with STM32F401
qmk/qmk_firmware pull request #17049
Opened 2022-05-10 11:33 UTC by jn-bernard

## Description

Added MS Sculpt ISO-layout conversion with STM32F401

## Types of Changes

A MS Sculpt ISO-layout conversion to QMK

2022-05-10 15:36 UTC, zvecr commented
![image](https://user-images.githubusercontent.com/16520359/167666811-c8de4fd5-ad51-4580-b451-3beab4224227.png)

We wont be able to do anything with this PR in its current state. The history will need to be fixed so its just the intended keyboard addition.

2022-05-11 23:13 UTC, drashna commented
Pretty sure this was meant to go to master, not a very old/outdated branch....

Changed to master

2022-05-11 23:18 UTC, drashna requested changes

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/config.h
> +#define NO_PRINT
If console isn't enabled, these are already defined.  If console is enabled, you probably want to have debug and print enabled, too.
```suggestion
```

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/config.h
> +#define NO_ACTION_ONESHOT
Not sure you want these, as this disables layers, hold-tap keys, etc. 
```suggestion
/* disable action features */
// #define NO_ACTION_LAYER
// #define NO_ACTION_TAPPING
// #define NO_ACTION_ONESHOT
```

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/halconf.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/keymaps/default/keymap.c
> +#define _BASE 0
```suggestion
enum custom_layers {
    _BASE,
};
```

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/rules.mk
> +
the rgblight values aren't used and should be removed.  The rest don't appear to be used. 
```suggestion
```

2022-05-11 23:18 UTC, drashna commented on keyboards/ms_sculpt/sculpt_iso.h
> +#pragma once
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-12 06:47 UTC, jn-bernard reviewed
fixed your issues

2022-05-13 06:25 UTC, drashna approved these changes

2022-07-02 12:16 UTC, tzarc approved these changes

2022-07-02 12:16 UTC, merged