[Keyboard] New Keyboard - Mokulua
qmk/qmk_firmware pull request #17055
Opened 2022-05-11 02:11 UTC by kylemccreery

## Description

Initial PR for adding the Mokulua keyboard kit by MechWild. This is the default, VIA, and Silly keymaps for Standard layout, and the default and VIA keymaps for Mirrored layout.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x]I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-11 23:22 UTC, drashna requested changes

2022-05-11 23:22 UTC, drashna commented on keyboards/mechwild/mokulua/mirrored/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-05-11 23:22 UTC, drashna commented on keyboards/mechwild/mokulua/standard/config.h
> +#define NO_ACTION_FUNCTION
```suggestion
```

2022-05-11 23:30 UTC, kylemccreery commented
@drashna Are those not needed/suggested to include anymore going forward?

2022-05-12 00:54 UTC, drashna commented
> @drashna Are those not needed/suggested to include anymore going forward?

Not entirely sure what you mean. 

But the action function and action macro features have been removed from QMK.  So the defines don't do anything anymore.

2022-05-12 00:56 UTC, drashna approved these changes

2022-05-12 01:23 UTC, fauxpark approved these changes

2022-05-12 04:49 UTC, merged