Added keyboard M64 RGB
qmk/qmk_firmware pull request #17069
Opened 2022-05-12 07:10 UTC by HorrorTroll

## Description

Added keyboard M64 RGB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-12 18:49 UTC, drashna requested changes

2022-05-12 18:49 UTC, drashna commented on keyboards/mss_studio/m64_rgb/keymaps/via/config.h
> +#endif
Develop handles this already, and that lands end of month.
```suggestion
```

2022-05-12 18:50 UTC, drashna commented on keyboards/mss_studio/m64_rgb/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
#include QMK_KEYBOARD_H
#include <lib/lib8tion/lib8tion.h>
#include <math.h>
```

lib8tion.h includes string.h, but only if it's not arm. 
Also, it includes math8.h from it's own code, which may make math.h unnecessary, as well.

2022-05-13 11:49 UTC, HorrorTroll commented
THanks, i've just pushing new commit to resolved those issue

2022-05-13 14:53 UTC, drashna approved these changes

2022-05-14 01:02 UTC, fauxpark approved these changes

2022-05-14 03:16 UTC, merged