add new keyboard rad
qmk/qmk_firmware pull request #17088
Opened 2022-05-14 15:59 UTC by anubhavd7

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-14 16:07 UTC, zvecr commented
> You do not have permissions to merge. You need to follow the PR checklist and wait for us to review and merge.

Also, please **_stop_** closing and opening new PRs. Push additional changes to the same branch.

2022-05-14 17:55 UTC, drashna requested changes

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/Makefile
> +RAD
This file looks like it's supposed to be a readme, and would need to be renamed to `readme.md`

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/config.h
> +#define PREVENT_STUCK_MODIFIERS
```suggestion
```

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/config.h
> +#define DESCRIPTION     Keyboard
```suggestion
```

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/keymaps/default/keymap.c
> +
```suggestion
#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[0] = LAYOUT(
		KC_SPC, KC_SPC, 
		KC_SPC, KC_SPC, KC_SPC, 
		KC_SPC, KC_SPC, KC_SPC, 
		KC_SPC, KC_SPC, KC_SPC)
}
```

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/keymaps/via/keymap.c
> +
```suggestion
#define ____ KC_TRNS
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[0] = LAYOUT(
		KC_SPC, KC_SPC, 
		KC_SPC, KC_SPC, KC_SPC, 
		KC_SPC, KC_SPC, KC_SPC, 
		KC_SPC, KC_SPC, KC_SPC),
		[1] = LAYOUT(
			    ____ , ____, 
                ____ , ____, ____,
                ____ , ____, ____,
				____ , ____, ____
		),
		[2] = LAYOUT(
			    ____ , ____, 
                ____ , ____, ____,
                ____ , ____, ____,
				____ , ____, ____
		),
		[3] = LAYOUT(
			    ____ , ____, 
                ____ , ____, ____,
                ____ , ____, ____,
				____ , ____, ____
		)
}
       
```

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/keymaps/via/vial.json
> +{
This appears to be a VIAL json. 
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs

> Do not include VIAL json files in the PR. These do not belong in the QMK repository as they are not used by QMK firmware – they belong in the VIAL

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/rad.h
> +#define LAYOUT_horizontal( \
```suggestion
#define LAYOUT( \
```

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/info.json
> +    "LAYOUT_horizontal": {
```suggestion
    "LAYOUT": {
```

2022-05-14 17:55 UTC, drashna commented on keyboards/rad/rules.mk
> +COMMAND_ENABLE		= yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-05-14 21:20 UTC, zvecr requested changes

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/keymaps/default/keymap.c
> +[0] = LAYOUT_horizontal(
```suggestion
[0] = LAYOUT(
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/keymaps/default/keymap.c
> +
```suggestion
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/keymaps/via/keymap.c
> +#define ____ KC_TRNS
```suggestion
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/keymaps/via/rules.mk
> +VIAL_ENABLE		= yes
```suggestion
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/config.h
> +
```suggestion
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/keymaps/default/keymap.c
> +}
```suggestion
};
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/keymaps/via/keymap.c
> +
```suggestion
		[0] = LAYOUT(
			    KC_SPC, KC_SPC, 
			    KC_SPC, KC_SPC, KC_SPC, 
			    KC_SPC, KC_SPC, KC_SPC, 
			    KC_SPC, KC_SPC, KC_SPC),
		[1] = LAYOUT(
			    _______ , _______, 
                _______ , _______, _______,
                _______ , _______, _______,
				_______ , _______, _______
		),
		[2] = LAYOUT(
			    _______ , _______, 
                _______ , _______, _______,
                _______ , _______, _______,
				_______ , _______, _______
		),
		[3] = LAYOUT(
			    _______ , _______, 
                _______ , _______, _______,
                _______ , _______, _______,
				_______ , _______, _______
		)
};
```

2022-05-14 21:20 UTC, zvecr commented on keyboards/rad/readme.md
> +
```suggestion
# rad

The Rad Macro Pad is a USB-C,  Macro Pad with 11 keys powered by QMK

* Keyboard Maintainer: Anubhav Dhiman 
* Hardware Supported: ATmega32U4
* Hardware Availability: Interest Check

Make example for this keyboard (after setting up your build environment):

    make rad:default

Flashing example for this keyboard:

    make rad:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2022-05-14 21:25 UTC, zvecr commented
As well as the keyboard passing a basic compile, it seems line endings on at least the readme are incorrect.

2022-05-17 03:39 UTC, drashna requested changes

2022-05-17 03:39 UTC, drashna commented on keyboards/rad/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-05-17 03:39 UTC, drashna commented on keyboards/rad/readme.md
> +*
```suggestion


```

2022-05-17 05:06 UTC, drashna approved these changes

2022-05-17 13:25 UTC, fauxpark commented on keyboards/rad/info.json
> +  "maintainer": "anubhavd7",
```suggestion
  "manufacturer": "anubhavd7",
  "maintainer": "anubhavd7",
```

2022-05-17 14:51 UTC, zvecr commented
> yes sir i have checked it, it works and even i have made the changes as per asked by you

It does not.

```
tmk_core/protocol/usb_descriptor.c:437:35: error: 'DEVICE_VER' undeclared here (not in a function)
  437 |     .ReleaseNumber              = DEVICE_VER,
```

Note: PRs are reviewed in peoples free time, pinging multiple times will not make the process happen any faster

2022-05-18 05:45 UTC, fauxpark commented
> Note: PRs are reviewed in peoples free time, pinging multiple times will not make the process happen any faster

2022-05-20 05:28 UTC, merged