Add Eu isolation
qmk/qmk_firmware pull request #17102
Opened 2022-05-15 21:36 UTC by aadriance

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-15 21:45 UTC, aadriance commented
@TuckTuckFloof as an FYI incase you have any input on merging this in.  Just thought it would be worth sharing it to the QMK community.

2022-05-15 22:05 UTC, aadriance commented
After reading the PR checklist I realized I could test the configurator layout file.  Did that and got it updated because it initially looked weird. Pardon the extra commit

2022-05-17 03:51 UTC, drashna requested changes

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/info.json
> +    "height": 4,
```suggestion
```

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/bigspace/config.h
> +#define COMBO_COUNT 5
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

And it needs an include header (`#pragma once`)

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/bigspace/keymap.c
> +#include "eu_isolation.h"
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

Also, 
```suggestion
#include QMK_KEYBOARD_H
```

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/bigspace/keymap.c
> +    _BASE = 0,
```suggestion
    _BASE,
```

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/default/config.h
> +#define COMBO_COUNT 5
Same as above

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/default/keymap.c
> +#include "eu_isolation.h"
Same as above

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/mit/config.h
> +#define COMBO_COUNT 5
Same as above

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/keymaps/mit/keymap.c
> +#include "eu_isolation.h"
Same as above.

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/readme.md
> + Open source  bits available on [TuckTuckFloofs github](https://github.com/TuckTuckFloof/EUISO-pcb)
```suggestion

## Bootloader

Enter the bootloader in 3 ways:

* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available

## Information

Make example for this keyboard (after setting up your build environment):

    make eu_isolation:default

Flashing example for this keyboard:

    make eu_isolation:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
```

2022-05-17 03:51 UTC, drashna commented on keyboards/eu_isolation/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
AUDIO_ENABLE = no           # Audio output
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```

2022-05-18 02:58 UTC, aadriance commented
pushed on big update to address @drashna comments (Thanks for review). I recompiled all firmware and reflashed to my eu-isolation to confirm all is well (this comment brought to you by this firmware :)). I additionally re-opened the json layout in the configurator to ensure that didn't break aswell.

2022-05-18 03:44 UTC, fauxpark requested changes

2022-05-18 03:44 UTC, fauxpark commented on keyboards/eu_isolation/rules.mk
> +RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
```suggestion
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-05-18 03:44 UTC, fauxpark commented on keyboards/eu_isolation/readme.md
> +![euisolation](https://i.imgur.com/5LGsiJZ.jpg)
```suggestion

![euisolation](https://i.imgur.com/5LGsiJZh.jpg)
```

2022-05-19 02:57 UTC, fauxpark approved these changes

2022-05-20 05:37 UTC, drashna approved these changes

2022-05-20 05:38 UTC, merged