Re-refactor Mokulua
qmk/qmk_firmware pull request #17125
Opened 2022-05-17 13:20 UTC by kylemccreery

## Description

The refactor of the Mokulua firmware removed the support for one of the 2 possible PCBs that this split board can use. This readds support for the second PCB while keeping a couple of the changes that were suggested by that refactor.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-17 14:32 UTC, zvecr requested changes
Conflicts need to be resolved where the branch was reused from a previous PR.

2022-05-17 16:27 UTC, kylemccreery commented
@zvecr Fixed. Thanks. Sorry I missed that.

2022-06-13 19:25 UTC, drashna requested changes
It looks like you have changes to the submodules here.  These need to be reverted before the PR can be approved. 

Rebasing sometimes will fix this. Otherwise, you'd want to do something like this to fix them:
```sh
git checkout master
git submodule foreach 'git log -n1 --oneline'
# remember the first abcdef1234 on the submodules that have an issue
git checkout @@your-branch@@
# for each of the problematic repo's:
cd lib/@@name@@
git checkout abcdef1234
```

2022-06-13 19:25 UTC, drashna commented on keyboards/mechwild/mokulua/mirrored/mirrored.c
> +	oled_rotation_t oled_init_user(oled_rotation_t rotation) {
Please revert this change.  This should be the kb level function, NOT the user level. 
```suggestion
	oled_rotation_t oled_init_kb(oled_rotation_t rotation) {
```

2022-06-13 19:25 UTC, drashna commented on keyboards/mechwild/mokulua/standard/standard.c
> +	oled_rotation_t oled_init_user(oled_rotation_t rotation) {
```suggestion
	oled_rotation_t oled_init_kb(oled_rotation_t rotation) {
```

2022-06-16 22:00 UTC, drashna approved these changes

2022-06-16 22:00 UTC, drashna commented on keyboards/mechwild/mokulua/mirrored/config.h
> +//#    define RGBLIGHT_ANIMATIONS
```suggestion
```

2022-06-16 22:07 UTC, fauxpark requested changes

2022-06-16 22:07 UTC, fauxpark commented on keyboards/mechwild/mokulua/standard/standard.c
> +	oled_rotation_t oled_init_kb(oled_rotation_t rotation) {
Mixed tabs and spaces here, and in other files.

2022-06-16 22:07 UTC, fauxpark commented on keyboards/mechwild/mokulua/standard/keymaps/default/keymap.c
> +	_FN3
```suggestion
    _FN2,
    _FN3
```

2022-06-16 22:07 UTC, fauxpark commented on keyboards/mechwild/mokulua/mirrored/keymaps/via/keymap.c
> +	_FN3
```suggestion
    _FN2,
    _FN3
```

2022-06-16 22:07 UTC, fauxpark commented on keyboards/mechwild/mokulua/mirrored/keymaps/default/keymap.c
> +	_FN3
```suggestion
    _FN2,
    _FN3
```

2022-06-16 22:07 UTC, fauxpark commented on keyboards/mechwild/mokulua/standard/keymaps/via/keymap.c
> +	_FN3
```suggestion
    _FN2,
    _FN3
```

2022-06-21 12:17 UTC, kylemccreery commented
@zvecr @fauxpark Anything else that needs to be changed on this for a rereview?

2022-07-16 20:51 UTC, noroadsleft approved these changes
Slight `__attribute__ ((weak))` :heavy_check_mark:.

I diff'd the previous `mirrored`/`standard` implementation and came to the same conclusion @waffle87 seems to have done, but if the keyboard maintainer says some of the supported hardware doesn't work on the post-refactor version, I'm inclined to believe them.

2022-07-17 23:53 UTC, noroadsleft approved these changes
Took another look at this and spotted an error in the original refactor that this PR solves.

2022-07-17 23:55 UTC, merged

2022-07-17 23:55 UTC, noroadsleft commented
Thanks!