Added new keymap for KPrepublic BM60v2_poker
qmk/qmk_firmware pull request #17141
Opened 2022-05-18 07:07 UTC by TheChilledDejw

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-24 06:28 UTC, drashna commented on keyboards/kprepublic/bm60hsrgb_poker/rev2/keymaps/TheChilledDejw/rules.mk
> +# MCU name
Most of this should be removed.  Only the settings that need to be changed should be included here.

2022-10-25 05:40 UTC, drashna requested changes
Please rename the keymap folder to be all lower case.

2022-10-26 20:33 UTC, TheChilledDejw commented
> Please rename the keymap folder to be all lower case.

Renamed, everything should be fine with the folders

2022-10-31 01:20 UTC, drashna commented
It looks like you have changes to the submodules here.  These need to be reverted before the PR can be approved. 

Rebasing sometimes will fix this. Otherwise, you'd want to do something like this to fix them:
```sh
git checkout master
git submodule foreach 'git log -n1 --oneline'
# remember the first abcdef1234 on the submodules that have an issue
git checkout @@your-branch@@
# for each of the problematic repo's:
cd lib/@@name@@
git checkout abcdef1234
```

2023-01-18 02:03 UTC, closed without merging