[Keyboard] add Stello65 keyboard
qmk/qmk_firmware pull request #17168
Opened 2022-05-20 07:48 UTC by uybv

## Description

Stello65 Keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-20 16:26 UTC, drashna requested changes

2022-05-20 16:26 UTC, drashna commented on keyboards/stello65/hs_rev1/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-05-20 16:26 UTC, drashna commented on keyboards/stello65/hs_rev1/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-05-20 16:26 UTC, drashna commented on keyboards/stello65/sl_rev1/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-05-20 16:26 UTC, drashna commented on keyboards/stello65/sl_rev1/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-05-21 17:16 UTC, drashna approved these changes

2022-05-21 17:23 UTC, fauxpark requested changes

2022-05-21 17:23 UTC, fauxpark commented on keyboards/stello65/sl_rev1/config.h
> +//#define BOOTMAGIC_LITE_COLUMN 0
```suggestion
```

2022-05-21 17:23 UTC, fauxpark commented on keyboards/stello65/hs_rev1/config.h
> +//#define BOOTMAGIC_LITE_COLUMN 0
```suggestion
```

2022-06-02 17:06 UTC, drashna approved these changes

2022-06-03 09:25 UTC, fauxpark approved these changes

2022-06-07 18:28 UTC, merged