[Keyboard] New Keyboard - BB Steno
qmk/qmk_firmware pull request #17163
Opened 2022-05-20 02:09 UTC by kylemccreery

## Description

Initial add of MechWild's BB Steno. A simple steno keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-20 06:25 UTC, drashna requested changes

2022-05-20 06:25 UTC, drashna commented on keyboards/mechwild/bbs/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware? 

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-05-20 16:15 UTC, drashna requested changes

2022-05-20 16:15 UTC, drashna commented on keyboards/mechwild/bbs/bbs.c
> +    steno_set_mode(STENO_MODE_GEMINI); // or STENO_MODE_BOLT
```suggestion
    steno_set_mode(STENO_MODE_GEMINI); // or STENO_MODE_BOLT
    eeconfig_init_user();
```

2022-05-20 17:16 UTC, drashna approved these changes

2022-05-20 22:26 UTC, fauxpark requested changes

2022-05-20 22:26 UTC, fauxpark commented on keyboards/mechwild/bbs/info.json
> +{
![image](https://user-images.githubusercontent.com/4781841/169620246-c01b6756-fe78-4703-b334-4681182f6a68.png)

2022-07-14 01:49 UTC, noroadsleft requested changes

2022-07-14 01:49 UTC, noroadsleft commented on keyboards/mechwild/bbs/info.json
> +            "layout": [{"label":"k03", "x":3, "y":0.13}, {"label":"k08", "x":8.75, "y":0.13}, {"label":"k02", "x":2, "y":0.25}, {"label":"k04", "x":4, "y":0.25}, {"label":"k05", "x":5, "y":0.25}, {"l
Corrects the key sequence.

```suggestion
            "layout": [
                {"label":"k00", "x":0, "y":0.5},
                {"label":"k01", "x":1, "y":0.5},
                {"label":"k02", "x":2, "y":0.25},
                {"label":"k03", "x":3, "y":0.125},
                {"label":"k04", "x":4, "y":0.25},
                {"label":"k05", "x":5, "y":0.25},
                {"label":"k06", "x":6.75, "y":0.25},
                {"label":"k07", "x":7.75, "y":0.25},
                {"label":"k08", "x":8.75, "y":0.125},
                {"label":"k09", "x":9.75, "y":0.25},
                {"label":"k0A", "x":10.75, "y":0.5},
                {"label":"k0B", "x":11.75, "y":0.5},

                {"label":"k10", "x":0, "y":1.5},
                {"label":"k11", "x":1, "y":1.5},
                {"label":"k12", "x":2, "y":1.25},
                {"label":"k13", "x":3, "y":1.125},
                {"label":"k14", "x":4, "y":1.25},
                {"label":"k15", "x":5, "y":1.25},
                {"label":"k16", "x":6.75, "y":1.25},
                {"label":"k17", "x":7.75, "y":1.25},
                {"label":"k18", "x":8.75, "y":1.125},
                {"label":"k19", "x":9.75, "y":1.25},
                {"label":"k1A", "x":10.75, "y":1.5},
                {"label":"k1B", "x":11.75, "y":1.5},

                {"label":"k23", "x":2.75, "y":3.25, "h":1.5},
                {"label":"k24", "x":3.75, "y":3.25, "h":1.5},
                {"label":"k25", "x":4.75, "y":3, "h":1.5},
                {"label":"k26", "x":7, "y":3, "h":1.5},
                {"label":"k27", "x":8, "y":3.25, "h":1.5},
                {"label":"k28", "x":9, "y":3.25, "h":1.5}
            ]
```

2022-07-14 01:49 UTC, noroadsleft commented on keyboards/mechwild/bbs/rules.mk
> +OLED_ENABLE = no            # OLED Enabled
```suggestion
```

2022-07-14 06:25 UTC, noroadsleft approved these changes

2022-07-14 06:26 UTC, merged

2022-07-14 06:26 UTC, noroadsleft commented
Thanks!