Added Lunar Keyboard with Default and VIA Keymaps
qmk/qmk_firmware pull request #17172
Opened 2022-05-21 03:19 UTC by FreshCourageTake

## Description
Created a new keyboard called the Lunar. Added a default keymap as well as a VIA keymap.

## Types of Changes
Added new keyboard with 2 keymaps

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-21 17:14 UTC, drashna requested changes

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/config.h
> +#define VENDOR_ID       0x33F9
This vender ID is in used, and needs to be changed.

https://www.the-sz.com/products/usbid/index.php?v=0x33F9&p=&n=

Above 0x4000 is clear, and the further past that, the better.

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/config.h
> +#endif
```suggestion
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/config.h
> +#ifdef RGB_MATRIX_ENABLE
no animation modes enabled?

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/rev1/rev1.c
> +};
```suggestion
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/rev1/rev1.c
> +}
```suggestion
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/lunar.h
> +#define LAYOUT_lunar_grid LAYOUT_ortho_5x12
```suggestion
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/via/rules.mk
> +RGB_MATRIX_ENABLE = no
why switch off rgb matrix?

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/default/keymap.c
> +[_QWERTY] = LAYOUT_lunar_grid(
```suggestion
[_QWERTY] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/default/keymap.c
> +[_LOWER] = LAYOUT_lunar_grid(
```suggestion
[_LOWER] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/default/keymap.c
> +[_RAISE] = LAYOUT_lunar_grid(
```suggestion
[_RAISE] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/via/keymap.c
> +[_QWERTY] = LAYOUT_lunar_grid(
```suggestion
[_QWERTY] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/via/keymap.c
> +[_ONE] = LAYOUT_lunar_grid(
```suggestion
[_ONE] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/via/keymap.c
> +[_TWO] = LAYOUT_lunar_grid(
```suggestion
[_TWO] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented on keyboards/keebmaker/lunar/keymaps/via/keymap.c
> +[_THREE] = LAYOUT_lunar_grid(
```suggestion
[_THREE] = LAYOUT_ortho_5x12(
```

2022-05-21 17:14 UTC, drashna commented
Also, remove the lib/ugfx folder.

2022-05-26 05:32 UTC, FreshCourageTake commented
Enough updates were required that it seemed prudent to simply create a new PR.

2022-05-26 05:32 UTC, closed without merging