[Code] Mouse key kinetic mode fix
qmk/qmk_firmware pull request #17176
Opened 2022-05-21 10:26 UTC by filterpaper

## Description

Iterating the mouse key kinetic mode fix from #16951 with functional mouse wheel and slightly faster and usable defaults.

## Types of Changes

- [x] Core
- [x] Bugfix
- [x] Documentation

## Issues Fixed or Closed by This PR

* #13711

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-21 16:45 UTC, drashna commented
Lint is upset.  File needs a format pass.

2022-05-21 22:57 UTC, drashna requested changes

2022-05-21 22:57 UTC, drashna commented on quantum/mousekey.c
> +float   mk_wheel_interval    = 1000.0f / MOUSEKEY_WHEEL_INITIAL_MOVEMENTS;
```suggestion
float mk_wheel_interval = 1000.0f / MOUSEKEY_WHEEL_INITIAL_MOVEMENTS;
```

2022-05-21 22:57 UTC, drashna commented on quantum/mousekey.c
>  uint8_t mk_wheel_interval    = MOUSEKEY_WHEEL_INTERVAL;
```suggestion
uint8_t mk_wheel_interval = MOUSEKEY_WHEEL_INTERVAL;
```

2022-05-21 23:07 UTC, filterpaper commented
> Lint is upset. File needs a format pass.

Can't have nice spacing with linter around.

2022-05-23 05:05 UTC, drashna approved these changes

2022-06-19 00:55 UTC, draffensperger commented
I tried this branch out on my Moonlander and it works well for me! I like the kinetic mouse keys algorithm - helps with both slow and fast movements better. Any chance this could get final review and merged in?

2022-06-19 01:11 UTC, filterpaper commented
This PR is will be merged into `develop` branch. Barring bugs, it should be in `master` by August 27, 2022.

2022-06-19 07:58 UTC, fauxpark approved these changes

2022-06-19 18:15 UTC, merged