Add base Ryujin firmware
qmk/qmk_firmware pull request #17187
Opened 2022-05-22 12:27 UTC by ToastyStoemp

## Description

Firmware for the Ryujin 65 case designed by Miroticaps

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-23 05:17 UTC, drashna requested changes

2022-05-23 05:17 UTC, drashna commented on keyboards/wolf/ryujin/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-06-10 01:23 UTC, drashna approved these changes

2022-07-02 12:36 UTC, tzarc approved these changes

2022-07-02 12:36 UTC, merged