KPrepublic bm80v2 ANSI Layout support
qmk/qmk_firmware pull request #17192
Opened 2022-05-23 03:08 UTC by edwardslau

## Description
BM80 V2 ANSI layout 

## Types of Changes

- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-23 06:00 UTC, drashna requested changes

2022-05-23 06:00 UTC, drashna commented on keyboards/kprepublic/bm80v2/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-05-23 06:00 UTC, drashna commented on keyboards/kprepublic/bm80v2/rules.mk
> +BLUETOOTH_ENABLE = no          # Enable Bluetooth
```suggestion
NKRO_ENABLE = yes              # Enable N-Key Rollover
BACKLIGHT_ENABLE = no          # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no           # Enable keyboard RGB underglow
```

2022-05-27 16:54 UTC, edwardslau commented
Modified the files as requested

2022-05-31 08:29 UTC, drashna commented on keyboards/kprepublic/bm80v2/readme.md
> +# bm80v2
This needs to be filled out, RE:
https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md

2022-06-02 17:11 UTC, drashna approved these changes

2022-06-02 17:11 UTC, drashna commented on keyboards/kprepublic/bm80v2/rules.mk
> +BOOTMAGIC_ENABLE = yes        # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes         # Enable Bootmagic Light
```

2022-07-02 13:14 UTC, tzarc approved these changes

2022-07-02 13:14 UTC, merged