foureight84 keymap for sofle
qmk/qmk_firmware pull request #17246
Opened 2022-05-30 01:03 UTC by foureight84

## Description

Add foureight84 keymap to the sofle keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-30 16:54 UTC, drashna commented
You need to rebase your branch, as you need to update the chibiOS libraries, so they're not being reverted here.  Rebasing sometimes will fix this. Otherwise, you'd want to do something like this to fix them:
```sh
git checkout master
git submodule foreach 'git log -n1 --oneline'
# remember the first abcdef1234 on the submodules that have an issue
git checkout @@your-branch@@
# for each of the problematic repo's:
cd lib/@@name@@
git checkout abcdef1234
```


Additionally, please review the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and verify that you have followed the checklist for the type of PR this is.  I've unchecked the "I have read the PR Checklist documentation" option, as there are changes listed there that have not been applied.

Eg, all c/h files need to have GPL 2+ compatible license headers. 

Additionally, you may want to change your oled wpm code, as s(n)printf uses ~1.5kb of firmware space.
https://docs.qmk.fm/#/squeezing_avr?id=oled-tweaks

2022-05-31 01:44 UTC, foureight84 commented
Gotcha. Thanks for this information.

2022-05-31 06:58 UTC, drashna requested changes

2022-05-31 06:58 UTC, drashna commented on keyboards/sofle/keymaps/foureight84/config.h
> +#endif // !NO_PRINT
This isn't needed.
```suggestion
```

2022-05-31 06:58 UTC, drashna commented on keyboards/sofle/keymaps/foureight84/README.md
> +For more information on integrating the Pimoroni Trackball, please see: https://github.com/foureight84/sofle-keyboard-pimoroni
Please rename this file to be lower case.

2022-05-31 06:58 UTC, drashna commented on keyboards/sofle/keymaps/foureight84/keymap.c
> +    KC_MOUSE_BTN2
```suggestion
```

2022-05-31 06:58 UTC, drashna commented on keyboards/sofle/keymaps/foureight84/keymap.c
> +}
```suggestion
```

2022-06-02 16:33 UTC, drashna commented on keyboards/sofle/keymaps/foureight84/keymap.c
> +#endif
```suggestion
```

2022-06-03 07:45 UTC, drashna approved these changes

2022-07-02 12:08 UTC, tzarc approved these changes

2022-07-02 12:08 UTC, merged