[Keyboard] IDOBAO ID80v1 folder rename
qmk/qmk_firmware pull request #17265
Opened 2022-05-31 08:47 UTC by vinorodrigues

## Description

IDOBAO support has received numerous support calls with users confused with the "v1" name used in the folder structure introduced in https://github.com/qmk/qmk_firmware/pull/15992.

The code in the v1 folder is a folder shift from the base of the `id80`folder and actually pertains to the "v2" boards. Both "v1" *(with no per-key under-light, or rather; self-solder per-key)* and "v2" *(with manufactured white per-key leds)* are compatible with that code base - however users seeking code for their "v2" boards are using the "v3" codebase, and this is not compatible as it uses RGB LED's and the RGB Matrix codebase.

This PR seeks to rename the "v1" folder to "v2" *(to eliminate confusion)*, and then add a `readme.md` and `rules.mk` file to the "v1" (ensuring backward compatibility).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A *(more about code clean-up)*

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-31 21:07 UTC, drashna requested changes

2022-05-31 21:07 UTC, drashna commented on keyboards/idobao/id80/v1/readme.md
> +![ID80](https://i.imgur.com/977ENjp.png)
```suggestion
![ID80](https://i.imgur.com/977ENjph.png)
```

2022-05-31 21:07 UTC, drashna commented on keyboards/idobao/id80/v2/readme.md
> +![ID80](https://i.imgur.com/977ENjp.png)
```suggestion
![ID80](https://i.imgur.com/977ENjph.png)
```

2022-06-02 16:16 UTC, drashna approved these changes

2022-06-03 08:46 UTC, fauxpark requested changes

2022-06-03 08:46 UTC, fauxpark commented on keyboards/idobao/id80/v2/rules.mk
> +BACKLIGHT_ENABLE = yes       # Enable underkey LED backlight
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
EXTRAKEY_ENABLE = yes        # Audio control and System control
CONSOLE_ENABLE = no          # Console for debug
COMMAND_ENABLE = no          # Commands for debug and configuration
NKRO_ENABLE = yes            # Enable N-Key Rollover
RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow
BACKLIGHT_ENABLE = yes       # Enable underkey LED backlight

DEFAULT_FOLDER = idobao/id80/v2/ansi
```

2022-06-10 01:14 UTC, drashna commented
Have these been checked to make sure they still compile?

2022-06-10 01:32 UTC, vinorodrigues commented
absolument

![image](https://user-images.githubusercontent.com/366673/172972368-dc09d9e5-55a8-4175-8ac1-7250619c31dd.png)

2022-06-11 00:34 UTC, drashna approved these changes

2022-08-13 14:00 UTC, tzarc approved these changes

2022-08-13 14:00 UTC, merged