add support for fuji75 solder & hotswap, kp60 hotswap pcb
qmk/qmk_firmware pull request #17264
Opened 2022-05-31 06:16 UTC by CMMS-Freather

add firmware support for fuji75 solder pcb
add firmware support for fuji75 hotswap pcb
add firmware support for keyspensory kp60 hotswap pcb

## Description
add qmk support for above keyboards

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-05-31 06:18 UTC, CMMS-Freather reviewed
updated 05/30

2022-05-31 06:24 UTC, CMMS-Freather reviewed
updated config.h for kp60

2022-05-31 07:30 UTC, drashna requested changes

2022-05-31 07:30 UTC, drashna commented on keyboards/cmm_studio/fuji75_hotswap/config.h
> +    #define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-05-31 07:30 UTC, drashna commented on keyboards/cmm_studio/fuji75_hotswap/readme.md
> +![CMM.Studio Fuji75 hotswap](https://i.imgur.com/0qiX0H7.png)
```suggestion
![CMM.Studio Fuji75 hotswap](https://i.imgur.com/0qiX0H7h.png)
```

2022-05-31 07:30 UTC, drashna commented on keyboards/cmm_studio/fuji75_solder/config.h
> +    #define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-05-31 07:30 UTC, drashna commented on keyboards/keyspensory/kp60/config.h
> +    #define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-06-02 16:14 UTC, drashna approved these changes

2022-06-16 03:24 UTC, CMMS-Freather reviewed
viewed changes

2022-07-02 12:56 UTC, tzarc requested changes

2022-07-02 12:56 UTC, tzarc commented on keyboards/cmm_studio/fuji75_hotswap/fuji75_hotswap.h
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/cmm_studio/fuji75_hotswap/keymaps/via/keymap.c
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/cmm_studio/fuji75_solder/fuji75_solder.h
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/cmm_studio/fuji75_solder/keymaps/via/keymap.c
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/keyspensory/kp60/config.h
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/keyspensory/kp60/keymaps/default/keymap.c
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/keyspensory/kp60/keymaps/via/keymap.c
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-02 12:56 UTC, tzarc commented on keyboards/keyspensory/kp60/kp60.h
> +// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
This copyright is wrong.

2022-07-06 07:35 UTC, CMMS-Freather reviewed
the copy right part on each file has been updated accordingly

2022-07-06 23:46 UTC, fauxpark requested changes

2022-07-06 23:46 UTC, fauxpark commented on keyboards/keyspensory/kp60/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-08-11 16:40 UTC, CMMS-Freather commented
recent comment has been commited, please review

2022-08-14 02:19 UTC, drashna requested changes

2022-08-14 02:19 UTC, drashna commented on keyboards/cmm_studio/fuji75_hotswap/config.h
> +#define PRODUCT         Fuji75_Hotswap
```suggestion
```

2022-08-14 02:19 UTC, drashna commented on keyboards/cmm_studio/fuji75_hotswap/info.json
> +    "layouts": {
```suggestion
    "manufacturer": "CMM.Studio",
    "usb": {
        "device_version": "1.0.0",
        "pid": "0x4638",
        "vid": "0x434D"
    },
    "layouts": {
```

2022-08-14 02:19 UTC, drashna commented on keyboards/cmm_studio/fuji75_solder/config.h
> +#define PRODUCT         Fuji75_solder
```suggestion
```

2022-08-14 02:19 UTC, drashna commented on keyboards/cmm_studio/fuji75_solder/info.json
> +    "layouts": {
```suggestion
    "manufacturer": "CMM.Studio",
    "usb": {
        "device_version": "1.0.0",
        "pid": "0x4637",
        "vid": "0x434D"
    },
    "layouts": {
```

2022-08-14 02:19 UTC, drashna commented on keyboards/cmm_studio/fuji75_solder/readme.md
> +![CMM.Studio Fuji75 solder](https://i.imgur.com/6eRavvW.png)
```suggestion
![CMM.Studio Fuji75 solder](https://i.imgur.com/6eRavvWh.png)
```

2022-08-14 02:19 UTC, drashna commented on keyboards/keyspensory/kp60/config.h
> +#define PRODUCT         KP60
```suggestion
```

2022-08-14 02:19 UTC, drashna commented on keyboards/keyspensory/kp60/info.json
> +    "layouts": {
```suggestion
    "manufacturer": "Keyspensory",
    "usb": {
        "device_version": "1.0.0",
        "pid": "0x0060",
        "vid": "0x4B50"
    },
    "layouts": {
```

2022-08-21 19:01 UTC, drashna approved these changes

2022-09-16 00:55 UTC, fauxpark requested changes

2022-09-16 00:55 UTC, fauxpark commented on keyboards/cmm_studio/fuji65/readme.md
> +
```suggestion
```

2022-09-16 00:55 UTC, fauxpark commented on keyboards/cmm_studio/fuji75_solder/fuji75_solder.c
> +}
This can be replaced with https://docs.qmk.fm/#/feature_led_indicators?id=configuration-options

2022-12-07 02:40 UTC, closed without merging