[Keyboard] Add Avalanche v4
qmk/qmk_firmware pull request #17288
Opened 2022-06-01 14:57 UTC by winder

## Description

Add v4 version of Avalanche keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-02 15:31 UTC, drashna requested changes

2022-06-02 15:31 UTC, drashna commented on keyboards/avalanche/v4/keymaps/winder/keymap.c
> +    return true;
```suggestion
    return false;
```

2022-06-02 15:31 UTC, drashna commented on keyboards/avalanche/v4/v4.c
> +#include "avalanche.h"
This allows you to have a default implementation, without needing to specify a config, and allows for the user code to override the behavior.

This is especially useful when compiling from the QMK Configurator. 

```suggestion
#include "avalanche.h"

#ifdef OLED_ENABLE
oled_rotation_t oled_init_kb(oled_rotation_t rotation) {
    return OLED_ROTATION_180;
}

bool oled_task_kb(void) {
    if (!oled_task_user()) {
        return false;
    }
    oled_write_P(PSTR("Avalanche\nVersion 4"), false);
    return true;
}
#endif
```

2022-06-03 07:41 UTC, drashna approved these changes

2022-07-02 12:07 UTC, tzarc approved these changes

2022-07-02 12:07 UTC, merged