Update massdrop/alt:charlesrocket
qmk/qmk_firmware pull request #17297
Opened 2022-06-03 05:53 UTC by charlesrocket

Updates for `massdrop/alt:charlesrocket` keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-03 07:53 UTC, drashna requested changes

2022-06-03 07:53 UTC, drashna commented on keyboards/massdrop/alt/keymaps/charlesrocket/config.h
> +#define UNICODE_SELECTED_MODES UC_BSD, UC_MAC, UC_LNX
```suggestion
#pragma once

#define UNICODE_SELECTED_MODES UC_BSD, UC_MAC, UC_LNX
```

2022-06-07 21:42 UTC, drashna commented on users/charlesrocket/rules.mk
> +ifdef APL_ENABLE
You might want this instead: 
```suggestion
ifeq ($(strip $(APL_ENABLE)), yes)
```

2022-06-07 21:42 UTC, drashna approved these changes

2022-06-07 22:18 UTC, charlesrocket commented on users/charlesrocket/rules.mk
> +ifdef APL_ENABLE
Thanks!

2022-07-02 12:19 UTC, tzarc approved these changes

2022-07-02 12:19 UTC, merged