Nebula12b
qmk/qmk_firmware pull request #17308
Opened 2022-06-04 21:38 UTC by yiancar

## Description

Successor of Nebula12.
Similar story as Nebula68b:)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-07 22:16 UTC, drashna commented on keyboards/spaceholdings/nebula12b/config.h
> +#define VIA_CUSTOM_LIGHTING_ENABLE
This isn't needed anymore.
```suggestion
```

2022-06-07 22:16 UTC, drashna commented on keyboards/spaceholdings/nebula12b/nebula12b.c
> +#endif
```suggestion
```

2022-06-07 23:40 UTC, yiancar commented
Ah yes nice!
One addition for the via code tho (in via.c) would be to scale brightness with MAX_BRIGHTNESS variable ;) I can do the PR if you like.

2022-06-08 01:21 UTC, fauxpark requested changes

2022-06-08 01:21 UTC, fauxpark commented on keyboards/spaceholdings/nebula12b/readme.md
> +    make spaceholdings/nebula12b:via
```suggestion
    make spaceholdings/nebula12b:default
```

2022-06-08 01:21 UTC, fauxpark commented on keyboards/spaceholdings/nebula12b/nebula12b.c
> +#include <lib/lib8tion/lib8tion.h>
```suggestion
```

2022-06-08 06:12 UTC, drashna commented
> Ah yes nice! One addition for the via code tho (in via.c) would be to scale brightness with MAX_BRIGHTNESS variable ;) I can do the PR if you like.

Hmm, I'm not sure. In theory, even if you set the val to a higher value, it won't use past that. But I'm not sure that via will re-read and report that correctly?  May need some testing/etc.

2022-06-08 07:44 UTC, yiancar commented
> > Ah yes nice! One addition for the via code tho (in via.c) would be to scale brightness with MAX_BRIGHTNESS variable ;) I can do the PR if you like.
> 
> Hmm, I'm not sure. In theory, even if you set the val to a higher value, it won't use past that. But I'm not sure that via will re-read and report that correctly? May need some testing/etc.

Yes that is correct, essentially by doing a scale operation (as I had done here) the brightness dial will not jump around in via. Currently lets say max brightness is at 150, half the dial does nothing. You slide it to 100% and it will jump back to 50% after the refresh.

2022-06-30 13:24 UTC, yiancar commented
Can we get this merged please?:)

2022-06-30 21:34 UTC, fauxpark approved these changes

2022-07-01 06:11 UTC, merged

2022-07-01 06:11 UTC, drashna commented
Thanks!