add kinesis/kintlc
qmk/qmk_firmware pull request #17301
Opened 2022-06-03 22:16 UTC by aleb

Added support for Teensy LC to the kinx/kint board for Kinesis keyboards.

## Description

I added a new keyboard, copy/pasted from kinesis/kint36, kinesis/kint41 and handwired/onekey/teensy_lc.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] Went to sleep because it's late now

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-08 01:12 UTC, fauxpark requested changes

2022-06-08 01:12 UTC, fauxpark commented on keyboards/kinesis/kint36/rules.mk
> +# MCU name from https://docs.qmk.fm/#/compatible_microcontrollers
```suggestion
# MCU name
```

2022-06-08 01:12 UTC, fauxpark commented on keyboards/kinesis/kintlc/rules.mk
> +# MCU name from https://docs.qmk.fm/#/compatible_microcontrollers
```suggestion
# MCU name
```

2022-06-08 01:12 UTC, fauxpark commented on keyboards/kinesis/kintlc/rules.mk
> +FIRMWARE_FORMAT = hex
```suggestion
```

2022-06-26 15:11 UTC, aleb commented
I've been using it for the past three weeks with no issues.

2022-06-26 18:37 UTC, fauxpark requested changes

2022-06-26 18:37 UTC, fauxpark commented on keyboards/kinesis/kint36/rules.mk
>  FIRMWARE_FORMAT = hex
```suggestion
```
This should not be needed as of #17014

2022-07-02 23:07 UTC, fauxpark requested changes

2022-07-02 23:07 UTC, fauxpark commented on keyboards/kinesis/kint41/rules.mk
>  DEBOUNCE_TYPE = sym_eager_pk
```suggestion
DEBOUNCE_TYPE = sym_eager_pk

FIRMWARE_FORMAT = hex
```
Teensy 4.1 does not have an entry in mcu_selection.mk yet so it is not covered here.

2022-07-03 04:12 UTC, fauxpark approved these changes

2022-07-11 19:46 UTC, merged