Added Halokeys Elemental 75 Keyboard
qmk/qmk_firmware pull request #17323
Opened 2022-06-06 23:45 UTC by shamit05

This commit adds the Elemental 75 keyboard produced by Halokeys.

## Description

Added QMK support to Elemental 75. Provides two different keymaps: default and via. Keyboard uses custom PCB built on STM32F303 microcontroller. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-08 02:24 UTC, drashna requested changes

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/elemental75.c
> +}
This should be the kb level function, not the user level.  

And if it's the kb level, then it needs to to call the user level, as well.

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/elemental75.json
> +{
This should be removed

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
There is no "full" bootmagic anymore, only the "lite" option, which can be turned on with just "yes".
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-06-08 02:24 UTC, drashna commented on keyboards/halokeys/elemental75/rules.mk
> +TAP_DANCE_ENABLE = yes
Tap Dance should not be enabled at the keyboard level, as it requires user configuration to work properly.   It should only be enabled at the keymap level. 

```suggestion
```

2022-06-11 18:04 UTC, drashna requested changes

2022-06-11 18:04 UTC, drashna commented on keyboards/halokeys/elemental75/keymaps/default/keymap.c
> +}
```suggestion
```

2022-06-11 18:04 UTC, drashna commented on keyboards/halokeys/elemental75/keymaps/via/keymap.c
> +}
```suggestion
```

2022-06-11 18:04 UTC, drashna commented on keyboards/halokeys/elemental75/elemental75.c
> +#include "print.h"
```suggestion
#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) {
        return false;
    }
    uprintf("Encoder Hit: clockwise: %b, index: %u\n", clockwise, index);
    if (index == 0) {
      if (clockwise) {
          print("Tapped code: KC_VOLU\n");
          tap_code(KC_VOLU);
      } else {
          print("Tapped code: KC_VOLD\n");
          tap_code(KC_VOLD);
      }
    }
    return true;
}
#endif
```

2022-06-12 22:56 UTC, drashna approved these changes

2022-06-14 11:00 UTC, fauxpark requested changes

2022-06-14 11:00 UTC, fauxpark commented on keyboards/halokeys/elemental75/info.json
> +    },
```suggestion
```

2022-06-15 00:23 UTC, zvecr requested changes

2022-06-15 00:23 UTC, zvecr commented on keyboards/halokeys/elemental75/chconf.h
> +
```suggestion
#pragma once

```

2022-06-16 21:58 UTC, drashna approved these changes

2022-06-27 20:06 UTC, shamit05 commented
Can someone take a look at this? Thanks.

2022-07-04 20:55 UTC, fauxpark approved these changes

2022-07-11 19:31 UTC, drashna requested changes

2022-07-11 19:31 UTC, drashna commented on keyboards/halokeys/elemental75/keymaps/default/keymap.c
> +      uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %b, time: %u, interrupt: %b, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time,
```suggestion
      uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %d, time: %u, interrupt: %d, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
```

2022-07-11 19:31 UTC, drashna commented on keyboards/halokeys/elemental75/keymaps/via/keymap.c
> +      uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %b, time: %u, interrupt: %b, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time,
```suggestion
      uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %d, time: %u, interrupt: %d, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
```

2022-07-16 19:15 UTC, drashna commented on keyboards/halokeys/elemental75/config.h
> +#define ENCODER_RESOLUTION 2
Not a fan of this being set by default. 

```suggestion
```

2022-07-16 19:15 UTC, drashna commented on keyboards/halokeys/elemental75/elemental75.c
> +    uprintf("Encoder Hit: clockwise: %b, index: %u\n", clockwise, index);
```suggestion
    uprintf("Encoder Hit: clockwise: %d, index: %u\n", clockwise, index);
```

2022-07-19 01:34 UTC, fauxpark approved these changes

2022-07-22 17:41 UTC, shamit05 commented
Can someone revise the most recent changes and merge if it's good? Thanks!

2022-07-26 05:35 UTC, drashna approved these changes

2022-07-26 05:36 UTC, merged