Add the GHS.JEM
qmk/qmk_firmware pull request #17340
Opened 2022-06-09 14:54 UTC by ramonimbao

## Description

Add the GHS.JEM

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-26 06:23 UTC, drashna requested changes

2022-07-26 06:23 UTC, drashna commented on keyboards/ghs/jem/config.h
> +//#    define RGBLIGHT_EFFECT_ALTERNATING
```suggestion
/*== choose animations ==*/
#    define RGBLIGHT_EFFECT_BREATHING
#    define RGBLIGHT_EFFECT_RAINBOW_MOOD
#    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    define RGBLIGHT_EFFECT_SNAKE
#    define RGBLIGHT_EFFECT_KNIGHT
#    define RGBLIGHT_EFFECT_CHRISTMAS
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT
#    define RGBLIGHT_EFFECT_RGB_TEST
#    define RGBLIGHT_EFFECT_ALTERNATING
```

2022-07-26 06:23 UTC, drashna commented on keyboards/ghs/jem/rules.mk
> +NKRO_ENABLE = no            # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-07-26 07:26 UTC, drashna approved these changes

2022-07-26 07:30 UTC, fauxpark requested changes

2022-07-26 07:30 UTC, fauxpark commented on keyboards/ghs/jem/rules.mk
> +BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
```

2022-07-26 07:30 UTC, fauxpark commented on keyboards/ghs/jem/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-09-02 11:26 UTC, ramonimbao commented
Hello, can I request for a recheck of this? I've finished migrating everything to the new data-driven way of QMK.

2022-09-02 11:30 UTC, fauxpark requested changes

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/soldered/config.h
> +// Copyright 2021 Ramon Imbao (@ramonimbao)
This file can be deleted.

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/hotswap_ansi/keymaps/default/readme.md
> +# The default keymap for GHS.JEM
This file can be deleted.

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/hotswap_ansi/config.h
> +// Copyright 2021 Ramon Imbao (@ramonimbao)
This file can be deleted.

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/soldered/keymaps/default/readme.md
> +# The default keymap for GHS.JEM
This file can be deleted.

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/info.json
> +    "maintainer": "ramonimbao",
```suggestion
    "maintainer": "ramonimbao",
    "usb": {
        "vid": "0x0645",
        "device_version": "1.0.0"
    },
```

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/hotswap_ansi/info.json
> +        "device_version": "1.0.0"
```suggestion
        "pid": "0x2003"
```

2022-09-02 11:30 UTC, fauxpark commented on keyboards/ghs/jem/soldered/info.json
> +        "device_version": "1.0.0"
```suggestion
        "pid": "0x1003"
```

2022-09-26 04:59 UTC, fauxpark approved these changes

2022-09-26 06:00 UTC, merged