Add Chaos65 keyboard
qmk/qmk_firmware pull request #17369
Opened 2022-06-12 13:33 UTC by kb-elmo

## Description

Added support for the Chaos65 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-12 18:43 UTC, drashna requested changes

2022-06-12 18:43 UTC, drashna commented on keyboards/chaos65/rules.mk
> +BACKLIGHT_ENABLE = no        # Enable keyboard backlight functionality on B7 by default
```suggestion
BOOTMAGIC_ENABLE = yes       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
EXTRAKEY_ENABLE = yes        # Audio control and System control
CONSOLE_ENABLE = no          # Console for debug
COMMAND_ENABLE = no          # Commands for debug and configuration
NKRO_ENABLE = yes            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no        # Enable keyboard backlight functionality
```

2022-06-12 22:29 UTC, drashna approved these changes

2022-06-14 11:03 UTC, fauxpark approved these changes

2022-06-14 23:42 UTC, merged