[Keyboard] Add ADM42 Keyboard
qmk/qmk_firmware pull request #17366
Opened 2022-06-12 09:45 UTC by lleonini

## Description

Add support for the ADM42 keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-12 18:39 UTC, drashna requested changes

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/config.h
> +#define USB_POLLING_INTERVAL_MS 1
These are the default values and don't need to be specified.

```suggestion
```

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/config.h
> +#endif
If console isn't enabled these are automatically defined.  If console is enabled, you don't want to disable these. 
```suggestion
```

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/readme.md
> +![ADM42](https://adm42.dev/images/adm42.jpg)
please rehost the image on Imgur or similar image hosting site.

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/rev4/keymaps/default/keymap.c
> +};
This should be moved to the keyboard's c file, not the keymap.

```suggestion
```

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/rev4/keymaps/default/keymap.c
> +#define _SETUP 5
```suggestion
enum custom_layers {
    _QWERTY,
    _COLEMAKDH,
    _SPECIAL,
    _EXTRA,
    _ADM,
    _SETUP,
};
```

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/config.h
> +#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
These should be defined at the keymap/user level, not kb level. 
```suggestion
```

2022-06-12 18:39 UTC, drashna commented on keyboards/adm42/rules.mk
> +EXTRAFLAGS += -flto
```suggestion
LTO_ENABLE = yes
```

2022-06-12 19:55 UTC, lleonini commented
Thanks for your feedback, I have commited the changes. Should I create a new pull request ?

2022-06-12 22:52 UTC, drashna approved these changes

2022-06-12 22:54 UTC, drashna commented
> Thanks for your feedback, I have commited the changes. Should I create a new pull request ?

No need.  The suggestions commit directly to the branch used for the PR, and when the branch is updated, the PR is updated. 

So there is no need to re-open, since the PR gets updated.

2022-06-14 10:55 UTC, fauxpark requested changes

2022-06-14 10:55 UTC, fauxpark commented on keyboards/adm42/rules.mk
> +LTO_ENABLE = yes
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
DEBOUNCE_TYPE = sym_eager_pk
LTO_ENABLE = yes
```

2022-06-14 10:55 UTC, fauxpark commented on keyboards/adm42/readme.md
> +![ADM42](https://i.imgur.com/pviCQSQ.jpeg)
```suggestion
![ADM42](https://i.imgur.com/pviCQSQh.jpeg)
```

2022-06-16 09:56 UTC, fauxpark approved these changes

2022-06-16 18:20 UTC, merged

2022-06-16 18:20 UTC, drashna commented
Thanks!