Le Chiffre rev 2 and HE additions
qmk/qmk_firmware pull request #17377
Opened 2022-06-13 12:09 UTC by tominabox1

## Description

Updated  Le Chiffre keyboard folder to add the rev2 version from P3D and the Hotswap Edition from Checkerboards.xyz

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-13 19:30 UTC, drashna requested changes

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/he/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/he/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/info.json
> +  "height": 4,
```suggestion
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/keymaps/default/keymap.c
> +      RESET,  _______,  AG_NORM,  AG_SWAP,  DEBUG, KC_TRNS,   KC_GRV,  KC_PGDN,    KC_UP,  KC_PGUP,  KC_SCLN,
Please revert. `RESET` is being deprecated, in favor of a keycode that doesn't collide with controller specific code.

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/keymaps/default/keymap.c
> +void oled_task_user(void) {
Please revert. 
```suggestion
bool oled_task_user(void) {
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/keymaps/default/keymap.c
> -
Please revert

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/keymaps/via/keymap.c
> +void oled_task_user(void) {
please revert.

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/rev1/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion
BOOTLOADER = atmel-dfu
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/rev1/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/rev2/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2022-06-13 19:30 UTC, drashna commented on keyboards/tominabox1/le_chiffre/rev2/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-06-13 21:55 UTC, tominabox1 commented on keyboards/tominabox1/le_chiffre/keymaps/default/keymap.c
> -
Ah I see I need a return false... updated!

2022-06-14 04:02 UTC, drashna requested changes

2022-06-14 04:02 UTC, drashna commented on keyboards/tominabox1/le_chiffre/keymaps/via/keymap.c
> +void oled_task_keymap(void) {
Pretty sure this is supposed to be:
```suggestion
bool oled_task_user(void) {
```

2022-06-26 13:30 UTC, tominabox1 commented
Any updates?

2022-06-26 16:25 UTC, drashna approved these changes

2022-06-26 18:34 UTC, fauxpark requested changes
Please fix the file permissions and remove empty files.

2022-06-26 18:34 UTC, fauxpark commented on keyboards/tominabox1/le_chiffre/readme.md
> +HE:       make tominabox1/le_chiffre/he:default
```suggestion
    make tominabox1/le_chiffre/rev1:default
    make tominabox1/le_chiffre/rev2:default
    make tominabox1/le_chiffre/he:default
```

2022-06-26 18:34 UTC, fauxpark commented on keyboards/tominabox1/le_chiffre/he/rules.mk
> +
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
```

2022-06-26 18:34 UTC, fauxpark commented on keyboards/tominabox1/le_chiffre/rev1/rules.mk
> +
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
```

2022-06-26 18:34 UTC, fauxpark commented on keyboards/tominabox1/le_chiffre/rev2/rules.mk
> +
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
```

2022-07-17 00:13 UTC, noroadsleft commented
The file permissions and [fauxpark's note regarding the readme](https://github.com/qmk/qmk_firmware/pull/17377#discussion_r906855800) still need addressing.

2022-07-17 18:51 UTC, tominabox1 commented
> The file permissions and [fauxpark's note regarding the readme](https://github.com/qmk/qmk_firmware/pull/17377#discussion_r906855800) still need addressing.

I have already pushed an update to fauxpark's note and I'm not sure what file permission issues you're seeing.

2022-07-21 18:16 UTC, noroadsleft requested changes
I'm still trying to find a solution for the file permissions. Git tracks them, but it's a feature Windows doesn't use at all, so figuring out how to set them is proving difficult for me.

----

2022-07-21 18:16 UTC, noroadsleft commented on keyboards/tominabox1/le_chiffre/readme.md
> +HE:       make tominabox1/le_chiffre/he:default
```suggestion
    make tominabox1/le_chiffre/rev1:default
    make tominabox1/le_chiffre/rev2:default
    make tominabox1/le_chiffre/he:default
```

2022-07-21 18:20 UTC, noroadsleft commented
> I have already pushed an update to fauxpark's note and I'm not sure what file permission issues you're seeing.

GitHub is showing a lot of the files in this PR as follows:

![image](https://user-images.githubusercontent.com/18669334/180285421-28222d17-2ab1-40e4-b71d-6e403a59c1cc.png)

The `100644 -> 100755` part at the end means the file permissions have changed. This affects how the files are handled in Linux (not sure about macOS; Windows doesn't use this feature at all).

2022-07-21 18:20 UTC, fauxpark commented
`git update-index --chmod=-x filename`

2022-07-21 18:42 UTC, noroadsleft commented
> `git update-index --chmod=-x filename`

Odd; I tried this command yesterday and it didn't do anything, but I try it now and it works. :confused: :man_shrugging:

2022-07-21 23:10 UTC, tominabox1 commented
I ran the command and updated but I dont know how to commit them. I did `git add .` then `git commit` and it said there was nothing to commit... even did the other suggested change and pushed it as you can see but it didnt fix the perms

2022-07-21 23:19 UTC, tominabox1 commented
Sorry think I got em now! I wish I understood how that happens

2022-07-22 03:35 UTC, fauxpark requested changes

2022-07-22 03:35 UTC, fauxpark commented on keyboards/tominabox1/le_chiffre/readme.md
> +make tominabox1/le_chiffre/he:default
```suggestion
    make tominabox1/le_chiffre/rev1:default
    make tominabox1/le_chiffre/rev2:default
    make tominabox1/le_chiffre/he:default 
```

2022-07-24 00:03 UTC, noroadsleft approved these changes
Looks good to me.

2022-07-24 00:03 UTC, merged

2022-07-24 00:03 UTC, noroadsleft commented
Thanks!