move to json
qmk/qmk_firmware pull request #17379
Opened 2022-06-13 15:44 UTC by alinelena

move to the new info.json approach

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-13 19:40 UTC, zvecr requested changes
Same should apply to all the other revisions.

2022-06-13 19:40 UTC, zvecr commented on keyboards/mlego/m65/rev1/info.json
> +    },
```suggestion
```

2022-06-13 19:40 UTC, zvecr commented on keyboards/mlego/m65/rev1/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-13 19:40 UTC, zvecr commented on keyboards/mlego/m65/rev1/info.json
> +    "protocol": "ChibiOS",
```suggestion
```

2022-06-13 19:40 UTC, zvecr commented on keyboards/mlego/m65/rev1/info.json
> +        "device_ver": "0x0001",
```suggestion
```

2022-06-19 20:13 UTC, zvecr requested changes

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m48/rev1/info.json
> +    "keyboard_folder": "mlego/m48/rev1",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m48/rev1/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m60/rev1/info.json
> +    "keyboard_folder": "mlego/m60/rev1",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m60/rev1/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m60_split/rev1/info.json
> +    "keyboard_folder": "mlego/m60_split/rev1",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m60_split/rev1/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m60_split/rev2/info.json
> +    "keyboard_folder": "mlego/m60_split/rev2",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m60_split/rev2/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev1/info.json
> +    "keyboard_folder": "mlego/m65/rev1",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev1/info.json
> +    },
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev2/info.json
> +    "keyboard_folder": "mlego/m65/rev2",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev2/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev3/info.json
> +    "keyboard_folder": "mlego/m65/rev3",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev3/info.json
> +    "platform": "STM32",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev4/info.json
> +    "keyboard_folder": "mlego/m65/rev4",
```suggestion
```

2022-06-19 20:13 UTC, zvecr commented on keyboards/mlego/m65/rev4/info.json
> +    "platform": "STM32",
```suggestion
```

2022-07-02 17:28 UTC, alinelena commented
> Same should apply to all the other revisions.

done

2022-08-19 10:45 UTC, closed without merging