Add Vector PCB to QMK
qmk/qmk_firmware pull request #17380
Opened 2022-06-13 20:03 UTC by awkannan

## Description

Adding Vector keyboard to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-16 23:50 UTC, keyboard-magpie requested changes
Minor formatting suggestions.

2022-08-16 23:50 UTC, keyboard-magpie commented on keyboards/cannonkeys/vector/readme.md
> +    make vector:default:flash
```suggestion
    make cannonkeys/vector:default:flash
```

2022-08-16 23:50 UTC, keyboard-magpie commented on keyboards/cannonkeys/vector/keymaps/via/keymap.c
> +    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,  KC_SPC,  KC_SPC,                                 KC_RALT, KC_RGUI, KC_RCTL
```suggestion
    KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,   KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,   KC_BSPC, KC_BSPC,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,   KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,  KC_BSLS,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,      KC_ENT,
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,    KC_RSFT, MO(_FN1),
    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,  KC_SPC,  KC_SPC,                                 KC_RALT, KC_RGUI, KC_RCTL
```

2022-08-16 23:50 UTC, keyboard-magpie commented on keyboards/cannonkeys/vector/keymaps/default/keymap.c
> +    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,  KC_SPC,  KC_SPC,                                 KC_RALT, KC_RGUI, KC_RCTL
```suggestion
    KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,   KC_BSPC, KC_BSPC,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,   KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC,  KC_BSLS,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,      KC_ENT,
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,    KC_RSFT, MO(_FN1),
    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,  KC_SPC,  KC_SPC,                                 KC_RALT, KC_RGUI, KC_RCTL
```

2022-08-17 22:48 UTC, zvecr requested changes

2022-08-17 22:48 UTC, zvecr commented on keyboards/cannonkeys/vector/config.h
> +// Copyright 2022 Andrew Kannan (@awkannan)
This file can be removed

2022-08-17 22:48 UTC, zvecr commented on keyboards/cannonkeys/vector/info.json
> +    },
```suggestion
    },
    "indicators": {
        "caps_lock": "B3",
        "on_state": 0
    },
```

2022-08-30 21:27 UTC, awkannan commented
@zvecr this one should be good to go now.
Thank you for the callout on moving things into info.json and removing config.h

I merged master in so I could test that it all worked - it does.

2022-08-30 23:48 UTC, drashna approved these changes

2022-09-13 13:12 UTC, awkannan commented
Hey @drashna thank you for the approval :)
I just wanted to bump this up a bit as its been a few weeks.

2022-09-13 14:49 UTC, fauxpark approved these changes

2022-09-14 18:13 UTC, merged