Add tegic for melgeek!
qmk/qmk_firmware pull request #17400
Opened 2022-06-16 10:57 UTC by mj-bomb

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-16 18:24 UTC, drashna requested changes

2022-06-16 18:24 UTC, drashna commented on keyboards/melgeek/tegic/config.h
> +#define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
```suggestion
```

2022-06-16 18:24 UTC, drashna commented on keyboards/melgeek/tegic/rev1/rev1.c
> +}
```suggestion
```

2022-06-16 18:24 UTC, drashna commented on keyboards/melgeek/tegic/rev1/rev1.c
> +#endif
```suggestion
#endif

void keyboard_pre_init_kb(void) {
    setPinOutput(B7);
    writePinHigh(B7);
    keyboard_pre_init_user();
}
```

2022-06-20 04:47 UTC, drashna commented on keyboards/melgeek/tegic/readme.md
> +![Tegic](https://i.imgur.com/v2Xctfg.jpeg | https://i.imgur.com/UYNzkIf.jpeg)
```suggestion
![Tegic](https://i.imgur.com/v2Xctfgh.jpeg)

![Tegic](https://i.imgur.com/UYNzkIfh.jpeg)
```

2022-06-20 04:52 UTC, drashna approved these changes

2022-06-20 08:12 UTC, fauxpark approved these changes

2022-06-21 00:26 UTC, merged