Added new keyboard KB16-01
qmk/qmk_firmware pull request #17418
Opened 2022-06-19 04:36 UTC by HorrorTroll

## Description

Added new keyboard KB16-01, made by DOIO

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-19 18:05 UTC, drashna requested changes

2022-06-19 18:05 UTC, drashna commented on keyboards/doio/kb16/rev1/rules.mk
> +SRC += lib/layer_status/layer_status_4.c
Might be simpler to just make this an array of arrays, so you have one variable. 

And then you could run `oled_write_raw_P(layer_status[get_highest_layer(layer_state)], sizeof(layer_status[0])`

2022-06-21 00:27 UTC, drashna approved these changes

2022-07-02 14:08 UTC, tzarc approved these changes

2022-07-02 14:08 UTC, merged