Add nt-650
qmk/qmk_firmware pull request #17471
Opened 2022-06-24 14:06 UTC by evyd13

## Description

Adds the nt-650 to QMK.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-06-24 15:07 UTC, zvecr requested changes

2022-06-24 22:24 UTC, fauxpark requested changes

2022-06-24 22:24 UTC, fauxpark commented on keyboards/evyd13/nt650/keymaps/default/keymap.c
> +#define _XTRA 3
```suggestion
enum layer_names {
    _BASE,
    _FUNC,
    _LOCK,
    _XTRA
};
```

2022-06-24 22:25 UTC, fauxpark requested changes

2022-06-24 22:25 UTC, fauxpark commented on keyboards/evyd13/nt650/readme.md
> +![nt650](https://i.imgur.com/z0Xi6qo.png)
```suggestion
![nt650](https://i.imgur.com/z0Xi6qoh.png)
```

2022-06-28 06:30 UTC, fauxpark approved these changes

2022-07-02 18:09 UTC, drashna approved these changes

2022-07-02 18:09 UTC, merged