Fork Quefrency Rev. 5
qmk/qmk_firmware pull request #17503
Opened 2022-06-29 17:43 UTC by nooges

## Description

- Add Quefrency Rev. 5
- Make `default65macro` be the new `default` keymap
- Remove ISO layouts not supported by Rev. 4 & 5 PCBs

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-01 05:41 UTC, drashna requested changes

2022-07-01 05:41 UTC, drashna commented on keyboards/keebio/quefrency/keymaps/default/keymap.c
> +extern keymap_config_t keymap_config;
```suggestion
```

2022-07-01 05:41 UTC, drashna commented on keyboards/keebio/quefrency/keymaps/default60/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-07-01 05:41 UTC, drashna commented on keyboards/keebio/quefrency/keymaps/default60/keymap.c
> +#define _FN1 1
```suggestion
enum custom_layer {
    _BASE,
    _FN1,
};
```

2022-07-01 05:41 UTC, drashna commented on keyboards/keebio/quefrency/rev5/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-07-11 19:00 UTC, drashna approved these changes

2022-07-11 20:35 UTC, keyboard-magpie approved these changes
In terms of getting to grips with approvals, this all LGTM

2022-07-11 21:14 UTC, merged