Add Bemini
qmk/qmk_firmware pull request #17504
Opened 2022-06-29 18:03 UTC by ianklug

## Description

Add config and keymaps for Bemini keyboard controller

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-01 05:48 UTC, drashna requested changes

2022-07-01 05:48 UTC, drashna commented on keyboards/ianklug/bemini/config.h
> +#define ENCODER_RESOLUTION 2
This is something that should (usually) be set by users, not globally. 
```suggestion
```

2022-07-01 05:48 UTC, drashna commented on keyboards/ianklug/bemini/config.h
> +#define QMK_KEYS_PER_SCAN 12
There should be no need for this.  Default polling rate is already set to this. 

```suggestionz
```

2022-07-01 05:48 UTC, drashna commented on keyboards/ianklug/bemini/keymaps/default/keymap.c
> +}
```suggestion
```

2022-07-01 05:48 UTC, drashna commented on keyboards/ianklug/bemini/keymaps/default_p2/keymap.c
> +}
```suggestion
```

2022-07-01 05:48 UTC, drashna commented on keyboards/ianklug/bemini/bemini.c
> +
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion

#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code(KC_LSFT);
        } else {
            tap_code(KC_LCTL);
        }
    }
    return true;
}
#endif
```

2022-07-01 05:48 UTC, drashna commented on keyboards/ianklug/bemini/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-07-01 15:20 UTC, ianklug commented
your suggestions have been implemented, thanks drashna!

2022-07-02 19:07 UTC, drashna approved these changes

2022-07-02 23:11 UTC, fauxpark requested changes

2022-07-02 23:11 UTC, fauxpark commented on keyboards/ianklug/bemini/info.json
> +    "height": 3,
```suggestion
```

2022-08-16 19:40 UTC, closed without merging

2022-08-16 19:41 UTC, ianklug commented
closed - reworking for new hardware MCU