Fin pad
qmk/qmk_firmware pull request #17523
Opened 2022-07-01 07:08 UTC by evyd13

## Description

Adds the Fin Pad, a replacement PCB for the Lin Dolphin Pad. (Commission)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-02 18:31 UTC, drashna approved these changes

2022-07-02 22:56 UTC, zvecr requested changes

2022-07-02 22:56 UTC, zvecr commented on keyboards/evyd13/fin_pad/info.json
> +        "LAYOUT_all": {
```suggestion
        "LAYOUT_all": "LAYOUT_ortho_6x4"
    },
    "layouts": {
        "LAYOUT_ortho_6x4": {
```

2022-07-02 22:56 UTC, zvecr commented on keyboards/evyd13/fin_pad/keymaps/default/keymap.c
> +    [0] = LAYOUT_all(
```suggestion
    [0] = LAYOUT_ortho_6x4(
```

2022-07-06 23:47 UTC, fauxpark approved these changes

2022-07-11 12:57 UTC, merged

2022-07-11 12:57 UTC, drashna commented
Thanks!