Add new keyboard Promise87
qmk/qmk_firmware pull request #17525
Opened 2022-07-01 16:22 UTC by spbgzh

## Description

add new keyboard promise87
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-02 18:49 UTC, drashna approved these changes

2022-07-02 22:54 UTC, zvecr requested changes

2022-07-02 22:54 UTC, zvecr commented on keyboards/wuque/promise87/ansi/rules.mk
> +LAYOUT = 87_ansi
```suggestion
```

2022-07-02 22:54 UTC, zvecr commented on keyboards/wuque/promise87/wkl/rules.mk
> +LAYOUT = 87_wkl
```suggestion
```

2022-07-02 23:17 UTC, fauxpark requested changes

2022-07-02 23:17 UTC, fauxpark commented on keyboards/wuque/promise87/ansi/anis.c
> +#include "anis.h"
```suggestion
#include "ansi.h"
```
Typo here and in the filename.

2022-07-02 23:17 UTC, fauxpark commented on keyboards/wuque/promise87/ansi/readme.md
> +Flashing example for this keyboard:
```suggestion

Flashing example for this keyboard:
```

2022-07-03 00:39 UTC, spbgzh commented on keyboards/wuque/promise87/ansi/anis.c
> +#include "anis.h"
deleted 'anis.c' and added 'ansi.c'

2022-07-03 00:39 UTC, spbgzh commented on keyboards/wuque/promise87/ansi/readme.md
> +Flashing example for this keyboard:
solved

2022-07-03 00:39 UTC, spbgzh commented on keyboards/wuque/promise87/wkl/rules.mk
> +LAYOUT = 87_wkl
deleted

2022-07-03 00:39 UTC, spbgzh commented on keyboards/wuque/promise87/ansi/rules.mk
> +LAYOUT = 87_ansi
deleted

2022-07-04 17:19 UTC, fauxpark approved these changes

2022-07-11 02:55 UTC, spbgzh commented on keyboards/wuque/promise87/wkl/rules.mk
> +LAYOUT = 87_wkl
deleted

2022-07-11 02:55 UTC, spbgzh commented on keyboards/wuque/promise87/ansi/rules.mk
> +LAYOUT = 87_ansi
deleted

2022-07-11 11:23 UTC, merged