Added KG60 and KG65 to QMK
qmk/qmk_firmware pull request #17565
Opened 2022-07-05 00:09 UTC by mrnoisytiger

## Description

Added KG60 and KG65 to QMK. Cloned from FJLabs TF60 and TF65 and changed VID/PID as well as all FJLabs references to reflect Keygem due to branding.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- ]x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-11 19:29 UTC, drashna requested changes

2022-07-11 19:29 UTC, drashna commented on keyboards/keygem/kg60ansi/readme.md
> +---
```suggestion
```

2022-07-11 19:29 UTC, drashna commented on keyboards/keygem/kg60ansi/readme.md
> +---
```suggestion
```

2022-07-11 19:29 UTC, drashna commented on keyboards/keygem/kg65rgbv2/readme.md
> +---
```suggestion
```

2022-07-11 21:23 UTC, drashna approved these changes

2022-08-05 19:54 UTC, mrnoisytiger commented
Bump. 😊

2022-08-05 21:13 UTC, fauxpark requested changes

2022-08-05 21:13 UTC, fauxpark commented on keyboards/keygem/kg60ansi/info.json
> +    "maintainer": "Keygem",
```suggestion
    "keyboard_name": "KG60 ANSI",
    "manufacturer": "FJLabs",
    "url": "https://www.keygem.store/",
    "maintainer": "Keygem",
    "usb": {
        "vid": "0x4B47",
        "pid": "0x0001",
        "device_version": "0.0.1"
    },
```

2022-08-05 21:13 UTC, fauxpark commented on keyboards/keygem/kg60ansi/config.h
> +
```suggestion
```

2022-08-05 21:13 UTC, fauxpark commented on keyboards/keygem/kg65rgbv2/info.json
> +    "maintainer": "Keygem",
```suggestion
    "keyboard_name": "KG65 RGB V2",
    "manufacturer": "FJLabs",
    "url": "https://www.keygem.store/",
    "maintainer": "Keygem",
    "usb": {
        "vid": "0x4B47",
        "pid": "0x0002",
        "device_version": "0.0.1"
    },
```

2022-08-05 21:13 UTC, fauxpark commented on keyboards/keygem/kg65rgbv2/config.h
> +
```suggestion
```

2022-09-26 10:05 UTC, fauxpark approved these changes

2022-09-28 19:20 UTC, merged