Added Windz Sinanju to QMK
qmk/qmk_firmware pull request #17566
Opened 2022-07-05 00:17 UTC by mrnoisytiger

## Description

Added Windz Sinanju to QMK. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-11 19:27 UTC, drashna requested changes

2022-07-20 14:57 UTC, zvecr commented on keyboards/fjlabs/sinanju/sinanju.h
> +/* Midway60 Keymap Definitions */
```suggestion
```

2022-07-20 15:00 UTC, zvecr requested changes

2022-07-20 15:00 UTC, zvecr commented on keyboards/fjlabs/sinanju/sinanju.h
> +/* Midway60 Keymap Definitions */
```suggestion
```

2022-07-20 15:01 UTC, zvecr approved these changes

2022-07-20 15:01 UTC, merged