[Keyboard] Add yandrstudio/nz67v2 keyboard.
qmk/qmk_firmware pull request #17591
Opened 2022-07-07 17:54 UTC by jiaxin96

## Description
add nz67v2 keyboard.
`RESET` => `QK_BOOT` in readme of nz64 and zhou65.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-11 12:35 UTC, drashna requested changes

2022-07-11 20:31 UTC, drashna approved these changes

2022-08-13 19:31 UTC, keyboard-magpie requested changes
Is there any reason you have not included an info.json?

2022-08-16 03:43 UTC, jiaxin96 commented
> 1

The info.json file has been supplemented according to the qmk format requirements. Please review it again.

2022-08-16 04:00 UTC, fauxpark requested changes

2022-08-16 04:03 UTC, jiaxin96 commented on keyboards/yandrstudio/nz67v2/info.json
> +    },
I wrote these common configurations in the root directory of thess keyboards (). Do I need to repeat them again in a specific keyboard?

2022-08-16 04:05 UTC, fauxpark requested changes

2022-08-16 04:05 UTC, fauxpark commented on keyboards/yandrstudio/nz67v2/info.json
> +        "vid": "0xAA96",
```suggestion
    "processor": "STM32F103",
    "bootloader": "stm32duino",
    "usb": {
```

2022-08-20 20:20 UTC, keyboard-magpie approved these changes

2022-08-20 20:21 UTC, merged