Reduce Pixel Fractal effect array size
qmk/qmk_firmware pull request #17602
Opened 2022-07-09 02:59 UTC by filterpaper

## Description

Refactor the pixel fractal effect by halving the array size to reduce memory footprint.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-10 23:23 UTC, drashna approved these changes

2022-07-14 07:56 UTC, filterpaper commented
Added fix for #17589

2022-07-16 18:49 UTC, drashna requested changes
Looks like lint wants some formatting changes:

2022-07-16 18:49 UTC, drashna commented on quantum/rgb_matrix/animations/pixel_fractal_anim.h
> +    static bool led[MATRIX_ROWS][MID_COL];
```suggestion
    static bool     led[MATRIX_ROWS][MID_COL];
```

2022-07-16 18:49 UTC, drashna commented on quantum/rgb_matrix/animations/pixel_fractal_anim.h
> +            // Light and copy columns outward
```suggestion
    if (g_rgb_timer > wait_timer) {
        RGB rgb = rgb_matrix_hsv_to_rgb(rgb_matrix_config.hsv);
        for (uint8_t h = 0; h < MATRIX_ROWS; ++h) {
            // Light and copy columns outward
```

2022-07-21 17:20 UTC, drashna approved these changes

2022-08-11 21:40 UTC, zvecr approved these changes

2022-08-11 21:41 UTC, merged