boardsource/3x4 data driven
qmk/qmk_firmware pull request #17628
Opened 2022-07-11 18:01 UTC by waffle87

## Description

As title

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-11 20:08 UTC, zvecr requested changes
`development_board` presets various config like bootloader and processor.

In the future it will become a requirement for converters to work.

2022-07-11 20:08 UTC, zvecr commented on keyboards/boardsource/3x4/info.json
> +  "bootloader": "caterina",
```suggestion
  "development_board": "promicro",
```

2022-07-11 20:08 UTC, zvecr commented on keyboards/boardsource/3x4/info.json
> +  "processor": "atmega32u4",
```suggestion
```

2022-07-11 21:09 UTC, zvecr commented on keyboards/boardsource/3x4/keymaps/via/keymap.c
> +  )
```suggestion
  [2] = LAYOUT(
    _______, _______, _______, _______,
    _______, _______, _______, _______,
    _______, _______, _______, _______
  ),
  [3] = LAYOUT(
    _______, _______, _______, _______,
    _______, _______, _______, _______,
    _______, _______, _______, _______
  )
```

2022-07-11 21:11 UTC, zvecr commented on keyboards/boardsource/3x4/rules.mk
> -# MCU name
Can we align this to the template file `data/templates/keyboard/rules.mk`
```makefile
# This file intentionally left blank
```

2022-07-11 23:00 UTC, zvecr approved these changes

2022-07-12 00:51 UTC, fauxpark approved these changes

2022-07-13 04:58 UTC, merged