Add support for PAW3204 Optical Sensor
qmk/qmk_firmware pull request #17669
Opened 2022-07-13 18:51 UTC by drashna

## Description

Adds support for the PAW3204 low powered optical sensor.

This is basic support, as the device supports multiple power modes and more, but aren't actually implemented here.

Uses bitbanged communication

## Types of Changes

- [x] Core
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-14 11:25 UTC, KarlK90 reviewed
Nice! Do we have any prove that the driver works? As I don't have the sensor myself this would be good.

2022-07-14 11:25 UTC, KarlK90 commented on drivers/sensors/paw3204.c
> +    }
Both branches write the pin low, is this correct?

2022-07-14 11:25 UTC, KarlK90 commented on drivers/sensors/paw3204.c
> +        return data;
Parenthesis should be added to the branches.

2022-07-14 11:25 UTC, KarlK90 commented on drivers/sensors/paw3204.c
> +        // wait_us(2);
```suggestion
```

If it is not needed at all?

2022-07-14 14:14 UTC, drashna commented
> Nice! Do we have any prove that the driver works? As I don't have the sensor myself this would be good.

Unfortunately, no.  The code is taken from a fork. And unfortunately, I don't have actual hardware to test on.

2022-07-14 19:26 UTC, KarlK90 requested changes
More thorough review of the code. I'm beginning to think that we should get somebody with a PAW3204 to verify that this driver actually works. (Maybe the original author?)

2022-07-14 19:26 UTC, KarlK90 commented on drivers/sensors/paw3204.c
> +    data.y        = convert_twoscomp(paw3204_read_reg(REG_Y));
```suggestion
    data.x        = (int8_t)paw3204_read_reg(REG_X);
    data.y        = (int8_t)paw3204_read_reg(REG_Y);
```

2022-07-14 19:26 UTC, KarlK90 commented on drivers/sensors/paw3204.c
> +uint8_t datatogglestate;
```suggestion
```
This variable is only written to once and never used.

2022-07-14 19:26 UTC, KarlK90 commented on drivers/sensors/paw3204.c
> +}
```suggestion
uint8_t paw3204_read_reg(uint8_t reg_addr) {
    paw3204_serial_write(reg_addr);
    wait_us(5);
    return paw3204_serial_read();
}
```

2022-07-15 02:34 UTC, drashna commented
> More thorough review of the code. I'm beginning to think that we should get somebody with a PAW3204 to verify that this driver works an intended. ~(Maybe the original author?)~ Pinged Gompa on Discord.

Yeah, ideally, we should. 

That said, @GEIGEIGEIST (?) was designing a PCB around this sensor, which is what kicked this off for me.

2022-07-16 12:40 UTC, KarlK90 commented
Gompa is away from their computer for a week, but will report back afterwards.

2022-07-17 00:10 UTC, GEIGEIGEIST commented
I'm back at my computer/my keyboard on Monday and will report back then.

2022-07-17 18:14 UTC, freznel10 commented
I tested on a blackpill and can confirm that it works.

2022-07-18 23:18 UTC, GEIGEIGEIST commented
I tested it on my PCB, running on a RP2040 Pro Micro and it works too. Thank you!

2022-07-19 12:00 UTC, KarlK90 approved these changes
One last round of review comments (hope you don't feel nitpicked) and then this is good to go from my side.

2022-07-19 16:05 UTC, drashna commented
> One last round of review comments (hope you don't feel nitpicked) and then this is good to go from my side.

Nope, not at all.  Helps me get into better practice :)

And applied.

2022-07-19 18:30 UTC, KarlK90 commented
> > One last round of review comments (hope you don't feel nitpicked) and then this is good to go from my side.
> 
> Nope, not at all. Helps me get into better practice :)
> 
> And applied.

Good to hear! Feel free to merge.

2022-07-20 00:46 UTC, merged