Dactyl Manuform 4x5 with 5 thumb cluster
qmk/qmk_firmware pull request #17671
Opened 2022-07-13 19:13 UTC by ssedrick

Created a new version of the dactyl manuform. The 4x5 uses 6 keys in the thumb cluster, so needed a new one that supports only a 5 key thumb cluster

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-14 06:36 UTC, drashna requested changes

2022-07-14 06:36 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x5_5/keymaps/default/config.h
> +// Copyright 2022 Shem Sedrick (@ssedrick)
This entire file could be removed, actually.

2022-07-14 06:36 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x5_5/keymaps/default/keymap.c
> +    uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %b, time: %u, interrupt: %b, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, re
```suggestion
    uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %d, time: %u, interrupt: %d, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
```

2022-07-14 06:36 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x5_5/keymaps/default/keymap.c
> +}
```suggestion
```

2022-07-14 06:36 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x5_5/keymaps/ssedrick/config.h
> +// Copyright 2022 Shem Sedrick (@ssedrick)
same, can be removed.

2022-07-14 06:36 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x5_5/keymaps/ssedrick/keymap.c
> +}
```suggestion
```

2022-07-14 06:36 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x5_5/keymaps/ssedrick/keymap.c
> +    uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %b, time: %u, interrupt: %b, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, re
```suggestion
    uprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %d, time: %u, interrupt: %d, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
```

2022-07-26 07:35 UTC, drashna approved these changes

2022-08-13 19:38 UTC, keyboard-magpie approved these changes

2022-08-13 19:38 UTC, merged