add promicro87
qmk/qmk_firmware pull request #17682
Opened 2022-07-14 08:43 UTC by KD-MM2

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-14 12:54 UTC, drashna commented
Please don't close and re-open PRs: #17622

Also, 
> Yeah, I'm really not comfortable about the name here. ProMicro is a name that technically belongs to SparkFun. And as this isn't a board that is released by them, having it as part of the name is at best sketchy.

2022-07-16 19:29 UTC, drashna commented on keyboards/handwired/hwpm87/readme.md
> +![hwpm87](https://i.imgur.com/DLqdtAW.jpeg)
```suggestion
![hwpm87](https://i.imgur.com/DLqdtAWh.jpeg)
```

2022-07-16 19:29 UTC, drashna commented on keyboards/handwired/hwpm87/info.json
> +    "keyboard_name": "promicro87",
Should be changed

2022-07-20 03:29 UTC, KD-MM2 commented on keyboards/handwired/hwpm87/readme.md
> +![hwpm87](https://i.imgur.com/DLqdtAW.jpeg)
> 

Suggested change is a wrong image link.

2022-07-20 17:22 UTC, zvecr requested changes

2022-07-20 17:22 UTC, zvecr commented on keyboards/handwired/hwpm87/readme.md
> +    make hwpm87:default:flash
```suggestion
    make handwired/hwpm87:default

Flashing example for this keyboard:

    make handwired/hwpm87:default:flash
```

2022-07-20 22:32 UTC, keyboard-magpie approved these changes

2022-07-26 05:58 UTC, drashna commented on keyboards/handwired/hwpm87/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-08-09 18:15 UTC, drashna requested changes

2022-08-09 18:15 UTC, drashna commented on keyboards/handwired/hwpm87/config.h
> +#define PRODUCT         HWPM87
```suggestion
```

2022-08-09 18:15 UTC, drashna commented on keyboards/handwired/hwpm87/info.json
> +    "url": "",
```suggestion
    "url": "",
    "usb": {
        "vid": "0xFEED",
        "pid": "0x0001",
        "device_version": "0.0.1"
    },
```

2022-08-11 01:51 UTC, drashna approved these changes

2022-09-26 04:53 UTC, fauxpark approved these changes

2022-09-26 05:42 UTC, merged