[Keyboard] Added Atreyu keyboard.
qmk/qmk_firmware pull request #17698
Opened 2022-07-16 08:34 UTC by climent

Pull request for a new Atreyu keyboard to mainline.

## Description

Keyboard and keymap definition for a new atreyu keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-19 20:28 UTC, drashna commented on keyboards/atreyu/rev1/rev1.c
> +#include "atreyu.h"
This allows for a default behavior to be defined, without the need for the user to specify the behavior.  This is very useful for the configurator which doesn't have a way to configure this behavior, currently.

```suggestion
#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) {
        return false; 
    }

    if (index == 1) {
      if (clockwise) {
          tap_code(KC_VOLU);
      } else {
          tap_code(KC_VOLD);
      }
    }
    if (index == 0) {
      if (IS_LAYER_ON(_LOWER)) {
        if (clockwise) {
            tap_code(KC_WH_U);
        } else {
            tap_code(KC_WH_D);
        }
      } else {
        if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
      }
    }
    return true;
}
#endif
```

2022-07-19 20:29 UTC, drashna commented on keyboards/atreyu/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output

ENCODER_ENABLE = yes
```

2022-07-20 06:51 UTC, climent commented on keyboards/atreyu/readme.md
> +![atreyu](https://github.com/climent/atreyu/raw/main/pictures/PXL_20220331_122640681.jpg?raw=true)
Updated to imgur image.

2022-07-20 06:51 UTC, climent commented on keyboards/atreyu/readme.md
> +Make example for this keyboard (after setting up your build environment):
Updated readme.md with suggestion.

2022-07-20 06:52 UTC, climent commented
Please, take another look.

2022-07-26 07:41 UTC, drashna requested changes
Is there a reason for the revision folder? Do you plan on adding additional versions of the board?

2022-07-26 07:41 UTC, drashna commented on keyboards/atreyu/keymaps/default/keymap.c
> +#define KC_ALT_T ALT_T
```suggestion
```

2022-07-26 07:41 UTC, drashna commented on keyboards/atreyu/keymaps/default/keymap.c
> +
```suggestion
```

2022-07-26 07:41 UTC, drashna commented on keyboards/atreyu/readme.md
> +![atreyu](https://i.imgur.com/NP0cux1.jpg)
```suggestion
![atreyu](https://i.imgur.com/NP0cux1h.jpg)
```

2022-07-26 08:44 UTC, climent commented
> Is there a reason for the revision folder? Do you plan on adding additional versions of the board?

Yes, I am just completing rev2 which comes with an OLED screen, and requires pin changes.

2022-07-26 21:24 UTC, drashna approved these changes

2022-07-27 11:39 UTC, fauxpark requested changes

2022-07-27 11:39 UTC, fauxpark commented on keyboards/atreyu/keymaps/default/keymap.c
> +  _______,          _______, _______, _______, _______ , _______, _______ , _______, _______, _______, _______,         _______\
```suggestion
[_RAISE] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                    KC_HOME, KC_END , _______, KC_LCBR, KC_RCBR, KC_TILD,
  _______, _______, _______, _______, KC_HOME, KC_END ,                    KC_PGUP, XXXXXXX, KC_UP  , KC_LBRC, KC_RBRC, KC_DEL ,
  _______, _______, _______, _______, _______, _______,                    KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_PIPE, KC_ENT ,
  _______, _______, _______, _______, _______, _______,                    KC_UNDS, KC_MINS, KC_EQL , KC_PLUS, KC_BSLS, _______,
  _______,          _______, _______, _______, KC_SPC , KC_HOME, KC_END  , _______, _______, KC_RGUI, KC_RALT,          _______
),

[_LOWER] = LAYOUT(
  KC_GRV , KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  ,                   KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , _______,
  _______, KC_VOLU, _______, _______, TG(_RAISE), AG_TOGG,                _______, _______, _______, _______, _______, KC_DEL ,
  _______, KC_VOLD, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______, 
  _______, KC_CAPS, _______, _______, _______, _______,                   _______, _______, _______, _______, _______, _______,
  _______,          _______, _______, _______, KC_SPC , KC_VOLD, KC_VOLU, _______, _______, _______, _______, _______
),

[_ADJUST] = LAYOUT(
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  _______,          _______, _______, _______, _______ , _______, _______ , _______, _______, _______, _______,         _______
```

2022-07-27 11:39 UTC, fauxpark commented on keyboards/atreyu/keymaps/default/keymap.c
> +     KC_LCTRL,          LWR    , KC_LALT, KC_LGUI, KC_ENT , KC_LBRC, KC_RBRC, KC_SPC , RSE    , KC_NO  ,  KC_NO ,          KC_RCTRL
```suggestion
     KC_LCTL,           LWR    , KC_LALT, KC_LGUI, KC_ENT , KC_LBRC, KC_RBRC, KC_SPC , RSE    , KC_NO  ,  KC_NO ,          KC_RCTL 
```

2022-08-04 08:06 UTC, fauxpark requested changes

2022-08-04 08:06 UTC, fauxpark commented on keyboards/atreyu/rev1/info.json
> +      "device_version": "0.0.1",
```suggestion
      "device_version": "0.0.1"
```

2022-08-04 08:06 UTC, fauxpark commented on keyboards/atreyu/readme.md
> +*An unsplit, modified version of a Lily58 having a baby with a Sofle keyboard*
```suggestion
An unsplit, modified version of a Lily58 having a baby with a Sofle keyboard
```

2022-08-13 17:55 UTC, climent commented
Anything else needed to get this approved?

2022-08-13 17:58 UTC, climent reviewed
All changes merged.

2022-08-13 20:25 UTC, keyboard-magpie approved these changes
The picture including an encoder may be confusing for some, a future PR with an encoder enabled keymap may be a good idea.

2022-08-13 20:26 UTC, merged