Add Bonsai C4 converter
qmk/qmk_firmware pull request #17711
Opened 2022-07-18 07:24 UTC by infinityis

Adds converter for:

promicro -> [bonsai c4](https://github.com/customMK/Bonsai-C/tree/main/C4)

At the moment this PR only performs basic pin conversion. Despite peripheral support being needed to access on-board EEPROM and flash memory chips on Bonsai C4, peripheral support is currently not included because this converter leverages the existing GENERIC_STM32_F411XE board definition, and boards inheriting boards is not yet available.

If it is preferable to use dedicated Bonsai C4 board/config files (which include peripheral support) in the meantime, I have that ready as well and can update the PR accordingly.

## Description

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-20 17:33 UTC, zvecr submitted a review, later dismissed

2022-07-20 17:38 UTC, zvecr commented
Could you also update the docs at <https://github.com/qmk/qmk_firmware/blob/develop/docs/feature_converters.md>.

> If it is preferable to use dedicated Bonsai C4 board/config files (which include peripheral support) in the meantime, I have that ready as well and can update the PR accordingly.

Maybe, not sure I will have time before the end of the current develop cycle to improve the situation. Somewhat depends the level of "Out the box" configuration its providing.

2022-08-13 13:33 UTC, tzarc requested changes
Needs conflicts fixed, too.

2022-08-13 13:33 UTC, tzarc commented on docs/feature_converters.md
> +| `promicro` | `bonasai_c4`      |
```suggestion
| `promicro` | `bonsai_c4`      |
```

2022-08-13 13:33 UTC, tzarc commented on keyboards/custommk/bonsai_c4_template/bonsai_c4_template.c
> +}
If this is a template for use in other boards, lets clean up the indenting and the like.

2022-08-14 20:55 UTC, zvecr commented
Sorry, got conflicts again. Will merge asap once they are resolved.

2022-08-15 19:24 UTC, zvecr approved these changes

2022-08-15 19:31 UTC, keyboard-magpie approved these changes

2022-08-18 00:01 UTC, merged