Added WT65-D
qmk/qmk_firmware pull request #17724
Opened 2022-07-19 23:08 UTC by wilba

Added WT65-D

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-19 23:23 UTC, zvecr requested changes

2022-07-19 23:23 UTC, zvecr commented on keyboards/wilba_tech/wt65_d/wt65_d.c
> +}
```suggestion
```

2022-07-19 23:23 UTC, zvecr commented on keyboards/wilba_tech/wt65_d/config.h
> +
```suggestion

#define LED_CAPS_LOCK_PIN F1

```

2022-07-20 00:58 UTC, drashna requested changes

2022-07-20 00:58 UTC, drashna commented on keyboards/wilba_tech/wt65_d/info.json
> +    "height": 5,
```suggestion
```

2022-07-20 00:58 UTC, drashna commented on keyboards/wilba_tech/wt65_d/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-07-20 01:00 UTC, zvecr commented on keyboards/wilba_tech/wt65_d/rules.mk
> +BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
```

2022-07-20 02:10 UTC, drashna approved these changes

2022-07-20 02:16 UTC, fauxpark requested changes

2022-07-20 02:16 UTC, fauxpark commented on keyboards/wilba_tech/wt65_d/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-07-20 02:16 UTC, fauxpark commented on keyboards/wilba_tech/wt65_d/rules.mk
> +BOOTMAGIC_ENABLE = yes      # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
```

2022-07-26 16:36 UTC, zvecr approved these changes

2022-07-26 16:36 UTC, merged