[Docs] Add a note about the print function.
qmk/qmk_firmware pull request #17737
Opened 2022-07-21 06:11 UTC by caffeinism

## Description

Added undocumented content for print function.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-02 03:11 UTC, tzarc approved these changes

2022-10-02 03:42 UTC, fauxpark requested changes

2022-10-02 03:42 UTC, fauxpark commented on docs/faq_debug.md
> +- Try printing newline("\n"). Sometimes there is no output until newline is printed.
```suggestion
- Ensure all strings end with a newline character (`\n`). QMK Toolbox prints console output on a per-line basis.
```

2022-10-04 04:42 UTC, fauxpark approved these changes

2022-10-05 02:16 UTC, merged