Added sinanju WK
qmk/qmk_firmware pull request #17736
Opened 2022-07-21 04:48 UTC by mrnoisytiger

## Description

Added Sinanju WK PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation
 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-24 07:37 UTC, drashna approved these changes

2022-08-05 19:53 UTC, mrnoisytiger commented
Bump 😊

2022-08-05 21:09 UTC, fauxpark requested changes

2022-08-05 21:09 UTC, fauxpark commented on keyboards/fjlabs/sinanjuwk/info.json
> +    "maintainer": "FJLabs",
```suggestion
    "keyboard_name": "Sinanju WK",
    "manufacturer": "FJLabs",
    "url": "https://www.fjlaboratories.com",
    "maintainer": "FJLabs",
    "usb": {
        "vid": "0x7074",
        "pid": "0x1023",
        "device_version": "0.0.1"
    },
```

2022-08-05 21:09 UTC, fauxpark commented on keyboards/fjlabs/sinanjuwk/config.h
> +
```suggestion
```

2022-08-05 21:09 UTC, fauxpark commented on keyboards/fjlabs/sinanjuwk/readme.md
> +* Hardware Supported: Sinanju WK
```suggestion
* Keyboard Maintainer: FJLabs
* Hardware Supported: Sinanju WK

```

2022-08-29 07:07 UTC, mrnoisytiger commented
Bump. 😊

2022-08-29 11:27 UTC, fauxpark approved these changes

2022-08-29 18:25 UTC, merged