Dz65v2 Settings for SBennett13
qmk/qmk_firmware pull request #17747
Opened 2022-07-22 05:19 UTC by SBennett13

## Description

Add settings for SBennett13 dz65v2 keyboard to qmk master
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-24 03:54 UTC, drashna requested changes

2022-07-24 03:54 UTC, drashna commented on keyboards/dztech/dz65rgb/keymaps/sbennett13/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-07-24 03:54 UTC, drashna commented on keyboards/dztech/dz65rgb/keymaps/sbennett13/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-07-24 04:45 UTC, SBennett13 commented
Added to both, let me know if anything else looks wrong. Thanks!

2022-07-26 05:55 UTC, drashna approved these changes

2022-07-26 19:43 UTC, keyboard-magpie approved these changes

2022-07-26 19:43 UTC, merged