add dyz60-hs
qmk/qmk_firmware pull request #17763
Opened 2022-07-23 15:20 UTC by dayatz

# dyz60

60% layout with multiple layout and mounting support, it's the same as dyz60 but this is for hotswap version
![pcb](https://i.imgur.com/bXmwHS5l.jpg)

* Keyboard Maintainer: [dayatz](https://github.com/dayatz)
* Hardware Supported: dyz60, ATMega32u4
* Hardware Availability: Local Indonesia GB.

Make example for this keyboard (after setting up your build environment):

    make dyz/dyz60_hs:default

Flashing example for this keyboard:

    make dyz/dyz60_hs:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

2022-07-24 03:41 UTC, drashna commented on keyboards/dyz/dyz60_hs/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```


Also, most of the settings here can be moved to the info.json file.

2022-07-24 03:41 UTC, drashna requested changes

2022-07-24 03:41 UTC, drashna commented on keyboards/dyz/dyz60_hs/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware?  This is needed, as a new user may not be aware of how to enter to bootloader to flash new firmware.

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```

2022-07-26 05:45 UTC, drashna approved these changes

2022-07-26 18:29 UTC, zvecr requested changes

2022-07-26 18:29 UTC, zvecr commented on keyboards/dyz/dyz60_hs/config.h
> +#define LED_CAPS_LOCK_PIN F1
```suggestion
```

2022-07-26 18:29 UTC, zvecr commented on keyboards/dyz/dyz60_hs/info.json
> +    "usb": {
```suggestion
    "indicators": {
        "caps_lock": "F1"
    },
    "usb": {
```

2022-07-26 18:29 UTC, zvecr commented on keyboards/dyz/dyz60_hs/config.h
> +#define PRODUCT         dyz60-hs
```suggestion
```

2022-07-26 18:29 UTC, zvecr commented on keyboards/dyz/dyz60_hs/info.json
> +    "keyboard_name": "dyz60-hs",
```suggestion
    "keyboard_name": "dyz60-hs",
    "manufacturer": "dyz",
```

2022-07-30 03:35 UTC, fauxpark approved these changes

2022-07-30 04:07 UTC, merged