Add OwLab Link files
qmk/qmk_firmware pull request #17826
Opened 2022-07-28 14:40 UTC by owlab-git

## Description

Added support for the PCB of the OwLab Link.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-28 15:29 UTC, zvecr requested changes

2022-07-28 15:29 UTC, zvecr commented on keyboards/owlab/link/hotswap/chconf.h
> +/* Copyright 2020 Owlab
This file should be removed

2022-07-28 15:29 UTC, zvecr commented on keyboards/owlab/link/solder/config.h
> +#define USB_POLLING_INTERVAL_MS 1
```suggestion
```

2022-07-29 05:07 UTC, owlab-git commented
Modified files as suggestions.

2022-07-29 06:43 UTC, drashna requested changes

2022-07-29 06:43 UTC, drashna commented on keyboards/owlab/link/hotswap/config.h
> +#define USB_POLLING_INTERVAL_MS 1
This is the  default value and doesn't need to be set here.

2022-07-29 06:43 UTC, drashna commented on keyboards/owlab/link/hotswap/config.h
> +#    define FORCE_NKRO
Just a heads up, this can cause issues on system BIOS/Firmwares, as some don't support NKRO.

2022-07-29 06:43 UTC, drashna commented on keyboards/owlab/link/hotswap/readme.md
> +![LINK](https://imgur.com/a/Jqcl5Dq.png)
This uses a smaller, but still hi res image, that is more suitable for github markdown rendering. 
```suggestion
![LINK](https://imgur.com/a/Jqcl5Dqh.png)
```

2022-08-02 07:14 UTC, drashna commented on keyboards/owlab/link/hotswap/readme.md
> +![LINK](https://imgur.com/a/Jqcl5Dq.jpg)
```suggestion
![LINK](https://i.imgur.com/tbeeWsph.jpeg)
```

2022-08-06 06:40 UTC, drashna approved these changes

2022-08-06 06:55 UTC, fauxpark requested changes

2022-08-06 06:55 UTC, fauxpark commented on keyboards/owlab/link/solder/info.json
> +    "maintainer": "Owlab",
```suggestion
    "keyboard_name": "LINK Solder",
    "manufacturer": "Owlab",
    "url": "",
    "maintainer": "Owlab",
    "usb": {
        "vid": "0x4F53",
        "pid": "0x4C53",
        "device_version": "0.0.1"
    },
```

2022-08-06 06:55 UTC, fauxpark commented on keyboards/owlab/link/solder/config.h
> +
```suggestion
```

2022-08-06 06:55 UTC, fauxpark commented on keyboards/owlab/link/hotswap/info.json
> +    "maintainer": "Owlab",
```suggestion
    "keyboard_name": "LINK Hotswap",
    "manufacturer": "Owlab",
    "url": "",
    "maintainer": "Owlab",
    "usb": {
        "vid": "0x4F53",
        "pid": "0x4C49",
        "device_version": "0.0.1"
    },
```

2022-08-06 06:55 UTC, fauxpark commented on keyboards/owlab/link/hotswap/config.h
> +
```suggestion
```

2022-11-05 02:16 UTC, closed without merging