Automate "Data Driven" migrations?
qmk/qmk_firmware pull request #17820
Opened 2022-07-27 22:59 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-28 02:50 UTC, fauxpark commented
How disruptive is this to the rest of the `info.json`? They often have varying or mixed indentation, and may not follow the rules of `InfoJSONEncoder`. I'm aiming to minimise the diffs for ease of review, and the simplest (but obviously not the fastest) workflow I've come up with is to just make some snippets in Sublime and do it one board at a time.

2022-07-28 13:37 UTC, zvecr commented
It is more disruptive, mostly in the area of layout macros. Next iteration I plan to add will be for layout macros, so bulk changes in that area wont matter as much. Nothing will stop manual migrations, however an automated process potentially needs less review.

Longer term, `info.json` formatting is something that I want to add to PR validation.

2022-10-04 03:11 UTC, tzarc commented
bad stalebot

2022-10-04 05:45 UTC, tzarc requested changes

2022-10-04 05:45 UTC, tzarc commented on lib/python/qmk/cli/migrate.py
> +                    file_contents.pop(num)
```suggestion
                    while line.rstrip().endswith('\\'):
                        file_contents.pop(num)
                        line = file_contents[num]
                    file_contents.pop(num)
```

2022-11-21 06:51 UTC, tzarc approved these changes

2022-11-30 20:08 UTC, merged