[keymap] Add kkokdae keymap for keyboardio/atreus
qmk/qmk_firmware pull request #17843
Opened 2022-07-29 23:27 UTC by kkokdae

## Description

This is a new key map for keyboardio/atreus

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-07-30 02:34 UTC, drashna requested changes

2022-07-30 02:34 UTC, drashna commented on keyboards/keyboardio/atreus/keymaps/kkokdae/keymap.c
> +      default_layer = biton32(default_layer_state);
```suggestion
      default_layer = get_highest_layer(default_layer_state);
```

2022-07-30 02:34 UTC, drashna commented on keyboards/keyboardio/atreus/keymaps/kkokdae/keymap.c
> +  uint32_t default_layer;
Since this will be a number between 0-32, at most, a uint8_t is a better idea. 
```suggestion
    uint8_t default_layer;
```

2022-07-30 04:20 UTC, drashna approved these changes

2022-08-03 06:47 UTC, keyboard-magpie approved these changes

2022-08-03 06:47 UTC, merged