I2c alignment
qmk/qmk_firmware pull request #17896
Opened 2022-08-03 18:24 UTC by JohSchneider

while working on a new incarnation of an existing avr-keyboard, with now a chibios-based MCU i ran into compile-time issues for a driver that relies on the platform specific i2c_master implementation

it turned out that a "misaligned" signature in the chibios variant was the culpirt... 

## Description

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-04 13:07 UTC, sigprof commented
This change is not really useful — it just increases the confusion, because the `i2c_start()` and `i2c_stop()` function provided by the AVR and ChibiOS drivers are completely different.

The AVR `i2c_master` driver provides the low-level I2C API:
- `i2c_start(uint8_t address, uint16_t timeout)` — transmit the START condition and the device address;
- `i2c_write(uint8_t data, uint16_t timeout)` — transmit a single data byte;
- `i2c_read_ack(uint16_t timeout)` — receive a single byte and reply with ACK;
- `i2c_read_nack(uint16_t timeout)` — receive a single byte and reply with NACK;
- `i2c_stop()` — transmit the STOP condition.

It also provides the high-level I2C API on top of that low-level API:
- `i2c_transmit(uint8_t address, const uint8_t* data, uint16_t length, uint16_t timeout)`:
  transmit START condition, address with the WRITE direction, data bytes, STOP condition;
- `i2c_receive(uint8_t address, uint8_t* data, uint16_t length, uint16_t timeout)`:
  transmit START condition, transmit address with the READ direction, receive data bytes (replying with ACK to all bytes except the last one), transmit STOP condition;
- `i2c_writeReg(uint8_t devaddr, uint8_t regaddr, const uint8_t* data, uint16_t length, uint16_t timeout)`:
  transmit START condition, transmit address with the WRITE direction, transmit register address, transmit data bytes, transmit STOP condition;
- `i2c_writeReg16(uint8_t devaddr, uint16_t regaddr, const uint8_t* data, uint16_t length, uint16_t timeout)`:
  the same as above with a 16-bit register address (big endian on the I2C bus);
- `i2c_readReg(uint8_t devaddr, uint8_t regaddr, uint8_t* data, uint16_t length, uint16_t timeout)`:
   transmit START condition, transmit address with the WRITE direction, transmit register address, transmit START condition, transmit device address with the READ direction, receive data bytes (replying with ACK to all bytes except the last one), transmit STOP condition);
- `i2c_readReg16(uint8_t devaddr, uint16_t regaddr, uint8_t* data, uint16_t length, uint16_t timeout)`:
  the same as above with a 16-bit register address (big endian on the I2C bus).

However, the ChibiOS I2C API does not provide any equivalent to the low-level I2C API — it provides only functions like `i2cMasterReceiveTimeout()` and `i2cMasterTransmitTimeout()`, which could be used to implement the high-level I2C API.  Therefore the QMK `i2c_master` driver for ChibiOS implements only the high-level I2C API, and ideally it should not have the `i2c_start()` and `i2c_stop()` functions at all.

Unfortunately, somebody thought that it would be good to expose the `i2cStart()` and `i2cStop()` functions of the ChibiOS I2C API (which actually enable and disable the I2C controller and do not send anything over the I2C bus) under the `i2c_start()` and `i2c_stop()` names, despite the fact that functions with these names do completely different things on AVR.  So now we are stuck with those names until someone finally pushes through a cleanup PR for this.

------

As for porting your keyboard, what you actually need to do is rewrite the code to use the high-level I2C API instead of the AVR-only low-level API — then your code should work on both AVR and ChibiOS.  Any calls to `i2c_start()` or `i2c_stop()` would be dropped in the process, therefore the signature mismatch won't matter.

2022-08-05 12:10 UTC, JohSchneider commented
thanks for the detailed feedback - wasn't aware of that kind of code legacy...

> is rewrite the code to use the high-level I2C API instead

good idea! i'll do that


btw: from what i saw - going through the code and "adjusting" the few i2c_start(add_only) calls: there aren't that many users of the chibios version... so the "wrong-ish" chibios:i2c_start could be dropped relatively easily - thoughts on that?

also: revising the documentation to recommend/push users to stay with the higher level i2c-api instead of i2c_star/_stop?

2022-08-05 13:19 UTC, JohSchneider commented
regarding documentation: how about something like this: e6ff49e ?

2022-10-08 02:08 UTC, fauxpark requested changes

2022-10-08 02:08 UTC, fauxpark commented on docs/i2c_driver.md
> + - `uint16_t timeout`
```suggestion
 - `uint16_t timeout`  
```

2022-10-08 02:08 UTC, fauxpark commented on docs/i2c_driver.md
> + - `uint8_t address`
```suggestion
 - `uint8_t address`  
```

2022-10-08 02:08 UTC, fauxpark commented on docs/i2c_driver.md
> + - `uint16_t timeout`
```suggestion
 - `uint16_t timeout`  
```

2022-12-24 01:54 UTC, closed without merging