Add an ez_maker directpins for rp2040
qmk/qmk_firmware pull request #17908
Opened 2022-08-04 15:57 UTC by jepler

## Description

This allows all exposed pins on the Raspberry Pi Pico to be used
as up to 26 individual keys. Keys use a common ground arrangement.

The firmware is also expected to work on generic RP2040 boards, check
manufacturer pinout diagrams or use trial and error to find out the GP#s
of the pins.

Pinging @skullydazed since they are listed as maintainer for the other ez_maker keyboards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* (none)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-04 19:31 UTC, zvecr requested changes

2022-08-04 19:31 UTC, zvecr commented on keyboards/ez_maker/directpins/rp2040/config.h
> +/*
This file should be removed

2022-08-04 19:31 UTC, zvecr commented on keyboards/ez_maker/directpins/rp2040/info.json
> +    "diode_direction": "COL2ROW",
```suggestion
```

2022-08-04 19:31 UTC, zvecr commented on keyboards/ez_maker/directpins/rp2040/rp2.c
> +/* Copyright 2021 Zach White
This file should be removed

2022-08-04 19:31 UTC, zvecr commented on keyboards/ez_maker/directpins/rp2040/rp2.h
> +/* Copyright 2021 Zach White
This file should be removed

2022-08-04 19:31 UTC, zvecr commented on keyboards/ez_maker/directpins/rp2040/rules.mk
> +BOOTLOADER = rp2040
```suggestion
# This file intentionally left blank
```

2022-08-04 21:12 UTC, zvecr approved these changes

2022-08-06 02:02 UTC, drashna approved these changes

2022-08-28 20:40 UTC, merged

2022-08-29 00:16 UTC, jepler commented
Thank you!