[Keyboard] Add Zed65 to QMK
qmk/qmk_firmware pull request #17917
Opened 2022-08-05 07:11 UTC by mechlovin

## Description

Add Zed65 PCB to QMK, Retro66 and Wearhaus66 base on Zed65.
Thanks.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-06 02:15 UTC, drashna requested changes

2022-08-06 02:15 UTC, drashna commented on keyboards/mechlovin/zed65/retro66/config.h
> +#define ENCODERS 2
```suggestion
```

2022-08-06 02:15 UTC, drashna commented on keyboards/mechlovin/zed65/retro66/config.h
> +#define ENCODERS_CCW_KEY { { 4, 4 }, {8, 4} }
```suggestion
```

2022-08-07 21:28 UTC, drashna approved these changes

2022-08-08 08:11 UTC, fauxpark requested changes

2022-08-08 08:11 UTC, fauxpark commented on keyboards/mechlovin/zed65/wearhaus66/config.h
> +
```suggestion
```

2022-08-08 08:11 UTC, fauxpark commented on keyboards/mechlovin/zed65/wearhaus66/info.json
> +    "keyboard_name": "Retro66",
```suggestion
    "keyboard_name": "Wearhaus66", 
    "manufacturer": "Mechlovin Studio",
```

2022-08-08 08:11 UTC, fauxpark commented on keyboards/mechlovin/zed65/retro66/info.json
> +    "keyboard_name": "Retro66",
```suggestion
    "keyboard_name": "Retro66", 
    "manufacturer": "Mechlovin Studio",
```

2022-08-08 08:11 UTC, fauxpark commented on keyboards/mechlovin/zed65/retro66/config.h
> +
```suggestion
```

2022-08-08 08:11 UTC, fauxpark commented on keyboards/mechlovin/zed65/config.h
> +
```suggestion
```

2022-08-15 03:22 UTC, fauxpark requested changes

2022-08-15 03:22 UTC, fauxpark commented on keyboards/mechlovin/zed65/wearhaus66/readme.md
> +    make mechlovin/zed65/wearhaus66:via:flash
```suggestion

Flashing example for this keyboard:

    make mechlovin/zed65/wearhaus66:default:flash
```

2022-08-15 03:22 UTC, fauxpark commented on keyboards/mechlovin/zed65/wearhaus66/keymaps/via/keymap.c
> +  LOGO_LED_OFF = USER01
```suggestion
  LOGO_LED_OFF
```

2022-08-15 03:22 UTC, fauxpark commented on keyboards/mechlovin/zed65/retro66/readme.md
> +    make mechlovin/zed65/retro66:via:flash
```suggestion

Flashing example for this keyboard:

    make mechlovin/zed65/retro66:default:flash
```

2022-08-15 03:22 UTC, fauxpark commented on keyboards/mechlovin/zed65/readme.md
> +    make mechlovin/zed65:via:flash
```suggestion

Flashing example for this keyboard:

    make mechlovin/zed65:default:flash
```

2022-08-16 22:43 UTC, fauxpark approved these changes

2022-08-18 04:11 UTC, mechlovin commented
Thanks.

2022-08-20 18:45 UTC, merged