Update ginkgo65hot to allow use of community layouts
qmk/qmk_firmware pull request #17911
Opened 2022-08-04 20:52 UTC by spidey3

## Description

* Add the standard LAYOUT_65_ansi_blocker to `mokey/ginkgo65hot` to allow using community layouts
* Add a test layout in the `spidey3` userspace

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-04 22:33 UTC, fauxpark approved these changes

2022-08-06 02:04 UTC, drashna requested changes

2022-08-06 02:04 UTC, drashna commented on layouts/community/65_ansi_blocker/spidey3/config.h
> +#pragma once
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-08-06 02:04 UTC, drashna commented on layouts/community/65_ansi_blocker/spidey3/keymap.c
> +#include "spidey3.h"
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-08-06 20:28 UTC, drashna approved these changes

2022-08-06 20:29 UTC, merged