single layer layout for BFO-9000 with numpad on the left
qmk/qmk_firmware pull request #17957
Opened 2022-08-08 22:41 UTC by rogthefrog

New layout for keebio BFO-9000 with all the keys.

## Description

New layout for the 6x9 PCB.

Highlights:

* numpad on the left, with calculator key
* sound controls inn top right

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-08 23:57 UTC, drashna requested changes

2022-08-08 23:57 UTC, drashna commented on keyboards/keebio/bfo9000/keymaps/rogthefrog6x9/config.h
> +#define MASTER_LEFT
Is default behavior, not technically needed.

2022-08-08 23:57 UTC, drashna commented on keyboards/keebio/bfo9000/keymaps/rogthefrog6x9/keymap.c
> +#define _BASE 0
```suggestion
enum custom_layers {
    _BASE,
};
```

2022-08-09 00:18 UTC, rogthefrog commented
@drashna I made your requested changes. Thanks for the review.

2022-08-09 06:41 UTC, drashna approved these changes

2022-08-10 11:19 UTC, fauxpark approved these changes

2022-08-11 01:33 UTC, merged