added keymap for kprepublic/jj40:brdlf
qmk/qmk_firmware pull request #17961
Opened 2022-08-09 02:23 UTC by BRDLF

## Description

Added a new keymap for the kprepublic/jj40 keyboard and the associated rules/readme

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-09 08:14 UTC, zvecr requested changes

2022-08-09 08:14 UTC, zvecr commented on keyboards/kprepublic/jj40/keymaps/brdlf/rules.mk
> +AUDIO_SUPPORTED = no
```suggestion
MOUSEKEY_ENABLE = yes
```

2022-08-09 17:48 UTC, drashna approved these changes

2022-08-13 20:44 UTC, keyboard-magpie requested changes

2022-08-13 20:44 UTC, keyboard-magpie commented on keyboards/kprepublic/jj40/keymaps/brdlf/keymap.c
> +  RESET,   KC_NO,   KC_NO,   BL_ON,   BL_OFF,  KC_NO,   KC_NO,   _______,             _______,             _______,             _______, KC_DEL  ,
```suggestion
  QK_BOOT,   KC_NO,   KC_NO,   BL_ON,   BL_OFF,  KC_NO,   KC_NO,   _______,             _______,             _______,             _______, KC_DEL  ,
```

2022-08-13 20:44 UTC, keyboard-magpie commented on keyboards/kprepublic/jj40/keymaps/brdlf/keymap.c
> +  RESET,   KC_NO,   KC_NO,   BL_ON,   BL_OFF,  KC_NO,   KC_NO,   _______,             _______,             _______,             _______, KC_DEL  ,
RESET is now deprecated.

2022-08-16 03:31 UTC, fauxpark approved these changes

2022-08-20 20:27 UTC, keyboard-magpie approved these changes

2022-08-20 20:28 UTC, merged