add BAMFK-4
qmk/qmk_firmware pull request #17985
Opened 2022-08-10 21:12 UTC by emlah

## Description

add BAMFK-4

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-11 02:28 UTC, drashna requested changes

2022-08-11 02:28 UTC, drashna commented on keyboards/keebio/bamfk4/bamfk4.c
> +#    endif // defined(VIA_ENABLE) && defined(VIA_CUSTOM_LIGHTING_ENABLE)
```suggestion
```

2022-08-11 02:28 UTC, drashna commented on keyboards/keebio/bamfk4/config.h
> +#define VIA_QMK_RGBLIGHT_ENABLE
```suggestion
```

2022-08-12 02:20 UTC, drashna requested changes

2022-08-12 02:20 UTC, drashna commented on keyboards/keebio/bamfk4/config.h
> +#define PRODUCT      BAMFK-4
```suggestion
```

2022-08-13 02:29 UTC, drashna approved these changes

2022-08-13 19:47 UTC, keyboard-magpie approved these changes

2022-08-13 19:47 UTC, merged