[Keyboard] Add Valor FRL TKL rev2.0 and 2.1
qmk/qmk_firmware pull request #17992
Opened 2022-08-11 07:24 UTC by Xelus22

## Description

Add Rev2.0 and Rev2.1 to Valor FRL TKL

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add Rev2.0 and Rev2.1 to Valor FRL TKL

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-11 18:15 UTC, drashna approved these changes

2022-08-13 19:54 UTC, keyboard-magpie requested changes
Minor touch-ups to match new DD changes required.

2022-08-13 19:54 UTC, keyboard-magpie commented on keyboards/xelus/valor_frl_tkl/rev2_0/config.h
> +#define MANUFACTURER    Xelus
Not needed as already present in info.json

2022-08-13 19:54 UTC, keyboard-magpie commented on keyboards/xelus/valor_frl_tkl/rev2_1/config.h
> +#define MANUFACTURER    Xelus
Not needed as already present in info.json

2022-08-14 07:16 UTC, keyboard-magpie approved these changes

2022-08-14 07:17 UTC, merged