Added different wiring of dactyl
qmk/qmk_firmware pull request #17997
Opened 2022-08-11 16:45 UTC by skakunm

## Description
Added a new keyboard, it is similar to the Dactyl, but has 3x5 configuration with 5 thumb keys. Wiring is not compatible with the original dactyl since I used different wiring, so I had to make a different keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-11 18:21 UTC, drashna requested changes

2022-08-11 18:21 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/keymaps/default/config.h
> +#pragma once
None of this is needed, and can be removed.

2022-08-11 18:21 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-08-11 18:21 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/keymaps/default/keymap.c
> +#define _LAYER2 2
```suggestion
enum custom_layers {
    _LAYER0,
    _LAYER1,
    _LAYER2,
};
```

2022-08-11 18:21 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/skakunm_dactyl.c
> +#include "skakunm_dactyl.h"
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-08-11 18:21 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/skakunm_dactyl.h
> +#pragma once
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-08-11 18:21 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/skakunm_dactyl.h
> +#endif
```suggestion
```

2022-08-13 02:12 UTC, drashna commented on keyboards/handwired/skakunm_dactyl/keymaps/default/config.h
> +
This entire file could be removed, as these are the default behaviors.

2022-08-13 20:32 UTC, keyboard-magpie requested changes
This requires a [readme](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md)

2022-08-13 21:43 UTC, keyboard-magpie approved these changes

2022-08-14 00:45 UTC, drashna approved these changes

2022-08-14 00:46 UTC, merged