Add personal keymap for kprepublic BM40HSRGB
qmk/qmk_firmware pull request #18021
Opened 2022-08-13 03:23 UTC by CoffeeIsLife87

## Description

This is the keymap I've been using for months at this point and I think it flows well and is easy to adjust to after coming from a larger sized board ( I was using a TKL before this )

The primary layer is a qwerty layer
The FN/Num/Nav layer is activated with the key to the immediate left of the spacebar
The RGB/Volume/Macro layer is activated with the key to the immediate right of the spacebar

This PR was initially https://github.com/qmk/qmk_firmware/pull/17794 but too many things were done wrong that it was easier to redo it here
I've gone over everything a few times now and I think it's good 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-13 04:47 UTC, drashna requested changes

2022-08-13 04:47 UTC, drashna commented on keyboards/kprepublic/bm40hsrgb/keymaps/coffee/config.h
> +#include "config_common.h"
```suggestion
```

2022-08-13 17:32 UTC, drashna approved these changes

2022-08-13 17:37 UTC, fauxpark requested changes

2022-08-13 17:37 UTC, fauxpark commented on keyboards/kprepublic/bm40hsrgb/keymaps/coffee/rules.mk
> +VIA_ENABLE = no              # Enable VIA
```suggestion
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
LTO_ENABLE = yes
```

2022-08-13 17:41 UTC, fauxpark requested changes

2022-08-13 17:41 UTC, fauxpark commented on keyboards/kprepublic/bm40hsrgb/keymaps/coffee/config.h
> +#    define LED_MATRIX_KEYPRESSES
```suggestion
```

2022-08-13 17:41 UTC, fauxpark commented on keyboards/kprepublic/bm40hsrgb/keymaps/coffee/config.h
> +
```suggestion
```

2022-08-13 17:41 UTC, fauxpark commented on keyboards/kprepublic/bm40hsrgb/keymaps/coffee/config.h
> +#    define LED_MATRIX_LED_FLUSH_LIMIT 10
```suggestion
#    define RGB_MATRIX_LED_FLUSH_LIMIT 10
```

2022-08-13 17:41 UTC, fauxpark commented on keyboards/kprepublic/bm40hsrgb/keymaps/coffee/config.h
> +#    endif
```suggestion
```

2022-08-16 22:44 UTC, fauxpark approved these changes

2022-08-17 07:27 UTC, merged