[Keyboard] Add ibis80
qmk/qmk_firmware pull request #18051
Opened 2022-08-15 01:16 UTC by Runheme

Add ibis80

## Description

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-15 01:20 UTC, zvecr commented on keyboards/mokey/ibis80/config.h
> +
```suggestion
```

2022-08-15 05:38 UTC, drashna requested changes

2022-08-15 05:38 UTC, drashna commented on keyboards/mokey/ibis80/rules.mk
> +NKRO_ENABLE = yes            # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-08-15 17:47 UTC, drashna approved these changes

2022-08-16 03:33 UTC, fauxpark requested changes

2022-08-16 03:33 UTC, fauxpark commented on keyboards/mokey/ibis80/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-08-16 22:43 UTC, fauxpark approved these changes

2022-08-17 02:37 UTC, merged