add new keyboard 'soda/cherish'
qmk/qmk_firmware pull request #18057
Opened 2022-08-15 09:27 UTC by gezhaoyou

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-15 17:53 UTC, drashna requested changes

2022-08-15 17:53 UTC, drashna commented on keyboards/soda/cherish/config.h
> +#define PRODUCT         Cherish-75
```suggestion
```

2022-08-15 17:53 UTC, drashna commented on keyboards/soda/cherish/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-08-15 17:53 UTC, drashna commented on keyboards/soda/cherish/info.json
> +    "layouts": {
```suggestion
    "manufacturer": "gezhaoyou",
    "usb": {
        "vid": "0xEB50",
        "pid": "0xEB52",
        "device_version": "0.0.1"
    },
    "layouts": {
```

2022-08-15 17:53 UTC, drashna commented on keyboards/soda/cherish/info.json
> +    "keyboard_name": "75% ANSI layout",
```suggestion
    "keyboard_name": "Cherish-75",
```

2022-08-15 17:53 UTC, drashna commented on keyboards/soda/cherish/rules.mk
> +VIA_ENABLE = yes
VIA should be enabled at the keymap level, not the keyboard level.
```suggestion
```

2022-08-16 22:44 UTC, fauxpark approved these changes

2022-08-17 07:26 UTC, drashna approved these changes

2022-08-17 07:26 UTC, merged