Add Crin PCB to QMK
qmk/qmk_firmware pull request #18065
Opened 2022-08-15 15:39 UTC by awkannan

## Description

Adding Crin PCB to QMK

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-15 16:56 UTC, zvecr requested changes

2022-08-15 16:56 UTC, zvecr commented on keyboards/cannonkeys/crin/halconf.h
> +#define HAL_USE_SPI TRUE
```suggestion
#define HAL_USE_PWM TRUE
```

2022-08-15 16:56 UTC, zvecr commented on keyboards/cannonkeys/crin/mcuconf.h
> +#define STM32_SPI_USE_SPI2 TRUE
```suggestion
#undef STM32_PWM_USE_TIM3
#define STM32_PWM_USE_TIM3 TRUE
```

2022-08-16 21:52 UTC, awkannan commented
@zvecr Thank you for the catch!

2022-08-30 21:28 UTC, awkannan commented
@drashna This one is a bit weird, as zvecr's suggested changes did not make it in before the prior PR was merged.
I think we should still merge these.

2022-10-21 05:17 UTC, drashna approved these changes

2023-01-06 02:20 UTC, tzarc approved these changes

2023-01-07 15:16 UTC, fauxpark approved these changes

2023-02-02 21:32 UTC, merged