New keyboard for the QMK Master
qmk/qmk_firmware pull request #18081
Opened 2022-08-17 02:49 UTC by AliceH66

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-17 07:05 UTC, drashna requested changes

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/info.json
> +    "maintainer": "AliceH66",
```suggestion
    "maintainer": "AliceH66",
    "manufacturer": AlliceH",
    "usb": {
        "device_version": "1.0.0",
        "pid": "0x7066",
        "vid": "0x6168"
    },
```

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/keymaps/via/rules.mk
> +VIAL_ENABLE = yes
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs
> Vial-related files or changes will not be accepted, as they are not used by QMK firmware (no Vial-specific core code has been submitted or merged)

```suggestion
```

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/keymaps/vial/config.h
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs
> Vial-related files or changes will not be accepted, as they are not used by QMK firmware (no Vial-specific core code has been submitted or merged)

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/keymaps/vial/keymap.c
> +/*
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs
> Vial-related files or changes will not be accepted, as they are not used by QMK firmware (no Vial-specific core code has been submitted or merged)

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/keymaps/vial/pianoforte/pianoforte.json
> +{
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs
> Vial-related files or changes will not be accepted, as they are not used by QMK firmware (no Vial-specific core code has been submitted or merged)

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/keymaps/vial/rules.mk
> +VIA_ENABLE = yes
https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs
> Vial-related files or changes will not be accepted, as they are not used by QMK firmware (no Vial-specific core code has been submitted or merged)

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/config.h
> +#define PRODUCT         pianoforte_hotswap
```suggestion
```

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/info.json
> +    "maintainer": "AliceH66",
```suggestion
    "maintainer": "AliceH66",
    "manufacturer": AliceH",
    "usb": {
        "device_version": "1.0.0",
        "pid": "0x7068",
        "vid": "0x6168"
    },
```

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/keymaps/via/rules.mk
> +VIAL_ENABLE = yes
```suggestion
```

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/keymaps/vial/config.h
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
same

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/keymaps/vial/pianoforte_hs/pianoforte_hs.json
> +{
same

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/rules.mk
> +QMK_SETTINGS = no 			# QMK Settings
```suggestion
```

2022-08-17 07:05 UTC, drashna commented on keyboards/aliceh66/pianoforte/rules.mk
> +QMK_SETTINGS = no			# QMK Settings
```suggestion
```

2022-08-17 21:56 UTC, AliceH66 commented
I committed to the suggestions and removed the VIAL files, I believe that should be it?

2022-08-18 04:51 UTC, drashna requested changes

2022-08-18 04:51 UTC, drashna commented on keyboards/aliceh66/pianoforte/config.h
> +#define VIAL_UNLOCK_COMBO_COLS { 0, 6 }
```suggestion
```

2022-08-18 04:51 UTC, drashna commented on keyboards/aliceh66/pianoforte_hs/config.h
> +#define VIAL_UNLOCK_COMBO_COLS { 0, 6 }
```suggestion
```

2022-08-18 16:52 UTC, drashna approved these changes

2022-08-18 23:28 UTC, fauxpark requested changes

2022-08-18 23:28 UTC, fauxpark commented on keyboards/aliceh66/pianoforte_hs/info.json
> +    "manufacturer": AliceH",
```suggestion
    "keyboard_name": "pianoforte hotswap",
    "manufacturer": "AliceH",
    "url": "https://github.com/AliceH66",
    "maintainer": "AliceH66",
```

2022-08-18 23:28 UTC, fauxpark commented on keyboards/aliceh66/pianoforte/info.json
> +    "manufacturer": AlliceH",
```suggestion
    "keyboard_name": "pianoforte solder",
    "manufacturer": "AliceH",
    "url": "https://github.com/AliceH66",
    "maintainer": "AliceH66",
```

2022-08-19 21:42 UTC, fauxpark requested changes

2022-08-19 21:42 UTC, fauxpark commented on keyboards/aliceh66/pianoforte/readme.md
> +	make aliceh66/pianoforte:default
```suggestion

    make aliceh66/pianoforte:default
```

2022-08-19 21:42 UTC, fauxpark commented on keyboards/aliceh66/pianoforte/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
```

2022-08-19 21:42 UTC, fauxpark commented on keyboards/aliceh66/pianoforte_hs/readme.md
> +	make aliceh66/pianoforte_hs:default
```suggestion

    make aliceh66/pianoforte_hs:default
```

2022-08-19 21:42 UTC, fauxpark commented on keyboards/aliceh66/pianoforte_hs/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
```

2022-08-20 01:38 UTC, fauxpark approved these changes

2022-08-20 01:55 UTC, merged