Add om60 rev1 keyboard
qmk/qmk_firmware pull request #18126
Opened 2022-08-21 13:09 UTC by jun10000

## Description

Initial PR for adding om60 rev1 keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
None

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-21 18:24 UTC, drashna requested changes

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/config.h
> +#define PRODUCT         OM60
```suggestion
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/config.h
> +#define UNUSED_PINS
```suggestion
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/config.h
> +#define ENCODERS_CW_KEY  { {6, 6} }
```suggestion
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/encoder.c
> +/* Copyright 2021 3araht
Please remove this file, and use encoder map instead. 

https://docs.qmk.fm/#/feature_encoders?id=encoder-map

And via does support this.

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/info.json
> +  "maintainer": "jun10000",
```suggestion
  "maintainer": "jun10000", 
  "usb": {
      "vid": "0x6A6E",
      "pid": "0x0001",
      "device_version": "0.0.1",
  }
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/keymaps/default/config.h
> +#define RGBLIGHT_SLEEP
This should probably be moved to the keyboard's config.h

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/keymaps/via/config.h
> +#define RGBLIGHT_SLEEP
Same

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/readme.md
> +* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```suggestion
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/om60.h
> +    E0L, E0R, \
```suggestion
```

2022-08-21 18:24 UTC, drashna commented on keyboards/om60/om60.h
> +    {   R42,   R47,   R52,   R57,   R62,   R67,   E0R, KC_NO }, \
```suggestion
    {   R41,   R46,   R51,   R56,   R61,   R66,   KC_NO, KC_NO }, \
    {   R42,   R47,   R52,   R57,   R62,   R67,   KC_NO, KC_NO }, \
```

2022-08-23 02:03 UTC, drashna commented on keyboards/om60/keymaps/via/keymap.c
> +    [3] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
Heads up, you can fill these with transparent keycodes, just like the normal keymap. 

```suggestion
    [1] = { ENCODER_CCW_CW(_______, _______) },
    [2] = { ENCODER_CCW_CW(_______, _______) },
    [3] = { ENCODER_CCW_CW(_______, _______) },
```

2022-08-23 02:04 UTC, drashna approved these changes

2022-08-25 05:10 UTC, fauxpark requested changes

2022-08-25 05:10 UTC, fauxpark commented on keyboards/om60/info.json
> +  "keyboard_name": "OM60",
```suggestion
  "keyboard_name": "OM60", 
  "manufacturer": "jun10000",
```

2022-09-02 04:37 UTC, jun10000 commented
Thank you for fixing the encoder map feature.
It correctly works in the via (https://usevia.app/#/).

2022-09-09 04:41 UTC, jun10000 commented
@fauxpark
Is there any problems?

2022-09-09 04:50 UTC, fauxpark requested changes

2022-09-09 04:50 UTC, fauxpark commented on keyboards/om60/matrix.c
> +#    define ROW_SHIFTER  ((uint32_t)1)
```suggestion
#    define ROW_SHIFTER ((uint8_t)1)
#elif (MATRIX_COLS <= 16)
#    define ROW_SHIFTER ((uint16_t)1)
#elif (MATRIX_COLS <= 32)
#    define ROW_SHIFTER  ((uint32_t)1)
```

2022-09-13 06:07 UTC, jun10000 commented
@fauxpark
Are there another problems?

2022-09-14 07:38 UTC, fauxpark approved these changes

2022-09-14 17:55 UTC, drashna requested changes

2022-09-14 17:55 UTC, drashna commented on keyboards/om60/rules.mk
> +ENCODER_MAP_ENABLE = yes
This should not be enabled at the keyboard level.   Please move this to the keymap level. 

```suggestion
```

2022-09-24 07:37 UTC, drashna approved these changes

2022-09-24 07:38 UTC, merged