[Keyboard] Add Shoc Keyboard
qmk/qmk_firmware pull request #18143
Opened 2022-08-23 08:40 UTC by JannikB5825

Pull request for a new keyboard to mainline

## Description

Keyboard and keymap definition for a new Shoc Keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-23 08:42 UTC, fauxpark commented
This code is incomplete and outdated. Please create the board with `qmk new-keyboard` and follow the PR checklist.

2022-08-23 18:06 UTC, drashna requested changes

2022-08-23 20:28 UTC, drashna commented on keyboards/shoc/config.h
> +#define PRODUCT         SHOC
```suggestion
```

2022-08-23 20:38 UTC, drashna approved these changes

2022-08-24 00:27 UTC, fauxpark requested changes

2022-08-24 00:27 UTC, fauxpark commented on keyboards/shoc/rules.mk
> +MCU = atmega32u4
```suggestion
```

2022-08-24 00:27 UTC, fauxpark commented on keyboards/shoc/info.json
> +    "keyboard_name": "Shoc",
```suggestion
    "keyboard_name": "Shoc",
    "manufacturer": "JannikB5825",
```

2022-08-24 00:27 UTC, fauxpark commented on keyboards/shoc/info.json
> +    "diode_direction": "COL2ROW",
```suggestion
    "diode_direction": "COL2ROW",
    "processor": "atmega32u4",
    "bootloader": "caterina",
```

2022-08-30 10:03 UTC, fauxpark requested changes

2022-08-30 10:03 UTC, fauxpark commented on keyboards/shoc/rules.mk
> +WPM_ENABLE = yes
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes
```

2022-09-02 02:52 UTC, fauxpark approved these changes

2022-09-02 03:48 UTC, merged