Adding the arcboard-mk9 keymap and my userspace
qmk/qmk_firmware pull request #18167
Opened 2022-08-25 23:30 UTC by christrotter

## Description

This is the final working code for the first generation (mk9/10/11) keyboard I made.  It is a clone of Drashna's tractyl board/userspace, but has since been heavily mashed/modded.

The board uses the auto-mouse layer and PMW-3360 features, plus RBB matrix and some layers, plus the transport/other insanity Drashna came up with.

I've also included the STL and Fusion360 files, plus my simple build script.

I'm effectively abandoning the code as the next generation is ready for coding (mk13), but others might want to build the old gen.

Some changes I might have made if this was a 'real thing'...
- renaming the board (and all the files)
- undoing the horror of the layout, due to moving away from a multi-kb dir structure to single-kb

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-25 23:30 UTC, christrotter commented
My sincere apologies for not squashing the commits...I know it's bad practice, but it's not part of my workflow yet.  Jeff would yell at me.

2022-08-25 23:33 UTC, christrotter commented
Also, the branch was pretty old, and I did my best to merge in latest master, but had issues w. qmk doctor/chibios after moving to a new laptop.  Let me know what i should do about the lib dir... i think delete...?

2022-08-26 00:29 UTC, zvecr commented
Adding the `invalid` label due to:
* Submodule changes which need to be reverted
* addition of "drashna" keymaps
* > I've also included the STL and Fusion360 files, plus my simple build script.
  * These will not be accepted to the qmk_firmware repo and should be hosted elsewhere.

2022-08-26 00:41 UTC, christrotter commented
> Adding the `invalid` label due to:
> 
> * Submodule changes which need to be reverted

Do you have any guidance on why this would be an issue - like, how on earth did I manage to get lib stuff in play?  I have been trying to stick to what qmk doctor tells me, plus doing upstream master/develop re-syncs.

Right now that branch breaks on qmk doctor, chibios clone blows up.

![image](https://user-images.githubusercontent.com/8292406/186792611-97312032-e2d7-41ef-a665-372b4a5847c9.png)

As a result of this, I get lib issues.  Thoughts?

2022-08-26 10:45 UTC, christrotter commented
Okie dokie, removed the stuff you requested.  And magically qmk-doctor is fine now.  Kay so ... anyways, let me know if you would like other improvements.

2022-08-28 16:51 UTC, drashna requested changes
Honestly, a lot of this could be simply moved to something like:
```
keyboards/handwired/tractyl_manuform/5x6_right_massive/
```

That would significantly reduce the duplication here, and be easier to maintain, long term. 


Also, there is a lot of overlap here between user and keyboard code, which is problematic. (try compiling the default keymap, for instance).

2022-08-28 16:51 UTC, drashna commented on keyboards/handwired/tractyl_manuform_ct/5x6_right/5x6_right.c
> +#include "christrotter.h"
User files shouldn't be included in keyboard files.  If you compile the default keymap, this will likely fail.
```suggestion
```

2022-08-28 16:51 UTC, drashna commented on keyboards/handwired/tractyl_manuform_ct/5x6_right/config.h
> +    #        define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_STATE_SYNC, RPC_ID_USER_KEYMAP_SYNC, RPC_ID_USER_CONFIG_SYNC, RPC_ID_USER_WATCHDOG_SYNC, RPC_ID_USER_KEYLOG_STR
shouldn't be at keyboard level
```suggestion
```

2022-08-28 19:44 UTC, christrotter commented
> Honestly, a lot of this could be simply moved to something like:
> 
> ```
> keyboards/handwired/tractyl_manuform/5x6_right_massive/
> ```
> 
> That would significantly reduce the duplication here, and be easier to maintain, long term.
> 
> Also, there is a lot of overlap here between user and keyboard code, which is problematic. (try compiling the default keymap, for instance).

Yeah ok so that answers what I kinda had in the back of my mind - I have no intentions of supporting this going forward, it's a failed prototype to me.  The reason why I'd made the PR was really historical reasons - a few people had mentioned interest in the code.  If duplication is a factor (and well it should be!) then I think we should close this and I'll just refer people to the tractyl code going forward.  

I have learned much in this process, however, so not waste to delete this.
- contributed keyboards are viewed as supported products (dear user, get started by getting the default map working, create your own if you wish!)
- the role of userspace/keymap vs. keyboard code (keyboard should work out of the box, user/keymap is above-beyond customization)
- contributing rando stuff is for other places (totally makes sense!)

So having thus taught me, I thank you, and shall close this PR.  The next keyboard (already underway) I will endeavour to keep to these principles!  Thanks!

2022-08-28 19:44 UTC, closed without merging