new keyboard rb1
qmk/qmk_firmware pull request #18164
Opened 2022-08-25 16:00 UTC by ryanbaekr

## Description

Added new keyboard: ryanbaekr rb1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-26 05:31 UTC, drashna approved these changes

2022-08-26 05:38 UTC, fauxpark requested changes

2022-08-26 05:38 UTC, fauxpark commented on keyboards/ryanbaekr/rb1/info.json
> +                {"x":0, "y":0}
```suggestion
                {"matrix": [0, 0], "x":0, "y":0}
```
rb1.[ch] can be deleted with this :)

2022-11-25 22:52 UTC, fauxpark requested changes

2022-11-25 22:52 UTC, fauxpark commented on keyboards/ryanbaekr/rb1/config.h
> +
```suggestion
```

2022-11-25 22:52 UTC, fauxpark commented on keyboards/ryanbaekr/rb1/config.h
> +#define UNUSED_PINS
```suggestion
```

2022-11-25 22:52 UTC, fauxpark commented on keyboards/ryanbaekr/rb1/config.h
> +
```suggestion
```

2022-11-25 22:59 UTC, fauxpark approved these changes

2022-11-28 05:45 UTC, zvecr approved these changes

2022-11-28 05:46 UTC, merged