Add a new keyboard `Lunakey Pico`.
qmk/qmk_firmware pull request #18202
Opened 2022-08-29 10:07 UTC by yoichiro

This pull request adds a new keyboard designed by @yoichiro to the QMK Firmware.

## Description

I sent this pull request to add a new keyboard named "Lunakey Pico" to the QMK Firmware. I created both the simple default key mappings definition and the key mappings definition for VIA.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-29 14:19 UTC, zvecr requested changes

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/rules.mk
> +# This file intentionally left blank
```suggestion
```

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/keymaps/default/rules.mk
> +# This file intentionally left blank
This file should be removed

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/config.h
> +#define PERMISSIVE_HOLD
We generally ask this to be defined at the keymap level instead
```suggestion
```

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/keymaps/via/keymap.c
> +}
```suggestion
```

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/keymaps/via/keymap.c
> +#define RAISE MO(_RAISE)
```suggestion
#define LOWER FN_MO13
#define RAISE FN_MO23
```

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/lunakey_pico.c
> +//}
```suggestion
```

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/mcuconf.h
> +//#define RP_SERIAL_USE_UART1 FALSE
```suggestion
```

2022-08-29 14:19 UTC, zvecr commented on keyboards/yoichiro/lunakey_pico/halconf.h
> +//#define HAL_USE_SERIAL TRUE
```suggestion
```

2022-08-29 21:30 UTC, yoichiro commented on keyboards/yoichiro/lunakey_pico/keymaps/default/rules.mk
> +# This file intentionally left blank
I removed this file at f532758.

2022-08-29 21:55 UTC, yoichiro commented
@zvecr Thank you for many suggestions! Could you review them again?

2022-08-30 03:08 UTC, drashna requested changes

2022-08-30 03:08 UTC, drashna commented on keyboards/yoichiro/lunakey_pico/info.json
> +            "all": true
Could you explicitly define the animations:
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": false,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2022-08-30 03:28 UTC, yoichiro commented
@drashna Thank you the suggestion! I committed your suggestion just now. Could you review this again?

2022-08-30 03:29 UTC, drashna approved these changes

2022-08-30 03:54 UTC, fauxpark requested changes

2022-08-30 03:54 UTC, fauxpark commented on keyboards/yoichiro/lunakey_pico/readme.md
> +![lunakey_pico](https://i.imgur.com/S5N8AFh.jpg)
```suggestion
![lunakey_pico](https://i.imgur.com/S5N8AFhh.jpg)
```

2022-08-30 04:22 UTC, yoichiro commented
@fauxpark Thank you for the suggestion! I committed the suggestion just now.

2022-08-31 23:47 UTC, yoichiro commented
@drashna @fauxpark @zvecr Is there something else I should do?

2022-09-02 02:50 UTC, fauxpark approved these changes

2022-09-02 03:54 UTC, merged