Add absolute key positions to microdox info.json
qmk/qmk_firmware pull request #18238
Opened 2022-08-31 21:30 UTC by timtraversy

## Description

Without these values the QMK Configurator doesn't know how to layout the board visually.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/qmk/qmk_configurator/issues/1179

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-08-31 21:39 UTC, timtraversy commented
@waffle87 did you mean to remove these in #17675?

2022-08-31 22:08 UTC, zvecr requested changes

2022-08-31 22:08 UTC, zvecr commented on keyboards/boardsource/microdox/info.json
> +        { "matrix": [7, 2], "x": 7, "y": 4.375 }
Order is incorrect, should be:
```json
        { "matrix": [0, 0], "x": 0, "y": 0.375 },
        { "matrix": [0, 1], "x": 1, "y": 0.125 },
        { "matrix": [0, 2], "x": 2, "y": 0 },
        { "matrix": [0, 3], "x": 3, "y": 0.125 },
        { "matrix": [0, 4], "x": 4, "y": 0.375 },
        { "matrix": [4, 4], "x": 7, "y": 0.375 },
        { "matrix": [4, 3], "x": 8, "y": 0.125 },
        { "matrix": [4, 2], "x": 9, "y": 0 },
        { "matrix": [4, 1], "x": 10, "y": 0.125 },
        { "matrix": [4, 0], "x": 11, "y": 0.375 },
        { "matrix": [1, 0], "x": 0, "y": 1.375 },
        { "matrix": [1, 1], "x": 1, "y": 1.125 },
        { "matrix": [1, 2], "x": 2, "y": 1 },
        { "matrix": [1, 3], "x": 3, "y": 1.125 },
        { "matrix": [1, 4], "x": 4, "y": 1.375 },
        { "matrix": [5, 4], "x": 7, "y": 1.375 },
        { "matrix": [5, 3], "x": 8, "y": 1.125 },
        { "matrix": [5, 2], "x": 9, "y": 1 },
        { "matrix": [5, 1], "x": 10, "y": 1.125 },
        { "matrix": [5, 0], "x": 11, "y": 1.375 },
        { "matrix": [2, 0], "x": 0, "y": 2.375 },
        { "matrix": [2, 1], "x": 1, "y": 2.125 },
        { "matrix": [2, 2], "x": 2, "y": 2 },
        { "matrix": [2, 3], "x": 3, "y": 2.125 },
        { "matrix": [2, 4], "x": 4, "y": 2.375 },
        { "matrix": [6, 4], "x": 7, "y": 2.375 },
        { "matrix": [6, 3], "x": 8, "y": 2.125 },
        { "matrix": [6, 2], "x": 9, "y": 2 },
        { "matrix": [6, 1], "x": 10, "y": 2.125 },
        { "matrix": [6, 0], "x": 11, "y": 2.375 },
        { "matrix": [3, 2], "x": 2, "y": 4 },
        { "matrix": [3, 3], "x": 3, "y": 4.125},
        { "matrix": [3, 4], "x": 4, "y": 4.375 },
        { "matrix": [7, 4], "x": 7, "y": 4.375 },
        { "matrix": [7, 3], "x": 8, "y": 4.125 },
        { "matrix": [7, 2], "x": 9, "y": 4 }
```

2022-09-03 14:36 UTC, zvecr approved these changes

2022-09-03 14:41 UTC, fauxpark approved these changes

2022-09-03 14:47 UTC, merged