fix data-driven split handedness pin assignement
qmk/qmk_firmware pull request #18254
Opened 2022-09-03 12:05 UTC by Kriechi

Rename 'primary' to 'main' and assign correct values.

## Description

This PR fixes an issue with data-driven options for setting SPLIT_HAND_PIN.
There was a mix of `split.primary` and `split.main` used in the json schema.
Since the only usage I could find were two keyboards, both using `main`, I chose this one.

Added the missing `split.pin` key to the json schema, to be used and then set the actual pin as:
```json
"split": { 
    "enabled": true,
    "main": "pin",
    "pin": "GP4"
}
```

## Types of Changes

- [X] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-03 13:11 UTC, sigprof commented
The more important question is why `main` is even used here? The handedness options do not select which side of the keyboard is “main”/“master”, they select which side is left (but the default method is driven by the master detection status). Only the `"main": "left"` and `"main": "right"` values make some sense.

The handedness configuration should probably look like this:
```json
"split": {
    "side_detection": {
        "method": "pin",
        "pin": "GP4",
        "low_side": "left"
    }
}
```
```json
"split": {
    "side_detection": {
        "method": "matrix_grid",
        "matrix_grid": ["GP4", "GP10"],
        "low_side": "left"
    }
}
```
```json
"split": {
    "side_detection": {
        "method": "eeprom"
    }
}
```
```json
"split": {
    "side_detection": {
        "method": "main_status",
        "main_side": "left"
    }
}
```
To avoid confusing defaults, we could make the `low_side` parameter mandatory when `"method": "pin"` or `"method": "matrix_grid"` is specified in JSON (currently at the C level `SPLIT_HAND_PIN` defaults to `"low_side": "right"`, but `SPLIT_HAND_MATRIX_GRID` defaults to `"low_side": "left"`); alternatively we could do a breaking change for `SPLIT_HAND_PIN`, but that might be a lot of work.

2022-09-03 15:15 UTC, Kriechi commented
Thanks @sigprof - this makes way more sense!

I've pushed the changes - with small changes to your proposed naming.
I did not add strict validation / error throwing for weird combinations, with the idea that somebody might want to configure "pin" method, while keeping the line for matrix_grid for debugging or other reasons. So whatever the method is set to - will only read the fields that are actually needed by the currently selected method.

And I think I got away with all the LOW/HIGH default handling without too much issues - please verify.

2022-09-22 21:33 UTC, fauxpark requested changes

2022-09-22 21:33 UTC, fauxpark commented on lib/python/qmk/cli/generate/config_h.py
> +            config_h_lines.append('#   endif // MASTER_RIGHT')
```suggestion
            config_h_lines.append('#    ifndef MASTER_RIGHT')
            if kb_info_json['split']['side_detection']['determined_side'] == 'left':
                config_h_lines.append('#        define MASTER_LEFT')
            elif kb_info_json['split']['side_detection']['determined_side'] == 'right':
                config_h_lines.append('#        define MASTER_RIGHT')
            config_h_lines.append('#    endif // MASTER_RIGHT')
```

2022-09-23 18:04 UTC, Kriechi commented on lib/python/qmk/cli/generate/config_h.py
> +            config_h_lines.append('#   endif // MASTER_RIGHT')
Thanks - included now!

2022-09-25 11:38 UTC, daskygit commented
There's been some further discussion on [discord](https://discord.com/channels/440868230475677696/867530715192885269/1022614573011963924) with no resolution.

Quick recap is I'd like to see the options renamed with `method: usb' requiring it's own further configuration option. For example,

```json
"split": {
    "handedness": {
        "method": "pin|matrix_grid|eeprom|usb",
        "pin": "GP1",
        "matrix_grid": ["GP1", "GP2"],
        "active_low": "left|right",
        "usb_side": "left|right"
    }
}
```

2022-10-22 09:27 UTC, evils commented on data/schemas/keyboard.jsonschema
> +                    "$comment": "deprecated - see side_detection instead",
seems like that maybe got renamed?

```suggestion
                    "$comment": "deprecated - see handedness instead",
                    "deprecated": true,
                    "type": "string",
                    "enum": ["eeprom", "left", "matrix_grid", "pin", "right"]
                },
                "matrix_grid": {
                    "$comment": "deprecated - see handedness instead",
```

2022-10-22 11:20 UTC, Kriechi commented on data/schemas/keyboard.jsonschema
> +                    "$comment": "deprecated - see side_detection instead",
Yes! Thanks!

2023-04-15 13:14 UTC, Kriechi commented
bump - please assign *awaiting review* label, or close directly.

2023-11-01 12:36 UTC, Kriechi commented
Partially implemented and superseeded by #22369.

2024-07-18 13:42 UTC, zvecr commented
Closing as I plan to re-implement based on the current state of the repo.

2024-07-18 13:42 UTC, closed without merging