Add pascalpfeil keymap for gmmk pro
qmk/qmk_firmware pull request #18267
Opened 2022-09-04 17:28 UTC by pascalpfeil

## Description

Add pascalpfeil keymap for gmmk pro

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-12 23:36 UTC, spidey3 approved these changes

2022-09-13 00:08 UTC, fauxpark requested changes

2022-09-13 00:08 UTC, fauxpark commented on keyboards/gmmk/pro/ansi/keymaps/pascalpfeil/keymap.c
> +            RGB_MATRIX_INDICATOR_SET_COLOR(right_side_leds[i], 0xFF, 0x00, 0x00); // set to red
```suggestion
    led_t led_state = host_keyboard_led_state();
    if (led_state.caps_lock)
        for (uint8_t i = 0; i < left_side_leds_size; i++)
            RGB_MATRIX_INDICATOR_SET_COLOR(left_side_leds[i], 0xFF, 0x00, 0x00); // set to red

    if (led_state.num_lock)
        for (uint8_t i = 0; i < right_side_leds_size; i++)
            RGB_MATRIX_INDICATOR_SET_COLOR(right_side_leds[i], 0xFF, 0x00, 0x00); // set to red
```

2022-09-24 18:48 UTC, drashna commented on keyboards/gmmk/pro/ansi/keymaps/pascalpfeil/keymap.c
> +bool encoder_update_user(uint8_t index, bool clockwise) {
Just a heads up, you may want to convert this over to encoder map.

2022-12-29 02:00 UTC, closed without merging