Add the Plywrks Allaro
qmk/qmk_firmware pull request #18275
Opened 2022-09-05 15:57 UTC by ramonimbao

## Description

Add the Plywrks Allaro.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-14 16:21 UTC, drashna requested changes

2022-09-20 00:56 UTC, drashna requested changes

2022-09-20 00:56 UTC, drashna commented on keyboards/plywrks/allaro/info.json
> +            "all": true
Could you explicitly enable the animation modes? 
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2022-09-24 07:02 UTC, drashna approved these changes

2022-09-24 07:05 UTC, fauxpark approved these changes

2022-09-24 18:49 UTC, merged