Add some feature to rgb/led matrix for wireless application
qmk/qmk_firmware pull request #18285
Opened 2022-09-06 06:20 UTC by lokher

## Description

Add LED/RGB_MATRIX_DRIVER_SHUTDOWN_ENABLE feature to save power.
Add LED/RGB_MATRIX_BRIGHTNESS_TURN_OFF_VAL feature to turn off backlight if brightness is too low.
Enhance LED_DISABLE_TIMEOUT feature.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-04 07:27 UTC, drashna requested changes

2022-12-04 07:27 UTC, drashna commented on quantum/led_matrix/led_matrix.c
> +static uint32_t led_disable_timeout = LED_DISABLE_TIMEOUT;
`LED_DISABLE_TIMEOUT` has been renamed  to `LED_MATRIX_TIMEOUT`.  All instances of this needs to be updated.

2022-12-04 07:27 UTC, drashna commented on quantum/rgb_matrix/rgb_matrix.c
> +static uint32_t rgb_disable_timeout = RGB_DISABLE_TIMEOUT;
Same here. `RGB_MATRIX_TIMEOUT`, in this case.

2023-02-04 02:28 UTC, zvecr requested changes
* `LED_MATRIX_DRIVER_SHUTDOWN_ENABLE` doeesnt really align with other configuration variables
* No docs have been updated

2023-02-04 02:28 UTC, zvecr commented on quantum/led_matrix/led_matrix.c
> +    led_matrix_driver.shutdown();
This isnt safe, as the other backend drivers do not implement the function. They should be explicitly initialled to NULL and  `led_matrix_driver.shutdown`  checked before use

2023-05-14 01:57 UTC, closed without merging