Uni v4 keyboard add
qmk/qmk_firmware pull request #18280
Opened 2022-09-05 21:17 UTC by petercpark

## Description

Adding another keyboard version. [The Uni v4](https://stenokeyboards.com/products/the-uni-v4) uses the rp2040 chip.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-05 22:32 UTC, zvecr requested changes

2022-09-05 22:32 UTC, zvecr commented on keyboards/the_uni/rp_2040/config.h
> +
```suggestion
```

2022-09-05 22:32 UTC, zvecr commented on keyboards/the_uni/rp_2040/rules.mk
> +
```suggestion

```

2022-09-05 22:32 UTC, zvecr commented on keyboards/the_uni/rp_2040/rp_2040.c
> +#include QMK_KEYBOARD_H
```suggestion
```

2022-09-05 22:32 UTC, zvecr commented on keyboards/the_uni/rp_2040/config.h
> +
Should be configured like `keyboards/the_uni/usb_c/info.json`
```suggestion

```

2022-09-14 16:05 UTC, drashna commented on keyboards/the_uni/rp_2040/readme.md
> +![Uni v4](https://cdn.shopify.com/s/files/1/0581/6798/4289/products/top4_1680x.png)
please rehost this image on Imgur

2022-09-20 01:02 UTC, drashna requested changes

2022-09-20 01:02 UTC, drashna commented on keyboards/the_uni/rp_2040/readme.md
> +![Uni v4](https://i.imgur.com/HyvMu26.png?1)
```suggestion
![Uni v4](https://i.imgur.com/HyvMu26h.png)
```

2022-09-24 18:51 UTC, drashna requested changes

2022-09-24 18:51 UTC, drashna commented on keyboards/the_uni/pro_micro/readme.md
> +![Uni v2](https://github.com/petercpark/The_Uni/blob/main/Pics/uni%20v2/uni-v2.JPG?raw=true)
Please rehost on Imgur.

2022-09-30 23:08 UTC, drashna approved these changes

2022-09-30 23:18 UTC, fauxpark requested changes

2022-09-30 23:18 UTC, fauxpark commented on keyboards/the_uni/rp_2040/rules.mk
> +BOOTLOADER = rp2040
```suggestion

# Bootloader selection
BOOTLOADER = rp2040

```

2022-10-01 17:43 UTC, drashna approved these changes

2022-10-01 17:50 UTC, fauxpark approved these changes

2022-10-01 17:56 UTC, merged