add rart80
qmk/qmk_firmware pull request #18287
Opened 2022-09-06 06:28 UTC by alabahuy

## Description

Add Rart80 and support via

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-14 16:04 UTC, drashna requested changes

2022-09-14 16:04 UTC, drashna commented on keyboards/rart/rart80/readme.md
> +![RART 80](https://i.imgur.com/QCeTuBe.png)
```suggestion
![RART 80](https://i.imgur.com/QCeTuBeh.png)
```

2022-09-15 02:11 UTC, alabahuy commented on keyboards/rart/rart80/readme.md
> +![RART 80](https://i.imgur.com/QCeTuBe.png)
Done :)

2022-09-20 01:06 UTC, drashna approved these changes

2022-09-26 07:17 UTC, fauxpark approved these changes

2022-09-28 19:23 UTC, merged