Correct microdox/v2 pins and organize common defs
qmk/qmk_firmware pull request #18318
Opened 2022-09-09 15:22 UTC by timtraversy

## Description

I flashed my v2 microdox a few days ago, but none of the switches were working. I looked at the firmware and realized that the `config.h` files were incorrectly configured. The config in the `microdox` folder defined the `v1` pins, and the `v2` config didn't override these values. The `info.json` files *are* correct, so I based the `config.h` updates of those.

I left all shared configuration in the parent `config.h`, and put version specific configs in the folders.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- But I only have a v2 microdox, so I can't test this for v1.

2022-09-09 16:13 UTC, zvecr requested changes
These are now in info.json

2022-09-09 16:13 UTC, zvecr commented on keyboards/boardsource/microdox/config.h
> +
```suggestion
```

2022-09-09 16:13 UTC, zvecr commented on keyboards/boardsource/microdox/v1/config.h
> +#define DEVICE_VER 0x0100
```suggestion
```

2022-09-09 16:13 UTC, zvecr commented on keyboards/boardsource/microdox/v2/config.h
> +
```suggestion
```

2022-09-09 17:37 UTC, zvecr commented
Just as an FYI, most of the changes in this PR are incorrect as they are duplicating content already configured within `info.json`. Matrix pins, encoders, etc.

2022-09-11 17:12 UTC, timtraversy commented
Ahh I thought `info.json` was just for the API, and `config.h` was for compiling. Closing in favor of yours.

2022-09-11 17:12 UTC, closed without merging