Add Pila87/XM87 Pro
qmk/qmk_firmware pull request #18329
Opened 2022-09-10 20:16 UTC by Pangorin

## Description

Add support for the Pila87/XM87 Pro

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

Add support for the Pila87/XM87 Pro

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-11 12:43 UTC, Pangorin reviewed
Delete some old files

2022-09-12 15:54 UTC, drashna requested changes
the animation c files need licenses headers, too

2022-09-12 15:54 UTC, drashna commented on keyboards/pangorin/pila87_mod/config.h
> +#define PRODUCT         Pila87
Please move these values to the info.json file.

2022-09-12 15:54 UTC, drashna commented on keyboards/pangorin/pila87_mod/config.h
> +#define FORCE_NKRO
This can cause issues on some systems.

2022-09-12 15:54 UTC, drashna commented on keyboards/pangorin/pila87_mod/config.h
> +#define USB_POLLING_INTERVAL_MS 1
this is the default behavior already. 
```suggestion
```

2022-09-12 15:54 UTC, drashna commented on keyboards/pangorin/pila87_mod/config.h
> +#define QMK_KEYS_PER_SCAN 12
deprecated. 
```suggestion
```

2022-09-12 15:54 UTC, drashna commented on keyboards/pangorin/pila87_mod/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-09-13 14:08 UTC, Pangorin reviewed
Delete some unnecessary things.

2022-09-13 14:19 UTC, Pangorin reviewed
Edit some unnecessary things.

2022-09-13 14:31 UTC, Pangorin reviewed
Delete things that will cause issues on some systems.

2022-09-14 16:28 UTC, drashna approved these changes

2022-09-19 00:58 UTC, zvecr requested changes

2022-09-19 00:58 UTC, zvecr commented on keyboards/pangorin/pila87_mod/readme.md
> +    make phage_studio/pila87_mod:default
```suggestion
    make pangorin/pila87_mod:default
```

2022-09-19 00:58 UTC, zvecr commented on keyboards/pangorin/pila87_mod/keymaps/default/keymap.c
> +// enum layer_keycodes { };
```suggestion
enum layer_names {
    _BASE,
    _FN
};
```

2022-09-19 00:58 UTC, zvecr commented on keyboards/pangorin/pila87_mod/config.h
> +#define DISABLE_RGB_MATRIX_SOLID_SPLASH
These are not valid config options. Effects are now opt-in, <https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects>.

2022-09-19 00:58 UTC, zvecr commented on keyboards/pangorin/pila87_mod/keymaps/via/keymap.c
> +// enum layer_keycodes { };
```suggestion
enum layer_names {
    _BASE,
    _FN
};
```

2022-10-28 08:07 UTC, Pangorin reviewed
Commit changes and update

2022-10-28 09:27 UTC, Pangorin reviewed
Change RGB_MATRIX codes

2022-10-28 09:34 UTC, fauxpark requested changes

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/pila87_mod.c
> +led_config_t g_led_config = { {
```suggestion
#ifdef RGB_MATRIX_ENABLE
led_config_t g_led_config = { {
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/pila87_mod.c
> +} };
```suggestion
} };
#endif
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/via/keymap.c
> +                RESET,            RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD,  RGB_SPI, RGB_SPD, _______, NK_TOGG, _______, _______, _______,
```suggestion
                QK_BOOT,          RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD,  RGB_SPI, RGB_SPD, _______, NK_TOGG, _______, _______, _______,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/via/keymap.c
> +                _______, KC_INS,  KC_DEL,  KC_HOME, KC_END,  KC_PGUP, KC_PGDN, KC_LEFT, KC_DOWN, KC_RIGHT, _______, _______,          _______,
```suggestion
                _______, KC_INS,  KC_DEL,  KC_HOME, KC_END,  KC_PGUP, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______,          _______,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/via/keymap.c
> +                KC_ESC,           KC_F1,   KC_F2, KC_F3, KC_F4,  KC_F5, KC_F6, KC_F7,   KC_F8,  KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_SLCK, KC_PAUSE,
```suggestion
                KC_ESC,           KC_F1,   KC_F2, KC_F3, KC_F4,  KC_F5, KC_F6, KC_F7,   KC_F8,  KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/via/keymap.c
> +                KC_LCTL, KC_LGUI, KC_LALT,               KC_SPC,                                KC_RALT, MO(_FN), KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RIGHT
```suggestion
                KC_LCTL, KC_LGUI, KC_LALT,               KC_SPC,                                KC_RALT, MO(_FN), KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/horrortroll/keymap.c
> +                RESET,            KC_MSEL, KC_VOLD, KC_VOLU, KC_MUTE, KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT, KC_MAIL, KC_WHOM, KC_CALC, KC_WSCH, RGB_RMOD, RGB_MOD, RGB_TOG,
```suggestion
                QK_BOOT,          KC_MSEL, KC_VOLD, KC_VOLU, KC_MUTE, KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT, KC_MAIL, KC_WHOM, KC_CALC, KC_WSCH, RGB_RMOD, RGB_MOD, RGB_TOG,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/horrortroll/keymap.c
> +                KC_ESC,           KC_F1,   KC_F2, KC_F3, KC_F4,  KC_F5, KC_F6, KC_F7,   KC_F8,  KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_SLCK, KC_PAUSE,
```suggestion
                KC_ESC,           KC_F1,   KC_F2, KC_F3, KC_F4,  KC_F5, KC_F6, KC_F7,   KC_F8,  KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/horrortroll/keymap.c
> +                KC_LCTL, KC_LGUI, KC_LALT,               KC_SPC,                                KC_RALT, MO(_FN), KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RIGHT
```suggestion
                KC_LCTL, KC_LGUI, KC_LALT,               KC_SPC,                                KC_RALT, MO(_FN), KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/default/keymap.c
> +                RESET,            RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD,  RGB_SPI, RGB_SPD, _______, NK_TOGG, _______, _______, _______,
```suggestion
                QK_BOOT,          RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD,  RGB_SPI, RGB_SPD, _______, NK_TOGG, _______, _______, _______,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/default/keymap.c
> +                _______, KC_INS,  KC_DEL,  KC_HOME, KC_END,  KC_PGUP, KC_PGDN, KC_LEFT, KC_DOWN, KC_RIGHT, _______, _______,          _______,
```suggestion
                _______, KC_INS,  KC_DEL,  KC_HOME, KC_END,  KC_PGUP, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______,          _______,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/default/keymap.c
> +                KC_ESC,           KC_F1,   KC_F2, KC_F3, KC_F4,  KC_F5, KC_F6, KC_F7,   KC_F8,  KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_SLCK, KC_PAUSE,
```suggestion
                KC_ESC,           KC_F1,   KC_F2, KC_F3, KC_F4,  KC_F5, KC_F6, KC_F7,   KC_F8,  KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/keymaps/default/keymap.c
> +                KC_LCTL, KC_LGUI, KC_LALT,               KC_SPC,                                KC_RALT, MO(_FN), KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RIGHT
```suggestion
                KC_LCTL, KC_LGUI, KC_LALT,               KC_SPC,                                KC_RALT, MO(_FN), KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```

2022-10-28 09:34 UTC, fauxpark commented on keyboards/pangorin/pila87_mod/info.json
> +    "keyboard_name": "Pila87 / XM87 Pro",
Need `manufacturer` entry here as well.

2022-10-28 09:40 UTC, Pangorin commented on keyboards/pangorin/pila87_mod/info.json
> +    "keyboard_name": "Pila87 / XM87 Pro",
I'll add it asap

2022-10-28 09:48 UTC, Pangorin reviewed
Fix literally everything by fauxpark :D

2022-10-28 09:55 UTC, Pangorin reviewed
Typo

2022-10-28 11:46 UTC, Pangorin reviewed
More typo :(

2022-10-28 12:03 UTC, Pangorin reviewed
Delete error codes

2022-10-31 15:50 UTC, closed without merging