Added skmt/15k keyboard
qmk/qmk_firmware pull request #18321
Opened 2022-09-09 19:40 UTC by satorusaka

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-09 20:32 UTC, zvecr requested changes

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/15k.h
> +// Copyright 2022 Jimmy Lye (@satorusaka)
This file should be removed

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/skmt_15k_macropad.json
> +{
This should be removed as it does not belong in this repo.

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/rules.mk
> +# RGBLIGHT_ENABLE = yes
```suggestion
```

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/keymaps/qwert/keymap.c
> +    )
```suggestion
    )
```

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/keymaps/fns/keymap.c
> +    )
```suggestion
    )
```

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/keymaps/default/keymap.c
> +    )
```suggestion
    )
```

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/15k.c
> +// Copyright 2022 Jimmy Lye (@satorusaka)
This file can be removed

2022-09-09 20:32 UTC, zvecr commented on keyboards/skmt/15k/info.json
> +    }
```suggestion
    },
    "rgb_matrix": {
        "driver": "WS2812",
        "layout": [
            { "flags": 4, "matrix": [2, 4], "x": 224, "y": 64 },
            { "flags": 4, "matrix": [2, 3], "x": 168, "y": 64 },
            { "flags": 4, "matrix": [2, 2], "x": 112, "y": 64 },
            { "flags": 4, "matrix": [2, 1], "x": 56, "y": 64 },
            { "flags": 4, "matrix": [2, 0], "x": 0, "y": 64 },
            { "flags": 4, "matrix": [1, 4], "x": 224, "y": 32 },
            { "flags": 4, "matrix": [1, 3], "x": 168, "y": 32 },
            { "flags": 4, "matrix": [1, 2], "x": 112, "y": 32 },
            { "flags": 4, "matrix": [1, 1], "x": 56, "y": 32 },
            { "flags": 4, "matrix": [1, 0], "x": 0, "y": 32 },
            { "flags": 4, "matrix": [0, 4], "x": 224, "y": 0 },
            { "flags": 4, "matrix": [0, 3], "x": 168, "y": 0 },
            { "flags": 4, "matrix": [0, 2], "x": 112, "y": 0 },
            { "flags": 4, "matrix": [0, 1], "x": 56, "y": 0 },
            { "flags": 4, "matrix": [0, 0], "x": 0, "y": 0 }
        ]
    }
```

2022-09-10 00:13 UTC, zvecr requested changes

2022-09-10 00:13 UTC, zvecr commented on keyboards/skmt/15k/rules.mk
> +RGB_MATRIX_ENABLE = yes
```suggestion
```

2022-09-10 00:13 UTC, zvecr commented on keyboards/skmt/15k/readme.md
> +    make skmt_15k_macropad:default:flash
```suggestion
    make skmt/15k:default

Flashing example for this keyboard:

    make skmt/15k:default:flash
```

2022-09-10 00:13 UTC, zvecr commented on keyboards/skmt/15k/info.json
> +        "nkro": true
```suggestion
        "nkro": true,
        "rgb_matrix": true
```

2022-09-11 18:48 UTC, zvecr approved these changes

2022-09-11 19:18 UTC, fauxpark approved these changes

2022-09-14 15:40 UTC, drashna approved these changes

2022-09-14 15:40 UTC, merged