Defer layer rgblight set
qmk/qmk_firmware pull request #18338
Opened 2022-09-11 17:36 UTC by spidey3

## Description

See https://discord.com/channels/440868230475677696/440868230475677698/1018496514470981642.

There is a hypothesis that quickly repeated calls to `rgblight_set()` can cause problems with certain led drivers on certain boards / MCUs. That situation occurs when:
* there is code in `layer_state_set_user()` to select lighting layers based on the currently enabled keymap layers, and...
* a static rgblight animation mode is displayed, OR
* `RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF` is set and rgblight is currently disabled.

This PR avoids the repeated calls to `rgblight_set()`, instead deferring the action until the next invocation of `rgblight_task()`.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* See https://discord.com/channels/440868230475677696/440868230475677698/1018496514470981642 and the following discussion.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-18 21:32 UTC, sigprof requested changes
Needs some testing, but looks like it should work

2022-09-18 21:32 UTC, sigprof commented on quantum/rgblight/rgblight.c
> +bool deferred_set_layer_state = false;
```suggestion
static bool deferred_set_layer_state = false;
```

2022-10-25 05:58 UTC, drashna approved these changes

2022-11-10 07:36 UTC, sigprof approved these changes

2022-11-10 09:27 UTC, tzarc approved these changes

2022-11-10 09:27 UTC, merged

2022-12-20 21:22 UTC, climent commented
This PR broke RGBLIGHT for my setup. I do not know if this is a widespread problem, or just particular to my setup, but with both an ELITE-C and a FROOD (rp2040) boards, reverting this PR returns the RGB operation to a working state.

Way it breaks, with this PR:

* Flashed my atreyu board (https://github.com/climent/qmk_firmware/tree/climent-develop/keyboards/atreyu/keymaps/pcb-rp2040) with either the CONVERT_TO (for rp2040) and without (for the ELITE-C)
* all operations on layers (RAISE, LOWER and CAPS_LOCK) do not work
* RGB_* commands cause the LEDs to glow green, and no further changes happen on the LEDs, although restarting the board indicates that the EEPROM was written after a successful operation, as the LEDs now show the new state (for example, running the RGB_HUI changes the HUE to the new value, but it is only visible after reattaching the board).

I tested it by checking out ae94be98ed6b00a79c0db94a463593f7276d5401, reverting this PR (patching my tree with git diff + patch -p1 < patch), recompiling the code and reflashing the board (both ELITE-C and rp2040 MCUs).