Add support to Zookeepers Leon
qmk/qmk_firmware pull request #18350
Opened 2022-09-13 09:57 UTC by HuangJuanLR

## Description
Add support to Zookeepers' Leon, an TKL F13 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-14 17:20 UTC, drashna requested changes
All C and H files need to include a license header.

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/config.h
> +// #define PRODUCT         Leon
```suggestion
```

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/config.h
> +#define FORCE_NKRO
don't need to undefine this, I think.

Also, this can cause problems in some cases, as some BIOSes/Firmware don't support NKRO properly.

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/leon.c
> +#include "leon.h"
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/leon.h
> +#pragma once
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/leonh/config.h
> +// #define PRODUCT         Leon
```suggestion
```

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/leonh/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware?  This is needed, as a new user may not be aware of how to enter to bootloader to flash new firmware.

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2022-09-14 17:20 UTC, drashna commented on keyboards/zoop/leon/leons/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```

2022-09-14 22:52 UTC, fauxpark requested changes

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/config.h
> +
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/config.h
> +//#define NO_ACTION_FUNCTION
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leonh/config.h
> +//#define NO_ACTION_FUNCTION
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leonh/info.json
> +    "height": 6.5,
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leonh/rules.mk
> +AUDIO_ENABLE = no           # Audio output
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leons/config.h
> +
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leons/config.h
> +//#define NO_ACTION_FUNCTION
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leons/info.json
> +    "height": 6.5,
```suggestion
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leons/rules.mk
> +BOOTMAGIC_ENABLE = no     # Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
```

2022-09-14 22:52 UTC, fauxpark commented on keyboards/zoop/leon/leons/rules.mk
> +BLUETOOTH_ENABLE = no       # Enable Bluetooth
```suggestion
```

2022-09-15 06:46 UTC, fauxpark requested changes

2022-09-15 06:46 UTC, fauxpark commented on keyboards/zoop/leon/leonh/rules.mk
> +NKRO_ENABLE = yes           # USB Nkey Rollover
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2022-10-05 00:24 UTC, noroadsleft requested changes
A lot of issues here.

Please consult the [Files Changed tab](https://github.com/qmk/qmk_firmware/pull/18350/files) to view the full list of suggestions.

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/info.json
> +                { "label": "LBkspc", "x": 13, "y": 1.25 },
Moving `RBkspc` up from Line 81.

```suggestion
                { "label": "LBkspc", "x": 13, "y": 1.25 },
                { "label": "RBkspc", "x": 14, "y": 1.25 },
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/info.json
> +                { "label": "RBkspc", "x": 14, "y": 1.25 },
```suggestion
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/leons.h
> +       K500, K501, K502,                   K506,                   K510, K511, K512, K513,   K514, K515, K516  \
Moves `K313` (right half of split Backspace) to the number row.

```suggestion
       K000, K001, K002, K003, K004, K005, K006, K007, K008, K009, K010, K011, K012, K013,         K014, K015, K016, \
       K100, K101, K102, K103, K104, K105, K106, K107, K108, K109, K110, K111, K112, K113, K313,   K114, K115, K116, \
       K200, K201, K202, K203, K204, K205, K206, K207, K208, K209, K210, K211, K212, K213,         K214, K215, K216, \
       K300, K301, K302, K303, K304, K305, K306, K307, K308, K309, K310, K311,       K312,                           \
       K400,       K402, K403, K404, K405, K406, K407, K408, K409, K410, K411, K412, K413,               K415,       \
       K500, K501, K502,                   K506,                   K510, K511, K512, K513,         K514, K515, K516  \
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/keymaps/default/keymap.c
> +    KC_LCTL, KC_LALT, KC_LGUI,                            KC_SPC,                             MO(1),    KC_RGUI,    KC_RALT,    KC_RCTL,    KC_LEFT, KC_DOWN, KC_RGHT),
Moves Backspace to the number row.

```suggestion
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,              KC_PSCR, KC_SLCK, KC_PAUS,
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSLS, KC_BSPC,    KC_INS,  KC_HOME, KC_PGUP,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,             KC_DEL,  KC_END,  KC_PGDN,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,              
    KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),                        KC_UP,
    KC_LCTL, KC_LALT, KC_LGUI,                            KC_SPC,                             MO(1),   KC_RGUI, KC_RALT, KC_RCTL,             KC_LEFT, KC_DOWN, KC_RGHT),
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/keymaps/default/keymap.c
> +    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/keymaps/via/keymap.c
> +    KC_LCTL, KC_LALT, KC_LGUI,                            KC_SPC,                             MO(1),    KC_RGUI,    KC_RALT,    KC_RCTL,    KC_LEFT, KC_DOWN, KC_RGHT
Moves Backspace to the number row.

```suggestion
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,              KC_PSCR, KC_SLCK, KC_PAUS,
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSLS, KC_BSPC,    KC_INS,  KC_HOME, KC_PGUP,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,             KC_DEL,  KC_END,  KC_PGDN,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,              
    KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),                        KC_UP,
    KC_LCTL, KC_LALT, KC_LGUI,                            KC_SPC,                             MO(1),   KC_RGUI, KC_RALT, KC_RCTL,             KC_LEFT, KC_DOWN, KC_RGHT
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/keymaps/via/keymap.c
> +      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS,
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/keymaps/via/keymap.c
> +    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS,
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/keymaps/via/keymap.c
> +      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS,
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leonh/readme.md
> +**Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
Bootmagic is disabled.

```suggestion
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/leons/readme.md
> +**Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
Bootmagic is disabled.

```suggestion
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/readme.md
> +Keyboard Maintainer: ZooP HuangJuanLr(https://github.com/HuangJuanLR)
```suggestion
* Keyboard Maintainer: [HuangJuanLR](https://github.com/HuangJuanLR)
* Hardware Supported:
  * [Leon Hotswap](leonh/)
  * [Leon Solderable](leons/)
```

2022-10-05 00:24 UTC, noroadsleft commented on keyboards/zoop/leon/readme.md
> +
These instructions won't actually do anything.

```suggestion
```

2023-01-08 02:03 UTC, closed without merging