dygma/raise: multiple fixes and improvements
qmk/qmk_firmware pull request #18361
Opened 2022-09-14 14:09 UTC by justfalter

- respect RGB_MATRIX_ENABLE = no
- Only flush LED buffer when changes have occurred. This significantly improves typing accuracy by reducing traffic related to LED state, increasing the bandwidth available for matrix scans.
- improve configurability of RGB matrix, reduce refresh rate
  - Reduce LED refresh rate from 60fps to 10fps, given the significant impact on typing accuract.
  - Allow enabling/disabling of reactive RGB matrix modes from rules.mk
- fix right-hand ansi LED key map
  - The ansi layout right hand LED key mapping was seemingly flipped and offset by 1 key. For example, when the LED for "7" was to light, the "= +" LED would light, instead. Reversing each row of the led mapping resolved the issue.
  - LEDs for the "\ |" and "enter" keys were swapped.
- fix color order to GRB
  - Colors were incorrectly mapped with red and green swapped. Actual color order is GRB, not RGB.
- Add color-correction for red channel, as it apparently receives more voltage than the other color channels.

## Description

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-14 14:10 UTC, justfalter commented
@ibash you might be interested in this

2022-09-14 14:38 UTC, ibash commented
Awesome! Lgtm

Out of curiosity what are you using for a mcu?

2022-09-14 17:46 UTC, drashna approved these changes

2022-09-14 22:55 UTC, fauxpark requested changes

2022-09-14 22:55 UTC, fauxpark commented on keyboards/handwired/dygma/raise/leds.c
> +
```suggestion
```
Use `post_rules.mk` to control whether this code is compiled.

2022-09-14 22:55 UTC, fauxpark commented on keyboards/handwired/dygma/raise/leds.c
> +#endif
```suggestion
```

2022-09-14 22:55 UTC, fauxpark commented on keyboards/handwired/dygma/raise/leds.h
> +#ifdef RGB_MATRIX_ENABLE
```suggestion
```

2022-09-14 22:55 UTC, fauxpark commented on keyboards/handwired/dygma/raise/leds.h
> +#endif
```suggestion
```

2022-09-19 14:24 UTC, justfalter commented
@fauxpark I got the changes in to use `post_rules.mk` instead of `#ifdef``'s . 

I also fixed dygma/raise's q_led_config, which was failing to validate (#17105).

2022-09-22 03:54 UTC, justfalter commented
@drashna is this something you can take care of merging? I've addressed @fauxpark's requested changes.

2022-09-28 16:37 UTC, ibash commented
@justfalter thanks for all the work here! Hopefully this can get a second approval soon...

2022-09-28 16:37 UTC, ibash approved these changes

2022-09-28 16:44 UTC, fauxpark approved these changes

2022-09-28 19:23 UTC, merged