[Keyboard] Add Janus keyboard
qmk/qmk_firmware pull request #18367
Opened 2022-09-15 01:13 UTC by skarrmann

## Description

This PR adds a keyboard definition and default keymap for my split keyboard [Janus](https://github.com/skarrmann/janus).

Note the keyboard uses UART serial for split communication.

Thank you!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-15 01:21 UTC, fauxpark requested changes

2022-09-15 01:21 UTC, fauxpark commented on keyboards/janus/info.json
> +    },
```suggestion
```

2022-09-24 06:07 UTC, drashna approved these changes
LGTM

2022-09-24 06:35 UTC, fauxpark approved these changes

2022-09-24 15:35 UTC, merged