Add the Gone Hacking Studio XLS
qmk/qmk_firmware pull request #18362
Opened 2022-09-14 16:13 UTC by ramonimbao

## Description

Adds the Gone Hacking Studio XLS numpad.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-14 16:28 UTC, zvecr requested changes

2022-09-14 16:28 UTC, zvecr commented on keyboards/ghs/xls/keymaps/via/keymap.c
> +keyevent_t encoder0_cw = {
This is no longer accepted for new contributions, as <https://github.com/qmk/qmk_firmware/pull/17734> provides proper support.

2022-09-14 16:28 UTC, zvecr commented on keyboards/ghs/xls/info.json
> +        "rows": ["A4", "B12", "A6", "A10", "A5", "B2", "NO_PIN", "NO_PIN"]
```suggestion
        "rows": ["A4", "B12", "A6", "A10", "A5", "B2"]
```

2022-09-14 16:28 UTC, zvecr commented on keyboards/ghs/xls/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Licence headers are missing

2022-11-28 14:25 UTC, ramonimbao commented
Will reopen a new PR. I messed up rebasing this.

2022-11-28 14:25 UTC, closed without merging