Invert pointing device motion pin for cirque touchpads
qmk/qmk_firmware pull request #18404
Opened 2022-09-18 14:02 UTC by preisi

## Description

Cirque touchpads 'data ready'-pin implements active-high logic in contrast to most other pointing devices which use an active-low logic. Therefore, this commit implements both a configurable inversion of the motion pin logic and sets the the default for the cirque touchpad driver accordingly.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR
This issue came up yesterday in the #help-firmware discord channel and was pointed out by @daskygit after Kuromitsu#5783 tried to use the motion pin.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-18 18:40 UTC, KarlK90 approved these changes
LGTM! Thanks.

2022-09-18 19:41 UTC, zvecr requested changes
Not a fan of the chosen name as it doesnt really align with any of the existing options.

Suggestions would be to align to the existing `_ACTIVE_LOW` (or at a push `_ON_STATE`?).

2022-09-19 10:43 UTC, preisi commented
> Not a fan of the chosen name as it doesnt really align with any of the existing options.
I aligned the name with the other defines in `quantum/pointing_device` which are  named `POINTING_DEVICE_INVERT_{X,Y,_X_RIGHT,_Y_RIGHT}`. But granted,  I'm not the biggest fan of the naming myself as it is not very explicit about the default behavior of the motion pin.

> Suggestions would be to align to the existing `_ACTIVE_LOW` (or at a push `_ON_STATE`?).
To my understanding (and after grepping over parts of QMK), the `_ACTIVE_LOW`/`_ACTIVE_HIGH`  seems to be mostly a ChibiOS convention. I hope the new choice `_ON_STATE` is better. Thank you for your feedback :)

2022-09-19 11:02 UTC, daskygit commented
My issue with `_ON_STATE` is it doesn't line up with terminology (active low/high) that will be used by datasheets.

2022-09-20 19:54 UTC, preisi commented
> My issue with `_ON_STATE` is it doesn't line up with terminology (active low/high) that will be used by datasheets.

Mh, that is obviously true. So you're suggesting to rename the current `_ON_STATE` to `_ACTIVE_LOW` and assign it the according boolean value? Or is there any better way your envisioning? Creating 2 defines "_ACTIVE_LOW" and "_ACTIVE_HIGH" and assign them to a third define as some sort of "enum" seems overkill to me. Or do you have something else in mind? (Otherwise I'd just rename the existing define to "_ACTIVE_LOW".

2022-09-20 20:02 UTC, daskygit commented
Nah, you'd only need to define `_ACTIVE_LOW` for it to switch behaviour with the undefined/default being active high which wouldn't need to be specified. I guess something like how `HAPTIC_ENABLE_PIN_ACTIVE_LOW` is handled.

2022-09-21 00:00 UTC, preisi commented
> Nah, you'd only need to define `_ACTIVE_LOW` for it to switch behaviour with the undefined/default being active high which wouldn't need to be specified. I guess something like how `HAPTIC_ENABLE_PIN_ACTIVE_LOW` is handled.

Alright, this should now be more to your liking :) I'm not completely happy with the result as `_ACTIVE_LOW` is basically be the default for all pointing devices except for the cirque touchpad. Then again, generally defining it and then specifically undefining it for the cirque touchpad would be possible, too (if that were to be preferred).

2022-09-21 11:11 UTC, daskygit approved these changes

2022-09-24 15:43 UTC, drashna approved these changes

2022-09-24 15:44 UTC, merged