Add darkproject/kd83a_bfg_edition keyboard
qmk/qmk_firmware pull request #18416
Opened 2022-09-19 09:45 UTC by gksygithub

## Description

Add darkproject/kd83a_bfg_edition keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-24 07:28 UTC, drashna requested changes

2022-09-24 07:28 UTC, drashna commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +#define PRODUCT KD83A_BFG_Edition
These have been moved to info.json
```suggestion
```

2022-09-29 18:39 UTC, fauxpark requested changes

2022-09-29 18:39 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +
```suggestion
```

2022-09-29 18:39 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/info.json
> +        "device_version": "0.0.3"
```suggestion
    "keyboard_name": "KD83A_BFG_Edition",
    "manufacturer": "GSKY",
    "url": "",
    "maintainer": "Gsky",
    "usb": {
        "vid": "0x342D",
        "pid": "0xE392",
        "device_version": "0.0.2"
```

2022-09-29 18:39 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/via/keymap.c
> +	if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK)) {
```suggestion
	if (host_keyboard_led_state().caps_lock) {
```

2022-09-30 03:22 UTC, drashna commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/via/keymap.c
> +void rgb_matrix_indicators_user(void) {
Not to self: https://github.com/qmk/qmk_firmware/pull/18450

2022-09-30 03:23 UTC, drashna approved these changes

2022-10-11 02:41 UTC, gksygithub commented
@fauxpark , Resolved requested changes. Could you please help me to take a look. Thanks

2022-10-24 01:48 UTC, gksygithub commented
Can someone please take a look at this PR please.

2022-12-23 09:11 UTC, drashna approved these changes

2022-12-26 01:31 UTC, gksygithub commented
@fauxpark, please take a look at this PR please. Thanks

2023-01-16 08:55 UTC, fauxpark requested changes

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +
```suggestion
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/info.json
> +                { "label": "z2", "x": 17.25, "y": 0 },
```suggestion
                { "label": "z2", "x": 17.25, "y": 0 },
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/via/keymap.c
> +                host_consumer_send(0x2A0);
```suggestion
                host_consumer_send(0x2A0);
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/via/keymap.c
> +            if (record->event.pressed) {
```suggestion
            if (record->event.pressed) {
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/via/keymap.c
> +            if (record->event.pressed) {
```suggestion
            if (record->event.pressed) {
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/via/keymap.c
> +            return false; /* Skip all further processing of this key */
```suggestion
            return false; /* Skip all further processing of this key */
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/rules.mk
> +
```suggestion
```

2023-01-16 08:55 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/info.json
> +    },
```suggestion
    },
    "processor": "WB32F3G71",
    "bootloader": "wb32-dfu",
```

2023-01-16 11:20 UTC, fauxpark approved these changes

2023-01-16 11:21 UTC, fauxpark requested changes
.

2023-01-17 01:05 UTC, gksygithub commented
@fauxpark I didn't get you, could you please explain in detail what are the changes I need to do in this pull request.

2023-01-17 01:32 UTC, fauxpark commented
The suggestions above still need to be accepted.

2023-01-24 17:35 UTC, Serega2009bk commented
@gksygithub have a release version of this keyboard, it uses a different mcu WB32FQ95
![20221230_012818](https://user-images.githubusercontent.com/71171695/214366045-a35e30e6-07b6-486e-ab11-c41591461050.jpg)

2023-01-25 02:07 UTC, SHVD3x commented
My board also came with WB32FQ95

2023-02-01 10:12 UTC, gksygithub commented
@Serega2009bk, [SHVD3x](https://github.com/SHVD3x), yes it is correct MCU (WB32FQ95). updated json file, Thanks.

2023-02-08 01:25 UTC, gksygithub commented
@drashna , @fauxpark , please take a look at this PR. Thanks.

2023-02-08 02:27 UTC, fauxpark requested changes

2023-02-08 02:27 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +// #define FORCE_NKRO
```suggestion
```

2023-02-13 07:55 UTC, gksygithub commented
@fauxpark , Resolved requested changes. Please take a look, thanks.

2023-02-13 11:22 UTC, fauxpark requested changes

2023-02-13 11:22 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +
```suggestion
```

2023-02-13 11:22 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +
```suggestion
```

2023-02-13 11:22 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/info.json
> +    "processor": "WB32FQ95",
```suggestion
    "indicators": {
        "caps_lock": "C14"
    },
    "processor": "WB32FQ95",
```

2023-02-15 10:07 UTC, gksygithub commented
@fauxpark Resolved requested changes, thanks.

2023-03-08 04:16 UTC, gksygithub commented
@fauxpark Can you please help to review the changes, thanks.

2023-03-22 08:47 UTC, gksygithub commented
Can someone take a look at this PR please..., thanks.

2023-06-12 01:14 UTC, gksygithub commented
@fauxpark, please take a look at this PR, thanks.

2023-06-12 01:16 UTC, fauxpark requested changes

2023-06-12 01:16 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/kd83a_bfg_edition.h
> +#define LAYOUT( \
Needs to be moved to info.json.

2023-06-12 01:16 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/kd83a_bfg_edition.c
> +led_config_t g_led_config = {
Needs to be moved to info.json.

2023-06-12 01:16 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/config.h
> +#define BOOTMAGIC_LITE_COLUMN 3
Needs to be moved to info.json.

2023-07-24 01:17 UTC, gskygithub commented
@fauxpark , Could you please take a look at this PR, thanks.

2023-07-24 01:45 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/kd83a_bfg_edition.h
> +#define LAYOUT( \
This is still outstanding.

2023-08-21 21:49 UTC, fauxpark approved these changes

2023-08-25 01:16 UTC, gskygithub commented
@drashna @fauxpark , still is there any modifications in this PR? please kindly help to review or merge it, thanks.

2023-09-08 10:22 UTC, fauxpark requested changes

2023-09-08 10:22 UTC, fauxpark commented on keyboards/darkproject/kd83a_bfg_edition/info.json
> +        "driver": "AW20216",
```suggestion
        "driver": "aw20216",
```

2023-09-25 03:51 UTC, drashna commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/default/keymap.c
> +            return false; /* Skip all further processing of this key */
This keycode exists as `KC_WWW_SEARCH` already.

2023-10-05 04:01 UTC, drashna commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/default/keymap.c
> +            return false; /* Skip all further processing of this key */
```suggestion
```

2023-10-12 18:22 UTC, drashna commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/default/keymap.c
> +            return false; /* Skip all further processing of this key */
This exists in core, already, as well.

2023-10-12 18:22 UTC, drashna commented on keyboards/darkproject/kd83a_bfg_edition/keymaps/default/keymap.c
> +bool process_record_user(uint16_t keycode, keyrecord_t *record) {
These should be moved to the kb level

2023-10-14 19:28 UTC, noroadsleft requested changes

2023-10-14 19:28 UTC, noroadsleft commented on keyboards/darkproject/kd83a_bfg_edition/kd83a_bfg_edition.c
> +};
Defines a default behaviour for encoders that works for keymaps compiled in QMK Configurator. (Configurator doesn't use `ENCODER_MAP`.)

```suggestion
};

#if defined(ENCODER_ENABLE)
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) {
        return false;
    }
    if (clockwise) {
        tap_code(KC_VOLU);
    } else {
        tap_code(KC_VOLD);
    }
    return false;
};
#endif
```

2023-10-14 19:28 UTC, noroadsleft commented on keyboards/darkproject/kd83a_bfg_edition/readme.md
> +
Would be good to have a photo of the keyboard and/or PCB here.

2023-11-07 10:23 UTC, gskygithub commented
@drashna @fauxpark @lesshonor @noroadsleft, can someone please take a look at this PR please.

2023-11-22 21:59 UTC, noroadsleft approved these changes
Looks good to me.

2023-11-22 22:11 UTC, drashna approved these changes

2023-11-22 22:13 UTC, merged

2023-11-22 22:13 UTC, noroadsleft commented
Thanks!