[Keymap] KO Kyria
qmk/qmk_firmware pull request #18413
Opened 2022-09-19 04:10 UTC by ohlin

## Description

Adding v1 of my personal keymap for the splitkb Kyria.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-24 14:16 UTC, drashna requested changes

2022-09-24 14:16 UTC, drashna commented on keyboards/splitkb/kyria/keymaps/ohlin/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-09-30 03:24 UTC, drashna approved these changes

2022-09-30 03:31 UTC, fauxpark requested changes

2022-09-30 03:31 UTC, fauxpark commented on keyboards/splitkb/kyria/keymaps/ohlin/rules.mk
> +VELOCIKEY_ENABLE = no
```suggestion
ENCODER_ENABLE = no
MOUSEKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
```

2022-10-29 02:59 UTC, fauxpark approved these changes

2022-11-08 04:50 UTC, merged