Fix Per Key LED Indicator Callbacks
qmk/qmk_firmware pull request #18450
Opened 2022-09-21 21:01 UTC by drashna

## Description

They aren't boolean, so no good way to override them.  This aims to fix that. 

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-22 05:26 UTC, daskygit requested changes

2022-09-22 05:26 UTC, daskygit commented on keyboards/keybee/keybee65/keymaps/via/keymap.c
> +bool rgb_matrix_indicators_kb(void) {
```suggestion
bool rgb_matrix_indicators_user(void) {
```

2022-09-22 05:26 UTC, daskygit commented on keyboards/keychron/q2/rev_0113/keymaps/dhertz/keymap.c
> +bool rgb_matrix_indicators_kb(void) {
```suggestion
bool rgb_matrix_indicators_user(void) {
```

2022-09-22 05:26 UTC, daskygit commented on keyboards/kprepublic/bm60hsrgb_poker/rev1/keymaps/ipetepete/keymap.c
> +bool rgb_matrix_indicators_kb(void)
```suggestion
bool rgb_matrix_indicators_user(void)
```

2022-09-22 05:26 UTC, daskygit commented on keyboards/tkc/portico/portico.c
> +    return
```suggestion
    return true;
```

2022-09-22 07:09 UTC, tzarc requested changes
Everything Dasky said, too.

2022-09-22 07:09 UTC, tzarc commented on keyboards/planck/keymaps/gunp/keymap.c
> +  bool rgb_matrix_indicators_kb(void) {
```suggestion
  bool rgb_matrix_indicators_user(void) {
```

2022-09-26 20:31 UTC, daskygit approved these changes

2022-10-04 22:24 UTC, merged