[Core] Quantum Painter - LVGL Integration
qmk/qmk_firmware pull request #18499
Opened 2022-09-27 02:06 UTC by Jpe230

## Description

This PR aims to integrate  [LVGL (Light and Versatile Embedded Graphics Library)](https://lvgl.io/) into QMK by utilizing Quantum Painter's APIs and drivers.

This PR includes the following:
- Addition of LVGL v8.2 as a submodule.
- Hooking LVGL internal ticks into quantum's main loop by using deferred executions.
- Public API to attach/detach a QP display.
- Enable the use of a `lv_conf.h` user defined file to enable/disable features, much like the rest of the ChibiOS configs. (Courtesy of @tzarc, thanks Tzarc!)
- Documentation of the feature
- Onekey keymap of the feature.

Worth mentioning that English isn't my first language, so I expect to bounce with maintainers the wording of the documentation....

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-09-27 02:36 UTC, zvecr requested changes
* `data/keyboard-config-templates/chibios/` should be `data/templates/<something>`
* some files are missing licence headers

2022-09-27 02:36 UTC, zvecr commented on keyboards/handwired/onekey/keymaps/lvgl/config.h
> +/* SPI pins */
```suggestion
#pragma once 

/* SPI pins */
```

2022-09-27 02:36 UTC, zvecr commented on quantum/main.c
> +
Introducing extra logic here would be nice to avoid and instead introduce something like a `qp_task()`

2022-09-27 03:08 UTC, tzarc commented
We'll need changes to the root `Makefile` too, specifically for handling submodules.

I *think* that may need to go to master in order to deal with swapping branches and the like, people are likely going to end up with an `lvgl` directory otherwise, and end up adding it to their master-based branches.

2022-09-27 03:09 UTC, tzarc commented
And, of course, we'll need a `qmk/lvgl` mirror.

2022-10-14 12:25 UTC, tzarc requested changes
Just some verbiage. LGTM otherwise.

2022-10-14 12:25 UTC, tzarc commented on docs/_summary.md
> +        * [ Quantum Painter LVGL Integration](quantum_painter_lvgl.md)
```suggestion
        * [Quantum Painter LVGL Integration](quantum_painter_lvgl.md)
```

2022-10-14 12:25 UTC, tzarc commented on docs/quantum_painter_lvgl.md
> +bool qp_lvgl_attach(painter_device_t device)
```suggestion
bool qp_lvgl_attach(painter_device_t device);
```

2022-10-14 12:25 UTC, tzarc commented on docs/quantum_painter_lvgl.md
> +The `qp_lvgl_attach` function is used to set up LVGL with the supplied display, it requires an already configured display.
```suggestion
The `qp_lvgl_attach` function is used to set up LVGL with the supplied display, and requires an already configured display.
```

2022-10-14 12:25 UTC, tzarc commented on docs/quantum_painter_lvgl.md
> +
```suggestion

!> Attaching LVGL to a display means LVGL subsequently "owns" the display. Using standard Quantum Painter drawing operations with the display after LVGL attachment will likely result in display artifacts.
```

2022-10-14 12:25 UTC, tzarc commented on docs/quantum_painter_lvgl.md
> +You can overwrite LVGL specific features in your `lv_conf.h` file.
```suggestion
## Enabling/Disabling LVGL features :id=lvgl-configuring

You can overwrite LVGL specific features in your `lv_conf.h` file.
```

2022-10-14 12:29 UTC, tzarc commented
Would also be good if you could incorporate your `jpe230/lvgl_makefile_changes` modifications too. We can backport the appropriate lines to `master` afterwards.

2022-10-14 20:47 UTC, tzarc approved these changes

2022-12-12 20:50 UTC, KarlK90 approved these changes
Tested with ST7789 and RP2040 development board, works nicely. Also rather low impact on the scan rate, which is very welcome.

2022-12-12 20:51 UTC, merged