[Keyboard] Add steamroller
qmk/qmk_firmware pull request #18563
Opened 2022-10-02 02:41 UTC by DeskDaily

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-02 07:10 UTC, drashna requested changes

2022-10-02 07:10 UTC, drashna commented on keyboards/nightly_boards/steamroller/readme.md
> +![Steamroller](https://i.imgur.com/x8CmwWD.png)
```suggestion
![Steamroller](https://i.imgur.com/x8CmwWDh.png)
```

2022-10-02 07:10 UTC, drashna commented on keyboards/nightly_boards/steamroller/readme.md
> +Make example for this keyboard (after setting up your build environment):
Could you add instructions on how to enter the bootloader, to flash new firmware?  This is needed, as a new user may not be aware of how to enter to bootloader to flash new firmware.

Eg: 
```markup
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-01-25 02:14 UTC, tzarc commented
Our fault, stalebot kicked in before we got back to it.

2023-01-27 21:17 UTC, drashna approved these changes

2023-01-27 21:38 UTC, waffle87 requested changes

2023-01-27 21:38 UTC, waffle87 commented on keyboards/nightly_boards/steamroller/config.h
> +
```suggestion
```

2023-01-27 21:38 UTC, waffle87 commented on keyboards/nightly_boards/steamroller/keymaps/default/keymap.c
> +    ),
```suggestion
    )
```

2023-01-27 21:38 UTC, waffle87 commented on keyboards/nightly_boards/steamroller/rules.mk
> +
```suggestion
```

2023-01-27 21:38 UTC, waffle87 commented on keyboards/nightly_boards/steamroller/info.json
> +    },
```suggestion
    },
    "processor": "atmega32u4",
    "bootloader": "atmel-dfu",
```

2023-04-13 01:53 UTC, closed without merging