Add `tzarc/ghoul`.
qmk/qmk_firmware pull request #18562
Opened 2022-10-01 22:23 UTC by tzarc

## Description

As per the title.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-01 22:26 UTC, tzarc commented
CI build error is because `qmk list-keyboards` incorrectly detects the base folder as a keyboard due to the presence of `rules.mk`.

2022-10-01 22:30 UTC, tzarc commented
Needs a `readme.md`. Incoming.

2022-10-02 00:05 UTC, zvecr requested changes

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/ghoul.h
> +// Copyright 2018-2022 Nick Brassel (@tzarc)
This file can be removed as DD layout macro

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/info.json
> +    "LAYOUT_all": {
```suggestion
    "LAYOUT": {
```

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/keymaps/default/keymap.c
> +    [_QWERTY] = LAYOUT_all(
```suggestion
    [_QWERTY] = LAYOUT(
```

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/keymaps/default/keymap.c
> +    [_LOWER] = LAYOUT_all(
```suggestion
    [_LOWER] = LAYOUT(
```

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/keymaps/default/keymap.c
> +    [_RAISE] = LAYOUT_all(
```suggestion
    [_RAISE] = LAYOUT(
```

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/keymaps/default/keymap.c
> +    [_ADJUST] = LAYOUT_all(
```suggestion
    [_ADJUST] = LAYOUT(
```

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/readme.md
> +*A short description of the keyboard/project*
```suggestion
Planck-like development board for QMK, using SparkFun MicroMod for hot-swap MCU capability.
```

2022-10-02 00:05 UTC, zvecr commented on keyboards/tzarc/ghoul/readme.md
> +Hardware Availability: [Open-source](https://github.com/tzarc/ghoul)
```suggestion
* Hardware Availability: [Open-source](https://github.com/tzarc/ghoul)
```

2022-10-02 06:55 UTC, drashna requested changes

2022-10-02 06:55 UTC, drashna commented on keyboards/tzarc/ghoul/readme.md
> +![Ghoul](https://i.imgur.com/T8wp7cE.jpg)
```suggestion
![Ghoul](https://i.imgur.com/T8wp7cEh.jpg)
```

2022-10-02 14:03 UTC, zvecr approved these changes

2022-10-02 20:24 UTC, merged