Add customized 62 key layout called "nobreakfast/nb62"
qmk/qmk_firmware pull request #18572
Opened 2022-10-03 14:34 UTC by Nobreakfast

Add customized 62 key layout called "nobreakfast/nb62"

I add new customized 62 key layout called `nobreakfast/nb62` in folder `qmk_firmware/keyboards/` with userspace `nobreakfast`

## Description

Layout: nobreakfast/nb62

The main difference of this `nb62` layout and general `GH60` is that split the space key into two parts (2.25+2.75). Besides, the left space is aligned with the "C" key, and right space is aligned with the "M" key, which are same for Mac users.

Add file and folder:
nobreakfast
└── nb62
    ├── Makefile
    ├── config.h
    ├── keymaps
        └── default
           └── keymap.c
    ├── nb62.c
    ├── nb62.h
    └── rules.mk

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-03 15:10 UTC, sigprof requested changes
Unfortunately, your pull request does not have several important parts:

- The `info.json` file is required (as a minimum, it must contain the parts listed in the [PR Checklist](https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs), but you may consider moving other things like matrix pins and layout definitions there too).
- The `readme.md` file is also required (again, see the PR Checklist).
- The `rules.mk` file should not contain obsolete comments with the approximate number of bytes; even better, the data that you have there should be moved to `info.json` instead (see https://github.com/qmk/qmk_firmware/tree/master/data/templates/keyboard for the template that is currently used by `qmk new-keyboard`).

2022-10-03 15:10 UTC, sigprof commented on keyboards/nobreakfast/nb62/rules.mk
> +VIA_ENABLE = no
```suggestion
```
No need to mention VIA anywhere except in the `via` keymap.

2022-10-03 15:10 UTC, sigprof commented on keyboards/nobreakfast/nb62/rules.mk
> +SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
```suggestion
```
This obsolete option should not be mentioned at all.

2022-10-03 15:10 UTC, sigprof commented on keyboards/nobreakfast/nb62/rules.mk
> +BOOTMAGIC_ENABLE = yes	# Virtual DIP switch configuration(+1000)
If you want to keep using `rules.mk`, please change the whole section to match https://github.com/qmk/qmk_firmware/blob/a239051c4a4779767059140892144dedea09aaf2/data/templates/avr/rules.mk (this is the last version of the `rules.mk` template before switching to the data-driven format as the default):
- fix the comment before the section, which is wrong in general (some options might be enabled by default and need an explicit `no` to disable);
- remove the obsolete `(+1000)`-like parts which refer to approximate code size (those values are often completely wrong);
- keep the order of options like in the template, add any extras below.

2022-10-03 15:10 UTC, sigprof commented on keyboards/nobreakfast/nb62/config.h
> +#endif
```suggestion
```

2022-10-03 15:10 UTC, sigprof commented on keyboards/nobreakfast/nb62/nb62.h
> +#define NB62_H
```suggestion
#pragma once
```

2022-10-03 15:10 UTC, sigprof commented on keyboards/nobreakfast/nb62/nb62.h
> +#endif
```suggestion
```

2022-10-03 15:54 UTC, Nobreakfast commented on keyboards/nobreakfast/nb62/config.h
> +
Thanks for your detailed advices and suggestions.

I am a noob in this qmk firmware, but want to build my own keyboard. I will fix my problem as soon as possible.

2022-10-08 01:21 UTC, Nobreakfast commented
Sorry, this request does not follow the rule of fork in qmk, and I closed this request.

2022-10-08 01:21 UTC, closed without merging