Implement split comms watchdog
qmk/qmk_firmware pull request #18599
Opened 2022-10-05 02:55 UTC by daskygit

## Description

Only had minimal testing so far, but this will allow for some feedback.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-05 16:23 UTC, KarlK90 requested changes
Great feature :tada:. From my testing this works great and I found only one tiny edge case.

2022-10-05 16:58 UTC, daskygit commented on quantum/split_common/split_util.c
> +    if (!is_transport_connected()) {
Yeah definitely, I couldn't decide last night if I wanted to require `is_transport_connected` work. I was thinking maybe do a ping on an interval if `SPLIT_MAX_CONNECTION_ERRORS == 0` but think that goes against my intention of not sending data when it's not required.

Anyways, long story short. I'll add an assertion, thanks.

2022-10-05 16:59 UTC, daskygit commented on quantum/split_common/transactions.c
> +    split_watchdog_update(split_shmem->watchdog_pinged);
I couldn't see a reason to ever require rearming the secondary side watchdog.

2022-10-05 21:41 UTC, daskygit commented
Not entirely happy with the DD mapping

2022-10-05 22:13 UTC, KarlK90 commented on quantum/split_common/transactions.c
> +    split_watchdog_update(split_shmem->watchdog_pinged);
Me neither, just double checking the implementation.

2022-10-05 22:29 UTC, drashna approved these changes

2022-10-06 09:00 UTC, KarlK90 approved these changes
LGTM now!

2022-10-06 09:52 UTC, tzarc approved these changes

2022-10-06 09:52 UTC, merged