add akb/vero
qmk/qmk_firmware pull request #18652
Opened 2022-10-09 06:14 UTC by arnstadm

## Description
Add akb/vero keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-09 22:45 UTC, drashna commented on keyboards/akb/vero/readme.md
> +![antipode/vero](https://imgur.com/znKP8XQ.jpeg)
```suggestion
![antipode/vero](https://i.imgur.com/znKP8XQh.jpeg)
```

2022-10-09 23:13 UTC, fauxpark requested changes

2022-10-09 23:13 UTC, fauxpark commented on keyboards/akb/vero/info.json
> +    "keyboard_name": "akb/vero",
```suggestion
    "keyboard_name": "Vero",
```

2022-10-10 09:19 UTC, fauxpark approved these changes

2022-10-13 19:34 UTC, keyboard-magpie approved these changes

2022-10-13 19:34 UTC, merged