Add support for keebsforall freebird75
qmk/qmk_firmware pull request #18653
Opened 2022-10-09 09:20 UTC by e11i0t23

## Description
Add support for keebsforall freebird75

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-09 20:11 UTC, zvecr requested changes

2022-10-09 20:11 UTC, zvecr commented on keyboards/keebsforall/freebird75/config.h
> +// Copyright 2022 Elliot Powell (@Elliot Powell)
This file can be removed

2022-10-09 20:11 UTC, zvecr commented on keyboards/keebsforall/freebird75/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
// Copyright 2022 Elliot Powell (@Elliot Powell)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
```

2022-10-09 20:11 UTC, zvecr commented on keyboards/keebsforall/freebird75/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
// Copyright 2022 Elliot Powell (@Elliot Powell)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
```

2022-10-09 20:11 UTC, zvecr commented on keyboards/keebsforall/freebird75/readme.md
> +*A short description of the keyboard/project*
Fill in or remove

2022-10-09 22:46 UTC, drashna commented on keyboards/keebsforall/freebird75/readme.md
> +![fb75](https://cdn.shopify.com/s/files/1/0466/1408/5790/products/Scene_03_1200x.jpg?v=1664496240)
Please rehost image on Imgur (or another dedicated image hosting site).  Shopify links are non-permanent.

2022-10-10 05:03 UTC, e11i0t23 commented on keyboards/keebsforall/freebird75/readme.md
> +*A short description of the keyboard/project*
Filled in

2022-10-10 05:04 UTC, e11i0t23 commented on keyboards/keebsforall/freebird75/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Updated

2022-10-10 08:01 UTC, drashna commented on keyboards/keebsforall/freebird75/readme.md
> +![fb75](https://i.imgur.com/fGRQZ2g.jpg)
```suggestion
![fb75](https://i.imgur.com/fGRQZ2gh.jpg)
```

2022-10-30 13:53 UTC, e11i0t23 commented
Any update here getting this merged? @zvecr

2022-10-30 19:03 UTC, keyboard-magpie approved these changes

2022-11-08 05:02 UTC, drashna requested changes

2022-11-08 05:02 UTC, drashna commented on keyboards/keebsforall/freebird75/info.json
> +        "LAYOUT_75": {
This should match one of the community layouts, or should be left as just `LAYOUT`.
```suggestion
        "LAYOUT": {
```

Either way, that necessitates a change, and needs to be applied to the keymap.c files, as well.

2022-11-19 21:38 UTC, drashna approved these changes

2022-11-19 21:39 UTC, merged