Fixup keychron/q3
qmk/qmk_firmware pull request #18687
Opened 2022-10-12 20:09 UTC by waffle87

## Description

As title — to align with develop specific changes.
Also changes `rgb_matrix_indicators_advanced_user` -> `rgb_matrix_indicators_advanced_kb`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-12 21:46 UTC, tzarc commented
There are a few cases where `KC_ROPT` and `KC_ROPTN` have potentially been changed incorrectly, probably should rectify that.

2022-10-12 22:25 UTC, fauxpark requested changes

2022-10-12 22:25 UTC, fauxpark commented on keyboards/keychron/q3/jis_encoder/keymaps/default/keymap.c
> +        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_INT1,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_ROPT,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-12 22:25 UTC, fauxpark commented on keyboards/keychron/q3/jis_encoder/keymaps/keychron/keymap.c
> +        KC_LCTL,  KC_LOPTN, KC_LCMMD, KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMMD, KC_INT1, MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPTN, KC_LCMMD, KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMMD, KC_ROPTN, MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-12 22:25 UTC, fauxpark commented on keyboards/keychron/q3/jis_encoder/keymaps/via/keymap.c
> +        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_INT1,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_ROPT,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-12 22:25 UTC, fauxpark commented on keyboards/keychron/q3/jis/keymaps/via/keymap.c
> +        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_INT1,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_ROPT,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-12 22:25 UTC, fauxpark commented on keyboards/keychron/q3/jis/keymaps/keychron/keymap.c
> +        KC_LCTL,  KC_LOPTN, KC_LCMMD, KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMMD, KC_INT1, MO(MAC_FN), KC_RCTL,             KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPTN, KC_LCMMD, KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMMD, KC_ROPTN, MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-12 22:25 UTC, fauxpark commented on keyboards/keychron/q3/jis/keymaps/default/keymap.c
> +        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_INT1,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPT,  KC_LCMD,  KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMD,  KC_ROPT,  MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-13 00:47 UTC, waffle87 commented
Thanks fauxpark

2022-10-13 00:50 UTC, fauxpark approved these changes

2022-10-13 00:50 UTC, fauxpark commented on keyboards/keychron/q3/jis/keymaps/keychron/keymap.c
> +        KC_LCTL,  KC_LOPTN, KC_LCMMD, KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMMD, KC_ROPTN, MO(MAC_FN), KC_RCTL,             KC_LEFT,  KC_DOWN,  KC_RGHT),
```suggestion
        KC_LCTL,  KC_LOPTN, KC_LCMMD, KC_LNG2,                      KC_SPC,                       KC_LNG1,  KC_RCMMD, KC_ROPTN, MO(MAC_FN), KC_RCTL,            KC_LEFT,  KC_DOWN,  KC_RGHT),
```

2022-10-13 03:09 UTC, tzarc approved these changes

2022-10-13 03:09 UTC, merged