Add mini36
qmk/qmk_firmware pull request #18739
Opened 2022-10-15 23:35 UTC by controller-works

Add support for mini36 keyboard by Controller Works.

## Description

The mini36 is a low profile, split, ergonomic keyboard based on the RP2040 processor. It has a direct scan design, per-key LEDs and LED underglow, OLEDs on each half, and over current and ESD protection on the USB and TRRS connectors. Includes default and via keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-15 23:45 UTC, zvecr requested changes

2022-10-15 23:45 UTC, zvecr commented on keyboards/controllerworks/mini36/config.h
> +#define I2C1_SDA_PIN GP24
```suggestion
#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP25
#define I2C1_SDA_PIN GP24
```

2022-10-15 23:45 UTC, zvecr commented on keyboards/controllerworks/mini36/mini36.h
> +/*
This file can be removed

2022-10-15 23:45 UTC, zvecr commented on keyboards/controllerworks/mini36/readme.md
> +\* Right Column numbers run right (pinky position) to left (thumb position)
```suggestion
```

2022-10-15 23:45 UTC, zvecr commented on keyboards/controllerworks/mini36/info.json
> +        "main": "left",
Currently doesnt map to anything
```suggestion
```

2022-10-16 01:29 UTC, controller-works commented on keyboards/controllerworks/mini36/mini36.h
> +/*
Removed.

2022-10-16 19:49 UTC, controller-works commented
@zvecr I believe I implemented all of the suggested changes. Thank you for your time in reviewing this PR.

2022-10-21 02:11 UTC, drashna requested changes

2022-10-21 02:11 UTC, drashna commented on keyboards/controllerworks/mini36/readme.md
> +![mini36PCB](https://i.imgur.com/6NjZ8Cq.jpg)
```suggestion
![mini36](https://i.imgur.com/JwhiE9ll.png)
![mini36PCB](https://i.imgur.com/6NjZ8Cql.jpg)
```

2022-10-21 12:21 UTC, controller-works commented
@drashna All changes are implemented as requested. Thank you for your time in reviewing this PR.

2022-10-22 19:16 UTC, drashna approved these changes

2022-10-22 22:56 UTC, zvecr approved these changes

2022-10-22 22:56 UTC, merged