Update MNK65
qmk/qmk_firmware pull request #18743
Opened 2022-10-16 09:03 UTC by kopibeng

Update MNK65 for more layout support

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-21 02:38 UTC, drashna commented
This has merge conflicts.

2022-10-22 19:13 UTC, drashna approved these changes

2022-10-23 03:04 UTC, fauxpark requested changes

2022-10-23 03:04 UTC, fauxpark commented on keyboards/kopibeng/mnk65/readme.md
> +    make kopibeng/mnk65:via
```suggestion
```

2022-10-23 03:04 UTC, fauxpark commented on keyboards/kopibeng/mnk65/mnk65.h
>      K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, K1B, K2C, K1C,      K1E, \
Since you added matrix positions to info.json, the C layout macro should be removed.

2022-10-23 03:04 UTC, fauxpark commented on keyboards/kopibeng/mnk65/info.json
> +	  "manufacturer": "kopibeng",
```suggestion
    "manufacturer": "kopibeng",
```

2022-10-23 03:04 UTC, fauxpark commented on keyboards/kopibeng/mnk65/info.json
> +	  "usb": {
```suggestion
    "usb": {
```

2022-10-25 13:53 UTC, fauxpark approved these changes

2022-10-26 19:41 UTC, merged