Add support for MNK65_STM32
qmk/qmk_firmware pull request #18744
Opened 2022-10-16 09:09 UTC by kopibeng

## Description
Add support for MNK65_STM32

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-21 02:06 UTC, drashna requested changes

2022-10-21 02:06 UTC, drashna commented on keyboards/kopibeng/mnk65_stm32/config.h
> +//#define PRODUCT         MNK65
```suggestion
```

2022-10-21 02:06 UTC, drashna commented on keyboards/kopibeng/mnk65_stm32/readme.md
> +![MNK65](https://i.imgur.com/YTrMDHj.jpg)
```suggestion
![MNK65](https://i.imgur.com/YTrMDHjh.jpg)
```

2022-10-22 19:12 UTC, drashna requested changes

2022-10-22 19:12 UTC, drashna commented on keyboards/kopibeng/mnk65_stm32/mnk65.c
> +/* Copyright 2021 Samuel Lu
File needs to match the folder name.  Eg, `mnk65_stm32.c`

2022-10-22 19:12 UTC, drashna commented on keyboards/kopibeng/mnk65_stm32/mnk65.h
> +/* Copyright 2021 Samuel Lu
File needs to match the folder name.  Eg, `mnk65_stm32.h`

2022-10-22 19:12 UTC, drashna commented on keyboards/kopibeng/mnk65_stm32/mnk65.h
> +#define LAYOUT_all( \
If this is the only layout included here, then it should be just `LAYOUT`.
```suggestion
#define LAYOUT( \
```

However, you should probably break out the different layouts.

2022-10-31 01:15 UTC, drashna approved these changes

2022-10-31 06:39 UTC, fauxpark requested changes

2022-10-31 06:39 UTC, fauxpark commented on keyboards/kopibeng/mnk65_stm32/readme.md
> +    make kopibeng/mnk65_stm32:via
```suggestion
```

2022-10-31 06:39 UTC, fauxpark commented on keyboards/kopibeng/mnk65_stm32/mnk65_stm32.h
> +}
```suggestion
```
You have matrix positions in the info.json layout so this isn't needed.

2022-11-28 08:52 UTC, fauxpark requested changes

2022-11-28 08:52 UTC, fauxpark commented on keyboards/kopibeng/mnk65_stm32/keymaps/via/keymap.c
> +		KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
```suggestion
		QK_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
```

2022-11-28 08:52 UTC, fauxpark commented on keyboards/kopibeng/mnk65_stm32/keymaps/default/keymap.c
> +		KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
```suggestion
		QK_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
```

2022-12-02 10:23 UTC, fauxpark requested changes

2022-12-02 10:23 UTC, fauxpark commented on keyboards/kopibeng/mnk65_stm32/mnk65_stm32.h
> +/* Copyright 2021 Samuel Lu
This file can be deleted.

2022-12-02 10:23 UTC, fauxpark commented on keyboards/kopibeng/mnk65_stm32/mnk65_stm32.c
> +/* Copyright 2021 Samuel Lu
This file can be deleted.

2022-12-05 00:38 UTC, fauxpark approved these changes

2022-12-08 16:48 UTC, tzarc approved these changes

2022-12-08 16:48 UTC, merged