Adds fzero keymap for GMMK Pro ANSI rev1
qmk/qmk_firmware pull request #18757
Opened 2022-10-17 22:13 UTC by fzero

## Description

Adds fzero keymap for GMMK Pro ANSI rev1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-21 01:48 UTC, drashna requested changes

2022-10-21 01:48 UTC, drashna commented on keyboards/gmmk/pro/rev1/ansi/keymaps/fzero/README.md
> +# fzero's GMMK Pro layout
Please rename the file, so that it's lower case.

2022-10-21 01:53 UTC, drashna requested changes

2022-10-21 01:53 UTC, drashna commented on keyboards/gmmk/pro/rev1/ansi/keymaps/fzero/README.md
> +# fzero's GMMK Pro layout
Please rename the file to be lower case.

2022-10-22 19:09 UTC, drashna approved these changes

2023-01-11 02:49 UTC, fauxpark approved these changes

2023-02-02 18:25 UTC, drashna requested changes

2023-02-02 18:25 UTC, drashna commented on keyboards/gmmk/pro/rev1/ansi/keymaps/fzero/keymap.c
> +void rgb_matrix_indicators_user() {
```suggestion
bool rgb_matrix_indicators_user(void) {
```

2023-02-02 18:25 UTC, drashna commented on keyboards/gmmk/pro/rev1/ansi/keymaps/fzero/keymap.c
> +}
```suggestion
    return false;
}
```

2023-02-09 19:18 UTC, drashna approved these changes

2023-02-10 09:25 UTC, drashna requested changes

2023-04-28 01:55 UTC, closed without merging