New corne keymap with Chilean spanish keymap.
qmk/qmk_firmware pull request #18765
Opened 2022-10-18 22:21 UTC by Gseguelg

2022-10-18 23:23 UTC, zvecr requested changes

2022-10-18 23:23 UTC, zvecr commented on quantum/keymap_extras/keymap_spanish_chile.h
> +/* Copyright 2015-2016 Jack Humbert
This would have to be PRed separately to `develop`.

2022-10-19 04:38 UTC, tzarc commented
Also, need a PR description, and keymap folder name needs to be lowercase.
Please refer to the [PR Checklist](https://docs.qmk.fm/#/pr_checklist) (which was in the now-deleted PR description).

2022-11-12 23:49 UTC, zvecr commented
Closing due to lack of movement.

2022-11-12 23:49 UTC, closed without merging