Kepler 33
qmk/qmk_firmware pull request #18771
Opened 2022-10-19 07:51 UTC by seityaya

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-20 07:47 UTC, drashna commented on keyboards/kepler_33/readme.md
> +# Kepler-33
Please use the default template:
```c
# %KEYBOARD%

![%KEYBOARD%](imgur.com image replace me!)

*A short description of the keyboard/project*

* Keyboard Maintainer: [%REAL_NAME%](https://github.com/%USER_NAME%)
* Hardware Supported: *The PCBs, controllers supported*
* Hardware Availability: *Links to where you can find this hardware*

Make example for this keyboard (after setting up your build environment):

    make %KEYBOARD%:default

Flashing example for this keyboard:

    make %KEYBOARD%:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2022-10-21 01:24 UTC, drashna commented on keyboards/kepler_33/readme.md
> +[![Foo](kepler-33.png)](https://www.keyboard-layout-editor.com/#/gists/a456c2256174a2cfa0b4aea832e78d8e)
Please rehost image on Imgur or similar dedicate image hosting site.

2022-10-22 18:51 UTC, drashna commented on keyboards/kepler_33/readme.md
> +![Kepler-33](https://i.imgur.com/zVvzBrO.png)
This uses a smaller, but still high res version of the image, that is more suitable for github markdown rendering. 
```suggestion
![Kepler-33](https://i.imgur.com/zVvzBrOl.png)
```

2022-10-25 05:32 UTC, drashna approved these changes

2022-10-25 07:01 UTC, fauxpark requested changes

2022-10-25 07:01 UTC, fauxpark commented on keyboards/kepler_33/readme.md
> +* Hardware Supported: *Kepler-33/proto, STM32F401*
```suggestion
True 40% keyboard. The simple and symmetric.

* Keyboard Maintainer: [Yaya](https://github.com/seityaya)
* Hardware Supported: Kepler-33/proto, STM32F401
```

2022-10-25 13:54 UTC, fauxpark approved these changes

2022-10-26 19:41 UTC, merged