add kbdpadmk3
qmk/qmk_firmware pull request #18795
Opened 2022-10-21 04:11 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-21 04:14 UTC, fauxpark requested changes

2022-10-21 04:14 UTC, fauxpark commented on keyboards/kbdfans/kbdpad/mk3/mk3.c
> +    if (IS_HOST_LED_ON(USB_LED_NUM_LOCK))
```suggestion
    if (host_keyboard_led_state().num_lock)
```

2022-10-21 05:07 UTC, drashna approved these changes

2022-10-21 14:24 UTC, zvecr requested changes

2022-10-21 14:24 UTC, zvecr commented on keyboards/kbdfans/kbdpad/mk3/keymaps/default/keymap.c
> +  ),
```suggestion
  [0] = LAYOUT_numpad_6x4( /* Base */
    KC_ESC,  KC_LCTL, KC_LALT, KC_BSPC,
    KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
    KC_P7,   KC_P8,   KC_P9,
    KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
    KC_P1,   KC_P2,   KC_P3,
    KC_P0,            KC_PDOT, KC_PENT,
  )
```

2022-10-21 14:24 UTC, zvecr commented on keyboards/kbdfans/kbdpad/mk3/mk3.h
> +    K50,      K52 \
```suggestion
    K00, K01, K02, K03, \
    K10, K11, K12, K13, \
    K20, K21, K22, \
    K30, K31, K32, K23, \
    K40, K41, K42, \
    K50,      K52, K43, \
```

2022-10-21 14:24 UTC, zvecr commented on keyboards/kbdfans/kbdpad/mk3/info.json
> +            ]
```suggestion
            "layout": [
                {"x":0, "y":0},
                {"x":1, "y":0},
                {"x":2, "y":0},
                {"x":3, "y":0},

                {"x":0, "y":1},
                {"x":1, "y":1},
                {"x":2, "y":1},
                {"x":3, "y":1},

                {"x":0, "y":2},
                {"x":1, "y":2},
                {"x":2, "y":2},

                {"x":0, "y":3},
                {"x":1, "y":3},
                {"x":2, "y":3},
                {"x":3, "y":2, "h":2},

                {"x":0, "y":4},
                {"x":1, "y":4},
                {"x":2, "y":4},

                {"x":0, "y":5, "w":2},
                {"x":2, "y":5},
                {"x":3, "y":4, "h":2}
            ]
```

2022-10-21 14:24 UTC, zvecr commented on keyboards/kbdfans/kbdpad/mk3/keymaps/via/keymap.c
> +  ),
```suggestion
  [0] = LAYOUT_numpad_6x4( /* Base */
    KC_ESC,  KC_LCTL, KC_LALT, KC_BSPC,
    KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
    KC_P7,   KC_P8,   KC_P9,
    KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
    KC_P1,   KC_P2,   KC_P3,
    KC_P0,            KC_PDOT, KC_PENT,
  ),
  [1] = LAYOUT_numpad_6x4(
    _______, _______, _______, _______,
    _______, _______, _______, _______,
    _______, _______, _______,
    _______, _______, _______, _______, 
    _______, _______, _______,
    _______,          _______, _______
  ),
  [2] = LAYOUT_numpad_6x4(
    _______, _______, _______, _______,
    _______, _______, _______, _______,
    _______, _______, _______,
    _______, _______, _______, _______, 
    _______, _______, _______,
    _______,          _______, _______
  ),
  [3] = LAYOUT_numpad_6x4(
    _______, _______, _______, _______,
    _______, _______, _______, _______,
    _______, _______, _______,
    _______, _______, _______, _______, 
    _______, _______, _______,
    _______,          _______, _______
  ),
```

2022-10-23 04:33 UTC, fauxpark requested changes

2022-10-23 04:33 UTC, fauxpark commented on keyboards/kbdfans/kbdpad/mk3/mk3.h
> +    K50,      K52, K43, \
```suggestion
    K50,      K52, K43 \
```

2022-10-23 04:33 UTC, fauxpark commented on keyboards/kbdfans/kbdpad/mk3/keymaps/via/keymap.c
> +    KC_P0,            KC_PDOT, KC_PENT,
```suggestion
    KC_P0,            KC_PDOT, KC_PENT
```

2022-10-23 04:33 UTC, fauxpark commented on keyboards/kbdfans/kbdpad/mk3/keymaps/default/keymap.c
> +    KC_P0,            KC_PDOT, KC_PENT,
```suggestion
    KC_P0,            KC_PDOT, KC_PENT
```

2022-10-25 05:48 UTC, drashna commented on keyboards/kbdfans/kbdpad/mk3/mk3.c
> +void rgb_matrix_indicators_user(void)
Note to self: #18450

2022-10-25 05:49 UTC, drashna submitted a review, later dismissed

2022-10-27 00:17 UTC, drashna approved these changes

2022-11-28 01:01 UTC, drashna requested changes

2022-11-28 01:01 UTC, drashna commented on keyboards/kbdfans/kbdpad/mk3/mk3.c
> +void rgb_matrix_indicators_user(void)
```suggestion
bool rgb_matrix_indicators_kb(void) {
    if (!rgb_matrix_indicators_user()) { 
        return false;
    }
```

2022-11-28 01:01 UTC, drashna commented on keyboards/kbdfans/kbdpad/mk3/mk3.c
> +    {
```suggestion
    if (host_keyboard_led_state().num_lock) {
```

2022-11-28 01:49 UTC, drashna requested changes

2022-11-28 01:49 UTC, drashna commented on keyboards/kbdfans/kbdpad/mk3/mk3.c
> +}
```suggestion
    return true;
}
```

2022-11-28 01:49 UTC, drashna commented on keyboards/kbdfans/kbdpad/mk3/mk3.c
> +__attribute__ ((weak))
```suggestion
```

2022-12-01 06:12 UTC, fauxpark approved these changes

2022-12-04 09:36 UTC, drashna requested changes

2022-12-04 09:36 UTC, drashna commented on keyboards/kbdfans/kbdpad/mk3/config.h
> +#define RGB_MATRIX_LED_COUNT 21
```suggestion
#pragma once

#define RGB_MATRIX_LED_COUNT 21
```

2022-12-04 18:52 UTC, drashna approved these changes

2022-12-04 18:53 UTC, merged