gmmk gmmk2 p65: new keymap
qmk/qmk_firmware pull request #18808
Opened 2022-10-22 10:26 UTC by thekorn

## Description

Thats a slight variation of the default keymap for this keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-22 18:42 UTC, drashna requested changes

2022-10-22 18:42 UTC, drashna commented on keyboards/gmmk/pro/rev1/ansi/keymaps/andrebrait/config.h
> +
```suggestion
```

2022-10-23 07:32 UTC, thekorn commented
thanks @drashna - that was a totally unintended change...

2022-10-25 05:53 UTC, drashna commented
No worries, it happens some times. Bad merges, and what not.

2022-10-25 05:53 UTC, drashna approved these changes

2022-10-25 07:06 UTC, fauxpark approved these changes

2022-10-26 19:38 UTC, merged