Add ISO Encoder variant of Keychron Q1v1
qmk/qmk_firmware pull request #18829
Opened 2022-10-24 03:41 UTC by adophoxia

## Description
* Adds the ISO Encoder variant of the Keychron Q1v1 (A means to complete the v1 revision of the Q1)
  *  Made to be in spec with how the Q3 was structured to make use of the new `common` folder for the KC-specific custom keycodes and other functionality.
  * Added new compile option in `q1.h`. (Should not be able to conflict with [#18713](https://github.com/qmk/qmk_firmware/pull/18713) if/when it gets merged.)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-25 05:34 UTC, drashna approved these changes

2022-10-25 07:02 UTC, fauxpark requested changes

2022-10-25 07:02 UTC, fauxpark commented on keyboards/keychron/q1/iso_encoder/readme.md
> +- Turn colckwise to increase volume and turn anti-colckwise to decrease volume.
```suggestion
- Turn clockwise to increase volume and turn anti-clockwise to decrease volume.
```

2022-10-25 13:22 UTC, adophoxia commented on keyboards/keychron/q1/iso_encoder/readme.md
> +- Turn colckwise to increase volume and turn anti-colckwise to decrease volume.
Resolved.

2022-11-08 15:22 UTC, fauxpark approved these changes

2022-11-08 16:21 UTC, merged