Add keyboard - Dactyl Manuform 5x6 with 6 thumb cluster
qmk/qmk_firmware pull request #18845
Opened 2022-10-25 16:15 UTC by fgoodwin

## Description

Adding a new keyboard ased on the 5x6_5 Dactyl Manuform but with an additional thumb button and different layout

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-08 12:21 UTC, keyboard-magpie approved these changes

2022-11-08 15:37 UTC, fauxpark requested changes

2022-11-08 15:37 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6_6/readme.md
> +Dactyl Manuform (5x6) with 6 thumb cluster
```suggestion
# Dactyl Manuform (5x6) with 6 thumb cluster
```

2022-11-08 15:37 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6_6/readme.md
> +the [Dactyl-Manuform](https://github.com/tshort/dactyl-keyboard) is a split curved keyboard based on the design of [adereth dactyl](https://github.com/adereth/dactyl-keyboard) and thumb cluster desig
```suggestion
The [Dactyl-Manuform](https://github.com/tshort/dactyl-keyboard) is a split curved keyboard based on the design of [adereth dactyl](https://github.com/adereth/dactyl-keyboard) and thumb cluster design of the [manuform](https://geekhack.org/index.php?topic=46015.0) keyboard, the hardware is similar to the let's split keyboard. All information needed for making one is in the first link.
```

2022-11-08 15:37 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6_6/readme.md
> +    Hardware Supported: Pro Micro Micro Micro USB or USB C
```suggestion
![Imgur](https://i.imgur.com/MvtMG1vh.png)

* Keyboard Maintainer: fgoodwin
* Hardware Supported: Pro Micro Micro Micro USB or USB C
```

2022-11-08 15:37 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6_6/readme.md
> +qmk flash -kb handwired/dactyl_manuform/5x6_6 -km defaul
```suggestion
    make handwired/dactyl_manuform/5x6_6:default

Flashing example for this keyboard:

    make handwired/dactyl_manuform/5x6_6:default:flash
```

2022-11-08 15:37 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6_6/readme.md
> +    **Keycode in layout**: Press the key mapped to RESET (by default hold down MO(1) and press the left most key in row 5 on the left hand half of the keyboard)
```suggestion
**Physical reset button**: Briefly press the reset button on the bottom of the case, or bridge the reset and ground pins momentarily on the pro micro
**Keycode in layout**: Press the key mapped to `QK_BOOT` (by default hold down `MO(1)` and press the left most key in row 5 on the left hand half of the keyboard)
```

2022-11-11 05:19 UTC, fauxpark approved these changes

2022-11-13 01:01 UTC, drashna approved these changes

2022-11-13 01:01 UTC, merged