Bubble 75
qmk/qmk_firmware pull request #18863
Opened 2022-10-27 02:19 UTC by d-floe

## Description

Bubble75 is a compact exploded F-Row 75% keyboard with Per-Key RGB. Includes Default and VIA keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-31 02:02 UTC, drashna reviewed
It looks like you pulled this from kbfirmware.com directly. 

If so, you may want to run the config file through this: 
https://noroadsleft.github.io/kbf_qmk_converter/

And then overwrite the files here with what that outputs.

2022-10-31 02:02 UTC, drashna commented on keyboards/bubble75/hotswap/config.h
> +)
```suggetion
```

2022-10-31 02:02 UTC, drashna commented on keyboards/bubble75/hotswap/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED false
```suggestion
```

2022-10-31 02:02 UTC, drashna commented on keyboards/bubble75/hotswap/hotswap.c
> +#include "rgb_matrix_types.h"
```suggestion
```

2022-10-31 02:02 UTC, drashna commented on keyboards/bubble75/hotswap/hotswap.c
> +
```suggestion

2022-10-31 02:02 UTC, drashna commented on keyboards/bubble75/hotswap/keymaps/default/keymap.c
> +#include "hotswap.h"
```suggestion
#include QMK_KEYBOARD_H
```

2022-10-31 06:11 UTC, d-floe commented
> It looks like you pulled this from kbfirmware.com directly.
> 
> If so, you may want to run the config file through this: https://noroadsleft.github.io/kbf_qmk_converter/
> 
> And then overwrite the files here with what that outputs.
I don't have access to the original JSON made to build this Firmware, unfortunately. This is a little complicated for me.
I wrote up an info.json with KLE but I am unsure if it is sufficient
`{
    "keyboard_name": "bubble75", 
    "url": "", 
    "manufacturer": "phl",
    "maintainer": "velocifire", 
    "usb": {
        "vid": "0x4242",
        "pid": "0x5A4C",
    },
    "layouts": {
        "LAYOUT": {
            "layout": [{"x":0, "y":0}, 
                       {"x":1.5, "y":0}, 
                       {"x":2.5, "y":0}, 
                       {"x":3.5, "y":0}, 
                       {"x":4.5, "y":0}, 
                       {"x":6, "y":0}, 
                       {"x":7, "y":0}, 
                       {"x":8, "y":0}, 
                       {"x":9, "y":0}, 
                       {"x":10.5, "y":0}, 
                       {"x":11.5, "y":0}, 
                       {"x":12.5, "y":0}, 
                       {"x":13.5, "y":0}, 
                       {"x":15, "y":0}, 
                       {"x":0, "y":1.5}, 
                       {"x":1, "y":1.5}, 
                       {"x":2, "y":1.5}, 
                       {"x":3, "y":1.5}, 
                       {"x":4, "y":1.5}, 
                       {"x":5, "y":1.5}, 
                       {"x":6, "y":1.5}, 
                       {"x":7, "y":1.5}, 
                       {"x":8, "y":1.5}, 
                       {"x":9, "y":1.5}, 
                       {"x":10, "y":1.5}, 
                       {"x":11, "y":1.5}, 
                       {"x":12, "y":1.5}, 
                       {"x":13, "y":1.5, "w":2}, 
                       {"x":15, "y":1.5}, 
                       {"x":0, "y":2.5, "w":1.5}, 
                       {"x":1.5, "y":2.5}, 
                       {"x":2.5, "y":2.5}, 
                       {"x":3.5, "y":2.5}, 
                       {"x":4.5, "y":2.5}, 
                       {"x":5.5, "y":2.5}, 
                       {"x":6.5, "y":2.5}, 
                       {"x":7.5, "y":2.5}, 
                       {"x":8.5, "y":2.5}, 
                       {"x":9.5, "y":2.5}, 
                       {"x":10.5, "y":2.5}, 
                       {"x":11.5, "y":2.5}, 
                       {"x":12.5, "y":2.5}, 
                       {"x":13.5, "y":2.5, "w":1.5}, 
                       {"x":15, "y":2.5}, 
                       {"x":0, "y":3.5, "w":1.75}, 
                       {"x":1.75, "y":3.5}, 
                       {"x":2.75, "y":3.5}, 
                       {"x":3.75, "y":3.5}, 
                       {"x":4.75, "y":3.5}, 
                       {"x":5.75, "y":3.5}, 
                       {"x":6.75, "y":3.5}, 
                       {"x":7.75, "y":3.5}, 
                       {"x":8.75, "y":3.5}, 
                       {"x":9.75, "y":3.5}, 
                       {"x":10.75, "y":3.5}, 
                       {"x":11.75, "y":3.5}, 
                       {"x":12.75, "y":3.5, "w":2.25}, 
                       {"x":15, "y":3.5}, 
                       {"x":0, "y":4.5, "w":2.25}, 
                       {"x":2.25, "y":4.5}, 
                       {"x":3.25, "y":4.5}, 
                       {"x":4.25, "y":4.5}, 
                       {"x":5.25, "y":4.5}, 
                       {"x":6.25, "y":4.5}, 
                       {"x":7.25, "y":4.5}, 
                       {"x":8.25, "y":4.5}, 
                       {"x":9.25, "y":4.5}, 
                       {"x":10.25, "y":4.5}, 
                       {"x":11.25, "y":4.5}, 
                       {"x":12.25, "y":4.5, "w":1.75}, 
                       {"x":14, "y":4.5}, 
                       {"x":15, "y":4.5}, 
                       {"x":0, "y":5.5, "w":1.25}, 
                       {"x":1.25, "y":5.5, "w":1.25}, 
                       {"x":2.5, "y":5.5, "w":1.25}, 
                       {"x":3.75, "y":5.5, "w":6.25}, 
                       {"x":10, "y":5.5, "w":1.25}, 
                       {"x":11.25, "y":5.5, "w":1.25}, 
                       {"x":13, "y":5.5}, 
                       {"x":14, "y":5.5}, 
                       {"x":15, "y":5.5}]
        }
    }
}
`

2022-11-19 20:03 UTC, drashna commented on keyboards/bubble75/hotswap/hotswap.c
> +    void rgb_matrix_indicators_kb(void) {
Note to self: #18450

2022-11-19 20:06 UTC, drashna requested changes

2022-11-19 20:06 UTC, drashna commented on keyboards/bubble75/hotswap/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-11-19 20:06 UTC, drashna commented on keyboards/bubble75/hotswap/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-11-19 20:06 UTC, drashna commented on keyboards/bubble75/hotswap/rules.mk
> +NO_USB_STARTUP_CHECK = yes
Via should not be enabled at the keyboard level, only the keymap level. 

```suggestion
# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
AUDIO_ENABLE = no           # Audio output

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
NO_USB_STARTUP_CHECK = yes
```

2022-11-19 20:06 UTC, drashna commented on keyboards/bubble75/hotswap/keymaps/via/rules.mk
> +VIA_ENABLE ?=yes
```suggestion
VIA_ENABLE = yes
```

2022-11-19 20:06 UTC, drashna commented on keyboards/bubble75/hotswap/readme.md
> +![image](https://user-images.githubusercontent.com/31980883/198159649-718a85f7-5d49-47b6-a46e-fa8c656d27c3.png)
Please rehost on imgur.

2022-11-20 05:17 UTC, d-floe commented
@drashna I made the changes requested, however, my Bubble75 no longer lets me change the RGB mode and doesn't get detected by VIA anymore. No errors while compiling.

2022-11-20 06:50 UTC, d-floe commented
> @drashna I made the changes requested, however, my Bubble75 no longer lets me change the RGB mode and doesn't get detected by VIA anymore. No errors while compiling.
> 
> EDIT: My mistake, VIA seems to work fine. Still no ability to change RGB modes though. Im able to configure the lighting in VIA now, but the only lighting mode that works is solid color.

RGB has been fixed.

2022-11-20 18:47 UTC, drashna approved these changes

2022-11-28 02:05 UTC, drashna commented on keyboards/bubble75/hotswap/hotswap.c
> +}
```suggestion
    return true;
}
```

2022-11-29 08:03 UTC, d-floe commented
@drashna  Attempting to make these changes on my local copy results in an error when compiling
```Compiling: keyboards/bubble75/hotswap/hotswap.c                                                    keyboards/bubble75/hotswap/hotswap.c:47:6: error: conflicting types for 'rgb_matrix_indicators_kb'

 bool rgb_matrix_indicators_kb(void) {
      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from quantum/quantum.h:36,
                 from keyboards/bubble75/hotswap/hotswap.h:19,
                 from keyboards/bubble75/hotswap/hotswap.c:17:
quantum/rgb_matrix/rgb_matrix.h:132:6: note: previous declaration of 'rgb_matrix_indicators_kb' was here
 void rgb_matrix_indicators_kb(void);
      ^~~~~~~~~~~~~~~~~~~~~~~~
keyboards/bubble75/hotswap/hotswap.c: In function 'rgb_matrix_indicators_kb':
keyboards/bubble75/hotswap/hotswap.c:48:9: error: invalid use of void expression
     if (!rgb_matrix_indicators_user()) {
         ^
keyboards/bubble75/hotswap/hotswap.c:55:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1.exe: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [builddefs/common_rules.mk:359: .build/obj_bubble75_hotswap_via/keyboards/bubble75/hotswap/hotswap.o] Error 1
Make finished with errors
make: *** [Makefile:414: bubble75/hotswap:via] Error 1

2022-11-29 09:58 UTC, d-floe commented
> @drashna Attempting to make these changes on my local copy results in an error when compiling
> 
> ```
> Compiling: keyboards/bubble75/hotswap/hotswap.c                                                    In file included from quantum/rgb_matrix/rgb_matrix.h:23,
>                  from quantum/quantum.h:36,
>                  from keyboards/bubble75/hotswap/hotswap.h:19,
>                  from keyboards/bubble75/hotswap/hotswap.c:17:
> quantum/rgb_matrix/rgb_matrix_types.h:81:23: error: 'RGB_MATRIX_LED_COUNT' undeclared here (not in a function); did you mean 'RGB_MATRIX_ENABLE'?
>      led_point_t point[RGB_MATRIX_LED_COUNT];
>                        ^~~~~~~~~~~~~~~~~~~~
>                        RGB_MATRIX_ENABLE
> keyboards/bubble75/hotswap/hotswap.c: In function 'rgb_matrix_indicators_kb':
> keyboards/bubble75/hotswap/hotswap.c:55:1: error: control reaches end of non-void function [-Werror=return-type]
>  }
>  ^
> cc1.exe: all warnings being treated as errors
>  [ERRORS]
>  |
>  |
>  |
> make[1]: *** [builddefs/common_rules.mk:360: .build/obj_bubble75_hotswap_via/keyboards/bubble75/hotswap/hotswap.o] Error 1
> Make finished with errors
> make: *** [Makefile:414: bubble75/hotswap:via] Error 1
> ```
> 
> This is how I have formatted lines 47-55 of `hotswap.c`
> 
> ```
> bool rgb_matrix_indicators_kb(void) {
>     if (!rgb_matrix_indicators_user()) {
>         return false;
>     }
>     if (host_keyboard_led_state().caps_lock) {  // Capslock = WHITE
>         rgb_matrix_set_color(57, 255, 255, 255);
>       return true;
>     }
> }
> ```

Issue has been resolved with help from @waffle87 from the QMK discord.

2022-12-04 05:35 UTC, drashna requested changes

2022-12-04 05:35 UTC, drashna commented on keyboards/bubble75/hotswap/config.h
> +/* prevent stuck modifiers */
```suggestion
```

2022-12-04 05:35 UTC, drashna commented on keyboards/bubble75/hotswap/config.h
> +
These are the default, so they don't need to be defined
```suggestion
```

2022-12-04 05:35 UTC, drashna commented on keyboards/bubble75/hotswap/readme.md
> +![image](https://i.imgur.com/9J01bYH.png)
```suggestion
![image](https://i.imgur.com/9J01bYHh.png)
```

The additional `h` in the url/filename renders a smaller version of the image, that is still high res but better for github's markdown rendering

2022-12-05 00:34 UTC, fauxpark requested changes

2022-12-05 00:34 UTC, fauxpark commented on keyboards/bubble75/hotswap/config.h
> +#define RGB_MATRIX_STARTUP_SPD 127
```suggestion
//#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_DEFAULT_SPD 127
```

2022-12-05 00:34 UTC, fauxpark commented on keyboards/bubble75/hotswap/config.h
> +#define RGB_DISABLE_AFTER_TIMEOUT 0
```suggestion
```

2022-12-11 02:48 UTC, drashna approved these changes

2023-01-11 20:33 UTC, d-floe commented
Hey there, any update on this? It's been radio silent for about a month. I don't mean to rush

2023-01-13 06:37 UTC, fauxpark requested changes

2023-01-13 06:37 UTC, fauxpark commented on keyboards/bubble75/hotswap/config.h
> +#define MATRIX_COLS 15
```suggestion
```

2023-01-13 06:37 UTC, fauxpark commented on keyboards/bubble75/hotswap/rules.mk
> +
```suggestion
```

2023-01-13 06:37 UTC, fauxpark commented on keyboards/bubble75/hotswap/info.json
> +    },
```suggestion
    },
    "processor": "atmega32u4",
    "bootloader": "atmel-dfu",
```

2023-01-14 02:09 UTC, fauxpark approved these changes

2023-01-17 04:33 UTC, merged