[Keyboard] Add Constellation Rev3
qmk/qmk_firmware pull request #18868
Opened 2022-10-27 07:54 UTC by Xelus22

## Description

Add Constellation Rev3. It is Rev1 but the space is on a different column.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add Constellation Rev3

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-31 02:08 UTC, drashna commented on keyboards/aeboards/constellation/rev3/readme.md
> +</ol>
```suggestion
* Software reset on Fn + Backspace
* Bootmagic reset: hold down the top left key (usually escape) and plugin the keyboard
* Physical reset: on the back of the PCB, there is a ISP header which you should short the RST and GND together
```

2022-11-12 22:23 UTC, drashna approved these changes

2022-11-13 07:42 UTC, fauxpark requested changes

2022-11-13 07:42 UTC, fauxpark commented on keyboards/aeboards/constellation/rev3/readme.md
> +    make aeboards/constellation/rev3:via
```suggestion
```

2022-11-13 07:48 UTC, fauxpark approved these changes

2022-11-15 09:33 UTC, merged