[Keyboard] Add Satellite Rev1
qmk/qmk_firmware pull request #18869
Opened 2022-10-27 08:10 UTC by Xelus22

## Description

Add Satellite Rev1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add Satellite Rev1

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-31 02:07 UTC, drashna requested changes

2022-10-31 02:07 UTC, drashna commented on keyboards/aeboards/satellite/rev1/config.h
> +#define PRODUCT         AEBoards Satellite Rev1
Please move this to your info.json

2022-10-31 02:07 UTC, drashna commented on keyboards/aeboards/satellite/rev1/readme.md
> +</ol>
```suggestion
* Software reset on Fn + Backspace
* Bootmagic reset: hold down the top left key (usually escape) and plugin the keyboard
* Physical reset: on the back of the PCB, there is a ISP header which you should short the RST and GND together
```

2022-10-31 02:07 UTC, drashna commented on keyboards/aeboards/satellite/rev1/rev1.c
> +__attribute__ ((weak))
This doesn't need to be weak.  It can be reconfigured at runtime.
```suggestion
```

2022-10-31 02:07 UTC, drashna commented on keyboards/aeboards/satellite/rev1/rev1.c
> +#include "rev1.h"
```suggestion
#include "rev1.h"
#include "i2c_master.h"
#include "drivers/led/issi/is31fl3731.h"
```

2022-11-08 07:50 UTC, drashna approved these changes

2022-11-08 15:30 UTC, fauxpark requested changes

2022-11-08 15:30 UTC, fauxpark commented on keyboards/aeboards/satellite/readme.md
> +    make aeboards/satellite/rev1:via
```suggestion
```

2022-11-20 12:34 UTC, fauxpark requested changes

2022-11-20 12:34 UTC, fauxpark commented on keyboards/aeboards/satellite/keymaps/default/keymap.c
> +		KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SLCK, KC_PAUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
		KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SCRL, KC_PAUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2022-11-20 12:34 UTC, fauxpark commented on keyboards/aeboards/satellite/keymaps/via/keymap.c
> +		KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SLCK, KC_PAUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
		KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SCRL, KC_PAUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2022-11-20 12:40 UTC, fauxpark approved these changes

2022-11-20 18:24 UTC, merged