Support for pumpkin pad
qmk/qmk_firmware pull request #18897
Opened 2022-10-28 10:59 UTC by Jels02

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-28 11:20 UTC, zvecr requested changes

2022-10-28 11:20 UTC, zvecr commented on keyboards/laser_ninja/pumpkin_pad/info.json
> +    },
```suggestion
```

2022-10-28 11:20 UTC, zvecr commented on keyboards/laser_ninja/pumpkin_pad/info.json
> +        "count": 28,
```suggestion
```

2022-10-28 11:20 UTC, zvecr commented on keyboards/laser_ninja/pumpkin_pad/keymaps/default/keymap.c
> +)
```suggestion
)
```

2022-10-28 19:38 UTC, drashna requested changes

2022-10-28 19:38 UTC, drashna commented on keyboards/laser_ninja/pumpkin_pad/readme.md
> +![pumpkin-pad](https://i.imgur.com/jFkl9rw.jpg)
```suggestion
![pumpkin-pad](https://i.imgur.com/jFkl9rwh.jpg)
```

2022-10-31 02:48 UTC, drashna approved these changes

2022-10-31 06:45 UTC, fauxpark approved these changes

2022-11-12 22:56 UTC, merged