Add Brutal v2 1800 PCB to QMK
qmk/qmk_firmware pull request #18891
Opened 2022-10-28 00:02 UTC by awkannan

## Description

Add the Brutal v2 1800 PCB to QMK

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-28 19:33 UTC, drashna approved these changes

2022-10-28 20:33 UTC, fauxpark requested changes

2022-10-28 20:33 UTC, fauxpark commented on keyboards/cannonkeys/brutalv2_1800/readme.md
> +* Hardware Supported: RP2040
```suggestion
* Keyboard Maintainer: [Andrew Kannan](https://github.com/awkannan)
* Hardware Supported: RP2040
```

2022-10-28 20:33 UTC, fauxpark commented on keyboards/cannonkeys/brutalv2_1800/keymaps/via/keymap.c
> +		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_BSPC, KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_BSPC, KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
```

2022-10-28 20:33 UTC, fauxpark commented on keyboards/cannonkeys/brutalv2_1800/keymaps/default/keymap.c
> +		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_BSPC, KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_BSPC, KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
```

2022-11-03 13:30 UTC, awkannan commented
@faxupark Ready for re-review :) Thank you!

2022-11-03 14:39 UTC, fauxpark approved these changes

2022-11-08 16:23 UTC, merged