Add the Ortho60 v2 Keyboard to QMK
qmk/qmk_firmware pull request #18890
Opened 2022-10-27 20:16 UTC by awkannan

## Description

Adding the Ortho60v2 keyboard to QMK.
I made it a new top-level keyboard because of the addition of an encoder.
MCU has also been swapped to RP2040

A revision of the existing top level Ortho60 didn't feel quite appropriate due to these changes - but if necessary, I can change organization to reflect this.

Targeting develop so we can use the PWM functionality @KarlK90 has added :)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-28 19:33 UTC, drashna requested changes

2022-10-28 19:33 UTC, drashna commented on keyboards/cannonkeys/ortho60v2/keymaps/default/keymap.c
> +#define _LOWER 2
```suggestion
enum custom_layers {
    _BASE,
    _RAISE,
    _LOWER,
};
```

2022-10-28 19:33 UTC, drashna commented on keyboards/cannonkeys/ortho60v2/keymaps/via/rules.mk
> +LTO_ENABLE = yes
```suggestion
```

2022-11-03 13:30 UTC, awkannan commented
@drashna Ready for re-review :) Thank you!

2022-11-20 07:13 UTC, drashna requested changes

2022-11-20 07:13 UTC, drashna commented on keyboards/cannonkeys/ortho60v2/ortho60v2.c
> +}
```suggestion
#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) {
        return false;
    }
    if (clockwise) {
        tap_code_delay(KC_VOLU, 10);
    } else {
        tap_code_delay(KC_VOLD, 10);
    }
    return true;
}
#endif
```

2022-11-20 12:22 UTC, fauxpark requested changes

2022-11-20 12:22 UTC, fauxpark commented on keyboards/cannonkeys/ortho60v2/readme.md
> +* Hardware Availability: [CannonKeys](https://cannonkeys.com)
```suggestion
* Keyboard Maintainer: [Andrew Kannan](https://github.com/awkannan1)
* Hardware Supported: RP2040
* Hardware Availability: [CannonKeys](https://cannonkeys.com)
```

2022-11-30 20:16 UTC, drashna approved these changes

2022-12-01 05:56 UTC, fauxpark approved these changes

2022-12-04 07:15 UTC, merged