Add Bonsai C4 as a platform board file
qmk/qmk_firmware pull request #18901
Opened 2022-10-29 02:45 UTC by infinityis

This creates Bonsai C4 as a board file (as recommended [here](https://discord.com/channels/440868230475677696/440868230475677698/1013346652247035944)), which makes the ProMicro to Bonsai C4 converter work without having to configure hardware, change/add code, etc.

This also removes the Bonsai C4 template code from the keyboards/customMK folder which demonstrated how to configure the hardware, since that is no longer needed, and updates the converter documentation accordingly.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-12 00:09 UTC, zvecr approved these changes

2022-11-12 23:38 UTC, zvecr commented
Conflicts will need to be resolved, otherwise it will fall into the next develop cycle.

2022-11-13 01:30 UTC, infinityis commented
Conflicts have been resolved

2022-11-13 15:53 UTC, tzarc requested changes
Just a small fix, rest LGTM.

2022-11-13 15:53 UTC, tzarc commented on platforms/chibios/boards/BONSAI_C4/configs/config.h
> +#    define EXTERNAL_FLASH_SPI_CLOCK_DIVISOR 1  // 96MHz; max supported by W25Q128JV is 133MHz
Minimum clock divisor on STM32 is `/2` -- it'd work with this code in place, as it'll default to `/2` anyway, but for clarity it should probably be fixed up.
```suggestion
#    define EXTERNAL_FLASH_SPI_CLOCK_DIVISOR 2  // 48MHz; max supported by W25Q128JV is 133MHz
```

2022-11-13 23:27 UTC, infinityis commented
Fixed, thank you!

2022-11-13 23:59 UTC, merged