Add WITF
qmk/qmk_firmware pull request #18922
Opened 2022-11-01 02:14 UTC by Sleepdealr

## Description

WITF Keyboard PR

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-01 03:00 UTC, zvecr requested changes

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
Should be filled in

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/readme.md
> +    make witf:default:flash
```suggestion
    make ramlord/witf:default

Flashing example for this keyboard:

    make ramlord/witf:default:flash
```

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/readme.md
> +* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```suggestion
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
Needs compliant licence header

```suggestion
// Copyright 2022 Sleepdealer (@Sleepdealr)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
```

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Needs compliant licence header

```suggestion
// Copyright 2022 Sleepdealer (@Sleepdealr)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
```

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/info.json
> +    "processor": "STM32F072",
```suggestion
    "indicators": {
        "num_lock": "A5",
        "caps_lock": "A3",
        "scroll_lock": "A4"
    },
    "processor": "STM32F072",
```

2022-11-01 03:00 UTC, zvecr commented on keyboards/ramlord/witf/config.h
> +// Copyright 2022 Sleepdealer (@Sleepdealr)
This file should be removed

2022-11-19 05:24 UTC, fauxpark approved these changes

2022-11-20 03:45 UTC, drashna approved these changes

2022-11-20 03:46 UTC, merged