[Add function] add 'Split Space and ISO and delete RGUI for Promise 87
qmk/qmk_firmware pull request #18929
Opened 2022-11-01 11:47 UTC by spbgzh

## Description
add 'Split Space and ISO for Promise 87

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
https://github.com/qmk/qmk_firmware/pull/17525

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-08 15:34 UTC, fauxpark approved these changes

2022-11-20 04:14 UTC, fauxpark requested changes

2022-11-20 04:14 UTC, fauxpark commented on keyboards/wuque/promise87/ansi/keymaps/default_tkl_f13_ansi_iso/keymap.c
> +        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,  KC_PSCR, KC_SLCK, KC_PAUS,
```suggestion
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,  KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-11-20 04:14 UTC, fauxpark commented on keyboards/wuque/promise87/ansi/keymaps/default_tkl_f13_ansi_split_space/keymap.c
> +        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,  KC_PSCR, KC_SLCK, KC_PAUS,
```suggestion
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,  KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-11-20 04:14 UTC, fauxpark commented on keyboards/wuque/promise87/wkl/keymaps/default_tkl_f13_ansi_wkl_iso/keymap.c
> +        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,     KC_PSCR, KC_SLCK, KC_PAUS,
```suggestion
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,     KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-11-20 04:14 UTC, fauxpark commented on keyboards/wuque/promise87/wkl/keymaps/default_tkl_f13_ansi_wkl_split_space/keymap.c
> +        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,     KC_PSCR, KC_SLCK, KC_PAUS,
```suggestion
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,     KC_PSCR, KC_SCRL, KC_PAUS,
```

2022-11-20 11:12 UTC, spbgzh commented
Emmm I just request review, I dont know why it removed

2022-11-20 12:32 UTC, fauxpark approved these changes

2022-11-21 00:52 UTC, noroadsleft reviewed
Is the `wuque/promise87/ansi` version just short for `winkey` (as opposed to `wkl` winkeyless)?

2022-11-21 08:59 UTC, spbgzh commented
> Is the `wuque/promise87/ansi` version just short for `winkey` (as opposed to `wkl` winkeyless)?

wkl is for win key less

2022-11-21 14:05 UTC, noroadsleft commented
> just add the win key from wkl version

Okay, in my opinion that should be renamed during the next Breaking Changes cycle (2023q1).

I have some change requests for you but I'm on mobile right now; will have to wait until I'm back at my PC.

2022-11-22 07:05 UTC, spbgzh commented
@noroadsleft ok👌

2022-11-22 20:55 UTC, noroadsleft approved these changes

2022-11-22 20:56 UTC, merged

2022-11-22 20:56 UTC, noroadsleft commented
Thanks!