[Keyboard] Add YR80
qmk/qmk_firmware pull request #18945
Opened 2022-11-03 19:42 UTC by jiaxin96

## Description

Add YR80 Rev1.0 keyboard.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-12 23:14 UTC, drashna requested changes

2022-11-12 23:14 UTC, drashna commented on keyboards/yandrstudio/yr80/yr80.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2022-11-12 23:14 UTC, drashna commented on keyboards/yandrstudio/yr80/yr80.c
> +    rgblight_set_layer_state(0, led_state.caps_lock);
```suggestion
    if (!led_update_user(led_state)) { return false; }
    rgblight_set_layer_state(0, led_state.caps_lock);
```

2022-11-19 21:34 UTC, drashna approved these changes

2022-11-20 04:08 UTC, fauxpark approved these changes

2022-11-20 08:29 UTC, merged