Align haptic feedback keycode names
qmk/qmk_firmware pull request #18964
Opened 2022-11-05 15:31 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-05 23:52 UTC, tzarc approved these changes

2022-11-06 04:40 UTC, fauxpark requested changes

2022-11-06 04:40 UTC, fauxpark commented on data/constants/keycodes/keycodes_0.0.1_quantum.hjson
> +                "HF_MOD"
```suggestion
                "HF_NEXT"
```

2022-11-06 04:40 UTC, fauxpark commented on data/constants/keycodes/keycodes_0.0.1_quantum.hjson
> +                "HF_RMOD"
```suggestion
                "HF_PREV"
```

2022-11-06 04:40 UTC, fauxpark commented on data/constants/keycodes/keycodes_0.0.1_quantum.hjson
> +                "HF_FBK"
```suggestion
                "HF_FDBK"
```

2022-11-06 04:40 UTC, fauxpark commented on docs/feature_haptic_feedback.md
> +|`QK_HAPTIC_MODE_PREVIOUS`    |`HF_RMOD`| Go to previous DRV2605L waveform                      |
```suggestion
|`QK_HAPTIC_FEEDBACK_TOGGLE`  |`HF_FDBK`| Toggle feedback to occur on keypress, release or both |
|`QK_HAPTIC_BUZZ_TOGGLE`      |`HF_BUZZ`| Toggle solenoid buzz on/off                           |
|`QK_HAPTIC_MODE_NEXT`        |`HF_NEXT`| Go to next DRV2605L waveform                          |
|`QK_HAPTIC_MODE_PREVIOUS`    |`HF_PREV`| Go to previous DRV2605L waveform                      |
```

2022-11-06 04:40 UTC, fauxpark commented on quantum/keycodes.h
> +    HF_RMOD    = QK_HAPTIC_MODE_PREVIOUS,
```suggestion
    HF_FDBK    = QK_HAPTIC_FEEDBACK_TOGGLE,
    HF_BUZZ    = QK_HAPTIC_BUZZ_TOGGLE,
    HF_NEXT    = QK_HAPTIC_MODE_NEXT,
    HF_PREV    = QK_HAPTIC_MODE_PREVIOUS,
```

2022-11-07 00:38 UTC, fauxpark approved these changes

2022-11-07 02:43 UTC, merged