[Keymap] add crkbd/keymaps/markstos
qmk/qmk_firmware pull request #19010
Opened 2022-11-09 12:32 UTC by markstos

## Description

Adds "markstos" layout for crkbd

## Types of Changes

- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-11 05:51 UTC, drashna requested changes

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/config.h
> +    #define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/config.h
> +#define PREVENT_STUCK_MODIFERS
This setting was deprecating a long time ago, and is the default behavior now.
```suggestion
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/config.h
> +#define USE_SERIAL_PD2
```suggestion
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +
```suggestion
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/rules.mk
> +LINK_TIME_OPTIMIZATION_ENABLE = yes
```suggestion
LTO_ENABLE = yes
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/rules.mk
> +BACKLIGHT_ENABLE = no  # Enable keyboard backlight functionality
As far as I'm aware, no version of the corne supports the backlight feature. 
```suggestion
```

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/rules.mk
> +TAP_DANCE_ENABLE = no
Nor tapdance.

2022-11-11 05:51 UTC, drashna commented on keyboards/crkbd/keymaps/markstos/README.md
> +# Markstos Corne keyboard layout
Please rename the file to be all lower case.

2022-11-13 13:29 UTC, markstos commented
@drashna, thank you for the peer-review.

I have pushed fixup commits with the requested refinements and believe this branch is ready for a squash-and-merge.

Thanks.

2022-11-20 03:54 UTC, drashna approved these changes

2022-11-20 04:15 UTC, fauxpark requested changes

2022-11-20 04:15 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +  [_FUNC] = LAYOUT( \
```suggestion
  [_FUNC] = LAYOUT(
```

2022-11-20 04:15 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +  [_RAISE] = LAYOUT( \
```suggestion
  [_RAISE] = LAYOUT(
```

2022-11-20 04:15 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +  [_LOWER] = LAYOUT( \
```suggestion
  [_LOWER] = LAYOUT(
```

2022-11-20 04:15 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +  [_QWERTY] = LAYOUT( \
```suggestion
  [_QWERTY] = LAYOUT(
```

2022-11-20 04:15 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +      _______, KC_CAPS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX , XXXXXXX, XXXXXXX, XXXXXXX, RESET  ,XXXXXXX ,
```suggestion
      _______, KC_CAPS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                     XXXXXXX , XXXXXXX, XXXXXXX, XXXXXXX, QK_BOOT,XXXXXXX ,
```

2022-11-20 16:04 UTC, markstos commented
All suggested refinements have been accepted.

2022-11-20 16:34 UTC, fauxpark requested changes

2022-11-20 16:34 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/rules.mk
> +
```suggestion
```

2022-11-20 16:34 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +                                          CTL_ESC, KC_TRNS, XXXXXXX,    RAISE  , KC_TRNS, KC_TRNS\
```suggestion
                                          CTL_ESC, KC_TRNS, XXXXXXX,    RAISE  , KC_TRNS, KC_TRNS
```

2022-11-20 16:34 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +                                          XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX, FUNC   , XXXXXXX\
```suggestion
                                          XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX, FUNC   , XXXXXXX
```

2022-11-20 16:34 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +                                          KC_TRNS,  KC_TRNS, LOWER,    KC_TRNS, KC_TRNS, KC_COLON \
```suggestion
                                          KC_TRNS,  KC_TRNS, LOWER,    KC_TRNS, KC_TRNS, KC_COLON
```

2022-11-20 16:34 UTC, fauxpark commented on keyboards/crkbd/keymaps/markstos/keymap.c
> +                                         OSM_LCTL, GUI_ENT, LOW_TAB,   RSE_BSP ,KC_SPC  ,OSM_SFT \
```suggestion
                                         OSM_LCTL, GUI_ENT, LOW_TAB,   RSE_BSP ,KC_SPC  ,OSM_SFT
```

2022-12-15 15:25 UTC, markstos commented
@fauxpark , thank you for the peer-review.

I have pushed fixup commits with the requested refinements and believe this branch is ready for a squash-and-merge.

Thanks.

2023-03-01 16:30 UTC, markstos commented
ping for review

2023-03-01 22:04 UTC, fauxpark approved these changes

2023-03-10 07:19 UTC, drashna approved these changes

2023-03-10 07:19 UTC, merged