[keymap] komidore64 planck rev6
qmk/qmk_firmware pull request #19036
Opened 2022-11-11 21:11 UTC by komidore64

## Description

Add komidore64 planck rev6 keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-19 21:09 UTC, drashna approved these changes

2022-11-20 04:07 UTC, fauxpark requested changes

2022-11-20 04:07 UTC, fauxpark commented on keyboards/planck/keymaps/komidore64/keymap.c
> +            RESET,          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_MPLY, KC_DEL,
```suggestion
            QK_BOOT,        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_MPLY, KC_DEL,
```

2022-11-21 12:23 UTC, komidore64 commented on keyboards/planck/keymaps/komidore64/keymap.c
> +            RESET,          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_MPLY, KC_DEL,
Whoops! Thank you for catching this.

2022-11-22 03:53 UTC, fauxpark approved these changes

2022-11-23 18:12 UTC, merged

2022-11-23 18:41 UTC, komidore64 commented
Thank you @drashna and @fauxpark! ❤️