[Keyboard] Add Slime88
qmk/qmk_firmware pull request #19054
Opened 2022-11-13 11:19 UTC by zykrah

Added support for Slime88 PCB. https://github.com/zykrah/slime88.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-13 20:28 UTC, zvecr requested changes
Also `keyboards/zykrah/slime88/rules.mk` should match `data/templates/keyboard/rules.mk`

2022-11-13 20:28 UTC, zvecr commented on keyboards/zykrah/slime88/info.json
> +        "audio": false
```suggestion
        "bootmagic": true,
        "mousekey": true,
        "extrakey": true,
        "console": false,
        "command": false,
        "nkro": true
```

2022-11-13 20:28 UTC, zvecr commented on keyboards/zykrah/slime88/keymaps/default/keymap.c
> +
```suggestion
```

2022-11-13 20:28 UTC, zvecr commented on keyboards/zykrah/slime88/readme.md
> +SLIME88
This should follow the template `data/templates/keyboard/readme.md`

2022-11-20 04:11 UTC, drashna requested changes

2022-11-20 04:11 UTC, drashna commented on keyboards/zykrah/slime88/readme.md
> +![Slime88](https://user-images.githubusercontent.com/23428162/170985512-ec79f498-7476-4ab6-8150-877c67a25f26.png)
Please rehost on imgur.

2022-11-20 04:11 UTC, drashna commented on keyboards/zykrah/slime88/info.json
> +        "LAYOUT_all": {
since this is the only layout, it should probably be renamed to just `LAYOUT`

2022-12-12 22:45 UTC, drashna approved these changes

2022-12-12 22:45 UTC, drashna requested changes

2022-12-12 22:45 UTC, drashna commented on keyboards/zykrah/slime88/readme.md
> +![Slime88](https://i.imgur.com/DYNJZFH.png)
```suggestion
![Slime88](https://i.imgur.com/DYNJZFHh.png)
```

2022-12-13 00:19 UTC, zykrah commented on keyboards/zykrah/slime88/readme.md
> +![Slime88](https://i.imgur.com/DYNJZFH.png)
Could I ask the reasoning behind this?

2022-12-13 04:41 UTC, fauxpark requested changes

2022-12-13 04:41 UTC, fauxpark commented on keyboards/zykrah/slime88/readme.md
> +*A Hotswap Multi-layout F13 TKL PCB (h88c compatible) powered by RP2040.*
```suggestion
A Hotswap Multi-layout F13 TKL PCB (h88c compatible) powered by RP2040.
```

2022-12-14 03:04 UTC, fauxpark approved these changes

2022-12-14 20:51 UTC, merged