Corrections to uart driver for Chibios platform
qmk/qmk_firmware pull request #19075
Opened 2022-11-14 19:02 UTC by infinityis

UART driver for ChibiOS was not working on ARM (testing using STM32F411), it looks like it just didn't follow along with changes in the serial driver as far as how to correctly assign pin modes with palSetLineMode. With these changes, it now works as expected.

I also took the opportunity to refactor some naming to make it more generic (SD instead of SD1) and updated documentation accordingly. A search of the repo showed that no one was actually using the original SD1 naming yet.

## Description

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-14 19:13 UTC, zvecr commented
The changes of `SD1` to `SD` should be avoided for now, and at least should be separate from any bug fixes. Renaming currently makes things less consistent, and isnt necessarily aligned to the long term direction.

2022-11-14 19:40 UTC, infinityis commented
> The changes of `SD1_` to `SD_` should be avoided for now, and at least should be separate from any bug fixes. Renaming currently makes things less consistent to other ChibiOS drivers, and isnt necessarily aligned to the long term direction.

Noted, renaming has been reverted. Thank you!

2022-11-15 04:44 UTC, fauxpark commented
Aligning this code with the split serial driver is not really the right move IMO, if anything the reverse should be done. Ideally, split_common should be using this driver instead of reimplementing it, if possible.

I also note that the I2C driver sets its pins to open drain too so I am not sure why this would be any different - I have not heard of any issues with I2C on F4xx.
https://github.com/qmk/qmk_firmware/blob/master/platforms/chibios/drivers/i2c_master.c#L145-L146

2022-11-15 05:24 UTC, infinityis commented
Agreed

> Aligning this code with the split serial driver is not really the right move IMO, if anything the reverse should be done. Ideally, split_common should be using this driver instead of reimplementing it, if possible.
> 
> I also note that the I2C driver sets its pins to open drain too so I am not sure why this would be any different - I have not heard of any issues with I2C on F4xx. https://github.com/qmk/qmk_firmware/blob/master/platforms/chibios/drivers/i2c_master.c#L145-L146

Agreed that split_common could/should use ideally be using the uart driver since is split_common is just a specific use of uart. The uart driver would need to also be modified to include support for half-duplex comms, but conceptually, it all can work.

However, I would disagree that I2C comms are the right comparison to make as far as pin mode settings. Open drain absolutely works for I2C because I2C is indeed an open drain protocol, and so we need to add external pull up resistors to make it work. Half duplex serial comms is also open drain + external pull up resistor, so open drain can work for that too. But full duplex serial comms is pushpull using two dedicated pins with no external pull up resistor. And using push pull matches what is done in the existing serial_usart driver here:
https://github.com/qmk/qmk_firmware/blob/master/platforms/chibios/drivers/serial_usart.c#L200-L201
So if we don't use pushpull mode for uart, then someday when the split_common code starts using the uart driver, all split keyboards that use full duplex comms would stop working unless/until two pull up resistors are added.

2022-11-15 05:28 UTC, fauxpark requested changes
Let's keep the GPIOv1 stuff configurable just in case.

2022-11-15 05:29 UTC, fauxpark commented
Good point on I2C being open drain, I should have checked the SPI driver too.

2022-11-15 05:56 UTC, infinityis commented on platforms/chibios/drivers/uart.h
> +#if !defined(USE_GPIOV1)
Sounds good, I've left it configurable now.

2022-11-15 06:26 UTC, fauxpark reviewed
Tested on Blackpill F411, looks good. Also checked Bluepill as that uses GPIOv1 - doesn't work either way. Not sure what's up there.

2023-01-23 09:25 UTC, tzarc approved these changes

2023-01-23 09:25 UTC, tzarc commented
Guessing F103 doesn't work before this PR either, can probably iterate with another PR later so that at least F4xx is working?

2023-01-23 11:18 UTC, drashna approved these changes

2023-01-23 17:13 UTC, xisang233 commented
Let me summarize what happend when I tried to make a split keyboard firmware on STM32F103 blue pill board.
1. After I defined `SERIAL_USART_FULL_DUPLEX` `SERIAL_USART_TX_PIN A9` `SERIAL_USART_RX_PIN A10` `SERIAL_USART_DRIVER SD1` like https://docs.qmk.fm/#/serial_driver told me, the compile failed. The error message was `platforms/chibios/drivers/serial_usart.h:11: error: "SERIAL_USART_TX_PIN" redefined [-Werror]`.
I think `USART SD1` equals to A9 as TX pin and A10 as RX pin, so I tried to delect `SERIAL_USART_TX_PIN A9` `SERIAL_USART_RX_PIN A10` and it works.
2. The board cannot connect to each other until I changed `platforms/chibios/drivers/uart.c` and `platforms/chibios/drivers/uart.h`.
Thank you all.

2023-01-23 20:05 UTC, tzarc commented
Split serial driver is different to this uart driver.

2023-01-23 20:05 UTC, merged