add aeroboard
qmk/qmk_firmware pull request #19087
Opened 2022-11-15 16:05 UTC by EasonQian1

## Description
add aeroboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-15 18:34 UTC, drashna approved these changes

2022-11-15 19:15 UTC, zvecr requested changes

2022-11-15 19:15 UTC, zvecr commented on keyboards/eason/aeroboard/rules.mk
> +
```suggestion

```

2022-11-15 19:15 UTC, zvecr commented on keyboards/eason/aeroboard/rules.mk
> +COMMAND_ENABLE = yes        # Commands for debug and configuration
```suggestion
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
```

2023-02-02 05:57 UTC, waffle87 requested changes

2023-02-02 05:57 UTC, waffle87 commented on keyboards/eason/aeroboard/config.h
> +
```suggestion
```

2023-02-02 05:57 UTC, waffle87 commented on keyboards/eason/aeroboard/config.h
> + */
```suggestion
```

2023-02-02 05:57 UTC, waffle87 commented on keyboards/eason/aeroboard/aeroboard.h
> +#define LAYOUT_all( \
(and everywhere else `LAYOUT_all` was used eg. `info.json` & keymaps)
```suggestion
#define LAYOUT( \
```

2023-02-02 05:57 UTC, waffle87 commented on keyboards/eason/aeroboard/rules.mk
> +
```suggestion
```

2023-02-02 05:57 UTC, waffle87 commented on keyboards/eason/aeroboard/info.json
> +    },
```suggestion
    },
    "processor": "STM32F103",
    "bootloader": "stm32duino",
```

2023-02-02 05:57 UTC, waffle87 commented on keyboards/eason/aeroboard/readme.md
> +** A customizable hotswap 70% keyboard.
```suggestion
A customizable hotswap 70% keyboard.
```

2023-02-02 06:14 UTC, EasonQian1 commented
@waffle87 Hello，Dude.I have changed it correctly.

2023-02-02 06:43 UTC, waffle87 approved these changes

2023-02-03 01:25 UTC, fauxpark approved these changes

2023-02-07 06:57 UTC, EasonQian1 commented
May I ask whether the PR can be merged
@drashna @fauxpark @waffle87 @zvecr

2023-02-07 07:54 UTC, merged