add odinmini keyboard
qmk/qmk_firmware pull request #19111
Opened 2022-11-19 04:39 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-20 07:20 UTC, drashna requested changes

2022-11-20 07:20 UTC, drashna commented on keyboards/kbdfans/odinmini/info.json
> +        "all": true
Could you explicitly define which animations are enabled? 
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2022-11-20 12:21 UTC, fauxpark requested changes

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/via/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS, 
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/via/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS, 
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/via/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS, 
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/via/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS, 
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/default/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/default/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/default/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
```

2022-11-20 12:21 UTC, fauxpark commented on keyboards/kbdfans/odinmini/keymaps/default/keymap.c
> +		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
```suggestion
		KC_ESC,  KC_1,    KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_HOME,  KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
```

2022-11-30 19:29 UTC, drashna approved these changes
LGTM.

Though, for the layout macro, generally, `LAYOUT` if there is only one, and `LAYOUT_all` if there are multiple layouts.

2022-12-01 06:11 UTC, fauxpark requested changes

2022-12-01 06:11 UTC, fauxpark commented on keyboards/kbdfans/odinmini/info.json
> +        "device_ver": "0x0001",
```suggestion
```

2022-12-01 06:11 UTC, fauxpark commented on keyboards/kbdfans/odinmini/info.json
> +        "on_state": 1
```suggestion
        "num_lock": "GP4"
```

2022-12-01 23:34 UTC, fauxpark approved these changes

2022-12-04 09:22 UTC, merged