[Keyboard] Add NCR-80
qmk/qmk_firmware pull request #19130
Opened 2022-11-21 14:50 UTC by j4ckofalltrades

## Description

Add NCR-80.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-04 02:33 UTC, drashna approved these changes

2022-12-04 02:44 UTC, fauxpark requested changes

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/hotswap.h
> +#define LAYOUT_tkl_ansi_wkl( \
Missing print screen, scroll lock and pause/break, so this is not a TKL ANSI WKL layout.
```suggestion
#define LAYOUT( \
```

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/keymaps/default/keymap.c
> +  [0] = LAYOUT_tkl_ansi_wkl(
```suggestion
  [0] = LAYOUT(
```

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/keymaps/via/keymap.c
> +  [0] = LAYOUT_tkl_ansi_wkl(
```suggestion
  [0] = LAYOUT(
```

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/keymaps/via/keymap.c
> +  [1] = LAYOUT_tkl_ansi_wkl(
```suggestion
  [1] = LAYOUT(
```

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/keymaps/via/keymap.c
> +  [2] = LAYOUT_tkl_ansi_wkl(
```suggestion
  [2] = LAYOUT(
```

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/keymaps/via/keymap.c
> +  [3] = LAYOUT_tkl_ansi_wkl(
```suggestion
  [3] = LAYOUT(
```

2022-12-04 02:44 UTC, fauxpark commented on keyboards/mt/ncr80/hotswap/info.json
> +          "LAYOUT_tkl_ansi_wkl": {
```suggestion
          "LAYOUT": {
```

2022-12-05 00:30 UTC, fauxpark approved these changes

2022-12-07 21:02 UTC, merged

2023-03-12 01:05 UTC, j4ckofalltrades commented
@lesshonor 

I'm not certain but I think it should, my understanding is that the only difference from R1 vs R2 is that R2 has a different shade of grey and beige for the plastic housing.