KBDFans Tiger80 Keymap
qmk/qmk_firmware pull request #19148
Opened 2022-11-25 06:19 UTC by micros24

## Description

RGB underglow is disabled as I don't use it.
Keymap by Micros24 for optimized gaming performance and media controls.
SCROLL LOCK and PAUSE BREAK keys have been replaced with VOL- and VOL+ respectively.
F13 have been replaced with PLAY/PAUSE MEDIA.
RWIN is configured as F9 + ENTER macro.
RALT and RCTRL have tap and hold configured as follows:
RALT:
- TAP is configured as PREVIOUS MEDIA
- HOLD is configured as normal RALT

RCTRL:
- TAP is configured as NEXT MEDIA
- HOLD is configured as normal RCTRL

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-25 06:42 UTC, waffle87 requested changes

2022-11-25 06:42 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/config.h
> +
```suggestion
```

2022-11-25 06:42 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/config.h
> +
```suggestion
```

2022-11-25 06:42 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/config.h
> +#define USB_POLLING_INTERVAL_MS 1
```suggestion
```

2022-11-25 06:42 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/keymap.c
> +#pragma once
```suggestion
```

2022-11-25 06:42 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/readme.md
> +
```suggestion
```

2022-11-25 06:42 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/rules.mk
> +LAYOUTS = tkl_f13_ansi_tsangan
```suggestion
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
DEBOUNCE_TYPE = sym_eager_pk
VIA_ENABLE = yes
LTO_ENABLE = yes
```

2022-11-30 20:46 UTC, drashna approved these changes

2022-12-01 00:03 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/rules.mk
> +LAYOUTS = tkl_f13_ansi_tsangan
> `LT0_ENABLE = yes`

This still needs to be resolved — `LTO_ENABLE`

2022-12-01 00:06 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/micros24/rules.mk
> +LT0_ENABLE = yes
```suggestion
LTO_ENABLE = yes
```
this still needs to be resolved.

2022-12-01 06:11 UTC, fauxpark approved these changes

2022-12-04 07:16 UTC, merged