Refactor some led_set_kb instances
qmk/qmk_firmware pull request #19179
Opened 2022-11-28 05:07 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-28 05:51 UTC, fauxpark requested changes

2022-11-28 05:51 UTC, fauxpark commented on keyboards/handwired/retro_refit/retro_refit.c
> +        }
```suggestion
        writePin(D0, !led_state.caps_lock);
```

2022-11-28 05:51 UTC, fauxpark commented on keyboards/handwired/retro_refit/retro_refit.c
> +        }
```suggestion
        writePin(D1, !led_state.num_lock);
```

2022-11-28 05:51 UTC, fauxpark commented on keyboards/handwired/retro_refit/retro_refit.c
> +        }
```suggestion
        writePin(C6, !led_state.scroll_lock);
```

2022-11-28 20:13 UTC, t-8ch commented on keyboards/dumbpad/v1x_right/v1x_right.c
> +    return res;
This pattern could be replaced by
```c
void led_update_ports(led_t led_state) {
    writePin(LED_02, !led_state.num_lock);
}
```

(same goes for most of the other changes)

2022-12-01 21:27 UTC, drashna approved these changes

2022-12-09 01:42 UTC, merged