Add the Gone Hacking Studio XLS
qmk/qmk_firmware pull request #19185
Opened 2022-11-28 14:29 UTC by ramonimbao

## Description

Adds the Gone Hacking Studio XLS. I had a previous PR I messed up so this is a redo: https://github.com/qmk/qmk_firmware/pull/18362 This does include all the latest changes requested though (missing license headers, encoder map support).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-03 20:10 UTC, drashna approved these changes

2022-12-04 00:29 UTC, fauxpark requested changes

2022-12-04 00:29 UTC, fauxpark commented on keyboards/ghs/xls/keymaps/via/keymap.c
> +const uint16_t PROGMEM encoder_map[][4][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```

2022-12-12 22:11 UTC, drashna approved these changes

2022-12-12 22:46 UTC, fauxpark approved these changes

2022-12-13 02:36 UTC, merged