moved E80-1800 to data driven configuration
qmk/qmk_firmware pull request #19199
Opened 2022-11-30 00:21 UTC by ebastler

I moved all config options for this board that were possible over to info.json in the new data driven configuration. No other changes, changes are tested and working on local hardware.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-11-30 00:57 UTC, waffle87 requested changes

2022-11-30 00:57 UTC, waffle87 commented on keyboards/ebastler/e80_1800/config.h
> -/* Copyright 2022 Moritz Plattner
A license header is still needed here.

2022-11-30 01:08 UTC, ebastler commented on keyboards/ebastler/e80_1800/config.h
> -/* Copyright 2022 Moritz Plattner
Fixed, thanks

2022-12-04 02:48 UTC, drashna requested changes

2022-12-04 02:48 UTC, drashna commented on keyboards/ebastler/e80_1800/config.h
```suggestion

#include "config_common.h"
```

2022-12-12 22:09 UTC, drashna approved these changes

2022-12-12 22:32 UTC, fauxpark approved these changes

2022-12-13 02:35 UTC, merged