[Keymap] lets_split: add mypetyak map
qmk/qmk_firmware pull request #19205
Opened 2022-11-30 05:53 UTC by mypetyak

## Description

This PR adds a new `mypetyak` keymap for the Let's Split keyboard. It's the map I've been using since ~2017 on my daily driver, and I've finally taken the time to merge upstream.

Thanks for making this possible!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-04 04:56 UTC, drashna commented on keyboards/lets_split/keymaps/mypetyak/config.h
> +#pragma once
You could remove this entire file, as master left is the default behavior.

2022-12-04 05:22 UTC, drashna requested changes

2022-12-04 05:22 UTC, drashna commented on keyboards/lets_split/keymaps/mypetyak/keymap.c
> +}
This could be removed completely, as it's not needed, really.

2022-12-04 05:22 UTC, drashna commented on keyboards/lets_split/keymaps/mypetyak/keymap.c
> +  _______,   _______, _______, _______, _______, _______, _______, _______, COLEMAK, _______, _______, _______,
```suggestion
  _______,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2022-12-09 05:22 UTC, mypetyak commented
Thanks for the simplification suggestions!

2022-12-09 05:25 UTC, fauxpark requested changes

2022-12-09 05:25 UTC, fauxpark commented on keyboards/lets_split/keymaps/mypetyak/keymap.c
> +[_COLEMAK] = LAYOUT_ortho_4x12( \
```suggestion
[_COLEMAK] = LAYOUT_ortho_4x12(
```

2022-12-09 05:25 UTC, fauxpark commented on keyboards/lets_split/keymaps/mypetyak/keymap.c
> +[_LOWER] = LAYOUT_ortho_4x12( \
```suggestion
[_LOWER] = LAYOUT_ortho_4x12(
```

2022-12-09 05:25 UTC, fauxpark commented on keyboards/lets_split/keymaps/mypetyak/keymap.c
> +[_RAISE] = LAYOUT_ortho_4x12( \
```suggestion
[_RAISE] = LAYOUT_ortho_4x12(
```

2022-12-12 02:02 UTC, fauxpark approved these changes

2022-12-12 05:17 UTC, drashna approved these changes

2022-12-12 05:17 UTC, merged