add keyboard mw80
qmk/qmk_firmware pull request #19223
Opened 2022-12-02 11:13 UTC by TW59420

## Description
MWStudio is a custom keyboard enthusiast
Upload qmk firmware of mw80 PCB

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-02 11:17 UTC, tzarc commented
Dupe of [#17558](https://github.com/qmk/qmk_firmware/pull/17558).

2022-12-02 20:01 UTC, tzarc commented
Reopening as the other was closed and I didn't see it.

2022-12-02 20:03 UTC, tzarc commented
In the future, please refrain from opening multiple PRs -- the original could have been reused and ensured context was maintained between reviews.

2022-12-03 03:21 UTC, TW59420 commented
Sorry, there were some issues with the previous pr, so pulled the new branch

2022-12-03 08:43 UTC, waffle87 requested changes

2022-12-03 08:43 UTC, waffle87 commented on keyboards/mwstudio/mw80/mw80.h
> +/* Copyright 2022 TW59420 <https://github.com/TW59420>
This file should be removed.

2022-12-03 08:43 UTC, waffle87 commented on keyboards/mwstudio/mw80/info.json
> +				{ "matrix": [0, 0], "x": 0, "y": 0 },
```suggestion
                { "matrix": [0, 0], "x": 0, "y": 0 },
```

2022-12-03 08:43 UTC, waffle87 commented on keyboards/mwstudio/mw80/info.json
> +            "all": true
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2022-12-03 08:43 UTC, waffle87 commented on keyboards/mwstudio/mw80/readme.md
> +* **Keycode in layout**: Press the key mapped to RESET if it is available
```suggestion
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2022-12-03 08:43 UTC, waffle87 commented on keyboards/mwstudio/mw80/mw80.c
> +
```suggestion
```

2022-12-12 22:07 UTC, drashna approved these changes

2022-12-12 22:45 UTC, fauxpark approved these changes

2022-12-12 23:50 UTC, merged