Add new config for bumwings keyboard, based on RP2040 MCU. (second attempt)
qmk/qmk_firmware pull request #19234
Opened 2022-12-04 08:26 UTC by tubbytwins

I'd like to add a new config and layouts for my "bumwings" keyboard design.

## Description

New keyboard config and layout

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

(none)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-11 17:08 UTC, drashna requested changes

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/colemak-dh/keymap.c
> +    [1] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [1] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/colemak-dh/keymap.c
> +    [2] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [2] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/default/keymap.c
> +#include "bumwings_common.h"
```suggestion
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/default/keymap.c
> +    [0] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [0] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/default/keymap.c
> +    [1] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [1] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/default/keymap.c
> +    [2] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [2] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/dvorak/keymap.c
> +#include "bumwings_common.h"
```suggestion
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/dvorak/keymap.c
> +    [0] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [0] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/dvorak/keymap.c
> +    [1] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [1] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/keymaps/dvorak/keymap.c
> +    [2] = LAYOUT_14x4_bum_thumbs(
```suggestion
    [2] = LAYOUT(
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/readme.md
> +![BumWings](https://i.imgur.com/WwpVsNN.jpg)
```suggestion
![BumWings](https://i.imgur.com/WwpVsNNh.jpg)
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/rules.mk
> +SRC += bumwings_common.c
When properly named, this isn't needed. 
```suggestion
```

2023-02-11 17:08 UTC, drashna commented on keyboards/bumwings/v001/info.json
> +{
this can be merged with the top level,

2023-02-12 00:29 UTC, fauxpark requested changes

2023-02-12 00:29 UTC, fauxpark commented on keyboards/bumwings/config.h
> +// Copyright 2022 Matthew A. Schnoor (@tubbytwins)
This file can be deleted.

2023-06-05 02:07 UTC, closed without merging