Add Jisoo pcb
qmk/qmk_firmware pull request #19238
Opened 2022-12-05 03:15 UTC by DeskDaily

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-05 08:29 UTC, waffle87 requested changes

2022-12-05 08:29 UTC, waffle87 commented on keyboards/nightly_boards/jisoo/info.json
> +        "LAYOUT_all": {
```suggestion
        "LAYOUT": {
```

2022-12-05 08:29 UTC, waffle87 commented on keyboards/nightly_boards/jisoo/jisoo.h
> +#define LAYOUT_all( \
```suggestion
#define LAYOUT( \
```

2022-12-05 08:29 UTC, waffle87 commented on keyboards/nightly_boards/jisoo/keymaps/default/keymap.c
> +    [0] = LAYOUT_all(
```suggestion
    [0] = LAYOUT(
```

2022-12-05 08:29 UTC, waffle87 commented on keyboards/nightly_boards/jisoo/keymaps/via/keymap.c
> +    [0] = LAYOUT_all(
```suggestion
    [0] = LAYOUT(
```

2022-12-05 08:29 UTC, waffle87 commented on keyboards/nightly_boards/jisoo/readme.md
> +* Hardware Supported: Atmega32u4
```suggestion
* Hardware Supported: RP2040
```

2022-12-12 21:50 UTC, drashna approved these changes

2022-12-12 23:48 UTC, merged