add ubest/vn 68 keyboard
qmk/qmk_firmware pull request #19263
Opened 2022-12-08 15:36 UTC by mfkiiyd

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-08 18:17 UTC, waffle87 requested changes

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/config.h
> +// /*== or choose animations ==*/
```suggestion
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/vn.h
> +}
```suggestion
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/rules.mk
> +LAYOUTS = tkl_ansi
```suggestion
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/readme.md
> +
```suggestion

Flashing example for this keyboard:

    make ubest/vn:default:flash
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
Please add instructions on entering bootloader mode.
eg.

```suggestion
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/info.json
> +        }
```suggestion
        }
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/info.json
> +        "LAYOUT_all": {
`LAYOUT_all` is generally used with keyboards support multiple layouts.
```suggestion
    "layouts": {
        "LAYOUT": {
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/keymaps/default/keymap.c
> +        _______,     _______, _______, _______, RESET,   _______, _______, _______, _______, _______, _______, _______, _______, _______,      _______,
```suggestion
	[0] = LAYOUT(
        KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
        KC_TAB,      KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,      KC_PGUP,
        KC_CAPS,       KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,              KC_PGDN,
        KC_LSFT,   KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,        KC_UP,   MO(1),
        KC_LCTL,   KC_LGUI,   KC_LALT,   KC_SPC,                                         KC_RALT, KC_RGUI, KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
    ),
	[1] = LAYOUT(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_DEL,  KC_DEL,  _______,
        _______,     _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,      _______,
        _______,       _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______,
        _______,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,        _______, _______,
        _______,   _______,   _______,   _______,                                        _______, _______, _______, _______, _______, _______, _______
    ),
	[2] = LAYOUT(
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______,     _______, _______, _______, QK_BOOT,   _______, _______, _______, _______, _______, _______, _______, _______, _______,      _______,
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/keymaps/via/keymap.c
> +	[3] = LAYOUT_all(
```suggestion
	[0] = LAYOUT(
        KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
        KC_TAB,      KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,      KC_PGUP,
        KC_CAPS,       KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,              KC_PGDN,
        KC_LSFT,   KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,        KC_UP,   MO(1),
        KC_LCTL,   KC_LGUI,   KC_LALT,   KC_SPC,                                         KC_RALT, KC_RGUI, KC_APP,  KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
    ),
	[1] = LAYOUT(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_DEL,  KC_DEL,  _______,
        _______,     _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,      _______,
        _______,       _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______,
        _______,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,        _______, _______,
        _______,   _______,   _______,   _______,                                        _______, _______, _______, _______, _______, _______, _______
    ),
	[2] = LAYOUT(
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______,     _______, _______, _______, QK_BOOT,   _______, _______, _______, _______, _______, _______, _______, _______, _______,      _______,
        _______,       _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______,
        _______,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,        _______, _______,
        _______,   _______,   _______,   _______,                                        _______, _______, _______, _______, _______, _______, _______
    ),
	[3] = LAYOUT(
```

2022-12-08 18:17 UTC, waffle87 commented on keyboards/ubest/vn/vn.h
> +#define LAYOUT_all( \
```suggestion
#define LAYOUT( \
```

2022-12-09 16:48 UTC, mfkiiyd commented
Please merge, thank you

2022-12-12 21:46 UTC, drashna approved these changes

2022-12-12 22:41 UTC, fauxpark requested changes

2022-12-12 22:41 UTC, fauxpark commented on keyboards/ubest/vn/readme.md
> +    make ubest/vn:default:flash
```suggestion
    make ubest/vn:default:flash

```

2022-12-14 15:50 UTC, tzarc approved these changes

2022-12-14 15:50 UTC, merged