add d45 lite keyboard
qmk/qmk_firmware pull request #19288
Opened 2022-12-10 10:09 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-10 10:52 UTC, zvecr requested changes

2022-12-10 10:52 UTC, zvecr commented on keyboards/kbdfans/d45/lite/keymaps/default/keymap.c
> +		    KC_F4,  KC_LCTL,   KC_LALT,            KC_SPC,       KC_SPC,         KC_RALT, KC_RCTL,                   KC_LEFT,  KC_DOWN, KC_RIGHT),
```suggestion
```

2022-12-12 21:18 UTC, drashna approved these changes

2022-12-12 21:19 UTC, drashna approved these changes

2022-12-12 22:39 UTC, fauxpark approved these changes

2022-12-12 23:46 UTC, merged