Add Keychron Q7
qmk/qmk_firmware pull request #19308
Opened 2022-12-13 15:13 UTC by lalalademaxiya1

We added new keyboard Q7 which contains two sub versions.
Thanks!

## Description

We added ANSI and ISO versions.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-13 18:57 UTC, waffle87 requested changes

2022-12-13 18:57 UTC, waffle87 commented on keyboards/keychron/q7/ansi/ansi.h
> +/* Copyright 2021 @ Keychron (https://www.keychron.com)
This file can be removed.

2022-12-14 05:09 UTC, lalalademaxiya1 commented on keyboards/keychron/q7/readme.md
> +![Keychron Q7](https://cdn.shopify.com/s/files/1/0059/0630/1017/t/5/assets/keychronq770percentcustommechanicalkeyboardqmkvia26-1656926361466.jpg?v=1656926455)
Sorry, I can't login to the Imgur for some reason, so i remove the image address and it is not very important here.

2022-12-17 06:59 UTC, keychron-dev commented
@waffle87 do you have time to have a look at it?

2022-12-17 19:54 UTC, drashna approved these changes

2022-12-19 09:47 UTC, tzarc approved these changes

2022-12-19 09:48 UTC, merged