Add Eclipse60 / tinyneko
qmk/qmk_firmware pull request #19379
Opened 2022-12-19 04:35 UTC by MaiTheSan

Added Eclipse60 / tinyneko support

## Description
Add Eclipse60 / tinyneko 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-19 05:22 UTC, waffle87 requested changes
`keyboards/sawnsprojects/eclipse/eclipse60/rules.mk` & `keyboards/sawnsprojects/eclipse/tinyneko/rules.mk` need to match [data/templates/keyboard/rules.mk](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/rules.mk)

2022-12-19 05:22 UTC, waffle87 commented on keyboards/sawnsprojects/eclipse/eclipse60/info.json
> +            "all": true
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2022-12-19 05:22 UTC, waffle87 commented on keyboards/sawnsprojects/eclipse/tinyneko/info.json
> +            "all": true
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2022-12-19 05:22 UTC, waffle87 commented on keyboards/sawnsprojects/eclipse/eclipse60/readme.md
> +![eclipse60](i.imgur.com/0nttqlt.png)
```suggestion
![eclipse60](i.imgur.com/0nttqlth.png)
```

2022-12-19 05:22 UTC, waffle87 commented on keyboards/sawnsprojects/eclipse/tinyneko/readme.md
> +![tinyneko](https://i.imgur.com/hs8RWzL.png)
```suggestion
![tinyneko](https://i.imgur.com/hs8RWzLh.png)
```

2022-12-19 05:22 UTC, waffle87 commented on keyboards/sawnsprojects/eclipse/eclipse60/info.json
> +        "LAYOUT_all": {
`LAYOUT_all` is generally used for boards that support multiple layouts. `LAYOUT` should be used here instead. Same goes for `keyboards/sawnsprojects/eclipse/tinyneko`.

2022-12-23 07:32 UTC, drashna approved these changes

2022-12-24 02:36 UTC, fauxpark requested changes

2022-12-24 02:36 UTC, fauxpark commented on keyboards/sawnsprojects/eclipse/eclipse60/readme.md
> +![eclipse60](i.imgur.com/0nttqlth.png)
```suggestion
![eclipse60](https://i.imgur.com/0nttqlth.png)
```

2023-02-14 02:32 UTC, fauxpark approved these changes

2023-02-14 07:17 UTC, merged

2023-02-14 07:25 UTC, MaiTheSan commented
Thanks~