Add Z60 PCB Solder version
qmk/qmk_firmware pull request #19384
Opened 2022-12-20 13:59 UTC by tommyamoszhao

Variants:
Split backspace, nor/stepped capslock, split left shift, split right shift, ISO enter Bottom row variants:
6.25U spacebar, 7U spacebar, HHKB and WKL

## Description

## Types of Changes
- [ Add ] Z60 Keyboard solder version
- [ ] Via enabled

## Checklist

- [ * ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ * ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ * ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ * ] I have added tests to cover my changes.
- [ * ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-20 17:08 UTC, waffle87 requested changes

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/keymaps/default/keymap.c
> +}
The indicator functionality belongs in `config.h`: [https://docs.qmk.fm/#/feature_led_indicators](https://docs.qmk.fm/#/feature_led_indicators).
```suggestion
```

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/keymaps/via/keymap.c
> +#include QMK_KEYBOARD_H
This file is missing a license header.

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/keymaps/via/keymap.c
> +		RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS,
```suggestion
		QK_BOOT,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
```

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/keymaps/via/keymap.c
> +}
```suggestion
```

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/rules.mk
> +
```suggestion
# Bootloader selection
BOOTLOADER = atmel-dfu
```

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/z60.c
> +#include "z60.h"
This file is missing a license header.

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/z60.h
> +
This file is missing a license header.
```suggestion
```

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/z60.h
> +#endif
```suggestion
```

2022-12-20 17:08 UTC, waffle87 commented on keyboards/quarkeys/z60/config.h
> +#define RGB_DISABLE_WHEN_USB_SUSPENDED true
```suggestion
#define RGBLIGHT_SLEEP 
```

2022-12-21 07:57 UTC, tommyamoszhao commented
Hi Jack,
This is TommyZ from Quarkeys studio. I couldn’t thank you enough for the much detailed and in time message, the QMK I’ve been using turned out to be an older version, didn’t realize until I send the pull request. Sorry for taking much of your time to correct this. One question though, when I upload quarkeys/z60 firmware file, it shows on GitHub with “quarkeys/z60”, actually, there are more keyboards other than z60, so is there any way that I could make the directory on qmk_firmware:master shows only “quarkeys” with many subdirectory of “Z60” and “Z40” so on? Or, it is an automatic process after other keyboards files are updated? Cheers.
Sincerely, TommyZ

> On Dec 21, 2022, at 01:08, jack ***@***.***> wrote:
> 
> 
> @waffle87 requested changes on this pull request.
> 
> In keyboards/quarkeys/z60/Z60-VIA.json <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053538608>:
> 
> > @@ -0,0 +1,178 @@
> +{
> This file needs to be removed. (You'll want to submit a PR to the-via/keyboards <https://github.com/the-via/keyboards>)
> 
> In keyboards/quarkeys/z60/config.h <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053539944>:
> 
> > +#ifndef CONFIG_H
> +#define CONFIG_H
> +
> This file is missing a license header.
> eg.
> 
> // Copyright 2021 Your Name ***@***.***)
> // SPDX-License-Identifier: GPL-2.0-or-later
> ⬇️ Suggested change
> -#ifndef CONFIG_H
> -#define CONFIG_H
> -
> +#pragma once
> In keyboards/quarkeys/z60/config.h <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053540696>:
> 
> > +
> +#define VENDOR_ID       0x8490
> +#define PRODUCT_ID      0x0006
> +#define DEVICE_VER      0x0002
> +#define MANUFACTURER    QUARKeys
> +#define PRODUCT         Z60 SD
> This all needs to be moved to info.json, which you're missing.
> 
> In keyboards/quarkeys/z60/config.h <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053541245>:
> 
> > +#define VENDOR_ID       0x8490
> +#define PRODUCT_ID      0x0006
> +#define DEVICE_VER      0x0002
> +#define MANUFACTURER    QUARKeys
> +#define PRODUCT         Z60 SD
> +
> +#define MATRIX_ROWS 5
> +#define MATRIX_COLS 15
> +#define DIODE_DIRECTION COL2ROW
> +
> +#define MATRIX_ROW_PINS { B0, B1, B2, B3, B4 }
> +#define MATRIX_COL_PINS { E6, F0, F7, F1, F6, F5, F4, C7, B7, D5, C6, B6, B5, D7, D4 }
> +
> +#define DEBOUNCE 5
> +
> +#define RGBLIGHT_ANIMATIONS
> ⬇️ Suggested change
> -#define RGBLIGHT_ANIMATIONS
> +#define RGBLIGHT_EFFECT_BREATHING
> +#define RGBLIGHT_EFFECT_RAINBOW_MOOD
> +#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
> +#define RGBLIGHT_EFFECT_SNAKE
> +#define RGBLIGHT_EFFECT_KNIGHT
> +#define RGBLIGHT_EFFECT_CHRISTMAS
> +#define RGBLIGHT_EFFECT_STATIC_GRADIENT
> +#define RGBLIGHT_EFFECT_RGB_TEST
> +#define RGBLIGHT_EFFECT_ALTERNATING
> In keyboards/quarkeys/z60/config.h <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053541736>:
> 
> > +
> +#endif
> ⬇️ Suggested change
> -
> -#endif
> In keyboards/quarkeys/z60/keymaps/default/keymap.c <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053541963>:
> 
> > @@ -0,0 +1,112 @@
> +#include QMK_KEYBOARD_H
> This file is missing a license header.
> 
> In keyboards/quarkeys/z60/keymaps/default/keymap.c <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053542920>:
> 
> > @@ -0,0 +1,112 @@
> +#include QMK_KEYBOARD_H
> +
> +const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
> +
> +	[0] = LAYOUT_all(
> +		KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL, 
> +		LT(3, KC_TAB),    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, 
> +		LT(4, KC_CAPS),   KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_HASH, KC_ENT, 
> +		KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, RSFT_T(KC_UP),    MO(1), 
> +		KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,  MO(2),   RALT_T(KC_LEFT),  RGUI_T(KC_DOWN),  RCTL_T(KC_RGHT)),
> +
> +	[1] = LAYOUT_all( 
> +		RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
> ⬇️ Suggested change
> -		RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
> +		QK_BOOT,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
> In keyboards/quarkeys/z60/keymaps/default/keymap.c <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053545895>:
> 
> > +
> +void matrix_scan_user(void) {
> +}
> +
> +bool process_record_user(uint16_t keycode, keyrecord_t *record) {
> +	return true;
> +}
> +
> +void led_set_user(uint8_t usb_led) {
> +
> +	if (usb_led & (1 << USB_LED_NUM_LOCK)) {
> +		
> +	} else {
> +		
> +	}
> +
> +	if (usb_led & (1 << USB_LED_CAPS_LOCK)) {
> +		DDRC |= (1 << 6); PORTC &= ~(1 << 6);
> +	} else {
> +		DDRC &= ~(1 << 6); PORTC &= ~(1 << 6);
> +	}
> +
> +	if (usb_led & (1 << USB_LED_SCROLL_LOCK)) {
> +		
> +	} else {
> +		
> +	}
> +
> +	if (usb_led & (1 << USB_LED_COMPOSE)) {
> +		
> +	} else {
> +		
> +	}
> +
> +	if (usb_led & (1 << USB_LED_KANA)) {
> +		
> +	} else {
> +		
> +	}
> +
> +}
> The indicator functionality belongs in config.h: https://docs.qmk.fm/#/feature_led_indicators.
> 
> ⬇️ Suggested change
> -
> -void matrix_scan_user(void) {
> -}
> -
> -bool process_record_user(uint16_t keycode, keyrecord_t *record) {
> -	return true;
> -}
> -
> -void led_set_user(uint8_t usb_led) {
> -
> -	if (usb_led & (1 << USB_LED_NUM_LOCK)) {
> -		
> -	} else {
> -		
> -	}
> -
> -	if (usb_led & (1 << USB_LED_CAPS_LOCK)) {
> -		DDRC |= (1 << 6); PORTC &= ~(1 << 6);
> -	} else {
> -		DDRC &= ~(1 << 6); PORTC &= ~(1 << 6);
> -	}
> -
> -	if (usb_led & (1 << USB_LED_SCROLL_LOCK)) {
> -		
> -	} else {
> -		
> -	}
> -
> -	if (usb_led & (1 << USB_LED_COMPOSE)) {
> -		
> -	} else {
> -		
> -	}
> -
> -	if (usb_led & (1 << USB_LED_KANA)) {
> -		
> -	} else {
> -		
> -	}
> -
> -}
> In keyboards/quarkeys/z60/keymaps/via/keymap.c <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053546807>:
> 
> > @@ -0,0 +1,112 @@
> +#include QMK_KEYBOARD_H
> This file is missing a license header.
> 
> In keyboards/quarkeys/z60/keymaps/via/keymap.c <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053547025>:
> 
> > @@ -0,0 +1,112 @@
> +#include QMK_KEYBOARD_H
> +
> +const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
> +
> +	[0] = LAYOUT_all(
> +		KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL, 
> +		LT(3, KC_TAB),    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, 
> +		LT(4, KC_CAPS),   KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_HASH, KC_ENT, 
> +		KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, RSFT_T(KC_UP),    MO(1), 
> +		KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,  MO(2),   RALT_T(KC_LEFT),  RGUI_T(KC_DOWN),  RCTL_T(KC_RGHT)),
> +
> +	[1] = LAYOUT_all( 
> +		RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
> ⬇️ Suggested change
> -		RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
> +		QK_BOOT,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS, 
> In keyboards/quarkeys/z60/keymaps/via/keymap.c <https://github.com/qmk/qmk_firmware/pull/19384#discussion_r1053547487>:
> 
> > +
> +void matrix_scan_user(void) {
> +} [...]

2022-12-21 09:31 UTC, waffle87 commented
@tommyamoszhao You can add multiple keyboards to the `quarkeys/` directory — it's a common practice throughout the repo. 
eg.
```
quarkeys
├── z40
├── z60
└── z_etc

3 directories
```
However, please add additional keyboards in separate pull requests.

2022-12-22 11:45 UTC, closed without merging