[Keyboard] Add XR63GL keyboard
qmk/qmk_firmware pull request #19380
Opened 2022-12-19 14:18 UTC by gachiham

## Description

Add keyboard XR63GL using GL516 case.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-23 07:08 UTC, drashna requested changes

2022-12-23 07:08 UTC, drashna commented on keyboards/gl516/xr63gl/keymaps/default/keymap.c
> +};
```suggestion
```

This should go in the keyboard's c file.  Which should look something like: 

```c
// Copyright 2022 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

const matrix_row_t matrix_mask[MATRIX_ROWS] = {
    0b1111111111111110,
    0b1111111111111101,
    0b1111111111111011,
    0b1111111111110111,
    0b1111111111101111,
    0b1111111111011111,
    0b1111111110111111,
    0b1111111101111111,
    0b1111111011111111,
};
```

2022-12-23 07:08 UTC, drashna commented on keyboards/gl516/xr63gl/keymaps/via/keymap.c
> +};
```suggestion
```

2022-12-23 07:08 UTC, drashna commented on keyboards/gl516/xr63gl/readme.md
> +![gl516/xr63gl](https://cdn-ak.f.st-hatena.com/images/fotolife/g/gachiham/20221211/20221211132634.jpg)
Please rehost on imgur.

2022-12-24 02:43 UTC, fauxpark approved these changes

2022-12-27 20:29 UTC, drashna approved these changes

2022-12-27 20:29 UTC, merged