Add The Uni Utility Belt Keymap
qmk/qmk_firmware pull request #19411
Opened 2022-12-23 21:22 UTC by petercpark

Adding a new keymap for the Uni by StenoKeyboards.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-23 21:26 UTC, petercpark commented
The build fails because the "keymap_steno.h" file does not have the correct data in the develop branch. It compiles correctly in the master branch.

2022-12-23 21:50 UTC, waffle87 requested changes

2022-12-23 21:50 UTC, waffle87 commented on .vscode/settings.json
> -	    "editor.formatOnSave": false
Changes to this file should be reverted.

2022-12-27 20:34 UTC, drashna requested changes

2022-12-27 20:34 UTC, drashna commented on keyboards/stenokeyboards/the_uni/keymaps/utility_belt/keymap.c
> + void matrix_init_user() {
```suggestion
void keyboard_post_init_user(void) {
```

2022-12-27 20:34 UTC, drashna commented on keyboards/stenokeyboards/the_uni/keymaps/utility_belt/README.md
> +# Utility Bar Uni Layout
Please rename the file to be all lower case.

2023-01-10 09:01 UTC, drashna approved these changes

2023-01-12 09:56 UTC, merged