Atreyu rev2
qmk/qmk_firmware pull request #19443
Opened 2022-12-29 11:18 UTC by climent

## Description

New release of the Atreyu keyboard (rev2).

Changes:
- OLED display now possible (I2C pins freed).
- changed pin connections so that different MCUs can be used: ProMicro (no encoders), Elite-C/Elite-Pi/Puchi (with encoders) and Nice!Nano (encoders + BT).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-12-29 23:45 UTC, waffle87 requested changes
* `keyboards/atreyu/rev2/rules.mk` should match [data/templates/keyboard/rules.mk](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/rules.mk)

2022-12-29 23:45 UTC, waffle87 commented on keyboards/atreyu/rev2/rev2.c
> + */
This file should be removed.

2022-12-31 17:55 UTC, climent commented
Updated the files following the comments. Also, the code if fully tested with the new rev2 PCBs I received.

2022-12-31 20:37 UTC, drashna approved these changes

2023-01-01 00:38 UTC, tzarc approved these changes

2023-01-01 00:38 UTC, merged