Add SapuSeven MacroPad12
qmk/qmk_firmware pull request #19466
Opened 2023-01-01 07:52 UTC by SapuSeven

## Description

Add new keyboard - MacroPad12.
It will be released soon as I still need to finish some documentation.
This is my first contribution to QMK - please feel free to point out any mistakes.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*(none)*

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-01 15:10 UTC, zvecr requested changes

2023-01-01 15:10 UTC, zvecr commented on keyboards/sapuseven/macropad12/keymaps/default/keymap.c
> +    )
```suggestion
    )
```

2023-01-01 15:53 UTC, drashna requested changes

2023-01-01 15:53 UTC, drashna commented on keyboards/sapuseven/macropad12/readme.md
> +![macropad12](https://i.imgur.com/StqDhH8.png)
```suggestion
![macropad12](https://i.imgur.com/StqDhH8h.png)
```

This uses a smaller, but still high res version of the image that is more suitable for github markdown rendering.

2023-01-02 01:20 UTC, drashna approved these changes

2023-01-02 01:33 UTC, zvecr approved these changes

2023-01-04 03:46 UTC, fauxpark approved these changes

2023-01-04 06:18 UTC, merged