adding plop keyboard
qmk/qmk_firmware pull request #19486
Opened 2023-01-03 03:08 UTC by lukeski14

## Description

Adding plop keyboard
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-03 03:27 UTC, waffle87 requested changes

2023-01-03 03:27 UTC, waffle87 commented on keyboards/rainkeebs/plop/plop.c
> +// Copyright 2023 Regan Palmer (@rainkeebs)
This file should be removed. (Assuming the matrix data in `info.json` is correct)

2023-01-03 03:27 UTC, waffle87 commented on keyboards/rainkeebs/plop/plop.h
> +// Copyright 2023 Regan Palmer (@rainkeebs)
This file should be removed. (Assuming the matrix data in `info.json` is correct)

2023-01-03 03:27 UTC, waffle87 commented on keyboards/rainkeebs/plop/readme.md
> +![plop](https://imgur.com/5zZRGun)
```suggestion
![plop](https://i.imgur.com/5zZRGunh.png)
```

2023-01-03 03:27 UTC, waffle87 commented on keyboards/rainkeebs/plop/config.h
> +
```suggestion
```

2023-01-03 03:27 UTC, waffle87 commented on keyboards/rainkeebs/plop/info.json
> +        "LAYOUT_ortho_4x12": {
```suggestion
        "LAYOUT": {
```
\+ whatever other fixes this entails.

2023-01-03 03:27 UTC, waffle87 commented on keyboards/rainkeebs/plop/rules.mk
> +
```suggestion
```

2023-01-07 18:20 UTC, lukeski14 commented
Let me know if additional changes are needed @waffle87 ! Appreciate it

2023-01-12 09:58 UTC, drashna requested changes

2023-01-12 09:58 UTC, drashna commented on keyboards/rainkeebs/plop/rules.mk
> +NKRO_ENABLE = yes		# USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
Please remove the `SLEEP_LED_ENABLE` setting, as it's not really used, and remove the comments for both it and NKRO.  
```suggestion
NKRO_ENABLE = yes           # Enable N-Key Rollover
```

2023-01-12 09:58 UTC, drashna commented on keyboards/rainkeebs/plop/rules.mk
> +BOOTMAGIC_ENABLE = yes	# Virtual DIP switch configuration
```suggestion
BOOTMAGIC_ENABLE = yes	# Enable bootmagic Lite
```

2023-01-12 09:58 UTC, drashna commented on keyboards/rainkeebs/plop/rules.mk
> +RGBLIGHT_ENABLE = yes
```suggestion
RGBLIGHT_ENABLE = yes

```

2023-01-13 19:05 UTC, drashna approved these changes

2023-03-01 02:49 UTC, lukeski14 commented
I believe this one is good to go still. Let me know, thanks @drashna @waffle87

2023-03-01 17:51 UTC, waffle87 requested changes

2023-03-01 17:51 UTC, waffle87 commented on keyboards/rainkeebs/plop/config.h
> +#define MATRIX_COLS 12
```suggestion
```

2023-03-01 17:51 UTC, waffle87 commented on keyboards/rainkeebs/plop/config.h
> +
```suggestion
```

2023-03-10 07:30 UTC, drashna commented on keyboards/rainkeebs/plop/config.h
> +#define MATRIX_COL_PINS { C7, C6, B6, B5, B4, D7, D6, D4, F6, F7, F5, F4 }
This should be moved to the info.json

2023-05-26 01:55 UTC, closed without merging