Acacia keyboard
qmk/qmk_firmware pull request #19532
Opened 2023-01-07 21:49 UTC by jpsecher

## Description

New custom 42 key keyboard, with link to all source files to build it.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-07 22:55 UTC, zvecr requested changes

2023-01-07 22:55 UTC, zvecr commented on keyboards/handwired/acacia/info.json
> +    "keyboard_folder": "handwired/acacia",
```suggestion
```

2023-01-07 22:55 UTC, zvecr commented on keyboards/handwired/acacia/readme.md
> +    qmk clean
```suggestion
Make example for this keyboard (after setting up your build environment):

    make handwired/acacia:default

Flashing example for this keyboard:

    make handwired/acacia:default:flash
```

2023-01-07 22:55 UTC, zvecr commented on keyboards/handwired/acacia/rules.mk
> +LTO_ENABLE = yes            # Link-time optimisation for smaller code
```suggestion
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # N-Key Rollover
LTO_ENABLE = yes            # Link-time optimisation for smaller code
```

2023-01-07 22:55 UTC, zvecr commented on keyboards/handwired/acacia/keymaps/default/keymap.c
> +//#define OSM_CG OSM(MOD_LCTL|MOD_LGUI)
We wouldnt really want commented out code here

2023-01-07 22:55 UTC, zvecr commented on keyboards/handwired/acacia/keymaps/default/keymap.c
> +    NUMBER_OF_LAYERS
```suggestion
    _MACRO
```

2023-01-07 22:55 UTC, zvecr commented on keyboards/handwired/acacia/acacia.c
> + */
```suggestion
 */

#include "acacia.h"
```

2023-01-12 18:55 UTC, drashna approved these changes

2023-01-13 06:54 UTC, fauxpark approved these changes

2023-01-13 11:04 UTC, merged