new keyboard rb87
qmk/qmk_firmware pull request #19546
Opened 2023-01-09 02:00 UTC by ryanbaekr

## Description

Added new keyboard: ryanbaekr rb87

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-09 05:12 UTC, waffle87 requested changes

2023-01-09 05:12 UTC, waffle87 commented on keyboards/ryanbaekr/rb87/keymaps/default/readme.md
> +# The default keymap for rb87
This file should be removed.

2023-01-09 05:12 UTC, waffle87 commented on keyboards/ryanbaekr/rb87/readme.md
> +    make ryanbaekr/rb87:default
```suggestion
    make ryanbaekr/rb87:default
    
Flashing example for this keyboard:

    make ryanbaekr/rb87:default:flash
```

2023-01-09 05:13 UTC, waffle87 commented on keyboards/ryanbaekr/rb87/info.json
> +    "maintainer": "ryanbaekr",
```suggestion
    "maintainer": "ryanbaekr",
    "processor": "atmega32u4",
    "bootloader": "caterina",
```

2023-01-12 19:35 UTC, drashna approved these changes

2023-01-13 06:56 UTC, fauxpark requested changes

2023-01-13 06:56 UTC, fauxpark commented on keyboards/ryanbaekr/rb87/config.h
> +
```suggestion
```

2023-01-13 06:56 UTC, fauxpark commented on keyboards/ryanbaekr/rb87/rules.mk
> +
```suggestion
```

2023-01-15 03:32 UTC, fauxpark approved these changes

2023-01-16 00:55 UTC, merged