Add commit info to `version.h`
qmk/qmk_firmware pull request #19542
Opened 2023-01-08 12:25 UTC by elpekenin

## Description
Small changes to the CLI to add the current commit's hash into `version.h` aswell as a marker(`*`) to know if the repository contained any un-commited changes when firmware was compiled.
This way we can `print` stuff like: `firmware built with commit: e725d6b199*`.
I made this to show the hash on a corner of my Quantum Painter screen(s) but thought it could be useful to other people thus sharing it.

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist
- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-08 13:04 UTC, fauxpark commented on lib/python/qmk/cli/generate/version_h.py
> +        git_dirty = ""  # so that it evaluates as False
```suggestion
        git_dirty = False
```

2023-01-09 02:58 UTC, zvecr commented on lib/python/qmk/cli/generate/version_h.py
> +#define GIT_COMMIT "{git_commit}{'*' if git_dirty else ''}"
Maybe `QMK_GIT_HASH` or something so that its partially consistent with other variables, and allows for ChibiOS variants in the future?

2023-01-09 16:08 UTC, zvecr commented on lib/python/qmk/git.py
> +        return "Unknown"
```suggestion
        return None
```

2023-01-09 16:09 UTC, zvecr requested changes

2023-01-09 16:09 UTC, zvecr commented on lib/python/qmk/cli/generate/version_h.py
> +        git_qmk_hash = git_get_qmk_hash()
```suggestion
        git_qmk_hash = git_get_qmk_hash() or "Unknown"
```

2023-01-09 16:09 UTC, zvecr commented on lib/python/qmk/git.py
> +        return "Unknown"
```suggestion
        return None
```

2023-01-09 20:01 UTC, zvecr approved these changes

2023-01-10 06:38 UTC, drashna approved these changes

2023-02-02 18:23 UTC, merged