New Custom Massdrop CTRL keymap
qmk/qmk_firmware pull request #19559
Opened 2023-01-10 22:09 UTC by rallyrabbit

New keymap
Adding unicode characters to a second layer
ANSI keymap relatively untouched
Added 4 RGB modes not previously with Massdrop CTRL

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-11 01:10 UTC, waffle87 requested changes

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/README.md
> +# Massdrop Ctrl RallyRabbit
This file should be renamed to lowercase.

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/config.h
> +// https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
```suggestion
// Copyright 2023 @rallyrabbit 
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
```

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/keymap.c
> +#include QMK_KEYBOARD_H
This file is missing a license header.

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/rules.mk
> +
```suggestion

# Custom RGB matrix handling
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = custom
```

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/rules.mk
> +
```suggestion
UNICODE_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
```

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/rgb_matrix_user.inc
> +#include "flower_blooming/flower_blooming.c"
C files should not be `#include`'d. Either add the code in this file or use a more appropriate way of including it.

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/README.md
> +* Build with "qmk compile -kb massdrop/ctrl -km rallyrabbit"
```suggestion
* Build with `qmk compile -kb massdrop/ctrl -km rallyrabbit`
```

2023-01-11 01:10 UTC, waffle87 commented on keyboards/massdrop/ctrl/keymaps/rallyrabbit/flower_blooming/flower_blooming.h
> +#pragma once
This file is missing a license header.

2023-01-12 02:34 UTC, rallyrabbit commented
@tzarc if this is on hold to facilitate HorrorTroll's changes into a central location rather than copy pasting everywhere, I can certainly pull those out for now and re-work once that work is complete.

2023-01-12 20:45 UTC, rallyrabbit commented
> On hold; awaiting PR from @HorrorTroll to move RGB effects to core instead of copypasting everywhere.

Blooming Flower removed from PR

2023-08-29 17:24 UTC, zvecr commented
Unfortunately since this PRs creation, QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

In the near future we will be providing a more user focused workflow for keymaps, but till then the suggestion is to keep changes in your own fork.

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.

2023-08-29 17:24 UTC, closed without merging