new keyboard: edinburgh41
qmk/qmk_firmware pull request #19569
Opened 2023-01-11 21:54 UTC by schwarzer-geiger

I want to add the edinburgh41 keyboard to the QMK repository.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-11 22:30 UTC, zvecr requested changes

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/edinburgh41.h
> +#define LAYOUT_edinburgh41( \
This will produce lint errors on up-to-date QMK
```suggestion
#define LAYOUT( \
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/info.json
> +        "LAYOUT_edinburgh41": {
```suggestion
        "LAYOUT": {
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +layer_state_t layer_state_set_kb(layer_state_t state) {
Cant have `_kb` funcs at keymap level
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +report_mouse_t pointing_device_task_kb(report_mouse_t mouse_report) {
```suggestion
report_mouse_t pointing_device_task_user(report_mouse_t mouse_report) {
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/keymap.c
> +layer_state_t layer_state_set_kb(layer_state_t state) {
```suggestion
layer_state_t layer_state_set_user(layer_state_t state) {
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/keymap.c
> +report_mouse_t pointing_device_task_kb(report_mouse_t mouse_report) {
```suggestion
report_mouse_t pointing_device_task_user(report_mouse_t mouse_report) {
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/keymap.c
> +  [_BASE] = LAYOUT_edinburgh41(
```suggestion
  [_BASE] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/keymap.c
> +  [_LOWER] = LAYOUT_edinburgh41(
```suggestion
  [_LOWER] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/keymap.c
> +  [_RAISE] = LAYOUT_edinburgh41(
```suggestion
  [_RAISE] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/keymap.c
> +  [_ADJUST] = LAYOUT_edinburgh41(
```suggestion
  [_ADJUST] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +  [_BASE] = LAYOUT_edinburgh41(
```suggestion
  [_BASE] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +  [_LOWER] = LAYOUT_edinburgh41(
```suggestion
  [_LOWER] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +  [_RAISE] = LAYOUT_edinburgh41(
```suggestion
  [_RAISE] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +  [_ADJUST] = LAYOUT_edinburgh41(
```suggestion
  [_ADJUST] = LAYOUT(
```

2023-01-11 22:30 UTC, zvecr commented on keyboards/edinburgh41/keymaps/lalit/rules.mk
> +POINTING_DEVICE_DRIVER = analog_joystick
Only overrides
```suggestion
TAP_DANCE_ENABLE = yes
```

2023-01-12 00:03 UTC, waffle87 requested changes

2023-01-12 00:03 UTC, waffle87 commented on keyboards/edinburgh41/readme.md
> +* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```suggestion
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-01-12 00:03 UTC, waffle87 commented on keyboards/edinburgh41/rules.mk
> +
```suggestion
```

2023-01-12 19:46 UTC, drashna approved these changes

2023-01-12 19:51 UTC, drashna requested changes

2023-01-12 19:51 UTC, drashna commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +}
```suggestion
```

2023-01-12 19:51 UTC, drashna commented on keyboards/edinburgh41/keymaps/default/keymap.c
> +    switch (get_highest_layer(state)) {
```suggestion
    state = update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
    switch (get_highest_layer(state)) {
```

2023-01-13 06:57 UTC, fauxpark requested changes

2023-01-13 06:57 UTC, fauxpark commented on keyboards/edinburgh41/config.h
> +
```suggestion
```

2023-01-18 14:54 UTC, schwarzer-geiger commented
What further steps should I take until I can merge the pull request?

2023-01-18 17:11 UTC, waffle87 approved these changes

2023-01-26 16:34 UTC, keyboard-magpie approved these changes

2023-01-26 16:34 UTC, merged