Keyboard/bear65 v2
qmk/qmk_firmware pull request #19578
Opened 2023-01-12 21:18 UTC by beelzebubi

Added support for the Bear65 V2 board by Jacky Studio + custom user script and keymap

## Description

The V2 of the Bear65 comes with a WK version, while the V1 was a WKL only board. 

This PR implements a rev2 subfolder, adding support for all version of the V2 board while leaving the original files in a rev1 folder.

Additionally, this PR adds a custom keymap for the V2 including user scripts.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-12 23:15 UTC, zvecr requested changes
userspace additions should not happen in keyboard PRs. The changes should be removed and submitted separately. We are a little less strict on user keymaps, however if the `nazu` keymap depends on userspace, then that should also be removed.

2023-01-13 01:25 UTC, waffle87 requested changes

2023-01-13 01:25 UTC, waffle87 commented on keyboards/jacky_studio/bear_65/rev1/rules.mk
> +
```suggestion
```

2023-01-13 01:25 UTC, waffle87 commented on keyboards/jacky_studio/bear_65/rev2/rules.mk
> +
```suggestion
```

2023-01-13 01:25 UTC, waffle87 commented on keyboards/jacky_studio/bear_65/rev2/info.json
> +    "maintainer": "qmk",
```suggestion
    "maintainer": "qmk",
    "processor": "atmega32u4",
    "bootloader": "atmel-dfu",
```

2023-01-13 01:25 UTC, waffle87 commented on keyboards/jacky_studio/bear_65/rev1/info.json
> +    "maintainer": "qmk",
```suggestion
    "maintainer": "qmk",
    "processor": "atmega32u4",
    "bootloader": "atmel-dfu",
```

2023-01-13 01:25 UTC, waffle87 commented on keyboards/jacky_studio/bear_65/rev1/rev1.c
> +#endif
This code is no different from what's in `bear65.c`? It shouldn't be added at the revision level unless necessary.

2023-01-13 01:25 UTC, waffle87 commented on keyboards/jacky_studio/bear_65/rev2/rev2.c
> +#endif
Above comment.

2023-01-29 22:27 UTC, beelzebubi commented
Do I still need to make any updates on the code?

2023-01-30 05:39 UTC, waffle87 approved these changes

2023-02-08 04:53 UTC, drashna approved these changes

2023-02-08 04:54 UTC, merged