Add ERA65 PCB to QMK
qmk/qmk_firmware pull request #19591
Opened 2023-01-14 08:00 UTC by eerraa

Add the ERA65 PCB to QMK

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-15 05:00 UTC, drashna approved these changes

2023-01-15 05:38 UTC, fauxpark requested changes

2023-01-15 05:38 UTC, fauxpark commented on keyboards/era/era65/readme.md
> +	make era/era65:default
```suggestion
    make era/era65:default

Flashing example for this keyboard:

    make era/era65:default:flash
```

2023-01-17 00:15 UTC, fauxpark approved these changes

2023-01-17 01:55 UTC, merged