[Keymap] Add saph1s keymap
qmk/qmk_firmware pull request #19608
Opened 2023-01-16 14:44 UTC by Saph1s

## Description

Add additional keymap for KPrepublic BM80v2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-16 16:11 UTC, waffle87 requested changes

2023-01-16 16:11 UTC, waffle87 commented on keyboards/kprepublic/bm80v2/keymaps/saph1s/keymap.c
> +
```suggestion
    )
```

2023-01-16 16:20 UTC, Saph1s commented on keyboards/kprepublic/bm80v2/keymaps/saph1s/keymap.c
> +
Done!

2023-01-17 05:20 UTC, drashna approved these changes

2023-01-17 13:10 UTC, fauxpark approved these changes

2023-01-17 17:44 UTC, waffle87 commented on keyboards/kprepublic/bm80v2/keymaps/saph1s/rgb_matrix_map.h
> +
```suggestion
#pragma once
```

2023-01-17 17:46 UTC, merged