Refactor Leader key feature
qmk/qmk_firmware pull request #19632
Opened 2023-01-19 02:33 UTC by fauxpark

## Description

This is quite a large and fairly invasive rework of the Leader key. Instead of hooking into `matrix_scan_user()`, leader sequences are now defined in the `leader_end_user()` callback. The `LEADER_EXTERNS()` and `LEADER_DICTIONARY()` macros are now extinct, and the core functionality has been moved out of `process_leader.[ch]` into a dedicated `leader.[ch]`. The documentation has also been significantly improved.

I can't guarantee the changes to the user code still work, but most of the heavy lifting has already been done here, and I suspect some of these keymaps probably didn't compile in the first place.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-19 06:13 UTC, fauxpark commented
`LEADER_NO_TIMEOUT` doesn't appear to work properly in develop:

`QK_LEAD` ... wait more than 300ms ... `a`, `s`
just prints `s` instead of doing the sequence.

I'll need to investigate some more to see if I can fix it.

2023-01-19 07:00 UTC, fauxpark commented
It appears to work if you have `LEADER_PER_KEY_TIMING` also defined. But it should really be fine on its own.

2023-01-27 21:24 UTC, drashna requested changes

2023-01-27 21:24 UTC, drashna commented on quantum/leader.c
> +#include "leader.h"
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "leader.h"
```

2023-01-27 21:24 UTC, drashna commented on quantum/leader.h
> +#include <stdbool.h>
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include <stdbool.h>
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/config.h
> +#pragma once
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/leader_no_initial_timeout/config.h
> +#pragma once
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/leader_no_initial_timeout/test_leader_no_initial_timeout.cpp
> +#include "keyboard_report_util.hpp"
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "keyboard_report_util.hpp"
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/leader_per_key_timeout/test_leader_per_key_timeout.cpp
> +#include "keyboard_report_util.hpp"
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "keyboard_report_util.hpp"
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/leader_sequences.c
> +#include "quantum.h"
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "quantum.h"
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/leader_strict_key_processing/config.h
> +#pragma once
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/leader_strict_key_processing/test_leader_strict_key_processing.cpp
> +#include "keyboard_report_util.hpp"
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "keyboard_report_util.hpp"
```

2023-01-27 21:24 UTC, drashna commented on tests/leader/test_leader.cpp
> +#include "keyboard_report_util.hpp"
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "keyboard_report_util.hpp"
```

2023-02-10 04:20 UTC, drashna approved these changes

2023-02-12 16:18 UTC, tzarc approved these changes

2023-02-12 16:19 UTC, merged