Custom/noobs2023
qmk/qmk_firmware pull request #19636
Opened 2023-01-19 14:43 UTC by yeahnoob

## Description
Base on keymaps "foureight84" and "helltm". Just keep the VIA enabled and the RGB Light enabled as additional.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-19 15:46 UTC, waffle87 requested changes
The `.` in the directory name should be removed.
eg. `dr_noobs`

2023-01-19 15:59 UTC, fauxpark requested changes
Keymap folder name should match your GitHub username.

2023-01-19 15:59 UTC, fauxpark commented on keyboards/sofle/keymaps/dr.noobs/keymap.c
> +#include "lib/lib8tion/lib8tion.h"
```suggestion
#include <lib/lib8tion/lib8tion.h>
```

2023-01-23 10:53 UTC, drashna commented on keyboards/sofle/keymaps/yeahnoob/keymap.c
> +    oled_write_ln_P(PSTR("CPSLK"), led_usb_state.caps_lock);
since you're only using it once, you could do this: 
```suggestion
    oled_write_ln_P(PSTR("CPSLK"), host_keyboard_led_state().caps_lock);
```

2023-01-23 10:55 UTC, drashna commented on keyboards/sofle/keymaps/yeahnoob/keymap.c
> +    return rotation;
```suggestion
    return OLED_ROTATION_270;
```

2023-04-12 01:54 UTC, closed without merging