Added via keymap
qmk/qmk_firmware pull request #19653
Opened 2023-01-21 21:56 UTC by C4illin

## Description

Added VIA keymap and changed info.json and config.h for 2015 to include device manufacturer, name and USB vid and pid. The changes to 2015 keyboard should cause no conflicts to existing users.

The VIA keymap matches the default keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-21 22:24 UTC, zvecr requested changes

2023-01-21 22:24 UTC, zvecr commented on keyboards/bpiphany/pegasushoof/2015/config.h
> +
This should not be added back, any required changes must instead be made to `info.json`
```suggestion
```

2023-01-21 22:24 UTC, zvecr commented on keyboards/bpiphany/pegasushoof/keymaps/via/rules.mk
> +
This should only contain overrides, not a copy/paste from the keyboard level
```suggestion
```

2023-01-23 11:05 UTC, drashna requested changes

2023-01-23 11:05 UTC, drashna commented on keyboards/bpiphany/pegasushoof/keymaps/via/keymap.c
> +#define KM_MEDIA   1
```suggestion
enum custom_layers {
    KM_QWERTY,
    M_MEDIA,
};
```

2023-01-24 09:21 UTC, drashna requested changes

2023-01-24 09:21 UTC, drashna commented on keyboards/bpiphany/pegasushoof/keymaps/via/keymap.c
> +    M_MEDIA,
Seems like the K got truncated? 
```suggestion
    KM_MEDIA,
```

2023-01-25 17:21 UTC, waffle87 requested changes

2023-01-25 17:21 UTC, waffle87 commented on keyboards/bpiphany/pegasushoof/2015/info.json
> +    },
If this isn't any different from what's in `keyboards/bpiphany/pegasushoof/info.json`, no need for it to be in this file.
```suggestion
```

2023-01-25 17:21 UTC, waffle87 commented on keyboards/bpiphany/pegasushoof/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```suggestion
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
```

2023-01-25 18:30 UTC, C4illin commented on keyboards/bpiphany/pegasushoof/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 3
But it works with 3?

2023-02-06 20:12 UTC, waffle87 approved these changes

2023-02-09 21:19 UTC, drashna approved these changes

2023-02-12 22:01 UTC, C4illin commented
Is there anything I need to do?

2023-02-17 06:29 UTC, merged