Add new keyboard Igloo
qmk/qmk_firmware pull request #19678
Opened 2023-01-25 03:55 UTC by djok0127

Pull request for Igloo

## Description

Adding support for new keyboard igloo

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ x ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ x ]Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-25 04:13 UTC, waffle87 requested changes

2023-01-25 04:13 UTC, waffle87 commented on keyboards/igloo/config.h
> +/*
This file should be removed.

2023-01-25 04:13 UTC, waffle87 commented on keyboards/igloo/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
These fields should be filled out or removed.

2023-01-25 04:13 UTC, waffle87 commented on keyboards/igloo/readme.md
> +* **Keycode in layout**: Press the key mapped to `RESET` if it is available
```suggestion
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-01-26 17:50 UTC, zvecr requested changes

2023-01-26 17:50 UTC, zvecr commented on keyboards/igloo/via/keymap.c
> +/*
This keymap is not inside the keymaps folder

2023-02-03 00:56 UTC, zvecr commented
As an fyi, you have a bunch of garbage commits pulled in from master. You can see this in the file changed tab and added labels .These will have to be removed for the PR to be considered mergable.

2023-02-03 11:16 UTC, djok0127 commented
Reverted the merge, sorry about that

2023-02-09 19:31 UTC, drashna approved these changes

2023-02-09 21:09 UTC, waffle87 commented on keyboards/igloo/readme.md
> +
```suggestion
```

2023-02-09 21:10 UTC, waffle87 approved these changes

2023-02-09 21:10 UTC, merged