[Keymap] Add milouk keymap and config
qmk/qmk_firmware pull request #19681
Opened 2023-01-25 16:47 UTC by milouk

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-25 17:06 UTC, waffle87 commented on keyboards/keebio/quefrency/keymaps/milouk/keymap.c
> +/* Copyright 2023 Michael Loukeris
This file should be removed if you intend to use the `keymap.json`. (That's what takes precedence anyway)

2023-02-08 04:39 UTC, drashna approved these changes

2023-03-03 17:42 UTC, waffle87 requested changes

2023-03-03 17:42 UTC, waffle87 commented on keyboards/keebio/quefrency/keymaps/milouk/keymap.json
> +  "keymap": "milouk_quefrency_rev1",
```suggestion
  "keymap": "milouk_quefrency_rev1",
  "config": {
      "features": {
          "via": true,
          "lto": true,
          "mousekey": true,
          "bootloader": "atmel-dfu"
      }
  }
```

2023-03-03 17:42 UTC, waffle87 commented on keyboards/keebio/quefrency/keymaps/milouk/rules.mk
> +BOOTLOADER = atmel-dfu  # Elite-C
This file should be able to be removed with above changes.

2023-05-18 01:55 UTC, closed without merging