adds gummykey
qmk/qmk_firmware pull request #19695
Opened 2023-01-27 19:30 UTC by gumorr

## Description
adds support for a keyboard i built called the "GummyKey". forgive me if theres any glaring issues, this is my first time doing something like this.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-27 19:43 UTC, waffle87 requested changes

2023-01-27 19:43 UTC, waffle87 commented on keyboards/gummykey/config.h
> +
```suggestion
```

2023-01-27 19:43 UTC, waffle87 commented on keyboards/gummykey/info.json
> +    },
```suggestion
    },
    "processor": "atmega32u4",
    "bootloader": "caterina",
```

2023-01-27 19:43 UTC, waffle87 commented on keyboards/gummykey/keymaps/default/readme.md
> +# Default layout for GummyKey
This file should be removed.

2023-01-27 19:43 UTC, waffle87 commented on keyboards/gummykey/readme.md
> +![gummykey](https://user-images.githubusercontent.com/102767971/215166168-12f08a78-ce6e-4368-9a70-0d4e8173b8e2.png)
This image should be rehosted on Imgur.

2023-01-27 19:43 UTC, waffle87 commented on keyboards/gummykey/readme.md
> +
```suggestion

* Keyboard Maintainer: [Gummor](https://github.com/gumorr)
* Hardware Supported: Pro Micro
* Hardware Availability: [Github](https://github.com/gumorr/GummyKey)

Make example for this keyboard (after setting up your build environment):

    make gummykey:default

Flashing example for this keyboard:

    make gummykey:default:flash
    
```

2023-01-27 19:43 UTC, waffle87 commented on keyboards/gummykey/rules.mk
> +
```suggestion
```

2023-02-03 01:11 UTC, zvecr requested changes

2023-02-03 01:11 UTC, zvecr commented on keyboards/gummykey/rules.mk
> +COMMAND_ENABLE = yes        # Commands for debug and configuration
```suggestion
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no        # Commands for debug and configuration
```

2023-02-03 01:11 UTC, zvecr commented on keyboards/gummykey/readme.md
> +a split keyboard i made
```suggestion
A 4x6+5 split keyboard.
```

2023-02-03 01:11 UTC, zvecr commented on keyboards/gummykey/readme.md
> +Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).
Missing <https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md#bootloader> per template.

2023-02-09 21:28 UTC, drashna commented on keyboards/gummykey/readme.md
> +![gummykey](https://i.imgur.com/R6ffs2B.png)
```suggestion
![gummykey](https://i.imgur.com/R6ffs2Bh.png)
```

2023-02-17 19:04 UTC, drashna requested changes

2023-02-17 19:04 UTC, drashna commented on keyboards/gummykey/config.h
> +#include "config_common.h"
```suggestion
```

2023-02-18 17:24 UTC, waffle87 requested changes

2023-02-18 17:24 UTC, waffle87 commented on keyboards/gummykey/config.h
> +
```suggestion
```

2023-02-18 17:24 UTC, waffle87 commented on keyboards/gummykey/info.json
> +	"bootloader": "caterina",
```suggestion
    },
    "processor": "atmega32u4",
    "bootloader": "caterina",
    "diode_direction": "ROW2COL",
```

2023-02-19 05:31 UTC, waffle87 approved these changes

2023-02-26 18:06 UTC, gumorr commented
is this gonna be merged any time soon?

2023-03-06 19:17 UTC, drashna approved these changes

2023-03-06 19:17 UTC, merged