Baion 808
qmk/qmk_firmware pull request #19690
Opened 2023-01-26 23:12 UTC by yiancar

Add Baion 808 keyboard:)

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-26 23:34 UTC, waffle87 requested changes

2023-01-26 23:34 UTC, waffle87 commented on keyboards/baion_808/config.h
> +
```suggestion
```

2023-01-26 23:34 UTC, waffle87 commented on keyboards/baion_808/config.h
> +#define BOOTMAGIC_LITE_COLUMN 0
```suggestion
```

2023-01-26 23:34 UTC, waffle87 commented on keyboards/baion_808/readme.md
> +
```suggestion
Flashing example for this keyboard:

    make baion_808:default:flash

```

2023-01-26 23:34 UTC, waffle87 commented on keyboards/baion_808/rules.mk
> +
```suggestion
```

2023-01-26 23:34 UTC, waffle87 commented on keyboards/baion_808/info.json
> +    },
```suggestion
    },
    "processor": "STM32F072",
    "bootloader": "stm32-dfu",
```

2023-01-26 23:34 UTC, waffle87 commented on keyboards/baion_808/keymaps/default/readme.md
> +![Layer 0](https://i.imgur.com/IhbvSZ1.png)
Both the keymap `readme.md`'s should be removed and this image displayed in keyboard level `readme.md`, if you feel necessary.

2023-01-26 23:42 UTC, yiancar commented
Done!

2023-01-26 23:44 UTC, waffle87 approved these changes

2023-01-27 00:08 UTC, zvecr requested changes
Also does the following image represent the PCB?
![image](https://user-images.githubusercontent.com/16520359/214977940-350eff05-0bb8-42cd-abf7-4e3923e06af6.png)

2023-01-27 00:08 UTC, zvecr commented on keyboards/baion_808/readme.md
> +    make baion_808:default
```suggestion
    make baion_808:default

```

2023-01-27 00:34 UTC, yiancar commented
@zvecr indeed so:)

2023-01-27 01:33 UTC, zvecr commented
> @zvecr indeed so:)

Then I would expect the layout macro to be `LAYOUT_all` and it should also implement the tlk community layouts.

2023-01-27 01:38 UTC, yiancar commented
Can add the tlk community layout.
So in that case the suggestion would be LAYOUT_all for via and then a LAYOUT_tkl_f13_ansi_split_bs_rshift for the comunity?

2023-01-27 15:34 UTC, yiancar commented
@zvecr I think now everyone should be happy with the layouts?:)

2023-01-29 11:18 UTC, yiancar commented
Bump:)

2023-01-29 12:24 UTC, fauxpark approved these changes

2023-01-29 14:08 UTC, yiancar commented
Sorry I made a mistake with f13 here... give me a few to fix that..

2023-01-29 14:52 UTC, yiancar commented
Sorry for all the mess, it is now correct...

2023-01-29 15:00 UTC, yiancar commented
OK CI is failing on [talljoe-tkl](https://github.com/qmk/qmk_firmware/tree/master/layouts/community/tkl_ansi/talljoe-tkl) this layout :/ I think the layout itself is broken?

2023-01-29 15:26 UTC, sigprof commented
Yes, looks like most layouts and some keymaps by @Talljoe are broken since #17229, included in [QMK 0.18.0](https://docs.qmk.fm/#/ChangeLog/20220827). In #17559 (also included in QMK 0.18.0) a workaround for similar cases was added (the source file that actually defines the `keymaps` array needs to be specified in the `INTROSPECTION_KEYMAP_C` make variable and removed from `SRC`).

2023-01-29 16:59 UTC, merged