Add new keymap for Preonic
qmk/qmk_firmware pull request #19706
Opened 2023-01-28 21:15 UTC by guillermoap

## Description
Created new keymap for Preonic with encoder support. As mentioned in the README this is highly curated to my liking but is a good example to use the ENCODER_MAP_ENABLE from the docs that I haven't seen in other keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-08 04:44 UTC, drashna commented on keyboards/preonic/keymaps/guillermoap/keymap.c
> +}
```suggestion
```

2023-02-08 04:45 UTC, drashna commented on keyboards/preonic/keymaps/guillermoap/keymap.c
> +                SEND_STRING(SS_LCTL("c"));
`LCTL(KC_C)` in your keymap will work for this as well (as will `C(KC_NC)`.

2023-02-08 04:45 UTC, drashna commented on keyboards/preonic/keymaps/guillermoap/keymap.c
> +                SEND_STRING(SS_LCTL("z"));
Same, here.

2023-02-08 05:26 UTC, fauxpark requested changes

2023-02-08 05:26 UTC, fauxpark commented on keyboards/preonic/keymaps/guillermoap/config.h
> +//#define MIDI_TONE_KEYCODE_OCTAVES 2
```suggestion
```

2023-02-10 09:22 UTC, drashna approved these changes

2023-02-22 14:37 UTC, guillermoap commented
@drashna @fauxpark Do I need to do anything else with this PR?

2023-02-23 01:09 UTC, fauxpark approved these changes

2023-03-03 22:01 UTC, merged