[Keyboard] Add alas keyboard
qmk/qmk_firmware pull request #19717
Opened 2023-01-30 14:31 UTC by yiancar

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-01-30 14:34 UTC, yiancar commented
errors of CI have to do with community layouts

2023-01-30 17:18 UTC, waffle87 requested changes

2023-01-30 17:18 UTC, waffle87 commented on keyboards/alas/config.h
> +
Moving away from this as per #19714.
```suggestion
```

2023-01-30 17:18 UTC, waffle87 commented on keyboards/alas/config.h
> +//#define FORCE_NKRO
Moving away from this as per #19718.
```suggestion
```

2023-01-30 17:18 UTC, waffle87 commented on keyboards/alas/readme.md
> +This is a standard TKL layout PCB. It supports VIA.
> TKL

I'd fix this to avoid any confusion..

2023-01-30 18:29 UTC, yiancar commented on keyboards/alas/config.h
> +
good to know!

2023-01-30 18:29 UTC, yiancar commented on keyboards/alas/readme.md
> +This is a standard TKL layout PCB. It supports VIA.
i thought i fixed this upsie one second

2023-02-09 11:41 UTC, yiancar commented
ping:)

2023-02-09 11:43 UTC, fauxpark requested changes

2023-02-09 11:43 UTC, fauxpark commented on keyboards/alas/config.h
> +
```suggestion
```

2023-02-09 11:43 UTC, fauxpark commented on keyboards/alas/config.h
> +
```suggestion
```

2023-02-09 12:04 UTC, fauxpark approved these changes

2023-02-10 06:25 UTC, drashna commented on keyboards/alas/readme.md
> +![Layer 1](https://i.imgur.com/RJDVmty.png)
```suggestion
![Layer 0](https://i.imgur.com/LL5mZXAh.png)
![Layer 1](https://i.imgur.com/RJDVmtyh.png)
```

2023-02-10 09:09 UTC, drashna approved these changes

2023-02-10 09:09 UTC, merged