Add greatsword80
qmk/qmk_firmware pull request #19746
Opened 2023-02-04 17:24 UTC by EasonQian1

## Description
Add greatsword80

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-04 17:53 UTC, waffle87 requested changes

2023-02-04 17:53 UTC, waffle87 commented on keyboards/eason/greatsword80/config.h
> + */
```suggestion
```

2023-02-04 17:53 UTC, waffle87 commented on keyboards/eason/greatsword80/greatsword80.h
> +/* Copyright 2023 Eason <xiaoxuxk@yeah.net>
This file should be removed, assuming the `matrix` data in `info.json` file is correct.

2023-02-04 17:53 UTC, waffle87 commented on keyboards/eason/greatsword80/greatsword80.c
> +/* Copyright 2023 Eason <xiaoxuxk@yeah.net>
This file can also be removed if above comment is true.

2023-02-04 17:53 UTC, waffle87 commented on keyboards/eason/greatsword80/rules.mk
> +
```suggestion
```

2023-02-04 17:53 UTC, waffle87 commented on keyboards/eason/greatsword80/info.json
> +    },
```suggestion
    },
    "processor": "atmega32u4",
    "bootloader": "atmel-dfu",
```

2023-02-04 17:53 UTC, waffle87 commented on keyboards/eason/greatsword80/readme.md
> +    make eason/greatsword80:default
```suggestion
    make eason/greatsword80:default
    
Flashing example for this keyboard:

    make eason/greatsword80:default:flash

```

2023-02-06 17:09 UTC, waffle87 commented
Please see the changes that I marked as unresolved.

2023-02-07 06:54 UTC, EasonQian1 commented
> Please see the changes that I marked as unresolved.
Hello buddy. I modified

2023-02-07 07:57 UTC, waffle87 commented
That's not what I meant. In `info.json` file, you have `matrix` coordinates:
eg.
```{"label": "K00 (B0,B6)", "matrix": [0, 0], "x": 0, "y": 0},```
This eliminates the need to define the layout macro in `greatsword.h` file.
So if the `matrix` data in `info.json` file is correct, `greatsword.c` & `greatsword.h` files should both be deleted.

2023-02-07 08:02 UTC, EasonQian1 commented
> That's not what I meant. In `info.json` file, you have `matrix` coordinates: eg. `{"label": "K00 (B0,B6)", "matrix": [0, 0], "x": 0, "y": 0},` This eliminates the need to define the layout macro in `greatsword.h` file. So if the `matrix` data in `info.json` file is correct, `greatsword.c` & `greatsword.h` files should both be deleted.

LOL！I see, I misunderstood. Thanks

2023-02-08 03:42 UTC, EasonQian1 commented
@waffle87 Hi buddy. Please help me to check if it is correct

2023-02-09 20:38 UTC, drashna approved these changes

2023-02-09 20:57 UTC, waffle87 approved these changes

2023-02-09 20:57 UTC, merged