Move FAve 84H to data driven design + Via Custom UI
qmk/qmk_firmware pull request #19763
Opened 2023-02-07 02:44 UTC by ToastyStoemp

## Description

This updates the FAve 84 Hotswap board to data driven design.
Fixes the LED config that was removed due to incorrect configuration from previous PR.
Set the right flags on Mods / Alphas for LEDs

Add Custom UI VIA definitions for user control of the Caps lock indicator

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-07 03:25 UTC, zvecr requested changes
You have a mixture of `_kb` functions defined at the keymap level. This is incorrect and needs to be changed to `_user` versions (should probably also use the basic `eeconfig_update_user` as you are only storing 4 bytes, which the basic functionality already provides ).

2023-02-07 03:25 UTC, zvecr commented on keyboards/linworks/fave84h/config.h
> +#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_ALL
`RGB_MATRIX_STARTUP_MODE` isnt a thing anymore

```suggestion
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL
```

2023-02-07 03:29 UTC, waffle87 requested changes

2023-02-07 03:29 UTC, waffle87 commented on keyboards/linworks/fave84h/config.h
> +#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_ALL
```suggestion
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL
```

2023-02-07 03:29 UTC, waffle87 commented on keyboards/linworks/fave84h/config.h
>  #include "config_common.h"
```suggestion
```

2023-02-07 03:29 UTC, waffle87 commented on keyboards/linworks/fave84h/keymaps/via/keymap.c
> +    }
```suggestion
void keyboard_post_init_user(void) {
    //Read our custom menu variables from memory
    eeconfig_read_kb_datablock(&fave);
}

bool rgb_matrix_indicators_user(void) {
```

2023-02-07 03:29 UTC, waffle87 commented on keyboards/linworks/fave84h/keymaps/via/keymap.c
> +void eeconfig_init_kb(void) {
```suggestion
void eeconfig_init_user(void) {
```

2023-02-08 06:55 UTC, ToastyStoemp commented
> You have a mixture of `_kb` functions defined at the keymap level. This is incorrect and needs to be changed to `_user` versions (should probably also use the basic `eeconfig_update_user` as you are only storing 4 bytes, which the basic functionality already provides ).

Updated all Except for the `via_custom_value_command_kb` function due to the lack of a user version of that.

2023-02-10 03:21 UTC, drashna approved these changes

2023-02-10 03:58 UTC, waffle87 approved these changes

2023-02-10 03:59 UTC, merged