Sejin EAT-1010M2 keyboard
qmk/qmk_firmware pull request #19802
Opened 2023-02-10 15:11 UTC by DmNosachev

Sejin Electronics EAT-1010M2 controller replacement.
Handwired Blue Pill to membrane.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-10 17:14 UTC, waffle87 requested changes

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/keymaps/default/keymap.c
> +*/
```suggestion
```

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/readme.md
> +![Z-150](https://imgur.com/jayyyvJ.jpg)
```suggestion
![Z-150](https://i.imgur.com/jayyyvJh.jpg)
```

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/readme.md
> +    make handwired/z150:default
```suggestion
    make handwired/sejin_eat1010r2:default

Flashing example for this keyboard:

    make handwired/sejin_eat1010r2:default:flash

```

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/readme.md
> +
Please add instruction on entering bootloader mode, as per [template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md?plain=1#L21-L27).

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/readme.md
> +## Black Pill
`info.json` says this uses a bluepill? May want to clear that up.

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/info.json
> +	"debounce": 5
```suggestion
```

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/info.json
> +}
This file is missing the x, y coordinates (at the minimum). See [configuator support](https://docs.qmk.fm/#/reference_configurator_support).

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/config.h
> +
```suggestion
#define MATRIX_HAS_GHOST
```

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/info.json
> +    },
```suggestion
        "command": false,
        "console": false,
        "extrakey": true,
        "midi": false,
        "mousekey": true,
        "nkro": false,
        "rgblight": false,
        "unicode": false,
        "bluetooth": false,
        "backlight": false,
        "sleep_led": false
    },
    "indicators": {
        "num_lock": "B0",
        "caps_lock": "B1",
        "scroll_lock": "B10",
    },
```

2023-02-10 17:14 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/sejin_eat1010r2.c
> +}
```suggestion
```

2023-02-11 07:27 UTC, DmNosachev commented
Sorry, I messed up something in my fork. I'd better delete this pull request and fix everything.

2023-02-11 07:27 UTC, closed without merging