Sejin EAT-1010R2 keyboard
qmk/qmk_firmware pull request #19809
Opened 2023-02-11 09:09 UTC by DmNosachev

## Description
Sejin EAT-1010R2 keyboard, STM32F103 Blue Pill handwired to the membrane.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-11 17:11 UTC, zvecr requested changes

2023-02-11 17:11 UTC, zvecr commented on keyboards/handwired/sejin_eat1010r2/config.h
> +
```suggestion
```

2023-02-11 17:11 UTC, zvecr commented on keyboards/handwired/sejin_eat1010r2/halconf.h
> +/* Copyright 2020 QMK
File should be deleted

2023-02-11 17:11 UTC, zvecr commented on keyboards/handwired/sejin_eat1010r2/keymaps/default/keymap.c
> +*/
```suggestion
```

2023-02-11 17:11 UTC, zvecr commented on keyboards/handwired/sejin_eat1010r2/mcuconf.h
> +/* Copyright 2020 QMK
File should be deleted

2023-02-11 17:11 UTC, zvecr commented on keyboards/handwired/sejin_eat1010r2/sejin_eat1010r2.c
> +/* Copyright 2023 DmNosachev
File should be deleted

2023-02-11 18:49 UTC, waffle87 commented
Unsure why you closed #19802, but the changes I suggested there still need to be applied to this one.

2023-02-12 05:52 UTC, drashna commented
> Unsure why you closed #19802, but the changes I suggested there still need to be applied to this one.

To pile on that, PRs shouldn't be closed and reopened.  If there is an issue with a PR, there is a good chance that it is something that we've run into as well, and may be able to help fix.

2023-02-17 12:23 UTC, DmNosachev commented
Sorry for the inconvenience. I'm still insecure with complex Git actions. I closed the previous PR because I got confused about the commits in my fork.

2023-02-18 08:11 UTC, drashna approved these changes

2023-02-18 17:20 UTC, waffle87 requested changes

2023-02-18 17:20 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/info.json
> +	"debounce": 5,
```suggestion
    "diode_direction": "COL2ROW",
    "development_board": "bluepill",
    "matrix_pins": {
        "cols": ["B9", "B8", "B7", "B6", "B5", "B4", "B3", "A15", "C13", "C14", "C15", "A0", "A1", "A2", "A3", "A4"],
        "rows": ["B11", "B12", "B13", "B14", "B15", "A8", "A9", "A10"],
        "ghost": true
    },
    "indicators": {
        "caps_lock": "B1",
        "num_lock": "B0",
        "scroll_lock": "B10"
    },
    "features": {
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": false
    },
    "bootmagic" {
        "matrix": [1, 0]
    },
```

2023-02-18 17:20 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/config.h
> +/*
This file can be removed with my suggestion in `info.json`.

2023-02-18 17:20 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/readme.md
> +    qmk compile -kb handwired/sejin_eat1010r2 -km default
```suggestion
    make handwired/sejin_eat1010r2:default
    
Flashing example for this keyboard:

    make handwired/sejin_eat1010r2:default:flash

```

2023-02-18 17:55 UTC, waffle87 commented on keyboards/handwired/sejin_eat1010r2/info.json
> +    "bootmagic" {
Sorry, typo'd this.
```suggestion
    "bootmagic": {
```

2023-02-18 17:55 UTC, waffle87 approved these changes

2023-02-20 12:55 UTC, DmNosachev commented
I see а message 'Changes requested' ('zvecr requested changes'), but his changes are marked as 'Outdated'. What should I do about these messages?

2023-03-06 19:39 UTC, merged