[Keymap] Add new 42 keymap for the cantor keyboard
qmk/qmk_firmware pull request #19810
Opened 2023-02-11 16:54 UTC by Cobbleston

## Description

Added new keymap for the cantor keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-11 17:09 UTC, zvecr requested changes
* "Cobbleston" is an invalid keymap name due to the capital letter, folder needs to be renamed
* pdf files are not accepted to this repo, they need to be deleted

2023-02-11 17:09 UTC, zvecr commented on keyboards/cantor/keymaps/Cobbleston/config.h
> +//#define NO_ACTION_ONESHOT
```suggestion
```

2023-02-11 17:09 UTC, zvecr commented on keyboards/cantor/keymaps/Cobbleston/keymap-markstos-like.c
> +#include QMK_KEYBOARD_H
File should be deleted

2023-02-11 17:09 UTC, zvecr commented on keyboards/cantor/keymaps/Cobbleston/keymap-miryoku-like.c
> +#include QMK_KEYBOARD_H
File should be deleted

2023-02-11 17:09 UTC, zvecr commented on keyboards/cantor/keymaps/Cobbleston/keymap.c
> +#include QMK_KEYBOARD_H
Needs licence header

2023-02-13 17:25 UTC, Cobbleston commented
Now it should be ok I think, do I need to check all 14 checks before being able to merge in the mail repo?

2023-02-17 19:05 UTC, drashna commented on keyboards/cantor/keymaps/konova8/config.h
> +#include "config_common.h"
```suggestion
```

2023-03-06 19:40 UTC, drashna approved these changes

2023-03-25 15:03 UTC, konova8 commented
Sorry to bother, is there still something I have to do before being able to merge?
Thank you!

2023-03-25 15:08 UTC, fauxpark approved these changes

2023-03-25 15:08 UTC, fauxpark commented on keyboards/cantor/keymaps/konova8/config.h
> +
```suggestion
```

2023-03-25 15:09 UTC, fauxpark requested changes
Wrong button

2023-08-29 17:25 UTC, zvecr commented
Unfortunately since this PRs creation, QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

In the near future we will be providing a more user focused workflow for keymaps, but till then the suggestion is to keep changes in your own fork.

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.

2023-08-29 17:25 UTC, closed without merging