Add Keychron Q12
qmk/qmk_firmware pull request #19844
Opened 2023-02-14 03:36 UTC by lalalademaxiya1

Added new keyboard Q12 which contains two sub versions.
Thanks!

## Description

- Added ANSI and ISO versions with encoder support.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-14 03:44 UTC, fauxpark requested changes

2023-02-14 03:44 UTC, fauxpark commented on keyboards/keychron/q12/config.h
> +
```suggestion
```

2023-02-14 06:14 UTC, lalalademaxiya1 commented on keyboards/keychron/q12/config.h
> +
Thanks!

2023-02-15 22:18 UTC, drashna requested changes

2023-02-15 22:18 UTC, drashna commented on keyboards/keychron/q12/ansi_encoder/config.h
> +#define ENCODER_RESOLUTION 4
This is the default and shouldn't be defined here. 
```suggestion
```

2023-02-15 22:18 UTC, drashna commented on keyboards/keychron/q12/iso_encoder/config.h
> +#define ENCODER_RESOLUTION 4
```suggestion
```

2023-02-16 02:28 UTC, lalalademaxiya1 commented on keyboards/keychron/q12/iso_encoder/config.h
> +#define ENCODER_RESOLUTION 4
All right, Thanks!

2023-02-17 19:07 UTC, drashna approved these changes

2023-02-28 03:34 UTC, flowchartsman commented
My Q12 arrived today, any chance we can get this merged?

2023-02-28 03:40 UTC, fauxpark requested changes

2023-02-28 03:40 UTC, fauxpark commented on keyboards/keychron/q12/ansi_encoder/info.json
> +    },
```suggestion
    },
    "encoder": {
        "rotary": [
            {"pin_a": "A2", "pin_b": "C14"}
        ]
    },
```

2023-02-28 03:40 UTC, fauxpark commented on keyboards/keychron/q12/ansi_encoder/config.h
> +#define ENCODERS_PAD_B { C14 }
```suggestion
```

2023-02-28 03:40 UTC, fauxpark commented on keyboards/keychron/q12/iso_encoder/info.json
> +    },
```suggestion
    },
    "encoder": {
        "rotary": [
            {"pin_a": "A2", "pin_b": "C14"}
        ]
    },
```

2023-02-28 03:40 UTC, fauxpark commented on keyboards/keychron/q12/iso_encoder/config.h
> +#define ENCODERS_PAD_B { C14 }
```suggestion
```

2023-02-28 03:43 UTC, lalalademaxiya1 commented on keyboards/keychron/q12/ansi_encoder/info.json
> +    },
Thanks!

2023-03-01 01:03 UTC, keychron-dev commented
@fauxpark please have a look of this. thanks

2023-03-01 01:17 UTC, fauxpark approved these changes

2023-03-01 14:31 UTC, keychron-dev commented
can you merge this since we have two approvals on this? sorry about the message, we have users keep asking about this, thanks @fauxpark @drashna

2023-03-04 00:53 UTC, merged