Add ac001 keyboard
qmk/qmk_firmware pull request #19868
Opened 2023-02-17 08:22 UTC by jonylee1986

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-17 10:44 UTC, zvecr requested changes
Also,
* `readme.md` missing - needs to follow [template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md)

2023-02-17 10:44 UTC, zvecr commented on keyboards/hfdkb/ac001/config.h
> +#define RGB_MATRIX_CENTER {112,32}
```suggestion
```

2023-02-17 10:44 UTC, zvecr commented on keyboards/hfdkb/ac001/rules.mk
> +ENCODER_ENABLE = no
```suggestion
```

2023-02-17 10:44 UTC, zvecr commented on keyboards/hfdkb/ac001/keymaps/default/keymap.c
> +		RGB_MOD, KC_LCTL, KC_ENT,KC_NO,KC_NO)
```suggestion
```

2023-02-18 05:28 UTC, drashna approved these changes

2023-02-18 17:28 UTC, waffle87 commented on keyboards/hfdkb/ac001/readme.md
> +    make hfdkb/ac001:default
```suggestion
    make hfdkb/ac001:default

Flashing example for this keyboard:

    make hfdkb/ac001:default:flash

```

2023-02-18 17:28 UTC, waffle87 approved these changes

2023-02-18 17:28 UTC, merged