Add Support for Lilly58 r2g
qmk/qmk_firmware pull request #19862
Opened 2023-02-16 17:44 UTC by e11i0t23

## Description

Add support for the mechboards lily58 r2g, this is a revision of the lily58 which comes presolder featuring custom rgb and a base keymap with altered oled behaviour. SImilar also to the CRKBD R2G

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-16 17:48 UTC, fauxpark requested changes

2023-02-16 17:48 UTC, fauxpark commented on keyboards/lily58/r2g/config.h
> +
```suggestion
```

2023-02-16 17:48 UTC, fauxpark commented on keyboards/lily58/r2g/rules.mk
> +BOOTLOADER = atmel-dfu
```suggestion
```

2023-02-16 17:48 UTC, fauxpark commented on keyboards/lily58/r2g/readme.md
> +```
```suggestion

    make crkbd/r2g:default

Flashing example for this keyboard:

    make crkbd/r2g:default:flash
```

2023-02-16 21:20 UTC, waffle87 requested changes

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/keymaps/mb_via/config.h
> +*/
```suggestion
```

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/keymaps/mb_via/keymap.c
> +//extern uint8_t is_master;
```suggestion
```

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/r2g/config.h
> +
```suggestion
```

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/r2g/info.json
> +
```suggestion
```

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/r2g/config.h
> +#ifdef RGB_MATRIX_ENABLE
```suggestion
#ifdef RGB_MATRIX_ENABLE
#   define RGB_DI_PIN D3
```

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/r2g/r2g.c
> +#include "r2g.h"
This file is missing a license header.

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/r2g/r2g.c
> +}
```suggestion
void oled_render_layer_state_r2g(void) {
    oled_write_P(PSTR("Layer: "), false);
    switch (get_highest_layer(layer_state)) {
        case 0:
            oled_write_ln_P(PSTR("Default"), false);
            break;
        case 1:
            oled_write_ln_P(PSTR("Lower"), false);
            break;
        case 2:
            oled_write_ln_P(PSTR("Raise"), false);
            break;
        case 3:
            oled_write_ln_P(PSTR("Adjust"), false);
            break;
        default:
            oled_write_ln_P(PSTR("Unknown"), false);
    }
}
```

2023-02-16 21:20 UTC, waffle87 commented on keyboards/lily58/r2g/r2g.h
> +#pragma once
This file can probably be removed. Will need to remove its inclusion elsewhere and whatnot of course.

2023-03-03 22:07 UTC, waffle87 approved these changes

2023-03-03 23:02 UTC, keyboard-magpie approved these changes

2023-03-03 23:04 UTC, merged