Update to pi40
qmk/qmk_firmware pull request #19903
Opened 2023-02-21 16:58 UTC by ziptyze

Updates to pi40

## Description

Updated pi40 to include v1.1 of the pcb which allows for grid and mit layouts

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-21 19:28 UTC, zvecr commented on keyboards/1upkeyboards/pi40/rules.mk
> -# MCU name
This file needs a `DEFAULT_FOLDER` rule or it has to be removed (otherwise it will create invalid build targets).

2023-03-07 18:49 UTC, drashna requested changes

2023-03-07 18:49 UTC, drashna commented on keyboards/1upkeyboards/pi40/grid_v1_1/config.h
> +#define RGB_MATRIX_LED_COUNT 48
```suggestion
#pragma once

#define RGB_MATRIX_LED_COUNT 48
```

2023-03-08 09:25 UTC, drashna approved these changes

2023-03-08 17:07 UTC, closed without merging