implement rgb matrix for momokai keyboards
qmk/qmk_firmware pull request #19904
Opened 2023-02-21 17:21 UTC by peepeetee

Enabled the RGB matrix I implemented but didn't enable due to VIA incompatibility. now that VIA works with it I have enabled it. I also enabled all effects to work with VIA effect selection, suggest something else if preferable.

At the request of the vendor I limited the max brightness to 200

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-21 21:21 UTC, waffle87 requested changes

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_duo/config.h
```suggestion
```

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_duo/config.h
> +
```suggestion
```

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_duo/config.h
> +#ifdef RGB_MATRIX_ENABLE
```suggestion
#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_LED_COUNT 4
#define RGB_MATRIX_KEYPRESSES // reacts to keypresses
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
```

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_trio/config.h
```suggestion
```

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_trio/config.h
```suggestion
```

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_trio/config.h
```suggestion
#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_LED_COUNT 5
```

2023-02-21 21:21 UTC, waffle87 commented on keyboards/momokai/tap_trio/config.h
> +#ifdef RGB_MATRIX_ENABLE
```suggestion
```

2023-03-07 18:50 UTC, drashna approved these changes

2023-03-07 21:07 UTC, waffle87 approved these changes

2023-03-07 21:07 UTC, merged