Added a new keyboard LXXT
qmk/qmk_firmware pull request #19935
Opened 2023-02-25 07:09 UTC by DeskDaily

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-25 07:23 UTC, fauxpark requested changes

2023-02-25 07:23 UTC, fauxpark commented on keyboards/lxxt/info.json
> +    },
```suggestion
    },
    "encoder": {
        "rotary": [
            {"pin_a": "GP27", "pin_b": "GP28"},
            {"pin_a": "GP8", "pin_b": "GP9"}
        ]
    },
```

2023-02-25 07:23 UTC, fauxpark commented on keyboards/lxxt/config.h
> +#define ENCODERS_PAD_B { GP28, GP9 }
```suggestion
```

2023-02-25 13:21 UTC, zvecr requested changes

2023-02-25 13:21 UTC, zvecr commented on keyboards/lxxt/info.json
> +        "key_lock": false
```suggestion
        "rgblight": true,
```

2023-02-25 13:21 UTC, zvecr commented on keyboards/lxxt/keymaps/default/keymap.c
> +    ),
```suggestion
```

2023-02-28 05:38 UTC, drashna requested changes
Could you do this: 
https://docs.qmk.fm/#/feature_encoders?id=callbacks

2023-02-28 23:33 UTC, fauxpark approved these changes

2023-03-01 01:09 UTC, zvecr commented on keyboards/lxxt/keymaps/default/keymap.c
> +}
Or encoder should be enabled by default
```suggestion
#if defined(ENCODER_ENABLE)
bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) { /* First encoder */
        if (clockwise) {
            tap_code_delay(KC_VOLU, 10);
        } else {
            tap_code_delay(KC_VOLD, 10);
        }
    } else if (index == 1) { /* Second encoder */
        if (clockwise) {
            tap_code_delay(KC_BRIU, 10);
        } else {
            tap_code_delay(KC_BRID, 10);
        }
    }
    return false;
}
#endif
```

2023-03-10 20:12 UTC, drashna approved these changes

2023-03-10 20:13 UTC, drashna commented on keyboards/lxxt/keymaps/default/keymap.c
> +#endif
could this be moved to a lxxt.c file instead?

2023-03-23 03:37 UTC, fauxpark requested changes

2023-03-23 03:37 UTC, fauxpark commented on keyboards/lxxt/lxxt.h
> +/* Copyright 2023 DeskDaily
This file can be deleted.

2023-03-23 03:37 UTC, fauxpark commented on keyboards/lxxt/lxxt.c
> +#include "lxxt.h"
```suggestion
#include "quantum.h"
```

2023-04-02 17:52 UTC, waffle87 commented on keyboards/lxxt/keymaps/default/rules.mk
This file should be removed.

2023-04-05 18:24 UTC, waffle87 approved these changes

2023-04-05 18:25 UTC, merged