Add FRL84 PCB.
qmk/qmk_firmware pull request #19942
Opened 2023-02-26 03:53 UTC by studiokestra

## Description

Add QMK & VIA support for FRL84 PCB, meant to be used in the P3D FRL84 Invisibolt keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-02-26 06:04 UTC, waffle87 requested changes

2023-02-26 06:04 UTC, waffle87 commented on keyboards/studiokestra/frl84/config.h
> +
```suggestion
```

2023-02-26 06:04 UTC, waffle87 commented on keyboards/studiokestra/frl84/config.h
> +//   #define RGBLIGHT_EFFECT_BREATHE_MAX    255   // 0 to 255
```suggestion
```

2023-02-26 06:04 UTC, waffle87 commented on keyboards/studiokestra/frl84/keymaps/default/keymap.c
> +    )
```suggestion
    )
```

2023-02-26 06:04 UTC, waffle87 commented on keyboards/studiokestra/frl84/readme.md
> +![studiokestra/frl84](https://i.imgur.com/XzO7Ly0.png)
```suggestion
![studiokestra/frl84](https://i.imgur.com/XzO7Ly0h.png)
```

2023-02-26 06:04 UTC, waffle87 commented on keyboards/studiokestra/frl84/readme.md
> +* Hardware Availability: https://p3dstore.com/products/frl84-invisibolt-case-and-pcb-group-buy
```suggestion
* Hardware Availability: [FRL84 Invisibolt Case and PCB Group Buy](https://p3dstore.com/products/frl84-invisibolt-case-and-pcb-group-buy)
```

2023-02-26 18:04 UTC, waffle87 approved these changes

2023-02-27 10:11 UTC, fauxpark approved these changes

2023-02-28 05:26 UTC, drashna approved these changes

2023-02-28 20:22 UTC, merged