[Keyboard] Neokeys G88 hotswap & solder
qmk/qmk_firmware pull request #19962
Opened 2023-02-28 08:08 UTC by tommyamoszhao

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-01 03:19 UTC, tommyamoszhao commented
Thank you @lesshonor , matrix info is added in info.json, modified some minor infomation mistakes.
Best, TommyZ

2023-03-01 04:54 UTC, tommyamoszhao commented
Hi @lesshonor, sorry to bother, I built all default and via version of firmwares of both G88 solder and hotswap PCBs locally, all went well, but they still failed in QMK CI Build. May I know is there anything I still need to change?
Best, TommyZ

2023-03-01 17:42 UTC, waffle87 requested changes

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/hotswap/config.h
> +
```suggestion
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/hotswap/config.h
> +#endif
```suggestion
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/hotswap/info.json
> +    "bootloader": "atmel-dfu",
```suggestion
    "bootloader": "atmel-dfu",
    "diode_direction": "COL2ROW",
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/readme.md
> +
```suggestion

## Bootloader

```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/solder/config.h
> +
```suggestion
#define MATRIX_ROW_PINS { B0, B1, B2, B3, B7, C6 }
#define MATRIX_COL_PINS { C7, F6, F5, F4, F1, E6, D5, D2, D0, D3, D4, D1, D6, D7, B4, B5 }
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/solder/info.json
> +    "bootloader": "atmel-dfu",
```suggestion
    "bootloader": "atmel-dfu",
    "diode_direction": "COL2ROW",
    "backlight": {
        "pin": "B6",
        "levels": 6,
        "breathing": true
    },
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/solder/info.json
> +        "LAYOUT_all": {
```suggestion
        "LAYOUT": {
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/solder/keymaps/via/keymap.c
> +	[2] = LAYOUT_all(
```suggestion
    [0] = LAYOUT(
		KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_F13, KC_SCRL, KC_PAUS, 
		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_MINS, KC_EQL, KC_BSPC, KC_DEL, KC_HOME, KC_PGUP, 
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, KC_END, KC_PGDN, 
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_HASH, KC_ENT, KC_LEFT, KC_INS, 
		KC_LSFT, KC_BSLS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(2), KC_UP, KC_DEL, 
		KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_PSCR, KC_0, KC_RALT, MO(1), KC_APP, KC_RCTL, KC_DOWN, KC_RGHT
    ),
	[1] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, RGB_TOG, KC_UP,   RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, QK_BOOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
	[2] = LAYOUT(
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/solder/rules.mk
> +RGBLIGHT_ENABLE = yes		# Enable RGB Backlight
```suggestion
```

2023-03-01 17:42 UTC, waffle87 commented on keyboards/neokeys/g88/solder/solder.h
> +#define LAYOUT_all( \
```suggestion
#define LAYOUT( \
```

2023-03-22 04:30 UTC, tommyamoszhao commented
Hi @drashna, matrix_pins info has been moved into info.json, .h file is deleted and copyright info is corrected. Thx TommyZ

2023-03-23 06:48 UTC, drashna commented on keyboards/neokeys/g88/hotswap/config.h
> +#define MATRIX_COL_PINS { C7, F6, F5, F4, F1, E6, D5, D2, D0, D3, D4, D1, D6, D7, B4, B5 }
```suggestion
```

2023-03-26 08:44 UTC, tommyamoszhao commented
hi @drashna , both .h files are deleted and matrix info is moved into info.json. :)

2023-06-15 02:01 UTC, closed without merging