add tiger80 iso layout support
qmk/qmk_firmware pull request #19975
Opened 2023-03-01 00:17 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-01 00:38 UTC, zvecr commented on keyboards/kbdfans/tiger80/config.h
>   */
```suggestion
 */
 
 #pragma once
```

2023-03-01 17:28 UTC, waffle87 requested changes

2023-03-01 17:28 UTC, waffle87 commented on keyboards/kbdfans/tiger80/keymaps/iso/keymap.c
> +    [_LAYER0] = LAYOUT_tkl_f13_iso_tsangan(
```suggestion
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [0] = LAYOUT_tkl_f13_iso_tsangan(
```

2023-03-01 17:28 UTC, waffle87 commented on keyboards/kbdfans/tiger80/info.json
>      "community_layouts": ["tkl_f13_ansi_tsangan"],
```suggestion
    "community_layouts": ["tkl_f13_ansi_tsangan", "tkl_f13_iso_tsangan"],
```

2023-03-01 17:28 UTC, waffle87 commented on keyboards/kbdfans/tiger80/info.json
> +    "debounce": 5,
```suggestion
```

2023-03-04 03:12 UTC, waffle87 commented on keyboards/kbdfans/tiger80/rules.mk
> -AUDIO_ENABLE = no           # Audio output
If this file is empty, it should contain only
```make
# This file intentionally left blank
```

2023-03-10 07:56 UTC, drashna approved these changes

2023-03-15 16:53 UTC, waffle87 approved these changes

2023-03-15 16:53 UTC, merged