Add new keymap for hotdox76v2
qmk/qmk_firmware pull request #20016
Opened 2023-03-04 21:01 UTC by dancxjo

## Description

Adds my own personal keymap for the hotdox76v2 based on [Arno's Engram layout](http://engram.dev). It also overrides the display to include modifiers and locks.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-10 08:54 UTC, drashna requested changes

2023-03-21 19:23 UTC, dancxjo commented on keyboards/hotdox76v2/keymaps/dancxjo/keymap.c
> +
Don't I need to include this to use it use `keymap_config.swap_lctl_lgui` ?

2023-03-23 06:21 UTC, drashna approved these changes

2023-04-02 18:00 UTC, waffle87 approved these changes

2023-04-02 18:01 UTC, merged