RF R1 8-9Xu PCB
qmk/qmk_firmware pull request #20048
Opened 2023-03-07 11:04 UTC by Cipulot

Addition of the RF R1 8-9Xu PCB firmware. Open source universal PCB for the Realforce R1 family of keyboards.
## Description

The RF R1 8-9Xu PCB is a replacement PCB for the Realforce R1 family of keyboards. All the layouts from the R1 series are supported in a single PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-07 11:18 UTC, keyboard-magpie requested changes

2023-03-07 11:18 UTC, keyboard-magpie commented on keyboards/cipulot/rf_r1_8_9xu/readme.md
> +![RF_R1_8-9Xu PCB](https://i.imgur.com/lyy5OPr.png)
```suggestion
![RF_R1_8-9Xu PCB](https://i.imgur.com/lyy5OPrh.png)
```
Same deal.

2023-03-07 11:18 UTC, keyboard-magpie commented on keyboards/cipulot/rf_r1_8_9xu/readme.md
> +    make rf_r1_8_9xu:default
```suggestion
    make cipulot/rf_r1_8_9xu:default
```
Presumably?

2023-03-07 11:18 UTC, keyboard-magpie commented on keyboards/cipulot/rf_r1_8_9xu/readme.md
> +    make rf_r1_8_9xu:default:flash
```suggestion
    make cipulot/rf_r1_8_9xu:default:flash
```
Yep.

2023-03-07 11:19 UTC, Cipulot commented on keyboards/cipulot/rf_r1_8_9xu/readme.md
> +    make rf_r1_8_9xu:default:flash
Overlook on my side. Changes applied 👍

2023-03-07 11:24 UTC, Cipulot commented on keyboards/cipulot/rf_r1_8_9xu/readme.md
> +![RF_R1_8-9Xu PCB](https://i.imgur.com/lyy5OPr.png)
Done 👍

2023-03-07 11:25 UTC, keyboard-magpie approved these changes

2023-03-10 11:53 UTC, drashna commented on keyboards/cipulot/rf_r1_8_9xu/rules.mk
> +SRC += analog.c matrix.c ec_switch_matrix.c
```suggestion
QUANTUM_LIB_SRC += analog.c 
SRC += matrix.c ec_switch_matrix.c
```

2023-03-10 12:20 UTC, Cipulot commented on keyboards/cipulot/rf_r1_8_9xu/rules.mk
> +SRC += analog.c matrix.c ec_switch_matrix.c
Done 👍

2023-03-11 03:24 UTC, drashna approved these changes

2023-03-14 07:41 UTC, merged