Move a_dux to data-driven
qmk/qmk_firmware pull request #20043
Opened 2023-03-07 02:21 UTC by filterpaper

## Description

* Move build settings into info.json
* Remove unsupported switch type locking support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-07 05:28 UTC, waffle87 commented on keyboards/a_dux/info.json
> +        },
```suggestion
```

2023-03-07 05:28 UTC, waffle87 approved these changes

2023-03-07 08:14 UTC, fauxpark requested changes

2023-03-07 08:14 UTC, fauxpark commented on keyboards/a_dux/info.json
> +    "pin_compatible": "promicro",
```suggestion
    "development_board": "promicro",
```

2023-04-07 04:14 UTC, fauxpark approved these changes

2023-04-07 04:27 UTC, merged