Add h87g2 files
qmk/qmk_firmware pull request #20053
Opened 2023-03-07 19:39 UTC by hineybush

## Description

Adding firmware for my new "Gen 2" h87, which is STM32-based

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-07 21:03 UTC, waffle87 requested changes
There are also submodule commits that need to be reverted. This [doc](https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch) may help.

2023-03-07 21:03 UTC, waffle87 commented on keyboards/hineybush/h87_g2/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
This file is missing a license header.
eg.
```
// Copyright 2023 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-03-07 21:03 UTC, waffle87 commented on keyboards/hineybush/h87_g2/info.json
> +        "LAYOUT_all": {
This change will also need to be reflected in the keymaps.
```suggestion
        "LAYOUT": {
```

2023-03-07 21:03 UTC, waffle87 commented on keyboards/hineybush/h87_g2/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
These fields should be filled out.

2023-03-07 23:44 UTC, zvecr commented on keyboards/hineybush/h87_g2/keymaps/default/keymap.c
> +// SPDX-License-Identifier: GPL-2.0-or-later
```suggestion
// Copyright 2023 Josh Hinnebusch
// SPDX-License-Identifier: GPL-2.0-or-later
#include QMK_KEYBOARD_H
```

2023-03-11 02:14 UTC, drashna commented on keyboards/hineybush/h87_g2/readme.md
> +[h87_g2](https://i.imgur.com/t7chDf8.png)
```suggestion
[h87_g2](https://i.imgur.com/t7chDf8h.png)
```

2023-03-11 02:14 UTC, drashna approved these changes

2023-03-15 16:42 UTC, waffle87 commented on keyboards/hineybush/h87_g2/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
```suggestion
* Hardware Supported: H87 G2 PCB w/ STM32F072 MCU
* Hardware Availability: [hineybush.com](https://hineybush.com)
```

2023-03-15 16:43 UTC, merged