Make Pointing Device Auto Layer more configurable
qmk/qmk_firmware pull request #20061
Opened 2023-03-08 09:34 UTC by drashna

## Description

As the title says. 

Specifically make the layer timeout and debouncing configurable at runtime.

## Types of Changes

- [x] Core
- [x] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* Discord comments in bastardkb #firmware channel

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-08 11:06 UTC, Alabastard-64 commented
Thanks Drashna I was planning on coming back to this soon to add something
similar but I was also wondering about adding a configurable threshold for
movement as well rather than a simple check for non zero values.

I have had issues with my cursor "vibrating" and activating the automouse
layer if I type a bit too aggressively.

On Wed., Mar. 8, 2023, 03:34 Drashna Jaelre, ***@***.***>
wrote:

> Description
>
> As the title says.
>
> Specifically make the layer timeout and debouncing configurable at runtime.
> Types of Changes
>
>    - Core
>    - Enhancement/optimization
>    - Documentation
>
> Issues Fixed or Closed by This PR
>
>    - Discord comments in bastardkb #firmware channel
>
> Checklist
>
>    - My code follows the code style of this project: *C*
>    <https://docs.qmk.fm/#/coding_conventions_c>, *Python*
>    <https://docs.qmk.fm/#/coding_conventions_python>
>    - I have read the *PR Checklist* document
>    <https://docs.qmk.fm/#/pr_checklist> and have made the appropriate
>    changes.
>    - My change requires a change to the documentation.
>    - I have updated the documentation accordingly.
>    - I have read the *CONTRIBUTING* document
>    <https://docs.qmk.fm/#/contributing>.
>    - I have added tests to cover my changes.
>    - I have tested the changes and verified that they work and don't
>    break anything (as well as I can manage).
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/qmk/qmk_firmware/pull/20061
> Commit Summary
>
>    - 1e09504
>    <https://github.com/qmk/qmk_firmware/pull/20061/commits/1e095040db259de8cf396584098fbcb6ddaeb191>
>    Make Pointing Device Auto Layer more configurable
>
> File Changes
>
> (3 files <https://github.com/qmk/qmk_firmware/pull/20061/files>)
>
>    - *M* docs/feature_pointing_device.md
>    <https://github.com/qmk/qmk_firmware/pull/20061/files#diff-7080a07adbb90120aeb1030beeb37025784ed0784b1b90147385b152fa7b169a>
>    (4)
>    - *M* quantum/pointing_device/pointing_device_auto_mouse.c
>    <https://github.com/qmk/qmk_firmware/pull/20061/files#diff-bf09b1ae7a62309f851d8b26d1e7cd96bc09ae535aa058382e1d2b4c161d90dd>
>    (50)
>    - *M* quantum/pointing_device/pointing_device_auto_mouse.h
>    <https://github.com/qmk/qmk_firmware/pull/20061/files#diff-b6b9a06ef92a8c80365993eb1fda9bf65d69d15e239a72a8409c275ee33f4e28>
>    (10)
>
> Patch Links:
>
>    - https://github.com/qmk/qmk_firmware/pull/20061.patch
>    - https://github.com/qmk/qmk_firmware/pull/20061.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qmk/qmk_firmware/pull/20061>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW7FCGQ3Q2LVOMQXOIQVKPLW3BHDPANCNFSM6AAAAAAVTREATQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-03-08 17:42 UTC, drashna commented
I've not experienced that. But might be worth handling that in a generic manner, in the main code as some sort of cursor smoothing option.

2023-03-16 12:54 UTC, tzarc requested changes

2023-03-16 12:54 UTC, tzarc commented on quantum/pointing_device/pointing_device_auto_mouse.c
> +    .config.debounce = (uint8_t)AUTO_MOUSE_DEBOUNCE,
```suggestion
    .config.layer    = (uint8_t)(AUTO_MOUSE_DEFAULT_LAYER),
    .config.timeout  = (uint16_t)(AUTO_MOUSE_TIME),
    .config.debounce = (uint8_t)(AUTO_MOUSE_DEBOUNCE),
```

2023-03-17 02:57 UTC, tzarc commented on quantum/pointing_device/pointing_device_auto_mouse.c
> +    .config.debounce = (uint8_t)AUTO_MOUSE_DEBOUNCE,
Seemed to revert these in the force-push.

2023-04-12 21:28 UTC, elpekenin commented on docs/feature_pointing_device.md
> +| `get_auto_mouse_debounce(void)`                            | Return the current debounce for preventing layer activation                          |                           |      `uint8_t` |
Mis-aligned
```suggestion
| `get_auto_mouse_debounce(void)`                            | Return the current debounce for preventing layer activation                          |                           |       `uint8_t` |
```

2023-05-06 06:50 UTC, tzarc approved these changes

2023-05-06 13:38 UTC, merged