[Keyboard] Add KP60
qmk/qmk_firmware pull request #20096
Opened 2023-03-12 04:32 UTC by d-floe

## Description

KP60 is a hotswap multi-layout GH60 PCB. Includes Default and VIA keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-12 05:57 UTC, adophoxia requested changes

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/kp60.h
> +}
```suggestion

```
Should be moved to `info.json`.

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/info.json
> +    "bootloader": "atmel-dfu",
```suggestion
    "bootloader": "atmel-dfu",
    "diode_direction": "COL2ROW",
    "matrix_pins": {
        "cols": ["F4", "F1", "D5", "F6", "F5"],
        "rows": ["B0", "B1", "B2", "B6", "F7", "D0", "D1", "D2", "D3", "B5", "B4", "D7", "D6", "D4"]
    },
    "features": {
        "bootmagic": true,
        "mousekey": true,
        "extrakey": true,
        "console": false,
        "command": false,
        "nkro": true,
        "backlight": false,
        "rgblight": true,
        "audio": false,
    },
    "rgblight": {
        "pin": "F0",
        "led_count": 8,
        "hue_steps": 8,
        "saturation_steps": 8,
        "brightness_steps": 8,
        "max_brightness": 255,
        "animations": {
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
        }
    },
```

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/config.h
> +#define DIODE_DIRECTION COL2ROW
```suggestion

```
This should be moved to `info.json`.

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/readme.md
> +![Keyspensory KP60 PCB](https://i.imgur.com/3Ob0bp9.png)
```suggestion
![Keyspensory KP60 PCB](https://i.imgur.com/3Ob0bp9h.png)
```
As per the [`PR Checklist`](https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs):
> * if imgur is used, images should be resized appropriately: append “h” to the image url i.e. https://i.imgur.com/vqgE7Ok.jpg becomes https://i.imgur.com/vqgE7Okh.jpg

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/readme.md
> +For reset instruction, use the physical reset button on the back of the keyboard to enter bootloader mode
```suggestion
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/rules.mk
> +NO_USB_STARTUP_CHECK = yes
```suggestion
This file is left intentionally blank.
```
Everything inside should be moved to `info.json`.

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/info.json
> +        "device_version": "0.0.1"
```suggestion
        "device_version": "0.0.1"
        "no_startup_check": true,
        "force_nkro": true,
```

2023-03-12 05:57 UTC, adophoxia commented on keyboards/keyspensory/kp60/config.h
> +#endif
```suggestion

```
Should be moved to `info.json`.

2023-03-12 07:31 UTC, d-floe commented
I cant get a definitive answer why my keymap's are not being accepted by PR Lint. I ran them through jsonlint.com and the formatting SHOULD be correct unless I'm somehow missing something

2023-03-13 03:18 UTC, adophoxia approved these changes

2023-03-13 03:34 UTC, waffle87 commented on keyboards/keyspensory/kp60/readme.md
> +    make keyspensory/kp60:default
```suggestion
![Keyspensory KP60 PCB](https://i.imgur.com/3Ob0bp9h.png)

* Keyboard Maintainer: [Freather](https://github.com/CMMS-Freather), [d-floe](https://github.com/d-floe)
* Hardware Supported: PCB, Atmega32u4

Make example for this keyboard (after setting up your build environment):

    make keyspensory/kp60:default

Flashing example for this keyboard:

    make keyspensory/kp60:default:flash
```

2023-03-13 19:30 UTC, waffle87 approved these changes

2023-03-14 01:33 UTC, fauxpark approved these changes

2023-03-14 19:56 UTC, drashna approved these changes

2023-03-14 19:56 UTC, merged