Consolidate Binepad BN009 R1 and R2 into common folder
qmk/qmk_firmware pull request #20113
Opened 2023-03-13 12:05 UTC by vinorodrigues

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-13 12:13 UTC, fauxpark requested changes

2023-03-13 12:13 UTC, fauxpark commented on keyboards/binepad/bn009/readme.md
> +*A 9% macropad.*
```suggestion
A 9% macropad.
```

2023-03-13 12:13 UTC, fauxpark commented on keyboards/binepad/bn009/r1/config.h
> +#define LOCKING_SUPPORT_ENABLE
Considering this is a macropad, these are probably not that useful.

2023-03-13 12:13 UTC, fauxpark commented on keyboards/binepad/bn009/r1/Info.json
> +{
Filename should be lowercase.

2023-03-17 17:14 UTC, drashna approved these changes

2023-03-17 22:42 UTC, fauxpark approved these changes

2023-03-21 05:13 UTC, merged