momokai tap_* rgb modes and bootmagic key update
qmk/qmk_firmware pull request #20126
Opened 2023-03-15 07:32 UTC by peepeetee

updated momokai/tap_* RGB modes, and changed bootmagic key for tap_duo to the lower middle key.
amended readme.md for tap_duo

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-15 16:11 UTC, waffle87 commented on keyboards/momokai/tap_duo/config.h
This belongs in `info.json` as
```json
"bootmagic": {
    "matrix": [0, 3]
}```
```suggestion
```

2023-03-21 06:07 UTC, drashna approved these changes

2023-04-03 05:14 UTC, tzarc requested changes

2023-04-03 05:14 UTC, tzarc commented on keyboards/momokai/tap_duo/info.json
You're marked as maintainer in the `readme.md`, can you please update it here too?
Same for `tap_trio`'s `info.json`.

2023-04-03 05:24 UTC, peepeetee commented on keyboards/momokai/tap_duo/info.json
Nice catch. Updated

2023-05-13 06:18 UTC, waffle87 approved these changes

2023-05-13 06:19 UTC, merged