Add Royal Kludge RKG-68
qmk/qmk_firmware pull request #20138
Opened 2023-03-16 02:09 UTC by Thomaz-Peres

## Description

Create keyboard map for Royal Kludge RK0-G68

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-16 03:09 UTC, zvecr requested changes

2023-03-16 03:09 UTC, zvecr commented on keyboards/rkg68/info.json
> +    "layouts": {
```suggestion
    "matrix_pins": {
        "cols": ["F0", "F1", "E6", "C7", "C6", "B6", "D4", "B1", "B7", "B5", "B4", "D7", "D6", "B3", "F4"],
        "rows": ["D0", "D1", "D2", "D3", "D5"]
    },
    "diode_direction": "COL2ROW",
    "layouts": {
```

2023-03-16 03:09 UTC, zvecr commented on keyboards/rkg68/info.json
> +	},
Copying in `qmk info` content is wrong here, as api specific content should not exist in the repo

2023-03-16 03:09 UTC, zvecr commented on keyboards/rkg68/info.json
> +		"platform_key": "avr",
```suggestion
```

2023-03-16 03:09 UTC, zvecr commented on keyboards/rkg68/info.json
> +		"processor_type": "avr",
```suggestion
```

2023-03-16 03:09 UTC, zvecr commented on keyboards/rkg68/info.json
> +	"keyboard_folder": "rkg68",
```suggestion
```

2023-03-21 06:28 UTC, drashna requested changes

2023-03-21 06:28 UTC, drashna commented on keyboards/rkg68/readme.md
> +![Keyboard picture](https://imgur.com/UnOJPZr.jpg)
```suggestion
![Keyboard picture](https://imgur.com/UnOJPZrh.jpg)
```

2023-03-21 06:28 UTC, drashna commented on keyboards/rkg68/readme.md
> +![image](https://user-images.githubusercontent.com/58439854/225489922-a6a4df65-aff7-4835-a452-3b1afdb6fc15.png)
Please rehost this image on Imgur.

2023-03-23 05:23 UTC, drashna approved these changes

2023-03-23 05:55 UTC, zvecr requested changes

2023-03-23 05:55 UTC, zvecr commented on keyboards/rkg68/readme.md
> +---
```suggestion
```

2023-03-23 05:55 UTC, zvecr commented on keyboards/rkg68/readme.md
> +
```suggestion
```

2023-03-23 05:55 UTC, zvecr commented on keyboards/rkg68/info.json
> +	},
```suggestion
```

2023-03-23 05:55 UTC, zvecr commented on keyboards/rkg68/info.json
> +		"encoder": false
```suggestion
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true
```

2023-03-23 05:55 UTC, zvecr commented on keyboards/rkg68/info.json
> +		"saturation_steps": 17
```suggestion
		"led_count": 4,
		"pin": "B3"
```

2023-03-24 14:47 UTC, fauxpark requested changes

2023-03-24 14:47 UTC, fauxpark commented on keyboards/rkg68/info.json
> +				{"matrix": [0, 0], "x": 0, "y": 0.0},
```suggestion
				{"matrix": [0, 0], "x": 0, "y": 0},
```
etc

2023-03-29 20:26 UTC, drashna approved these changes

2023-04-02 17:48 UTC, waffle87 approved these changes

2023-04-02 17:49 UTC, merged

2023-12-23 18:04 UTC, darknblack commented
Hi @Thomaz-Peres, 

I have RKG68 and my keyboard layout matches exactly from the one on the readme.md, however my keyboard has different PID (00E7). Do you think flashing it by simply changing the PID from the `info.json` will do? If not maybe you could guide me or at least provide images of the board you have. I will really appreciate your help. 

Thank you so much

2023-12-23 22:53 UTC, Thomaz-Peres commented
Hello @darknblack.

In response to your question, if you update the info.json file with the PID, it will probably work (make sure to check the bootloader, processor, and the VID as well).
If it doesn’t work, and you want, we can discuss this on QMK Discord. 
If your solution works, you can submit a PR to update the PID, and if there’s more new information, you can update that too.

##### Why PID is different ?
This is because (If I’m not mistaken), RoyalKludge updated the RKG68 with new PCBs. (I really struggled to find information about the old one).

**NOTE**: It’s been a few months since I last read about keyboards, so some of the information I provide might be incorrect (apologies in advance)

2023-12-24 05:53 UTC, darknblack commented
Hi @Thomaz-Peres,

> (make sure to check the bootloader, processor, and the VID as well)
Is there a way to know the bootloader without opening the keyboard?

Here's the device info from Device Manager:
`Device HID\VID_258A&PID_00E7&MI_00\b&110c8674&0&0000 was configured.`

QMK Toolbox:
`USB device connected (HidUsb): (Standard system devices) USB Input Device (258A:00E7:1007)`

Thank you so much for your help 🙇 🤞

2023-12-24 08:31 UTC, HorrorTroll commented
> Here's the device info from Device Manager: `Device HID\VID_258A&PID_00E7&MI_00\b&110c8674&0&0000 was configured.`
> 
> QMK Toolbox: `USB device connected (HidUsb): (Standard system devices) USB Input Device (258A:00E7:1007)`

If the keyboard support bluetooth, it mean the MCU is not supported for QMK. Since official QMK was never supported wireless.

2023-12-24 09:19 UTC, darknblack commented
Hi @HorrorTroll

> If the keyboard support bluetooth, it mean the MCU is not supported for QMK. Since official QMK was never supported wireless.

Does that mean QMK will not work in general for keyboards with Bluetooth feature? Or you can still flash the firmware but it will only work on wired mode? Thank you

2023-12-28 19:53 UTC, Thomaz-Peres commented
@darknblack, I'm not familiar with these new RK versions, but typically, you can accomplish this using a macro (in the oldest version, I used fn+shift+b or fn+shift+enter for 3 seconds, although I don't remember exactly). Therefore, you can update the VID and the PID with the Device Manager you've provided.

@HorrorTroll, but does using the USB work, right? I don't recall reading anything about it; I understood that only when using the keyboard as Bluetooth it would not work. If you have a link to read about this, please share.

2023-12-29 06:41 UTC, HorrorTroll commented
> Does that mean QMK will not work in general for keyboards with Bluetooth feature? Or you can still flash the firmware but it will only work on wired mode? Thank you
> But does using the USB work, right? I don't recall reading anything about it; I understood that only when using the keyboard as Bluetooth it would not work. If you have a link to read about this, please share.

Sorry for late reply to you guys. As I recall that RK and other company are order the OEM PCB directly from Evision/HFD or other manufacturer for wireless support. Those company are using like Sonix SN32F248B, CH555 or SH68F90 at the main MCU. Even trying to port QMK and use only wired is not really possible.

At for the Sonix SN32F248B, it kinda really on old PCB. So I don't know if RK are even have those anymore. But luckily that these chip are having community port QMK on it. It called SonixQMK.

While CH555 and SH68F90 are Intel 8051 (8-bit Enhanced customize) architecture, so yeah. It not possible to do that anyway.

2023-12-29 08:18 UTC, Thomaz-Peres commented
That's nice, I found the repository here! I will do some tests to see if it works.

And thank you very much, I really didn't know about that; probably because of this, I've had many problems!

2024-01-03 02:58 UTC, darknblack commented
Hello, I recently opened up my keyboard to install new switches, and I discovered that it uses the following chip:

`BYK916-00997A NRW37-1 2203-D`

I'm not sure if this chip is currently supported. Could someone please confirm this? Thank you

2024-01-03 03:15 UTC, fauxpark commented
BYK916 is 8051 architecture. You will not be able to run QMK on this.

2024-05-11 09:34 UTC, karror commented
Hello @Thomaz-Peres! Thank you for your job for community! I know that was a while when these thread was alive, but i want to know if You had some success on flashing rkg68 with this firmware. I ask, because I found it on production in qmk compiler list of keyboards. My issue is that, I bought "rk61 plus" which have this "amazing" chip byk916, and i find out that rkg68 is based on the same family from sinowealth. Thats [here](https://github.com/carlossless/sinowealth-kb-tool?tab=readme-ov-file#keyboards). It's also have bluetooth and 2.4G interfaces. I wondering that, if your firmware is working, could that be, your driver will handle also byk916 (SH68F90A) of "rk61 plus"?

2024-05-11 13:05 UTC, fauxpark commented
QMK will not run on this board or MCU. Please read what I have posted above.