Add my handwired keyboard 2d4d
qmk/qmk_firmware pull request #20133
Opened 2023-03-15 20:13 UTC by mechmehmet

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-15 20:40 UTC, waffle87 commented
Unsure why you closed #20105 , but the suggestions I made still need to be applied.
* Everything in `config.h` file needs to be migrated to `info.json` file, as per the [PR checklist](https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs). See [info.json reference](https://docs.qmk.fm/#/reference_info_json) as well.
* The layout macro in `2d4d.h` file also needs to be migrated to `info.json`. That file can then be deleted.
* Basic encoder functionality needs to exist in `2d4d.c` file. See [doc](https://docs.qmk.fm/#/feature_encoders?id=callbacks).

You can use `qmk info -f json -kb  handwired/2d4d` to help automate some of this.

2023-03-15 21:11 UTC, mechmehmet commented
Thanks for your help, but why didnt you read my comments, I have not a basic encoder func on keymap and if you look at the doc, it says you can use on keymap with return false. Can you check my keymap for encoder func and layer_state_t function; case 6. I cannot use in c file, how could I use.

2023-03-15 22:18 UTC, mechmehmet commented
@waffle87 I merge all files to info.json, but you can tell me: "we aimed to use info.json instead of struggle with other files". At the end of 3 hours, I could only understand what was wrong. When I compare the old projects, nothing is understood, because I already did it by taking examples from the projects.

2023-03-15 22:46 UTC, waffle87 requested changes

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/info.json
> +    },
```suggestion
```

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/info.json
> +        "enabled": true,
```suggestion
    "features": {
        "encoder": true,
        "extrakey": true,
        "mousekey": true
    },
    "diode_direction": "COL2ROW",
    "encoder": {
```

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/info.json
> +            "json_layout": false,
```suggestion
    "matrix_pins": {
        "cols": ["B12", "B13", "B14", "B15", "A8", "A15"],
        "rows": ["B3", "B4", "B5", "B6", "A2", "A3", "A4", "A5"]
    },
    "processor": "STM32F401",
    "layouts": {
        "LAYOUT_8x6": {
```

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/keymaps/default/keymap.c
> +
```suggestion
    SHUT = QK_USER
```

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/config.h
> +//#define NO_ACTION_ONESHOT
```suggestion
/* Mechanical locking support. Use KC_LCAP, KC_LNUM or KC_LSCR instead in keymap */
#define LOCKING_SUPPORT_ENABLE
/* Locking resynchronize hack */
#define LOCKING_RESYNC_ENABLE

#define ledGreen B0
#define ledBlue  B1
#define ledRed   B10
#define ledWhite B9
```

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/keymaps/default/keymap.c
> +    }
```suggestion
    writePin(ledWhite, !led_state.caps_lock);
```

2023-03-15 22:46 UTC, waffle87 commented on keyboards/handwired/2d4d/rules.mk
> +
```suggestion
# This file intentionally left blank
```

2023-03-21 06:26 UTC, drashna requested changes

2023-03-21 06:26 UTC, drashna commented on keyboards/handwired/2d4d/info.json
> +    "processor": "STM32F401",
```suggestion
```

2023-03-21 06:26 UTC, drashna commented on keyboards/handwired/2d4d/info.json
> +    "bootloader": "stm32-dfu",
```suggestion
    "development_board": "blackpill_f401",
```

2023-03-21 06:26 UTC, drashna commented on keyboards/handwired/2d4d/keymaps/default/keymap.c
In general, we want the default keymap to be simple and clean.  Additional stuff should go into a separate keymap.

2023-03-21 06:26 UTC, drashna commented on keyboards/handwired/2d4d/readme.md
> +![2d4d_2](https://i.imgur.com/IfoQUnc.jpg)
```suggestion
![2d4d](https://i.imgur.com/famGFG8h.jpg)

![2d4d_2](https://i.imgur.com/IfoQUnch.jpg)
```

2023-03-23 07:24 UTC, drashna commented on keyboards/handwired/2d4d/keymaps/default/keymap.c
`layer_state_set_kb`.

Also, moving all the more complicated stuff to a different (non-default) keymap would be fine.

2023-04-02 17:59 UTC, waffle87 commented on keyboards/handwired/2d4d/info.json
> +        "encoder": true,
If encoders are enabled at the keyboard level, there needs to be some keyboard level encoder functionality as well. See [doc](https://docs.qmk.fm/#/feature_encoders?id=callbacks).

2023-04-02 17:59 UTC, waffle87 commented on keyboards/handwired/2d4d/keymaps/default/keymap.c
> +bool led_update_kb(led_t led_state) {
```suggestion
bool led_update_user(led_t led_state) {
```

2023-07-03 02:10 UTC, closed without merging