add via firmware support
qmk/qmk_firmware pull request #20146
Opened 2023-03-16 12:34 UTC by jotix

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-16 17:03 UTC, waffle87 requested changes

2023-03-16 17:03 UTC, waffle87 commented on keyboards/handwired/jotanck/keymaps/via/keymap.c
> +#define _ADJUST   3
```suggestion
enum layers {
    _QWERTY,
    _LOWER,
    _RAISE,
    _ADJUST
};
```

2023-03-16 17:03 UTC, waffle87 commented on keyboards/handwired/jotanck/keymaps/via/rules.mk
> +BOOTMAGIC_ENABLE = yes
This is conditionally enabled when VIA is enabled.
```suggestion
```

2023-03-16 20:24 UTC, waffle87 approved these changes

2023-03-21 06:43 UTC, drashna requested changes

2023-03-21 06:43 UTC, drashna commented on keyboards/handwired/jotanck/keymaps/via/keymap.c
> +    KC_LCTL, KC_LGUI, KC_LALT, KC_RALT, LOWER,   KC_SPC,  KC_SPC,  RAISE,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT
```suggestion
    KC_LCTL, KC_LGUI, KC_LALT, KC_RALT, TL_LOWR, KC_SPC,  KC_SPC,  TL_UPPR, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT
```

2023-03-21 06:43 UTC, drashna commented on keyboards/handwired/jotanck/keymaps/via/keymap.c
> +#define RAISE MO(_RAISE)
```suggestion
```

2023-03-23 04:36 UTC, drashna approved these changes

2023-03-23 04:38 UTC, merged