refactor: keebio/bamfk1
qmk/qmk_firmware pull request #20162
Opened 2023-03-17 18:25 UTC by lesshonor

## Description

- Migration to standard encoder callback/map functionality instead of `action_exec` on "extra keys".
- Data-driven migration for other attributes.
- Broken Shopify image replaced and bootloader instructions improved.
- ~~:warning: Enabled tri-layers on the `via` keymap, since it uses `TL_LOWR`.~~
- :warning: Mousekeys have been enabled at the keyboard level for Configurator users. This wasn't possible on the `via` keymap for size reasons.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-17 18:49 UTC, zvecr requested changes
The issue with this, is that it will break via compatibility,

1. updating via config file will break existing firmware
2. flashing this without the updated config will also fall over 

Previously this has been handled by updating the product ID so that it stops `1` above.

2023-03-17 18:49 UTC, zvecr commented on keyboards/keebio/bamfk1/keymaps/via/rules.mk
> +TRI_LAYER_ENABLE = yes
This is enabled when via, so is pointless
```suggestion
```

2023-03-17 18:49 UTC, zvecr commented on keyboards/keebio/bamfk1/keymaps/via/rules.mk
> +MOUSEKEY_ENABLE = no
Its generally wise to keep this enabled where possible, and trim firmware size elsewhere
```suggestion
```

2023-03-17 18:49 UTC, zvecr commented on keyboards/keebio/bamfk1/info.json
> +        "console": true,
```suggestion
        "console": false,
```

2023-04-25 03:30 UTC, closed without merging

2023-05-03 02:38 UTC, nooges commented
@lesshonor Sorry I didn't see this earlier, I have all my QMK GitHub emails filtered to a different folder since I get a ton of them as a contributor. I'm okay if you want to change the PID for the BAMFK-1 and adjust whatever is needed, followed by a "Rev. 1a" VIA definition .json. If you do open a new PR, please ping me on Discord with a link for review, but I have also tried adjusting my email filter settings to try to capture GitHub mentions of my username.

2024-03-07 17:24 UTC, nooges commented
I've created a new PR for the migration to encoder map and RGB matrix now: https://github.com/qmk/qmk_firmware/pull/23236