[Keyboard] Add pocketpad
qmk/qmk_firmware pull request #20229
Opened 2023-03-22 16:49 UTC by butterkeebs

## Description

Added the ButterKeebs PocketPad folder and relevant files

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-22 17:00 UTC, waffle87 requested changes

2023-03-22 17:00 UTC, waffle87 commented on keyboards/butterkeebs/pocketpad/info.json
> +    "keymaps": {},
```suggestion
```

2023-03-22 17:00 UTC, waffle87 commented on keyboards/butterkeebs/pocketpad/info.json
> +
```suggestion
```

2023-03-22 17:50 UTC, butterkeebs commented
Folder ButterKeebs/PocketPad has been renamed to butterkeebs/pocketpad to comply with naming scheme

2023-03-22 18:18 UTC, waffle87 requested changes
The directory name(s) should also be all lowercase, as per the PR checklist.
Lint check is also failing.

2023-03-22 18:22 UTC, butterkeebs commented
> The directory name(s) should also be all lowercase, as per the PR checklist. Lint check is also failing.

The directories are now lowercase? What is lint check?

2023-03-22 18:26 UTC, waffle87 commented
You've split up the directories...
There's [`keyboards/ButterKeebs/PocketPad`](https://github.com/butterkeebs/qmk_firmware/tree/master/keyboards/ButterKeebs/PocketPad) and [`keyboards/butterkeebs/pocketpad`](https://github.com/butterkeebs/qmk_firmware/tree/master/keyboards/butterkeebs/pocketpad).

2023-03-22 19:12 UTC, waffle87 approved these changes

2023-03-22 20:54 UTC, zvecr commented
`readme.md` (following <https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md>) is currently considered mandatory.

2023-03-23 07:33 UTC, drashna approved these changes

2023-03-23 07:33 UTC, drashna requested changes
readme is needed.

2023-03-23 17:23 UTC, zvecr requested changes

2023-03-23 17:23 UTC, zvecr commented on keyboards/butterkeebs/pocketpad/readme.md
> +<h1> PocketPad </h1>
This does not follow the template that was linked

2023-04-02 17:49 UTC, waffle87 approved these changes

2023-04-02 17:50 UTC, merged