update to data driven - superseeds part of https://github.com/qmk/qmk…
qmk/qmk_firmware pull request #20220
Opened 2023-03-22 06:01 UTC by alinelena

…_firmware/pull/18468

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-22 06:06 UTC, alinelena commented
this was reviewed in #18468

2023-07-04 04:01 UTC, drashna requested changes

2023-07-04 04:01 UTC, drashna commented on keyboards/mlego/m65/rev1/info.json
> +    },
```suggestion
        "saturation_steps": 8
    },
    "ws2812": {
        "pin": "B15"
    },
```

2023-07-04 06:49 UTC, alinelena commented on keyboards/mlego/m65/m65.c
> +bool process_record_user(uint16_t keycode, keyrecord_t* record) {
done

2023-07-04 06:51 UTC, alinelena commented on keyboards/mlego/m65/m65.c
> +layer_state_t layer_state_set_user(layer_state_t state) {
done

2023-07-05 01:09 UTC, fauxpark requested changes

2023-07-05 01:09 UTC, fauxpark commented on keyboards/mlego/m65/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-05 01:09 UTC, fauxpark commented on keyboards/mlego/m65/keymaps/uk/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-06 01:09 UTC, fauxpark requested changes

2023-07-11 15:53 UTC, drashna commented on keyboards/mlego/m65/m65.c
> +bool led_update_kb(led_t led_state) {
All of these functions need to call the user version, somewhere.

2023-08-26 06:04 UTC, fauxpark requested changes
Please run `qmk format-json` on all info.json files.

2023-08-29 10:01 UTC, alinelena commented
> Please run `qmk format-json` on all info.json files.

done, thank you!

2023-08-29 23:34 UTC, drashna requested changes

2023-08-29 23:34 UTC, drashna commented on keyboards/mlego/m65/rev2/info.json
> +    "debounce": 5,
```suggestion
```

2023-08-29 23:34 UTC, drashna commented on keyboards/mlego/m65/rev3/info.json
> +    "debounce": 5,
```suggestion
```

2023-08-29 23:34 UTC, drashna commented on keyboards/mlego/m65/rev4/info.json
> +    "debounce": 5,
```suggestion
```

2023-08-29 23:34 UTC, drashna commented on keyboards/mlego/m65/rev4/rules.mk
> +OLED_DRIVER = SSD1306      # Enable Support for SSD1306 or SH1106 OLED Displays; Communicating over I2C
This is the default, and should be removed.
```suggestion
```

2023-09-21 02:46 UTC, drashna reviewed
CI is reporting an unterminated ifdef, but it's hard to see it in all the changes here.

2023-09-25 13:15 UTC, alinelena commented
> CI is reporting an unterminated ifdef, but it's hard to see it in all the changes here.
> 
> Ah, introduced here: [63063a4](https://github.com/qmk/qmk_firmware/commit/63063a494308358607f22f8cc4d4c210ef79debd)

done thank you! too eager on dd

2023-09-25 13:16 UTC, alinelena commented
> Please run `qmk format-json` on all info.json files.

done!

2023-09-26 01:39 UTC, drashna approved these changes

2023-10-06 05:43 UTC, fauxpark approved these changes

2023-10-12 05:24 UTC, drashna approved these changes

2023-10-12 05:26 UTC, merged