update mlego/m60 to data driven
qmk/qmk_firmware pull request #20223
Opened 2023-03-22 07:09 UTC by alinelena

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-29 18:47 UTC, drashna approved these changes

2023-04-03 05:43 UTC, tzarc requested changes

2023-04-03 05:43 UTC, tzarc commented on keyboards/mlego/m48/config.h
Delete this file.

2023-04-03 08:00 UTC, alinelena commented on keyboards/mlego/m48/config.h
done thank you!

2023-04-03 08:21 UTC, fauxpark commented
As of #20323 data-driven keyboard refactors should target `develop`.

2023-04-03 10:00 UTC, fauxpark commented on keyboards/mlego/m48/rev1/info.json
> +            }
```suggestion
            {"pin_a": "A0", "pin_b": "B8"}
```

`qmk format-json` should help here.

2023-05-29 12:43 UTC, alinelena commented
I will reopen this when https://github.com/qmk/qmk_firmware/pull/20224 is merged

2023-05-29 12:43 UTC, closed without merging