add m4, small test board for various matrix styles
qmk/qmk_firmware pull request #20227
Opened 2023-03-22 09:01 UTC by alinelena

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-22 20:58 UTC, alinelena commented on keyboards/mlego/m4/rev2/info.json
> +    },
this is trickier since years ago this was the recommended method.. also not caps_lock is used as capslock

2023-03-23 12:47 UTC, alinelena commented on keyboards/mlego/m4/rev2/info.json
> +    },
i came out with a solution, I think is correct since it works.

2023-07-04 03:34 UTC, drashna requested changes

2023-07-04 03:34 UTC, drashna commented on keyboards/mlego/m4/keymaps/default/config.h
> +#define TAPPING_TOGGLE 2
```suggestion
#ppragma once

#define TAPPING_TOGGLE 2
```

2023-07-04 03:34 UTC, drashna commented on keyboards/mlego/m4/keymaps/default/keymap.c
default keymap should be kept plain and simple.

2023-07-04 03:34 UTC, drashna commented on keyboards/mlego/m4/m4.c
> +        user_oled_magic();
function isn't present here.

2023-07-04 03:34 UTC, drashna commented on keyboards/mlego/m4/rev2/config.h
> +#    define OLED_DISPLAY_128X32
is the default, shouldn't be needed.

2023-07-04 03:34 UTC, drashna commented on keyboards/mlego/m4/rev2/rules.mk
> +OLED_DRIVER = SSD1306      # Enable Support for SSD1306 or SH1106 OLED Displays; Communicating over I2C
is default, not needed here.
```suggestion
```

2023-07-04 07:52 UTC, alinelena commented on keyboards/mlego/m4/m4.c
> +        user_oled_magic();
thanks moved at the keymap level

2023-07-04 07:53 UTC, alinelena commented on keyboards/mlego/m4/rev2/config.h
> +#    define OLED_DISPLAY_128X32
done

2023-07-04 07:53 UTC, alinelena commented on keyboards/mlego/m4/keymaps/default/keymap.c
done

2023-10-05 04:43 UTC, drashna commented on keyboards/mlego/m4/rev2/config.h
> +#endif
```suggestion
#define I2C1_SCL_PIN GP7
#define I2C1_SDA_PIN GP6
#define I2C_DRIVER I2CD1
#define OLED_BRIGHTNESS 128
#define OLED_FONT_H "keyboards/mlego/m65/lib/glcdfont.c"
```

2023-10-13 08:58 UTC, alinelena commented
while I implemented the complete changes, the take on some elements moved to much and merged in another pr, I will close this and resubmit this one the mlego/m65 train is over.

2023-10-13 08:58 UTC, closed without merging