Add the KJ-Modify RS40 PCB keyboard
qmk/qmk_firmware pull request #20243
Opened 2023-03-23 16:25 UTC by AuditeMarlow

## Description

Add the KJ-Modify RS40 PCB keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-26 12:46 UTC, elpekenin requested changes

2023-03-26 12:46 UTC, elpekenin commented on keyboards/kj_modify/rs40/info.json
> +    "keyboard_name": "kj_modify/rs40",
```suggestion
    "keyboard_name": "rs40",
```

2023-03-26 12:46 UTC, elpekenin commented on keyboards/kj_modify/rs40/info.json
> +    "url": "",
I think this has to link to some source where to buy/build the keyboard, perhaps the one at `README/Hardware Availability`

2023-03-26 12:46 UTC, elpekenin commented on data/mappings/keyboard_aliases.hjson
> +    },
No idea if these aliases are only meant for backwards compatibility (when a board's files get moved into a new folder) or if they can be used in a "normal" scenario like this too

2023-03-26 13:11 UTC, elpekenin commented on keyboards/kj_modify/rs40/info.json
> +    "keyboard_name": "kj_modify/rs40",
I **think** it is okay

2023-03-28 06:06 UTC, waffle87 approved these changes

2023-04-02 08:59 UTC, drashna approved these changes

2023-04-02 09:00 UTC, merged