[keyboard] Add Plaque80 into QMK
qmk/qmk_firmware pull request #20240
Opened 2023-03-23 07:53 UTC by MaiTheSan

## Description
Add QMK support for PLAQUE PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-23 08:37 UTC, drashna requested changes

2023-03-23 08:37 UTC, drashna commented on keyboards/sawnsprojects/plaque80/info.json
> +        "max_brightness": 255,
```suggestion
```

2023-03-23 08:37 UTC, drashna commented on keyboards/sawnsprojects/plaque80/info.json
> +            "all": true
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2023-03-23 11:23 UTC, zvecr requested changes

2023-03-23 11:23 UTC, zvecr commented on keyboards/sawnsprojects/plaque80/info.json
> +        "led_count": 0,
Zero LEDs, either the rgblight config should be removed or this value corrected.

2023-03-23 11:23 UTC, zvecr commented on keyboards/sawnsprojects/plaque80/info.json
> +        "key_lock": false
```suggestion
        "rgblight": true
```

2023-03-29 19:16 UTC, drashna approved these changes

2023-03-29 19:34 UTC, waffle87 approved these changes

2023-03-29 19:34 UTC, merged