Adding my keymap
qmk/qmk_firmware pull request #20282
Opened 2023-03-28 19:55 UTC by Huguesmmm

I added a Keymap for a Planck that would work on Windows and MacOS (you need to change de layer manualy).

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* No issues

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-03-28 20:12 UTC, Huguesmmm commented
The QMK CI Build seem to have failed because of my initialisation of TAPPING_TOGGLE that is already declared in planck/ez/config.h

I need to define it because in the rev6 it is not defined. 

Should Ieave it like this or should I put a validation in my file that the variable is not define before making my initialisation?

2023-03-28 20:28 UTC, zvecr commented on keyboards/planck/keymaps/Huguesmmm/keymap_canadian_multilingual.h
> +// Copyright 2023 QMK
This file should be removed as its identical to the one provided in core

2023-03-29 19:14 UTC, waffle87 requested changes
The directory name also needs to be lowercase.

2023-03-29 19:14 UTC, waffle87 commented on keyboards/planck/keymaps/Huguesmmm/config.h
> +#pragma once
This file is missing a license header.

2023-03-29 19:14 UTC, waffle87 commented on keyboards/planck/keymaps/Huguesmmm/keymap.c
> +      state = update_tri_layer_state(state, _MACLOWER, _MACRAISE, _ADJUST2);
Something tells me this is the only value ever to be returned? The core [tri layer feature](https://docs.qmk.fm/#/feature_tri_layer) should be used instead.

2023-03-29 19:14 UTC, waffle87 commented on keyboards/planck/keymaps/Huguesmmm/readme.md
> +# The Default Planck Layout
This file should be removed.

2023-08-08 01:52 UTC, closed without merging