add keyboard cover65
qmk/qmk_firmware pull request #20384
Opened 2023-04-09 12:44 UTC by TW59420

## Description
MWStudio is a custom keyboard enthusiast
Add keyboard cover65 PCB

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-09 21:01 UTC, zvecr requested changes

2023-04-09 21:01 UTC, zvecr commented on keyboards/mwstudio/cover65/keymaps/via/keymap.c
> +void encoder_action_unregister(void) {
This code is no longer accepted to the repo, and <https://docs.qmk.fm/#/feature_encoders?id=encoder-map> has to be used instead.

2023-04-09 21:01 UTC, zvecr commented on keyboards/mwstudio/cover65/rules.mk
> +# DEFAULT_FOLDER = mwstudio/mw660/apm32f103
```suggestion
# This file intentionally left blank
```

2023-04-09 21:01 UTC, zvecr commented on keyboards/mwstudio/cover65/halconf.h
> +// #define HAL_USE_I2C TRUE
```suggestion
```

2023-04-09 21:01 UTC, zvecr requested changes

2023-04-09 21:01 UTC, zvecr commented on keyboards/mwstudio/cover65/config.h
> +#define DRIVER_LED_TOTAL 21
```suggestion
```

2023-05-12 06:24 UTC, TW59420 commented
@drashna Hi, Can you help me merge branches

2023-05-12 06:24 UTC, TW59420 commented
@drashna Hi, Can you help me merge branches

2023-07-06 01:59 UTC, TW59420 commented
@fauxpark and this, help me merge branches, thank you!

2023-07-11 15:57 UTC, drashna requested changes

2023-07-11 15:57 UTC, drashna commented on keyboards/mwstudio/cover65/config.h
> +#define WS2812_DMA_CHANNEL 2                  // DMA Channel for TIMx_UP, see the respective reference manual for the appropriate values for your MCU.
```suggestion
#define WS2812_PWM_DRIVER PWMD4
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 1
#define WS2812_DMA_STREAM STM32_DMA1_STREAM7
#define WS2812_DMA_CHANNEL 2
```

2023-07-11 15:57 UTC, drashna commented on keyboards/mwstudio/cover65/info.json
> +    "bootloader": "stm32duino",
This sets the processor, bootloader and board to f103+stm32duino
```suggestion
    "developmennt_board": "bluepill"
```

2023-07-11 15:57 UTC, drashna commented on keyboards/mwstudio/cover65/readme.md
> +![Cover65](https://github.com/TW59420/MWStudio/blob/e61bb0c59f3394ed859e408245a74ff30029079b/pcb_img/Cover65.png)
Please rehost this on Imgur, or the like.

2023-07-17 07:36 UTC, fauxpark requested changes

2023-07-17 07:36 UTC, fauxpark commented on keyboards/mwstudio/cover65/keymaps/via/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-17 08:05 UTC, fauxpark requested changes

2023-07-17 08:05 UTC, fauxpark commented on keyboards/mwstudio/cover65/readme.md
> +![Cover65](https://imgur.com/m1EFfOU)
```suggestion
![Cover65](https://i.imgur.com/m1EFfOU.png)
```
Needs to be a direct link.

2023-07-20 03:32 UTC, TW59420 commented on keyboards/mwstudio/cover65/readme.md
> +![Cover65](https://imgur.com/m1EFfOU)
thanks

2023-07-24 13:27 UTC, fauxpark requested changes

2023-07-24 13:27 UTC, fauxpark commented on keyboards/mwstudio/cover65/readme.md
> +Support STM32F103 keyboard..
```suggestion
Support STM32F103 keyboard.
```

2023-07-24 13:27 UTC, fauxpark commented on keyboards/mwstudio/cover65/readme.md
> +    make mwstudio/cover65:default
```suggestion
    make mwstudio/cover65:default
```

2023-07-24 13:27 UTC, fauxpark commented on keyboards/mwstudio/cover65/info.json
> +				{ "matrix": [0, 0], "x": 0, "y": 1 },
```suggestion
                { "matrix": [0, 0], "x": 0, "y": 1 },
```

2023-07-24 13:27 UTC, fauxpark commented on keyboards/mwstudio/cover65/info.json
> +		"rgblight": true
```suggestion
        "encoder": true,
        "rgblight": true
```

2023-07-26 08:32 UTC, fauxpark requested changes

2023-07-26 08:32 UTC, fauxpark commented on keyboards/mwstudio/cover65/readme.md
> +![Cover65](https://i.imgur.com/m1EFfOU.png)
```suggestion
![Cover65](https://i.imgur.com/m1EFfOUh.png)
```

2023-08-03 06:20 UTC, drashna approved these changes

2023-08-30 07:48 UTC, drashna requested changes

2023-08-30 07:48 UTC, drashna commented on keyboards/mwstudio/cover65/keymaps/default/keymap.c
> +	[0] = LAYOUT(
```suggestion
    [0] = LAYOUT(
```

2023-08-30 07:48 UTC, drashna commented on keyboards/mwstudio/cover65/keymaps/default/keymap.c
> +	[1] = LAYOUT(
```suggestion
    [1] = LAYOUT(
```

2023-08-30 07:48 UTC, drashna commented on keyboards/mwstudio/cover65/keymaps/via/keymap.c
> +	[0] = LAYOUT(
```suggestion
    [0] = LAYOUT(
```

2023-08-30 07:48 UTC, drashna commented on keyboards/mwstudio/cover65/keymaps/via/keymap.c
> +	[1] = LAYOUT(
```suggestion
    [1] = LAYOUT(
```

2023-08-30 07:48 UTC, drashna commented on keyboards/mwstudio/cover65/keymaps/via/keymap.c
> +    [1] =  { ENCODER_CCW_CW(RGB_HUD, RGB_HUI) },
```suggestion
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(RGB_HUD, RGB_HUI) },
```

2023-08-30 07:48 UTC, drashna commented on keyboards/mwstudio/cover65/keymaps/via/rules.mk
> +LTO_ENABLE = yes
Just a heads up, but you likely don't need LTO here, as it's mostly a space saving measure.

2023-09-21 03:09 UTC, drashna approved these changes

2023-11-11 19:24 UTC, drashna approved these changes

2023-11-20 13:23 UTC, dunk2k requested changes

2023-11-20 13:23 UTC, dunk2k commented on keyboards/mwstudio/cover65/keymaps/default/keymap.c
> +};
```suggestion
    [0] = LAYOUT_65_ansi_blocker(
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,     KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,     KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_PGUP,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,     KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGDN,
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,     KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_END,
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPACE,                            KC_RALT, MO(1),   KC_LEFT, KC_DOWN, KC_RIGHT
    ),

    [1] = LAYOUT_65_ansi_blocker(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______, RGB_HUI,
        RGB_TOG, _______, _______, _______, QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_HUD,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, RGB_SAI,
        _______,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_VAI, RGB_SAD,
        _______, _______, _______,                            _______,                            RGB_MOD, _______, RGB_SPD, RGB_VAD, RGB_SPI
    ),
};

```

2023-11-20 13:23 UTC, dunk2k commented on keyboards/mwstudio/cover65/keymaps/via/keymap.c
> +    [1] = LAYOUT(
```suggestion
    [0] = LAYOUT_65_ansi_blocker(
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,     KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,     KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_PGUP,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,     KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGDN,
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,     KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_END,
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPACE,                            KC_RALT, MO(1),   KC_LEFT, KC_DOWN, KC_RIGHT
    ),

    [1] = LAYOUT_65_ansi_blocker(
```

2023-11-20 13:23 UTC, dunk2k commented on keyboards/mwstudio/cover65/info.json
> +                { "matrix": [3, 12], "x": 12.25, "y": 4.25, "w":1.75},
```suggestion
                { "matrix": [2, 0], "x": 0, "y": 3, "w": 1.75 },
                { "matrix": [2, 1], "x": 1.75, "y": 3 },
                { "matrix": [2, 2], "x": 2.75, "y": 3 },
                { "matrix": [2, 3], "x": 3.75, "y": 3 },
                { "matrix": [2, 4], "x": 4.75, "y": 3 },
                { "matrix": [2, 5], "x": 5.75, "y": 3 },
                { "matrix": [2, 6], "x": 6.75, "y": 3 },
                { "matrix": [2, 7], "x": 7.75, "y": 3 },
                { "matrix": [2, 8], "x": 8.75, "y": 3 },
                { "matrix": [2, 9], "x": 9.75, "y": 3 },
                { "matrix": [2, 10], "x": 10.75, "y": 3 },
                { "matrix": [2, 11], "x": 11.75, "y": 3 },
                { "matrix": [2, 13], "x": 12.75, "y": 3, "w": 2.25 },
                { "matrix": [2, 14], "x": 15, "y": 3 },

                { "matrix": [3, 0], "x": 0, "y": 4, "w": 2.25 },
                { "matrix": [3, 2], "x": 2.25, "y": 4 },
                { "matrix": [3, 3], "x": 3.25, "y": 4 },
                { "matrix": [3, 4], "x": 4.25, "y": 4 },
                { "matrix": [3, 5], "x": 5.25, "y": 4 },
                { "matrix": [3, 6], "x": 6.25, "y": 4 },
                { "matrix": [3, 7], "x": 7.25, "y": 4 },
                { "matrix": [3, 8], "x": 8.25, "y": 4 },
                { "matrix": [3, 9], "x": 9.25, "y": 4 },
                { "matrix": [3, 10], "x": 10.25, "y": 4 },
                { "matrix": [3, 11], "x": 11.25, "y": 4 },
                { "matrix": [3, 12], "x": 12.25, "y": 4, "w":1.75},
```

2024-08-26 10:33 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2025-01-28 20:31 UTC, dunk2k requested changes

2025-01-28 21:39 UTC, zvecr commented
The request for via keymap removal has not been completed. closing as stalebot would have done so ages ago.

2025-01-28 21:39 UTC, closed without merging