Adding my Iris-Rev4 and Lily58 keymaps with suggested changes from waffle87
qmk/qmk_firmware pull request #20484
Opened 2023-04-18 01:26 UTC by tehxeno

## Description

I added my key configs for the:

- Keebio\iris\Rev4
- Lily58\Rev1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

- I applied suggested changes from reviewer waffle87

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-18 02:41 UTC, waffle87 commented
In the future, please commit changes to the same PR.

2023-04-18 04:10 UTC, tehxeno commented
> In the future, please commit changes to the same PR.

Sorry about that. This is my first PR, so I'm not sure what I'm doing or what next steps are.

It looks like my PR failed some automated tests?

2023-04-18 05:02 UTC, waffle87 commented
You don't really need to worry about those failures, unless you have an `iris/rev1` of course. However, since they're both just size checks, you could have a look at [squeezing AVR doc](https://docs.qmk.fm/#/squeezing_avr).

2023-04-26 04:02 UTC, drashna requested changes

2023-04-26 04:02 UTC, drashna commented on keyboards/keebio/iris/keymaps/tehxeno/keymap.c
> +bool encoder_update_user(uint8_t index, bool clockwise) {
You may want to use Encoder Map here, rather than the encoder update callback.

2023-04-26 04:02 UTC, drashna commented on keyboards/lily58/keymaps/tehxeno/config.h
> +#define MASTER_LEFT
Is default behavior, define not needed: 
```suggestion
```

2023-08-22 01:48 UTC, closed without merging