Adds Docs option for ArduinoIDE's example `ArduinoISP`
qmk/qmk_firmware pull request #20486
Opened 2023-04-18 01:54 UTC by teadetime

Current docs point to a specific `.hex` to flash to a Pro-Micro to sue it as an ISP. However, the default example ArduinoISP sketch emulates a stk500 ISP flasher. This is very accessible and should also be listed in the docs.

I confirmed this worked for my flashing `atmel-dfu` onto my Pro-Micro, via and Arduino Uno using the command (wiring as indicated):
```
avrdude -c stk500v1 -b 19200 -P /dev/ttyACM0 -p atmega32u4 -U flash:w:bootloader_atmega32u4_1.0.0.hex:i -U hfuse:w:0xD9:m -U efuse:w:0xC3:m -U lock:w:0x3F:m
```
 

## Description
Added corresponding wiring, description and `avrdude` parameters to guide. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-18 02:40 UTC, fauxpark requested changes

2023-04-18 02:40 UTC, fauxpark commented on docs/isp_flashing_guide.md
> +[Arduino Uno](https://store.arduino.cc/products/arduino-uno-rev3) or Pro Micro
```suggestion
### Arduino Uno / Micro as ISP

[Arduino Uno](https://store.arduino.cc/products/arduino-uno-rev3)
[Arduino Micro](https://store.arduino.cc/products/arduino-micro)
```

2023-04-18 02:40 UTC, fauxpark commented on docs/isp_flashing_guide.md
> +A standard 5v/16MMhz Uno or Pro Micro can be used as an ISP flashing tool using the [example "ArduinoISP" sketch](https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP#load-the-sketch) to
```suggestion
A standard Uno or Micro can be used as an ISP flashing tool using the [example "ArduinoISP" sketch](https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP#load-the-sketch) to emulate an STK500 ISP. Also works with Sparkfun Pro Micros and clones.
```

2023-04-18 02:40 UTC, fauxpark commented on docs/isp_flashing_guide.md
> +|`12`       |`MISO`  |
```suggestion
|Uno        |Keyboard|
|-----------|--------|
|`5V`       |`VCC`   |
|`GND`      |`GND`   |
|`10` (`B2`)|`RESET` |
|`13` (`B5`)|`SCLK`  |
|`11` (`B3`)|`MOSI`  |
|`12` (`B4`)|`MISO`  |
```

2023-04-18 02:40 UTC, fauxpark commented on docs/isp_flashing_guide.md
> +|Pro-Micro  |Keyboard|
```suggestion
|Micro      |Keyboard|
```

2023-04-18 02:40 UTC, fauxpark commented on docs/isp_flashing_guide.md
> +!> Note that the `10` pin on the Uno/Pro-Micro should be wired to the `RESET` pin on the keyboard's controller. ***DO NOT*** connect the `RESET` pin on the Uno/Pro-Micro to the `RESET` on the keyboar
```suggestion
!> Note that the `10` pin on the Uno/Micro should be wired to the `RESET` pin on the keyboard's controller. ***DO NOT*** connect the `RESET` pin on the Uno/Micro to the `RESET` on the keyboard.
```

2023-04-18 02:40 UTC, fauxpark commented on docs/isp_flashing_guide.md
> +|`VCC`      |`VCC`   |
```suggestion
|`5V`       |`VCC`   |
```

2023-04-18 02:52 UTC, teadetime commented
Thanks for the quick review and good edits -- couldn't track down the `B5` etc. labels for the Uno so wasn't sure if they were the same. Let me know if any other changes to be made.

2023-04-19 17:57 UTC, teadetime commented
> Thanks for the quick review and good edits -- couldn't track down the `B5` etc. labels for the Uno so wasn't sure if they were the same. Let me know if any other changes to be made.

@fauxpark  made the requested changes

2023-04-19 18:17 UTC, fauxpark approved these changes
TBH, I'm not actually sure where the .hex files in the repo came from, so perhaps this Arduino method should completely replace them instead. Just thinking out loud.

2023-04-19 18:23 UTC, zvecr approved these changes

2023-04-19 18:23 UTC, merged