Added /handwired/asesmero/6x6
qmk/qmk_firmware pull request #20507
Opened 2023-04-19 15:20 UTC by asesmero

A simple Otrho 6x6 keyboard for shorcut launch.

"I'm still learning, I hope this pull request is correct."

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-26 03:52 UTC, drashna commented on keyboards/handwired/asesmero/6x6/info.json
> +        "vid": "0x0282"
This makes me uncomfortable.  While yes, it's not assigned officially...

2023-04-26 03:53 UTC, drashna commented on keyboards/handwired/asesmero/6x6/readme.md
> +! Asesmero 6x6(https://bit.ly/3mM9xPz)
This should be rehosted on Imgur or the like (if imgur, make sure it's submitted by an account)

2023-04-26 03:54 UTC, drashna commented on keyboards/handwired/asesmero/6x6/keymaps/default/keymap.c
> +		MEH(KC_5), MEH(KC_6), MEH(KC_7), MEH(KC_8), MEH(KC_9), MEH(KC_0)),
Just a nit: 
```suggestion
		MEH(KC_5), MEH(KC_6), MEH(KC_7), MEH(KC_8), MEH(KC_9), MEH(KC_0)
	)
```

2023-05-09 07:32 UTC, drashna commented on keyboards/handwired/asesmero/6x6/info.json
> +        "vid": "0x0282"
In general, I prefer VIDs that are much higher in number.  Past 0x4000 is good, and the further past, the better.   For instance, `0x5A30`, which was generated with this command: 
```sh
echo -n 'asesmero' | shasum | cut -c1-4 | tr '[:lower:]' '[:upper:]'
```

2023-05-09 10:23 UTC, asesmero reviewed
Changed vid

2023-05-14 09:17 UTC, drashna requested changes

2023-05-14 09:17 UTC, drashna commented on keyboards/handwired/asesmero/6x6/readme.md
> +* Hardware Supported: Arduino ProMicro (ATMEGA32U4)
There is no Arduino Pro Micro.  it's a SparkFun design. 
```suggestion
* Hardware Supported: SparkFun Pro Micro (ATMEGA32U4)
```

2023-07-31 11:43 UTC, closed without merging