Adding the Bento Box macropad
qmk/qmk_firmware pull request #20521
Opened 2023-04-21 03:59 UTC by Synth-and-Keys

## Description

* keyboard files added
* default keymap included
* added to keyboards/synthandkeys

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-21 04:14 UTC, zvecr requested changes

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/config.h
> +// Copyright 2023 Synth-and-Keys (@Synth-and-Keys)
This file should be removed

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/rules.mk
> +MCU = STM32F072
```suggestion
# This file intentionally left blank
```

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/readme.md
> +    make bento_box:default
```suggestion
    make synthandkeys/bento_box:default
```

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/readme.md
> +    make bento_box:default:flash
```suggestion
    make synthandkeys/bento_box:default:flash
```

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/info.json
> +    },
```suggestion
    },
    "encoder": {
        "rotary": [
            { "pin_a": "B2", "pin_b": "B1" },
            { "pin_a": "A13", "pin_b": "A14" },
            { "pin_a": "A15", "pin_b": "B3" }
        ]
    },
    "bootmagic": {
        "matrix": [2, 0]
    },
```

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/info.json
> +        "nkro": true
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true
        "encoder": true
```

2023-04-21 04:14 UTC, zvecr commented on keyboards/synthandkeys/bento_box/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
// Copyright 2023 Synth-and-Keys (@Synth-and-Keys)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
```

2023-04-22 08:00 UTC, drashna commented on keyboards/synthandkeys/bento_box/keymaps/default/keymap.c
> +
This should be moved to the keyboard's c file ("bento_box.c"), that way the board has a default configuration, and can be overwritten.


```c
#ifdef ENCODER_ENABLE
bool encoder_update_kb(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) { return false; }
    if (index == 0) {
        if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
    }
/* TOP LEFT*/
    else if (index == 1) {
        if (clockwise) {
            tap_code16(C(KC_EQUAL));
        } else {
            tap_code16(C(KC_MINUS));
        }
    }
/* TOP RIGHT*/
    else if (index == 2) {
        if (clockwise) {
            tap_code16(C(KC_Y));
        } else {
            tap_code16(C(KC_Z));
        }
    }
    return true;
}
#endif
```

2023-04-22 20:32 UTC, zvecr commented on keyboards/synthandkeys/bento_box/bento_box.c
> +#ifdef ENCODER_ENABLE
```suggestion
// Copyright 2023 Synth-and-Keys (@Synth-and-Keys)
// SPDX-License-Identifier: GPL-2.0-or-later

#include "quantum.h"

#ifdef ENCODER_ENABLE
```

2023-04-26 03:45 UTC, drashna commented
Lint has some complaints that should be addressed

2023-05-01 23:45 UTC, Synth-and-Keys commented
Resolved lint complaints. It says there are changes requested, but I believe I have already resolved all of them?

2023-05-06 22:48 UTC, Synth-and-Keys reviewed
Just trying to close out the change requests to move forward

2023-05-09 07:12 UTC, drashna approved these changes

2023-05-09 10:33 UTC, fauxpark requested changes

2023-05-09 10:33 UTC, fauxpark commented on keyboards/synthandkeys/bento_box/info.json
> +                { "h": 1.5, "matrix": [4, 4], "x": 4.5, "y": 3.5 }
```suggestion
                {"matrix": [0, 3], "x": 3.5, "y": 0},
                {"matrix": [0, 4], "x": 4.5, "y": 0},
                {"matrix": [1, 1], "x": 1, "y": 0.5},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [1, 4], "x": 4.5, "y": 1},
                {"matrix": [2, 0], "x": 0, "y": 2},
                {"matrix": [2, 1], "x": 1, "y": 2},
                {"matrix": [2, 2], "x": 2, "y": 2},
                {"matrix": [3, 0], "x": 0, "y": 3},
                {"matrix": [3, 1], "x": 1, "y": 3},
                {"matrix": [3, 2], "x": 2, "y": 3},
                {"matrix": [3, 3], "x": 3.5, "y": 2.5},
                {"matrix": [3, 4], "x": 4.5, "y": 2.5},
                {"matrix": [4, 0], "x": 0, "y": 4},
                {"matrix": [4, 1], "x": 1, "y": 4},
                {"matrix": [4, 2], "x": 2, "y": 4},
                {"matrix": [4, 3], "x": 3.5, "y": 3.5, "h": 1.5},
                {"matrix": [4, 4], "x": 4.5, "y": 3.5, "h": 1.5}
```

2023-05-09 10:33 UTC, fauxpark commented on keyboards/synthandkeys/bento_box/info.json
> +            }
```suggestion
            {"pin_a": "B2", "pin_b": "B1"},
            {"pin_a": "A13", "pin_b": "A14"},
            {"pin_a": "A15", "pin_b": "B3"}
```

2023-05-14 09:14 UTC, drashna approved these changes

2023-07-20 10:12 UTC, fauxpark requested changes

2023-07-20 10:12 UTC, fauxpark commented on keyboards/synthandkeys/bento_box/keymaps/default/keymap.c
> +        KC_LEFT,   KC_DOWN,   KC_RIGHT, (S(C(KC_TAB))),   (C(KC_TAB))
```suggestion
                                             C(KC_0),  G(S(KC_S)),
                   KC_MUTE,                  C(KC_C),     C(KC_V),
        KC_MPRV,   KC_MPLY,    KC_MNXT,
        KC_HOME,     KC_UP,     KC_END,      C(KC_T),     C(KC_W),
        KC_LEFT,   KC_DOWN,   KC_RIGHT, S(C(KC_TAB)),   C(KC_TAB)
```

2023-07-20 10:12 UTC, fauxpark commented on keyboards/synthandkeys/bento_box/info.json
> +            [null, null, null, "A9", "A8"],
You should not have any null pins here.

2023-07-21 20:55 UTC, fauxpark commented on keyboards/synthandkeys/bento_box/info.json
> +            ["A6", "A3", "A0", "B7", "B4"]
You can make better use of the matrix like so:
```suggestion
            ["A9", "A8", "B9", "B6", "B0", "A5"],
            ["A2", "A7", "A4", "A1", "B8", "B5"],
            ["A6", "A3", "A0", "B7", "B4", null]
```
Then adjust the layout matrix positions appropriately.

2023-07-21 21:05 UTC, fauxpark commented on keyboards/synthandkeys/bento_box/info.json
> +                { "matrix": [4, 4], "x": 4.5, "y": 3.5, "h": 1.5}
```suggestion
                { "matrix": [0, 0], "x": 3.5, "y": 0 },
                { "matrix": [0, 1], "x": 4.5, "y": 0 },

                { "matrix": [0, 2], "x": 1, "y": 0.5 },
                { "matrix": [0, 3], "x": 3.5, "y": 1 },
                { "matrix": [0, 4], "x": 4.5, "y": 1 },

                { "matrix": [0, 5], "x": 0, "y": 2 },
                { "matrix": [1, 0], "x": 1, "y": 2 },
                { "matrix": [1, 1], "x": 2, "y": 2 },

                { "matrix": [1, 2], "x": 0, "y": 3 },
                { "matrix": [1, 3], "x": 1, "y": 3 },
                { "matrix": [1, 4], "x": 2, "y": 3 },
                { "matrix": [1, 5], "x": 3.5, "y": 2.5 },
                { "matrix": [2, 0], "x": 4.5, "y": 2.5 },

                { "matrix": [2, 1], "x": 0, "y": 4 },
                { "matrix": [2, 2], "x": 1, "y": 4 },
                { "matrix": [2, 3], "x": 2, "y": 4 },
                { "matrix": [2, 4], "x": 3.5, "y": 3.5, "h": 1.5},
                { "matrix": [2, 5], "x": 4.5, "y": 3.5, "h": 1.5}
```
This layout doesn't make sense; there are 18 keys but the direct_pins configuration above only specifies 17 pins (hence the single `null` pin). Please double check this.

2023-07-28 04:56 UTC, drashna approved these changes

2023-08-01 22:04 UTC, fauxpark approved these changes

2023-08-02 17:05 UTC, merged