Johnstegeman Colemak layout for Keebio Iris
qmk/qmk_firmware pull request #20545
Opened 2023-04-24 14:17 UTC by johnstegeman

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-24 16:08 UTC, waffle87 commented on keyboards/keebio/iris/keymaps/johnstegeman/README.md
This filename should be lowercase.

2023-04-24 16:18 UTC, johnstegeman commented on keyboards/keebio/iris/keymaps/johnstegeman/README.md
fixed

2023-04-25 08:23 UTC, drashna requested changes

2023-04-25 08:23 UTC, drashna commented on keyboards/keebio/iris/keymaps/johnstegeman/keymap.c
> +_COLEMAK=0,
The zero isn't needed, as the enum starts at zero, by default. 
```suggestion
_COLEMAK,
```

2023-04-25 08:23 UTC, drashna commented on keyboards/keebio/iris/keymaps/johnstegeman/keymap.c
> +      break;
If this is the only default layer, then this isn't needed and can be removed.

2023-04-25 08:23 UTC, drashna commented on keyboards/keebio/iris/keymaps/johnstegeman/keymap.c
> +      break;
Just a heads up, these are built into core:
https://docs.qmk.fm/#/feature_tri_layer

And the adjust layer is basically just `MO(_ADJUST)`

2023-04-25 08:23 UTC, drashna commented on keyboards/keebio/iris/keymaps/johnstegeman/keymap.c
> +         SEND_STRING("Colemak Rocks!\n");
lol, nice. ;)

2023-04-25 08:23 UTC, drashna commented on keyboards/keebio/iris/keymaps/johnstegeman/rules.mk
> +RGB_MATRIX_ENABLE = no # by default this is yes, but for the rgb light layers to work it needs to be `no`
You can do the same with rgb matrix, and the indicators function: 
https://docs.qmk.fm/#/feature_rgb_matrix?id=callbacks

It's a bit more manual, but just as flexible

2023-04-25 08:23 UTC, drashna commented on keyboards/keebio/iris/keymaps/johnstegeman/rules.mk
> +SPLIT_KEYBOARD = yes
```suggestion
```

2023-04-26 13:49 UTC, closed without merging