add 5087 keyboard
qmk/qmk_firmware pull request #20557
Opened 2023-04-25 08:08 UTC by jonylee1986

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-26 01:39 UTC, drashna commented on keyboards/akko/5087/rules.mk
> +
nit:
```suggestion
```

2023-04-26 01:46 UTC, drashna requested changes

2023-04-26 01:46 UTC, drashna commented on keyboards/akko/5087/config.h
> +#define RGB_MATRIX_CENTER {112,32}
This is the default, it doesn't need to be set. 
```suggestion
```

2023-04-26 01:46 UTC, drashna commented on keyboards/akko/5087/5087.c
> +
these should be kb config, since it's not user config.

```suggestion
} kb_config_t;

kb_config_t kb_config;

```

2023-04-26 01:46 UTC, drashna commented on keyboards/akko/5087/5087.c
> +    }
```suggestion
    kb_config.raw = eeconfig_read_kb(); // Read status from EEPROM
    if (kb_config.MacMode_flag) { 
        layer_on(MAC_B);
    }
    if (kb_config._WASD_layer_flag) {
        kb_config.MacMode_flag ? layer_on(MAC_W) : layer_on(WIN_W);
    }
```

2023-04-26 01:46 UTC, drashna commented on keyboards/akko/5087/5087.c
> +    eeconfig_update_user(user_config.raw);
```suggestion
    kb_config._WASD_layer_flag = false;
    eeconfig_update_kb(kb_config.raw);
```

2023-05-29 05:14 UTC, drashna commented on keyboards/akko/5087/5087.c
> +enum __layers { WIN_B, WIN_W, WIN_FN, MAC_B, MAC_W, MAC_FN };
Just a heads up, it's a weird hack, but if you add a comma at the end, it prevents it from being reformatted into a single line.
```suggestion
enum __layers { 
	WIN_B, 
	WIN_W, 
	WIN_FN, 
	MAC_B, 
	MAC_W, 
	MAC_FN, 
};
```

2023-07-03 21:33 UTC, drashna commented on keyboards/akko/5087/5087.c
> +    if (kb_config.MacMode_flag) {
persistent default layer is set already, no need to do this, TBH.

2023-07-03 21:33 UTC, drashna commented on keyboards/akko/5087/5087.c
> +                layer_state_set(1 << WIN_B);
This isn't needed.

2023-07-03 21:33 UTC, drashna commented on keyboards/akko/5087/5087.c
> +        kb_config.MacMode_flag ? layer_on(MAC_W) : layer_on(WIN_W);
Not necessary, but a bit more compact:
```suggestion
        layer_on(kb_config.MacMode_flag ? MAC_W : WIN_W);
```

2023-08-31 23:10 UTC, fauxpark approved these changes

2023-09-03 04:13 UTC, drashna approved these changes

2023-09-03 04:14 UTC, drashna requested changes

2023-09-03 04:14 UTC, drashna commented on keyboards/akko/5087/info.json
> +        "driver": "IS31FL3733",
```suggestion
        "driver": "is31fl3733",
```

2023-09-03 05:07 UTC, zvecr requested changes

2023-09-03 05:07 UTC, zvecr commented on keyboards/akko/5087/info.json
> +        "encoder": false,
```suggestion
```

2023-09-03 05:07 UTC, zvecr commented on keyboards/akko/5087/5087.c
> +}
```suggestion
    writePinLow(LED_WIN_LOCK_PIN);

    matrix_init_user();
}
```

2023-09-03 05:07 UTC, zvecr commented on keyboards/akko/5087/info.json
> +    },    "layouts": {
```suggestion
    },
    "layouts": {
```

2023-09-03 05:07 UTC, zvecr commented on keyboards/akko/5087/rules.mk
> +#
```suggestion
```

2023-09-18 03:43 UTC, fauxpark requested changes

2023-09-18 03:43 UTC, fauxpark commented on keyboards/akko/5087/5087.c
> +const is31_led PROGMEM g_is31_leds[RGB_MATRIX_LED_COUNT] = {
```suggestion
const ckled2001_led PROGMEM g_ckled2001_leds[RGB_MATRIX_LED_COUNT] = {
```

2023-09-18 03:43 UTC, fauxpark commented on keyboards/akko/5087/info.json
> +        "driver": "is31fl3733",
```suggestion
        "driver": "ckled2001",
```

2023-09-18 03:43 UTC, fauxpark commented on keyboards/akko/5087/info.json
> +            "solid_reactive_cross": true,
```suggestion
            "solid_reactive_cross": true,
```

2023-09-23 05:01 UTC, drashna requested changes

2023-09-23 05:01 UTC, drashna commented on keyboards/akko/5087/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 6
```suggestion
```

2023-09-23 05:01 UTC, drashna commented on keyboards/akko/5087/info.json
> +    "matrix_pins": {
```suggestion
    "dynamic_keymap": {
        "layer_count": 6
    },
    "matrix_pins": {
```

2023-09-23 05:01 UTC, drashna commented on keyboards/akko/5087/keymaps/default/keymap.c
Could you replace the tabs with spaces?

2023-09-23 05:01 UTC, drashna commented on keyboards/akko/5087/keymaps/via/keymap.c
here too.

2023-09-27 02:36 UTC, jonylee1986 commented on keyboards/akko/5087/keymaps/default/keymap.c
got it!

2023-10-10 20:39 UTC, noroadsleft requested changes

2023-10-10 20:39 UTC, noroadsleft commented on keyboards/akko/5087/info.json
> +        "LAYOUT": {
```suggestion
    "community_layouts": ["tkl_ansi"],
    "layouts": {
        "LAYOUT_tkl_ansi": {
```

2023-10-10 20:39 UTC, noroadsleft commented on keyboards/akko/5087/keymaps/default/keymap.c
> +    [MAC_FN] = LAYOUT( /* FN */
```suggestion
    [WIN_B] = LAYOUT_tkl_ansi( /* Base */
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,           KC_PSCR, KC_SCRL, KC_PAUS,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,  KC_HOME, KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,  KC_END,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT,          KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                             KC_RALT, KC_RGUI, MO(WIN_FN),       KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

    [WIN_W] = LAYOUT_tkl_ansi( /* Base */
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, KC_UP,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                   _______,          KC_W,
        _______, _______, _______,                   _______,                            _______, _______, MO(WIN_FN),       _______, KC_A,    KC_S,    KC_D),


    [WIN_FN] = LAYOUT_tkl_ansi( /* FN */
        _______, KC_MYCM, KC_MAIL, KC_WSCH, KC_WHOM, KC_MSEL, KC_MPLY, KC_MPRV, KC_MNXT, _______,_______,  _______, _______,          _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_SPD, RGB_SPI, _______, _______, _______, _______,
        _______, _______,TG(WIN_W),_______, _______, _______, _______, _______, _______, DF(MAC_B),_______,_______, _______, RGB_MOD, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_TOG, _______, _______,          RGB_HUI,
        _______, _______, _______, KC_CALC, _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,                   _______,          RGB_VAI,
        _______, GU_TOGG, _______,                   _______,                            _______, _______, _______,          _______, RGB_SAD, RGB_VAD, RGB_SAI),

    [MAC_B] = LAYOUT_tkl_ansi( /* Base */
        KC_ESC,  KC_BRID, KC_BRIU, KC_MCTL, KC_LPAD, KC_F5,   KC_F6,   KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_VOLD, KC_VOLU,          KC_PSCR, KC_SCRL, KC_PAUS,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,  KC_HOME, KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,  KC_END,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT,          KC_UP,
        KC_LCTL, KC_LALT, KC_LGUI,                   KC_SPC,                             KC_RGUI, KC_RALT, MO(MAC_FN),       KC_RCTL, KC_LEFT, KC_DOWN,   KC_RGHT),

    [MAC_W] = LAYOUT_tkl_ansi( /* Base */
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, KC_UP,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                   _______,          KC_W,
        _______, _______, _______,                   _______,                            _______, _______, MO(MAC_FN),       _______, KC_A,    KC_S,    KC_D),
    [MAC_FN] = LAYOUT_tkl_ansi( /* FN */
```

2023-10-10 20:39 UTC, noroadsleft commented on keyboards/akko/5087/keymaps/via/keymap.c
> +    [MAC_FN] = LAYOUT( /* FN */
```suggestion
    [WIN_B] = LAYOUT_tkl_ansi( /* Base */
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,           KC_PSCR, KC_SCRL, KC_PAUS,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,  KC_HOME, KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,  KC_END,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT,          KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                             KC_RALT, KC_RGUI, MO(WIN_FN),       KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

    [WIN_W] = LAYOUT_tkl_ansi( /* Base */
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, KC_UP,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                   _______,          KC_W,
        _______, _______, _______,                   _______,                            _______, _______, MO(WIN_FN),       _______, KC_A,    KC_S,    KC_D),


    [WIN_FN] = LAYOUT_tkl_ansi( /* FN */
        _______, KC_MYCM, KC_MAIL, KC_WSCH, KC_WHOM, KC_MSEL, KC_MPLY, KC_MPRV, KC_MNXT, _______,_______,  _______, _______,          _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_SPD, RGB_SPI, _______, _______, _______, _______,
        _______, _______,TG(WIN_W),_______, _______, _______, _______, _______, _______, DF(MAC_B),_______,_______, _______, RGB_MOD, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_TOG, _______, _______,          RGB_HUI,
        _______, _______, _______, KC_CALC, _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,                   _______,          RGB_VAI,
        _______, GU_TOGG, _______,                   _______,                            _______, _______, _______,          _______, RGB_SAD, RGB_VAD, RGB_SAI),

    [MAC_B] = LAYOUT_tkl_ansi( /* Base */
        KC_ESC,  KC_BRID, KC_BRIU, KC_MCTL, KC_LPAD, KC_F5,   KC_F6,   KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_VOLD, KC_VOLU,          KC_PSCR, KC_SCRL, KC_PAUS,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,  KC_HOME, KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,  KC_END,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT,          KC_UP,
        KC_LCTL, KC_LALT, KC_LGUI,                   KC_SPC,                             KC_RGUI, KC_RALT, MO(MAC_FN),       KC_RCTL, KC_LEFT, KC_DOWN,   KC_RGHT),

    [MAC_W] = LAYOUT_tkl_ansi( /* Base */
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, KC_UP,   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                   _______,          KC_W,
        _______, _______, _______,                   _______,                            _______, _______, MO(MAC_FN),       _______, KC_A,    KC_S,    KC_D),
    [MAC_FN] = LAYOUT_tkl_ansi( /* FN */
```

2023-10-12 21:44 UTC, noroadsleft approved these changes

2023-10-27 06:50 UTC, drashna requested changes

2023-10-27 06:50 UTC, drashna commented on keyboards/akko/5087/5087.c
> +            return true;
you have this set above, in housekeeping, so you don't need this here. 
```suggestion
```

2023-11-11 19:08 UTC, drashna approved these changes

2023-11-11 19:08 UTC, drashna approved these changes

2023-11-11 19:08 UTC, merged

2024-02-12 16:50 UTC, mbana commented
Is this, https://www.amazon.co.uk/dp/B0BVQCF2PY, keyboard supported?

2024-02-12 17:16 UTC, fauxpark commented
No.

2024-02-12 18:12 UTC, mbana commented
So which keyboard(s) are supported then? Please provide links.