[Controller] Add ModelH STM32 controller firmware
qmk/qmk_firmware pull request #20578
Opened 2023-04-26 22:21 UTC by medoix

## Description

Looking to merge the ModelH config and keymaps into QMK master. This device is an STM32 controller designed as a drop in replacement for the IBM Model M Keyboard series to support USB Type-B and QMK.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-27 03:11 UTC, drashna requested changes
PR checklist needs to be reviewed. 

Most of the config.h settings are outdated, etc.

2023-04-27 03:11 UTC, drashna commented on keyboards/modelh/chconf.h
Please remove.

Defaults have been set in core, and you should only change what is needed to be changed. 

A bunch of the mechlovin boards use the f103, for instance.

2023-04-27 03:11 UTC, drashna commented on keyboards/modelh/halconf.h
same as chconf.h

2023-04-27 03:11 UTC, drashna commented on keyboards/modelh/mcuconf.h
same as chconf.h

2023-04-29 08:06 UTC, medoix commented on keyboards/modelh/chconf.h
Removed in 90dccdb4eb0759966224d0c90ba02748baa761b6

2023-04-29 08:06 UTC, medoix commented on keyboards/modelh/halconf.h
Removed in 90dccdb4eb0759966224d0c90ba02748baa761b6

2023-04-29 08:06 UTC, medoix commented on keyboards/modelh/mcuconf.h
Removed in 90dccdb4eb0759966224d0c90ba02748baa761b6

2023-05-02 03:25 UTC, drashna commented
identical to #20625

2023-05-02 06:02 UTC, sc-steven commented
> identical to #20625

@drashna Yes it appears someone else raised a PR a couple of days after this one. Happy for either to be selected.

2023-06-25 22:08 UTC, medoix commented
Closing in favor of this PR https://github.com/qmk/qmk_firmware/pull/20625

2023-06-25 22:08 UTC, closed without merging