[Feature] Disable debug on QP's internal task
qmk/qmk_firmware pull request #20623
Opened 2023-04-29 09:22 UTC by elpekenin

## Description

#20013 introduced auto-flushing on QP's internal task, however this leads to a problem when debugging, as the console gets a spam of `qp_flush` messages, thus added a define to disable output while the task perform the flushes

## Types of Changes

- [X] Core
- [ ] Bugfix
- [X] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- X ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-04-29 13:02 UTC, tzarc requested changes

2023-04-29 13:02 UTC, tzarc commented on docs/quantum_painter.md
> +| `QP_DEBUG_ENABLE_INTERNAL_FLUSH_OUTPUT`  | _unset_ | By default, debug is disabled while internal task is flushing the display(s). If you want want it to keep enabled, add this. Note: Console will
```suggestion
| `QP_DEBUG_ENABLE_FLUSH_TASK_OUTPUT`  | _unset_ | By default, debug output is disabled while the internal task is flushing the display(s). If you want to keep it enabled, add this to your `config.h`. Note: Console will get clogged.                                 |
```

2023-04-29 13:02 UTC, tzarc commented on quantum/painter/qp_internal.c
> +#endif // defined(QP_DEBUG_ENABLE_INTERNAL_FLUSH_OUTPUT)
```suggestion
#if !defined(QP_DEBUG_ENABLE_FLUSH_TASK_OUTPUT)
    bool old_debug_state = debug_enable;
    debug_enable     = false;
#endif // defined(QP_DEBUG_ENABLE_FLUSH_TASK_OUTPUT)
```

2023-04-29 13:02 UTC, tzarc commented on quantum/painter/qp_internal.c
> +#endif // defined(QP_DEBUG_ENABLE_INTERNAL_FLUSH_OUTPUT)
```suggestion
#if !defined(QP_DEBUG_ENABLE_FLUSH_TASK_OUTPUT)
    debug_enable = old_debug_state;
#endif // defined(QP_DEBUG_ENABLE_FLUSH_TASK_OUTPUT)
```

2023-04-30 01:53 UTC, tzarc approved these changes

2023-05-02 02:37 UTC, drashna approved these changes

2023-05-02 02:38 UTC, merged