add azerty_fr keymap for kprepublic/bm60hsrgb_iso/rev1
qmk/qmk_firmware pull request #20683
Opened 2023-05-03 08:01 UTC by tbourgain

Add a keymap for french AZERTY layout on KPRepublic bm60hsrgb_iso/rev1 keyboard
Update readme file for rev1 to match keyboard rev (rev2 -> rev1)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-30 06:23 UTC, drashna requested changes

2023-08-30 06:23 UTC, drashna commented on keyboards/kprepublic/bm60hsrgb_iso/rev1/keymaps/azerty_fr/readme.md
> +with dynamic macros enabled.
```suggestion
```

2023-08-30 06:23 UTC, drashna commented on keyboards/kprepublic/bm60hsrgb_iso/rev1/keymaps/azerty_fr/rules.mk
this file can be removed.

2023-10-06 14:50 UTC, tbourgain commented on keyboards/kprepublic/bm60hsrgb_iso/rev1/keymaps/azerty_fr/readme.md
> +with dynamic macros enabled.
file removed

2023-10-06 14:51 UTC, tbourgain commented on keyboards/kprepublic/bm60hsrgb_iso/rev1/keymaps/azerty_fr/rules.mk
file removed

2023-12-13 18:02 UTC, closed without merging