Add a winter keyboard made by kibou
qmk/qmk_firmware pull request #20707
Opened 2023-05-04 08:44 UTC by biuboom-jun

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-04 13:10 UTC, zvecr requested changes

2023-05-05 02:59 UTC, biuboom-jun commented on keyboards/winter/rules.mk
Hello, after I modified this template, I got an error "File 'keyboards/winter/rules.mk' Requires Formatting
Error: Requires Formatting", this error also occurs in my info.json and readme.md, can you give me a solution?

2023-05-06 01:00 UTC, zvecr commented on keyboards/winter/rules.mk
You need to use unix line endings.

2023-05-06 01:17 UTC, zvecr commented on keyboards/winter/rules.mk
This file can not be empty

2023-05-06 09:49 UTC, tzarc commented
As per the PR Checklist this should be multiple PRs, one keyboard each.

2023-05-08 01:00 UTC, closed without merging