Add Cepstrum Rev. 1 Keyboard
qmk/qmk_firmware pull request #20721
Opened 2023-05-04 22:15 UTC by nooges

## Description

Adds Cepstrum Rev. 1 Keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-11 16:57 UTC, zvecr requested changes

2023-05-12 20:15 UTC, nooges commented on keyboards/keebio/cepstrum/rev1/rev1.h
> +#define LAYOUT_65xt( \
Resolved by using `qmk info -f json --keyboard keebio/cepstrum/rev1`

2023-05-14 08:02 UTC, drashna requested changes

2023-05-14 08:02 UTC, drashna commented on keyboards/keebio/cepstrum/rev1/config.h
> +#define RGB_DI_PIN GP18
```suggestion
#define WS2812_DI_PIN GP18
#define RGB_DI_PIN WS2812_DI_PIN
```

2023-05-14 08:02 UTC, drashna commented on keyboards/keebio/cepstrum/rev1/info.json
> +    "debounce": 5,
```suggestion
```

2023-05-18 08:03 UTC, drashna approved these changes

2023-05-18 10:29 UTC, merged