[keybaord]Move kb83 keyboard.
qmk/qmk_firmware pull request #20761
Opened 2023-05-06 09:05 UTC by jonylee1986

## Description
move hfdkb/keyboard_sw/k83 --> inland/kb83

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-10 21:27 UTC, dunk2k approved these changes

2023-06-13 08:41 UTC, drashna approved these changes

2023-06-13 17:46 UTC, fauxpark requested changes

2023-06-13 17:46 UTC, fauxpark commented on data/mappings/keyboard_aliases.hjson
> +        "target":"inland/kb83"
```suggestion
        "target": "inland/kb83"
```

2023-06-13 17:46 UTC, fauxpark commented on data/mappings/keyboard_aliases.hjson
> +    "hfdkb/keyboard_sw/k83":{
Should be moved below `hecomi/alpha`.

2023-06-14 10:15 UTC, fauxpark approved these changes

2023-06-19 02:20 UTC, noroadsleft commented
Would like for this to stay unmerged until I can get a fix in for the Configurator layout data (which hopefully shouldn't take long):

![image](https://github.com/qmk/qmk_firmware/assets/18669334/733ae2c4-3d75-44a7-b547-c570c165fb57)

2023-06-19 02:49 UTC, noroadsleft commented
> a fix in for the Configurator layout data

#21297

2023-06-19 03:36 UTC, jonylee1986 commented
Sorry, I misunderstood your meaning. I have also submitted changes here, and I am not sure if this will lead to any conflicts. If there are any, please follow your modifications. Your modifications are very suitable for this keyboard.@noroadsleft

2023-06-19 04:01 UTC, noroadsleft commented
@jonylee1986,

Sorry for the lack of clarity. I requested a hold on this PR because QMK Configurator is using this data already, but if this PR gets merged, the Configurator implementation won't get fixed until the next `develop`->`master` merge at the end of August.

Once my PR is merged, ideally I will be able to integrate its changes into this PR from my end and you won't need to do anything.

2023-06-19 16:10 UTC, noroadsleft commented
@jonylee1986,

My Configurator layout fix has been merged to `qmk:master`, and the implementation now appears as:
![](https://user-images.githubusercontent.com/18669334/246713376-1c3cad6d-9fc8-4740-b5f2-205af53f6fac.png)

Unfortunately, it appears either my attempt or yours to fix the layout data have created a merge conflict.

Removing the last six commits from your GitHub fork's `move_kb83` branch by running:

```
git push --force-with-lease git@github.com:jonylee1986/qmk_firmware_master.git c085c54765:move_kb83
```

in your command line interface should fix the conflict.

2023-06-20 02:30 UTC, noroadsleft approved these changes
... or you could merge the branches together - which strangely didn't merge cleanly when I tried it locally. :confused: 

Looks good, thanks!

2023-06-20 02:31 UTC, merged