add subrezon/lancer keyboard
qmk/qmk_firmware pull request #20792
Opened 2023-05-08 12:57 UTC by subrezon

## Description

Added subrezon/lancer keyboard. Keyboard source: https://github.com/subrezon/lancer 

I have tested the keyboard with the firmware built using the contents of this pull request, and am typing this using the keyboard right now.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-08 13:33 UTC, zvecr requested changes

2023-05-08 13:33 UTC, zvecr commented on keyboards/subrezon/lancer/info.json
> +	"bootloader": "caterina",
```suggestion
	"development_board": "promicro",
```

2023-05-08 13:33 UTC, zvecr commented on keyboards/subrezon/lancer/rules.mk
> +LTO_ENABLE = yes
```suggestion
# This file intentionally left blank
```

2023-05-08 13:33 UTC, zvecr commented on keyboards/subrezon/lancer/info.json
> +	},
```suggestion
	    "features": {
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true
    },
```

2023-05-09 04:54 UTC, drashna commented on keyboards/subrezon/lancer/readme.md
> +![subrezon/lancer](https://i.imgur.com/W41Vx4r.jpg)
```suggestion
![subrezon/lancer](https://i.imgur.com/W41Vx4rh.jpg)
```

2023-05-09 04:54 UTC, drashna approved these changes

2023-05-30 08:16 UTC, subrezon commented
Is there anything else I need to do to get this merged?

2023-08-21 16:33 UTC, subrezon commented
@zvecr could you review this again please?

2023-08-30 06:24 UTC, drashna requested changes

2023-08-30 06:24 UTC, drashna commented on keyboards/subrezon/lancer/info.json
Could you run `qmk format-json` on this file (or otherwise convert the tabs to spaces)?

2023-08-30 06:24 UTC, drashna commented on keyboards/subrezon/lancer/keymaps/default/keymap.json
same here.

2023-09-03 04:03 UTC, drashna approved these changes

2023-09-04 00:38 UTC, fauxpark approved these changes

2023-09-19 10:58 UTC, subrezon commented
Anytihng else I need to do?

2023-09-23 05:10 UTC, merged