add linworks fave60a
qmk/qmk_firmware pull request #20795
Opened 2023-05-08 15:32 UTC by duilchoi

add fave60a

## Description

hi.
i added linworks fave60a.
please review.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-09 16:04 UTC, duilchoi commented
info.json file updated!
thank you.drashna!

2023-05-11 19:39 UTC, drashna requested changes

2023-05-11 19:39 UTC, drashna commented on keyboards/linworks/fave60a/info.json
> +    },
```suggestion
```

2023-05-11 19:39 UTC, drashna commented on keyboards/linworks/fave60a/info.json
> +    "protocol": "ChibiOS",
```suggestion
    "processor": "STM32F072",
```

2023-05-11 19:39 UTC, drashna commented on keyboards/linworks/fave60a/info.json
> +            "c_macro": true,
```suggestion
```

2023-05-11 19:39 UTC, drashna commented on keyboards/linworks/fave60a/readme.md
> +![linworks/fave60a back](https://imgur.com/j3mu8LF)
```suggestion
![linworks/fave60a front](https://i.imgur.com/UeWR8Klh.png)
![linworks/fave60a back](https://i.imgur.com/j3mu8LFh.png)
```

2023-05-12 03:22 UTC, drashna approved these changes

2023-05-12 04:15 UTC, fauxpark requested changes

2023-05-12 04:15 UTC, fauxpark commented on keyboards/linworks/fave60a/info.json
> +                { "label": "Esc", "matrix": [0, 0], "w": 1, "x": 0, "y": 0 },
```suggestion
                { "label": "Esc", "matrix": [0, 0], "x": 0, "y": 0 },
```
etc...

2023-05-12 06:29 UTC, fauxpark commented on keyboards/linworks/fave60a/info.json
> +                { "label": "Esc", "matrix": [0, 0], "w": 1, "x": 0, "y": 0 },
The rest of these still need to be done.

2023-05-14 05:38 UTC, drashna requested changes

2023-05-14 05:38 UTC, drashna commented on keyboards/linworks/fave60a/config.h
> +#define RGB_DI_PIN A10
```suggestion
#define WS2812_DI_PIN A10
#define RGB_DI_PIN WS2812_DI_PIN
```

2023-05-14 14:25 UTC, fauxpark requested changes

2023-05-14 14:25 UTC, fauxpark commented on keyboards/linworks/fave60a/info.json
> +    "debounce": 5,
```suggestion
```

2023-05-14 14:25 UTC, fauxpark commented on keyboards/linworks/fave60a/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
Please fill these out.

2023-05-15 00:36 UTC, fauxpark requested changes

2023-05-15 00:36 UTC, fauxpark commented on keyboards/linworks/fave60a/readme.md
> +*A short description of the keyboard/project*
```suggestion
```

2023-05-15 00:36 UTC, fauxpark commented on keyboards/linworks/fave60a/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
These two still need to be filled out.

2023-05-18 07:56 UTC, drashna requested changes

2023-05-18 07:56 UTC, drashna commented on keyboards/linworks/fave60a/info.json
> +    },
```suggestion
```

2023-05-18 07:56 UTC, drashna commented on keyboards/linworks/fave60a/info.json
> +    },
```suggestion
```

2023-05-18 07:56 UTC, drashna commented on keyboards/linworks/fave60a/info.json
> +        "mousekey": false,
```suggestion
        "encoder": true,
        "extrakey": true,
        "mousekey": true,
```

2023-05-29 04:45 UTC, drashna requested changes

2023-05-29 04:45 UTC, drashna commented on keyboards/linworks/fave60a/config.h
> +#define RGB_DI_PIN WS2812_DI_PIN
```suggestion
```

2023-05-30 07:29 UTC, fauxpark requested changes

2023-05-30 07:29 UTC, fauxpark commented on keyboards/linworks/fave60a/config.h
> +#define WS2812_DI_PIN A10
```suggestion
```

2023-05-30 07:29 UTC, fauxpark commented on keyboards/linworks/fave60a/info.json
> +    "processor": "STM32F072",
```suggestion
    "processor": "STM32F072",
    "ws2812": {
        "pin": "A10"
    },
```

2023-07-03 20:49 UTC, drashna commented on keyboards/linworks/fave60a/config.h
> +// Framebuffer effects; can be enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS
Undefining `RGB_MATRIX_FRAMEBUFFER_EFFECTS` will effectively disable these too.

But if these aren't enabled, they don't need to be undef'ed

2023-07-04 01:20 UTC, fauxpark requested changes

2023-07-04 01:20 UTC, fauxpark commented on keyboards/linworks/fave60a/config.h
> +#define RGBLED_NUM 91
```suggestion
```

2023-07-04 01:20 UTC, fauxpark commented on keyboards/linworks/fave60a/config.h
> +#endif
```suggestion
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_KEYPRESSES 
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL

#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
// The PIXEL_FRACTAL effect does not work properly when the matrix layout is
// different from the physical layout; it also has problems when underglow
// LEDs are present, or when multiple LEDs are associated with the same key.
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL

// Framebuffer effects; can be enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS
// is defined.  Both of these effects currently don't work properly when the
// key matrix does not match the physical layout, so they are disabled.
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

// Reactive effects; can be enabled only if at least one of
// RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined.
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
```
These can be moved to info.json.

2023-07-07 21:39 UTC, drashna requested changes

2023-07-07 21:39 UTC, drashna commented on keyboards/linworks/fave60a/config.h
> +
```suggestion
#pragma once

```

2023-07-08 03:23 UTC, fauxpark requested changes

2023-07-08 03:23 UTC, fauxpark commented on keyboards/linworks/fave60a/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```suggestion
```

2023-07-11 07:47 UTC, drashna approved these changes

2023-07-24 13:28 UTC, fauxpark approved these changes

2023-07-25 02:54 UTC, waffle87 commented on keyboards/linworks/fave60a/info.json
> +        "rgblight": false
```suggestion
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgb_matrix": true
```

2023-07-25 02:54 UTC, waffle87 approved these changes

2023-07-25 02:55 UTC, merged