Add LD7032 support to QP.
qmk/qmk_firmware pull request #20828
Opened 2023-05-09 23:26 UTC by daskygit

## Description

Depends on https://github.com/qmk/qmk_firmware/pull/19997

I've tested I2C using a 96x24 display.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-09 23:34 UTC, daskygit commented
It's pretty much ready to go minus the poor i2c/spi comms handling. Opened so duplicate work doesn't get done (although unlikely).

2023-12-07 13:52 UTC, daskygit commented
best I sort the documentation conflicts

2024-09-09 22:48 UTC, tzarc requested changes

2024-09-09 22:48 UTC, tzarc commented on drivers/painter/ld7032/qp_ld7032.c
> +    };
// clang-format off
    uint8_t ld7032_memory_setup[] = {
        // Command,        Delay,  N, Data[N]
        LD7032_DISP_SIZE_X,     0, 2, 0x00, 0x7F,
        LD7032_DISP_SIZE_Y,     0, 2, 0x00, 0x27,
        LD7032_X_DISP_START,    0, 1, 0x0,
        LD7032_Y_DISP_START,    0, 1, 0x0,
    };
    // clang-format on

2024-09-10 03:17 UTC, drashna approved these changes

2024-09-10 06:18 UTC, sigprof requested changes

2024-09-10 06:18 UTC, sigprof commented on docs/quantum_painter.md
> +painter_device_t qp_ld7032_make_i2c_device(uint16_t panel_width, uint16_t panel_height, uint8_t i2c_address);
```suggestion
// SPI-based LD7032:
painter_device_t qp_ld7032_make_spi_device(uint16_t panel_width, uint16_t panel_height, pin_t chip_select_pin, pin_t dc_pin, pin_t reset_pin, uint16_t spi_divisor, int spi_mode);
// I2C-based LD7032:
painter_device_t qp_ld7032_make_i2c_device(uint16_t panel_width, uint16_t panel_height, uint8_t i2c_address);
```

2024-09-10 06:18 UTC, sigprof commented on docs/quantum_painter.md
> +Native color format mono2 is compatible with LD7032
```suggestion
Native color format mono2 is compatible with LD7032.
```

2024-09-10 07:00 UTC, sigprof requested changes

2024-09-10 11:16 UTC, daskygit commented on drivers/painter/ld7032/qp_ld7032.c
> +        memcpy(packet, &framebuffer[(y_pos * (driver->panel_width >> 3)) + x_start], x_length);
Ta, I'd be a little surprised if the driver is ever used for anything else. It does seem like there's potential for another steelseries mouse but looks like it's the same display size.

2024-09-10 11:28 UTC, sigprof commented on drivers/painter/ld7032/qp_ld7032.c
> +        memcpy(packet, &framebuffer[(y_pos * (driver->panel_width >> 3)) + x_start], x_length);
Yeah, the only thing with LD7032 that I was able to find on AliExpress is https://www.aliexpress.com/item/1005006897048850.html, and the description says that the model is off production (it also uses an unusual FPC connector with 0.3mm pitch and two rows of contacts).

2024-09-11 00:43 UTC, tzarc approved these changes

2024-09-18 11:44 UTC, merged

2024-09-18 14:52 UTC, daskygit commented
Ta