Add `RGB_DEFAULT_DISABLED` macro configuration option
qmk/qmk_firmware pull request #20857
Opened 2023-05-11 03:16 UTC by Gondolindrim

## Description

Adds the possibility of defining RGB lighting disabled by deafult at  EEPROM initialization.

This is done through a macro in `config.h`:

```
#define RGB_DEFAULT_DISABLED
```

The macro works in the `rgblight.c` quantum driver setting enable to true if the macro is not enabled and false if it is.

An accompanying addition to the documentation is also pushed.

This was tested on a couple PCBs around; all STM32 though, but I am sure this should not pose an  issue for the AVR units.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-29 02:06 UTC, drashna approved these changes

2023-05-29 02:16 UTC, fauxpark reviewed
I'm thinking this should be inverted and default to `true` to be consistent with the other defines:
```c
#if !defined(RGBLIGHT_DEFAULT_ON)
#    define RGBLIGHT_DEFAULT_ON true
#endif
```

2023-05-30 04:15 UTC, Gondolindrim commented
> I'm thinking this should be inverted and default to `true` to be consistent with the other defines:
> 
> ```c
> #if !defined(RGBLIGHT_DEFAULT_ON)
> #    define RGBLIGHT_DEFAULT_ON true
> #endif
> ```

So the idea would be, if I want the RGB off by default I'd use

```c
#undef RGBLIGHT_DEFAULT_ON
```

?

2023-05-30 04:19 UTC, fauxpark commented
No, you'd set it to `false`.

2023-06-02 22:24 UTC, Gondolindrim commented
> No, you'd set it to `false`.

Done in https://github.com/qmk/qmk_firmware/pull/20857/commits/c253989fe83ede7e3e7c11e22a55b6b28e5dbb17

2023-06-03 01:14 UTC, fauxpark requested changes

2023-06-03 01:14 UTC, fauxpark commented on docs/feature_rgblight.md
> +|`RGBLIGHT_DEFAULT_ON`      |`1`                         |If defined  `0`, RGB lighting will be disabled (off) by default when EEPROM is initialized.                                |
```suggestion
|`RGBLIGHT_DEFAULT_ON`      |`true`                      |Enable RGB lighting upon clearing the EEPROM                           |
```

2023-06-03 01:14 UTC, fauxpark commented on quantum/rgblight/rgblight.c
> +#    define RGBLIGHT_DEFAULT_ON 1
```suggestion
#    define RGBLIGHT_DEFAULT_ON true
```

2023-06-03 01:14 UTC, fauxpark commented on quantum/rgblight/rgblight.c
>      rgblight_config.enable = 1;
```suggestion
    rgblight_config.enable = RGBLIGHT_DEFAULT_ON;
```

2023-06-03 01:14 UTC, fauxpark commented on quantum/rgblight/rgblight.c
> +    rgblight_config.speed = RGBLIGHT_DEFAULT_SPD;
```suggestion
```

2023-06-03 02:45 UTC, fauxpark requested changes

2023-06-03 02:45 UTC, fauxpark commented on docs/feature_rgblight.md
> +|`RGBLIGHT_DEFAULT_ON`      |`true`                      |Enable RGB lighting upon clearing the EEPROM                           |
```suggestion
|`RGBLIGHT_DEFAULT_ON`      |`true`                      |Enable RGB lighting upon clearing the EEPROM                                                                               |
```

2023-06-03 02:45 UTC, fauxpark commented on quantum/rgblight/rgblight.c
> +// If RGBLIGHT_DEFAULT_ON is set 0, RGBLIGHT will be disabled at EEPROM initialization.
```suggestion
```

2023-06-03 02:45 UTC, fauxpark commented on quantum/rgblight/rgblight.c
>      RGBLIGHT_SPLIT_SET_CHANGE_MODEHSVS;
```suggestion
    rgblight_config.mode   = RGBLIGHT_DEFAULT_MODE;
    rgblight_config.hue    = RGBLIGHT_DEFAULT_HUE;
    rgblight_config.sat    = RGBLIGHT_DEFAULT_SAT;
    rgblight_config.val    = RGBLIGHT_DEFAULT_VAL;
    rgblight_config.speed  = RGBLIGHT_DEFAULT_SPD;
    RGBLIGHT_SPLIT_SET_CHANGE_MODEHSVS;
```

2023-09-29 12:41 UTC, zvecr approved these changes

2023-09-29 13:50 UTC, fauxpark approved these changes

2023-09-29 13:53 UTC, merged