Add ScottoInvader Keyboard
qmk/qmk_firmware pull request #20941
Opened 2023-05-14 16:25 UTC by joe-scotto

Add ScottoInvader handwired keyboard

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-31 20:03 UTC, dunk2k commented on keyboards/handwired/scottokeebs/scottoinvader/info.json
> +        "LAYOUT_ortho_3x10_6": {
Entirely optional, but changing `LAYOUT_ortho_3x10_6` to `LAYOUT_split_3x5_3` will allow community layouts to automatically be assigned (namely miryoku).  
Would have to apply this change to all `keymap.c` files also.

Whilst this board isn't a split body or split key-well, the key arrangement is identical to the suggested LAYOUT.

2023-06-01 14:19 UTC, drashna approved these changes

2023-06-01 14:52 UTC, fauxpark requested changes

2023-06-01 14:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoinvader/readme.md
> +    make handwired/jscotto/scottoinvader:default
```suggestion
    make handwired/scottokeebs/scottoinvader:default

Flashing example for this keyboard:

    make handwired/scottokeebs/scottoinvader:default
```

2023-06-01 14:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoinvader/readme.md
> +-   Hardware Availability: [Amazon](https://amazon.com)
```suggestion
* Keyboard Maintainer: [Joe Scotto](https://github.com/joe-scotto)
* Hardware Supported: ATmega32U4
* Hardware Availability: [Amazon](https://amazon.com)
```

2023-08-14 09:52 UTC, fauxpark approved these changes

2023-08-16 01:46 UTC, merged