Add ScottoSlant Keyboard
qmk/qmk_firmware pull request #20942
Opened 2023-05-14 16:40 UTC by joe-scotto

Add ScottoSlant handwired keyboard

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-01 14:18 UTC, drashna approved these changes

2023-06-01 14:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/readme.md
> +    make handwired/jscotto/scottoslant:default
```suggestion
    make handwired/scottokeebs/scottoslant:default

Flashing example for this keyboard:

    make handwired/scottokeebs/scottoslant:default
```

2023-08-14 09:52 UTC, fauxpark requested changes

2023-08-14 09:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/info.json
> +        "LAYOUT_3x10_7": {
```suggestion
        "LAYOUT": {
```

2023-08-14 09:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/keymaps/default/keymap.c
> +    [1] = LAYOUT_3x10_7(
```suggestion
    [1] = LAYOUT(
```

2023-08-14 09:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/keymaps/scotto/keymap.c
> +    [4] = LAYOUT_3x10_7(
```suggestion
    [4] = LAYOUT(
```

2023-08-14 09:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/keymaps/scotto/keymap.c
> +    [5] = LAYOUT_3x10_7(
```suggestion
    [5] = LAYOUT(
```

2023-08-14 09:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/keymaps/scotto/keymap.c
> +    [6] = LAYOUT_3x10_7(
```suggestion
    [6] = LAYOUT(
```

2023-08-14 09:52 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottoslant/keymaps/scotto/keymap.c
> +    [7] = LAYOUT_3x10_7(
```suggestion
    [7] = LAYOUT(
```

2023-08-31 23:19 UTC, fauxpark requested changes
Please revert the submodule changes.

2023-08-31 23:26 UTC, joe-scotto commented
I believe this is done for all PRs now... please correct me if `git revert` is incorrect.

2023-09-10 00:17 UTC, fauxpark approved these changes

2023-09-21 02:31 UTC, merged