add keyboard keymap
qmk/qmk_firmware pull request #20984
Opened 2023-05-18 17:09 UTC by linlin012

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-18 17:49 UTC, waffle87 commented
A valid `keymaps` directory is missing, which is required.

2023-05-18 19:11 UTC, noroadsleft commented on keyboards/onepiece/qk21/logo-JZ.png
Per the [Keyboard Guidelines](https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=imagehardware-files):

> In an effort to keep the repo size down we’re no longer accepting binary files of any format, with few exceptions. Hosting them elsewhere (such as https://imgur.com/) and linking them in the readme.md is preferred.

Please remove this file (`git rm --cached keyboards/onepiece/qk21/logo-JZ.png`) and host it on an external service.

2023-05-19 09:42 UTC, linlin012 commented on keyboards/onepiece/qk21/logo-JZ.png
I have updated the document, what should I do to resubmit it? I am a beginner.

2023-05-20 07:19 UTC, drashna commented on keyboards/onepiece/qk21/config.h
> +#define RGB_DI_PIN B7
This is changing at the end of the month. 
```suggestion
#define RGB_DI_PIN B7
#define WS2812_DI_PIN B7
```
or just:
```
#define WS2812_DI_PIN B7
```
(will fail to compile until develop is merged at end of month)

2023-05-20 07:21 UTC, drashna commented on keyboards/onepiece/qk21/logo-JZ.png
Specifically, any changes to the branch that was used to create the PR will also update the PR, automatically.

2023-05-20 07:26 UTC, drashna requested changes
Is missing a default keymap. That needs to be added.

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/info.json
> +        "vid": "0x1EA7"
This vendor ID is in use, and should be changed.
https://www.the-sz.com/products/usbid/index.php?v=0x1EA7&p=&n=

Specifically, anything above 0x4000 is unassigned, though the further past this, the better. 

Also, you can check against Vendor ID's used in QMK here: https://yanfali.github.io/qmk_usb_usage/

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/qk21.c
> +}};
This structure should be moved to the info.json file. 

You can run `qmk info -kb onepiece/qk21 -f json` to generate the config, automatically.

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/qk21.h
This file can be completely removed.

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/qk21.c
> +#include "qk21.h"
```suggestion
#include "quantum.h"

```

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
Should be filled out.

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/info.json
> +    },
Is the default values, isn't needed.
```suggestion
```

2023-05-20 07:26 UTC, drashna commented on keyboards/onepiece/qk21/info.json
> +    "layouts": {
```suggestion
    "community_layouts": ["numpad_6x4"],
    "layouts": {
```

2023-10-05 01:49 UTC, closed without merging