Add 'dactyl_tracer' keyboard
qmk/qmk_firmware pull request #20993
Opened 2023-05-19 21:52 UTC by dunk2k

## Description

`readme.md` mentions #20517

If #20447 is merged, can this keyboard's directory be renamed to `tracer` and placed under directory `handwired/dactyl` i.e. `handwired/dactyl/tracer` 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-20 21:32 UTC, drashna commented on keyboards/handwired/dactyl_tracer/readme.md
> +The following [layout](/layouts/) is supported:
Not sure this should be a link, though. 
```suggestion
The following [community layout](/layouts/) is supported:
```

2023-05-29 00:52 UTC, drashna approved these changes

2023-05-29 01:57 UTC, fauxpark requested changes

2023-05-29 01:57 UTC, fauxpark commented on keyboards/handwired/dactyl_tracer/info.json
> +    "diode_direction": "COL2ROW",
```suggestion
    "diode_direction": "COL2ROW",
    "debounce": 15,
```

2023-05-29 01:57 UTC, fauxpark commented on keyboards/handwired/dactyl_tracer/config.h
> +
```suggestion
```

2023-08-31 23:12 UTC, fauxpark approved these changes

2023-09-03 04:16 UTC, drashna requested changes

2023-09-03 04:16 UTC, drashna commented on keyboards/handwired/dactyl_tracer/keymaps/default/config.h
> +/* mouse config */
```suggestion
#pragma once

/* mouse config */
```

2023-09-03 04:16 UTC, drashna commented on keyboards/handwired/dactyl_tracer/keymaps/via/config.h
> +/* mouse config */
```suggestion
#pragma once

/* mouse config */
```

2023-09-23 04:44 UTC, drashna approved these changes

2023-09-23 04:45 UTC, merged