[Keyboard] Add new keyboard soda/mango
qmk/qmk_firmware pull request #21014
Opened 2023-05-22 07:57 UTC by gezhaoyou

## Description

 Add new keyboard soda/mango
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-22 15:14 UTC, zvecr requested changes
From <https://docs.qmk.fm/#/pr_checklist?id=keyboard-prs>

```
info.json
With the move to [data driven](https://docs.qmk.fm/#/data_driven_config) keyboard configuration, we encourage contributors to utilise as many features as possible of the info.json [schema](https://github.com/qmk/qmk_firmware/blob/master/data/schemas/keyboard.jsonschema).
the mandatory elements for a minimally complete info.json at present are:
valid URL
valid maintainer
valid USB VID/PID and device version
displays correctly in Configurator (press Ctrl+Shift+I to preview local file, turn on fast input to verify ordering)
layout definitions should include matrix positions, so that LAYOUT macros can be generated at build time
should use standard definitions if applicable
use the Community Layout macro names where they apply (preferred above LAYOUT/LAYOUT_all)
If the keyboard only has a single electrical/switch layout:
use LAYOUT as your macro name, unless a community layout already exists
If the keyboard has multiple electrical/switch layouts:
include a LAYOUT_all which specifies all possible layout positions in the electrical matrix
use alternate layout names for all other possible layouts, preferring community layout names if an equivalent is available (e.g. LAYOUT_tkl_ansi, LAYOUT_ortho_4x4 etc.)
Microcontroller and bootloader
Diode Direction (if not using direct pins)
the following are required to be configured in info.json if necessary
Direct pin configuration
Backlight Configuration (where applicable)
Split keyboard configuration (where applicable)
Encoder Configuration
Bootmagic Configuration
LED Indicator Configuration
```

2023-05-22 15:14 UTC, zvecr commented on keyboards/soda/mango/keymaps/default/keymap.c
> +
```suggestion
```

2023-05-22 15:14 UTC, zvecr commented on keyboards/soda/mango/chconf.h
This file should be removed

2023-05-24 04:48 UTC, drashna requested changes

2023-05-24 04:48 UTC, drashna commented on keyboards/soda/mango/config.h
> +#define RGB_DI_PIN A2
This is changed in develop, and lands on master in a week.  To ensure that it compiles: 
```suggestion
#define RGB_DI_PIN A2
#define WS2812_DI_PIN A2
```

2023-05-24 04:48 UTC, drashna commented on keyboards/soda/mango/mango.c
> +led_config_t g_led_config = {
This should be moved to the info.json config.  You can run `qmk info -k soda/mango -f json` for assistance with that.

2023-05-24 04:48 UTC, drashna commented on keyboards/soda/mango/mango.h
> +#define LAYOUT_numpad_5x4( \
As above -> info.json.

2023-06-01 14:24 UTC, closed without merging