Remove `dactyl_manuform` variant `3x5_3`
qmk/qmk_firmware pull request #21015
Opened 2023-05-22 10:33 UTC by dunk2k

Requesting the removal of 3x5_3 variant from dactyl manuform for the following reasons:
1. Doesn't conform to Dactyl ManuForm variant convention
2. The readme shows the `3x5_3` is a case design variation, rather than there being any electronic/firmware significance. e.g. The Redox ManuForm is a case design variation of and electronically identical to the Redox, yet there's no `redox_manuform` keyboard in QMK.
3. There are plenty of native LAYOUT_split_3x5_3 keyboards (19 counted on develop branch) that are electronically identical to the `3x5_3` (e.g. `crbkd`, `maple_computing/minidox`, `bastardkb/skeletyl`) 

## Description

Removed `3x5_3` dir from `keyboards/handwired/dactyl_manuform` dir

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-24 04:49 UTC, drashna requested changes
Name changes should also include an entry in `/data/mappings/keyboard_aliases.json`

2023-05-24 07:07 UTC, dunk2k commented
@drashna I've added keyboard alias as of commit [0af8520](https://github.com/qmk/qmk_firmware/pull/21015/commits/0af8520882cca45503f77ef20f60126b9c0945dd)

That more like it chief?

2023-07-11 15:28 UTC, drashna approved these changes

2023-07-20 20:03 UTC, nooges approved these changes

2023-07-20 20:03 UTC, merged