Add Neely 65 PCB
qmk/qmk_firmware pull request #21027
Opened 2023-05-23 13:43 UTC by ToastyStoemp

## Description

Add firmware for the Neely65 PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-23 17:17 UTC, waffle87 requested changes

2023-05-23 17:17 UTC, waffle87 commented on keyboards/wolf/neely65/keymaps/via/keymap.c
> +    _LAYER3,
```suggestion
    _LAYER1
```

2023-05-23 20:01 UTC, zvecr requested changes

2023-05-23 20:01 UTC, zvecr commented on keyboards/wolf/neely65/keymaps/via/keymap.c
> +*/
```suggestion
// Copyright 2023 contact@vwolf.be
```

2023-05-23 20:01 UTC, zvecr commented on keyboards/wolf/neely65/keymaps/default/keymap.c
> +*/
```suggestion
// Copyright 2023 contact@vwolf.be
```

2023-05-24 04:51 UTC, fauxpark requested changes

2023-05-24 04:51 UTC, fauxpark commented on keyboards/wolf/neely65/readme.md
> +![Neely65](https://i.imgur.com/qu6fxXS.jpeg)
```suggestion
![Neely65](https://i.imgur.com/qu6fxXSh.jpeg)
```

2023-05-26 04:17 UTC, fauxpark requested changes

2023-05-26 04:17 UTC, fauxpark commented on keyboards/wolf/neely65/readme.md
> +
```suggestion
```

2023-05-26 04:17 UTC, fauxpark commented on keyboards/wolf/neely65/readme.md
> +	make wolf/neely65:default
```suggestion
    make wolf/neely65:default
```

2023-07-03 20:05 UTC, drashna approved these changes

2023-07-04 01:10 UTC, fauxpark approved these changes

2023-07-07 21:20 UTC, merged