[Keyboard] Add the Zed65 rev.1 PCB
qmk/qmk_firmware pull request #21043
Opened 2023-05-25 06:04 UTC by mechlovin

## Description

Add the Zed65 Rev. 1 PCB.
Thanks.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-25 15:31 UTC, zvecr requested changes

2023-05-25 15:31 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/rules.mk
> +RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow
```suggestion
```

2023-05-25 15:31 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/keymaps/default/readme.md
This file can be removed

2023-05-25 15:31 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/keymaps/via/keymap.c
> +
```suggestion
    )
```

2023-05-25 15:31 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/keymaps/default/keymap.c
> +
```suggestion
    )
```

2023-05-25 15:31 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/info.json
> +        "backlight": false
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgblight": true
```

2023-05-25 15:31 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/info.json
> +        "LAYOUT_all": {
Providing only `LAYOUT_all` is invalid

2023-05-29 00:26 UTC, drashna requested changes

2023-05-29 00:26 UTC, drashna commented on keyboards/mechlovin/zed65/rev1/config.h
> +#define RGB_DI_PIN A7
```suggestion
#define WS2812_DI_PIN A7
```

2023-05-29 00:26 UTC, drashna commented on keyboards/mechlovin/zed65/rev1/readme.md
> +![Zed65](https://i.imgur.com/IbsSLb6.jpeg)
```suggestion
![Zed65](https://i.imgur.com/IbsSLb6h.jpeg)
```

2023-06-01 08:39 UTC, drashna approved these changes

2023-06-03 06:54 UTC, waffle87 requested changes

2023-06-03 06:54 UTC, waffle87 commented on keyboards/mechlovin/zed65/rev1/config.h
> +#    define RGBLIGHT_EFFECT_TWINKLE
```suggestion
#define WS2812_SPI SPID1 // default: SPID1
#define WS2812_SPI_MOSI_PAL_MODE 6 // MOSI pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 5
#define WS2812_SPI_USE_CIRCULAR_BUFFER
```

2023-06-03 06:54 UTC, waffle87 commented on keyboards/mechlovin/zed65/rev1/info.json
> +    },
```suggestion
    },
    "rgblight": {
        "pin": "A7",
        "led_count": 24,
        "sleep": true,
        "animations": {
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
        }
    },
```

2023-06-03 06:54 UTC, waffle87 commented on keyboards/mechlovin/zed65/rev1/info.json
> +    "layouts": {
```suggestion
    "community_layouts": ["65_ansi_blocker_tsangan"],
    "layouts": {
```

2023-06-03 07:00 UTC, waffle87 reviewed
Sorry, forgot a couple.

2023-06-03 07:00 UTC, waffle87 commented on keyboards/mechlovin/zed65/rev1/info.json
> +    },
```suggestion
    },
    "ws2812": {
        "driver": "spi"
    },
```

2023-06-03 07:00 UTC, waffle87 commented on keyboards/mechlovin/zed65/rev1/rules.mk
> +WS2812_DRIVER = spi
```suggestion
# This file intentionally left blank
```

2023-06-03 07:03 UTC, waffle87 approved these changes

2023-06-03 07:03 UTC, merged

2023-06-03 08:59 UTC, keyboard-magpie commented
Failing CI on missing diode directions- @mechlovin is this row2col or col2row

2023-06-03 09:02 UTC, mechlovin commented
col2row on zed65/config.h.
Should I move it from config.h to info.json?

2023-06-03 09:03 UTC, keyboard-magpie commented
@mechlovin thanks for prompt response, will need to be in info.json, seems to have been overlooked.

Needs a line like `  "diode_direction": "COL2ROW",` 

Will need a new PR if possible please as bugfix.

2023-06-03 09:04 UTC, mechlovin commented
I will. thanks.