[keyboard] Phoenix
qmk/qmk_firmware pull request #21051
Opened 2023-05-26 08:29 UTC by yiancar

Initial commit for Phoenix.
This is my first time doing fully json PR plz be kind:)

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-26 10:53 UTC, zvecr requested changes

2023-05-26 10:53 UTC, zvecr commented on keyboards/cablecardesigns/phoenix/info.json
> +        "rgblight": false
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true
```

2023-05-26 14:37 UTC, yiancar commented on keyboards/cablecardesigns/phoenix/config.h
Done:)

2023-05-28 00:18 UTC, drashna approved these changes

2023-06-02 07:45 UTC, keyboard-magpie approved these changes

2023-06-02 07:45 UTC, merged