Feature/ctrl dvp layout
qmk/qmk_firmware pull request #21069
Opened 2023-05-28 13:36 UTC by sebosp

Dvorak programmer setup for Massdrop CTRL.

## Description

Provides Dvorak Programmer (dvp) on the first layer.
The second layer is for controlling of LEDs, volume, etc.
The third layer is the original qwerty setup.

To switch between the layers the key PAUSE is overriden:
- On dvp (layer 0) -> Pause switches to led control layer (layer 1).
- On led control layer (layer 1) -> Pause switches to original qwerty factory setup (layer 2).
- On original qwerty (layer 2) -> Pause switches to dvp layer (layer 0).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Initial setup for dvorak programmer (dvp).

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-28 23:46 UTC, drashna commented on keyboards/massdrop/ctrl/keymaps/dvp/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-05-29 19:44 UTC, drashna approved these changes

2023-05-29 23:34 UTC, fauxpark requested changes

2023-05-29 23:34 UTC, fauxpark commented on keyboards/massdrop/ctrl/keymaps/dvp/README.md
> +Must be downloaded, unzipped and placed somewhere in the $PATH
```suggestion
```

2023-08-17 08:58 UTC, dunk2k approved these changes

2023-08-21 21:00 UTC, fauxpark requested changes

2023-08-21 21:00 UTC, fauxpark commented on keyboards/massdrop/ctrl/keymaps/dvp/README.md
Please rename this file to lowercase.

2023-08-29 17:32 UTC, closed without merging

2023-08-29 17:32 UTC, zvecr commented
Unfortunately since this PRs creation, QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

In the near future we will be providing a more user focused workflow for keymaps, but till then the suggestion is to keep changes in your own fork.

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.