Add Scottomouse Handwired Macropad
qmk/qmk_firmware pull request #21074
Opened 2023-05-28 22:49 UTC by joe-scotto

## Description

Added handwired ScottoMouse macropad with default and scotto keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-28 22:53 UTC, zvecr requested changes

2023-05-28 22:53 UTC, zvecr commented on keyboards/handwired/scottokeebs/scottomouse/rules.mk
> +BOOTLOADER = rp2040
This is already specified in info.json (and thus produces lint warnings)
```suggestion
# This file intentionally left blank
```

2023-05-28 23:32 UTC, drashna approved these changes

2023-05-29 01:53 UTC, fauxpark requested changes

2023-05-29 01:53 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottomouse/info.json
> +                { "matrix": [0, 5], "x": 5, "y": 0 }
```suggestion
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [0, 2], "x": 2, "y": 0},
                {"matrix": [0, 3], "x": 3, "y": 0},
                {"matrix": [0, 4], "x": 4, "y": 0},
                {"matrix": [0, 5], "x": 5, "y": 0}
```

2023-06-02 05:13 UTC, filterpaper commented on keyboards/handwired/scottokeebs/scottomouse/readme.md
> +-   Hardware Availability: [ScottoKeebs](https://scottokeebs.com), [Amazon](https://amazon.com), [Ali](https://amazon.com)
```suggestion
*   Keyboard Maintainer: [Joe Scotto](https://github.com/joe-scotto)
*   Hardware Supported: Raspberry Pi Pico
*   Hardware Availability: [ScottoKeebs](https://scottokeebs.com), [Amazon](https://amazon.com), [Ali](https://amazon.com)
```

Template consistency suggestion.

2023-08-14 09:47 UTC, fauxpark requested changes

2023-08-14 09:47 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottomouse/info.json
> +        "LAYOUT_1x6": {
```suggestion
        "LAYOUT": {
```

2023-08-14 09:47 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottomouse/keymaps/default/keymap.c
> +    [0] = LAYOUT_1x6(
```suggestion
    [0] = LAYOUT(
```

2023-08-14 12:02 UTC, fauxpark requested changes

2023-08-14 12:02 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scottomouse/keymaps/scotto/keymap.c
> +    [0] = LAYOUT_1x6(
```suggestion
    [0] = LAYOUT(
```

2023-08-31 23:18 UTC, fauxpark requested changes
Please revert the submodule changes.

2023-08-31 23:23 UTC, joe-scotto commented
Done in [746798d](https://github.com/qmk/qmk_firmware/pull/21074/commits/746798d5eae2c81dd69ce08f2d9955c4d367855d)

2023-09-10 00:18 UTC, fauxpark approved these changes

2023-09-21 02:32 UTC, merged