[Keyboard] Adding OSAv2 Topre PCB
qmk/qmk_firmware pull request #21080
Opened 2023-05-29 16:24 UTC by blindassassin111

## Description

Adding the firmware for the OSAv2 topre pcb.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-05-29 17:22 UTC, zvecr requested changes

2023-05-29 17:22 UTC, zvecr commented on keyboards/viktus/osav2_topre/keymaps/default/keymap.c
> +                 KC_LSFT, KC_Z, KC_X,    KC_C, KC_V,   KC_B,       KC_B, KC_N,   KC_M, KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
`MO(1)` would go out of bounds.

2023-05-29 17:22 UTC, zvecr commented on keyboards/viktus/osav2_topre/keymaps/via/keymap.c
> +                 KC_LSFT, KC_Z, KC_X,    KC_C, KC_V,   KC_B,       KC_B, KC_N,   KC_M, KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
Same here.

2023-05-29 18:02 UTC, blindassassin111 commented on keyboards/viktus/osav2_topre/keymaps/default/keymap.c
> +                 KC_LSFT, KC_Z, KC_X,    KC_C, KC_V,   KC_B,       KC_B, KC_N,   KC_M, KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
Oops, forgot the second layer.

2023-06-05 20:29 UTC, blindassassin111 commented
Any changes still needed?

2023-06-05 20:37 UTC, waffle87 approved these changes

2023-06-11 06:26 UTC, drashna approved these changes

2023-06-11 06:27 UTC, merged