Add Scotto9 handwired macropad
qmk/qmk_firmware pull request #21105
Opened 2023-06-01 15:57 UTC by joe-scotto

## Description

Add Scotto36 handwired keyboard along with `default` keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-02 05:03 UTC, filterpaper requested changes

2023-06-02 05:03 UTC, filterpaper commented on keyboards/handwired/scottokeebs/scotto9/info.json
> +    "bootloader": "caterina",
```suggestion
```

Caterina bootloader is implied with ["promicro" development board](https://github.com/qmk/qmk_firmware/blob/master/data/mappings/defaults.hjson#L3-L7).

Can you proactively update this in your current active PRs?

2023-06-02 05:03 UTC, filterpaper commented on keyboards/handwired/scottokeebs/scotto9/info.json
> +    "url": "",
```suggestion
```

2023-06-06 05:19 UTC, drashna commented on keyboards/handwired/scottokeebs/scotto9/readme.md
> +![Scotto9](https://imgur.com/inbmNSEh.jpeg)
```suggestion
![Scotto9](https://i.imgur.com/inbmNSEh.jpeg)
```

2023-06-07 09:59 UTC, fauxpark approved these changes

2023-06-11 06:47 UTC, drashna approved these changes

2023-06-11 07:52 UTC, merged