Update G60BLE folder to allow firmware to use Bluetooth with QMK keymaps
qmk/qmk_firmware pull request #21120
Opened 2023-06-02 23:10 UTC by will-hedges

## Description

Original G60BLE folder did not contain code in `rules.mk` to use the Bluetooth driver for this keyboard, which was present in the G60 folder. As such, if the G60BLE was flashed with a .hex compiled from source, it could be paired over Bluetooth but would not function.

* updated `g60ble/rules.mk` to enable Bluetooth and custom driver
* reorganized `g60ble/config.h` to better match `g60/config.h`
* copied `matrix_diagram.md` to G60BLE folder and added 2.75u RShift
* added my personal keymap to demonstrate successful compile and sending tap dances over Bluetooth

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-03 03:49 UTC, will-hedges commented on keyboards/bioi/g60ble/rules.mk
> +
Done. 

Reverted licensing changes since I am not technically adding any files, only changing/copying

2023-06-03 03:50 UTC, fauxpark requested changes

2023-06-03 03:50 UTC, fauxpark commented on keyboards/bioi/g60ble/keymaps/chemicalwill/keymap.c
> +#include "g60ble_tap_dances.c"
Do not include .c files.

2023-06-03 03:51 UTC, will-hedges commented
Did not add any files, only changes/updates, so I reverted the licensing changes.

2023-06-03 06:16 UTC, waffle87 requested changes

2023-06-03 06:16 UTC, waffle87 commented on keyboards/bioi/g60ble/keymaps/chemicalwill/keymap.c
This file is missing a license header.

2023-06-03 06:16 UTC, waffle87 commented on keyboards/bioi/g60ble/keymaps/chemicalwill/keymap.c
> +#define _FN1 2
```suggestion
enum layers {
    _QWER,
    _WORK,
    _FN1
};
```

2023-06-03 06:16 UTC, waffle87 commented on keyboards/bioi/g60ble/matrix_diagram.md
> +# Matrix Diagram for Basic IO Instruments G60
```suggestion
# Matrix Diagram for Basic IO Instruments G60BLE
```

2023-06-03 20:18 UTC, waffle87 approved these changes

2023-06-04 01:30 UTC, fauxpark approved these changes

2023-06-05 10:11 UTC, drashna approved these changes

2023-06-05 20:34 UTC, merged