[Keyboard] Zed65 Rev.1 - Update info.json
qmk/qmk_firmware pull request #21122
Opened 2023-06-03 09:09 UTC by mechlovin

## Description

Update diode direction. Thank to @keyboard-magpie 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-03 09:09 UTC, keyboard-magpie approved these changes

2023-06-03 09:17 UTC, fauxpark commented
Should go in the rev1 info.json instead. `rgblight.pin` has also been renamed to `ws2812.pin`.

2023-06-03 17:28 UTC, zvecr approved these changes

2023-06-03 17:32 UTC, zvecr requested changes

2023-06-03 17:32 UTC, zvecr commented on keyboards/mechlovin/zed65/info.json
> +    "diode_direction": "COL2ROW"
```suggestion
```

2023-06-03 17:32 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/info.json
>      },
Ideally this would be on line 18, but i cannot make the suggestion there
```suggestion
    },
    "diode_direction": "COL2ROW"
```

2023-06-04 01:10 UTC, zvecr commented on keyboards/mechlovin/zed65/rev1/info.json
> +    "diode_direction": "COL2ROW"
```suggestion
    "diode_direction": "COL2ROW",
```

2023-06-04 01:10 UTC, zvecr approved these changes

2023-06-04 01:10 UTC, merged