BM40 keymap/dan layout update
qmk/qmk_firmware pull request #21123
Opened 2023-06-03 13:02 UTC by syntax-magic

BM40 Keyboard layout update for keymaps/dan.

## Description

   - Moved RGB keys to RightFN layer
   - Added mouse keys in MOU layer
   - Removed keys that use tap dance

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-03 17:39 UTC, zvecr commented on keyboards/kprepublic/bm40hsrgb/keymaps/dan/rules.mk
> +HOLD_ON_OTHER_KEY_PRESS = no
These are not `rules.mk` settings, so specifying them here will do absolutely nothing.
```suggestion
```

2023-06-03 17:40 UTC, zvecr commented on keyboards/kprepublic/bm40hsrgb/keymaps/dan/rules.mk
> +TAP_DANCE_ENABLE = no
Setting this to "no" is the default, so also does nothing
```suggestion
```

2023-06-03 17:41 UTC, zvecr requested changes

2023-06-03 17:41 UTC, zvecr commented on keyboards/kprepublic/bm40hsrgb/keymaps/dan/keymap.c
> +// tap_dance_action_t tap_dance_actions[] = {
We also do not want commented out code in the repo, which there is a fair amount introduced in this file.

2023-06-05 08:22 UTC, drashna approved these changes

2023-09-21 02:08 UTC, fauxpark approved these changes

2023-12-05 18:19 UTC, zvecr commented
Unfortunately QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

QMK Firmware now officially supports [storing user keymaps outside of the normal QMK Firmware repository](https://docs.qmk.fm/#/newbs_external_userspace), allowing users to maintain their own keymaps without having to fork, modify, and maintain a copy of QMK Firmware themselves. 

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.

2023-12-05 18:19 UTC, closed without merging