[Core] RGB matrix ws2812 update
qmk/qmk_firmware pull request #21135
Opened 2023-06-05 13:33 UTC by Xelus22

## Description

Goes with https://github.com/qmk/qmk_firmware/pull/21134 . This change makes it so that the WS2812 doesn't update every cycle if no RGB LEDs have updated colour. (mainly for static and bitbang applications)

**Untested because I don't have any WS2812 only rgb matrix boards**

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* WS2812 don't update every RGB Matrix cycle

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-06 04:32 UTC, drashna reviewed
Lint angry.

Otherwise tested, and works well.

2023-06-06 04:32 UTC, drashna commented on quantum/rgb_matrix/rgb_matrix_drivers.c
> +bool updateLEDs = false;
```suggestion
bool     updateLEDs = false;
```

2023-06-06 04:32 UTC, drashna commented on quantum/rgb_matrix/rgb_matrix_drivers.c
> +    updateLEDs = true;
And: 
```suggestion
    if (rgb_matrix_ws2812_array[i].r == r && rgb_matrix_ws2812_array[i].g == g && rgb_matrix_ws2812_array[i].b == b) {
        return;
    }

    updateLEDs                   = true;
```

2023-06-06 10:03 UTC, ToastyStoemp commented
Also tested this on Atmega32u4 PCB (126 WS2812 leds)
Matrix scan frequency:

- Master branch: 

1. Off							789
2. Solid						650
3. Gradient Up/Down	424
4. Cycle Left/Right		418
5. Cycle Spiral				286

- Xelus WS2812 update branch:

1. Off							799
2. Solid						733
3. Gradient Up/Down	453
4. Cycle Left/Right		414
5. Cycle Spiral				284

2023-06-06 17:56 UTC, drashna approved these changes

2023-06-08 01:23 UTC, zvecr commented on quantum/rgb_matrix/rgb_matrix_drivers.c
> +bool     updateLEDs = false;
Jumping from a snake case variable to `updateLEDs` is a little inconsistent.

Should probably be called something like `ws2812_dirty` or `update_required`.

2023-06-08 20:05 UTC, zvecr requested changes
Lint fixes

2023-06-08 20:05 UTC, zvecr commented on quantum/rgb_matrix/rgb_matrix_drivers.c
> +bool ws2812_dirty = false;
```suggestion
bool     ws2812_dirty = false;
```

2023-06-08 23:46 UTC, zvecr commented on quantum/rgb_matrix/rgb_matrix_drivers.c
> +    ws2812_dirty = true;
```suggestion
    ws2812_dirty                 = true;
```

2023-06-08 23:48 UTC, zvecr approved these changes

2023-06-09 00:00 UTC, merged