Add new keyboard: vinhcatba/uncertainty
qmk/qmk_firmware pull request #21142
Opened 2023-06-06 12:51 UTC by vinhcatba

## Description
Add a new keyboard named Uncertainty

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-06 14:12 UTC, vinhcatba commented
I have rebased. When I run `git status` on Git Bash, it showed `nothing to commit, working tree clean` but on QMK MYSYS:
```
On branch dev_uncertainty
Your branch is up to date with 'origin/dev_uncertainty'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   ../../../lib/chibios (modified content)
        modified:   ../../../lib/chibios-contrib (modified content)
        modified:   ../../../lib/googletest (modified content)
        modified:   ../../../lib/lvgl (modified content)
        modified:   ../../../lib/pico-sdk (modified content)
        modified:   ../../../lib/printf (modified content)
        modified:   ../../../lib/vusb (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
```

2023-06-07 11:34 UTC, vinhcatba commented
> The instructions below presume you have `vinhcatba` as your `origin` and `qmk` as your upstream.
> 
> 1. Run `git restore lib` to undo whatever's been changed in that folder.
> 2. Check out `upstream/master`.
> 3. Run `qmk doctor` and make a note of the commit listed for `lib/chibios` (to save you the trouble, it is currently `11edb1610`).
> 4. Check out `dev_uncertainty`.
> 5. Run `cd lib/chibios && git checkout 11edb1610`
> 6. Commit the changes.

When I run to step 6, it said:
```
HEAD detached at 11edb1610
nothing to commit, working tree clean
```

2023-06-10 10:40 UTC, elpekenin commented on keyboards/vinhcatba/uncertainty/uncertainty.c
> +    switch (keycode) {
You don't want to ignore user-level processing
```suggestion   
     if (!process_record_user(keycode, record)) {
        return false;
    }

    switch (keycode) {
 ```

2023-06-11 06:57 UTC, drashna commented on keyboards/vinhcatba/uncertainty/bongo.h
This isn't being used as a header file, but a full on source file. 

It should be renamed to bongo.c, and added by `SRC += bongo.c` in the rules.mk file, or moved to uncertainty.c

2023-06-11 15:22 UTC, vinhcatba commented on keyboards/vinhcatba/uncertainty/bongo.h
> It should be renamed to bongo.c, and added by SRC += bongo.c in the rules.mk file
I did this (without including it in any file) but got `implicit declaration of function 'draw_bongo'` 
> or moved to uncertainty.c
I included bongo.c in uncertainty.c (without `SRC += bongo.c` in rules.mk) and it worked. So I'm guessing this is the correct way?

2023-06-11 15:48 UTC, elpekenin commented on keyboards/vinhcatba/uncertainty/bongo.h
Correct way is to `SRC +=` it, as said.

In order for other files to use its content, you need to create a header (`.h`) file that "describes" them, and that's what you include.

eg a file named `functions.h`(you should name it `bongo.h`, but names dont really have to match), containing this code...
```c
#pragma once

void draw_bongo(bool minimal); // remove the `static` qualifier from it on the `.c` file
``` 
would make any file that does `#include "functions.h"` know that there's a `draw_bongo` function, and what their input(s) and output are

2023-06-18 10:27 UTC, vinhcatba commented
Hello, is there any change I need to make in order to merge? I've done all your suggestions. Thanks

2023-07-03 19:18 UTC, drashna requested changes

2023-07-03 19:18 UTC, drashna commented on keyboards/vinhcatba/uncertainty/config.h
> +#define I2C_SDA_PAL_MODE 4
These are all the default values. No need to specify them.
```suggestion
```

2023-07-03 19:18 UTC, drashna commented on keyboards/vinhcatba/uncertainty/config.h
> +#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2
This may work better: 
```suggestion
#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_16_9
```

2023-07-03 19:18 UTC, drashna commented on keyboards/vinhcatba/uncertainty/rules.mk
> +ENCODER_MAP_ENABLE = yes
this should only be enabled at the keymap level.

2023-07-03 19:18 UTC, drashna commented on keyboards/vinhcatba/uncertainty/rules.mk
> +OLED_DRIVER = SSD1306
Is the default, no need to specify
```suggestion
```

2023-07-04 16:55 UTC, waffle87 requested changes

2023-07-04 16:55 UTC, waffle87 commented on keyboards/vinhcatba/uncertainty/info.json
> +        "console": true,
```suggestion
        "command": false,
        "console": false,
        "wpm": true,
```

2023-07-04 16:55 UTC, waffle87 commented on keyboards/vinhcatba/uncertainty/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-04 16:55 UTC, waffle87 commented on keyboards/vinhcatba/uncertainty/keymaps/default/rules.mk
> +WPM_ENABLE = yes
```suggestion
```

2023-07-04 16:55 UTC, waffle87 commented on keyboards/vinhcatba/uncertainty/keymaps/via/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-04 16:55 UTC, waffle87 commented on keyboards/vinhcatba/uncertainty/keymaps/via/rules.mk
> +
```suggestion
ENCODER_MAP_ENABLE = yes
```

2023-07-04 16:55 UTC, waffle87 commented on keyboards/vinhcatba/uncertainty/readme.md
> +![uncertainty](https://i.imgur.com/IKrn37B.jpeg)
```suggestion
![uncertainty](https://i.imgur.com/IKrn37Bh.jpeg)
```

2023-07-11 16:35 UTC, drashna approved these changes

2023-08-16 21:06 UTC, dunk2k requested changes

2023-08-16 21:06 UTC, dunk2k commented on keyboards/vinhcatba/uncertainty/keymaps/default/keymap.c
> +    [1] =   { ENCODER_CCW_CW(KC_BRID, KC_BRIU)  }
```suggestion
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(KC_BRID, KC_BRIU) }
```

2023-08-28 02:29 UTC, vinhcatba reviewed
add/remove spacing as suggested

2023-08-30 06:07 UTC, drashna requested changes

2023-08-30 06:07 UTC, drashna commented on keyboards/vinhcatba/uncertainty/config.h
> +#define RGBLIGHT_LED_MAP { 2,	3,	4,	5,	6,	0,	1,	7,	8,	9,	10,	11,	12,	13}    // index 5 = CAPS; index 6 = NUM
```suggestion
#define RGBLIGHT_LED_MAP { 2, 3, 4, 5, 6, 0, 1, 7, 8, 9, 10, 11, 12, 13}    // index 5 = CAPS; index 6 = NUM
```

2023-08-30 08:28 UTC, drashna approved these changes

2023-10-09 06:35 UTC, noroadsleft approved these changes
Looks good to me.

2023-10-09 06:35 UTC, merged

2023-10-09 06:35 UTC, noroadsleft commented
Thanks!