Add lindgrenj6 planck layout
qmk/qmk_firmware pull request #21155
Opened 2023-06-07 15:21 UTC by lindgrenj6

Adding my planck layout.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-11 07:06 UTC, drashna approved these changes

2023-06-21 03:03 UTC, waffle87 requested changes

2023-06-21 03:03 UTC, waffle87 commented on keyboards/planck/keymaps/lindgrenj6/keymap.c
> +
```suggestion
```

2023-06-21 03:03 UTC, waffle87 commented on keyboards/planck/keymaps/lindgrenj6/keymap.c
> +
The core [tri layer feature](https://docs.qmk.fm/#/feature_tri_layer) should be used instead.
```suggestion
```

2023-06-21 03:03 UTC, waffle87 commented on keyboards/planck/keymaps/lindgrenj6/readme.md
This file should be removed.

2023-06-21 18:41 UTC, waffle87 approved these changes

2023-06-21 18:42 UTC, merged