teleport/native: switch from wrongly used user to kb function, boost matrix scan rate
qmk/qmk_firmware pull request #21172
Opened 2023-06-08 12:59 UTC by ebastler

## Description
This PR makes a few changes to the Native keyboard. First, it enables LTO for all keymaps, and replaces a `keyboard_post_init_user()` function with `keyboard_post_init_kb()` in native.c - as far as I am aware, _user functions should be used in keymaps, _kb functions in board-wide code files.

In addition, on the highly customized "perfmode" keymaps, it will replace the matrix delays with nops and add `OPT=2` to rules.mk. Both together lead to a significant speed-up of matrix scan rates, from about 3 kHz to 13.5 kHz (disabled LEDs, or static LEDs together with PR #21134).

The board was originally tested and working fine with `OPT=3`, but I was told `3` could lead to issues with custom keymaps enabling other features by other users eventually, so decided to play safe and stay at `2`. 13.5 kHz is plenty.

This firmware has been tested over a few days on an ISO board without issues.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Native had _user function in native.c, replaced by _kb function

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-08 19:54 UTC, zvecr requested changes

2023-06-08 19:54 UTC, zvecr commented on keyboards/teleport/native/native.c
>      writePinHigh(B9);
```suggestion
    writePinHigh(B9);
    
    keyboard_post_init_user();
```

2023-06-10 21:45 UTC, drashna approved these changes

2023-09-29 11:18 UTC, zvecr approved these changes

2023-09-29 11:19 UTC, merged