[keybord]add 5075 keybord.
qmk/qmk_firmware pull request #21184
Opened 2023-06-09 08:29 UTC by jonylee1986

## Description
as title.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-09 18:33 UTC, adophoxia requested changes

2023-06-09 18:33 UTC, adophoxia commented on keyboards/akko/5108/keymaps/via/rules.mk
> +ENCODER_MAP_ENABLE = no
```suggestion

```
Since this board doesn't look like it's using an encoder, this flag shouldn't be needed

2023-06-10 00:53 UTC, waffle87 requested changes

2023-06-10 00:53 UTC, waffle87 commented on keyboards/akko/5108/5108.c
> +        writePin(LED_CAPS_LOCK_PIN, led_state.caps_lock);
This is already done at the core level.
```suggestion
    setPinOutput(LED_WIN_LOCK_PIN); // LED3 Win Lock
    writePinLow(LED_WIN_LOCK_PIN);
}

bool led_update_kb(led_t led_state) {
    bool res = led_update_user(led_state);
    if (res) {
```

2023-06-10 00:53 UTC, waffle87 commented on keyboards/akko/5108/config.h
> +#define I2C1_CLOCK_SPEED 400000 /* 400000 */
All default values as far as I can tell.
```suggestion
#define I2C1_SCL_PAL_MODE 4
```

2023-06-10 00:53 UTC, waffle87 commented on keyboards/akko/5108/info.json
> +        "mousekey": false,
Generally preferred to have mousekeys enabled, unless there's a good reason not to (eg. USB endpoints)
```suggestion
        "mousekey": true,
```

2023-06-10 00:53 UTC, waffle87 commented on keyboards/akko/5108/info.json
> +        "encoder": false,
```suggestion
```

2023-06-10 00:53 UTC, waffle87 commented on keyboards/akko/5108/rules.mk
> +
```suggestion
EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = spi_flash
```

2023-06-10 01:25 UTC, waffle87 commented on keyboards/akko/5108/5108.c
> +}
```suggestion

void keyboard_pre_init_kb(void) {
    setPinOutput(LED_WIN_LOCK_PIN); // LED3 Win Lock
    writePinLow(LED_WIN_LOCK_PIN);
    keyboard_pre_init_user();
}
```

2023-06-10 01:25 UTC, waffle87 commented on keyboards/akko/5108/readme.md
> +
```suggestion

## Bootloader
```

2023-06-12 01:40 UTC, drashna approved these changes

2023-06-13 22:29 UTC, surfaceflinger commented
It builds but I can't flash. I made some research and basically:

OEMs using ROYUAN boards distribute .rar files on their websites with firmware and "Royuan Toolbox" which is supposed to be open source according to information inside this application (ofc there's no source anywhere).

I also found this thread https://www.reddit.com/r/akkogear/comments/12ai3lg/used_wrong_firmware_for_akko_acr75_v2/ and it looks like these keyboards don't have DFU mode but instead are able to be flashed by just plugging them.

I got wb32-dfu-updater_cli to build but it can't find my device. Looking at dmesg after maaany retries, it always just shows up as `ROYUAN Akko Multi-modes Keyboard-B`.

While the code might indeed be working it would be nice to get proper instructions for flashing (unless I messed something up?)

2023-06-14 02:30 UTC, jonylee1986 commented
> It builds but I can't flash. I made some research and basically:
> 
> OEMs using ROYUAN boards distribute .rar files on their websites with firmware and "Royuan Toolbox" which is supposed to be open source according to information inside this application (ofc there's no source anywhere).
> 
> I also found this thread https://www.reddit.com/r/akkogear/comments/12ai3lg/used_wrong_firmware_for_akko_acr75_v2/ and it looks like these keyboards don't have DFU mode but instead are able to be flashed by just plugging them.
> 
> I got wb32-dfu-updater_cli to build but it can't find my device. Looking at dmesg after maaany retries, it always just shows up as `ROYUAN Akko Multi-modes Keyboard-B`.
> 
> While the code might indeed be working it would be nice to get proper instructions for flashing (unless I messed something up?)
> 
> Also, 5108 comes in S and B variants. Is this port compatible with both of them?

Currently, AKKO 5108QMK is not available for sale. What I have learned is that neither 5108S nor 5108B seems to support QMK @surfaceflinger

2023-06-14 06:26 UTC, waffle87 approved these changes

2023-06-14 06:27 UTC, merged

2024-10-22 09:42 UTC, jonylee1986 commented
This product was initially developed in response to a partner's request, but they later decided not to move forward with the project. As a result, the QMK version of the 5108S was never produced or sold as of today. Please note that this should not be confused with 5108B Plus, that is wireless and uses a completely different solution.