Planck Matrix Fixes
qmk/qmk_firmware pull request #21196
Opened 2023-06-10 00:54 UTC by jackhumbert

## Description

* Fixes non-default keymap compiling by defining a default encoder resolution value
* Fixes the initial matrix state
* Allows configuring/disabling watchdog timer
* Errors on encoder map being enabled (not currently supported)
* Removes some irrelevant ifdefs

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-11 05:27 UTC, drashna approved these changes

2023-06-11 23:17 UTC, fauxpark requested changes

2023-06-11 23:17 UTC, fauxpark commented on keyboards/planck/rev7/keymaps/default/config.h
>  // #define MIDI_TONE_KEYCODE_OCTAVES 2
```suggestion
```

2023-06-17 15:28 UTC, jackhumbert commented
Started trying to fix some planck keymaps, but didn't release how deep the problems went, so I reverted those & will save for later.

2023-06-21 00:32 UTC, merged