Add support for Chaz
qmk/qmk_firmware pull request #21207
Opened 2023-06-10 18:10 UTC by jasonhazel

## Description

Adding support for Chaz.

Had a previous PR for this board (#21091) but after seeing #21186 I closed it rework for RP2040 configurator support.  

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-10 18:59 UTC, dunk2k commented on keyboards/hazel/chaz/keymaps/jasonhazel/keymap.json
> +  "keymap": "default",
would you be able to change `"default"` to `"jasonhazel"` so this file matches directory it's located under? 🙂

2023-06-10 19:02 UTC, dunk2k commented on keyboards/hazel/chaz/promicro/info.json
> +    "maintainer": "jasonhazel",
`manufacturer`, `keyboard_name`, and `maintainer` lines are already specified in `info.json` in directory above, so they can be removed from this file.

2023-06-10 19:02 UTC, dunk2k commented on keyboards/hazel/chaz/rp2040ce/info.json
> +    "diode_direction": "COL2ROW",
`manufacturer`, `keyboard_name`, `maintainer`, and `url` lines are already specified in `info.json` in directory above, so they can be removed from this file.

2023-06-10 19:03 UTC, dunk2k commented on keyboards/hazel/chaz/rp2040ce/info.json
> +    "url": "https://github.com/hazels-garage/chaz",
`manufacturer`, `keyboard_name`, `maintainer`, and `url` lines are already specified in info.json in directory above, so they can be removed from this file.

2023-06-10 19:05 UTC, dunk2k commented on keyboards/hazel/chaz/rp2040ce/info.json
> +        "pid": "0x435A",
`vid` and `pid` are identical for both `rp2040ce` and `promicro` directories, would you be able to move these two lines to `info.json` in the directory above (keyboard level)?

2023-06-10 19:06 UTC, dunk2k commented on keyboards/hazel/chaz/promicro/info.json
> +        "pid": "0x435A",
`vid` and `pid` are identical for both `rp2040ce` and `promicro` directories, would you be able to move these two lines to `info.json` in the directory above (keyboard level)?

2023-06-10 19:10 UTC, jasonhazel commented
I saw some comments come through relating to info.json information duplicated across files.  I went to reply and they're missing now so I assume a single, all encompassing comment is coming?

There is a lot of overlap between the two version info.json.  Is it safe to assume all of that overlap can be moved to the top level info.json?

2023-06-10 19:18 UTC, dunk2k commented
@jasonhazel 

> There is a lot of overlap between the two version info.json. Is it safe to assume all of that overlap can be moved to the top level info.json?

you got it chief! There's argument for moving/merging the readme.md's to keyboard level, but I'll let the collaborators call that one 😉

2023-06-10 19:20 UTC, jasonhazel commented
@dunk2k right on.  I applied your suggestions and will wait to see what the collaborators say about the readme. Thanks for your feedback!

2023-06-10 19:21 UTC, dunk2k approved these changes

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/promicro/info.json
> +        "pid": "0x435A",
`vid` and `pid` are identical for both rp2040ce and promicro directories, would you be able to move these two lines to `info.json` in the directory above (keyboard level)?

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/rp2040ce/info.json
> +        "pid": "0x435A",
`vid` and `pid` are identical for both `rp2040ce` and `promicro` directories, would you be able to move these two lines to `info.json` in the directory above (keyboard level)?

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/rp2040ce/info.json
> +    "url": "https://github.com/hazels-garage/chaz",
`manufacturer`, `keyboard_name`, `maintainer`, and `url` lines are already specified in `info.json` in directory above, so they can be removed from this file.

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/promicro/info.json
> +    "url": "https://github.com/hazels-garage/chaz",
`manufacturer`, `keyboard_name`, `maintainer`, and `url` lines are already specified in `info.json` in directory above, so they can be removed from this file.

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/keymaps/jasonhazel/keymap.json
> +  "keymap": "default",
would you be able to change `"default"` to `"jasonhazel"`, on line 6, so this file matches directory it's located under? 🙂

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/rp2040ce/info.json
> +    "layouts": {
the layouts specified in `promicro` and `rp2040ce` are identical. Could you move "layouts" to `info.json` in directory above (keyboard level)? if done previously, please remove.

2023-06-10 19:21 UTC, dunk2k commented on keyboards/hazel/chaz/promicro/info.json
> +    "layouts": {
the layouts specified in `promicro` and `rp2040ce` are identical. Could you move "layouts" to `info.json` in directory above (keyboard level)?

2023-06-10 20:06 UTC, waffle87 requested changes

2023-06-10 20:06 UTC, waffle87 commented on keyboards/hazel/chaz/keymaps/default/keymap.json
> +  "documentation": "",
```suggestion
```

2023-06-10 20:06 UTC, waffle87 commented on keyboards/hazel/chaz/keymaps/jasonhazel/config.h
> +#define TAPPING_TERM 200
```suggestion
```

2023-06-10 20:06 UTC, waffle87 commented on keyboards/hazel/chaz/keymaps/jasonhazel/keymap.json
> +  "documentation": "",
```suggestion
```

2023-06-10 20:06 UTC, waffle87 commented on keyboards/hazel/chaz/promicro/readme.md
> +    make hazel/chaz:default:flash
This file could just be moved to the top level keyboard directory, and the `keyboards/hazel/chaz/rp2040ce/readme.md` one removed.
```suggestion
* Hardware Supported: Chaz, atmega32u4 ProMicro Compatible Controller, RP2040 Community Edition Compatible Controller
* Hardware Availability: [Hazel's Garage](https://shop.hazel.cc/products/chaz), [Open Source](https://github.com/hazels-garage/chaz)

Make example for this keyboard (after setting up your build environment):

    make hazel/chaz:default
    make hazel/chaz/rp2040ce:default

Flashing example for this keyboard:

    make hazel/chaz:default:flash
    make hazel/chaz/rp2040ce:default:flash
```

2023-06-10 20:29 UTC, waffle87 approved these changes

2023-06-12 20:17 UTC, drashna commented on keyboards/hazel/chaz/rp2040ce/info.json
> +{
It's using the same pinout as the pro micro, correct?

2023-06-13 02:13 UTC, jasonhazel commented
@drashna I realized converters could be specified via rules.mk.  I've rearranged things to a single top-level `info.json` with promicro pins specified and then a sub directory for `rp2040ce` with the converter defined in the `rules.mk`.

2023-06-13 02:15 UTC, fauxpark requested changes

2023-06-13 02:15 UTC, fauxpark commented on keyboards/hazel/chaz/rp2040ce/rules.mk
> +CONVERT_TO=rp2040_ce
Converters at keyboard level won't work with Configurator.

2023-07-04 02:30 UTC, closed without merging