[Keyboard] update xs60 to use rgb matrix and custom VIA indicators
qmk/qmk_firmware pull request #21210
Opened 2023-06-11 04:45 UTC by Xelus22

## Description

Update to use VIA indicators and RGB matrix.

Move things into info.json

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-11 16:25 UTC, zvecr commented
> keyboard updates and refactors (eg. to data driven) must go through develop to reduce master -> develop merge conflicts

and also any additional implementations of"VIA indicators" are currently not being accepted to the repo.

2023-06-12 02:25 UTC, Xelus22 commented
> > keyboard updates and refactors (eg. to data driven) must go through develop to reduce master -> develop merge conflicts
> 
> and also any additional implementations of"VIA indicators" are currently not being accepted to the repo.

Removed VIA indicators code

2023-06-13 08:32 UTC, drashna approved these changes

2023-06-13 17:45 UTC, fauxpark requested changes

2023-06-13 17:45 UTC, fauxpark commented on keyboards/xelus/xs60/soldered/rules.mk
> +WS2812_DRIVER = pwm
These can be moved to info.json.

2023-06-13 17:45 UTC, fauxpark commented on keyboards/xelus/xs60/hotswap/rules.mk
> +WS2812_DRIVER = pwm
As above.

2023-06-13 17:45 UTC, fauxpark commented on keyboards/xelus/xs60/hotswap/hotswap.c
> +led_config_t g_led_config = { {
As above.

2023-10-28 01:47 UTC, closed without merging