Add skyloong/Dt40 keyboard
qmk/qmk_firmware pull request #21237
Opened 2023-06-14 07:46 UTC by JZ-Skyloong

## Description
Add skyloong/Dt40 keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-15 03:34 UTC, drashna approved these changes

2023-06-15 04:03 UTC, waffle87 commented on keyboards/skyloong/dt40/keymaps/default/keymap.c
> +
```suggestion
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Base */
    [0] = LAYOUT(
        KC_ESC,     KC_Q,    KC_W,     KC_E,    KC_R,   KC_T,   KC_Y,     KC_U,      KC_O,      KC_I,    KC_BSPC,
       KC_CAPS,     KC_A,    KC_S,     KC_D,    KC_F,   KC_G,   KC_H,     KC_J,      KC_L,      KC_P,     KC_ENT,
       KC_LSFT,     KC_Z,    KC_X,     KC_C,    KC_V,   KC_B,   KC_N,     KC_M,   KC_RSFT,     KC_UP,    RGB_TOG,
       KC_LCTL,  KC_LALT,  KC_SPC,  KC_LWIN,  KC_SPC,   KC_K, KC_SPC, 	KC_APP,   KC_LEFT,   KC_DOWN,    KC_RGHT
    )
```

2023-06-15 10:21 UTC, fauxpark requested changes

2023-06-15 10:21 UTC, fauxpark commented on keyboards/skyloong/dt40/readme.md
> +    make skyloong/dt40:via:flash
```suggestion

Flashing example for this keyboard:

    make skyloong/dt40:default:flash
```

2023-06-16 02:29 UTC, JZ-Skyloong reviewed
Files were modified regarding to suggesting.

2023-06-17 01:12 UTC, JZ-Skyloong commented
QMK CI check shows a lack of two files crt1.td and chmtx.td, how can I correct it?

2023-07-10 01:14 UTC, JZ-Skyloong commented
PR has not been updated for a long time, what can I do next? @fauxpark @waffle87  @lesshonor  @drashna

2023-07-10 02:40 UTC, waffle87 approved these changes

2023-07-10 02:41 UTC, merged