Equals keyboard
qmk/qmk_firmware pull request #21230
Opened 2023-06-13 15:58 UTC by daysgobye

## Description
Added a new keyboard to the boardsource folder. 
it is called the equals 60 or equals 48 just a 5x12 with a snap off bottom row. So there are two folders in there for the 2 layouts.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-13 17:56 UTC, drashna commented on keyboards/boardsource/equals/48/keymaps/default/ui.c
This should be moved to the keyboard level.

And it may help to add bool callback functions so that the behavior can be overwritten.  For instance:
```c
__attribute__((weak)) bool ui_init_user(void) { return true; }

void ui_init(void) {
    if (!ui_init_user()) { return; }
    // rest of normal code
}
```

2023-06-13 17:58 UTC, drashna requested changes

2023-07-03 18:14 UTC, drashna requested changes

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/48/keymaps/cole/config.h
combo count should no longer be needed, and this file can be removed.

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/48/keymaps/cole/keymap.c
> +combo_t key_combos[COMBO_COUNT] = {
```suggestion
combo_t key_combos[] = {
```

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/60/keymaps/cole/config.h
As above. This file should be removed.

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/60/keymaps/cole/keymap.c
> +combo_t key_combos[COMBO_COUNT] = {
```suggestion
combo_t key_combos[] = {
```

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/config.h
> +#define RGB_DI_PIN GP21
```suggestion
#define WS2812_DI_PIN GP21
```

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/config.h
> +#define AUDIO_INIT_DELAY 1000
This isn't a value, it's either enabled or not.
```suggestion
#define AUDIO_INIT_DELAY
```

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/readme.md
> +![equals](https://i.imgur.com/c3adFqs.jpeg)
```suggestion
![equals](https://i.imgur.com/c3adFqsh.jpeg)
```

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/ui.c
> +void ui_task(void) {
Otherwise, there is no way to override this? 

```suggestion
__attribute__((weak)) void ui_task(void) {
```

2023-07-03 18:14 UTC, drashna commented on keyboards/boardsource/equals/ui.c
> +void                         ui_init(void) {
```suggestion

__attribute__((weak)) void ui_init(void) {
```

2023-07-09 16:01 UTC, daysgobye commented on keyboards/boardsource/equals/48/keymaps/default/ui.c
Im sorry I dont quite understand. This was meant to provide an example to users of what could be done with the tft. By keyboard level do you mean move it to 48.c?

2023-07-11 04:56 UTC, drashna approved these changes

2023-07-26 18:41 UTC, waffle87 approved these changes

2023-07-26 18:42 UTC, merged

2023-07-27 03:31 UTC, tzarc commented
Please re-raise this PR -- it was hastily merged without ensuring CI builds were successful.