[Keyboard] Add support for Infinity87 Rev. 3
qmk/qmk_firmware pull request #21239
Opened 2023-06-14 12:12 UTC by mechlovin

## Description
Add support for Infinity87 Rev. 3, APM32F103
Thanks.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-15 04:29 UTC, mechlovin commented on keyboards/mechlovin/infinity87/rev3/standard/readme.md
> +* Keyboard Maintainer: [Team Mechlovin'](https://github.com/mechlovin)
Thanks, I will change to "Mechlovin' Studio"

2023-07-14 07:38 UTC, drashna approved these changes

2023-07-21 10:32 UTC, mechlovin commented on keyboards/mechlovin/infinity87/rev3/rouge87/info.json
> +        "LAYOUT_ansi": {
Hi, the "2N" key does not exist, here is the KLE for Infinity87 Rev. 3: 
http://www.keyboard-layout-editor.com/#/gists/745c76d01db56d915b00330d6c2f4900
Thank you.

2023-07-23 01:02 UTC, fauxpark requested changes
Keyboard updates need to go through `develop`.

2023-10-12 04:41 UTC, drashna requested changes

2023-10-12 04:41 UTC, drashna commented on keyboards/splitkb/aurora/sofle_v2/rev1/config.h
> +<<<<<<<< HEAD:keyboards/splitkb/aurora/sofle_v2/rev1/config.h
merge conflists

2023-10-12 04:41 UTC, drashna commented on keyboards/mechlovin/infinity87/rev3/standard/config.h
> +#define WS2812_SPI SPID2
```suggestion
#define WS2812_SPI_DRIVER SPID2
```

2024-01-10 01:50 UTC, closed without merging