Lilith101 keyboard addition
qmk/qmk_firmware pull request #21253
Opened 2023-06-15 09:44 UTC by St0RM53

## Description

- Added new keyboard: lilith101

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-15 12:05 UTC, zvecr requested changes

2023-06-15 12:05 UTC, zvecr commented on keyboards/lilith101/custom_keys.c
As this file implements `_user` functions, including keymap specific keycodes, it should not exist at the keyboard level.

It should be moved to `keyboards/lilith101/keymaps/default/custom_keys.c` and a `keyboards/lilith101/keymaps/default/rules.mk` added to set `SRC += custom_keys.c` at the keymap level.

2023-06-15 12:05 UTC, zvecr commented on keyboards/lilith101/info.json
> +            { "pin_a": "B18", "pin_b": "A4", "resolution": 4 } /* pin_b on 1st Prototype is on C5, 2nd Prototype on A4 */
```suggestion
            { "pin_a": "B18", "pin_b": "A4" } /* pin_b on 1st Prototype is on C5, 2nd Prototype on A4 */
```

2023-06-15 12:05 UTC, zvecr commented on keyboards/lilith101/info.json
> +        "layout": [
```suggestion
        "driver": "ws2812",
        "layout": [
```

2023-06-15 12:05 UTC, zvecr commented on keyboards/lilith101/rules.mk
> +#WS2812_DRIVER = bitbang #Default value
```suggestion
```

2023-06-15 12:05 UTC, zvecr commented on keyboards/lilith101/readme.md
> +*A short description of the keyboard/project*
Should be filled in

2023-06-15 12:05 UTC, zvecr commented on keyboards/lilith101/info.json
> +
```suggestion
        "oled": true,
        "rgb_matrix": true
```

2023-06-16 09:20 UTC, St0RM53 commented on keyboards/lilith101/custom_keys.c
I am getting implicit declaration of function errors for all `rgb_matrix_function()` functions after i moved it :/

2023-06-16 13:33 UTC, St0RM53 commented on keyboards/lilith101/info.json
> +        "layout": [
Needs to be capitalized: `WS2812`

2023-11-05 01:50 UTC, closed without merging