add initial svalboard configuration and keymap
qmk/qmk_firmware pull request #21257
Opened 2023-06-15 23:44 UTC by morganvenable

## Description
This adds support for Svalboard, www.svalboard.com, a Datahand evolution based on the lalboard architecture, but adapted for RP2040.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ X] Keyboard (addition or update)
- [ X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-15 23:48 UTC, tzarc commented
I've unticked "I have read the [PR Checklist document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes." for you.

2023-06-16 00:48 UTC, morganvenable commented
I did read the notes and try to comply, but obviously missed some things.
I'm up to date AFAIK on the build, and the default keymap is building for me locally with this code with no errors. I'll strip it down to just the default keymap to get going, but I'm confused about what exactly in the default build is throwing these -- is there a mandatory "do-stuff-in-info.json-instead-of-elsewhere" thing here that I'm violating?
Is there some way to locally reproduce this test pass so I don't thrash anyone with PRs?

2023-06-16 04:08 UTC, morganvenable commented
Wow, thanks for the incredibly thorough comments.
I'm migrating from an old forked build circa 2019 by someone else, which
ran on ESP32S2 (he did some unholy stuff to make it run on there).
That build predates a lot of the new json-based stuff as I understand it.
I don't mind converting, but I'm having a hard time validating my
info.json, which... makes that kind of difficult.

Specifically, when I try to validate my info.json against the schema here:
https://github.com/qmk/qmk_firmware/blob/master/data/schemas/keyboard.jsonschema
using any online JSON validator, I just get errors saying *the schema
itself* is invalid :(
Is there some other tool folks use for this step?
Attempting to preview in Configurator fails, unsurprisingly.

I'll run along to the discord to reduce the noise here if that's preferred,
just let me know.


On Thu, Jun 15, 2023 at 8:13 PM lesshonor ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On keyboards/svalboard/.noci
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231670311>:
>
> Please delete this file.
> ------------------------------
>
> On keyboards/svalboard/keymaps/DH-QWERTY/keymap.c
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231670619>:
>
>    - newly-added directories and filenames must be lowercase
>    <https://github.com/qmk/qmk_firmware/blob/94311e4dc27e603b6c421d2773a5f82275a24411/docs/pr_checklist.md?plain=1#LL16C3-L16C58>
>
> Also...is this keymap really necessary? There are only two keys that
> differ from default here.
> ------------------------------
>
> On keyboards/svalboard/svalboard.h
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231673930>:
>
>    - LAYOUT macros are no longer accepted and should instead be moved to
>    info.json
>    <https://github.com/qmk/qmk_firmware/blob/94311e4dc27e603b6c421d2773a5f82275a24411/docs/pr_checklist.md?plain=1#LL127C7-L127C88>
>
> ------------------------------
>
> On keyboards/svalboard/svalboard.c
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231674033>:
>
> Since this file isn't doing anything, it can be deleted.
> ------------------------------
>
> On keyboards/svalboard/config.h
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231688284>:
>
> Running qmk info -f json -kb svalboard will help you migrate most of this
> -- though watch out as it includes a small bit of duplicate data. Examining
> other split keyboards in the repository (ex
> <https://github.com/qmk/qmk_firmware/blob/94311e4dc27e603b6c421d2773a5f82275a24411/keyboards/tweetydabird/lotus58/info.json#L4>)
> will help.
>
> Also: short explanatory comments are fine, but the unused, obsolete and/or
> default commented-out defines should be removed.
> ------------------------------
>
> In keyboards/svalboard/config.h
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231689142>:
>
> > +#define MATRIX_ROW_PINS \
> +    { GP8, GP7, GP6, GP5, GP4 }
>
> I understand that the PR checklist specifically cites "keyboards with a
> custom matrix" for examples of when you can't move the row and column pins
> to info.json...but yours compiles just fine with them there, so that
> exemption doesn't appear to apply to you.
> ------------------------------
>
> In keyboards/svalboard/info.json
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231691115>:
>
> > @@ -0,0 +1,81 @@
> +{
> +  "keyboard_name": "svalboard",
> +  "url": "http://svalboard.com",
> +  "maintainer": "MorganVenable",
>
> This is a guess on my part; please correct if needed.
> ⬇️ Suggested change
>
> -  "maintainer": "MorganVenable",
> +  "manufacturer": "Svalboard",
> +  "maintainer": "MorganVenable",
>
> ------------------------------
>
> In keyboards/svalboard/info.json
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231699069>:
>
> > @@ -0,0 +1,81 @@
> +{
> +  "keyboard_name": "svalboard",
> +  "url": "http://svalboard.com",
> +  "maintainer": "MorganVenable",
> +  "width": 20.5,
> +  "height": 6,
> +  "usb": {
> +    "vid": "0x303A",
> +    "pid": "0x4044",
> +    "device_version": "0.0.1"
> +  },
> +
> +  "layouts": {
>
> A collaborator may not agree on the readability of the Datahand-sized
> keys. I have to admit I was surprised by how legible they remained in
> Configurator, so it gets an 🆗 from me.
> ------------------------------
>
> In keyboards/svalboard/info.json
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231699250>:
>
> > +              {"label":"l2e", "x":5.5, "y":0.5, "w":0.5},
> +              {"label":"l2s", "x":4.5, "y":1.5, "h":0.5},
> +              {"label":"l2w", "x":4, "y":0.5, "w":0.5},
> +
> +              {"label":"l1c", "x":6.5, "y":1},
> +              {"label":"l1n", "x":6.5, "y":0.5, "h":0.5},
> +              {"label":"l1e", "x":7.5, "y":1, "w":0.5},
> +              {"label":"l1s", "x":6.5, "y":2, "h":0.5},
> +              {"label":"l1w", "x":6, "y":1, "w":0.5},
> +
> +              {"label":"ltd", "x":8.5, "y":4, "h": 2},
> +              {"label":"lti", "x":8, "y":3.5, "h": 1.5, "w":0.5},
> +              {"label":"ltu", "x":7.5, "y":3.5, "w": 0.5},
> +              {"label":"ltuo", "x":9.5, "y":3.5, "h": 1.5, "w": 0.5},
> +              {"label":"ltlo", "x":9.5, "y":5, "h": 1.5, "w": 0.5},
> +              {"label":"ltdd", "x":8.5, "y":5, "h": 1.5, "w": 0.5},
>
> I don't think it's a good idea to have these keys overlap anything, though.
> ⬇️ Suggested change
>
> -              {"label":"ltdd", "x":8.5, "y":5, "h": 1.5, "w": 0.5},
> +              {"label":"ltdd", "x":8, "y":5, "h": 1.5, "w": 0.5},
>
> ------------------------------
>
> In keyboards/svalboard/info.json
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231699418>:
>
> > +              {"label":"l1w", "x":6, "y":1, "w":0.5},
> +
> +              {"label":"ltd", "x":8.5, "y":4, "h": 2},
> +              {"label":"lti", "x":8, "y":3.5, "h": 1.5, "w":0.5},
> +              {"label":"ltu", "x":7.5, "y":3.5, "w": 0.5},
> +              {"label":"ltuo", "x":9.5, "y":3.5, "h": 1.5, "w": 0.5},
> +              {"label":"ltlo", "x":9.5, "y":5, "h": 1.5, "w": 0.5},
> +              {"label":"ltdd", "x":8.5, "y":5, "h": 1.5, "w": 0.5},
> +
> +
> +              {"label":"rtd", "x":11, "y":4, "h": 2},
> +              {"label":"rti", "x":12, "y":3.5, "h": 1.5, "w":0.5},
> +              {"label":"rtu", "x":12.5, "y":3.5, "w": 0.5},
> +              {"label":"rtuo", "x":10.5, "y":3.5, "h": 1.5, "w": 0.5},
> +              {"label":"rtlo", "x":10.5, "y":5, "h": 1.5, "w": 0.5},
> +              {"label":"rtdd", "x":11, "y":5, "h": 1.5, "w": 0.5},
>
> This one appears to be misplaced.
> ⬇️ Suggested change
>
> -              {"label":"rtdd", "x":11, "y":5, "h": 1.5, "w": 0.5},
> +              {"label":"rtdd", "x":12, "y":5, "h": 1.5, "w": 0.5},
>
> ------------------------------
>
> In keyboards/svalboard/keymaps/DH-QWERTY/keymap.c
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231701257>:
>
> > +
> +#include <stdbool.h>
> +#include <stdint.h>
>
> ⬇️ Suggested change
>
> -
> -#include <stdbool.h>
> -#include <stdint.h>
>
> ------------------------------
>
> In keyboards/svalboard/keymaps/DH-QWERTY/keymap.c
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231715379>:
>
> > +enum my_keycodes {
> + KC_NORMAL_HOLD = SAFE_RANGE,
> +  KC_FUNC_HOLD
> +  //
> +  //KC_GAME_HOLD,
> +  //KC_GAZE,
> +};
>
> ⬇️ Suggested change
>
> -enum my_keycodes {
> - KC_NORMAL_HOLD = SAFE_RANGE,
> -  KC_FUNC_HOLD
> -  //
> -  //KC_GAME_HOLD,
> -  //KC_GAZE,
> -};
> +enum my_keycodes {
> +  KC_NORMAL_HOLD = SAFE_RANGE,
> +  KC_FUNC_HOLD
> +};
>
> ------------------------------
>
> In keyboards/svalboard/keymaps/DH-QWERTY/keymap.c
> <https://github.com/qmk/qmk_firmware/pull/21257#discussion_r1231715922>:
>
> > +enum layer {
> +  NORMAL,
> +    COLEMAK_ASRT,
> +    NORMAL_HOLD,
> +    FUNC,
> +    FUNC_HOLD,
> +    NAS,
> +    //COLEMAK,
> +
> +//   [...]

2023-06-16 04:28 UTC, morganvenable commented on keyboards/svalboard/matrix.c
> +// }
I'm definitely using this.  Svalboard has unusual timing, active-high rows and cols[2] is active high as well -- this is roughly the approach suggested on the discord by elpekenin, not that any of the clumsiness is his :P
If there's a cleaner way to scan rows/cols with differing active states I'm all ears!

2023-06-16 04:29 UTC, morganvenable commented on keyboards/svalboard/config.h
> +#define INVERTED_DOWN_KEYS
it does -- there are just a handful of early boards without the inverted down keys, and come to think of it, all the RP2040-based units should have them, so I can just delete it in this version.

2023-06-16 04:30 UTC, morganvenable commented on keyboards/svalboard/readme.md
> +RP2040 should boot into mass storage for FW loading when both buttons are pressed, or if the reset button is double-tapped.  TBD
TBD because of a dumb schematic gaffe.  Not sure if I'm going to blue-wire the next few sets :shrug:

2023-06-16 04:30 UTC, morganvenable commented on keyboards/svalboard/keymaps/vial/config.h
yeah this is template cruft I thought was in my .gitignore 😓

2023-06-16 04:33 UTC, morganvenable commented on keyboards/svalboard/info.json
> +  "layouts": {
How did you get this to render in Configurator?  I tried using Ctrl-Shift-I and selecting this file in the dialog that popped up, but it says it's not a valid keymap file.  Very confused.

2023-06-16 04:37 UTC, morganvenable commented
Thanks.  I reinstalled QMK_MSYS and can now reproduce at least some of
these errors.

On Thu, Jun 15, 2023 at 7:05 PM jack ***@***.***> wrote:

> I'm confused about what exactly in the default build is throwing these
>
> You can view the CI build logs here
> <https://github.com/qmk/qmk_firmware/pull/21257/checks?check_run_id=14307171551>.
> However, sounds like there's something wrong with your local QMK build
> environment if this code is building successfully for you on an up-to-date
> version of QMK.
>
> is there a mandatory "do-stuff-in-info.json-instead-of-elsewhere" thing
> here that I'm violating?
>
> Yes, quite a few things, that the PR checklist covers.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qmk/qmk_firmware/pull/21257#issuecomment-1593980250>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAGVYI45EZ4RWHCSKSJMH3XLO5QHANCNFSM6AAAAAAZIQVQMI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-16 04:54 UTC, waffle87 commented on keyboards/svalboard/matrix.c
> +// }
lesshonor is referring to the fact it's commented out. Commented out code is not being used and should be removed, as covered in PR checklist.

2023-06-16 05:03 UTC, morganvenable commented on keyboards/svalboard/matrix.c
> +// }
sorry, I was being thick and somehow misread this as a different section of code that wasn't commented out :(

2023-06-19 05:46 UTC, waffle87 requested changes

2023-06-19 05:46 UTC, waffle87 commented on .gitignore
Changes to this file should be reverted.

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/info.json
Please run `qmk format-json path/to/info.json` on this file.

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/info.json
> +      "unicode": false
```suggestion             
      "bootmagic": true,                                                                 
      "command": true,                                                                    
      "console": true,                                                                    
      "extrakey": true,                                                                   
      "midi": false,                                                                      
      "mousekey": true,                                                                   
      "nkro": true
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/info.json
> +  "height": 10,
```suggestion
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/info.json
> +  },
```suggestion
      "main": "eeprom"
  }
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/info.json
> +  "width": 20.5,
```suggestion
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/info.json
> +      "polling_interval": 1,
```suggestion
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/keymaps/default/keymap.c
> +
```suggestion
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/keymaps/default/keymap.c
> +__attribute__((weak)) const uint16_t PROGMEM keymaps[NUM_LAYERS][MATRIX_ROWS][MATRIX_COLS] = {
```suggestion
const uint16_t PROGMEM keymaps[NUM_LAYERS][MATRIX_ROWS][MATRIX_COLS] = {
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/readme.md
> +![Svalboard](https://www.svalboard.com)
This is meant to be an image, not a plain link.

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/readme.md
> +```
```suggestion
Make example for this keyboard (after setting up your build environment):

    make svalboard:default

Flashing example for this keyboard:

    make svalboard:default:flash

```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/rules.mk
> +
```suggestion
```

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/svalboard.c
This file should be removed.

2023-06-19 05:46 UTC, waffle87 commented on keyboards/svalboard/svalboard.h
This file should be removed.

2023-11-06 01:50 UTC, closed without merging