commit bigsmoothknob
qmk/qmk_firmware pull request #21265
Opened 2023-06-16 17:35 UTC by Na-Cly

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-17 02:42 UTC, zvecr requested changes

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/keymaps/default/keymap.c
> +        ),
```suggestion
    [0] = LAYOUT(
        KC_1, KC_2, KC_3, KC_4,
        KC_5, KC_6, KC_7, KC_8
        )
```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/keymaps/default/keymap.c
> +    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
```suggestion
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/keymaps/via/keymap.c
> +    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
```suggestion
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/keymaps/via/keymap.c
> +        ),
```suggestion
    [0] = LAYOUT(
        KC_1, KC_2, KC_3, KC_4,
        KC_5, KC_6, KC_7, KC_8
        )
```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/config.h
> +
```suggestion

```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
# This file intentionally left blank
```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/info.json
> +    "layouts": {
```suggestion
    "features": {
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true,
        "encoder": true
    },
    "layouts": {
```

2023-06-17 02:42 UTC, zvecr commented on keyboards/nacly/bigsmoothknob/info.json
> +    "matrix_pins": {
```suggestion
    "encoder": {
        "rotary": [
            { "pin_a": "GP26", "pin_b": "GP27" }
        ]
    },
    "matrix_pins": {
```

2023-06-19 06:09 UTC, waffle87 commented on keyboards/nacly/bigsmoothknob/readme.md
> +    ```
```suggestion
Make example for this keyboard (after setting up your build environment):

    make nacly/bigsmoothknob:default

Flashing example for this keyboard:

    make nacly/bigsmoothknob:default:flash


```

2023-06-20 03:51 UTC, drashna approved these changes

2023-06-20 15:35 UTC, waffle87 approved these changes

2023-06-20 15:35 UTC, merged