add `laneware/raindrop/hhkb` keyboard
qmk/qmk_firmware pull request #21277
Opened 2023-06-17 19:05 UTC by dunk2k

## Description

During a request for help in r/qmk; this board, and many others by the manufacturer, are required to have their firmware files updated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-17 19:55 UTC, sigprof commented
Looking at the [shop page](https://lanewareperipherals.com/collections/raindrop-60), it appears that there is only a single version of the PCB that supports multiple layouts.  The way to support such PCBs in QMK is to add a single keyboard with multiple entries under `layouts` in `info.json`, not to create multiple separate keyboards for each possible layout.

2023-06-17 23:17 UTC, dunk2k commented
> Looking at the [shop page](https://lanewareperipherals.com/collections/raindrop-60), it appears that there is only a single version of the PCB that supports multiple layouts. The way to support such PCBs in QMK is to add a single keyboard with multiple entries under `layouts` in `info.json`, not to create multiple separate keyboards for each possible layout.

Appears this reference on [geekhack.org](https://geekhack.org/index.php?topic=105885.0) is more accurate than the shop page.

2023-06-18 08:34 UTC, sigprof commented
The [GB thread](https://geekhack.org/index.php?topic=107163) claims that ISO is supported, but still shows the same PCB image without any ISO support; also all renders and prototypes show a plate with a single supported layout (ANSI with 2u left Shift and cursor keys).  No idea how the actual GB boards look.

2023-06-18 09:00 UTC, sigprof requested changes

2023-06-18 10:14 UTC, dunk2k commented on keyboards/raindrop/info.json
> +    "layouts": {
LAYOUT_all added

2023-07-07 17:18 UTC, dunk2k commented
@Laneware 
Could you review to ensure this PR matches the Group Buy board being added

2023-07-11 08:09 UTC, drashna approved these changes

2023-07-25 21:58 UTC, fauxpark requested changes

2023-07-25 21:58 UTC, fauxpark commented on keyboards/raindrop/readme.md
> +    make raindrop:hhkb:flash
```suggestion

Flashing example for this keyboard:

    make raindrop:default:flash
```

2023-07-30 21:54 UTC, fauxpark approved these changes

2023-08-12 08:42 UTC, merged