[Keymap] Add slotThe keyboardio/atreus keymap
qmk/qmk_firmware pull request #21274
Opened 2023-06-17 12:13 UTC by slotThe

## Description

Adds 

    keyboards/keyboardio/atreus/keymaps/slotthe
    ├── README.md
    ├── autocorrect_data.h
    ├── config.h
    ├── keymap.c
    └── rules.mk

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

n/a 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)

  I *should* follow all of the C style guideline, except that I use 2 spaces for indentation instead of 4, and sometimes (well, often) omit optional braces. I don't know what the etiquette is regarding user keymaps; if needed I can adjust all of this to 100% fit the guideline. 

- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-19 06:19 UTC, drashna requested changes

2023-06-19 06:19 UTC, drashna commented on keyboards/keyboardio/atreus/keymaps/slotthe/rules.mk
> +EXTRAFLAGS     += -flto
```suggestion
LTO_ENABLE = yes
```

2023-06-19 06:19 UTC, drashna commented on keyboards/keyboardio/atreus/keymaps/slotthe/README.md
please rename this to be all lower case.

2023-06-19 09:23 UTC, slotThe commented
@drashna should be all done

2023-06-24 08:53 UTC, drashna approved these changes

2023-07-07 14:34 UTC, tzarc approved these changes

2023-07-07 14:35 UTC, merged