[Keyboard] Add new keyboard nemui65
qmk/qmk_firmware pull request #21304
Opened 2023-06-19 16:38 UTC by spbgzh

## Description
Add new keyboard nemui65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-21 12:43 UTC, dunk2k commented on keyboards/wuque/nemui65/info.json
> +                {"matrix": [0, 13], "x": 13, "y": 0},
```suggestion
                {"matrix": [0, 13], "x": 13, "y": 0, "w": 2},
```

2023-06-21 12:44 UTC, dunk2k commented on keyboards/wuque/nemui65/info.json
> +                {"matrix": [3, 0], "x": 0, "y": 3, "w": 1.25},
```suggestion
                {"matrix": [3, 0], "x": 0, "y": 3, "w": 2.25},
```

2023-06-21 12:45 UTC, dunk2k commented on keyboards/wuque/nemui65/info.json
> +                {"matrix": [4, 6], "x": 6, "y": 4, "w": 1.25},
```suggestion
                {"matrix": [4, 6], "x": 3.75, "y": 4, "w": 6.25},
```

2023-06-21 12:57 UTC, dunk2k commented on keyboards/wuque/nemui65/rules.mk
> +ENCODER_ENABLE = no         # Enable Encoder
moved to info.json
```suggestion
# This file intentionally left blank
```

2023-06-21 13:00 UTC, dunk2k commented on keyboards/wuque/nemui65/info.json
> +        "max_brightness": 200
```suggestion
         "animations": {
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
        },
        "max_brightness": 200,
        "led_count": 1,
        "hue_steps": 8,
        "saturation_steps": 8,
        "brightness_steps": 8,
        "sleep": true
```

2023-06-21 13:01 UTC, dunk2k commented on keyboards/wuque/nemui65/keymaps/via/rules.mk
> +LTO_ENABLE = yes
add EOF
```suggestion
LTO_ENABLE = yes

```

2023-06-21 13:03 UTC, dunk2k commented on keyboards/wuque/nemui65/zoom65.c
Based on this file's current contents, it can be safely removed; as it provides no additional functionality therefore won't cause build/compile errors.

2023-06-21 18:18 UTC, spbgzh commented on keyboards/wuque/nemui65/zoom65.c
deleted

2023-06-21 18:26 UTC, dunk2k approved these changes

2023-06-21 18:40 UTC, waffle87 requested changes

2023-06-21 18:40 UTC, waffle87 commented on keyboards/wuque/nemui65/info.json
> +        "encoder": false,
```suggestion
        "console": false
        "extrakey": true,
        "mousekey": true,
        "nkro": true
```

2023-06-21 18:40 UTC, waffle87 commented on keyboards/wuque/nemui65/info.json
> +        "hue_steps": 8,
```suggestion
```

2023-06-21 18:40 UTC, waffle87 commented on keyboards/wuque/nemui65/keymaps/via/keymap.c
> +    ),
```suggestion
    )
```

2023-06-24 08:11 UTC, drashna approved these changes

2023-07-12 00:59 UTC, spbgzh commented
@waffle87 bro, take a look at this PR

2023-07-12 01:28 UTC, waffle87 approved these changes

2023-07-12 01:28 UTC, merged