Rework info.json reference
qmk/qmk_firmware pull request #21324
Opened 2023-06-21 03:42 UTC by fauxpark

## Description

I think I got pretty much everything.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-21 13:23 UTC, dunk2k commented
@fauxpark Great write up chief!

Could I be a pain with a question:
    Should `development_board` be used to indicate that keyboard requires a microcontroller (daughter) board exclusively?. i.e. the controller chip **is not** part of the key switch/mother PCB.

2023-06-21 13:27 UTC, dunk2k commented on docs/reference_info_json.md
> +    * The the microcontroller development board, if applicable.
```suggestion
    * The microcontroller development board, if applicable.
```

2023-06-21 13:58 UTC, sigprof requested changes

2023-06-21 13:58 UTC, sigprof commented on docs/reference_info_json.md
> +    * The the microcontroller development board, if applicable.
```suggestion
    * The microcontroller development board, if applicable.
```

2023-06-21 16:06 UTC, fauxpark commented
@dunk2k Are you asking whether that should be documented here, or are you asking when to use `development_board`?

Since this page is only meant as a quick reference, with each section linking to the respective feature/driver/etc. docs, it's not really in scope to provide more than a simple description of a given key. I've also omitted the full list of MCUs and bootloaders for a similar reason.

2023-06-21 17:14 UTC, dunk2k commented
> @dunk2k Are you asking whether that should be documented here, or are you asking when to use `development_board`?

The latter. Though if there's documentation in pipeline/future that describes when to use `development_board` then that document will save someone asking to elaborate in this file 😁

2023-06-22 14:10 UTC, fauxpark commented
Then to answer your original question, yes. In this case you would not need to specify `processor` and `bootloader` (and usually also `board` for ChibiOS targets): https://github.com/qmk/qmk_firmware/blob/develop/data/mappings/defaults.hjson

2023-07-11 03:43 UTC, drashna approved these changes

2023-07-23 10:18 UTC, dunk2k commented
Would a listing of all available entries for `"features"`, be appropriate in this file?

2023-07-23 10:21 UTC, fauxpark commented
There is no canonical list. Most of them, I think, should be moved into their own `<feature>.enabled` key anyway.

2023-07-29 08:06 UTC, dunk2k approved these changes

2023-08-24 18:27 UTC, zvecr commented on docs/reference_info_json.md
> +        * How to determine the main/primary half. Must be one of `eeprom`, `left`, `matrix_grid`, `pin`, `right`.
Probably not worth documenting this given its broken, <https://github.com/qmk/qmk_firmware/pull/18254>. Same goes for some of the other fields that PR flags issue to, matrix_grid.

2023-08-25 14:33 UTC, zvecr approved these changes

2023-08-26 20:03 UTC, merged