add jaykeeb sebelas
qmk/qmk_firmware pull request #21335
Opened 2023-06-22 06:29 UTC by alabahuy

## Description

add new board "jaykeeb sebelas"

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-22 08:44 UTC, dunk2k commented
1. `matrix_diagram.md` and matrix information in info.json layouts don't match:  
`matrix_diagram.md` has one additional key than key count of each community layout in `info.json` layouts.
2. CI builds are failing for community layouts as the layout macro's, for each community layout, has one less key than the key count of the respective community layout.

If the matrix diagram is correct then each layout in `info.json` will need to be amended,
else remove `community layouts` from `info.json`

That'll correct the CI builds 🙂

2023-06-22 08:46 UTC, alabahuy commented
@dunk2k thanks, i already remove community layout

2023-06-22 08:48 UTC, dunk2k commented
> @dunk2k thanks, i already remove community layout

Great stuff! I've noticed are few other 65% sized board PRs coming in that have the upper right most key removed. I'm starting to wonder if this should be accommodated for 🤔

2023-06-22 08:57 UTC, dunk2k commented
@alabahuy 

just noticed you both the `community layouts` field and the layout macros that were named same as community layouts.

in `info.json` could you please revert deletion of the community named layout macros, but not revert the removal of `community layouts` field?

These community named layouts will still function without the `community layout` field in `info.json` and these layouts would be required if the PCB can be populated with more than one switch arrangement, as this PCB can 😊

2023-06-22 09:08 UTC, dunk2k commented
@alabahuy 
would you be able to add keymaps for layout macros `LAYOUT_65_ansi_blocker_split_bs`, `LAYOUT_65_ansi_blocker_tsangan`, and `LAYOUT_65_ansi_blocker_tsangan_split_bs`?

`default` keymap is set to layout macro `LAYOUT_65_ansi_blocker`
Suggestions for keymap names:
| layout macro | keymap name |
| --- | --- |
| LAYOUT_65_ansi_blocker_split_bs | blckr |
| LAYOUT_65_ansi_blocker_tsangan | blckr_tsgn  |
|  LAYOUT_65_ansi_blocker_tsangan_split_bs | blckr_tsgn_sb |

2023-06-22 09:28 UTC, alabahuy commented
@dunk2k thank you very much, I followed your suggestion and still named the layout macro

2023-06-22 13:36 UTC, zvecr requested changes

2023-06-22 13:36 UTC, zvecr commented on keyboards/jaykeeb/sebelas/info.json
> +        "twinkle": true
```suggestion
        "animations": {
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2023-06-22 13:36 UTC, zvecr commented on keyboards/jaykeeb/sebelas/info.json
> +                {"label": "Space", "matrix": [4, 7], "x": 6, "y": 4, "w": 1.25},
```
linting jaykeeb/sebelas
Ψ Lint check passed!
Keyboard Name: Sebelas
Manufacturer: Alabahuy
Website: 
Maintainer: Alabahuy
Layouts: LAYOUT_65_ansi_blocker, LAYOUT_65_ansi_blocker_split_bs, LAYOUT_65_ansi_blocker_tsangan, LAYOUT_65_ansi_blocker_tsangan_split_bs, LAYOUT_all
Processor: RP20[40](https://github.com/qmk/qmk_firmware/actions/runs/5343882060/jobs/9687556069#step:8:41)
Bootloader: rp2040
Layout Layout_All:
┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐
│Es││1 ││2 ││3 ││4 ││5 ││6 ││7 ││8 ││9 ││0 ││- ││= ││Ba││De│
└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘
┌────┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌────┐┌──┐
│Tab ││Q ││W ││E ││R ││T ││Y ││U ││I ││O ││P ││[ ││] ││\   ││En│
└────┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└────┘└──┘
┌─────┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌───────┐┌──┐
│Caps ││A ││S ││D ││F ││G ││H ││J ││K ││L ││; ││' ││Enter  ││Pa│
└─────┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└───────┘└──┘
┌───┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌──┐┌─────┐┌──┐┌──┐
│Shi││\ ││Z ││X ││C ││V ││B ││N ││M ││, ││. ││/ ││Shift││↑ ││Pa│
└───┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└──┘└─────┘└──┘└──┘
┌───┐┌───┐┌───┐         ┌───┐           ┌───┐┌───┐  ┌──┐┌──┐┌──┐
│Ctr││GUI││Alt│         │Spa│           │Alt││Ctr│  │← ││↓ ││→ │
└───┘└───┘└───┘         └───┘           └───┘└───┘  └──┘└──┘└──┘
```

```suggestion
                {"label": "Space", "matrix": [4, 7], "x": 3.75, "y": 4, "w": 6.25},
```

2023-06-23 01:22 UTC, alabahuy commented on keyboards/jaykeeb/sebelas/info.json
> +                {"label": "Space", "matrix": [4, 7], "x": 6, "y": 4, "w": 1.25},
sorry my fault, i fixed this. thanks

2023-06-24 08:45 UTC, drashna approved these changes

2023-06-30 21:56 UTC, alabahuy commented
Any update @zvecr ?

2023-07-01 03:25 UTC, waffle87 approved these changes

2023-07-01 03:26 UTC, merged