add jels60v2 support
qmk/qmk_firmware pull request #21337
Opened 2023-06-22 10:18 UTC by Jels02

## Description

add support for v2 of the PCB using rp2040

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-22 14:39 UTC, zvecr requested changes
> keyboard updates and refactors (eg. to data driven) must go through develop to reduce master -> develop merge conflicts

This would include adding to `data/mappings/keyboard_aliases.hjson` for `jels/jels60` to `jels/jels60/v1` compatibility.

2023-06-22 14:39 UTC, zvecr commented on keyboards/jels/jels60/v2/info.json
> +        "max_brightness": 255,
```suggestion
```

2023-06-22 14:39 UTC, zvecr commented on keyboards/jels/jels60/v2/info.json
> +    "debounce": 5
```suggestion
    }
```

2023-06-22 14:39 UTC, zvecr commented on keyboards/jels/jels60/v2/info.json
> +    "diode_direction": "COL2ROW",
```suggestion
```

2023-06-23 09:12 UTC, Jels02 commented
@zvecr would I be able to add a temporary keyboard (i.e jels/jels60v2) to master (so that I can change VIA) and then put in a pr for refactoring targeted towards develop?

2023-07-03 10:35 UTC, drashna commented
> @zvecr would I be able to add a temporary keyboard (i.e jels/jels60v2) to master (so that I can change VIA) and then put in a pr for refactoring targeted towards develop?

IIRC, via doesn't actually provide firmware images.  The collection that they have is very much out of date, I believe.  So, really, it's up to you to provide them. So compiling from source means that you should be able to compile from develop. So shouldn't be an issue.

2023-07-03 10:35 UTC, drashna approved these changes

2023-07-04 00:59 UTC, fauxpark approved these changes

2023-07-07 21:19 UTC, merged