small changes, game layer
qmk/qmk_firmware pull request #21375
Opened 2023-06-24 21:23 UTC by mattly

## Description

updating my keymap and colors after a few yeas

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-03 10:13 UTC, drashna commented on users/mattly/mattly.c
> +    rgblight_enable();
I don't see that issue with a different board.  So very odd.

2023-07-03 10:13 UTC, drashna approved these changes

2023-07-03 10:17 UTC, drashna commented
> so, I have a rev3 iris. I have no idea why this fails against the rev6/7 ones. Excess elements in array initializer? What's that even supposed to mean, and why is it not failing on the earlier revs?

The issue is the number of leds defined.  rgb matrix with the ws2812 driver uses the same config for the number of leds as rgblight.  So it basically has too many entries.  adding `RGB_MATRIX_ENABLE=no` to your keymap's rules.mk should fix that.  But either way, should be fine

2023-07-04 01:13 UTC, fauxpark requested changes

2023-07-04 01:13 UTC, fauxpark commented on keyboards/keebio/iris/keymaps/mattly/config.h
> +/*p
```suggestion
/*
```

2023-07-05 01:18 UTC, fauxpark approved these changes

2023-07-06 06:03 UTC, merged