update keyboard soda/mango, support rgb matrix
qmk/qmk_firmware pull request #21385
Opened 2023-06-26 03:10 UTC by gezhaoyou

## Description

update keyboard soda/mango, support rgb matrix

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-26 09:27 UTC, zvecr requested changes

2023-06-26 09:27 UTC, zvecr commented on keyboards/soda/mango/info.json
> +        "rgblight": false
```suggestion
        "rgb_matrix": true
```

2023-06-28 09:34 UTC, drashna approved these changes

2023-06-30 06:52 UTC, dunk2k requested changes

2023-07-03 08:27 UTC, dunk2k approved these changes

2023-07-03 09:58 UTC, drashna approved these changes

2023-07-04 00:59 UTC, fauxpark approved these changes

2023-07-07 21:19 UTC, merged