Add Iris Rev. 8
qmk/qmk_firmware pull request #21392
Opened 2023-06-26 22:32 UTC by nooges

## Description

Adds Iris Rev. 8 (uses RP2040 controller now).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-28 05:44 UTC, drashna approved these changes

2023-06-30 06:52 UTC, dunk2k requested changes

2023-06-30 22:10 UTC, nooges commented on keyboards/keebio/iris/rev8/info.json
> +        "enabled": true,
I'll wait for the migration to occur first before doing this.

2023-06-30 22:39 UTC, dunk2k approved these changes

2023-07-01 01:36 UTC, merged