Added /handwired/ziyoulang_k3_mod
qmk/qmk_firmware pull request #21403
Opened 2023-06-28 16:28 UTC by coomstoolbox

## Description

Initial PR for adding ziyoulang k3 keyboard modify project.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-30 06:41 UTC, dunk2k requested changes

2023-06-30 17:31 UTC, dunk2k approved these changes

2023-07-01 03:30 UTC, waffle87 requested changes

2023-07-01 03:30 UTC, waffle87 commented on keyboards/handwired/ziyoulang_k3_mod/keymaps/default/keymap.c
> +        _______,          _______, _______,                   _______,                            _______, MO(1),            _______,                            _______,          _______,
This won't have worked.
```suggestion
        _______,          _______, _______,                   _______,                            _______, _______,            _______,                            _______,          _______,
```

2023-07-01 03:30 UTC, waffle87 commented on keyboards/handwired/ziyoulang_k3_mod/keymaps/via/keymap.c
> +                                                                                                                                      KC_LEFT, KC_DOWN, KC_RGHT
```suggestion
```

2023-07-03 09:41 UTC, drashna approved these changes

2023-07-10 12:34 UTC, coomstoolbox commented
@waffle87 
Corrected the corrections. Please let me know if there is anything else I should fix.

2023-07-10 12:44 UTC, fauxpark requested changes

2023-07-10 12:44 UTC, fauxpark commented on keyboards/handwired/ziyoulang_k3_mod/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```suggestion
```

2023-07-27 03:42 UTC, drashna approved these changes

2023-09-09 14:53 UTC, closed without merging