Add glara keymaps: idobao, gmmk, kbdfans & mode
qmk/qmk_firmware pull request #21418
Opened 2023-06-30 12:47 UTC by glara

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-01 03:47 UTC, waffle87 requested changes
* Your `gmmk/pro` keymap is in a non-existent location. It should be in `qmk_firmware/keyboards/gmmk/pro/rev1/iso/keymaps`.
* There is no such this as an `idobao/id80/v1/iso`, only `v2/iso`... Your keymap there should be moved accordingly or removed.
* You have an extra nested `glara` directory in your `kbdfans/kbd75/keymaps/glara` directory that needs to be removed...

2023-07-01 03:47 UTC, waffle87 commented on keyboards/gmmk/pro/iso/keymaps/glara/config.h
> +// #    define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
```suggestion

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#    define RGB_MATRIX_KEYPRESSES
#    define RGB_DISABLE_WHEN_USB_SUSPENDED
```

2023-07-01 03:47 UTC, waffle87 commented on keyboards/gmmk/pro/iso/keymaps/glara/keymap.c
> +
```suggestion
```

2023-07-01 03:47 UTC, waffle87 commented on keyboards/gmmk/pro/iso/keymaps/glara/rgb_matrix_map.h
> +
```suggestion
#pragma once

```

2023-07-01 03:47 UTC, waffle87 commented on keyboards/gmmk/pro/iso/keymaps/glara/rules.mk
> +
```suggestion
MOUSEKEY_ENABLE = no       # Mouse keys
```

2023-07-01 03:47 UTC, waffle87 commented on keyboards/idobao/id80/v1/iso/keymaps/glara/rules.mk
> +
```suggestion
VIA_ENABLE = yes
```

2023-07-01 03:47 UTC, waffle87 commented on keyboards/kbdfans/kbd75/keymaps/glara/rules.mk
> +
```suggestion
```

2023-08-29 17:32 UTC, zvecr commented
Unfortunately since this PRs creation, QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

In the near future we will be providing a more user focused workflow for keymaps, but till then the suggestion is to keep changes in your own fork.

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.

2023-08-29 17:32 UTC, closed without merging