Add Nyquist Rev. 4
qmk/qmk_firmware pull request #21421
Opened 2023-07-01 01:38 UTC by nooges

## Description

Add Nyquist Rev. 4

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-01 08:59 UTC, dunk2k commented
Linting check fail due to `keymap.c` for `default` and `default_4x12` not having a licence header.

2023-07-01 14:32 UTC, dunk2k approved these changes

2023-07-03 08:16 UTC, drashna requested changes

2023-07-03 08:16 UTC, drashna commented on keyboards/keebio/nyquist/keymaps/default/keymap.c
> +    [1] = { ENCODER_CCW_CW(RGB_MOD, RGB_RMOD), ENCODER_CCW_CW(KC_MNXT, KC_MPRV) },
If this is meant to be on the lower layer, it isn't. It would be on the colemak layer

2023-07-03 08:16 UTC, drashna commented on keyboards/keebio/nyquist/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-03 08:16 UTC, drashna commented on keyboards/keebio/nyquist/keymaps/via/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-07-03 08:16 UTC, drashna commented on keyboards/keebio/nyquist/keymaps/default/keymap.c
> +    [5] = { ENCODER_CCW_CW(_______, _______), ENCODER_CCW_CW(_______, _______) }
In fact, would probably make things easier to use the enum names.

```suggestion
    [_QWERTY] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN) },
    [_COLEMAK] = { ENCODER_CCW_CW(_______, _______), ENCODER_CCW_CW(_______, _______) },
    [_DVORAK] = { ENCODER_CCW_CW(_______, _______), ENCODER_CCW_CW(_______, _______) },
    [_LOWER] = { ENCODER_CCW_CW(RGB_MOD, RGB_RMOD), ENCODER_CCW_CW(KC_MNXT, KC_MPRV) },
    [_RAISE] = { ENCODER_CCW_CW(_______, _______), ENCODER_CCW_CW(_______, _______) },
    [_ADJUST] = { ENCODER_CCW_CW(_______, _______), ENCODER_CCW_CW(_______, _______) }
```

2023-07-06 06:01 UTC, drashna approved these changes

2023-07-06 06:42 UTC, waffle87 approved these changes

2023-07-06 06:42 UTC, merged