[Keyboard] Add cf81 keyboard.
qmk/qmk_firmware pull request #21437
Opened 2023-07-03 05:59 UTC by jonylee1986

## Description
As title.

## Types of Changes

- [] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-03 07:10 UTC, dunk2k requested changes

2023-07-03 07:12 UTC, drashna commented on keyboards/chosfox/cf81/cf81.c
> +                layer_state_set(1<<WIN_B);
why set the layer here, when setting the default layer?  That's kind of at odds with the behavior of the two layer masks. 

Also, if you want to set the default layer to be persistent from keycode, you could do this in `default_layer_state_set_kb`: 
https://github.com/qmk/qmk_firmware/blob/26227d1f66673a5c16bef72971202811cd4b5eae/users/drashna/callbacks.c#L190-L202

2023-07-03 07:14 UTC, drashna commented on keyboards/chosfox/cf81/cf81.c
> +                keymap_config.no_gui     = 0;
Any specific reason for disabling win/gui/cmd on the mac layer?  The key is still usable and used heavily

2023-07-03 07:41 UTC, drashna commented on keyboards/chosfox/cf81/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
6 or 4?

2023-07-06 05:50 UTC, drashna approved these changes

2023-07-06 06:44 UTC, waffle87 commented on keyboards/chosfox/cf81/rules.mk
> +
```suggestion
WEAR_LEVELING_DRIVER = spi_flash
```

2023-07-06 06:45 UTC, waffle87 approved these changes

2023-07-06 06:45 UTC, merged