add mazestudio jocker
qmk/qmk_firmware pull request #21446
Opened 2023-07-04 04:59 UTC by mazestd

## Description

add new board "mazestudio jocker"

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-04 05:26 UTC, mazestd reviewed
Updating Bootmagic Config

2023-07-04 17:14 UTC, waffle87 requested changes

2023-07-04 17:14 UTC, waffle87 commented on keyboards/mazestudio/jocker/info.json
> +    },
```suggestion
    },
    "dynamic_keymap": {
        "layer_count": 3
    },
```

2023-07-04 17:14 UTC, waffle87 commented on keyboards/mazestudio/jocker/config.h
This file should be removed with the above suggestion.

2023-07-04 17:14 UTC, waffle87 commented on keyboards/mazestudio/jocker/info.json
> +        "enabled": true,
```suggestion
```

2023-07-04 17:14 UTC, waffle87 commented on keyboards/mazestudio/jocker/info.json
> +    "features": {
```suggestion
    "features": {
        "bootmagic": true,
```

2023-07-05 01:44 UTC, mazestd reviewed
Just updated based on your review @waffle87 . Thanks

2023-07-05 04:45 UTC, waffle87 approved these changes

2023-07-06 01:05 UTC, fauxpark requested changes

2023-07-06 02:21 UTC, mazestd commented on keyboards/mazestudio/jocker/readme.md
> +![jocker1800]( https://i.imgur.com/aQEiE4H.jpg )
Thanks @fauxpark , but may i know why i should add h at the end of the url?

2023-07-06 03:15 UTC, fauxpark commented on keyboards/mazestudio/jocker/readme.md
> +![jocker1800]( https://i.imgur.com/aQEiE4H.jpg )
https://api.imgur.com/models/image#thumbs

2023-07-06 05:41 UTC, drashna approved these changes

2023-07-06 06:38 UTC, merged