[Keyboard] add itstleo9
qmk/qmk_firmware pull request #21460
Opened 2023-07-06 14:08 UTC by ItsTLeo

add itstleo9 to QMK Firmware source code

I made an orthor 3x3 firmware for my macropad, can be using with RP2040 and ATmega32u4. Help the one who dont know how to make a firmware just handwire, solder and flash my firmware

## Description

I made the handwired firmware that have QMK Configurator, Via and Vial keymap to make the people who don't know how to made a firmware just handwire the switches on correct pin, and then install the firmware to have a nice macropad. Also im using firmware with RP2040 and ATmega 32u4, two of the most popular and easy use Promicro.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-06 16:02 UTC, dunk2k commented
Could folder structure be changed to the following:
```
keyboards
└─ itstleo
   └─ itsfleo9
      ├─ keymaps
      │  ├─ default 
      │  │  └─ keymap.c
      │  └─ via
      │     └─ keymap.c
      ├─ rp2040
      │  ├─ info.json
      │  ├─ readme.md
      │  └─ rules.mk
      ├─ promicro
      │  ├─ info.json
      │  ├─ readme.md
      │  └─ rules.mk
      └─ info.json
```
respective `info.json` in rp2040 and promicro directories contain definitions pertinent to respective controller. Shared definitions go into `itstleo/itsfleo9/info.json`.

2023-07-06 16:07 UTC, waffle87 requested changes
This keyboard's file structure should be consolidated into one:
```shell
itstleo9
├── atmega32u4
│   └── info.json # avr specific configuration
├── info.json # global configuration that applies to all hardware (eg. layout)
├── keymaps
└── rp2040
    └── info.json # rp2040 specific configuration
```

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_32u4/readme.md
> +This is my first handwire macropad project call itstleo9 or it9, using orthor 3x3 layout powered with 2 MCU are promicro ATmega32u4 and RasberryPi RP2040 for simple flash using QMK Toolbox and Drag&D
```suggestion
Handwired 3x3 macropad built with Pro Micro compatible microcontrollers
```

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_32u4/readme.md
> +* Hardware Availability: [Promicro](https://aliexpress.com/item/32888212119.html?spm=a2g0o.productlist.main.3.6e5ef70cdBVEF7&algo_pvid=fe4ec051-4a64-4e5d-810f-9984bfe852eb&aem_p4p_detail=202307060514
```suggestion
* Hardware Availability: [Promicro](https://aliexpress.com/item/32888212119.html)
```

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_rp2040/info.json
> +    "keyboard_name": "itstleo/handwired/ItsTleo9",
```suggestion
    "keyboard_name": "ItsTleo9",
```

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_rp2040/info.json
> +    },
```suggestion
    },
    "community_layouts": ["ortho_3x3"],
```

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_rp2040/keymaps/via/config.h
This file should be removed.

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_rp2040/keymaps/via/itstleo9_rp2040.json
This file should be removed.

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_rp2040/keymaps/via/rules.mk
> +# This file intentionally left blank
As above.

2023-07-06 16:07 UTC, waffle87 commented on keyboards/itstleo/itstleo9/itstleo9_rp2040/keymaps/vial/config.h
This directory needs to be removed.

2023-07-06 17:30 UTC, ItsTLeo commented on keyboards/itstleo/itstleo9/itstleo9_32u4/config.h
i have change all, hope you check it again. Thank you so much for fixing my source code

2023-07-06 17:42 UTC, dunk2k commented
Linting check failing as directory names must be all lower case

2023-07-06 17:47 UTC, dunk2k commented on keyboards/itstleo/itstleo9/keymaps/via/itstleo9.json
Could you remove this file from this PR and instead include it in a PR to VIA's [keyboards](https://github.com/the-via/keyboards) GitHub repo.

2023-07-06 17:56 UTC, waffle87 requested changes

2023-07-06 17:56 UTC, waffle87 commented on keyboards/itstleo/itstleo9/Promicro/readme.md
Could you move this file up to the keyboard level (`keyboards/itstleo/itstleo9`)

2023-07-06 17:56 UTC, waffle87 commented on keyboards/itstleo/itstleo9/RP2040/readme.md
Then remove this file.

2023-07-06 17:56 UTC, waffle87 commented on keyboards/itstleo/itstleo9/info.json
> +    },
```suggestion
    },
    "community_layouts": ["ortho_3x3"],
```

2023-07-06 17:56 UTC, waffle87 commented on keyboards/itstleo/itstleo9/keymaps/via/rules.mk
> +LTO_ENABLE = yes
```suggestion
VIA_ENABLE = yes
```

2023-07-06 23:19 UTC, ItsTLeo commented on keyboards/itstleo/itstleo9/keymaps/via/rules.mk
> +LTO_ENABLE = yes
all changed, thank you

2023-07-07 04:45 UTC, ItsTLeo commented
finished all the change that need to fix on this itstleo9 source code

2023-07-07 12:15 UTC, ItsTLeo commented
> Handwired keyboards should be placed under `keyboards/handwired`.

i will change it as fast as i can, thankyou for remind me

2023-07-07 13:59 UTC, ItsTLeo commented
changed the sourcecode path

2023-07-10 03:26 UTC, waffle87 requested changes

2023-07-10 03:26 UTC, waffle87 commented on keyboards/handwired/itstleo9/readme.md
> +# itstleo/handwired/it9_rp2040
```suggestion
# itstleo9
```

2023-07-10 03:26 UTC, waffle87 commented on keyboards/handwired/itstleo9/readme.md
> +                         [Promicro](https://aliexpress.com/item/32888212119.html)
Also, neither of these links seem to work..
```suggestion
* Hardware Supported: RP2040/ATmega32U4 Pro Micro
* Hardware Availability: [RP2040](https://aliexpress.com/item/1005005616524430.html), [ATmega32U4](https://aliexpress.com/item/32888212119.html)
```

2023-07-10 03:26 UTC, waffle87 commented on keyboards/handwired/itstleo9/readme.md
> +    make itstleo/itstleo9:default:flash
```suggestion
    make handwired/itstleo9/promicro:default
    make handwired/itstleo9/rp2040:default
    
Flashing example for this keyboard:

    make handwired/itstleo9/promicro:default:flash
    make handwired/itstleo9/rp2040:default:flash
```

2023-07-10 03:26 UTC, waffle87 commented on keyboards/handwired/itstleo9/readme.md
> +* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```suggestion
## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (top left key) and plug in the keyboard
* **Physical reset button**: Double-press reset button
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-07-10 06:09 UTC, ItsTLeo commented
thankyou all guys

2023-07-10 06:41 UTC, waffle87 approved these changes

2023-07-10 07:32 UTC, dunk2k approved these changes

2023-07-11 04:16 UTC, drashna approved these changes

2023-07-11 04:16 UTC, merged