Add PW88 keyboard
qmk/qmk_firmware pull request #21482
Opened 2023-07-08 18:40 UTC by SmollChungus

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-08 20:18 UTC, drashna requested changes

2023-07-08 20:18 UTC, drashna commented on lib/chibios
You have changes to the chibios submoudle, which I assume you didn't mean to do.

This should be simpler to fix than in the past. Specifically: 
```sh
cd lib/chibios
git checkout qmk-develop
```

2023-07-08 20:38 UTC, SmollChungus commented on lib/chibios
Definitely unintentional, my apologies.

About the proposed fix above, I'm not certain how to exclude the chibios in this current PR. Would it be easier to start a new pr?

2023-07-08 20:55 UTC, drashna commented on lib/chibios
the above commands should revert to the proper version.  Committing that and pushing it should fix the PR.

2023-07-10 03:15 UTC, waffle87 requested changes

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/config.h
> +#define RGBLIGHT_LAYERS
```suggestion
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/info.json
> +    "bootloader": "rp2040",
```suggestion
    "bootloader": "rp2040",
    "rgblight": {
        "led_count": 34,
        "layers": {
             "enabled": true
        },
        "animation": {
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
        }
    },
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/keymaps/default/keymap.c
> +
```suggestion
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,   KC_SLSH,    KC_RSFT,    _______,                            KC_UP,
    KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT,  MO(1),      KC_RGUI,    KC_RCTL,                 KC_LEFT, KC_DOWN, KC_RGHT
    ),

  [1] = LAYOUT_all(
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,               RGB_TOG, RGB_MOD, RGB_RMOD,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,   KC_TRNS,    RGB_HUI, RGB_SAI, RGB_VAI,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,               RGB_HUD, RGB_SAD, RGB_VAD,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,               KC_TRNS,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    _______,                          KC_VOLU,
    KC_TRNS,  KC_TRNS, KC_TRNS,                                    KC_MPLY,                                        KC_TRNS,    _______, _______,      KC_TRNS,               KC_MPRV, KC_VOLD, KC_MNXT
  )
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/keymaps/default/keymap.c
> +*/
```suggestion
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/keymaps/via/keymap.c
> +
```suggestion
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,   KC_SLSH,    KC_RSFT,    _______,                            KC_UP,
    KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT,  MO(1),      KC_RGUI,    KC_RCTL,                 KC_LEFT, KC_DOWN, KC_RGHT
    ),

  [1] = LAYOUT(
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,               RGB_TOG, RGB_MOD, RGB_RMOD,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,   KC_TRNS,    RGB_HUI, RGB_SAI, RGB_VAI,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,               RGB_HUD, RGB_SAD, RGB_VAD,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,               KC_TRNS,
    KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_TRNS,   KC_TRNS,    _______,                          KC_VOLU,
    KC_TRNS,  KC_TRNS, KC_TRNS,                                    KC_MPLY,                                        KC_TRNS,    _______, _______,      KC_TRNS,               KC_MPRV, KC_VOLD, KC_MNXT
  )
};
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/readme.md
This file need to follow the [template](https://github.com/qmk/qmk_firmware/blob/develop/data/templates/keyboard/readme.md?plain=1).

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/rules.mk
> +WS2812_DRIVER = vendor      # RGB driver
```suggestion
# This file intentionally blank
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/info.json
> +    "layouts": {
```suggestion
    "ws2812": {
        "pin": "GP0",
        "driver": "vendor"
    }, 
    "layouts": {
```

2023-07-10 03:15 UTC, waffle87 commented on keyboards/pw88/info.json
> +    },
```suggestion
    },
    "features": {
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true,
        "rgblight": true,
        "nkro": true
    },
```

2023-07-11 20:02 UTC, SmollChungus commented on lib/chibios
Thank you for the instructions, I believe its fixed now, although I'm not completly sure how to check

2023-07-11 20:03 UTC, SmollChungus reviewed
i believe this covers everything

2023-07-27 01:51 UTC, drashna requested changes

2023-07-27 01:51 UTC, drashna commented on keyboards/pw88/readme.md
> +![%PW88%](https://i.imgur.com/0uN5u2g.jpg)
```suggestion
![%PW88%](https://i.imgur.com/0uN5u2gh.jpg)
```

2023-08-03 04:20 UTC, drashna approved these changes

2023-08-03 04:20 UTC, merged