Add kibou/suisei
qmk/qmk_firmware pull request #21487
Opened 2023-07-09 07:16 UTC by biuboom-jun

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-09 09:36 UTC, fauxpark requested changes

2023-07-09 09:36 UTC, fauxpark commented on keyboards/kibou/suisei/info.json
> +                {"matrix": [3,11], "x":12.25, "y":3, "w":1.752},
```suggestion
                {"matrix": [3,11], "x":12.25, "y":3, "w":1.75}, 
```

2023-07-09 17:58 UTC, drashna approved these changes

2023-07-10 02:49 UTC, waffle87 requested changes

2023-07-10 02:49 UTC, waffle87 commented on keyboards/kibou/suisei/keymaps/default/keymap.c
> +	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
```suggestion
	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, _______, 
```

2023-07-10 02:49 UTC, waffle87 commented on keyboards/kibou/suisei/keymaps/via/keymap.c
> +	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
```suggestion
	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, _______, 
```

2023-07-10 06:41 UTC, waffle87 approved these changes

2023-07-10 06:42 UTC, merged