[Keyboard] Add boardsource/unicorne
qmk/qmk_firmware pull request #21510
Opened 2023-07-11 16:25 UTC by waffle87

## Description

Title.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-12 07:55 UTC, drashna requested changes

2023-07-12 07:55 UTC, drashna commented on keyboards/boardsource/unicorne/config.h
> +#define AUDIO_INIT_DELAY 1000
Setting is a boolean, not a time setting.
```suggestion
#define AUDIO_INIT_DELAY
```

2023-07-12 23:34 UTC, drashna approved these changes

2023-07-20 19:57 UTC, nooges approved these changes

2023-07-20 23:57 UTC, merged