Add dactyl_manuform_rp2040
qmk/qmk_firmware pull request #21538
Opened 2023-07-15 17:50 UTC by GustawXYZ

Adds new keyboard under handwired/dactyl_manuform_rp2040

It is a mashup of alcor_datyl nad dactyl_manuform(5x6)

## Description

Started by cloning alcor_dactyl. Changed GPIOs to be Raspberry Pi Pico friendly.
Changed the layout to use dactyl_manuform 5x6. Added my default keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [NA?] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-16 11:25 UTC, dunk2k requested changes

2023-07-16 11:25 UTC, dunk2k commented on keyboards/handwired/dactyl_manuform_rp2040/keymaps/default/keymap.c
> +
code block not required as encoders not set to true and the code block is essentially null/functionless
```suggestion
```

2023-07-16 11:25 UTC, dunk2k commented on keyboards/handwired/dactyl_manuform_rp2040/keymaps/default/keymap.c
> +#define _GAMING 4
```suggestion
enum layers {
    _QWERTY,
    _NUMPAD,
    _ARROWS,
    _MOUSE,
    _GAMING,
};
```

2023-07-16 11:28 UTC, dunk2k commented
@GustawXYZ 

Would you be able to change `dactyl_manuform_rp2040` to `dactyl_manuform_pi_pico` as not to confuse terminology with QMK's rp2040 based converters and rp2040 development boards?

2023-07-16 11:48 UTC, dunk2k requested changes

2023-07-16 11:48 UTC, dunk2k commented on keyboards/handwired/dactyl_manuform_rp2040/info.json
> +        "driver": "WS2812",
```suggestion
        "driver": "WS2812",
        "split_count": [1, 1],
```

2023-07-16 11:48 UTC, dunk2k commented on keyboards/handwired/dactyl_manuform_rp2040/config.h
> +    { 1, 1 }
moved to `info.json`
```suggestion
```

2023-09-15 19:00 UTC, drashna requested changes

2023-09-15 19:00 UTC, drashna commented on keyboards/handwired/dactyl_manuform_pi_pico/readme.md
> +    make dactyl_manuform_pi_pico:default
```suggestion
    make handwired/dactyl_manuform_pi_pico:default
```

2023-09-15 19:00 UTC, drashna commented on keyboards/handwired/dactyl_manuform_pi_pico/readme.md
> +    make dactyl_manuform_pi_pico:default:flash
```suggestion
    make handwired/dactyl_manuform_pi_pico:default:flash
```

2023-09-15 22:12 UTC, GustawXYZ commented on keyboards/handwired/dactyl_manuform_pi_pico/config.h
> +#define EE_HANDS
Thanks for the pointer. I don't think I've noticed any issues using the keyboard for last month or two. Although pi pico has plenty GPIO. What would be the symtomps of this? Bacause I'm not sure if it's worth resoldering

2023-09-15 22:13 UTC, GustawXYZ commented on keyboards/handwired/dactyl_manuform_pi_pico/info.json
> +        "driver": "WS2812",
Thanks a lot! I was going to look into that in some spare time

2023-09-21 03:50 UTC, drashna commented on keyboards/handwired/dactyl_manuform_pi_pico/config.h
> +#define EE_HANDS
Mostly, user experience.  If it's working fine, that that's okay.

2023-12-15 01:49 UTC, closed without merging