Move files to rev1 folder, add rev2
qmk/qmk_firmware pull request #21563
Opened 2023-07-19 18:46 UTC by nooges

## Description

- Moves Rev. 1 into its own folder
- Add RP2040-based Rev. 2

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-19 21:39 UTC, dunk2k requested changes

2023-07-19 21:39 UTC, dunk2k commented on keyboards/keebio/chocopad/rev1/info.json
> +    "bootloader": "caterina",
```suggestion
    "development_board": "promicro",
```

2023-07-19 21:40 UTC, dunk2k commented
`readme.md` will need to be changed to reflect these changes, as running command `make keebio/chocopad:default` will fail.

2023-07-20 07:32 UTC, drashna approved these changes

2023-07-20 11:34 UTC, dunk2k approved these changes

2023-07-20 12:10 UTC, merged

2023-07-20 13:38 UTC, fauxpark commented
This PR should have gone to develop.