[keyboard] tominabox1/le_chiffre refactor pt 1
qmk/qmk_firmware pull request #21567
Opened 2023-07-20 15:27 UTC by lesshonor

## Description

### Keyboard
- Unifies data that is common across all revisions
- Migrates various attributes to `info.json`
  - ...This had the unintended side effect of fixing the RGB Matrix configuration.
- The OLED was originally disabled by default because of an i2c timeout problem that has been fixed for years, so reenable it.
- Updates readme to fit current standards and add information.
- Runs `format-c` / `format-json` on files.

### Keymaps
- All keymaps now leverage encoder mapping.
- `via` keymap had extra transparent layers removed and now compiles with OLED enabled.
- General cleanup/reformatting

**Yes**, an OLED refactor is in the works, but has been omitted from this PR for ease of review.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-20 21:58 UTC, dunk2k requested changes

2023-07-20 21:58 UTC, dunk2k commented on keyboards/tominabox1/le_chiffre/info.json
> +        "hue_steps": 8,
default value (source: `/quantum/rgblight/rgblight.h`)
```suggestion
```

2023-07-21 06:05 UTC, drashna approved these changes

2023-07-25 03:09 UTC, waffle87 commented on keyboards/tominabox1/le_chiffre/info.json
> +        "rgb_matrix": true
Since OLEDs are enabled at the keyboard level, could you place the current OLED code in a `le_chiffre.c` file and remove it from the keymaps

2023-07-25 06:27 UTC, waffle87 commented on keyboards/tominabox1/le_chiffre/info.json
> +        "rgb_matrix": true
Ah, I see, thanks for the consideration. A future PR is a fine approach.

2023-07-25 06:27 UTC, waffle87 approved these changes

2023-07-25 06:29 UTC, merged