Add QMK support for Okayu
qmk/qmk_firmware pull request #21575
Opened 2023-07-21 03:29 UTC by MaiTheSan

## Description
Add support for Salane Okayu PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-21 07:23 UTC, drashna requested changes

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/readme.md
> +![Okayu](https://i.imgur.com/pRnRHl8.png)
```suggestion
![Okayu](https://i.imgur.com/pRnRHl8h.png)
```

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f072/info.json
> +        "rgblight": {
```suggestion
    "rgblight": {
```

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f072/mcuconf.h
> +#define WS2812_SPI_SCK_PAL_MODE 5 // SCK pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 5
This should be in your config.h, not here.

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f303/chconf.h
Is this actually needed?

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f072/chconf.h
Is this actually needed?

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f303/info.json
> +        "rgblight": {
```suggestion
    "rgblight": {
```

2023-07-21 07:23 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f303/mcuconf.h
> +#define WS2812_SPI_SCK_PAL_MODE 5 // SCK pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 5
This needs to be in the config.h, not here.

2023-07-21 11:59 UTC, dunk2k requested changes

2023-07-21 11:59 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/info.json
> +    "keyboard_name": "Salane | Okayu",
```suggestion
    "keyboard_name": "Okayu",
```

2023-07-21 11:59 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/info.json
@MaiTheSan 
Could you review 60% (60_*) layouts in `/layouts/default` for matching key arrangements this PCB matches.

Per match:
1. Append `"layouts"` with matching layout name and layout information, assign matrix positions/co-ordinates
2. Add `"community_layouts": []` to `info.json`, entering matching layout names (minus `LAYOUT_`) as comma separated JSON strings.
e.g. `"community_layouts" : ["60_ansi", "60_iso"]`

2023-07-21 16:52 UTC, waffle87 requested changes

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/info.json
> +        "command": true,
Unless there's a specific reason to have these enabled.
```suggestion
        "console": false,
        "command": false,
```

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/keymaps/default/readme.md
This file should be removed.

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/keymaps/via/readme.md
This file should be removed.

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f303/info.json
> +    }
```suggestion
```

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/info.json
> +    }
```suggestion
```

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/info.json
> +    },
```suggestion
    },
    "bootloader": "stm32-dfu",
    "matrix_pins": {
        "cols": ["A9", "A0", "A8", "C13", "C4", "C2", "B11", "B10", "B1", "B0", "A7", "A6", "A5", "A4"],
        "rows": ["B3", "A15", "A3", "A10", "B14"]
    },
    "diode_direction": "COL2ROW",
    "indicators": {
        "caps_lock": "B12"
    },
    "ws2812": {
        "pin": "B15",
        "driver": "spi"
    },
    "rgblight": {
        "led_count": 24,
        "sleep": true,
        "animations": {
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
        }
    },
```

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/mcuconf.h
> + */
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/mcuconf.h
This file should be moved to the top keyboard level (`keyboards/sawnsprojects/okayu`), and removed from here.

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f303/mcuconf.h
This file should be removed with the above suggestion.

2023-07-21 16:52 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/halconf.h
This file should be moved to the top keyboard level (`keyboards/sawnsprojects/okayu`), and removed from here.

2023-07-25 03:04 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/chconf.h
Then the file should be removed.

2023-09-06 09:41 UTC, closed without merging