Redox keymap for muralisc
qmk/qmk_firmware pull request #21584
Opened 2023-07-22 16:02 UTC by muralisc

## Description

Redox Keymap for muralisc

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-22 18:21 UTC, dunk2k requested changes

2023-07-22 18:21 UTC, dunk2k commented on keyboards/redox/keymaps/muralisc/keymap.c
> +#define _ADJUST 3
```suggestion
enum layers {
    _QWERTY,
    _SYMB,
    _NAV,
    _ADJUST,
};
```

2023-07-22 18:21 UTC, dunk2k commented on keyboards/redox/keymaps/muralisc/readme.md
Based on this file's current contents, it would be best if it was removed/deleted

2023-07-22 18:21 UTC, dunk2k commented on keyboards/redox/keymaps/muralisc/config.h
> +#define RGBLIGHT_HUE_STEP 8
default value (source: `/quantum/rgblight/rgblight.h`)
```suggestion
```

2023-07-24 07:33 UTC, waffle87 requested changes

2023-07-24 07:33 UTC, waffle87 commented on keyboards/redox/keymaps/muralisc/keymap.c
> +
```suggestion
```

2023-07-24 07:33 UTC, waffle87 commented on keyboards/redox/keymaps/muralisc/keymap.c
> +#define KC_NAMI LT(_NAV, KC_MINS)
```suggestion
```

2023-08-02 21:39 UTC, dunk2k approved these changes

2023-08-12 08:22 UTC, drashna requested changes

2023-08-12 08:22 UTC, drashna commented on keyboards/redox/keymaps/muralisc/config.h
> +#define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```
or
```suggestion
            "alternating": true,
            "breathing": true,
            "christmas": true,
            "knight": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "rgb_test": true,
            "snake": true,
            "static_gradient": true,
            "twinkle": true
```

2023-08-12 08:22 UTC, drashna commented on keyboards/redox/keymaps/muralisc/keymap.c
> +#include QMK_KEYBOARD_H
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2023 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-08-29 17:38 UTC, closed without merging