DD framebuffer and reactive configs for LED/RGB Matrix
qmk/qmk_firmware pull request #21598
Opened 2023-07-24 11:52 UTC by dexter93

invocation example
```json
    "rgb_matrix": {
        "framebuffer": true,
         "reactive": {
              "keypresses" : true,
              "keyreleases" : false
          },
    }
```

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-24 13:01 UTC, sigprof requested changes

2023-07-24 13:26 UTC, dexter93 commented on lib/python/qmk/cli/generate/config_h.py
> +            config_h_lines.append(generate_define(f'{prefix}{"MATRIX_"}{reactive.upper()}'))
well, it was an idea. migrated with 3cb8bb09c0759510f4a960387736a3e920704573

2023-07-24 13:36 UTC, dunk2k approved these changes

2023-09-26 23:41 UTC, zvecr commented
Implemented as 21939.

2023-09-26 23:41 UTC, closed without merging