add new keyboard epiphany70
qmk/qmk_firmware pull request #21616
Opened 2023-07-26 08:50 UTC by spbgzh

## Description
add new keyboard epiphany70

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-26 09:29 UTC, dunk2k requested changes

2023-07-26 09:29 UTC, dunk2k commented on keyboards/wuque/epiphany70/rules.mk
> +RGBLIGHT_ENABLE = yes
moved to `info.json`
```suggestion
# This file is intentionally blank
```

2023-07-26 09:29 UTC, dunk2k commented on keyboards/wuque/epiphany70/info.json
> +      "nkro": true
rgblight_enable migrated from `rules.mk`
```suggestion
      "nkro": true,
      "rgblight": true
```

2023-07-26 09:29 UTC, dunk2k commented on keyboards/wuque/epiphany70/info.json
> +    },
rbglight defs migrated from `config.h`
```suggestion
        "led_count": 7,
        "sleep": true,
        "saturation_steps": 8,
        "brightness_steps": 8,
        "animations": {
            "breathing": true,
            "rainbow_mood": true,
            "rainbow_swirl": true,
            "snake": true,
            "knight": true,
            "christmas": true,
            "static_gradient": true,
            "rgb_test": true,
            "alternating": true,
            "twinkle": true
        }
    },
```

2023-07-26 09:29 UTC, dunk2k commented on keyboards/wuque/epiphany70/config.h
The suggestion of migrating (all) settings in this file to `info.json` results in this file not being required.  
Could this file be removed if the suggestion to migrate contents to `info.json` is accepted?

2023-07-26 09:34 UTC, spbgzh commented
@dunk2k fixed)

2023-07-26 09:37 UTC, dunk2k approved these changes

2023-07-26 09:37 UTC, spbgzh commented on keyboards/wuque/epiphany70/info.json
> +    },
I just dont know how to write it(

2023-07-26 09:38 UTC, spbgzh commented on keyboards/wuque/epiphany70/config.h
deleted

2023-07-26 09:39 UTC, dunk2k requested changes

2023-07-26 09:39 UTC, dunk2k commented on keyboards/wuque/epiphany70/keymaps/via/keymap.c
> +    ),
remove non-functional layers. VIA defaults to 4 layers regardless if 4 layers are specified, or not, in keymap
```suggestion
    )
```

2023-07-26 09:43 UTC, dunk2k approved these changes

2023-07-26 15:16 UTC, spbgzh commented
![mmexport1690384202096.jpg](https://github.com/qmk/qmk_firmware/assets/72414103/6f333721-d32c-4d6d-85eb-53c906ff63e3)

![mmexport1690384150621.jpg](https://github.com/qmk/qmk_firmware/assets/72414103/9f01a406-899e-4910-b07b-935627000f8d)

@lesshonor 
they are different keuboards now

2023-07-27 15:45 UTC, zvecr requested changes

2023-07-27 15:45 UTC, zvecr commented on keyboards/wuque/epiphany70/info.json
> +      "brightness_steps": 8,
```suggestion
```

2023-07-27 15:45 UTC, zvecr commented on keyboards/wuque/epiphany70/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader using one of the following methods:

* Tap the Reset switch mounted on the PCB
* In the case of the default keymap, use the key combination Fn + PageUp
* Hold the Esc key while connecting the USB cable (also erases persistent settings)
```

2023-08-12 08:26 UTC, drashna approved these changes

2023-10-07 14:47 UTC, fauxpark requested changes

2023-10-07 14:47 UTC, fauxpark commented on keyboards/wuque/epiphany70/readme.md
> +Make example for this keyboard (after setting up your build environment):
```suggestion
* Hardware Availability: [epiphany70](https://shop.wuquestudio.com/)

Make example for this keyboard (after setting up your build environment):
```

2023-10-12 06:30 UTC, drashna approved these changes

2023-11-11 18:46 UTC, drashna approved these changes

2024-08-26 10:34 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2025-04-14 14:24 UTC, closed without merging