Kintwin controller for kinesis keyboard, split layout
qmk/qmk_firmware pull request #21614
Opened 2023-07-26 03:46 UTC by alvicstep

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-26 08:37 UTC, fauxpark requested changes

2023-07-26 08:37 UTC, fauxpark commented on keyboards/kinesis/kintwin/config.h
> +/* Copyright 2023 Alex Stepanov
This file can be deleted.

2023-07-26 08:37 UTC, fauxpark commented on keyboards/kinesis/keymaps/default/keymap.c
> +/* Copyright 2023 QMK
Prefer SPDX headers eg.
```c
// Copyright %YEAR% %REAL_NAME% (@%USER_NAME%)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-07-27 15:36 UTC, zvecr requested changes

2023-07-27 15:36 UTC, zvecr commented on keyboards/kinesis/kintwin/info.json
> +        "extrakey": false,
```suggestion
        "mousekey": true,
        "extrakey": true,
```

2023-07-27 15:36 UTC, zvecr commented on keyboards/kinesis/kintwin/halconf.h
This file should be removed as nothing is configured to use pwm or i2c.

2023-07-27 15:36 UTC, zvecr commented on keyboards/kinesis/kintwin/mcuconf.h
This file should be removed as nothing is configured to use pwm or i2c.

2023-07-28 14:30 UTC, fauxpark requested changes

2023-07-28 16:51 UTC, zvecr commented on keyboards/kinesis/rules.mk
Removing this file, and not migrating its settings to each build revision will mean they now have the various features disabled now. The `features` object should be added to the relevant `info.json` files.

2023-08-03 14:45 UTC, fauxpark approved these changes

2023-08-03 14:45 UTC, fauxpark commented on keyboards/kinesis/kintwin/info.json
> +                {"matrix": [6, 4], "x": 5.25, "y": 7, "h": 2},
```suggestion
                {"matrix": [6, 4], "x": 5.25, "y": 7, "h": 2},
```
etc

2023-08-04 07:27 UTC, fauxpark commented on keyboards/kinesis/kintwin/info.json
> +            "keyboard": true
etc

2023-08-08 17:34 UTC, laffed commented
@zvecr  please <3
![7v4w9e](https://github.com/qmk/qmk_firmware/assets/55990572/2ce02668-f924-42d3-8b93-9d37b9d0d4e3)

2023-08-14 06:57 UTC, drashna approved these changes

2023-08-14 07:01 UTC, merged

2023-12-19 15:51 UTC, asegarra commented
@alvicstep apologize for contacting you here but found no other way, just wanted to know if your board is compatible with STM32F411 ?

2023-12-19 19:07 UTC, alvicstep commented
Yes it is

It is a fork of kinbp board

You can find github pages for both boards

Thanks

On Tue, Dec 19, 2023 at 7:51 AM Angel Segarra ***@***.***>
wrote:

> @alvicstep <https://github.com/alvicstep> apologize for contacting you
> here but found no other way, just wanted to know if your board is
> compatible with STM32F411 ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qmk/qmk_firmware/pull/21614#issuecomment-1863021697>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEY7SXZA26AWMYDKLNM43WDYKGZXLAVCNFSM6AAAAAA2X6UYBKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRTGAZDCNRZG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>