Add Garavito keymap to lily58
qmk/qmk_firmware pull request #21627
Opened 2023-07-27 21:58 UTC by EGaravitoM

## Description

Add Garavito keymap to Lily58

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-02 21:47 UTC, dunk2k requested changes

2023-08-02 21:47 UTC, dunk2k commented on keyboards/lily58/keymaps/garavito/config.h
> +// #define EE_HANDS
not required:
1. MASTER_LEFT is default handedness settings for split keyboards
2. doesn't override handedness settings from directories above, as there are none.
```suggestion
```

2023-08-02 21:47 UTC, dunk2k commented on keyboards/lily58/keymaps/garavito/rules.mk
> +OLED_DRIVER = SSD1306
already defined in `rules.mk` of directories above
```suggestion
```

2023-08-14 18:41 UTC, waffle87 requested changes

2023-08-14 18:41 UTC, waffle87 commented on keyboards/lily58/keymaps/garavito/keymap.c
> +// }
```suggestion
```

2023-08-14 18:41 UTC, waffle87 commented on keyboards/lily58/keymaps/garavito/config.h
> +
```suggestion
```

2023-08-29 17:38 UTC, zvecr commented
Unfortunately since this PRs creation, QMK has [changed its stance](https://docs.qmk.fm/#/ChangeLog/20230827?id=notable-changes) on accepting user keymaps to the repository.

> qmk/qmk_firmware is no longer accepting PRs for keymaps other than for manufacturer-supported keymaps. User keymap workflow has been documented [here](https://docs.qmk.fm/#/newbs) for several years. This change is to progressively reduce the maintenance burden on the project, and to allow us to focus on the core features of QMK.

In the near future we will be providing a more user focused workflow for keymaps, but till then the suggestion is to keep changes in your own fork.

While we appreciate the time that was taken on this PR, hopefully you understand we are closing it, so that QMK can improve in the long term.

2023-08-29 17:38 UTC, closed without merging