Refactoring entirely Caticorn PCB
qmk/qmk_firmware pull request #21644
Opened 2023-07-30 15:24 UTC by HorrorTroll

## Description

Refactoring entirely Caticorn PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-30 15:43 UTC, dunk2k commented
As per PR Contributing guidelines, these changes should be targeted at `develop` branch

2023-07-31 09:05 UTC, fauxpark requested changes

2023-07-31 09:05 UTC, fauxpark commented on keyboards/horrortroll/caticorn/rev1/hotswap/info.json
> -
Please keep the spacing here.

2023-07-31 15:35 UTC, HorrorTroll commented
Thanks both of you guys for pointing me out some issues. I've just pushed new commit to resolved these problem, and re-target from `master` to `develop` branch. If you have time, feel free to checked.

2023-07-31 16:37 UTC, dunk2k commented
@HorrorTroll 
> Would you be able to cross reference `tkl` entries in `/layouts/default` for matching layouts this PCB can accommodate? adding matching layouts to `"community_layouts"` and "`layouts"` in info.json.

2023-07-31 17:10 UTC, HorrorTroll commented
Ummm, I've still not know what that mean?

Did you mean solder or hotswap PCB? If it the solder PCB, I've been added all the `TKL` entries from `/layouts/default`, because the PCB supported all of it.

While hotswap board is just only `tkl_f13_ansi` anyway. Thanks!
@dunk2k

2023-07-31 17:24 UTC, dunk2k commented
> I've been added all the `TKL` entries from `/layouts/default`, because the PCB supported all of it.
> 
> While hotswap board is just only `tkl_f13_ansi` anyway. 

Thanks for clarifying 😊

2023-07-31 22:34 UTC, fauxpark approved these changes

2023-08-03 06:39 UTC, drashna commented on keyboards/horrortroll/caticorn/rev1/hotswap/keymaps/default/keymap.c
> +    _FN
This should be reverted. 
```suggestion
    _FN,
```
While not critical, clang-format will condense this to one line for the entire enum. The comma at the end prevents it from doing so.

2023-08-03 06:39 UTC, drashna commented on keyboards/horrortroll/caticorn/rev1/hotswap/keymaps/via/keymap.c
> +    _FN
```suggestion
    _FN,
```

2023-08-03 06:40 UTC, drashna approved these changes
a couple of nits, but otherwise, LGTM.

2023-08-05 03:06 UTC, HorrorTroll commented
Thanks, I've just resolved the suggested. If you have time, please take a look.

2023-08-14 06:13 UTC, merged