Adding support for new Waffling60 revision
qmk/qmk_firmware pull request #21664
Opened 2023-08-01 18:21 UTC by 4pplet

## Description

Adding QMK support for the latest revision of waffling60. Revision E adds underglow and 6u space support. 

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-01 20:38 UTC, dunk2k requested changes

2023-08-01 20:38 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/info.json
> +        "backlight": false,
not enabled by default
```suggestion
        "audio": false,
        "backlight": false,
```

2023-08-01 20:38 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/keymaps/via/rules.mk
> +VIA_ENABLE = yes
Required for conditional encoder_map_enable code in `keymap.c` to trigger
```suggestion
VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
```

2023-08-01 20:38 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/keymaps/via/keymap.c
> +    [3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
1. non-functional layers removed
```suggestion
  KC_TRNS,  KC_TRNS,  KC_TRNS,            KC_TRNS,              KC_TRNS,              KC_TRNS,               KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS)
};
#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(KC_BRID, KC_BRIU) }
```

2023-08-01 20:38 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-08-01 20:40 UTC, dunk2k commented
Could you add a `rules.mk` file to `keymaps/default` directory with contents:
```
ENCODER_MAP_ENABLE = yes

```

2023-08-01 22:05 UTC, fauxpark requested changes

2023-08-01 22:05 UTC, fauxpark commented on keyboards/4pplet/waffling60/rev_e/rev_e.h
> +#include "quantum.h"
```suggestion
#include "quantum.h"

#define CAPS_LOCK_ENABLE true
#define CAPS_LOCK_COLOR HSV_GREEN
```

2023-08-01 22:05 UTC, fauxpark commented on keyboards/4pplet/waffling60/rev_e/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```suggestion
```

2023-08-01 22:12 UTC, 4pplet commented
> @4pplet Could you add a `rules.mk` file to `keymaps/default` directory with contents:
> 
> ```
> ENCODER_MAP_ENABLE = yes
> ```

Added now! :)

2023-08-01 22:19 UTC, dunk2k requested changes

2023-08-01 22:19 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/info.json
> +        "backlight": false,
not enabled by default
```suggestion
```

2023-08-16 09:12 UTC, dunk2k requested changes

2023-08-16 09:12 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/rules.mk
> +KEY_LOCK_ENABLE = yes
migrate to `info.json`
```suggestion
```

2023-08-16 09:12 UTC, dunk2k commented on keyboards/4pplet/waffling60/rev_e/info.json
> +        "extrakey": true,
migrated from `rules.mk`
```suggestion
        "extrakey": true,
        "key_lock": true,
```

2023-08-17 03:34 UTC, drashna approved these changes

2023-08-23 09:32 UTC, 4pplet commented
Any update on this? This should be ready for merge?

2023-08-30 03:30 UTC, drashna approved these changes

2023-08-30 03:30 UTC, drashna commented
> Any update on this? This should be ready for merge?

Sorry, the last couple of weeks are/were breaking changes time, so ... busy and merge blocked.

2023-08-31 23:03 UTC, fauxpark requested changes
This PR should go to `develop`, as it modifies existing keyboard files.

2023-09-29 09:32 UTC, fauxpark requested changes

2023-09-29 09:32 UTC, fauxpark commented on keyboards/4pplet/waffling60/rev_e/rules.mk
> +
```suggestion
```

2023-09-29 10:34 UTC, dunk2k commented
@4pplet 

Reading `readme.md` says there is 6u (space bar) support but not seeing anything here that show it. Would you be able to provide a `matrix_diagram.md`?

2023-10-05 03:25 UTC, drashna commented
> @4pplet
> 
> Reading `readme.md` says there is 6u (space bar) support but not seeing anything here that shows it. Would you be able to provide a `matrix_diagram.md`?

Yeah, it's a bit odd to call it out in the readme, but not actually support it in the config. 

One or the other should go, but it sounds like ideally, the config should be updated.

2023-10-05 08:24 UTC, 4pplet commented
For sure, I'll add layouts in info.json for: 6u ISO, 6u ISO split backspace, 6u ANSI, 6u ANSI split backspace before merge. That should be fine?

2023-10-05 10:42 UTC, dunk2k commented
> For sure, I'll add layouts in info.json for: 6u ISO, 6u ISO split backspace, 6u ANSI, 6u ANSI split backspace before merge. That should be fine? And a matrix diagram

Yes please, thank you.

2023-10-12 05:34 UTC, drashna approved these changes

2023-10-25 09:09 UTC, 4pplet commented
This should be ready for merge?

2023-10-25 09:25 UTC, fauxpark approved these changes

2023-10-27 06:42 UTC, merged

2023-10-27 06:42 UTC, drashna commented
Thanks!