Update personal keymap
qmk/qmk_firmware pull request #21674
Opened 2023-08-02 14:08 UTC by rpbaptist

## Description

This is an update of my personal keymap. Current keymap in master branch is broken and outdated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-03 07:31 UTC, drashna requested changes

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/config.h
> +#define USB_POLLING_INTERVAL_MS 1
This is unneeded, as it is the default setting.
```suggestion
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/oled.c
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/oled.h
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/rgb.c
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/rgb.c
> +void matrix_scan_user(void) {
should use:
```suggestion
void housekeeping_task_user(void) {
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/rgb.h
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/rgb.h
> +user_config_t user_config;
This should be an extern, and declared in a c file.
```suggestion
extern user_config_t user_config;
```

Also, you may want: 
```c
_Static_assert(sizeof(user_config_t) == sizeof(uint32_t), "Userspace EECONFIG out of spec.");
```

2023-08-03 07:31 UTC, drashna commented on keyboards/crkbd/keymaps/rpbaptist/rpbaptist.h
Could you add a GPL2+ compatible license header here?  All of the source files need to have a license explicitly listed.

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-08-03 08:11 UTC, rpbaptist commented on keyboards/crkbd/keymaps/rpbaptist/rpbaptist.h
> +uint32_t idle_timer;
I was not aware of that function. I'll happily use that instead. Thank you!

2023-08-03 08:16 UTC, rpbaptist commented on keyboards/crkbd/keymaps/rpbaptist/glcdfont_multi.c
> +#if defined(THEME_GODSPEED) || defined(THEME_GODSPEED_ARES)
Will do!

2023-08-06 12:19 UTC, rpbaptist commented
I moved the keymap to the `rev1` directory as the build was too large for the `r2g` version.

2023-08-12 09:35 UTC, drashna approved these changes

2023-08-14 18:20 UTC, waffle87 approved these changes

2023-08-14 18:21 UTC, merged