rename og60 to tofu60
qmk/qmk_firmware pull request #21684
Opened 2023-08-03 08:32 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-03 11:10 UTC, dunk2k commented
Missing corresponding entry in `/data/mappings/keyboard_aliases.hjson`

2023-08-07 17:51 UTC, dunk2k requested changes

2023-08-07 17:51 UTC, dunk2k commented on data/mappings/keyboard_aliases.hjson
> +	"dztech/tofu60": {
```suggestion
	"dztech/og60": {
```

2023-08-07 17:51 UTC, dunk2k commented on keyboards/dztech/tofu60/keymaps/default/keymap.c
As layers 1-3 are repeats of layer 0 and there is no means to switch between layers, could layer count be reduced to just layer 0

2023-08-07 17:51 UTC, dunk2k commented on keyboards/dztech/tofu60/keymaps/via/keymap.c
As layers 1-3 are repeats of layer 0 and there is no means to switch between layers, could layer count be reduced to just layer 0

2023-08-12 19:05 UTC, dunk2k approved these changes

2023-08-16 01:14 UTC, drashna approved these changes

2023-08-16 07:08 UTC, fauxpark requested changes

2023-08-16 07:08 UTC, fauxpark commented on data/mappings/keyboard_aliases.hjson
> +	"dztech/og60": {
```suggestion
    "dztech/og60": {
```

2023-08-23 13:21 UTC, fauxpark approved these changes

2023-09-15 19:36 UTC, merged