Add faunchpad and my keymap
qmk/qmk_firmware pull request #21693
Opened 2023-08-04 16:07 UTC by loadedsith

The Faunch pad had a limited release, as far as I can tell, it is very uncommon. Shortly after the release, something happened that caused the original author to not contribute the files to QMK. I do not know if my contributing them now is the right thing to do or not, but I fear the files could be lost if they're not contributed. 

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-04 19:30 UTC, dunk2k requested changes

2023-08-04 19:30 UTC, dunk2k commented on keyboards/gboards/k/faunchpad/keymaps/default/keymap.c
> +// Don't fuck with this, thanks.
```suggestion
// please do not alter this section of code, thanks.
```

2023-08-04 19:30 UTC, dunk2k commented on keyboards/gboards/k/faunchpad/keymaps/grahampheath-kvm/keymap.c
> +// Don't fuck with this, thanks.
```suggestion
// please do not alter this section of code, thanks.
```

2023-08-04 19:33 UTC, dunk2k commented on keyboards/gboards/k/faunchpad/readme.md
> +![Faunchpad](https://assets.bigcartel.com/product_images/247416671/IMG_20191025_1322045-01.jpeg)
Could this image be re-hosted on imgur?

2023-08-14 18:12 UTC, waffle87 requested changes

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/config_engine.h
This file is missing a license header.

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/config_engine.h
> +
```suggestion
#pragma once
```

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/faunchpad.c
> +#include "faunchpad.h"
Edited.

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/faunchpad.c
> +}
Does this serve any purpose beside printing debug info? If not, it's best if this file is just removed.

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/info.json
> +      "LAYOUT_faunch": {
This change will need to be reflected in the keymaps as well.
```suggestion
      "LAYOUT": {
```

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/keymaps/grahampheath-kvm/keymap.c
> +              // when keycode QMKBEST is released
```suggestion
              tap_code(KC_SCROLL_LOCK);
              tap_code(KC_SCROLL_LOCK);
              tap_code(KC_1);
```

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/keymaps/grahampheath-kvm/keymap.c
> +          // when keycode QMKBEST is released
```suggestion
          tap_code(KC_SCROLL_LOCK);
          tap_code(KC_SCROLL_LOCK);
          tap_code(KC_3);
```

2023-08-14 18:12 UTC, waffle87 commented on keyboards/gboards/k/faunchpad/keymaps/grahampheath-kvm/keymap.c
> +          // when keycode QMKBEST is released
```suggestion
          tap_code(KC_SCROLL_LOCK);
          tap_code(KC_SCROLL_LOCK);
          tap_code(KC_PGDN);
```

2023-12-15 01:50 UTC, closed without merging