add shostudio arc pcb
qmk/qmk_firmware pull request #21733
Opened 2023-08-11 09:59 UTC by mechlovin

## Description
Add shostudio ARC PCB. An Ergonomic 65% PCB, APM32F103.
Thanks.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [s] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-11 13:56 UTC, zvecr requested changes
Both keymaps have multiple references to layers that do not exist

2023-08-12 18:49 UTC, drashna approved these changes

2023-08-12 18:50 UTC, drashna approved these changes

2023-08-14 17:18 UTC, waffle87 approved these changes

2023-08-14 17:18 UTC, merged