add tofujr v2 keyboard
qmk/qmk_firmware pull request #21740
Opened 2023-08-12 00:37 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-12 07:02 UTC, dunk2k commented
Missing a `readme.md` file.
Template is available in `/data/templates/keyboard`

2023-08-30 02:34 UTC, drashna approved these changes

2023-08-31 23:01 UTC, fauxpark requested changes
This PR should go to `develop`, as it modifies existing keyboard files.

2023-09-19 08:42 UTC, fauxpark requested changes

2023-09-19 08:42 UTC, fauxpark commented on keyboards/dztech/tofu/jr/v2/info.json
> +        "rgblight": true
```suggestion
        "rgblight": true
```

2023-09-26 01:16 UTC, merged