Added timeout option for OLED boot logo.
qmk/qmk_firmware pull request #21823
Opened 2023-08-23 22:00 UTC by luttermann

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-23 23:10 UTC, zvecr requested changes

2023-08-23 23:10 UTC, zvecr commented on keyboards/doio/kb16/rev1/config.h
> +
```suggestion
```

2023-08-23 23:10 UTC, zvecr commented on keyboards/doio/kb16/rev2/config.h
> +
```suggestion
```

2023-08-23 23:10 UTC, zvecr commented on keyboards/doio/kb16/kb16.c
Somewhere at the top of the file,
```c
/* Default timeout for displaying boot logo */
#ifndef OLED_LOGO_TIMEOUT
    #define OLED_LOGO_TIMEOUT 5000
#endif
```

2023-08-24 07:20 UTC, luttermann commented on keyboards/doio/kb16/kb16.c
You're right @zvecr, it doesn't make sense to have the configuration separated for `rev1` and `rev2`, but wouldn't it make more sense to put it into a new header file `keyboards/doio/kb16/config.h` instead?

That could be done for all the common settings for the two revisions (Thats most of them, I'll gladly make a separate PR for that, or update this one).

2023-08-24 14:09 UTC, zvecr commented on keyboards/doio/kb16/kb16.c
This particular setting does not need to be in a config.h at all. Doing so then requires users to undef when specifying their override.

2023-08-25 08:40 UTC, luttermann commented on keyboards/doio/kb16/kb16.c
Thanks for the information and suggestions :smiley:

2023-08-26 01:23 UTC, drashna approved these changes

2023-08-30 00:33 UTC, zvecr approved these changes

2023-08-30 00:34 UTC, merged