Add M6-C Keyboard Firmware
qmk/qmk_firmware pull request #21852
Opened 2023-08-28 02:16 UTC by ToastyStoemp

## Description

Add Firmware for the Rama M6-c

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-28 14:19 UTC, zvecr requested changes

2023-08-28 14:19 UTC, zvecr commented on keyboards/wolf/m6_c/info.json
> +        "rgblight": false
```suggestion
        "rgb_matrix": true
```

2023-08-28 14:19 UTC, zvecr commented on keyboards/wolf/m6_c/config.h
> +
```suggestion
```

2023-08-30 01:45 UTC, drashna requested changes

2023-08-30 01:45 UTC, drashna commented on keyboards/wolf/m6_c/keymaps/via/rules.mk
> +LTO_ENABLE = yes
Not sure you need lto here, but shouldn't hurt anything either.

2023-08-30 01:45 UTC, drashna commented on keyboards/wolf/m6_c/info.json
> +        "driver": "WS2812",
```suggestion
        "driver": "ws2812",
```

2023-09-01 05:42 UTC, drashna approved these changes

2023-09-01 05:43 UTC, fauxpark approved these changes

2023-09-03 04:32 UTC, merged