add dz60v2 keyboard
qmk/qmk_firmware pull request #21862
Opened 2023-08-29 09:34 UTC by moyi4681

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-29 10:45 UTC, dunk2k commented
If it's not too much to ask, could you add the following community layouts (`/layouts/default`), using mod numbers in `readme.md` as reference, to `layouts` in `info.json`?

| layout name | mod numbers |
| :---: | :---: |
| 60_ansi_tsangan | 13 |
| 60_iso_split_bs_rshift | 1, 2, 3, 6  |
| 60_iso_tsangan | 13 |
| 64_ansi | 7, 8, 15 |
| 64_iso | 2, 7, 8, 15, 16 |

2023-08-29 11:07 UTC, dunk2k requested changes

2023-08-29 11:07 UTC, dunk2k commented on keyboards/dztech/dz60v2/info.json
1 is the default for key width, please can all instances of `"w" :1` be removed

2023-08-29 11:07 UTC, dunk2k commented on keyboards/dztech/dz60v2/info.json
> +    "debounce": 5,
5 is default settings for debounce
```suggestion
```

2023-08-29 14:39 UTC, dunk2k requested changes

2023-08-29 14:39 UTC, dunk2k commented on keyboards/dztech/dz60v2/info.json
> +    },
assuming RGB lighting will use the ws2182 driver, defined pin will need to be moved to `ws2812.pin`
```suggestion
        "saturation_steps": 10
    },
    "ws2812": {
        "pin": "B2"
    },
```

2023-08-29 23:19 UTC, drashna requested changes

2023-08-29 23:19 UTC, drashna commented on keyboards/dztech/dz60v2/info.json
> +    },
formatting nit: 
```suggestion
        },
```

2023-08-29 23:19 UTC, drashna commented on keyboards/dztech/dz60v2/readme.md
> +![A Customizable 60% Mechanical Keyboard PCB](https://cdn.shopify.com/s/files/1/1473/3902/files/1_03_abb48769-9486-44bd-a761-7cd39d7e1bda.jpg)
Please rehost on a dedicated image hosting site (Imgur, etc).  Shopify removes the images, so this may end up as a dead link very easily.

2023-08-31 07:58 UTC, dunk2k requested changes

2023-08-31 07:58 UTC, dunk2k commented on keyboards/dztech/dz60v2/info.json
> +}
1. layouts added
2. community_layouts added
3. `"w:1"` removed
```suggestion
    "community_layouts": [
        "60_abnt2",
        "60_ansi",
        "60_ansi_arrow",
        "60_ansi_arrow_split_bs_7u_spc",
        "60_ansi_split_bs_rshift",
        "60_ansi_tsangan",
        "60_hhkb",
        "60_iso",
        "60_iso_split_bs_rshift",
        "60_iso_tsangan",
        "60_tsangan_hhkb",
        "64_ansi",
        "64_iso"
    ],
    "layouts": {
        "LAYOUT": {
            "layout": [
                { "label": "k00", "matrix": [0, 0], "x": 0, "y": 0 },
                { "label": "k01", "matrix": [0, 1], "x": 1, "y": 0 },
                { "label": "k02", "matrix": [0, 2], "x": 2, "y": 0 },
                { "label": "k03", "matrix": [0, 3], "x": 3, "y": 0 },
                { "label": "k04", "matrix": [0, 4], "x": 4, "y": 0 },
                { "label": "k05", "matrix": [0, 5], "x": 5, "y": 0 },
                { "label": "k06", "matrix": [0, 6], "x": 6, "y": 0 },
                { "label": "k07", "matrix": [0, 7], "x": 7, "y": 0 },
                { "label": "k08", "matrix": [0, 8], "x": 8, "y": 0 },
                { "label": "k09", "matrix": [0, 9], "x": 9, "y": 0 },
                { "label": "k0a", "matrix": [0, 10], "x": 10, "y": 0 },
                { "label": "k0b", "matrix": [0, 11], "x": 11, "y": 0 },
                { "label": "k0c", "matrix": [0, 12], "x": 12, "y": 0 },
                { "label": "k0d", "matrix": [0, 13], "x": 13, "y": 0 },
                { "label": "k0e", "matrix": [0, 14], "x": 14, "y": 0 },
                { "label": "k10", "matrix": [1, 0], "w": 1.5, "x": 0, "y": 1 },
                { "label": "k12", "matrix": [1, 2], "x": 1.5, "y": 1 },
                { "label": "k13", "matrix": [1, 3], "x": 2.5, "y": 1 },
                { "label": "k14", "matrix": [1, 4], "x": 3.5, "y": 1 },
                { "label": "k15", "matrix": [1, 5], "x": 4.5, "y": 1 },
                { "label": "k16", "matrix": [1, 6], "x": 5.5, "y": 1 },
                { "label": "k17", "matrix": [1, 7], "x": 6.5, "y": 1 },
                { "label": "k18", "matrix": [1, 8], "x": 7.5, "y": 1 },
                { "label": "k19", "matrix": [1, 9], "x": 8.5, "y": 1 },
                { "label": "k1a", "matrix": [1, 10], "x": 9.5, "y": 1 },
                { "label": "k1b", "matrix": [1, 11], "x": 10.5, "y": 1 },
                { "label": "k1c", "matrix": [1, 12], "x": 11.5, "y": 1 },
                { "label": "k1d", "matrix": [1, 13], "x": 12.5, "y": 1 },
                { "label": "k1e", "matrix": [1, 14], "w": 1.5, "x": 13.5, "y": 1 },
                { "label": "k20", "matrix": [2, 0], "w": 1.75, "x": 0, "y": 2 },
                { "label": "k22", "matrix": [2, 2], "x": 1.75, "y": 2 },
                { "label": "k23", "matrix": [2, 3], "x": 2.75, "y": 2 },
                { "label": "k24", "matrix": [2, 4], "x": 3.75, "y": 2 },
                { "label": "k25", "matrix": [2, 5], "x": 4.75, "y": 2 },
                { "label": "k26", "matrix": [2, 6], "x": 5.75, "y": 2 },
                { "label": "k27", "matrix": [2, 7], "x": 6.75, "y": 2 },
                { "label": "k28", "matrix": [2, 8], "x": 7.75, "y": 2 },
                { "label": "k29", "matrix": [2, 9], "x": 8.75, "y": 2 },
                { "label": "k2a", "matrix": [2, 10], "x": 9.75, "y": 2 },
                { "label": "k2b", "matrix": [2, 11], "x": 10.75, "y": 2 },
                { "label": "k2c", "matrix": [2, 12], "x": 11.75, "y": 2 },
                { "label": "k2d", "matrix": [2, 13], "w": 2.25, "x": 12.75, "y": 2 },
                { "label": "k30", "matrix": [3, 0], "w": 1.25, "x": 0, "y": 3 },
                { "label": "k31", "matrix": [3, 1], "x": 1.25, "y": 3 },
                { "label": "k32", "matrix": [3, 2], "x": 2.25, "y": 3 },
                { "label": "k33", "matrix": [3, 3], "x": 3.25, "y": 3 },
                { "label": "k34", "matrix": [3, 4], "x": 4.25, "y": 3 },
                { "label": "k35", "matrix": [3, 5], "x": 5.25, "y": 3 },
                { "label": "k36", "matrix": [3, 6], "x": 6.25, "y": 3 },
                { "label": "k37", "matrix": [3, 7], "x": 7.25, "y": 3 },
                { "label": "k38", "matrix": [3, 8], "x": 8.25, "y": 3 },
                { "label": "k39", "matrix": [3, 9], "x": 9.25, "y": 3 },
                { "label": "k3a", "matrix": [3, 10], "x": 10.25, "y": 3 },
                { "label": "k3b", "matrix": [3, 11], "x": 11.25, "y": 3 },
                { "label": "k3d", "matrix": [3, 13], "w": 1.75, "x": 12.25, "y": 3 },
                { "label": "k3e", "matrix": [3, 14], "x": 14, "y": 3 },
                { "label": "k40", "matrix": [4, 0], "w": 1.25, "x": 0, "y": 4 },
                { "label": "k41", "matrix": [4, 1], "w": 1.25, "x": 1.25, "y": 4 },
                { "label": "k43", "matrix": [4, 3], "w": 1.25, "x": 2.5, "y": 4 },
                { "label": "k44", "matrix": [4, 4], "w": 2.25, "x": 3.75, "y": 4 },
                { "label": "k46", "matrix": [4, 6], "w": 1.25, "x": 6, "y": 4 },
                { "label": "k48", "matrix": [4, 8], "w": 2.75, "x": 7.25, "y": 4 },
                { "label": "k4a", "matrix": [4, 10], "x": 10, "y": 4 },
                { "label": "k4b", "matrix": [4, 11], "x": 11, "y": 4 },
                { "label": "k4c", "matrix": [4, 12], "x": 12, "y": 4 },
                { "label": "k4d", "matrix": [4, 13], "x": 13, "y": 4 },
                { "label": "k4e", "matrix": [4, 14], "x": 14, "y": 4 }
            ]
        },
        "LAYOUT_60_2_function": {
            "layout": [
                { "label": "k00", "matrix": [0, 0], "x": 0, "y": 0 },
                { "label": "k01", "matrix": [0, 1], "x": 1, "y": 0 },
                { "label": "k02", "matrix": [0, 2], "x": 2, "y": 0 },
                { "label": "k03", "matrix": [0, 3], "x": 3, "y": 0 },
                { "label": "k04", "matrix": [0, 4], "x": 4, "y": 0 },
                { "label": "k05", "matrix": [0, 5], "x": 5, "y": 0 },
                { "label": "k06", "matrix": [0, 6], "x": 6, "y": 0 },
                { "label": "k07", "matrix": [0, 7], "x": 7, "y": 0 },
                { "label": "k08", "matrix": [0, 8], "x": 8, "y": 0 },
                { "label": "k09", "matrix": [0, 9], "x": 9, "y": 0 },
                { "label": "k0a", "matrix": [0, 10], "x": 10, "y": 0 },
                { "label": "k0b", "matrix": [0, 11], "x": 11, "y": 0 },
                { "label": "k0c", "matrix": [0, 12], "x": 12, "y": 0 },
                { "label": "k0d", "matrix": [0, 13], "x": 13, "y": 0 },
                { "label": "k0e", "matrix": [0, 14], "x": 14, "y": 0 },
                { "label": "k10", "matrix": [1, 0], "w": 1.5, "x": 0, "y": 1 },
                { "label": "k12", "matrix": [1, 2], "x": 1.5, "y": 1 },
                { "label": "k13", "matrix": [1, 3], "x": 2.5, "y": 1 },
                { "label": "k14", "matrix": [1, 4], "x": 3.5, "y": 1 },
                { "label": "k15", "matrix": [1, 5], "x": 4.5, "y": 1 },
                { "label": "k16", "matrix": [1, 6], "x": 5.5, "y": 1 },
                { "label": "k17", "matrix": [1, 7], "x": 6.5, "y": 1 },
                { "label": "k18", "matrix": [1, 8], "x": 7.5, "y": 1 },
                { "label": "k19", "matrix": [1, 9], "x": 8.5, "y": 1 },
                { "label": "k1a", "matrix": [1, 10], "x": 9.5, "y": 1 },
                { "label": "k1b", "matrix": [1, 11], "x": 10.5, "y": 1 },
                { "label": "k1c", "matrix": [1, 12], "x": 11.5, "y": 1 },
                { "label": "k1d", "matrix": [1, 13], "x": 12.5, "y": 1 },
                { "label": "k1e", "matrix": [1, 14], "w": 1.5, "x": 13.5, "y": 1 },
                { "label": "k20", "matrix": [2, 0], "w": 1.75, "x": 0, "y": 2 },
                { "label": "k22", "matrix": [2, 2], "x": 1.75, "y": 2 },
                { "label": "k23", "matrix": [2, 3], "x": 2.75, "y": 2 },
                { "label": "k24", "matrix": [2, 4], "x": 3.75, "y": 2 },
                { "label": "k25", "matrix": [2, 5], [...]

2023-09-01 06:06 UTC, drashna commented on keyboards/dztech/dz60v2/keymaps/via/keymap.c
> +		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
```suggestion
    LAYOUT_all(
        QK_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_NO,   KC_BSPC,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,
        KC_LSFT, KC_NO,   KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_NO,
        KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,  KC_SPC,  KC_SPC,  KC_RALT, KC_RGUI, KC_NO,   MO(1),   KC_RCTL),
    LAYOUT_all(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_DEL,
        KC_TRNS, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_BOOT,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, BL_DEC,  BL_TOGG, BL_INC,  BL_STEP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
```

2023-09-05 06:48 UTC, dunk2k requested changes

2023-09-05 06:48 UTC, dunk2k commented on keyboards/dztech/dz60v2/keymaps/default/keymap.c
> +        _______, _______, _______,                   _______, _______, _______,          _______, _______, _______, _______, _______
fix build failing for this keymap due to 1 missing keycode
```suggestion
        QK_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP, MO(1),
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,  KC_SPC,  KC_SPC,           KC_RALT, KC_RCTL, KC_LEFT, KC_DOWN,   KC_RGHT
    ),

    LAYOUT_all(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______, _______,
        _______, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, _______, _______, _______, _______, QK_BOOT,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, BL_DEC,  BL_TOGG, BL_INC,  BL_STEP, _______, _______, _______, _______, _______, _______,
        _______, _______, _______,                   _______, _______, _______,          _______, _______, _______, _______, _______
```

2023-09-05 06:48 UTC, dunk2k commented on keyboards/dztech/dz60v2/keymaps/via/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
fix build failing for this keymap
```suggestion
        QK_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_DEL,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP, MO(1),
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,  KC_SPC,  KC_SPC,           KC_RALT, KC_RCTL, KC_LEFT, KC_DOWN,   KC_RGHT
    ),

    LAYOUT_all(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______, _______,
        _______, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, _______, _______, _______, _______, QK_BOOT,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,
        _______, _______, _______, _______, BL_DEC,  BL_TOGG, BL_INC,  BL_STEP, _______, _______, _______, _______, _______, _______,
        _______, _______, _______,                   _______, _______, _______,          _______, _______, _______, _______, _______
    }
```

2023-09-05 10:19 UTC, fauxpark requested changes

2023-09-05 10:19 UTC, fauxpark commented on keyboards/dztech/dz60v2/readme.md
> +    make dz60:default
```suggestion
```

2023-09-05 10:19 UTC, fauxpark commented on keyboards/dztech/dz60v2/info.json
> +        "on_state": 1
```suggestion
        "caps_lock": "E6"
```

2023-09-05 15:15 UTC, dunk2k requested changes

2023-09-05 15:15 UTC, dunk2k commented on keyboards/dztech/dz60v2/keymaps/default/keymap.c
> +        _______, _______, _______, _______, BL_DEC,  BL_TOGG, BL_INC,  BL_STEP, _______, _______, _______, _______, _______, _______, _______,
```suggestion
        _______, _______, _______, _______, BL_DOWN,  BL_TOGG, BL_UP,  BL_STEP, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-05 15:15 UTC, dunk2k commented on keyboards/dztech/dz60v2/keymaps/via/keymap.c
> +        _______, _______, _______, _______, BL_DEC,  BL_TOGG, BL_INC,  BL_STEP, _______, _______, _______, _______, _______, _______,
```suggestion
        _______, _______, _______, _______, BL_DOWN,  BL_TOGG, BL_UP,  BL_STEP, _______, _______, _______, _______, _______, _______,
```

2023-09-05 15:21 UTC, dunk2k requested changes

2023-09-05 15:21 UTC, dunk2k commented on keyboards/dztech/dz60v2/info.json
> +    "keyboard_name": "DZ60",
```suggestion
    "keyboard_name": "DZ60v2",
```

2023-09-05 15:21 UTC, dunk2k commented on keyboards/dztech/dz60v2/info.json
> +        "backlight": false,
```suggestion
```

2023-09-19 06:59 UTC, drashna approved these changes

2023-09-19 07:00 UTC, drashna commented
QMK CI failure is due to `unxmaal`, and no other keymaps appear to be failing.

2023-09-19 08:21 UTC, fauxpark approved these changes

2023-09-21 06:01 UTC, merged