add qk80 files
qmk/qmk_firmware pull request #21882
Opened 2023-09-01 10:50 UTC by owlab-git

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-01 11:04 UTC, dunk2k requested changes

2023-09-01 11:04 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/info.json
> +        "LAYOUT_sol": {
matches community layout
```suggestion
    },
    "community_layouts": ["tkl_f13_iso_tsangan"],
    "layouts": {
        "LAYOUT_tkl_f13_iso_tsangan": {
```

2023-09-01 11:04 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/keymaps/default/keymap.c
> +  [1] = LAYOUT_sol(
```suggestion
  [0] = LAYOUT_tkl_f13_iso_tsangan(
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,  KC_PSCR, KC_SCRL, KC_PAUS, 
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSLS, KC_BSPC, KC_INS,  KC_HOME, KC_PGUP,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_DEL,  KC_END,  KC_PGDN,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,  
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,                   KC_UP,
    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                                               KC_RALT, KC_RGUI, MO(1),   KC_LEFT, KC_DOWN, KC_RIGHT
  ),
  [1] = LAYOUT_tkl_f13_iso_tsangan(
```

2023-09-01 11:04 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/keymaps/via/keymap.c
> +  [1] = LAYOUT_sol(
```suggestion
  [0] = LAYOUT_tkl_f13_iso_tsangan(
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F13,  KC_PSCR, KC_SCRL, KC_PAUS, 
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSLS, KC_BSPC, KC_INS,  KC_HOME, KC_PGUP,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_DEL,  KC_END,  KC_PGDN,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,  
    KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,                   KC_UP,
    KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                                               KC_RALT, KC_RGUI, MO(1),   KC_LEFT, KC_DOWN, KC_RIGHT
  ),
  [1] = LAYOUT_tkl_f13_iso_tsangan(
```

2023-09-03 01:46 UTC, zvecr requested changes

2023-09-03 01:46 UTC, zvecr commented on keyboards/qwertykeys/qk80/ansi/chconf.h
This file should be removed.

2023-09-03 01:46 UTC, zvecr commented on keyboards/qwertykeys/qk80/ansi/halconf.h
> +
Nothing is configured to use PWM
```suggestion

```

2023-09-03 01:46 UTC, zvecr commented on keyboards/qwertykeys/qk80/ansi_625u/chconf.h
This file should be removed.

2023-09-03 01:46 UTC, zvecr commented on keyboards/qwertykeys/qk80/ansi/mcuconf.h
> +#define STM32_PWM_USE_TIM1 TRUE
```suggestion
```

2023-09-03 01:46 UTC, zvecr commented on keyboards/qwertykeys/qk80/ansi_625u/halconf.h
> +
```suggestion
```

2023-09-03 01:46 UTC, zvecr commented on keyboards/qwertykeys/qk80/ansi_625u/mcuconf.h
> +#define STM32_PWM_USE_TIM1 TRUE
```suggestion
```

2023-09-04 18:29 UTC, dunk2k requested changes

2023-09-04 18:29 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/info.json
as this is the solder version, I presume there is more than one layout for this board?

2023-09-05 07:45 UTC, dunk2k requested changes

2023-09-05 07:45 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/info.json
> +                {"matrix": [1, 13], "x":14, "y":1.25, "w":2},
```suggestion
                {"matrix": [1, 13], "x":13, "y":1.25, "w":2},
```

2023-09-05 07:45 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/info.json
> +                {"matrix": [3, 12], "x":13.75, "y":2.25, "w":2.25},
```suggestion
                {"matrix": [3, 12], "x":12.75, "y":3.25, "w":2.25},
```

2023-09-09 07:41 UTC, owlab-git commented
Bump

2023-09-23 04:41 UTC, drashna approved these changes

2023-09-30 15:01 UTC, dunk2k requested changes

2023-09-30 15:01 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/readme.md
> +![qk80](https://i.imgur.com/qSXHoWyh.jpg)
Could this image be changed to match keyboard - current iimage is a tsangan/7u spacebar layout.

2023-09-30 15:01 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/readme.md
> +![qk80](https://i.imgur.com/qSXHoWyh.jpg)
Could this be an image of the PCB, in question, instead?

2023-10-11 08:54 UTC, owlab-git commented
Please Check for merge.

2023-10-11 09:14 UTC, dunk2k requested changes

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/info.json
> +}
Add EoF
```suggestion
}

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/keymaps/default/keymap.c
> +};
Add EoF
```suggestion
};

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/keymaps/via/keymap.c
> +};
Add EoF
```suggestion
};

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/keymaps/via/rules.mk
> +LTO_ENABLE = yes
Add EoF
```suggestion
LTO_ENABLE = yes

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/mcuconf.h
> +#define STM32_I2C_USE_I2C1                  TRUE
Add EoF
```suggestion
#define STM32_I2C_USE_I2C1                  TRUE

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/rules.mk
> +# This file intentionally left blank
Add EoF
```suggestion
# This file intentionally left blank

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/ansi_625u.c
> +#endif
Add EoF
```suggestion
#endif

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/config.h
> +#    define RGB_MATRIX_LED_COUNT          88
Add EoF
```suggestion
#    define RGB_MATRIX_LED_COUNT          88 

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/halconf.h
> +#include_next <halconf.h>
Add EoF
```suggestion
#include_next <halconf.h>

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/info.json
> +}
Add EoF
```suggestion
}

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/keymaps/default/keymap.c
> +};
Add EoF
```suggestion
};

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/keymaps/via/keymap.c
> +};
Add EoF
```suggestion
};

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/keymaps/via/rules.mk
> +LTO_ENABLE = yes
Add EoF
```suggestion
LTO_ENABLE = yes

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/mcuconf.h
> +#define STM32_I2C_USE_I2C1                  TRUE
Add EoF
```suggestion
#define STM32_I2C_USE_I2C1                  TRUE

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi_625u/rules.mk
> +# This file intentionally left blank
Add EoF
```suggestion
# This file intentionally left blank

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/info.json
> +}
Add EoF
```suggestion
}

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/config.h
> +#    define RGBLIGHT_EFFECT_BREATHE_MAX    100
Add EoF
```suggestion
#    define RGBLIGHT_EFFECT_BREATHE_MAX    100

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/info.json
> +}
Add EoF
```suggestion
}

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/keymaps/default/keymap.c
> +};
Add EoF
```suggestion
};

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/keymaps/via/keymap.c
> +};
Add EoF
```suggestion
};

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/keymaps/via/rules.mk
> +LTO_ENABLE = yes
Add EoF
```suggestion
LTO_ENABLE = yes

```

2023-10-11 09:14 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/rules.mk
> +# This file intentionally left blank
Add Eof
```suggestion
# This file intentionally left blank

```

2023-10-19 05:16 UTC, owlab-git commented
Bump

2023-10-23 12:06 UTC, owlab-git commented
Please check, thanks.

2023-11-07 18:16 UTC, mkylama commented
Seems like at least the solder version (don't have other versions to test with) has the same bootloader "issue" as QK65v2 [discussed in qmk discord](https://discord.com/channels/440868230475677696/867530222407778344/1147865498567053313)

It is recognized as `USB device connected (WinUSB): Saab AB Qwertykeys Firmware Update (1688:2220:0200)` so compiling it with bootloader set to `stm32duino` wont be compatible with the keyboard.

2023-11-08 05:45 UTC, drashna requested changes

2023-11-08 05:45 UTC, drashna commented on keyboards/qwertykeys/qk80/ansi/config.h
Could you run a format pass on this file?

2023-11-08 05:45 UTC, drashna commented on keyboards/qwertykeys/qk80/ansi_625u/config.h
same here.

2023-11-08 05:45 UTC, drashna commented on keyboards/qwertykeys/qk80/solder/config.h
Here too

2023-11-08 05:45 UTC, drashna commented on keyboards/qwertykeys/qk80/ansi/ansi.c
> +bool process_record_kb(uint16_t keycode, keyrecord_t *record) {
Since you have two boards that are using this code, it may make more sense to move this to qk80.c in the qk80 folder to reduce redundant code.

2023-11-18 10:13 UTC, dunk2k requested changes

2023-11-18 10:13 UTC, dunk2k commented on keyboards/qwertykeys/qk80/solder/info.json
> +        }
add WKL layouts
```suggestion
        },
        "LAYOUT_tkl_f13_ansi_wkl": {
            "layout": [
                {"matrix": [0, 0], "x":0, "y":0},
                {"matrix": [0, 1], "x":1.25, "y":0},
                {"matrix": [0, 2], "x":2.25, "y":0},
                {"matrix": [0, 3], "x":3.25, "y":0},
                {"matrix": [0, 4], "x":4.25, "y":0},
                {"matrix": [0, 5], "x":5.5, "y":0},
                {"matrix": [0, 6], "x":6.5, "y":0},
                {"matrix": [0, 7], "x":7.5, "y":0},
                {"matrix": [0, 8], "x":8.5, "y":0},
                {"matrix": [0, 9], "x":9.75, "y":0},
                {"matrix": [0, 10], "x":10.75, "y":0},
                {"matrix": [0, 11], "x":11.75, "y":0},
                {"matrix": [0, 12], "x":12.75, "y":0},
                {"matrix": [0, 13], "x":14, "y":0},
                {"matrix": [0, 14], "x":15.25, "y":0},
                {"matrix": [1, 14], "x":16.25, "y":0},
                {"matrix": [2, 14], "x":17.25, "y":0},
                {"matrix": [1, 0], "x":0, "y":1.25},
                {"matrix": [1, 1], "x":1, "y":1.25},
                {"matrix": [1, 2], "x":2, "y":1.25},
                {"matrix": [1, 3], "x":3, "y":1.25},
                {"matrix": [1, 4], "x":4, "y":1.25},
                {"matrix": [1, 5], "x":5, "y":1.25},
                {"matrix": [1, 6], "x":6, "y":1.25},
                {"matrix": [1, 7], "x":7, "y":1.25},
                {"matrix": [1, 8], "x":8, "y":1.25},
                {"matrix": [1, 9], "x":9, "y":1.25},
                {"matrix": [1, 10], "x":10, "y":1.25},
                {"matrix": [1, 11], "x":11, "y":1.25},
                {"matrix": [1, 12], "x":12, "y":1.25},
                {"matrix": [1, 13], "x":14, "y":1.25, "w":2},
                {"matrix": [3, 13], "x":15.25, "y":1.25},
                {"matrix": [3, 14], "x":16.25, "y":1.25},
                {"matrix": [4, 12], "x":17.25, "y":1.25},
                {"matrix": [2, 0], "x":0, "y":2.25, "w":1.5},
                {"matrix": [2, 1], "x":1.5, "y":2.25},
                {"matrix": [2, 2], "x":2.5, "y":2.25},
                {"matrix": [2, 3], "x":3.5, "y":2.25},
                {"matrix": [2, 4], "x":4.5, "y":2.25},
                {"matrix": [2, 5], "x":5.5, "y":2.25},
                {"matrix": [2, 6], "x":6.5, "y":2.25},
                {"matrix": [2, 7], "x":7.5, "y":2.25},
                {"matrix": [2, 8], "x":8.5, "y":2.25},
                {"matrix": [2, 9], "x":9.5, "y":2.25},
                {"matrix": [2, 10], "x":10.5, "y":2.25},
                {"matrix": [2, 11], "x":11.5, "y":2.25},
                {"matrix": [2, 12], "x":12.5, "y":2.25},
                {"matrix": [5, 6], "x":13.5, "y":2.25, "w":1.5},
                {"matrix": [4, 13], "x":15.25, "y":2.25},
                {"matrix": [4, 14], "x":16.25, "y":2.25},
                {"matrix": [5, 10], "x":17.25, "y":2.25},
                {"matrix": [3, 0], "x":0, "y":3.25, "w":1.75},
                {"matrix": [3, 1], "x":1.75, "y":3.25},
                {"matrix": [3, 2], "x":2.75, "y":3.25},
                {"matrix": [3, 3], "x":3.75, "y":3.25},
                {"matrix": [3, 4], "x":4.75, "y":3.25},
                {"matrix": [3, 5], "x":5.75, "y":3.25},
                {"matrix": [3, 6], "x":6.75, "y":3.25},
                {"matrix": [3, 7], "x":7.75, "y":3.25},
                {"matrix": [3, 8], "x":8.75, "y":3.25},
                {"matrix": [3, 9], "x":9.75, "y":3.25},
                {"matrix": [3, 10], "x":10.75, "y":3.25},
                {"matrix": [3, 11], "x":11.75, "y":3.25},
                {"matrix": [3, 12], "x":12.75, "y":3.25, "w":2.25},
                {"matrix": [4, 0], "x":0, "y":4.25, "w":2.25},
                {"matrix": [4, 1], "x":2.25, "y":4.25},
                {"matrix": [4, 2], "x":3.25, "y":4.25},
                {"matrix": [4, 3], "x":4.25, "y":4.25},
                {"matrix": [4, 4], "x":5.25, "y":4.25},
                {"matrix": [4, 5], "x":6.25, "y":4.25},
                {"matrix": [4, 6], "x":7.25, "y":4.25},
                {"matrix": [4, 7], "x":8.25, "y":4.25},
                {"matrix": [4, 8], "x":9.25, "y":4.25},
                {"matrix": [4, 9], "x":10.25, "y":4.25},
                {"matrix": [4, 10], "x":11.25, "y":4.25},
                {"matrix": [4, 11], "x":12.25, "y":4.25, "w":2.75},
                {"matrix": [5, 11], "x":16.25, "y":4.25},
                {"matrix": [5, 0], "x":0, "y":5.25, "w":1.5},
                {"matrix": [5, 2], "x":2.5, "y":5.25, "w":1.5},
                {"matrix": [5, 4], "x":4, "y":5.25, "w":7},
                {"matrix": [5, 7], "x":11, "y":5.25, "w":1.5},
                {"matrix": [5, 9], "x":13.5, "y":5.25, "w":1.5},
                {"matrix": [5, 12], "x":15.25, "y":5.25},
                {"matrix": [5, 13], "x":16.25, "y":5.25},
                {"matrix": [5, 14], "x":17.25, "y":5.25}
            ]
        },
        "LAYOUT_tkl_f13_iso_wkl": {
            "layout": [
                {"matrix": [0, 0], "x":0, "y":0},
                {"matrix": [0, 1], "x":1.25, "y":0},
                {"matrix": [0, 2], "x":2.25, "y":0},
                {"matrix": [0, 3], "x":3.25, "y":0},
                {"matrix": [0, 4], "x":4.25, "y":0},
                {"matrix": [0, 5], "x":5.5, "y":0},
                {"matrix": [0, 6], "x":6.5, "y":0},
                {"matrix": [0, 7], "x":7.5, "y":0},
                {"matrix": [0, 8], "x":8.5, "y":0},
                {"matrix": [0, 9], "x":9.75, "y":0},
                {"matrix": [0, 10], "x":10.75, "y":0},
                {"matrix": [0, 11], "x":11.75, "y":0},
                {"matrix": [0, 12], "x":12.75, "y":0},
                {"matrix": [0, 13], "x":14, "y":0},
                {"matrix": [0, 14], "x":15.25, "y":0},
                {"matrix": [1, 14], "x":16.25, "y":0},
                {"matrix": [2, 14], "x":17.25, "y":0},
                {"matrix": [1, 0], "x":0, "y":1.25},
                {"matrix": [1, 1], "x":1, "y":1.25},
                {"matrix": [1, 2], "x":2, "y":1.25},
                {"matrix": [1, 3], "x":3, "y":1.25},
                {"matrix": [1, 4], "x":4, "y":1.25},
                {"matrix": [1, 5], "x":5, "y":1.25},
                {"matrix": [1, 6], "x":6, "y":1.25},
                {"matrix": [1, 7], "x":7, "y":1.25},
                {"matrix": [1, 8], "x":8, "y":1.25},
                {"matrix": [1, 9], "x":9, "y":1.25},
                {"matrix": [1, 10], "x":10, "y":1.25},
                {"matrix": [1, 11], "x":11, "y":1.25},
                {"matrix": [1, 12], "x":12, "y":1.25},
                {"matrix": [1, 13], "x":13, "y":1.25, "w":2},
                {"matrix": [3, 13], "x":15.25, "y":1.25},
                {"matrix": [3, 14], "x":16.25, "y":1.25},
                {"matrix": [4, 12], "x":17.25, "y":1.25},
                {"matrix": [2, 0], "x":0, "y":2.25, "w":1.5},
                {"matrix": [2, 1], "x":1.5, "y":2.25},
                {"matrix": [2, 2], "x":2.5, "y":2.25},
                {"matrix": [2, 3], "x":3.5, "y":2.25},
                {"matrix": [2, 4], "x":4.5, "y":2.25},
                {"matrix": [2, 5], "x":5.5, "y":2.25},
                {"matrix": [2, 6], "x":6.5, "y":2.25},
                {"matrix": [2, 7], "x":7.5, "y":2.25},
                {"matrix": [2, 8], "x":8.5, "y":2.25},
                {"matrix": [2, 9], "x":9.5, "y":2.25},
                {"matrix": [2, 10], "x":10.5, "y":2.25},
                {"matrix": [2, 11], "x":11.5, "y":2.25},
                {"matrix": [2, 12], "x":12.5, "y":2.25},
                {"matrix": [4, 13], "x":15.25, "y":2.25},
                {"matrix": [4, 14], "x":16.25, "y":2.25},
                {"matrix": [5, 10], "x":17.25, "y":2.25},
                {"matrix": [3, 0], "x":0, "y":3.25, "w":1.75},
                {"matrix": [3, 1], "x":1.75, "y":3.25},
                {"matrix": [3, 2], "x":2.75, "y":3.25},
                {"matrix": [3, 3], "x":3.75, "y":3.25},
                {"matrix": [3, 4], "x":4.75, "y":3. [...]

2023-11-18 10:13 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/info.json
> +        }
add WKL layout
```suggestion
        },
        "LAYOUT_tkl_f13_ansi_wkl": {
            "layout": [
                {"matrix": [0, 0], "x":0, "y":0},
                {"matrix": [0, 1], "x":1.25, "y":0},
                {"matrix": [0, 2], "x":2.25, "y":0},
                {"matrix": [0, 3], "x":3.25, "y":0},
                {"matrix": [0, 4], "x":4.25, "y":0},
                {"matrix": [0, 5], "x":5.5, "y":0},
                {"matrix": [0, 6], "x":6.5, "y":0},
                {"matrix": [0, 7], "x":7.5, "y":0},
                {"matrix": [0, 8], "x":8.5, "y":0},
                {"matrix": [0, 9], "x":9.75, "y":0},
                {"matrix": [0, 10], "x":10.75, "y":0},
                {"matrix": [0, 11], "x":11.75, "y":0},
                {"matrix": [0, 12], "x":12.75, "y":0},
                {"matrix": [0, 13], "x":14, "y":0},
                {"matrix": [0, 14], "x":15.25, "y":0},
                {"matrix": [1, 14], "x":16.25, "y":0},
                {"matrix": [2, 14], "x":17.25, "y":0},
                {"matrix": [1, 0], "x":0, "y":1.25},
                {"matrix": [1, 1], "x":1, "y":1.25},
                {"matrix": [1, 2], "x":2, "y":1.25},
                {"matrix": [1, 3], "x":3, "y":1.25},
                {"matrix": [1, 4], "x":4, "y":1.25},
                {"matrix": [1, 5], "x":5, "y":1.25},
                {"matrix": [1, 6], "x":6, "y":1.25},
                {"matrix": [1, 7], "x":7, "y":1.25},
                {"matrix": [1, 8], "x":8, "y":1.25},
                {"matrix": [1, 9], "x":9, "y":1.25},
                {"matrix": [1, 10], "x":10, "y":1.25},
                {"matrix": [1, 11], "x":11, "y":1.25},
                {"matrix": [1, 12], "x":12, "y":1.25},
                {"matrix": [1, 13], "x":13, "y":1.25, "w":2},
                {"matrix": [3, 13], "x":15.25, "y":1.25},
                {"matrix": [3, 14], "x":16.25, "y":1.25},
                {"matrix": [4, 12], "x":17.25, "y":1.25},
                {"matrix": [2, 0], "x":0, "y":2.25, "w":1.5},
                {"matrix": [2, 1], "x":1.5, "y":2.25},
                {"matrix": [2, 2], "x":2.5, "y":2.25},
                {"matrix": [2, 3], "x":3.5, "y":2.25},
                {"matrix": [2, 4], "x":4.5, "y":2.25},
                {"matrix": [2, 5], "x":5.5, "y":2.25},
                {"matrix": [2, 6], "x":6.5, "y":2.25},
                {"matrix": [2, 7], "x":7.5, "y":2.25},
                {"matrix": [2, 8], "x":8.5, "y":2.25},
                {"matrix": [2, 9], "x":9.5, "y":2.25},
                {"matrix": [2, 10], "x":10.5, "y":2.25},
                {"matrix": [2, 11], "x":11.5, "y":2.25},
                {"matrix": [2, 12], "x":12.5, "y":2.25},
                {"matrix": [2, 13], "x":13.5, "y":2.25, "w":1.5},
                {"matrix": [4, 13], "x":15.25, "y":2.25},
                {"matrix": [4, 14], "x":16.25, "y":2.25},
                {"matrix": [5, 10], "x":17.25, "y":2.25},
                {"matrix": [3, 0], "x":0, "y":3.25, "w":1.75},
                {"matrix": [3, 1], "x":1.75, "y":3.25},
                {"matrix": [3, 2], "x":2.75, "y":3.25},
                {"matrix": [3, 3], "x":3.75, "y":3.25},
                {"matrix": [3, 4], "x":4.75, "y":3.25},
                {"matrix": [3, 5], "x":5.75, "y":3.25},
                {"matrix": [3, 6], "x":6.75, "y":3.25},
                {"matrix": [3, 7], "x":7.75, "y":3.25},
                {"matrix": [3, 8], "x":8.75, "y":3.25},
                {"matrix": [3, 9], "x":9.75, "y":3.25},
                {"matrix": [3, 10], "x":10.75, "y":3.25},
                {"matrix": [3, 11], "x":11.75, "y":3.25},
                {"matrix": [3, 12], "x":12.75, "y":3.25, "w":2.25},
                {"matrix": [4, 0], "x":0, "y":4.25, "w":2.25},
                {"matrix": [4, 1], "x":2.25, "y":4.25},
                {"matrix": [4, 2], "x":3.25, "y":4.25},
                {"matrix": [4, 3], "x":4.25, "y":4.25},
                {"matrix": [4, 4], "x":5.25, "y":4.25},
                {"matrix": [4, 5], "x":6.25, "y":4.25},
                {"matrix": [4, 6], "x":7.25, "y":4.25},
                {"matrix": [4, 7], "x":8.25, "y":4.25},
                {"matrix": [4, 8], "x":9.25, "y":4.25},
                {"matrix": [4, 9], "x":10.25, "y":4.25},
                {"matrix": [4, 10], "x":11.25, "y":4.25},
                {"matrix": [4, 11], "x":12.25, "y":4.25, "w":2.75},
                {"matrix": [5, 11], "x":16.25, "y":4.25},
                {"matrix": [5, 0], "x":0, "y":5.25, "w":1.5},
                {"matrix": [5, 2], "x":2.5, "y":5.25, "w":1.5},
                {"matrix": [5, 4], "x":4, "y":5.25, "w":7},
                {"matrix": [5, 7], "x":11, "y":5.25, "w":1.5},
                {"matrix": [5, 9], "x":13.5, "y":5.25, "w":1.5},
                {"matrix": [5, 12], "x":15.25, "y":5.25},
                {"matrix": [5, 13], "x":16.25, "y":5.25},
                {"matrix": [5, 14], "x":17.25, "y":5.25}
            ]
        }
```

2023-11-18 10:15 UTC, dunk2k commented on keyboards/qwertykeys/qk80/ansi/readme.md
> +![qk80](https://i.imgur.com/qSXHoWyh.jpg)
this image is of a tsangan bottom row layout rather than standard TKL bottom row layout, could this be amended if possible?

2024-03-08 01:47 UTC, closed without merging