ADD keyboard vortex/Mo110a_ansi
qmk/qmk_firmware pull request #21931
Opened 2023-09-06 08:57 UTC by gskygithub

## Description

Add m0110a_ansi keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-06 09:40 UTC, dunk2k commented
@gskygithub 
could I recommend that this _Pull Request_ (PR) and the 3 other directly related PRs that use the same PCB, be merged into 1 PR; each board would be a layout entry in `layouts` of `info.json`:
| board | layout name in `info.json` |
| :---: | :---: |
| Mo110a_ansi | LAYOUT_ansi |
| Mo110a_iso | LAYOUT_iso |
| Mo110a_1800_ansi | LAYOUT_1800_ansi |
| Mo110a_1800_iso | LAYOUT_1800_iso |

2023-09-06 09:45 UTC, dunk2k requested changes

2023-09-06 09:45 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/info.json
> +        "nkro": true
```suggestion
    "features": {
        "audio": false,
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true
```

2023-09-06 09:45 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/rules.mk
> +EEPROM_DRIVER = wear_leveling
```suggestion
```

2023-09-06 09:45 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/info.json
> +    },
```suggestion
    },
    "eeprom": {
        "driver": "wear_leveling"
    },
```

2023-09-06 09:45 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/config.h
> +#define LOCKING_RESYNC_ENABLE
please move these settings to a `config.h` file in desired keymap(s) directory

2023-09-07 01:40 UTC, gskygithub commented
> @gskygithub could I recommend that this _Pull Request_ (PR) and the 3 other directly related PRs that use the same PCB, be merged into 1 PR; each board would be a layout entry in `layouts` of `info.json`:
> 
> board	layout name in `info.json`
> Mo110a_ansi	LAYOUT_ansi
> Mo110a_iso	LAYOUT_iso
> Mo110a_1800_ansi	LAYOUT_1800_ansi
> Mo110a_1800_iso	LAYOUT_1800_iso
> edit: I would be willing to assist you with implementation of this recommendation.

@dunk2k Thanks, Can you please guide me how to implement this...

2023-09-07 08:50 UTC, dunk2k requested changes
1. adds layouts from the 3 related PR's
2. adjusts keymaps and naming

With these suggestions accepted, you would be able to close the 3 related PRs and rename this PR to `Add keyboard vortex/Mo110a`.

Entirely optional if you wish to add a keymap for each layout (that is not `LAYOUT_all`).

2023-09-07 08:50 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/info.json
> +                { "label": "Numdel", "matrix": [13, 3], "x": 17.5, "y": 5 }
1. added layouts from PRs #21932, #21933, and #21934
2. added layout `LAYOUT_all` to conform to PR guidelines
3. for ISO layouts, moved ISO Enter key position in matrix/layout sequence to conform to community layouts
```suggestion
        "LAYOUT_all": {
            "layout": [
                { "label": "ESC", "matrix": [1, 6], "x": 0, "y": 0 },
                { "label": "1", "matrix": [1, 7], "x": 1, "y": 0 },
                { "label": "2", "matrix": [2, 7], "x": 2, "y": 0 },
                { "label": "3", "matrix": [3, 7], "x": 3, "y": 0 },
                { "label": "4", "matrix": [4, 7], "x": 4, "y": 0 },
                { "label": "5", "matrix": [4, 6], "x": 5, "y": 0 },
                { "label": "6", "matrix": [5, 6], "x": 6, "y": 0 },
                { "label": "7", "matrix": [5, 7], "x": 7, "y": 0 },
                { "label": "8", "matrix": [6, 7], "x": 8, "y": 0 },
                { "label": "9", "matrix": [7, 7], "x": 9, "y": 0 },
                { "label": "0", "matrix": [8, 7], "x": 10, "y": 0 },
                { "label": "-", "matrix": [8, 6], "x": 11, "y": 0 },
                { "label": "=", "matrix": [6, 6], "x": 12, "y": 0 },
                { "label": "\\", "matrix": [10, 2], "x": 13, "y": 0 },
                { "label": "delete", "matrix": [6, 5], "x": 14, "y": 0 },
                { "label": "Numlock", "matrix": [11, 4], "x": 15.5, "y": 0 },
                { "label": "Num/", "matrix": [12, 4], "x": 16.5, "y": 0 },
                { "label": "Num*", "matrix": [13, 4], "x": 17.5, "y": 0 },
                { "label": "Num-", "matrix": [13, 5], "x": 18.5, "y": 0 },

                { "label": "Tab", "matrix": [1, 1], "w": 1.5, "x": 0, "y": 1 },
                { "label": "Q", "matrix": [1, 0], "x": 1.5, "y": 1 },
                { "label": "W", "matrix": [2, 0], "x": 2.5, "y": 1 },
                { "label": "E", "matrix": [3, 0], "x": 3.5, "y": 1 },
                { "label": "R", "matrix": [4, 0], "x": 4.5, "y": 1 },
                { "label": "T", "matrix": [4, 1], "x": 5.5, "y": 1 },
                { "label": "Y", "matrix": [5, 1], "x": 6.5, "y": 1 },
                { "label": "U", "matrix": [5, 0], "x": 7.5, "y": 1 },
                { "label": "I", "matrix": [6, 0], "x": 8.5, "y": 1 },
                { "label": "O", "matrix": [7, 0], "x": 9.5, "y": 1 },
                { "label": "P", "matrix": [8, 0], "x": 10.5, "y": 1 },
                { "label": "[", "matrix": [8, 1], "x": 11.5, "y": 1 },
                { "label": "]", "matrix": [6, 1], "x": 12.5, "y": 1 },
                { "label": "\\", "matrix": [10, 5], "w": 1.5, "x": 13.5, "y": 1 },
                { "label": "Num7", "matrix": [11, 0], "x": 15.5, "y": 1 },
                { "label": "Num8", "matrix": [12, 0], "x": 16.5, "y": 1 },
                { "label": "Num9", "matrix": [13, 0], "x": 17.5, "y": 1 },
                { "label": "Num+", "matrix": [11, 3], "h":2, "x": 18.5, "y": 1 },

                { "label": "Caps Lock", "matrix": [2, 1], "w": 1.75, "x": 0, "y": 2 },
                { "label": "A", "matrix": [1, 2], "x": 1.75, "y": 2 },
                { "label": "S", "matrix": [2, 2], "x": 2.75, "y": 2 },
                { "label": "D", "matrix": [3, 2], "x": 3.75, "y": 2 },
                { "label": "F", "matrix": [4, 2], "x": 4.75, "y": 2 },
                { "label": "G", "matrix": [4, 3], "x": 5.75, "y": 2 },
                { "label": "H", "matrix": [5, 3], "x": 6.75, "y": 2 },
                { "label": "J", "matrix": [5, 2], "x": 7.75, "y": 2 },
                { "label": "K", "matrix": [6, 2], "x": 8.75, "y": 2 },
                { "label": "L", "matrix": [7, 2], "x": 9.75, "y": 2 },
                { "label": ";", "matrix": [8, 2], "x": 10.75, "y": 2 },
                { "label": "'", "matrix": [8, 3], "x": 11.75, "y": 2 },
                { "label": "Enter", "matrix": [10, 4], "w": 2.25, "x": 12.75, "y": 2 },
                { "label": "Num4", "matrix": [11, 1], "x": 15.5, "y": 2 },
                { "label": "Num5", "matrix": [12, 1], "x": 16.5, "y": 2 },
                { "label": "Num6", "matrix": [13, 1], "x": 17.5, "y": 2 },

                { "label": "Shift", "matrix": [0, 0], "w": 1.25, "x": 0, "y": 3 },
                { "label": "\\", "matrix": [2, 3], "x": 1.25, "y": 3 },
                { "label": "Z", "matrix": [1, 4], "x": 2.25, "y": 3 },
                { "label": "X", "matrix": [2, 4], "x": 3.25, "y": 3 },
                { "label": "C", "matrix": [3, 4], "x": 4.25, "y": 3 },
                { "label": "V", "matrix": [4, 4], "x": 5.25, "y": 3 },
                { "label": "B", "matrix": [4, 5], "x": 6.25, "y": 3 },
                { "label": "N", "matrix": [5, 5], "x": 7.25, "y": 3 },
                { "label": "M", "matrix": [5, 4], "x": 8.25, "y": 3 },
                { "label": ",", "matrix": [6, 4], "x": 9.25, "y": 3 },
                { "label": ".", "matrix": [7, 4], "x": 10.25, "y": 3 },
                { "label": "/", "matrix": [8, 5], "x": 11.25, "y": 3 },
                { "label": "Shift", "matrix": [9, 1], "w": 1.75, "x": 12.25, "y": 3 },
                { "label": "Up", "matrix": [3, 5], "x": 14.25, "y": 3.25 },
                { "label": "Num1", "matrix": [11, 2], "x": 15.5, "y": 3 },
                { "label": "Num2", "matrix": [12, 2], "x": 16.5, "y": 3 },
                { "label": "Num3", "matrix": [13, 2], "x": 17.5, "y": 3 },
                { "label": "Numenter", "matrix": [13, 6], "h":2, "x": 18.5, "y": 3 },

                { "label": "Ctrl", "matrix": [0, 6], "w": 1.25, "x": 0, "y": 4 },
                { "label": "Win", "matrix": [9, 0], "w": 1.25, "x": 1.25, "y": 4 },
                { "label": "Alt", "matrix": [9, 3], "w": 1.25, "x": 2.5, "y": 4 },
                { "label": "Space", "matrix": [9, 4], "w": 6.25, "x": 3.75, "y": 4 },
                { "label": "RAlt", "matrix": [9, 5], "x": 10, "y": 4 },
                { "label": "FN", "matrix": [9, 2], "x": 11, "y": 4 },
                { "label": "RCtrl", "matrix": [0, 4], "x": 12, "y": 4 },
                { "label": "Left", "matrix": [0, 3], "x": 13.25, "y": 4.25 },
                { "label": "Down", "matrix": [7, 3], "x": 14.25, "y": 4.25 },
                { "label": "Right", "matrix": [0, 5], "x": 15.25, "y": 4.25 },
                { "label": "Num0", "matrix": [12, 3], "x": 16.5, "y": 4 },
                { "label": "Numdel", "matrix": [13, 3], "x": 17.5, "y": 4 }
            ]
        },
        "LAYOUT_ansi": {
            "layout": [
                { "label": "ESC", "matrix": [1, 6], "x": 0, "y": 0 },
                { "label": "1", "matrix": [1, 7], "x": 1, "y": 0 },
                { "label": "2", "matrix": [2, 7], "x": 2, "y": 0 },
                { "label": "3", "matrix": [3, 7], "x": 3, "y": 0 },
                { "label": "4", "matrix": [4, 7], "x": 4, "y": 0 },
                { "label": "5", "matrix": [4, 6], "x": 5, "y": 0 },
                { "label": "6", "matrix": [5, 6], "x": 6, "y": 0 },
                { "label": "7", "matrix": [5, 7], "x": 7, "y": 0 },
                { "label": "8", "matrix": [6, 7], "x": 8, "y": 0 },
                { "label": "9", "matrix": [7, 7], "x": 9, "y": 0 },
                { "label": "0", "matrix": [8, 7], "x": 10, "y": 0 },
                { "label": "-", "matrix": [8, 6], "x": 11, "y": 0 },
                { "label": "=", "matrix": [6, 6], "x": 12, "y": 0 },
                { "label": "Backspace", "matrix": [10, 1], "w":2, "x": 13, "y": 0 },
                { "label": "Numlock", "matrix": [11, 4], "x": 15.5, "y": 0 },
                { "label": "Num/", "matrix": [12, 4], "x": 16.5, "y": 0 },
                { "label": "Num*", "matrix": [13, 4], "x": 17.5, "y": 0 },
                { "label": "Num-", "matrix": [13, 5], "x": 18.5, "y": 0 },

                { "label": "Tab", "matrix": [1, 1], "w": 1.5, "x": 0, "y": 1 },
                { "label": "Q", "matrix": [1, 0], "x": 1.5, "y": 1 },
                { "label": "W", "matrix": [2, 0], "x": 2.5, "y": 1 },
                { "label": "E", "ma [...]

2023-09-07 08:50 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/readme.md
> +# M0110A_ANSI
```suggestion
# M0110A
```

2023-09-07 08:50 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/info.json
> +    "keyboard_name": "M0110A_ANSI",
```suggestion
    "keyboard_name": "M0110A",
```

2023-09-07 08:50 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/readme.md
> +
```suggestion
![m0110a](https://imgur.com/bWpBa8th.png)
```

2023-09-07 08:50 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/keymaps/default/keymap.c
> +  KC_TRNS,  GUI_TOG,  KC_TRNS,                      KC_TRNS,                      KC_LEFT,  KC_DOWN,  KC_RIGHT,   KC_TRNS,                     KC_TRNS,KC_TRNS ),
```suggestion
[Win] = LAYOUT_all(
  KC_ESC,   KC_1,    KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,     KC_8,     KC_9,     KC_0,    KC_MINS,  KC_EQL,   KC_BSPC,  KC_DEL, KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
  KC_TAB,   KC_Q,    KC_W,     KC_E,     KC_R,     KC_T,     KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,    KC_LBRC,  KC_RBRC,  KC_BSLS,          KC_P7,  KC_P8,   KC_P9,   KC_PPLS,
  KC_CAPS,  KC_A,    KC_S,     KC_D,     KC_F,     KC_G,     KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN, KC_QUOT,            KC_ENT,           KC_P4,  KC_P5,   KC_P6,
  KC_LSFT,  KC_NUBS, KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_N,     KC_M,     KC_COMM,  KC_DOT,  KC_SLSH,  KC_RSFT,  KC_UP,            KC_P1,  KC_P2,   KC_P3,   KC_PENT,
  KC_LCTL,  KC_LGUI, KC_LALT,                      KC_SPC,                       KC_RALT,  MO(Winfn),KC_RCTL, KC_LEFT,  KC_DOWN,  KC_RIGHT,         KC_P0,  KC_PDOT
),

[Winfn] = LAYOUT_all(
  KC_GRV,   KC_F1,   KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,  KC_F11,   KC_F12,   _______, _______, _______,_______, _______, _______,
  QK_BOOT,  _______, _______,  _______,  _______,  _______,  _______,  KC_PGUP,  _______,  KC_PGDN,  KC_PSCR, KC_SCRL,  KC_PAUS,  _______,          _______,_______, _______, _______,
  _______,  _______, KC_VOLD,  KC_VOLU,  KC_MUTE,  _______,  KC_HOME,  _______,  _______,  _______,  KC_INS,  _______,            _______,          _______,_______, _______,
  _______,  _______, KC_APP,   _______,  _______,  _______,  _______,  KC_END,   _______,  _______,  _______, _______,  _______,  _______,          _______,_______, _______, _______,
  _______,  GUI_TOG, _______,                      _______,                      _______,  _______,  _______, _______,  _______,  _______,          _______,_______
),
```

2023-09-07 08:50 UTC, dunk2k commented on keyboards/vortex/m0110a/m0110a_ansi/keymaps/via/keymap.c
> +  KC_TRNS,  GUI_TOG,  KC_TRNS,                      KC_TRNS,                      KC_LEFT,  KC_DOWN,  KC_RIGHT,   KC_TRNS,                     KC_TRNS,KC_TRNS ),
```suggestion
[Win] = LAYOUT_all(
  KC_ESC,   KC_1,    KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,     KC_8,     KC_9,     KC_0,    KC_MINS,  KC_EQL,   KC_BSPC,  KC_DEL, KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
  KC_TAB,   KC_Q,    KC_W,     KC_E,     KC_R,     KC_T,     KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,    KC_LBRC,  KC_RBRC,  KC_BSLS,          KC_P7,  KC_P8,   KC_P9,   KC_PPLS,
  KC_CAPS,  KC_A,    KC_S,     KC_D,     KC_F,     KC_G,     KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN, KC_QUOT,            KC_ENT,           KC_P4,  KC_P5,   KC_P6,
  KC_LSFT,  KC_NUBS, KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_N,     KC_M,     KC_COMM,  KC_DOT,  KC_SLSH,  KC_RSFT,  KC_UP,            KC_P1,  KC_P2,   KC_P3,   KC_PENT,
  KC_LCTL,  KC_LGUI, KC_LALT,                      KC_SPC,                       KC_RALT,  MO(Winfn),KC_RCTL, KC_LEFT,  KC_DOWN,  KC_RIGHT,         KC_P0,  KC_PDOT
),

[Winfn] = LAYOUT_all(
  KC_GRV,   KC_F1,   KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,  KC_F11,   KC_F12,   _______, _______, _______,_______, _______, _______,
  QK_BOOT,  _______, _______,  _______,  _______,  _______,  _______,  KC_PGUP,  _______,  KC_PGDN,  KC_PSCR, KC_SCRL,  KC_PAUS,  _______,          _______,_______, _______, _______,
  _______,  _______, KC_VOLD,  KC_VOLU,  KC_MUTE,  _______,  KC_HOME,  _______,  _______,  _______,  KC_INS,  _______,            _______,          _______,_______, _______,
  _______,  _______, KC_APP,   _______,  _______,  _______,  _______,  KC_END,   _______,  _______,  _______, _______,  _______,  _______,          _______,_______, _______, _______,
  _______,  GUI_TOG, _______,                      _______,                      _______,  _______,  _______, _______,  _______,  _______,          _______,_______
),
```

2023-09-07 09:26 UTC, gskygithub commented
@dunk2k can you please take a look at the changes, thanks.

2023-09-07 10:13 UTC, gskygithub commented
@dunk2k I also have a doubt, now keyboard is recognizing as one keyboard but if I want to recognize 4 keyboards separately in VIA. How is this possible?

2023-09-07 10:13 UTC, dunk2k commented on keyboards/vortex/m0110a/info.json
> +    },
false by default
```suggestion
```

2023-09-07 10:16 UTC, dunk2k commented
> @dunk2k I also have a doubt, now keyboard is recognizing as one keyboard but if I want to recognize 4 keyboards separately in VIA. How is this possible?

Could I ask you review VIA documentation regarding [layouts](https://www.caniusevia.com/docs/layouts#layout-options)

2023-09-07 10:29 UTC, gskygithub commented
> > @dunk2k I also have a doubt, now keyboard is recognizing as one keyboard but if I want to recognize 4 keyboards separately in VIA. How is this possible?
> 
> Could I ask you review VIA documentation regarding [layouts](https://www.caniusevia.com/docs/layouts#layout-options)

@dunk2k We don't want all layouts in one keyboard, Our requirement is all 4 as a separate keyboard and we want to use separate VID and PID. sorry for misunderstanding and all the effort, thanks.

2023-09-07 10:48 UTC, dunk2k commented
> @dunk2k We don't want all layouts in one keyboard, Our requirement is all 4 as a separate keyboard and we want to use separate VID and PID. sorry for misunderstanding and all the effort, thanks.

understandable.

Could you rename directory from `keyboards/vortex/m0110a` to `keyboards/vortex/m0110a/ansi` and replace files as they were pre-layout merge 🙂

2023-09-11 18:45 UTC, dunk2k commented
> @dunk2k We don't want all layouts in one keyboard, Our requirement is all 4 as a separate keyboard and we want to use separate VID and PID. sorry for misunderstanding and all the effort, thanks.

Looking at the image provided in `readme.md` and the quote above - is it correct, during production/manufacturing, that this PCB **would not** have the ability to have more than one key arrangement?  
i.e. separate Product IDs for different physical key arrangements using the same PCB isn't conventional.

2023-09-12 03:47 UTC, gskygithub commented
> > @dunk2k We don't want all layouts in one keyboard, Our requirement is all 4 as a separate keyboard and we want to use separate VID and PID. sorry for misunderstanding and all the effort, thanks.
> 
> Looking at the image provided in `readme.md` and the quote above - is it correct, during production/manufacturing, that this PCB **would not** have the ability to have more than one key arrangement? i.e. separate Product IDs for different physical key arrangements using the same PCB just isn't conventional; applies to vortex/M0110_700_(ansi|iso) and vortex/M0110_625_(ansi|iso) also.

@dunk2k We want Firmware to support more keys to let the user choose what key they wanted to use. This is our requirement, thanks.

2023-09-22 22:04 UTC, dunk2k commented
We want Firmware to support more keys to let the user choose what key they wanted to use. This is our requirement, thanks.

unfortunately, this response sows confusion as first response says *"We don't want all layouts in one keyboard, Our requirement is all 4 as a separate keyboard and we want to use separate VID and PID"* yet second response says *"We want Firmware to support more keys to let the user choose what key they wanted to use"* - both responses state they are a requirement yet are contradicting.
Either:
1. a PCB/board that has only one key switch arrangement/layout affirms a unique Product ID, for that board
2. a PCB/board that has multiple key switch layout combinations/possibilities would have one product ID and more than one layout, in `layouts` of `info.json`. A keymap can be create per layout, which essentially creates a default keymap for each layout. It would be advised that a `matrix_diagram_md` file is supplied so users can create combinations based on the provided matrix co-ordiantes.  
e.g. from image provided, this board has key sockets for a split or non-split Right Shift, as well as split or non-split Backspace. A user *may* want an ISO Enter with an ANSI Left Shift, a combination possible on PCB/board that has key sockets for both ANSI and ISO keys.

To clarify: is the PCB for this keyboard (`Mo110a_ansi`), `Mo110a_iso`, `Mo110a_1800_ansi`, and `Mo110a_1800_iso` the one and same PCB?

2023-09-23 09:43 UTC, gskygithub commented
> We want Firmware to support more keys to let the user choose what key they wanted to use. This is our requirement, thanks.
> 
> unfortunately, this response sows confusion as first response says _"We don't want all layouts in one keyboard, Our requirement is all 4 as a separate keyboard and we want to use separate VID and PID"_ yet second response says _"We want Firmware to support more keys to let the user choose what key they wanted to use"_ - both responses state they are a requirement yet are contradicting.
> 
> Either:
> 
> 1. a PCB/board that has only one key switch arrangement/layout, affirming a unique Product ID, for that board
> 2. a PCB/board that has multiple key switch layout combinations/possibilities would have one product ID and more than one layout, in `layouts` of `info.json`. A keymap can be create per layout, which essentially creates a default keymap for each layout. It would be advised that a `matrix_diagram_md` file is supplied so users can create combinations based on the provided matrix co-ordiantes.
>    e.g. from image provided, this board has key sockets for a split or non-split Right Shift, as well as split or non-split Backspace. A user _may_ want an ISO Enter with an ANSI Left Shift, a combination possible on PCB/board that has key sockets for both ANSI and ISO keys.
> 
> To clarify: is the PCB for this keyboard (`Mo110a_ansi`), `Mo110a_iso`, `Mo110a_1800_ansi`, and `Mo110a_1800_iso` the one and same PCB?

@dunk2k sorry about the confusion, yes the 4 keyboards you mentioned will use same PCB with different PID's. (we sold keyboards like this "https://www.vortexgear.tw/products/m0110-qmk-via-vial-version") to allow the user to change their key position what they want. This PCB/board that has multiple key switch arrangements, I hope this clarifies you. Thanks.

2023-09-25 04:01 UTC, drashna approved these changes

2023-10-03 10:16 UTC, closed without merging