Add Palmetto PCB
qmk/qmk_firmware pull request #21955
Opened 2023-09-08 16:20 UTC by Rossman360

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-08 16:24 UTC, fauxpark commented on keyboards/montsinger/palmetto/config.h
> +
```suggestion
```
These are default.

2023-09-08 16:24 UTC, fauxpark commented on keyboards/montsinger/palmetto/config.h
> +#define TAP_CODE_DELAY 10
```suggestion
```
This needs to go in info.json.

2023-09-08 16:24 UTC, fauxpark commented on keyboards/montsinger/palmetto/info.json
> + "community_layouts": [
```suggestion
    "community_layouts": [
```

2023-09-08 16:24 UTC, fauxpark commented on keyboards/montsinger/palmetto/info.json
> +
```suggestion
```

2023-09-08 16:26 UTC, fauxpark commented on keyboards/montsinger/palmetto/mcuconf.h
> +#define RP_I2C_USE_I2C1 FALSE
Since you've disabled I2C these shouldn't need to be changed, and this file can be deleted.

2023-09-08 16:33 UTC, dunk2k commented
Would it be possible to either add tsangan bottom row community layouts, in `info.json`, or add a `matrix_diagram.md` file that also includes tsangan bottom row?

2023-09-08 17:29 UTC, dunk2k requested changes
community layouts added

2023-09-08 17:29 UTC, dunk2k commented on keyboards/montsinger/palmetto/info.json
> +        "60_iso_split_bs_rshift"
```suggestion
        "60_iso_split_bs_rshift",
        "60_iso_tsangan",
        "60_tsangan_hhkb",
        "60_hhkb"
```

2023-09-08 17:29 UTC, dunk2k commented on keyboards/montsinger/palmetto/info.json
> +                {"matrix": [4, 14], "x": 13.75, "y": 4, "w": 1.25}
more, tsangan based, layouts
```suggestion
                {"matrix": [4, 14], "x": 13.75, "y": 4, "w": 1.25},
        "LAYOUT_60_iso_tsangan": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [0, 2], "x": 2, "y": 0},
                {"matrix": [0, 3], "x": 3, "y": 0},
                {"matrix": [0, 4], "x": 4, "y": 0},
                {"matrix": [0, 5], "x": 5, "y": 0},
                {"matrix": [0, 6], "x": 6, "y": 0},
                {"matrix": [0, 7], "x": 7, "y": 0},
                {"matrix": [0, 8], "x": 8, "y": 0},
                {"matrix": [0, 9], "x": 9, "y": 0},
                {"matrix": [0, 10], "x": 10, "y": 0},
                {"matrix": [0, 11], "x": 11, "y": 0},
                {"matrix": [0, 12], "x": 12, "y": 0},
                {"matrix": [0, 13], "x": 13, "y": 0, "w": 2},

                {"matrix": [1, 0], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [1, 1], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [1, 4], "x": 4.5, "y": 1},
                {"matrix": [1, 5], "x": 5.5, "y": 1},
                {"matrix": [1, 6], "x": 6.5, "y": 1},
                {"matrix": [1, 7], "x": 7.5, "y": 1},
                {"matrix": [1, 8], "x": 8.5, "y": 1},
                {"matrix": [1, 9], "x": 9.5, "y": 1},
                {"matrix": [1, 10], "x": 10.5, "y": 1},
                {"matrix": [1, 11], "x": 11.5, "y": 1},
                {"matrix": [1, 12], "x": 12.5, "y": 1},

                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [2, 7], "x": 7.75, "y": 2},
                {"matrix": [2, 8], "x": 8.75, "y": 2},
                {"matrix": [2, 9], "x": 9.75, "y": 2},
                {"matrix": [2, 10], "x": 10.75, "y": 2},
                {"matrix": [2, 11], "x": 11.75, "y": 2},
                {"matrix": [2, 12], "x": 12.75, "y": 2},
                {"matrix": [2, 13], "x": 13.75, "y": 1, "w": 1.25, "h": 2},

                {"matrix": [3, 0], "x": 0, "y": 3, "w": 1.25},
                {"matrix": [3, 1], "x": 1.25, "y": 3},
                {"matrix": [3, 2], "x": 2.25, "y": 3},
                {"matrix": [3, 3], "x": 3.25, "y": 3},
                {"matrix": [3, 4], "x": 4.25, "y": 3},
                {"matrix": [3, 5], "x": 5.25, "y": 3},
                {"matrix": [3, 6], "x": 6.25, "y": 3},
                {"matrix": [3, 7], "x": 7.25, "y": 3},
                {"matrix": [3, 8], "x": 8.25, "y": 3},
                {"matrix": [3, 9], "x": 9.25, "y": 3},
                {"matrix": [3, 10], "x": 10.25, "y": 3},
                {"matrix": [3, 11], "x": 11.25, "y": 3},
                {"matrix": [3, 13], "x": 12.25, "y": 3, "w": 2.75},

                {"matrix": [4, 0], "x": 0, "y": 4, "w": 1.5},
                {"matrix": [4, 1], "x": 1.5, "y": 4},
                {"matrix": [4, 2], "x": 2.5, "y": 4, "w": 1.5},
                {"matrix": [4, 6], "x": 4, "y": 4, "w": 7},
                {"matrix": [4, 12], "x": 11, "y": 4, "w": 1.5},
                {"matrix": [4, 13], "x": 12.5, "y": 4},
                {"matrix": [4, 14], "x": 13.5, "y": 4, "w": 1.5}
            ]
        },
        "LAYOUT_60_tsangan_hhkb": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [0, 2], "x": 2, "y": 0},
                {"matrix": [0, 3], "x": 3, "y": 0},
                {"matrix": [0, 4], "x": 4, "y": 0},
                {"matrix": [0, 5], "x": 5, "y": 0},
                {"matrix": [0, 6], "x": 6, "y": 0},
                {"matrix": [0, 7], "x": 7, "y": 0},
                {"matrix": [0, 8], "x": 8, "y": 0},
                {"matrix": [0, 9], "x": 9, "y": 0},
                {"matrix": [0, 10], "x": 10, "y": 0},
                {"matrix": [0, 11], "x": 11, "y": 0},
                {"matrix": [0, 12], "x": 12, "y": 0},
                {"matrix": [0, 13], "x": 13, "y": 0},
                {"matrix": [0, 14], "x": 14, "y": 0},

                {"matrix": [1, 0], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [1, 1], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [1, 4], "x": 4.5, "y": 1},
                {"matrix": [1, 5], "x": 5.5, "y": 1},
                {"matrix": [1, 6], "x": 6.5, "y": 1},
                {"matrix": [1, 7], "x": 7.5, "y": 1},
                {"matrix": [1, 8], "x": 8.5, "y": 1},
                {"matrix": [1, 9], "x": 9.5, "y": 1},
                {"matrix": [1, 10], "x": 10.5, "y": 1},
                {"matrix": [1, 11], "x": 11.5, "y": 1},
                {"matrix": [1, 12], "x": 12.5, "y": 1},
                {"matrix": [1, 13], "x": 13.5, "y": 1, "w": 1.5},

                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [2, 7], "x": 7.75, "y": 2},
                {"matrix": [2, 8], "x": 8.75, "y": 2},
                {"matrix": [2, 9], "x": 9.75, "y": 2},
                {"matrix": [2, 10], "x": 10.75, "y": 2},
                {"matrix": [2, 11], "x": 11.75, "y": 2},
                {"matrix": [2, 13], "x": 12.75, "y": 2, "w": 2.25},

                {"matrix": [3, 0], "x": 0, "y": 3, "w": 2.25},
                {"matrix": [3, 2], "x": 2.25, "y": 3},
                {"matrix": [3, 3], "x": 3.25, "y": 3},
                {"matrix": [3, 4], "x": 4.25, "y": 3},
                {"matrix": [3, 5], "x": 5.25, "y": 3},
                {"matrix": [3, 6], "x": 6.25, "y": 3},
                {"matrix": [3, 7], "x": 7.25, "y": 3},
                {"matrix": [3, 8], "x": 8.25, "y": 3},
                {"matrix": [3, 9], "x": 9.25, "y": 3},
                {"matrix": [3, 10], "x": 10.25, "y": 3},
                {"matrix": [3, 11], "x": 11.25, "y": 3},
                {"matrix": [3, 13], "x": 12.25, "y": 3, "w": 1.75},
                {"matrix": [3, 14], "x": 14, "y": 3},

                {"matrix": [4, 0], "x": 0, "y": 4, "w": 1.5},
                {"matrix": [4, 1], "x": 1.5, "y": 4},
                {"matrix": [4, 2], "x": 2.5, "y": 4, "w": 1.5},
                {"matrix": [4, 6], "x": 4, "y": 4, "w": 7},
                {"matrix": [4, 12], "x": 11, "y": 4, "w": 1.5},
                {"matrix": [4, 13], "x": 12.5, "y": 4},
                {"matrix": [4, 14], "x": 13.5, "y": 4, "w": 1.5}
            ]
        },
        "LAYOUT_60_hhkb": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [0, 2], "x": 2, "y": 0},
                {"matrix": [0, 3], "x": 3, "y": 0},
                {"matrix": [0, 4], "x": 4, "y": 0},
                {"matrix": [0, 5], "x": 5, "y": 0},
                {"matrix": [0, 6], "x": 6, "y": 0},
                {"matrix": [0, 7], "x": 7, "y": 0},
                {"matrix": [0, 8], "x": 8, "y": 0},
                {"matrix": [0, 9], "x": 9, "y": 0},
                {"matrix": [0, 10], "x": 10, "y": 0},
                {"matrix": [0, 11], "x": 11, "y": 0},
                {"matrix": [0, 12], "x": 12, "y": 0},
                {"matrix": [0, 13], "x": 13, "y": 0},
                {" [...]

2023-09-08 17:33 UTC, dunk2k requested changes

2023-09-08 17:33 UTC, dunk2k commented on keyboards/montsinger/palmetto/info.json
> +                {"matrix": [3, 14], "x": 14, "y": 3},
```suggestion
                {"matrix": [3, 13], "x": 12.25, "y": 3, "w": 2.75},
```

2023-09-08 17:33 UTC, dunk2k commented on keyboards/montsinger/palmetto/info.json
> +                {"matrix": [0, 14], "x": 14, "y": 0},
```suggestion
                {"matrix": [0, 13], "x": 13, "y": 0, "w": 2},
```

2023-09-08 18:00 UTC, dunk2k approved these changes

2023-09-08 18:03 UTC, dunk2k commented on keyboards/montsinger/palmetto/readme.md
An, imgur hosted, image of this PCB/keyboard would be great, if you could please? 🙂

2023-09-19 03:49 UTC, drashna requested changes

2023-09-19 03:49 UTC, drashna commented on keyboards/montsinger/palmetto/info.json
> +        "extrakey": true,
```suggestion
        "bootmagic": true,
        "extrakey": true,
```

2023-09-19 03:49 UTC, drashna commented on keyboards/montsinger/palmetto/readme.md
> +Palmetto PCB from Montsinger (https://carolinamech.com/cdn/shop/products/IMG_20210327_164948_040_1024x1024@2x.jpg?v=1620393767)
Please rehost this on imgur or the like.

2023-09-19 03:49 UTC, drashna commented on keyboards/montsinger/palmetto/halconf.h
This file isn't needed, as i2c should be defaulted to off.

2023-09-19 03:51 UTC, drashna commented on keyboards/montsinger/palmetto/keymaps/via/rules.mk
This needs to be removed, or you need to add a keymap.c

2023-09-23 05:42 UTC, drashna commented on keyboards/montsinger/palmetto/readme.md
> +Palmetto PCB from Montsinger (https://i.imgur.com/VmmAW97)
```suggestion
Palmetto PCB from Montsinger (https://i.imgur.com/VmmAW97h.jpeg)
```

2023-09-23 06:18 UTC, fauxpark approved these changes

2023-09-25 03:33 UTC, drashna approved these changes

2023-09-25 03:33 UTC, merged