Chromatonemini info json revised to support qmk 0.22.2
qmk/qmk_firmware pull request #21966
Opened 2023-09-09 15:49 UTC by 3araht

## Description

info.json updated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-09 16:51 UTC, dunk2k requested changes

2023-09-09 16:51 UTC, dunk2k commented on keyboards/chromatonemini/info.json
> +            "SOLID_MULTISPLASH": true
lower case please

2023-09-19 03:40 UTC, drashna approved these changes

2023-09-25 02:55 UTC, tzarc approved these changes

2023-09-25 02:55 UTC, merged