[Keyboard] Add MIIIW BlackIO83
qmk/qmk_firmware pull request #21970
Opened 2023-09-10 12:47 UTC by ArthurCyy

## Description

Add MIIIW BlackIO83, an ansi version of 83 keys keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-10 14:21 UTC, ArthurCyy commented
> Please stop opening new PRs. You can update the existing one by pushing to the same branch.

Sorry, I will push to the same branch and not open new PRs.

2023-09-19 02:46 UTC, drashna commented on keyboards/miiiw/blackio83/blackio83.c
> +    rgb_matrix_set_suspend_state(true);
Clever.  Though, this would only work if suspend is enabled for rgb matrix, in general.  If it's not... then it won't do anything.

2023-09-19 03:37 UTC, drashna requested changes

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/keymaps/via/keymap.c
> +        }
There are already keycodes for this.  is there a specific reason for this?

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/config.h
> +#define MATRIX_COL_PINS { H0, H1, H2, H3, H4, H5, H6, H7, H8, H9, H10, H11, H12, H13, H14, H15 }
This should be moved to info.json

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/config.h
> +#define LED_NUM_LOCK_PIN B14
same

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/rev_0100.c
> +/* Leds on the CU80 go ltr > rtl > ltr > rlt > Ltr > rtl */
This should be moved to the info.json

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/rules.mk
> +# EEPROM_DRIVER = i2c
All of this can be moved to the info.json.   `qmk info -kb (name) -f ascii` can help with that

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/common/ws2812_custom.c
This is a direct copy of the bitbang driver for ws2812.  

This file should be removed

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/rules.mk
> +
```suggestion
```

2023-09-19 03:37 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/rules.mk
> +       common/ws2812_custom.c
```suggestion
# Project specific files
SRC += matrix.c \
	   common/shift_register.c \
```

To add the rgb driver with additional behavior...

Add this:
```make
WS2812_DRIVER_REQUIRED := yes
```
And then properly implement a custom driver.  Eg: 
```c
// LED color buffer
rgb_led_t rgb_matrix_ws2812_array[RGB_MATRIX_LED_COUNT];
bool      ws2812_dirty = false;
static bool p_setup = false;
static bool s_init = false;

static void init(void) {
    palSetLineMode(WS2812_DI_PIN, WS2812_OUTPUT_MODE);
}

void ws2812_poweron(void) {
    if(p_setup) return;
    p_setup = true;
    s_init = false;
    setPinOutput(RGB_EN_PIN);
    writePinHigh(RGB_EN_PIN);
}

void ws2812_poweroff(void) {
    if(!p_setup) return;
    p_setup = false;
    setPinInputLow(WS2812_DI_PIN);
    writePinLow(RGB_EN_PIN);
}

static void flush(void) {
    if (ws2812_dirty && p_setup) {
        ws2812_setleds(rgb_matrix_ws2812_array, RGB_MATRIX_LED_COUNT);
        ws2812_dirty = false;
    }
}

// Set an led in the buffer to a color
static inline void setled(int i, uint8_t r, uint8_t g, uint8_t b) {
#    if defined(RGB_MATRIX_ENABLE) && defined(RGB_MATRIX_SPLIT)
    const uint8_t k_rgb_matrix_split[2] = RGB_MATRIX_SPLIT;
    if (!is_keyboard_left()) {
        if (i >= k_rgb_matrix_split[0]) {
            i -= k_rgb_matrix_split[0];
        } else {
            return;
        }
    } else if (i >= k_rgb_matrix_split[0]) {
        return;
    }
#    endif

    if (rgb_matrix_ws2812_array[i].r == r && rgb_matrix_ws2812_array[i].g == g && rgb_matrix_ws2812_array[i].b == b) {
        return;
    }

    ws2812_dirty                 = true;
    rgb_matrix_ws2812_array[i].r = r;
    rgb_matrix_ws2812_array[i].g = g;
    rgb_matrix_ws2812_array[i].b = b;
#    ifdef RGBW
    convert_rgb_to_rgbw(&rgb_matrix_ws2812_array[i]);
#    endif
}

static void setled_all(uint8_t r, uint8_t g, uint8_t b) {
    for (int i = 0; i < ARRAY_SIZE(rgb_matrix_ws2812_array); i++) {
        setled(i, r, g, b);
    }
}

const rgb_matrix_driver_t rgb_matrix_driver = {
    .init          = init,
    .flush         = flush,
    .set_color     = setled,
    .set_color_all = setled_all,
};
```

This has the advantage of using the core driver files, so it's not a duplicate and out of date and fragmented version of the core file.  (eg, any updates or fixes would be carried over to your board).

2023-09-20 04:15 UTC, ArthurCyy commented
Thanks! Changes have been made based on your suggestions, but may still be lacking. @drashna

2023-09-23 08:57 UTC, drashna requested changes

2023-09-23 08:57 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/config.h
> +#define RGB_MATRIX_LED_COUNT RGBLED_NUM
```suggestion
#define RGB_MATRIX_LED_COUNT 83
```

2023-09-23 08:57 UTC, drashna commented on keyboards/miiiw/blackio83/rev_0100/config.h
> +#define DIP_SWITCH_PINS { POWER_SWITCH_PIN, B1, B8, B12 }
```suggestion
#define DIP_SWITCH_PINS { B0, B1, B8, B12 }
```

2023-09-23 08:57 UTC, drashna commented on keyboards/miiiw/blackio83/config.h
> +#define MATRIX_COLS 16
This matches the number of pins defined in the info.json, so shouldn't be necessary (as it will be automatically generated)
```suggestion
```

2023-09-25 05:36 UTC, drashna approved these changes

2023-10-10 00:41 UTC, noroadsleft approved these changes
Looks good to me.

2023-10-10 00:41 UTC, merged

2023-10-10 00:41 UTC, noroadsleft commented
Thanks!