Add Jank RP2040 Dactyl
qmk/qmk_firmware pull request #21973
Opened 2023-09-11 10:21 UTC by wheres-perry

## Description

Adding handwired keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-17 17:48 UTC, waffle87 requested changes

2023-09-17 17:48 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/config.h
> +#define GRAVE_ESC_SHIFT_OVERRIDE //
```suggestion
// Copyright 2023 Ethan Perry (@wheres-perry)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define GRAVE_ESC_SHIFT_OVERRIDE
```

2023-09-17 17:48 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +        KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,MO(_ARROWLAYER),
```suggestion
        KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS, KC_TRNS,
```

2023-09-17 17:48 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +        MO(_FUNCTIONLAYER),  KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
```suggestion
        KC_TRNS,  KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,  
```

2023-09-17 17:48 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +				                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, MO(_SYMBOLLAYER), KC_TAB,
```suggestion
				                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, KC_TRNS, KC_TAB,     
```

2023-09-17 17:48 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/rules.mk
> +BOOTMAGIC_ENABLE = yes
```suggestion
```

2023-09-17 17:48 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/info.json
> +        "nkro": true
```suggestion
        "nkro": true,
        "bootmagic": true
```

2023-09-19 02:41 UTC, drashna requested changes

2023-09-19 02:41 UTC, drashna commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +				                  KC_DEL, KC_SPC,KC_BSPC,       KC_ENT, MO(_SYMBOLLAYER), KC_TAB,
```suggestion
                                  KC_DEL, KC_SPC,KC_BSPC,       KC_ENT, MO(_SYMBOLLAYER), KC_TAB,    
```

2023-09-19 02:41 UTC, drashna commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +				                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, MO(_SYMBOLLAYER), KC_TAB,
```suggestion
                                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, MO(_SYMBOLLAYER), KC_TAB,    
```

2023-09-19 02:41 UTC, drashna commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +				                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, MO(_SYMBOLLAYER), KC_TAB,
```suggestion
                                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, MO(_SYMBOLLAYER), KC_TAB,    
```

2023-09-19 02:41 UTC, drashna commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +				                  KC_DEL, KC_SPC,KC_BSPC,      KC_ENT, KC_TRNS, KC_TAB,
```suggestion
                                  KC_DEL, KC_SPC,KC_BSPC,       KC_ENT, MO(_SYMBOLLAYER), KC_TAB,    
```

2023-09-19 02:41 UTC, drashna commented on keyboards/handwired/jankrp2040dactyl/info.json
> +        "console": false,
```suggestion
```

2023-09-19 02:41 UTC, drashna commented on keyboards/handwired/jankrp2040dactyl/info.json
> +	    "rows": ["GP8", "GP9", "GP10", "GP11", "GP12"]
```suggestion
        "rows": ["GP8", "GP9", "GP10", "GP11", "GP12"]
```

2023-09-19 22:50 UTC, waffle87 requested changes

2023-09-19 22:50 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +        KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,MO(_ARROWLAYER),
```suggestion
        KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,      KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
```

2023-09-19 22:50 UTC, waffle87 commented on keyboards/handwired/jankrp2040dactyl/keymaps/default/keymap.c
> +                                  KC_DEL, KC_SPC,KC_BSPC,       KC_ENT, MO(_SYMBOLLAYER), KC_TAB,
```suggestion
       KC_TRNS,  KC_QUES,KC_QUOT,KC_DQUO,KC_COLN,KC_SCLN,      KC_LPRN,KC_RPRN,KC_COMM,KC_DOT, KC_MINS,KC_NO,
        KC_LSFT,KC_CIRC,KC_PERC,KC_AMPR,KC_HASH,KC_SLSH,      KC_LBRC,KC_RBRC,KC_DLR,	KC_AT,	KC_EXLM,KC_TRNS,
                                  KC_DEL, KC_SPC,KC_BSPC,       KC_ENT, KC_TRNS, KC_TAB,    
```

2023-09-21 17:18 UTC, waffle87 approved these changes

2023-09-23 08:34 UTC, drashna approved these changes

2023-09-23 08:34 UTC, merged