Added k3 qmk keyboard
qmk/qmk_firmware pull request #21980
Opened 2023-09-12 06:32 UTC by proceee

Added  darmoshark k3 qmk keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-12 06:50 UTC, zvecr requested changes

2023-09-12 06:50 UTC, zvecr commented on keyboards/darmoshark/k3/.gitignore
This file should be removed.

2023-09-12 06:50 UTC, zvecr commented on keyboards/darmoshark/k3/info.json
> +        "speed_steps": 64,
```suggestion
```

2023-09-12 06:50 UTC, zvecr commented on keyboards/darmoshark/k3/keymaps/default/keymap.c
> +    )
```suggestion
    )
```

2023-09-12 06:50 UTC, zvecr commented on keyboards/darmoshark/k3/keymaps/via/keymap.c
> +    )
```suggestion
    )
```

2023-09-12 06:50 UTC, zvecr commented on keyboards/darmoshark/k3/readme.md
> +# K3 QMK
```suggestion
# K3 QMK
```

2023-09-12 06:50 UTC, zvecr commented on keyboards/darmoshark/k3/readme.md
> +    make k3:default:flash
```suggestion
    make darmoshark/k3:default

Flashing example for this keyboard:

    make darmoshark/k3:default:flash
```

2023-09-12 06:53 UTC, tzarc commented on keyboards/darmoshark/k3/mcuconf.h
> +// Copyright 2023 Proceee
Remove this file, it is not used.

2023-09-12 06:55 UTC, tzarc commented
Also, it would be much appreciated if you stopped changing github handles every few boards.

2023-09-12 06:57 UTC, zvecr requested changes

2023-09-12 06:57 UTC, zvecr commented on keyboards/darmoshark/k3/info.json
> +                { "matrix":[5,2],  "x": 2, "y": 5 }
```suggestion
                { "matrix":[2,2], "x": 2, "y": 2 },

                { "matrix":[3,0], "x": 0, "y": 3 },
                { "matrix":[3,1], "x": 1, "y": 3 },
                { "matrix":[3,2], "x": 2, "y": 3 },
                { "matrix":[2,3], "x": 3, "y": 2, "h": 2 },

                { "matrix":[4,0], "x": 0, "y": 4 },
                { "matrix":[4,1], "x": 1, "y": 4 },
                { "matrix":[4,2], "x": 2, "y": 4 },

                { "matrix":[5,1],  "x": 0, "y": 5, "w": 2 },
                { "matrix":[5,2],  "x": 2, "y": 5 },
                { "matrix":[4,3], "x": 3, "y": 4, "h": 2 }
```

2023-09-12 06:57 UTC, zvecr commented on keyboards/darmoshark/k3/info.json
> +        "LAYOUT": {
```suggestion
    "community_layouts": ["numpad_6x4"],
    "layouts": {
        "LAYOUT_numpad_6x4": {
```

2023-09-12 06:57 UTC, zvecr commented on keyboards/darmoshark/k3/keymaps/default/keymap.c
> +        _______,            RGB_TOG
```suggestion
    [0] = LAYOUT_numpad_6x4(
        KC_ESC,   KC_TAB,   KC_BSPC,  MO(1),
        KC_NUM,   KC_PSLS,  KC_PAST,  KC_PMNS,
        KC_P7,    KC_P8,    KC_P9, 
        KC_P4,    KC_P5,    KC_P6, KC_PPLS,
        KC_P1,    KC_P2,    KC_P3,
        KC_P0,              KC_PDOT,    KC_PENT
    ),

    [1] = LAYOUT_numpad_6x4(
        EE_CLR,   _______,  RGB_MOD,  _______,
        KC_CALC,  _______,  _______,  RGB_VAD,
        _______,  RGB_SPI,  _______,
        _______,  _______,  _______, RGB_VAI,
        _______,  RGB_SPD,  _______, 
        _______,            RGB_TOG,    _______
```

2023-09-12 06:57 UTC, zvecr commented on keyboards/darmoshark/k3/keymaps/via/keymap.c
> +        _______,            RGB_TOG
```suggestion
    [0] = LAYOUT_numpad_6x4(
        KC_ESC,   KC_TAB,   KC_BSPC,  MO(1),
        KC_NUM,   KC_PSLS,  KC_PAST,  KC_PMNS,
        KC_P7,    KC_P8,    KC_P9, 
        KC_P4,    KC_P5,    KC_P6, KC_PPLS,
        KC_P1,    KC_P2,    KC_P3,
        KC_P0,              KC_PDOT,    KC_PENT
    ),

    [1] = LAYOUT_numpad_6x4(
        EE_CLR,   _______,  RGB_MOD,  _______,
        KC_CALC,  _______,  _______,  RGB_VAD,
        _______,  RGB_SPI,  _______,
        _______,  _______,  _______, RGB_VAI,
        _______,  RGB_SPD,  _______, 
        _______,            RGB_TOG,    _______
```

2023-09-12 07:06 UTC, tzarc commented on keyboards/darmoshark/k3/mcuconf.h
> +// Copyright 2023 Proceee
Ignore this, you're using the QSPI peripheral in SPI mode.

2023-09-12 07:08 UTC, proceee commented
> Also, it would be much appreciated if you stopped changing github handles every few boards.

I don't quite see your point

2023-09-19 02:33 UTC, drashna commented on keyboards/darmoshark/k3/info.json
> +        "vid": "0x3555",
https://www.the-sz.com/products/usbid/index.php?v=0x3555&p=&n=

2023-10-14 14:57 UTC, dunk2k requested changes

2023-10-14 14:57 UTC, dunk2k commented on keyboards/darmoshark/k3/rules.mk
> +EEPROM_DRIVER = wear_leveling
migrate to `info.json`
```suggestion
```

2023-10-14 14:57 UTC, dunk2k commented on keyboards/darmoshark/k3/info.json
> +    },
```suggestion
    },
    "eeprom": {
        "driver": "wear_leveling"
    },
```

2023-10-24 01:07 UTC, proceee commented on keyboards/darmoshark/k3/info.json
> +        "vid": "0x3555",
```suggestion
        "vid": "0xC001",
```

2023-11-08 06:10 UTC, drashna approved these changes

2023-12-23 01:40 UTC, proceee commented
Can merge？

2023-12-23 01:56 UTC, zvecr requested changes

2023-12-23 01:56 UTC, zvecr commented on keyboards/darmoshark/k3/config.h
> +
```suggestion

```

2023-12-23 01:56 UTC, zvecr commented on keyboards/darmoshark/k3/config.h
> +#define RGB_MATRIX_KEYPRESSES
```suggestion

#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C12
```

2023-12-23 01:56 UTC, zvecr commented on keyboards/darmoshark/k3/rules.mk
> +WEAR_LEVELING_DRIVER = spi_flash
```suggestion
# This file intentionally left blank
```

2023-12-23 01:56 UTC, zvecr commented on keyboards/darmoshark/k3/info.json
> +        "driver": "wear_leveling"
```suggestion
        "driver": "wear_leveling",
        "wear_leveling": {
            "driver": "spi_flash",
            "backing_size": 4096
        }
```

2023-12-23 01:56 UTC, zvecr commented on keyboards/darmoshark/k3/info.json
> +        "driver": "ws2812",
```suggestion
        "driver": "ws2812",
        "default":{
          "val": 80
        },
        "sleep": true.
```

2023-12-23 02:00 UTC, zvecr commented on keyboards/darmoshark/k3/info.json
> +        "sleep": true.
Sorry, fixes previous bad suggesion 
```suggestion
        "sleep": true,
```

2023-12-23 08:43 UTC, drashna approved these changes

2023-12-23 23:54 UTC, fauxpark approved these changes

2023-12-24 03:01 UTC, merged