Update Keychron Q3
qmk/qmk_firmware pull request #21995
Opened 2023-09-13 03:52 UTC by adophoxia

## Description
Superseeds https://github.com/qmk/qmk_firmware/pull/21406, but this will only cover one board from each series update of PRs.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-20 22:48 UTC, dunk2k requested changes

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/ansi_encoder/info.json
> +    },
```suggestion
    },
    "community_layouts": ["tkl_f13_ansi"],
```

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/ansi/info.json
>      },
```suggestion
    },
    "community_layouts": ["tkl_ansi"],
```

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/iso/info.json
>      },
```suggestion
    },
    "community_layouts": ["tkl_iso"],
```

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/iso_encoder/info.json
> +    },
```suggestion
    },
    "community_layouts": ["tkl_f13_iso"],
```

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/jis/info.json
>      },
```suggestion
    },
    "layout_aliases": {
        "LAYOUT_tkl_jis": "LAYOUT_jis_91"
    },
    "community_layouts": ["tkl_jis"],
```

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/jis_encoder/info.json
> +    },
```suggestion
    },
    "layout_aliases": {
        "LAYOUT_tkl_f13_jis": "LAYOUT_jis_92"
    },
    "community_layouts": ["tkl_f13_jis"],
```

2023-09-20 22:48 UTC, dunk2k commented on keyboards/keychron/q3/readme.md
> +![Keychron Q3](https://i.imgur.com/KjP4nqd.jpg)
```suggestion
![Keychron Q3](https://i.imgur.com/KjP4nqdh.jpg)
```

2023-09-21 04:56 UTC, drashna approved these changes
LGTM.  Though, the community layout support would be good to have, too.

2023-09-22 18:16 UTC, dunk2k approved these changes

2023-09-25 03:17 UTC, drashna commented on keyboards/keychron/q3/config.h
> +#endif
```suggestion
#define ENCODER_DEFAULT_POS 0x3
```

2023-10-04 03:53 UTC, drashna commented
CI failure is due to `brandonschlack` keymap.  Otherwise, LGTM.

2023-10-04 03:53 UTC, merged