Update Keychron Q0
qmk/qmk_firmware pull request #21997
Opened 2023-09-13 04:00 UTC by adophoxia

## Description
Superseeds https://github.com/qmk/qmk_firmware/pull/21406, but this will only cover one board from each series update of PRs.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-13 12:51 UTC, zvecr requested changes

2023-09-13 12:51 UTC, zvecr commented on keyboards/keychron/q0/rev_0131/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
This should not be re-introduced
```suggestion
# This file intentionally left blank
```

2023-09-13 12:51 UTC, zvecr commented on keyboards/keychron/q0/rev_0130/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```suggestion
# This file intentionally left blank
```

2023-09-13 12:51 UTC, zvecr commented on keyboards/keychron/q0/info.json
> +        "rgblight": false
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgb_matrix": true
```

2023-09-19 01:43 UTC, drashna commented
Since this is moving the folders around, this needs an entry in https://github.com/qmk/qmk_firmware/blob/master/data/mappings/keyboard_aliases.hjson at the very least.

2023-09-19 01:45 UTC, drashna requested changes

2023-09-19 01:45 UTC, drashna commented on keyboards/keychron/q1v1/q1.c
this file needs to be renamed to q1v1.c

2023-09-19 01:51 UTC, adophoxia commented on keyboards/keychron/q1v1/q1.c
I must've mistakenly pulled the `keychron-q1v1-update `branch for my `Update Keychron Q1` PR and merged it, seeing how even `q1/readme.md` was changed. I'll deal with this right now.

2023-09-19 02:04 UTC, closed without merging