Update Keychron Q1v1
qmk/qmk_firmware pull request #21993
Opened 2023-09-13 03:37 UTC by adophoxia

## Description
Superseeds #21406, but this will only cover one board from each series update of PRs. After this is made, 21406 will be closed to make things more simpler.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-23 08:59 UTC, drashna requested changes
needs an entry in `/data/mapping/keyboard_aliases.hjson`

2023-09-23 08:59 UTC, drashna commented on keyboards/keychron/q1v1/q1.c
This needs to be renamed to match the folder name, or it won't be picked up.

2023-09-25 06:19 UTC, drashna commented on keyboards/keychron/q1v1/config.h
> +#endif
```suggestion
#define ENCODER_DEFAULT_POS 0x3
```

2023-09-26 01:42 UTC, adophoxia commented
Since the LED driver for this board uses `is32fl3733`, do I also need to have: 
```h
#define DRIVER_ADDR_1 IS31FL3733_I2C_ADDRESS_GND_GND
#define DRIVER_ADDR_2 IS31FL3733_I2C_ADDRESS_GND_VCC
```
as well?

2023-09-29 06:27 UTC, drashna reviewed
If you could, yeah?

2023-09-30 02:06 UTC, adophoxia commented
Added `IS32FL3733_I2C_ADDRESS` names in recent commit.

2023-10-04 03:51 UTC, drashna approved these changes

2023-10-04 03:53 UTC, merged