chibios: disable RWX segment warning on newer GNU lds
qmk/qmk_firmware pull request #22007
Opened 2023-09-13 15:44 UTC by t-8ch

The cc-option and try-run functions are GPL2 from the Linux kernel.
cc-option was adapted to also handle -Wl,foo linker arguments.

See discussion in #21986
Cc @tzarc @KarlK90

2023-09-17 10:45 UTC, tzarc requested changes

2023-09-17 10:45 UTC, tzarc commented on builddefs/common_rules.mk
> +	fi)
```suggestion
try-run = $(shell set -e; \
	TMP=$(TMPOUT)/tmp; \
	mkdir -p $(TMPOUT); \
	trap "rm -rf $(TMPOUT)" EXIT; \
	if ($(1)) >/dev/null 2>&1; \
	then echo "$(2)"; \
	else echo "$(3)"; \
	fi)
```

2023-09-18 11:35 UTC, tzarc approved these changes

2023-09-18 13:48 UTC, sigprof commented
> The cc-option and try-run functions are GPL2 from the Linux kernel.

Unfortunately, the Linux license is GPL-2.0-only, not GPL-2.0-or-later, and QMK contains quite some code marked as GPL-3.0-or-later.

There might be some other implementations of option checking which won't have license compatibility issues like that (e.g., https://git.busybox.net/uClibc/tree/Rules.mak is LGPL-2.1-only, which, according to the [license compatibility table in the GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility), can be relicensed as GPL-2.0-or-later).

2023-09-19 05:53 UTC, t-8ch commented
@sigprof Thanks for the pointer! I naively assumed "GPL" == "GPL-2.0".

I'll look at the other implementations.

FYI there are is also some GPL-2.0-only code in `keymaps/`

2023-09-19 06:56 UTC, drashna commented
> FYI there are is also some GPL-2.0-only code in `keymaps/`

To not pollute the convo here, would you mind creating an issue with links to the offending keymaps?

2023-09-20 10:43 UTC, drashna reviewed
Older gcc versions don't like this.  Like arm-none-eabi-gcc 8.x, which is basically what we target for. 

>  | /usr/local/Cellar/arm-gcc-bin@8/8-2019-q3-update_3/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld: unrecognized option '--no-warn-rwx-segments'

2023-09-20 21:21 UTC, t-8ch commented
> Older gcc versions don't like this.

This is what the `cc-option` thingy is supposed to handle.
I messed it up when migrating from the kernel to uclibc implementation though.
Should work again.

2023-09-21 19:25 UTC, drashna commented
Can confirm this works now, with arm-none-eabi-gcc 8.x

2023-11-13 22:26 UTC, tzarc approved these changes

2023-11-13 22:29 UTC, zvecr approved these changes

2023-11-13 22:29 UTC, merged

2023-11-13 22:39 UTC, tzarc commented
This breaks I2C builds. Reverting.

2023-11-13 22:41 UTC, t-8ch commented
> This breaks I2C builds

Could you provide a reproducer or log?

2023-11-13 22:47 UTC, tzarc commented
`make aeboards/satellite/rev1:default`
```
Compiling: platforms/avr/drivers/i2c_master.c                                                      In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:60:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   60 |     TWCR = 0;
      |          ^
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:62:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   62 |     TWCR = (1 << TWINT) | (1 << TWSTA) | (1 << TWEN);
      |          ^
In function 'i2c_start':
cc1: note: source object is likely at address zero
In file included from /usr/avr/include/avr/io.h:99,
                 from platforms/avr/drivers/i2c_master.c:20:
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:65:14: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   65 |     while (!(TWCR & (1 << TWINT))) {
      |              ^~~~
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:72:11: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   72 |     if (((TW_STATUS & 0xF8) != TW_START) && ((TW_STATUS & 0xF8) != TW_REP_START)) {
      |           ^~~~~~~~~
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:72:47: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   72 |     if (((TW_STATUS & 0xF8) != TW_START) && ((TW_STATUS & 0xF8) != TW_REP_START)) {
      |                                               ^~~~~~~~~
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:77:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   77 |     TWDR = address;
      |          ^
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:79:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   79 |     TWCR = (1 << TWINT) | (1 << TWEN);
      |          ^
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:82:14: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   82 |     while (!(TWCR & (1 << TWINT))) {
      |              ^~~~
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_start_impl',
    inlined from 'i2c_start' at platforms/avr/drivers/i2c_master.c:103:18:
platforms/avr/drivers/i2c_master.c:89:30: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
   89 |     uint8_t twst = TW_STATUS & 0xF8;
      |                              ^
In function 'i2c_start':
cc1: note: source object is likely at address zero
In function 'i2c_stop',
    inlined from 'i2c_transmit' at platforms/avr/drivers/i2c_master.c:165:5:
platforms/avr/drivers/i2c_master.c:298:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
  298 |     TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
      |          ^
In function 'i2c_transmit':
cc1: note: source object is likely at address zero
In function 'i2c_stop',
    inlined from 'i2c_receive' at platforms/avr/drivers/i2c_master.c:187:5:
platforms/avr/drivers/i2c_master.c:298:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
  298 |     TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
      |          ^
In function 'i2c_receive':
cc1: note: source object is likely at address zero
In function 'i2c_stop',
    inlined from 'i2c_writeReg' at platforms/avr/drivers/i2c_master.c:202:5:
platforms/avr/drivers/i2c_master.c:298:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
  298 |     TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
      |          ^
In function 'i2c_writeReg':
cc1: note: source object is likely at address zero
In function 'i2c_stop',
    inlined from 'i2c_writeReg16' at platforms/avr/drivers/i2c_master.c:221:5:
platforms/avr/drivers/i2c_master.c:298:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
  298 |     TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
      |          ^
In function 'i2c_writeReg16':
cc1: note: source object is likely at address zero
In function 'i2c_stop',
    inlined from 'i2c_readReg' at platforms/avr/drivers/i2c_master.c:254:5:
platforms/avr/drivers/i2c_master.c:298:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
  298 |     TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
      |          ^
In function 'i2c_readReg':
cc1: note: source object is likely at address zero
In function 'i2c_stop',
    inlined from 'i2c_readReg16' at platforms/avr/drivers/i2c_master.c:291:5:
platforms/avr/drivers/i2c_master.c:298:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds=]
  298 |     TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTO);
      |          ^
In function 'i2c_readReg16':
cc1: note: source object is likely at address zero
cc1: all warnings being treated as errors
```

2023-11-13 22:48 UTC, tzarc commented
(`avr-gcc` from fedora 38)
```
% avr-gcc -v                                                                                                
Using built-in specs.
Reading specs from /usr/lib/gcc/avr/13.2.0/device-specs/specs-avr2
COLLECT_GCC=/usr/bin/avr-gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/avr/13.2.0/lto-wrapper
Target: avr
Configured with: ../gcc-13.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --target=avr --enable-languages=c,c++ --disable-nls --disable-libssp --with-system-zlib --enable-version-specific-runtime-libs --with-pkgversion='Fedora 13.2.0-1.fc38' --with-bugurl=https://bugzilla.redhat.com/
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 13.2.0 (Fedora 13.2.0-1.fc38) 
```

2023-11-14 06:57 UTC, t-8ch commented
I managed to break my own fix for gcc13...