Allow for specifying `all` for keyboard name.
qmk/qmk_firmware pull request #22022
Opened 2023-09-14 10:18 UTC by tzarc

## Description

Docs currently state that one can do a `qmk compile -kb all -km ...`, but specifying `all` would throw errors.
This just reroutes such requests to invoke `qmk mass-compile`.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-14 11:58 UTC, dunk2k approved these changes

2023-09-14 12:20 UTC, sigprof requested changes

2023-09-14 21:56 UTC, tzarc commented on lib/python/qmk/cli/flash.py
> +        return False
Yep, much cleaner. Done.

2023-09-17 05:01 UTC, tzarc commented on lib/python/qmk/cli/mass_compile.py
Diff best viewed with whitespace changes ignored.

2023-09-19 01:24 UTC, drashna approved these changes
Not a python export, but LGTM.

2023-09-22 02:12 UTC, merged