Bastard Keyboards: Add support for Dilemma Max (4x6_4)
qmk/qmk_firmware pull request #22064
Opened 2023-09-18 17:18 UTC by casuanoob

## Description

This PR adds support for @bstiq's Dilemma Max keyboard, which is a 4x6+4 addition to the Dilemma range of keyboards.
- Add implementation for the `dilemma_4x6_4` keyboard
- Add basic `default` keymap.
- Add `via` keymap.
- Update `bastardkb/dilemma/readme.md`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-18 18:18 UTC, zvecr commented on keyboards/bastardkb/dilemma/4x6_4/config.h
> +#    define RGB_MATRIX_DEFAULT_HSV RGB_MATRIX_DEFAULT_HUE, RGB_MATRIX_DEFAULT_SAT, RGB_MATRIX_DEFAULT_VAL
```suggestion
```

2023-09-18 18:33 UTC, casuanoob commented
Thanks for the review! I've applied the requested changes.

2023-09-19 00:39 UTC, drashna commented on keyboards/bastardkb/dilemma/4x6_4/config.h
> +#endif
```suggestion
/* RGB matrix support. */
#define SPLIT_TRANSPORT_MIRROR
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

// Startup values.
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 64

// Rainbow swirl as startup mode.
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT

// Slow swirl at startup.
#define RGB_MATRIX_DEFAULT_SPD 32
```

2023-09-19 00:40 UTC, drashna commented on keyboards/bastardkb/dilemma/4x6_4/info.json
> +    },
Mostly a nit, this is easier to read/more compact: 
```suggestion
        "rgb_matrix": true,
        "caps_word": true
    },
```

2023-09-19 02:14 UTC, casuanoob commented
Thanks for the review, @drashna! 
I'm a bit confused at the GitHub status - I've applied all the requested changes verbatim, but the PR is still apparently flagged as "Changes requested", is that just how GitHub PRs work?

2023-09-19 02:20 UTC, drashna commented
> Thanks for the review, @drashna! I'm a bit confused at the GitHub status - I've applied all the requested changes verbatim, but the PR is still apparently flagged as "Changes requested", is that just how GitHub PRs work?

Yup, that's just how github works.  Until the change request/review is dismissed or updated, it shows up as "change requested".

2023-09-19 06:41 UTC, drashna commented on keyboards/bastardkb/dilemma/4x6_4/keymaps/via/keymap.c
> +#ifdef POINTING_DEVICE_ENABLE
Would rather see this using the core code, but isn't a blocker (more of a nitpick).

2023-09-19 06:42 UTC, drashna approved these changes

2023-09-19 08:23 UTC, fauxpark requested changes

2023-09-19 08:23 UTC, fauxpark commented on keyboards/bastardkb/dilemma/readme.md
> +    make bastardkb/dilemma/4x6_4:via:flash
```suggestion
    make bastardkb/dilemma/3x5_3:default
    make bastardkb/dilemma/4x6_4:default

Flashing example for this keyboard:

    make bastardkb/dilemma/3x5_3:default:flash
    make bastardkb/dilemma/4x6_4:default:flash
```

2023-09-19 08:23 UTC, fauxpark commented on keyboards/bastardkb/dilemma/4x6_4/keymaps/default/readme.md
> +> :bulb: Have a look at the [`via` keymap](../via) for a more feature-rich layout.
```suggestion
```

2023-10-01 17:55 UTC, keyboard-magpie approved these changes

2023-10-01 17:55 UTC, merged