Add riot pad
qmk/qmk_firmware pull request #22060
Opened 2023-09-18 01:12 UTC by CheeseL0ver

## Description
Add the RiotPad to QMK. Additionally added both a default and VIA keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-18 09:35 UTC, dunk2k requested changes

2023-09-18 09:35 UTC, dunk2k commented on keyboards/riot_pad/info.json
> +}
1. add community layout
2. EoF added
```suggestion
    },
    "community_layouts": ["ortho_2x3"],
    "layouts": {
        "LAYOUT_ortho_2x3": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [0, 2], "x": 2, "y": 0},
                {"matrix": [1, 0], "x": 0, "y": 1},
                {"matrix": [1, 1], "x": 1, "y": 1},
                {"matrix": [1, 2], "x": 2, "y": 1}
            ]
        }
    }
}

```

2023-09-18 16:25 UTC, waffle87 approved these changes

2023-09-19 00:59 UTC, drashna approved these changes

2023-09-19 01:00 UTC, merged