[keyboard] Add support for Nuxros RE65
qmk/qmk_firmware pull request #22078
Opened 2023-09-19 21:03 UTC by MaiTheSan

## Description

Add support for Nuxros RE65
65%
Rotary encoder
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-19 21:18 UTC, adophoxia requested changes

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/keymaps/default/keymap.c
> +}
```suggestion
#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_PGDN, KC_PGUP) },
    [_FN1] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
};
#endif // ENCODER_MAP_ENABLE
```
More simple to use than with encoder callbacks. Also need a `rules.mk` for this keymap that has `ENCODER_MAP_ENABLE = yes`.

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/keymaps/via/rules.mk
> +LTO_ENABLE = yes
```suggestion

```
No reason to have this since this board is using an RP2040.

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/keymaps/via/keymap.c
> +),
There a reason why only these two "empty" layers only have `QK_BOOT`?

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 6
```suggestion

```
Can be moved into `info.json`

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/info.json
> +    },
```suggestion
    },
    "dynamic_keymap": {
        "layer_count": 6
    },
```

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/info.json
> +        "encoder": true
```suggestion
        "bootmagic": true,
        "mousekey": true,
        "extrakey": true,
        "console": false,
        "command": false,
        "nkro": true,
        "rgblight": true,
        "encoder": true
```

2023-09-19 21:18 UTC, adophoxia commented on keyboards/sawnsprojects/re65/rules.mk
```suggestion
# This file intentionally left blank
```

2023-09-19 22:28 UTC, dunk2k requested changes

2023-09-19 22:28 UTC, dunk2k commented on keyboards/sawnsprojects/re65/info.json
> +        "encoder_map": true
could encoder_map be enabled at keymap level please?
```suggestion
        "encoder": true
```

2023-09-19 22:28 UTC, dunk2k commented on keyboards/sawnsprojects/re65/info.json
> +        "LAYOUT": {
community layout support added
```suggestion
    },
    "community_layouts": ["65_ansi_blocker"],
    "layouts": {
        "LAYOUT_65_ansi_blocker": {
```

2023-09-19 22:28 UTC, dunk2k commented on keyboards/sawnsprojects/re65/keymaps/default/keymap.c
> +[_FN1] = LAYOUT(
```suggestion
 * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬─┬───┼───┼───┤
 * │Ctrl│ Opt│ Cmd│          Space         │Cmd │FnPy│ │Lef│Dow│Rig│
 * └────┴────┴────┴────────────────────────┴────┴────┘ └───┴───┴───┘
 */
[_BASE] = LAYOUT_65_ansi_blocker(
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_PGUP,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGDN,
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_END,
    KC_LCTL, KC_LOPT, KC_LCMD,                            KC_SPC,                    KC_RCMD, MO(_FN1),          KC_LEFT, KC_DOWN, KC_RGHT
),
/* Function Layer
 * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┬───┐
 * │` ~│ F1│ F2│ F3│ F4│ F5│ F6│ F7│ F8│ F9│F10│F11│F12│ Delete│SlD│
 * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┼───┤
 * │RMod │RH+│RS+│RV+│AS+│   │   │   │   │   │F13│F14│F15│ LHP │VlU│
 * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┼───┤
 * │RTgl  │RH-│RS-│RV-│AS-│   │   │   │   │   │   │   │        │VlD│
 * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┬───┼───┤
 * │        │LYR│Thm│   │   │RST│   │Mke│Prv│Nxt│Ply│      │PgU│Mut│
 * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬─┬───┼───┼───┤
 * │    │    │    │                        │    │    │ │Hom│PgD│End│
 * └────┴────┴────┴────────────────────────┴────┴────┘ └───┴───┴───┘
 */
[_FN1] = LAYOUT_65_ansi_blocker(
```

2023-09-19 22:28 UTC, dunk2k commented on keyboards/sawnsprojects/re65/info.json
> +        "hue_steps": 8,
default setting
```suggestion
```

2023-09-19 22:30 UTC, dunk2k commented
@MaiTheSan 
Would you be able to either add to `layouts`, in `info.json`, the QMK Community Layouts this board supports (image in `readme.md` shows `65_ansi_blocker_tsangan`) or provide a `matrix_diagram.md`

2023-09-19 22:47 UTC, waffle87 requested changes

2023-09-19 22:47 UTC, waffle87 commented on keyboards/sawnsprojects/re65/info.json
> +    },
```suggestion
```

2023-09-19 22:47 UTC, waffle87 commented on keyboards/sawnsprojects/re65/info.json
> +        "max_brightness": 255,
```suggestion
```

2023-09-19 23:14 UTC, dunk2k commented on keyboards/sawnsprojects/re65/info.json
> +        "encoder_map": true
Correct 😁

2023-09-20 08:54 UTC, dunk2k requested changes

2023-09-20 08:54 UTC, dunk2k commented on keyboards/sawnsprojects/re65/keymaps/via/keymap.c
> + * └────┴────┴────┴────────────────────────┴────┴────┴─┴───┴───┴───┘
```suggestion
 * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┐
 * │Esc│! 1│@ 2│# 3│$ 4│% 5│^ 6│& 7│* 8│( 9│) 0│_ -│+ =│Bsp│Bsp│Home   │
 * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┼───┤
 * │Tab  │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │{ [│} ]│|   \│PgU│
 * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┼───┤
 * │HyCaps│ A │ S │ D │ F │ G │ H │ J │ K │ L │: ;│" '│   Enter│PgD│
 * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┬───┼───┤
 * │Shift   │ Z │ X │ C │ V │ B │ N │ M │< ,│> .│? /│ Shift│ Up│End│
 * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬─┬───┼───┼───┤
 * │Ctrl│ Opt│ Cmd│          Space         │Cmd │FnPy│ │Lef│Dow│Rig│
 * └────┴────┴────┴────────────────────────┴────┴────┘ └───┴───┴───┘
 */
[_BASE] = LAYOUT_65_ansi_blocker_split_bs(
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_BSPC, KC_HOME,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_PGUP,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGDN,
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_UP,   KC_END,
    KC_LCTL, KC_LOPT, KC_LCMD,                            KC_SPC,                    KC_RCMD, MO(_FN1),          KC_LEFT, KC_DOWN, KC_RGHT
),
/* Function Layer
 * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┐
 * │` ~│ F1│ F2│ F3│ F4│ F5│ F6│ F7│ F8│ F9│F10│F11│F12│Del│   │   │
 * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┼───┤
 * │RMod │RH+│RS+│RV+│AS+│   │   │   │   │   │F13│F14│F15│ LHP │VlU│
 * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┼───┤
 * │RTgl  │RH-│RS-│RV-│AS-│   │   │   │   │   │   │   │        │VlD│
 * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┬───┼───┤
 * │        │LYR│Thm│   │   │RST│   │Mke│Prv│Nxt│Ply│      │PgU│Mut│
 * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬─┬───┼───┼───┤
 * │    │    │    │                        │    │    │ │Hom│PgD│End│
 * └────┴────┴────┴────────────────────────┴────┴────┘ └───┴───┴───┘
```

2023-09-20 08:54 UTC, dunk2k commented on keyboards/sawnsprojects/re65/keymaps/via/keymap.c
> +    _FN3
```suggestion
    _FN2,
    _FN3
non-functional layers removed
```suggestion
    _FN2,
    _FN3
```

2023-09-20 08:54 UTC, dunk2k commented on keyboards/sawnsprojects/re65/keymaps/via/keymap.c
> +),
Non-functional layers/information removed
P.S. 4 is default layer count for VIA
```suggestion
```

2023-09-20 08:54 UTC, dunk2k commented on keyboards/sawnsprojects/re65/keymaps/default/keymap.c
> +*/
non-functional information removed
```suggestion
```

2023-09-20 17:27 UTC, dunk2k requested changes

2023-09-20 17:27 UTC, dunk2k commented on keyboards/sawnsprojects/re65/keymaps/via/keymap.c
> +    [_FN3] = { ENCODER_CCW_CW(RGB_RMOD, RGB_MOD) },
fixes build error
```suggestion
```

2023-09-21 04:57 UTC, drashna approved these changes

2023-11-17 22:31 UTC, dunk2k requested changes

2023-11-21 05:04 UTC, MaiTheSan commented on keyboards/sawnsprojects/re65/info.json
> +    "layouts": {
i almost forgot that, sorry 😓

2023-12-23 08:53 UTC, drashna approved these changes

2023-12-23 23:49 UTC, fauxpark approved these changes

2023-12-24 06:30 UTC, merged