add support for Okayu
qmk/qmk_firmware pull request #22077
Opened 2023-09-19 20:59 UTC by MaiTheSan

## Description

Add QMK support for Okayu
60% 
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-19 22:36 UTC, dunk2k requested changes

2023-09-19 22:36 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/info.json
> +    "layouts": {
could the following QMK Community Layouts be added?:
- `60_tsangan_hhkb`
- `60_hhkb`
- `60_iso`
- `60_iso_split_bs_rshift`
- `60_iso_tsangan`
or a `matrix_disgram.md` provided

2023-09-19 22:44 UTC, waffle87 requested changes

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/halconf.h
> +
These don't seem to be used?
```suggestion
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/rules.mk
> +OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
```suggestion
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/halconf.h
> + */
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/config.h
> +
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/mcuconf.h
> +
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f072/mcuconf.h
> +#define STM32_PWM_USE_TIM3 TRUE
As above.
```suggestion
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f103/config.h
> +
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f103/info.json
> +    "bootloader": "stm32duino"
```suggestion
    "development_board": "bluepill"
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f103/mcuconf.h
> +
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f103/mcuconf.h
> +#define STM32_PWM_USE_TIM3 TRUE
As above.
```suggestion
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f303/config.h
> +
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f303/mcuconf.h
> +
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-09-19 22:44 UTC, waffle87 commented on keyboards/sawnsprojects/okayu/stm32f303/mcuconf.h
> +#define STM32_PWM_USE_TIM3 TRUE
As above.
```suggestion
```

2023-09-20 08:31 UTC, dunk2k requested changes

2023-09-20 08:34 UTC, dunk2k requested changes

2023-09-20 08:34 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/info.json
> +           ],
erroneous comma 
```suggestion
           ]
```

2023-09-20 08:34 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/info.json
> +                {"label": "K4C", "matrix": [4, 12], "x": 12.5, "y": 4},
erroneous comma
```suggestion
                {"label": "K4C", "matrix": [4, 12], "x": 12.5, "y": 4}
```

2023-09-20 08:43 UTC, dunk2k requested changes

2023-09-20 08:43 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/info.json
> +           ]
```suggestion
           ]
        },
        "LAYOUT_60_iso_tsangan_split_bs_rshift": {
            "layout": [
                {"label": "K00", "matrix": [0, 0], "x": 0, "y": 0},
                {"label": "K01", "matrix": [0, 1], "x": 1, "y": 0},
                {"label": "K02", "matrix": [0, 2], "x": 2, "y": 0},
                {"label": "K03", "matrix": [0, 3], "x": 3, "y": 0},
                {"label": "K04", "matrix": [0, 4], "x": 4, "y": 0},
                {"label": "K05", "matrix": [0, 5], "x": 5, "y": 0},
                {"label": "K06", "matrix": [0, 6], "x": 6, "y": 0},
                {"label": "K07", "matrix": [0, 7], "x": 7, "y": 0},
                {"label": "K08", "matrix": [0, 8], "x": 8, "y": 0},
                {"label": "K09", "matrix": [0, 9], "x": 9, "y": 0},
                {"label": "K0A", "matrix": [0, 10], "x": 10, "y": 0},
                {"label": "K0B", "matrix": [0, 11], "x": 11, "y": 0},
                {"label": "K0C", "matrix": [0, 12], "x": 12, "y": 0},
                {"label": "K0D", "matrix": [0, 13], "x": 13, "y": 0},
                {"label": "K2D", "matrix": [2, 13], "x": 14, "y": 0},

                {"label": "K10", "matrix": [1, 0], "x": 0, "y": 1, "w": 1.5},
                {"label": "K11", "matrix": [1, 1], "x": 1.5, "y": 1},
                {"label": "K12", "matrix": [1, 2], "x": 2.5, "y": 1},
                {"label": "K13", "matrix": [1, 3], "x": 3.5, "y": 1},
                {"label": "K14", "matrix": [1, 4], "x": 4.5, "y": 1},
                {"label": "K15", "matrix": [1, 5], "x": 5.5, "y": 1},
                {"label": "K16", "matrix": [1, 6], "x": 6.5, "y": 1},
                {"label": "K17", "matrix": [1, 7], "x": 7.5, "y": 1},
                {"label": "K18", "matrix": [1, 8], "x": 8.5, "y": 1},
                {"label": "K19", "matrix": [1, 9], "x": 9.5, "y": 1},
                {"label": "K1A", "matrix": [1, 10], "x": 10.5, "y": 1},
                {"label": "K1B", "matrix": [1, 11], "x": 11.5, "y": 1},
                {"label": "K1C", "matrix": [1, 12], "x": 12.5, "y": 1},

                {"label": "K20", "matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"label": "K21", "matrix": [2, 1], "x": 1.75, "y": 2},
                {"label": "K22", "matrix": [2, 2], "x": 2.75, "y": 2},
                {"label": "K23", "matrix": [2, 3], "x": 3.75, "y": 2},
                {"label": "K24", "matrix": [2, 4], "x": 4.75, "y": 2},
                {"label": "K25", "matrix": [2, 5], "x": 5.75, "y": 2},
                {"label": "K26", "matrix": [2, 6], "x": 6.75, "y": 2},
                {"label": "K27", "matrix": [2, 7], "x": 7.75, "y": 2},
                {"label": "K28", "matrix": [2, 8], "x": 8.75, "y": 2},
                {"label": "K29", "matrix": [2, 9], "x": 9.75, "y": 2},
                {"label": "K2A", "matrix": [2, 10], "x": 10.75, "y": 2},
                {"label": "K2B", "matrix": [2, 11], "x": 11.75, "y": 2},
                {"label": "K1D", "matrix": [1, 13], "x": 12.75, "y": 2},

                {"label": "K2C", "matrix": [2, 12], "x": 13.75, "y": 1, "w": 1.25, "h": 2},

                {"label": "K30", "matrix": [3, 0], "x": 0, "y": 3, "w": 1.25},
                {"label": "K31", "matrix": [3, 1], "x": 1.25, "y": 3},
                {"label": "K32", "matrix": [3, 2], "x": 2.25, "y": 3},
                {"label": "K33", "matrix": [3, 3], "x": 3.25, "y": 3},
                {"label": "K34", "matrix": [3, 4], "x": 4.25, "y": 3},
                {"label": "K35", "matrix": [3, 5], "x": 5.25, "y": 3},
                {"label": "K36", "matrix": [3, 6], "x": 6.25, "y": 3},
                {"label": "K37", "matrix": [3, 7], "x": 7.25, "y": 3},
                {"label": "K38", "matrix": [3, 8], "x": 8.25, "y": 3},
                {"label": "K39", "matrix": [3, 9], "x": 9.25, "y": 3},
                {"label": "K3A", "matrix": [3, 10], "x": 10.25, "y": 3},
                {"label": "K3B", "matrix": [3, 11], "x": 11.25, "y": 3},
                {"label": "K3C", "matrix": [3, 12], "x": 12.25, "y": 3, "w": 1.75},
                {"label": "K3D", "matrix": [3, 13], "x": 14, "y": 3},
                
                {"label": "K40", "matrix": [4, 0], "x": 0, "y": 4, "w": 1.5},
                {"label": "K41", "matrix": [4, 1], "x": 1.5, "y": 4},
                {"label": "K42", "matrix": [4, 2], "x": 2.5, "y": 4, "w": 1.5},
                {"label": "K46", "matrix": [4, 6], "x": 4, "y": 4, "w": 7},
                {"label": "K4B", "matrix": [4, 11], "x": 11, "y": 4, "w": 1.5},
                {"label": "K4C", "matrix": [4, 12], "x": 12.5, "y": 4},
                {"label": "K4D", "matrix": [4, 13], "x": 13.5, "y": 4, "w": 1.5}
```

2023-09-22 19:16 UTC, dunk2k requested changes

2023-09-22 19:16 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/halconf.h
> +// Copyright 2023 QMK
```suggestion
// Copyright 2023 MaiTheSan (@maithesan)
```

2023-09-22 19:16 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/keymaps/default/keymap.c
> +    _CL
```suggestion
    _CL,
```

2023-09-22 19:16 UTC, dunk2k commented on keyboards/sawnsprojects/okayu/keymaps/via/keymap.c
> +    _CL
```suggestion
    _CL,
```

2023-09-25 04:17 UTC, drashna requested changes

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/info.json
> +        "rgblight": {
just a formatting nit: 
```suggestion
    "rgblight": {
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/default/keymap.c
> +	KC_TAB,  KC_Q,    KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U,  KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC, KC_BSLS,
```suggestion
    KC_TAB,  KC_Q,    KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U,  KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC, KC_BSLS,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/default/keymap.c
> +	_______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```suggestion
    _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/default/keymap.c
> +  	BL_TOGG, BL_UP,    BL_DOWN, BL_STEP, QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```suggestion
    BL_TOGG, BL_UP,    BL_DOWN, BL_STEP, QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/default/keymap.c
> +	_______, _______, _______, EE_CLR,  QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```suggestion
    _______, _______, _______, EE_CLR,  QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/via/keymap.c
> +	KC_TAB,  KC_Q,    KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U,  KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC, KC_BSLS,
```suggestion
    KC_TAB,  KC_Q,    KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U,  KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC, KC_BSLS,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/via/keymap.c
> +  	BL_TOGG, BL_UP,    BL_DOWN, BL_STEP, QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```suggestion
    BL_TOGG, BL_UP,    BL_DOWN, BL_STEP, QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/via/keymap.c
> +	_______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```suggestion
    _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/keymaps/via/keymap.c
> +	_______, _______, _______, EE_CLR,  QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```suggestion
    _______, _______, _______, EE_CLR,  QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______,
```

2023-09-25 04:17 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f072/chconf.h
Are these needed, or just copy-pasted from other boards? 

Eg, remove this if it isn't necessary.

2023-10-04 00:42 UTC, drashna requested changes

2023-10-04 00:42 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f072/config.h
> +#define WS2812_SPI_SCK_PAL_MODE 5 // SCK pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 5
```suggestion
#define WS2812_SPI SPID1
#define WS2812_SPI_MOSI_PAL_MODE 5
#define WS2812_SPI_SCK_PIN B13
#define WS2812_SPI_SCK_PAL_MODE 5
```

2023-10-04 00:42 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f103/config.h
> +#define WS2812_SPI_SCK_PAL_MODE 5 // SCK pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 5
```suggestion
#define WS2812_SPI SPID2
#define WS2812_SPI_MOSI_PAL_MODE 5 
#define WS2812_SPI_SCK_PIN B13
#define WS2812_SPI_SCK_PAL_MODE 5
```

2023-10-04 00:42 UTC, drashna commented on keyboards/sawnsprojects/okayu/stm32f303/config.h
> +#define WS2812_SPI_SCK_PAL_MODE 5 // SCK pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 5
```suggestion
#define WS2812_SPI SPID1
#define WS2812_SPI_MOSI_PAL_MODE 5
#define WS2812_SPI_SCK_PIN B13
#define WS2812_SPI_SCK_PAL_MODE 5
```

2023-10-12 06:55 UTC, drashna approved these changes

2023-10-13 07:53 UTC, merged