Add the Split67 keyboard PCB to QMK
qmk/qmk_firmware pull request #22107
Opened 2023-09-22 10:16 UTC by LXF-YZP

## Description
Add the Brutal v2 60 keyboard PCB to QMK.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-22 15:07 UTC, LXF-YZP commented on keyboards/split67/info.json
The layout is different from the picture, because this layout was specially made in order to save Promicro stitches when making the pcb.

2023-09-22 15:16 UTC, LXF-YZP commented on keyboards/split67/readme.md
> +![split67](https://imgur.com/s1WYDy6.jpg)
Reuploaded the picture of the assembled keyboard，Thank you very much.

2023-09-22 15:59 UTC, LXF-YZP commented on keyboards/split67/keymaps/via/config.h
Suggestions received, thank you very much

2023-09-23 00:33 UTC, drashna requested changes

2023-09-23 00:33 UTC, drashna commented on keyboards/split67/keymaps/default/keymap.c
> +};
```suggestion
    [0] = LAYOUT(
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,               KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_INS,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,             KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC,   KC_BSLS,
         KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G,            KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_DEL,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,               KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, MO(1), KC_6,     KC_SPC, KC_RCTL, KC_RALT, KC_LEFT, KC_DOWN, KC_RGHT),

    [1] = LAYOUT(
        KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,  KC_F7,KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_BSPC, KC_INS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,
         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_LGUI, KC_TRNS, KC_SPC, KC_TRNS,   KC_F6,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
```

2023-09-23 00:33 UTC, drashna commented on keyboards/split67/keymaps/via/keymap.c
> +};
```suggestion
[0] = LAYOUT(
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,     KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_INS,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,      KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC,   KC_BSLS,
         KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G,     KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_DEL,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,     KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, MO(1), KC_6,     KC_SPC, KC_RCTL, KC_RALT, KC_LEFT, KC_DOWN, KC_RGHT),

  /* Keymap Fn Layer
   * .-----------------------------------.     .---------------------------------------------------.
   * |   |  F1 |  F2 |   F3  | F4  | F5  |     |  F7  |  F8  | F9 |  F10 |  F11 |   F12   |     |  |
   * |-----------------------------------|     |---------------------------------------------------|
   * |   |     |     |       |     |     |     |      |      |    |      |      |         |     |  |
   * |-----------------------------------|     | --------------------------------------------------|
   * |   |     |     |       |     |     |     |      |      |    |      |      |         |     |  |
   * |-----------------------------------|     |---------------------------------------------------|
   * |   |     |     |       |     |     |     |      |      |    |      |      |         |     |  |
   * |-----------------------------------|     |---------------------------------------------------|
   * |   |     |     |       |     | F6  |     |      |      |    |      |      |         |     |  |
   * .-----------------------------------.     .---------------------------------------------------.
   */
[1] = LAYOUT(
    KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_BSPC, KC_INS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,
         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_LGUI, KC_TRNS, KC_SPC, KC_TRNS,  KC_TRNS,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
```

2023-09-23 00:33 UTC, drashna commented on keyboards/split67/readme.md
> +* Hardware Supported: Pro Micro, (ATmega32u4)
```suggestion
# split67

![split67](https://imgur.com/2eC03Sm.jpg)

A 65% keys split keyboard.

* Keyboard Maintainer: https://github.com/LXF-YZP
* Hardware Supported: Pro Micro, (ATmega32u4)

Make example for this keyboard (after setting up your build environment):

    make split67:default

Flashing example for this keyboard:

    make split67:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available

2023-09-25 04:19 UTC, drashna commented on keyboards/split67/keymaps/default/keymap.c
> +};
```suggestion
    [0] = LAYOUT(
        KC_ESC,  KC_1,    KC_2,    KC_3,   KC_4,  KC_5,           KC_7,   KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,   KC_BSPC,   KC_INS,
        KC_TAB,  KC_Q,    KC_W,    KC_E,   KC_R,  KC_T,           KC_Y,   KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC,  KC_BSLS,
        KC_CAPS, KC_A,    KC_S,    KC_D,   KC_F,  KC_G,           KC_H,   KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,  KC_ENT,   KC_DEL,
        KC_LSFT, KC_Z,    KC_X,    KC_C,   KC_V,  KC_B,           KC_N,   KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,  KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, MO(1), KC_6,           KC_SPC, KC_RCTL, KC_RALT, KC_LEFT, KC_DOWN, KC_RGHT),

    [1] = LAYOUT(
        KC_TRNS, KC_F1,   KC_F2,   KC_F3,   KC_F4,    KC_F5,     KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_BSPC, KC_INS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_LGUI, KC_TRNS, KC_SPC,  KC_TRNS,  KC_F6,     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
```

2023-09-25 04:20 UTC, drashna commented on keyboards/split67/keymaps/via/keymap.c
> +};
```suggestion
        KC_TRNS, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_BSPC, KC_INS,
          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
          KC_TRNS, KC_LGUI, KC_TRNS, KC_SPC,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
```

2023-09-25 04:22 UTC, drashna commented on keyboards/split67/readme.md
> +* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```suggestion
# split67

![split67](https://imgur.com/2eC03Sm.jpg)

A 65% keys split keyboard.

* Keyboard Maintainer: https://github.com/LXF-YZP
* Hardware Supported: Pro Micro, (ATmega32u4)

Make example for this keyboard (after setting up your build environment):

    make split67:default

Flashing example for this keyboard:

    make split67:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-09-25 08:43 UTC, dunk2k requested changes

2023-09-25 08:43 UTC, dunk2k commented on keyboards/split67/readme.md
> +![split67](https://imgur.com/2eC03Sm.jpg)
```suggestion
![split67](https://imgur.com/2eC03Smh.jpg)
```

2023-09-26 01:23 UTC, drashna commented on keyboards/split67/keymaps/default/keymap.c
Could you replace all of the tabs with spaces, per the coding convention

2023-09-26 01:23 UTC, drashna commented on keyboards/split67/keymaps/via/keymap.c
Could you replace all of the tabs with spaces, per the coding convention

2023-09-26 01:50 UTC, LXF-YZP commented on keyboards/split67/keymaps/via/keymap.c
Thank you very much

2023-09-26 01:50 UTC, LXF-YZP commented on keyboards/split67/keymaps/default/keymap.c
Thank you very much

2023-09-30 08:01 UTC, drashna commented on keyboards/split67/keymaps/via/config.h
The dynamic keymap layer count is set in the info.json, so this file isn't needed and can/should be removed.

2023-09-30 08:01 UTC, drashna commented on keyboards/split67/readme.md
> +![split67](https://imgur.com/2eC03Smh.jpg)
```suggestion
![split67](https://i.imgur.com/2eC03Smh.jpg)
```

2023-09-30 09:59 UTC, LXF-YZP commented on keyboards/split67/keymaps/via/config.h
thanks

2023-09-30 15:23 UTC, LXF-YZP commented on keyboards/split67/info.json
> +        "layer_count": 2
thanks

2023-09-30 15:28 UTC, LXF-YZP commented on keyboards/split67/info.json
> +                {"matrix": [5, 0], "x": 9, "y": 0},
Sorry for the trouble

2023-09-30 15:57 UTC, LXF-YZP commented on keyboards/split67/info.json
> +                {"matrix": [5, 0], "x": 9, "y": 0},
Thank you. Do I see what that means

2023-09-30 16:12 UTC, LXF-YZP commented on keyboards/split67/info.json
> +                {"matrix": [5, 0], "x": 9, "y": 0},
> > Sorry for the trouble
> 
> No need to apologize, but the key is still out of place. The `x` and `y` positions describe the physical location. So it should be `"x": 6, "y": 0`, not `"x": 7, "y": 4`. Please try running `qmk info -m -kb split67` to see how it looks.

Thanks, first pr learned a lot of knowledge.

2023-10-01 01:30 UTC, drashna approved these changes

2023-10-04 04:02 UTC, drashna approved these changes

2023-10-04 04:02 UTC, merged