adding fuji75 pcb support
qmk/qmk_firmware pull request #22158
Opened 2023-09-28 13:54 UTC by CMMS-Freather

adding fuji75 pcb support
includes
solder
hotswap

## Description
adding fuji75 pcb support
includes
solder
hotswap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-28 14:54 UTC, zvecr requested changes

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/solder/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/hotswap/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/solder/readme.md
> +
```suggestion
```

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/hotswap/readme.md
> +
```suggestion
# Fuji75 Hotswap

![Fuji75 hotswap](https://i.imgur.com/SfucJxa.png)
```

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/config.h
> +// Copyright 2023 CMM.S Freather
This file should be removed

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/info.json
> +        "sleep": true,
```suggestion
       "layers": {
             "enabled": true
        },
        "sleep": true,
```

2023-09-28 14:54 UTC, zvecr commented on keyboards/sakura_workshop/fuji75/fuji75.c
> +}
`_user` functions at the keyboard level is invalid.

```suggestion
void keyboard_post_init_kb(void) {
  rgblight_layers = my_rgb_layers;
  
  keyboard_post_init_user();
}

bool led_update_kb(led_t led_state) {
    bool res = led_update_user(led_state);
    if(res) {
        rgblight_set_layer_state(0, led_state.caps_lock);
        rgblight_set_layer_state(1, !led_state.caps_lock);
    }
    return res;
}
```

2023-10-02 00:00 UTC, drashna commented on keyboards/sakura_workshop/fuji75/hotswap/readme.md
> +![Fuji75 hotswap](https://i.imgur.com/SfucJxa.png)
```suggestion
![Fuji75 hotswap](https://i.imgur.com/SfucJxah.png)
```

2023-10-02 00:00 UTC, drashna commented on keyboards/sakura_workshop/fuji75/solder/readme.md
> +![Fuji75 Solder](https://i.imgur.com/tv6YdWt.png)
```suggestion
![Fuji75 Solder](https://i.imgur.com/tv6YdWth.png)
```

2023-10-22 15:35 UTC, CMMS-Freather commented
@zvecr @drashna bump

2023-10-27 08:20 UTC, drashna approved these changes

2023-12-08 07:23 UTC, CMMS-Freather commented
@drashna would you mind look again if it can be merged? it has been a while

2023-12-13 18:38 UTC, CMMS-Freather commented on keyboards/sakura_workshop/fuji75/hotswap/info.json
updated

2023-12-13 18:38 UTC, CMMS-Freather commented on keyboards/sakura_workshop/fuji75/solder/info.json
updated

2023-12-14 01:50 UTC, fauxpark approved these changes

2023-12-14 07:40 UTC, waffle87 approved these changes

2023-12-14 07:41 UTC, merged