layouts: dvorak_emacs: Add missing keys, caps word, improve LEDs.
qmk/qmk_firmware pull request #22175
Opened 2023-10-01 13:08 UTC by Apteryks

The following changes are made:

- Enable caps word feature
- Add the `, CAPS, SCRL, INS keyn as well as L1 toggles to the base layer
- Add Mute, Bright+, Bright-, Prev, Next, Stop and Play to the AUX layer
- Wire LED 2 and 3 to caps word and scroll lock (previously unused)
- Use PERMISSIVE_HOLD strategy, to reduce errors at high typing speed
- Remove some obsolete/dead code such as KEY_TAP_FAST/KEY_TAP_SLOW

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python) (clang-formatted)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-16 16:58 UTC, waffle87 requested changes

2023-11-16 16:58 UTC, waffle87 commented on layouts/community/ergodox/dvorak_emacs_software/keymap.c
> +#define AUX 1  // auxiliary keys
```suggestion
enum layers {
    BASE, // dvorak layout (default)
    AUX   // auxiliary keys
};
```

2023-11-16 16:58 UTC, waffle87 commented on layouts/community/ergodox/dvorak_emacs_software/config.h
This file is missing a license header.

2023-11-16 16:58 UTC, waffle87 commented on layouts/community/ergodox/dvorak_emacs/keymap.c
> +#define AUX 1  // auxiliary keys
```suggestion
enum layers {
    BASE, // dvorak layout (default)
    AUX   // auxiliary keys
};
```

2023-11-16 16:58 UTC, waffle87 commented on layouts/community/ergodox/dvorak_emacs/config.h
This file is missing a license header.

2024-02-01 01:49 UTC, closed without merging

2024-05-19 01:34 UTC, Apteryks commented on layouts/community/ergodox/dvorak_emacs_software/config.h
Added.

2024-05-19 01:34 UTC, Apteryks commented on layouts/community/ergodox/dvorak_emacs/config.h
Add SPDX + copyright.

2024-05-19 01:43 UTC, Apteryks commented on layouts/community/ergodox/dvorak_emacs/keymap.c
> +#define AUX 1  // auxiliary keys
Done! Thanks for the review.

2024-05-19 01:53 UTC, Apteryks commented
@waffle87 I've reopened a new PR here with your suggested changes implemented: https://github.com/qmk/qmk_firmware/pull/23741