Add Line TKL keyboard.
qmk/qmk_firmware pull request #22172
Opened 2023-09-30 18:37 UTC by studiokestra

## Description

Add support for LINE FRIENDS TKL PCB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-09-30 19:32 UTC, dunk2k requested changes

2023-09-30 19:32 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/info.json
> +        "LAYOUT": {
could a layout with 2u Backspace and 2.75u Right shift (`LAYOUT_tkl_ansi_tsangan`) be added?

2023-09-30 19:32 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/keymaps/default/keymap.c
> +    [1] = LAYOUT(
```suggestion
    [0] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,                         KC_PSCR, KC_SCRL, KC_PAUS,
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_BSPC,     KC_INS,  KC_HOME, KC_PGUP,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,               KC_DEL,  KC_END,  KC_PGDN,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,     
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),                                   KC_UP,          
    KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT, KC_RGUI, KC_RCTL,                        KC_LEFT, KC_DOWN, KC_RIGHT ),

    [1] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
```

2023-09-30 19:32 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/keymaps/via/keymap.c
> +    [1] = LAYOUT(
```suggestion
    [0] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
    KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,                         KC_PSCR, KC_SCRL, KC_PAUS,
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,  KC_BSPC,     KC_INS,  KC_HOME, KC_PGUP,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,               KC_DEL,  KC_END,  KC_PGDN,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,     
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),                                   KC_UP,          
    KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT, KC_RGUI, KC_RCTL,                        KC_LEFT, KC_DOWN, KC_RIGHT ),

    [1] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
```

2023-09-30 19:32 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/info.json
> +        "LAYOUT": {
```suggestion
    },
    "community_layouts": ["tkl_ansi_tsangan_split_bs_rshift"],
    "layouts": {
        "LAYOUT_tkl_ansi_tsangan_split_bs_rshift": {
```

2023-09-30 23:14 UTC, studiokestra commented
Added tkl_ansi_tsangan layout and set to default. added split_bs_rshift layout

2023-10-01 08:27 UTC, dunk2k requested changes

2023-10-01 08:27 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/info.json
> +
tidy
```suggestion
    "community_layouts": [
        "tkl_ansi_tsangan",
        "tkl_ansi_tsangan_split_bs_rshift"
    ],
    "layouts": {
        "LAYOUT_tkl_ansi_tsangan": {
            "layout": [
```

2023-10-01 08:27 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/info.json
> +
tidy
```suggestion
```

2023-10-01 08:27 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/info.json
> +}
add EoF
```suggestion
}

```

2023-10-01 08:27 UTC, dunk2k commented on keyboards/studiokestra/line_tkl/config.h
> +#define LOCKING_RESYNC_ENABLE
add EoF
```suggestion
#define LOCKING_RESYNC_ENABLE

```

2023-10-01 21:21 UTC, drashna approved these changes

2023-10-05 04:53 UTC, drashna approved these changes

2023-10-05 04:53 UTC, merged