Add kelwin465 and utopia88 keyboard pcb
qmk/qmk_firmware pull request #22197
Opened 2023-10-03 18:35 UTC by Kelwin0313

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-03 23:54 UTC, waffle87 requested changes

2023-10-03 23:54 UTC, waffle87 commented on keyboards/kelwin/utopia88/readme.md
> +![Utopia88](https://imgur.com/pRKQIIH.jpeg)
```suggestion
![Utopia88](https://i.imgur.com/pRKQIIHh.jpeg)
```

2023-10-03 23:54 UTC, waffle87 commented on keyboards/kelwin/utopia88/info.json
Please run `qmk format-json` on this file.

2023-10-04 00:22 UTC, drashna requested changes

2023-10-04 00:22 UTC, drashna commented on keyboards/kelwin/utopia88/readme.md
> +    make kelwin\utopia88:default:flash
```suggestion
    make kelwin/utopia88:default

Flashing example for this keyboard:

    make kelwin/utopia88:default:flash
```

2023-10-04 08:55 UTC, dunk2k requested changes

2023-10-04 08:55 UTC, dunk2k commented on keyboards/kelwin/utopia88/info.json
> +        "LAYOUT": {
```suggestion
    },
    "community_layouts": ["tkl_f13_ansi_tsangan"],                                                                                                                                                                                                                                                                                                                       
    "layouts": {                                                                                                                                                                                                                                                                                                             
        "LAYOUT_tkl_f13_ansi_tsangan": {                                                                                                                                                                                                                                                                                                      
```

2023-10-04 08:55 UTC, dunk2k commented on keyboards/kelwin/utopia88/keymaps/default/keymap.c
> +	[0] = LAYOUT(
```suggestion
	[0] = LAYOUT_tkl_f13_ansi_tsangan(
```

2023-10-04 08:55 UTC, dunk2k commented on keyboards/kelwin/utopia88/keymaps/via/keymap.c
> +	[0] = LAYOUT(
```suggestion
	[0] = LAYOUT_tkl_f13_ansi_tsangan(
```

2023-10-04 08:55 UTC, dunk2k commented on keyboards/kelwin/utopia88/readme.md
> +![Utopia88](https://i.imgur.com/pRKQIIH.jpeg)
```suggestion
![Utopia88](https://i.imgur.com/pRKQIIHh.jpeg)
```

2023-10-04 08:55 UTC, dunk2k commented on keyboards/kelwin/utopia88/info.json
> +        "device_version": "0.0.1",
```suggestion
        "device_version": "1.0.0",                                                                                                                                                                                                                                                                                           
```

2023-10-04 08:55 UTC, dunk2k commented on keyboards/kelwin/utopia88/info.json
> +}
```suggestion
}

```

2023-10-04 16:11 UTC, closed without merging