Emit neutralizer in clear_active_override()
qmk/qmk_firmware pull request #22209
Opened 2023-10-05 17:00 UTC by iQuerz

## Description
I've tried to emit the neutralizer in the `clear_active_override()` function, but I'd like a suggestion, where should I pull the `active_mods` from? Is this a good general direction for this issue? I confirmed that this code here works 100%, but it will be sending not needed neutralizers here and there because we are not passing `active_mods`, but `active_trigger->trigger_mods` to the `neutralize_flashing_modifiers` function. Should we require `active_mods` as an argument to the `clear_active_override()` function? @precondition @sigprof 

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #22208 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-05 19:41 UTC, sigprof commented
The modifier state that we care about is the current state, that could be reconstructed by something like
```c
    uint8_t active_mods = get_mods | get_weak_mods();
#ifndef NO_ACTION_ONESHOT
    active_mods |= get_oneshot_locked_mods() | get_oneshot_mods();
#endif
```
(`process_key_override()` has some similar code, where `get_weak_mods()` is wrapped inside `#ifdef KEY_OVERRIDE_INCLUDE_WEAK_MODS`, but here we should probably consider weak mods too, because that's what would be sent to the host.)

However, this could still result in some superfluous neutralizer taps:

1. Even if the problematic modifier is active, it should not cause any problem if it's not included in `override->suppressed_mods` (if the modifier is not suppressed, it won't actually be released when activating the override, and won't be pressed again when deactivating the override).  Although that's some unusual use case that might not be worth optimizing.
   (This actually affects the existing `neutralize_flashing_modifiers(active_mods)` call in `try_activating_override()` too.)
2. There is the `clear_active_override(false)` call in `try_activating_override()` just before `neutralize_flashing_modifiers(active_mods)`; if it's possible to directly go from one override into another, this would probably result in a duplicate neutralizer tap.  Again, that use case might not be forth optimizing (and if the neutralizer key is chosen properly, the extra tap won't really matter apart from some extra time to send that tap).

2023-10-06 04:58 UTC, drashna requested changes

2023-10-06 04:58 UTC, drashna commented on quantum/process_keycode/process_key_override.c
> +	neutralize_flashing_modifiers(active_override->trigger_mods);
```suggestion
    // Tap dummy mod neutralizer again after reregistering mod key
    neutralize_flashing_modifiers(active_override->trigger_mods);
```

2024-01-22 22:15 UTC, iQuerz commented
I will re-open the PR when I get some time on my hands(probably in 2-4 weeks). I am working and studying at the same time and it's exam season so I don't do much of my hobbies

2024-04-08 01:48 UTC, closed without merging