New RGB Animations - 4 "Starlight" Animation Variations
qmk/qmk_firmware pull request #22212
Opened 2023-10-06 00:02 UTC by bactaholic

## Description

This PR contains 4 animations which do similar things, named Starlight, Starlight Smooth, Starlight Dual Hue, and Starlight Dual Sat. The first two being the main objective I set out to do, the latter two being consequences of testing that I found interesting. 

Starlight - Randomly sets hsv.v value to appear as twinkling lights in the night sky, hence "Starlight"
Starlight Smooth - This one looks similar but it smoothly transitions between brightness levels. Its actually accomplished by offsetting the breathing animation to such an extent that it seems keys to randomly increase/decrease in brightness, smoothly
Starlight Dual Hue - Same thing as Starlight, but it also randomly adjusts the hsv.h value by + or - 30
Starlight Dual Sat - Same as Dual Hue, but it adjusts hsv.s value by + or - 30

I started making these several years ago, there is a reddit post with the early attempts and I was encouraged by Drashna to create a PR for them but I wasn't quite happy with them. I ended up taking a break from them which lasted longer then expected, but came back these last few days determined to finish. Hopefully there is still interest.

## Types of Changes

- [x ] New feature

## Issues Fixed or Closed by This PR

N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [maybe?] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-14 09:21 UTC, drashna commented
Could you add the animations to the rgb matrix doc? 
https://github.com/qmk/qmk_firmware/blob/master/docs/feature_rgb_matrix.md

2023-10-17 17:01 UTC, bactaholic commented
> Could you add the animations to the rgb matrix doc? 
> https://github.com/qmk/qmk_firmware/blob/master/docs/feature_rgb_matrix.md
> 
> 

Howdy! Sure thing, sorry for the delay. I'll get the docs updated today.

2023-10-17 22:45 UTC, bactaholic commented
@drashna docs have been updated, renamed Starlight Smooth to Riverflow as it looks more like water flowing than it does like the Starlight animations but smooth, will continue to try and perfect the Starlight Smooth animation. Riverflow looks really nice though so I didn't wanna delete it.

2023-10-22 09:02 UTC, drashna approved these changes

2023-10-22 15:46 UTC, zvecr requested changes

2023-10-22 15:46 UTC, zvecr commented on quantum/rgb_matrix/animations/starlight_smooth_anim.h
> renamed Starlight Smooth to Riverflow

This file should be removed? As its not included in effects.inc.

2023-11-02 22:48 UTC, bactaholic commented on quantum/rgb_matrix/animations/starlight_smooth_anim.h
@zvecr sorry for the delayed reply, got a lot going on in my personal life and had to take a break from my projects. I've removed this file from the PR, should be good to go.

2023-11-26 12:07 UTC, tzarc approved these changes

2023-11-26 12:07 UTC, merged