Add new Keyboard Primer61's setting PR
qmk/qmk_firmware pull request #22249
Opened 2023-10-11 06:41 UTC by marby3

## Description
This is firmware for a simple 60% keyboard using ProMicro.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-11 07:16 UTC, drashna requested changes

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/config.h
> +#define MATRIX_ROW_PINS { C6, D7, E6, B4, B5 }
```suggestion
```

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/info.json
> +    "processor": "atmega32u4",
```suggestion
    "matrix_pins": {
        "cols": ["F4", "F5", "F6", "F7", "B1", "B3", "B2"],
        "rows": ["C6", "D7", "E6", "B4", "B5"]
    },
    "development_board": "promicro",
```

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/info.json
> +    "bootloader": "caterina",
```suggestion
```

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/info.json
> +        "vid": "0x3265",
Vendor ID appears to check out. 
https://www.the-sz.com/products/usbid/index.php?v=0x3265&p=&n=

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/keymaps/VIA/config.h
This file can be removed.  4 is the default, so this doesn't need to be set, and nothing else here means that it can be removed.

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/keymaps/VIA/keymap.c
> +    )
Unpopulated layers can be removed, as they will be automatically replaced with transparency, by default. 
```suggestion
```

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/keymaps/VIA/keymap.c
please rename this folder to be all lower case. 

You may need to rename it to something else, commit, and then rename it to `via` and commit again.

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/keymaps/default/keymap.c
> +    )
```suggestion
```

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/readme.md
> +![primer61](https://drive.google.com/uc?export=view&id=14yIqf5XfCR3nu6v57iXRixEVLnlZrEVY)
Please rehost this image on Imgur, or the like.

2023-10-11 07:16 UTC, drashna commented on keyboards/yushakobo/primer61/rules.mk
> +# This file intentionally left blank
```suggestion
```

2023-10-11 07:48 UTC, dunk2k requested changes

2023-10-11 07:48 UTC, dunk2k commented on keyboards/yushakobo/primer61/info.json
> +        "LAYOUT": {
```suggestion
    },
    "community_layouts": ["60_ansi"],
    "layouts": {
        "LAYOUT_60_ansi": {
```

2023-10-11 07:48 UTC, dunk2k commented on keyboards/yushakobo/primer61/keymaps/VIA/keymap.c
> +    [1] = LAYOUT(
```suggestion
    [0] = LAYOUT_60_ansi(
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
        KC_LCTL, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,          KC_RSFT,
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT, KC_LGUI, MO(1),   KC_RCTL
    ),
    [1] = LAYOUT_60_ansi(
```

2023-10-11 07:48 UTC, dunk2k commented on keyboards/yushakobo/primer61/keymaps/default/keymap.c
> +    [1] = LAYOUT(
```suggestion
    [0] = LAYOUT_60_ansi(
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
        KC_LCTL, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,          KC_RSFT,
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                             KC_RALT, KC_LGUI, MO(1),   KC_RCTL
    ),
    [1] = LAYOUT_60_ansi(
```

2023-10-11 07:48 UTC, dunk2k commented on keyboards/yushakobo/primer61/keymaps/VIA/rules.mk
> +
```suggestion
```

2023-10-11 11:01 UTC, dunk2k requested changes

2023-10-11 11:01 UTC, dunk2k commented on keyboards/yushakobo/primer61/readme.md
> +![primer61](https://imgur.com/a/AtEjG6h)
```suggestion
![primer61](https://i.imgur.com/nU35TG7h.jpeg)
```

2023-12-12 09:18 UTC, drashna requested changes

2023-12-12 09:18 UTC, drashna commented on keyboards/yushakobo/primer61/config.h
This file can be deleted.  the matrix col/row size is inferred by the pins (and split kb being enabled). And the locking support can be moved to info.json (`qmk migrate` or `qmk info -kb (name) -f json` can help with that)

2023-12-12 09:18 UTC, drashna commented on keyboards/yushakobo/primer61/matrix.c
could you run a format pass on this file?  `qmk format-c` can/will help with that.

2024-02-28 01:48 UTC, closed without merging