Add PCB Utopia88
qmk/qmk_firmware pull request #22257
Opened 2023-10-12 13:20 UTC by Kelwin0313

Add PCB Utopia88

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-12 13:50 UTC, zvecr commented
Why have you opened yet another PR?

2023-10-12 14:23 UTC, zvecr commented
Please stop! It makes the review process much harder than it needs to be. Repeated closing and reopening as you have done many many times is likely to get you blocked from submitting PRs.

2023-10-12 14:45 UTC, Kelwin0313 commented
@zvecr I will keep everything in this PR. I understand my client has submitted like 4PRs before hiring me to deal with the PR. Sorry for that.

2023-11-01 19:51 UTC, dunk2k requested changes

2023-11-01 19:51 UTC, dunk2k commented on keyboards/kelwin/utopia88/info.json
> +
```suggestion

```

2023-11-01 19:51 UTC, dunk2k commented on keyboards/kelwin/utopia88/info.json
please run, qmk CLI command, `qmk format-json` against this file

2023-11-08 09:12 UTC, drashna approved these changes

2023-11-08 09:58 UTC, fauxpark approved these changes

2023-11-08 17:40 UTC, waffle87 approved these changes

2023-11-08 17:40 UTC, merged