Add riblee handwired split keyboard
qmk/qmk_firmware pull request #22277
Opened 2023-10-15 10:16 UTC by riblee

## Description

This PR adds support for a handwired 12X5 split keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-15 19:45 UTC, dunk2k requested changes

2023-10-15 19:45 UTC, dunk2k commented on keyboards/handwired/riblee_split/info.json
> +    "processor": "STM32F411",
`processor` defined by `development_board`
```suggestion
```

2023-10-15 19:45 UTC, dunk2k commented on keyboards/handwired/riblee_split/info.json
> +    },
```suggestion
    },
    "community_layouts": ["ortho_5x12"],
```

2023-10-15 19:45 UTC, dunk2k commented on keyboards/handwired/riblee_split/info.json
> +}
add EoF
```suggestion
}

```

2023-10-15 19:45 UTC, dunk2k commented on keyboards/handwired/riblee_split/halconf.h
> +#include_next <halconf.h>
add EOF
```suggestion
#include_next <halconf.h>

```

2023-10-15 19:45 UTC, dunk2k commented on keyboards/handwired/riblee_split/mcuconf.h
> +#define STM32_SERIAL_USE_USART1 TRUE
add EoF
```suggestion
#define STM32_SERIAL_USE_USART1 TRUE

```

2023-10-15 19:45 UTC, dunk2k commented on keyboards/handwired/riblee_split/rules.mk
> +SERIAL_DRIVER = usart
add EoF
```suggestion
SERIAL_DRIVER = usart

```

2023-10-27 08:02 UTC, drashna approved these changes

2023-10-27 08:22 UTC, fauxpark approved these changes

2023-11-08 08:31 UTC, merged