Fix Layout_ALL in info.json
qmk/qmk_firmware pull request #22317
Opened 2023-10-22 14:42 UTC by yakMM

Herringbone pro have several problems in `info.json`:

- The left and right arrow keys are missing in the LAYOUT_all layout (visible in QMK configurator for example), instead, two keys are present next to the encoder with weird matrix ids. LAYOUT_ansi and LAYOUT_iso are fine.
- The encoder is not using the right resolution by default

2023-10-22 19:57 UTC, dunk2k requested changes

2023-10-22 19:57 UTC, dunk2k commented on keyboards/rmi_kb/herringbone/pro/info.json
>                  {"matrix": [0, 14], "x": 16.25, "y": 0},
```suggestion
                {"matrix": [0, 14], "x": 15.5, "y": 0},
```

2023-10-26 09:28 UTC, dunk2k approved these changes

2023-11-08 09:13 UTC, drashna approved these changes

2023-11-08 09:57 UTC, fauxpark approved these changes

2023-11-08 17:42 UTC, waffle87 approved these changes

2023-11-08 17:42 UTC, merged