add pisces pcb
qmk/qmk_firmware pull request #22334
Opened 2023-10-25 09:45 UTC by khchen2004

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-25 11:50 UTC, dunk2k requested changes

2023-10-25 11:50 UTC, dunk2k commented on keyboards/kwstudio/pisces/readme.md
> +![Pisces](https://i.imgur.com/fqEBVD8.jpeg)
```suggestion
![Pisces](https://i.imgur.com/fqEBVD8h.jpeg)
```

2023-10-25 11:50 UTC, dunk2k commented on keyboards/kwstudio/pisces/info.json
> +
```suggestion

```

2023-10-25 11:50 UTC, dunk2k commented on keyboards/kwstudio/pisces/readme.md
> +* Hardware Supported: Pisces PCBs, atmega32u4
```suggestion
* Hardware Supported: Pisces PCB
```

2023-10-25 12:59 UTC, dunk2k requested changes

2023-10-25 12:59 UTC, dunk2k commented on keyboards/kwstudio/pisces/info.json
> +}
```suggestion
}

```

2023-10-25 12:59 UTC, dunk2k commented on keyboards/kwstudio/pisces/readme.md
> +
```suggestion
```

2023-10-25 13:47 UTC, dunk2k approved these changes

2023-10-25 14:29 UTC, khchen2004 commented
@dunk2k updated

2023-10-25 23:05 UTC, waffle87 commented on keyboards/kwstudio/pisces/info.json
> +        "mousekey": false,
This is preferred to be left enabled if possible.
```suggestion
        "mousekey": true,
```

2023-10-27 04:25 UTC, waffle87 approved these changes

2023-10-27 04:30 UTC, fauxpark approved these changes

2023-10-27 06:38 UTC, drashna approved these changes

2023-10-27 06:38 UTC, merged

2023-10-27 06:39 UTC, drashna commented
Thanks!

For future reference, we recommend against committing to your `master` branch as you've done here, because pull requests from modified `master` branches can make it more difficult to keep your QMK fork updated. It is highly recommended for QMK development – regardless of what is being done or where – to keep your master updated, but **NEVER** commit to it. Instead, do all your changes in a branch (branches are basically free in Git) and issue PRs from your branches when you're developing.

There are instructions on how to keep your fork updated here:

[**Best Practices: Your Fork's Master: Update Often, Commit Never**](https://docs.qmk.fm/#/newbs_git_using_your_master_branch)

[Fixing Your Branch](https://docs.qmk.fm/#/newbs_git_resynchronize_a_branch) will walk you through fixing up your `master` branch moving forward. If you need any help with this just ask.

Thanks for contributing!