add enter67_pcb
qmk/qmk_firmware pull request #22346
Opened 2023-10-27 08:51 UTC by LXF-YZP

## Description

Add a 67 layout pcb

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-27 14:36 UTC, dunk2k requested changes

2023-10-27 14:36 UTC, dunk2k commented on keyboards/enter67/keymaps/via/keymap.c
> +
```suggestion
[0] = LAYOUT_65_ansi_blocker(
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_HOME,
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_END,
    KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,  KC_PGUP,
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,          KC_UP,   KC_PGDN,
    KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                    MO(1),   KC_RCTL,          KC_LEFT, KC_DOWN, KC_RGHT),
[1] = LAYOUT_65_ansi_blocker(
    KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                   KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS),
```

2023-10-27 16:31 UTC, LXF-YZP commented on keyboards/enter67/info.json
> +}
I executed the command "qmk format-json info.json " ，Please accept my heartfelt thanks.

2023-10-27 18:36 UTC, waffle87 commented on keyboards/enter67/config.h
This file should be removed.

2023-10-27 18:36 UTC, waffle87 commented on keyboards/enter67/halconf.h
This file should be removed.

2023-10-27 18:36 UTC, waffle87 commented on keyboards/enter67/mcuconf.h
This file should be removed.

2023-10-27 19:34 UTC, LXF-YZP commented on keyboards/enter67/mcuconf.h
thank you

2023-10-27 20:02 UTC, LXF-YZP commented on keyboards/enter67/mcuconf.h
I had no problem compiling the firmware locally, but a check failed after I submitted it. I'm trying to figure it out

2023-10-27 22:34 UTC, dunk2k requested changes

2023-10-27 22:34 UTC, dunk2k commented on keyboards/enter67/readme.md
> +A 67 layout pcb.
```suggestion
67 layout PCB, with option for stepped Caps Lock
```

2023-10-28 06:17 UTC, LXF-YZP commented on keyboards/enter67/info.json
> +        "vid": "0x1000"
I have no right to use it, I will modify vid, thank you

2023-10-28 06:29 UTC, waffle87 approved these changes

2023-10-28 06:33 UTC, LXF-YZP commented on keyboards/enter67/mcuconf.h
Please accept my heartfelt thanks @lesshonor

2023-10-28 07:57 UTC, fauxpark approved these changes

2023-10-28 20:27 UTC, drashna approved these changes

2023-10-28 20:28 UTC, merged