Add Support for Keyboard: TeaQueen
qmk/qmk_firmware pull request #22352
Opened 2023-10-28 23:36 UTC by gregandcin

## Description

This adds support in QMK for the keyboard [TeaQueen](https://github.com/gregandcin/teaqueen). Included is a default keymap and a VIA enabled keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-28 23:45 UTC, zvecr requested changes

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/config.h
This file should be removed.

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/default/keymap.c
> +
```suggestion
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/via/keymap.c
> +
```suggestion
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/via/keymap.c
> +
```suggestion
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/default/keymap.c
> +
```suggestion
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/via/keymap.c
> +		KC_TRNS, KC_TRNS,          KC_TRNS,          KC_TRNS, KC_TRNS,                     KC_TRNS,          KC_TRNS,                   KC_TRNS, KC_TRNS)
Dead layer
```suggestion
		KC_TRNS, KC_TRNS,          KC_TRNS,           KC_TRNS, KC_TRNS,                     KC_TRNS,          KC_TRNS,                   KC_TRNS, KC_TRNS)
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/default/keymap.c
> +		KC_TRNS, KC_TRNS,          KC_TRNS,          KC_TRNS, KC_TRNS,                     KC_TRNS,          KC_TRNS,                   KC_TRNS, KC_TRNS)
Dead layer
```suggestion
		KC_TRNS, KC_TRNS,          KC_TRNS,           KC_TRNS, KC_TRNS,                     KC_TRNS,          KC_TRNS,                   KC_TRNS, KC_TRNS)
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/via/keymap.c
> +    _ADJUST
```suggestion
    _NAV
```

2023-10-28 23:45 UTC, zvecr commented on keyboards/gregandcin/teaqueen/keymaps/default/keymap.c
> +    _ADJUST
```suggestion
    _NAV
```

2023-10-28 23:49 UTC, gregandcin commented
Removed unused code and files

2023-10-29 02:04 UTC, waffle87 commented on keyboards/gregandcin/teaqueen/info.json
> +        }
```suggestion
        "soft_serial_pin": "GP3"
```

2023-10-29 07:30 UTC, drashna approved these changes

2023-11-01 00:17 UTC, waffle87 approved these changes

2023-11-01 00:17 UTC, merged