Add Duet Switch Tester
qmk/qmk_firmware pull request #22367
Opened 2023-10-29 23:32 UTC by ai03-2725

## Description

Adds support for the [Duet switch tester](https://github.com/ai03-2725/duet-switch-tester).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds support for the Duet switch tester

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-30 17:32 UTC, waffle87 requested changes

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/config.h
> +#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 128
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 128
```

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/keymaps/coordinate/README.md
Please rename this file to lowercase.

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/keymaps/coordinate/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/keymaps/default/README.md
As above.

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/readme.md
> +![Cover image](https://raw.githubusercontent.com/ai03-2725/duet-switch-tester/main/images/cover.jpg)
Please rehost this image on Imgur.

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/rules.mk
> +WEAR_LEVELING_DRIVER = rp2040_flash
```suggestion
# This file intentionally left blank
```

2023-10-30 17:32 UTC, waffle87 commented on keyboards/ai03/duet/info.json
> +    },
```suggestion
    },
    "eeprom": {
        "driver": "wear_leveling"
    },
```

2023-10-31 00:47 UTC, drashna requested changes

2023-10-31 00:47 UTC, drashna commented on keyboards/ai03/duet/keymaps/coordinate/keymap.c
> +
```suggestion
	[0] = LAYOUT(
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0
    ),
```

2023-10-31 00:47 UTC, drashna commented on keyboards/ai03/duet/keymaps/coordinate/keymap.c
> +{
```suggestion
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
```

2023-10-31 00:47 UTC, drashna commented on keyboards/ai03/duet/keymaps/default/keymap.c
> +
```suggestion
	[0] = LAYOUT(
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,
        KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0,    KC_0
    ),
```

2023-10-31 00:47 UTC, drashna commented on keyboards/ai03/duet/readme.md
> +![Cover image](https://i.imgur.com/sFuHJbL.png)
```suggestion
![Cover image](https://i.imgur.com/sFuHJbLh.png)
```

2023-11-01 00:45 UTC, waffle87 requested changes

2023-11-01 00:45 UTC, waffle87 commented on keyboards/ai03/duet/keymaps/default/keymap.c
> +	[0] = LAYOUT(
```suggestion
```

2023-11-01 00:45 UTC, waffle87 commented on keyboards/ai03/duet/info.json
> +    },
This actually isn't needed, sorry.
```suggestion
```

2023-11-08 10:22 UTC, drashna approved these changes

2023-11-08 17:38 UTC, waffle87 approved these changes

2023-11-08 17:39 UTC, merged