Klein_SD PCB support
qmk/qmk_firmware pull request #22371
Opened 2023-10-30 10:22 UTC by eerraa

Klein_SD PCB for SIRIND MontCervin

## Description
Ergonomics Split PCB powered by RP2040.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-30 10:24 UTC, fauxpark requested changes

2023-10-30 10:24 UTC, fauxpark commented on keyboards/era/sirind/klein_sd/info.json
Please run `qmk format-json` on this file.

2023-10-30 10:32 UTC, eerraa commented
@fauxpark 
Thank you sir, I just did qmk format-json. is this right?

2023-10-30 17:11 UTC, waffle87 approved these changes

2023-10-30 17:21 UTC, zvecr requested changes

2023-10-30 17:21 UTC, zvecr commented on keyboards/era/sirind/klein_sd/config.h
> +#define WS2812_PIO_USE_PIO1 // Force the usage of PIO1 peripheral, by default the WS2812 implementation uses the PIO0 peripheral
Not using another PIO peripheral
```suggestion
```

2023-10-30 17:21 UTC, zvecr commented on keyboards/era/sirind/klein_sd/config.h
> +#define RGB_MATRIX_KEYPRESSES
Now inferred from enabled animations
```suggestion
```

2023-10-31 11:18 UTC, eerraa commented on keyboards/era/sirind/klein_sd/rules.mk
@lesshonor 
Thank you!

2023-11-01 00:40 UTC, merged