consolidate firmware folder in smoll parent folder
qmk/qmk_firmware pull request #22401
Opened 2023-11-04 12:25 UTC by SmollChungus

Consolidate firmware folders into the smoll parent folder, in preparation for future additions.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-04 13:16 UTC, dunk2k commented
@SmollChungus 
Could respective entries, for moved keyboards, be added in `data/mappings/keyboard_aliases.hjson`?

2023-11-04 16:58 UTC, SmollChungus commented
> @SmollChungus Could respective entries, for moved keyboards, be added in `data/mappings/keyboard_aliases.hjson`?

Yes for sure! Is this something I would need to add to this PR / open another PR for?

2023-11-04 17:19 UTC, dunk2k commented
> > @SmollChungus Could respective entries, for moved keyboards, be added in `data/mappings/keyboard_aliases.hjson`?
> 
> Yes for sure! Is this something I would need to add to this PR / open another PR for?

With this PR please 😊

2023-11-04 17:28 UTC, SmollChungus commented
Okay perfect, added modified mappings to the PR!

2023-11-08 20:24 UTC, drashna approved these changes

2023-11-09 02:06 UTC, zvecr requested changes

2023-11-09 02:06 UTC, zvecr commented on keyboards/smoll/lefty/rules.mk
`DEFAULT_FOLDER = lefty/rev2` in this file is incorrect and needs to be updated to `smoll/lefty/rev2`.

2023-11-30 20:18 UTC, dunk2k requested changes

2023-11-30 20:18 UTC, dunk2k commented on data/mappings/keyboard_aliases.hjson
> +    },
```suggestion
    },
    "lefty/rev1": {
        "target": "smoll/lefty/rev1"
    },
```

2023-12-08 04:36 UTC, zvecr approved these changes

2023-12-08 04:36 UTC, merged