[Keyboard] Fixes to make snes_macropad play nicer with qmk configurator
qmk/qmk_firmware pull request #22432
Opened 2023-11-09 23:02 UTC by JBarberU

Some minor tweaks to make snes_macropad work better with QMK Configurator

## Description

Contains the following changes:

- changes to info.json to layout the lower 12 keys in the shape of a snes controller, to make mapping in configurator less confusing.
- changes the default implementation for get_layer_name_user so that it will print the layer number instead of "Unknown"

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-11 11:34 UTC, zvecr requested changes

2023-11-11 11:34 UTC, zvecr commented on keyboards/snes_macropad/snes_macropad.c
> +_Static_assert(MAX_LAYER < 100, "layer_str is too small");
QMK does not support more than 32 layers.
```suggestion
```

2023-11-11 11:34 UTC, zvecr commented on keyboards/snes_macropad/snes_macropad.c
> +    return layer_str;
Assuming the current use case of  `get_layer_name_user`,
```suggestion
    return get_u8_str(layer_str, ' ');
```

2023-11-11 11:34 UTC, zvecr commented on keyboards/snes_macropad/snes_macropad.c
> +char     layer_str[3] = ""; // 2 digits + null terminator
Not required if using `get_u8_str`
```suggestion
```

2023-11-11 19:42 UTC, JBarberU commented
Thanks for the review, really appreciate it! I implemented your suggestion which certainly made the code neater.

2023-11-11 20:01 UTC, zvecr approved these changes

2023-11-12 05:30 UTC, waffle87 approved these changes

2023-11-12 05:30 UTC, merged