Update MNK65_STM32
qmk/qmk_firmware pull request #22430
Opened 2023-11-09 16:00 UTC by kopibeng

## Description
Added RGB underglow support and moved to data driven config for MNK65_STM32

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-09 16:24 UTC, dunk2k requested changes

2023-11-09 16:24 UTC, dunk2k commented on keyboards/kopibeng/mnk65_stm32/info.json
could `qmk format-json` with `-i` please be run on this file?

2023-11-09 16:28 UTC, dunk2k requested changes

2023-11-09 16:28 UTC, dunk2k commented on keyboards/kopibeng/mnk65_stm32/info.json
> +}
add EoF (it's a GitHub thing)
```suggestion
}

```

2023-11-09 16:39 UTC, kopibeng commented on keyboards/kopibeng/mnk65_stm32/info.json
done!

2023-11-10 11:16 UTC, fauxpark approved these changes

2023-11-10 12:34 UTC, dunk2k approved these changes

2023-11-10 21:32 UTC, waffle87 approved these changes

2023-11-11 11:26 UTC, zvecr requested changes

2023-11-11 11:26 UTC, zvecr commented on keyboards/kopibeng/mnk65_stm32/info.json
>      "layouts": {
Not backwards compatible without adding an alias, which would then require it to go via `develop`
```suggestion
    "layout_aliases": {"LAYOUT": "LAYOUT_all"},
    "layouts": {
```

2023-11-29 02:02 UTC, fauxpark approved these changes

2023-12-05 07:14 UTC, drashna approved these changes

2023-12-05 07:14 UTC, merged