Generalise analog SRC inclusion
qmk/qmk_firmware pull request #22448
Opened 2023-11-11 14:15 UTC by zvecr

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-11 14:40 UTC, fauxpark requested changes

2023-11-11 14:40 UTC, fauxpark commented on builddefs/common_features.mk
> +    OPT_DEFS += -DSTM32_ADC -DHAL_USE_ADC=TRUE
```suggestion
    OPT_DEFS += -DHAL_USE_ADC=TRUE
```

2023-11-11 16:13 UTC, fauxpark approved these changes

2023-11-12 20:20 UTC, drashna approved these changes

2023-11-12 22:30 UTC, merged