Add the Relapse-KB OR87
qmk/qmk_firmware pull request #22458
Opened 2023-11-12 17:39 UTC by ramonimbao

## Description

Add the Relapse-KB OR87.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-12 19:19 UTC, dunk2k requested changes

2023-11-12 19:19 UTC, dunk2k commented on keyboards/relapsekb/or87/info.json
> +                { "matrix": [11, 8], "x": 17.25, "y": 5.25 }
WKL layouts added based on `readme.md` image, possible future proofing too
```suggestion
                { "matrix": [11, 8], "x": 17.25, "y": 5.25 }
            ]
        },
        "LAYOUT_tkl_ansi_wkl": {
            "layout": [
                { "matrix": [0, 0], "x": 0, "y": 0 },
                { "matrix": [0, 1], "x": 2, "y": 0 },
                { "matrix": [1, 1], "x": 3, "y": 0 },
                { "matrix": [0, 2], "x": 4, "y": 0 },
                { "matrix": [1, 2], "x": 5, "y": 0 },
                { "matrix": [0, 3], "x": 6.5, "y": 0 },
                { "matrix": [1, 3], "x": 7.5, "y": 0 },
                { "matrix": [0, 4], "x": 8.5, "y": 0 },
                { "matrix": [1, 4], "x": 9.5, "y": 0 },
                { "matrix": [0, 5], "x": 11, "y": 0 },
                { "matrix": [1, 5], "x": 12, "y": 0 },
                { "matrix": [0, 6], "x": 13, "y": 0 },
                { "matrix": [1, 6], "x": 14, "y": 0 },
                { "matrix": [1, 7], "x": 15.25, "y": 0 },
                { "matrix": [0, 8], "x": 16.25, "y": 0 },
                { "matrix": [1, 8], "x": 17.25, "y": 0 },

                { "matrix": [2, 0], "x": 0, "y": 1.25 },
                { "matrix": [3, 0], "x": 1, "y": 1.25 },
                { "matrix": [2, 1], "x": 2, "y": 1.25 },
                { "matrix": [3, 1], "x": 3, "y": 1.25 },
                { "matrix": [2, 2], "x": 4, "y": 1.25 },
                { "matrix": [3, 2], "x": 5, "y": 1.25 },
                { "matrix": [2, 3], "x": 6, "y": 1.25 },
                { "matrix": [3, 3], "x": 7, "y": 1.25 },
                { "matrix": [2, 4], "x": 8, "y": 1.25 },
                { "matrix": [3, 4], "x": 9, "y": 1.25 },
                { "matrix": [2, 5], "x": 10, "y": 1.25 },
                { "matrix": [3, 5], "x": 11, "y": 1.25 },
                { "matrix": [2, 6], "x": 12, "y": 1.25 },
                { "matrix": [2, 7], "x": 13, "y": 1.25, "w": 2 },
                { "matrix": [3, 7], "x": 15.25, "y": 1.25 },
                { "matrix": [2, 8], "x": 16.25, "y": 1.25 },
                { "matrix": [3, 8], "x": 17.25, "y": 1.25 },

                { "matrix": [4, 0], "x": 0, "y": 2.25, "w": 1.5 },
                { "matrix": [5, 0], "x": 1.5, "y": 2.25 },
                { "matrix": [4, 1], "x": 2.5, "y": 2.25 },
                { "matrix": [5, 1], "x": 3.5, "y": 2.25 },
                { "matrix": [4, 2], "x": 4.5, "y": 2.25 },
                { "matrix": [5, 2], "x": 5.5, "y": 2.25 },
                { "matrix": [4, 3], "x": 6.5, "y": 2.25 },
                { "matrix": [5, 3], "x": 7.5, "y": 2.25 },
                { "matrix": [4, 4], "x": 8.5, "y": 2.25 },
                { "matrix": [5, 4], "x": 9.5, "y": 2.25 },
                { "matrix": [4, 5], "x": 10.5, "y": 2.25 },
                { "matrix": [5, 5], "x": 11.5, "y": 2.25 },
                { "matrix": [4, 6], "x": 12.5, "y": 2.25 },
                { "matrix": [5, 6], "x": 13.5, "y": 2.25, "w": 1.5 },
                { "matrix": [5, 7], "x": 15.25, "y": 2.25 },
                { "matrix": [4, 8], "x": 16.25, "y": 2.25 },
                { "matrix": [5, 8], "x": 17.25, "y": 2.25 },

                { "matrix": [6, 0], "x": 0, "y": 3.25, "w": 1.75 },
                { "matrix": [7, 0], "x": 1.75, "y": 3.25 },
                { "matrix": [6, 1], "x": 2.75, "y": 3.25 },
                { "matrix": [7, 1], "x": 3.75, "y": 3.25 },
                { "matrix": [6, 2], "x": 4.75, "y": 3.25 },
                { "matrix": [7, 2], "x": 5.75, "y": 3.25 },
                { "matrix": [6, 3], "x": 6.75, "y": 3.25 },
                { "matrix": [7, 3], "x": 7.75, "y": 3.25 },
                { "matrix": [6, 4], "x": 8.75, "y": 3.25 },
                { "matrix": [7, 4], "x": 9.75, "y": 3.25 },
                { "matrix": [6, 5], "x": 10.75, "y": 3.25 },
                { "matrix": [7, 5], "x": 11.75, "y": 3.25 },
                { "matrix": [6, 6], "x": 12.75, "y": 3.25, "w": 2.25 },

                { "matrix": [8, 0], "x": 0, "y": 4.25, "w": 2.25 },
                { "matrix": [8, 1], "x": 2.25, "y": 4.25 },
                { "matrix": [9, 1], "x": 3.25, "y": 4.25 },
                { "matrix": [8, 2], "x": 4.25, "y": 4.25 },
                { "matrix": [9, 2], "x": 5.25, "y": 4.25 },
                { "matrix": [8, 3], "x": 6.25, "y": 4.25 },
                { "matrix": [9, 3], "x": 7.25, "y": 4.25 },
                { "matrix": [8, 4], "x": 8.25, "y": 4.25 },
                { "matrix": [9, 4], "x": 9.25, "y": 4.25 },
                { "matrix": [8, 5], "x": 10.25, "y": 4.25 },
                { "matrix": [9, 5], "x": 11.25, "y": 4.25 },
                { "matrix": [8, 6], "x": 12.25, "y": 4.25, "w": 2.75 },
                { "matrix": [8, 8], "x": 16.25, "y": 4.25 },

                { "matrix": [10, 0], "x": 0, "y": 5.25, "w": 1.5 },
                { "matrix": [10, 1], "x": 2.5, "y": 5.25, "w": 1.5 },
                { "matrix": [11, 3], "x": 4, "y": 5.25, "w": 7 },
                { "matrix": [11, 5], "x": 11, "y": 5.25, "w": 1.5 },
                { "matrix": [11, 6], "x": 13.5, "y": 5.25, "w": 1.5 },
                { "matrix": [11, 7], "x": 15.25, "y": 5.25 },
                { "matrix": [10, 8], "x": 16.25, "y": 5.25 },
                { "matrix": [11, 8], "x": 17.25, "y": 5.25 }
            ]
        },
        "LAYOUT_tkl_ansi_wkl_split_bs_rshift": {
            "layout": [
                { "matrix": [0, 0], "x": 0, "y": 0 },
                { "matrix": [0, 1], "x": 2, "y": 0 },
                { "matrix": [1, 1], "x": 3, "y": 0 },
                { "matrix": [0, 2], "x": 4, "y": 0 },
                { "matrix": [1, 2], "x": 5, "y": 0 },
                { "matrix": [0, 3], "x": 6.5, "y": 0 },
                { "matrix": [1, 3], "x": 7.5, "y": 0 },
                { "matrix": [0, 4], "x": 8.5, "y": 0 },
                { "matrix": [1, 4], "x": 9.5, "y": 0 },
                { "matrix": [0, 5], "x": 11, "y": 0 },
                { "matrix": [1, 5], "x": 12, "y": 0 },
                { "matrix": [0, 6], "x": 13, "y": 0 },
                { "matrix": [1, 6], "x": 14, "y": 0 },
                { "matrix": [1, 7], "x": 15.25, "y": 0 },
                { "matrix": [0, 8], "x": 16.25, "y": 0 },
                { "matrix": [1, 8], "x": 17.25, "y": 0 },

                { "matrix": [2, 0], "x": 0, "y": 1.25 },
                { "matrix": [3, 0], "x": 1, "y": 1.25 },
                { "matrix": [2, 1], "x": 2, "y": 1.25 },
                { "matrix": [3, 1], "x": 3, "y": 1.25 },
                { "matrix": [2, 2], "x": 4, "y": 1.25 },
                { "matrix": [3, 2], "x": 5, "y": 1.25 },
                { "matrix": [2, 3], "x": 6, "y": 1.25 },
                { "matrix": [3, 3], "x": 7, "y": 1.25 },
                { "matrix": [2, 4], "x": 8, "y": 1.25 },
                { "matrix": [3, 4], "x": 9, "y": 1.25 },
                { "matrix": [2, 5], "x": 10, "y": 1.25 },
                { "matrix": [3, 5], "x": 11, "y": 1.25 },
                { "matrix": [2, 6], "x": 12, "y": 1.25 },
                { "matrix": [3, 6], "x": 13, "y": 1.25 },
                { "matrix": [2, 7], "x": 14, "y": 1.25 },
                { "matrix": [3, 7], "x": 15.25, "y": 1.25 },
                { "matrix": [2, 8], "x": 16.25, "y": 1.25 },
                { "matrix": [3, 8], "x": 17.25, "y": 1.25 },

                { "matrix": [4, 0], "x": 0, "y": 2.25, "w": 1.5 },
                { "matrix": [5, 0], "x": 1.5, "y": 2.25 },
                { "matrix": [4, 1], "x": 2.5, "y": 2.25 },
                { "matrix": [5, 1], "x": 3.5, "y": 2.25 },
                { "matrix": [4, 2], "x": 4.5, "y": 2.25 },
                { "matrix": [5, 2], "x": 5.5, "y": 2.25 },
                { "matrix": [4, 3], "x": 6.5, "y": 2.25 },
                { "matrix": [5, 3], "x": 7.5, "y": 2.25 },
                { "matrix": [4, 4], "x": 8.5, "y": 2.25 },
                { "matrix": [5, 4], "x": 9.5, "y": 2.25 },
                { "matrix": [4, 5], "x": 10.5, "y": 2.25 },
                { "matrix":  [...]

2023-11-17 13:55 UTC, dunk2k commented on keyboards/relapsekb/or87/readme.md
> +![OR87](https://i.imgur.com/nvXwreYlh.jpg)
```suggestion
![OR87](https://i.imgur.com/nvXwreYh.jpg)
```

2023-11-17 14:02 UTC, dunk2k approved these changes

2023-12-05 07:56 UTC, drashna approved these changes

2023-12-06 03:34 UTC, waffle87 approved these changes

2023-12-06 03:34 UTC, merged