add tokki
qmk/qmk_firmware pull request #22463
Opened 2023-11-13 04:56 UTC by alabahuy

## Description

PCB 65% soldered with many layout and top right blocker

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-13 05:56 UTC, waffle87 approved these changes

2023-11-13 09:18 UTC, dunk2k requested changes

2023-11-13 09:30 UTC, alabahuy commented on keyboards/jaykeeb/tokki/info.json
> +    },
done :)

2023-11-15 22:50 UTC, dunk2k requested changes

2023-11-15 22:50 UTC, dunk2k commented on keyboards/jaykeeb/tokki/matrix_diagram.md
> +│20    │21 │22 │23 │24 │25 │26 │27 │28 │29 │2A │2B │2C      │2E │  │2C │ 2D │ ISO Enter
```suggestion
├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┼───┤  ┌──┴┐2D  │
│20    │21 │22 │23 │24 │25 │26 │27 │28 │29 │2A │2B │2C      │2E │  │2C │    │ ISO Enter
```

2023-11-16 07:19 UTC, dunk2k approved these changes

2023-11-19 01:24 UTC, alabahuy commented
any update ?

2023-11-19 06:06 UTC, fauxpark approved these changes

2023-11-29 03:32 UTC, drashna approved these changes

2023-11-29 03:32 UTC, merged