Documentation regarding user code removal/acceptance
qmk/qmk_firmware pull request #22507
Opened 2023-11-20 07:09 UTC by waffle87

## Description

As per [#22485 comment](https://github.com/qmk/qmk_firmware/pull/22485#issuecomment-1817784401). Please do comment if a notice should be added elsewhere.

## Types of Changes

- [x] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-20 07:40 UTC, dunk2k approved these changes

2023-11-20 10:53 UTC, dunk2k requested changes

2023-11-20 10:53 UTC, dunk2k commented on docs/feature_userspace.md
> +!> Please note, userspace submissions to the upstream `qmk/qmk_firmware` repository are no longer being accepted. The userspace feature itself remains functional and can be configured locally.
```suggestion
!> Please note, userspace submissions to the upstream `qmk/qmk_firmware` repository are no longer being accepted. The userspace feature itself remains functional and is intended to be utilised locally.
```

2023-11-29 02:48 UTC, drashna approved these changes

2023-12-04 00:56 UTC, zvecr approved these changes

2023-12-04 00:57 UTC, merged