Add EE-AT and move W1-AT under geonworks
qmk/qmk_firmware pull request #22526
Opened 2023-11-21 23:44 UTC by yiancar

I added the alias of W1-AT as well, please let me know if this is correct.

Also updated W1-AT to use more JSON.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-29 02:20 UTC, drashna commented on keyboards/geonworks/ee_at/ee_at.c
> +    palSetLineMode(A14, PAL_MODE_OUTPUT_OPENDRAIN);
```suggestion
    setPinOutputOpenDrain(LED_CAPS_LOCK_PIN);
    setPinOutputOpenDrain(LED_NUM_LOCK_PIN);
    setPinOutputOpenDrain(LED_SCROLL_LOCK_PIN);
    setPinOutputOpenDrain(LED_KANA_PIN);
    setPinOutputOpenDrain(A14);
```

2023-11-29 22:59 UTC, fauxpark requested changes

2023-11-29 22:59 UTC, fauxpark commented on keyboards/geonworks/ee_at/info.json
Please run `qmk format-json -i` on this file.

2023-11-30 01:05 UTC, yiancar commented on keyboards/geonworks/ee_at/info.json
Done, Both W1-AT and EE-AT

2023-12-04 09:06 UTC, keyboard-magpie approved these changes

2023-12-04 09:07 UTC, merged