El Cantor HS keyboard. 43 key diodeless split keyboard with support for hotswap sockets. Based on diepala/cantor.
qmk/qmk_firmware pull request #22531
Opened 2023-11-22 12:00 UTC by azhizhinov

## Description

The El Cantor HS keyboard is a 43 key diodeless split keyboard with support for hotswap sockets, designed with simplicity in mind. It is based on the popular [cantor](https://github.com/diepala/cantor), which is inspired on the popular [corne](https://github.com/foostan/crkbd), [ferris](https://github.com/pierrechevalier83/ferris) and [sweep](https://github.com/davidphilipbarr/Sweep) keyboards, aiming to provide a more ergonomic (stronger column stagger) corne-like layout with a simple, easy to assemble and cheap design.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-22 16:09 UTC, azhizhinov reviewed
All checks were passed.

2023-11-22 18:34 UTC, azhizhinov commented
Thanks for your help.

2023-11-23 07:39 UTC, dunk2k requested changes

2023-11-23 07:39 UTC, dunk2k commented on keyboards/elcantorhs/readme.md
> +The El Cantor HS keyboard is a 43 key diodeless split keyboard with support for hotswap sockets, designed with simplicity in mind. It is based on the popular [cantor](https://github.com/diepala/canto
No need to elaborate on Cantor's design influences, this readme.md is all about the El Cantor HS 😉
```suggestion
The El Cantor HS keyboard is a 44 key diodeless split keyboard with support for hotswap sockets, designed with simplicity in mind. Based on the popular [Cantor](https://github.com/diepala/cantor) keyboard, this keyboard features a more aggressive column stagger than the afore mentioned, whilst aiming to simplify assembly and improve cost efficiency.
```

2023-11-28 08:40 UTC, azhizhinov commented
Hello.
Done.

2023-11-29 01:35 UTC, drashna requested changes

2023-11-29 01:35 UTC, drashna commented on keyboards/elcantorhs/readme.md
> +![El Cantor HS](https://thumb.cloud.mail.ru/weblink/thumb/xw1/VtFZ/jwSN7r6BB)
Could you rehost this on imgur or the like?

2023-11-29 05:44 UTC, azhizhinov commented
Hello.
Done.

2023-12-01 08:00 UTC, azhizhinov commented
Hello.
@drashna
Done. Hosting for the image has been changed.
The image can be removed at all, it's not important in this case at all.
Thanks in advance.

2023-12-11 17:06 UTC, azhizhinov commented
Hello.
@drashna 
Is there any reason, why you are not approving this pull request?
Thanks in advance.

2023-12-12 06:16 UTC, azhizhinov commented
Hello.
@drashna 
Done. Thanks for your time.

2023-12-13 23:42 UTC, drashna approved these changes

2023-12-14 01:44 UTC, fauxpark approved these changes

2023-12-14 07:42 UTC, waffle87 approved these changes

2023-12-14 07:43 UTC, merged