[Keyboard] Add Mode Tempo PCB's
qmk/qmk_firmware pull request #22550
Opened 2023-11-27 01:57 UTC by ToastyStoemp

## Description

Add Solder, and 2 versions of hotswap PCBs for the Mode Tempo, called M60S M60H and M60H-F respectively

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-28 05:07 UTC, drashna requested changes
Same for all of the pcbs here.

2023-11-28 05:07 UTC, drashna commented on keyboards/mode/m60h/config.h
> +#endif
```suggestion
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
```

2023-11-28 05:07 UTC, drashna commented on keyboards/mode/m60h/info.json
> +    },
```suggestion
        "sleep": true
    },
    "ws2812": {
        "pin": "B9"
    },
```

2023-11-28 05:07 UTC, drashna commented on keyboards/mode/m60h/m60h.c
This file can be/should be removed.  The core is already handling this, so this shouldn't be needed. 

If there is an issue with this, then it's likely a bug, and should be addressed, rather than worked around.

2023-11-28 11:42 UTC, ToastyStoemp commented on keyboards/mode/m60h/m60h.c
When we turn off all the leds, and replug the PCB one underglow LED lights up green, when looking at other projects that with similar chips we found this bit of code on a different PR with the same MCU [https://github.com/qmk/qmk_firmware/pull/20501/files#diff-fe96b9da2fd0cd7105a4e3edc05ee2dfc47204f9cbb08c2c077dfde790f30b4aR45](https://github.com/qmk/qmk_firmware/pull/20501/files#diff-fe96b9da2fd0cd7105a4e3edc05ee2dfc47204f9cbb08c2c077dfde790f30b4aR45)

After trying this out on a prototype PCB only after increasing the wait time to reload the EEPROM did the issue resolve.

2023-11-28 11:47 UTC, fauxpark commented on keyboards/mode/m60h/m60h.c
Just because it works doesn't mean it's the right, or best, solution.

2023-11-28 11:57 UTC, ToastyStoemp commented on keyboards/mode/m60h/m60h.c
I agree to the statement. What alternative solutions do you recommend on a software level?

2023-11-29 00:42 UTC, drashna commented on keyboards/mode/m60h/m60h.c
There are a few.  The simplest option would be to use the PWM or SPI driver for ws2812, rather than the bitbang one.   But otherwise, it sounds like this may be a timing issue, and adjusting the driver timings would likely fix this issue. 

https://docs.qmk.fm/#/ws2812_driver?id=adjusting-bit-timings

At lest for the m60h, it's using an STM32F401, and using B9 for the pin.  This supports PWM via TIM4 and TIM11 for B9.   You could easily enable this, and you'd likely see fewer issues with the LEDs. 

https://docs.qmk.fm/#/ws2812_driver?id=pwm

2023-11-29 04:26 UTC, ToastyStoemp commented on keyboards/mode/m60h/m60h.c
I've pushed an update with the drivers modified to use PWM

2023-12-01 18:19 UTC, fauxpark requested changes

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h/config.h
> +#define WS2812_PWM_PAL_MODE 2
```suggestion
```
This is the default.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60s/readme.md
> +	make mode/m60s:default:flash
```suggestion
    make mode/m60s:default

Flashing example for this keyboard:

    make mode/m60s:default:flash
```

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60s/readme.md
> +![Mode Tempo M60S](https://modedesigns.com/products/tempo)
This isn't an image.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60s/info.json
Please run `qmk format-json -i` on this file.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60s/config.h
> +#define WS2812_PWM_PAL_MODE 2
```suggestion
```
This is the default.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h_f/readme.md
> +	make mode/m60h_f:default:flash
```suggestion
    make mode/m60h_f:default

Flashing example for this keyboard:

    make mode/m60h_f:default:flash
```

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h_f/readme.md
> +![Mode Tempo M60H_F](https://modedesigns.com/products/tempo)
As above.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h_f/info.json
As above.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h_f/config.h
> +#define WS2812_PWM_PAL_MODE 2
```suggestion
```

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h/readme.md
> +	make mode/m60h:default:flash
```suggestion
    make mode/m60h:default

Flashing example for this keyboard:

    make mode/m60h:default:flash
```

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h/readme.md
> +![Mode Tempo M60H](https://modedesigns.com/products/tempo)
As above.

2023-12-01 18:19 UTC, fauxpark commented on keyboards/mode/m60h/info.json
As above.

2023-12-11 21:48 UTC, fauxpark commented on keyboards/mode/m60h_f/readme.md
> +	make mode/m60h_f:default:flash
Still outstanding.

2023-12-12 03:20 UTC, drashna requested changes
Is there a reason to use timer 5 as the system tick timer?

2023-12-12 03:20 UTC, drashna requested changes
Is there a reason to use timer 5 as the system tick timer?

2023-12-13 03:25 UTC, ToastyStoemp commented on keyboards/mode/m60s/chconf.h
Removed

2023-12-13 03:26 UTC, ToastyStoemp commented
> Is there a reason to use timer 5 as the system tick timer?

I can't say for certain, I'm out of the country at the moment and don't have the PCB with me for testing. 
I did change around the timings a lot to make it work, and know that this configuration works as is

2023-12-13 23:46 UTC, drashna commented
> > Is there a reason to use timer 5 as the system tick timer?
> 
> I can't say for certain, I'm out of the country at the moment and don't have the PCB with me for testing. I did change around the timings a lot to make it work, and know that this configuration works as is

The default timer is Timer 2. Between it and timer 5, these are usually the more accurate timers, and what should be used for the system tick timer.   Either is okay, but generally, unless there is a reason to change it,  it shouldn't be changed.  And reasons for changing it are usually along the lines of DMA conflict resolution or requiring timer 2 for PWM or the like.  

And given a quick look, I don't see either of those in your config.  And wanted to make sure that I wasn't missing anything.

2023-12-13 23:47 UTC, drashna approved these changes

2023-12-14 01:46 UTC, fauxpark requested changes
/

2023-12-14 23:51 UTC, fauxpark approved these changes

2023-12-15 21:28 UTC, waffle87 approved these changes

2023-12-15 21:28 UTC, merged