add keyboard mmk_3
qmk/qmk_firmware pull request #22569
Opened 2023-11-29 02:55 UTC by TW59420

## Description
MWStudio is a custom keyboard enthusiast
Add keyboard mmk_3 PCB

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-30 22:53 UTC, waffle87 requested changes

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/config.h
> +
```suggestion
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/halconf.h
> +// #define HAL_USE_I2C TRUE
```suggestion
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/info.json
> +        "encoder": false
```suggestion
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgblight": true
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/info.json
> +            "all": true
```suggestion
      "alternating": true,
      "breathing": true,
      "christmas": true,
      "knight": true,
      "rainbow_mood": true,
      "rainbow_swirl": true,
      "rgb_test": true,
      "snake": true,
      "static_gradient": true,
      "twinkle": true
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/info.json
> +        "LAYOUT_3key": {
```suggestion
        "LAYOUT": {
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/keymaps/default/keymap.c
> +    )
```suggestion
	[0] = LAYOUT(
		KC_LCTL, KC_C, KC_V
    )
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/keymaps/via/keymap.c
> +    )
```suggestion
	[0] = LAYOUT(
		KC_LCTL, KC_C, KC_V
    )
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/keymaps/via/keymap.c
> +}
This code needs to be properly revised for the keyboard/keymap it's being applied to. Not copy-pasted from elsewhere.

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/mmk_3.c
This file should be removed.

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/readme.md
> +![3Key](https://imgur.com/a/qPK5GmI)
```suggestion
![3Key](https://i.imgur.com/WuwlVknh.jpeg)
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/rules.mk
> +WS2812_DRIVER = pwm
```suggestion
# This file intentionally left blank
```

2023-11-30 22:53 UTC, waffle87 commented on keyboards/mwstudio/mmk_3/info.json
> +    "url": "",
```suggestion
    "url": "",
    "ws2812": {
        "driver": "pwm"
    },
```

2023-12-02 06:59 UTC, fauxpark requested changes

2023-12-02 06:59 UTC, fauxpark commented on keyboards/mwstudio/mmk_3/info.json
> +        "pin": "B8",
```suggestion
        "driver": "pwm",
        "pin": "B8"
    },
    "rgblight": {
        "led_count": 5,
```

2023-12-02 06:59 UTC, fauxpark commented on keyboards/mwstudio/mmk_3/info.json
Please run `qmk format-json -i` on this file.

2023-12-03 18:24 UTC, fauxpark commented on keyboards/mwstudio/mmk_3/readme.md
> +    make mwstudio/3key:default:flash
```suggestion
    make mwstudio/mmk_3:default 

Flashing example for this keyboard:

    make mwstudio/mmk_3:default:flash
```

2023-12-05 04:34 UTC, drashna requested changes

2023-12-05 04:34 UTC, drashna commented on keyboards/mwstudio/mmk_3/config.h
> +#define WS2812_DMA_CHANNEL 2                  // DMA Channel for TIMx_UP, see the respective reference manual for the appropriate values for your MCU.
```suggestion
#define WS2812_PWM_DRIVER PWMD4
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 1
#define WS2812_DMA_STREAM STM32_DMA1_STREAM7
#define WS2812_DMA_CHANNEL 2
```

2023-12-05 04:34 UTC, drashna commented on keyboards/mwstudio/mmk_3/info.json
> +        "pin": "B8",
```suggestion
```

2023-12-05 04:34 UTC, drashna commented on keyboards/mwstudio/mmk_3/info.json
> +    },
```suggestion
        "pin": "B8",
    },
    "layouts": {
```

2023-12-05 04:34 UTC, drashna commented on keyboards/mwstudio/mmk_3/keymaps/default/keymap.c
please run `qmk format-c` on this file. Or otherwise replace the tabs with spaces.

2023-12-05 04:34 UTC, drashna commented on keyboards/mwstudio/mmk_3/keymaps/via/keymap.c
same

2023-12-09 21:39 UTC, zvecr commented on keyboards/mwstudio/mmk_3/info.json
> +        "saturation_steps": 17
Should avoid re-specifying defaults
```suggestion
        "hue_steps": 10,
        "led_count": 5
```

2023-12-12 03:09 UTC, drashna commented on keyboards/mwstudio/mmk_3/info.json
> +        "rows": ["A6"]
Could have used direct pin, when designing (eg, GPIO to GND for each).

2023-12-12 03:12 UTC, drashna approved these changes

2023-12-12 03:21 UTC, merged