Update Q9
qmk/qmk_firmware pull request #22578
Opened 2023-11-30 03:14 UTC by adophoxia

## Description
Superseeds https://github.com/qmk/qmk_firmware/pull/21423, but this will only cover one board from each series update of PRs. Also enables Num Lock Indicator LED.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-05 04:17 UTC, drashna approved these changes

2023-12-05 05:15 UTC, fauxpark requested changes

2023-12-05 05:15 UTC, fauxpark commented on keyboards/keychron/q8/ansi_encoder/info.json
> +
```suggestion

```

2023-12-05 05:15 UTC, fauxpark commented on keyboards/keychron/q8/iso/info.json
> +
```suggestion

```

2023-12-14 01:41 UTC, fauxpark approved these changes

2023-12-14 07:44 UTC, waffle87 approved these changes

2023-12-14 07:44 UTC, merged