[Keyboard] Valor Rev3
qmk/qmk_firmware pull request #22581
Opened 2023-11-30 04:05 UTC by Xelus22

## Description

Add Valor Rev3
Takes over from #20606 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Add Valor Rev3

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-11-30 04:53 UTC, Xelus22 commented on keyboards/xelus/valor/rev3/readme.md
> +* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
Fixed thanks :)

2023-12-05 03:55 UTC, drashna requested changes

2023-12-05 03:55 UTC, drashna commented on keyboards/xelus/valor/rev3/rev3.c
> +void matrix_io_delay(void) { __asm__ volatile("nop\nnop\nnop\n"); }
```suggestion
void matrix_output_unselect_delay(void) { __asm__ volatile("nop\nnop\nnop\n"); }
```

2023-12-06 13:55 UTC, dunk2k requested changes

2023-12-06 13:55 UTC, dunk2k commented on keyboards/xelus/valor/rev3/rev3.c
to confirm: is this file, more so its contents, required?

2023-12-12 07:52 UTC, Xelus22 commented on keyboards/xelus/valor/rev3/rev3.c
Gives a significant speed bump. I've done this for multiple other boards.

2024-02-01 06:12 UTC, drashna approved these changes

2024-08-26 10:35 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2025-03-01 20:37 UTC, waffle87 commented on keyboards/xelus/valor/rev3/keymaps/default/keymap.c
> +             KC_TRNS,          KC_TRNS,          KC_TRNS, KC_TRNS,          KC_TRNS,          KC_TRNS,                   KC_TRNS
```suggestion
    UG_TOGG, _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______, _______,
    UG_NEXT, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
    QK_BOOT, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
             _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
             _______,          _______,          _______, _______,          _______,          _______,                   _______
```

2025-03-02 08:03 UTC, waffle87 approved these changes

2025-03-02 21:04 UTC, merged