KinBP firmware
qmk/qmk_firmware pull request #22597
Opened 2023-12-02 17:09 UTC by DmNosachev

Firmware for [KinBP](https://github.com/DmNosachev/kinbp), a drop-in replacement controller for Kinesis Contoured keyboards.
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-02 17:34 UTC, DmNosachev commented
Hello,
Lint is failing with following message: `Error: Process completed with exit code 255`.
But I don't understand the reason for the error. Locally, the Lint check completes successfully:

```
[nosac@WIN-OSD802N8KU1 qmk_firmware]$ qmk lint -kb kinesis/kinbp/blackpill411
Ψ Lint check passed!
[nosac@WIN-OSD802N8KU1 qmk_firmware]$ qmk lint -kb kinesis/kinbp/blackpill401
Ψ Lint check passed!
```

2023-12-02 22:36 UTC, fauxpark commented
That's because you have a rules.mk at the root, which signals to the build system that this is a valid keyboard target, however there are things missing (namely the matrix pins) at this level since they are only in the "revision" folders.
You should either remove the root rules.mk, or set `DEFAULT_FOLDER = kinesis/kinbp/<rev>` to redirect it.

2023-12-03 18:22 UTC, fauxpark requested changes

2023-12-03 18:22 UTC, fauxpark commented on keyboards/kinesis/kinbp/blackpill401/info.json
Please run `qmk format-json -i` on this file.

2023-12-03 18:22 UTC, fauxpark commented on keyboards/kinesis/kinbp/blackpill411/info.json
As above.

2023-12-03 18:22 UTC, fauxpark commented on keyboards/kinesis/kinbp/info.json
As above.

2023-12-04 11:40 UTC, LXF-YZP reviewed
`"usb": {
        "device_version": "0.0.1",
        "pid": "0x4B4E",
        "vid": "0xFEED"
    },`

vid better not. If it wasn't for 0xFEED,via wouldn't pass the review when it was submitted.

2023-12-05 04:03 UTC, drashna approved these changes

2024-02-21 07:39 UTC, DmNosachev reviewed
Hi all. Please tell me what I should do. It seems that I have made all the requested changes. As always, I lack experience with Github

2024-06-24 01:52 UTC, closed without merging