Argyle
qmk/qmk_firmware pull request #22607
Opened 2023-12-04 12:13 UTC by yiancar

## Description
As this uses matrix lite please let me know if rules.mk are still needed to load the right i2c lib and point to the correct matrix.c.
I think they are but a second look is always welcome!

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-04 13:15 UTC, dunk2k requested changes

2023-12-04 13:19 UTC, dunk2k commented on keyboards/argyle/keymaps/via/rules.mk
> +VIA_ENABLE = yes
```suggestion
VIA_ENABLE = yes

```

2023-12-04 13:19 UTC, dunk2k commented on keyboards/argyle/keymaps/iso/keymap.c
> +};
```suggestion
};

```

2023-12-04 13:31 UTC, dunk2k requested changes

2023-12-04 13:31 UTC, dunk2k commented on keyboards/argyle/info.json
> +                { "matrix": [2, 12], "x": 12.75, "y": 2 },
move sequence of ISO Enter to conform to respective Community Layout
```suggestion
                { "matrix": [2, 0], "w": 1.75, "x": 0, "y": 2 },
                { "matrix": [2, 1], "x": 1.75, "y": 2 },
                { "matrix": [2, 2], "x": 2.75, "y": 2 },
                { "matrix": [2, 3], "x": 3.75, "y": 2 },
                { "matrix": [2, 4], "x": 4.75, "y": 2 },
                { "matrix": [2, 5], "x": 5.75, "y": 2 },
                { "matrix": [2, 6], "x": 6.75, "y": 2 },
                { "matrix": [2, 7], "x": 7.75, "y": 2 },
                { "matrix": [2, 8], "x": 8.75, "y": 2 },
                { "matrix": [2, 9], "x": 9.75, "y": 2 },
                { "matrix": [2, 10], "x": 10.75, "y": 2 },
                { "matrix": [2, 11], "x": 11.75, "y": 2 },
                { "matrix": [2, 12], "x": 12.75, "y": 2 },
                { "h": 2, "matrix": [2, 13], "w": 1.25, "x": 13.75, "y": 1 },
                { "matrix": [3, 0], "w": 1.25, "x": 0, "y": 3 },
                { "matrix": [3, 1], "x": 1.25, "y": 3 },
                { "matrix": [3, 2], "x": 2.25, "y": 3 },
                { "matrix": [3, 3], "x": 3.25, "y": 3 },
                { "matrix": [3, 4], "x": 4.25, "y": 3 },
                { "matrix": [3, 5], "x": 5.25, "y": 3 },
                { "matrix": [3, 6], "x": 6.25, "y": 3 },
                { "matrix": [3, 7], "x": 7.25, "y": 3 },
                { "matrix": [3, 8], "x": 8.25, "y": 3 },
                { "matrix": [3, 9], "x": 9.25, "y": 3 },
                { "matrix": [3, 10], "x": 10.25, "y": 3 },
                { "matrix": [3, 11], "x": 11.25, "y": 3 },
                { "matrix": [3, 12], "w": 2.75, "x": 12.25, "y": 3 },
                { "matrix": [4, 0], "w": 1.25, "x": 0, "y": 4 },
                { "matrix": [4, 1], "w": 1.25, "x": 1.25, "y": 4 },
                { "matrix": [4, 2], "w": 1.25, "x": 2.5, "y": 4 },
                { "matrix": [4, 6], "w": 6.25, "x": 3.75, "y": 4 },
                { "matrix": [4, 10], "w": 1.25, "x": 10, "y": 4 },
                { "matrix": [4, 11], "w": 1.25, "x": 11.25, "y": 4 },
                { "matrix": [4, 12], "w": 1.25, "x": 12.5, "y": 4 },
                { "matrix": [4, 13], "w": 1.25, "x": 13.75, "y": 4 }
            ]
        },
        "LAYOUT_60_iso_split_bs_rshift": {
            "layout": [
                { "matrix": [0, 0], "x": 0, "y": 0 },
                { "matrix": [0, 1], "x": 1, "y": 0 },
                { "matrix": [0, 2], "x": 2, "y": 0 },
                { "matrix": [0, 3], "x": 3, "y": 0 },
                { "matrix": [0, 4], "x": 4, "y": 0 },
                { "matrix": [0, 5], "x": 5, "y": 0 },
                { "matrix": [0, 6], "x": 6, "y": 0 },
                { "matrix": [0, 7], "x": 7, "y": 0 },
                { "matrix": [0, 8], "x": 8, "y": 0 },
                { "matrix": [0, 9], "x": 9, "y": 0 },
                { "matrix": [0, 10], "x": 10, "y": 0 },
                { "matrix": [0, 11], "x": 11, "y": 0 },
                { "matrix": [0, 12], "x": 12, "y": 0 },
                { "matrix": [0, 13], "x": 13, "y": 0 },
                { "matrix": [1, 13], "x": 14, "y": 0 },
                { "matrix": [1, 0], "w": 1.5, "x": 0, "y": 1 },
                { "matrix": [1, 1], "x": 1.5, "y": 1 },
                { "matrix": [1, 2], "x": 2.5, "y": 1 },
                { "matrix": [1, 3], "x": 3.5, "y": 1 },
                { "matrix": [1, 4], "x": 4.5, "y": 1 },
                { "matrix": [1, 5], "x": 5.5, "y": 1 },
                { "matrix": [1, 6], "x": 6.5, "y": 1 },
                { "matrix": [1, 7], "x": 7.5, "y": 1 },
                { "matrix": [1, 8], "x": 8.5, "y": 1 },
                { "matrix": [1, 9], "x": 9.5, "y": 1 },
                { "matrix": [1, 10], "x": 10.5, "y": 1 },
                { "matrix": [1, 11], "x": 11.5, "y": 1 },
                { "matrix": [1, 12], "x": 12.5, "y": 1 },
                { "matrix": [2, 0], "w": 1.75, "x": 0, "y": 2 },
                { "matrix": [2, 1], "x": 1.75, "y": 2 },
                { "matrix": [2, 2], "x": 2.75, "y": 2 },
                { "matrix": [2, 3], "x": 3.75, "y": 2 },
                { "matrix": [2, 4], "x": 4.75, "y": 2 },
                { "matrix": [2, 5], "x": 5.75, "y": 2 },
                { "matrix": [2, 6], "x": 6.75, "y": 2 },
                { "matrix": [2, 7], "x": 7.75, "y": 2 },
                { "matrix": [2, 8], "x": 8.75, "y": 2 },
                { "matrix": [2, 9], "x": 9.75, "y": 2 },
                { "matrix": [2, 10], "x": 10.75, "y": 2 },
                { "matrix": [2, 11], "x": 11.75, "y": 2 },
                { "matrix": [2, 12], "x": 12.75, "y": 2 },
                { "h": 2, "matrix": [2, 13], "w": 1.25, "x": 13.75, "y": 1 },
                { "matrix": [3, 0], "w": 1.25, "x": 0, "y": 3 },
                { "matrix": [3, 1], "x": 1.25, "y": 3 },
                { "matrix": [3, 2], "x": 2.25, "y": 3 },
                { "matrix": [3, 3], "x": 3.25, "y": 3 },
                { "matrix": [3, 4], "x": 4.25, "y": 3 },
                { "matrix": [3, 5], "x": 5.25, "y": 3 },
                { "matrix": [3, 6], "x": 6.25, "y": 3 },
                { "matrix": [3, 7], "x": 7.25, "y": 3 },
                { "matrix": [3, 8], "x": 8.25, "y": 3 },
                { "matrix": [3, 9], "x": 9.25, "y": 3 },
                { "matrix": [3, 10], "x": 10.25, "y": 3 },
                { "matrix": [3, 11], "x": 11.25, "y": 3 },
                { "matrix": [3, 12], "w": 1.75, "x": 12.25, "y": 3 },
                { "matrix": [3, 13], "x": 14, "y": 3 },
                { "matrix": [4, 0], "w": 1.25, "x": 0, "y": 4 },
                { "matrix": [4, 1], "w": 1.25, "x": 1.25, "y": 4 },
                { "matrix": [4, 2], "w": 1.25, "x": 2.5, "y": 4 },
                { "matrix": [4, 6], "w": 6.25, "x": 3.75, "y": 4 },
                { "matrix": [4, 10], "w": 1.25, "x": 10, "y": 4 },
                { "matrix": [4, 11], "w": 1.25, "x": 11.25, "y": 4 },
                { "matrix": [4, 12], "w": 1.25, "x": 12.5, "y": 4 },
                { "matrix": [4, 13], "w": 1.25, "x": 13.75, "y": 4 }
            ]
        },
        "LAYOUT_60_iso_tsangan": {
            "layout": [
                { "matrix": [0, 0], "x": 0, "y": 0 },
                { "matrix": [0, 1], "x": 1, "y": 0 },
                { "matrix": [0, 2], "x": 2, "y": 0 },
                { "matrix": [0, 3], "x": 3, "y": 0 },
                { "matrix": [0, 4], "x": 4, "y": 0 },
                { "matrix": [0, 5], "x": 5, "y": 0 },
                { "matrix": [0, 6], "x": 6, "y": 0 },
                { "matrix": [0, 7], "x": 7, "y": 0 },
                { "matrix": [0, 8], "x": 8, "y": 0 },
                { "matrix": [0, 9], "x": 9, "y": 0 },
                { "matrix": [0, 10], "x": 10, "y": 0 },
                { "matrix": [0, 11], "x": 11, "y": 0 },
                { "matrix": [0, 12], "x": 12, "y": 0 },
                { "matrix": [0, 13], "w": 2, "x": 13, "y": 0 },
                { "matrix": [1, 0], "w": 1.5, "x": 0, "y": 1 },
                { "matrix": [1, 1], "x": 1.5, "y": 1 },
                { "matrix": [1, 2], "x": 2.5, "y": 1 },
                { "matrix": [1, 3], "x": 3.5, "y": 1 },
                { "matrix": [1, 4], "x": 4.5, "y": 1 },
                { "matrix": [1, 5], "x": 5.5, "y": 1 },
                { "matrix": [1, 6], "x": 6.5, "y": 1 },
                { "matrix": [1, 7], "x": 7.5, "y": 1 },
                { "matrix": [1, 8], "x": 8.5, "y": 1 },
                { "matrix": [1, 9], "x": 9.5, "y": 1 },
                { "matrix": [1, 10], "x": 10.5, "y": 1 },
                { "matrix": [1, 11], "x": 11.5, "y": 1 },
                { "matrix": [1, 12], "x": 12.5, "y": 1 },
                { "matrix": [2, 0], "w": 1.75, "x": 0, "y": 2 },
                { "matrix": [2, 1], "x": 1.75, "y": 2 },
                { "matrix": [2, 2], "x": 2.75, "y": 2 },
                { "matrix": [2, 3], "x": 3.75, "y": 2 },
                { "matrix": [2, 4], "x": 4.75, "y": 2 },
                { "matrix": [2,  [...]

2023-12-04 14:21 UTC, yiancar commented
@dunk2k Do you know why the CI is unhappy? 60_iso_wkl_split_bs_rshift does exist :/

2023-12-04 14:57 UTC, dunk2k commented
> Can someone rerun the first CI I don't know why its failing

"Pull Request Labeler / triage" check would require a collaborator to investigate. Linting and Build check pass, so it's good 🙂

2023-12-04 16:58 UTC, dunk2k commented
> For the record, it's been broken by a recent merge- discussion on discord [here](https://discord.com/channels/440868230475677696/867530715192885269/1181246832790212608)

And fixed with [commit 6042094](https://github.com/qmk/qmk_firmware/commit/6042094c7549d7fda4f1e749d5b3652c2f442974) 🙂

2023-12-05 04:09 UTC, drashna requested changes

2023-12-05 04:09 UTC, drashna commented on keyboards/argyle/info.json
> +    "community_layouts": ["60_ansi", "60_ansi_split_bs_rshift", "60_ansi_tsangan", "60_tsangan_hhkb", "60_ansi_wkl", "60_ansi_wkl_split_bs_rshift", "60_hhkb", "60_iso", "60_iso_split_bs_rshift", "60_
```suggestion
    "community_layouts": [
    	"60_ansi", 
    	"60_ansi_split_bs_rshift", 
    	"60_ansi_tsangan", 
    	"60_tsangan_hhkb", 
    	"60_ansi_wkl", 
    	"60_ansi_wkl_split_bs_rshift", 
    	"60_hhkb", 
    	"60_iso", 
    	"60_iso_split_bs_rshift", 
    	"60_iso_tsangan", 
    	"60_iso_tsangan_split_bs_rshift", 
    	"60_iso_wkl", 
    	"60_iso_wkl_split_bs_rshift"
    ],
```

2023-12-05 04:09 UTC, drashna commented on keyboards/argyle/rules.mk
> +QUANTUM_LIB_SRC += i2c_master.c
```suggestion
I2C_DRIVER_REQUIRED = yes
```

2023-12-05 22:54 UTC, keyboard-magpie requested changes
Just a small one

2023-12-05 22:54 UTC, keyboard-magpie commented on keyboards/argyle/readme.md
> +
```suggestion
To put the board in bootloader, either press and hold escape as you plug in, or press the button under the spacebar as you plug in.
```

2023-12-06 14:41 UTC, keyboard-magpie approved these changes

2023-12-06 17:39 UTC, waffle87 approved these changes

2023-12-06 17:39 UTC, merged