WWA Keyboards
qmk/qmk_firmware pull request #22612
Opened 2023-12-05 04:58 UTC by spacehangover

Added support to WWA Macropads, Argentinian Keyboards

## Description

Added suppor to Helios and Kepler models
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-05 22:48 UTC, waffle87 requested changes

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/helios/config.h
This file should be removed.

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/helios/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
Please fill these fields out.

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/kepler/config.h
This file should be removed.

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/helios/keymaps/default/keymap.c
> +     */
```suggestion
```

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/helios/keymaps/via/keymap.c
> +     */
```suggestion
```

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/kepler/keymaps/default/keymap.c
> +     */
```suggestion
```

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/kepler/keymaps/via/keymap.c
> +     */
```suggestion
```

2023-12-05 22:48 UTC, waffle87 commented on keyboards/wwa/kepler/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
Please fill these fields out.

2023-12-06 03:39 UTC, waffle87 requested changes
As these are both handwired keyboards, the `wwa` directory should be moved under `keyboards/handwired`.

2023-12-06 03:39 UTC, waffle87 commented on keyboards/wwa/helios/readme.md
> +* Hardware Availability: https://www.amazon.com/dp/B08ZSKMJJD/ref=sspa_dk_detail_6?psc=1&pd_rd_i=B08ZSKMJJD&pd_rd_w=K8K1X&content-id=amzn1.sym.08ba9b95-1385-44b0-b652-c46acdff309c&pf_rd_p=08ba9b95-13
```suggestion
* Hardware Availability: RP2040 Pico
```
Or any sort of link to project specific info, like a case or something.

2023-12-06 05:02 UTC, fauxpark requested changes

2023-12-06 05:02 UTC, fauxpark commented on keyboards/handwired/wwa/kepler/readme.md
> +*A short description of the keyboard/project*
```suggestion
```

2023-12-06 17:36 UTC, waffle87 approved these changes

2023-12-08 03:42 UTC, drashna approved these changes

2023-12-08 03:43 UTC, merged