[Keyboard]add luckycat70
qmk/qmk_firmware pull request #22622
Opened 2023-12-07 08:07 UTC by rhmokey

[Keyboard]add luckycat70

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-07 19:57 UTC, waffle87 requested changes

2023-12-07 19:57 UTC, waffle87 commented on keyboards/mokey/luckycat70/config.h
> +#endif
```suggestion
#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_LED_COUNT 255
#    define RGB_MATRIX_KEYPRESSES
#    define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#    define RGB_DISABLE_WHEN_USB_SUSPENDED
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#    define ENABLE_RGB_MATRIX_ALPHAS_MODS
#    define ENABLE_RGB_MATRIX_BREATHING
#endif
```

2023-12-07 19:57 UTC, waffle87 commented on keyboards/mokey/luckycat70/info.json
> +        "driver": "WS2812",
This will not build. Please test your changes before submitting them.
```suggestion
        "driver": "ws2812",
```

2023-12-07 19:57 UTC, waffle87 commented on keyboards/mokey/luckycat70/keymaps/default/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                         KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
```

2023-12-07 19:57 UTC, waffle87 commented on keyboards/mokey/luckycat70/keymaps/via/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                         KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
```

2023-12-07 19:57 UTC, waffle87 commented on keyboards/mokey/luckycat70/readme.md
> +* Hardware Supported: [rhmokey](https://github.com/rhmokey)
A link to any sort of information about the board here would be helpful.

2023-12-07 19:57 UTC, waffle87 commented on keyboards/mokey/luckycat70/rules.mk
> +
```suggestion
```

2023-12-07 20:21 UTC, zvecr requested changes

2023-12-07 20:21 UTC, zvecr commented on keyboards/mokey/luckycat70/info.json
> +        "audio": false
```suggestion
        "rgb_matrix": true
```

2023-12-07 20:21 UTC, zvecr commented on keyboards/mokey/luckycat70/info.json
> +            {"flags": 1, "matrix": [0, 0], "x": 0, "y": 0},
A flag of `1` configures as a "modifier". I very much doubt is every single key on the keyboard.

2023-12-07 20:21 UTC, zvecr commented on keyboards/mokey/luckycat70/rules.mk
> +DFU_SUFFIX_ARGS = -p FFFF -v FFFF
The readme suggests this is just copy paste from somewhere else?
```suggestion
```

2023-12-10 18:38 UTC, zvecr requested changes

2023-12-10 18:38 UTC, zvecr commented on keyboards/mokey/luckycat70/info.json
> +        "max_brightness": 255,
```suggestion
```

2023-12-12 02:46 UTC, drashna approved these changes

2023-12-12 02:49 UTC, fauxpark approved these changes

2023-12-12 03:06 UTC, merged