Add support for KLC x TGR Lena
qmk/qmk_firmware pull request #22629
Opened 2023-12-08 11:28 UTC by kopibeng

## Description
Add support for KLC x TGR Lena

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-09 05:11 UTC, waffle87 requested changes

2023-12-09 05:11 UTC, waffle87 commented on keyboards/kopibeng/tgr_lena/info.json
> +		"LAYOUT_lena": {
```suggestion
		"LAYOUT": {
```

2023-12-11 02:10 UTC, waffle87 approved these changes

2023-12-11 21:49 UTC, fauxpark approved these changes

2023-12-12 02:11 UTC, drashna approved these changes

2023-12-12 02:12 UTC, merged