Added NT Engineering 12-key Macropad
qmk/qmk_firmware pull request #22660
Opened 2023-12-14 18:12 UTC by NickTaormina

## Description

Added firmware for NT Engineering 12-key Macropad

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-16 01:57 UTC, waffle87 requested changes

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/config.h
This file should be removed, as this is the default behaviour.

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/info.json
> +        "mousekey": false,
This is preferred to be left enabled if possible.
```suggestion
        "mousekey": true,
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/info.json
> +        "brightness_steps": 17,
```suggestion
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/info.json
> +        "enabled": true,
```suggestion
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/info.json
> +        "rgblight": true
```suggestion
        "rgblight": true,
        "encoder": true
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/info.json
> +    },
```suggestion
    },
    "community_layouts": ["ortho_4x3"],
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/keymaps/default/config.h
This file should be removed.

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/keymaps/default/keymap.c
> +const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[_MAIN] = LAYOUT_ortho_4x3(KC_ENT, KC_0, KC_BSPC, KC_7, KC_8, KC_9, KC_4, KC_5, KC_6, KC_1, KC_2, KC_3), [_FN] = LAYOUT_ortho_4x3(KC_MEDI
Also in the keymap's current state, the `_FN` layer is not accessible.
```suggestion
enum layers {
  _MAIN,
  _FN
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_MAIN] = LAYOUT_ortho_4x3(
    KC_ENT, KC_0, KC_BSPC, 
    KC_7,   KC_8, KC_9,
    KC_4,   KC_5, KC_6, 
    KC_1,   KC_2, KC_3
  ),
  [_FN] = LAYOUT_ortho_4x3(
    KC_MPRV, KC_MPLY, KC_MNXT, 
    KC_CALC, KC_MYCM, KC_WHOM, 
    KC_BSLS, KC_PIPE, KC_TILDE, 
    KC_UNDO, C(KC_C), C(KC_V)
  )
};
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/rules.mk
> +
```suggestion
# This file intentionally left blank
```

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/readme.md
Please add bootloader instructions, as per [readme template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md?plain=1).

2023-12-16 01:57 UTC, waffle87 commented on keyboards/nt_engineering/macropad/macropad.c
> +        }
What exactly is the purpose of this code?

2023-12-30 18:19 UTC, waffle87 commented
I have marked a comment as unresolved that was not addressed.

2024-01-06 04:07 UTC, NickTaormina commented
> I have marked a comment as unresolved that was not addressed.

I reformatted the file to match what you put. Pushing the rotary encoder switches between the two layers, so there is no button in the keymap to swap them

2024-03-09 07:02 UTC, waffle87 requested changes

2024-03-09 07:02 UTC, waffle87 commented on keyboards/nt_engineering/macropad/macropad.c
> +void matrix_scan_user(void) {
```suggestion
void matrix_scan_kb(void) {
```

2024-03-09 07:02 UTC, waffle87 commented on keyboards/nt_engineering/macropad/macropad.c
> +    }
```suggestion
    }
    matrix_scan_user();
```

2024-03-09 07:02 UTC, waffle87 commented on keyboards/nt_engineering/macropad/macropad.c
> +}
This is the default behaviour.
```suggestion
```

2024-05-27 01:50 UTC, closed without merging