Add keyboard Ergo68
qmk/qmk_firmware pull request #22677
Opened 2023-12-16 03:47 UTC by MakotoKurauchi

## Description

Add keyboard Ergo68

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-16 04:49 UTC, zvecr requested changes

2023-12-16 04:49 UTC, zvecr commented on keyboards/yushakobo/ergo68/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
Flashing example for this keyboard:

    make yushakobo/ergo68:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (usually the top left key or Escape) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2023-12-16 04:49 UTC, zvecr commented on keyboards/yushakobo/ergo68/keymaps/via/keymap.c
> +    )
```suggestion
    )
```

2023-12-16 04:49 UTC, zvecr commented on keyboards/yushakobo/ergo68/config.h
This file should be removed, as all the contents can be migrated to `info.json`.

2023-12-16 10:07 UTC, dunk2k requested changes

2023-12-16 10:07 UTC, dunk2k commented on keyboards/yushakobo/ergo68/info.json
> +    "processor": "atmega32u4",
1. Pro micro mentioned in readme.md and confirmed in build guide
2. `5` is default value for debounce
3. removed settings in `features` that are disabled/false by default
```suggestion
    "features": {
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true,
        "rgb_matrix": true,
    },
    "development_board": "promicro",
    "diode_direction": "COL2ROW",
    "matrix_pins": {
        "cols": ["F4", "F5", "F6", "F7", "B1", "B3", "B2"],
        "rows": ["D4", "C6", "D7", "E6", "B4"]
    },
```

2023-12-16 10:07 UTC, dunk2k commented on keyboards/yushakobo/ergo68/keymaps/via/rules.mk
> +VIA_ENABLE = yes
```suggestion
VIA_ENABLE = yes

```

2023-12-16 10:24 UTC, MakotoKurauchi commented on keyboards/yushakobo/ergo68/config.h
ok

2023-12-16 10:36 UTC, MakotoKurauchi commented
Thanks for the suggestion. Please check.

2023-12-16 15:22 UTC, dunk2k requested changes

2023-12-16 15:22 UTC, dunk2k commented on keyboards/yushakobo/ergo68/keymaps/default/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
makes layer 1 functional
```suggestion
        QK_BOOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2023-12-16 15:22 UTC, dunk2k commented on keyboards/yushakobo/ergo68/keymaps/via/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
makes layer 1 functional
```suggestion
        QK_BOOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2023-12-17 02:22 UTC, waffle87 commented on keyboards/yushakobo/ergo68/info.json
> +        "led_flush_limit": 16,
```suggestion
```

2023-12-17 02:22 UTC, waffle87 commented on keyboards/yushakobo/ergo68/info.json
> +            "protocol": "serial",
```suggestion
```

2023-12-17 02:25 UTC, waffle87 approved these changes

2023-12-17 03:12 UTC, zvecr requested changes

2023-12-17 03:12 UTC, zvecr commented on keyboards/yushakobo/ergo68/info.json
> +          "speed": 127
Should avoid duplication of default values
```suggestion
          "val": 50
```

2023-12-17 07:48 UTC, fauxpark approved these changes

2023-12-17 08:39 UTC, merged