Fix Scotto61 Configurator Layout
qmk/qmk_firmware pull request #22718
Opened 2023-12-19 22:30 UTC by joe-scotto

## Description

Position of the following key is incorrect due to a `4` instead of a `1` in `info.json`.
![image](https://github.com/qmk/qmk_firmware/assets/8194147/b5e38835-987b-45c3-bb8c-39ac13cfc695)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-19 22:40 UTC, elpekenin approved these changes

2023-12-19 23:41 UTC, zvecr requested changes
While this fixes a single key position, the overall layout macro still does not match the physical layout shown in the readmes image.

2023-12-19 23:50 UTC, joe-scotto commented
@zvecr Fixe in [240829e](https://github.com/qmk/qmk_firmware/pull/22718/commits/240829ea24585b122a29dc878d0817cd5da89f72)

2023-12-20 00:09 UTC, zvecr approved these changes

2023-12-23 22:03 UTC, drashna approved these changes

2023-12-23 22:05 UTC, merged