Update momokai tap trio readme with website and image
qmk/qmk_firmware pull request #22729
Opened 2023-12-21 02:23 UTC by peepeetee

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-21 10:21 UTC, dunk2k requested changes

2023-12-21 10:21 UTC, dunk2k commented on keyboards/momokai/tap_trio/readme.md
> +![Momokai tap trio](https://i.imgur.com/xqeq75V.jpg)
```suggestion
![Momokai tap trio](https://i.imgur.com/xqeq75Vh.jpg)
```

2023-12-23 21:49 UTC, drashna requested changes

2023-12-23 21:49 UTC, drashna commented on keyboards/momokai/tap_trio/readme.md
> +https://www.momokai.com/pages/tap-trio
```suggestion
```

2024-03-08 01:47 UTC, closed without merging