add scorpio pcb
qmk/qmk_firmware pull request #22732
Opened 2023-12-21 06:56 UTC by khchen2004

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-12-22 04:01 UTC, waffle87 requested changes
SPI needs to be configured if that's what's being used for the RGB, as the firmware does not compile in it's current state. See [SPI driver doc](https://docs.qmk.fm/#/spi_driver).

2023-12-22 04:01 UTC, waffle87 commented on keyboards/kwstudio/scorpio/readme.md
> +![Scorpio](https://i.imgur.com/ikAlEQM.jpeg)
```suggestion
![Scorpio](https://i.imgur.com/ikAlEQMh.jpeg)
```

2023-12-23 14:03 UTC, dunk2k requested changes
- end of file added, where missing
- conformity to PR guidelines regarding multiple layouts

2023-12-23 14:03 UTC, dunk2k commented on keyboards/kwstudio/scorpio/info.json
> +}
```suggestion
}

```

2023-12-23 14:03 UTC, dunk2k commented on keyboards/kwstudio/scorpio/keymaps/default/keymap.c
> +[1] = LAYOUT_65_ansi_blocker_tsangan_wkl_split_bs(
```suggestion
[0] = LAYOUT_all(
    KC_ESC,   KC_1,     KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,    KC_8,      KC_9,    KC_0,      KC_MINS,   KC_EQL,   KC_BSPC,   KC_SPC, 
    KC_TAB,   KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,     KC_Y,     KC_U,    KC_I,      KC_O,    KC_P,      KC_LBRC,   KC_RBRC,  KC_BSLS,             KC_PGUP, 
    KC_CAPS,  KC_A,     KC_S,     KC_D,     KC_F,     KC_G,     KC_H,     KC_J,    KC_K,      KC_L,    KC_SCLN,   KC_QUOT,   KC_ENT,                        KC_PGDN, 
    KC_LSFT,  KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_N,     KC_M,    KC_COMM,   KC_DOT,  KC_SLSH,   KC_RSFT,                        KC_UP,    MO(1), 
    KC_LCTL,            KC_LALT,                      KC_SPC,                                          KC_RALT,                        KC_LEFT,   KC_DOWN,  KC_RGHT),
	
[1] = LAYOUT_all(
```

2023-12-23 14:03 UTC, dunk2k commented on keyboards/kwstudio/scorpio/keymaps/via/keymap.c
> +[1] = LAYOUT_65_ansi_blocker_tsangan_wkl_split_bs(
```suggestion
[0] = LAYOUT_all(
    KC_ESC,   KC_1,     KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,    KC_8,      KC_9,    KC_0,      KC_MINS,   KC_EQL,   KC_BSPC,   KC_SPC, 
    KC_TAB,   KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,     KC_Y,     KC_U,    KC_I,      KC_O,    KC_P,      KC_LBRC,   KC_RBRC,  KC_BSLS,             KC_PGUP, 
    KC_CAPS,  KC_A,     KC_S,     KC_D,     KC_F,     KC_G,     KC_H,     KC_J,    KC_K,      KC_L,    KC_SCLN,   KC_QUOT,   KC_ENT,                        KC_PGDN, 
    KC_LSFT,  KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_N,     KC_M,    KC_COMM,   KC_DOT,  KC_SLSH,   KC_RSFT,                        KC_UP,    MO(1), 
    KC_LCTL,            KC_LALT,                      KC_SPC,                                          KC_RALT,                        KC_LEFT,   KC_DOWN,  KC_RGHT),
	
[1] = LAYOUT_all(
```

2023-12-23 14:03 UTC, dunk2k commented on keyboards/kwstudio/scorpio/info.json
> +        "LAYOUT": "LAYOUT_65_ansi_blocker_tsangan_wkl_split_bs"
```suggestion
        "LAYOUT_all": "LAYOUT_65_ansi_blocker_tsangan_wkl_split_bs"
```

2023-12-23 14:03 UTC, dunk2k commented on keyboards/kwstudio/scorpio/config.h
> +#define WS2812_PIO_USE_PIO1
```suggestion
#define WS2812_PIO_USE_PIO1

```

2023-12-23 14:50 UTC, khchen2004 commented on keyboards/kwstudio/scorpio/config.h
> +#define WS2812_PIO_USE_PIO1
Updated upon your request. Please check, thanks!

2023-12-23 21:45 UTC, drashna approved these changes

2023-12-23 23:44 UTC, fauxpark approved these changes

2023-12-24 03:34 UTC, merged