Cirque reachable calibration aide
qmk/qmk_firmware pull request #22803
Opened 2024-01-01 15:11 UTC by JohSchneider

## Description

the physical reachable range for the x/y axis can be user defined with `CIRQUE_PINNACLE_X_LOWER` etc, 
to figure out these values the new `CIRQUE_PINNACLE_REACHABLE_CALIBRATION` can be used.

a user can enable the debug console, this feature, dandomly move over the sensor to cover the whole area and then read the last min/max value set printed to the console to set those defines

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-10 16:41 UTC, KarlK90 requested changes
Thanks. LGTM except for a small nit.

2024-01-10 16:41 UTC, KarlK90 commented on drivers/sensors/cirque_pinnacle.c
> +    static uint16_t xMin = 0xffff, yMin = 0xffff, yMax = 0, xMax = 0;
```suggestion
    static uint16_t xMin = UINT16_MAX, yMin = UINT16_MAX, yMax = 0, xMax = 0;
```

Nit, the maximum values of all fixed width integer types are available as macro constants IMHO we should use them for readability.

2024-01-12 19:04 UTC, KarlK90 approved these changes

2024-01-13 08:27 UTC, drashna approved these changes

2024-01-13 08:28 UTC, merged