[Core] Allow ChibiOS `SIO` driver for `UART` driver
qmk/qmk_firmware pull request #22839
Opened 2024-01-06 19:43 UTC by KarlK90

## Description

1. Rename `SD1` UART prefix to `UART`
2. Allow usage of `SIO` driver for `UART`
3. Enable `SIO` for `UART` by default for RP2040

Untested other than compilation 

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-06 19:45 UTC, KarlK90 commented on builddefs/common_features.mk
> +    ifneq ($(filter $(MCU_SERIES),RP2040),)
I really don't like this solution, is it the best we can do?

2024-01-06 19:46 UTC, KarlK90 commented
IMHO the whole driver infrastructure scream for a makeover - but this is outside the scope of this PR.

2024-01-07 17:12 UTC, KarlK90 commented
Tested on both RP2040 and STM32F411.

2024-01-07 18:42 UTC, sigprof requested changes

2024-01-07 18:42 UTC, sigprof commented on platforms/chibios/boards/GENERIC_PROMICRO_RP2040/configs/config.h
Probably also need to add this to the `QMK_PM2040` and `QMK_BLOK` boards (which are used by converters) and enable the appropriate UARTs there, so that converted firmwares have some chance to work.

2024-01-09 22:18 UTC, KarlK90 commented on platforms/chibios/boards/GENERIC_PROMICRO_RP2040/configs/config.h
Done.

2024-01-09 22:19 UTC, KarlK90 commented on platforms/chibios/drivers/uart_sio.c
> +// clang-format off
Applied, thanks!

2024-01-09 22:19 UTC, KarlK90 commented on platforms/chibios/drivers/uart_sio.c
> +    .UARTDMACR = 0U
Applied, thanks!

2024-01-09 22:22 UTC, KarlK90 commented on platforms/chibios/drivers/uart_sio.c
> +static SIOConfig sioConfig = {SIO_DEFAULT_BITRATE, UART_CR1, UART_CR2, UART_CR3};
Thanks for the detailed comment. Just a quick reply - I've ordered some WeAct G431 dev boards as I don't have any USARTv3 boards with FIFOs. The F303 devboard I have has problems both with the sio and serial driver - I'm investigating.

2024-01-17 21:21 UTC, KarlK90 commented on platforms/chibios/drivers/uart_sio.c
> +static SIOConfig sioConfig = {SIO_DEFAULT_BITRATE, UART_CR1, UART_CR2, UART_CR3};
@sigprof The G431 boards arrived and the UART driver works just fine with the `serial` and `sio` implementation on this board. The F303 had problems due to the pin mapping. For now I opted to just enable the SIO driver for RP2040 though to keep the configuration simple.

2024-01-20 20:32 UTC, vinorodrigues commented on docs/platformdev_rp2040.md
> +| [UART driver](uart_driver.md)                                    | :heady_check_mark: using `SIO` driver          |
:heavy_check_mark:

2024-01-26 18:40 UTC, KarlK90 commented on docs/platformdev_rp2040.md
> +| [UART driver](uart_driver.md)                                    | :heady_check_mark: using `SIO` driver          |
Thanks! Committed.

2024-02-16 14:11 UTC, tzarc approved these changes

2024-02-18 11:03 UTC, zvecr commented on platforms/chibios/drivers/uart.h
```suggestion

// ======== DEPRECATED DEFINES - DO NOT USE ========
#ifdef SERIAL_DRIVER
#    define UART_DRIVER SERIAL_DRIVER
#endif
#ifdef SD1_TX_PIN
#    define UART_TX_PIN SD1_TX_PIN
#endif
#ifdef SD1_RX_PIN
#    define UART_RX_PIN SD1_RX_PIN
#endif
#ifdef SD1_CTS_PIN
#    define UART_CTS_PIN SD1_CTS_PIN
#endif
#ifdef SD1_RTS_PIN
#    define UART_RTS_PIN SD1_RTS_PIN
#endif
#ifdef SD1_TX_PAL_MODE
#    define UART_TX_PAL_MODE SD1_TX_PAL_MODE
#endif
#ifdef SD1_RX_PAL_MODE
#    define UART_RX_PAL_MODE SD1_RX_PAL_MODE
#endif
#ifdef SD1_CTS_PAL_MODE
#    define UART_RTS_PAL_MODE SD1_CTS_PAL_MODE
#endif
#ifdef SD1_RTS_PAL_MODE
#    define UART_TX_PAL_MODE SD1_RTS_PAL_MODE
#endif
#ifdef SD1_CR1
#    define UART_CR1 SD1_CR1
#endif
#ifdef SD1_CR2
#    define UART_CR2 SD1_CR2
#endif
#ifdef SD1_CR3
#    define UART_CR3 SD1_CR3
#endif
#ifdef SD1_WRDLEN
#    define UART_WRDLEN SD1_WRDLEN
#endif
#ifdef SD1_STPBIT
#    define UART_STPBIT SD1_STPBIT
#endif
#ifdef SD1_PARITY
#    define UART_PARITY SD1_PARITY
#endif
#ifdef SD1_ATFLCT
#    define UART_ATFLCT SD1_ATFLCT
#endif
// ========

```

2024-02-20 10:33 UTC, KarlK90 commented on platforms/chibios/drivers/uart.h
Thanks!

2024-02-20 10:34 UTC, merged