[Keyboard] Add dnworks numpad
qmk/qmk_firmware pull request #22882
Opened 2024-01-10 12:14 UTC by itsme-zeix

## Description

Added support for dnworks numpad rev1. Thank you!
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-13 08:08 UTC, drashna commented on keyboards/dnworks/numpad/keymaps/default/keymap.c
> +	),
```suggestion
        KC_ESC,  KC_APP,  KC_TAB,  KC_BSPC,
    
        KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
        KC_P1,   KC_P2,   KC_P3,   KC_PENT,
        KC_P0,   KC_P0,   KC_PDOT, KC_PENT
    ),
```

2024-01-13 08:16 UTC, drashna requested changes

2024-01-13 08:16 UTC, drashna commented on keyboards/dnworks/numpad/keymaps/via/keymap.c
> +	),
```suggestion
[0] = LAYOUT_ortho_6x4(
        KC_ESC,  KC_APP,  KC_TAB,  KC_BSPC,
    
        KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
        KC_P1,   KC_P2,   KC_P3,   KC_PENT,
        KC_P0,   KC_P0,   KC_PDOT, KC_PENT
    ),
```

2024-01-13 08:16 UTC, drashna commented on keyboards/dnworks/numpad/keymaps/default/keymap.c
> +	),
```suggestion
[0] = LAYOUT_ortho_6x4(
        KC_ESC,  KC_APP,  KC_TAB,  KC_BSPC,
    
        KC_NUM,  KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
        KC_P1,   KC_P2,   KC_P3,   KC_PENT,
        KC_P0,   KC_P0,   KC_PDOT, KC_PENT
    ),
```

2024-01-13 08:16 UTC, drashna commented on keyboards/dnworks/numpad/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_ortho_6x4": {
```

2024-01-13 08:16 UTC, drashna commented on keyboards/dnworks/numpad/info.json
> +        }
```suggestion
        },
        "LAYOUT_numpad_6x4": {
            "layout": [
                { "matrix": [0, 0], "x": 0, "y": 0 },
                { "matrix": [0, 1], "x": 1, "y": 0 },
                { "matrix": [0, 2], "x": 2, "y": 0 },
                { "matrix": [0, 3], "x": 3, "y": 0 },
                { "matrix": [1, 0], "x": 0, "y": 1.25 },
                { "matrix": [1, 1], "x": 1, "y": 1.25 },
                { "matrix": [1, 2], "x": 2, "y": 1.25 },
                { "matrix": [6, 3], "x": 3, "y": 1.25 },
                { "matrix": [2, 0], "x": 0, "y": 2.25 },
                { "matrix": [2, 1], "x": 1, "y": 2.25 },
                { "matrix": [2, 2], "x": 2, "y": 2.25 },
                { "matrix": [3, 0], "x": 0, "y": 3.25 },
                { "matrix": [3, 1], "x": 1, "y": 3.25 },
                { "matrix": [3, 2], "x": 2, "y": 3.25 },
                { "matrix": [3, 3], "x": 3, "y": 2.25, "h": 2 },
                { "matrix": [4, 0], "x": 0, "y": 4.25 },
                { "matrix": [4, 1], "x": 1, "y": 4.25 },
                { "matrix": [4, 2], "x": 2, "y": 4.25 },
                { "matrix": [5, 0], "x": 0, "y": 5.25, "w": 2 },
                { "matrix": [5, 2], "x": 2, "y": 5.25 },
                { "matrix": [5, 3], "x": 3, "y": 4.25, "h": 2 }
            ]
        }
```

2024-01-13 08:16 UTC, drashna commented on keyboards/dnworks/numpad/info.json
> +    "layouts": {
```suggestion
    "community_layouts": [
        "numpad_6x4",
        "ortho_6x4"
    },
    "layouts": {
```

2024-01-23 17:22 UTC, itsme-zeix commented
@drashna Small bump for a review! Requested changes have been made.

2024-02-01 07:51 UTC, drashna approved these changes

2024-02-01 17:13 UTC, itsme-zeix commented on keyboards/dnworks/numpad/info.json
Thanks for the review, change made as requested!

2024-02-01 21:09 UTC, fauxpark approved these changes

2024-02-02 15:36 UTC, waffle87 approved these changes

2024-02-02 15:37 UTC, merged