initial
qmk/qmk_firmware pull request #22921
Opened 2024-01-19 01:24 UTC by waffle87

## Description

* Adds `NO_ACTION_ONESHOT` to reduce size (macropad, so not much functionality lost)
* Moves RGB matrix configuration to data drive
* Moves duplicate keymaps and configuration to top level folder
* Other misc tidying

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-19 01:50 UTC, zvecr requested changes

2024-01-19 01:50 UTC, zvecr commented on keyboards/doio/kb16/config.h
> +#endif
This shouldnt be added back after it was just migrated
```suggestion
```

2024-01-19 01:50 UTC, zvecr commented on keyboards/doio/kb16/config.h
> +
Not sure about this change, given rev2 has sufficient flash. 

rev1 previously had `SPACE_CADET_ENABLE = no` which has not been maintained?

2024-01-24 22:51 UTC, drashna commented on keyboards/doio/kb16/rev1/info.json
> +        "space_cadet": false,
Could probably disable grave escape, too.
```suggestion
        "grave_esc": false,
        "space_cadet": false,
```

2024-02-01 07:59 UTC, drashna approved these changes

2024-02-01 11:56 UTC, merged