[keyboard] add smk82_pro keyboard.
qmk/qmk_firmware pull request #22944
Opened 2024-01-22 03:14 UTC by jonylee1986

add smk82_pro keyboard.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-22 04:07 UTC, zvecr requested changes

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/config.h
> +#define DRIVER_ADDR_2 0b1110111
```suggestion
/* I2C Config for LED Driver */
#define SNLED27351_I2C_ADDRESS_1 SNLED27351_I2C_ADDRESS_GND
#define SNLED27351_I2C_ADDRESS_2 SNLED27351_I2C_ADDRESS_VDDIO
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/config.h
> +#define BT_MODE_ENABLE
```suggestion
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/info.json
> +        "rgblight": false
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
        "dip_switch": true,
        "encoder": true,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgb_matrix": true
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/keymaps/default/keymap.c
> +}
```suggestion
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/keymaps/via/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/keymaps/via/keymap.c
> +}
```suggestion
```

2024-01-22 04:07 UTC, zvecr commented on keyboards/steed/smk82_pro/smk82_pro.c
> +#include <stdlib.h>
```suggestion
#include "rgb_matrix.h"
```

2024-01-23 02:27 UTC, drashna requested changes

2024-01-23 02:27 UTC, drashna commented on keyboards/steed/smk82_pro/config.h
> +#define I2C1_OPMODE OPMODE_I2C
These are the default values, and don't need to be specified.
```suggestion
```

2024-01-23 02:27 UTC, drashna commented on keyboards/steed/smk82_pro/config.h
> +#define SPI_MOSI_PAL_MODE 5
```suggestion
```

2024-01-23 02:27 UTC, drashna commented on keyboards/steed/smk82_pro/keymaps/default/keymap.c
Please replace the tabs with spaces.

2024-01-23 02:27 UTC, drashna commented on keyboards/steed/smk82_pro/keymaps/via/keymap.c
same

2024-02-01 08:14 UTC, drashna commented on keyboards/steed/smk82_pro/readme.md
> +![STEED SMK82 PRO](https://github.com/jonylee1986/qmk_firmware_master/assets/108282809/42973b4e-8ed5-43d7-8379-70851c67df0f)
Please rehost on imgur or the like.

2024-03-12 18:24 UTC, drashna requested changes

2024-03-12 18:24 UTC, drashna commented on keyboards/steed/smk82_pro/readme.md
> +![STEED SMK82 PRO](https://cdn.shopifycdn.net/s/files/1/0809/0550/3006/files/SMK82WARCTIC.jpg?v=1701773689&width=1000)
Please rehost the image.

2024-03-19 01:24 UTC, jonylee1986 commented on keyboards/steed/smk82_pro/readme.md
> +![STEED SMK82 PRO](https://cdn.shopifycdn.net/s/files/1/0809/0550/3006/files/SMK82WARCTIC.jpg?v=1701773689&width=1000)
OK

2024-03-30 01:52 UTC, drashna commented on keyboards/steed/smk82_pro/smk82_pro.c
> +        }
wouldn't this work: 
```suggestion
        keymap_config.no_gui = !active;
```

2024-07-24 01:29 UTC, closed without merging