[keyboard]add monsgeek M7 keyboard.
qmk/qmk_firmware pull request #22956
Opened 2024-01-24 08:06 UTC by jonylee1986

add monsgeek M7 keyboard.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-24 09:16 UTC, dunk2k requested changes
add Community Layout support

2024-01-24 09:16 UTC, dunk2k commented on keyboards/monsgeek/m7/info.json
> +        "LAYOUT_ansi": {
```suggestion
    "community_layouts": ["68_ansi"],
    "layouts": {
        "LAYOUT_68_ansi": {
```

2024-01-24 09:16 UTC, dunk2k commented on keyboards/monsgeek/m7/keymaps/default/keymap.c
> +    [MAC_FN] = LAYOUT_ansi( /* FN */
```suggestion
    [WIN_B] = LAYOUT_68_ansi( /* Base */
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,KC_EQL,   KC_BSPC, KC_INS,  KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,KC_RBRC,  KC_BSLS, KC_DEL,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT, KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                             KC_RALT,MO(WIN_FN),KC_RCTL,         KC_LEFT, KC_DOWN, KC_RGHT),

    [WIN_FN] = LAYOUT_68_ansi( /* FN */
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11, KC_F12,   _______, _______, KC_HOME,
        _______, _______, _______, _______, _______, _______, _______, _______, KC_INS,  DF(MAC_B),KC_PSCR,RGB_SPD, RGB_SPI, _______, RGB_MOD, KC_END,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_TOG, _______, _______,          RGB_HUI,
        _______, _______, _______, KC_CALC, _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,                   _______, RGB_VAI,
        _______, GU_TOGG, _______,                   _______,                            _______, _______, _______,          RGB_SAD, RGB_VAD, RGB_SAI),

    [MAC_B] = LAYOUT_68_ansi( /* Base */
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,KC_EQL,   KC_BSPC, KC_INS,  KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,KC_RBRC,  KC_BSLS, KC_DEL,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT, KC_UP,
        KC_LCTL, KC_LALT, KC_LGUI,                   KC_SPC,                             KC_RGUI,MO(MAC_FN),KC_RCTL,         KC_LEFT, KC_DOWN, KC_RGHT),

    [MAC_FN] = LAYOUT_68_ansi( /* FN */
```

2024-01-24 09:16 UTC, dunk2k commented on keyboards/monsgeek/m7/keymaps/via/keymap.c
> +    [MAC_FN] = LAYOUT_ansi( /* FN */
```suggestion
    [WIN_B] = LAYOUT_68_ansi( /* Base */
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,KC_EQL,   KC_BSPC, KC_INS,  KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,KC_RBRC,  KC_BSLS, KC_DEL,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT, KC_UP,
        KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPC,                             KC_RALT,MO(WIN_FN),KC_RCTL,         KC_LEFT, KC_DOWN, KC_RGHT),

    [WIN_FN] = LAYOUT_68_ansi( /* FN */
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11, KC_F12,   _______, _______, KC_HOME,
        _______, _______, _______, _______, _______, _______, _______, _______, KC_INS,  DF(MAC_B),KC_PSCR,RGB_SPD, RGB_SPI, _______, RGB_MOD, KC_END,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, RGB_TOG, _______, _______,          RGB_HUI,
        _______, _______, _______, KC_CALC, _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,                   _______, RGB_VAI,
        _______, GU_TOGG, _______,                   _______,                            _______, _______, _______,          RGB_SAD, RGB_VAD, RGB_SAI),

    [MAC_B] = LAYOUT_68_ansi( /* Base */
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,KC_EQL,   KC_BSPC, KC_INS,  KC_PGUP,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,KC_RBRC,  KC_BSLS, KC_DEL,  KC_PGDN,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,                   KC_RSFT, KC_UP,
        KC_LCTL, KC_LALT, KC_LGUI,                   KC_SPC,                             KC_RGUI,MO(MAC_FN),KC_RCTL,         KC_LEFT, KC_DOWN, KC_RGHT),

    [MAC_FN] = LAYOUT_68_ansi( /* FN */
```

2024-01-24 09:20 UTC, dunk2k requested changes

2024-01-24 09:20 UTC, dunk2k commented on keyboards/monsgeek/m7/readme.md
> +A customizable 65% keyboard.
```suggestion
A customizable 65% (68 key) keyboard.
```

2024-01-24 09:20 UTC, dunk2k commented on keyboards/monsgeek/m7/info.json
> +}
```suggestion
}

```

2024-01-24 09:20 UTC, dunk2k commented on keyboards/monsgeek/m7/readme.md
> +![M7](https://github.com/jonylee1986/qmk_firmware_master/assets/108282809/b9d54e20-7691-489b-903b-c3e40744e583)
Could this image be (re-)hosted on Imgur?

2024-01-24 09:20 UTC, dunk2k commented on keyboards/monsgeek/m7/rules.mk
> +# This file intentionally left blank
```suggestion
# This file intentionally left blank

```

2024-03-12 18:29 UTC, drashna commented on keyboards/monsgeek/m7/readme.md
> +![M7](https://www.monsgeek.com/wp-content/uploads/2023/12/M7-VIA-Main-1.png)
Pleasn  rehost this on imgur or the like

2024-03-12 18:29 UTC, drashna commented on keyboards/monsgeek/m7/keymaps/via/keymap.c
> +bool process_record_user(uint16_t keycode, keyrecord_t *record)
These should be moved to the kb file, and use the kb functions

2024-03-19 09:10 UTC, fauxpark commented
@jonylee1986 please stop merging master on your PRs. There is absolutely no need to do this unless there are conflicts to resolve.

2024-03-29 02:44 UTC, drashna approved these changes

2024-05-15 04:11 UTC, fauxpark requested changes

2024-05-15 04:11 UTC, fauxpark commented on keyboards/monsgeek/m7/config.h
> +
```suggestion
```

2024-06-03 06:45 UTC, fauxpark requested changes

2024-06-03 06:45 UTC, fauxpark commented on keyboards/monsgeek/m7/rules.mk
This file can be deleted.

2024-06-03 06:45 UTC, fauxpark commented on keyboards/monsgeek/m7/info.json
This file should be renamed to `keyboard.json`.

2024-08-26 10:43 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-11-06 04:26 UTC, fauxpark requested changes

2024-11-06 04:26 UTC, fauxpark commented on keyboards/monsgeek/m7/readme.md
> +[![M7](https://s21.ax1x.com/2024/03/19/pFRg3cT.png)](https://imgse.com/i/pFRg3cT)
```suggestion
![M7](https://s21.ax1x.com/2024/03/19/pFRg3cT.png)
```

2024-11-22 13:08 UTC, fauxpark requested changes
`RGB_` -> `RM_` keycodes after this round of breaking changes.

2024-11-22 13:08 UTC, fauxpark commented on keyboards/monsgeek/m7/keymaps/default/keymap.c
> +        _______, GU_TOGG, _______,                   _______,                            _______, _______, _______,          RGB_SAD, RGB_VAD, RGB_SAI),
```suggestion
        _______, _______, _______, _______, _______, _______, _______, _______, KC_INS,  DF(MAC_B),KC_PSCR,RM_SPDD, RM_SPDU, _______, RM_NEXT, KC_END,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, RM_TOGG, _______, _______,          RM_HUEU,
        _______, _______, _______, KC_CALC, _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,                   _______, RM_VALU,
        _______, GU_TOGG, _______,                   _______,                            _______, _______, _______,          RM_SATD, RM_VALD, RM_SATU),
```

2024-11-22 13:08 UTC, fauxpark commented on keyboards/monsgeek/m7/keymaps/default/keymap.c
> +        _______, _______, _______,                   _______,                            _______, _______, _______,          RGB_SAD, RGB_VAD, RGB_SAI),
```suggestion
        _______, _______, _______, _______, _______, _______, _______, _______, KC_INS,  DF(WIN_B),KC_PSCR,RM_SPDD, RM_SPDU, _______, RM_NEXT, KC_END,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, RM_TOGG, _______, _______,          RM_HUEU,
        _______, _______, _______, KC_CALC, _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,                   _______, RM_VALU,
        _______, _______, _______,                   _______,                            _______, _______, _______,          RM_SATD, RM_VALD, RM_SATU),
```

2024-11-22 13:08 UTC, fauxpark commented on keyboards/monsgeek/m7/m7.c
> +    case RGB_TOG:
```suggestion
    case RM_TOGG:
```

2025-07-06 05:21 UTC, fauxpark approved these changes

2025-07-06 05:39 UTC, zvecr commented on keyboards/monsgeek/m7/halconf.h
> +#define SPI_SELECT_MODE SPI_SELECT_MODE_PAD
```suggestion
```

2025-07-06 05:39 UTC, zvecr commented on keyboards/monsgeek/m7/keyboard.json
> +        "console": false,
```suggestion
```

2025-07-06 05:39 UTC, zvecr commented on keyboards/monsgeek/m7/keyboard.json
> +        "force_nkro": true,
```suggestion
```

2025-07-06 05:40 UTC, zvecr commented on keyboards/monsgeek/m7/keyboard.json
> +    "url": "",
```suggestion
    "host": {
        "default": {
            "nkro": true
        }
    },
```

2025-09-21 02:12 UTC, closed without merging