[keyboard] mechwild/bb40
qmk/qmk_firmware pull request #22958
Opened 2024-01-25 03:02 UTC by lesshonor

## Description

Adds MechWild's [bb40](https://mechwild.com/product/bb40) to the main QMK repo.

The code has been publicly available for about six months, so I've added a `LAYOUT` alias to avoid breaking out-of-tree keymaps.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-25 09:30 UTC, dunk2k requested changes

2024-01-25 09:30 UTC, dunk2k commented on keyboards/mechwild/bb40/readme.md
very quick piece: would it be possible to accommodate the novice user with addition of a small paragraph regarding when to compile for `f401` or `f411`?

2024-01-25 14:45 UTC, dunk2k approved these changes

2024-03-15 05:04 UTC, drashna requested changes
Only caveat here, is that weact now has a 8MHz crystal variant, too...  But that doesn't effect this PR.

2024-03-15 05:05 UTC, drashna approved these changes

2024-03-29 01:21 UTC, merged