Add str_studio cadence_16 keyboard
qmk/qmk_firmware pull request #22960
Opened 2024-01-25 21:11 UTC by str-studio

## Description

Add str_studio cadence_16 keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-26 06:35 UTC, fauxpark requested changes

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/cadence_16.c
This file can be deleted.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/config.h
> +
```suggestion
```

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/info.json
> +    },
```suggestion
    },
    "matrix_pins": {
        "cols" ["B6", "B5", "B4", "D7"],
        "rows": ["F0", "F6", "F5", "F4", "F1"]
    },
    "diode_direction": "COL2ROW",
```

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keyboard_layout-default.json
Please remove this file.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/cadence_16.h
This file can be deleted.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keyboard_layout_with_encoder.json
Please remove this file.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/default/config.h
This file can be deleted.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +#endif
This should use Encoder Map instead.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +#include "oled.c"
Do not include .c files in other .c files.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/default/readme.md
This file can be deleted.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/str-vial/config.h
This entire VIAL keymap must be deleted.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/via/config.h
> +#define DISABLE_LEADER     // 0
```suggestion
```

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/keymaps/via/encoder.c
VIA supports Encoder Map; there is no need for this. Please remove it.

2024-01-26 06:35 UTC, fauxpark commented on keyboards/str_studio/cadence_16/rules.mk
> +
```suggestion
```

2024-01-26 09:32 UTC, fauxpark requested changes

2024-01-26 09:32 UTC, fauxpark commented on keyboards/str_studio/cadence_16/cadence_16.h
This file should be deleted. You already have matrix positions defined in info.json. If they are incorrect, you need to fix them there instead.

2024-01-26 09:32 UTC, fauxpark commented on keyboards/str_studio/cadence_16/info.json
Please run `qmk format-json -i` on this file.

2024-01-26 09:58 UTC, str-studio commented on keyboards/str_studio/cadence_16/info.json
Thanks for the suggestions!

2024-01-27 00:19 UTC, zvecr requested changes

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +
```suggestion
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/oled.c
This file is not being compiled, and should be removed.

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +#    define ANIM_SIZE           128   // number of bytes in array. If you change sprites, minimize for adequate firmware size. max is 1024
```suggestion
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +    // oled_write_P(PSTR("\n\n"), false);
```suggestion
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +
```suggestion
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +    }
```suggestion
    print_status_narrow();
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/keymaps/default/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
OLED_ENABLE = yes
ENCODER_MAP_ENABLE = yes
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/readme.md
> +Enter the bootloader in 3 ways:
```suggestion
Enter the bootloader in 2 ways:
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/rules.mk
> +MIDI_ENABLE = yes
```suggestion
# This file intentionally left blank
```

2024-01-27 00:19 UTC, zvecr commented on keyboards/str_studio/cadence_16/info.json
> +    },
```suggestion
    },
    "features": {
        "bootmagic": true,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "encoder": true
    },
```

2024-01-27 00:54 UTC, fauxpark requested changes

2024-01-27 00:54 UTC, fauxpark commented on keyboards/str_studio/cadence_16/info.json
> +    },
```suggestion
    },
    "qmk": {
        "tap_keycode_delay": 10
    },
```

2024-01-27 00:54 UTC, fauxpark commented on keyboards/str_studio/cadence_16/config.h
> +
```suggestion
```

2024-01-31 02:53 UTC, str-studio commented
Hey @fauxpark @zvecr, really appreciate for your suggestions. I was wondering if you could help review the code again? So that it can be able merge into the repo. 🙏

2024-01-31 04:50 UTC, fauxpark approved these changes

2024-02-01 12:06 UTC, str-studio commented
Hello @zvecr , 

I hope you're doing well. Just circling back to the review request that's been waiting in the pipeline for a few days. I totally understand how packed your schedule must be, and I appreciate your time in reviewing the code.

Following your valuable advice, I've updated the code accordingly. If you could find a moment to approve this pull request, it would be great. It'll allow us to integrate the keyboard and keymap files into the official firmware, giving users the ability to utilize and personalize them as per their needs.

Thanks a lot in advance for your help with this. Really appreciate it!

2024-02-25 09:42 UTC, str-studio commented
@zvecr Hi, Joel. Any updates for this MR? It has been idling for several weeks, feel free to lmk if anything need to be fixed? I'd appreciate it

2024-03-12 18:49 UTC, drashna commented on keyboards/str_studio/cadence_16/keymaps/default/keymap.c
> +#ifdef OLED_ENABLE
Ideally, the oled code should be in the keyboard's c file, so there is a default behavior (eg when it's compiled by the configurator, etc). And use the kb function.

2024-05-27 01:50 UTC, closed without merging