Update ScottoAlp handwired keyboard to 12 column layout
qmk/qmk_firmware pull request #22962
Opened 2024-01-26 03:59 UTC by joe-scotto

## Description

Added extra pins and keys for a 12-column layout. Because this board is handwired, I am just using `LAYOUT` and the extra columns can be left off or added depending on the variant.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-12 18:49 UTC, drashna approved these changes

2024-03-12 22:19 UTC, fauxpark requested changes
Keyboard updates must go through `develop`.

2024-03-13 15:32 UTC, joe-scotto commented
@fauxpark I changed the target branch to `develop`, is that all that needs to change?

2024-03-13 22:13 UTC, fauxpark requested changes

2024-03-13 22:13 UTC, fauxpark commented on keyboards/scottokeebs/scotto34/info.json
> +        ],
```suggestion
        "cols": ["GP9", "GP10", "GP11", "GP12", "GP13", "GP18", "GP19", "GP20", "GP21", "GP22"],
```

2024-03-13 22:13 UTC, fauxpark commented on keyboards/scottokeebs/scotto34/info.json
> +            "rgb_test": true,
```suggestion
```

2024-03-13 22:41 UTC, fauxpark approved these changes

2024-03-15 05:03 UTC, merged