Add FS streampad
qmk/qmk_firmware pull request #22991
Opened 2024-01-30 20:07 UTC by SmollChungus

## Description

Addition of the FS streampad firmware

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-01-30 20:27 UTC, waffle87 requested changes

2024-01-30 20:27 UTC, waffle87 commented on keyboards/fs_streampad/config.h
> +#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
```suggestion
```

2024-01-30 20:27 UTC, waffle87 commented on keyboards/fs_streampad/info.json
> +        },
```suggestion
        },
        "default": {
            "animation": "cycle_left_right"
        },
```

2024-01-30 20:27 UTC, waffle87 commented on keyboards/fs_streampad/readme.md
> +========
```suggestion
# FS streampad
```

2024-01-31 02:21 UTC, waffle87 approved these changes

2024-01-31 02:26 UTC, fauxpark approved these changes

2024-01-31 03:35 UTC, drashna approved these changes

2024-01-31 03:35 UTC, merged