[keyboard] add bear_face/v3, bear_face keyboard folder maintenance
qmk/qmk_firmware pull request #23017
Opened 2024-02-04 17:08 UTC by will-hedges

## Description

* Added `bear_face/v3`
* Updated `info.json`s, keymaps to include `LAYOUT`, `LAYOUT_all` where applicable
* Updated bootloader options, imgur link in readme
* Updated keyboard-level files to be consistent with PR checklist
* Updated copyrights with github username

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-15 08:02 UTC, drashna requested changes

2024-03-15 08:02 UTC, drashna commented on keyboards/bear_face/v3/keymaps/default/keymap.c
> +            }
```suggestion
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWER);
            }
            break;
        case BASE_COLE:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_COLE);
            }
            break;
        case BASE_DVOR:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_DVOR);
            }
```

2024-03-15 08:02 UTC, drashna commented on keyboards/bear_face/v3/keymaps/default/readme.md
This can be removed.

2024-03-15 08:02 UTC, drashna commented on keyboards/bear_face/v3/keymaps/default_iso/keymap.c
> +            }
```suggestion
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWER);
            }
            break;
        case BASE_COLE:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_COLE);
            }
            break;
        case BASE_DVOR:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_DVOR);
            }
```

2024-03-15 08:02 UTC, drashna commented on keyboards/bear_face/v3/keymaps/default_iso/readme.md
Should be removed.

2024-06-06 20:49 UTC, will-hedges commented
Awaiting for re-review, commenting to keep PR open

2024-06-18 00:14 UTC, will-hedges commented
Not sure what happened to this branch but will close and re-open off a fresh `master` branch

2024-06-18 00:14 UTC, closed without merging