Fix Caps Lock indication on Valhalla v2
qmk/qmk_firmware pull request #23012
Opened 2024-02-03 23:15 UTC by Gondolindrim

## Description

Fixes Caps Lock indication on Valhalla V2 . The PCB suffers from the same problem than the Albatross PCB (see https://github.com/qmk/qmk_firmware/pull/22941) where the backlight feature, when paired with backlight as caps lock, gives a unwanted behavior.

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-29 01:38 UTC, drashna approved these changes

2024-05-13 02:30 UTC, Gondolindrim commented
Guys can we please take a look at this

2024-05-14 22:59 UTC, drashna requested changes

2024-05-14 22:59 UTC, drashna commented on keyboards/noxary/valhalla_v2/valhalla_v2.c
> +    (led_state.caps_lock && backlight_config.enable) ? backlight_set(backlight_config.level) : backlight_set(0);
```suggestion
    (led_state.caps_lock && is_backlight_enabled()) ? backlight_set(get_backlight_level()) : backlight_set(0);
```

2024-05-14 22:59 UTC, drashna commented on keyboards/noxary/valhalla_v2/valhalla_v2.c
> +extern backlight_config_t backlight_config;
```suggestion
```

2024-07-15 00:15 UTC, drashna approved these changes

2024-10-07 04:28 UTC, tzarc approved these changes

2024-10-07 04:29 UTC, merged