add new pcb - chlx ppr merro
qmk/qmk_firmware pull request #23014
Opened 2024-02-04 03:03 UTC by gaclee3b

## Description

Adding new 60% pcb variant.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-04 03:31 UTC, fauxpark requested changes

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/keymaps/default/keymap.c
> +  _______, _______,                   _______, _______, _______, _______,          _______, _______, _______, _______),
```suggestion
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/keymaps/via/keymap.c
> +  _______, _______,                   _______, _______, _______, _______,          _______, _______, _______, _______),
```suggestion
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/readme.md
> +![ppr.merro60 PCB](https://i.imgur.com/xyQA68X.jpg)
```suggestion
![ppr.merro60 PCB](https://i.imgur.com/xyQA68Xh.jpg)
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/readme.md
> +Hardware Supported: chlx PCB ppr.merro60.x.x.x
```suggestion
* Keyboard Maintainer: [Alexander Lee](https://github.com/gaclee3b)
* Hardware Supported: chlx PCB ppr.merro60.x.x.x
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/info.json
> +    "diode_direction": "ROW2COL",
```suggestion
    "diode_direction": "ROW2COL",
    "indicators": {
        "caps_lock": "C7",
        "scroll_lock": "F0",
        "on_state": 0
    },
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/info.json
> +    "bootloader": "atmel-dfu",
```suggestion
    "bootloader": "atmel-dfu",
    "community_layouts": [
        "60_ansi",
        "60_ansi_split_bs_rshift",
        "60_hhkb",
        "60_iso",
        "60_tsangan_hhkb"
    ],
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/info.json
> +    "maintainer": "gaclee3b",
```suggestion
    "maintainer": "gaclee3b",
    "features": {
        "bootmagic": true,
        "mousekey": true,
        "extrakey": true,
        "console": false,
        "command": false,
        "nkro": true,
        "backlight": false,
        "rgblight": false,
        "audio": false
    },
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/rules.mk
> +Layouts = 60_ansi 60_ansi_split_bs_rshift 60_hhkb 60_iso 60_tsangan_hhkb
```suggestion
# This file intentionally left blank
```

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/ppr_merro60.c
This file can be deleted.

2024-02-04 03:31 UTC, fauxpark commented on keyboards/chlx/ppr_merro60/info.json
Please run `qmk format-json -i` on this file.

2024-02-04 04:34 UTC, gaclee3b commented on keyboards/chlx/ppr_merro60/ppr_merro60.c
deleting

2024-02-04 04:38 UTC, gaclee3b commented on keyboards/chlx/ppr_merro60/info.json
ran qmk format-json -i on info.json file after pulling previous info.json content updates. pushing latest info.json

2024-02-04 04:39 UTC, zvecr commented on keyboards/chlx/ppr_merro60/readme.md
> +See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to Q
```suggestion
Make example for this keyboard (after setting up your build environment):

    make chlx/ppr_merro60:default

Flashing example for this keyboard:

    make chlx/ppr_merro60:default:flash

See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

## Bootloader

Enter bootloader mode by any of the following options -
- When unplugged, holding the top-left key (typically ESC) while plugging in the keyboard
- When plugged in, pressing and releasing the reset button on the pcb bottom behind the CAPSLOCK / A-key region
- When plugged in, shorting out the two reset metal contacts near the 'z' key (accessible through the switch LED slot)
```

2024-02-04 10:14 UTC, dunk2k requested changes
adds Community Layout support

2024-02-04 10:14 UTC, dunk2k commented on keyboards/chlx/ppr_merro60/info.json
> +    "community_layouts": ["60_ansi", "60_hhkb", "60_iso", "60_tsangan_hhkb"],
```suggestion
    "community_layouts": ["60_ansi", "60_ansi_split_bs_rshift", "60_ansi_tsangan", "60_tsangan_hhkb", "60_ansi_wkl", "60_ansi_wkl_split_bs_rshift", "60_hhkb", "60_iso", "60_iso_split_bs_rshift", "60_iso_tsangan", "60_iso_tsangan_split_bs_rshift", "60_iso_wkl", "60_iso_wkl_split_bs_rshift"],
```

2024-02-04 10:14 UTC, dunk2k commented on keyboards/chlx/ppr_merro60/info.json
> +        },
```suggestion
        },
        "LAYOUT_60_ansi_split_bs_rshift": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [1, 0], "x": 2, "y": 0},
                {"matrix": [1, 1], "x": 3, "y": 0},
                {"matrix": [2, 0], "x": 4, "y": 0},
                {"matrix": [2, 1], "x": 5, "y": 0},
                {"matrix": [3, 0], "x": 6, "y": 0},
                {"matrix": [3, 1], "x": 7, "y": 0},
                {"matrix": [4, 0], "x": 8, "y": 0},
                {"matrix": [4, 1], "x": 9, "y": 0},
                {"matrix": [5, 0], "x": 10, "y": 0},
                {"matrix": [5, 1], "x": 11, "y": 0},
                {"matrix": [6, 0], "x": 12, "y": 0},
                {"matrix": [6, 1], "x": 13, "y": 0},
                {"matrix": [6, 9], "x": 14, "y": 0},
                {"matrix": [0, 2], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [0, 3], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [2, 2], "x": 4.5, "y": 1},
                {"matrix": [2, 3], "x": 5.5, "y": 1},
                {"matrix": [3, 2], "x": 6.5, "y": 1},
                {"matrix": [3, 3], "x": 7.5, "y": 1},
                {"matrix": [4, 2], "x": 8.5, "y": 1},
                {"matrix": [4, 3], "x": 9.5, "y": 1},
                {"matrix": [5, 2], "x": 10.5, "y": 1},
                {"matrix": [5, 3], "x": 11.5, "y": 1},
                {"matrix": [6, 2], "x": 12.5, "y": 1},
                {"matrix": [6, 3], "x": 13.5, "y": 1, "w": 1.5},
                {"matrix": [0, 4], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [0, 5], "x": 1.75, "y": 2},
                {"matrix": [1, 4], "x": 2.75, "y": 2},
                {"matrix": [1, 5], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [3, 4], "x": 6.75, "y": 2},
                {"matrix": [3, 5], "x": 7.75, "y": 2},
                {"matrix": [4, 4], "x": 8.75, "y": 2},
                {"matrix": [4, 5], "x": 9.75, "y": 2},
                {"matrix": [5, 4], "x": 10.75, "y": 2},
                {"matrix": [5, 5], "x": 11.75, "y": 2},
                {"matrix": [6, 5], "x": 12.75, "y": 2, "w": 2.25},
                {"matrix": [0, 6], "x": 0, "y": 3, "w": 2.25},
                {"matrix": [1, 6], "x": 2.25, "y": 3},
                {"matrix": [1, 7], "x": 3.25, "y": 3},
                {"matrix": [2, 6], "x": 4.25, "y": 3},
                {"matrix": [2, 7], "x": 5.25, "y": 3},
                {"matrix": [3, 6], "x": 6.25, "y": 3},
                {"matrix": [3, 7], "x": 7.25, "y": 3},
                {"matrix": [4, 6], "x": 8.25, "y": 3},
                {"matrix": [4, 7], "x": 9.25, "y": 3},
                {"matrix": [5, 6], "x": 10.25, "y": 3},
                {"matrix": [5, 7], "x": 11.25, "y": 3},
                {"matrix": [6, 6], "x": 12.25, "y": 3, "w": 1.75},
                {"matrix": [6, 7], "x": 14, "y": 3},
                {"matrix": [0, 9], "x": 0, "y": 4, "w": 1.25},
                {"matrix": [0, 8], "x": 1.25, "y": 4, "w": 1.25},
                {"matrix": [2, 9], "x": 2.5, "y": 4, "w": 1.25},
                {"matrix": [3, 8], "x": 3.75, "y": 4, "w": 6.25},
                {"matrix": [4, 9], "x": 10, "y": 4, "w": 1.25},
                {"matrix": [5, 8], "x": 11.25, "y": 4, "w": 1.25},
                {"matrix": [5, 9], "x": 12.5, "y": 4, "w": 1.25},
                {"matrix": [6, 8], "x": 13.75, "y": 4, "w": 1.25}
            ]
        },
        "LAYOUT_60_ansi_tsangan": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [1, 0], "x": 2, "y": 0},
                {"matrix": [1, 1], "x": 3, "y": 0},
                {"matrix": [2, 0], "x": 4, "y": 0},
                {"matrix": [2, 1], "x": 5, "y": 0},
                {"matrix": [3, 0], "x": 6, "y": 0},
                {"matrix": [3, 1], "x": 7, "y": 0},
                {"matrix": [4, 0], "x": 8, "y": 0},
                {"matrix": [4, 1], "x": 9, "y": 0},
                {"matrix": [5, 0], "x": 10, "y": 0},
                {"matrix": [5, 1], "x": 11, "y": 0},
                {"matrix": [6, 0], "x": 12, "y": 0},
                {"matrix": [6, 1], "x": 13, "y": 0, "w": 2},
                {"matrix": [0, 2], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [0, 3], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [2, 2], "x": 4.5, "y": 1},
                {"matrix": [2, 3], "x": 5.5, "y": 1},
                {"matrix": [3, 2], "x": 6.5, "y": 1},
                {"matrix": [3, 3], "x": 7.5, "y": 1},
                {"matrix": [4, 2], "x": 8.5, "y": 1},
                {"matrix": [4, 3], "x": 9.5, "y": 1},
                {"matrix": [5, 2], "x": 10.5, "y": 1},
                {"matrix": [5, 3], "x": 11.5, "y": 1},
                {"matrix": [6, 2], "x": 12.5, "y": 1},
                {"matrix": [6, 3], "x": 13.5, "y": 1, "w": 1.5},
                {"matrix": [0, 4], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [0, 5], "x": 1.75, "y": 2},
                {"matrix": [1, 4], "x": 2.75, "y": 2},
                {"matrix": [1, 5], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [3, 4], "x": 6.75, "y": 2},
                {"matrix": [3, 5], "x": 7.75, "y": 2},
                {"matrix": [4, 4], "x": 8.75, "y": 2},
                {"matrix": [4, 5], "x": 9.75, "y": 2},
                {"matrix": [5, 4], "x": 10.75, "y": 2},
                {"matrix": [5, 5], "x": 11.75, "y": 2},
                {"matrix": [6, 5], "x": 12.75, "y": 2, "w": 2.25},
                {"matrix": [0, 6], "x": 0, "y": 3, "w": 2.25},
                {"matrix": [1, 6], "x": 2.25, "y": 3},
                {"matrix": [1, 7], "x": 3.25, "y": 3},
                {"matrix": [2, 6], "x": 4.25, "y": 3},
                {"matrix": [2, 7], "x": 5.25, "y": 3},
                {"matrix": [3, 6], "x": 6.25, "y": 3},
                {"matrix": [3, 7], "x": 7.25, "y": 3},
                {"matrix": [4, 6], "x": 8.25, "y": 3},
                {"matrix": [4, 7], "x": 9.25, "y": 3},
                {"matrix": [5, 6], "x": 10.25, "y": 3},
                {"matrix": [5, 7], "x": 11.25, "y": 3},
                {"matrix": [6, 6], "x": 12.25, "y": 3, "w": 2.75},
                {"matrix": [0, 9], "x": 0, "y": 4, "w": 1.5},
                {"matrix": [0, 8], "x": 1.5, "y": 4},
                {"matrix": [2, 9], "x": 2.5, "y": 4, "w": 1.5},
                {"matrix": [3, 8], "x": 4, "y": 4, "w": 7},
                {"matrix": [5, 8], "x": 11, "y": 4, "w": 1.5},
                {"matrix": [5, 9], "x": 12.5, "y": 4},
                {"matrix": [6, 8], "x": 13.5, "y": 4, "w": 1.5}
            ]
        },
        "LAYOUT_60_ansi_wkl": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [1, 0], "x": 2, "y": 0},
                {"matrix": [1, 1], "x": 3, "y": 0},
                {"matrix": [2, 0], "x": 4, "y": 0},
                {"matrix": [2, 1], "x": 5, "y": 0},
                {"matrix": [3, 0], "x": 6, "y": 0},
                {"matrix": [3, 1], "x": 7, "y": 0},
                {"matrix": [4, 0], "x": 8, "y": 0},
                {"matrix": [4, 1], "x": 9, "y": 0},
                {"matrix": [5, 0], "x": 10, "y": 0},
                {"matrix": [5, 1], "x": 11, "y": 0},
                {"matrix": [6, 0], "x": 12, "y": 0},
                {"matrix": [6, 1], "x": 13, "y": 0, "w": 2},
                {"matrix": [0, 2], "x": 0, "y": 1, "w": 1.5},
                {"matr [...]

2024-02-04 10:14 UTC, dunk2k commented on keyboards/chlx/ppr_merro60/info.json
> +        },
```suggestion
        },
        "LAYOUT_60_iso_split_bs_rshift": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [1, 0], "x": 2, "y": 0},
                {"matrix": [1, 1], "x": 3, "y": 0},
                {"matrix": [2, 0], "x": 4, "y": 0},
                {"matrix": [2, 1], "x": 5, "y": 0},
                {"matrix": [3, 0], "x": 6, "y": 0},
                {"matrix": [3, 1], "x": 7, "y": 0},
                {"matrix": [4, 0], "x": 8, "y": 0},
                {"matrix": [4, 1], "x": 9, "y": 0},
                {"matrix": [5, 0], "x": 10, "y": 0},
                {"matrix": [5, 1], "x": 11, "y": 0},
                {"matrix": [6, 0], "x": 12, "y": 0},
                {"matrix": [6, 1], "x": 13, "y": 0},
                {"matrix": [6, 9], "x": 14, "y": 0},
                {"matrix": [0, 2], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [0, 3], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [2, 2], "x": 4.5, "y": 1},
                {"matrix": [2, 3], "x": 5.5, "y": 1},
                {"matrix": [3, 2], "x": 6.5, "y": 1},
                {"matrix": [3, 3], "x": 7.5, "y": 1},
                {"matrix": [4, 2], "x": 8.5, "y": 1},
                {"matrix": [4, 3], "x": 9.5, "y": 1},
                {"matrix": [5, 2], "x": 10.5, "y": 1},
                {"matrix": [5, 3], "x": 11.5, "y": 1},
                {"matrix": [6, 2], "x": 12.5, "y": 1},
                {"matrix": [0, 4], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [0, 5], "x": 1.75, "y": 2},
                {"matrix": [1, 4], "x": 2.75, "y": 2},
                {"matrix": [1, 5], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [3, 4], "x": 6.75, "y": 2},
                {"matrix": [3, 5], "x": 7.75, "y": 2},
                {"matrix": [4, 4], "x": 8.75, "y": 2},
                {"matrix": [4, 5], "x": 9.75, "y": 2},
                {"matrix": [5, 4], "x": 10.75, "y": 2},
                {"matrix": [5, 5], "x": 11.75, "y": 2},
                {"matrix": [6, 4], "x": 12.75, "y": 2},
                {"matrix": [6, 5], "x": 13.75, "y": 1, "w": 1.25, "h": 2},
                {"matrix": [0, 6], "x": 0, "y": 3, "w": 1.25},
                {"matrix": [0, 7], "x": 1.25, "y": 3},
                {"matrix": [1, 6], "x": 2.25, "y": 3},
                {"matrix": [1, 7], "x": 3.25, "y": 3},
                {"matrix": [2, 6], "x": 4.25, "y": 3},
                {"matrix": [2, 7], "x": 5.25, "y": 3},
                {"matrix": [3, 6], "x": 6.25, "y": 3},
                {"matrix": [3, 7], "x": 7.25, "y": 3},
                {"matrix": [4, 6], "x": 8.25, "y": 3},
                {"matrix": [4, 7], "x": 9.25, "y": 3},
                {"matrix": [5, 6], "x": 10.25, "y": 3},
                {"matrix": [5, 7], "x": 11.25, "y": 3},
                {"matrix": [6, 6], "x": 12.25, "y": 3, "w": 1.75},
                {"matrix": [6, 7], "x": 14, "y": 3},
                {"matrix": [0, 9], "x": 0, "y": 4, "w": 1.25},
                {"matrix": [0, 8], "x": 1.25, "y": 4, "w": 1.25},
                {"matrix": [2, 9], "x": 2.5, "y": 4, "w": 1.25},
                {"matrix": [3, 8], "x": 3.75, "y": 4, "w": 6.25},
                {"matrix": [4, 9], "x": 10, "y": 4, "w": 1.25},
                {"matrix": [5, 8], "x": 11.25, "y": 4, "w": 1.25},
                {"matrix": [5, 9], "x": 12.5, "y": 4, "w": 1.25},
                {"matrix": [6, 8], "x": 13.75, "y": 4, "w": 1.25}
            ]
        },
        "LAYOUT_60_iso_tsangan": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [1, 0], "x": 2, "y": 0},
                {"matrix": [1, 1], "x": 3, "y": 0},
                {"matrix": [2, 0], "x": 4, "y": 0},
                {"matrix": [2, 1], "x": 5, "y": 0},
                {"matrix": [3, 0], "x": 6, "y": 0},
                {"matrix": [3, 1], "x": 7, "y": 0},
                {"matrix": [4, 0], "x": 8, "y": 0},
                {"matrix": [4, 1], "x": 9, "y": 0},
                {"matrix": [5, 0], "x": 10, "y": 0},
                {"matrix": [5, 1], "x": 11, "y": 0},
                {"matrix": [6, 0], "x": 12, "y": 0},
                {"matrix": [6, 1], "x": 13, "y": 0, "w": 2},
                {"matrix": [0, 2], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [0, 3], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [2, 2], "x": 4.5, "y": 1},
                {"matrix": [2, 3], "x": 5.5, "y": 1},
                {"matrix": [3, 2], "x": 6.5, "y": 1},
                {"matrix": [3, 3], "x": 7.5, "y": 1},
                {"matrix": [4, 2], "x": 8.5, "y": 1},
                {"matrix": [4, 3], "x": 9.5, "y": 1},
                {"matrix": [5, 2], "x": 10.5, "y": 1},
                {"matrix": [5, 3], "x": 11.5, "y": 1},
                {"matrix": [6, 2], "x": 12.5, "y": 1},
                {"matrix": [0, 4], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [0, 5], "x": 1.75, "y": 2},
                {"matrix": [1, 4], "x": 2.75, "y": 2},
                {"matrix": [1, 5], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [3, 4], "x": 6.75, "y": 2},
                {"matrix": [3, 5], "x": 7.75, "y": 2},
                {"matrix": [4, 4], "x": 8.75, "y": 2},
                {"matrix": [4, 5], "x": 9.75, "y": 2},
                {"matrix": [5, 4], "x": 10.75, "y": 2},
                {"matrix": [5, 5], "x": 11.75, "y": 2},
                {"matrix": [6, 4], "x": 12.75, "y": 2},
                {"matrix": [6, 5], "x": 13.75, "y": 1, "w": 1.25, "h": 2},
                {"matrix": [0, 6], "x": 0, "y": 3, "w": 1.25},
                {"matrix": [0, 7], "x": 1.25, "y": 3},
                {"matrix": [1, 6], "x": 2.25, "y": 3},
                {"matrix": [1, 7], "x": 3.25, "y": 3},
                {"matrix": [2, 6], "x": 4.25, "y": 3},
                {"matrix": [2, 7], "x": 5.25, "y": 3},
                {"matrix": [3, 6], "x": 6.25, "y": 3},
                {"matrix": [3, 7], "x": 7.25, "y": 3},
                {"matrix": [4, 6], "x": 8.25, "y": 3},
                {"matrix": [4, 7], "x": 9.25, "y": 3},
                {"matrix": [5, 6], "x": 10.25, "y": 3},
                {"matrix": [5, 7], "x": 11.25, "y": 3},
                {"matrix": [6, 6], "x": 12.25, "y": 3, "w": 2.75},
                {"matrix": [0, 9], "x": 0, "y": 4, "w": 1.5},
                {"matrix": [0, 8], "x": 1.5, "y": 4},
                {"matrix": [2, 9], "x": 2.5, "y": 4, "w": 1.5},
                {"matrix": [3, 8], "x": 4, "y": 4, "w": 7},
                {"matrix": [5, 8], "x": 11, "y": 4, "w": 1.5},
                {"matrix": [5, 9], "x": 12.5, "y": 4},
                {"matrix": [6, 8], "x": 13.5, "y": 4, "w": 1.5}
            ]
        },
        "LAYOUT_60_iso_tsangan_split_bs_rshift": {
            "layout": [
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [1, 0], "x": 2, "y": 0},
                {"matrix": [1, 1], "x": 3, "y": 0},
                {"matrix": [2, 0], "x": 4, "y": 0},
                {"matrix": [2, 1], "x": 5, "y": 0},
                {"matrix": [3, 0], "x": 6, "y": 0},
                {"matrix": [3, 1], "x": 7, "y": 0},
                {"matrix": [4, 0], "x": 8, "y": 0},
                {"matrix": [4, 1], "x": 9, "y": 0},
                {"matrix": [5, 0], "x": 10, "y": 0},
                {"matrix": [5, 1], "x": 11, "y": 0},
                {"matrix": [6, 0], "x": 12, "y": 0},
                {"ma [...]

2024-02-04 10:17 UTC, dunk2k requested changes

2024-02-04 10:17 UTC, dunk2k commented on keyboards/chlx/ppr_merro60/keymaps/via/keymap.c
> +  KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_UP,   KC_ENT,
ISO keycode amendment
```suggestion
  KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
```

2024-02-04 10:17 UTC, dunk2k commented on keyboards/chlx/ppr_merro60/keymaps/via/rules.mk
> +
whitespace removal
```suggestion
```

2024-02-04 10:17 UTC, dunk2k commented on keyboards/chlx/ppr_merro60/readme.md
> +Meant to be manufactured in 1.2mm.
```suggestion
- Standard 60% format keyboard PCB with USB-C and unified daughterboard compatibility.
- Modified cutouts to allow usage of certain tray mount cases into gummy gasket o-ring mount.
- Additional center flex cut.
- Meant to be manufactured in 1.2mm thickness.
```

2024-02-04 23:53 UTC, fauxpark approved these changes

2024-02-05 03:43 UTC, gaclee3b commented
hey everyone, something weird is going on. before adding all the formatting changes, my qmk toolbox flashing was fine and pcb was working perfect. after all the updates, I just regenerated the qmk hex file and it's giving me a dead pcb now. I'm not sure how to debug what's going on. 

- my qmk is v 1.1.2
- my qmk toolbox is v 0.2.2

I'm working off macOS Sonoma v 14.2.1

Any tips as to where to look to see what's breaking?

2024-02-12 00:53 UTC, drashna approved these changes

2024-02-16 23:30 UTC, waffle87 commented on keyboards/chlx/ppr_merro60/config.h
> +
```suggestion
```

2024-02-16 23:30 UTC, waffle87 commented on keyboards/chlx/ppr_merro60/info.json
> +    },
```suggestion
    },
    "qmk": {
        "locking": {
            "enabled": true,
            "resync": true
        }
    },
```

2024-02-16 23:34 UTC, waffle87 approved these changes

2024-02-16 23:35 UTC, merged