Add  KB3x keyboard
qmk/qmk_firmware pull request #23015
Opened 2024-02-04 08:37 UTC by DOIO2022

## Description

Add  KB3x  keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-16 23:19 UTC, waffle87 commented on keyboards/doio/kb3x/readme.md
> +    make doio/kb19:default:flash
```suggestion
    make doio/kb3x:default

Flashing example for this keyboard:

    make doio/kb3x:default:flash
```

2024-02-17 10:07 UTC, dunk2k commented on keyboards/doio/kb3x/readme.md
Image of this keypad would be helpful 😉

2024-02-19 06:36 UTC, DOIO2022 commented on keyboards/doio/kb3x/readme.md
@dunk2k  Thank you for your suggestion and I've added it.

2024-02-24 00:12 UTC, fauxpark requested changes

2024-02-24 00:12 UTC, fauxpark commented on keyboards/doio/kb3x/info.json
Please run `qmk format-json -i` on this file.

2024-02-26 01:13 UTC, DOIO2022 commented on keyboards/doio/kb3x/info.json
@fauxpark  Hi ,I've run it. Thank you!

2024-03-05 00:13 UTC, zvecr commented
![image](https://github.com/qmk/qmk_firmware/assets/16520359/b367ac4d-517e-4a75-98bb-d531b92e36ea)

All clicking that "update branch" button is doing is using up CI minutes and making the queue longer for other PRs. I suggest you actually implement the requested changes <https://github.com/qmk/qmk_firmware/pull/23015#discussion_r1501098124>.

2024-03-06 01:14 UTC, DOIO2022 commented on keyboards/doio/kb3x/readme.md
> +![kb3x](https://github.com/DOIO2022/qmk_firmware/assets/116554792/cc2d265c-75e4-46fe-b8a1-19698ae61a3e)
@waffle87  Hi,I‘ve changed it. Thank you!

2024-03-06 01:20 UTC, DOIO2022 commented
> ![image](https://private-user-images.githubusercontent.com/16520359/309936852-b367ac4d-517e-4a75-98bb-d531b92e36ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2ODc5NDMsIm5iZiI6MTcwOTY4NzY0MywicGF0aCI6Ii8xNjUyMDM1OS8zMDk5MzY4NTItYjM2N2FjNGQtNTE3ZS00YTc1LTk4YmItZDUzMWI5MmUzNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAxMTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNGVmM2VkNThiNDNmZmEzMGQ2YmMwNDMyMTNlMGU0MmY0MGI2NDA0ZDE5NmI1MmE3YTUyN2MzODU1OWZjODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y5kl3zrsYl9pbEqjeoi-Crg6P0LmDEnIn2z1XcfpQac)
> 
> All clicking that "update branch" button is doing is using up CI minutes and making the queue longer for other PRs. I suggest you actually implement the requested changes [#23015 (comment)](https://github.com/qmk/qmk_firmware/pull/23015#discussion_r1501098124).

@zvecr   Hi，I have been troubled by this problem for a long time，could you tell me the mean of  "implement the requested changes"? I don't know what should I do next. Thank  you  for your help.

2024-03-06 01:58 UTC, zvecr commented on keyboards/doio/kb3x/readme.md
> +[![kb3x-01](https://imgur.com/gallery/vVF4TNW)](https://imgur.com/gallery/vVF4TNW)
```suggestion
![kb3x-01](https://i.imgur.com/6DvIu9Ml.png)
```

2024-03-10 00:09 UTC, fauxpark approved these changes

2024-03-12 05:46 UTC, closed without merging

2024-03-12 05:59 UTC, DOIO2022 commented
@fauxpark  Hi, I accidentally closed this pull. Can I open it again? Thank you!

2024-03-12 06:05 UTC, zvecr commented
No, as you have force pushed while the PR was closed. (An action that was not requested or required)