adds rot13labs rotc0n macropad
qmk/qmk_firmware pull request #23028
Opened 2024-02-06 13:47 UTC by c0ldbru

## Description

Adds rot13labs rotc0n macropad and keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-06 23:42 UTC, zvecr requested changes

2024-02-06 23:42 UTC, zvecr commented on keyboards/rot13labs/rotc0n/config.h
This file should be removed.

2024-02-06 23:44 UTC, zvecr commented on keyboards/rot13labs/rotc0n/info.json
> +    "layouts": {
```suggestion
    "community_layouts": ["ortho_2x3"],
    "layouts": {
```

2024-02-07 01:08 UTC, c0ldbru commented on keyboards/rot13labs/rotc0n/config.h
nuked!

2024-02-09 14:03 UTC, c0ldbru commented
Just checking in on this to see if theres anything else I can do to help move this PR forward?

2024-02-09 14:07 UTC, fauxpark requested changes

2024-02-09 14:07 UTC, fauxpark commented on keyboards/rot13labs/rotc0n/readme.md
> +![rotcon](https://i.imgur.com/InAAdPp.jpg)
```suggestion
![rotcon](https://i.imgur.com/InAAdPph.jpg)
```

2024-02-13 14:33 UTC, c0ldbru commented
Anything else needed for this PR?

2024-02-13 22:11 UTC, fauxpark approved these changes

2024-02-14 21:51 UTC, waffle87 approved these changes

2024-02-14 21:51 UTC, merged