Brick65 fix
qmk/qmk_firmware pull request #23032
Opened 2024-02-07 09:37 UTC by Xiasis

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-07 20:29 UTC, zvecr commented
<https://github.com/qmk/qmk_firmware/pull/23031#issuecomment-1931546884>

This doesnt contain any actual "fixes".

Also you need to stop opening new PRs and push changes to the same branch.

2024-02-11 09:52 UTC, Xiasis commented
> [#23031 (comment)](https://github.com/qmk/qmk_firmware/pull/23031#issuecomment-1931546884)
> 
> This doesnt contain any actual "fixes".
> 
> Also you need to stop opening new PRs and push changes to the same branch.

I thought it was a branch problem. I'm sorry.
Was it invalidated due to the key map issue in the document?
Can you tell me if there is a keyboard within qmk_firmware that I can refer to?

I'm sorry to bother you.

2024-02-12 00:49 UTC, drashna requested changes
A lot of the fixes can be handled with `qmk migrate` or more selectively by running `qmk info -f json`

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/brick65.c
rgb matrix data needs to be migrated to info.json, and this file can/should be removed.

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/brick65.h
This file should be removed.

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/config.h
This config should be moved to info.json, and this file removed.

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/info.json
needs a format pass (`qmk format-json`)

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/keymaps/default/keymap.c
> +    )
Empty layers are not needed, and needlessly increase firmware size.  They should be removed.
```suggestion
```

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/keymaps/via/config.h
Most of this can and should be moved to info.json, rather than being at the keymap level

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/keymaps/via/keymap.c
> +    )
As default, but the dynamic keymap feature which VIA uses will automatically populate undeclared layers with `KC_TRANSPARENT` automatically.
```suggestion
```

2024-02-12 00:49 UTC, drashna commented on keyboards/brick65/rules.mk
Most of this should be moved to info.json.   Custom matrix should be removed since no custom matrix is actually provided.  File should be left, but blank, as a rules.mk file is needed by the build system.

2024-02-15 12:40 UTC, Xiasis commented on keyboards/brick65/rules.mk
Thank you very much for your kind help.
I've fixed some things, but I don't know if it's right.

2024-02-15 16:17 UTC, fauxpark requested changes

2024-02-15 16:17 UTC, fauxpark commented on keyboards/brick65/brick65.c
This file can be deleted.

2024-02-15 16:17 UTC, fauxpark commented on keyboards/brick65/readme.md
> +![Brick65](https://imgur.com/bBSayS9h.png)
```suggestion

![Brick65](https://imgur.com/bBSayS9h.png)
```

2024-02-15 16:17 UTC, fauxpark commented on keyboards/brick65/readme.md
> +* Hardware Availability : Produced and Sold by Syryan
```suggestion
* Keyboard Maintainer: Pyupyu
* Hardware Supported: Brick65
* Hardware Availability: Produced and Sold by Syryan
```

2024-02-15 16:17 UTC, fauxpark commented on keyboards/brick65/rules.mk
> +
```suggestion
# This file intentionally left blank
```

2024-02-15 16:17 UTC, fauxpark commented on keyboards/brick65/info.json
Please run `qmk format-json -i` on this file.

2024-05-01 01:50 UTC, closed without merging