Add support for Smart 68 keyboard
qmk/qmk_firmware pull request #23043
Opened 2024-02-09 09:43 UTC by Shados

## Description

Adds support for the Smart 68. Some notes:
- I based the layout off of the default used for it in its original TMK firmware, and enabled Command in it for feature-parity with that.
- Bootmagic key is also set to the one used in its original firmware.

Also, it's not entirely clear to me what "keyboard maintainer" implies in this context. Should I be putting myself there, as I have done, or should I just put `qmk`?

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-09 09:46 UTC, fauxpark requested changes

2024-02-09 09:46 UTC, fauxpark commented on keyboards/smart68/config.h
This file can be deleted.

2024-02-12 01:09 UTC, waffle87 approved these changes

2024-03-15 08:39 UTC, drashna approved these changes

2024-05-03 04:00 UTC, Shados commented
Not stale...

2024-05-03 04:34 UTC, fauxpark approved these changes

2024-05-05 01:38 UTC, merged