[quick7] update keyboard and keymap
qmk/qmk_firmware pull request #23051
Opened 2024-02-11 10:46 UTC by MakotoKurauchi

## Description
update keyboard and keymap

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-11 10:54 UTC, zvecr commented
> keyboard updates and refactors (eg. to data driven) must go through develop to reduce master -> develop merge conflicts

Also, all keyboard must have a default keymap so its deletion is incorrect.

2024-02-12 14:09 UTC, dunk2k requested changes

2024-02-12 14:09 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
>          "LAYOUT": {
```suggestion
    "layout_aliases": {
        "LAYOUT": "LAYOUT_ortho_3x3"
    },
    "community_layouts": ["ortho_3x3"],
    "layouts": {
        "LAYOUT_ortho_3x3": {
```

2024-02-12 14:09 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
>      },
already enabled in `features`
```suggestion
```

2024-02-12 14:09 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
> +    },
already enabled in `features`
```suggestion
```

2024-02-12 14:09 UTC, dunk2k commented on keyboards/yushakobo/quick7/keymaps/default/rules.mk
> +ENCODER_MAP_ENABLE = yes
```suggestion
ENCODER_MAP_ENABLE = yes

```

2024-02-12 14:19 UTC, dunk2k requested changes
replace `bootloader` and `processor` with `development_board`

2024-02-12 14:19 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
>      "matrix_pins": {
```suggestion
    "development_board": "promicro",
    "matrix_pins": {
```

2024-02-12 14:19 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
> +    "bootloader": "caterina",
```suggestion
```

2024-02-12 14:19 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
> +    "processor": "atmega32u4",
```suggestion
```

2024-02-12 15:28 UTC, dunk2k requested changes

2024-02-12 15:28 UTC, dunk2k commented on keyboards/yushakobo/quick7/info.json
> +        "enabled": true,
Already enabled in `features`
```suggestion
```

2024-02-13 09:33 UTC, zvecr commented on keyboards/yushakobo/quick7/info.json
> +        "console": true,
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
```

2024-04-29 01:49 UTC, closed without merging