nacly/sodium62: Update vid, pid, and add via keymap
qmk/qmk_firmware pull request #23063
Opened 2024-02-12 19:17 UTC by Na-Cly

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-12 23:28 UTC, waffle87 approved these changes

2024-02-12 23:32 UTC, fauxpark requested changes
Keyboard updates need to go through `develop`.

2024-02-13 00:55 UTC, Na-Cly commented
Based off the develop branch? I'm not sure what go through develop means.

2024-02-14 01:20 UTC, fauxpark approved these changes

2024-02-14 02:03 UTC, zvecr approved these changes

2024-02-14 02:03 UTC, merged

2024-02-14 14:21 UTC, Na-Cly commented
About how long until the keyboard gets updated in master?