Added Mercury, Soyuz and Soyuz XL Macropads
qmk/qmk_firmware pull request #23064
Opened 2024-02-12 20:02 UTC by spacehangover

Added Mercury, Soyuz and Soyuz XL Macropads by WWA

Added 3 new macropads by WWA

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-12 23:26 UTC, waffle87 requested changes

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuz/keymaps/default/keymap.c
> +
Unused.
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuz/keymaps/default/keymap.c
> +}
This should be moved to the keyboard level in a `soyuz.c` using the appropriate `_kb` functions.
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuz/keymaps/via/keymap.c
> +
Unused.
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuz/keymaps/via/keymap.c
> +}
As above.
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuz/readme.md
> +![soyuz](https://imgur.com/a/sOYdpzS)
```suggestion
![soyuz](https://i.imgur.com/KwwORGSh.jpeg)
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuz/rules.mk
> +
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/config.h
> +//#define NO_ACTION_ONESHOT
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/keymaps/default/keymap.c
> +}
As above.
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/keymaps/default/keymap.c
> +
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/keymaps/via/keymap.c
> +
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/keymaps/via/keymap.c
> +}
As above.
```suggestion
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/readme.md
> +![soyuzxl](https://imgur.com/gallery/AqPRXY7)
```suggestion
![soyuzxl](https://i.imgur.com/njUq2s3h.jpeg)
```

2024-02-12 23:26 UTC, waffle87 commented on keyboards/handwired/wwa/soyuzxl/rules.mk
> +
```suggestion
```

2024-02-12 23:51 UTC, spacehangover commented
Hey, thanks for the review, will make the changes as requested, i just have one question, what do you mean by this? This should be moved to the keyboard level in a soyuz.c using the appropriate _kb functions. 
Referring to the MIDI part of my code, i wasn't able to find any docs regarding the use of MIDI, so i copied the code from another keyboard already merged in QMK.

2024-02-13 09:35 UTC, tzarc commented
This should be three separate PRs, one per keyboard.

2024-02-13 15:33 UTC, closed without merging