GC9xxx LCD family drivers (GC9107 and GC9A01)
qmk/qmk_firmware pull request #23091
Opened 2024-02-16 00:55 UTC by fpb

## Description

LCD GC9XXX family of drivers similar to ST7XXX. GC9107 support was added and also did a lot of initialisation code cleanup of GC9A01. Old init code for GC9A01 had a lot of flicker on my device and that has disappeared with the new (shorter) init code.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-21 11:52 UTC, fpb commented
Tested both display models and it all seems ok.

![IMG_20240221_105810](https://github.com/qmk/qmk_firmware/assets/456959/52c9cb9b-bc1b-4177-8491-0a8f8e9d2896)

2024-03-29 03:28 UTC, drashna approved these changes

2024-05-22 14:25 UTC, fpb commented
Reviews are still pending...

2024-06-03 12:18 UTC, tzarc requested changes
Just a few minor tidbits.

2024-06-03 12:18 UTC, tzarc commented on drivers/painter/gc9xxx/qp_gc9107.c
> +        // 0xC7, 0, 1, 0x18,
```suggestion
```

2024-06-03 12:18 UTC, tzarc commented on drivers/painter/gc9xxx/qp_gc9107.c
> +// Factory function for creating a handle to the ILI9341 device
```suggestion
// Factory function for creating a handle to the GC9107 device
```

2024-06-04 22:41 UTC, tzarc approved these changes

2024-06-04 22:41 UTC, merged