[Add Keyboard] Add the Compensator
qmk/qmk_firmware pull request #23103
Opened 2024-02-18 08:13 UTC by Lrfoster03

Added support for the Compensator Keyboard, seen [here](https://geekhack.org/index.php?topic=122493.0)

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-18 08:20 UTC, fauxpark requested changes

2024-02-18 08:20 UTC, fauxpark commented on keyboards/compensator/matrix_diagram.md
> +│20 │21 ││22 │23 │24 │25 │    │26 │    │27  │28 │29 │2A │2B │2C │2D │2E │2F │2G │2H │2I │2J    │2K │    │1L │    │2M │2N │2O │2P ││2Q │2R │
```suggestion
│20 │21 ││22 │23 │24 │25 │    │26 │    │27  │28 │29 │2A │2B │2C │2D │2E │2F │2G │2H │2I │2J    │2K │    │1L │    │2M │2N │2O │2P ││2Q │2R │
```

2024-02-18 08:20 UTC, fauxpark commented on keyboards/compensator/matrix_diagram.md
> +         ┌───┐                                    ┌───────────────────────────────────────┐                                  ┌───┐
```suggestion
         ┌───┐                                    ┌───────────────────────────────────────┐                                  ┌───┐
```

2024-02-18 08:20 UTC, fauxpark commented on keyboards/compensator/keymaps/via/keymap.c
> +    )
```suggestion
```

2024-02-18 08:48 UTC, zvecr requested changes

2024-02-18 08:48 UTC, zvecr commented on keyboards/compensator/keymaps/default/keymap.c
> +        KC_F5,  KC_F6,     KC_PENT,  KC_P1, KC_P2, KC_P3,          KC_NO,   KC_UP,   KC_NO,            KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT
`MO(1)` would go out of bounds

2024-02-18 08:48 UTC, zvecr commented on keyboards/compensator/info.json
> +        "key_lock": false
```suggestion
        "nkro": false
```

2024-02-19 02:31 UTC, drashna reviewed
That or move the macro to compensator.c/h

2024-02-19 02:31 UTC, drashna commented on keyboards/compensator/keymaps/default/keymap.c
> +    KC_P00 = QK_KB_0
```suggestion
    KC_P00 = SAFE_RANGE,
```
or
```suggestion
    KC_P00 = QK_USER,
```

2024-02-19 02:31 UTC, drashna commented on keyboards/compensator/keymaps/via/keymap.c
> +    KC_P00 = QK_KB_0
same.

2024-02-19 21:42 UTC, waffle87 commented on keyboards/compensator/keymaps/default/keymap.c
> +        KC_TRNS,  KC_TRNS,     KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,  KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS,
```suggestion
        KC_F5,  KC_F6,     KC_PENT,  KC_P1, KC_P2, KC_P3,          KC_NO,   KC_UP,   KC_NO,            KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_TRNS,                  KC_NO,   KC_UP,   KC_NO,            KC_P1,   KC_P2,   KC_P3,   KC_PENT,     KC_F5,  KC_F6,
        KC_F7,  KC_F8,     KC_PMNS,  KC_PDOT, KC_P0, KC_P00,       KC_LEFT, KC_DOWN, KC_RIGHT,         KC_LCTL, KC_LALT, KC_SPC,  KC_SPC,  KC_SPC,  KC_LALT, KC_LCTL,                                                                               KC_LEFT, KC_DOWN, KC_RIGHT,         KC_P00,  KC_P0,  KC_PDOT,  KC_PMNS,     KC_F7,  KC_F8
```

2024-02-19 21:42 UTC, waffle87 commented on keyboards/compensator/keymaps/via/keymap.c
> +        KC_F5,  KC_F6,     KC_PENT,  KC_P1, KC_P2, KC_P3,          KC_NO,   KC_UP,   KC_NO,            KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT
```suggestion
        KC_F5,  KC_F6,     KC_PENT,  KC_P1, KC_P2, KC_P3,          KC_NO,   KC_UP,   KC_NO,            KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_TRNS,                  KC_NO,   KC_UP,   KC_NO,            KC_P1,   KC_P2,   KC_P3,   KC_PENT,     KC_F5,  KC_F6,
```

2024-02-21 19:38 UTC, Lrfoster03 commented
Initially, I wanted to leave the layers for the user to customize themselves, but I should've mentioned this. I believe this change will be better for the end-user anyway.

2024-02-21 20:52 UTC, waffle87 approved these changes

2024-02-21 21:36 UTC, fauxpark approved these changes

2024-02-21 22:35 UTC, merged