Add werk.technica werk.one keyboard
qmk/qmk_firmware pull request #23130
Opened 2024-02-22 16:17 UTC by ebastler

This PR adds the WT One keyboard to QMK

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-22 17:48 UTC, zvecr requested changes

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/keymaps/via/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/werk_one.c
This file can be removed, as its the default behaviour <https://github.com/qmk/qmk_firmware/blob/master/quantum/encoder.c#L90>.

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/info.json
> +        "lto": true
```suggestion
        "encoder": true
```

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/info.json
> +    "features": {
```suggestion
    "build": {
        "lto": true
    },
    "features": {
```

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/info.json
> +    "board": "GENERIC_STM32_F411XE",
```suggestion
```

2024-02-22 17:48 UTC, zvecr commented on keyboards/werk_technica/one/info.json
> +                "resolution": 4
```suggestion
                "pin_b": "A15"
```

2024-02-22 18:12 UTC, ebastler commented on keyboards/werk_technica/one/werk_one.c
Oh, I was not aware that a fallback from encoder map exists. Thank you!

I also just realized it still had an outdated file name from when the board folder was werk_one and therefore not used for compiling anyway. File removed.

2024-02-23 00:41 UTC, fauxpark approved these changes

2024-02-23 00:41 UTC, fauxpark commented on keyboards/werk_technica/one/info.json
Please run `qmk format-json -i` on this file.

2024-02-24 00:10 UTC, fauxpark approved these changes

2024-03-21 15:08 UTC, ebastler commented
Sorry for being pushy, but we're one month in with no suggestions for changes or anything else, and I kinda need this merged before the boards ship to customers... Is there any news on this PR?

2024-03-22 12:09 UTC, nooges commented on keyboards/werk_technica/one/keymaps/via/rules.mk
> +VIA_ENABLE=yes
```suggestion
VIA_ENABLE = yes 
```

2024-03-22 12:13 UTC, merged