Add Hatsukey70
qmk/qmk_firmware pull request #23140
Opened 2024-02-24 09:47 UTC by interestor

## Description

I added a new keyboard named Hatsukey70.Keyboard directories, keymaps, etc. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-24 09:52 UTC, fauxpark commented on keyboards/hatsukey70/keymaps/via/hatsukey70.json
As above.

2024-02-24 09:52 UTC, fauxpark commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +        )
```suggestion
```

2024-02-24 09:52 UTC, fauxpark commented on keyboards/hatsukey70/readme.md
> +![hatsukey70](https://scrapbox.io/files/657eefbbe3d8d30022ed614d.jpg)
Please rehost this on imgur.

2024-02-24 09:53 UTC, fauxpark commented on keyboards/hatsukey70/readme.md
> +    make hatsukey70:via:flash
```suggestion
    make hatsukey70:default

Flashing example for this keyboard:

    make hatsukey70:default:flash
```

2024-02-24 11:48 UTC, fauxpark requested changes

2024-02-24 11:48 UTC, fauxpark commented on keyboards/hatsukey70/keymaps/via/hatsukey70.json
This file also needs to be removed.

2024-02-24 12:56 UTC, dunk2k requested changes

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/info.json
> +        }
default setting not required to be explicitly defined 
```suggestion
        "soft_serial_pin": "D0"
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/info.json
> +    "processor": "atmega32u4",
change to `development_board`
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/info.json
> +    "bootloader": "atmel-dfu",
change to `development_board`
```suggestion
    "development_board": "promicro",
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/info.json
> +}
```suggestion
}

```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/info.json
> +                {"matrix": [9, 7], "x": 17.25, "y": 4}
Rearrange keys positions, as best as, to match physical layout
```suggestion
                {"matrix": [0, 0], "x": 0, "y": 0},
                {"matrix": [0, 1], "x": 1, "y": 0},
                {"matrix": [0, 2], "x": 2, "y": 0},
                {"matrix": [0, 3], "x": 3, "y": 0},
                {"matrix": [0, 4], "x": 4, "y": 0},
                {"matrix": [0, 5], "x": 5, "y": 0},
                {"matrix": [0, 6], "x": 6, "y": 0},
                {"matrix": [5, 1], "x": 9, "y": 0},
                {"matrix": [5, 2], "x": 10, "y": 0},
                {"matrix": [5, 3], "x": 11, "y": 0},
                {"matrix": [5, 4], "x": 12, "y": 0},
                {"matrix": [5, 5], "x": 13, "y": 0},
                {"matrix": [5, 6], "x": 14, "y": 0},
                {"matrix": [5, 7], "x": 15, "y": 0, "w": 1.5},
                {"matrix": [1, 0], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [1, 1], "x": 1.5, "y": 1},
                {"matrix": [1, 2], "x": 2.5, "y": 1},
                {"matrix": [1, 3], "x": 3.5, "y": 1},
                {"matrix": [1, 4], "x": 4.5, "y": 1},
                {"matrix": [1, 5], "x": 5.5, "y": 1},
                {"matrix": [1, 6], "x": 6.5, "y": 1},
                {"matrix": [6, 0], "x": 8.5, "y": 1},
                {"matrix": [6, 1], "x": 9.5, "y": 1},
                {"matrix": [6, 2], "x": 10.5, "y": 1},
                {"matrix": [6, 3], "x": 11.5, "y": 1},
                {"matrix": [6, 4], "x": 12.5, "y": 1},
                {"matrix": [6, 5], "x": 13.5, "y": 1},
                {"matrix": [6, 6], "x": 14.5, "y": 1},
                {"matrix": [6, 7], "x": 15.5, "y": 1},
                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [7, 1], "x": 8.75, "y": 2},
                {"matrix": [7, 2], "x": 9.75, "y": 2},
                {"matrix": [7, 3], "x": 10.75, "y": 2},
                {"matrix": [7, 4], "x": 11.75, "y": 2},
                {"matrix": [7, 5], "x": 12.75, "y": 2},
                {"matrix": [7, 6], "x": 13.75, "y": 2},
                {"matrix": [7, 7], "x": 14.75, "y": 2, "w": 1.75},
                {"matrix": [3, 0], "x": 0, "y": 3, "w": 2.25},
                {"matrix": [3, 1], "x": 2.25, "y": 3},
                {"matrix": [3, 2], "x": 3.25, "y": 3},
                {"matrix": [3, 3], "x": 4.25, "y": 3},
                {"matrix": [3, 4], "x": 5.25, "y": 3},
                {"matrix": [3, 5], "x": 6.25, "y": 3},
                {"matrix": [8, 0], "x": 8.25, "y": 3},
                {"matrix": [8, 1], "x": 9.25, "y": 3},
                {"matrix": [8, 2], "x": 10.25, "y": 3},
                {"matrix": [8, 3], "x": 11.25, "y": 3},
                {"matrix": [8, 4], "x": 12.25, "y": 3},
                {"matrix": [8, 5], "x": 13.25, "y": 3},
                {"matrix": [8, 6], "x": 14.25, "y": 3},
                {"matrix": [8, 7], "x": 15.25, "y": 3, "w": 1.25},
                {"matrix": [4, 0], "x": 0.25, "y": 4},
                {"matrix": [4, 1], "x": 1.25, "y": 4},
                {"matrix": [4, 2], "x": 2.25, "y": 4},
                {"matrix": [4, 3], "x": 3.25, "y": 4, "w": 1.25},
                {"matrix": [4, 4], "x": 4.5, "y": 4},
                {"matrix": [4, 5], "x": 5.5, "y": 4, "w": 1.5},
                {"matrix": [9, 1], "x": 8.25, "y": 4, "w": 1.5},
                {"matrix": [9, 2], "x": 9.75, "y": 4},
                {"matrix": [9, 3], "x": 10.75, "y": 4, "w": 1.5},
                {"matrix": [9, 4], "x": 12.25, "y": 4},
                {"matrix": [9, 5], "x": 13.25, "y": 4},
                {"matrix": [9, 6], "x": 14.25, "y": 4},
                {"matrix": [9, 7], "x": 15.25, "y": 4}
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/readme.md
> +* Hardware Supported: hatsukey70 rev1, ProMicro
```suggestion
* Hardware Supported: hatsukey70 rev1 PCB, ProMicro development board
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +
```suggestion
```

2024-02-24 12:56 UTC, dunk2k commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +
```suggestion
```

2024-03-21 04:51 UTC, zvecr requested changes

2024-03-21 04:51 UTC, zvecr commented on keyboards/hatsukey70/keymaps/via/rules.mk
> +
```suggestion
```

2024-03-21 04:51 UTC, zvecr commented on keyboards/hatsukey70/readme.md
> +Enter the bootloader in 3 ways:
```suggestion
Enter the bootloader in 2 ways:
```

2024-03-21 04:51 UTC, zvecr commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +        )
This still needs to be completed

2024-03-21 04:51 UTC, zvecr commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +        )
As does this

2024-05-07 01:17 UTC, interestor commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +        )
Thank you for the revew.I believe that keeping empty layers is useful, considering that other users of this keyboard may customize it using a service called Remap. By keeping empty layers, users can modify the key layout of those layers as needed when using Remap. Many users who use this keyboard are new to QMK, so I want to make it easier for them to customize by keeping it in a more understandable state.Is it not good?

2024-06-22 02:28 UTC, fauxpark requested changes

2024-06-22 02:28 UTC, fauxpark commented on keyboards/hatsukey70/rules.mk
This file can be deleted.

2024-06-22 02:28 UTC, fauxpark commented on keyboards/hatsukey70/readme.md
> +![hatsukey70](https://imgur.com/a/4KEGMBC)
```suggestion
![hatsukey70](https://i.imgur.com/wQG6KxD.jpeg)
```
Needs to be a direct link.

2024-06-22 02:28 UTC, fauxpark commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +        )
As above, still outstanding.

2024-06-22 02:28 UTC, fauxpark commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +        )
Empty layers are pointless and wasteful, please remove them.

2024-06-22 02:28 UTC, fauxpark commented on keyboards/hatsukey70/info.json
This file should be renamed to `keyboard.json` per recent changes.

2024-07-05 04:10 UTC, fauxpark requested changes

2024-07-05 04:10 UTC, fauxpark commented on keyboards/hatsukey70/rules.mk
This file can be deleted.

2024-07-05 05:07 UTC, zvecr commented on keyboards/hatsukey70/hatsukey70.json
This file needs to be renamed to `keyboard.json`, not the name of the keyboard.

2024-07-08 05:58 UTC, fauxpark approved these changes

2024-07-15 05:17 UTC, drashna requested changes

2024-07-15 05:17 UTC, drashna commented on keyboards/hatsukey70/keymaps/default/keymap.c
> +      		MO(1), KC_LCTL, KC_LALT, KC_LGUI, KC_ESC, KC_SPC, KC_ENT, KC_BSPC, KC_RGUI, KC_RALT, KC_LEFT, KC_DOWN, KC_RIGHT
```suggestion
            KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC,
            KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS,
            KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT,
            KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_UP, KC_RSFT,
            MO(1), KC_LCTL, KC_LALT, KC_LGUI, KC_ESC, KC_SPC, KC_ENT, KC_BSPC, KC_RGUI, KC_RALT, KC_LEFT, KC_DOWN, KC_RIGHT
```

2024-07-15 05:17 UTC, drashna commented on keyboards/hatsukey70/keymaps/via/keymap.c
> +      		MO(1), KC_LCTL, KC_LALT, KC_LGUI, KC_ESC, KC_SPC, KC_ENT, KC_BSPC, KC_RGUI, KC_RALT, KC_LEFT, KC_DOWN, KC_RIGHT
```suggestion
            KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC,
            KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS,
            KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT,
            KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_UP, KC_RSFT,
            MO(1), KC_LCTL, KC_LALT, KC_LGUI, KC_ESC, KC_SPC, KC_ENT, KC_BSPC, KC_RGUI, KC_RALT, KC_LEFT, KC_DOWN, KC_RIGHT
```

2024-08-26 10:38 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-11-10 02:04 UTC, closed without merging