Tbkmini fix led
qmk/qmk_firmware pull request #23153
Opened 2024-02-25 20:51 UTC by AdolfMuffin

## Description

There was a problem with mapping a thumb-cluster leds, that I found on key-specific lightning effects, so I remapped the leds in config.
There wasn't VIA support "out of the box" in the default keymap - added.
There wasn't any glowing effect except static, so I added them into config.
Also, enabled NKRO as a feature.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-02-25 21:17 UTC, waffle87 requested changes

2024-02-25 21:17 UTC, waffle87 commented on keyboards/bastardkb/tbkmini/keymaps/default/rules.mk
This file should be remove. VIA is not to be enabled in the `default` keymap.

2024-02-25 21:17 UTC, zvecr requested changes

2024-02-25 21:17 UTC, zvecr commented on keyboards/bastardkb/tbkmini/keymaps/default/rules.mk
This file needs to be removed. VIA cannot be enabled on the default keymap, and needs to be added to a `via` keymap like every other keyboard in the repo.

2024-02-25 21:17 UTC, zvecr commented on keyboards/bastardkb/tbkmini/v2/splinky_3/config.h
> +#ifdef RGB_MATRIX_ENABLE
These need to be enabled in info.json instead.

2024-02-26 02:17 UTC, 0xcharly commented
@AdolfMuffin thanks for the RGB matrix fix. 

If possible, I'd like to request to revert all other changes, since we're trying to keep the default keymaps simple and consistent across all BastardKB boards. It's easier for us to keep up with QMK and maintain those firmwares when the implementations are consistent

2024-05-15 02:01 UTC, closed without merging