Add set_st custom macropads
qmk/qmk_firmware pull request #23151
Opened 2024-02-25 13:13 UTC by set-st

Custom macropad based on rp2040

2024-02-25 13:17 UTC, keyboard-magpie commented
Invalid PR as you have deleted the PR template which is there for good reason, as well as extra files included.

2024-02-25 14:56 UTC, set-st commented
fixed

2024-02-25 19:04 UTC, zvecr commented
> fixed

Nope, you still have many issues covered by the PR checklist. This includes:
* VIA json which need to be removed
* vscode settings file which needs to be removed
* Content which should be migrated to info.json

Also, you should not close/open new PRs with the same content.

2024-02-25 19:36 UTC, tzarc commented
And, one PR per board.

2024-02-28 14:07 UTC, set-st commented
What is wrong with encoder_map? Its compiling fine locally.

Run QMK_CHANGES=$(echo -e 'keyboards/handwired/set_st/rp2040/config.h keyboards/handwired/set_st/rp2040/halconf.h keyboards/handwired/set_st/rp2040/info.json keyboards/handwired/set_st/rp2040/keymaps/default/keymap.c keyboards/handwired/set_st/rp2040/keymaps/default/rules.mk keyboards/handwired/set_st/rp2040/keymaps/via/keymap.c keyboards/handwired/set_st/rp2040/keymaps/via/rules.mk keyboards/handwired/set_st/rp2040/mcuconf.h keyboards/handwired/set_st/rp2040/readme.md keyboards/handwired/set_st/rp2040/rp2040.c keyboards/handwired/set_st/rp2040/rules.mk' | sed 's/ /\n/g')
linting handwired/set_st/rp2040
☒ handwired/set_st/rp2040: Invalid keyboard level feature detected - encoder_map
☒ Lint check failed for: handwired/set_st/rp2040
Error: Process completed with exit code 1.

2024-02-28 14:10 UTC, fauxpark commented
Encoder map is not allowed at keyboard level. It will not compile in the Configurator, because it generates its own keymap which will not have an encoder_map array.

2024-02-28 14:15 UTC, fauxpark requested changes

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/config.h
> +
```suggestion
```

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/config.h
> +#endif
```suggestion
```
The RGB Matrix effects config above should be moved to info.json.

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/keymaps/default/keymap.c
> +
```suggestion
```
`default` keymaps must not have VIA enabled.

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/keymaps/via/keymap.c
> +
```suggestion
```
This serves no purpose anyway as via.h is already included through `QMK_KEYBOARD_H`.

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/rp2040.c
> +} };
LED config should be moved to info.json and this file deleted.

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/rules.mk
> +OLED_TRANSPORT = i2c
```suggestion
# This file intentionally left blank
```

2024-02-28 14:15 UTC, fauxpark commented on keyboards/handwired/set_st/rp2040/info.json
> +        "nkro": true
```suggestion
        "nkro": true,
        "encoder": true,
        "rgb_matrix": true,
        "oled": true
```

2024-02-28 19:21 UTC, closed without merging