Chameleon
qmk/qmk_firmware pull request #23184
Opened 2024-02-29 10:04 UTC by TweetyDaBird

## Description

Added auto shift and encoder mapping

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-02 06:22 UTC, drashna requested changes

2024-03-02 06:22 UTC, drashna commented on keyboards/tweetydabird/chameleon/info.json
> +		"extrakey": true,
```suggestion
        "extrakey": true,
```

2024-03-29 04:36 UTC, drashna approved these changes

2024-03-29 05:46 UTC, fauxpark requested changes
Keyboard updates should go through `develop`, unless they are bugfixes.

2024-08-05 01:55 UTC, closed without merging