Add Baion878 PCB
qmk/qmk_firmware pull request #23198
Opened 2024-03-02 13:34 UTC by ojthetiny

## Description

Add support for Baion878 TKL PCB line

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-02 19:42 UTC, waffle87 requested changes

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsa/config.h
> +/* Ensure we jump to bootloader if the RESET keycode was pressed */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Ensure we jump to bootloader if the QK_BOOT keycode was pressed
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsa/config.h
This file should be moved to the top keyboard level, as it's the same across all revisions.

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsa/keymaps/default/keymap.c
> +
```suggestion
		KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_RSFT, KC_TRNS,  						 KC_UP,
		KC_LCTL, KC_LGUI, KC_LALT,								 KC_SPC,  							KC_RALT, 	KC_RGUI, 	KC_RCTL, 				KC_LEFT, KC_DOWN, KC_RGHT
	)
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsa/keymaps/via/keymap.c
> +
```suggestion
		KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_RSFT, KC_TRNS,  						 KC_UP,
		KC_LCTL, KC_LGUI, KC_LALT,								 KC_SPC,  							KC_RALT, 	KC_RGUI, 	KC_RCTL, 				KC_LEFT, KC_DOWN, KC_RGHT
	)
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsi/config.h
This file should be removed, as per above comment.

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsi/keymaps/default/keymap.c
> +
```suggestion
		KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_RSFT, KC_TRNS,   						 KC_UP,
		KC_LCTL, KC_LGUI, KC_LALT, 									KC_SPC,  								KC_RALT, KC_RGUI, KC_RCTL, 						KC_LEFT, KC_DOWN, KC_RGHT
	)
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsi/keymaps/via/keymap.c
> +
```suggestion
		KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_RSFT, KC_TRNS,   						 KC_UP,
		KC_LCTL, KC_LGUI, KC_LALT, 									KC_SPC,  								KC_RALT, KC_RGUI, KC_RCTL, 						KC_LEFT, KC_DOWN, KC_RGHT
	)
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/readme.md
> +    make baion878/sl:default:flash
```suggestion
    make baion878/hsa:default
    make baion878/hsi:default
    make baion878/sl:default

Flashing example for this keyboard:

    make baion878/hsa:default:flash
    make baion878/hsi:default:flash
    make baion878/sl:default:flash
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/sl/config.h
This file should be removed, as per above comment.

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/sl/keymaps/default/keymap.c
> +
```suggestion
		KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_RSFT, KC_TRNS,   				 KC_UP,
		KC_LCTL, KC_LGUI, KC_LALT, 							KC_SPC, 								KC_APP,  KC_RALT, KC_RGUI, KC_RCTL, 			KC_LEFT, KC_DOWN, KC_RGHT
	)
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/sl/keymaps/via/keymap.c
> +
```suggestion
		KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, KC_RSFT, KC_TRNS,   				 KC_UP,
		KC_LCTL, KC_LGUI, KC_LALT, 							KC_SPC, 								KC_APP,  KC_RALT, KC_RGUI, KC_RCTL, 			KC_LEFT, KC_DOWN, KC_RGHT
	)
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsa/keymaps/default/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsa/keymaps/via/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsi/keymaps/default/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/hsi/keymaps/via/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/sl/keymaps/default/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-02 19:42 UTC, waffle87 commented on keyboards/baion878/sl/keymaps/via/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 ojthetiny
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-02 23:32 UTC, waffle87 approved these changes

2024-03-03 21:03 UTC, dunk2k requested changes
1. add Community Layout support
    1. rename LAYOUT to LAYOUT_all to conform to PR guidelines
2. add EoF where missing

2024-03-03 21:03 UTC, dunk2k commented on keyboards/baion878/sl/keymaps/default/keymap.c
> +	[0] = LAYOUT(
```suggestion
	[0] = LAYOUT_all(
```

2024-03-03 21:03 UTC, dunk2k commented on keyboards/baion878/sl/keymaps/via/keymap.c
> +	[0] = LAYOUT(
```suggestion
	[0] = LAYOUT_all(
```

2024-03-03 21:03 UTC, dunk2k commented on keyboards/baion878/sl/keymaps/via/rules.mk
> +VIA_ENABLE = yes
```suggestion
VIA_ENABLE = yes

```

2024-03-03 21:03 UTC, dunk2k commented on keyboards/baion878/sl/rules.mk
> +# This file intentionally left blank
```suggestion
# This file intentionally left blank

```

2024-03-10 00:20 UTC, fauxpark requested changes

2024-03-10 00:20 UTC, fauxpark commented on keyboards/baion878/sl/info.json
Please run `qmk format-json -i` on this file.

2024-03-10 00:20 UTC, fauxpark commented on keyboards/baion878/hsi/info.json
Please run `qmk format-json -i` on this file.

2024-03-10 00:20 UTC, fauxpark commented on keyboards/baion878/hsa/info.json
Please run `qmk format-json -i` on this file.

2024-03-10 04:30 UTC, zvecr requested changes

2024-03-10 04:30 UTC, zvecr commented on keyboards/baion878/config.h
This file should be removed, as it only duplicates default settings

```
platforms/chibios/boards/GENERIC_STM32_F072XB/configs/config.h
19:#    define EARLY_INIT_PERFORM_BOOTLOADER_JUMP TRUE
```

2024-03-10 10:47 UTC, ojthetiny commented on keyboards/baion878/config.h
Removed

2024-03-10 10:47 UTC, ojthetiny commented on keyboards/baion878/sl/info.json
done

2024-03-11 07:31 UTC, fauxpark requested changes

2024-03-11 07:31 UTC, fauxpark commented on keyboards/baion878/sl/info.json
> +        "on_state": 1,
```suggestion
```

2024-03-11 07:31 UTC, fauxpark commented on keyboards/baion878/readme.md
> +    878SL for Universal Solderable
```suggestion
 * 878HSA for ANSI Hotswap
 * 878HSI for ISO Hotwsap
 * 878SL for Universal Solderable
```

2024-03-11 07:31 UTC, fauxpark commented on keyboards/baion878/hsa/info.json
> +        "on_state": 1,
```suggestion
```

2024-03-11 07:31 UTC, fauxpark commented on keyboards/baion878/hsi/info.json
> +        "on_state": 1,
```suggestion
```

2024-03-14 17:47 UTC, fauxpark commented
There is no need to continually merge master. Please do not do that.

2024-03-29 04:40 UTC, drashna commented on keyboards/baion878/hsa/keymaps/default/keymap.c
Please replace the tabs with spaces.

2024-03-29 04:40 UTC, drashna commented on keyboards/baion878/hsa/keymaps/via/keymap.c
Same

2024-06-13 01:51 UTC, closed without merging