switch to data driven config
qmk/qmk_firmware pull request #23228
Opened 2024-03-06 14:28 UTC by jotix

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-06 18:54 UTC, zvecr requested changes

2024-03-06 19:51 UTC, jotix commented on keyboards/handwired/jotanck/info.json
> +    "development_board": "promicro",
Thank you for the info, I've updated the json file

2024-03-06 22:22 UTC, waffle87 approved these changes

2024-03-09 14:51 UTC, drashna approved these changes

2024-03-09 14:52 UTC, merged