Add SIRIND Brick65
qmk/qmk_firmware pull request #23245
Opened 2024-03-09 00:54 UTC by eerraa

SIRIND Brick65

## Description
Brick65 is a 65% ANSI layout Custom Keyboard
Powered by ATMEGA32U4

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-12 17:30 UTC, waffle87 approved these changes

2024-03-12 22:15 UTC, drashna approved these changes

2024-03-12 22:23 UTC, fauxpark requested changes

2024-03-12 22:23 UTC, fauxpark commented on keyboards/era/sirind/brick65/readme.md
> +![Brick65](https://i.imgur.com/qyQYWfj.jpg)
```suggestion
![Brick65](https://i.imgur.com/qyQYWfjh.jpg)
```

2024-03-13 00:53 UTC, zvecr commented on keyboards/era/sirind/brick65/keymaps/default/keymap.c
> +        KC_LCTL,    KC_LWIN,  KC_LALT,                   KC_SPC,           KC_SPC,           KC_SPC,  KC_RALT, KC_RCTL,            KC_LEFT,   KC_DOWN,   KC_RGHT
```suggestion
        KC_LCTL,    KC_LWIN,  KC_LALT,                   KC_SPC,           MO(1),           KC_SPC,  KC_RALT, KC_RCTL,            KC_LEFT,   KC_DOWN,   KC_RGHT
```

2024-03-13 02:16 UTC, eerraa commented on keyboards/era/sirind/brick65/keymaps/default/keymap.c
> +        KC_LCTL,    KC_LWIN,  KC_LALT,                   KC_SPC,           KC_SPC,           KC_SPC,  KC_RALT, KC_RCTL,            KC_LEFT,   KC_DOWN,   KC_RGHT
Thank you sir!

2024-03-13 03:10 UTC, fauxpark requested changes

2024-03-13 03:10 UTC, fauxpark commented on keyboards/era/sirind/brick65/keymaps/default/keymap.c
> +        KC_LCTL,    KC_LWIN,  KC_LALT,                   KC_SPC,           MO(1),            KC_SPC,,  KC_RALT, KC_RCTL,            KC_LEFT,   KC_DOWN,   KC_RGHT
```suggestion
        KC_LCTL,    KC_LWIN,  KC_LALT,                   KC_SPC,           MO(1),            KC_SPC,  KC_RALT, KC_RCTL,            KC_LEFT,   KC_DOWN,   KC_RGHT
```
Typo in last review

2024-03-13 03:14 UTC, zvecr approved these changes

2024-03-13 03:18 UTC, fauxpark approved these changes

2024-03-13 03:21 UTC, merged