Ares Layout Additions
qmk/qmk_firmware pull request #23254
Opened 2024-03-10 08:15 UTC by noroadsleft

## Description

- adds seven new layouts
- adds layout/matrix diagram
- extends Community Layout support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-10 08:20 UTC, fauxpark approved these changes

2024-03-10 09:01 UTC, dunk2k requested changes
include 60*wkl* Community Layouts

2024-03-10 09:01 UTC, dunk2k commented on keyboards/ares/info.json
>          }
```suggestion
        },
        "LAYOUT_60_iso_wkl": {
            "layout": [
                {"matrix": [4, 0], "x": 0, "y": 0},
                {"matrix": [4, 1], "x": 1, "y": 0},
                {"matrix": [4, 2], "x": 2, "y": 0},
                {"matrix": [4, 3], "x": 3, "y": 0},
                {"matrix": [4, 4], "x": 4, "y": 0},
                {"matrix": [4, 5], "x": 5, "y": 0},
                {"matrix": [4, 6], "x": 6, "y": 0},
                {"matrix": [4, 7], "x": 7, "y": 0},
                {"matrix": [4, 8], "x": 8, "y": 0},
                {"matrix": [4, 9], "x": 9, "y": 0},
                {"matrix": [4, 10], "x": 10, "y": 0},
                {"matrix": [4, 11], "x": 11, "y": 0},
                {"matrix": [4, 12], "x": 12, "y": 0},
                {"matrix": [4, 13], "x": 13, "y": 0, "w": 2},

                {"matrix": [3, 0], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [3, 1], "x": 1.5, "y": 1},
                {"matrix": [3, 2], "x": 2.5, "y": 1},
                {"matrix": [3, 3], "x": 3.5, "y": 1},
                {"matrix": [3, 4], "x": 4.5, "y": 1},
                {"matrix": [3, 5], "x": 5.5, "y": 1},
                {"matrix": [3, 6], "x": 6.5, "y": 1},
                {"matrix": [3, 7], "x": 7.5, "y": 1},
                {"matrix": [3, 8], "x": 8.5, "y": 1},
                {"matrix": [3, 9], "x": 9.5, "y": 1},
                {"matrix": [3, 10], "x": 10.5, "y": 1},
                {"matrix": [3, 11], "x": 11.5, "y": 1},
                {"matrix": [3, 12], "x": 12.5, "y": 1},

                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [2, 7], "x": 7.75, "y": 2},
                {"matrix": [2, 8], "x": 8.75, "y": 2},
                {"matrix": [2, 9], "x": 9.75, "y": 2},
                {"matrix": [2, 10], "x": 10.75, "y": 2},
                {"matrix": [2, 11], "x": 11.75, "y": 2},
                {"matrix": [2, 12], "x": 12.75, "y": 2},
                {"matrix": [2, 13], "x": 13.75, "y": 1, "w": 1.25, "h": 2},

                {"matrix": [1, 0], "x": 0, "y": 3, "w": 1.25},
                {"matrix": [1, 1], "x": 1.25, "y": 3},
                {"matrix": [1, 2], "x": 2.25, "y": 3},
                {"matrix": [1, 3], "x": 3.25, "y": 3},
                {"matrix": [1, 4], "x": 4.25, "y": 3},
                {"matrix": [1, 5], "x": 5.25, "y": 3},
                {"matrix": [1, 6], "x": 6.25, "y": 3},
                {"matrix": [1, 7], "x": 7.25, "y": 3},
                {"matrix": [1, 8], "x": 8.25, "y": 3},
                {"matrix": [1, 9], "x": 9.25, "y": 3},
                {"matrix": [1, 10], "x": 10.25, "y": 3},
                {"matrix": [1, 11], "x": 11.25, "y": 3},
                {"matrix": [1, 12], "x": 12.25, "y": 3, "w": 2.75},

                {"matrix": [0, 0], "x": 0, "y": 4, "w": 1.5},
                {"matrix": [0, 2], "x": 2.5, "y": 4, "w": 1.5},
                {"matrix": [0, 6], "x": 4, "y": 4, "w": 7},
                {"matrix": [0, 11], "x": 11, "y": 4, "w": 1.5},
                {"matrix": [0, 13], "x": 13.5, "y": 4, "w": 1.5}
            ]
        },
        "LAYOUT_60_iso_wkl_split_bs_rshift": {
            "layout": [
                {"matrix": [4, 0], "x": 0, "y": 0},
                {"matrix": [4, 1], "x": 1, "y": 0},
                {"matrix": [4, 2], "x": 2, "y": 0},
                {"matrix": [4, 3], "x": 3, "y": 0},
                {"matrix": [4, 4], "x": 4, "y": 0},
                {"matrix": [4, 5], "x": 5, "y": 0},
                {"matrix": [4, 6], "x": 6, "y": 0},
                {"matrix": [4, 7], "x": 7, "y": 0},
                {"matrix": [4, 8], "x": 8, "y": 0},
                {"matrix": [4, 9], "x": 9, "y": 0},
                {"matrix": [4, 10], "x": 10, "y": 0},
                {"matrix": [4, 11], "x": 11, "y": 0},
                {"matrix": [4, 12], "x": 12, "y": 0},
                {"matrix": [4, 13], "x": 13, "y": 0},
                {"matrix": [4, 14], "x": 14, "y": 0},

                {"matrix": [3, 0], "x": 0, "y": 1, "w": 1.5},
                {"matrix": [3, 1], "x": 1.5, "y": 1},
                {"matrix": [3, 2], "x": 2.5, "y": 1},
                {"matrix": [3, 3], "x": 3.5, "y": 1},
                {"matrix": [3, 4], "x": 4.5, "y": 1},
                {"matrix": [3, 5], "x": 5.5, "y": 1},
                {"matrix": [3, 6], "x": 6.5, "y": 1},
                {"matrix": [3, 7], "x": 7.5, "y": 1},
                {"matrix": [3, 8], "x": 8.5, "y": 1},
                {"matrix": [3, 9], "x": 9.5, "y": 1},
                {"matrix": [3, 10], "x": 10.5, "y": 1},
                {"matrix": [3, 11], "x": 11.5, "y": 1},
                {"matrix": [3, 12], "x": 12.5, "y": 1},

                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [2, 7], "x": 7.75, "y": 2},
                {"matrix": [2, 8], "x": 8.75, "y": 2},
                {"matrix": [2, 9], "x": 9.75, "y": 2},
                {"matrix": [2, 10], "x": 10.75, "y": 2},
                {"matrix": [2, 11], "x": 11.75, "y": 2},
                {"matrix": [2, 12], "x": 12.75, "y": 2},
                {"matrix": [2, 13], "x": 13.75, "y": 1, "w": 1.25, "h": 2},

                {"matrix": [1, 0], "x": 0, "y": 3, "w": 1.25},
                {"matrix": [1, 1], "x": 1.25, "y": 3},
                {"matrix": [1, 2], "x": 2.25, "y": 3},
                {"matrix": [1, 3], "x": 3.25, "y": 3},
                {"matrix": [1, 4], "x": 4.25, "y": 3},
                {"matrix": [1, 5], "x": 5.25, "y": 3},
                {"matrix": [1, 6], "x": 6.25, "y": 3},
                {"matrix": [1, 7], "x": 7.25, "y": 3},
                {"matrix": [1, 8], "x": 8.25, "y": 3},
                {"matrix": [1, 9], "x": 9.25, "y": 3},
                {"matrix": [1, 10], "x": 10.25, "y": 3},
                {"matrix": [1, 11], "x": 11.25, "y": 3},
                {"matrix": [1, 12], "x": 12.25, "y": 3, "w": 1.75},
                {"matrix": [1, 13], "x": 14, "y": 3},

                {"matrix": [0, 0], "x": 0, "y": 4, "w": 1.5},
                {"matrix": [0, 2], "x": 2.5, "y": 4, "w": 1.5},
                {"matrix": [0, 6], "x": 4, "y": 4, "w": 7},
                {"matrix": [0, 11], "x": 11, "y": 4, "w": 1.5},
                {"matrix": [0, 13], "x": 13.5, "y": 4, "w": 1.5}
            ]
        }
```

2024-03-10 09:05 UTC, dunk2k requested changes

2024-03-10 09:05 UTC, dunk2k commented on keyboards/ares/matrix_diagram.md
> +└─────┴───┴─────┴───────────────────────────┴─────┴───┴─────┘
```suggestion
└─────┴───┴─────┴───────────────────────────┴─────┴───┴─────┘
┌─────┬───┬─────┬───────────────────────┬─────┬───┬───┬─────┐
│00   │01 │02   │06                     │0A   │0B │0C │0D   │ Infinity/True HHKB
└─────┴───┴─────┴───────────────────────┴─────┴───┴───┴─────┘
```

2024-03-10 22:14 UTC, dunk2k approved these changes

2024-03-12 20:47 UTC, drashna approved these changes

2024-03-12 22:18 UTC, merged