Remove 60_ansi_arrow_split_bs_7u_spc Community Layout
qmk/qmk_firmware pull request #23259
Opened 2024-03-11 21:40 UTC by dunk2k

Requesting removal of named Community Layout, as it has low utilisation in keyboards directory and isn't showcased in Mechanical Keyboard communities.

## Description

Remove `60_ansi_arrow_split_bs_7u_spc` from:
- layouts/sub-directories
- `"community_layouts"` array in `info.json` for keyboards where this Community Layout is present.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-15 01:57 UTC, fauxpark requested changes
Needs to go through `develop`.

2024-03-15 08:39 UTC, fauxpark approved these changes

2024-05-01 19:17 UTC, noroadsleft approved these changes

2024-05-01 19:18 UTC, merged

2024-05-01 19:18 UTC, noroadsleft commented
Thanks!