Created PMK brand folder including posey_split keyboards with default and via keymaps.
qmk/qmk_firmware pull request #23258
Opened 2024-03-11 20:26 UTC by joliverMI

## Description

-Created a new main keyboard folder for new brand "PMK" (poseysmechanicalkeyboards)
-Created a sub-folder for a keyboard we will sell: posey_split
-Created 2 version folders for two versions we have in circulation (version 4 and 5):
Included "default" and "via" keymaps for each version.

Future PR will include a different layout we sell

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-11 22:44 UTC, joliverMI commented
@zvecr Thanks for promptly reviewing my PR. This is my first PR. I did review the PR checklist several times, so any violations are surely from my lack of understanding. If you could point me to the general areas that need improvement, I'd really appreciate it.

2024-03-11 23:07 UTC, waffle87 requested changes

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/keymaps/VIA/keymap.c
This directory must be renamed to lowercase.

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/keymaps/default/config.h
This file should be removed.

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/keymaps/default/keymap.c
> +#define _SYMB 9
```suggestion
enum layers {
    _QWERTY,
    _NAV,
    _SYMB
};
```

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/keymaps/VIA/keymap.c
> +    [_SYMB] = LAYOUT_game_split_85(
```suggestion
    [_QWERTY] = LAYOUT(
    // ┌────────┐        ┌────────┬────────┬────────┬────────┬────────┬───────┐ ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬───────┐
        KC_ESC,  KC_NO,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,    KC_F6,   MO(_SYMB),  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,   KC_F13,
     //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,     KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,   KC_BACKSPACE,
     //├────────┴────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┬───────┤
        KC_TAB,           KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_CAPS,          KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,     KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,      KC_ENT,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────────────┤
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,     KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,   KC_UP,
     //├──────────┬──────┴─┬───────┼───────┴────────┼────────┴────────┴───────┤ ├────────┴────────┴────────┼────────┼────────┼────────┼────────────────┤
        KC_LCTL,   KC_LGUI, MO(_NAV),    KC_LALT,                  KC_SPC,                    KC_SPC,          MO(_NAV),   KC_RGUI, KC_LEFT, KC_DOWN,  KC_RIGHT
     //└──────────┴────────┴───────┴────────────────┴─────────────────────────┘ └──────────────────────────┴────────┴────────┴────────┴───────┴────────┘
    ),
    [_NAV] = LAYOUT(
    // ┌────────┐        ┌────────┬────────┬────────┬────────┬────────┬───────┐ ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬───────┐
        KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, MO(_SYMB), KC_TRNS, KC_VOLD, KC_VOLU, KC_MUTE, KC_MPRV, KC_MPLY, KC_MNXT,
     //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
     //├────────┴────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┬───────┤
        KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_ENT,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┴────────────────┤
        KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_UP,
     //├──────────┬──────┴─┬───────┼───────┴────────┼────────┴────────┴───────┤ ├────────┴────────┴────────┼────────┼────────┼────────┼────────────────┤
        KC_TRNS,   KC_TRNS, KC_TRNS,  KC_TRNS,                 KC_TRNS,                   KC_TRNS,          KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RIGHT
     //└──────────┴────────┴───────┴────────────────┴─────────────────────────┘ └──────────────────────────┴────────┴────────┴────────┴───────┴────────┘
    ),
    [_SYMB] = LAYOUT(
```

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/keymaps/default/keymap.c
> +    [_SYMB] = LAYOUT_game_split_85(
```suggestion
    [_QWERTY] = LAYOUT(
    // ┌────────┐        ┌────────┬────────┬────────┬────────┬────────┬───────┐ ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬───────┐
        KC_ESC,  KC_NO,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,    KC_F6,   MO(_SYMB),  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,   KC_F13,
     //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,     KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,   KC_BACKSPACE,
     //├────────┴────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┬───────┤
        KC_TAB,           KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_CAPS,          KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,     KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,      KC_ENT,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────────────┤
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,     KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,   KC_UP,
     //├──────────┬──────┴─┬───────┼───────┴────────┼────────┴────────┴───────┤ ├────────┴────────┴────────┼────────┼────────┼────────┼────────────────┤
        KC_LCTL,   KC_LGUI, MO(_NAV),    KC_LALT,                  KC_SPC,                    KC_SPC,          MO(_NAV),   KC_RGUI, KC_LEFT, KC_DOWN,  KC_RIGHT
     //└──────────┴────────┴───────┴────────────────┴─────────────────────────┘ └──────────────────────────┴────────┴────────┴────────┴───────┴────────┘
    ),
    [_NAV] = LAYOUT(
    // ┌────────┐        ┌────────┬────────┬────────┬────────┬────────┬───────┐ ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬───────┐
        KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, MO(_SYMB), KC_TRNS, KC_VOLD, KC_VOLU, KC_MUTE, KC_MPRV, KC_MPLY, KC_MNXT,
     //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
     //├────────┴────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┬───────┤
        KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┼────────┴───────┤
        KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_ENT,
     //├─────────────────┼────────┼────────┼────────┼────────┼────────┼───────┤ ├────────┼────────┼────────┼────────┼────────┼────────┴────────────────┤
        KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_UP,
     //├──────────┬──────┴─┬───────┼───────┴────────┼────────┴────────┴───────┤ ├────────┴────────┴────────┼────────┼────────┼────────┼────────────────┤
        KC_TRNS,   KC_TRNS, KC_TRNS,  KC_TRNS,                 KC_TRNS,                   KC_TRNS,          KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RIGHT
     //└──────────┴────────┴───────┴────────────────┴─────────────────────────┘ └──────────────────────────┴────────┴────────┴────────┴───────┴────────┘
    ),
    [_SYMB] = LAYOUT(
```

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/posey_split_v4.c
This file should be removed.

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/posey_split_v4.h
> +}
This must migrated to `info.json` and this file removed.

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/readme.md
> +    make posey_split_v4:default:flash
```suggestion
![posey_split_v4](https://i.imgur.com/g3yf6alh.png)


* Keyboard Maintainer: [Javier Oliver](https://github.com/joliverMI)
* Hardware Supported: posey_split_v4 and logic_module_v1
* Hardware Availability: poseysmechanicalkeyboards.com

Make example for this keyboard (after setting up your build environment):

    make pmk/posey_split/posey_split_v4:default
    
Flashing example for this keyboard:

    make pmk/posey_split/posey_split_v4:default:flash
```

2024-03-11 23:07 UTC, waffle87 commented on keyboards/pmk/posey_split/posey_split_v4/rules.mk
> +SERIAL_DRIVER = usart
```suggestion
```

2024-03-11 23:10 UTC, waffle87 commented
Please apply the same changes to the `posey_split_v5` directory as well. Mind you, what is the difference between the two revision?

2024-03-11 23:26 UTC, zvecr requested changes
As with the previous reviews, the same should be applied to the other keyboard.

Also, the folder structure would be better as
```
keyboards/pmk/posey_split/posey_split/v4/info.json
keyboards/pmk/posey_split/posey_split/v4/rules.mk
keyboards/pmk/posey_split/posey_split/v5/info.json
keyboards/pmk/posey_split/posey_split/v5/rules.mk
```

With potentially common items pulled to the new parent folder.

2024-03-11 23:26 UTC, zvecr commented on keyboards/pmk/posey_split/posey_split_v4/config.h
> +#define SERIAL_PIO_USE_PIO1
```suggestion
```

2024-03-11 23:26 UTC, zvecr commented on keyboards/pmk/posey_split/posey_split_v4/info.json
> +        "enabled": true,
```suggestion
        "enabled": true,
        "handedness": {
            "pin": "GP18"
        }
```

2024-03-11 23:26 UTC, zvecr commented on keyboards/pmk/posey_split/posey_split_v4/info.json
> +    "debounce": 5,
```suggestion
```

2024-03-11 23:26 UTC, zvecr commented on keyboards/pmk/posey_split/posey_split_v4/config.h
> +#define NOP_FUDGE 0.4
`WS2812_PIO_USE_PIO1` wouldnt really be required either.
```suggestion
```

2024-03-12 20:16 UTC, joliverMI commented
> As with the previous reviews, the same should be applied to the other keyboard.
> 
> Also, the folder structure would be better as
> 
> ```
> keyboards/pmk/posey_split/posey_split/v4/info.json
> keyboards/pmk/posey_split/posey_split/v4/rules.mk
> keyboards/pmk/posey_split/posey_split/v5/info.json
> keyboards/pmk/posey_split/posey_split/v5/rules.mk
> ```
> 
> With potentially common config pulled to the new parent folder.

2024-03-12 20:19 UTC, joliverMI commented
@waffle87 Thank you (and the other reviewers) for so much detailed help. I'm new to all this but I learned a lot from this process and really appreciate your time. I think I got everything, and I've tested the new setup and it seems to be working. Is there a process to put this PR back in review?

2024-03-13 00:11 UTC, zvecr requested changes
Many requested changes have not been completed.

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v4/info.json
> +        }
```suggestion
```

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v4/keymaps/VIA/keymap.c
The `VIA` folder still needs to be renamed to lower case

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v5/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
This still needs filling out

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v5/rules.mk
> +# Split Board Configuration
```suggestion
```

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v5/keymaps/VIA/keymap.c
> +#define _SYMB 9
```suggestion
enum my_layers {
    _QWERTY,
    _NAV,
    _SYMB,
};
```

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v4/keymaps/default/keymap.c
> +#define _SYMB 9
```suggestion
enum my_layers {
    _QWERTY,
    _NAV,
    _SYMB,
};
```

2024-03-13 00:11 UTC, zvecr commented on keyboards/pmk/posey_split/v4/keymaps/VIA/keymap.c
> +#define _SYMB 9
```suggestion
enum my_layers {
    _QWERTY,
    _NAV,
    _SYMB,
};
```

2024-03-13 21:32 UTC, joliverMI commented
> Many requested changes have not been completed.
My apologies, I certainly did miss a few. I hope I haven't missed more this time.

I noticed the PR Lint and the QMK CI Build checks failed. Is there something I can learn from that? Does it point to an issue with my code?

Thanks so much

2024-03-13 21:45 UTC, zvecr requested changes

2024-03-13 21:45 UTC, zvecr commented on keyboards/pmk/posey_split/v4/readme.md
> +About Posey's Split Mechanical Keyboards
```suggestion
```

2024-03-13 21:45 UTC, zvecr commented on keyboards/pmk/posey_split/v5/readme.md
> +About Posey's Split Mechanical Keyboards
```suggestion
```

2024-03-13 21:45 UTC, zvecr commented on keyboards/pmk/posey_split/v4/keymaps/via/keymap.c
> +#define _SYMB 9
This has been requested multiple times
```suggestion
enum my_layers {
    _QWERTY,
    _NAV,
    _SYMB,
};
```

2024-03-13 21:45 UTC, zvecr commented on keyboards/pmk/posey_split/rules.mk
This file should be removed.

2024-03-19 18:39 UTC, joliverMI commented
Hello, I just wanted to check and make sure I've made necessary changes and that I am just waiting for review?

2024-03-20 14:51 UTC, waffle87 approved these changes

2024-03-20 14:52 UTC, merged