Qmk and via Swiss support
qmk/qmk_firmware pull request #23272
Opened 2024-03-13 21:40 UTC by Bregoliii

## A HHKB Keyboard that looks like swiss

## Added QMK and Via Support

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [x ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-13 21:50 UTC, waffle87 requested changes

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/config.h
This file should be removed.

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/keymaps/default/keymap.c
> +//ooga booga
```suggestion
// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/keymaps/default/readme.md
This file should be removed.

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/keymaps/via/keymap.c
> +//ooga booga
```suggestion
// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/keymaps/via/readme.md
This file should be removed.

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/readme.md
> +![Swiss](https://imgur.com/8G6MB5D)
```suggestion
![Swiss](https://i.imgur.com/8G6MB5Dh.png)
```

2024-03-13 21:50 UTC, waffle87 commented on keyboards/swiss/readme.md
> +    make Swiss:default:flash
```suggestion
    make swiss:default

Flashing example for this keyboard:

    make swiss:default:flash
```

2024-03-13 22:28 UTC, Bregoliii commented
uuh think i did it all correctly

2024-03-13 22:30 UTC, dunk2k requested changes
- add Community Layout support
  - adjust keymap layout macro name to match
- add End of File where missing

2024-03-13 23:09 UTC, waffle87 approved these changes

2024-03-13 23:12 UTC, dunk2k approved these changes

2024-03-15 01:26 UTC, drashna requested changes

2024-03-15 01:26 UTC, drashna commented on keyboards/swiss/keymaps/default/keymap.c
> +	KC_TRNS, KC_TRNS,                            KC_TRNS,                                     KC_TRNS,          KC_TRNS
```suggestion
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSPC,
    KC_LCTL, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
    KC_LGUI, KC_LALT,                            KC_SPC,                                      KC_RALT,          KC_RCTL
    ),
    /* FN */
    [1] = LAYOUT_60_hhkb(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_INS,  KC_DEL,
    KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SLCT, KC_PAUS, KC_UP,   KC_TRNS, KC_TRNS,
    KC_TRNS, KC_VOLD, KC_VOLU, KC_MUTE, KC_EJCT, KC_TRNS, KC_PAST, KC_PSLS, KC_HOME, KC_PGUP, KC_LEFT, KC_RGHT, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PPLS, KC_PMNS, KC_END,  KC_PGDN, KC_DOWN, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS,                            KC_TRNS,                                     KC_TRNS,          KC_TRNS
```

2024-03-15 01:26 UTC, drashna commented on keyboards/swiss/keymaps/via/keymap.c
> +	KC_TRNS, KC_TRNS,                            KC_TRNS,                                     KC_TRNS,          KC_TRNS
```suggestion
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSPC,
    KC_LCTL, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
    KC_LGUI, KC_LALT,                            KC_SPC,                                      KC_RALT,          KC_RCTL
    ),
    /* FN */
    [1] = LAYOUT_60_hhkb(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_INS,  KC_DEL,
    KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SLCT, KC_PAUS, KC_UP,   KC_TRNS, KC_TRNS,
    KC_TRNS, KC_VOLD, KC_VOLU, KC_MUTE, KC_EJCT, KC_TRNS, KC_PAST, KC_PSLS, KC_HOME, KC_PGUP, KC_LEFT, KC_RGHT, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PPLS, KC_PMNS, KC_END,  KC_PGDN, KC_DOWN, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS,                            KC_TRNS,                                     KC_TRNS,          KC_TRNS
```

2024-03-21 04:03 UTC, zvecr approved these changes

2024-03-21 04:04 UTC, merged