Add cycle7
qmk/qmk_firmware pull request #23290
Opened 2024-03-15 15:40 UTC by Vertex-kb

## Description
Add cycle7

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-15 15:42 UTC, keyboard-magpie commented
And you might you be, in relation to this closed PR? https://github.com/qmk/qmk_firmware/pull/20896

2024-03-15 15:46 UTC, Vertex-kb commented
> And you might you be, in relation to this closed PR? #20896

Yes, the current account will be used to continue

2024-03-15 18:16 UTC, keyboard-magpie commented
I presume you are part of the same organisation then. Closing and reopening PRs loses all of the feedback that has been added and makes reviewers work harder. Please don't do this.

Most of the suggestions that were made on the last PR have not been applied here; as a result the code is failing lint check. Please resolve.

2024-03-16 19:02 UTC, dunk2k requested changes

2024-03-16 19:09 UTC, dunk2k requested changes

2024-03-16 19:09 UTC, dunk2k commented on keyboards/vertex/cycle7/info.json
> +                {"matrix": [2, 12], "x": 12.75, "y": 2},
correct ISO Enter position in sequence to match Community Layout
```suggestion
                {"matrix": [1, 14], "x": 15.25, "y": 1},
                {"matrix": [1, 15], "x": 16.25, "y": 1},
                {"matrix": [2, 15], "x": 17.25, "y": 1},
                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [2, 7], "x": 7.75, "y": 2},
                {"matrix": [2, 8], "x": 8.75, "y": 2},
                {"matrix": [2, 9], "x": 9.75, "y": 2},
                {"matrix": [2, 10], "x": 10.75, "y": 2},
                {"matrix": [2, 11], "x": 11.75, "y": 2},
                {"matrix": [2, 12], "x": 12.75, "y": 2},
                {"matrix": [2, 13], "x": 13.75, "y": 1, "w": 1.25, "h": 2},
```

2024-03-16 19:09 UTC, dunk2k commented on keyboards/vertex/cycle7/info.json
> +                {"matrix": [2, 12], "x": 12.75, "y": 2},
Correct ISO Enter position in sequence to match Community Layout
```suggestion
                {"matrix": [1, 14], "x": 15.25, "y": 1},
                {"matrix": [1, 15], "x": 16.25, "y": 1},
                {"matrix": [2, 15], "x": 17.25, "y": 1},
                {"matrix": [2, 0], "x": 0, "y": 2, "w": 1.75},
                {"matrix": [2, 1], "x": 1.75, "y": 2},
                {"matrix": [2, 2], "x": 2.75, "y": 2},
                {"matrix": [2, 3], "x": 3.75, "y": 2},
                {"matrix": [2, 4], "x": 4.75, "y": 2},
                {"matrix": [2, 5], "x": 5.75, "y": 2},
                {"matrix": [2, 6], "x": 6.75, "y": 2},
                {"matrix": [2, 7], "x": 7.75, "y": 2},
                {"matrix": [2, 8], "x": 8.75, "y": 2},
                {"matrix": [2, 9], "x": 9.75, "y": 2},
                {"matrix": [2, 10], "x": 10.75, "y": 2},
                {"matrix": [2, 11], "x": 11.75, "y": 2},
                {"matrix": [2, 12], "x": 12.75, "y": 2},
                {"matrix": [2, 13], "x": 13.75, "y": 1, "w": 1.25, "h": 2},
```

2024-03-16 19:14 UTC, dunk2k requested changes
correct ISO keycodes

2024-03-16 19:14 UTC, dunk2k commented on keyboards/vertex/cycle7/keymaps/default/keymap.c
> +        KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_SLSH, KC_UP,
```suggestion
        KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_SLSH, KC_UP,
```

2024-03-16 19:14 UTC, dunk2k commented on keyboards/vertex/cycle7/keymaps/via/keymap.c
> +        KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_SLSH, KC_UP,
```suggestion
        KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_SLSH, KC_UP,
```

2024-03-16 19:14 UTC, dunk2k commented on keyboards/vertex/cycle7/keymaps/via/keymap.c
> +        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,
```suggestion
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
```

2024-03-16 19:14 UTC, dunk2k commented on keyboards/vertex/cycle7/keymaps/default/keymap.c
> +        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,
```suggestion
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
```

2024-03-19 10:13 UTC, dunk2k requested changes

2024-03-19 10:13 UTC, dunk2k commented on keyboards/vertex/cycle7/info.json
bump

2024-03-29 05:03 UTC, drashna approved these changes

2024-05-14 03:26 UTC, fauxpark approved these changes

2024-05-15 04:05 UTC, waffle87 approved these changes

2024-05-15 04:06 UTC, merged