Dev/kprepublic jj40 rev1
qmk/qmk_firmware pull request #23299
Opened 2024-03-16 09:52 UTC by noroadsleft

## Description

- moves `kprepublic/jj40` to `kprepublic/jj40/rev1`
  - hopefully avoids users flashing rev1 firmware to rev2 boards
- adds layout/matrix diagram
- adds two new layouts
- converts `rules.mk` to data driven
  - removed `console` and `command` from keyboard-level configuration
- renames `info.json` to `keyboard.json`
  - `rev1/rules.mk` remains present because `<FEATURE>_SUPPORTED` isn't part of data-driven config yet

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-16 10:47 UTC, dunk2k approved these changes

2024-03-16 18:14 UTC, zvecr requested changes

2024-03-16 18:14 UTC, zvecr commented on keyboards/kprepublic/jj40/rev1/keyboard.json
> +        "audio": false
```suggestion
        "rgblight": true
```

2024-03-17 05:55 UTC, zvecr approved these changes

2024-03-17 07:03 UTC, merged