Kalakos Bahrnob Layout Additions
qmk/qmk_firmware pull request #23300
Opened 2024-03-16 10:05 UTC by noroadsleft

## Description

- corrects the position of the rotary encoder
- adds 24 new layouts (I may be *slightly* neurotic...)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-16 10:09 UTC, fauxpark approved these changes

2024-03-16 10:51 UTC, dunk2k commented
Hi @noroadsleft 
As this PR introduces new layouts confirming this board has more than one physical layout, based on PR checklist should the `LAYOUT` layout macro be renamed to `LAYOUT_all`?

2024-03-16 11:03 UTC, dunk2k requested changes

2024-03-17 05:59 UTC, noroadsleft commented on keyboards/kalakos/bahrnob/info.json
oop, fixed.

2024-03-17 06:03 UTC, noroadsleft commented
> should the `LAYOUT` layout macro be renamed to `LAYOUT_all`?

@dunk2k,

I was struggling to decide whether I should do that in this PR, or issue a second PR targeting `develop`. Looking it over, I can add it here - the key sequence there is already correct.

2024-03-17 06:09 UTC, noroadsleft commented on keyboards/kalakos/bahrnob/info.json
> +                {"matrix": [0, 14], "x": 15.5, "y": 0},
Fixed in 96d8daa.

2024-03-17 08:36 UTC, dunk2k approved these changes

2024-03-29 05:06 UTC, drashna approved these changes

2024-03-29 05:06 UTC, merged