MechKeys ACR60 Layout Updates
qmk/qmk_firmware pull request #23309
Opened 2024-03-19 02:10 UTC by noroadsleft

## Description

- adds 22 layouts
- removes 3 layouts
- renames `LAYOUT_mitchsplit` to `LAYOUT_60_ansi_split_space_split_rshift`
- adds layout/matrix diagram
- enables Community Layout support

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-19 02:19 UTC, fauxpark approved these changes

2024-03-19 09:42 UTC, dunk2k commented
Hi @noroadsleft,
I'd have to challenge addition of `60_abnt2` layout:
1. Using [image](https://i.imgur.com/55UK7s9.jpeg) as reference of PCB in question: From left to right, the last 2 switch holes of the shift/4th row are same spacing as last 2 holes of the number/1st row, as well as key stabiliser holes for a 2u key - which affirms the 2nd last switch hole on the shift row is for a 2u key, not a 1.75u key.
2. Using the measurement between the ABNT2 `.` key switch hole and ABNT2 `;` key switch hole to locate the ABNT2 `/` key shows there isn't a switch hole in the PCB for ABNT2 `/` key.
[ABNT2 reference](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/KB_Portuguese_Brazil_ABNT2.svg/1200px-KB_Portuguese_Brazil_ABNT2.svg.png)

I'm struggling to locate official information from mechkeys.ca regarding this PCB, so images are best that's available 🫤

2024-03-19 09:53 UTC, dunk2k requested changes

2024-03-19 09:53 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +└─────┴───┴─────┴───────────────────────────┴─────┴───┴─────┘
```suggestion
└─────┴───┴─────┴───────────────────────────┴─────┴───┴─────┘
┌─────┬─────┬───────────────────────────┐
│40   │41   │46                         │                     LWKL
└─────┴─────┴───────────────────────────┘
```

2024-03-19 09:53 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +└───────┘
```suggestion
┌───────┐                                           ┌───────┐
│30     │ 2u LShift                       2u Rshift │3E     │
└───────┘                                           └───────┘
```

2024-03-19 10:06 UTC, dunk2k requested changes

2024-03-19 10:06 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +Alternate Shift Row Options:
```suggestion
Shift Row Options:
┌───────┐                                           ┌───────┐
│30     │ 2u LShift                       2u RShift │3E     │
└───────┘                                           └───────┘
```

2024-03-19 19:45 UTC, noroadsleft commented
> 2. Using the measurement between the ABNT2 `.` key switch hole and ABNT2 `;` key switch hole to locate the ABNT2 `/` key shows there isn't a switch hole in the PCB for ABNT2 `/` key.
>        [ABNT2 reference](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/KB_Portuguese_Brazil_ABNT2.svg/1200px-KB_Portuguese_Brazil_ABNT2.svg.png)
> 
> 
> I'm struggling to locate official information from mechkeys.ca regarding this PCB, so images are best that's available 🫤

MechKeys.ca shut down a couple years ago, and as near as I know its proprietor completely left the hobby.

If I overlay your ABNT2 reference image over the PCB photo, it looks like the layout might be supported *if* the user uses the 1u/1u split Left Shift, but not with the normal 1.25u/1u split.

I'd also found a [post on reddit](https://www.reddit.com/r/MechanicalKeyboards/comments/6u6y3n/help_flashing_qmk_on_acr60_linux/) where a couple users implied/stated that flashing DZ60 firmware to an ACR60 works, so I compared the existing matrix pins and layouts (the ones that were present before my additions) and everything matched up. I know that MechKeys PCBs were frequently based on DZ designs - the PCB designer used to be active around QMK and I was able to [confirm that directly with them some years ago](https://github.com/qmk/qmk_firmware/pull/7583#pullrequestreview-329606134), so the ACR60 being a modified DZ60 makes sense to me.

I'll set this to WIP and work out some more accurate details.

2024-03-19 23:16 UTC, dunk2k commented
On the, admittingly unrelated to this PR, mention of the DZ60 and `60_abnt2` Community Layout:
I've removed `60_abnt2` layout for keyboards `dz60` and `dztech/dz60v2` in PRs 21832 and 22841 respectively, as named boards don't support the 1u-1.75u split Right Shift of ABNT2/JIS 🙈.  

A great visual example of a PCB with both 2u Right Shift and 1u-1.75u Right Shift is the [Play Keyboard 60 v3](https://www.play-keyboard.store/products/play-keyboard-60-v3-pcb) 😊

2024-03-20 06:23 UTC, noroadsleft commented
I actually just came back to ask what you thought about leaving the layout in, but changing the key sizes to match what's actually supported on the PCB. It's the same number of keycodes and the same sequence.

2024-03-20 07:34 UTC, dunk2k commented
> I actually just came back to ask what you thought about leaving the layout in, but changing the key sizes to match what's actually supported on the PCB. It's the same number of keycodes and the same sequence.

I appreciate you asking my thoughts on it 🙂
The Community Layout "purist" in me is saying they ain't fussed so long as `60_abnt2` is removed from `community_layouts` 😆
Me personally, yeah keep the layout; resize keys to match what's supported and rename layout (`LAYOUT_abnt2` perhaps?), no harm in that 🙂

2024-03-20 23:51 UTC, dunk2k approved these changes

2024-03-25 14:09 UTC, dunk2k requested changes

2024-03-25 14:09 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +                                             │3C    │3D │3E │ 1.25u/1u LShift + 1.75u/1u/1u RShift
```suggestion
                                             │3C    │3D │3E │ 1.75u/1u/1u RShift
```

2024-03-27 19:59 UTC, dunk2k requested changes

2024-03-27 19:59 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +               └────────────────────────┘
repeats "Standard" bottom row layout
```suggestion
```

2024-03-27 19:59 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +│40   │41   │46                         │4A │4B │4C │4D │4E │
```suggestion
│40   │41   │46                         │4A │4B │4C │4D │4E │ LWKL
```

2024-03-27 19:59 UTC, dunk2k commented on keyboards/mechkeys/acr60/matrix_diagram.md
> +└─────┴───┴─────┴───────────────────────────┴─────┴───┴─────┘
```suggestion
└─────┴───┴─────┴───────────────────────────┴─────┴───┴─────┘
┌─────┬───┬─────┬───────────────────────────┬───┬───┬───┬───┐
│40   │41 │43   │46                         │4B │4C │4D │4E │ Tsangan Arrow
└─────┴───┴─────┴───────────────────────────┴───┴───┴───┴───┘
```

2024-03-29 18:08 UTC, dunk2k requested changes

2024-03-29 18:08 UTC, dunk2k commented on keyboards/mechkeys/acr60/keyboard.json
layout `LAYOUT_60_true_hhkb` is missing 🙈

2024-04-03 06:49 UTC, dunk2k approved these changes

2024-04-30 03:04 UTC, merged