Add t75 keyboard
qmk/qmk_firmware pull request #23344
Opened 2024-03-25 10:21 UTC by JackyJia73

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* New keyboard t75

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-25 10:31 UTC, fauxpark requested changes

2024-03-25 10:31 UTC, fauxpark commented on keyboards/vertex/t75/info.json
> +        "on_state": 1
```suggestion
        "caps_lock": "B1"
```

2024-03-25 10:31 UTC, fauxpark commented on keyboards/vertex/t75/info.json
Please run `qmk format-json -i` on this file.

2024-03-25 10:32 UTC, fauxpark requested changes

2024-03-25 10:32 UTC, fauxpark commented on keyboards/vertex/t75/keymaps/default/keymap.c
> +	)
```suggestion
	),
```

2024-03-25 11:01 UTC, JackyJia73 commented on keyboards/vertex/t75/info.json
Done

2024-03-25 11:11 UTC, fauxpark commented on keyboards/vertex/t75/info.json
Doesn't seem like it.

2024-03-25 12:08 UTC, JackyJia73 commented on keyboards/vertex/t75/info.json
Something wrong : You have not concluded your merge.

2024-03-25 16:55 UTC, waffle87 requested changes

2024-03-25 16:55 UTC, waffle87 commented on keyboards/vertex/t75/info.json
> +        "rgblight": false
```suggestion
        "extrakey": true,
        "mousekey": true,
        "nkro": true
```

2024-03-25 16:55 UTC, waffle87 commented on keyboards/vertex/t75/keymaps/default/keymap.c
> +		_______,  _______,   _______,                         _______,                         _______,   _______,   _______,  _______,  _______
Neither of these layers are accessible.
```suggestion
```

2024-03-25 16:55 UTC, waffle87 commented on keyboards/vertex/t75/keymaps/via/keymap.c
> +		_______,  _______,   _______,                         _______,                         _______,   _______,   _______,  _______,  _______
```suggestion
```

2024-03-25 23:56 UTC, waffle87 approved these changes

2024-03-26 01:37 UTC, JackyJia73 commented on keyboards/vertex/t75/info.json
Done

2024-03-26 02:15 UTC, JackyJia73 commented on keyboards/vertex/t75/keymaps/default/keymap.c
> +	)
updated

2024-03-26 09:02 UTC, fauxpark approved these changes

2024-03-26 23:30 UTC, merged