Data
qmk/qmk_firmware pull request #23357
Opened 2024-03-26 08:44 UTC by noroadsleft

## Description

Converts configuration definitions and rules to data-driven where applicable. Renames `info.json` to `keyboard.json` in instances where `rules.mk` can be safely deleted.

- keyboards with names beginning with `[0-9]`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-26 08:46 UTC, noroadsleft commented
Affects:

```
- `0xc7/61key`
- `0xcb/1337`
- `0xcb/static`
- `1upkeyboards/1up60hse`
- `1upkeyboards/1up60hte`
- `1upkeyboards/1up60rgb`
- `1upkeyboards/1upocarina`
- `1upkeyboards/1upsuper16v3`
- `1upkeyboards/pi60`
- `1upkeyboards/pi60_hse`
- `1upkeyboards/pi60_rgb`
- `1upkeyboards/pi60_rgb_v2`
- `1upkeyboards/super16`
- `1upkeyboards/super16v2`
- `1upkeyboards/sweet16/v1`
- `1upkeyboards/sweet16v2/kb2040`
- `1upkeyboards/sweet16v2/pro_micro`
- `25keys/aleth42`
- `25keys/cassette42`
- `25keys/zinc`
- `2key2crawl`
- `40percentclub/25`
- `40percentclub/4pack`
- `40percentclub/4x4`
- `40percentclub/5x5`
- `40percentclub/6lit`
- `40percentclub/foobar`
- `40percentclub/half_n_half`
- `40percentclub/i75`
- `40percentclub/luddite`
- `40percentclub/mf68`
- `40percentclub/nein`
- `40percentclub/nori`
- `40percentclub/polyandry`
- `40percentclub/tomato`
- `40percentclub/ut47`
- `45_ats`
- `4pplet/aekiso60/rev_b`
- `4pplet/eagle_viper_rep`
- `4pplet/steezy60`
- `4pplet/unextended_std/rev_a`
- `4pplet/waffling60`
- `4pplet/waffling80`
- `4pplet/yakiimo/rev_a`
- `8pack`
```

2024-03-26 08:51 UTC, fauxpark commented on keyboards/1upkeyboards/super16/super16.c
Some of these `g_led_configs` don't make sense. I would prefer if they were not migrated yet, until they can all be verified.

2024-03-26 08:56 UTC, fauxpark commented on keyboards/40percentclub/ut47/info.json
> +  "diode_direction": "COL2ROW",
This board uses a custom matrix, these should not be migrated.

2024-03-26 10:10 UTC, noroadsleft commented on keyboards/1upkeyboards/super16/super16.c
https://github.com/noroadsleft/qmk_firmware/compare/61f56998d1..0481165c7b

2024-03-26 10:29 UTC, dunk2k commented
Quick check, more so my curiosity: would this be a good opportunity to start replacing `processor` and `bootloader` with `development_board`, where applicable?

2024-03-26 17:35 UTC, noroadsleft commented
@dunk2k, 

I think that would be worth doing, but it's out of scope for this PR (/ series of PRs) - I'm only replacing like for like.

2024-03-26 18:51 UTC, dunk2k commented
> @dunk2k,
> 
> I think that would be worth doing, but it's out of scope for this PR (/ series of PRs) - I'm only replacing like for like.

Just what I was thinking 😆
A nice to do but unfortunately would add complexity to what's going to be a rather hefty series of PRs.

2024-03-27 12:02 UTC, dunk2k requested changes

2024-03-27 12:02 UTC, dunk2k commented on keyboards/40percentclub/4pack/keyboard.json
> +            "resync": "True"
CI Build fix
```suggestion
            "enabled": true,
            "resync": true
```

2024-03-28 03:59 UTC, noroadsleft commented on keyboards/40percentclub/4pack/keyboard.json
> +            "resync": "True"
https://github.com/noroadsleft/qmk_firmware/compare/3dfe833164..f68348d8f3

2024-03-28 07:13 UTC, dunk2k approved these changes

2024-03-29 03:21 UTC, fauxpark approved these changes

2024-03-30 13:36 UTC, zvecr approved these changes

2024-03-30 13:51 UTC, merged