Adds keyboard suikagiken_suika85ergo
qmk/qmk_firmware pull request #23380
Opened 2024-03-31 10:54 UTC by suikagiken

## Description

Adds suikagiken suika85ergo as a new keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* n/a 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-03-31 17:35 UTC, waffle87 requested changes

2024-03-31 17:35 UTC, waffle87 commented on keyboards/suikagiken/config.h
This file should be removed.

2024-03-31 17:35 UTC, waffle87 commented on keyboards/suikagiken/keymaps/default/config.h
This file should be removed.

2024-03-31 17:35 UTC, waffle87 commented on keyboards/suikagiken/info.json
> +    },
```suggestion
    },
    "dynamic_keymap": {
        "layer_count": 2
    },
```

2024-03-31 17:35 UTC, waffle87 commented on keyboards/suikagiken/keymaps/default/rules.mk
This file should be removed. VIA is not to be enabled in the `default` keymap, it should be in it's own `via` keymap directory.

2024-03-31 17:35 UTC, waffle87 commented on keyboards/suikagiken/keymaps/default/keymap.c
> +                          _______, _______, _______, MO(1)  , _______, KC_HOME, KC_PGDN, KC_END , _______, MO(1)  , _______, _______, _______
```suggestion
                          _______, _______, _______, _______  , _______, KC_HOME, KC_PGDN, KC_END , _______, _______  , _______, _______, _______  
```

2024-04-01 04:22 UTC, suikagiken commented
@waffle87 @lesshonor 
Thank you for your suggestion. I have made the changes and committed them, please check back.

2024-04-04 20:06 UTC, waffle87 requested changes

2024-04-04 20:06 UTC, waffle87 commented on keyboards/suikagiken/suika85ergo/info.json
> +        "LAYOUT_6x17": {
```suggestion
        "LAYOUT": {
```

2024-04-04 20:06 UTC, waffle87 commented on keyboards/suikagiken/suika85ergo/keymaps/default/keymap.c
> +    [1] = LAYOUT_6x17(
```suggestion
    [0] = LAYOUT(
        KC_ESC , KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  , KC_F6  ,                            KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12 , KC_DEL , 
        C(KC_X), KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,          KC_PSCR,          KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_MINS, KC_BSPC, 
        C(KC_C), KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,          KC_EQL ,          KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_BSLS, KC_ENT , 
        C(KC_V), KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_LBRC,          KC_RBRC, KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,  
                 KC_LSFT, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   ,          KC_UP  ,          KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT,  
                          KC_LCTL, KC_LWIN, KC_LOPT, MO(1)  , KC_SPC , KC_LEFT, KC_DOWN, KC_RGHT, KC_SPC , MO(1)  , KC_ROPT, KC_APP , KC_RCTL  
    ),
    [1] = LAYOUT(
```

2024-04-04 20:06 UTC, waffle87 commented on keyboards/suikagiken/suika85ergo/keymaps/via/keymap.c
> +    [1] = LAYOUT_6x17(
```suggestion
    [0] = LAYOUT(
        KC_ESC , KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  , KC_F6  ,                            KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12 , KC_DEL , 
        C(KC_X), KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   ,          KC_PSCR,          KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_MINS, KC_BSPC, 
        C(KC_C), KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,          KC_EQL ,          KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_BSLS, KC_ENT , 
        C(KC_V), KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_LBRC,          KC_RBRC, KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,  
                 KC_LSFT, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   ,          KC_UP  ,          KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT,  
                          KC_LCTL, KC_LWIN, KC_LOPT, MO(1)  , KC_SPC , KC_LEFT, KC_DOWN, KC_RGHT, KC_SPC , MO(1)  , KC_ROPT, KC_APP , KC_RCTL  
    ),
    [1] = LAYOUT(
```

2024-04-04 20:06 UTC, waffle87 commented on keyboards/suikagiken/suika85ergo/keymaps/via/keymap.c
> +                          _______, _______, _______, MO(1)  , _______, KC_HOME, KC_PGDN, KC_END , _______, MO(1)  , _______, _______, _______
```suggestion
                          _______, _______, _______, _______, _______, KC_HOME, KC_PGDN, KC_END , _______, _______, _______, _______, _______  
```

2024-04-05 06:48 UTC, suikagiken commented
As pointed out, Elite-C is used. I've also fixed the other points, thank you.

2024-04-05 14:41 UTC, waffle87 approved these changes

2024-04-06 00:36 UTC, fauxpark approved these changes

2024-04-17 13:46 UTC, merged