Tidy up keyboards/zvecr
qmk/qmk_firmware pull request #23418
Opened 2024-04-04 23:09 UTC by zvecr

## Description

- Aligns to `keyboard.json `
- Removes `DEFAULT_FOLDER`
- Fixes lint warnings on missing headers

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-04 23:49 UTC, dunk2k approved these changes

2024-04-04 23:57 UTC, fauxpark requested changes

2024-04-04 23:57 UTC, fauxpark commented on keyboards/zvecr/split_blackpill/split_blackpill.c
> +#include "gpio.h"
```suggestion
#include "quantum.h"
```
This is fine here.

2024-04-04 23:57 UTC, fauxpark commented on keyboards/zvecr/zv48/zv48.c
> +#include "gpio.h"
```suggestion
#include "quantum.h"
```

2024-04-05 00:28 UTC, fauxpark approved these changes

2024-04-05 00:47 UTC, daskygit commented
could swap over the `palSetLineMode` to `gpio_set_pin_output_push_pull`/`gpio_set_pin_output_open_drain`

2024-04-05 01:36 UTC, daskygit approved these changes

2024-04-05 01:38 UTC, merged