Add MacOS Czech ISO and ANSI keymaps #23346
qmk/qmk_firmware pull request #23412
Opened 2024-04-03 19:54 UTC by Tabonx

## Description

This pull request introduces MacOS Czech input keymaps for both ANSI and ISO layouts.

The changes include:
- Declarations added in `keycodes_czech_mac_ansi_0.0.1.hjson` and `keycodes_czech_mac_iso_0.0.1.hjson` files.
- Generated keymap headers
- `SEND_STRING` lookup table.
- Documentation references updated accordingly.

Key names have been reused from `keycodes_czech_0.0.1.hjson` or other languages where necessary. 

All keycodes and the `SEND_STRING` macro, which sends the entire ASCII table, have been validated and tested.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [X] Documentation

## Issues Fixed or Closed by This PR

* #23346

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-07 01:10 UTC, fauxpark requested changes

2024-04-07 01:10 UTC, fauxpark commented on data/constants/keycodes/extras/keycodes_czech_mac_ansi_0.0.1.hjson
> +            "key": "CZ_ZDOT",
```suggestion
            "key": "CZ_CZDT",
```

2024-04-07 01:10 UTC, fauxpark commented on data/constants/keycodes/extras/keycodes_czech_mac_ansi_0.0.1.hjson
> +            "key": "CZ_UAOG",
``
```suggestion
            "key": "CZ_CAOG",
```

2024-04-07 01:10 UTC, fauxpark commented on data/constants/keycodes/extras/keycodes_czech_mac_iso_0.0.1.hjson
> +            "key": "CZ_HAT",
``
```suggestion
            "key": "CZ_DCIR",
```

2024-04-07 01:10 UTC, fauxpark commented on data/constants/keycodes/extras/keycodes_czech_mac_iso_0.0.1.hjson
> +            "key": "CZ_UZDT",
```suggestion
            "key": "CZ_CZDT",
```

2024-04-07 01:10 UTC, fauxpark commented on data/constants/keycodes/extras/keycodes_czech_mac_iso_0.0.1.hjson
> +            "key": "CZ_UAOG",
```suggestion
            "key": "CZ_CAOG",
```

2024-04-07 14:52 UTC, fauxpark approved these changes

2024-05-01 06:53 UTC, drashna approved these changes

2024-05-01 06:53 UTC, merged