Colemak now working with special chars
qmk/qmk_firmware pull request #23410
Opened 2024-04-03 16:17 UTC by MackanT

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-04 05:33 UTC, drashna requested changes

2024-04-04 05:33 UTC, drashna commented on keyboards/handwired/dactyl_manuform/4x6/info.json
> +    "pin_compatible": "promicro",
Processor and pin compatibility is set by dev board. 
```suggestion
    "development_board": "promicro",
```

2024-04-04 05:33 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6_main/.gitignore
This should be removed.

2024-04-04 05:33 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6_main/LICENSE
?

2024-04-04 05:33 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6_main/info.json
> +    "bootloader": "caterina",
```suggestion
    "development_board": "promicro",
```

2024-04-04 05:33 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6_main/keymaps/swedish/config.h
This file can be removed, as default behavior is master left.

2024-04-04 05:33 UTC, drashna commented on keyboards/handwired/dactyl_manuform/5x6_main/keymaps/swedish/keymap.c
> +// //Determine the current tap dance state
Commented code should be removed.

2024-04-05 14:22 UTC, MackanT commented
Opps, no it was not meant for the main repository, my bad!

2024-04-05 14:22 UTC, closed without merging