Add Meow65
qmk/qmk_firmware pull request #23427
Opened 2024-04-06 04:28 UTC by EasonQian1

## Description
Add Meow65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-06 06:29 UTC, fauxpark requested changes

2024-04-06 06:29 UTC, fauxpark commented on keyboards/eason/meow65/info.json
> +        "on_state": 1
```suggestion
        "caps_lock": "C13"
```

2024-04-06 07:34 UTC, dunk2k requested changes

2024-04-06 07:34 UTC, dunk2k commented on keyboards/eason/meow65/info.json
> +    ],
```suggestion
```

2024-04-06 07:34 UTC, dunk2k commented on keyboards/eason/meow65/info.json
> +        "LAYOUT_65_ansi": {
```suggestion
        "LAYOUT_ansi": {
```

2024-04-06 07:34 UTC, dunk2k commented on keyboards/eason/meow65/info.json
> +        "LAYOUT_tkl_iso": {
```suggestion
        "LAYOUT_iso": {
```

2024-04-06 07:34 UTC, dunk2k commented on keyboards/eason/meow65/keymaps/default/keymap.c
> +           KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,
```suggestion
           KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,  KC_PGDN,
           KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,
```

2024-04-06 07:34 UTC, dunk2k commented on keyboards/eason/meow65/keymaps/via/keymap.c
> +           KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,
```suggestion
           KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,  KC_PGDN,
           KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,
```

2024-04-06 18:23 UTC, waffle87 approved these changes

2024-05-01 06:59 UTC, drashna approved these changes

2024-05-21 00:16 UTC, merged