[Keyboard] NK Classic TKL
qmk/qmk_firmware pull request #23435
Opened 2024-04-07 17:09 UTC by yiancar

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-07 17:21 UTC, zvecr requested changes

2024-04-07 17:21 UTC, zvecr commented on keyboards/novelkeys/nk_classic_tkl/info.json
> +        "led_count": 92,
```suggestion
```

2024-04-07 17:21 UTC, zvecr commented on keyboards/novelkeys/nk_classic_tkl/info.json
> +        "rgblight": false
```suggestion
        "bootmagic": true,
        "command": false,
        "console": false,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgb_matrix": true
```

2024-04-07 17:21 UTC, zvecr commented on keyboards/novelkeys/nk_classic_tkl/keymaps/default/keymap.c
> +  RETRO_RGB = QK_KB_0
```suggestion
  RETRO_RGB = QK_USER_0
```

2024-04-07 17:21 UTC, zvecr commented on keyboards/novelkeys/nk_classic_tkl/readme.md
> +* Hardware Supported: A 65% with macro keys keyboard with STM32F072CB or APM compatible
65% tkl?

2024-04-07 18:02 UTC, yiancar commented on keyboards/novelkeys/nk_classic_tkl/info.json
> +        "led_count": 92,
nice! this is no longer needed!

2024-04-07 18:03 UTC, yiancar commented on keyboards/novelkeys/nk_classic_tkl/readme.md
> +* Hardware Supported: A 65% with macro keys keyboard with STM32F072CB or APM compatible
Upsie copypasta! thank you:)

2024-04-12 17:00 UTC, dunk2k requested changes

2024-04-12 17:00 UTC, dunk2k commented on keyboards/novelkeys/nk_classic_tkl/readme.md
Image of PCB in question would be helpful 🙂

2024-04-24 21:01 UTC, keyboard-magpie approved these changes

2024-04-30 04:14 UTC, drashna approved these changes

2024-05-02 22:21 UTC, merged