Data-Driven Keyboard Conversions: D
qmk/qmk_firmware pull request #23461
Opened 2024-04-12 05:03 UTC by noroadsleft

## Description

Converts `rules.mk` entries to data-driven where applicable. Renames `info.json` to `keyboard.json` in instances where `rules.mk` can be safely deleted.

- keyboards with names beginning with `d`

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-12 05:25 UTC, zvecr approved these changes

2024-04-12 07:22 UTC, dunk2k approved these changes

2024-04-12 10:44 UTC, fauxpark requested changes

2024-04-12 10:44 UTC, fauxpark commented on keyboards/dumbpad/v3x/info.json
> +    "features": {
`rules.mk` missed here

2024-04-12 21:33 UTC, noroadsleft commented on keyboards/dumbpad/v3x/info.json
> +    "features": {
Good catch, thanks.

2024-04-13 02:33 UTC, fauxpark approved these changes

2024-04-13 05:33 UTC, merged