Add imi60
qmk/qmk_firmware pull request #23570
Opened 2024-04-20 00:12 UTC by key10iq

## Description

imi60 - 60% PCB compatible with keyboards by La-Versa: Animi, Mirimi and Otsukimi (keyboards known only in a small local community).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Added new keyboard - keyten/imi60 (QMK and VIA)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-20 18:43 UTC, waffle87 approved these changes

2024-04-30 02:10 UTC, drashna requested changes

2024-04-30 02:10 UTC, drashna commented on keyboards/keyten/imi60/info.json
> +        "console": false,
This can be safely removed. 
```suggestion
```

2024-05-01 06:32 UTC, drashna approved these changes

2024-05-01 06:32 UTC, merged