Add Lisa
qmk/qmk_firmware pull request #23575
Opened 2024-04-20 14:24 UTC by key10iq

## Description

Lisa is a QMK and VIA compatible Tadpole mount keyboard with Prime_E layout.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Added new keyboard - keyten/lisa (QMK and VIA)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-20 14:42 UTC, key10iq commented
I don't understand what formatting is required of me

![image](https://github.com/qmk/qmk_firmware/assets/38141348/73465d88-43f3-45cf-a080-ca664c829f95)

2024-04-20 15:02 UTC, sigprof commented
As usual, lint wants Unix-style line endings in all files, and you have CRLF in `info.json`.

2024-04-20 15:20 UTC, key10iq commented
> As usual, lint wants Unix-style line endings in all files, and you have CRLF in `info.json`.

Spasibo, Sergey

2024-04-20 18:42 UTC, waffle87 requested changes

2024-04-20 18:42 UTC, waffle87 commented on keyboards/keyten/lisa/keymaps/default/keymap.c
> +}
This should be moved to the keyboard level in a `lisa.c` file.
```suggestion
```

2024-04-20 18:42 UTC, waffle87 commented on keyboards/keyten/lisa/keymaps/default/keymap.c
> +//}
```suggestion
```

2024-04-20 18:42 UTC, waffle87 commented on keyboards/keyten/lisa/keymaps/default/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-04-20 18:42 UTC, waffle87 commented on keyboards/keyten/lisa/keymaps/via/keymap.c
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
```suggestion
// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-04-20 18:42 UTC, waffle87 commented on keyboards/keyten/lisa/keymaps/via/keymap.c
> +//}
As above.
```suggestion
```

2024-04-21 08:36 UTC, waffle87 commented on keyboards/keyten/lisa/lisa.c
> +//}
```suggestion
void matrix_init_kb(void) {
    gpio_set_pin_output(B2);
    gpio_write_pin_high(B2);
    matrix_init_user();
}
```

2024-04-22 03:46 UTC, fauxpark commented on keyboards/keyten/lisa/lisa.c
> +    gpio_write_pin_high(B2);
What is this for?

2024-04-22 03:50 UTC, key10iq commented on keyboards/keyten/lisa/lisa.c
> +    gpio_write_pin_high(B2);
One LED indicator is always on

2024-04-22 03:59 UTC, fauxpark requested changes

2024-04-22 03:59 UTC, fauxpark commented on keyboards/keyten/lisa/lisa.c
> +    gpio_write_pin_high(B2);
```suggestion
#include "quantum.h"

#define LED_INDICATOR_PIN B2

void matrix_init_kb(void) {
    gpio_set_pin_output(LED_INDICATOR_PIN);
    gpio_write_pin_high(LED_INDICATOR_PIN);
```
Feel free to rename this to something more descriptive.

2024-04-22 04:09 UTC, fauxpark approved these changes

2024-04-22 14:21 UTC, waffle87 approved these changes

2024-04-22 14:22 UTC, merged