Add support for Bling65 PCB
qmk/qmk_firmware pull request #23587
Opened 2024-04-22 16:23 UTC by Deemen17

## Description

Add support for Bling65 PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-25 17:27 UTC, waffle87 requested changes
There are also submodule changes that need to be reverted.

2024-04-25 17:27 UTC, waffle87 commented on keyboards/deemen17/bling65/keymaps/default/keymap.c
> +        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                    KC_RALT, MO(1),   KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```suggestion
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                    KC_RALT, _______,   KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```

2024-04-25 17:27 UTC, waffle87 commented on keyboards/deemen17/bling65/keymaps/via/keymap.c
> +        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                    KC_RALT, MO(1),   KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```suggestion
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                    KC_RALT, _______,   KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```

2024-04-30 01:42 UTC, drashna commented
For the submodule, you should be able to cd into that directory and run `git checkout qmk-master`, cd out of it, and commit the changes.

2024-05-06 16:35 UTC, Deemen17 commented
> For the submodule, you should be able to cd into that directory and run `git checkout qmk-master`, cd out of it, and commit the changes.

Did I leave out the submodule change? I'm a bit new to git so I'm not sure yet

2024-05-19 05:11 UTC, drashna approved these changes

2024-07-07 07:40 UTC, fauxpark requested changes

2024-07-07 07:40 UTC, fauxpark commented on keyboards/deemen17/bling65/rules.mk
This file can be deleted.

2024-07-07 07:40 UTC, fauxpark commented on keyboards/deemen17/bling65/info.json
This file should be renamed to `keyboard.json`.

2024-08-26 10:38 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-11-12 02:00 UTC, closed without merging