[MECHWILD] New Keyboard BB65
qmk/qmk_firmware pull request #23581
Opened 2024-04-21 14:11 UTC by stephondoestech

## Description

Submitting this on behalf of @lesshonor. This is to add a default keymap for the BB65 to the core qmk repo. This keymap is the same as the image listed on the hardsite shown [here](https://mechwild.com/product/bb65/). 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-21 19:56 UTC, waffle87 commented on keyboards/mechwild/bb65/readme.md
> +![bb65](https://i.imgur.com/0PrDjuSh.png)
```suggestion
![bb65](https://i.imgur.com/0PrDjuS.png)
```

2024-04-23 19:53 UTC, dunk2k requested changes

2024-04-23 19:53 UTC, dunk2k commented on keyboards/mechwild/bb65/info.json
> +    "bootloader": "stm32-dfu",
`bootloader` defined by `development_board` in child directories
```suggestion
```

2024-04-25 17:29 UTC, waffle87 approved these changes
Pending dunk2k's suggestion.

2024-04-30 01:46 UTC, drashna approved these changes

2024-04-30 01:46 UTC, merged