Firmware for 3x3macropad
qmk/qmk_firmware pull request #23594
Opened 2024-04-23 20:19 UTC by rarepotato8de

## Description

Adds support for 3x3macropad.
This is a default firmware with bongocat gif for a DIY open-source 3x3macropad.
OLED and rotary encoder can be customized in the keymap. The macropad is linked in the readme.md.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-23 20:25 UTC, waffle87 requested changes

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/config.h
This file should be removed.

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +    "bootloader": "caterina",
```suggestion
    "development_board": "promicro",
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +    "debounce": 5,
```suggestion
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +        "tap_dance": false
```suggestion
        "encoder": true,
        "extrakey": true,
        "nkro": true,
        "oled": true,
        "rgblight": true
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +        "oled": true,
If OLEDs are enabled at the keyboard level, there needs to exist some code for them as well at the keyboard level in a `3x3macropad.c` file.

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +    "processor": "atmega32u4",
```suggestion
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +        "pin": "E6"
```suggestion
        "led_count": 6
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +            "c_macro": true,
```suggestion
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +                {"label": "k22", "matrix": [2, 2], "x": 2, "y": 2, "w": 1}
```suggestion
                {"label": "k00", "matrix": [0, 0], "x": 0, "y": 0},
                {"label": "k01", "matrix": [0, 1], "x": 1, "y": 0},
                {"label": "k02", "matrix": [0, 2], "x": 2, "y": 0},
                {"label": "k10", "matrix": [1, 0], "x": 0, "y": 1},
                {"label": "k11", "matrix": [1, 1], "x": 1, "y": 1},
                {"label": "k12", "matrix": [1, 2], "x": 2, "y": 1},
                {"label": "k20", "matrix": [2, 0], "x": 0, "y": 2},
                {"label": "k21", "matrix": [2, 1], "x": 1, "y": 2},
                {"label": "k22", "matrix": [2, 2], "x": 2, "y": 2}
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/config.h
This file should be removed.

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/info.json
> +        "key_override": false,
```suggestion
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/keymaps/default/keymap.c
> +}
```suggestion
```

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/readme.md
> +![3x3macropad](https://raw.githubusercontent.com/rarepotato8de/3x3macropad/main/resources/title.png)
This image needs to be rehosted on Imgur.

2024-04-23 20:25 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/keymaps/default/keymap.c
> +#ifdef OLED_ENABLE
As above; this should probably be moved to keyboard level.

2024-04-23 20:44 UTC, zvecr commented on keyboards/rarepotato8de/3x3macropad/3x3macropad.c
> +bool oled_task_user(void) {
```suggestion
bool oled_task_kb(void) {
    if (!oled_task_user()) { return false; }
```

2024-04-23 20:47 UTC, zvecr commented on keyboards/rarepotato8de/3x3macropad/readme.md
> +![3x3macropad](https://i.imgur.com/OTb3CUq.png)
The image here doesnt match up with the layout macro configured and default keymap

2024-04-24 00:43 UTC, waffle87 commented on keyboards/rarepotato8de/3x3macropad/3x3macropad.c
> +#include QMK_KEYBOARD_H
```suggestion
#include "quantum.h"
```

2024-04-24 19:26 UTC, dunk2k requested changes
- add Community Layout support
- add EoF, where missing

2024-04-24 19:26 UTC, dunk2k commented on keyboards/rarepotato8de/3x3macropad/info.json
> +        "LAYOUT": {
```suggestion
    "community_layouts": ["ortho_3x3"],
    "layouts": {
        "LAYOUT_ortho_3x3": {
```

2024-04-24 19:26 UTC, dunk2k commented on keyboards/rarepotato8de/3x3macropad/keymaps/default/keymap.c
> +    [0] = LAYOUT(
```suggestion
    [0] = LAYOUT_ortho_3x3(
```

2024-04-24 19:26 UTC, dunk2k commented on keyboards/rarepotato8de/3x3macropad/3x3macropad.c
> +#endif
```suggestion
#endif

```

2024-04-24 19:26 UTC, dunk2k commented on keyboards/rarepotato8de/3x3macropad/info.json
> +}
```suggestion
}

```

2024-04-24 19:26 UTC, dunk2k commented on keyboards/rarepotato8de/3x3macropad/keymaps/default/keymap.c
> +};
```suggestion
};

```

2024-04-29 23:30 UTC, drashna approved these changes
Aside from the nitpick, looks good.

2024-04-29 23:30 UTC, drashna commented on keyboards/rarepotato8de/3x3macropad/3x3macropad.c
Could you run a format pass here?  Or at least, replace the tabs with spaces?

2024-04-30 20:25 UTC, rarepotato8de commented on keyboards/rarepotato8de/3x3macropad/3x3macropad.c
done. Thanks :)

2024-05-01 06:31 UTC, merged