Adds new custom hand-wired hot-swap mono block RP2040 board nyaaaah54_rp2040 to upstream
qmk/qmk_firmware pull request #23613
Opened 2024-04-25 18:34 UTC by jkaunert

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [X] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-29 23:17 UTC, drashna approved these changes

2024-04-30 01:21 UTC, fauxpark requested changes

2024-04-30 01:21 UTC, fauxpark commented on keyboards/handwired/philo_and_gunge/nyaaaah54_rp2040/readme.md
> +    make handwired/philoandgunge/nyaaaah54_rp2040:default:flash
```suggestion
    make handwired/philo_and_gunge/nyaaaah54_rp2040:default

Flashing example for this keyboard:

    make handwired/philo_and_gunge/nyaaaah54_rp2040:default:flash
```

2024-06-27 02:56 UTC, fauxpark requested changes

2024-06-27 02:56 UTC, fauxpark commented on keyboards/handwired/philo_and_gunge/nyaaaah54_rp2040/rules.mk
This file can be deleted.

2024-06-27 02:56 UTC, fauxpark commented on keyboards/handwired/philo_and_gunge/nyaaaah54_rp2040/info.json
This file should be renamed to `keyboard.json`.

2024-06-27 19:53 UTC, jkaunert commented on keyboards/handwired/philo_and_gunge/nyaaaah54_rp2040/rules.mk
fixed

2024-06-27 19:54 UTC, jkaunert commented on keyboards/handwired/philo_and_gunge/nyaaaah54_rp2040/info.json
fixed

2024-06-28 01:38 UTC, fauxpark requested changes

2024-06-28 01:38 UTC, fauxpark commented on keyboards/handwired/philo_and_gunge/nyaaaah54_rp2040/keyboard.json
Layout is incorrect.
![image](https://github.com/qmk/qmk_firmware/assets/4781841/090f2fc5-c113-42ef-82dc-432d80d36d25)

2024-08-18 17:40 UTC, zvecr requested changes

2024-08-18 17:40 UTC, zvecr commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/rules.mk
This file needs to be removed.

2024-08-18 17:40 UTC, zvecr commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/config.h
This file needs to be removed.

2024-08-18 18:01 UTC, zvecr requested changes

2024-08-18 18:01 UTC, zvecr commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/readme.md
> +*A short description of the keyboard/project*
This needs to be filled in

2024-08-18 18:01 UTC, zvecr commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/keymaps/default/keymap.c
> +// SPDX-License-Identifier: GPL-2.0-or-later
```suggestion
// Copyright 2024 jkaunert (@jkaunert)
// SPDX-License-Identifier: GPL-2.0-or-later
```

2024-08-18 18:24 UTC, jkaunert commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/readme.md
> +*A short description of the keyboard/project*
corrected

2024-08-27 17:38 UTC, jkaunert commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/readme.md
> +* Hardware Availability: <https://areyoujoshing.me/keyboards>
fixed

2024-08-27 17:38 UTC, jkaunert commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/keymaps/default/keymap.c
> +// SPDX-License-Identifier: GPL-2.0-or-later
fixed

2024-08-27 17:38 UTC, jkaunert commented on keyboards/handwired/are_you_joshing_me/le_chiffre_pi/rules.mk
fixed

2024-09-06 06:14 UTC, drashna approved these changes

2024-11-21 02:05 UTC, closed without merging