Add Chew keyboard
qmk/qmk_firmware pull request #23628
Opened 2024-04-27 18:10 UTC by flinguenheld

## Description

Hello,
I've created a new 34 keys keyboard with a RP2040 Zéro.
You can see the repo with all information [here](https://github.com/flinguenheld/chew).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-04-27 20:14 UTC, waffle87 requested changes

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/config.h
> +//#define NO_ACTION_ONESHOT
```suggestion
```

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/info.json
Please run `qmk format-json` on this file.

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/keymaps/default/config.h
This file should be removed.

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/info.json
> +        "LAYOUT_split_5_5_4_3": {
```suggestion
        "LAYOUT": {
```

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/keymaps/default/keymap.c
> +    [0] = LAYOUT_split_5_5_4_3(
```suggestion
    [0] = LAYOUT(
```

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/keymaps/default/rules.mk
This file should be removed. This does not belong at the keymap level.

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/readme.md
All images here need to switched to the standard markdown format of
```markdown
![alt](link)
```

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/readme.md
> +- 2x MCU board [RP2040-Zéro](https://www.waveshare.com/wiki/RP2040-Zero)
```suggestion
- 2x MCU board [RP2040-Zero](https://www.waveshare.com/wiki/RP2040-Zero)
```

2024-04-27 20:14 UTC, waffle87 commented on keyboards/chew/rules.mk
> +# This file intentionally left blank
```suggestion
SERIAL_DRIVER = vendor
```

2024-04-27 20:55 UTC, waffle87 approved these changes
Otherwise, lgtm.

2024-04-27 20:55 UTC, waffle87 commented on keyboards/chew/info.json
> +        "bootmagic": false,
```suggestion
        "bootmagic": true,
```

2024-04-28 14:18 UTC, zvecr requested changes

2024-04-28 14:18 UTC, zvecr commented on keyboards/chew/info.json
> +            "protocol": "serial_usart",
` "protocol": "serial_usart"` doesnt do anything.

```suggestion
```

2024-04-28 14:18 UTC, zvecr commented on keyboards/chew/info.json
> +            }
Syncing matrix state with no rgb/oled is somewhat pointless.

```suggestion
            "watchdog": true
```

2024-04-28 14:18 UTC, zvecr commented on keyboards/chew/config.h
> +#define SPLIT_WATCHDOG_ENABLE
```suggestion
```

2024-04-29 22:37 UTC, drashna approved these changes

2024-04-30 01:40 UTC, merged