[Core] Led Double Buffer
qmk/qmk_firmware pull request #23625
Opened 2024-04-27 10:59 UTC by Xelus22

## Description

Adds double buffer functionality for LED matrix and RGB Matrix since RGB Matrix and LED Matrix both use the underlying drivers to set the values.

This feature is disabled by DEFAULT due to the ever present hardware of microcontrollers with very limited RAM. 
It should only be enabled by testing if there is enough RAM.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Adds double buffering to all drivers that are supported in RGB/LED Matrix

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-01 13:13 UTC, Xelus22 commented
![image](https://github.com/user-attachments/assets/8e46e269-9d32-46e9-b08b-27323fadc8b0)
Not sure why but `qmk format-c` gives a different lint to the github actions linter

2024-12-01 14:22 UTC, zvecr commented
Different version of clang-format to the one used in CI.

2024-12-02 11:32 UTC, dexter93 approved these changes
looking good

2025-01-18 08:59 UTC, fauxpark requested changes

2025-01-18 08:59 UTC, fauxpark commented on docs/features/rgblight.md
> +
```suggestion
|Define                  |Default                     |Description                                                                  |
|------------------------|----------------------------|-----------------------------------------------------------------------------|
|`RGBLIGHT_HUE_STEP`     |`8`                         |The number of steps to cycle through the hue by                              |
|`RGBLIGHT_SAT_STEP`     |`17`                        |The number of steps to increment the saturation by                           |
|`RGBLIGHT_VAL_STEP`     |`17`                        |The number of steps to increment the brightness by                           |
|`RGBLIGHT_LIMIT_VAL`    |`255`                       |The maximum brightness level                                                 |
|`RGBLIGHT_SLEEP`        |*Not defined*               |If defined, the RGB lighting will be switched off when the host goes to sleep|
|`RGBLIGHT_SPLIT`        |*Not defined*               |If defined, synchronization functionality for split keyboards is added       |
|`RGBLIGHT_DEFAULT_MODE` |`RGBLIGHT_MODE_STATIC_LIGHT`|The default mode to use upon clearing the EEPROM                             |
|`RGBLIGHT_DEFAULT_HUE`  |`0` (red)                   |The default hue to use upon clearing the EEPROM                              |
|`RGBLIGHT_DEFAULT_SAT`  |`UINT8_MAX` (255)           |The default saturation to use upon clearing the EEPROM                       |
|`RGBLIGHT_DEFAULT_VAL`  |`RGBLIGHT_LIMIT_VAL`        |The default value (brightness) to use upon clearing the EEPROM               |
|`RGBLIGHT_DEFAULT_SPD`  |`0`                         |The default speed to use upon clearing the EEPROM                            |
|`RGBLIGHT_DEFAULT_ON`   |`true`                      |Enable RGB lighting upon clearing the EEPROM                                 |
|`RGBLIGHT_DOUBLE_BUFFER`|*Not defined*               |If defined, use double buffer when rendering                                 |
```

2025-01-26 01:40 UTC, closed without merging