Add support for Kami65 and Ad-ware PCB
qmk/qmk_firmware pull request #23645
Opened 2024-05-01 23:35 UTC by MaiTheSan

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-02 01:17 UTC, zvecr commented
Per the PR checklist,

> * PRs should contain the smallest amount of modifications required for a single change to the codebase
>    * multiple keyboards at the same time is not acceptable

2024-05-02 05:25 UTC, MaiTheSan commented
> Per the PR checklist,
> 
> > * PRs should contain the smallest amount of modifications required for a single change to the codebase
> >   
> >   * multiple keyboards at the same time is not acceptable

got it

2024-05-31 12:04 UTC, dunk2k commented
please:
1. `rename keyboards/chickenman/kami65/info.json` to `keyboards/chickenman/kami65/keyboard.json`
2. delete `keyboards/chickenman/kami65/rules.mk`

As so this PR conforms to the recent changes regarding build markers.

2024-07-13 02:33 UTC, drashna commented on keyboards/chickenman/kami65/halconf.h
This file isn't doing anything, and should be removed.

2024-07-14 05:55 UTC, drashna commented on keyboards/chickenman/kami65/readme.md
> +* Hardware Availability: UCSD Discord
Do you have a more specific link, or a link to the design?

2024-08-26 10:39 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-10-08 20:21 UTC, dunk2k requested changes
conforms to PR guidance regarding PCBs with more than one physical layout

2024-10-08 20:21 UTC, dunk2k commented on keyboards/chickenman/kami65/keyboard.json
> +    },
```suggestion
    },
    "layout_aliases": {
        "LAYOUT_all": "LAYOUT_65_ansi_blocker_split_bs"
    },
```

2024-10-08 20:21 UTC, dunk2k commented on keyboards/chickenman/kami65/keymaps/default/keymap.c
> +    [0] = LAYOUT_65_ansi_blocker_split_bs(
```suggestion
    [0] = LAYOUT_all(
```

2024-10-08 20:21 UTC, dunk2k commented on keyboards/chickenman/kami65/keymaps/default/keymap.c
> +    [1] = LAYOUT_65_ansi_blocker_split_bs(
```suggestion
    [1] = LAYOUT_all(
```

2024-10-11 04:05 UTC, drashna approved these changes

2024-11-14 16:00 UTC, closed without merging