add macha60 pcb firmware
qmk/qmk_firmware pull request #23647
Opened 2024-05-02 10:45 UTC by CMMS-Freather

add macha60 pcb firmware

## Description
a 60% with exploded 7u spacebar

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-02 19:35 UTC, CMMS-Freather commented on keyboards/macha60/readme.md
> +* **Physical reset button**: Briefly press the button on the back of the PCB - some may have pads you must short instead
it actually have a button at the back

2024-05-02 19:36 UTC, CMMS-Freather commented on keyboards/macha60/keymaps/via/config.h
mostly because this was written in old format, and it had a config.h to include the caps lock indicator pin

2024-05-02 19:36 UTC, CMMS-Freather commented on keyboards/macha60/keymaps/via/config.h
mostly because this was written in old format, and it had a config.h to include the caps lock indicator pin

2024-05-02 20:04 UTC, CMMS-Freather commented on keyboards/macha60/readme.md
> +![macha60](https://i.imgur.com/tTY8uvX.png)
this has been updated

2024-05-03 05:25 UTC, zvecr requested changes
The other unresolved suggestions should also be completed.

2024-05-03 05:25 UTC, zvecr commented on keyboards/macha60/keymaps/via/rules.mk
> +# This file intentionally left blank
```suggestion
```

2024-05-03 05:25 UTC, zvecr commented on keyboards/macha60/keymaps/via/config.h
This file needs to be removed.

2024-05-03 05:25 UTC, zvecr commented on keyboards/macha60/info.json
> +      "meta": "https://noroadsleft.github.io/kbf_qmk_converter/"
```suggestion
      }
```

2024-05-03 05:25 UTC, zvecr commented on keyboards/macha60/macha60.c
This file should be removed.

2024-05-03 10:35 UTC, CMMS-Freather commented on keyboards/macha60/macha60.c
does the inclusion of capslock indicator pin and on state in info.json replace this part of function?

2024-05-05 15:34 UTC, zvecr commented
> The other unresolved suggestions should also be completed.

There is little point requesting a review, as there are at least 6 unresolved suggestions/comments still.

2024-05-15 04:28 UTC, waffle87 reviewed
;e

2024-05-15 04:28 UTC, waffle87 commented on keyboards/macha60/info.json
Please run `qmk format-json` on this file.

2024-07-13 02:25 UTC, drashna requested changes

2024-07-13 02:25 UTC, drashna commented on keyboards/macha60/info.json
Sorry it's been a bit... but could you rename this to `keyboard.json` and remove the `rules.mk`.   In the interem, we've changed it so that the keyboard.json is also a build marker (eg, it doesn't need a rules.mk to be considered a valid keyboard for compiling).

2024-07-15 18:28 UTC, CMMS-Freather commented on keyboards/macha60/info.json
does this mean i have to update my local qmk repo to the lastest so it will be able to test compile?

2024-07-27 04:36 UTC, drashna commented on keyboards/macha60/info.json
depending on how old your repo is, yes.  However the QMK CI will compile it automatically.

2024-08-26 10:43 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-11-12 02:00 UTC, closed without merging