Adding TRKeyboard TRK1 to QMK
qmk/qmk_firmware pull request #23642
Opened 2024-05-01 00:03 UTC by TvrdRadKeyboards

### Description
Adding [TRKeyboard TRK1](https://www.trkeyboards.com/en/keyboards/1-trk1/) to QMK

### Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation
- [ ] Issues Fixed or Closed by This PR

### Checklist
- [x] My code follows the code style of this project: [C](https://docs.qmk.fm/#/coding_conventions_c), [Python](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [PR Checklist document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-01 06:10 UTC, drashna requested changes

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/config.h
If this file has nothing in it, it can and should be removed.

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/default/keymap.c
> +    )
Empty layouts should be removed, as all they do is eat into usable firmware space. 
```suggestion
```

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/default/keymap.c
> +    [3] =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```suggestion
    [1] =  { ENCODER_CCW_CW(_______, _______) },
```

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/default/readme.md
This file can be removed.

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/via/keymap.c
> +    )
```suggestion
```

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/via/keymap.c
> +    [3] =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```suggestion
    [1] =  { ENCODER_CCW_CW(_______, _______) }
```

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/keymaps/via/readme.md
This file should be removed.

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/readme.md
> +![TRK1](https://www.trkeyboards.com/upload/products/gallery/1663968347286_raaw8387.jpg)
Please rehost the image on a dedicated image host, such as Imgur (with an account)

No offense, but shops are ephemeral, and regularly vanish.

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/readme.md
> +    # or, if you'd like a VIA-enabled keymap:
```suggestion
Or, if you'd like a VIA-enabled keymap:
```

2024-05-01 06:10 UTC, drashna commented on keyboards/trkeyboards/trk1/readme.md
> +    # or, if you'd like a VIA-enabled keymap:
```suggestion
Or, if you'd like a VIA-enabled keymap:
```

2024-05-01 13:55 UTC, waffle87 reviewed
Since you're targeting the `develop` branch, the `rules.mk` file should be removed, and the `info.json` file should be renamed to `keyboard.json`.

2024-05-01 13:55 UTC, waffle87 commented on keyboards/trkeyboards/trk1/readme.md
> +![TRK1](https://i.imgur.com/dbxoTah.jpg)
```suggestion
![TRK1](https://i.imgur.com/dbxoTa.jpg)
```

2024-05-01 13:55 UTC, waffle87 commented on keyboards/trkeyboards/trk1/readme.md
> +    make trkeyboards/trk1:via:flash
```suggestion
    make trkeyboards/trk1:default

Flashing example for this keyboard:

    make trkeyboards/trk1:default:flash
```

2024-07-13 02:37 UTC, drashna approved these changes

2024-07-13 08:38 UTC, fauxpark requested changes

2024-07-13 08:38 UTC, fauxpark commented on keyboards/trkeyboards/trk1/readme.md
> +    make trkeyboards/trk1:via:flash
```suggestion
    make trkeyboards/trk1:default:flash
```

2024-07-13 08:38 UTC, fauxpark commented on keyboards/trkeyboards/trk1/keyboard.json
Please run `qmk format-json -i` on this file.

Your layout is also incorrect; X/Y positions cannot be negative.
![image](https://github.com/user-attachments/assets/8527b263-ea12-4474-bec1-6a18f6a31aee)

2024-07-14 02:21 UTC, fauxpark approved these changes

2024-07-14 06:00 UTC, merged