[Keyboard] Add Typface Univers
qmk/qmk_firmware pull request #23664
Opened 2024-05-05 09:59 UTC by itsme-zeix

## Description

Added support for Typface Univers.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-05 12:23 UTC, dunk2k requested changes

2024-05-05 12:23 UTC, dunk2k commented on keyboards/zeix/typface/univers/matrix_diagram.md
1. F4 and 2u Backspace keys are labelled with the same matrix co-ordinate, could this be corrected?
2. Could right hand co-ordinate be changed from A-N to 0-9,A-E? to be in uniform with other `matrix_diagram.md` files

2024-05-05 12:25 UTC, dunk2k requested changes

2024-05-05 12:25 UTC, dunk2k commented on keyboards/zeix/typface/univers/rules.mk
> +# This file intentionally left blank
```suggestion
# This file intentionally left blank

```

2024-05-05 12:27 UTC, itsme-zeix commented on keyboards/zeix/typface/univers/matrix_diagram.md
Yup, I will correct it. Thanks for the review!

2024-05-19 04:41 UTC, drashna approved these changes

2024-06-07 11:08 UTC, dunk2k commented
To confirm to how build markers have been reworked as of most recent breaking changes, can:
1. `rules.mk` be removed
2. `info.json` re-named to `keyboard.json`

2024-06-07 11:31 UTC, dunk2k requested changes

2024-06-07 11:31 UTC, dunk2k commented on keyboards/zeix/typface/univers/info.json
> +                {"matrix": [3, 12], "x": 15.25, "y": 3.5},
correct key placement for ISO Hash, this does mean ANSI Enter key width is shortened to accomdate
```suggestion
                {"matrix": [3, 12], "x": 12.75, "y": 3.5},
                {"matrix": [3, 13], "x": 13.75, "y": 3.5, "w": 1.25},
                
```

2024-06-07 11:31 UTC, dunk2k commented on keyboards/zeix/typface/univers/info.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2024-06-07 11:34 UTC, dunk2k commented
Based on [store page](https://typface.com/products/univers), this PCB comes in to two variants - can the directory structure of this PR be change to reflect variants available.

2024-06-09 16:07 UTC, itsme-zeix commented
> To confirm to how build markers have been reworked as of most recent breaking changes, can:
> 
> 1. `rules.mk` be removed
> 2. `info.json` re-named to `keyboard.json`

Will make these changes, thank you for notifying me about the breaking changes!

> Based on [store page](https://typface.com/products/univers), this PCB comes in to two variants - can the directory structure of this PR be change to reflect variants available.

The firmware supports both the solder and hotswap variant, though the hotswap variant does not include ISO compatibility - in that case, is there still a need to duplicate the files?

2024-06-09 21:12 UTC, dunk2k requested changes

2024-06-09 21:12 UTC, dunk2k commented on keyboards/zeix/typface/univers/univers.json
can this file be renamed, literally, to `keyboard.json`?

2024-06-10 23:33 UTC, dunk2k commented
> The firmware supports both the solder and hotswap variant, though the hotswap variant does not include ISO compatibility - in that case, is there still a need to duplicate the files?

Thankfully, duplication can be avoided by:
1. Placing settings and configuration used by both variants in a directory above the proposed `solder` and `hotswap` (sub-)directories. This would include an `info.json` file that has layouts both variants support (i.e. `LAYOUT_ansi`, `LAYOUT_ansi_split_bs`).
2. Solder directory's `keyboard.json` would contain the compatible ISO `"layouts"` and `"community layouts", and the current `LAYOUT_all` layout.

This proposed directory restructure would mean a keymap (sub-directory) and differing PID for each variant.

2024-08-20 12:24 UTC, closed without merging