Fix Minerva LX `info.json`
qmk/qmk_firmware pull request #23706
Opened 2024-05-13 03:07 UTC by Gondolindrim

## Description

Fixes the info.json layout of minerva LX and adds missing column key defs

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-13 04:11 UTC, zvecr requested changes

2024-05-13 04:11 UTC, zvecr commented on keyboards/archetype/minervalx/info.json
This file should not be renamed back to `info.json`

2024-05-13 04:12 UTC, Gondolindrim commented on keyboards/archetype/minervalx/info.json
What should it be named?

2024-05-13 04:13 UTC, zvecr commented on keyboards/archetype/minervalx/info.json
`keyboard.json`, like it is currently in develop.

2024-05-13 19:22 UTC, Gondolindrim commented on keyboards/archetype/minervalx/info.json
Done in [09c8d80](https://github.com/qmk/qmk_firmware/pull/23706/commits/09c8d80279a132f1ab71f0f6ef2e937eb7db1857)

2024-05-18 06:53 UTC, drashna approved these changes

2024-05-18 09:18 UTC, zvecr requested changes
Build failures need to be resolved,
```
./keyboards/archetype/minervalx/keymaps/default/keymap.c:27:5: error: macro "LAYOUT" requires 70 arguments, but only 65 given
```

2024-08-02 01:54 UTC, closed without merging