New selfmade keyboard
qmk/qmk_firmware pull request #23732
Opened 2024-05-17 13:58 UTC by Pascal0816

I created a new keyboard for myself, that is a 96%ish keyboard with a full-size numberpad.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ]x I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-17 21:09 UTC, waffle87 requested changes

2024-05-17 21:09 UTC, waffle87 commented on keyboards/ingenieurrr/keymaps/default/keymap.c
> +        _______,    _______,    _______,                                        _______,                                        _______,    _______,    _______,    _______,    _______,    _______,
```suggestion
        KC_LCTL,    KC_LGUI,    KC_LALT,                                        KC_SPC,                                         KC_RALT,    _______,      KC_RCTL,    KC_LEFT,    KC_DOWN,    KC_RGHT,    KC_P0,      KC_PDOT
```

2024-05-17 21:09 UTC, waffle87 commented on keyboards/ingenieurrr/keymaps/via/keymap.c
> +        _______,    _______,    _______,                                        _______,                                        _______,    _______,    _______,    _______,    _______,    _______,
```suggestion
        KC_LCTL,    KC_LGUI,    KC_LALT,                                        KC_SPC,                                         KC_RALT,    _______,      KC_RCTL,    KC_LEFT,    KC_DOWN,    KC_RGHT,    KC_P0,      KC_PDOT
```

2024-05-17 21:09 UTC, waffle87 commented on keyboards/ingenieurrr/readme.md
This file must follow the [template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md).

2024-05-18 06:22 UTC, drashna commented on keyboards/ingenieurrr/info.json
This file has a mix of spaces and tabs.  Could you run `qmk format-json` on it?

2024-08-02 01:54 UTC, closed without merging