added via keymap
qmk/qmk_firmware pull request #23734
Opened 2024-05-17 16:03 UTC by mankokimochi

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* added new keymap for via support

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-17 16:13 UTC, zvecr requested changes
Files have been added to the wrong location. Keymaps must be within a folder under `/keymaps/`.

For this case:
```
keyboards/fr4/southpaw75/keymaps/via/keymap.c
keyboards/fr4/southpaw75/keymaps/via/rules.mk
```

2024-05-18 06:23 UTC, drashna requested changes

2024-05-18 06:23 UTC, drashna commented on keyboards/fr4/southpaw75/keymaps/keymap.c
> +    )
These layers appear empty.   They should be removed, as any empty layers are automatically populated on init.
```suggestion
```

2024-05-18 06:23 UTC, drashna commented on keyboards/fr4/southpaw75/keymaps/rules.mk
> +LTO_ENABLE = yes
```suggestion
LTO_ENABLE = yes

```

2024-07-05 02:37 UTC, zvecr commented
Closing as files have still not been moved to the correct location.

2024-07-05 02:37 UTC, closed without merging