fix keymap for kprepublic bm60hsrgb_iso
qmk/qmk_firmware pull request #23733
Opened 2024-05-17 15:04 UTC by mynimi

## Description
Noticed that when I first plugged in the kprepublic BM60 ISO board, that the keymap featured two spaces and was missing the Non-US `\` and `|`.
Felt like remapping `KC_SPC` to `KC_NUBS` in the default seemed sensible.

## Types of Changes
- [ ] Core
- [x ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

2024-05-17 20:37 UTC, dunk2k requested changes

2024-05-17 20:37 UTC, dunk2k commented on keyboards/kprepublic/bm60hsrgb_iso/rev2/keymaps/default/keymap.c
> +        KC_LSFT, KC_NUBS,  KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_RSFT, KC_UP,   KC_SLSH,
```suggestion
        KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_RSFT, KC_UP,   KC_SLSH,
```

2024-05-17 20:37 UTC, dunk2k commented on keyboards/kprepublic/bm60hsrgb_iso/rev2/keymaps/default/keymap.c
> +};
```suggestion
};

```

2024-05-17 20:37 UTC, dunk2k commented on keyboards/kprepublic/bm60hsrgb_iso/rev2/keymaps/via/keymap.c
> +        KC_LSFT, KC_NUBS,  KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_RSFT, KC_UP,   KC_SLSH,
```suggestion
        KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_RSFT, KC_UP,   KC_SLSH,
```

2024-05-17 23:02 UTC, fauxpark requested changes

2024-05-17 23:02 UTC, fauxpark commented on keyboards/kprepublic/bm60hsrgb_iso/rev2/keymaps/default/keymap.c
>          KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,
This one should also really be
```suggestion
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
```

2024-05-17 23:02 UTC, fauxpark commented on keyboards/kprepublic/bm60hsrgb_iso/rev2/keymaps/via/keymap.c
>          KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT,
```suggestion
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
```

2024-05-28 06:01 UTC, fauxpark approved these changes

2024-06-14 07:32 UTC, drashna approved these changes

2024-06-14 07:34 UTC, merged