Added MATRIX_HAS_GHOST definition for IBM Model H controller
qmk/qmk_firmware pull request #23744
Opened 2024-05-19 19:14 UTC by jberclaz

## Description

The Model M's matrix is 2-key rollover and can suffer from ghosting. This PR adds the constant `MATRIX_HAS_GHOST` to the Model H controller, so that the firmware addresses the issue.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-19 22:04 UTC, dunk2k approved these changes

2024-05-20 06:17 UTC, drashna approved these changes

2024-05-20 06:24 UTC, fauxpark requested changes

2024-05-20 06:24 UTC, fauxpark commented on keyboards/ibm/model_m/modelh/config.h
> +#define MATRIX_HAS_GHOST
This should go in info.json.
https://docs.qmk.fm/#/reference_info_json?id=matrix

2024-05-20 06:24 UTC, fauxpark commented on keyboards/ibm/model_m/modelh/info.json
> +        "device_version": "1.0.1",
This does not need to be changed.

2024-05-21 04:15 UTC, fauxpark approved these changes

2024-05-22 02:49 UTC, merged