Migrate `LOCKING_*_ENABLE` to Data-Driven: H, Part 2
qmk/qmk_firmware pull request #23762
Opened 2024-05-21 17:59 UTC by noroadsleft

## Description

Moves instances of `#define LOCKING_SUPPORT_ENABLE` and `#define LOCKING_RESYNC_ENABLE` to data-driven.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-21 21:47 UTC, fauxpark requested changes

2024-05-21 21:47 UTC, fauxpark commented on keyboards/handwired/dactyl_minidox/keyboard.json
> +    },
```suggestion
```
These are undefs so I think there's nothing to do here?

2024-05-22 02:15 UTC, fauxpark approved these changes

2024-05-22 09:52 UTC, zvecr approved these changes

2024-05-22 09:53 UTC, merged