[Keyboard] Add archerkeyboard/desire65
qmk/qmk_firmware pull request #23776
Opened 2024-05-22 19:37 UTC by akyp

## Description

Add new keyboard archerkeyboard/desire65

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-05-26 19:46 UTC, waffle87 commented on keyboards/archerkeyboard/desire65/config.h
This file should be removed.

2024-05-26 19:46 UTC, waffle87 commented on keyboards/archerkeyboard/desire65/readme.md
> +![desire65](https://i.imgur.com/bTjvGzC.jpg)
```suggestion
# desire65

![desire65](https://i.imgur.com/bTjvGzC.jpg)
```

2024-05-26 19:46 UTC, waffle87 commented on keyboards/archerkeyboard/desire65/rules.mk
Given that the breaking change cycle is occurring in the near future, this file can be removed, and the `info.json` renamed to `keyboard.json`.

2024-06-14 07:02 UTC, drashna approved these changes

2024-07-05 03:48 UTC, zvecr requested changes

2024-07-05 03:48 UTC, zvecr commented on keyboards/archerkeyboard/desire65/keyboard.json
> +    },
```suggestion
    "indicators": {
        "caps_lock": "GP18"
    },
```

2024-07-05 03:48 UTC, zvecr commented on keyboards/archerkeyboard/desire65/keyboard.json
> +        "console": false,
```suggestion
        "bootmagic": true,
```

2024-07-05 08:31 UTC, akyp commented on keyboards/archerkeyboard/desire65/keyboard.json
> +        "console": false,
Changed as requested

2024-07-05 09:17 UTC, akyp commented on keyboards/archerkeyboard/desire65/keyboard.json
> +    },
Changed as requested

2024-07-11 05:24 UTC, drashna approved these changes

2024-07-31 00:07 UTC, tzarc approved these changes

2024-07-31 00:07 UTC, merged