[Keyboard] Add boardsource/sessenta
qmk/qmk_firmware pull request #23823
Opened 2024-05-29 05:53 UTC by waffle87

## Description

As title.

## Types of Changes

- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-12 07:33 UTC, drashna approved these changes

2024-07-11 07:41 UTC, fauxpark requested changes

2024-07-11 07:41 UTC, fauxpark commented on keyboards/boardsource/sessanta/keyboard.json
> +            {"x": 82.5, "y": 0, "flags": 2},
```suggestion
            {"x": 156, "y": 0, "flags": 2},
            {"x": 82, "y": 0, "flags": 2},
```

2024-07-11 11:55 UTC, fauxpark approved these changes

2024-07-11 13:39 UTC, merged