Added keyboard layout images for drop thekey v2 keymaps
qmk/qmk_firmware pull request #23874
Opened 2024-06-06 20:12 UTC by pekvasnovsky

## Description

I added images (light and dark theme) for keyboard layouts for the drop/thekey/v2 keymaps (win and macos)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-06 20:38 UTC, waffle87 requested changes
These images should be rehosted on Imgur.

2024-06-06 20:50 UTC, pekvasnovsky commented
Yeah you are right that having it as assets under my repo is just bad

but I'd say there should be a way to have it hosted still on github under
the qmk repo assets.. no?

On Thu, Jun 6, 2024, 22:38 jack ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> These images should be rehosted on Imgur.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qmk/qmk_firmware/pull/23874#pullrequestreview-2103162843>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCT6EG2KC57G4YYGX4QYI3LZGDCEVAVCNFSM6AAAAABI5M4WVOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMBTGE3DEOBUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-06 21:16 UTC, waffle87 commented
No, all images found within QMK are hosted elsewhere (except for the single image in the repository which is the docs' favicon).

2024-06-09 19:53 UTC, drashna approved these changes

2024-10-11 06:14 UTC, fauxpark commented
> Reuploaded to imgur.
> 
> I still don't think using third party image hosting instead of using github image hosting which is used also for issue images and so on (or other github means) is correct, when it dies as many many other image hosts died all images will be gone.

The alternative is hosting all images in this same repo, which is already large enough as it is with mostly just code changes from the last ten or so years, and people still occasionally complain about the download size when cloning. It is simply not feasible to do anything other than use an external hosting service like imgur.

2024-10-11 06:37 UTC, pekvasnovsky commented
Thanks for the reply

You could also have another repo just for images, it would still be part of
github so no 3rd party risk but ofc it has its own issues - like who is
managing it, how would one decide when and what to delete and so on

so I understand why using imgur is easiest from management POV

On Fri, Oct 11, 2024, 08:14 Ryan ***@***.***> wrote:

> Reuploaded to imgur.
>
> I still don't think using third party image hosting instead of using
> github image hosting which is used also for issue images and so on (or
> other github means) is correct, when it dies as many many other image hosts
> died all images will be gone.
>
> The alternative is hosting all images in this same repo, which is already
> large enough as it is with mostly just code changes from the last ten or so
> years, and people still occasionally complain about the download size when
> cloning. It is simply not feasible to do anything other than use an
> external hosting service like imgur.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qmk/qmk_firmware/pull/23874#issuecomment-2406623999>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCT6EG2KY5Q36B6D4JTNOULZ25UETAVCNFSM6AAAAABI5M4WVOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBWGYZDGOJZHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-12 02:27 UTC, zvecr commented
From previous internal discussions, it was decided that this was not the direction we want to take.

Sorry its taken a while to respond.

2025-01-12 02:27 UTC, closed without merging