Add SyenaKeyboards Elaruus
qmk/qmk_firmware pull request #23870
Opened 2024-06-05 15:41 UTC by syenasweta

## Description

Add SyenaKeyboards Elaruus.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x] I have added tests to cover my changes.
- [ x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-05 20:44 UTC, waffle87 requested changes

2024-06-05 20:44 UTC, waffle87 commented on keyboards/syenakeyboards/elaruus/keyboard.json
> +        "nkro": true
Unless there's a specific reason for `command`/`console` features to be enabled, they generally shouldn't be by default. I also don't reckon NKRO is necessary for this board.
```suggestion
        "extrakey": true,
        "mousekey": true
```

2024-06-05 20:44 UTC, waffle87 commented on keyboards/syenakeyboards/elaruus/keymaps/default/keymap.c
> +        KC_DOWN,        KC_NO
```suggestion
        _______,          KC_UP
    ),
    [2] = LAYOUT_ortho_1x2(
        KC_DOWN,        _______
```

2024-06-05 20:44 UTC, waffle87 commented on keyboards/syenakeyboards/elaruus/keymaps/via/keymap.c
> +    )
```suggestion
    [1] = LAYOUT_ortho_1x2(
        _______,          KC_UP
    ),
    [2] = LAYOUT_ortho_1x2(
        KC_DOWN,        _______
    )
```

2024-06-06 19:41 UTC, waffle87 approved these changes

2024-06-06 23:17 UTC, fauxpark approved these changes

2024-06-07 01:17 UTC, merged