Add Scotto37 handwired keyboard
qmk/qmk_firmware pull request #23938
Opened 2024-06-16 20:15 UTC by joe-scotto

## Description

Adds the Scotto37 handwired keyboard and default keymap.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-18 03:34 UTC, zvecr requested changes

2024-06-18 03:34 UTC, zvecr commented on keyboards/handwired/scottokeebs/scotto37/info.json
Please rename this file to `keyboard.json`

2024-06-18 03:34 UTC, zvecr commented on keyboards/handwired/scottokeebs/scotto37/rules.mk
Please remove this file.

2024-06-18 03:34 UTC, zvecr commented on keyboards/handwired/scottokeebs/scotto37/keymaps/default/config.h
> +#define TAPPING_TERM_PER_KEY
This config option does provide any value when the corresponding code is not implemented.
```suggestion
```

2024-06-18 03:44 UTC, joe-scotto commented on keyboards/handwired/scottokeebs/scotto37/rules.mk
Resolved in [e3104c2](https://github.com/qmk/qmk_firmware/pull/23938/commits/e3104c27161f9aee4be6e28ba4e5fc214d21112c)

2024-06-18 03:44 UTC, joe-scotto commented on keyboards/handwired/scottokeebs/scotto37/info.json
Resolved in [e3104c2](https://github.com/qmk/qmk_firmware/pull/23938/commits/e3104c27161f9aee4be6e28ba4e5fc214d21112c)

2024-07-06 23:01 UTC, fauxpark requested changes

2024-07-06 23:01 UTC, fauxpark commented on keyboards/handwired/scottokeebs/scotto37/keyboard.json
Please run `qmk format-json -i` on this file.

2024-07-06 23:05 UTC, joe-scotto commented on keyboards/handwired/scottokeebs/scotto37/keyboard.json
Fixed in [72688e4](https://github.com/qmk/qmk_firmware/pull/23938/commits/72688e4720b15a05cc2b48a7932ef39818043e67)

2024-10-09 06:08 UTC, fauxpark approved these changes

2024-10-11 03:27 UTC, drashna approved these changes

2024-10-11 03:27 UTC, merged