Fix NKRO and Mouse Emulation on arm_atsam
qmk/qmk_firmware pull request #23945
Opened 2024-06-17 09:39 UTC by Izumemori

## Description
Removes `report_id` from the NKRO report struct for the arm_atsam protocol for NKRO and mouse emulation.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR
* Fixes #23939 
* Addresses bug introduced by #22267

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-18 10:22 UTC, drashna approved these changes

2024-06-21 03:43 UTC, fauxpark requested changes
This should be fixed in the ATSAM code, not report.h.

2024-06-21 19:54 UTC, Izumemori commented
> This should be fixed in the ATSAM code, not report.h.

I've moved the same behavior to `main_arm_atsam.c`.

2024-08-12 23:03 UTC, zvecr approved these changes

2024-08-12 23:06 UTC, tzarc approved these changes

2024-08-12 23:06 UTC, merged