Add support for Apollo87HL and Apollo87HL-T
qmk/qmk_firmware pull request #23951
Opened 2024-06-18 04:52 UTC by Gondolindrim

## Description

Adds support for Apollo87HL and Apollo87HL-T.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-19 12:16 UTC, dunk2k requested changes
add Community Layout Support

2024-06-19 12:16 UTC, dunk2k commented on keyboards/acheron/apollo/87hlt/keyboard.json
> +    "LAYOUT": {
```suggestion
    "community_layouts": ["tkl_ansi_tsangan_split_bs_rshift", "tkl_ansi_wkl_split_bs_rshift"],
    "layouts": {
        "LAYOUT_tkl_ansi_tsangan_split_bs_rshift": {
```

2024-06-19 12:16 UTC, dunk2k commented on keyboards/acheron/apollo/87hl/keymaps/default/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
   [0] = LAYOUT_tkl_ansi_split_bs_rshift(
        KC_ESC ,          KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  , KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12 ,             KC_PSCR, KC_SCRL, KC_PAUS, 
        KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   , KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_MINS, KC_EQL , KC_BSPC, KC_BSPC,    KC_INS , KC_HOME, KC_PGUP,
        KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   , KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_LBRC, KC_RBRC, KC_BSLS,             KC_DEL , KC_END , KC_PGDN,
        KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,          KC_ENT ,                                   
        KC_LSFT,          KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT, MO(1)  ,                      KC_UP,            
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC ,                            KC_RALT, KC_RGUI, MO(1)  , KC_RCTL,             KC_LEFT, KC_DOWN, KC_RIGHT
        ),

   [1] = LAYOUT_tkl_ansi_split_bs_rshift(
        QK_BOOT,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,    _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______, 
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,                              
        _______,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                      _______,   
        _______, _______, _______,                            _______,                            _______, _______, _______, _______,             _______, _______, _______
```

2024-06-19 12:16 UTC, dunk2k commented on keyboards/acheron/apollo/87hl/keymaps/via/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
   [0] = LAYOUT_tkl_ansi_split_bs_rshift(
        KC_ESC ,          KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  , KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12 ,             KC_PSCR, KC_SCRL, KC_PAUS, 
        KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   , KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_MINS, KC_EQL , KC_BSPC, KC_BSPC,    KC_INS , KC_HOME, KC_PGUP,
        KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   , KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_LBRC, KC_RBRC, KC_BSLS,             KC_DEL , KC_END , KC_PGDN,
        KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,          KC_ENT ,                                   
        KC_LSFT,          KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT, MO(1)  ,                      KC_UP,            
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC ,                            KC_RALT, KC_RGUI, MO(1)  , KC_RCTL,             KC_LEFT, KC_DOWN, KC_RIGHT
        ),

   [1] = LAYOUT_tkl_ansi_split_bs_rshift(
        QK_BOOT,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,    _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______, 
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,                              
        _______,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                      _______,   
        _______, _______, _______,                            _______,                            _______, _______, _______, _______,             _______, _______, _______
```

2024-06-19 12:16 UTC, dunk2k commented on keyboards/acheron/apollo/87hlt/keymaps/default/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                                     KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
   [0] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
        KC_ESC ,          KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  , KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12 ,             KC_PSCR, KC_SCRL, KC_PAUS, 
        KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   , KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_MINS, KC_EQL , KC_BSPC, KC_BSPC,    KC_INS , KC_HOME, KC_PGUP ,
        KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   , KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_LBRC, KC_RBRC, KC_BSLS,             KC_DEL , KC_END , KC_PGDN ,
        KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,          KC_ENT ,                                   
        KC_LSFT,          KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT, MO(1)  ,                      KC_UP,            
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC ,                                     KC_RALT, KC_RGUI, KC_RCTL,             KC_LEFT, KC_DOWN, KC_RIGHT
        ),
   [1] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
        QK_BOOT,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,    _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______, 
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,                              
        _______,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                      _______,   
        _______, _______, _______,                            _______,                                     _______, _______, _______,             _______, _______, _______
```

2024-06-19 12:16 UTC, dunk2k commented on keyboards/acheron/apollo/87hlt/keymaps/via/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                                     KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
   [0] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
        KC_ESC ,          KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5  , KC_F6  , KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12 ,             KC_PSCR, KC_SCRL, KC_PAUS, 
        KC_GRV , KC_1   , KC_2   , KC_3   , KC_4   , KC_5   , KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_MINS, KC_EQL , KC_BSPC, KC_BSPC,    KC_INS , KC_HOME, KC_PGUP ,
        KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   , KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_LBRC, KC_RBRC, KC_BSLS,             KC_DEL , KC_END , KC_PGDN ,
        KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT,          KC_ENT ,                                   
        KC_LSFT,          KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT, MO(1)  ,                      KC_UP,            
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC ,                                     KC_RALT, KC_RGUI, KC_RCTL,             KC_LEFT, KC_DOWN, KC_RIGHT
        ),
   [1] = LAYOUT_tkl_ansi_tsangan_split_bs_rshift(
        QK_BOOT,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,    _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,             _______, _______, _______, 
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,          _______,                              
        _______,          _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,                      _______,   
        _______, _______, _______,                            _______,                                     _______, _______, _______,             _______, _______, _______
```

2024-06-26 05:55 UTC, fauxpark requested changes

2024-06-26 05:55 UTC, fauxpark commented on keyboards/acheron/apollo/87hlarc1/keyboard.json
Please run `qmk format-json -i` on this file.

2024-06-26 05:55 UTC, fauxpark commented on keyboards/acheron/apollo/87hlarc2/keyboard.json
Please run `qmk format-json -i` on this file.

2024-06-26 05:55 UTC, fauxpark commented on keyboards/acheron/apollo/87hltarc1/keyboard.json
Please run `qmk format-json -i` on this file.

2024-06-26 05:55 UTC, fauxpark commented on keyboards/acheron/apollo/87hltarc2/keyboard.json
Please run `qmk format-json -i` on this file.

2024-08-30 06:06 UTC, drashna requested changes
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-08-30 06:06 UTC, drashna commented on keyboards/acheron/apollo/87hlarc1/87hlarc1.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2024-08-30 06:06 UTC, drashna commented on keyboards/acheron/apollo/87hlarc1/keyboard.json
> +    },
```suggestion
        "bootmagic": true,
        "extrakey": true,
        "nkro": true,
        "rgblight": true
    },
```

2024-08-30 06:06 UTC, drashna commented on keyboards/acheron/apollo/87hlarc2/87hlarc2.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2024-08-30 06:06 UTC, drashna commented on keyboards/acheron/apollo/87hltarc1/87hltarc1.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2024-08-30 06:06 UTC, drashna commented on keyboards/acheron/apollo/87hltarc2/87hltarc2.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2024-11-15 02:06 UTC, closed without merging