add new pcb - chlx lan metro
qmk/qmk_firmware pull request #24026
Opened 2024-06-30 14:40 UTC by gaclee3b

## Description

Adding new 60% pcb variant (meant for 2mm manufacturing thickness). 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-06-30 14:58 UTC, zvecr requested changes

2024-06-30 14:58 UTC, zvecr commented on keyboards/chlx/lfn_merro60/rules.mk
This file should be removed.

2024-06-30 14:58 UTC, zvecr commented on keyboards/chlx/lfn_merro60/config.h
This file should be moved to the via keymap.

2024-06-30 14:58 UTC, zvecr commented on keyboards/chlx/lfn_merro60/info.json
Please rename this file to `keyboard.json`

2024-06-30 23:55 UTC, gaclee3b commented on keyboards/chlx/lfn_merro60/config.h
could you clarify this request? does this mean the config.h file just needs to be in the keymaps/via/ directory?

2024-07-01 03:05 UTC, gaclee3b commented on keyboards/chlx/lfn_merro60/config.h
I just took a look at [a recent merged PR](https://github.com/qmk/qmk_firmware/pull/23949/files#diff-79c4b31e2fae76bf5b626e312de113a3fd52215653a926d3925d449f9b55e013) and it looks like they moved via-related config.h stuff to the keymaps/via/ directory. I will do the same until otherwise noted.

2024-07-01 11:23 UTC, dunk2k commented on keyboards/chlx/lfn_merro60/keymaps/default/keymap.c
> +  KC_LSFT, KC_LEFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
```suggestion
  KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT,
  KC_LSFT, KC_NUBS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, MO(1),
```

2024-07-01 21:29 UTC, dunk2k requested changes

2024-07-01 21:29 UTC, dunk2k commented on keyboards/chlx/lfn_merro60/readme.md
> +![lfn.merro60 PCB](https://github.com/gaclee3b/shared/blob/main/lfn.merro60/lfn_merro60_pcb.jpeg?raw=true)
Can image be re-hosted on imgur?

2024-07-02 03:02 UTC, gaclee3b commented on keyboards/chlx/lfn_merro60/readme.md
> +![lfn.merro60 PCB](https://github.com/gaclee3b/shared/blob/main/lfn.merro60/lfn_merro60_pcb.jpeg?raw=true)
done

2024-07-03 08:32 UTC, drashna approved these changes

2024-07-04 02:40 UTC, waffle87 approved these changes

2024-07-04 02:40 UTC, merged