Add gmkb keyboard
qmk/qmk_firmware pull request #24039
Opened 2024-07-03 10:04 UTC by diana202402

## Description

Add gmkb keyboard

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-07-03 10:22 UTC, zvecr requested changes
You seem to be attempting to add this as a personal project, rather than alongside the existing `keyboards/doio/` keyboards?

2024-07-03 10:26 UTC, fauxpark requested changes

2024-07-03 10:26 UTC, fauxpark commented on keyboards/diana/gmkb/keyboard.json
Please run `qmk format-json -i` on this file, and rename it to `keyboard.json`.

2024-07-03 10:26 UTC, fauxpark commented on keyboards/diana/gmkb/rules.mk
This file can be deleted.

2024-07-03 10:56 UTC, diana202402 commented
> You seem to be attempting to add this as a personal project, rather than alongside the existing `keyboards/doio/` keyboards?

@zvecr  Hi, I can't revert the  files  I previously modified, 
              So I used a new personal account to update the code.

2024-07-03 11:00 UTC, diana202402 commented on keyboards/diana/gmkb/rules.mk
@fauxpark  Hi, I've deleted it and formate the keyboard  file.

2024-07-03 11:01 UTC, zvecr commented
> Hi, I can't revert the files I previously modified,
So I used a new personal account to update the code.

That doesn't make any sense.

It would need to be `keyboards/doio/nindoio` (or something similar). Anything associated to your accounts username is invalid.

2024-07-04 01:42 UTC, diana202402 commented
> > Hi, I can't revert the files I previously modified,
> > So I used a new personal account to update the code.
> 
> That doesn't make any sense.
> 
> It would need to be `keyboards/doio/nindoio` (or something similar). Anything associated to your accounts username is invalid.

@zvecr  Hi ,if I 

> > Hi, I can't revert the files I previously modified,
> > So I used a new personal account to update the code.
> 
> That doesn't make any sense.
> 
> It would need to be `keyboards/doio/nindoio` (or something similar). Anything associated to your accounts username is invalid.

@zvecr  HI， I have reverted the pull request as DOIO account.I clesed this pull request.  Thank you for your help.

2024-07-04 01:42 UTC, closed without merging