Add keyboard transition lite 1k
qmk/qmk_firmware pull request #24040
Opened 2024-07-03 10:12 UTC by tabkb

Add keyboard transition lite 1k

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-07-03 17:25 UTC, drashna requested changes

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/board.h
If this file isn't being used to configure anything, then it should just be removed.

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/config.h
> +#endif
Unused blocks should be removed. 
```suggestion
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/config.h
> +
```suggestion
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/halconf.h
> +// #define HAL_USE_SPI TRUE
```suggestion
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/config.h
> + //#define NO_ACTION_ONESHOT
```suggestion
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/mcuconf.h
> +// #define STM32_PLLXTPRE STM32_PLLXTPRE_DIV2
```suggestion
#undef STM32_PWM_USE_TIM1
#define STM32_PWM_USE_TIM1 TRUE

#undef STM32_PWM_USE_TIM2
#define STM32_PWM_USE_TIM2 TRUE
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/rules.mk
> +DEBOUNCE_TYPE 		= sym_eager_pk
```suggestion

MCU_LDSCRIPT = STM32F103xB_uf2boot
BOARD        = STM32_F103_STM32DUINO
BOOTLOADER   = uf2boot

SRC += transition_lite_1k_impl.c ws2812_custom.c
```

Disabled features don't need to be present.  Wfi idle is enabled by default, and debounce type can go in keyboard.json

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
> +#endif // RGB_MATRIX_ENABLE
Just a heads up, rgb matrix and rgblight keycodes are actively being separated. So this may not be necessary.

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
> +void matrix_init_kb(void) {
Not matrix related.
```suggestion
void keyboard_post_init_kb(void) {
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
> +}
```suggestion
    keyboard_post_init_user();
}
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
> +void matrix_scan_user(void) {
```suggestion
void housekeeping_task_kb(void) {
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
> +bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
```suggestion
bool rgb_matrix_indicators_kb(void) {
    if (!rgb_matrix_indicators_users()) {
        return false;
    }
```

2024-07-03 17:25 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/ws2812_custom.c
This is just a copy and past of the core ws2812 driver, and as such has a very, very low likelihood of getting merged.

2024-07-04 22:28 UTC, zvecr requested changes

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
This file should be renamed to `transition_lite_1k.c`

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/rules.mk
Please remove this file

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k_impl.c
> +        cp_cfg_led_power_toggle();
These functions do not exist.

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/config.h
> +#define RGB_MATRIX_KEYPRESSES
```suggestion
```

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/keyboard.json
> +        "solid_color": true,
```suggestion
```

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/keyboard.json
> +        {"flags": 6,  "matrix":[ 5, 0 ],   "x": 6,    "y": 64 }
Flags on all these are incorrect.

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/keyboard.json
> +
```suggestion
  "bootloader": "uf2boot",
```

2024-07-04 22:28 UTC, zvecr commented on keyboards/tab/swagkeys/transition_lite_1k/keyboard.json
Please run ` qmk format-json` on this file.

2024-07-11 01:13 UTC, drashna approved these changes

2024-07-11 06:14 UTC, fauxpark requested changes

2024-07-11 06:14 UTC, fauxpark commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k.c
> +#endif
```suggestion
#include "quantum.h"
```

2024-07-11 06:14 UTC, fauxpark commented on keyboards/tab/swagkeys/transition_lite_1k/readme.md
> +* Hardware Availability: [swagkeys](https://swagkeys.com/)
```suggestion
* Keyboard Maintainer: [Tab](https://github.com/tabkb)
* Hardware Supported: Blue Pill STM32F103CBT6
* Hardware Availability: [swagkeys](https://swagkeys.com/)
```

2024-07-11 06:14 UTC, fauxpark commented on keyboards/tab/swagkeys/transition_lite_1k/config.h
> +#define RBG_INDEX_FN                    80  /** FN   指示灯索引 **/
```suggestion
#define RGB_INDEX_CAPS                  62  /** Caps 指示灯索引 **/
#define RGB_INDEX_SCROLL                14  /** Scroll 指示灯索引 **/
#define RGB_INDEX_FN                    80  /** FN   指示灯索引 **/
```

2024-07-11 06:14 UTC, fauxpark commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k.c
> +        rgb_matrix_set_color(RBG_INDEX_FN, RGB_WHITE);
```suggestion
        rgb_matrix_set_color(RGB_INDEX_CAPS, RGB_WHITE);
    }

    if (host_keyboard_led_state().scroll_lock) {
        rgb_matrix_set_color(RGB_INDEX_SCROLL, RGB_WHITE);
    }

    if (layer_state_is(1)) {
        rgb_matrix_set_color(RGB_INDEX_FN, RGB_WHITE);
```

2024-07-11 07:34 UTC, fauxpark requested changes

2024-07-11 07:34 UTC, fauxpark commented on keyboards/tab/swagkeys/transition_lite_1k/keyboard.json
> +            {"matrix": [5, 5], "x": 65, "y": 64, "flags": 4},
The LED index to matrix position mapping must be 1:1. Multiple LEDs assigned to the same key will not work properly.

2024-08-30 05:58 UTC, drashna requested changes
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-08-30 05:58 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/keyboard.json
> +            "rgb_test": true,
Not sure you want this enabled
```suggestion
```

2024-08-30 05:58 UTC, drashna commented on keyboards/tab/swagkeys/transition_lite_1k/transition_lite_1k.c
> +#endif
```suggestion
#endif
    keyboard_pre_init_user();
```

2024-10-16 04:54 UTC, closed without merging