Add rk750 keyboard
qmk/qmk_firmware pull request #24048
Opened 2024-07-04 09:40 UTC by yangzheng20003

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-07-04 10:14 UTC, zvecr requested changes

2024-07-04 10:14 UTC, zvecr commented on keyboards/rk/rk750/config.h
Please remove this file

2024-07-04 10:14 UTC, zvecr commented on keyboards/rk/rk750/keyboard.json
> +    },
```suggestion
    },
    "dynamic_keymap": {
        "layer_count": 3
    },
```

2024-07-04 19:46 UTC, waffle87 commented on keyboards/rk/rk750/rk750.c
> +    gpio_write_pin_high(LED_ENABLE_PIN);
What exactly is this for? All the results I'm seeing for this keyboard on Google indicate that this is a wireless keyboard. If this is initialisation code for a wireless module, this PR will not be accepted without the accompanying wireless code.

2024-07-10 07:52 UTC, tzarc commented
This PR is on hold until #24085 is rectified.

2024-08-26 10:37 UTC, tzarc commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

2024-09-11 07:14 UTC, closed without merging

2026-07-10 08:28 UTC, refineryBeans commented on keyboards/rk/rk750/rk750.c
> +    gpio_write_pin_high(LED_ENABLE_PIN);
I know I'm late but the keyboard has both a wireless and wired model, so perhaps this is for the wired model?