Adding support for IBE60
qmk/qmk_firmware pull request #24075
Opened 2024-07-07 10:27 UTC by 4pplet

## Description

Fixed layout (true HHKB) solder PCB for the IBE60 Keyboard

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist
- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-07-07 11:20 UTC, zvecr requested changes

2024-07-07 11:20 UTC, zvecr commented on keyboards/4pplet/ibe60/readme.md
This file needs to follow the template <https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md>

2024-07-07 11:20 UTC, zvecr commented on keyboards/4pplet/ibe60/keymaps/via/rules.mk
> +ENCODER_MAP_ENABLE = yes
Has no configured encoders
```suggestion
VIA_ENABLE = yes
```

2024-07-07 11:20 UTC, zvecr commented on keyboards/4pplet/ibe60/ibe60.h
Please remove this file

2024-07-07 11:20 UTC, zvecr commented on keyboards/4pplet/ibe60/ibe60.c
Please remove this file

2024-07-07 11:20 UTC, zvecr commented on keyboards/4pplet/ibe60/config.h
Please remove this file

2024-07-07 11:20 UTC, zvecr commented on keyboards/4pplet/ibe60/keyboard.json
> +        "on_state": 1
Duplicates defaults
```suggestion
        "caps_lock": "A8"
```

2024-07-08 07:32 UTC, 4pplet commented on keyboards/4pplet/ibe60/readme.md
Thanks! Fixed!

2024-07-08 07:33 UTC, 4pplet commented on keyboards/4pplet/ibe60/matrix_diagram.md
Yes, that is correct, I have updated this.

2024-07-08 07:34 UTC, 4pplet commented
Thanks for feedback! All should be fixed now

2024-07-08 14:52 UTC, 4pplet commented on keyboards/4pplet/ibe60/matrix_diagram.md
Let's remove it if not needed 👍

2024-07-11 00:11 UTC, drashna approved these changes

2024-07-11 12:51 UTC, zvecr approved these changes

2024-07-11 12:51 UTC, merged