add my handwired split RGB keyboard
qmk/qmk_firmware pull request #24144
Opened 2024-07-18 18:06 UTC by digex

my split RGB keyboard

RGB matrix

stmf103c8t6

![20240716_171712-EDIT](https://github.com/user-attachments/assets/77a21452-9be9-47d4-803f-23cbf5841bf8)

2024-07-18 18:21 UTC, zvecr commented
Please refrain from opening new PRs for the same content.

2024-07-23 00:53 UTC, drashna requested changes

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/chconf.h
> +#define _CHIBIOS_RT_CONF_VER_6_0_
```suggestion
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/config.h
Most of the content here can be migrated to json, and commented out code can/should be removed.

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/config.h
> +#include "config_common.h"
```suggestion
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/config_common.h
Remove this.

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/halconf.h
> +#include "mcuconf.h"
```suggestion
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/info.json
> +       // "tap_dance" : true,
Comments should be removed. 
```suggestion
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/info.json
> +        //"nkro": true,
```suggestion
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/info.json
> +    "processor": "STM32F103",
So, a bluepill? 
```suggestion
    "development_board": "bluepill",
    "diode_direction": "ROW2COL",
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/keymaps/default/keymap.c
default keymap should be pristine, and simple.

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/mcuconf.h
> +
```suggestion
```

2024-07-23 00:53 UTC, drashna commented on keyboards/handwired/digex/ortho_split_rgb_matrix_keyboard/ortho_split_rgb_matrix_keyboard.c
> +#endif
```suggestion
void board_init(void) {
    AFIO->MAPR |= AFIO_MAPR_USART1_REMAP | AFIO_MAPR_TIM3_REMAP_PARTIALREMAP;
}
```

2024-10-06 02:06 UTC, closed without merging