Add files via upload
qmk/qmk_firmware pull request #24173
Opened 2024-07-21 22:54 UTC by hen-des

Initial upload of the files for the epssp75 keyboard

2024-07-21 22:59 UTC, fauxpark requested changes

2024-07-21 22:59 UTC, fauxpark commented on keyboards/handwired/epssp75/info.json
This file should be renamed to `keyboard.json`. Please also run `qmk format-json -i`.

2024-07-21 22:59 UTC, fauxpark commented on keyboards/handwired/epssp75/rules.mk
This file can be deleted.

2024-07-21 22:59 UTC, fauxpark commented on keyboards/handwired/epssp75/keymaps/noted/keymap.c
User keymaps are no longer accepted, please remove this.

2024-07-22 00:10 UTC, waffle87 requested changes
In the future, please use the provided pull request template and fill it out.

2024-07-22 00:10 UTC, waffle87 commented on keyboards/handwired/epssp75/info.json
> +		"LAYOUT_epssp_75": {
```suggestion
		"LAYOUT": {

```

2024-07-22 00:10 UTC, waffle87 commented on keyboards/handwired/epssp75/keymaps/default/keymap.c
> +		KC_LCTL,	KC_LGUI,	KC_LALT,	KC_NUBS,			KC_SPC,			KC_LSFT,										KC_ENT,			KC_SPC,				KC_RALT,	KC_NO,		KC_APP,		KC_RCTL
```suggestion
		KC_LCTL,	KC_LGUI,	KC_LALT,	KC_NUBS,			KC_SPC,			KC_LSFT,										KC_ENT,			KC_SPC,				KC_RALT,	KC_NO,		_______,		KC_RCTL
```

2024-07-22 00:10 UTC, waffle87 commented on keyboards/handwired/epssp75/keymaps/default/keymap.c
> +    [0] = LAYOUT_epssp_75(
```suggestion
    [0] = LAYOUT(
```

2024-07-22 00:10 UTC, waffle87 commented on keyboards/handwired/epssp75/keymaps/default/keymap.c
> +	[1] = LAYOUT_epssp_75(
```suggestion
	[1] = LAYOUT(
```

2024-07-22 00:10 UTC, waffle87 commented on keyboards/handwired/epssp75/readme.md
> +![epssp75](https://raw.githubusercontent.com/hen-des/epssp75/main/docs/assets/epssp75-Noted.jpg)
Please rehost this image on Imgur.

2024-10-05 02:01 UTC, closed without merging