Add ScottoHazard
qmk/qmk_firmware pull request #24181
Opened 2024-07-22 23:24 UTC by joe-scotto

## Description
Adds the ScottoHazard handwired split keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-07-23 00:54 UTC, drashna requested changes

2024-07-23 00:54 UTC, drashna commented on keyboards/handwired/scottokeebs/scottohazard/config.h
> +#define EE_HANDS
```suggestion
#pragma once

#define EE_HANDS
```

2024-08-21 23:50 UTC, drashna approved these changes

2024-08-25 13:23 UTC, fauxpark approved these changes

2024-08-30 03:18 UTC, drashna requested changes

2024-08-30 03:18 UTC, drashna commented on keyboards/handwired/scottokeebs/scottohazard/rules.mk
This can be removed

2024-08-30 03:18 UTC, drashna commented on keyboards/handwired/scottokeebs/scottohazard/keyboard.json
> +        "soft_serial_pin": "GP1"
```suggestion
        "serial": {
            "driver": "vendor",
            "pin": "GP1"
        }
```

2024-08-30 14:42 UTC, drashna commented on keyboards/handwired/scottokeebs/scottohazard/rules.mk
This file still needs removing.

2024-08-30 14:46 UTC, joe-scotto commented on keyboards/handwired/scottokeebs/scottohazard/rules.mk
Removed in ec110a1

2024-08-31 03:46 UTC, waffle87 approved these changes

2024-08-31 03:46 UTC, merged