Rename saevus to concreteflowers
qmk/qmk_firmware pull request #24249
Opened 2024-08-06 13:35 UTC by ramonimbao

## Description

As part of a rebrand, saevus renamed itself to ConcreteFlowers. This PR updates the boards currently under saevus.
- `keyboards/saevus/cor` moved to `keyboards/concreteflowers/cor`
- `keyboards/saevus/cor_tkl` moved to `keyboards/concreteflowers/cor_tkl`
- README files updated
- `keyboard.json` files updated

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-08-06 15:42 UTC, zvecr requested changes
`data/mappings/keyboard_aliases.hjson` should also be updated to reflect the moved keyboards

2024-08-06 15:51 UTC, ramonimbao commented
Thanks. I've updated the file.,

2024-08-30 03:14 UTC, drashna approved these changes

2024-10-15 03:10 UTC, ramonimbao commented
Same with https://github.com/qmk/qmk_firmware/pull/23558, is there anything I need to do for these PRs?

2024-10-19 12:25 UTC, daskygit approved these changes

2024-10-19 12:25 UTC, merged