[Keyboard] Add keyboard Piantor UV 44
qmk/qmk_firmware pull request #24247
Opened 2024-08-06 08:40 UTC by azhizhinov

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-08-06 19:03 UTC, waffle87 commented on keyboards/piantoruv44/readme.md
> +![Piantor UV 44](https://github.com/user-attachments/assets/43d3886e-2063-45a0-89b7-176b8744ccfb)
Could this image be rehosted on Imgur.

2024-08-06 19:23 UTC, azhizhinov commented
Hello. Changed to ImgBB, is that OK?

2024-08-17 15:46 UTC, waffle87 approved these changes

2024-08-30 03:02 UTC, drashna commented
As of August 26, 2024, `qmk/qmk_firmware` is no longer accepting VIA-enabled keymaps as these have now transitioned to a repository under the VIA team's control.

As you've submitted a PR containing `via` or VIA-enabled keymap(s), this is your notice that they should be removed from this PR. You should now submit a secondary PR to the [VIA QMK Userspace](https://github.com/the-via/qmk_userspace_via) repository with your associated `via` or VIA-enabled keymaps instead.

Otherwise, LGTM.

2024-08-30 03:05 UTC, drashna requested changes

2024-08-30 03:05 UTC, drashna commented on keyboards/piantoruv44/rules.mk
This can be removed.

2024-08-30 03:05 UTC, drashna commented on keyboards/piantoruv44/keyboard.json
> +        }
```suggestion
        },
        "serial": {
            "driver": "vendor"
        }
```

2024-08-30 10:04 UTC, azhizhinov commented
@drashna 
Hello.
Done.

2024-08-30 10:07 UTC, zvecr commented
> Hello.
Done.

The following have **not** been completed.
https://github.com/qmk/qmk_firmware/pull/24247#discussion_r1737750106
https://github.com/qmk/qmk_firmware/pull/24247#discussion_r1737731357

2024-08-30 10:53 UTC, azhizhinov commented
@zvecr 
Hello.
Done.

2024-08-30 11:05 UTC, zvecr commented
https://github.com/qmk/qmk_firmware/pull/24247#discussion_r1737731357

...nope

2024-08-30 11:21 UTC, azhizhinov commented
@zvecr 
rules.mk has been deleted.

2024-09-24 17:14 UTC, azhizhinov commented
Hello.
@drashna, sorry to bother you, but could you review this PR?
Is anything there for me to improve?
Thanks in advance.

2024-09-28 18:27 UTC, drashna commented on keyboards/piantoruv44/readme.md
> +![Piantor UV 44](https://i.ibb.co/QvJM1GR/20240806-PIANTORUV44-00.png)
This image doesn't load?

2024-09-29 01:36 UTC, fauxpark commented on keyboards/piantoruv44/readme.md
> +![Piantor UV 44](https://i.ibb.co/QvJM1GR/20240806-PIANTORUV44-00.png)
Loads for me. Imgur is preferred though.

2024-09-29 01:37 UTC, fauxpark requested changes

2024-09-29 01:37 UTC, fauxpark commented on keyboards/piantoruv44/keyboard.json
Please run `qmk format-json -i` on this file.

2024-09-29 01:37 UTC, fauxpark commented on keyboards/piantoruv44/readme.md
> +    make azhizhinov/piantoruv44:default:flash
```suggestion
    make piantoruv44:default

Flashing example for this keyboard:

    make piantoruv44:default:flash
```

2024-09-29 07:23 UTC, azhizhinov commented on keyboards/piantoruv44/readme.md
> +![Piantor UV 44](https://i.ibb.co/QvJM1GR/20240806-PIANTORUV44-00.png)
Hello.
It's perfectly fine.
![Снимок экрана от 2024-09-29 10-20-47](https://github.com/user-attachments/assets/d87e50b2-8358-41b4-9b53-1c81a9f696e2)

2024-09-29 07:53 UTC, azhizhinov commented on keyboards/piantoruv44/keyboard.json
Hello.
@fauxpark 
Done.
Thanks in advance.

2024-10-02 17:04 UTC, drashna approved these changes

2024-10-11 03:01 UTC, merged