add rlycoolmacropad by tepphhra
qmk/qmk_firmware pull request #24340
Opened 2024-08-29 00:42 UTC by Tepphhra

## Description

i would like to add files for 4x4 macropad on ATmega32u4, such as config, keymaps

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-08-29 00:52 UTC, waffle87 requested changes

2024-08-29 00:52 UTC, waffle87 commented on keyboards/tepphhra/rlycoolmacropad/config.h
This file should be removed.

2024-08-29 00:52 UTC, waffle87 commented on keyboards/tepphhra/rlycoolmacropad/info.json
This file should be renamed to `keyboard.json`.

2024-08-29 00:52 UTC, waffle87 commented on keyboards/tepphhra/rlycoolmacropad/info.json
> +    "bootloader": "caterina",
```suggestion
    "development_board": "promicro",
```

2024-08-29 00:52 UTC, waffle87 commented on keyboards/tepphhra/rlycoolmacropad/info.json
> +        "console": false,
```suggestion
        "bootmagic": true,
```

2024-08-29 00:52 UTC, waffle87 commented on keyboards/tepphhra/rlycoolmacropad/keymaps/default/keymap.c
This file is missing a license header.

2024-08-29 00:52 UTC, waffle87 commented on keyboards/tepphhra/rlycoolmacropad/readme.md
This file does not follow the [template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md) and also contains various incorrect information pertaining to this keyboard.

2024-08-30 02:47 UTC, drashna commented on keyboards/tepphhra/rlycoolmacropad/keyboard.json
> +    }
```suggestion
    "usb": {
        "vid": "0xFEED",
        "pid": "0x0000",
        "device_version": "0x0001"
    }
```

2025-06-29 03:03 UTC, zvecr commented
Closing as if it were not marked as draft, stalebot would have been actioned,

> Thank you for your contribution!
This pull request has been automatically closed because it has not had activity in the last 30 days. Please feel free to give a status update now, ping for review, or re-open when it's ready.

If the intention is to move this PR forward, please also fix the build issues around `device_version` not being a semver string (eg `"device_version": "0.0.1"`).

2025-06-29 03:03 UTC, closed without merging