Add new keyboard "Jourkey"
qmk/qmk_firmware pull request #24409
Opened 2024-09-18 17:04 UTC by takashicompany

## Description

I have created a new keyboard and would appreciate a review.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-09-18 17:26 UTC, zvecr requested changes

2024-09-18 17:26 UTC, zvecr commented on keyboards/takashicompany/jourkey/readme.md
> +![takashicompany/jourkey](https://i.imgur.com/pCrTbKnh.jpeg)
```suggestion
![takashicompany/jourkey](https://i.imgur.com/pCrTbKn.jpeg)
```

2024-09-18 17:26 UTC, zvecr commented on keyboards/takashicompany/jourkey/keyboard.json
> +        "LAYOUT": {
* `LAYOUT` macro is missing key widths so it displays correctly
* Missing a layout macro that has an iso key

2024-10-11 02:27 UTC, drashna approved these changes

2024-12-02 17:09 UTC, waffle87 approved these changes

2024-12-02 17:10 UTC, merged