Add SteelSeries Prime+ mouse
qmk/qmk_firmware pull request #24408
Opened 2024-09-18 16:40 UTC by daskygit

## Description

Needs to go via develop for the QP driver.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-09-18 16:56 UTC, drashna approved these changes

2024-09-18 17:07 UTC, zvecr commented on keyboards/steelseries/prime_plus/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-09-18 17:16 UTC, zvecr requested changes

2024-09-18 17:16 UTC, zvecr commented on keyboards/steelseries/prime_plus/config.h
> +#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
```suggestion
```

2024-09-18 17:16 UTC, zvecr commented on keyboards/steelseries/prime_plus/keyboard.json
> +        },
```suggestion
        },
        "default": {
            "animation": "rainbow_mood"
        },
```

2024-09-18 17:16 UTC, zvecr commented on keyboards/steelseries/prime_plus/readme.md
> +Enter the bootloader in 3 ways:a
```suggestion
Enter the bootloader in 2 ways:
```

2024-09-20 05:04 UTC, tzarc approved these changes

2024-09-20 05:17 UTC, merged