NK Classic TKL ISO
qmk/qmk_firmware pull request #24434
Opened 2024-09-24 17:58 UTC by yiancar

## Description

Add the ISO variant of NK Classic TKL PCB
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-09-24 18:42 UTC, dunk2k requested changes

2024-09-24 18:42 UTC, dunk2k commented on keyboards/novelkeys/nk_classic_tkl_iso/keyboard.json
> +    },
1. layout alias not required
2. community layout support added
```suggestion
    "community_layouts": ["tkl_iso_tsangan"],
```

2024-10-05 14:31 UTC, keyboard-magpie approved these changes

2024-10-05 16:15 UTC, waffle87 approved these changes

2024-10-05 16:16 UTC, merged