Somei70 addition
qmk/qmk_firmware pull request #24444
Opened 2024-09-27 12:18 UTC by gzowski

Somei70 - 70 key keyboard with OLED and RGB LED's

## Description

New keyboard to add to QMK. formatted json, kept everything in keyboard.json where possible. Only one layout being default but with VIA_ENABLE set. 
Not sure if this needed to be in it's own VIA keymap or whether default was fine.
Link to projects github currently private while build guide is being written up.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-09-27 12:28 UTC, fauxpark requested changes

2024-09-27 12:28 UTC, fauxpark commented on keyboards/somei70/keyboard.json
Please run `qmk format-json -i` on this file.

2024-09-27 12:28 UTC, fauxpark commented on keyboards/somei70/keymaps/default/rules.mk
> +VIA_ENABLE = yes
```suggestion
```
VIA cannot be enabled on the default keymap.

2024-09-27 12:28 UTC, fauxpark commented on keyboards/somei70/rules.mk
This file can be deleted.

2024-09-27 12:28 UTC, fauxpark commented on keyboards/somei70/keymaps/default/keymap.c
Please use consistent indentation.

2024-09-27 14:18 UTC, fauxpark requested changes

2024-09-27 14:18 UTC, fauxpark commented on keyboards/somei70/keyboard.json
Layout and RGB Matrix seems like it needs work.
![image](https://github.com/user-attachments/assets/f2d471d3-4422-41d8-a8e9-bae69b99a1d0)

2024-09-27 23:49 UTC, fauxpark requested changes

2024-09-27 23:49 UTC, fauxpark commented on keyboards/somei70/keyboard.json
Layout is still wrong, please adjust the key sizes.
![image](https://github.com/user-attachments/assets/2644e08c-3a71-44fb-b93d-f8ecc17e674e)
RGB Matrix doesn't make sense to me, are the LEDs only on the top row?

2024-09-28 13:11 UTC, gzowski commented on keyboards/somei70/keyboard.json
LED's only apply to top row, recalculated based on full keyboard width by 224, key positions should all now be correct. Checked appearence in qmk info -m -kb somei70 and all appears correct.

![image](https://github.com/user-attachments/assets/dee23b1a-e222-4bea-81d0-03760c6f86b0)

2024-10-31 11:20 UTC, gzowski commented
Do I need to make any further changes?

2024-10-31 12:49 UTC, fauxpark requested changes

2024-10-31 12:49 UTC, fauxpark commented on keyboards/somei70/keymaps/default/rules.mk
This file can be deleted. OLED is enabled at keyboard level, and `ssd1306` is the default driver.

2024-11-01 16:17 UTC, gzowski commented on keyboards/somei70/keymaps/default/keymap.c
removed tabs and formatted C for somei70.c

2024-11-01 16:17 UTC, gzowski commented on keyboards/somei70/keymaps/default/keymap.c
> +	[_LAYERC] = LAYOUT_5x15(
removed _LAYERC

2024-11-01 16:18 UTC, gzowski commented on keyboards/somei70/keyboard.json
> +        "oled": true,
added somei70.c to include all OLED features.

2024-11-01 16:28 UTC, waffle87 requested changes

2024-11-01 16:28 UTC, waffle87 commented on keyboards/somei70/somei70.c
> +oled_rotation_t oled_init_user(oled_rotation_t rotation) {
```suggestion
oled_rotation_t oled_init_kb(oled_rotation_t rotation) {
```

2024-11-01 16:28 UTC, waffle87 commented on keyboards/somei70/somei70.c
> +bool oled_task_user(void) {
```suggestion
bool oled_task_kb(void) {
    if (!oled_task_user()) {
        return false;
    }
```

2024-11-01 16:28 UTC, waffle87 commented on keyboards/somei70/somei70.c
> +bool process_record_user(uint16_t keycode, keyrecord_t *record) {
```suggestion
bool process_record_kb(uint16_t keycode, keyrecord_t *record) {
```

2024-11-01 16:28 UTC, waffle87 commented on keyboards/somei70/somei70.c
> +    return true;
```suggestion
    return process_record_user(keycode, record);
```

2024-11-26 14:47 UTC, gzowski commented
Forgot I still had this open, Is there anything I'm missing out at this point to be added/modified?

2024-11-27 01:23 UTC, fauxpark requested changes

2024-11-27 01:23 UTC, fauxpark commented on keyboards/somei70/keymaps/default/keymap.c
> +  KC_LCTL, KC_LGUI, KC_LALT, KC_SPC , RGB_TOG, KC_ENT , KC_RALT, _______, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```suggestion
  KC_TAB , RM_NEXT, RM_VALD, RM_VALU, RM_SPDD, RM_SPDU, RM_HUED, RM_HUEU, RM_SATD, RM_SATU, KC_P   , KC_LBRC, KC_RBRC, KC_BSLS,
  KC_CAPS, KC_A   , KC_S   , KC_D   , KC_F   , KC_G   , KC_H   , KC_J   , KC_K   , KC_L   , KC_SCLN, KC_QUOT, KC_GRV , KC_DEL , KC_PGUP,
  KC_LSFT, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   , KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH, KC_RSFT, KC_INS , KC_UP  , KC_PGDN,
  KC_LCTL, KC_LGUI, KC_LALT, KC_SPC , RM_TOGG, KC_ENT , KC_RALT, _______, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
```

2024-12-09 04:18 UTC, drashna requested changes

2024-12-09 04:18 UTC, drashna commented on keyboards/somei70/somei70.c
> +    oled_write_ln(wpm_str, false);
I would recommend the `get_u8_str` function. It's much lighter on memory, and for stuff like this, recommended. 
```suggestion
    oled_write_P(PSTR("WPM: "), false);
    oled_write_ln(get_u8_str(get_current_wpm(), '0'), false);
```

2024-12-09 04:18 UTC, drashna commented on keyboards/somei70/somei70.c
> +    oled_write_ln(brightness_str, false);
```suggestion
    oled_write_P(PSTR("LED Brightness: "), false);
    oled_write_ln(get_u8_str(rgblight_get_val(), '0'), false);
```

2024-12-24 06:30 UTC, drashna approved these changes

2024-12-24 18:05 UTC, waffle87 approved these changes

2024-12-24 18:05 UTC, merged