always return audio pin to 0 on ARM
qmk/qmk_firmware pull request #24503
Opened 2024-10-19 03:14 UTC by infinityis

The ARM audio PWM hardware implementation does not always return the audio pin to 0 when stopping the PWM. If the audio pin is held high while not playing audio, for magnetic speakers/buzzers, this will result in excessive current consumption while also producing undesirable audible noise.

This PR ensures that the audio pin is cleared whenever the PWM is stopped.

## Description
[Context (Discord)](https://discord.com/channels/440868230475677696/867530303261114398/1296753666723676183)

Only specific timers fully support disabling (clearing) the PWM output pin when the PWM is stopped. For timers that don't clear the output pin, this PR enforces stopping while the pin is low by (1) increasing the frequency as high as possible, (2) waiting for the pin to go low, and (3) only then stopping the PWM.

The first attempt to do this may actually fail, because the pin state may independently change between the pin state detection and stopping the PWM.  If this happens, a loop ensures that the pin ends up in a low state (regardless of interrupts, etc. that may disrupt the process.

This implementation does not change the pin mode (PAL) to force the pin low; it merely waits briefly for a 0 to occur.

Additionally, when changing the frequency change to 0Hz, this implementation actually stops the PWM.

## Types of Changes

- [X] Core
- [X] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-10-19 18:53 UTC, sigprof requested changes
Although the current audio code is wrong (calling `audio_update_state()` from `audio_callback()` results in a call to `timer_read32()` → `chSysLock()` from an interrupt handler, which is not allowed), let's not introduce further bugs.  In particular, `pwmStart()` and `pwmStop()` may be invoked only from the Normal state, not from an interrupt handler or a system lock zone, therefore `channel_1_set_frequency()` can't use those functions, and must use only the `pwm*I()` functions which are safe to call after `chSysLockFromISR()`.

There are two ways to deactivate a PWM output channel while leaving the timer running:
- `pwmEnableChannelI(pwmp, channel, 0)` — set the PWM pulse width to 0.
- `pwmDisableChannelI(pwmp, channel)` — explicitly disable the channel.

There might be some hardware-dependent subtle differences between these functions though.  E.g., on RP2040 disabling the channel is internally implemented as setting the PWM pulse width to 0, which actually takes effect only on the next PWM timer cycle; however, on STM32 disabling the channel actually resets the enable bit in the `CCRx` register of the corresponding timer, which might take effect immediately in some cases, but apparently ChibiOS sets the `OCxPE` bits in the `CCMRx` registers, therefore the `CCRx` registers are buffered too.  So it seems that using `pwmDisableChannelI()` does not provide any real advantages in comparison to `pwmEnableChannelI(pwmp, channel, 0)`.

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +    }
This function is called from the timer interrupt handler; calling `pwmStop()` or `pwmStart()` in this state is not valid.

What could be valid is:
```suggestion
        chSysLockFromISR();
        pwmChangePeriodI(&AUDIO_PWM_DRIVER, 2);
        pwmEnableChannelI(&AUDIO_PWM_DRIVER, AUDIO_PWM_CHANNEL - 1, 0);
        chSysUnlockFromISR();
        return;
    }
```

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +    chSysUnlockFromISR();
```suggestion
    pwmChangePeriod(&AUDIO_PWM_DRIVER, 2);
    pwmEnableChannel(&AUDIO_PWM_DRIVER, AUDIO_PWM_CHANNEL - 1, 0);
```

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +void audio_wait_for_pin(pin_t pin, uint8_t target_state) {
```suggestion
static void audio_wait_for_pin(pin_t pin, uint8_t target_state) {
```

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +    }
With the pulse width set to 0 the second wait should not be needed.
```suggestion
```

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +static bool channel_1_stopped = true;
After removing the (invalid) code to start the timer from `channel_1_set_frequency()` this variable becomes write-only and can be removed.
```suggestion
```

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +    channel_1_stopped = false;
```suggestion
```

2024-10-19 18:53 UTC, sigprof commented on platforms/chibios/drivers/audio_pwm_hardware.c
> +    channel_1_stopped = true;
```suggestion
```

2024-10-19 19:00 UTC, sigprof commented
Also, after some more thinking, maybe this would be enough to reset the pin state on stop without those wait loops?
```c
void channel_1_stop(void) {
    pwmStop(&AUDIO_PWM_DRIVER);
    pwmStart(&AUDIO_PWM_DRIVER, &pwmCFG);
    pwmEnableChannelI(&AUDIO_PWM_DRIVER, AUDIO_PWM_CHANNEL - 1, 0);
    pwmStop(&AUDIO_PWM_DRIVER);
}
```

2024-10-20 23:08 UTC, infinityis commented
I've tested the approach proposed above by sigprof and found it works great and is much simpler, correct, and intuitive. The pulse width now gets set to zero before disabling the PWM. Additionally, inputting a frequency of zero now also sets the pulse width to zero.

2024-10-21 04:57 UTC, drashna commented
I can't speak for correctness here, but a quick test ... this breaks a LOT of the songs/notes with weird stops.

2024-10-21 07:07 UTC, sigprof requested changes

2024-10-22 16:33 UTC, drashna approved these changes
new changes work great

2024-12-14 06:50 UTC, infinityis commented
Commenting to remove stale label

2025-01-01 04:52 UTC, tzarc approved these changes

2025-01-02 07:10 UTC, merged