Add Iris LM series of keyboards
qmk/qmk_firmware pull request #24510
Opened 2024-10-21 21:37 UTC by nooges

## Description

Adds Iris LM-G and Iris LM-K PCBs for the Iris LM case.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-10-21 21:50 UTC, waffle87 requested changes

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/g1/config.h
> +#   define NOP_FUDGE 0.4
This shouldn't be needed.
```suggestion
```

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/g1/keyboard.json
> +        "enabled": true,
```suggestion
        "rgb_matrix": true,
        "encoder": true
    },
    "encoder": {
```

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/k1/config.h
> +#   define NOP_FUDGE 0.4
```suggestion
```

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/g1/keyboard.json
> +    "features": {
```suggestion
    "features": {
        "bootmagic": true,
```

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/k1/keyboard.json
> +    "features": {
```suggestion
    "features": {
        "bootmagic": true,
```

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/g1/rules.mk
This file should be removed:
- `SERIAL_DRIVER` should be migrated to `keyboard.json` under `split.serial.driver`
- These are the default values for EEPROM/Wear-leveling drivers

2024-10-21 21:50 UTC, waffle87 commented on keyboards/keebio/iris_lm/k1/rules.mk
As above.

2024-10-21 22:31 UTC, nooges commented on keyboards/keebio/iris_lm/g1/config.h
> +#   define NOP_FUDGE 0.4
Ah right, we fixed it the last time

2024-10-22 16:32 UTC, drashna approved these changes

2024-10-22 23:31 UTC, waffle87 approved these changes

2024-10-23 02:14 UTC, merged