Refactor Starlight matrix effect
qmk/qmk_firmware pull request #24521
Opened 2024-10-25 01:22 UTC by filterpaper

## Description

Guard main loop with `RGB_MATRIX_USE_LIMITS` to avoid breaking `rgb_matrix_indicators_advanced_user()` function.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-10-25 02:41 UTC, drashna approved these changes

2024-10-27 01:17 UTC, filterpaper commented
@drashna There are significant changes since your last approval.

2024-10-28 01:08 UTC, drashna requested changes
This appears to make the animation run slower (effect wise, not scan rate wise).

2024-10-28 01:08 UTC, drashna commented on quantum/rgb_matrix/animations/starlight_dual_hue_anim.h
> +    else if (led_min <= index && index < led_max && HAS_ANY_FLAGS(g_led_config.flags[idx], params->flags)) {
no `idx` variable.
```suggestion
    else if (led_min <= index && index < led_max && HAS_ANY_FLAGS(g_led_config.flags[index], params->flags)) {
```

2024-10-28 01:16 UTC, filterpaper commented on quantum/rgb_matrix/animations/starlight_anim.h
>          set_starlight_color(i, params);
Corrected.

2024-10-28 01:17 UTC, filterpaper commented
> This appears to make the animation run slower (effect wise, not scan rate wise).

There were no changes to the interval time scaling though.

2024-10-28 01:24 UTC, drashna commented
> > This appears to make the animation run slower (effect wise, not scan rate wise).
> 
> There were no changes to the interval time scaling though.

Odd.  More so that I can't reproduce it. So it may have been a syncing related issue.

2024-10-28 01:26 UTC, drashna approved these changes

2024-10-28 01:31 UTC, filterpaper commented
> > > This appears to make the animation run slower (effect wise, not scan rate wise).
> > 
> > 
> > There were no changes to the interval time scaling though.
> 
> Odd. More so that I can't reproduce it. So it may have been a syncing related issue.

These effects are a bit "jittery" because of the step interface. The revision in #24137 is a lot better and could be incorporated into the "hue" and "sat" version in another revision.

2024-12-12 02:15 UTC, filterpaper commented
Pull request is still awaiting review.

2025-01-01 04:48 UTC, tzarc approved these changes

2025-01-02 07:10 UTC, merged