[add]
qmk/qmk_firmware pull request #24526
Opened 2024-10-25 16:04 UTC by ambergon

add keyboards/ambergon/multipleglove

## Description

add my new keyboard map 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-10-25 18:07 UTC, zvecr requested changes

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/config.h
Please remove this file

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/rules.mk
Please remove this file

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/readme.md
> +* Hardware Availability: *Links to where you can find this hardware*
This section needs to be filled in

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/readme.md
> +    make ambergon/MultipleGlove:default:flash
```suggestion
    make ambergon/multipleglove:default

Flashing example for this keyboard:

    make ambergon/multipleglove:default:flash
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keymaps/default/rules.mk
> +ENCODER_ENABLE		= yes
```suggestion
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keyboard.json
> +            { "pin_a" : "D3" , "pin_b" : "D2" , "resolution" : 4 }
```suggestion
            { "pin_a" : "B4" , "pin_b" : "B5"},
            { "pin_a" : "B2" , "pin_b" : "B6" },
            { "pin_a" : "D3" , "pin_b" : "D2" }
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keyboard.json
> +        "command": false,
```suggestion
        "encoder": true,
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keyboard.json
> +    },
```suggestion
    },
    "dynamic_keymap": {
        "layer_count": 16
    },
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +#endif
```suggestion
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +    )
Padding out the keymap array with useless layers is not required.
```suggestion
    [0] = LAYOUT(
        KC_A  ,   KC_B  ,   KC_C  ,   KC_D  ,
        KC_E  ,   KC_F  ,   KC_G  ,   KC_H  ,
        KC_I  ,   KC_J  ,   KC_K  ,   KC_L  ,
        KC_NO ,   KC_NO ,   KC_NO ,   KC_NO ,
        KC_Q  ,   KC_R
    )
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +#endif
```suggestion

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0]  = { ENCODER_CCW_CW( KC_P , KC_Q ) , ENCODER_CCW_CW( KC_R , KC_S ) , ENCODER_CCW_CW( KC_T , KC_U ) }
};
#endif
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +
Default keymaps should be basic, and not contain this sort of logic.

Given you have a bunch of `KC_NO` in the layers, the suggestion would be to rework to use [standard layer keycodes](https://docs.qmk.fm/feature_layers#switching-and-toggling-layers)
```suggestion
```

2024-10-25 18:07 UTC, zvecr commented on keyboards/ambergon/multipleglove/keyboard.json
> +
```suggestion
```

2024-11-15 05:29 UTC, zvecr commented
Theres not much point requesting review, when you still have outstanding requested changes.

2024-11-15 06:26 UTC, ambergon commented
First, let me apologize for not understanding the “Commit suggestion and Add suggestion to batch” feature of github, and thus not being able to incorporate it properly.

2024-11-15 11:04 UTC, ambergon commented
I understand the role of the “Files change tab”.
Sorry for being rude.

2024-11-15 11:07 UTC, ambergon commented
The matrix_scan_user function, which you recommended to turn off,
I would like to keep it because it is the core function of the keyboard.

2025-01-03 06:22 UTC, drashna commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +    myLayer = ( matrix_is_on( 3 , 3 ) << 3 ) | ( matrix_is_on( 3 , 2 ) << 2 ) | ( matrix_is_on( 3 , 1 ) << 1 ) | ( matrix_is_on( 3 , 0 ) << 0 );
Generally, code like this isn't permitted in the default keymap, and would need to be moved to a vendor keyman. 

That said: 
```suggestion
static uint8_t myOldLayer = 0;
void matrix_scan_user(void) {

    uint8_t myLayer= (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0) ; 
    myLayer = ( matrix_is_on( 3 , 3 ) << 3 ) | ( matrix_is_on( 3 , 2 ) << 2 ) | ( matrix_is_on( 3 , 1 ) << 1 ) | ( matrix_is_on( 3 , 0 ) << 0 );
```
Also, this looks lo be a poor man's combo?

2025-01-03 10:39 UTC, ambergon commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +    myLayer = ( matrix_is_on( 3 , 3 ) << 3 ) | ( matrix_is_on( 3 , 2 ) << 2 ) | ( matrix_is_on( 3 , 1 ) << 1 ) | ( matrix_is_on( 3 , 0 ) << 0 );
Exactly.
I use four toggle switches on my keyboard.
https://github.com/ambergon/MultipeGlove

2025-03-01 22:44 UTC, waffle87 requested changes

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/keyboard.json
> +    "bootloader": "atmel-dfu",
Per the [github project](https://github.com/ambergon/MultipeGlove/tree/master) and the microcontroller you used, this would be the most appropriate configuration. If you do want to retain the `atmel-dfu` bootloader setting, use `elite_c` instead here.
```suggestion
    "development_board": "promicro",
```

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/keyboard.json
> +    "url": "",
```suggestion
    "url": "https://github.com/ambergon/MultipeGlove",
```

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/keyboard.json
Please run `qmk format -i keyboards/ambergon/multipleglove/keyboard.json` on this file.

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +        KC_Q  ,   KC_R
This does not look representative of the physical layout:
![image](https://github.com/user-attachments/assets/102ab901-5ba1-4ed1-ba28-a72d7558b3a6)

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/keymaps/default/keymap.c
> +}
As Zvecr suggested before, this should be removed and the existing layer keycodes used instead.
```suggestion
```

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/readme.md
> +![MultipleGlove](https://github.com/ambergon/MultipeGlove/blob/master/img/6.jpg)
These are all dead links. These images should be hosted on Imgur if you'd like them to be included here.

2025-03-01 22:44 UTC, waffle87 commented on keyboards/ambergon/multipleglove/readme.md
> +```
```suggestion
make ambergon/MultipleGlove:default

Flashing example for this keyboard:

make ambergon/MultipleGlove:default:flash
```

2025-05-23 02:13 UTC, closed without merging