Refactor Riverflow matrix effect
qmk/qmk_firmware pull request #24520
Opened 2024-10-24 23:56 UTC by filterpaper

## Description

Simplify effect by reusing an existing runner.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-10-25 02:39 UTC, drashna approved these changes

2024-10-27 04:35 UTC, fauxpark requested changes

2024-10-27 04:35 UTC, fauxpark commented on quantum/rgb_matrix/animations/riverflow_anim.h
> +hsv_t RIVERFLOW_maths(hsv_t hsv, uint8_t i, uint8_t time) {
```suggestion
hsv_t RIVERFLOW_math(hsv_t hsv, uint8_t i, uint8_t time) {
```

2024-10-27 04:35 UTC, fauxpark commented on quantum/rgb_matrix/animations/riverflow_anim.h
> +    return effect_runner_i(params, &RIVERFLOW_maths);
```suggestion
    return effect_runner_i(params, &RIVERFLOW_math);
```

2024-10-28 01:17 UTC, drashna approved these changes

2024-10-28 05:18 UTC, fauxpark approved these changes

2024-10-28 05:51 UTC, merged