[Keyboard] Add S6xty PCB
qmk/qmk_firmware pull request #24541
Opened 2024-10-28 09:13 UTC by trnthsn

## Description

Add QMK support for S6xty5 Rev.2 PCB

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-04 10:37 UTC, trnthsn commented
@waffle87 Sorry for tagging you. Could you review my pull request?

2024-11-04 15:43 UTC, waffle87 commented on keyboards/trnthsn/s6xty5r2/stm32f072/config.h
Since this is identical to `stm32f103/config.h`, this can be moved to the top keyboard level, and the `stm32f103/config.h` file removed.

2024-11-04 15:43 UTC, waffle87 commented on keyboards/trnthsn/s6xty5r2/stm32f072/mcuconf.h
As above.

2024-11-04 15:52 UTC, trnthsn commented on keyboards/trnthsn/s6xty5r2/stm32f072/config.h
i had moved 4 files out of stm32f103 and stm32f072 folder

2024-11-04 15:54 UTC, waffle87 approved these changes

2024-11-22 10:30 UTC, trnthsn commented
hi @fauxpark, could you review my PR.

2024-11-22 14:14 UTC, trnthsn commented on keyboards/trnthsn/s6xty5r2/keymaps/default/keymap.c
I updated my keymap

2024-11-22 14:14 UTC, trnthsn commented on keyboards/trnthsn/s6xty5r2/info.json
> +            "rgb_test": true,
i had removed that rgb mode

2024-11-22 14:22 UTC, fauxpark requested changes

2024-11-22 14:22 UTC, fauxpark commented on keyboards/trnthsn/s6xty5r2/keymaps/default/keymap.c
> +        MO(2)  , _______, _______, _______, _______, _______, _______, UG_NEXT, RGB_VAD, RGB_VAI, _______, _______, _______, _______,
```suggestion
        MO(2)  , _______, _______, _______, _______, _______, _______, UG_NEXT, UG_VALD, UG_VALU, _______, _______, _______, _______,
```

2024-11-22 16:06 UTC, trnthsn commented
@fauxpark i had applied your suggestion.

2024-12-02 15:27 UTC, trnthsn commented
hi @fauxpark, could you review my PR again

2025-01-03 07:06 UTC, trnthsn commented
hi @fauxpark, could you review my PR again

2025-04-21 02:12 UTC, closed without merging