Add Fuyu HS
qmk/qmk_firmware pull request #24567
Opened 2024-11-06 12:51 UTC by zykrah

## Description

As per title.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-06 13:55 UTC, zvecr commented on keyboards/zykrah/fuyu_hs/config.h
> +#define CAPS_LOCK_LED_INDEX 0
This is unused?

```suggestion
```

2024-11-06 14:03 UTC, zvecr requested changes

2024-11-06 14:03 UTC, zvecr commented on keyboards/zykrah/fuyu_hs/readme.md
> +![FUYU HS 7U](https://i.imgur.com/8zjDNJTh.jpg)
```suggestion
![FUYU HS 7U](https://i.imgur.com/8zjDNJT.jpg)
```

2024-11-08 01:13 UTC, waffle87 approved these changes

2024-11-08 17:27 UTC, drashna approved these changes

2024-11-09 04:23 UTC, merged