Add Idyllic Pizza Pad
qmk/qmk_firmware pull request #24566
Opened 2024-11-06 12:01 UTC by zykrah

## Description

As per title.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-06 14:05 UTC, zvecr requested changes

2024-11-06 14:05 UTC, zvecr commented on keyboards/idyllic/pizzapad/keyboard.json
> +        "LAYOUT": {
```suggestion
    "community_layouts": ["ortho_3x3"],
    "layouts": {
        "LAYOUT_ortho_3x3": {
```

2024-11-06 14:05 UTC, zvecr commented on keyboards/idyllic/pizzapad/keymaps/default/keymap.c
> +	),
```suggestion
	[0] = LAYOUT_ortho_3x3(
		KC_P7,   KC_P8,   KC_P9,
		KC_P4,   KC_P5,   KC_P6,
		KC_P1,   KC_P2,   KC_P3
	)
```

2024-11-08 01:08 UTC, waffle87 approved these changes
Otherwise LGTM.

2024-11-08 01:08 UTC, waffle87 commented on keyboards/idyllic/pizzapad/keymaps/default/keymap.c
> +
```suggestion
    [0] = LAYOUT_ortho_3x3(	
        KC_P7,   KC_P8,   KC_P9,
        KC_P4,   KC_P5,   KC_P6,
        KC_P1,   KC_P2,   KC_P3
    )
```

2024-11-09 02:43 UTC, drashna approved these changes

2024-11-09 04:21 UTC, merged