[Keyboard] Add Majestouch Redux
qmk/qmk_firmware pull request #24586
Opened 2024-11-10 11:56 UTC by Druah

## Description

Added Majestouch Redux

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* N/A

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-10 12:51 UTC, dunk2k requested changes

2024-11-10 12:51 UTC, dunk2k commented on keyboards/druah/majestouch_redux/keyboard.json
> +    },
Thankfully, `layout_aliases` not required
```suggestion
```

2024-11-10 12:51 UTC, dunk2k commented on keyboards/druah/majestouch_redux/keymaps/default/keymap.c
> +    [0] = LAYOUT(
```suggestion
    [0] = LAYOUT_tkl_ansi(
```

2024-11-10 19:08 UTC, waffle87 approved these changes

2024-11-13 04:17 UTC, drashna approved these changes

2024-11-13 04:29 UTC, merged