Azoteq - improve I2C behaviour while polling.
qmk/qmk_firmware pull request #24611
Opened 2024-11-17 15:59 UTC by daskygit

## Description
This aims to improve the behaviour when not using a motion pin. Using basic_profiling.h seems to have a fairly decent speed increase as less time is spent during I2C transactions.
```
Tweaked code
get_report -- Percentage time spent: 2% (idle)
get_report -- Percentage time spent: 2% (circle motion)

Old code
get_report -- Percentage time spent: 12% (idle)
get_report -- Percentage time spent: 63% (circle motion)
```
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2025-01-02 07:17 UTC, drashna approved these changes

2025-01-08 18:52 UTC, idank commented
This change also fixes a bug with the current driver where it mistakenly reads a double tap gesture on every report. Seems to be happening on newer Azoteqs only.

+1 to merging this.

2025-01-08 19:48 UTC, KarlK90 requested changes

2025-01-08 19:48 UTC, KarlK90 commented on drivers/sensors/azoteq_iqs5xx.c
> +        azoteq_iqs5xx_init_status = azoteq_iqs5xx_set_report_rate(AZOTEQ_IQS5XX_REPORT_RATE, AZOTEQ_IQS5XX_IDLE_TOUCH, false);
```suggestion
        azoteq_iqs5xx_init_status |= azoteq_iqs5xx_set_report_rate(AZOTEQ_IQS5XX_REPORT_RATE, AZOTEQ_IQS5XX_IDLE, false);
        azoteq_iqs5xx_init_status |= azoteq_iqs5xx_set_report_rate(AZOTEQ_IQS5XX_REPORT_RATE, AZOTEQ_IQS5XX_IDLE_TOUCH, false);
```

Maybe missing an or condition?

2025-01-09 23:56 UTC, daskygit commented on drivers/sensors/azoteq_iqs5xx.c
> +        azoteq_iqs5xx_init_status = azoteq_iqs5xx_set_report_rate(AZOTEQ_IQS5XX_REPORT_RATE, AZOTEQ_IQS5XX_IDLE_TOUCH, false);
Yeah, it is missing. Thanks.

2025-01-10 18:11 UTC, KarlK90 approved these changes

2025-01-11 01:29 UTC, merged