Add support for cans12erv2
qmk/qmk_firmware pull request #24628
Opened 2024-11-21 13:53 UTC by canbaytok

## Description
I've worked on a new version of my small handwired DIY keypad, which now features hot swap switch sockets and an encoder knob.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-21 14:06 UTC, waffle87 commented on keyboards/handwired/cans12erv2/keymaps/default/keymap.c
> +    [_KEYPAD] = LAYOUT(
```suggestion
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
```

2024-11-21 14:07 UTC, waffle87 commented on keyboards/handwired/cans12erv2/keymaps/default/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
```

2024-11-21 14:07 UTC, waffle87 commented on keyboards/handwired/cans12erv2/readme.md
> +![Cans12erV2](https://raw.githubusercontent.com/canbaytok/Cans12erV2/refs/heads/main/assets/Cans12erV2.png)
This image should be rehosted on Imgur.

2024-11-21 14:07 UTC, waffle87 commented on keyboards/handwired/cans12erv2/readme.md
> +Programming is planned to be possible with [QMK/VIA](https://usevia.app/)
```suggestion
```

2024-11-21 16:52 UTC, waffle87 approved these changes

2024-11-22 08:27 UTC, dunk2k requested changes

2024-11-22 08:27 UTC, dunk2k commented on keyboards/handwired/cans12erv2/keyboard.json
> +                {"matrix": [0, 3], "x": 3, "y": 0},
denotes encoder location
```suggestion
                {"matrix": [0, 3], "x": 3, "y": 0, "encoder": 0},
```

2024-12-02 01:08 UTC, drashna requested changes

2024-12-02 01:08 UTC, drashna commented on keyboards/handwired/cans12erv2/keymaps/default/keymap.c
> +#include "keymap_german.h"
This isn't used here, so can/should be removed. 
```suggestion
```

2024-12-02 01:08 UTC, drashna commented on keyboards/handwired/cans12erv2/keymaps/default/keymap.c
> +#endif
```suggestion
#endif

```

2024-12-02 01:08 UTC, drashna commented on keyboards/handwired/cans12erv2/keymaps/default/rules.mk
> +ENCODER_MAP_ENABLE = yes
```suggestion
ENCODER_MAP_ENABLE = yes

```

2024-12-04 16:37 UTC, merged