ADD NCR80 ALPS SKFL/FR
qmk/qmk_firmware pull request #24625
Opened 2024-11-20 12:04 UTC by MaiTheSan

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-23 18:31 UTC, dunk2k requested changes

2024-11-23 18:31 UTC, dunk2k commented on keyboards/salane/ncr80alpsskfl/keyboard.json
> +        "LAYOUT": {
```suggestion
        "LAYOUT_all": {
```

2024-11-23 18:31 UTC, dunk2k commented on keyboards/salane/ncr80alpsskfl/keymaps/default/keymap.c
> +    [0] = LAYOUT(
```suggestion
    [0] = LAYOUT_all(
```

2024-11-23 18:31 UTC, dunk2k commented on keyboards/salane/ncr80alpsskfl/keymaps/default/keymap.c
> +};
```suggestion
};

```

2024-12-02 04:04 UTC, drashna approved these changes

2024-12-03 07:35 UTC, waffle87 approved these changes

2024-12-03 07:35 UTC, merged

2024-12-17 00:22 UTC, fauxpark commented
@MaiTheSan This board is missing some layouts. Please fix this.
```
⚠ salane/ncr80alpsskfl: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```