Add support for Starry FRL
qmk/qmk_firmware pull request #24626
Opened 2024-11-20 14:17 UTC by MaiTheSan

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-02 04:02 UTC, drashna approved these changes

2024-12-02 04:02 UTC, drashna requested changes

2024-12-02 04:02 UTC, drashna commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
> +#endif // ENCODER_MAP_ENABLE
```suggestion
#endif // ENCODER_MAP_ENABLE

```

2024-12-02 04:02 UTC, drashna commented on keyboards/salane/starryfrl/keymaps/default/rules.mk
> +ENCODER_MAP_ENABLE = yes
```suggestion
ENCODER_MAP_ENABLE = yes

```

2024-12-02 15:26 UTC, waffle87 requested changes

2024-12-02 15:26 UTC, waffle87 commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
> +    [_FN1] = LAYOUT(
This layer is not accessible.

2024-12-02 15:26 UTC, waffle87 commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
> +        _______, _______, _______, _______, _______, _______,                   _______,          _______,          _______, _______, _______, _______,               _______, _______, _______
Blank layers should be removed.
```suggestion
```

2024-12-02 15:26 UTC, waffle87 commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
> +};
```suggestion

enum {
    _BASE,
    _FN1
};
```

2024-12-02 15:26 UTC, waffle87 commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
> +    [_L3] = { ENCODER_CCW_CW(_______, _______) }
```suggestion
    [_FN1] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```

2024-12-02 15:26 UTC, waffle87 commented on keyboards/salane/starryfrl/readme.md
> +    make salane/starryfrl:default
```suggestion
    make salane/starryfrl:default

Flashing example for this keyboard:

    make salane/starryfrl:default:flash
```

2024-12-03 07:34 UTC, waffle87 approved these changes

2024-12-03 07:37 UTC, waffle87 commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
On second thought, you have RGB Light enabled, but no keycodes in the keymap to do anything useful with it?

2024-12-03 10:41 UTC, MaiTheSan commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
atm, RGB just need to bright, not doing anything special, if yes i'll add it later👌

2024-12-03 22:41 UTC, waffle87 commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
Right, but if a user wishes to turn it off, change the colour, brightness, effect, etc., they are unable to do so.

2024-12-04 16:55 UTC, drashna commented on keyboards/salane/starryfrl/keymaps/default/keymap.c
For reference, the default keymap is what is copied when a user creates a new keymap.  Keycodes like rgb control should be present, ideally.

2024-12-04 18:28 UTC, fauxpark requested changes

2024-12-04 18:28 UTC, fauxpark commented on keyboards/salane/starryfrl/keyboard.json
> +            "rgb_test": true,
```suggestion
```

2024-12-18 15:12 UTC, fauxpark approved these changes

2025-03-28 08:27 UTC, drashna approved these changes

2025-03-28 08:27 UTC, merged