Add support E8ghty
qmk/qmk_firmware pull request #24632
Opened 2024-11-22 16:36 UTC by trnthsn

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-23 18:19 UTC, dunk2k requested changes

2024-11-23 18:19 UTC, dunk2k commented on keyboards/trnthsn/e8ghty/info.json
> +    ],
1. remove `layout_aliases`; as it's not used in keymap(s)
2. tidy community layouts literal array
```suggestion
    "community_layouts": ["tkl_ansi_tsangan", "tkl_ansi_tsangan_split_bs_rshift", "tkl_f13_ansi_tsangan", "tkl_f13_ansi_tsangan_split_bs_rshift"],
```

2024-11-23 18:19 UTC, dunk2k commented on keyboards/trnthsn/e8ghty/config.h
> +#define WS2812_SPI_SCK_PIN B13
EoF tidy
```suggestion
#define WS2812_SPI_SCK_PIN B13

```

2024-11-23 18:19 UTC, dunk2k commented on keyboards/trnthsn/e8ghty/halconf.h
> +
EoF tidy
```suggestion
```

2024-11-23 18:19 UTC, dunk2k commented on keyboards/trnthsn/e8ghty/info.json
> +}
EoF tidy
```suggestion
}

```

2024-12-02 01:05 UTC, drashna approved these changes

2024-12-02 15:20 UTC, waffle87 approved these changes

2024-12-02 15:20 UTC, merged