Addition of OK-1
qmk/qmk_firmware pull request #24646
Opened 2024-11-27 13:12 UTC by Cipulot

## Description

Addition of the OK-1, a low profile switch keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-11-27 15:22 UTC, zvecr requested changes

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/config.h
> +#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
```suggestion
```

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/keyboard.json
> +        },
```suggestion
        },
        "default": {
            "animation": "rainbow_moving_chevron"
        },
```

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/keyboard.json
> +        "max_brightness": 255,
```suggestion
```

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/keymaps/default/keymap.c
> +
```suggestion
```

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/keymaps/default/keymap.c
> +    CMD = QK_KB_7
Most of these do not add value, as they already exist in core

Also, `QK_KB` keycode range should not be used at the keymap level.
```suggestion
    SNIP = SAFE_RANGE,
```

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/keymaps/default/keymap.c
> +        MACFN,      CTLR,    OPT,     CMD,                   KC_SPC,                        CMD,     OPT,     KC_LEFT, KC_DOWN, KC_RIGHT
```suggestion
        MACFN,      KC_LCTL, KC_LOPT,  KC_LCMD,                KC_SPC,                        KC_RCMD,  KC_ROPT,  KC_LEFT, KC_DOWN, KC_RIGHT
```

2024-11-27 15:22 UTC, zvecr commented on keyboards/cipulot/ok_1/keymaps/default/keymap.c
> +
```suggestion

#define MAC PDF(_MAC_BASE)
#define WIN PDF(_WIN_BASE)

#define MACFN MO(_MAC_FN)
#define WINFN MO(_WIN_FN)

```

2024-11-27 23:03 UTC, Cipulot commented
Updated the RGB keycodes to reflect the changes brought up by RGB Keycode Overhaul changes

2024-11-30 03:09 UTC, drashna commented on keyboards/cipulot/ok_1/keymaps/default/keymap.c
> +                    unregister_code(KC_LSFT);
```suggestion
                    tap_code16(LSFT(LGUI(KC_3)));
```

2024-11-30 03:14 UTC, Cipulot commented on keyboards/cipulot/ok_1/keymaps/default/keymap.c
> +                    unregister_code(KC_LSFT);
Applied, thanks for the suggestion 👍

2024-12-01 07:12 UTC, drashna approved these changes

2025-01-16 02:01 UTC, Cipulot commented
Still active, waiting for merge

2025-04-13 07:50 UTC, fauxpark approved these changes

2025-04-28 05:54 UTC, drashna approved these changes

2025-04-28 05:55 UTC, merged