Update keymap.c
qmk/qmk_firmware pull request #24704
Opened 2024-12-10 22:41 UTC by Lostdotfish

enhancement - power down indicator LEDs when host sleeps

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-10 23:14 UTC, waffle87 requested changes

2024-12-10 23:14 UTC, waffle87 commented on keyboards/lostdotfish/rp2040_orbweaver/keymaps/default/keymap.c
> +    layer_state_set_user(layer_state);
```suggestion
void suspend_wakeup_init_kb(void) {
    layer_state_set_kb(layer_state);
    suspend_wakeup_init_user();
```

2024-12-10 23:14 UTC, waffle87 commented on keyboards/lostdotfish/rp2040_orbweaver/keymaps/default/keymap.c
> +    gpio_write_pin_high(GP25);
```suggestion
    gpio_write_pin_high(GP25);
    suspend_power_down_user();
```

2024-12-11 08:47 UTC, Lostdotfish commented
changes tested locally and functionality confirmed - commits accepted (thank you)

2024-12-11 15:55 UTC, waffle87 approved these changes

2024-12-11 20:26 UTC, drashna approved these changes

2024-12-11 20:29 UTC, merged