[Keyboard] Add support S7venty Rev.2
qmk/qmk_firmware pull request #24718
Opened 2024-12-16 03:17 UTC by trnthsn

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-16 04:41 UTC, waffle87 commented on keyboards/trnthsn/s7ventyr2/keymaps/default/keymap.c
> +        ______,  ______,  ______,  ______,  ______,  ______,  ______,  ______,  UG_VALD, UG_NEXT
I suggest you test your code compiles prior to opening a PR.
```suggestion
        _______,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12, _______, _______,  _______,  _______, _______,
        _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______, _______, _______,  _______,  _______,
        _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,
        _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______, _______, UG_VALU,
        _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  UG_VALD, UG_NEXT
```

2024-12-16 04:41 UTC, waffle87 commented on keyboards/trnthsn/s7ventyr2/info.json
> +            "rgb_test": true,
```suggestion
```

2024-12-16 04:44 UTC, trnthsn commented on keyboards/trnthsn/s7ventyr2/info.json
> +            "rgb_test": true,
I removed "rgb_test" animation

2024-12-16 04:45 UTC, waffle87 commented on keyboards/trnthsn/s7ventyr2/keymaps/default/keymap.c
> +    [1] = LAYOUT(
This layer is not accessible.

2024-12-16 04:46 UTC, trnthsn commented on keyboards/trnthsn/s7ventyr2/keymaps/default/keymap.c
> +    [1] = LAYOUT(
i has pushed new commit

2024-12-16 22:36 UTC, fauxpark requested changes

2024-12-16 22:36 UTC, fauxpark commented on keyboards/trnthsn/s7ventyr2/rules.mk
Please delete this file.

2024-12-17 04:47 UTC, trnthsn commented on keyboards/trnthsn/s7ventyr2/rules.mk
is it posible to compile, if i removed this file. It cannot be built  
![image](https://github.com/user-attachments/assets/467a0b63-f502-4ff3-b55f-0aaae20aa25b)

2024-12-17 05:12 UTC, fauxpark commented on keyboards/trnthsn/s7ventyr2/rules.mk
Yes, you need to be more specific now.

2024-12-17 06:17 UTC, trnthsn commented on keyboards/trnthsn/s7ventyr2/rules.mk
i has removed rules.mk

2024-12-17 06:45 UTC, fauxpark commented on keyboards/trnthsn/s7ventyr2/rules.mk
You also removed the subrevisions? That's not what I meant.

2024-12-17 07:13 UTC, trnthsn commented on keyboards/trnthsn/s7ventyr2/rules.mk
i has push new commit @fauxpark

2025-05-06 02:12 UTC, closed without merging