Add Icebreaker keyboard
qmk/qmk_firmware pull request #24723
Opened 2024-12-16 17:05 UTC by SmollChungus

## Description
Addition of the Icebreaker, 65% PCB featuring encoder and per-key RGB.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Added support for Icebreaker PCB 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-16 18:18 UTC, waffle87 requested changes

2024-12-16 18:18 UTC, waffle87 commented on keyboards/icebreaker/hotswap/keyboard.json
Please run `qmk format-json` on this file.

2024-12-16 18:29 UTC, waffle87 approved these changes

2024-12-16 22:20 UTC, fauxpark requested changes

2024-12-16 22:20 UTC, fauxpark commented on keyboards/icebreaker/readme.md
> +    make ccebreaker:default
```suggestion
    make icebreaker:default
```
Everything under `hotswap/` should be moved up unless you plan a non-hotswap version.

2024-12-18 04:55 UTC, drashna requested changes

2024-12-18 04:55 UTC, drashna commented on keyboards/icebreaker/hotswap/keyboard.json
> +    "keyboard_name": "Serene Industries - Icebreaker HS",
```suggestion
    "keyboard_name": "Icebreaker HS",
```

2024-12-18 04:55 UTC, drashna commented on keyboards/icebreaker/hotswap/keyboard.json
> +                {"label": "encoder", "matrix": [3, 1], "x": 16, "y": 0},
```suggestion
                {"label": "encoder", "matrix": [3, 1], "x": 16, "y": 0, "encoder": 0},
```

2024-12-18 04:55 UTC, drashna commented on keyboards/icebreaker/hotswap/keyboard.json
> +}
```suggestion
}

```

2024-12-18 04:55 UTC, drashna commented on keyboards/icebreaker/hotswap/keymaps/default/keymap.c
> +#endif
```suggestion
#endif

```

2024-12-18 04:55 UTC, drashna commented on keyboards/icebreaker/hotswap/keymaps/default/keymap.c
> +    [1] =  { ENCODER_CCW_CW(RM_SATD, RM_SATU)  },
Nit:
```suggestion
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(RM_SATD, RM_SATU) },
```

2024-12-18 04:55 UTC, drashna commented on keyboards/icebreaker/hotswap/keymaps/default/rules.mk
> +ENCODER_MAP_ENABLE = yes
```suggestion
ENCODER_MAP_ENABLE = yes

```

2025-01-01 09:56 UTC, dunk2k commented
Thankfully this PR doesn't change existing code, I'd recommend changing the base (merge into) branch from `develop` to `master` 🙂

2025-01-18 03:47 UTC, fauxpark approved these changes

2025-03-09 08:50 UTC, drashna approved these changes

2025-03-09 08:51 UTC, merged