Add "Large Lad" keyboard
qmk/qmk_firmware pull request #24727
Opened 2024-12-18 06:01 UTC by Hyphen-ated

## Description
I designed and built an open source keyboard: https://github.com/Hyphen-ated/large-lad-keyboard

It runs on qmk.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* none

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-18 06:11 UTC, waffle87 requested changes

2024-12-18 06:11 UTC, waffle87 commented on keyboards/large_lad/config.h
This file should be removed and its contents migrated to `keyboard.json`.

2024-12-18 06:11 UTC, waffle87 commented on keyboards/large_lad/keyboard.json
> +        "nkro": true
```suggestion
        "nkro": true,
        "encoder": true
```

2024-12-18 06:11 UTC, waffle87 commented on keyboards/large_lad/keyboard.json
Please run `qmk format-json` on this file.

2024-12-18 06:11 UTC, waffle87 commented on keyboards/large_lad/keymaps/default/keymap.c
This file is missing a license header.

2024-12-18 06:11 UTC, waffle87 commented on keyboards/large_lad/keymaps/default/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
```

2024-12-18 06:38 UTC, Hyphen-ated commented on keyboards/large_lad/config.h
The qmk documentation for using encoders is at https://docs.qmk.fm/features/encoders

The second thing it says to do is add stuff to config.h. Is there a more up-to-date document somewhere I should be looking at?

2024-12-18 07:29 UTC, waffle87 commented on keyboards/large_lad/config.h
See [reference `info.json`](https://docs.qmk.fm/reference_info_json).

2024-12-18 07:45 UTC, waffle87 commented on keyboards/large_lad/keyboard.json
> +        "enabled": true,
This is already handled under `features.bootmagic`.
```suggestion
```

2024-12-18 07:45 UTC, waffle87 commented on keyboards/large_lad/keyboard.json
> +            {"pin_a": "B7", "pin_b": "A0", "resolution": 4}
This is the default value.
```suggestion
            {"pin_a": "B7", "pin_b": "A0"}
```

2024-12-18 07:45 UTC, waffle87 commented on keyboards/large_lad/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2024-12-18 08:04 UTC, Hyphen-ated commented
those three changes pass my manual testing

2025-02-02 03:48 UTC, Hyphen-ated commented
I believe this is awaiting a second review

2025-03-28 08:25 UTC, drashna approved these changes

2025-03-28 08:27 UTC, merged