Created SH1107 driver for quantum painter
qmk/qmk_firmware pull request #24724
Opened 2024-12-16 20:55 UTC by Steve973

Created a SH1107 driver for Quantum Painter based on the existing SH1106 driver.

This is a small/simple change, since SH1107 and SH1106 are quite similar.

2025-01-01 04:36 UTC, tzarc approved these changes

2025-01-01 04:37 UTC, tzarc commented
LGTM.

2025-01-01 06:32 UTC, drashna approved these changes

2025-01-01 22:31 UTC, drashna reviewed
Ideally, docs should be added too.

Tested on i2c, and works... but my SPI oled is fried :/

2025-01-07 10:26 UTC, sigprof commented on drivers/painter/sh1107/qp_sh1107.c
> +    }
Was this part actually tested with any displays smaller than 128×128?

I have a 0.96" 64×128 I2C OLED supposedly based on SH1107 (looks like the “0.96inch” version currently available at https://www.aliexpress.us/item/1005005235557472.html), and it needed the following code (when using the existing `sh1106` driver and replacing just the `qp_sh1106_init()` implementation):
```c
    // If the display width is anything other than the default 128 pixels, change SH1106_SET_MUX_RATIO data byte to the correct value.
    // Note that this part is specific to SH1107 (unlike SH1106 and SSD1306, the mux ratio affect columns instead of rows).
    if (oled->base.panel_width != 128) {
        sh1106_init_sequence[3] = oled->base.panel_width - 1;
    }

    // If the display width is less than the default 128 pixels, change SH1106_DISPLAY_OFFSET to use the center columns.
    // This is again SH1107-specific.
    if (oled->base.panel_width < 128) {
        sh1106_init_sequence[7] = (128U - oled->base.panel_width) / 2;
    }
```

2025-01-07 10:34 UTC, sigprof commented on drivers/painter/sh1107/qp_sh1107.c
> +    uint8_t framebuffer[SURFACE_REQUIRED_BUFFER_BYTE_SIZE(128, 128, 1)];
Having the framebuffer size hardcoded to the maximum looks wrong (even though the typical MCUs with which the QP code is used are usually not that resource restricted).

Options that I could think of:
1. Add some defines which could default to the maximum size, but could be reduced if desired.
2. Provide the buffer externally in `make_*_device` functions, similar to what #21844 does (but maybe with more error checking — e.g., pass the buffer size too, then check the passed size against the value calculated from the display dimensions).

Opinions?

2025-01-17 21:23 UTC, sigprof requested changes
Tested with a couple of (supposedly) SH1107 displays which I have currently (more may be coming in a couple of weeks):
- [1.5" 128×128 **SPI** OLED](https://www.aliexpress.us/item/1005004837617125.html?sku_id=12000042919990549) — works (note that this particular display has a somewhat weird pinout which does not match most other 7-pin 128×64 or 64×128 SPI OLEDs);
- [0.96" 64×128 I2C OLED](https://www.aliexpress.us/item/1005005235557472.html) (not really from that listing, but looks exactly like that, and the original listing disappeared since 2020) — works if the suggested changes are applied.

2025-01-17 21:23 UTC, sigprof commented on drivers/painter/sh1107/qp_sh1107.c
> +    }
```suggestion
    // If the display width is anything other than the default 128 pixels, change SH1107_SET_MUX_RATIO data byte to the correct value.
    if (driver->oled.base.panel_width != 128) {
        sh1107_init_sequence[3] = driver->oled.base.panel_width - 1;
    }

    // If the display width is less than the default 128 pixels, change SH1107_DISPLAY_OFFSET to use the center columns.
    if (driver->oled.base.panel_width < 128) {
        sh1107_init_sequence[7] = (128U - driver->oled.base.panel_width) / 2;
    }
```
This change makes the driver work with the 0.96" 64×128 I2C OLED supposedly based on SH1107 (looks  like https://www.aliexpress.us/item/1005004190135420.html, but the one I have had been purchased in 2020, and a new one and the 1.3" version https://www.aliexpress.us/item/1005005473564682.html are still in transit).  It also matches the datasheet (unlike SH1106, in SH1107 the COM pins are used as columns, therefore the mux ratio needs to be changed based on the panel width, not height; and column centering is used for most known displays which have width less than the maximum supported by the controller chip).

2025-02-16 20:09 UTC, sigprof reviewed
Looks like the only remaining concern is the framebuffer size which is hardcoded to the maximum possible size supported by the controller.

Do we accept the driver as it is (which also matches what the existing SH1106 driver does), and then add some way to reduce the RAM consumption for smaller displays later (updating all such drivers at the same time)?

2025-02-16 20:16 UTC, Steve973 commented
I tried to make it exactly like the 1106 driver, and only introduced the single change that is needed for 1107.  But I'm fine with whatever people think is best. If anyone else wants to handle any of the changes, then that's fine with me, too.  I submitted this because Drashna suggested that I should.

2025-02-16 21:40 UTC, tzarc commented
> Do we accept the driver as it is (which also matches what the existing SH1106 driver does), and then add some way to reduce the RAM consumption for smaller displays later (updating all such drivers at the same time)?

Given this isn't targeting AVR I'm not too concerned, so if you think it's necessary I'd suggest a follow-up PR.

2025-02-16 21:41 UTC, merged