Adding the Zeropad keyboard
qmk/qmk_firmware pull request #24737
Opened 2024-12-21 21:03 UTC by diffrentGuesser

Adding the Zeropad (3x3 costum keyboard) to the keyboards/handwired file and now updating to public

2024-12-23 13:39 UTC, zvecr requested changes

2024-12-23 13:39 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> +![handwired/zeropad](imgur.com image replace me!)
This section needs filling out

2024-12-23 14:56 UTC, zvecr requested changes

2024-12-23 14:56 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
This file needs to follow the [template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md), which it largely did before you removed the bulk of the content.

Only the section that was flagged needed to be updated.

2024-12-23 15:10 UTC, diffrentGuesser commented on keyboards/handwired/zeropad/readme.md
Ok, so I only need to put an image there?

2024-12-23 15:26 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> * Hardware Supported: *The PCBs, controllers supported*
> * Hardware Availability: *Links to where you can find this hardware*
>
> make %KEYBOARD%:default

I would suggest you review the contents of the file, and make the appropriate changes.

2024-12-23 19:10 UTC, diffrentGuesser commented on keyboards/handwired/zeropad/readme.md
I filled it out. Is it now suitable to merge? with best regards, Leon

2024-12-25 22:09 UTC, diffrentGuesser commented
I filled it out. Can it be merged now? Or are there any further changes that need to be made?

2025-01-03 20:05 UTC, diffrentGuesser commented
can it be merged. I think I did what i have to and if not please tell me what there is to do.

2025-01-17 22:44 UTC, diffrentGuesser commented
Good evening, I wanted to ask, if there are any futher changes I have to make, for it to be merged.
with best regards, Leon

2025-01-29 02:23 UTC, drashna commented on keyboards/handwired/zeropad/readme.md
> +![ZeroPad](https://github.com/user-attachments/assets/224aa55a-045b-4bb9-b6e9-34f092ced5c4)
This should be rehosted on imgur or a similar dedicated image hosting site, rather than github.

2025-02-05 07:55 UTC, lesieber commented on keyboards/handwired/zeropad/readme.md
> +![ZeroPad](https://github.com/user-attachments/assets/224aa55a-045b-4bb9-b6e9-34f092ced5c4)
ok thanks, I will change this

2025-02-07 23:09 UTC, diffrentGuesser commented on keyboards/handwired/zeropad/readme.md
> +![ZeroPad](https://github.com/user-attachments/assets/224aa55a-045b-4bb9-b6e9-34f092ced5c4)
I have now changed this to imgur as told.

2025-03-28 07:45 UTC, drashna requested changes

2025-03-28 07:45 UTC, drashna commented on keyboards/handwired/zeropad/keyboard.json
> +        "LAYOUT": {
```suggestion
    "community_layouts": [ "ortho_3x3" ],
    "layouts": {
        "LAYOUT_ortho_3x3": {
```

2025-03-28 07:45 UTC, drashna commented on keyboards/handwired/zeropad/keymaps/default/keymap.c
> +    [0] = LAYOUT(
```suggestion
    [0] = LAYOUT_ortho_3x3(
```

2025-05-12 20:23 UTC, diffrentGuesser commented
Is everything good to go? Or are there any further changes needed to be made, if I need to change something else, please inform me about it. Thanks for verifing my request.
with best regards, Leon

2025-05-12 21:26 UTC, zvecr requested changes

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/keyboard.json
> +    "url": "",
```suggestion
```

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/keyboard.json
> +        "console": false,
```suggestion
```

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> +ZeroPad:
```suggestion
```

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> +*This keyboard is inspired by the scotto9 from Joe Scotto. This keyboard is compatible with via and has 4 layers of keybinds (24 keybinds - 4x8 + 1 per layer for changing the layer).*
```suggestion
This keyboard is inspired by the scotto9 from Joe Scotto. This keyboard is compatible with via and has 4 layers of keybinds (24 keybinds - 4x8 + 1 per layer for changing the layer).

```

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> +
```suggestion
```

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> +
```suggestion
```

2025-05-12 21:26 UTC, zvecr commented on keyboards/handwired/zeropad/readme.md
> +  * Make sure you disconnect and reconnect the cable after shorting the pins.
```suggestion
Enter the bootloader in 3 ways:

* **Bootmagic reset**: Hold down the key at (0,0) in the matrix (the top left key) and plug in the keyboard 
* **Physical reset**: Short the GND and the RST pins on the Pro Micro.
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available
```

2025-05-13 16:16 UTC, zvecr approved these changes

2025-05-17 21:10 UTC, diffrentGuesser commented
I don't wanna be pushy, but I wanted to ask if I need to make any further adjustments for it to be merged?

2025-05-18 03:28 UTC, drashna approved these changes

2025-05-18 03:28 UTC, merged