Add Silakka54 keyboard
qmk/qmk_firmware pull request #24757
Opened 2024-12-29 13:28 UTC by Squalius-cephalus

## Description
Addition of the Silakka54, 54-key split keyboard.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-12-29 18:36 UTC, waffle87 requested changes

2024-12-29 18:36 UTC, waffle87 commented on keyboards/silakka54/config.h
> +
```suggestion
```

2024-12-29 18:36 UTC, waffle87 commented on keyboards/silakka54/keyboard.json
> +        "enabled": true
```suggestion
        "enabled": true,
        "serial": {
            "driver": "vendor"
        }
```

2024-12-29 18:36 UTC, waffle87 commented on keyboards/silakka54/rules.mk
This file can be removed.

2024-12-30 08:13 UTC, drashna commented on keyboards/silakka54/config.h
> +#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
```suggestion
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

```

2024-12-30 08:13 UTC, drashna commented on keyboards/silakka54/keyboard.json
> +        "console": false,
```suggestion
```

2024-12-30 23:07 UTC, drashna approved these changes

2025-01-02 12:07 UTC, waffle87 approved these changes

2025-01-02 12:07 UTC, merged