Improve the accuracy of waits on Chibios
qmk/qmk_firmware pull request #7124
Opened 2019-10-23 06:22 UTC by skullydazed

## Description

On Chibios `wait_us()` is currently not very accurate for small values. This changes to the method @zvecr identified.

This needs more testing before we roll it out.

## Types of Changes

- [x] Core
- [x] Bugfix

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2019-10-23 06:44 UTC, drashna commented on tmk_core/common/wait.h
> +#    define wait_ms(ms) chSysPolledDelayX(MS2RTC(STM32_SYSCLK, x))
```suggestion
#    define wait_ms(ms) chSysPolledDelayX(MS2RTC(STM32_SYSCLK, ms))
```

2019-10-23 06:45 UTC, drashna commented on tmk_core/common/wait.h
> +#    define wait_us(us) chSysPolledDelayX(US2RTC(STM32_SYSCLK, x))
```suggestion
#    define wait_us(us) chSysPolledDelayX(US2RTC(STM32_SYSCLK, us))
```

2019-10-23 07:00 UTC, skullydazed commented
Yup, the dangers of redoing PR's.

2019-10-23 07:15 UTC, drashna commented
Unfortunately, it looks like this is very dependant on the chibiOS config, which means changing all of the boards and hoping it works.

2019-10-23 10:36 UTC, zvecr commented
@drashna got any specifics of scenarios this wont work for? And what parts of config its dependent on?

2019-10-23 10:42 UTC, zvecr commented on tmk_core/common/wait.h
>  #    include "ch.h"
Had to add the following to get it to work with my serial PR.
```suggestion
#    include "ch.h"
#    include "hal.h"
```

2019-10-23 15:34 UTC, drashna commented
@zvecr Just travis.

2019-10-23 15:47 UTC, zvecr commented
@drashna not sure what you mean about travis, i was referring to:
>  it looks like this is very dependant on the chibiOS config, which means changing all of the boards and hoping it works

Though i havent vastly tested systick vs tickless right now, i have gone f303 with tickless and f103 with systick and both give the expected result for `wait_us` timings.

2019-10-23 15:56 UTC, drashna commented
Well, right now, Travis is erroring out on every F072 chip, and every Kinesis chip (Teensy ARM).

2019-10-23 16:16 UTC, zvecr commented
Yeah teensy looks like its going to be a bit more of a pain, and f072 is something to do with `PORT_SUPPORTS_RT`. I have some test hardware so will have a tinker.

2019-10-23 19:57 UTC, drashna commented
Checking the makefile stuff, there isn't really anything that we could use to ID the chips right now. 

However, we could add something to this block: 
https://github.com/qmk/qmk_firmware/blob/68cf2725aa30eaa18db9c6149e5e361860db01d7/tmk_core/common.mk#L32-L57

That would at least give us a decent way to identify the MCU, and base the handling on that.

2019-10-23 20:38 UTC, skullydazed commented
We're setting `MCU = STM32F303` in `rules.mk`. Could we use that to identify the MCU?

2019-10-24 20:52 UTC, drashna commented
In makefiles, yes.  But I don't think we're setting a define for it.  At least not that I could find

2019-10-24 21:23 UTC, zvecr commented
We do the following in the ARM I2C driver
https://github.com/qmk/qmk_firmware/blob/e8453bbc1218a2cb40d4eac6cb543bd0c45d3de9/drivers/arm/i2c_master.h#L30-L32

2019-10-24 22:13 UTC, drashna commented
@zvecr We have that, but I don't see where those are actually defined.   I know whe have: `EEPROM_EMU_STM32F303xC` and the like, but not ... those. 

We'd need to add something like:
```
TMK_COMMON_DEFS += -D$(MCU_FAMILY)
```
(assuming this even works)

2019-10-24 23:38 UTC, zvecr commented
The i2c stuff works fine, I've tested it. it's using the chibios board.h defines.

2019-10-25 06:04 UTC, drashna commented
Aah, okay, it's defined a lot deeper into the chibiOS submodule, which is why I wasn't finding it. 

And yeah, it is defined by the HAL files in chibiOS.   So should definitely be fine to use. 


Specifically in:
```
lib/chibios/os/hal/ports/STM32/(mcu)/hal_lld.h
```

2020-11-09 20:35 UTC, tzarc requested changes

2020-11-09 20:35 UTC, tzarc commented on tmk_core/common/wait.h
> +#    define wait_us(us) chSysPolledDelayX(US2RTC(STM32_SYSCLK, us))
```suggestion
#    define wait_ms(ms) chSysPolledDelayX(TIME_MS2I(ms))
#    define wait_us(us) chSysPolledDelayX(TIME_US2I(us))
```

2021-10-30 22:22 UTC, tzarc commented
Removed "on hold" so stalebot can eventually close this.

2022-05-14 22:43 UTC, closed without merging