miles2go userspace  update, add functions for babblepaste library, add prime_e keybard keymap
qmk/qmk_firmware pull request #9196
Opened 2020-05-25 18:51 UTC by milestogo

## Description
Update miles2go userspace c functions and #defines

Add a prime_e keyboard synced to this version of the userspace updates. 

Cleanups in the babblepaste library - now has callback functions for babble_modeswitch_kb/user that are called when the babble mode changes. This makes it easier to have per-keyboard LED indicators. 
Added new feature to swap 2-3 keys when the mode changes, so that the most ergonomic position for cut & paste can be preserved across OSes. 

## Types of Changes
- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [X ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [X ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-07-28 06:00 UTC, drashna commented on keyboards/primekb/prime_e/keymaps/milestogo/config.h
> +#define DESCRIPTION     Ergo_45
You should need all of this, as it's already there, and doesn't appear to be changed. 

```suggestion
```

2021-02-12 20:37 UTC, spidey3 requested changes
Sorry for the long delay looking at your PR. I've made a few suggestions, but mostly it looks good.

2021-02-12 20:37 UTC, spidey3 commented on keyboards/primekb/prime_e/keymaps/milestogo/keymap.c
> +};
You may want to wrap these to match the actual layout.  It looks like cformat removed any newlines. That can be prevented by putting `// clang-format off` before the code where you want the formatting preserved, and `// clang-format on` after it.

2021-02-12 20:37 UTC, spidey3 commented on keyboards/primekb/prime_e/keymaps/milestogo/keymap.c
> +}
Both of these do nothing; perhaps they should be removed?
```suggestion
```

2021-02-14 02:19 UTC, spidey3 approved these changes

2021-02-14 03:02 UTC, drashna commented on keyboards/primekb/prime_e/keymaps/milestogo/keymap.c
> +    }
```suggestion
    writePin(B1, layer_state_cmp(state, _CDH));
```

2021-02-14 05:22 UTC, milestogo commented on keyboards/primekb/prime_e/keymaps/milestogo/keymap.c
> +    }
that's nifty! Thanks.

2021-02-18 20:35 UTC, spidey3 approved these changes

2021-03-14 19:23 UTC, drashna approved these changes

2021-03-14 19:23 UTC, merged