Add crkbd keymap by manna harbour
qmk/qmk_firmware pull request #9461
Opened 2020-06-18 06:55 UTC by manna-harbour

This keymap includes crkbd-specific hardware feature support.  It provides easy
selection of the following:

- hotswap trackpoint module in OLED port, or OLED with new or old drivers
- automatic mouse buttons layer activation on trackpoint movement
- keyboard-side mouse acceleration, or low rates for use with host-side
  acceleration
- static image display, or use as caps lock indicator
- built-in logo, or image from data file, with automatic rotation
- automatic conversion of image files
- matrix, light, or underglow RGB

It imports miryoku, an ergonomic, minimal, orthogonal layout for ergo or ortho
keyboards.

## Description

This PR depends on the following open PRs:
- #8805 "Add movement hook to ps2_mouse" to build with make argument MH_AUTO_BUTTONS=yes
- #9124 "Fix sharing of mouse button state from mousekeys to ps2_mouse" to eliminate extra mouse button clicks when building with make argument MH_AUTO_BUTTONS=yes 
- #9442 "Update miryoku" to build with the default imported keymap

This PR provides solutions or work-arounds for the following closed issues:
- #1925 "[Question] Possibility to auto-switch layers when using trackpoint?" by building with make argument MH_AUTO_BUTTONS=yes
- #5982 "OLED doesn't turn off after timeout" with default macro MH_OLED_TIMEOUT
- #6594 "split keyboard halves in different state, can't reset" with default macro MH_RGB_TOGGLE_OFF

This PR provides enhancements to the following closed PRs:
- #4151 "Update logo and commonize it" by including a full size corne logo with make argument MH_OLED_IMAGE=corne.c
- #7237 "Added oled_write_raw and oled_write_raw_P functions to the OLED driver" by providing automatic conversion of image files with make argument MH_OLED_IMAGE=image.c
- #7535 "[keymap] Display logo for caps lock indication on crkbd using old OLED driver" by supporting the new OLED driver and arbitrary images with make arguments MH_MODULE=oled and MH_OLED_IMAGE=image.c
- #9142 "Add shift-to-disable to RGB_TOG keycode" by providing a keymap-level work around with default macro MH_RGB_TOGGLE_OFF

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-06-23 07:16 UTC, manna-harbour commented
As #9442 has been merged this will now build with the default configuration.  #8805 is still required to build with other options as described.

2020-07-02 22:49 UTC, manna-harbour commented
All of the prerequisite PRs have now been merged and this is now ready for review.  Thanks!

2020-07-12 23:19 UTC, manna-harbour commented
Thanks @drashna!

2021-07-14 04:24 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/keymap.c
> +#endif
Ideally, the `SSD1306OLED` code shouldn't be used, at all. Instead, the oled driver feature should be used in its placen

2021-11-05 02:47 UTC, tzarc commented
Can we also get GPL2+ compatible copyright headers on all source files, please?

2021-11-05 16:58 UTC, drashna requested changes

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/config.h
> +// https://github.com/manna-harbour/qmk_firmware/blob/crkbd/keyboards/crkbd/keymaps/manna-harbour/readme.org
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/config.h
> +  #define RGB_DISABLE_WHEN_USB_SUSPENDED true
```suggestion
  #define RGB_DISABLE_WHEN_USB_SUSPENDED
```

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/config.h
> +  #define RGBLIGHT_ANIMATIONS
Could you explicitly define which animations are enabled? 
```suggestion
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
```

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/keymap.c
> +// https://github.com/manna-harbour/qmk_firmware/blob/crkbd/keyboards/crkbd/keymaps/manna-harbour/readme.org
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/keymap.c
> +#endif
```suggestion
```

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/keymap.c
> +#if defined OLED_DRIVER_ENABLE
```suggestion
#if defined OLED_ENABLE
```

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/keymap.c
> +#endif // defined SSD1306OLED
```suggestion
```

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/rules.mk
> +ifeq ($(strip $(MH_MODULE)), trackpoint)
All of this should probably go in `post_rules.mk`

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/mh_images/converted/corne.c
> +// https://github.com/manna-harbour/qmk_firmware/blob/crkbd/keyboards/crkbd/keymaps/manna-harbour/readme.org
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2021-11-05 16:58 UTC, drashna commented on keyboards/crkbd/keymaps/manna-harbour/mh_images/converted/qmk.c
> +// https://github.com/manna-harbour/qmk_firmware/blob/crkbd/keyboards/crkbd/keymaps/manna-harbour/readme.org
Could you add a GPL2+ compatible license header here? 

For instance:
```c
// Copyright 2021 Your Name (@yourgithub)
// SPDX-License-Identifier: GPL-2.0-or-later
```

Or 

https://github.com/qmk/qmk_firmware/blob/6b299fab6e6a3143c061b9ea005253361fcd524b/data/templates/base/keyboard.c#L1-L15

2022-10-06 09:59 UTC, keyboard-magpie commented
@manna-harbour in the spirit of tidying up, does this PR still need to remain open, or does your current mechanism fulfil all needs? IMO the latter is true.

2022-10-07 02:47 UTC, manna-harbour commented
Thanks @drashna and @tzarc for the review. 

This PR is now very out of date, and I've found a different method of adding custom code to any keymap at https://github.com/manna-harbour/qmk_firmware/issues/40, which should be much better than the `USER_NAME` method used here. The features from this PR will be added there in future, and I'll be sure to incorporate your feedback from this PR at that time.

As an aside, there was 12 months between @drashna's original approval and request for review, and the next review. There may be an issue with the use of the `awaiting review` label, as it suppresses the stale action, which seems to be the only automated reminder for PRs needing attention. Perhaps an `awaiting review` reminder action is also needed?

Thanks @keyboard-magpie for the reminder. The Miryoku [customisation](https://github.com/manna-harbour/miryoku/discussions/85) method is separate from this, but even so, this PR is now obsolete. Closing now.

2022-10-07 02:47 UTC, closed without merging