Adds support for XD84 Pro
qmk/qmk_firmware pull request #9750
Opened 2020-07-18 11:30 UTC by katawajojo

Adds QMK support for KPRepublic's XD84 Pro PCB.
Includes ANSI, ISO, and VIA (ANSI layout only currently) Support.

## Description

Adds support for KPRepublic's XD84 Pro PCB.
The PCB's silkscreen refers to this board as "XD84 v2.0"

I've also created a VIA pull request as well.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-07-18 12:40 UTC, fauxpark commented on keyboards/xd84pro/info.json
> +            "key_count": 84,
```suggestion
```

2020-07-18 12:40 UTC, fauxpark commented on keyboards/xd84pro/info.json
> +            "key_count": 85,
```suggestion
```

2020-07-18 12:41 UTC, fauxpark commented on keyboards/xd84pro/keymaps/via/rules.mk
> +VIA_ENABLE = yes
```suggestion
VIA_ENABLE = yes
LTO_ENABLE = yes
```

2020-07-18 12:41 UTC, fauxpark commented on keyboards/xd84pro/readme.md
> +Hardware Availability: [KPrepublic](https://kprepublic.com/products/xd84pro-xd84-pro-custom-mechanical-keyboard-kit-75-supports-tkg-tools-support-underglow-rgb-pcb-programmed-gh84-kle-type-c)
```suggestion
* Keyboard Maintainer: QMK Community
* Hardware Supported: XD84 Pro
* Hardware Availability: [KPrepublic](https://kprepublic.com/products/xd84pro-xd84-pro-custom-mechanical-keyboard-kit-75-supports-tkg-tools-support-underglow-rgb-pcb-programmed-gh84-kle-type-c)
```

2020-07-18 12:42 UTC, fauxpark commented on keyboards/xd84pro/readme.md
> +    make xd84pro:default:dfu
```suggestion
Flashing example for this keyboard:

    make xd84pro:default:flash
```

2020-07-18 12:42 UTC, fauxpark commented on keyboards/xd84pro/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-07-18 12:42 UTC, fauxpark commented on keyboards/xd84pro/rules.mk
> +HD44780_ENABLE = no         # Enable support for HD44780 based LCDs
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-07-18 12:45 UTC, fauxpark commented on keyboards/xd84pro/xd84pro.c
> +}
```suggestion
void keyboard_pre_init_kb(void) {
    led_init_ports();
    keyboard_pre_init_user();
}

void led_init_ports(void) {
    setPinOutput(B2);
}

bool led_update_kb(led_t led_state) {
    if (led_update_user(led_state)) {
        writePin(B2, !led_state.caps_lock);
    }

    return false;
}
```

2020-07-18 12:55 UTC, katawajojo commented
Thanks for the suggestions, I’ll take care of them when I wake up in the morning.

2020-07-18 20:17 UTC, sigprof commented
You should make a `LAYOUT_all` macro (and the corresponding entry in info.json) which includes all possible key positions. At the moment there are two missing parts:

1. According to the vendor documentation ([1](https://ae01.alicdn.com/kf/H6aa7f4160b55408facb8bde2f64a31bcI.jpg), [2](https://ae01.alicdn.com/kf/H9b653564abec4419825214f93ffc675aZ.jpg)), this PCB supports splitting the 2U Backspace key into 2×1U keys. You should figure out the matrix positions of those keys (one of them probably occupies some of remaining positions on the last row, the other is most likely the same as the 2U Backspace) and add them to `LAYOUT_all`.

2. This PCB, like other XD* PCBs, not just has three distinct matrix positions for the ANSI backslash, ISO NUHS and Enter, but actually supports installing 1U+1.25U keys in the place normally occupied by the 2.25U ANSI Enter. Again, you should check how those matrix positions are connected (although in this case the fact that the 1.25U part of ANSI Enter is connected in parallel to the normal ANSI Enter pads is even visible [on this shop photo](https://ae01.alicdn.com/kf/H4456b675111a4588a6e1f9e83bfc5b3em.jpg)), and add all those 3 keys to `LAYOUT_all`.

The rest of `LAYOUT_all` should be the same as `LAYOUT_75_iso` (so that the NUBS key would be present).

After adding this `LAYOUT_all` macro you should use it in the `via` keymap to make a layout which could work for both ISO and ANSI out of the box (this should be possible on this PCB, even the ANSI backslash and ISO NUHS could be made distinct). For the split Backspace you could just assign `KC_BSPC` to both halves of the 2U Backspace.

2020-09-04 14:40 UTC, Popkornium18 commented
@katawajojo are you still planning to make the requested changes? If not I might give it a go, since I picked up this board thinking it was supported :facepalm:

2020-09-05 01:48 UTC, katawajojo commented
Sorry! I've been working on these changes, but I've also been hella busy with school coming up and work. Give me like, a day or two to finish these up, and update the pull.

2020-09-05 10:06 UTC, katawajojo commented
Okay, so I'm going to remove the VIA stuff for now, as I need to do some research on doing that all properly. I have every layout mapped and ready, I'm just not sure how to go about properly creating the `LAYOUT_all` macro.

Side note: this keyboard has a backlighting issue that's resolved with the pull request #9575. Applying the code from this pull request fixes the flickering backlight.

Attached is the matrix layout for all keys, and all supported configurations of the board.

2020-09-05 16:10 UTC, Popkornium18 commented
> Side note: this keyboard has a backlighting issue that's resolved with the pull request #9575. Applying the code from this pull request fixes the flickering backlight.

It doesn't fix the problem for me :thinking:

2020-09-05 22:03 UTC, katawajojo commented
> > Side note: this keyboard has a backlighting issue that's resolved with the pull request #9575. Applying the code from this pull request fixes the flickering backlight.
> 
> 
> 
> It doesn't fix the problem for me :thinking: 

Odd, as this fixed the flickering issue on both XD84 Pro boards I have.

2020-09-07 01:43 UTC, drashna approved these changes

2020-09-07 12:58 UTC, Popkornium18 commented
> Side thought: Do you have the RGB underglow cycling through effects at all? or is it just a solid color and brightness?
No I was using the cycling effect. With the underglow disabled the flickering goes away. :thinking:

2020-09-07 15:07 UTC, katawajojo commented
> > Side thought: Do you have the RGB underglow cycling through effects at all? or is it just a solid color and brightness?
> 
> 
> 
> No I was using the cycling effect. With the underglow disabled the flickering goes away. :thinking: 

Okay, yeah, underglow effects can still cause issues with backlight flickering. If you read through that pull request, it mentions this. Iirc, this is just a bug within QMK itself.

2020-09-12 16:01 UTC, fauxpark requested changes

2020-09-12 16:01 UTC, fauxpark commented on keyboards/xd84pro/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-09-12 22:14 UTC, katawajojo commented on keyboards/xd84pro/config.h
> +#define PRODUCT_ID      0x8484
I used the original IDs for this board. Is there a reason for this change? Just out of curiosity.

2020-09-13 03:49 UTC, fauxpark commented on keyboards/xd84pro/config.h
> +#define PRODUCT_ID      0x8484
It matches the other XD boards.

2020-09-13 10:38 UTC, katawajojo commented
There we go, accepted those changes. I'll also have to change that info for the VIA request as well, to match the vendor ID and the product ID, however.

2020-09-18 16:21 UTC, fauxpark requested changes
Looks good, just waiting on the USB ID changes and VIA keymap.

2020-09-26 01:53 UTC, noroadsleft requested changes

2020-09-26 01:53 UTC, noroadsleft commented on keyboards/xd84pro/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
Could we get a license header here?

Here's a sample one:

https://github.com/qmk/qmk_firmware/blob/4a83021fe0d07888e0e3bf161882c4ab7221a4a6/quantum/template/base/keymaps/default/keymap.c#L1-L15

2020-09-26 01:53 UTC, noroadsleft commented on keyboards/xd84pro/keymaps/default_iso/keymap.c
> +#include QMK_KEYBOARD_H
And a license header here too.

2020-10-17 16:53 UTC, fauxpark commented
@katawajojo any updates on this? We're still missing the VIA keymap, but other than that and noroads' review above, I think this is good to go.

2020-10-17 16:57 UTC, katawajojo commented
I've been extra busy lately with work and school. I'm working on trying to make that VIA keymap, and adding the extra bottom row configurations. Thankfully, I have nothing but free time today, so I should be able to knock everything out.

2020-10-26 02:55 UTC, katawajojo commented
Okay, I've got everything ready, but I'm not 100% sure on making the new VIA .json file. If anyone can help out with that, that would be SUPER helpful. However, for now, everything should be ready to go. I'm gonna test before pushing.

Once again, sorry for the extremely long wait time, life's gotten extra busy on me lately.

2020-10-29 18:09 UTC, katawajojo commented
Okay, this should be everything. I'm getting the VIA json cleaned up for the pull request over there as well, but this should be everything needed for over here. I've tested this with my own PCB and everything seems to check out fine. I'm not sure what's failing in the Lint though.

2020-10-29 18:16 UTC, fauxpark requested changes

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/info.json
> +            "key_count": 87,
```suggestion
```

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/rules.mk
> +LAYOUTS = 75_all 75_ansi 75_iso
```suggestion
LAYOUTS = 75_ansi 75_iso
```

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/xd84pro.h
> +#define LAYOUT_75_all( \
```suggestion
#define LAYOUT_all( \
```

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/keymaps/via/keymap.c
> +  [0] = LAYOUT_75_all(
```suggestion
  [0] = LAYOUT_all(
```

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/keymaps/via/keymap.c
> +  [1] = LAYOUT_75_all(
```suggestion
  [1] = LAYOUT_all(
```

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/keymaps/via/keymap.c
> +  [2] = LAYOUT_75_all(
```suggestion
  [2] = LAYOUT_all(
```

2020-10-29 18:16 UTC, fauxpark commented on keyboards/xd84pro/keymaps/via/keymap.c
> +  [3] = LAYOUT_75_all(
```suggestion
  [3] = LAYOUT_all(
```

2020-10-29 18:20 UTC, fauxpark requested changes

2020-10-29 18:20 UTC, fauxpark commented on keyboards/xd84pro/info.json
> +            "key_count": 84,
```suggestion
```

2020-10-29 18:20 UTC, fauxpark commented on keyboards/xd84pro/info.json
> +            "key_count": 85,
```suggestion
```

2020-10-29 18:22 UTC, katawajojo commented
For future knowledge, should I forgo using "key_count" in the info.json?

2020-10-29 18:23 UTC, fauxpark commented
Yep. It's not really necessary as you can just count the number of elements in the `layout` array.

2020-10-29 18:24 UTC, katawajojo commented
> Yep. It's not really necessary as you can just count the number of elements in the `layout` array.

Huh! I never thought about that. Good to know, thanks! c:

2020-10-29 18:28 UTC, fauxpark requested changes
Whoops, one last thing then I think this is good to go.

2020-10-29 18:28 UTC, fauxpark commented on keyboards/xd84pro/info.json
> +        "LAYOUT_75_all": {
```suggestion
        "LAYOUT_all": {
```

2020-10-29 18:29 UTC, fauxpark approved these changes

2020-10-30 15:29 UTC, katawajojo commented
I also just updated the VIA .json file and updated the VIA pull request as well. This should complete the VIA and QMK port for this PCB.

2020-11-04 00:22 UTC, katawajojo commented
Any update on this?

2020-11-04 00:39 UTC, fauxpark commented
Thanks!

2020-11-04 00:39 UTC, merged