Adding several community hand-wired dactyl manuform variants and wiring, as well as keymaps.
qmk/qmk_firmware pull request #9882
Opened 2020-07-30 16:56 UTC by Lhun

## Description
-adding personal and /r/mk community keymap examples,
        - Lhun keymap is for the fbr layout variant 5x6 by /u/brownelvis from r/mechanicalkeyboards
	- c# and にほんご friendly, reintroduces KC_LBRC KC_RBRC, LALT, LGUI, DEL and PLUS
　　 - inclusion of KC_MHEN,KC_HENK for microsoft ime jp 106+
	- _RAISE layer includes RALT for f-combo purposes
	- swapped sides for raise and lower to be windows combo aware

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-09-03 16:29 UTC, noroadsleft requested changes

2020-09-03 16:29 UTC, noroadsleft commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis/keymap.c
> +    _BASE,
This is preventing the keymap from compiling.

```suggestion
    _QWERTY,
```

2020-09-04 03:10 UTC, noroadsleft requested changes
1. Please ensure all `.c` and `.h` files have license headers.
2. The layout macros added to `keyboards/handwired/dactyl_manuform/5x6/5x6.h` should have their layout data added to `keyboards/handwired/dactyl_manuform/5x6/info.json` as well.

2020-09-06 21:53 UTC, drashna approved these changes

2020-09-06 22:43 UTC, fauxpark requested changes

2020-09-06 22:43 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis/rules.mk
> +RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
```suggestion
AUDIO_ENABLE = no           # Audio output
BLUETOOTH_ENABLE = no       # Enable Bluetooth
RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
```

2020-09-06 22:43 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis/rules.mk
> +#   the appropriate keymap folder that will get included automatically
```suggestion
#   change yes to no to disable
```

2020-09-06 22:43 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis-3thumbkeys/rules.mk
> +RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
```suggestion
AUDIO_ENABLE = no           # Audio output
BLUETOOTH_ENABLE = no       # Enable Bluetooth
RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
```

2020-09-06 22:43 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis-3thumbkeys/rules.mk
> +#   the appropriate keymap folder that will get included automatically
```suggestion
#   change yes to no to disable
```

2020-09-06 22:43 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/4x6/keymaps/brownelvis/keymap.c
> +                                            _______,_______,    _______,_______                                    \
```suggestion
[_BASE] = LAYOUT(
    KC_ESC,  KC_Q,  KC_W,   KC_E,   KC_R,   KC_T,               KC_Y,   KC_U,   KC_I,   KC_O,   KC_P,   KC_MINS,
    KC_TAB,  KC_A,  KC_S,   KC_D,   KC_F,   KC_G,               KC_H,   KC_J,   KC_K,   KC_L,   KC_SCLN,KC_QUOT,
    KC_LSFT, KC_Z,  KC_X,   KC_C,   KC_V,   KC_B,               KC_N,   KC_M,   KC_COMM,KC_DOT, KC_SLSH,KC_BSLASH,
                    KC_LBRC,KC_RBRC,                                            KC_PLUS,KC_EQL,
                                    RAISE,  KC_SPC,             KC_ENT, LOWER,
                                    KC_TAB, KC_HOME,            KC_END, KC_DEL,
                                    KC_BSPC,KC_GRV,             KC_LGUI,KC_LALT
),

[_LOWER] = LAYOUT(
    _______,_______,_______,_______,_______,KC_LBRC,            KC_RBRC, KC_P7, KC_P8,  KC_P9,  RESET,  KC_PLUS,
    _______,KC_HOME,KC_PGUP,KC_PGDN,KC_END ,KC_LPRN,            KC_RPRN, KC_P4, KC_P5,  KC_P6,  KC_MINS,KC_PIPE,
    _______,_______,_______,_______,_______,_______,            _______, KC_P1, KC_P2,  KC_P3,  KC_EQL, KC_UNDS,
                                            _______,KC_PSCR,    _______, KC_P0,
                                            _______,_______,    _______,_______,
                                            _______,_______,    _______,_______,
                                            _______,_______,    _______,_______
),

[_RAISE] = LAYOUT(
    _______,RESET,  _______,_______,_______,KC_LBRC,            KC_RBRC,_______,KC_NLCK,KC_INS, KC_SLCK,KC_MUTE,
    _______,KC_LEFT,KC_UP  ,KC_DOWN,KC_RGHT,KC_LPRN,            KC_RPRN,KC_MPRV,KC_MPLY,KC_MNXT,_______,KC_VOLU,
    _______,_______,_______,_______,_______,_______,            _______,_______,_______,_______,_______,KC_VOLD,
                                            _______,_______,    KC_EQL, _______,
                                            _______,_______,    _______,_______,
                                            _______,_______,    _______,_______,
                                            _______,_______,    _______,_______
```

2020-10-01 03:44 UTC, fauxpark requested changes

2020-10-01 03:44 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis-fbr/keymap.c
> +     OSM(MOD_LCTL),KC_LGUI,OSM(MOD_LALT),OSL(LOWER), KC_DEL, LOWER,           RAISE, KC_BSPC, OSL(RAISE), KC_LEFT, KC_DOWN, KC_RIGHT,
```suggestion
     OSM(MOD_LCTL),KC_LGUI,OSM(MOD_LALT),OSL(LOWER), KC_DEL, LOWER,           RAISE, KC_BSPC, OSL(RAISE), KC_LEFT, KC_DOWN, KC_RIGHT,
```

2020-10-01 03:44 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/brownelvis/keymap.c
> +                                      TG(LOWER), KC_LGUI,                     KC_HOME, KC_END
```suggestion
                                      TG(LOWER), KC_LGUI,                     KC_HOME, KC_END
```

2020-10-01 03:44 UTC, fauxpark commented on keyboards/handwired/dactyl_manuform/5x6/keymaps/lhun-fbr/keymap.c
> +     KC_LGUI, KC_LALT,KC_LBRC,KC_RBRC, RAISE, KC_SPC,                        KC_BSPC, LOWER ,KC_PLUS, KC_LEFT, KC_DOWN, KC_RIGHT,
```suggestion
     KC_LGUI, KC_LALT,KC_LBRC,KC_RBRC, RAISE, KC_SPC,                        KC_BSPC, LOWER ,KC_PLUS, KC_LEFT, KC_DOWN, KC_RIGHT,
```

2020-12-15 19:54 UTC, closed without merging