add otakusplit v1.1 and update default kemap, support via
qmk/qmk_firmware pull request #9994
Opened 2020-08-10 15:38 UTC by takashiski

change SPLIT_HAND_PIN to EEHAND

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-08-18 12:36 UTC, takashiski commented
Hi, I fix and update checklist.

2020-08-20 12:15 UTC, takashiski commented
@drashna @fauxpark @zvecr @noroadsleft
Would you this pullrequest?

2020-08-23 23:00 UTC, drashna commented on keyboards/otaku_split/ver1/keymaps/via/keymap.c
> +			KC_LCTRL, KC_LGUI,KC_LALT,KC_MHEN,KC_TRNS,KC_SPC,KC_SPC,        KC_TRNS,KC_TRNS,KC_TRNS,KC_HENK,KC_TRNS,KC_LEFT,KC_DOWN,KC_RIGHT
```suggestion
    BASE,
    CURSOR
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT(
      KC_ESC, KC_1,  KC_2,  KC_3,  KC_4,  KC_5,  KC_6,             KC_6, KC_7,  KC_8,  KC_9,  KC_0,  KC_MINUS  ,KC_EQL,KC_JYEN,KC_BSPC,
      KC_TAB,   KC_Q,  KC_W,  KC_E,  KC_R,  KC_T,  KC_Y,      KC_Y,  KC_U,  KC_I,  KC_O,  KC_P,  KC_LBRC,KC_RBRC,KC_ENT,
      KC_CAPS,  KC_A,  KC_S,  KC_D,  KC_F,  KC_G,                    KC_H,  KC_J,  KC_K,  KC_L,  KC_SCLN,  KC_QUOT,KC_NUHS,
      KC_LSHIFT,KC_Z,  KC_X,  KC_C,  KC_V,  KC_B,             KC_B,  KC_N,  KC_M,  KC_COMM, KC_DOT, KC_SLASH,KC_RO,KC_RSHIFT,
      KC_LCTRL, KC_LGUI,KC_LALT,KC_MHEN,LT(CURSOR,KC_DEL),KC_SPC,KC_SPC,        LT(CURSOR,KC_SPC),LT(CURSOR,KC_ENT),LT(CURSOR,KC_BSPC),KC_HENK,LT(CURSOR,KC_KANA),KC_RALT,KC_APP,KC_RCTRL
  ),
  [CURSOR] = LAYOUT(
      KC_GRAVE, KC_F1,  KC_F2,  KC_F3,  KC_F4,  KC_F5,  KC_F6,             KC_F6, KC_F7,  KC_F8,  KC_F9,  KC_F10,  KC_F11,  KC_F12,  KC_JYEN,KC_DEL,
      KC_TAB,   KC_Q,  KC_UP,  KC_E,  KC_R,  KC_T,  KC_Y,      KC_Y,  KC_U,  KC_I,  KC_O,  KC_P,  KC_LBRC,KC_RBRC,KC_PSCR,
      KC_ESC,  KC_LEFT,  KC_DOWN,  KC_RIGHT,  KC_F,  KC_G,                    KC_LEFT,  KC_DOWN,  KC_UP,  KC_RIGHT,  KC_SCLN,  KC_QUOT,KC_NUHS,
      KC_LSHIFT,KC_HOME,  KC_END,  KC_PGUP,  KC_PGDN,  KC_INSERT,             KC_B,  KC_N,  KC_M,  KC_COMM, KC_DOT, KC_END,KC_UP,KC_HOME,
      KC_LCTRL, KC_LGUI,KC_LALT,KC_MHEN,KC_TRNS,KC_SPC,KC_SPC,        KC_TRNS,KC_TRNS,KC_TRNS,KC_HENK,KC_TRNS,KC_LEFT,KC_DOWN,KC_RIGHT
```

2020-08-27 01:01 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/config.h
> +
```suggestion
```

2020-08-27 01:02 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/config.h
> +// #define BOOTMAGIC_LITE_COLUMN 0
```suggestion
```

2020-08-27 01:12 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/readme.md
> +Hardware Availability: https://skyhigh-works.booth.pm/items/1398595
```suggestion
* Keyboard Maintainer: [takashiski](https://github.com/takashiski)
* Hardware Supported: promicro(atmega32u4) on Otaku Split rev. 1.1 PCB
* Hardware Availability: https://skyhigh-works.booth.pm/items/1398595
```

2020-08-27 01:12 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/readme.md
> +    make otaku_split/rev1:default
```suggestion
    make otaku_split/rev1p1:default
```

2020-08-27 01:14 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/rules.mk
> +#   ATmega328P   USBasp
```suggestion
```

2020-08-27 01:15 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/rules.mk
> +BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality on B7 by default
```suggestion
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
```

2020-08-27 01:15 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/rules.mk
> +UNICODE_ENABLE = no         # Unicode
```suggestion
```

2020-08-27 01:15 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/rules.mk
> +AUDIO_ENABLE = no           # Audio output on port C6
```suggestion
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
```

2020-08-27 01:18 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/ver1p1.c
> +*/
```suggestion
```

2020-09-03 10:27 UTC, takashiski commented
Thank you for telling tips! it is very useful!

2020-09-03 18:10 UTC, noroadsleft requested changes

2020-09-03 18:10 UTC, noroadsleft commented on keyboards/otaku_split/ver1p1/readme.md
> +    make otaku_split/rev1p1:default
```suggestion
    make otaku_split/ver1p1:default
```

2020-09-05 19:44 UTC, noroadsleft approved these changes
Looks good to me.

2020-09-05 23:09 UTC, fauxpark requested changes

2020-09-05 23:09 UTC, fauxpark commented on keyboards/otaku_split/ver1/keymaps/via/rule.mk
> +VIA_ENABLE=yes
```suggestion
VIA_ENABLE = yes
```
This file must be named `rules.mk`.

2020-09-05 23:09 UTC, fauxpark commented on keyboards/otaku_split/ver1p1/keymaps/via/rule.mk
> +VIA_ENABLE=yes
```suggestion
VIA_ENABLE = yes
```
As above.

2020-09-05 23:09 UTC, fauxpark commented on keyboards/otaku_split/ver1p1/rules.mk
> +SPLIT_KEYBOARD=yes
```suggestion
SPLIT_KEYBOARD = yes
```

2020-09-05 23:09 UTC, fauxpark commented on keyboards/otaku_split/ver1/keymaps/via/keymap.c
> +  )
Pretty sure you need two extra empty layers here.

2020-11-20 05:15 UTC, closed without merging